### ISSUE TITLE
[boost_python] boost python 1.68 missing header with python 3.5

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#100]
moved from https://github.com/conan-community/community/issues/142, by @joaquin-herrero 

### Description of Problem, Request, or Question
I get a fatal error while using boost_python recipe from conan community. 

It seems to need a missing header pyconfig.h.

Not sure what Python version is using although I set it on conanfile to v3.5.

* Package Name/Version: **boost/1.68.0**
* Operating System: **Linux**
* Operation System Version: **Debian 9**
* Compiler+version: **gcc-6.3**
* Conan version: **conan 1.7.3**
* Python version: **python 3.5.0**

I'm using this conanfile on a test Project:

[requires]
boost/1.68.0@conan/stable

[generators]
cmake

[options]
boost_python:python_version = 3.5
boost_python:python_executable = /usr/bin/python3

[imports]

Logs:
joaquin@debian:~/Documents/boost-python-test/build$ conan install .. --build missing
boost/1.68.0@conan/stable: Not found in local cache, looking in remotes...
boost/1.68.0@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 125B/125B        
Downloading conanfile.py
[==================================================] 23.1KB/23.1KB    
Downloading conan_export.tgz
[==================================================] 602B/602B        
bzip2/1.0.6@conan/stable: Not found in local cache, looking in remotes...
bzip2/1.0.6@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 163B/163B        
Downloading conanfile.py
[==================================================] 2.1KB/2.1KB      
Downloading conan_export.tgz
[==================================================] 747B/747B        
zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 296B/296B        
Downloading conanfile.py
[==================================================] 11.6KB/11.6KB    
Downloading conan_export.tgz
[==================================================] 742B/742B        
Downloading conaninfo.txt
[==================================================] 392B/392B        
Downloading conaninfo.txt
[==================================================] 428B/428B        
Downloading conaninfo.txt

PROJECT: Installing /home/joaquin/Documents/boost-python-test/conanfile.txt
Requirements
    boost/1.68.0@conan/stable from 'conan-center' - Downloaded
    bzip2/1.0.6@conan/stable from 'conan-center' - Downloaded
    zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
Packages
    boost/1.68.0@conan/stable:13daee7a47e302c72dad593b4ee2795702b91d30 - Download
    bzip2/1.0.6@conan/stable:f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb - Download
    zlib/1.2.11@conan/stable:f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb - Download

bzip2/1.0.6@conan/stable: Retrieving package f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb from remote 'conan-center' 
Downloading conanmanifest.txt
[==================================================] 395B/395B        
Downloading conaninfo.txt
[==================================================] 392B/392B        
Downloading conan_package.tgz
[==================================================] 100.5KB/100.5KB  
bzip2/1.0.6@conan/stable: Package installed f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb
zlib/1.2.11@conan/stable: Retrieving package f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb from remote 'conan-center' 
Downloading conanmanifest.txt
[==================================================] 296B/296B        
Downloading conaninfo.txt
[==================================================] 428B/428B        
Downloading conan_package.tgz
[==================================================] 94.1KB/94.1KB    
zlib/1.2.11@conan/stable: Package installed f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb
boost/1.68.0@conan/stable: Retrieving package 13daee7a47e302c72dad593b4ee2795702b91d30 from remote 'conan-center' 
Downloading conanmanifest.txt
[==================================================] 1.1MB/1.1MB      
Downloading conaninfo.txt
[==================================================] 2.5KB/2.5KB      
Downloading conan_package.tgz
[==================================================] 18.9MB/18.9MB    
boost/1.68.0@conan/stable: Package installed 13daee7a47e302c72dad593b4ee2795702b91d30
boost/1.68.0@conan/stable: LIBRARIES: ['boost_wave', 'boost_container', 'boost_contract', 'boost_exception', 'boost_graph', 'boost_iostreams', 'boost_locale', 'boost_log', 'boost_program_options', 'boost_random', 'boost_regex', 'boost_wserialization', 'boost_serialization', 'boost_signals', 'boost_coroutine', 'boost_fiber', 'boost_context', 'boost_timer', 'boost_thread', 'boost_chrono', 'boost_date_time', 'boost_atomic', 'boost_filesystem', 'boost_system', 'boost_type_erasure', 'boost_math_c99l', 'boost_stacktrace_noop', 'boost_log_setup', 'boost_unit_test_framework', 'boost_math_tr1l', 'boost_math_c99', 'boost_stacktrace_backtrace', 'boost_math_tr1', 'boost_math_tr1f', 'boost_math_c99f', 'boost_stacktrace_addr2line', 'boost_stacktrace_basic']
boost/1.68.0@conan/stable: Package folder: /home/joaquin/.conan/data/boost/1.68.0/conan/stable/package/13daee7a47e302c72dad593b4ee2795702b91d30
PROJECT: Generator cmake created conanbuildinfo.cmake
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
joaquin@debian:~/Documents/boost-python-test/build$ make
Scanning dependencies of target hello
[ 50%] Building CXX object CMakeFiles/hello.dir/world.cpp.o
In file included from /home/joaquin/.conan/data/boost/1.68.0/conan/stable/package/13daee7a47e302c72dad593b4ee2795702b91d30/include/boost/python/detail/prefix.hpp:13:0,
                 from /home/joaquin/.conan/data/boost/1.68.0/conan/stable/package/13daee7a47e302c72dad593b4ee2795702b91d30/include/boost/python/args.hpp:8,
                 from /home/joaquin/.conan/data/boost/1.68.0/conan/stable/package/13daee7a47e302c72dad593b4ee2795702b91d30/include/boost/python.hpp:11,
                 from /home/joaquin/Documents/boost-python-test/world.cpp:2:
/home/joaquin/.conan/data/boost/1.68.0/conan/stable/package/13daee7a47e302c72dad593b4ee2795702b91d30/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
                       ^
compilation terminated.
CMakeFiles/hello.dir/build.make:62: recipe for target 'CMakeFiles/hello.dir/world.cpp.o' failed
make[2]: *** [CMakeFiles/hello.dir/world.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/hello.dir/all' failed
make[1]: *** [CMakeFiles/hello.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Croydon** [comment]
We don't have Boost 1.68 in CCI. Is this still a problem with Boost 1.70.0 or 1.71.0?

**Comment by SSE4** [comment]
I don't think it's a problem, python builds fine with newer boost
