### ISSUE TITLE
How to Link only specific library of dependency package having multiple libraries in consumer.

### ISSUE THREAD

**Issue by Megha0894** [conan-io/conan-center-index#10019]
Hello,
I have made of "components" feature of conan in our poco recipe to have separated components for each libraries and it looks something like this.

        self.cpp_info.names["cmake_find_package"] = "Poco"
        self.cpp_info.names["cmake_find_package_multi"] = "Poco"
        self.cpp_info.filenames["cmake_find_package"] = "Poco"
        self.cpp_info.filenames["cmake_find_package_multi"] = "Poco"
                
        self.cpp_info.set_property("cmake_target_name", "PocoFoundation")
        self.cpp_info.components["PocoFoundation"].libs = ["libPocoFoundation.so"]
        self.cpp_info.components["PocoFoundation"].includedirs = ["include/Poco"]

        self.cpp_info.set_property("cmake_target_name", "PocoNet")
        self.cpp_info.components["PocoNet"].libs = ["libPocoNet.so"]
        self.cpp_info.components["PocoNet"].includedirs = ["include/Poco/Net"]
        self.cpp_info.components["PocoNet"].requires = ["PocoFoundation"]

        self.cpp_info.set_property("cmake_target_name", "PocoJSON")
        self.cpp_info.components["PocoJSON"].libs = ["libPocoJSON.so"]
        self.cpp_info.components["PocoJSON"].includedirs = ["include/Poco/JSON"]
        self.cpp_info.components["PocoJSON"].requires = ["PocoFoundation"]

        self.cpp_info.set_property("cmake_target_name", "PocoXML")
        self.cpp_info.components["PocoXML"].libs = ["libPocoXML.so"]
        self.cpp_info.components["PocoXML"].includedirs = ["include/Poco/XML"]
        self.cpp_info.components["PocoXML"].requires = ["PocoFoundation"]

        self.cpp_info.set_property("cmake_target_name", "PocoUtil")
        self.cpp_info.components["PocoUtil"].libs = ["libPocoUtil.so"]
        self.cpp_info.components["PocoUtil"].includedirs = ["include/Poco/Util"]
        self.cpp_info.components["PocoUtil"].requires = ["PocoFoundation","PocoJSON", "PocoXML"]

        self.cpp_info.set_property("cmake_target_name", "PocoZip")
        self.cpp_info.components["PocoZip"].libs = ["libPocoZip.so"]
        self.cpp_info.components["PocoZip"].includedirs = ["include/Poco/Zip"]
        self.cpp_info.components["PocoZip"].requires = ["PocoFoundation","PocoJSON", "PocoXML", "PocoUtil"]

For doing this I have used https://docs.conan.io/en/latest/creating_packages/package_information.html as reference.
In the same link, they have given ways to link only required libraries in consumer package. 
So, In the consumer package I have used something like below in package_info method
self.cpp_info.requires = ["poco::PocoUtil"] to link with only PocoUtil library as I do not need other libraries except the dependencies mentioned in requires section.
and included poco as requires "requires ="poco/"version"
To check if it is working fine, I have used Net headers and functions in cpp file  of consumer package, But the code gets compiled without any error. But as per the link mentioned it should throw error right?
Is there any mistake in the way I am following to link with only required libraries.?

**Comment by SpaceIm** [comment]
It's not related to conan-center, you should ask this question in https://github.com/conan-io/conan
