### ISSUE TITLE
[conan.io/center] Markdown failed `ms-gsl/4.0.0@#01159f08c2f860b4c8e6dbfbd9805eae`

### ISSUE THREAD

**Issue by chadlichty** [conan-io/conan-center-index#10015]
I clicked on use it in the ms-gsl package and there is an error.

Markdown failed ms-gsl/4.0.0@#01159f08c2f860b4c8e6dbfbd9805eae

**Comment by jgsogo** [comment]
Fixed. Thanks for reporting.
