### ISSUE TITLE
[package] CGAL/5.3: recipe does not make consumers aware of -frounding-mode flag with CMakeToolchain/CMakeDeps generators & gcc/g++

### ISSUE THREAD

**Issue by phillip-keldenich** [conan-io/conan-center-index#10011]
# Context
[cgal_test.zip](https://github.com/conan-io/conan-center-index/files/8372793/cgal_test.zip)

CGAL makes use of interval arithmetic in many places; some of these uses are in header files,
which means that they may require the client/consumer to compile using certain flags on some compilers
to make the compiler aware that the code makes use of rounding modes different from the default (round-to-nearest, ties-to-even).

Failure to do so may or may not silently make the compiler output incorrect code, depending on the use case and whether the compiler finds opportunities to apply "optimizations" that break the code because they are based on the assumption of a specific rounding mode.

The relevant flags are /fp:strict for MSVC or -frounding-math for GCC.
See, for example, the following somewhat related CGAL issue: https://github.com/CGAL/cgal/issues/3180 for a discussion where the developers conclude that the flag may still be necessary.

CLang does not support such flags and GCCs support is somewhat flaky,
so CGAL developers use a macro (IA_OPACIFY) with compiler detection macros, typically involving volatile or inline asm to hide certain optimization opportunities from the compiler, preventing breakage in most cases (but not always);
it is therefore not trivial to produce a program that actually breaks without the flag.

Usually, e.g., when building and linking against CGAL without using conan, linking with the cgal targets in CMake makes sure that the flag is added to the compilation of the consumer (i.e., it is a PUBLIC compile_option or compile_definition of the cgal target) if the compiler is GCC or MSVC.
When using the CMakeDeps and CMakeToolchain generators, this flag is lost. I did not test any other generators (cmake or cmake_paths).

## Expected Behavior
Linking a consumer library/executable against the cgal::cgal target provided by the CMakeDeps/CMakeToolchain generators should add the flag `-frounding-math` to the compiler command line.

## Actual Behavior
Linking a consumer library/executable against the cgal::cgal target provided by the CMakeDeps/CMakeToolchain generators does not add the flag `-frounding-math` to the compiler command line.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: cgal/5.3
  * Operating System+version: Mac OS, though probably every supported OS
  * Compiler+version: GCC 11.2
  * Docker image: Not a docker image, though conanio/gcc11 should also show this behaviour (not tested).
  * Conan version: 1.45.0
  * Python version: Python 3.9.12

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile gnu11:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11.2
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
CC=gcc-11
CXX=g++-11
```

### Steps to reproduce (Include if Applicable)
Unzip the attached (relatively small & simple) example, 
[cgal_test.zip](https://github.com/conan-io/conan-center-index/files/8372855/cgal_test.zip)
create & enter a build directory, run `conan install -s build_type=Release ..` in it.
Make sure that CMake finds and uses g++ and not clang.
Then run `cmake -DCMAKE_BUILD_TYPE=Release ..` and `VERBOSE=1 make` in it.
Check whether the compiler invocations are done using `-frounding-math`. It should be, but isn't (at least in my case).

### Logs (Include/Attach if Applicable)
[log.txt](https://github.com/conan-io/conan-center-index/files/8372849/log.txt)

**Comment by SpaceIm** [comment]
Looking at CMake documentation & CMakeLists, we should add to `self.cpp_info.cxxflags` in `package_info()`:
- `-frounding-math` if gcc
- `/fp:strict` & `/fp:except-` if msvc

**Comment by phillip-keldenich** [comment]
I guess this would be the appropriate place for such flags, though I'm by no means an expert when it comes to conan.
Good catch on the `/fp:except-` (allowing the compiler to assume no floating point exceptions is sensible and allows some important optimizations).
