### ISSUE TITLE
[service] Permission denied for user: 'None' when call conan install

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan-center-index#10024]
This issue is transferred from https://github.com/conan-io/conan/issues/10902

**Comment by jgsogo** [comment]
I'm copying your last comment here: https://github.com/conan-io/conan/issues/10902#issuecomment-1082544030

> 



> It could be caused by UA. This command will produce this problem.
> 
> ```
> curl -k -i --raw -o 0.dat  -H "Host: center.conan.io" -H "User-Agent: Conan/1.44.0 (Linux 5.10.43-2-windows-subsystem-for-android-wsa+; Python 3.10.4; x86_64)" -H "Accept-Encoding: gzip, deflate" -H "Accept: */*" -H "Connection: keep-alive" -H "X-Client-Anonymous-Id: e4bd9be7890f3e526e2ce857f3c9202df67dfa6f" -H "X-Client-Id: " "https://center.conan.io/v1/ping"
> ```
> 
> The response is
> 
> ```
> HTTP/2 403
> server: nginx/1.21.4
> date: Wed, 30 Mar 2022 02:13:55 GMT
> content-type: text/html
> content-length: 153
> via: 1.1 google
> cache-status: miss
> cache-id: HKG-4ee15f8e
> alt-svc: clear
> 
> <html>
> <head><title>403 Forbidden</title></head>
> <body>
> <center><h1>403 Forbidden</h1></center>
> <hr><center>nginx/1.21.4</center>
> </body>
> </html>
> ```
> 
> If I change the UA to `Conan/1.44.0 (Linux 5.10.43-2; Python 3.10.4; x86_64)`, it is ok.
> 
> ```
> HTTP/2 200
> server: nginx/1.21.4
> date: Wed, 30 Mar 2022 02:14:21 GMT
> content-length: 0
> x-conan-server-version: 0.20.0
> x-conan-server-capabilities: complex_search,checksum_deploy,revisions,matrix_params
> cache-control: private
> via: 1.1 google
> cache-status: miss
> cache-id: HKG-4ee15f8e
> alt-svc: clear
> ```

This is about infrastructure, not ConanCenter (or conan-center-index CI) logic layer, but I'll share this issue with the corresponding team.

**Comment by jgsogo** [comment]
Found it! We have a rule in the nginx configuration to deny requests from browser-like agents. They include some keywords that match your headers.

**Comment by jgsogo** [comment]
@xyz1001 I understand the header you are providing in your request is the default one for `Windows 11 21H2 + Windows subsystem for Android + Termux`, right? If it is the default I think we have a good chance that the infrastructure team will unblock it.

PS.- If you know about any other header with the same pattern, please share. Thanks!

**Comment by xyz1001** [comment]
Yes, It is the default header for `Windows 11 21H2 + Windows subsystem for Android + Termux`

**Comment by xyz1001** [comment]
Yeah, now it is ok. Thank you for your help.
