### ISSUE TITLE
[question] Trying to add recipe for diStorm3; a few specific questions

### ISSUE THREAD

**Issue by accwebs** [conan-io/conan-center-index#10041]
Hello, 

I recently raised a PR to add a recipe for library `funchook` (see #9877).  One of the feedback items I got was that I need to create a separate recipe for one of `funchook`'s dependencies, `diStorm3`.  Funchook includes it as a sub-module and auto-builds it as part of its own compilation process using CMake (and I had followed suit in my funchook recipe in the PR) but in hindsight (and as pointed out), we'd want a separate recipe added for `diStorm3` instead of relying on the `funchook` compilation behavior.

So, now I'm trying to create a recipe for diStorm3 (ref https://github.com/gdabah/distorm).  But I'm hitting a few pain points.  Can anyone in the know help me answer the following?

1.  Recipe naming convention.  Oddly, the `diStorm3` library seems to shift between including the "3" in the name, and not doing so.  The .so and other output filenames include it, but the Github repo name goes by `distorm` (no "3" in the name).  When projects do this sort of thing (incorporating a major version in their names) do we generally remove the version number?  I.e. I should create a recipe called "distorm"?  (It feels like this is the right answer but I'm entirely unsure.)

2.  Build system.   `distorm` doesn't use CMake and provides entirely different files depending on the target OS (Makefiles for Linux/MacOS, Visual Studio project for Windows).  In that case, do we find it to be bad/evil to simply ignore the project's own build system and provide a CMake wrapper instead (and use that in the Conan recipe)?  It seems to me like this would be simpler.  Especially if we want to override the output filenames from `distorm3.so` -> to the recipe convention of simply `distorm.so`?  

3.  Recipe completeness.  In order to support adding the `funchook` recipe, I really only need the C library features of `distorm`, not its associated Python binding.  In cases of adding new recipes is it entirely evil / unthinkable to add a simple recipe that doesn't incorporate all the options that the underlying library can produce (i.e. in this case the Python binding)?  Or is that entirely non-kosher?

4.  License.  distorm3 seems to have a custom license.  I wasn't sure how to indicate this in the Conan recipe.  What I did was:
```
license = "LicenseRef-COPYING"
```
This was based on a few other recipes I saw.  Is this right?

Thanks for the help!

edit:  add question 4 :-)

**Comment by Croydon** [comment]
1. `distorm` seems to be the right choice. Some projects have weird versioning, but generally, we remove version numbers from the end of the name (see `qt` and `sdl`)

2. Leave the library names as they are upstream. Build files should be used from upstream unless they really don't work without extensive work for us - or - if such a self-written CMake file would be small-ish and much better than what upstream offers.

3. Recipes don't need to expose all build options. It's fine to start out with some.

4. Correct

**Comment by accwebs** [comment]
Thanks for the guidance!  Much appreciated.  Closing this.
