### ISSUE TITLE
[question] is bootstrapping of boost correct?

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#1005]
The boost recipe has a `_bootstrap` method that will build `b2`.
In that method, the environment variables `CC`, `CXX`, `CFLAGS`, ... are removed
and `b2` is built.
I believe this method is very brittle.

Shouldn't this recipe just use `b2` as a build requirement?

CC'ing @SSE4 for being the main author (I think)

**Comment by SSE4** [comment]
@madebr yes, I agree that would be the ideal. feel free to submit such PR if you have an interest/time. as b2 is already in conan center, that should be the great improvement to simplify the recipe.
