### ISSUE TITLE
[package] <gdal/3.4.1>: default "with_geos=True" option works on Windows but not on Linux and OSX

### ISSUE THREAD

**Issue by lucsch** [conan-io/conan-center-index#10077]
### Package and Environment Details 
  * Package Name/Version: **gdal/3.4.1**, **gdal/3.3.3**, **gdal/3.3.1**
  * Operating System+version: **Linux Ubuntu 20.04**, **Macos x86_64**
  * Compiler+version: **GCC 9**, **apple-clang 12.0**
  * Docker image: None
  * Conan version: **conan 1.46.2**
  * Python version: **Python 3.9.10**

### Steps to reproduce

the option "with_geos" is set to true by default in GDAL. Indeed the geos library is needed for topological operations (for example the union of vector objects).

see the current version of gdal/conanfile.py

```
default_options = {
        ...
        "with_geos": True,
        ...
```

Under Windows, this option works and GDAL is available with GEOS support. There is a problem with OSX and Linux because the GEOS library is not correctly recognized by GDAL. 

It is possible to reproduce this problem with the following example code:

**conanfile.txt**
```
[requires]
gdal/3.4.1

[generators]
cmake
```

**main.cpp**
```
#include "gdal_priv.h"
#include "ogr_geometry.h"
#include <iostream>

int main(int argc, const char *argv[]) {
  GDALAllRegister();
  if (OGRGeometryFactory::haveGEOS()) {
    std::cout << "GEOS OK!" << std::endl;
  } else {
    std::cout << "NO GEOS IN GDAL!" << std::endl;
  }

  // testing union (GEOS is needed)
  OGRGeometry *p1 = nullptr;
  OGRGeometry *p2 = nullptr;
  OGRGeometry *p3 = nullptr;
  OGRGeometryFactory::createFromWkt("POINT(10 20)", NULL, &p1);
  OGRGeometryFactory::createFromWkt("POINT(30 20)", NULL, &p2);
  p3 = p1->Union(p2);
  return 0;
}
```

When built, the above code should return `GEOS OK!`. This works on Windows (Visual studio 2019) but with Linux and OSX the code returns :
```
NO GEOS IN GDAL!
ERROR 6: GEOS support not enabled.
``` 

I tested the last three versions of GDAL (3.4.1, 3.3.3, 3.3.1) and they all have the same problem.

**Comment by SpaceIm** [comment]
Thanks for noticing this issue. I think I know what's wrong. The patch of `configure.ac` in gdal recipe is missing `AC_SUBST(HAVE_GEOS)`.

**Comment by SpaceIm** [comment]
Please confirm that https://github.com/conan-io/conan-center-index/pull/10080 fixes this issue (on my mac it works, geos is properly enabled now).

**Comment by lucsch** [comment]
Your patch works and the problem is solved. Thank you very much for your help.
