### ISSUE TITLE
[question] Can we publish FFI on Rust?

### ISSUE THREAD

**Issue by uselessgoddess** [conan-io/conan-center-index#10081]
We have a static library written in Rust. It can be used in C/C++. Can we publish it?

It should also be build before installation (like gtest and others)

**Comment by jgsogo** [comment]
Hi! This is a central repository for C++ libraries, and everything we have in ConanCenter should be built from sources. We have some exceptions regarding tools that are not built from sources but are required for other recipes (Android NDK, emsdk,...). 

I understand that having everything into the same package management system could simplify things on your side, but orchestrating libraries coming from different registries should be done on your consumer project. You can upload this library to your own Artifactory (check Free Tier offering), add an additional remote in your Conan client and achieve the same goal without adding the library to ConanCenter itself.

In any case, I will share your question with the team, in case they think we should open the door to other technologies.

Thanks!

**Comment by jgsogo** [comment]
I forgot to answer here, but the opinion of the team is to keep focused on C++ (and also to maintain the policy that everything need to be built in-house)

**Comment by uselessgoddess** [comment]
Ok. How does it pass the build tests on conan's machine. I doubt that `rustup` is installed there

**Comment by jgsogo** [comment]
Maybe I didn't explain myself, or maybe I'm missing something... but no Rust ATM is the policy.

**Comment by Croydon** [comment]
Is Rust a build dependency for the bindings then?

**Comment by uselessgoddess** [comment]
The library is written in Rust and provides FFI. We have a C++ high-level wrapper.

**Comment by jgsogo** [comment]
The FFI library won't get into CCI (it is Rust and CI won't work for it) and the bindings require the binaries (as a Conan requirement) of the Rust library, so it is not going to work in the CI either.

In your analogy, `zlib` is a C library that is being built in ConanCenter, and the C++ wrapper can depend (as a Conan requirement) on `zlib` library.

---

Note.- Sorry if I previously said just C++, I meant C and C++.

**Comment by Konard** [comment]
@jgsogo do you mean that only because ConanCenter CI does not support Rust, but support C/C++ building we cannot use binaries from rust the same way `zlib` package does?

**Comment by uselessgoddess** [comment]
> @jgsogo do you mean that only because Conan Center's CI does not support Rust, but support C/C++ building we cannot use binaries from Rust the same way `zlib` package does?

We can use pre-buils binary packages, but it has many disadvantages

**Comment by jgsogo** [comment]
Yes. Because CCI doesn't support Rust you can't build FFI (we don't allow pre-build binaries) and it won't become a Conan package in ConanCenter. The consequence is that the bindings library won't be able to use FFI as a Conan requirement.
