### ISSUE TITLE
[conan.io/center] Markdown failed `boost-ext-ut/1.1.9@#8f3fd620f17fc894512e87a39b7e2296`

### ISSUE THREAD

**Issue by Sebanisu** [conan-io/conan-center-index#10099]
I was on https://conan.io/center/boost-ext-ut?tab=recipe and clicked "use it" and got this error message.

Markdown generator failed for reference 'boost-ext-ut/1.1.9@#8f3fd620f17fc894512e87a39b7e2296'. Please report [here](https://github.com/conan-io/conan-center-index/issues/new?assignees=&labels=conan.io%2Fcenter&template=center_conan_io.md&title=%5Bconan.io%2Fcenter%5D+Markdown+failed+%60boost-ext-ut/1.1.9@%238f3fd620f17fc894512e87a39b7e2296%60).

**Comment by jgsogo** [comment]
We deployed some changes in the past days. I've regenerated the content of these tabs, now it is available. Thanks for reporting!
