### ISSUE TITLE
[service] how to rerun failed version-bump updateable recipies build after user auth update?

### ISSUE THREAD

**Issue by patmantru** [conan-io/conan-center-index#10098]
https://github.com/conan-io/conan-center-index/pull/10054

A co-worker used the `Updatable recipes` bot list to create an automated version bump PR for our opentdf-client package.  He was not in the authorized users list at the time, so the build was blocked.  He was just added as an authorized user, but now the PR says `continuous-integration/jenkins/pr-merge — This commit cannot be built`, but the details link yields a 403, so we can't see what happened.  

How do we re-start the build process and/or see the error?

**Comment by uilianries** [comment]
Hello @patmantru , it is documented here: https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#the-build-service

To summarize, the CI bot has a cron job to list and start that PR.

**Comment by patmantru** [comment]
thank you!
