### ISSUE TITLE
[question] Can't generate opencv_objdetect455.lib on windows vs2019

### ISSUE THREAD

**Issue by WilliamBehrens** [conan-io/conan-center-index#10147]
I'm building opencv from source via the conancenter recipe on Windows using Visual Studio 2019 and the following options
```python
"opencv:dnn": False,
"opencv:with_quirc": False,
"opencv:with_ffmpeg": False,
"opencv:with_openexr": False,
"opencv:with_jpeg2000": False,
```

For whatever reason though this fails to build the file `opencv_objdetect455.lib` that is expected by the project

**Comment by Croydon** [comment]
This is not a question, please provide all information that the `Package: Bug Report` issue template asks for

https://github.com/conan-io/conan-center-index/issues/new?assignees=&labels=bug&template=package_bug.md&title=%5Bpackage%5D+%3CLIBRARY-NAME%3E%2F%3CLIBRARY-VERSION%3E%3A+SHORT+DESCRIPTION

**Comment by lkantola** [comment]
It seems that the objdetect module depends on the dnn module.

There is a related upstream issue with a patch to make the dependency optional.
https://github.com/opencv/opencv/issues/21368

**Comment by WilliamBehrens** [comment]
> It seems that the objdetect module depends on the dnn module.
> 
> There is a related upstream issue with a patch to make the dependency optional. [opencv/opencv#21368](https://github.com/opencv/opencv/issues/21368)
