### ISSUE TITLE
[question] Is there a way to use Conan import to deploy Qt apps (bundle.app *.exe) instead of using mac/windeployqt

### ISSUE THREAD

**Issue by nmgwddj** [conan-io/conan-center-index#10164]
Using Conan, we can copy files and dependent libraries through functions such as conanfile.py import. Is there any quick and effective way to implement it through conanfile.py without needing to find the mac/windeployqt executable file for deployment?

I believe this is possible and the Qt team should consider using Conan for standalone deployment instead of using the deploy tool as well.

**Comment by Jihadist** [comment]
Is this question for cci? I think it should be addressed qt team. Cci qt recipe differs from official conan qt recipe.

P.S. You can use conan with cmake for deployment, but you can deploy only linked libs this way not plugins.

**Comment by nmgwddj** [comment]
It feels a little confusing. Conan center is developed into so many public network branches, which can easily cause flooding. I temporarily close this issue and discuss it through the Qt team channel
