### ISSUE TITLE
[package] poco/1.10.1: Options not available / not correctly parsed

### ISSUE THREAD

**Issue by akalali** [conan-io/conan-center-index#1017]
### Package and Environment Details
  * Package Name/Version: **poco/1.10.1**
  * Operating System+version: **Windows 10 64-bit**
  * Compiler+version: **Visual Studio 15**
  * Conan version: **conan 1.22.2**
  * Python version: **Python 3.7.1**

---

I'm currently setting up a Poco-example project with Conan and I'm basically disabling every option (project only relies on Poco::Foundation).
However, when I use a list of options to disable, which also includes
- `poco:enable_encodings=False`
- `poco:enable_jwt=False`

I get the errors:
```
ERROR: poco/1.10.1: 'options.enable_encodings' doesn't exist
```
or
```
ERROR: poco/1.10.1: 'options.enable_jwt' doesn't exist
```

Looking at the `conanfile.py` that totally makes sense since these options are not available. **Why is that?**

However, If I use upper case options
- `Poco:enable_encodings=False`
- `Poco:enable_jwt=False`

I don't get any error; all options that can be disabled are disabled after build and encodings and jwt (as well as depending libraries) are created.

So I guess if `poco` was written in lower case some kind of "option-check" is performed before building Poco. If `Poco` was written in upper case the check is not performed but the options are correctly sent to Conan.

Additionally I tested this by adding arbitrary options
- `poco:enable_foobar=False`
- `Poco:enable_foobar=False`

Both did not make any difference in detecting unsupported options.

I think it would make sense to inform a user 
- if upper case namespace options are not available (`Poco:enable_encodings=False`)
- if upper case / lower case options are not available at all (`poco:enable_foobar=False`)

**Comment by uilianries** [comment]
Hi @akalali !

Where did you find `enable_encodings` and `enable_jwt`. Is there a link for that reference (docs, code, tutorial, ...)

Both these options are not part of Poco package. Even Poco project doesn't use them.

**Comment by akalali** [comment]
https://github.com/pocoproject/poco/blob/master/CMakeLists.txt#L160
and e.g.
https://github.com/pocoproject/poco/blob/master/CMakeLists.txt#L92

Also https://pocoproject.org/docs/00200-GettingStarted.html#9

**Comment by uilianries** [comment]
I see, what you want is including both options to Poco package. Fair enough.

**Comment by akalali** [comment]
That is the first part of my question. I would have opened a PR (if this is your preferred workflow) but I wasn't sure if there might be a reason not to include these options.

Second part of the question is about the parsing of the options with regards to lower case / upper case.

**Comment by jgsogo** [comment]
Hi, @akalali 

> That is the first part of my question. I would have opened a PR (if this is your preferred workflow) but I wasn't sure if there might be a reason not to include these options.
> 

Both options will be available soon https://github.com/conan-io/conan-center-index/pull/1021

> Second part of the question is about the parsing of the options with regards to lower case / upper case.

Conan 1.x is case-sensitive, so the package `Poco` and `poco` are two different packages. When Conan finds a match (in your case the lowercase `poco`) it will fail if the options are not declared in the recipe, otherwise it will pass all the options upstreams to the requirements, maybe there is a `Poco` (uppercase) package that will use them.
