### ISSUE TITLE
[package] qt/6.2.1: Conflict with 'glib' after adding `qt:qtmultimedia=True` option.

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan-center-index#10174]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.2.1**
  * Operating System+version: **Windows 11**
  * Compiler+version: **MSVC 2019**
  * Docker image: **None**
  * Conan version: **Conan 1.45.0**
  * Python version: **Python 3.9.2**

### Conan profile (output of `conan profile show default`)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Root-level CMakeLists.txt

I use [CMake-Conan](https://github.com/conan-io/cmake-conan) to install package. Here is my root-level `CMakeLists.txt` file:

<details><summary>Click to CMakeLists.txt</summary>

```cmake
cmake_minimum_required(VERSION 3.15)
get_filename_component(folder_name "${CMAKE_CURRENT_SOURCE_DIR}" NAME)
project(${folder_name} LANGUAGES C CXX)
message("========== ${folder_name} ==========")


get_cmake_property(is_multi_config GENERATOR_IS_MULTI_CONFIG)
if(is_multi_config)       # Multi-Config Generator
  set(output_dir "${CMAKE_BINARY_DIR}/$<CONFIG>")
else(is_multi_config)     # Single-Config Generator
  set(output_dir "${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}")
endif(is_multi_config)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${output_dir}/bin")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${output_dir}/lib")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${output_dir}/lib")
set(CMAKE_DEBUG_POSTFIX d)


if(CMAKE_CXX_COMPILER_ID MATCHES MSVC)
  add_compile_options("/source-charset:utf-8")
elseif(CMAKE_CXX_COMPILER_DIR MATCHES GNU)
  add_compile_options("-finput-charset=utf-8")
endif()


if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
  message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan ...")
  file(DOWNLOAD 
    "https://raw.githubusercontent.com/conan-io/cmake-conan/develop/conan.cmake"
    "${CMAKE_BINARY_DIR}/conan.cmake")
endif()
include("${CMAKE_BINARY_DIR}/conan.cmake")


set(conan_config_generators "CMakeDeps")
set(conan_config_requires   "qt/6.2.1@")
set(conan_config_options    "qt:shared=True"
                            "qt:qtmultimedia=True"    # After adding this option, the error shows up
                            )


if(is_multi_config)     # Multi-Config Generator
  foreach(type Debug;Release)
    conan_cmake_configure(
      GENERATORS  ${conan_config_generators}
      REQUIRES    ${conan_config_requires}
      OPTIONS     ${conan_config_options}
      IMPORTS     "bin, *.dll -> ../${type}/bin"
      IMPORTS     "res/archdatadir/plugins, styles* -> ../${type}/bin @ root_package=qt"
      IMPORTS     "res/archdatadir/plugins, platforms* -> ../${type}/bin @ root_package=qt"
    )
    conan_cmake_autodetect(settings BUILD_TYPE ${type})
    conan_cmake_install(
      PATH_OR_REFERENCE "."
      INSTALL_FOLDER    "./conan"
      BUILD             missing
      REMOTE            conancenter
      SETTINGS          ${settings}
    )
  endforeach()
else(is_multi_config)   # Single-Config Generator
  set(type ${CMAKE_BUILD_TYPE})
  conan_cmake_configure(
    GENERATORS  ${conan_config_generators}
    REQUIRES    ${conan_config_requires}
    OPTIONS     ${conan_config_options}
    IMPORTS     "bin, *.dll -> ../${type}/bin"
    IMPORTS     "res/archdatadir/plugins, styles* -> ../${type}/bin @ root_package=qt"
    IMPORTS     "res/archdatadir/plugins, platforms* -> ../${type}/bin @ root_package=qt"
  )
  conan_cmake_autodetect(settings)
  conan_cmake_install(
    PATH_OR_REFERENCE "."
    INSTALL_FOLDER    "./conan"
    BUILD             missing
    REMOTE            conancenter
    SETTINGS          ${settings}
  )
endif(is_multi_config)


list(APPEND CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}/conan")
list(APPEND CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}/conan")


set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)


find_package(QT NAMES Qt6 CONFIG REQUIRED)
find_package(Qt${QT_VERSION_MAJOR} CONFIG REQUIRED)
```

</details>

### Steps to reproduce

1.  Use VSCode to open a empty folder.
2.  Download [CMake-Tools](https://github.com/microsoft/vscode-cmake-tools) plugin from Extension.
3.  Create an empty `CMakeLists.txt` file, and then paste the above example on it.
4.  Press `Ctrl+Shift+P`, and then type `CMake: Configure`.

### Logs
<details><summary>Click to expand log</summary>

```
[cmake] ERROR: Conflict in gst-plugins-base/1.19.2:
[cmake]     'gst-plugins-base/1.19.2' requires 'glib/2.70.1' while 'harfbuzz/4.0.1' requires 'glib/2.71.3'.
[cmake]     To fix this conflict you need to override the package 'glib' in your root package.
```

</details>

**Comment by ilongshan** [comment]
Add 'glib/2.71.3' to conan_config_requires, and try again?

**Comment by hwhsu1231** [comment]
@ilongshan I add `glib/2.71.3@` into `conan_config_requires`, and it starts to configure.

```cmake
set(conan_config_requires   "qt/6.2.1@"
                            "glib/2.71.3@")
```

But it pops up another error: (log is to long, so I upload the txt file)

[LOG.txt](https://github.com/conan-io/conan-center-index/files/8459044/LOG.txt)

**Comment by ericLemanissier** [comment]
Can you please try to set option `qt:with_gstreamer=False` ?

**Comment by hwhsu1231** [comment]
@ericLemanissier It compiles **successfully** after I add `qt:with_gstreamer=False` option:

```cmake
set(conan_config_generators "CMakeDeps")
set(conan_config_requires   "qt/6.2.1@"
                            "glib/2.71.3")
set(conan_config_options    "qt:shared=True"
                            "qt:qtmultimedia=True"
                            "qt:with_gstreamer=False")
```

Here is the log:

[LOG.txt](https://github.com/conan-io/conan-center-index/files/8460799/LOG.txt)

So this is a bug, right? Because I remember I just need to add `qt:qtmultimedia=True` without doing other things before.

**Comment by hwhsu1231** [comment]
What I mean **"before"** is before this issue https://github.com/conan-io/conan-center-index/issues/9794.

**Comment by ericLemanissier** [comment]
this will be fixed by https://github.com/conan-io/conan-center-index/pull/10050/files#diff-c548829da9d38ae15a8cb4447140bc50ac3f38250d1f348decd9569dc3298b24R126

**Comment by hwhsu1231** [comment]
@ericLemanissier What might be the reason causing this error? Would you mind do some explanations after fixing this error and before closing this issue? I looks like it has something to do with **"glib"** and **"gstreamer"**.

**Comment by ericLemanissier** [comment]
the error you had was `'gst-plugins-base/1.19.2' requires 'glib/2.70.1' while 'harfbuzz/4.0.1' requires 'glib/2.71.3'.` It happened because the configuration of qt you were trying to build required `gst-plugins-base/1.19.2` and `harfbuzz/4.0.1` which did not agree on the version of glib to use. The "usual" fix to this would be to bump the glib version required from `gst-plugins-base` recipe and/or `harfbuzz` recipe. 
This this case, I took the shorter route: by default I will disable qt:with_gstreamer (with https://github.com/conan-io/conan-center-index/pull/10261/files#diff-c548829da9d38ae15a8cb4447140bc50ac3f38250d1f348decd9569dc3298b24R126), which means `gst-plugins-base` won't be required any more by default, so there won't be any conflict (except if the user explicitly asks for qt:with_gstreamer=True, in which case it will be solved with https://github.com/conan-io/conan-center-index/pull/10376)
