### ISSUE TITLE
[bzip2] bzip2/1.06@conan/stable fails as of a5875aed3fc7ae8dd0488f7e5e99acbc480d721d

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#102]
moved from https://github.com/conan-community/community/issues/279, by @thedracle 

### It seems like the bzip2 conan/stable package is broken as of a5875aed3fc7ae8dd0488f7e5e99acbc480d721d

when trying to build from source.

It works as of b27e2b40bcb70be2e7d6f0e0c6e43e35c530f8d3

The error it chokes on is :
`
bzip2/1.0.6@conan/stable: Configuring sources in /root/.conan/data/bzip2/1.0.6/conan/stable/source
ERROR: bzip2/1.0.6@conan/stable: Error in source() method, line 37
        tools.get(url="%s/download_file?file_path=%s" % (url, zip_name), sha256=sha256, filename=zip_name)
        AttributeError: 'NoneType' object has no attribute 'token'
`

### Package Details (Include if Applicable)

* Package Name/Version: **bzip2/1.06@conan/stable#a5875aed3fc7ae8dd0488f7e5e99acbc480d721d**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04** **Alpine 3.9.4**
* Compiler+version: **gcc-8.3.0** & **gcc 7.4.0***
* Conan version: **conan 1.18.0**
* Python version: **python 2.7.16**

### Steps to reproduce (Include if Applicable)
conanfile.txt

>[requires]
boost/1.65.1@conan/stable
OpenSSL/1.0.2@conan/stable
[options]
boost:shared=False
[generators]
make

And build with

> conan install . -s compiler.libcxx=libstdc++11 --build boost --build bzip2 --build zlib --build OpenSSL

### Build logs (Include if Available)

`Requirement already satisfied: conan in /usr/lib/python2.7/site-packages (1.18.4)
Requirement already satisfied: PyJWT<2.0.0,>=1.4.0 in /usr/lib/python2.7/site-packages (from conan) (1.7.1)
Requirement already satisfied: requests<3.0.0,>=2.8.1 in /usr/lib/python2.7/site-packages (from conan) (2.22.0)
Requirement already satisfied: colorama<0.5.0,>=0.3.3 in /usr/lib/python2.7/site-packages (from conan) (0.4.1)
Requirement already satisfied: PyYAML<6.0,>=3.11 in /usr/lib/python2.7/site-packages (from conan) (5.1.2)
Requirement already satisfied: patch==1.16 in /usr/lib/python2.7/site-packages (from conan) (1.16)
Requirement already satisfied: fasteners>=0.14.1 in /usr/lib/python2.7/site-packages (from conan) (0.15)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/site-packages (from conan) (1.12.0)
Requirement already satisfied: node-semver==0.6.1 in /usr/lib/python2.7/site-packages (from conan) (0.6.1)
Requirement already satisfied: distro<1.2.0,>=1.0.2 in /usr/lib/python2.7/site-packages (from conan) (1.1.0)
Requirement already satisfied: pylint!=2.3.0,>=1.9.3 in /usr/lib/python2.7/site-packages (from conan) (1.9.5)
Requirement already satisfied: future==0.16.0 in /usr/lib/python2.7/site-packages (from conan) (0.16.0)
Requirement already satisfied: pygments<3.0,>=2.0 in /usr/lib/python2.7/site-packages (from conan) (2.4.2)
Requirement already satisfied: astroid>=1.6.5 in /usr/lib/python2.7/site-packages (from conan) (1.6.6)
Requirement already satisfied: deprecation<2.1,>=2.0 in /usr/lib/python2.7/site-packages (from conan) (2.0.7)
Requirement already satisfied: tqdm<5,>=4.28.1 in /usr/lib/python2.7/site-packages (from conan) (4.36.1)
Requirement already satisfied: Jinja2<3,>=2.3 in /usr/lib/python2.7/site-packages (from conan) (2.10.1)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/lib/python2.7/site-packages (from conan) (2.8.0)
Requirement already satisfied: bottle<0.13,>=0.12.8 in /usr/lib/python2.7/site-packages (from conan) (0.12.17)
Requirement already satisfied: pluginbase<1.0,>=0.5 in /usr/lib/python2.7/site-packages (from conan) (0.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests<3.0.0,>=2.8.1->conan) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests<3.0.0,>=2.8.1->conan) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests<3.0.0,>=2.8.1->conan) (1.25.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests<3.0.0,>=2.8.1->conan) (2019.9.11)
Requirement already satisfied: monotonic>=0.1 in /usr/lib/python2.7/site-packages (from fasteners>=0.14.1->conan) (1.5)
Requirement already satisfied: isort>=4.2.5 in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (4.3.21)
Requirement already satisfied: singledispatch; python_version < "3.4" in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (3.4.0.3)
Requirement already satisfied: configparser; python_version == "2.7" in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (4.0.2)
Requirement already satisfied: mccabe in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (0.6.1)
Requirement already satisfied: backports.functools-lru-cache; python_version == "2.7" in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (1.5)
Requirement already satisfied: enum34>=1.1.3; python_version < "3.4" in /usr/lib/python2.7/site-packages (from astroid>=1.6.5->conan) (1.1.6)
Requirement already satisfied: wrapt in /usr/lib/python2.7/site-packages (from astroid>=1.6.5->conan) (1.11.2)
Requirement already satisfied: lazy-object-proxy in /usr/lib/python2.7/site-packages (from astroid>=1.6.5->conan) (1.4.2)
Requirement already satisfied: packaging in /usr/lib/python2.7/site-packages (from deprecation<2.1,>=2.0->conan) (19.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python2.7/site-packages (from Jinja2<3,>=2.3->conan) (1.1.1)
Requirement already satisfied: futures; python_version < "3.2" in /usr/lib/python2.7/site-packages (from isort>=4.2.5->pylint!=2.3.0,>=1.9.3->conan) (3.3.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python2.7/site-packages (from packaging->deprecation<2.1,>=2.0->conan) (2.4.2)
Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)
Found gcc 8.3
Found clang 5.0
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************

Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/root/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************

Default settings
        os=Linux
        os_build=Linux
        arch=x86_64
        arch_build=x86_64
        compiler=gcc
        compiler.version=8
        compiler.libcxx=libstdc++
        build_type=Release
*** You can change them in /root/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***

WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

boost/1.65.1@conan/stable: Not found in local cache, looking in remotes...
boost/1.65.1@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 180/180 [00:00<00:00, 114kB/s]
Downloading conanfile.py: 100%|##########| 31.1k/31.1k [00:00<00:00, 464kB/s]
Downloading conan_export.tgz: 100%|##########| 1.00k/1.00k [00:00<00:00, 822kB/s]
Decompressing conan_export.tgz: 1.00kB [00:00, 518kB/s]
boost/1.65.1@conan/stable: Downloaded recipe revision 0
boost/1.65.1@conan/stable: WARN: Setting 'cppstd' is deprecated in favor of 'compiler.cppstd', please update your recipe.
bzip2/1.0.6@conan/stable: Not found in local cache, looking in remotes...
bzip2/1.0.6@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 163/163 [00:00<00:00, 154kB/s]
Downloading conanfile.py: 100%|##########| 2.21k/2.21k [00:00<00:00, 1.67MB/s]
Downloading conan_export.tgz: 100%|##########| 766/766 [00:00<00:00, 481kB/s]
Decompressing conan_export.tgz: 774B [00:00, 723kB/s]
bzip2/1.0.6@conan/stable: Downloaded recipe revision 0
zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 296/296 [00:00<00:00, 225kB/s]
Downloading conanfile.py: 100%|##########| 8.74k/8.74k [00:00<00:00, 7.41MB/s]
Downloading conan_export.tgz: 100%|##########| 766/766 [00:00<00:00, 401kB/s]
Decompressing conan_export.tgz: 774B [00:00, 729kB/s]
zlib/1.2.11@conan/stable: Downloaded recipe revision 0
OpenSSL/1.0.2@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.0.2@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 58.0/58.0 [00:00<00:00, 43.3kB/s]
Downloading conanfile.py: 100%|##########| 106/106 [00:00<00:00, 63.5kB/s]
OpenSSL/1.0.2@conan/stable: Downloaded recipe revision 0
OpenSSL/1.0.2q@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.0.2q@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 58.0/58.0 [00:00<00:00, 41.3kB/s]
Downloading conanfile.py: 100%|##########| 28.7k/28.7k [00:00<00:00, 14.6MB/s]
OpenSSL/1.0.2q@conan/stable: Downloaded recipe revision 0
bzip2/1.0.6@conan/stable: Forced build from source
zlib/1.2.11@conan/stable: Forced build from source
OpenSSL/1.0.2q@conan/stable: Forced build from source
boost/1.65.1@conan/stable: Forced build from source
conanfile.txt: Installing package
Requirements
    OpenSSL/1.0.2q@conan/stable from 'conan-center' - Downloaded
    boost/1.65.1@conan/stable from 'conan-center' - Downloaded
    bzip2/1.0.6@conan/stable from 'conan-center' - Downloaded
    zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
Packages
    OpenSSL/1.0.2q@conan/stable:4f75e4b120320a9fb6ac0012242d9ac95d18b6f6 - Build
    boost/1.65.1@conan/stable:5e8eff81f2db7ac8c8c3d41364df2f92d8c53fdb - Build
    bzip2/1.0.6@conan/stable:a5875aed3fc7ae8dd0488f7e5e99acbc480d721d - Build
    zlib/1.2.11@conan/stable:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Build

Downloading conan_sources.tgz: 100%|##########| 807/807 [00:00<00:00, 504kB/s]
Decompressing conan_sources.tgz: 815B [00:00, 691kB/s]
bzip2/1.0.6@conan/stable: Configuring sources in /root/.conan/data/bzip2/1.0.6/conan/stable/source
ERROR: bzip2/1.0.6@conan/stable: Error in source() method, line 37
        tools.get(url="%s/download_file?file_path=%s" % (url, zip_name), sha256=sha256, filename=zip_name)
        AttributeError: 'NoneType' object has no attribute 'token'
`

**Comment by uilianries** [comment]
It's working fine, closing this issue:

```
$ conan install bzip2/1.0.6@ -s compiler.libcxx=libstdc++11 --build bzip2 -r conan-center
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

bzip2/1.0.6: Retrieving from server 'conan-center' 
bzip2/1.0.6: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.17k]                                          
Downloading conanfile.py completed [2.17k]                                               
Downloading conan_export.tgz completed [0.24k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
bzip2/1.0.6: Downloaded recipe revision 0
bzip2/1.0.6: Forced build from source
Installing package: bzip2/1.0.6
Requirements
    bzip2/1.0.6 from 'conan-center' - Downloaded
Packages
    bzip2/1.0.6:a5875aed3fc7ae8dd0488f7e5e99acbc480d721d - Build

Installing (downloading, building) binaries...
Downloading conan_sources.tgz completed [0.79k]                                          
Decompressing conan_sources.tgz completed [0.00k]                                        
bzip2/1.0.6: Configuring sources in /home/conan/.conan/data/bzip2/1.0.6/_/_/source
Downloading bzip2-1.0.6.tar.gz completed [763.70k]                                       

bzip2/1.0.6: Copying sources to build folder
bzip2/1.0.6: Building your package in /home/conan/.conan/data/bzip2/1.0.6/_/_/build/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d
bzip2/1.0.6: Generator cmake created conanbuildinfo.cmake
bzip2/1.0.6: Calling build()
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Adjusting fPIC flag (ON)
-- This project seems to be plain C, using 'GNU' compiler
-- Conan: Compiler GCC>=5, checking major version 8
-- Conan: Checking correct version: 8
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY


-- Build files have been written to: /home/conan/.conan/data/bzip2/1.0.6/_/_/build/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d
Scanning dependencies of target bz2
[ 10%] Building C object CMakeFiles/bz2.dir/source_subfolder/blocksort.c.o
[ 30%] Building C object CMakeFiles/bz2.dir/source_subfolder/bzlib.c.o
[ 30%] Building C object CMakeFiles/bz2.dir/source_subfolder/compress.c.o
[ 40%] Building C object CMakeFiles/bz2.dir/source_subfolder/crctable.c.o
[ 50%] Building C object CMakeFiles/bz2.dir/source_subfolder/decompress.c.o
[ 60%] Building C object CMakeFiles/bz2.dir/source_subfolder/huffman.c.o
[ 70%] Building C object CMakeFiles/bz2.dir/source_subfolder/randtable.c.o
[ 80%] Linking C static library lib/libbz2.a
[ 80%] Built target bz2
Scanning dependencies of target bzip2
[ 90%] Building C object CMakeFiles/bzip2.dir/source_subfolder/bzip2.c.o
/home/conan/.conan/data/bzip2/1.0.6/_/_/build/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d/source_subfolder/bzip2.c: In function ‘applySavedFileAttrToOutputFile’:
/home/conan/.conan/data/bzip2/1.0.6/_/_/build/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d/source_subfolder/bzip2.c:1073:11: warning: ignoring return value of ‘fchown’, declared with attribute warn_unused_result [-Wunused-result]
    (void) fchown ( fd, fileMetaInfo.st_uid, fileMetaInfo.st_gid );
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[100%] Linking C executable bin/bzip2
[100%] Built target bzip2
bzip2/1.0.6: Package 'a5875aed3fc7ae8dd0488f7e5e99acbc480d721d' built
bzip2/1.0.6: Build folder /home/conan/.conan/data/bzip2/1.0.6/_/_/build/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d
bzip2/1.0.6: Generated conaninfo.txt
bzip2/1.0.6: Generated conanbuildinfo.txt
bzip2/1.0.6: Generating the package
bzip2/1.0.6: Package folder /home/conan/.conan/data/bzip2/1.0.6/_/_/package/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d
bzip2/1.0.6: Calling package()
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Adjusting fPIC flag (ON)
-- This project seems to be plain C, using 'GNU' compiler
-- Conan: Compiler GCC>=5, checking major version 8
-- Conan: Checking correct version: 8
-- Configuring done
-- Generating done
-- Build files have been written to: /home/conan/.conan/data/bzip2/1.0.6/_/_/build/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d
[ 80%] Built target bz2
[100%] Built target bzip2
Install the project...
-- Install configuration: "Release"
-- Installing: /home/conan/.conan/data/bzip2/1.0.6/_/_/package/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d/lib/libbz2.a
-- Installing: /home/conan/.conan/data/bzip2/1.0.6/_/_/package/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d/bin/bzip2
-- Installing: /home/conan/.conan/data/bzip2/1.0.6/_/_/package/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d/include/bzlib.h
-- Installing: /home/conan/.conan/data/bzip2/1.0.6/_/_/package/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d/lib/cmake/bzip2/BZip2Config.cmake
-- Installing: /home/conan/.conan/data/bzip2/1.0.6/_/_/package/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d/lib/cmake/bzip2/BZip2Config-release.cmake
bzip2/1.0.6 package(): Packaged 1 '.h' file: bzlib.h
bzip2/1.0.6 package(): Packaged 1 '.a' file: libbz2.a
bzip2/1.0.6 package(): Packaged 2 files: bzip2, LICENSE
bzip2/1.0.6: Package 'a5875aed3fc7ae8dd0488f7e5e99acbc480d721d' created
bzip2/1.0.6: Created package revision 04f325943b631fcc0b8aadbc1b4a2a73

```
