### ISSUE TITLE
[package] libarchive/3.6.0, protobuf/3.19.2 and qt connot be added to tool_requires together

### ISSUE THREAD

**Issue by Psy-Kai** [conan-io/conan-center-index#10235]
See https://github.com/conan-io/conan/issues/11010 for more details.

I think `libarchive` and `qt` just needs to get its `requires` to `zlib` bumped.

**Comment by SpaceIm** [comment]
Yes, it's a unfortunat limitation of `tool_requires`/`build_requires` which don't scale when it comes to version override in build context graph. /cc @memsharded

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/10240, https://github.com/conan-io/conan-center-index/pull/10229 & https://github.com/conan-io/conan-center-index/pull/10050 together will fix this issue.
