### ISSUE TITLE
[package] Imgui/1.87: PC file has minor bug

### ISSUE THREAD

**Issue by Makogan** [conan-io/conan-center-index#10256]
In linux the PC generated file for imgui is this:

```
prefix=/home/ctalero/.conan/data/imgui/1.87/_/_/package/038baac88f4c7bfa972ce5adac1616bed8fe2ef4
libdir=${prefix}/lib
includedir=${prefix}/include

Name: imgui
Description: Bloat-free Immediate Mode Graphical User interface for C++ with minimal dependencies
Version: 1.87
Libs: -L"${libdir}" -limgui  -lm  -Wl,-rpath,"${libdir}"
Cflags: -I"${includedir}" -DIMGUI_USER_CONFIG="imgui_user_config.h"
```

However according to the people at meson https://github.com/mesonbuild/meson/issues/10201:

The last line should be generated with an additional set of quotations:

`Cflags: -I"${includedir}" -DIMGUI_USER_CONFIG='"imgui_user_config.h"'`

Tested locally on Ubuntu 20.10 and it works after manually changing the pc file.

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

I'm closing this issue as this is a `conan v1` related problem fixed a long time ago. Generators does no longer work like this in described in this issue.

Happy coding 🐸
