### ISSUE TITLE
[request] boost/1.72.0 x86

### ISSUE THREAD

**Issue by sinall** [conan-io/conan-center-index#1027]
### Package Details
  * Package Name/Version: **boost/1.72.0**
  * Changelog:

x86 version is not available. Could you please add it?
I failed to build it locally. Here's the log:

> boost/1.72.0: WARN: Build folder is dirty, removing it: D:\.conan\d0fdfc\1
> boost/1.72.0: Building your package in D:\.conan\d0fdfc\1
> boost/1.72.0: Generator txt created conanbuildinfo.txt
> boost/1.72.0: Calling build()
> boost/1.72.0: bootstrap.bat
> Bootstrapping the build engine
> 
> Failed to bootstrap the build engine
> Please consult bootstrap.log for further diagnostics.
> 
> boost/1.72.0: WARN: Error 1 while executing bootstrap.bat
> boost/1.72.0: WARN: LOCALAPPDATA=C:\Users\xxx\AppData\Local
> Found with vswhere Visual Studio Locator version 2.7.1+180c706d56 [query version 2.3.2200.14893]
> ###
> ### "Unknown toolset: vcunk"
> ###
> ### You can specify the toolset as the argument, i.e.:
> ###     .\build.bat msvc
> ###
> ### Toolsets supported by this script are: borland, como, gcc,
> ###     gcc-nocygwin, intel-win32, metrowerks, mingw,
> ###     vc11, vc12, vc14, vc141, vc142
> ###
> ### If you have Visual Studio 2017 installed you will need to either update
> ### the Visual Studio 2017 installer or run from VS 2017 Command Prompt
> ### as we where unable to detect your toolset installation.
> ###
> 
> boost/1.72.0:
> boost/1.72.0: ERROR: Package 'd23b03f4b2f5c819c42b1d0f32f3131799f51e1d' build failed
> boost/1.72.0: WARN: Build folder D:\.conan\d0fdfc\1
> ERROR: boost/1.72.0: Error in build() method, line 397
>         self._bootstrap()
> while calling '_bootstrap', line 869
>         self.run(cmd)
>         ConanException: Error 1 while executing bootstrap.bat
> Exit code: 1
> An error occurred when executing task 'ConanInstall'.
> Error: 发生一个或多个错误。
>         conan install exception
>

**Comment by sinall** [comment]
I have VS2019 with VS2017 build toolset installed.

**Comment by uilianries** [comment]
> x86 version is not available. Could you please add it?

What do you mean? The Boost x86 is not available for download or you can't build for x86?

Conan Center Index doesn't provide x86 package versions, please read the supported configurations section: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Comment by uilianries** [comment]
>  I failed to build it locally. Here's the log:

Now I understand your point. In this case you should open an issue using the template [BUG] which contains more fields for description.

We need to know your Conan profile and also your log, but more detailed, including the command line.

**Comment by sinall** [comment]
profile:
```
[settings]
arch=x86
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=14
os=Windows
os_build=Windows
arch_build=x86
```

command:
`conan install . -if conaninfo/Debug --profile debug --build missing --no-imports`

log:

> Preparing to run build script...
> Running build script...
> Analyzing build script...
> Processing build script...
> Installing addins...
> The 'addin' directive is attempting to install the 'Cake.Putty' package
> without specifying a package version number.
> More information on this can be found at https://cakebuild.net/docs/tutorials/pinning-cake-version
> It's not recommended, but you can explicitly override this warning
> by configuring the Skip Package Version Check setting to true
> (i.e. command line parameter "--settings_skippackageversioncheck=true",
> environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true",
> read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
> Compiling build script...
> 
> ========================================
> ConanInstall
> ========================================
> Executing task: ConanInstall
> Configuration:
> [settings]
> arch=x86
> arch_build=x86
> build_type=Debug
> compiler=Visual Studio
> compiler.runtime=MDd
> compiler.version=14
> os=Windows
> os_build=Windows
> [options]
> [build_requires]
> [env]
> 
> WARN: boost/1.72.0: requirement zlib/1.2.11 overridden by ths-client/None to zlib/1.2.11@conan/stable
> WARN: openssl/1.1.1d: requirement zlib/1.2.11 overridden by ths-client/None to zlib/1.2.11@conan/stable
> boost/1.72.0: WARN: Package is corrupted, removing folder: D:\.conan\d28fcd\1
> nasm/2.14: WARN: Package is corrupted, removing folder: D:\.conan\data\nasm\2.14\_\_\package\b2fcbc60b3bee75023a4f7934cadb723eec550bd
> conanfile.py (ths-client/None): Installing package
> Requirements
>     boost/1.72.0 from 'conan-center' - Cache
>     bzip2/1.0.8 from 'conan-center' - Cache
>     gsl_microsoft/2.0.0@bincrafters/stable from 'bincrafters' - Cache
>     openssl/1.1.1d from 'conan-center' - Cache
>     pcapplusplus/19.04@bincrafters/stable from 'bincrafters' - Cache
>     pthread-win32/2.9.1@bincrafters/stable from 'bincrafters' - Cache
>     winpcap/4.1.3@bincrafters/stable from 'bincrafters' - Cache
>     zlib/1.2.11@conan/stable from 'conan-center' - Cache
> Packages
>     boost/1.72.0:d23b03f4b2f5c819c42b1d0f32f3131799f51e1d - Build
>     bzip2/1.0.8:b7eeb3c6610abbce1a22dfdcf72bd330fbad7b46 - Cache
>     gsl_microsoft/2.0.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
>     openssl/1.1.1d:905af0349b2753e6dc59539d1317f5af5de9dba9 - Build
>     pcapplusplus/19.04@bincrafters/stable:42a3244884854f9f8ce88e663ab9200ab885339b - Cache
>     pthread-win32/2.9.1@bincrafters/stable:a8aed829304fe5cc95659bc2d44fa1628511899a - Cache
>     winpcap/4.1.3@bincrafters/stable:a8aed829304fe5cc95659bc2d44fa1628511899a - Cache
>     zlib/1.2.11@conan/stable:a8aed829304fe5cc95659bc2d44fa1628511899a - Cache
> Build requirements
>     nasm/2.14 from 'conan-center' - Cache
>     strawberryperl/5.30.0.1 from 'conan-center' - Cache
> Build requirements packages
>     nasm/2.14:b2fcbc60b3bee75023a4f7934cadb723eec550bd - Build
>     strawberryperl/5.30.0.1:b2fcbc60b3bee75023a4f7934cadb723eec550bd - Cache
> 
> bzip2/1.0.8: Already installed!
> gsl_microsoft/2.0.0@bincrafters/stable: Already installed!
> pthread-win32/2.9.1@bincrafters/stable: Already installed!
> strawberryperl/5.30.0.1: Already installed!
> strawberryperl/5.30.0.1: Appending PATH environment variable: D:\.conan\8dbda5\1\bin
> strawberryperl/5.30.0.1: Appending PATH environment variable: D:\.conan\8dbda5\1\bin
> winpcap/4.1.3@bincrafters/stable: Already installed!
> zlib/1.2.11@conan/stable: Already installed!
> boost/1.72.0: WARN: Build folder is dirty, removing it: D:\.conan\d0fdfc\1
> boost/1.72.0: Building your package in D:\.conan\d0fdfc\1
> boost/1.72.0: Generator txt created conanbuildinfo.txt
> boost/1.72.0: Calling build()
> boost/1.72.0: bootstrap.bat
> Bootstrapping the build engine
> 
> Failed to bootstrap the build engine
> Please consult bootstrap.log for further diagnostics.
> 
> boost/1.72.0: WARN: Error 1 while executing bootstrap.bat
> boost/1.72.0: WARN: LOCALAPPDATA=C:\Users\xxx\AppData\Local
> Found with vswhere Visual Studio Locator version 2.7.1+180c706d56 [query version 2.3.2200.14893]
> ###
> ### "Unknown toolset: vcunk"
> ###
> ### You can specify the toolset as the argument, i.e.:
> ###     .\build.bat msvc
> ###
> ### Toolsets supported by this script are: borland, como, gcc,
> ###     gcc-nocygwin, intel-win32, metrowerks, mingw,
> ###     vc11, vc12, vc14, vc141, vc142
> ###
> ### If you have Visual Studio 2017 installed you will need to either update
> ### the Visual Studio 2017 installer or run from VS 2017 Command Prompt
> ### as we where unable to detect your toolset installation.
> ###
> 
> boost/1.72.0:
> boost/1.72.0: ERROR: Package 'd23b03f4b2f5c819c42b1d0f32f3131799f51e1d' build failed
> boost/1.72.0: WARN: Build folder D:\.conan\d0fdfc\1
> ERROR: boost/1.72.0: Error in build() method, line 397
>         self._bootstrap()
> while calling '_bootstrap', line 869
>         self.run(cmd)
>         ConanException: Error 1 while executing bootstrap.bat
> Exit code: 1
> An error occurred when executing task 'ConanInstall'.
> Error: 发生一个或多个错误。
>         conan install exception

**Comment by sinall** [comment]
> > x86 version is not available. Could you please add it?
> 
> What do you mean? The Boost x86 is not available for download or you can't build for x86?
> 
> Conan Center Index doesn't provide x86 package versions, please read the supported configurations section: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

The old conan center provides x86 packages, Is there any reason conan center index doesn't provide them anymore?

**Comment by sinall** [comment]
It seems that I need to pass 'vc141' as argument to bootstrap.bat, I want to add the argument directly in conanfile.py but I don't know which conanfile.py & bootstrap.bat is conan using. Too many folders under D:\.conan and the log doesn't give a clue.

**Comment by sinall** [comment]
After adding 'vc141' to conanfile.py of boost, it compiles. But openssl-1.1.1d compains now:

> PS D:\Documents\source\repos\myproj> conan install . -if conaninfo/Debug --profile debug --build missing --no-imports
> Configuration:
> [settings]
> arch=x86
> arch_build=x86
> build_type=Debug
> compiler=Visual Studio
> compiler.runtime=MDd
> compiler.version=14
> os=Windows
> os_build=Windows
> [options]
> [build_requires]
> [env]
> 
> openssl/1.1.1d: WARN: Package is corrupted, removing folder: D:\.conan\data\openssl\1.1.1d\_\_\package\905af0349b2753e6dc59539d1317f5af5de9dba9
> conanfile.py (ths-client/None): Installing package
> Requirements
>     boost/1.72.0 from 'conan-center' - Cache
>     bzip2/1.0.8 from 'conan-center' - Cache
>     gsl_microsoft/2.0.0@bincrafters/stable from 'bincrafters' - Cache
>     openssl/1.1.1d from 'conan-center' - Cache
>     pcapplusplus/19.04@bincrafters/stable from 'bincrafters' - Cache
>     pthread-win32/2.9.1@bincrafters/stable from 'bincrafters' - Cache
>     winpcap/4.1.3@bincrafters/stable from 'bincrafters' - Cache
>     zlib/1.2.11 from 'conan-center' - Cache
> Packages
>     boost/1.72.0:d23b03f4b2f5c819c42b1d0f32f3131799f51e1d - Cache
>     bzip2/1.0.8:b7eeb3c6610abbce1a22dfdcf72bd330fbad7b46 - Cache
>     gsl_microsoft/2.0.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
>     openssl/1.1.1d:905af0349b2753e6dc59539d1317f5af5de9dba9 - Build
>     pcapplusplus/19.04@bincrafters/stable:42a3244884854f9f8ce88e663ab9200ab885339b - Cache
>     pthread-win32/2.9.1@bincrafters/stable:a8aed829304fe5cc95659bc2d44fa1628511899a - Cache
>     winpcap/4.1.3@bincrafters/stable:a8aed829304fe5cc95659bc2d44fa1628511899a - Cache
>     zlib/1.2.11:a8aed829304fe5cc95659bc2d44fa1628511899a - Cache
> Build requirements
>     nasm/2.14 from 'conan-center' - Cache
>     strawberryperl/5.30.0.1 from 'conan-center' - Cache
> Build requirements packages
>     nasm/2.14:b2fcbc60b3bee75023a4f7934cadb723eec550bd - Cache
>     strawberryperl/5.30.0.1:b2fcbc60b3bee75023a4f7934cadb723eec550bd - Cache
> 
> bzip2/1.0.8: Already installed!
> gsl_microsoft/2.0.0@bincrafters/stable: Already installed!
> nasm/2.14: Already installed!
> nasm/2.14: Appending PATH environment variable: D:\.conan\data\nasm\2.14\_\_\package\b2fcbc60b3bee75023a4f7934cadb723eec550bd\bin
> pthread-win32/2.9.1@bincrafters/stable: Already installed!
> strawberryperl/5.30.0.1: Already installed!
> strawberryperl/5.30.0.1: Appending PATH environment variable: D:\.conan\8dbda5\1\bin
> winpcap/4.1.3@bincrafters/stable: Already installed!
> zlib/1.2.11: Already installed!
> boost/1.72.0: Already installed!
> boost/1.72.0: LIBRARIES: ['libboost_wave', 'libboost_container', 'libboost_contract', 'libboost_exception', 'libboost_graph', 'libboost_iostreams', 'libboost_locale', 'libboost_log', 'libboost_program_options', 'libboost_random', 'libboost_regex', 'libboost_serialization', 'libboost_wserialization', 'libboost_coroutine', 'libboost_fiber', 'libboost_context', 'libboost_timer', 'libboost_thread', 'libboost_chrono', 'libboost_date_time', 'libboost_atomic', 'libboost_filesystem', 'libboost_system', 'libboost_type_erasure', 'libboost_log_setup', 'libboost_math_c99', 'libboost_math_c99f', 'libboost_math_c99l', 'libboost_math_tr1', 'libboost_math_tr1f', 'libboost_math_tr1l', 'libboost_stacktrace_basic', 'libboost_stacktrace_noop', 'libboost_unit_test_framework']
> boost/1.72.0: Package folder: D:\.conan\d28fcd\1
> boost/1.72.0: Disabled magic autolinking (smart and magic decisions)
> openssl/1.1.1d: Applying build-requirement: strawberryperl/5.30.0.1
> openssl/1.1.1d: Applying build-requirement: nasm/2.14
> openssl/1.1.1d: WARN: Build folder is dirty, removing it: D:\.conan\data\openssl\1.1.1d\_\_\build\905af0349b2753e6dc59539d1317f5af5de9dba9
> openssl/1.1.1d: Copying sources to build folder
> openssl/1.1.1d: Building your package in D:\.conan\data\openssl\1.1.1d\_\_\build\905af0349b2753e6dc59539d1317f5af5de9dba9
> openssl/1.1.1d: Generator txt created conanbuildinfo.txt
> openssl/1.1.1d: Calling build()
> openssl/1.1.1d: using target: VC-conan-Debug-Windows-x86-Visual Studio-14 -> VC-WIN32
> openssl/1.1.1d: my %targets = (
>     "VC-conan-Debug-Windows-x86-Visual Studio-14" => {
>         inherit_from => [ "VC-WIN32" ],
>         cflags => add("-Zi -Ob0 -Od -MDd"),
>         cxxflags => add("-Zi -Ob0 -Od -MDd"),
> 
>         includes => add("D:/.conan/8dbda5/1/include", "D:/.conan/data/zlib/1.2.11/_/_/package/a8aed829304fe5cc95659bc2d44fa1628511899a/include"),
>         lflags => add(""),
> 
> 
> 
> 
> 
>     },
> );
> 
> openssl/1.1.1d:
> openssl/1.1.1d: ERROR: Package '905af0349b2753e6dc59539d1317f5af5de9dba9' build failed
> openssl/1.1.1d: WARN: Build folder D:\.conan\data\openssl\1.1.1d\_\_\build\905af0349b2753e6dc59539d1317f5af5de9dba9
> ERROR: openssl/1.1.1d: Error in build() method, line 595
>         self._make()
> while calling '_make', line 540
>         args = " ".join(self._configure_args)
> while calling '_configure_args', line 420
>         if self.settings.os == "Neutrino":
>         ConanException: Invalid setting 'Neutrino' is not a valid 'settings.os' value.
> Possible values are ['Android', 'Arduino', 'FreeBSD', 'Linux', 'Macos', 'SunOS', 'Windows', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
> Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
> 
>

**Comment by SSE4** [comment]
@sinall as it says (at the very last line), you have to update your **settings.yml**. http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting

**Comment by sinall** [comment]
@SSE4 My project uses x86 libraries. Considering conan-center-index doesn't provide x86 versions, I'm going to rollback the change and use conan-community again at this moment.
But the problem now is that I have removed 'OpenSSL' previously, now I can't use it because of **case incompatible** issue. Do you know which version of conan can I use to avoid this?

**Comment by sinall** [comment]
@SSE4 Is `openssl/1.1.1d@_/_` the same as `openssl/1.1.1d`? I'm confused by those different suffixes like `_/_`, `conan/stable`, 'bincrafters/stable`, are they eventually replaced by `openssl/1.1.1d`?

**Comment by danimtb** [comment]
Hi @sinall,

Let me answer the questions in order:

- No, we are not providing binaries for the x86 configuration. However, building those binaries yourself should be straightforward using --build <pkg-name>` when installing your dependencies. The reason for this is just optimization of the building service: there are a lot of libraries, versions, and configurations to build. And of course usage: we see considerably fewer downloads for the x86 architecture and in some cases like MacOS, no further support for this architecture.

- Casing issues are known and Windows and we cannot do anything to solve them. Conan warns you about this possible issue and you will have to choose which package to use. That's why all new packages in this repo are always lowercase. Unfortunately, there is no Conan version (older or newer) able to overcome this issue without user interaction on the file system.

- Yes, `openssl/1.1.1d` is under the hood equivalent to `openssl/1.1.1d@_/_`. Some Conan versions ago we introduced the feature to be able to create packages without user and channel. This was done based on the feedback from users and all the conan-center-index references do not have user and channel. However, its usage is not deprecated, and you can still use and create packages with user and channel at your wish.

Hope the information helps you.

Please comment if there is any fix the boost recipe needs in order to compile for the x86 arch, otherwise, this issue will be closed. Thank you!

**Comment by sinall** [comment]
@danimtb Thanks you for those detailed explanation, it is much clear now.
Does `boost/1.71.0@conan/stable` still have x86 binaries? It seems that used this config to install boost without build. (I may remember wrong.)

**Comment by danimtb** [comment]
Yes, `` still has binaries for x86 architecture (it was generated in the past using 3rd party CIs) and you can still use it.

You can check the existing x96 packages with the command:

```
conan search boost/1.71.0@conan/stable -q arch=x86 -r conan-center
```

However, take into account that the recipe will not be updated with the changes in this repo (that's why we recommend using just `boost/1.71.0` from this repo instead).

No new packages will be uploaded to the reference `boost/1.71.0@conan/stable` and users should gradually shift to `boost/1.71.0`.

Hope that answers your questions. Thanks!

**Comment by sinall** [comment]
May I suggest conan could potentially classify libraries into different categories, and still provide x86 binaries for those very popular and build consuming libraries?

**Comment by danimtb** [comment]
@sinall I think it could be a partial solution. Anyway, I forgot to ask, why do you need the x86 package? Is that a hard requirement for you? We would like to know just in case we are missing something out of consideration. Thanks a lot

**Comment by sinall** [comment]
@danimtb It isn't hard requirement, there are 2 reasons:
1. A few users are still using 32bit Windows
2. Some of libraries my applications depends on still don't have corresponding conan infrastructure, they were previously compiled as 32bit.
The current situation is if I want to upgrade one of the libraries such as cpprestsdk, boost, etc, I have to compile them in my local machine, or I change entire application and dependencies to x64 architecture.
Compiling cpprestsdk is maybe easy, but boost will take huge time and could fail.
