### ISSUE TITLE
[package] glib/2.72.0: os.version not applied on MacOS

### ISSUE THREAD

**Issue by bkarasm** [conan-io/conan-center-index#10281]
### Package and Environment Details
  * Package Name/Version: **glib/2.72.0** (also tried with 2.70.1)
  * Operating System+version: **MacOS 12.2.1**
  * Compiler+version: **apple-clang 12.0.0**
  * Conan version: **conan 1.45.0**
  * Python version: **Python 3.9.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
`conan install glib/2.72.0@ -s os.version=10.12 -o glib:shared=True --build missing`

### Details
By setting os.version on MacOS I would expect that by running otool on any glib library, e.g. ` otool -l libglib-2.0.0.dylib `, I'd see an information that given library is supported from the desired version (10.12 in this case). 

Actual output:
```
...
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 11.1
      sdk 11.1
   ntools 1
     tool 3
  version 609.8
...
```

I verified that ` -mmacosx-version-min=10.12 ` flag is added to ` build.ninja ` so I'm not sure what's going wrong here.

**Comment by uilianries** [comment]
The setting `os.version` is not used by Conan Center.

**Comment by uilianries** [comment]
@battlmonstr I commented here: https://github.com/conan-io/conan-center-index/issues/20492#issuecomment-2162697246

It will not change your package ID. To change the package ID when using `tools.build:cxxflags`, you can add the follow configuration too:

`-c tools.info.package_id:confs='["tools.build:cxxflags"]'`

Still, you can add `os.version` to you settings.yml: https://docs.conan.io/2/examples/config_files/settings/settings_user.html
