### ISSUE TITLE
[boost] Boost 1.68.0 - Wrong linking order

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#103]
moved from https://github.com/conan-community/community/issues/51, by @uilianries 

### Description of Problem, Request, or Question

Hi!

I'm trying to build Facebook Folly package, but during linkage stage I get the follow error:

```
/home/conan/.conan/data/folly/2018.10.15.00/bincrafters/testing/package/a2b5bbc27f5f32aaf3f11506fa66f3c83eca270f/lib/libfolly.so: undefined reference to `boost::system::detail::generic_category_instance'
/home/conan/.conan/data/folly/2018.10.15.00/bincrafters/testing/package/a2b5bbc27f5f32aaf3f11506fa66f3c83eca270f/lib/libfolly.so: undefined reference to `boost::system::detail::system_category_instance'
```

@vdeurzen reported the same problem on Slack channel Conan:

> I'm having some trouble linking with boost from conan center, I'm missing some of the multithreading symbols it seems, any ideas what I might be doing wrong?
> for example: `boost::system::generic_category()`
> well, that's the first that's missing, I'm considering it may simply be the linking order
or `undefined reference to` > boost::log::v2s_mt_posix::aux::futex_based_event::wait()`

#### Logs:
* Travis: https://travis-ci.org/bincrafters/conan-folly/jobs/444214034#L2201

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.68.0@conan/stable**
* Operating System: **Linux**
* Compiler+version: **gcc-8**
* Docker image: **conanio/gcc8**
* Options: shared=False

### Steps to reproduce (Include if Applicable)

    git clone https://github.com/bincrafters/conan-folly.git
    cd conan-folly
    git checkout testing/2018.10.15.00
    conan create . bincrafters/testing -s build_type=Release -s arch=x86_64 -o folly:shared=True

**Comment by Croydon** [comment]
We don't have Boost 1.68.0 in CCI. Is this still a problem with newer Boost versions?

**Comment by SSE4** [comment]
I think it's done by #2097
