### ISSUE TITLE
[request] Clmg/3.0.2

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan-center-index#10317]
### Package Details
  * Package Name/Version: **Clmg/3.0.2**
  * Website: **http://cimg.eu/**
  * License: **CeCILL-C**
  * Source code: **https://github.com/dtschump/CImg**

### Description Of The Library / Tool
The CImg Library is a small and open-source C++ toolkit for image processing.

**Comment by SpaceIm** [comment]
CImg is already in conan-center.

**Comment by Tumb1eweed** [comment]
> CImg is already in conan-center.

Sorry, my bad, I overlook. Issue closed.
