### ISSUE TITLE
[question] Could conan use conda's method to split cuda into smaller dependency?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan-center-index#10371]
Like I said in #4844 , conda split the dependency of CUDA into specific libraries and compiler, etc.
![image](https://user-images.githubusercontent.com/27768261/163914958-f78546d9-3af2-4a72-b127-01ee07fb1a71.png)
Could conan use this idea to construct packages for CUDA?

**Comment by jgsogo** [comment]
Hi!

There is no strong requirement to build everything as a single package or several. The experience from these years shows that usually the best approach is to follow the build system: if all the sources are in the same repository and everything is built together, it is better to have one single package with different components (consumers can select which components to use and link with); but if the sources are scattered in different repositories and can be built independently, then several Conan packages are usually recommended.

Anyway, the best approach is always to submit some draft recipe, compiling some libraries, even if some requirements are not yet available and need to be linked from the system. On top of the draft, people can do suggestions, contribute requirements,... sometimes the process takes weeks, but working together is the only way to get some big libraries into conan-center.

**Comment by Tumb1eweed** [comment]
> Hi!
> 
> There is no strong requirement to build everything as a single package or several. The experience from these years shows that usually the best approach is to follow the build system: if all the sources are in the same repository and everything is built together, it is better to have one single package with different components (consumers can select which components to use and link with); but if the sources are scattered in different repositories and can be built independently, then several Conan packages are usually recommended.
> 
> Anyway, the best approach is always to submit some draft recipe, compiling some libraries, even if some requirements are not yet available and need to be linked from the system. On top of the draft, people can do suggestions, contribute requirements,... sometimes the process takes weeks, but working together is the only way to get some big libraries into conan-center.

Thanks. But I still confused, cuda doesn't like regular conan packages, first of all it's close source, so conan recipe doesn't need build stage (FYI, is there similar package in conancenter? Those don't need build, just download and package); and second, does github's CI/CD support GPU? If it doesn't, then it have to add a dependency for compiler (nvcc), if it does, then we could use docker from nvidia.

**Comment by jgsogo** [comment]
I don't think so. I agree it is widely used, but (still) there is not a high demand in ConanCenter for it. Probably the same comments from #4616 apply here: ConanCenter is not a place to redistribute binaries. If you are somehow in contact with Cuda developers, we can talk privately about some other alternatives, basically, we can help them to create Conan packages and setup a Conan remote for those packages.

**Comment by Tumb1eweed** [comment]
> I don't think so. I agree it is widely used, but (still) there is not a high demand in ConanCenter for it. Probably the same comments from #4616 apply here: ConanCenter is not a place to redistribute binaries. If you are somehow in contact with Cuda developers, we can talk privately about some other alternatives, basically, we can help them to create Conan packages and setup a Conan remote for those packages.
