### ISSUE TITLE
[question] Enforcing C11 (not C++)

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#10389]
Hi! :)

What's the preferred way to enforce a recipe to compile with C11 support? The project is CMake-based.

Thanks!

**Comment by SpaceIm** [comment]
`compiler.cppstd=11` in profile

**Comment by HappySeaFox** [comment]
> `compiler.cppstd=11` in profile

Correct me if I'm wrong, but this sets `C++` standard version. Not `C`.

**Comment by SpaceIm** [comment]
Oopps, sorry, misread. C standard is not a first class citizen in conan AFAIK, so there is no abstraction in profile which would inject the proper flag in underlying build system of the library.

What you can do is to set `CMAKE_C_STANDARD` to 11 in env section of your profile.
