### ISSUE TITLE
[service] makeinfo missing in CI

### ISSUE THREAD

**Issue by hlewin** [conan-io/conan-center-index#10385]
Working on https://github.com/conan-io/conan-center-index/pull/10365 I ran into the problem that makeinfo (texinfo) seems to be missing in the CI environment which causes build fails. I am unsure how to proceed from there. The package has no option to disable generation of docs.

Log of failed build: https://c3i.jfrog.io/c3i/misc/logs/pr/10365/1-linux-gcc/binutils/2.38//8e7714e05da644d1474247995163817b009f35ad-build.txt

**Comment by SSE4** [comment]
as I understand from the message, it should be optional:
```
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <http://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <http://www.gnu.org/software/make/>
```
in general, it should be needed only for the documentation, which we don't package anyway, so we usually just skip man-page generation (e.g. by specifying `--disable-doc`/`--disable-man`, if it's not available; or just making it no-op by specifying something like `MAKEIINFO=:` or `makeinfo=/bin/true`).
if it's impossible to bypass, and `makeinfo` is strictly required for the build, there are two ways how we can handle that situation:
1. install into our docker images (start by creating PR or issue for https://github.com/conan-io/conan-docker-tools)
2. package `makeinfo` as a conan package (e.g. packaging [textinfo](https://www.gnu.org/software/texinfo/) as a tool)
3. use system package with [SystemPackageTool](https://docs.conan.io/en/latest/reference/tools.html#tools-osinfo-and-tools-systempackagetool) to install it via apt. not sure if it's robust solution, as probably it will be required also for Windows and macOS?

/cc @uilianries @madebr @Croydon

**Comment by hlewin** [comment]
> as I understand from the message, it should be optional:
Partly. binutils contains quite a few subprojects which handle the generation differently. `as` seems to be the one that makes problems
```
GEN      doc/as.1
  MAKEINFO doc/as.info
Makefile:1465: recipe for target 'doc/as.info' failed
```

> in general, it should be needed only for the documentation, which we don't package anyway, so we usually just skip man-page generation (e.g. by specifying --disable-doc/--disable-man, if it's =available; or if it's not, just making it no-op by specifying something like MAKEIINFO=: or makeinfo=/bin/true).
I'll have a try doing this with env-vars as I do not see such an option for `as`.

**Comment by uilianries** [comment]
> 1. install into our docker images (start by creating PR or issue for [conan-io/conan-docker-tools](https://github.com/conan-io/conan-docker-tools))
> 2. package makeinfo as a conan package (e.g. packaging [textinfo](https://www.gnu.org/software/texinfo/) as a tool)
> 3. use system package with [SystemPackageTool](https://docs.conan.io/en/latest/reference/tools.html#tools-osinfo-and-tools-systempackagetool) to install it via apt. not sure if it's robust solution, as probably it will be required also for Windows and macOS?

I vote 2, if possible.

**Comment by madebr** [comment]
I've been able to build binutils without makeinfo/texinfo, so it's not really needed for that package.
But long term, it might be useful to have a texinfo package.

**Comment by hlewin** [comment]
> I've been able to build binutils without makeinfo/texinfo, so it's not really needed for that package.

Hmm - I can build 2.37 without but not 2.38...
May I ask how you did this?

**Comment by hlewin** [comment]
> I'll have a try doing this with env-vars as I do not see such an option for as.

Okay... This approach does not seem to work in this case.

TBH I am shying away from making a texinfo package and introducing a build-requirement for this: I have the feeling that such tools do not really belong into a package-recipe as requirement as they are part of an expected build-environment (Where would such a line be drawn? Is make available? Is there a compiler? ....)

**Comment by madebr** [comment]
This works on my Linux box:
https://github.com/madebr/conan-center-index/tree/recipes_wip/recipes/binutils

**Comment by hlewin** [comment]
I have to say, I feel tempted to make a try getting this into the docker image(s).
Listing this as explicit build-requirement in a recipe would lead to having conan download/build a package that alledgedly  is present on most *nix dev-systems.
Windows on the other hand is a whole different issue. In a mingw-environment the tool is likely to be present as well. For native/msvc I do not see if binutils makes much sense at all.

**Comment by madebr** [comment]
About my binutils recipe at https://github.com/madebr/conan-center-index/tree/recipes_wip/recipes/binutils,
it will build binutils for the target architecture. When that is not available, it will build for the host instead.

So the following should create a "native" binutils (when building on Linux, the built binutils will create binaries for Linux)
```
conan create . binutils/2.38@
``

It can also be used as a build requirement (untested).
When used as a build requirement, it will built binaries that generate binaries for the target os/arch.

That's where my questions for @jgsogo starts:
- how can I add settings_target to the package id?
- is it possible to create a binutils package, built for a different target os/arch, without having it as a build requirement?

**Comment by hlewin** [comment]
> how can I add settings_target to the package id?
Right now, binutils package that target Linux/Windows will use the same package_id.

Without any guarantees (I am quite new to conan) - from the docs I guess the settings_target would have to be translated to an option. see the example at https://docs.conan.io/en/latest/systems_cross_building/cross_building.html

This would also solve your 2nd issue.
When looking at your recipe it seems you already have put more work into it than me. Do you have any plans on having it merged into the "official" index?

**Comment by jgsogo** [comment]
Yes, that's the best approach I could think about it, at least for Conan v1.x. I really don't know what are the plans in v2 regarding this issue.

The `settings_target` are only available when the recipe is used as a build-requires, so the only way to add them to the packageID is to _encode_ them using an option. Then you should validate that the option matches the actual settings_target. It requires more work from the user (more things to provide in profiles and ensure they match), but probably the best we can do now.

I think that the Android NDK recipe already contains some of this.

**Comment by madebr** [comment]
> > how can I add settings_target to the package id?
> > Right now, binutils package that target Linux/Windows will use the same package_id.
> 
> Without any guarantees (I am quite new to conan) - from the docs I guess the settings_target would have to be translated to an option. see the example at https://docs.conan.io/en/latest/systems_cross_building/cross_building.html
> 

I've just added support +  for building binutils targeting x86/x86_64 on Linux/Windows + armv8,
using the suggestions from @jgsogo (thanks for that!)


> This would also solve your 2nd issue. When looking at your recipe it seems you already have put more work into it than me. Do you have any plans on having it merged into the "official" index?

I'll open a pr in a few minutes.
Let's see how it fares...

**Comment by madebr** [comment]
> > how can I add settings_target to the package id?
> > Right now, binutils package that target Linux/Windows will use the same package_id.
> 
> Without any guarantees (I am quite new to conan) - from the docs I guess the settings_target would have to be translated to an option. see the example at https://docs.conan.io/en/latest/systems_cross_building/cross_building.html
> 

I've just added support +  for building binutils targeting x86/x86_64 on Linux/Windows + armv8,
using the suggestions from @jgsogo (thanks for that!)


> This would also solve your 2nd issue. When looking at your recipe it seems you already have put more work into it than me. Do you have any plans on having it merged into the "official" index?

I've opened #10406
Let's see how it fares...
