### ISSUE TITLE
[question] How to make a PR build in C++17 mode?

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#10390]
Hi!

The pull request https://github.com/conan-io/conan-center-index/pull/10364 doesn't actually build the project as it requires C++17 and has

```
def validate(self):
    tools.check_min_cppstd(self, "17")
```

in the conanfile.

As a result, every CI node fails with `INVALID_CONFIGURATION` exception which is expected.

Q: How to force the nodes to use C++17?

**Comment by SpaceIm** [comment]
The underlying build system itself should ensure that at least C++17 is used (the proper way in a CMakeLists is `target_compile_features(foo PUBLIC cxx_std_17)`).

On top of that, conan-center recipes check that if `compiler.cppstd` is set in profile, it is at least the minimum C++ standard required by the project, basically for a C++17 project:

```python
def validate(self):
    if self.settings.compiler.get_safe("cppstd"):
        tools.check_min_cppstd(self, "17")
```

Moreover, you may have to manually check compiler version to raise ConanInvalidConfiguration if it can't support C++17.
