### ISSUE TITLE
[package] openssl/3.0.2: Failed to load legacy provider with prebuilt binaries

### ISSUE THREAD

**Issue by conr2d** [conan-io/conan-center-index#10409]
### Package and Environment Details
  * Package Name/Version: **openssl/3.0.2**
  * Operating System+version: **Linux Ubuntu 20.04** / **macOS Monterey**
  * Compiler+version: **GCC 10** (Ubuntu) / **AppleClang 13** (macOS)
  * Docker image: -
  * Conan version: **conan 1.47.0**
  * Python version: **Python 3.9.12**

### Conan profile
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Steps to reproduce

Even though all recipes for prebuilt binaries are configured with `no_legacy=False`, but it failed to load legacy provider with them.
If legacy provider is loaded successfully, following code should not show `0x0`, but it does.

``` c++
#include <iostream>
#include <openssl/provider.h>

int main() {
  std::cout << (void*)OSSL_PROVIDER_load(nullptr, "legacy") << std::endl;
}
```

**Comment by SSE4** [comment]
I am not familar with legacy providers, but that's indeed super weird

**Comment by conr2d** [comment]
https://www.openssl.org/docs/man3.0/man7/migration_guide.html#Legacy-Algorithms
Some cryptographic algorithms like ripemd-160 hash function has been deprecated since OpenSSL 3 and it requires loading legacy provider prior to calling them. I can make legacy provider loaded with OpenSSL installed by homebrew on macOS, but it failed to load with prebuilt binaries installed by Conan.

**Comment by e2m4n** [comment]
> Even though all recipes for prebuilt binaries are configured with `no_legacy=False`

If I understand the [INSTALL.md file](https://github.com/openssl/openssl/blob/master/INSTALL.md#enable-and-disable-features) correctly, the way to ensure the legacy provider would be to pass `enable-legacy`. But it should be enabled by default.

I've tried building after explicitly setting `enable-legacy`, but `OSSL_PROVIDER_load(NULL, "legacy");` still returns NULL.

The openssl command line tool also fails:
```
$ openssl version
OpenSSL 3.1.0-dev  (Library: OpenSSL 3.1.0-dev )
$ echo "123456" > 123456
$ openssl enc -bf-ecb < "123456"
enter BF-ECB encryption password:
Verifying - enter BF-ECB encryption password:
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
Error setting cipher BF-ECB
80AB5477667F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:330:Global default library context, Algorithm (BF-ECB : 0), Properties ()
Salted__
```
even though I have the openssl.cnf file configured as documented here: https://wiki.openssl.org/index.php/OpenSSL_3.0#Providers

**Comment by jngrb** [comment]
If the path to the shared legacy module changes (which is often the case for pre-built packages), the OpenSSL library might not be able to find and load the module.

You will need to activate the no-module in additition to the no-shared option to have fully statically linkable OpenSSL libraries.

I added a PR that adds the no_module/no-module option to the OpenSSL v3.0.x recipe => #11780
