### ISSUE TITLE
[center.conan.io] add badge for projects in conan center

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#1042]
would be great if cci automatically creates a badge for projects which they can put in the readme.

this badge should be a link to the https://conan.io/center/

this is already possible for bintray but not for conan center

**Comment by claremacrae** [comment]
As a manual workaround, the following markdown code works nicely:

```markdown
[![ConanCenter package](https://repology.org/badge/version-for-repo/conancenter/approvaltests.cpp.svg)](https://conan.io/center/approvaltests.cpp)
```

**Comment by Croydon** [comment]
This become possible at some point

See the `badges` tab: https://conan.io/center/recipes/openssl

Issue can be closed
