### ISSUE TITLE
[center.conan.io] show required dependencies in UI

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#1043]
I imagine:

now we have overview, recipe, configuration
in a next tab like dependencies we show: 

* build dependencies
* required dependencies
* optional dependencies and options which make those hard dependencies

and the other way around

show which packages depend on this one

npm does exactly this: `dependencies` and `dependents`

**Comment by Dattax** [comment]
We have added a basic dependencies tab: https://conan.io/center/freetype?tab=dependencies

**Comment by gocarlos** [comment]
great, we now have this feature

thanks
