### ISSUE TITLE
[conan.io/center] menu issue?

### ISSUE THREAD

**Issue by erdincay** [conan-io/conan-center-index#10452]
Markdown failed. I do not know any more on this issue.

**Comment by erdincay** [comment]
I will also add some information which i have witnessed:

Conan Center has an menu to view issue concerning the menu tabs of the package details page: 

https://conan.io/center/gtk?tab=overview

This page displays the following menu tabs to links: 

overview -> https://conan.io/center/gtk?tab=overview
use it -> https://conan.io/center/gtk?tab=recipe
recipe -> https://conan.io/center/gtk?tab=configuration
configuration -> https://conan.io/center/gtk?tab=dependencies&os=
dependencies -> https://conan.io/center/gtk?tab=usedby&os=
used by -> https://conan.io/center/gtk?os= 

Should I create another ticket for this?

**Comment by jgsogo** [comment]
Done with the `Use it` tab. Please, open a different issue for tabs-related one, or, at least, change the title of this one.

Thanks for reporting.

**Comment by erdincay** [comment]
Initial error was: [conan.io/center] Markdown failed gtk/system@#f6c019e9de83c8dd8ad2229bbce517df 

This has been solved. Thanks @jgsogo 

I think the second issue, concerning the wrong links has also been resolved. The page works fine.
