### ISSUE TITLE
lua/5.3.5: does not build on mobile iOS (and Android) 

### ISSUE THREAD

**Issue by a4z** [conan-io/conan-center-index#1046]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **lua/5.3.5**
  * Operating System+version: **Mac OSX**
  * Compiler+version: **clang from andriod ndk 21 and latest xcode **
  * Conan version: **conan 1.22.2**
  * Python version: **Python 3.7.6**

### Conan profile 
```
[settings]
os=iOS
os_build=Macos
arch=armv7
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
os.version=10.0
[options]
openssl:no_zlib=True
[build_requires]
*: cmake_installer/3.16.3@conan/stable, darwin-toolchain/1.0.6@theodelrieu/stable
[env]
CONAN_CMAKE_GENERATOR=Xcode
```

### Steps to reproduce (Include if Applicable)

build lua for iOS 

get a system calls on mobile are not available / wanted

### Logs (Include/Attach if Applicable)

```
f9c0cf0e82727814f66362eeb3305279f08ac9/lua.build/Release-iphoneos/lua.build/Objects-normal/armv7/loslib.o
/Users/a4z/.conan/data/lua/5.3.5/_/_/build/6bf9c0cf0e82727814f66362eeb3305279f08ac9/source_subfolder/src/loslib.c:143:14: error: 'system' is unavailable: not available on iOS
  int stat = system(cmd);
             ^
In file included from /Users/a4z/.conan/data/lua/5.3.5/_/_/build/6bf9c0cf0e82727814f66362eeb3305279f08ac9/source_subfolder/src/loslib.c:15:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/stdlib.h:190:6: note: 'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
1 error generated.
```

</details>

**Comment by gocarlos** [comment]
fixed?

**Comment by a4z** [comment]
yes, https://github.com/conan-io/conan-center-index/blob/master/recipes/lua/all/patches/5.3.5/lua_mobile.patch

not sure what about the latest version, but I guess the patch need to be ported to 5.4.1
