### ISSUE TITLE
[request] <pbc>/<0.5.14>

### ISSUE THREAD

**Issue by kshehata** [conan-io/conan-center-index#10496]
### Package Details
  * Package Name/Version: **pbc/0.5.14**
  * Website: **https://crypto.stanford.edu/pbc/**
  * Source code: **https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz**

### Description Of The Library / Tool

The PBC library is a free portable C library allowing the rapid prototyping of pairing-based cryptosystems. It provides an abstract interface to a cyclic group with a bilinear pairing, insulating the programmer from mathematical details. Knowledge of elliptic curves is optional.

**Comment by kshehata** [comment]
I've written PR #10394 to add a recipe for adding PBC to ConanCenter. I can't seem to directly assign anyone to the PR, how do I go about getting it reviewed? Thanks!

**Comment by SSE4** [comment]
> I've written PR #10394 to add a recipe for adding PBC to ConanCenter. I can't seem to directly assign anyone to the PR, how do I go about getting it reviewed? Thanks!

don't worry, our bot periodically assigns reviewers automatically.

**Comment by kshehata** [comment]
Not sure what's going on, but CI failed for no apparent reason. I've poked it and now it's green. I've gotten 1 approval. How do I get the rest?

**Comment by kshehata** [comment]
Fantastic! Thank you so much, I can't wait to link to this instead of my custom build.
