### ISSUE TITLE
[conan.io/center] Markdown failed `cgal/5.3@#efaaad29dd4cd2490a2b43dd98880194`

### ISSUE THREAD

**Issue by dstrebe-tableau** [conan-io/conan-center-index#10514]
See title. That failed.
https://conan.io/center/cgal?tab=recipe&os=Windows

**Comment by lrineau** [comment]
Hi, I am a member of the upstream CGAL.org project, and I am trying to take over the maintenance of the `cgal` recipe.

Recently, I have helped update the recipe to version 5.5 of CGAL: PR #12249 (recently merged).

What is the actual issue with markdown and `cgal`? Is it solved now that PR #11249 has been merged?

**Comment by jgsogo** [comment]
Hi! The generation of the markdowns was more challenging than expected. We are working on a new implementation that should be more error-prone. Currently, we use CloudRun in GCP which uses some kind of virtualization for the filesystem... and the process of generating the markdown fails too often (sometimes the download fails). The idea is to start using a regular node in k8s (like the ones we use to build the packages) which should be much more reliable.

**Comment by lrineau** [comment]
Is there anything I should do in the `cgal` recipe to fix or help?

**Comment by jgsogo** [comment]
Not really. One of the underlying issues is that the markdown generator is a regular generator, so it is executed by `conan install .... -g markdown`. Conan computes the graph of dependencies (it needs a valid configuration) and actually downloads all the requirements to the local cache. There is too much processing just to generate a ~README file, but so far it is not decoupled and has to be executed that way.

**Comment by jgsogo** [comment]
The new implementation will generate all these files again.
