### ISSUE TITLE
[package] libwebp/1.2.2: Failed to build cpufeatures when building libwebp for Android

### ISSUE THREAD

**Issue by WilliamBehrens** [conan-io/conan-center-index#10513]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libwebp/1.2.2**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **clang 8**
  * Conan version: **conan 1.47.0**
  * Python version: **Python 3.8.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
include(default)

target_host=aarch64-linux-android
android_ndk={{os.getenv("ANDROID_NDK")}}
api_level=21

[settings]
arch=armv7
build_type=Release
compiler=clang
compiler.libcxx=c++_shared
compiler.version=8
os=Android
os.api_level=$api_level

[conf]
tools.android:ndk_path=$android_ndk

[env]
PATH=[$android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host$api_level-clang
CXX=$target_host$api_level-clang++
LD=$target_host-ld
STRIP=$target_host-strip
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
CMake Error at source_subfolder/CMakeLists.txt:104 (add_library):
  Cannot find source file:

    /sources/android/cpufeatures/cpu-features.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at source_subfolder/CMakeLists.txt:104 (add_library):
  No SOURCES given to target: cpufeatures


CMake Generate step failed.  Build files cannot be regenerated correctly.
libwebp/1.2.2: ERROR: Package '21bb55e04f4ffef30958620a9d177197b82602c7' build failed
libwebp/1.2.2: 
libwebp/1.2.2: WARN: Build folder /home/wbehrens@staudertech.local/.conan/data/libwebp/1.2.2/_/_/build/21bb55e04f4ffef30958620a9d177197b82602c7
ERROR: libwebp/1.2.2: Error in build() method, line 96
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 89
        self._cmake.configure()
```

</details>

**Comment by SpaceIm** [comment]
Upstream CMakeListe relies on cpufeature source code being availabe in Android NDK:  https://github.com/webmproject/libwebp/blob/v1.2.2/CMakeLists.txt#L102-L115

I don't understand how adding `cpu_features/0.7.0` to requirements could fix anything without more modification in libwebp CMakeLists.

**Comment by WilliamBehrens** [comment]
> Upstream CMakeLists relies on cpufeature source code being availabe in Android NDK: https://github.com/webmproject/libwebp/blob/v1.2.2/CMakeLists.txt#L102-L115
> 
> I don't understand how adding `cpu_features/0.7.0` to requirements could fix anything without more modification in libwebp CMakeLists.

That's strange then, I'm using ndk 19c so it could just be too old, it did work by adding that line to the conanfile though strangely

**Comment by WilliamBehrens** [comment]
On second look cpufeatures source code is available in `<ndk-r19c-root>/sources/android/cpufeatures` so I'm unsure why the profile I'm using can't find it?

**Comment by WilliamBehrens** [comment]
I fixed it by fixing my spelling of Android(oops) and adding `CONAN_CMAKE_ANDROID_NDK=$android_ndk` under the `[env]` header
