### ISSUE TITLE
[package] qt/6.3.0: Cannot build exe with CCI prebuilt binaries, due to cppstd mismatch

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#10520]
In short, CCI's prebuilts do not have cppstd=17 specified, but QT 6.3.0 requires C++17 minimum.

OS: Linux Mint 20.3
Conan 1.47.0
Python 3.8.10

Configuration for profile qttest:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
CC=gcc-10
CXX=g++-10
```

NOTE: There is no compiler.cppstd=17
This is to match up with CCI's prebuilt binaries.

Make simple project
```
mkdir hello
cd hello
conan new hello/1.0 --template=cmake_exe
```

Edit conanfile.py, add:
```
generators = "CMakeToolchain", "CMakeDeps"
requires = "qt/6.3.0"
```

Get QT downloaded
```
conan install . -bf=build -pr=qttest
# Note: this should download CCI's precompiled version
```

Check the settings in QT6
```
conan show qt/6.3.0@
# should show:
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++11
            compiler.version: 10
            os: Linux
```

Edit our src to add 1 include... into src/hello.cpp, add:
```
#include <QString>
```

Try and build our project
```
cd build
conan build ..
```

Fails with the warning:
```
/build/conandata/conan-data/qt/6.3.0/_/_/package/9e25f8e30bf8d9b3ae3f64836ef8a25f280e3504/include/QtCore/qglobal.h:125:6: error: #error "Qt requires a C++17 compiler"
  125 | #    error "Qt requires a C++17 compiler"
      |      ^~~~~
```

And, if I add compiler.cppstd=17 into my profile,
conan will refuse to use the CCI version (it does not include the cppstd=17).

**Comment by paulharris** [comment]
Also note that 
```
conan install . -if=build -pr=profile
conan build . -bf=build -if=build
```
 does not work, says:
```
Using lockfile: '/build/gitsuper1/test-qt/hello/build/conan.lock'
Using cached profile from lockfile
conanfile.py (hello/1.0): Calling build()
ERROR: conanfile.py (hello/1.0): Error in build() method, line 42
	cmake = CMake(self)
	FileNotFoundError: [Errno 2] No such file or directory: '/build/gitsuper1/test-qt/hello/build/cmake-build-release/conan/CMakePresets.json'
```

It is looking in build/cmake-build-release
but it should be looking in ./cmake-build-release
because I didn't specify the output folder as the build folder.
It works if I do:
```
conan install . -if=build -of=build -pr=profile
conan build . -bf=build -if=build
```
But surely the output folder should have been stored in the build config?
Or the default should not be the current folder?

**Comment by SpaceIm** [comment]
It's not a conan-center issue. Just add C++17 in your CMakeLists or buid from source (`-b missing`) if you have `compiler.cppstd=17` in your profile.

**Comment by paulharris** [comment]
I'm not sure you understand,
I'm asking, how is it possible for *anyone* to use those pre-build binaries on CCI ?
Doesn't everyone need to add compiler.cppstd=17 to their profile in order to use those binaries?
And if so, then conan won't download the pre-built binaries ...

I'm also wondering how did the CI build those pre-built binaries without cppstd=17 set during the build?

Seems to me that those pre-built binaries aren't usable by conan users?

And adding C++17 directly into my CMakeLists.txt doesn't seem to be the conan way?

**Comment by paulharris** [comment]
I still don't understand what is going on here,
but I build all my packages now so I can close this and await V2.

**Comment by SpaceIm** [comment]
I don't understand what you don't understand :smile:

I would just say that CI is able to build C++11/14/17 libraries even if `compiler.cppstd` is not set, like you can build a library based on CMake without explicitly injecting `CMAKE_CXX_STANDARD` (for example when there are few `target_compile_features(target PUBLIC cxx_std_xx)`).

When compiler.cppstd is not set, you have no control over the C++ standard used in each library, that's all, but it should build.

Now at consume time, it's your problem. But conan generators are not able to pass a compile feature.
