### ISSUE TITLE
[package] hdf5/1.12.1 still depends on zlib/1.2.11 while many other use zlib/1.2.12

### ISSUE THREAD

**Issue by janbac** [conan-io/conan-center-index#10550]
Our software is built using conan. It depends, among others, on hdf5 and boost. 
Both depend on zlib.
Recently boost/1.78.0 got updated from using zlib/1.2.11 to zlib/1.2.12 (https://github.com/conan-io/conan-center-index/commit/9301eda1ed7c97e17bf32e3384823e596ef76ee9)
After that we get an error during `conan install`:
```
ERROR: Conflict in hdf5/1.12.0:
'hdf5/1.12.0' requires 'zlib/1.2.11' while 'boost/1.74.0' requires 'zlib/1.2.12'.
To fix this conflict you need to override the package 'zlib' in your root package.
```

However, being new to conan, we couldn't figure out how to state the correct `override` in our conanfile.py to fix this issue.
Also I am unsure whether this is a good fix, as we would override the dependency even after the problem vanished.
Or can I state that I don't care about exact minor versions of zlib being used and let conan decide?

I guess the best solution would be to also update hdf5 to zlib/1.2.12?
As I understand it would be best to change all dependencys on a package simultaneously if a new version is to be used, as users may otherwise run into the same problem in the future?

Thanks alot for working on conan and helping me with this problem!

**Comment by SpaceIm** [comment]
in your `conanfile.py` you could have something like this:

```python
    def requirements(self):
        self.requires("boost/1.78.0")
        self.requires("hdf5/1.12.0")
        self.requires("zlib/1.2.12", override=True)
```

Otherwise there is https://github.com/conan-io/conan-center-index/pull/10179, but no progress for 1 week.
