### ISSUE TITLE
[package] pkgconf/1.7.3: build failed with Error 2

### ISSUE THREAD

**Issue by basheer247** [conan-io/conan-center-index#10558]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **minizip-ng/3.0.5**
  * Operating System+version: **Linux Basheer-ZBook 5.10.102.1-microsoft-standard-WSL2**
  * Compiler+version: **GCC 8**
  * Conan version: **conan 1.47.0**
  * Python version: **Python 3.8.10**

pkgconf/1.7.3: Applying build-requirement: meson/0.62.1
pkgconf/1.7.3: Applying build-requirement: ninja/1.10.2
pkgconf/1.7.3: WARN: Build folder is dirty, removing it: /home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4
pkgconf/1.7.3: Copying sources to build folder
pkgconf/1.7.3: Building your package in /home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4
pkgconf/1.7.3: Generator txt created conanbuildinfo.txt
pkgconf/1.7.3: Aggregating env generators
pkgconf/1.7.3: Calling build()
The Meson build system
Version: 0.62.1
Source dir: /home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/source_subfolder
Build dir: /home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/build_subfolder
Build type: native build
Project name: pkgconf
Project version: 1.7.3

source_subfolder/meson.build:1:0: ERROR: Could not invoke sanity test executable: [Errno 2] No such file or directory: '/home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/build_subfolder/meson-private/sanitycheckc.exe'.

A full log can be found at /home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/build_subfolder/meson-logs/meson-log.txt
pkgconf/1.7.3:
pkgconf/1.7.3: ERROR: Package '6173abd988ee2e3159da6cce836868055fdb1cb4' build failed
pkgconf/1.7.3: WARN: Build folder /home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4
ERROR: pkgconf/1.7.3: Error in build() method, line 101
        meson = self._configure_meson()
while calling '_configure_meson', line 84
        meson.configure(source_folder=self._source_subfolder, build_folder=self._build_subfolder)
        ConanException: Error 1 while executing meson "/home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/source_subfolder" "/home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/build_subfolder" --backend=ninja -Dprefix="/home/basheer/.conan/data/pkgconf/1.7.3/_/_/package/6173abd988ee2e3159da6cce836868055fdb1cb4" -Dlibdir="lib" -Dbindir="bin" -Dsbindir="bin" -Dlibexecdir="bin" -Dincludedir="include" -Ddefault_library="static" -Dtests="False" -Dsharedstatedir="/home/basheer/.conan/data/pkgconf/1.7.3/_/_/package/6173abd988ee2e3159da6cce836868055fdb1cb4/bin/share" --buildtype=release

**Comment by basheer247** [comment]
### **meson-log.txt**

Build started at 2022-04-30T14:57:50.851947
Main binary: /usr/bin/python3
Build Options: -Dprefix=/home/basheer/.conan/data/pkgconf/1.7.3/_/_/package/6173abd988ee2e3159da6cce836868055fdb1cb4 -Dlibdir=lib -Dbindir=bin -Dsbindir=bin -Dlibexecdir=bin -Dincludedir=include -Ddefault_library=static -Dtests=False -Dsharedstatedir=/home/basheer/.conan/data/pkgconf/1.7.3/_/_/package/6173abd988ee2e3159da6cce836868055fdb1cb4/bin/share -Dbackend=ninja -Dbuildtype=release
Python system: Linux
The Meson build system
Version: 0.62.1
Source dir: /home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/source_subfolder
Build dir: /home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/build_subfolder
Build type: native build
Project name: pkgconf
Project version: 1.7.3
Sanity testing C compiler: i686-centos7-linux-gnu-gcc
Is cross compiler: False.
Sanity check compiler command line: i686-centos7-linux-gnu-gcc sanitycheckc.c -o sanitycheckc.exe -m32 -O3 -s -DNDEBUG -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/build_subfolder/meson-private/sanitycheckc.exe

source_subfolder/meson.build:1:0: ERROR: Could not invoke sanity test executable: [Errno 2] No such file or directory: '/home/basheer/.conan/data/pkgconf/1.7.3/_/_/build/6173abd988ee2e3159da6cce836868055fdb1cb4/build_subfolder/meson-private/sanitycheckc.exe'.

**Comment by madebr** [comment]
I suppose this is on WSL2 and not using a docker image (=you forgot to remove `conanio/gcc8` from your initial message)?

It looks like you are trying to build Windows executables (`.exe` suffixes) using compiler targeting Linux (`i686-centos7-linux-gnu-gcc`).
I'm no wsl2 user, but I think the default compilers of the distro running inside wsl2 build only linux executables (unless you use a suitable mingw toolchain.

**Comment by basheer247** [comment]
Hi @madebr , yeah, i forgot to remove the docker reference (edited). I'm running Linux on Windows (WSL2), Ubuntu distro from Microsoft Store. I'm using the special gcc compiled using https://crosstool-ng.github.io/.

I can run the sanitycheck in the wsl2 terminal without any error. 
_i686-centos7-linux-gnu-gcc sanitycheckc.c -o sanitycheckc.exe -m32 -O3 -s -DNDEBUG -D_FILE_OFFSET_BITS=64_

I think it ignores the ".exe" part when testing it on Linux. 

what i dont understand is that should i use the cross build or native build? if cross build, where should place the cross file and what will be the name of the cross file?

**Comment by madebr** [comment]
Since you're running inside wsl2, which is essentially a linux distribution, and you're using `i686-centos7-linux-gnu-gcc`, you're not cross building.
You're effectively natively building an application for Linux.
So I think you don't need any cross file. You just need to set `CC=i686-centos7-linux-gnu-gcc CXX=i686-centos7-linux-gnu-g++` and `os=Linux arch=x86` in your profile.

But then again, I don't use wsl2 myself so I can't really help you further.

**Comment by basheer247** [comment]
My conan profile is below.

```
_[env]
CONAN_CMAKE_FIND_ROOT_PATH=/home/basheer/x-tools/i686-centos7-linux-gnu/
CHOST=i686-centos7-linux-gnu
AR=i686-centos7-linux-gnu-ar
AS=i686-centos7-linux-gnu-as
RANLIB=i686-centos7-linux-gnu-ranlib
CC=i686-centos7-linux-gnu-gcc
CXX=i686-centos7-linux-gnu-g++
STRIP=i686-centos7-linux-gnu-strip

[settings]
os=Linux
os_build=Linux
arch=x86
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]_
```

All packages in my conan files are downloaded and cached properly except the minizip-ng/3.0.5 due the failure in pkgconf/1.7.3

```
[requires]
paho-mqtt-c/1.3.10
pugixml/1.12.1
rapidjson/1.1.0
spdlog/1.4.2
sqlite3/3.34.1
websocketpp/0.8.2
minizip-ng/3.0.5
catch2/2.13.8
libssh2/1.10.0
openssl/1.1.1n
cpp-httplib/0.10.4

[options]
websocketpp:asio=standalone
spdlog:header_only=True
fmt:header_only=True
pugixml:header_only=True
pugixml:no_exceptions=True
paho-mqtt-c:shared=False

[generators]
cmake
```

**Comment by basheer247** [comment]
@madebr The issue is with the cross compilation. 

The issue is sorted out by changing my conan install. I have sprecified the conan profile for the host machine and build machine.

From:

**`conan install ../Titan -pr=gcc8x86d -b=missing`**

To:

**`conan install ../Source --profile:host=gcc8x86d --profile:build=default -b=missing`**
-> gcc8x86d - custom compiler for host machine
-> default - default available gcc for my build machine (ubuntu WSL)

If there is any alternative or better way, i would like to hear.

**Comment by madebr** [comment]
Using a build and a host profile is the way to do a cross build with conan 1.x.
I think this will remain so in conan 2.x, but with some different syntax.

**Comment by basheer247** [comment]
@madebr noted and thank you.

Since this is the solution, i'm closing the issue.
