### ISSUE TITLE
[question] Default pattern for msys2 installer?

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#1059]
Original question comes from https://github.com/conan-io/conan-center-index/pull/971#discussion_r384523076

Usually we use the same exactly code for msys2 installer:

```python
    def build_requirements(self):
        if tools.os_info.is_windows and "CONAN_BASH_PATH" not in os.environ and \
           tools.os_info.detect_windows_subsystem() != "msys2":
            self.build_requires("msys2/20190524")
```

The question is, should we consider it as a pattern and apply all packages which are mingw compatible?

**Comment by madebr** [comment]
Is this #1054 or different?

**Comment by uilianries** [comment]
duplicated with #1054
