### ISSUE TITLE
[package] protobuf/3.20.0: Mismatched library names between debug and release

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan-center-index#10598]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **protobuf/3.20.0**
  * Operating System+version: **Windows 10 x64**
  * Compiler+version: **MSVC 17**
  * Conan version: **conan 1.47.0**
  * Python version: **Python 3.9.7**

### Steps to reproduce (Include if Applicable)
Simply require protobuf

The protobuf recipe produces libraries that differ in name between debug and release, which is utterly useless and causes issues.
Conan has separate directory structures for debug and release, so it makes even less sense to have different library names.
Having different library names causes issues with linking (when not using cmake in the consumer anyway) as the file name is different.
Other packages properly produce a unified library name (e.g. zlib).

</details>

**Comment by SpaceIm** [comment]
conan-center honors upstream lib names: https://github.com/protocolbuffers/protobuf/blob/cdc11c2d2d314ce0382fe0eaa715e5e0e1270438/CMakeLists.txt#L74-L75

**Comment by Sil3ntStorm** [comment]
So there is no chance of a PR that were to change this atrocious habit of producing different file names to be accepted?
Which would basically mean everyone not using cmake is fucked and has to run a fork of such recipes to fix atrocious and utterly stupid behavior...

**Comment by SSE4** [comment]
we usually package files "as is", following the convention of the upstream, not renaming anything, unless there is a strong reason to do it.
unfortunately, some projects tend to choose sophisticated naming for their libraries, and file name may depend on the platform, configuration (debug vs release), compiler and so on.
for instance, `zlib` library might be named:
- libz
- libzlib
- libzlibstatic
- libzlibstaticd
- z
- zlib

but renaming it to the unified value only makes it worse - as some projects tend to hard-code expected library name (like using `-lz` in their makefiles unconditionally), that then requires patching these makefiles to make it work properly for all the variants. but that's not just renaming, as executable and shared libraries bake the name of the dependency they are looking for, so it needs patching in earlier stage in build system, so everything is properly linked (in other words, if your executable looks for `libz.so`, you can't just rename `libzlib.so` to `libz.so`, you have to rebuild or patch the executable).

usually, you don't need to know the library name, as you use higher level abstractions, such as `pkg-config` files or `cmake` modules. in that case, you don't care what's the name on the file system, is it a single library or multiple or just header-only thing, are there any transitive dependencies, what's the linking order and so on. if possible, you should try to use that higher level abstractions. 

but that's not a silver bullet, and project tend to produce different target names per configuration 🤦  (e.g. `flatbuffers` vs `flatbuffer-shared`).
