### ISSUE TITLE
[boost] request: link boost with given python libs for a target system

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#106]
moved from https://github.com/conan-community/community/issues/162, by @Johnnyxy 

hi there,
I have a problem with the boost recipe. The recipe executes python scripts to detect the current version and other stuff. But for cross-compiling I need to specify the python libs which boost should be linked with by myself. I cannot rely on any autodetection the boost recipe does.

You can test this easily by "cross-building" boost on Windows from e.g. x86_64 to x86.
```python
os_build = "Windows"
os_arch = "x86_64"
os = "Windows"
arch = "x86"
```

When I am executing a Python x86_64 (64 bit) then the boost recipe would try to link against the wrong libs which it detects in the executing Python (x86_64) path.

The same applies to the Python version. If I want to link against Python 3.6 (target machine) but running Conan (build machine) with Python 3.7. Again the boost recipe tries to link against 3.7 (detected for the build machine) not 3.6 for the target machine.

Did I overlook something or is this not possible with the current boost recipe?

Best regards

**Comment by perseoGI** [comment]
Hi, I'm reviewing old issues. This is a real old one!
I'm closing this issue as boost recipe has change A LOT since this issue was open.


If this issue remains, do not hesitate to reopen it! 😄
