### ISSUE TITLE
[question] Is there any plan to have a commonly used SDL2::SDL2 target instead of sdl::sdl?

### ISSUE THREAD

**Issue by ghost** [conan-io/conan-center-index#10614]
I am pretty new with conan package manager so far and I really like how simple it makes dependency management! I'd like to use conan together with cmake, but in a non-instrusive way. So conan is only responsible for managing the dependencies, but it should not interfere with any cmake variables. In cmake you call find_package(SDL2 CONFIG REQUIRED) as usual and you links this third-party to your cmake target like this: target_link_libraries(target SDL2::SDL2) and that's it.

As far as I understand I use CMakeDeps in my conanfile.txt and it should work out-of-the-box or am I missing something?

Could you please help me out if I missing something?

```
c:\workspace>cd cpp-cmake-conan-base

c:\workspace\cpp-cmake-conan-base>rd /s /q build
The system cannot find the file specified.

c:\workspace\cpp-cmake-conan-base>conan install -if build .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    gtest/1.11.0 from 'conancenter' - Cache
    sdl/2.0.20 from 'conancenter' - Cache
Packages
    gtest/1.11.0:3f7b6d42d6c995a23d193db1f844ed23ae943226 - Cache
    sdl/2.0.20:d5963496fcfc7c5a7f3d13f39a26a3b3997af667 - Cache

Installing (downloading, building) binaries...
gtest/1.11.0: Already installed!
sdl/2.0.20: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo

c:\workspace\cpp-cmake-conan-base>cd build

c:\workspace\cpp-cmake-conan-base\build>cmake -DBUILD_TESTING=TRUE ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Component target declared 'SDL2::SDL2-static'
-- Conan: Component target declared 'SDL2::SDL2main'
-- Conan: Target declared 'sdl::sdl'
-- Conan: Component target declared 'GTest::gtest'
-- Conan: Component target declared 'GTest::gtest_main'
-- Conan: Component target declared 'GTest::gmock'
-- Conan: Component target declared 'GTest::gmock_main'
-- Conan: Target declared 'gtest::gtest'
-- Configuring done
CMake Error at src/CMakeLists.txt:28 (target_link_libraries):
  Target "base" links to:

    SDL2::SDL2

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

c:\workspace\cpp-cmake-conan-base\build>cmake -DBUILD_TESTING=TRUE ..
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19044.
-- Conan: Component target declared 'SDL2::SDL2-static'
-- Conan: Component target declared 'SDL2::SDL2main'
-- Conan: Target declared 'sdl::sdl'
-- Conan: Component target declared 'GTest::gtest'
-- Conan: Component target declared 'GTest::gtest_main'
-- Conan: Component target declared 'GTest::gmock'
-- Conan: Component target declared 'GTest::gmock_main'
-- Conan: Target declared 'gtest::gtest'
-- Configuring done
-- Generating done
-- Build files have been written to: C:/workspace/cpp-cmake-conan-base/build

c:\workspace\cpp-cmake-conan-base\build>cmake --build .
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/workspace/cpp-cmake-conan-base/src/CMakeLists.txt
  application.cpp
C:\workspace\cpp-cmake-conan-base\src\application.cpp(3): fatal error C1083: Cannot open include file: 'SDL2/SDL.h': No
 such file or directory [C:\workspace\cpp-cmake-conan-base\build\src\base.vcxproj]
```

**Comment by ericLemanissier** [comment]
by default, sdl package is built as static library, which implies that the target is `SDL2::SDL2-static`: https://github.com/conan-io/conan-center-index/blob/master/recipes/sdl/all/conanfile.py#L375-L376

If you use option `sdl:shared=True`, you should have a target `SDL2::SDL2`

**Comment by codehavik** [comment]
> I've checked again, and now they provide a `SDL2::SDL2` alias target in static only build (since 2.0.18: [libsdl-org/SDL@407867c](https://github.com/libsdl-org/SDL/commit/407867cf7262a45952d095b9a22af14b22878df9)).
> 
> So I think we should always set `cmake_target_name` to `SDL2::SDL2`, and `cmake_target_aliases` to `["SDL2::SDL2-static"]` if static.

It actually makes sense, because you don't want to link BOTH static and DLL. Or am I missing something? Is it possible to link against SDL2main (in order to override main function in your executable) and SDL2 symbols as a DLL? In my scenario, I just define my own main function... I'm just thinking....

**Comment by SpaceIm** [comment]
SDL2main is always static, and it's a different target. You can perfectly link SDL2 shared and SDL2main (static), or SDL2 shared only, or SDL2 static and SDL2 main, or SDL2 static only. conan doesn't package both SDL2 static & shared.

**Comment by SpaceIm** [comment]
> I agree on that. I mean, it's not a good idea to mix linkage. You either link dynamically or statically.

What do you mean? All combinations of static/shared of your dependencies work in theory. FYI, prebuilt packages in conan-center of shared libs are built against their static dependencies.

**Comment by codehavik** [comment]
@SpaceIm Yes, it's not relevant here. SDL2main SHOULD be static by design, because DLL cannot replace main in your executable otherwise.

**Comment by SpaceIm** [comment]
Maybe your question was: to we package together static & shared flavors of the same lib? The answer if no. It's controlled by `shared` option, and only one flavor of a lib can exist in a dependency graph.

**Comment by SpaceIm** [comment]
I don't know, works fine for me. Please share a reproducible example (cpp file, conanfile, conan command, your CMakeLists etc, how you call CMake eventually).

**Comment by codehavik** [comment]
@SpaceIm Could you please look at this project? It's just a small c++ template project. Not big at all. https://github.com/codehavik/cpp-cmake-conan-base

**Comment by SpaceIm** [comment]
Where is `CMakeToolchain`? You should add this generator and pass `conan_toolchain.cmake` to `CMAKE_TOOLCHAIN_FILE` during cmake configuration.

**Comment by codehavik** [comment]
@SpaceIm Is it possible without toolchains?

**Comment by SpaceIm** [comment]
Sure, but you have at least to set some CMake variables at configuration time to make CMake config or module files discoverable (`CMAKE_PREFIX_PATH` & `CMAKE_MODULE_PATH`).

**Comment by codehavik** [comment]
Sorry but I could not get it working. The compiler don't see the SDL include directories. For some reason the find_package() don't set the include dir on the cmake target which is not good. I didn't try ${SDL2_INCLUDE_DIRS} and ${SDL2_LIBRARIES} , because modern Cmake expects us to work with targets. I read more on this and how I supposed to set up the project, but I don't have a clue now.

**Comment by SpaceIm** [comment]
Maybe you have another SDL2Config.cmake of another installation elsewhere which is found by find_package(), and as you should know, `#include <SDL2/SDL.h>` is not a valid in official SDL2 config file, it's `#include <SDL.h>`.

**Comment by SpaceIm** [comment]
Ok I think I understand, you have forgotten to set CMAKE_BUILD_TYPE while calling CMake configuration

**Comment by SpaceIm** [comment]
Actually it's an issue of conan 1.48.0 https://github.com/conan-io/conan/issues/11167

**Comment by codehavik** [comment]
@SpaceIm Yes, I have discussion on both ends. I think it is worth it and I can't wait to manage this stuff work :) For me, conan dependency manager seems the cleanest solution especially if I want to use cmake
