### ISSUE TITLE
[package] libjpeg/9c : shared windows builds should probably be marked invalid

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-center-index#1062]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: libjpeg/9c
  * Operating System+version: Windows All
  * Compiler+version: MSVC all

For a `shared=True` build with `msvc`, the `package` method reports the following (There is indeed no `.dll` file in the cache.) : 

### Logs (Include/Attach if Applicable)
```
libjpeg/9c: Calling package()
libjpeg/9c: package(): Packaged 4 '.h' files: jconfig.h, jerror.h, jmorecfg.h, jpeglib.h
libjpeg/9c: package(): Packaged 1 '.lib' file: libjpeg.lib
libjpeg/9c: package(): Packaged 1 file: README
```

It seems pretty clear from a little research that the upstream-provided build system of `libjpeg` does not natively support being compiled to a shared library on windows.  Traditionally, we use conditional logic in the `configure` method to mark these configurations as `invalid` and raise an exception.  The mystery here is: 

1.  Why didn't we do it the normal way (willing to believe there was a reason, or perhaps it predated this convention) .
2.  If it's a mistake or just old code, how has the situation existed for so long that nobody reported it?  It's mostly surprising because it's a dependency to many other packages, so those dependents should fail at runtime because of missing `libjpeg.dll`

Ping @theirix  because he made some relevant commits 2 years ago: 
https://github.com/bincrafters/conan-libjpeg/blame/testing/9c/conanfile.py#L99

**Comment by theirix** [comment]
I think I just forgot to throw an exception. There is no check in the `build.py` too. It should be added, of course.

**Comment by madebr** [comment]
current master has

https://github.com/conan-io/conan-center-index/blob/6a86b1c0264e6771af0cdd6ec309833020bb8b4e/recipes/libjpeg/all/conanfile.py#L25-L29

So isn't this already ok?

**Comment by madebr** [comment]
The library looks outdated. I'm working on it atm.

**Comment by solvingj** [comment]
Thank you!
