### ISSUE TITLE
[request] libcurl/7.83

### ISSUE THREAD

**Issue by jaelsasser** [conan-io/conan-center-index#10624]
### Package Details
  * Package Name/Version: **libcurl/7.83**
  * Changelog: **https://curl.se/changes.html#7_83_0**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by toge** [comment]
It is already merged (https://github.com/conan-io/conan-center-index/pull/10580).
Could you close this issue?
