### ISSUE TITLE
 [boost] Visual Studio 64-bit build uses 32-bit address-model

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#107]
moved from https://github.com/conan-community/community/issues/164, by @firewave 

### Description of Problem, Request, or Question

When build on Windows with a 64-bit Visual Studio compiler it will generate working 64-bit libraries, but somehow just use a 32-bit address-model:
```
    - default address-model    : 32-bit
    - default architecture     : x86
```

Using a compiler on Linux will show:
```
        - default address-model    : 64-bit
        - default architecture     : x86
```

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.69**
* Operating System: **Windows 10**
* Operation System Version: **Version 1809 (OS Build 17763.348)**
* Compiler+version: **MSVC 19.0.24215.1**
* Conan version: **conan 1.13.0**
* Python version: **python 3.6.4**

**Comment by perseoGI** [comment]
Greetings, I'm reviewing old issues. This is a real old one!
I'm closing it as conan 1 is on the road to deprecation, and that concrete version was released a really long time ago.
Also, boost minimum version now is `1.71.0`.

If this issue remains, do not hesitate to reopen it! 😄
