### ISSUE TITLE
[question] ffmpeg configure codecs, muxers, etc.

### ISSUE THREAD

**Issue by simoncent** [conan-io/conan-center-index#10700]
Hey,

This isn't a question as such, but it's not really a bug either!

The ffmpeg recipe doesn't currently allow you to explicitly configure the codecs etc. that are included in the build. To replace my manual build I need to be able to restrict what's included.

ffmpeg  supports a large number different codecs, containers, etc. and trying to provide a comprehensive list and maintain parity when new ones are added etc. doesn't seem like it would scale and would add a maintenance burden. 

I'd like to put in a PR to allow these to be configured in some way, and in light of the above, I propose that boolean options for "disable everything" type flags be added, for example `--disable-everything` or `--disable-encoders`, along with free-form options for flags which take a value such as `--enable-encoder=`, it would be left to the autotools build system to complain about any incorrect values passed for these free-form options.  e.g.
```
options = {
# existing options ...
"disable-everything": [True, False],
"disable-encoders": [True, False],
"disable-decoders": [True, False],
"enable-encoder": "ANY",
"enable-decoder": "ANY",
"enable-muxer": "ANY",
"enable-demuxer":, "ANY",
}
```

This would then allow you enable / disable specific codecs by name or create a minimalist build, for example to avoid licencing/patent issues and only allow MP3 decoding:
```
[options]
ffmpeg:disable-everything=True
ffmpeg:enable-decoder="mp3"
ffmpeg:enable-decoder="opus"
ffmpeg:enable-demuxer="mp3"
ffmpeg:enable-demuxer="ogg"
``` 

Another option would be to instead allow a list of codecs etc. to be passed into the recipe, which would reduce the length of the options list in conanfiles, but at the expense of extra parsing logic in the recipe and potentially very long conanfile option lines. Given the trade off I think I'm leaning towards the above example rather than the one below, but I don't feel strongly about this if more people prefer the list approach.
```
[options]
ffmpeg:disable-everything=True
ffmpeg:enable-decoders="mp3, mp3float, opus"
ffmpeg:enable-demuxer="mp3, ogg"
```

Adding this functionality might also be useful for other purposes, such as mentioned in https://github.com/conan-io/conan-center-index/issues/10571, e.g:
```
[options]
ffmpeg:disable-decoders=True
ffmpeg:disable-demuxers=True
# etc
``` 

I'd like to start working on a PR for this, I'm just looking for some feedback on how to add it to the recipe, is this approach sensible or would another approach be preferred? Individual `enable-thing` options or `enable-things` lists? Any other suggestions?

Thanks for reading!

**Comment by uilianries** [comment]
It's a fair point. As ffmpeg is big and can accept many different codecs, I agree that is does not scale and a generic option could help with it. We would need to a set a default value with a minimal support, otherwise we would distribute an useless package.

As more contributors already helped with ffmpeg recipe, I'm pinging them here @SpaceIm @madebr @SSE4 @MartinDelille to give their thoughts.

**Comment by paulharris** [comment]
Can you even do this:
```
"enable-encoder": "ogg",
"enable-encoder": "opus",
```
Isn't that a set / dict, ie the keys have to be unique?

I normally see features listed like so:
```
"enable-ogg": True,
"enable-opus": True
```

There might be an array of encoders, ie ['ogg','opus']
and a loop to add them into the options {} and default_options {},
like... for each, options.append( "enable-" + name )   etc etc

**Comment by SSE4** [comment]
I think it's related to #10571
in general, I am not opposed to make recipes more configurable - contributions are always welcomed.
`ffmpeg` has literally hundreeds of possible encoders, decoders, filters to turn on/off one-by-one.
there are several ways on how it could be implemented.

1. allow arbitrary configure flags to be passed. the same way we did it in [boost](https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py#L94), for instance.
so, something like that may do the trick:
```
# option
"extra_configure_flags": "ANY",  # custom configure flags
...
# default 
"extra_configure_flags": "None",
..
# apply
        if self.options.extra_configure_flags:
            args.extend(shlex.split(str(self.options.extra_configure_flags)))
```
and then use it like:
```
ffmpeg:extra_configure_flags=--disable-everything --disable-encoders=mp3
```
2. something more specific, e.g. as in your previous example:
```
ffmpeg:disable-everything=True
ffmpeg:enable-decoders="mp3, mp3float, opus"
ffmpeg:enable-demuxer="mp3, ogg"
```
3. add fine-grained options for each decoder/encoder/filter/etc:
```
enable_mp3_decoder: [True, False],
enable_ogg_decoder: [True, False], 
```
might be very tedious to maintain. most likely, these options have to be generated programmatically. they also will be different for each release of ffmpeg.

**Comment by simoncent** [comment]
> Isn't that a set / dict, ie the keys have to be unique?

Ahh yes, good point, at the Conan level I think you are right, so they would need to be lists like
`ffmpeg:enable-decoders="mp3, mp3float, opus"`, that would work.

>There might be an array of encoders, ie ['ogg','opus']
and a loop to add them into the options {} and default_options {},
like... for each, options.append( "enable-" + name ) etc etc

I think there are just too many supported options to make this approach maintainable tbh.

>allow arbitrary configure flags to be passed. the same way we did it in [boost](https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py#L94), for instance.
so, something like that may do the trick:

I think this is potentially more complicated than more specific list based options because allowing any flag at all to be passed could conflict with other options provided by the recipe and also any flags the recipe silently passes, for example where the `gpl` flag is disabled when `with_libx264` is set. 

The recipe might then need to try and filter out these conflicting flags and any flags for which the recipe provides explicit options, it feels like it could become a bit of a headache.

So far I think the specific list options for each type of ffmpeg flag is probably the best compromise, it avoids issues with conflicting flags / options as I mentioned above by restricting where we pass free-form user input to the ffmpeg build system directly, but is not so fine-grained that it would be difficult to maintain between ffmpeg versions because we're leaving the ffmpeg build system responsible for validating the specific encoders etc. that are supported. e.g.
```
ffmpeg:disable-everything=True
ffmpeg:enable-decoders="mp3, mp3float, opus"
ffmpeg:enable-demuxer="mp3, ogg"
```
