### ISSUE TITLE
[package] qt/6.2.4: Does not define QT_DEFAULT_MAJOR_VERSION

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#10720]
* "versionless cmake functions" include qt_wrap_cpp() and qt_wrap_ui(), they are recommended for use instead of qt6_wrap_cpp() simply to help people switch between major versions easily.
* These functions are defined in lib/cmake/Qt6Widgets/Qt6WidgetsMacros.cmake
* They are dispatching functions, and will call qt5_wrap_ui or qt6_wrap_ui depending on the value of QT_DEFAULT_MAJOR_VERSION
* QT_DEFAULT_MAJOR_VERSION is defined in lib/cmake/Qt6Core/Qt6CoreConfigExtras.cmake
* This "extras" cmake file is never loaded with conan's set of generated cmake files, so QT_DEFAULT_MAJOR_VERSION is left unset, and calls to qt_wrap_cpp() will execute nothing (would've been nice to have an error message, that is due to QT's implementation).

The situation for the standard QT (looking at 
* There COULD BE "extras" cmake files for each of the modules (Core, Widgets, ...), I see there is one for "Qt6" and "Qt6Core", but not Qt6Widgets.  I haven't checked the others.
* These "extras" cmake files are loaded (if they exist) through lib/cmake/Qt6/QtModuleHelpers.cmake.

I'm now wondering how we should deal with this,
and what other things we need to duplicate from QT's standard cmake files.
There is a LOT of stuff in QT's cmake files, are we missing something important?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.2.4**
  * Conan version: **conan 1.48.0**

**Comment by mjvankampen** [comment]
I ran into the same issue for 6.3.0 
![image](https://user-images.githubusercontent.com/29380294/169021225-2b209f81-5cb4-41ad-9161-1315f5c1a576.png)

**Comment by ericLemanissier** [comment]
can you please try with https://github.com/conan-io/conan-center-index/pull/10862 ?

**Comment by paulharris** [comment]
> can you please try with #10862 ?

checking ...

**Comment by paulharris** [comment]
@ericLemanissier could I please get some attention on this issue:
https://github.com/conan-io/conan-center-index/issues/10709

It is blocking/obscuring my other QT issues, like this one.

**Comment by paulharris** [comment]
#10862 appears to solve this problem :)
