### ISSUE TITLE
[request] qwt/6.2.0 update so it can require qt/(5 or 6)

### ISSUE THREAD

**Issue by ashley-b** [conan-io/conan-center-index#10744]
### Package Details
  * Package Name/Version: **qwt/6.2.0**
  * Changelog: **https://qwt.sourceforge.io/qwtchangelog.html**

This recipe has been updated to qwt/6.2.0, but it's fixed to qt/5.15.2.
As mentioned in the qwt change log (What's new in Qwt 6.2), it can now be built against qt 5 or 6.

Can the recipe be updated to have the required qt version as a option

**Comment by SpaceIm** [comment]
Why an option? You can override transitive dependencies.
