### ISSUE TITLE
[request] libharu/2.4.0 - tricky problem due to many forks

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#10764]
This is a tricky one, but I thought it should be noted in CCI somewhere:

libharu 2.3.0 is very old now (2015).
It is unmaintained.
There are many forks on github.

VTK bundled its own version by pulling in some of those forks, and renumbered it 2.4.0,
but it still does not include many patches scattered on github.

It might be better to bring in one of the forks, perhaps even VTK's, or maybe Debian has a patched version...
but I don't know enough about libharu to help there.

The reality is the version that CCI has chosen may be more buggy than other available and commonly used libharu versions.
CCI should probably pin themselves to another version that is used by many people, so it is at least tested and used in recent times.

**Comment by Nekto89** [comment]
I've noticed that project has new maintainer now and there are new versions available on GH
https://github.com/libharu/libharu/releases/tag/v2.4.3

**Comment by paulharris** [comment]
Awesome, thank you for that !

**Comment by paulharris** [comment]
Recipe coming ... #13990
