### ISSUE TITLE
conandata.yml format documentation - quotes

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#10773]
https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#kb-h030-conandatayml-format

The example has "" quotes around a lot of things.
When the CCI linters are enabled, the CONANDATA.YML REDUCE (KB-H031) has no quotes around items.

If the REDUCE thinks there should not be quotes, then please adjust example so there are no quotes.

Or, does yaml _sometimes_ need quotes?   I do recall there was some horrible bug related to numbers or months.

**Comment by paulharris** [comment]
I'll tack this one on as well, there are already so many bug reports...

https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#kb-h030-conandatayml-format

Surely "bin/test" should be os.path.join("bin", "test") ?

# test_package/conanfile.py
class TestConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"

    def test(self):
        self.run("bin/test", run_environment=True)

**Comment by uilianries** [comment]
> Or, does yaml sometimes need quotes? I do recall there was some horrible bug related to numbers or months.

It needs quotes, it should be mandatory actually. YAML parser is limited and may break if is not string. We had incidents in the past, that's why enforce string.

**Comment by paulharris** [comment]
Ok well then I'd suggest putting back the "bug" tag and adding a linter,
because I got rid of the quotes and the hooks are perfectly happy with the sitation.

oh, is there some kind of update I have to do to the hooks from time to time?
I installed that at some point, but I know you are making continuous improvements to them.
They update along with conan releases?

**Comment by uilianries** [comment]
Again, those quotes are required for version, it's not a bug, the example is correct. That "example" it's part of base that was created to give more details about each hook. That hook, in specific, was created to validate the conandata.yml format (you can see the original PR [here](https://github.com/conan-io/hooks/pull/109)). The problem related to quotes is when a key is number, but next version is alphabetical, then the yaml parser is not able to handle it and throws an error. That hook does not affect it, it's one step later.  

Hooks is updated independent from Conan releases. You can use `config_install_interval` associated to `conan config install` to automate a periodic update. https://docs.conan.io/en/latest/reference/commands/consumer/config.html

**Comment by paulharris** [comment]
RE the hook update, would be good to have the hook check to see how old it is, and give a little warning to tell the poor CCI recipe writer they should manually update, or set up the auto update.

I don't know about other people, but there has been a lot to learn in a short period, so the more help and checks you can throw in, the better!

re the version-is-a-number, I tried to make it break.
I did try with two versions in one file: 1.30 and then 1.28.1b but conan create . 1.28.1b@ worked.  Oh well.

Thanks for the response and tips!
