### ISSUE TITLE
[package] zlib/1.2.12: wrong library name in cpp_info.libs on non-Unix/Windows

### ISSUE THREAD

**Issue by AlexRamallo** [conan-io/conan-center-index#10770]
The zlib package only works for Linux, Windows, Mac, and other Unixes. Other OSes produce invalid link info.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.12** and **zlib/1.2.11** were tested

### Steps to reproduce (Include if Applicable)

```
conan install "zlib/1.2.12@" -s os=baremetal --build

```
This will produce a library file called "libzlibstatic.a", yet the recipe will write `self.cpp_info.libs = ['z']`, which obviously won't work at link time. (should be `self.cpp_info.libs=['zlibstatic']`)

The zlib CMake script produces `libz.so/a` if the system is a Unix, however for everything else it will use the name above.

Relevant snippet from zlib's CMakeLists.txt:

```

if(UNIX)
    # On unix-like platforms the library is almost always called libz
   set_target_properties(zlib zlibstatic PROPERTIES OUTPUT_NAME z)
   if(NOT APPLE)
     set_target_properties(zlib PROPERTIES LINK_FLAGS "-Wl,--version-script,\"${CMAKE_CURRENT_SOURCE_DIR}/zlib.map\"")
   endif()
elseif(BUILD_SHARED_LIBS AND WIN32)
    # Creates zlib1.dll when building shared library version
    set_target_properties(zlib PROPERTIES SUFFIX "1.dll")
endif()
```

</details>

**Comment by SpaceIm** [comment]
Is it better with https://github.com/conan-io/conan-center-index/pull/10771?

**Comment by AlexRamallo** [comment]
Yup! That fixes the issue on my end.
