### ISSUE TITLE
[conan.io/center] Markdown failed `paho-mqtt-cpp/1.2.0@#8d592f43416b65a8aed8af5e1c058fc9`

### ISSUE THREAD

**Issue by jonas-w** [conan-io/conan-center-index#10785]
https://conan.io/center/paho-mqtt-cpp?version=1.2.0&tab=recipe
Opening this url yields this error

**Comment by jgsogo** [comment]
fixed https://conan.io/center/paho-mqtt-cpp?tab=useit
