### ISSUE TITLE
[package] libtiff/4.3.0: local conan create fails with cmake configuration error

### ISSUE THREAD

**Issue by rfn123** [conan-io/conan-center-index#10811]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libtiff/4.3.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 7**
  * Docker image: 
  * Conan version: **conan 1.46.2**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch.march=None
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
`conan create recipes/libtiff/all/conanfile.py 4.3.0@`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
-- Conan: Using autogenerated Findjbig.cmake
-- Found jbig: 20160605 (found version "20160605") 
-- Library jbig found /home/usr/.conan/data/jbig/20160605/_/_/package/d8fff784e71b40316e752103c83b4698d094b5e3/lib/libjbig.a
-- Found: /home/usr/.conan/data/jbig/20160605/_/_/package/d8fff784e71b40316e752103c83b4698d094b5e3/lib/libjbig.a
CMake Error at source_subfolder/cmake/FindJBIG.cmake:4 (target_link_libraries):
  Cannot specify link libraries for target "JBIG::JBIG" which is not built by
  this project.
Call Stack (most recent call first):
  source_subfolder/cmake/JBIGCodec.cmake:30 (find_package)
  source_subfolder/CMakeLists.txt:101 (include)


-- Configuring incomplete, errors occurred!
See also "/home/usr/.conan/data/libtiff/4.3.0/_/_/build/8311e1632d035c91234ae06c2588dd1f1f1da4e6/build_subfolder/CMakeFiles/CMakeOutput.log".
See also "/home/usr/.conan/data/libtiff/4.3.0/_/_/build/8311e1632d035c91234ae06c2588dd1f1f1da4e6/build_subfolder/CMakeFiles/CMakeError.log".
libtiff/4.3.0: 
libtiff/4.3.0: ERROR: Package '8311e1632d035c91234ae06c2588dd1f1f1da4e6' build failed
libtiff/4.3.0: WARN: Build folder /home/usr/.conan/data/libtiff/4.3.0/_/_/build/8311e1632d035c91234ae06c2588dd1f1f1da4e6
ERROR: libtiff/4.3.0: Error in build() method, line 181
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 176
	self._cmake.configure(build_folder=self._build_subfolder)
	ConanException: Error 1 while executing cd '/home/usr/.conan/data/libtiff/4.3.0/_/_/build/8311e1632d035c91234ae06c2588dd1f1f1da4e6/build_subfolder' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="7" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++11" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/home/usr/.conan/data/libtiff/4.3.0/_/_/package/8311e1632d035c91234ae06c2588dd1f1f1da4e6" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_MODULE_PATH="/home/usr/.conan/data/libtiff/4.3.0/_/_/build/8311e1632d035c91234ae06c2588dd1f1f1da4e6" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -Dlzma="True" -Djpeg="True" -Djbig="True" -Dzlib="True" -Dlibdeflate="True" -Dzstd="True" -Dwebp="True" -Dcxx="True" -Wno-dev '/home/usr/.conan/data/libtiff/4.3.0/_/_/build/8311e1632d035c91234ae06c2588dd1f1f1da4e6'

```

</details>

**Comment by ggulgulia** [comment]
Just adding some information (might be already obvious): the error appears from the recipe `build/8311e1632d035c91234ae06c2588dd1f1f1da4e6/source_subfolder/FindJBIG.cmake` file after the patch is applied. 

Also I'm curiousabout the purpose of including file `ConanFind<pkg-name>.cmake` @madebr

**Comment by madebr** [comment]
I just tried building libtiff using gcc11@Linux using master's recipes and got no error,
so first please make sure you're using the most recent version of all recipes (libtiff + dependencies).

The reason I'm doing this crazy sh*t is because of Windows (see the comments in the libtiff recipe:
https://github.com/conan-io/conan-center-index/blob/77d13649eb548d7b4331abbbe9f9ce18d97e9c55/recipes/libtiff/all/conanfile.py#L122

On Windows, `find_package(JBIG)` will also match `Findjbig.cmake` which creates a target `jbig::jbig`, where we expect it to create `JBIG::JBIG`.
By patching `FindJBIG.cmake` to include the conan generated one, everything should work out fine.

If updating the recipes still don't help, add `args=["--trace"]` to the cmake configure command in the libtiff recipe and post the log somewhere for us to review.

**Comment by madebr** [comment]
Thanks for the log, I think https://github.com/conan-io/conan-center-index/pull/10820 will fix your problem.

**Comment by rfn123** [comment]
There is a new error popping up now after the PR when building :see_no_evil: @madebr 

``` 
You have called ADD_LIBRARY for library tiffxx without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at source_subfolder/libtiff/CMakeLists.txt:192 (add_executable):
  add_executable called with incorrect number of arguments


CMake Error at source_subfolder/libtiff/CMakeLists.txt:193 (target_sources):
  Cannot specify sources for target "mkg3states" which is not built by this
  project.


CMake Error at source_subfolder/libtiff/CMakeLists.txt:194 (target_link_libraries):
  Cannot specify link libraries for target "mkg3states" which is not built by
  this project.


-- Configuring incomplete, errors occurred!
```

**Comment by madebr** [comment]
Can you re-add the `--trace` as I asked in https://github.com/conan-io/conan-center-index/issues/10811#issuecomment-1127471357?
The log was super helpful.

**Comment by rfn123** [comment]
Here is the log
[cci-libtiff-4.3.0-log_after_pr.10820.txt](https://github.com/conan-io/conan-center-index/files/8716298/cci-libtiff-4.3.0-log_after_pr.10820.txt)
