### ISSUE TITLE
[cryptopp] cryptopp/8.2.0: missing PEM Pack

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan-center-index#10812]
The PEM pack allow you to read and write keys and parameters in PEM format.  
It is not part of the cryptopp github repo but can be found here: https://github.com/noloader/cryptopp-pem  
"To compile the source files drop them in your cryptopp directory and run make. The makefile will automatically pick them up. ".  
See also https://www.cryptopp.com/wiki/PEM_Pack.

**Comment by SpaceIm** [comment]
If it's not in official cryptopp archive, it shouldn't be part of cryptopp recipe.

**Comment by fdgStilla** [comment]
The conan recipe is already using https://github.com/noloader/cryptopp-cmake/ which is not part of the cryptopp archive either (cryptopp-cmake and cryptopp-pem are from the same author).

Both of those repos are documented in the official cryptopp wiki:
- https://www.cryptopp.com/wiki/PEM_Pack
- https://www.cryptopp.com/wiki/CMake

**Comment by SpaceIm** [comment]
Cryptopp-cmake is just a build system file. It doesn't change binaries.
