### ISSUE TITLE
[package] freeimage/3.18.0: Options not handled in the code

### ISSUE THREAD

**Issue by baptisteesteban** [conan-io/conan-center-index#10842]
Two options of the Conan recipe of freeimage are not handled correctly when they are set to `False`. These options are:
* `with_jpeg2000`
* `with_openexr`

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **freeimage/3.18.0**
  * Operating System+version: **Debian 11 (Bullseye)**
  * Compiler+version: **GCC 10**
  * Conan version: **conan 1.48.0**
  * Python version: **Python 3.9.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
compiler.cppstd=20
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

* Create the following `conanfile.txt`:

```
[generators]
CMakeDeps
CMakeToolchain

[requires]
freeimage/3.18.0

[options]
freeimage:with_openexr=False # or freeimage:with_jpeg2000=False
```

* In the shell:

```
$ conan install conanfile.txt --build missing
```

### Logs (Include/Attach if Applicable)

* In the case of `freeimage:with_jpeg2000=False`:

<details><summary>Click to expand log</summary>

```
[...]
[...]/.conan/data/freeimage/3.18.0/_/_/build/9457b87cfdb33ce967eb5c5053e4e6db0f5956c5/source_subfolder/Source/FreeImage/J2KHelper.cpp:24:10: fatal error: openjpeg.h: Aucun fichier ou dossier de ce type
   24 | #include <openjpeg.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

</details>

* In the case of `freeimage:with_openexr=False`:

<details><summary>Click to expand log</summary>

```
[...]
[...]/.conan/data/freeimage/3.18.0/_/_/build/1c3c84d1a9784862feff32ebc6c9a4a8c2c4dccc/source_subfolder/Source/FreeImage/PluginTIFF.cpp:42:10: fatal error: OpenEXR/half.h: Aucun fichier ou dossier de ce type
   42 | #include <OpenEXR/half.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

</details>

**Comment by toge** [comment]
Thank you for bug report. 
I have created PR to solve it.
Please wait a bit until it is MERGED.

Unfortunately, part of openexr is used by freeimage's tiff plugin.
So if you set openexr to false, you must also set tiff to false.
