### ISSUE TITLE
[question] Package naming

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#109]
Hi!

When submitting a new PR, adding a new package, some of them could contain multiple words and as separator we have some options: `-`, `_`

As users can deduce the package name when searching, probably anyone would prefer a pattern for cases where a separator is required, so we can deduce easily the correct package name.

However, Conan Center Index has both separators included:
- expected-lite
- libjpeg-turbo
- ms-gsl
- optional-lite
- xz_utils

Famous packages like Boost modules use `_`.

We could create a new rule for new packages, where the hook is able to check the package name, also as CCI is just on the beginning, so I think we can rename some packages to follow the same pattern.

But first, we need to vote for a specific separator.

/cc @Croydon

**Comment by danimtb** [comment]
I'd try to stick to the original name as much as possible. For example `libjpeg-turbo` and `expected-lite` and `optional-lite` have the `-` in their names.

In the case of spaces in the name ` `, I'd rather go for the `_` as correctly done in `xz_utils`.

Finally, in the case for disambiguation, I'd use common sense as said in #21. Also if you look for `ms-gsl` on google, you get the right result in the first position. If you write `ms_gsl` you get nothing 😄

**Comment by danimtb** [comment]
If we agree on this, I could add this to the FAQ question about naming and close the issue. Thanks!

**Comment by Minimonium** [comment]
Having a unified style would hurt the discoverability, indeed.

**Comment by danimtb** [comment]
I have added a new section in the FAQ and updated the existing one with the GSL example: https://github.com/conan-io/conan-center-index/wiki/FAQ

Thanks for the feedback!
