### ISSUE TITLE
[request] libcurl: Expose control to --with_ca_bundle and --with_ca_path option

### ISSUE THREAD

**Issue by chenpengfei** [conan-io/conan-center-index#10919]
We needed a way to expose control of the --with_ca_bundle and --with_ca_path libcurl option to the users of this recipe. 

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x]  I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

**Comment by prince-chrismc** [comment]
This was done by OP in #10922
