### ISSUE TITLE
[question] Library with no license

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#1092]
Hi, I'm creating a recipe for [easylzma](https://github.com/lloyd/easylzma) which has no license file. The `readme` says that is Public Domain, so that's what I put on the `license` field of the recipe.
The issue lays on the conan-center hook, it marks as an error the fact that I'm not including a license file on the package. Should I export that readme as license or maybe create a file that says this library is public domain or something like that?

Thanks.

**Comment by ericriff** [comment]
Maybe a file with this extract from the readme?

> License

All the cruft you find here is public domain.  You don't have to credit
anyone to use this code, but my personal request is that you mention
Igor Pavlov for his hard, high quality work.

**Comment by Croydon** [comment]
Copying over these few lines should be fine IMHO
