### ISSUE TITLE
[request] cairomm 1.16

### ISSUE THREAD

**Issue by PaulCombal** [conan-io/conan-center-index#10936]
### Package Details
  * Package Name/Version: **cairomm 1.16**
  * Website: **https://www.cairographics.org/cairomm/**
  * Source code: **git://git.cairographics.org/git/cairomm**

### Description Of The Library / Tool

cairomm is a C++ wrapper for the [cairo graphics library](http://cairographics.org/). It offers all the power of cairo with an interface familiar to C++ developers, including use of the Standard Template Library where it makes sense.

----------

Referrences #7279

**Comment by hesham-essam** [comment]
Already has a pull request here https://github.com/conan-io/conan-center-index/pull/10673
Just waiting for it to be approved and merged.

**Comment by PaulCombal** [comment]
My bad, I must have overlooked it since it misses the tag thing 😬

I'll follow yours instead!
