### ISSUE TITLE
[package] sdl_image/2.0.5: Problems when build with bitcode for iOS

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan-center-index#10961]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl_image/2.0.5**
  * Operating System+version: **macos**
  * Compiler+version: **clang 13**
  * Docker image: **n/a**
  * Conan version: **conan 1.48.1**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration (profile_host):
[settings]
arch=armv7
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=iOS
os.version=9.0
os_build=Macos
[options]
nativium_arch=armv7
nativium_group=ios
nativium_product_name=Nativium
nativium_project_name=nativium
nativium_target=ios
nativium_version=1.0.0
nativium_version_code=1
[build_requires]
[env]
[conf]
tools.apple:enable_bitcode=True

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=[13](https://github.com/nativium/nativium-game/runs/6616402139?check_suite_focus=true#step:14:14)
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

https://github.com/nativium/nativium-game/runs/6616402139?check_suite_focus=true#step:15:215

Build `sdl_image` and `application` with `tools.apple:enable_bitcode=True`.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ld: '/Users/runner/.conan/data/sdl_image/2.0.5/_/_/package/2980311f97390015aa03a7ab8f6cc883cd94240b/lib/libSDL2_image.a(IMG.c.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

</details>

**Comment by SpaceIm** [comment]
> Build `sdl_image` and application with `tools.apple:enable_bitcode=True`.

Is it supposed to ever work with conan v1 recipes? Is it better with https://github.com/conan-io/conan-center-index/pull/12525?
