### ISSUE TITLE
[conan.io/center] Markdown failed `cvplot/1.2.2@#92d27040830ab40fef65706fd24af076`

### ISSUE THREAD

**Issue by Jihadist** [conan-io/conan-center-index#11008]
Markdown failed `cvplot/1.2.2@#92d27040830ab40fef65706fd24af076`

Also recipe generates wrong markdown 

```cmake
cmake_minimum_required(VERSION 3.15)
project(cvplot_project C)

find_package(cvplot)

add_executable(${PROJECT_NAME} src/main.c)

# Use the global target
target_link_libraries(${PROJECT_NAME} cvplot::cvplot)
```

But it's wrong cmake package name:

```
-- Conan: Using autogenerated FindCvPlot.cmake
CMake Warning (dev) at C:/Qt/Tools/CMake_64/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (CvPlot)
  does not match the name of the calling package (cvplot).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
```

I think it should CvPlot be as in the recipe (
https://github.com/conan-io/conan-center-index/blob/master/recipes/cvplot/all/conanfile.py#L34) and in the upstream (https://github.com/Profactor/cv-plot/blob/master/CvPlot/CMakeLists.txt#L5)
So recipe should generate
```cmake
cmake_minimum_required(VERSION 3.15)
project(cvplot_project C)

find_package(CvPlot )

add_executable(${PROJECT_NAME} src/main.c)

# Use the global target
target_link_libraries(${PROJECT_NAME} CvPlot::CvPlot )
```

**Comment by jgsogo** [comment]
We are working on a new implementation of the web that will regenerate all these files.

If the generated content doesn't match what is written in the recipe, then it is an error in the Conan client. Please, check and report there.
