### ISSUE TITLE
[package] pybind11/2.6.0: Not possible to cross compile

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan-center-index#11029]
Pybind11 cannot be cross compiled.

It takes the running python interpreter:
https://github.com/conan-io/conan-center-index/blob/master/recipes/pybind11/all/test_package/conanfile.py#L13
Which is of course not the correct one, when creating python bindings.

Any idea how to fix this?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **pybind11/2.6.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 9**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.46.0**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
gcc-9.0-mbient-armv8-release
```
[settings]
os=Linux
os.distro=mbient
arch=armv8
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

gcc-9.0-mbient-x86_x64-release
```
[settings]
os=Linux
os.distro=mydistro
arch=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
[ 50%] Building CXX object CMakeFiles/test_package.dir/test_package.cpp.o
[100%] Linking CXX shared module lib/test_package.cpython-38-x86_64-linux-gnu.so
/home/user/.conan/data/image-yocto-toolchain/1.2.0/company/stable/package/81fa1890dbdee4cb853676beed0cb00b7a564170/sdk/sysroots/x86_64-imagesdk-linux/usr/libexec/aarch64-image-linux/gcc/aarch64-image-linux/9.3.0/real-ld: /opt/pyenv/versions/3.8.10/lib/libpython3.8.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/test_package.dir/build.make:104: recipe for target 'lib/test_package.cpython-38-x86_64-linux-gnu.so' failed
make[2]: *** [lib/test_package.cpython-38-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/test_package.dir/all' failed
make[1]: *** [CMakeFiles/test_package.dir/all] Error 2
Makefile:114: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: pybind11/2.6.2 (test package): Error in build() me
```

</details>

**Comment by derived-coder** [comment]
I modified the original conan recipe of pybind and provided the cross compiled python to it, which also fails:

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
-- Found PythonInterp: /home/user/.conan/data/image-yocto-toolchain/1.2.0/company/stable/package/81fa1890dbdee4cb853676beed0cb00b7a564170/sdk/sysroots/aarch64-image-linux/usr/bin/python3  
CMake Error at /home/user/.conan/data/pybind11/2.6.2/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/pybind11/FindPythonLibsNew.cmake:133 (message):
  Python config failure:

  
  /home/user/.conan/data/image-yocto-toolchain/1.2.0/company/stable/package/81fa1890dbdee4cb853676beed0cb00b7a564170/sdk/sysroots/aarch64-image-linux/usr/bin/python3:
  1:
  /home/user/.conan/data/image-yocto-toolchain/1.2.0/company/stable/package/81fa1890dbdee4cb853676beed0cb00b7a564170/sdk/sysroots/aarch64-image-linux/usr/bin/python3:
  ELF�@@8: not found

  
  /home/user/.conan/data/image-yocto-toolchain/1.2.0/company/stable/package/81fa1890dbdee4cb853676beed0cb00b7a564170/sdk/sysroots/aarch64-image-linux/usr/bin/python3:
  2:
  /home/user/.conan/data/image-yocto-toolchain/1.2.0/company/stable/package/81fa1890dbdee4cb853676beed0cb00b7a564170/sdk/sysroots/aarch64-image-linux/usr/bin/python3:
  �: not found

  
  /home/user/.conan/data/image-yocto-toolchain/1.2.0/company/stable/package/81fa1890dbdee4cb853676beed0cb00b7a564170/sdk/sysroots/aarch64-image-linux/usr/bin/python3:
  3:
```

</details>

Because this is how pybind11 find the python executable. They execute code with it.
My guess, this cannot work for cross compilation...

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `pybind11/2.6.0` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
