### ISSUE TITLE
[package] catch2/3.0.1: missing Catch.cmake, CatchAddTests.cmake

### ISSUE THREAD

**Issue by rbrich** [conan-io/conan-center-index#11112]
This bit of the 2.x.x recipe is missing in 3.x.x: https://github.com/conan-io/conan-center-index/blob/232a32d832f9754b81dde348e8fd8ded37ad404b/recipes/catch2/2.x.x/conanfile.py#L96

It's used for test autodiscovery.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **catch2/3.0.1**
  * Operating System+version: **macOS 11.6.6**
  * Conan version: **conan 1.49.0**

### Steps to reproduce (Include if Applicable)

1. Check [Automatic test registration](https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#automatic-test-registration)
2. Try to `include(Catch)` and call `catch_discover_tests` in CMakeLists.txt

```
CMake Error at tests/CMakeLists.txt:5 (include):
  include could not find requested file:

    Catch


CMake Error at tests/CMakeLists.txt:14 (catch_discover_tests):
  Unknown CMake command "catch_discover_tests".
```

This worked with previous versions, stopped working with 3.0.1.

**Comment by toge** [comment]
@rbrich 
Thank you for reporting.
I missed theses scripts are place in extras.
I create PR to install them.
Please wait for merged.

**Comment by wouterbeek** [comment]
```

**Comment by wouterbeek** [comment]
I see `FindCatch2.cmake` in my `Debug` directory.  This worked and works fine (`find_package(Catch2 3 REQUIRED)` step).

There are no other CMake files from the Catch2 project in my `Debug` directory.  I do see additional CMake files in `~/.conan/data/catch2/3.0.1/_/_/source/source_subfolder/extras`, but I cannot find a connection between the `Debug` directory and the Conan data directory somewhere.  Could this still be missing in the latest revision?

**Comment by rbrich** [comment]
@toge Thanks!

@wouterbeek Your reproducer actually works for me. (Only needed to change conanfile.py -> conanfile.txt)

In the generated `FindCatch2.cmake`, I see the path to Conan package is added to CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH, event the exact `lib/cmake/Catch2` subdirectory where the Catch.cmake file can be found (for `include(Catch)`. This is enough to make the include work. Maybe you have older version of Conan?

You can also try to add `cmake_paths` to `[generators]` and `include(${CMAKE_BINARY_DIR}/conan_paths.cmake)` to CMakeLists.txt, but the effect should be the same - adding the package to CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH.

**Comment by wouterbeek** [comment]
@rbrich Thank you for confirming that the problem must be on my end.  Indeed, after a `conan delete catch2` my MWE now works :-)
