### ISSUE TITLE
[service] PhysX: only one configuration displayed

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#1111]
Web UI reports only one available configuration (on Linux) even though others are available:
https://conan.io/center/physx/4.1.1/?user=_&channel=_

![image](https://user-images.githubusercontent.com/30052553/76687024-7ff57200-6620-11ea-8e4a-10b2b23c2487.png)

**Comment by danimtb** [comment]
We realized there were some missing entries in the ConanCenter database, so we will try to fix them soon. Thanks for reporting

**Comment by solvingj** [comment]
Fixed

![image](https://user-images.githubusercontent.com/8557737/79752152-d4f06c00-82e1-11ea-9396-6443bbce87af.png)

@SpaceIm do you approve of ticket closure?

**Comment by SpaceIm** [comment]
Sure, thanks👍
