### ISSUE TITLE
[center.conan.io] Website claims that libtool is only available for Windows

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#1113]
[https://conan.io/center/libtool/2.4.6/?user=_&channel=_](https://conan.io/center/libtool/2.4.6/?user=_&channel=_)

while
`conan search libtool/2.4.6@ -r conan-center --table file.html` shows that it is available for Linux/macOS/Windows

![Screenshot_20200313_145042](https://user-images.githubusercontent.com/1593194/76626823-287cd680-653a-11ea-86f2-b7b3df36a0ca.png)

**Comment by danimtb** [comment]
Same as #1111

**Comment by solvingj** [comment]
Fixed

![image](https://user-images.githubusercontent.com/8557737/79752321-1e40bb80-82e2-11ea-9a59-7c695d56f363.png)

@Croydon do you approve of ticket closure?

**Comment by Croydon** [comment]
When clicking on one of those available configurations it just says `no data` 🤔

**Comment by solvingj** [comment]
I see.  There seems to be a bug in the UI.  Please choose the dropdown for "OS" and change it to "Any" and you will see all three.  I will file a bug with the UI team.

**Comment by Croydon** [comment]
This seems to be fixed now 👍
