### ISSUE TITLE
[conan.io/center] Markdown failed `qt/6.3.0@#67d45f5425575521592e68cf091d1c27`

### ISSUE THREAD

**Issue by nowgain-nowpain** [conan-io/conan-center-index#11168]
select the qt package, then switch to "use it" tab, i got the following message:

_> 
> Markdown generator failed for reference qt/6.3.0@#67d45f5425575521592e68cf091d1c27.
> command line: conan install qt/6.3.0@#67d45f5425575521592e68cf091d1c27 -g markdown --remote conancenter.
> profile:
> 
> include(default)
> [settings]
> arch=x86_64
> build_type=Debug
> compiler=gcc
> compiler.libcxx=libstdc++11
> compiler.version=10
> os=Linux
> Please report here._

**Comment by jgsogo** [comment]
we are working on a new implementation of the web that will regenerate all these files
