### ISSUE TITLE
[request] hdf5/5.12.2

### ISSUE THREAD

**Issue by agom** [conan-io/conan-center-index#11163]
### Package Details
  * Package Name/Version: **cmake/3.15.3**
  * Changelog: **https://portal.hdfgroup.org/display/HDF5/Software+Changes+from+Release+to+Release+for+HDF5-1.12**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by paulharris** [comment]
This issue can be closed now?
