### ISSUE TITLE
[package] libpciaccess/0.16: TypeError: __init__() got an unexpected keyword argument 'build_script_folder' with conan 1.49.0

### ISSUE THREAD

**Issue by tsondergaard** [conan-io/conan-center-index#11176]
### Package and Environment Details

* Package Name/Version: **libpciaccess/0.16**
* Operating System+version: **Fedora 34 x86_64**
* Compiler+version: **gcc 11.3.1**
* Conan version: **conan 1.49.0**
* Python version: **Python 3.9.13**

### Conan profile

```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce

Simply run `conan install libpciaccess/0.16@ --build` using conan 1.49.0.

Expected result:
libpciaccess/0.16 is successfully built and made available in conan cache.

Actual result:
Build fails with the following error:

```
libpciaccess/0.16: 
libpciaccess/0.16: ERROR: Package 'dfbe50feef7f3c6223a476cd5aeadb687084a646' build failed
libpciaccess/0.16: WARN: Build folder /home/ts/.conan/data/libpciaccess/0.16/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646
ERROR: libpciaccess/0.16: Error in build() method, line 66
	autotools = Autotools(self, build_script_folder=self._source_subfolder)
	TypeError: __init__() got an unexpected keyword argument 'build_script_folder'

```
The problem appears to be that the changes merged in #11021 which reverts the fix introduced for #10909 in #10910 hasn't been updated in the conan center. Possibly because it reverts to a previous version?

**Comment by uilianries** [comment]
Both Conan versions 1.49.0, 1.48.2 and 1.47.0 work fine with `build_script_folder`. Or, you are running an older version, or you are trying to use a cached and outdated recipe.

- Check your current version `python -m conans.conan --version` and be careful with multiple Conan versions installed in your machine.
- Update your local copy with `conan install <package_name> --update` (reference [here](https://docs.conan.io/en/latest/reference/commands/consumer/install.html))

**Comment by ericLemanissier** [comment]
the recipe we get on conan-center is not the one on conan-center-index. compare https://conan.io/center/libpciaccess?tab=configuration to https://github.com/conan-io/conan-center-index/blob/master/recipes/libpciaccess/all/conanfile.py

**Comment by uilianries** [comment]
@ericLemanissier the conan.io/center can not be used as parameter, because it uses a separated scheduled service to collect recipes from Conan Center and show there, it's delayed. I would say the best option is conan command against conancenter. 

Anyway, I gonna take a look on it. Thank you for reporting.

**Comment by ericLemanissier** [comment]
kmod and ruby have the same problem, after https://github.com/conan-io/conan-center-index/pull/11020 and https://github.com/conan-io/conan-center-index/pull/11019

**Comment by ericLemanissier** [comment]
I think the simplest solution is simply to add a newline somewhere in the recipe, to create a revision which is actually new

**Comment by uilianries** [comment]
Okay, I just opened 3 PRs, one for each package.
