### ISSUE TITLE
add flag to disable ctest (boost test_package)

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan-center-index#1118]
Please add option to disable ctest in https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/test_package/conanfile.py#L37

```bash
self.run('ctest --output-on-error -C %s' % bt, run_environment=True)
```

For example `without_ctest`:

```bash
        if not self.options["boost"].without_ctest:
            self.run('ctest --output-on-error -C %s' % bt, run_environment=True)
```

**Comment by SSE4** [comment]
@blockspacer is there any problem/error with running ctest?

**Comment by blockspacer** [comment]
> @blockspacer is there any problem/error with running ctest?

yes, conan package requires ctest installed in system

**Comment by uilianries** [comment]
I think adding cmake as build_requirement can solve it.

**Comment by danimtb** [comment]
I think this could be very annoying for those who don't have ctest installed and want to create the boost packages from sources. If there is a way to get rid of it and run the boost examples it will be much better.

Anyway, @blockspacer could you tell us more about your use case? Why are you executing the test_package?

**Comment by blockspacer** [comment]
@danimtb 

I'm trying to build boost with custom openssl version (and custom zlib cause it depends on openssl too) and options

You can find modified version here https://github.com/blockspacer/conan_boost 

I just copied recipe and changed `def requirements`

Maybe conan allows to override requirements somehow, but i can't find anything similar in docs

Thanks in advance

**Comment by danimtb** [comment]
Sure, you can always override requirements downstream. Take a look at https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#overriding-requirements

If you are using a copy of the boost library you can always modify the test package and remove the ctest part.

Anyway, if you override the requirements as explained above, I guess you wouldn't have to modify the boost recipe and you could issue a ``conan install conanfile.py --build`` to rebuild everything with the new dependencies. That way, the test package will not be executed (it is only executed in the ``conan create`` command) and you should avoid the issue

**Comment by blockspacer** [comment]
@danimtb 
Thanks, i'll try to override the requirements as explained above
My problem is solved, but there are suggestions above
`adding cmake as build_requirement can solve it.`
`If there is a way to get rid of it and run the boost examples it will be much better.`
so i'll keep issue open

**Comment by danimtb** [comment]
Sure, no problem. @SSE4 do you think we could improve that? Is that ctest line something we cannot drop?

**Comment by SSE4** [comment]
@danimtb I'd say we can conditionally run it (e.g. `if tools.which("ctest")`).

**Comment by danimtb** [comment]
but we will need to run something if ctest is not available

**Comment by SSE4** [comment]
in that case, it might be simpler to just run produced executables, without ctest

**Comment by danimtb** [comment]
ok. Maybe not all the examples but just some of them
