### ISSUE TITLE
support clang with zlib

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan-center-index#1119]
installed `clang-6` on ubuntu. `clang-6.0` in $PATH, but not `clang`

currently zlib forces to use `clang`

```bash
env = {"CC": "clang", "CXX": "clang++"} if "clang" in str(self.settings.compiler) else {}
```

please allow custom `clang version` like so:

```bash
# allow changing clang version by environment variables `CC` and `CXX`, fallback to `clang`
env = {"CC": ("clang" if ("CC" not in os.environ) else os.environ['CC']), "CXX": ("clang++" if ("CXX" not in os.environ) else os.environ['CXX'])} if "clang" in str(self.settings.compiler) else {}
```

Note that approach may be also useful for `clang-cl` users

**Comment by SSE4** [comment]
for the record, the code is:
https://github.com/conan-io/conan-center-index/blob/master/recipes/zlib/1.2.11/conanfile.py#L68
I'll create a PR with fix

**Comment by uilianries** [comment]
Duplicated https://github.com/conan-io/conan-center-index/issues/1259
