### ISSUE TITLE
boost: xml.jam:12:  in load ERROR: rule "Copyright" unknown in module "xml".

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan-center-index#1122]
I am not able to use boost installed using `sudo apt install libboost-all-dev` and boost from `conan-center-index` at the same time.

The read-out from the console error is (during `conan create` for boost from conan-center-index):

```bash
/home/benjamin/boost/boost_1_71_0/tools/build/src/tools/types/xml.jam:12: 
in load ERROR: rule "Copyright" unknown in module "xml".
```

TMP FIX:

```bash
# see https://github.com/boostorg/build/issues/418
# use b2 provided by conan package
(sudo apt remove libboost-*-dev || true)
(sudo mv /usr/bin/b2 /usr/bin/b2_backup || true)
```

Please force boost to use local `b2`, not system one.

**Comment by SSE4** [comment]
@blockspacer thanks for the report
fill free to test the proposed fix (#1124) and let us know
