### ISSUE TITLE
[conan.io/center] Markdown failed `opencv/4.5.5@#b5c2e3085ee6193a0dd40cbb1eb7e0aa`

### ISSUE THREAD

**Issue by Siech0** [conan-io/conan-center-index#11220]
Markdown generator failed for reference opencv/4.5.3@#69b5332c32770b53be1d0d4867522b77.
command line: conan install opencv/4.5.3@#69b5332c32770b53be1d0d4867522b77 -g markdown --remote conancenter.
profile:

This occurs when browsing on firefox & chrome.

**Comment by jgsogo** [comment]
We are working on a new implementation of the web that will regenerate all these files
