### ISSUE TITLE
[package] glfw/3.3.7 : vulkan-headers mismatched while using static build when paired with moltenvk/1.1.9

### ISSUE THREAD

**Issue by KaoCC** [conan-io/conan-center-index#11237]
### Package and Environment Details

* Package Name/Version: **moltenvk/1.1.9 & glfw/3.3.7**
* Operating System+version: **Mac OS 12.4**
* Compiler+version: **Apple clang version 13.1.6**
* Conan version: **conan 1.48.1**
* Python version: **Python 3.10.0**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=13
compiler.libcxx=libc++
build_type=Release
compiler.cppstd=17
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

in the conanfile.txt, set the followings :

```
[requires]
moltenvk/1.1.9
glfw/3.3.7

[generators]
cmake

[options]
glfw:vulkan_static=True
```

then do the normal `conan install`

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: Conflict in moltenvk/1.1.9:
    'moltenvk/1.1.9' requires 'vulkan-headers/1.3.211.0' while 'vulkan-loader/1.3.204.1' requires 'vulkan-headers/1.3.204.1'.
    To fix this conflict you need to override the package 'vulkan-headers' in your root package.
```

</details>

**Comment by KaoCC** [comment]
Note: this is not necessary a bug but we can probably update the version at this [line](https://github.com/conan-io/conan-center-index/blob/master/recipes/glfw/all/conanfile.py#L60)

**Comment by SpaceIm** [comment]
It's not a bug because anybody can use any version of MoltenVK along glfw, and moreover you can override version of any dependency in conan.

**Comment by KaoCC** [comment]
updated.
