### ISSUE TITLE
[package] kcov/38: GLIBC issue

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan-center-index#11232]
### Package and Environment Details

* Package Name/Version: **kcov/38**
* Operating System+version: **Redhat 7**
* Compiler+version: **GCC 7**
* Conan version: **conan 1.49.0**
* Python version: **Python 3.6.8**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce

conan create . 

I'll provide an example.

### Logs

<details><summary>Click to expand log</summary>

```
/export/home/workingArea/cache/conan/kcov/38/_/_/package/5b86215d714ae28c079f13edb57aaed889aeee5c/bin/kcov: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /export/home/workingArea/cache/conan/kcov/38/_/_/package/5b86215d714ae28c079f13edb57aaed889aeee5c/bin/kcov)
/export/home/workingArea/cache/conan/kcov/38/_/_/package/5b86215d714ae28c079f13edb57aaed889aeee5c/bin/kcov: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /export/home/workingArea/cache/conan/kcov/38/_/_/package/5b86215d714ae28c079f13edb57aaed889aeee5c/bin/kcov)
```

</details>

**Comment by uilianries** [comment]
@EstebanDugueperoux2 You need to build everything from source. You are running an environment with older glibc version and libstdc++. For instance, ConanCenter uses Ubuntu as base image to build their package. For GCC7, it used Ubuntu 17.04, which contains glibc 2.26 and libstdc++ 3.4.24. 

```
git clone https://github.com/conan-io/conan-center-index.git
cd conan-center-index/recipes/kcov/all
conan create . 38@ --build
```

Another option is running Conan docker images which are totally compatible with those packages:

```
git clone https://github.com/conan-io/conan-center-index.git
cd conan-center-index/recipes/kcov/all
docker run --rm -ti -v ${PWD}:/home/conan/project conanio/gcc7
cd project
conan create . 38@
```

**Comment by EstebanDugueperoux2** [comment]
Indeed on RHEL7, we have glibc 2.17 and libstdc++ 4.8.5.
Then I understand the "GLIBC_2.25" error but not the "GLIBCXX_3.4.20".

It means that packages from conan-center cannot works on RH7 but only from RH8 according to https://distrowatch.com/table.php?distribution=redhat glib releases.

Thanks.

**Comment by uilianries** [comment]
@EstebanDugueperoux2 You still can build from sources to make it compatible. In it does not work, it's a need from the project upstream, not from Conan.
