### ISSUE TITLE
gdal and proj conflict on libcurl version

### ISSUE THREAD

**Issue by Chrismarsh** [conan-io/conan-center-index#11240]
If both gdal and proj are configured with `with_curl`, they conflict on the version of curl required

GDAL requires 7.83.0
https://github.com/conan-io/conan-center-index/blob/master/recipes/gdal/pre_3.5.0/conanfile.py#L323

whereas proj requires 7.83.1
https://github.com/conan-io/conan-center-index/blob/master/recipes/proj/all/conanfile.py#L70

**Comment by samuel-emrys** [comment]
Have you tried your install command with `--require-override="curl/7.83.1"`? https://docs.conan.io/en/latest/reference/commands/consumer/install.html#require-override

**Comment by toge** [comment]
I think @samuel-emrys's method is the most common.
But I created a PR since the other dependent libraries of gdal were also upgraded,
