### ISSUE TITLE
[conan.io/center] "Use it" tab for eigen does not load

### ISSUE THREAD

**Issue by tkoskela** [conan-io/conan-center-index#11252]
The "Use it" tab for the eigen package https://conan.io/center/eigen?tab=recipe hangs indefinitely in "Generating the content. This could take a couple minutes. Please wait...". Happens at least on MacOS-12/Chromium and Ubuntu-20.04/Firefox.

**Comment by AbrilRBS** [comment]
This has been fixed for a while now, sorry that we didn't circle back to you on time :)
