### ISSUE TITLE
[package] zmq/4.3.1: build from sources fails due to wrong references to source

### ISSUE THREAD

**Issue by AltenOosterbeek** [conan-io/conan-center-index#1127]
Although no conan-center package yet exists here for v4.3.1, I was referred here from bincrafters, so I hope someone can help me. At this point, I would rather not migrate to v4.3.2.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zmq/4.3.1**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Conan version: **conan 1.18.0**
  * Tried with multiple conan profiles...

### Steps to reproduce (Include if Applicable)
When adding zmq/4.3.1 as a required package, I use conan create to build the package, but it gives the following error:
```
ERROR: libsodium/1.0.16@bincrafters/stable: Error in source() method, line 33
        tools.get(source_url, sha256=sha256)
        NotFoundException: Not found: https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz
```
This is due to the fact the 1.0.16 has been moved to the old/ subdirectory, so the correct link is then: https://download.libsodium.org/libsodium/releases/old/libsodium-1.0.16.tar.gz

Please change this. Thanks in advance!

Kind regards,

Wouter Oosterbeek

**Comment by Croydon** [comment]
This seems to be solved 😄 

https://github.com/bincrafters/community/issues/1151#issuecomment-599630472

**Comment by madebr** [comment]
Should we add a 3-level fallback to libsodium?
1. https://download.libsodium.org/libsodium/releases/
2. https://download.libsodium.org/libsodium/releases/old
3. https://download.libsodium.org/libsodium/releases/old/unsupported

**Comment by Croydon** [comment]
No, the CCI recipe variant uses GitHub downloads which are fine. This error is about old Bincrafters' versions.

**Comment by Croydon** [comment]
Actually, I think this can be closed. See the Bincrafters' issue.

**Comment by madebr** [comment]
I'm not so sure about my proposal.
Soon, the download link of 1.0.18 might be moved.

**Comment by madebr** [comment]
> I'm not so sure about my proposal.
> Soon, the download link of 1.0.18 might be moved.

@Croydon Scrap my remark. You're right.

**Comment by AltenOosterbeek** [comment]
I agree, I'll close it, since the github download is used for zeromq...
