### ISSUE TITLE
[service] Wrong apple-clang selected

### ISSUE THREAD

**Issue by theirix** [conan-io/conan-center-index#113]
Probable there are some problems with multiple coexisting XCodes on CCI build machine.

A build requests apple-clang 9.1 which is shipped with XCode 9.3 and XCode 9.4 according to https://gist.github.com/yamaya/2924292 . Build log shows that a darwin18.2.0 compiler is used which is shipped with XCode 10.1. The directory with XCode installation can be seen in logs - `/Applications/Xcode-9.4.app/`. For example, various Travis builds executing on xcode9.4 images show compiler x86_64-apple-darwin17.4.0.

Build profile:
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=9.1
os=Macos
os_build=Macos
[options]
lcms:shared=True
[build_requires]
[env]
```

**Output:**

Output of task by conan-center-bot: https://github.com/conan-io/conan-center-index/pull/112#issuecomment-535425386

Excerpt:
`
checking whether the gcc linker (/Applications/Xcode-9.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.2.0 dyld
`

**Expected:**
darwin17.4.0 is found

**Actual:**
darwin18.2.0 is found

One extra note (may be not related) that this compiler does not pass `__attribute__((visibility))` check which is very strange since all apple-clang compilers have this flag. It leads to a build failure for lcms recipe.

**Comment by lasote** [comment]
Running `cc --version` on the CI machines I get the following:

```
+ cc --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode-9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
[Pipeline] }
[Pipeline] // node
[Pipeline] }

+ cc --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode-9.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
[Pipeline] }
[Pipeline] // node
[Pipeline] }

+ cc --version
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Might the difference be in the target only that looks like the OSS? Do you think that is the issue?

**Comment by theirix** [comment]
Thanks for the helpful! Seems the target is a build machine (darwin18.2.0) not a compiler version. Compiler version is not shown in logs though can be identified by XCode path. So it is not a problem.

The problem is a visibility issue (`checking for __attribute__((visibility))... no`) with clang 9.1 which I didn't encounter in similar deployments (travis).

**Comment by theirix** [comment]
Closing the bug because the problem was not in selecting a target platform (it works as expected) but in choosing SDK for different installed apple-clang compilers.
