### ISSUE TITLE
[conan.io/center] Project descriptions get funky escape characters on the overview tab

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#11317]
https://github.com/conan-io/conan-center-index/blob/87c7499737ef3fde8cf95858c3363d91ebf64e27/recipes/ade/all/conanfile.py#L13

![image](https://user-images.githubusercontent.com/16867443/174894734-86cb6479-bb47-4ce1-98a0-46e135b36be9.png)

and 

![image](https://user-images.githubusercontent.com/16867443/174894851-51a8ca7c-5acc-4a35-b93f-6389456d7a9f.png)

**Comment by prince-chrismc** [comment]
Also reported in #11782

**Comment by bshoshany** [comment]
This issue has been known for at least 6 months, affects any package that has a comma in its description (which is most of them), and seems like it should be easy to fix. Any ETA on a fix?

**Comment by prince-chrismc** [comment]
It's not. Sadly ConanCenter was not standalone and it needed to support 8 or 10 other packages so this won't be fixed.

We are working on a new backend so hopefully we will have better control.

**Comment by bshoshany** [comment]
I see, thanks. Hopefully the new backend will be available soon.

**Comment by prince-chrismc** [comment]
@davidsanfal @franramirez688 I can close this issue

![image](https://github.com/conan-io/conan-center-index/assets/16867443/6cbf977c-bf2c-42a6-bf28-230a7c5dc9be)

Fixed!
