### ISSUE TITLE
[conan.io/center] Markdown failed `libcurl/7.83.1@#bd022189cc3fcf7a6df5e1c98d1537bc`

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan-center-index#11336]
The "Use it" tab for libcurl is not showing the markdown with the instructions on how to consume it:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/3535649/175266901-0614cc85-f7b7-4d45-aa57-34083304f5bd.png">

**Comment by jgsogo** [comment]
fixed
