### ISSUE TITLE
[package] libgeotiff/1.7.1: Fails to find proj

### ISSUE THREAD

**Issue by Chrismarsh** [conan-io/conan-center-index#11368]
### Package and Environment Details

* Package Name/Version: **libgeotiff/1.7.1**
* Operating System+version: **Macos 12.4**
* Compiler+version: **Apple clang version 13.1.6 (clang-1316.0.21.2.5) Target: arm64-apple-darwin21.5.0**
* Conan version: **conan 1.49.0**
* Python version: **Python 3.10.4**

Issue regarding PR #11329 as per @SpaceIm 's request.

libgeotiff doesn't correctly find the conan provided `proj` library

```
-- Library proj not found in package, might be system one
-- Library proj.25 not found in package, might be system one
-- Library proj.25.9.0.1 not found in package, might be system one
-- Library proj not found in package, might be system one
-- Library proj.25 not found in package, might be system one
-- Library proj.25.9.0.1 not found in package, might be system one

[...]

.conan/data/libgeotiff/1.7.1/_/_/build/8c4e784c8e523cadba0c054914b8d76687863587/source_subfolder/libgeotiff/geo_keyp.h:18:10: fatal error: 'proj.h' file not found
#include "proj.h"
         ^~~~~~~~
```

Contrary to [this comment](https://github.com/conan-io/conan-center-index/pull/11329#issuecomment-1165372860) it does not work for me. 

One difference that jumps out at me is that I am building `proj` and `libgeotiff` as `shared=True`

### Conan profile

```
conan profile show default
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=13
compiler.libcxx=libc++
build_type=Release
compiler.cppstd=14
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce

```
conan create . libgeotiff/1.7.1@ --build -o '*:shared=True'
```

**Comment by SpaceIm** [comment]
Works fine for me on macOS intel with `conan create . libgeotiff/1.7.1@ --build -o '*:shared=True'`. I guess your `proj` package is corrupted, try to clean it and build/download it again.

**Comment by Chrismarsh** [comment]
Well I'm at a loss. Removing everything and rebuilding worked. When I first hit the issues I confirmed `proj.h` was present as I couldn't remember which header was the deprecated one (`proj_api.h`). I don't understand how it was corrupted and how it wasn't detected. I'll close this for now and reopen if this is something else in the future. Thanks!
