### ISSUE TITLE
[service] V2 migration linter - checks to add

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#11393]
now we have V2 migration linter (#11147), it's time to think about useful checks to add.
we definetely don't want to add too broad checks like `replace "import conans" via "import conan"`, as it basically means "rewrite the whole recipe".
I personally guess we should start from small things, which are easy to check and fix.
a good candidates where should we start could be:
1. [V2 migration guide](https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html) - it lists some useful things, but definetely, it still lacks a lot of things.
2. learn from our own expirience. e.g. [fmt migration](https://github.com/conan-io/conan-center-index/pull/10456/files) highlights some major things to be done

from what I can currently recommend, we may try to implement the following pieces first:
1. easy imports (existing in both v1 and v2), like `from conan.errors import ConanInvalidConfiguration`, `from conan import ConanFile`, with higher granularty
2. replace `run_environment=True` via `env="conanrun"` (`VirtualRunEnv` generator)
3. use `self.info` in `package_id` method instead of just `self`
4. use `conan.tools` instead of `conan.tools`, with higher granularity - code changes are mostly to add first `self` argument, but they are in different namespaces now
5. replace `build_requires` via `tool_requires`
6. enforce explicit `test_type`

anything else?

**Comment by uilianries** [comment]
I would say https://github.com/conan-io/hooks/issues/387 is related. Adding set_property would be great too.

**Comment by Croydon** [comment]
I guess this issue can be closed.

The check is basically no imports from conans.* and then let's see if 2.0 CI succeeds.

**Comment by valgur** [comment]
@uilianries Can probably close this one as well.
