### ISSUE TITLE
[service] Pull Request result should show total built packages

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#114]
Hi!

When a build is finished on a PR, the total packages created on that build is showed by the conan-center-bot. So far, so good, but when we have unexpected errors, like Jenkins problems, we need to cancel and start a new job, at end, conan-center-bot will show only what was built on this new build, not the total, which makes sense, since we don't want to re-build all packages again.

However, the result is a bit confusing, since we don't the total number of packages, even summing all partial results, because an internal error does not expose how many packages were built.

Related PR: https://github.com/conan-io/conan-center-index/pull/84

An idea is showing both partial result + total result:

![Screenshot_2019-09-26 add pcre2 10 32 by ericLemanissier · Pull Request #84 · conan-io conan-center-index](https://user-images.githubusercontent.com/4870173/65688665-e7534180-e041-11e9-9db6-d7be0ee6dc66.png)

**Comment by lasote** [comment]
Fixed. Validated here: https://github.com/conan-io/conan-center-index/pull/145
