### ISSUE TITLE
[config] Take linter status check into account when merging a PR

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#11438]
> @jgsogo huho, I think there is a problem: the merging bot does not seem to take into account github actions status, cf [#11419 (comment)](https://github.com/conan-io/conan-center-index/pull/11419#event-6900836800)

Yes. That's true (and expected). We wanted to check during these days that it was not failing or raising false-negatives. Now we are confident enough that it works and we will add it here: https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L20 (although this file is not yet used, CI will be changed during this week and will start to use that file)

_Originally posted by @jgsogo in https://github.com/conan-io/conan-center-index/issues/11427#issuecomment-1169774597_

**Comment by jgsogo** [comment]
This is in the backlog. We are working on it in stg environment, eventually it will arrive to `master` and deployed to prod
