### ISSUE TITLE
[question] How to consume glog

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan-center-index#11446]
Hello conan community,

I try to make works a little example with conan to consume glog but I get following error when invoking `conan create .`:

```
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "Findglog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glog", but
  CMake did not find one.

  Could not find a package configuration file provided by "glog" with any of
  the following names:

    glogConfig.cmake
    glog-config.cmake

  Add the installation prefix of "glog" to CMAKE_PREFIX_PATH or set
  "glog_DIR" to a directory containing one of the above files.  If "glog"
  provides a separate development package or SDK, be sure it has been
  installed.
```

See https://github.com/conan-io/examples2/pull/31/files to reproduce it.
In this example the generator used is the old CMake from conans namespace.
I have also tried with CMakeToolChain generator, from conan 2.x, but get same error.

What is the mistake in my example?

Regards.

**Comment by SpaceIm** [comment]
> What is the mistake in my example?

`cmake_find_package` (or `CMakeDeps`) generator is missing.

**Comment by EstebanDugueperoux2** [comment]
Thanks @SpaceIm it works now.
Indeed I have forget conan_basic_setup part, I'm most used to conan 2.0 way as 1.x one.
And I use CMakeDeps since it seems prefered with future conan 2.0 than cmake_find_package.

Regards.
