### ISSUE TITLE
[pkgconf] build dep meson broken with python 3.6

### ISSUE THREAD

**Issue by jpilet** [conan-io/conan-center-index#11451]
### Package and Environment Details

* Package **pkgconf/1.7.4** (all versions affected)
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 7.5**
* Docker image: **nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04**
* Conan version: **conan 1.50.0**
* Python version: **Python 3.6.9**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7.5
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

```
cd conan-center-index/recipes/pkgconf/all
conan create . pkgconf/1.7.4@ --build=missing
```

### Logs

pkgconf has a build_dependency: meson.
In 480febd359, meson has been bumped to meson/0.62.1
But meson 0.62.1 has a problem with python <3.7.
ubuntu 18.04 ships with python 3.6.9.

There is no way of overriding build_dependencies.

What is the proper way to fix this?
- Revert to meson 0.62.1 ?
- check python version and choose meson accordingly?
- Fix meson 0.62 so that it works with python 3.6?

<details><summary>
SyntaxError: future feature annotations is not defined
</summary>

```
pkgconf/1.7.4: Applying build-requirement: meson/0.62.1
pkgconf/1.7.4: Applying build-requirement: ninja/1.10.2
pkgconf/1.7.4: Configuring sources in /home/invision/.conan/data/pkgconf/1.7.4/_/_/source
Downloading pkgconf-1.7.4.tar.xz completed [287.00k]                                     

pkgconf/1.7.4: Copying sources to build folder
pkgconf/1.7.4: Building your package in /home/invision/.conan/data/pkgconf/1.7.4/_/_/build/24647d9fe8ec489125dfbae4b3ebefaf7581674c
pkgconf/1.7.4: Generator txt created conanbuildinfo.txt
pkgconf/1.7.4: Aggregating env generators
pkgconf/1.7.4: Calling build()
Traceback (most recent call last):
  File "/home/invision/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/home/invision/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonmain.py", line 28, in <module>
    from . import mesonlib
  File "/home/invision/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonlib/__init__.py", line 21, in <module>
    from .universal import *
  File "/home/invision/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonlib/universal.py", line 17
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
pkgconf/1.7.4: 
pkgconf/1.7.4: ERROR: Package '24647d9fe8ec489125dfbae4b3ebefaf7581674c' build failed
pkgconf/1.7.4: WARN: Build folder /home/invision/.conan/data/pkgconf/1.7.4/_/_/build/24647d9fe8ec489125dfbae4b3ebefaf7581674c
ERROR: pkgconf/1.7.4: Error in build() method, line 101
        meson = self._configure_meson()
while calling '_configure_meson', line 84
        meson.configure(source_folder=self._source_subfolder, build_folder=self._build_subfolder)
        ConanException: Error 1 while executing meson "/home/invision/.conan/data/pkgconf/1.7.4/_/_/build/24647d9fe8ec489125dfbae4b3ebefaf7581674c/source_subfolder" "/home/invision/.conan/data/pkgconf/1.7.4/_/_/build/24647d9fe8ec489125dfbae4b3ebefaf7581674c/build_subfolder" --backend=ninja -Dprefix="/home/invision/.conan/data/pkgconf/1.7.4/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c" -Dlibdir="lib" -Dbindir="bin" -Dsbindir="bin" -Dlibexecdir="bin" -Dincludedir="include" -Ddefault_library="static" -Dtests="False" -Dsharedstatedir="/home/invision/.conan/data/pkgconf/1.7.4/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin/share" --buildtype=release
```

</details>

**Comment by ericLemanissier** [comment]
use a python which is not EOL: https://endoflife.date/python

**Comment by jpilet** [comment]
@ericLemanissier so if I understand properly, you're suggesting to modify the meson receipe to install a more recent version of python if the one available in the system is outdated?
That would be a good idea, but I do not think there are conan packages for python.

Or are you suggesting to drop support for ubuntu18.04 for all packages that use meson as build tool? Ubuntu 18.04 is supported (until 2028)[https://ubuntu.com/about/release-cycle]. So in that case, we should modify the meson conan receipe to at least produce a meaningful error message.

**Comment by ericLemanissier** [comment]
No, I'm suggesting conan users to update their python version. You can install [python3.7](https://packages.ubuntu.com/bionic/python3.7) or [python3.8 ](https://packages.ubuntu.com/bionic/python3.8) on ubuntu 18.04 .
Even if there was no system package, you could still use pyenv.

**Comment by jpilet** [comment]
So how to change meson recipe to provide appropriate instructions?

**Comment by ericLemanissier** [comment]
If such python version check had to be implemented, it would have to be in meson itself. Please submit the issue in https://github.com/mesonbuild/meson/issues

**Comment by jpilet** [comment]
I think conan's role is to install dependencies.

I ask conan to install X that depends on pkgconfig that depends on meson that depends on python >= 3.7.
Isn't it the role of conan to install the appropriate python or explain that installing X requires python >= 3.7 ?

right now, the error "SyntaxError: future feature annotations is not defined" is quite opaque.

This is a terrible user experience, especially since a working recipe is silently broken by a commit that does not even bump the recipe revision (https://github.com/conan-io/conan-center-index/commit/480febd359703d9682d2854f6417e22c68ffcea7)

Anyway in my company we work with a fork of conan-center-index, so we can deal with it. But I think about other conan users and I would like to make it more friendly. If you do not think making conan user friendly is a good idea, please close this issue.

**Comment by jpilet** [comment]
meson is quite clear about its dependency on python >= 3.7, it is one of the first thing written in the README.

**Comment by ericLemanissier** [comment]
My feeling is that it's fine if the recipe does not check the version of python because you only get the error if you use an outdated piece of software (which you should not be using anyway). You are right that the error message is not immediately understandable, but all the results of a google search on the error message give the solution, so I don't think anybody will stay in the dark for more than a few seconds.
Actually doing the check of the python version is technically not be possible: how do you know which python executable will be used ? Apart from patching meson itself, but then you'd better make a PR there.
That said, if you have an idea, don't hesitate to make a pull request to improve the recipe, I'll approve it.

**Comment by jpilet** [comment]
The check on python version is easy because meson is a build dependency invoked by conan itself.
