### ISSUE TITLE
:pushpin: Pinned issues

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-center-index#11463]
This is a list of interesting issues that we would like to pin (only 3 are allowed in Github interface). Here we can keep a longer list so they are not lost:

- https://github.com/conan-io/conan-center-index/issues/4
- https://github.com/conan-io/conan-center-index/issues/20516
- https://github.com/conan-io/conan-center-index/issues/15557
- https://github.com/conan-io/conan-center-index/issues/11393
- https://github.com/conan-io/conan-center-index/issues/12888
- https://github.com/conan-io/conan-center-index/issues/621
- https://github.com/prince-chrismc/conan-center-index-pending-review/issues/1
- https://github.com/conan-io/conan-center-index/issues/3571

**Comment by AndreyMlashkin** [comment]
You mentioned, there is a statistics about how many downloads each recipe has. Is it an opened information? If so, where can I look it up?

**Comment by Croydon** [comment]
https://conan.io/center/ is displaying download numbers?

**Comment by uilianries** [comment]
@Croydon Yes, but it's the total, based on Artifactory API. I meant based on arch/os/distro.

**Comment by valgur** [comment]
I would maybe include the following Repology badge in the top comment as well:
`[![Repository status](https://repology.org/badge/repository-big/conancenter.svg)](https://repology.org/repository/conancenter)`
[![Repository status](https://repology.org/badge/repository-big/conancenter.svg)](https://repology.org/repository/conancenter)

**Comment by danimtb** [comment]
As we updated the description, I am closing this old issue in favor of https://github.com/conan-io/conan-center-index/issues/20998

Thanks a lot for the advice. We have updated the links up there 😄
