### ISSUE TITLE
[service] CI is not launched again for Pull Request

### ISSUE THREAD

**Issue by Latios96** [conan-io/conan-center-index#11474]
Hi,

I made [a PR](https://github.com/conan-io/conan-center-index/pull/11450) to add a new recipe to Conan. I tried to test as many configurations locally as I could, but the CI found some situations where the build would fail. I fixed the occuring issues in several commits, but since my last push the CI says "This commit cannot be built" and the build is not launched again.

The CI already ran 4 times for this PR, because I could not find all issues at once. Is there a limit of 4 runs per PR? Otherwise I can't see why the build is not launched again.

![image](https://user-images.githubusercontent.com/30260518/176893809-3abd44fd-b509-4eaf-9eb6-a36f6978e1c5.png)

**Comment by uilianries** [comment]
@Latios96 you can re-launch a PR by closing it, then wait 10 secs, then open it again. There is a delay for github send the notification, that's why need to wait few seconds.

Anyway, I just relaunched your PR now. Let's keep the discussion there.
