### ISSUE TITLE
[package] qt/6.3.1:  Component qt::qtWebEngineCore library 'Qt6WebEngineCore' is listed in the recipe, but not found installed at self.cpp_info.libdirs

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan-center-index#11489]
### Package and Environment Details

* Package Name/Version: **qt/6.3.1**
* Operating System+version: **Fedora Linux 36**
* Compiler+version: **GCC 12**
* Conan version: **conan 1.50.0**
* Python version: **Python 3.10.5**

### Conan profile

Configuration for profile linux/gcc/debug:

[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++11
compiler.cppstd=17
build_type=Debug
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

1. Install Conan Hooks.
2. `cd recipes/qt/6.x.x/`
3. `conan create . qt/6.3.1@ -o:h qt:qtwebchannel=True -o:h qt:qtwebengine=True -o:h qt:qtpositioning=True -o:h qt:shared=True -o:h qt:gui=True -o:h qt:qtdeclarative=True -o:h qt:qtmultimedia=True -o:h qt:with_dbus=True -o:h qt:with_mysql=False -o:h qt:with_zstd=True -pr:b linux/gcc/release -pr:h linux/gcc/debug -u -b outdated -b cascade -k`

### Logs

<details><summary>Click to expand log</summary>

```
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
[HOOK - conan-center.py] post_package_info(): ERROR: [LIBRARY DOES NOT EXIST (KB-H054)] Component qt::qtWebEngineCore library 'Qt6WebEngineCore' is listed in the recipe, but not found installed at self.cpp_info.libdirs. Make sure you compiled the library correctly. If so, then the library name should probably be fixed. Otherwise, then the component should be removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H054) 
[HOOK - conan-center.py] post_package_info(): ERROR: [LIBRARY DOES NOT EXIST (KB-H054)] Component qt::qtWebEngineQuick library 'Qt6WebEngineQuick' is listed in the recipe, but not found installed at self.cpp_info.libdirs. Make sure you compiled the library correctly. If so, then the library name should probably be fixed. Otherwise, then the component should be removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H054) 
[HOOK - conan-center.py] post_package_info(): ERROR: [LIBRARY DOES NOT EXIST (KB-H054)] Component qt::qtWebEngineWidgets library 'Qt6WebEngineWidgets' is listed in the recipe, but not found installed at self.cpp_info.libdirs. Make sure you compiled the library correctly. If so, then the library name should probably be fixed. Otherwise, then the component should be removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H054) 
[HOOK - conan-center.py] post_package_info(): ERROR: [INCLUDE PATH DOES NOT EXIST (KB-H071)] Component qt::qtWebEngineCore include dir 'include/QtWebEngineCore' is listed in the recipe, but not found in package folder. The include dir should probably be fixed or removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H071) 
[HOOK - conan-center.py] post_package_info(): ERROR: [INCLUDE PATH DOES NOT EXIST (KB-H071)] Component qt::qtWebEngineQuick include dir 'include/QtWebEngineQuick' is listed in the recipe, but not found in package folder. The include dir should probably be fixed or removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H071) 
[HOOK - conan-center.py] post_package_info(): ERROR: [INCLUDE PATH DOES NOT EXIST (KB-H071)] Component qt::qtWebEngineWidgets include dir 'include/QtWebEngineWidgets' is listed in the recipe, but not found in package folder. The include dir should probably be fixed or removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H071) 
ERROR: 
	ConanException: [HOOK - conan-center.py] post_package_info(): Some checks failed running the hook, check the output
```

[conan-create-qt-6-qtwebengine.txt](https://github.com/conan-io/conan-center-index/files/9033174/conan-create-qt-6-qtwebengine.txt)

</details>

**Comment by ericLemanissier** [comment]
This reuses a binary from cache, so there is not log of the build in this file. Please retry with `-b qt` and send the full log.

**Comment by jwillikers** [comment]
> This reuses a binary from cache, so there is not log of the build in this file. Please retry with `-b qt` and send the full log.

Sorry about that. Here's the new log:

[conan-create-qt-6-qtwebengine.txt](https://github.com/conan-io/conan-center-index/files/9034659/conan-create-qt-6-qtwebengine.txt)

**Comment by ericLemanissier** [comment]
Log says 
```
WARNING: QtWebEngine won't be built. Python3 html5lib is missing.
WARNING: QtPdf won't be built. Python3 html5lib is missing.
```

**Comment by jwillikers** [comment]
> Log says
> 
> ```
> WARNING: QtWebEngine won't be built. Python3 html5lib is missing.
> WARNING: QtPdf won't be built. Python3 html5lib is missing.
> ```

Thanks for pointing that out! I've installed `python3-html5lib` along with a few other packages that appear to be needed, `cups-devel` and `libxshmfence-devel`. I'm now stuck at another error where GN can't find NSS.

[conan-create-qt-6-qtwebengine.txt](https://github.com/conan-io/conan-center-index/files/9035504/conan-create-qt-6-qtwebengine.txt)

**Comment by ericLemanissier** [comment]
your log both says
`qt/6.3.1: Generator pkg_config created nss.pc`
and
```
 Package nss was not found in the pkg-config search path.

  Perhaps you should add the directory containing `nss.pc'

  to the PKG_CONFIG_PATH environment variable
```
and the recipe sets this variable in https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L699

I have no idea what is wrong here.
Also, it "should not" be necessary to install system xshmfence, because qt recipe should rely on the conan package `libxshmfence/1.3`

**Comment by jwillikers** [comment]
> your log both says `qt/6.3.1: Generator pkg_config created nss.pc` and
> 
> ```
>  Package nss was not found in the pkg-config search path.
> 
>   Perhaps you should add the directory containing `nss.pc'
> 
>   to the PKG_CONFIG_PATH environment variable
> ```
> 
> and the recipe sets this variable in https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L699
> 
> I have no idea what is wrong here. Also, it "should not" be necessary to install system xshmfence, because qt recipe should rely on the conan package `libxshmfence/1.3`

An issue with how Qt's calling into GN most likely?

**Comment by jwillikers** [comment]
@ericLemanissier Looking at the log output, it appears this error is happening in the `package()` method? The error happens after `qt` notes that it is calling the `package` method. That means the issue might be that `cmake` is either reconfiguring without the proper environment setup and/or the `cmake.install` command is happening without the proper environment and needs it.

**Comment by ericLemanissier** [comment]
owww, very good catch !
We should extract most of the environment setup in

https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L695-L721

into its own `@contextmanagger`, like
https://github.com/conan-io/conan-center-index/blob/b5a9d42e63a69f4fbd989152a257bda1df2d1076/recipes/gn/all/test_package/conanfile.py#L12

then we would be able to re-use the same environment in package(self). Would you have the possibility to try and make a PR for this?

**Comment by jwillikers** [comment]
> owww, very good catch ! We should extract most of the environment setup in
> 
> https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L695-L721
> 
> into its own `@contextmanagger`, like
> 
> https://github.com/conan-io/conan-center-index/blob/b5a9d42e63a69f4fbd989152a257bda1df2d1076/recipes/gn/all/test_package/conanfile.py#L12
> 
> then we would be able to re-use the same environment in package(self). Would you have the possibility to try and make a PR for this?

No problem, I really appreciate the help with all of this. Thanks!
