### ISSUE TITLE
[package] protobuf/3.21.1: protoc: error while loading shared libraries: libllvm-unwind.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yssource** [conan-io/conan-center-index#11497]
### Package and Environment Details

* Package Name/Version: **protobuf/3.21.1**
* Operating System+version: **OS: Manjaro 21.3.1 Ruah Kernel: x86_64 Linux 5.10.127-1-MANJARO**
* Compiler+version: **GCC 12**
* Conan version: **conan 1.50.0**
* Python version: **Python 3.10**

### Conan profile

``` bash
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=13
compiler.libcxx=libc++
build_type=Release
# build_type=Debug
[options]
[build_requires]
[env]
CC="clang"
CXX="clang++"
CPP="cpp"
LDFLAGS="-fuse-ld=lld"
CONAN_CMAKE_GENERATOR=Ninja
```

### Steps to reproduce

`conan install protobuf/3.21.1@`

`/home/user/.conan/data/protobuf/3.21.1/_/_/package/8bf80f61e626c664a94fa5752cc1b7e58b9853bc/bin/protoc --version`

`/home/user/.conan/data/protobuf/3.21.1/_/_/package/8bf80f61e626c664a94fa5752cc1b7e58b9853bc/bin/protoc: error while loading shared libraries: libllvm-unwind.so.1: cannot open shared object file: No such file or directory`

### Logs

<details><summary>Click to expand log</summary>

```
/home/user/.conan/data/protobuf/3.21.1/_/_/package/8bf80f61e626c664a94fa5752cc1b7e58b9853bc/bin/protoc: error while loading shared libraries: libllvm-unwind.so.1: cannot open shared object file: No such file or directory
```

</details>

**Comment by kekeliu-whu** [comment]
Same problem too.

**Comment by uilianries** [comment]
You are missing a system library for your compiler. Need to be installed.

**Comment by kekeliu-whu** [comment]
> You are missing a system library for your compiler. Need to be installed.

Hi, what's the system library name contains file `libllvm-unwind.so.1`?
I've used `apt-file search libllvm-unwind.so.1` and google but haven't found the library name yet.

**Comment by uilianries** [comment]
@yssource Checking again this case and it's a bit more complicated. The failure does not come from protobuf package, but it's from our Clang 13 docker image:

```
$ ldd /home/conan/.conan/data/protobuf/3.21.1/_/_/package/8bf80f61e626c664a94fa5752cc1b7e58b9853bc/bin/protoc --version
/home/conan/.conan/data/protobuf/3.21.1/_/_/package/8bf80f61e626c664a94fa5752cc1b7e58b9853bc/bin/protoc:
	linux-vdso.so.1 =>  (0x00007fffbe1f0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f789aaa0000)
	libc++.so.1 => /usr/local/lib/libc++.so.1 (0x00007f789adca000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f789a797000)
	libllvm-unwind.so.1 => /usr/local/lib/libllvm-unwind.so.1 (0x00007f789adbc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f789a3cd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f789acbd000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f789a1c5000)
	libatomic.so.1 => /usr/local/lib64/libatomic.so.1 (0x00007f7899fbe000)
	libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007f7899da7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7899ba3000)
```

This output it's from the Docker image `conanio/clang13-ubuntu16.04`, the same used for Clang 13 packages.

We build LLVM from sources and it uses libunwind. However, we wanted to avoid name collision as Conan also provides libunwind, so we renamed its internal library to libllvm-unwind. We also configured LLVM to force static link always. However, as you can see on your case, we missed something, because unwind should not be listed there.

I'll need to fix the LLVM Docker image and generate a fix. Meanwhile, I recommend building from source, so you will consume only your local libraries:

    conan install -r conancenter protobuf/3.21.1@ --build=protobuf

**Comment by yssource** [comment]
Thanks. 
I've noticed this problem coming from the Docker image, but forget to refer it here.
My local environment has been upgraded to clang14.
And protobuf's protoc compiled with clang14 has no such link problem, which no longer link unwind.so again.

``` bash
ldd /home/conan/.conan/data/protobuf/3.21.1/_/_/package/c08740f3a000c5c2cadbf6813fe9118e5b0d8da0/bin/protoc

	linux-vdso.so.1 (0x00007ffef03ce000)
	libc++.so.1 => /usr/lib/libc++.so.1 (0x00007fabf0ca9000)
	libc++abi.so.1 => /usr/lib/libc++abi.so.1 (0x00007fabf0c66000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fabf0b7f000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fabf0b5f000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fabf0953000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fabf119d000)
```

**Comment by uilianries** [comment]
I just opened an issue to Conan Docker Tools: https://github.com/conan-io/conan-docker-tools/issues/449. I gonna investigate a solution today, as that bug affects any packages built by clang. Thank you for your report.

**Comment by hrishikesh713** [comment]
@uilianries I am seeing the exact same problem for `spdlog/1.10.0` package downloaded from conan center.

**Comment by uilianries** [comment]
@hrishikesh713 Use the latest docker image, or, build from source.

    conan install -r conancenter spdlog/1.10.0@ --build=spdlog -pr:h=default -pr:b=default

**Comment by yssource** [comment]
@uilianries Since my local developing environoment has been upgraded to llvm-14, I'm not able to reproduce this problem again. So please feel free to close this thread, if the  [conan-docker-tools/issues/449](https://github.com/conan-io/conan-docker-tools/issues/449) has been closed.

**Comment by uilianries** [comment]
@yssource Thank you for your feedback!
