### ISSUE TITLE
[question] publish to github pages

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-center-index#11529]
Could you consider publishing this repo to github pages ? It only takes the following configuration

![image](https://user-images.githubusercontent.com/1926390/177157468-e068e65d-e466-44d0-8831-1b565987c091.png)

and then you automatically get this nicely readable website: https://ericlemanissier.github.io/conan-center-index/ with links to docs etc., basically for free.

**Comment by Croydon** [comment]
Nice catch! Pretty much a late solution to #2283

**Comment by SSE4** [comment]
@ericLemanissier (and others who find it useful) - could you clarify what's an advantage/value of having this github page over the native GH markdown rendering (https://github.com/conan-io/conan-center-index/blob/master/README.md)?

also, why icons aren't rendered? (such as `:rocket:` and so on)

**Comment by ericLemanissier** [comment]
I find it more readable to have only the documentation on the page, without the header
![image](https://user-images.githubusercontent.com/1926390/177744695-1954dd98-c2ce-4c80-bb5d-871b12e2b786.png)
The icons not being rendered is indeed a problem, it looks like it can be solved by creating a `_config.yml` and add this snippet:
```
plugins:
  - jemoji
```
(cf https://github.community/t/emojis-and-pictures-arent-showing/134860/4?u=ericlemanissier and https://github.com/jekyll/jemoji)
