### ISSUE TITLE
[package] qt/6.3.0: When compiling with gcc in Debug mode, the "d" suffix is not added to libraries.

### ISSUE THREAD

**Issue by hjlre** [conan-io/conan-center-index#11523]
### Package and Environment Details

* Package Name/Version: **qt/6.3.0**
* Operating System+version: **Windows 10**
* Compiler+version: **GCC 12**
* Conan version: **conan 1.48.2**
* Python version: **Python 3.9.10**

### Conan profile

```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce

Build a project using qt/6.3.0 with MinGW in Debug mode.
Conan will build Qt from source. However, the Qt libraries do not have the "d" suffix, whereas Conan assumes the suffix to be added, causing it not to find the libraries.

```-- Library Qt6EntryPointd not found in package, might be system one
-- Library Qt6Cored not found in package, might be system one
-- Library Qt6Networkd not found in package, might be system one
-- Library Qt6Guid not found in package, might be system one
-- Library Qt6Multimediad not found in package, might be system one
-- Library Qt6Qmld not found in package, might be system one
-- Library Qt6QmlModelsd not found in package, might be system one
-- Library Qt6Quickd not found in package, might be system one
-- Library Qt6MultimediaQuickd not found in package, might be system one
-- Library Qt6Widgetsd not found in package, might be system one
-- Library Qt6MultimediaWidgetsd not found in package, might be system one
-- Library Qt6VirtualKeyboardd not found in package, might be system one
-- Library Qt6Svgd not found in package, might be system one
-- Library Qt6SvgWidgetsd not found in package, might be system one
-- Library Qt6ShaderToolsd not found in package, might be system one
-- Library Qt6QuickTemplates2d not found in package, might be system one
-- Library Qt6QuickControls2d not found in package, might be system one
-- Library Qt6Testd not found in package, might be system one
-- Library Qt6QuickTestd not found in package, might be system one
-- Library Qt6QmlWorkerScriptd not found in package, might be system one
-- Library Qt6QuickShapesd not found in package, might be system one
-- Library Qt6QuickWidgetsd not found in package, might be system one
-- Library Qt6Xmld not found in package, might be system one
-- Library Qt6Concurrentd not found in package, might be system one
-- Library Qt6OpenGLd not found in package, might be system one
-- Library Qt6OpenGLWidgetsd not found in package, might be system one
-- Library Qt6PrintSupportd not found in package, might be system one
-- Library Qt6Sqld not found in package, might be system one
-- Configuring done

```

Root cause is probably the following code in the qt conanfile:
```
if self.settings.build_type == "Debug":
            if self.settings.os == "Windows":
                libsuffix = "d"
            if tools.is_apple_os(self.settings.os):
                libsuffix = "_debug"
```

Replacing the second line with `if self.settings.os == "Windows" and self._is_msvc` fixes the issue. Apparently, Qt does not add the d suffix anymore for GCC builds (Qt5 versions might also be affected):
https://bugreports.qt.io/browse/QTBUG-81021

**Comment by scandyna** [comment]
> (Qt5 versions might also be affected)

Yes, I have the same issue for qt 5.15.2 (MinGW gcc 8 Debug build).

**Comment by hjlre** [comment]
@scandyna Please check the pull request by hubjak. It fixes the problem but we don't have time to do all the CI stuff required by conan to merge it

**Comment by scandyna** [comment]
PR https://github.com/conan-io/conan-center-index/pull/12656 was integrated into PR https://github.com/conan-io/conan-center-index/pull/12879.
By my side, MinGW (gcc 8, Release and Debug) builds are now ok for Qt 5.15.6, many thanks.

**Comment by ericLemanissier** [comment]
yes, but this issue is about qt6 which is not solved yet I think

**Comment by hjlre** [comment]
> yes, but this issue is about qt6 which is not solved yet I think

No, the pull request worked for us with Qt 6.3.0

**Comment by ericLemanissier** [comment]
Which pull request? All the PRs mentionned in this issue modify only qt5 recipe. The root cause is still present in qt6 recipe: https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L912
