### ISSUE TITLE
[package] spirv-tool/1.3.216.0 has the wrong sha256 hash and cannot be downloaded to be built

### ISSUE THREAD

**Issue by ntagliani** [conan-io/conan-center-index#11550]
### Package and Environment Details

* Package Name/Version: **spirv-tool/1.3.216.0**
* Operating System+version: **Linux Ubuntu 18.04** and **Windows**
* Compiler+version: **doesn't matter**
* Conan version: **conan 1.47.0**
* Python version: **Python 3.7.8**

I wanted to download the latest version of the spirv-tool package and conan stumbled on the source() step because the sha256 hash computed doesn't match with the one stored in the conandata.yml.
Upon manually downloading the file I could confirm that the actual computed sha256 hash is correct and other 3rf party tools and  Get-FileHash from powershell give the same result as conan.

I could easily open a pr with the correct hash in the conandata.yml but I looked around in the history of when that hash was added (49b10090a136fd070e65c69057677682b9a038c6 and issue #11226) and it looks like the recipe was built by your CI.

Am I missing something in here? Does this implies that kronos re-published the tar.gz after the recipe was originally added to this repo?

### Conan profile

not relevant but I'm using:
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce

from: conan-center-index\recipes\spirv-tools\all> run: 
```
conan create conanfile.py spirv-tools/1.3.216.0@ntagliani/testing --build=missing
```
### Logs

<details><summary>
ERROR: spirv-tools/1.3.216.0@ntagliani/testing: Error in source() method, line 102
        destination=self._source_subfolder, strip_root=True)
        ConanException: sha256 signature failed for 'sdk-1.3.216.0.tar.gz' file.
 Provided signature: b82c5d4790ea4c27ff3a6152fc2fbbb11f6d89702f04d6c644512d851608d67b
 Computed signature: b4b9abeb59deda20c41808ac4cd5f9faf6f0a9daa51a8c82e13ca47c045e982f
</summary>

```
Exporting package recipe
spirv-tools/1.3.216.0@ntagliani/testing exports: File 'conandata.yml' found. Exporting it...
spirv-tools/1.3.216.0@ntagliani/testing exports: Copied 1 '.yml' file: conandata.yml
spirv-tools/1.3.216.0@ntagliani/testing: Calling export_sources()
spirv-tools/1.3.216.0@ntagliani/testing export_sources() method: Copied 1 '.txt' file: CMakeLists.txt
spirv-tools/1.3.216.0@ntagliani/testing: The stored package has not changed
spirv-tools/1.3.216.0@ntagliani/testing: Source folder is corrupted, forcing removal
spirv-tools/1.3.216.0@ntagliani/testing: Exported revision: 03fb0593725b743d38f617c4aec58adf
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

spirv-tools/1.3.216.0@ntagliani/testing (test package): Installing package
Requirements
    spirv-headers/1.3.216.0 from 'conancenter' - Cache
    spirv-tools/1.3.216.0@ntagliani/testing from local cache - Cache
Packages
    spirv-headers/1.3.216.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    spirv-tools/1.3.216.0@ntagliani/testing:a5dfd3fe242a39adf525dfe68dc5bffbd4f31e64 - Build

Installing (downloading, building) binaries...
spirv-headers/1.3.216.0: Already installed!
spirv-tools/1.3.216.0@ntagliani/testing: Configuring sources in C:\.conan\56039e\1
Downloading sdk-1.3.216.0.tar.gz completed [2948.59k]
ERROR: spirv-tools/1.3.216.0@ntagliani/testing: Error in source() method, line 102
        destination=self._source_subfolder, strip_root=True)
        ConanException: sha256 signature failed for 'sdk-1.3.216.0.tar.gz' file.
 Provided signature: b82c5d4790ea4c27ff3a6152fc2fbbb11f6d89702f04d6c644512d851608d67b
 Computed signature: b4b9abeb59deda20c41808ac4cd5f9faf6f0a9daa51a8c82e13ca47c045e982f
```

</details>

**Comment by SpaceIm** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/issues/4825#issuecomment-1175250362
