### ISSUE TITLE
[conan.io/center] Markdown failed `cpython/3.10.0@#6a5396cadb44e81a53b11e7e87907506`

### ISSUE THREAD

**Issue by victorpaleologue** [conan-io/conan-center-index#11568]
Encountered that issue with Firefox 102.0.1 (64 bits) on Mac OS Monterey, with an arm64 processor.
![image](https://user-images.githubusercontent.com/8899804/177573651-ac5f8858-1755-44ca-8296-70a6df77e40b.png)

**Comment by jgsogo** [comment]
we are working on a new implementation of the web and all these files will be generated again
