### ISSUE TITLE
[request] websocketpp/0.8.1

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#1156]
### Package Details
  * Package Name/Version: **websocketpp/0.8.1**
  * Website: **http://www.zaphoyd.com/websocketpp**
  * Source code: **https://github.com/zaphoyd/websocketpp/tree/develop**

### Description Of The Library / Tool
C++ webscoket library on top of boost asio

Currently this is hosted by @bincrafters-user but I would like to migrate it to CCI.
https://github.com/bincrafters/conan-websocketpp

@Croydon would this be allowed? I would like to confirm before doing the work =)

**Comment by Croydon** [comment]
Yes, please go ahead! 😄

**Comment by Croydon** [comment]
The patch needs to move into the `conandata.yml`, but other than that it should not need to much changed to be ready for CCI
