### ISSUE TITLE
[package] wayland: Break out wayland-scanner to a separate Conan package to allow cross-compiling

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan-center-index#11579]
### Package and Environment Details

* Package Name/Version: **wayland**
* Operating System+version: **Fedora Linux 36**
* Compiler+version: **GCC 12**
* Conan version: **conan 1.50.0**
* Python version: **Python 3.10.5**

### Conan profile

```
Configuration for profile armv7hf-debug:

[settings]
os=Linux
arch=armv7hf
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
compiler.cppstd=17
build_type=Debug
```

### Steps to reproduce

0. Attempt to cross-compile the `wayland` package.
It won't work unless the exact same version of `wayland-scanner` is installed on the build system since it needs to run it to generate source files.
Ideally, `wayland-scanner` could be a `tool_requires` for the `wayland` package.
This would allow `wayland-scanner` to be built and used on the host.

For reference, see the [MR that added this behavior](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/68).

To build `wayland` with proper cross-compilation support in Meson, I currently have to use the `MesonToolchain` generator, so see my fork [here](https://github.com/jwillikers/conan-center-index/tree/wayland-mesontoolchain).

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by jwillikers** [comment]
Well, it is also technically possible to circularly require the `wayland` package as a `tool_requires`, but only when cross compiling. I got this working in another branch [here](https://github.com/jwillikers/conan-center-index/tree/wayland-tool-requires-wayland).

The main caveat either way is that the `wayland` package locates the `wayland-scanner` executable using the `pkg-config` variable `wayland_scanner` found in the pkg-config file `wayland-scanner.pc`. I had to package the `wayland-scanner.pc` file generated by the build-system and not use one generated from Conan's PkgConfigDeps generator. This is due to the fact that the `PkgConfigDeps` generator won't create a `.pc` file for a package that is `tool_requires`. Maybe there is some way to accomplish this with `PkgConfigDeps`, though?

I think it would still be cleaner to have a separate `wayland-scanner` package that is used as a `tool_requires` for the `wayland` package, but I'm sure there are trade-offs I haven't considered here.

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

I'm closing this issue as this recipe supports nowadays cross compiling. If you still wish to break out `wayland-scanner` from this main package, we can talk about it. I'm an X user so I don't any idea about wayland for the moment.
