### ISSUE TITLE
[question] cannot search/install benchmark/1.5.0

### ISSUE THREAD

**Issue by akshit-sharma** [conan-io/conan-center-index#1157]
It appears that conan already have support for [benchmark/1.5.0](https://github.com/conan-io/conan-center-index/issues/370). 

I am not able to search the same with conan.
```
akshit:~$ conan search *benchmark*
There are no packages matching the '*benchmark*' pattern
akshit:~$ conan search *benchmark* --remote=conan-center
Existing package recipes:

benchmark/1.5.0
```
I am wondering how should I go about knowing which package to search and install for [google benchmark](https://github.com/google/benchmark).

```
akshit:~$ conan install benchmark/1.5.0
ERROR: Conanfile not found at /home/akshit/benchmark/1.5.0
akshit:~$ conan install benchmark/1.5.0@bincrafter/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8.3
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

benchmark/1.5.0@bincrafter/stable: Not found in local cache, looking in remotes...
benchmark/1.5.0@bincrafter/stable: Trying with 'conan-center'...
benchmark/1.5.0@bincrafter/stable: Trying with 'conan-community'...
benchmark/1.5.0@bincrafter/stable: Trying with 'bincrafters'...
ERROR: Unable to find 'benchmark/1.5.0@bincrafter/stable' in remotes
```

**Comment by prince-chrismc** [comment]
Try `conan install benchmark/1.5.0@_/_` without the `@user/channel` the command line does not know to search the remotes when installing.

**Comment by akshit-sharma** [comment]
Thanks, it's working with ```conan install benchmark/1.5.0@_/_```.

**Comment by Croydon** [comment]
`conan install benchmark/1.5.0@` is shorter and works too 😄

**Comment by uilianries** [comment]
@akshit-sharma prefer @Croydon approaches. The underscore are just placeholders and have no effect.
