### ISSUE TITLE
[service] ERROR: [HOOK - hook_reduce_conandata.py] post_export(): post_export() missing 3 required positional arguments: 'conanfile', 'conanfile_path', and 'reference'

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan-center-index#11597]
I'm seeing the following hook error for Conan V2 support in #11580 but not sure what it is referring to:

```
ERROR: [HOOK - hook_reduce_conandata.py] post_export(): post_export() missing 3 required positional arguments: 'conanfile', 'conanfile_path', and 'reference'
```

**Comment by SSE4** [comment]
don't worry about it. hook was adapted for beta1, while CI is stil running alpha7 (update is pending).

**Comment by jgsogo** [comment]
@jwillikers , check https://github.com/conan-io/hooks/pull/436
