### ISSUE TITLE
[package] catch2/3.0.1: pkg-config generated files do not link catch2 lib

### ISSUE THREAD

**Issue by vvainola** [conan-io/conan-center-index#11604]
### Package and Environment Details

* Package Name/Version: **catch2/3.0.1**
* Operating System+version: **Windows 11**
* Compiler+version: **MSVC 2022**
* Conan version: **conan 1.50**
* Python version: **Python 3.10.2**

### Conan profile

```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
compiler.cppstd=20
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce

Using conanfile.txt with contents 
```
[requires]
catch2/3.0.1

[generators]
pkg_config
```
produces 2 pkg-config files.

Catch2.pc
```
Name: catch2
Description: A modern, C++-native, header-only, framework for unit-tests, TDD and BDD
Version: 3.0.1
Requires: Catch2 Catch2WithMain
```

Catch2WithMain.pc
```
prefix=C:/Users/viliv/.conan/data/catch2/3.0.1/_/_/package/45046cca4611564b3e723e57d427413b1c2c937f
libdir=${prefix}/lib
includedir=${prefix}/include

Name: catch2-Catch2WithMain
Description: Conan package: catch2-Catch2WithMain
Version: 3.0.1
Libs: -L"${libdir}" -lCatch2Main 
Cflags: -I"${includedir}"
Requires: Catch2
```

Trying to use Catch2WithMain causes linker errors from catch_main.obj  `error LNK2019: unresolved external symbol "public: __cdecl Catch::Session::Session(void)"` because Catch2.lib does not get linked by the Catch2.pc and only Catch2Main.lib from the build folder is linked. 

The Catch2.pc seems to refer recursively to itself and maybe the .pc file for the lib gets overwritten during generation.

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by SpaceIm** [comment]
Interesting issue for case insensitive systems, maybe it could even be reported to conan client to disallow the same name in recipe & components in case insensitive way. This is why I advice to always give lower case name to components.

Recipe name is catch2, components are Catch2 & Catch2Main. On Windows, catch2.pc & Catch2.pc files cannot live together in the same folder, leading to this issue.

/cc @uilianries @SSE4

**Comment by SSE4** [comment]
@czoido is it something that rings a bell for you? I remember we had some issue with .pc files referenced themselves.
but if upstream uses (for some crazy purpose?) two files with different case, how is it supposed to work in the first place on case-insensitive file system?

**Comment by SpaceIm** [comment]
It doesn't come from upstream, it's a recipe issue. Upstream provides `catch2.pc` & `catch2-with-main.pc`

**Comment by SSE4** [comment]
so what is the `Catch2.pc` (starting with capital) and why is it needed?

**Comment by SpaceIm** [comment]
it's not needed, it shouldn't be there. It's a side effect of defining conan components with capital letters and not re-defining pc files.

**Comment by SpaceIm** [comment]
Is it better with https://github.com/conan-io/conan-center-index/pull/11621?

**Comment by czoido** [comment]
I have checked and https://github.com/conan-io/conan-center-index/pull/11621 should solve this issue
