### ISSUE TITLE
[question] don't build libqsqlpsql with qt6

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#11630]
I am using macdeployqt tool from qt/6.2.4 recipe and I am getting 2 warnings:

WARNING: Plugin "libqsqlodbc.dylib" uses private API and is not Mac App store compliant.
WARNING: Plugin "libqsqlpsql.dylib" uses private API and is not Mac App store compliant.

It's easy to get rid from the first one by setting .with_odbc=False. But how to get rid of the second one?
There is no dedicated flag for it. Could you please add with_psql flag @ericLemanissier ?

**Comment by ericLemanissier** [comment]
@AndreyMlashkin did you try to set option `qt:with_pq=False` ?

**Comment by ericLemanissier** [comment]
@AndreyMlashkin friendly ping, did you see my answer above (and below) ?

> @AndreyMlashkin did you try to set option `qt:with_pq=False` ?

**Comment by AndreyMlashkin** [comment]
Ah, yes, that removes a warning, thank you.

**Comment by ericLemanissier** [comment]
@AndreyMlashkin so this issue can probably be closed right?
