### ISSUE TITLE
[request] <libsodium/cci.20220430> Needs configuration for Visual Studio 2022 (compiler v17 toolset v143)

### ISSUE THREAD

**Issue by gprosch** [conan-io/conan-center-index#11653]
libsodium/cci.20220430

Need recipe configuration for Visual Studio 2022 (msvs v17 toolset v143). Build missing does not work because there does not appear to be a recipe. The following error message is emitted:

ERROR: libsodium/1.0.18: Invalid configuration: Unsupported msvc version: 17

**Comment by SpaceIm** [comment]
You have an old recipe revision, update to latest revision. Your issue has been fixed 5 months ago by https://github.com/conan-io/conan-center-index/pull/8957

**Comment by gprosch** [comment]
Here is the relevant code snippet from the recipe.  I do not see: "17": "vs2022",

 

if self.settings.compiler == "Visual Studio":

            folder = {

                "10": "vs2010",

                "11": "vs2012",

                "12": "vs2013",

                "14": "vs2015",

                "15": "vs2017",

                "16": "vs2019",

            }

**Comment by SpaceIm** [comment]
It's quite confusing.

- Are you talking now of the same recipe revision than your first message? Do you still have an error with latest RREV of either 1.0.18 (or cci.20220430)
- There is a cci.20220430 version already in conan-center, so why do you ask for an upstream update?
- Code snippet you show is not relevant without all the other logic in the recipe, which should properly handle Visual Studio 2022.

**Comment by gprosch** [comment]
Thank you for your explanation and patience.  I understand now and appreciate your help.  Case resolved.

 

Greg

**Comment by SpaceIm** [comment]
@uilianries this issue can be closed
