### ISSUE TITLE
[package]   paho-mqtt-cpp/1.1   cpr/1.3.0   cpp-jwt/1.2: multiple definition of `SHA1_...

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#1168]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **paho-cpp-mqtt, cpr, cpp-jwt, openssl**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 9.2**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.23.0**
  * Python version: **Python 3.7.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9.2
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

depend on:
```txt
  paho-mqtt-cpp/1.1
  cpr/1.3.0
  cpp-jwt/1.2
```

use functions from those libs in source code, link everything in cmake using f`ind package` and `target link directories`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>
 
```
/usr/bin/ld: /home/ladmin/.conan/data/openssl/1.1.1d/_/_/package/acc1bd9feeca12810ba1313c4fd8867e201d928f/lib/libcrypto.a(sha1dgst.o): in function `SHA1_Update':
/tmp/c3ipr/pr_1086_2_24_17/.conan/data/openssl/1.1.1d/_/_/build/acc1bd9feeca12810ba1313c4fd8867e201d928f/sources/crypto/include/internal/md32_common.h:129: multiple definition of `SHA1_Update'; /home/ladmin/.conan/data/paho-mqtt-c/1.3.1/_/_/package/2fa1bd12cda3f261d17227d637ed61fef1c14f07/lib/libpaho-mqtt3a-static.a(SHA1.c.o):/tmp/c3ipr/pr_981_2_4_17/.conan/data/paho-mqtt-c/1.3.1/_/_/build/2fa1bd12cda3f261d17227d637ed61fef1c14f07/source_subfolder/src/SHA1.c:174: first defined here
/usr/bin/ld: /home/ladmin/.conan/data/openssl/1.1.1d/_/_/package/acc1bd9feeca12810ba1313c4fd8867e201d928f/lib/libcrypto.a(sha1dgst.o): in function `SHA1_Final':
/tmp/c3ipr/pr_1086_2_24_17/.conan/data/openssl/1.1.1d/_/_/build/acc1bd9feeca12810ba1313c4fd8867e201d928f/sources/crypto/include/internal/md32_common.h:192: multiple definition of `SHA1_Final'; /home/ladmin/.conan/data/paho-mqtt-c/1.3.1/_/_/package/2fa1bd12cda3f261d17227d637ed61fef1c14f07/lib/libpaho-mqtt3a-static.a(SHA1.c.o):/tmp/c3ipr/pr_981_2_4_17/.conan/data/paho-mqtt-c/1.3.1/_/_/build/2fa1bd12cda3f261d17227d637ed61fef1c14f07/source_subfolder/src/SHA1.c:140: first defined here
/usr/bin/ld: /home/ladmin/.conan/data/openssl/1.1.1d/_/_/package/acc1bd9feeca12810ba1313c4fd8867e201d928f/lib/libcrypto.a(sha1dgst.o): in function `SHA1_Init':
/tmp/c3ipr/pr_1086_2_24_17/.conan/data/openssl/1.1.1d/_/_/build/acc1bd9feeca12810ba1313c4fd8867e201d928f/sources/crypto/sha/sha_locl.h:54: multiple definition of `SHA1_Init'; /home/ladmin/.conan/data/paho-mqtt-c/1.3.1/_/_/package/2fa1bd12cda3f261d17227d637ed61fef1c14f07/lib/libpaho-mqtt3a-static.a(SHA1.c.o):/tmp/c3ipr/pr_981_2_4_17/.conan/data/paho-mqtt-c/1.3.1/_/_/build/2fa1bd12cda3f261d17227d637ed61fef1c14f07/source_subfolder/src/SHA1.c:78: first defined here
collect2: error: ld returned 1 exit status```

**Comment by gocarlos** [comment]
could it be that I run into `C` lack if namespace issues? 
* https://github.com/openssl/openssl/search?q=SHA1_Init&type=
* https://github.com/eclipse/paho.mqtt.c/search?q=SHA1_Init&unscoped_q=SHA1_Init

**Comment by gocarlos** [comment]
ok, all good: paho-mqtt-c had embedded a sha1 implementation which is used if not compiled with ssl

ssl is by default `OFF` -> this leads to issues if other dependencies have default to `ON`

eventually we should start having a standard here, either have ssl `OFF` by default or `ON`

**Comment by danimtb** [comment]
I see the options are well managed between both recipes and they should work just fine if you set the option accordingly.

However, I agree with you that this could be a hint to change the default value of that option:

https://github.com/microsoft/vcpkg/blob/2d9a32b46fc82d50aa7714a1a4bedc8f0d153dcc/ports/paho-mqtt/portfile.cmake#L22

Do you think it should be a good default?

**Comment by gocarlos** [comment]
I have the feeling that in 2020 we should have ssl by default... who can afford to not use ssl, probably only for testing

**Comment by danimtb** [comment]
But this should be a request for the library author. Maybe there are some implications for this not being enabled by default.

Anyway, I am not saying that the defaults of the library should be the Conan's defaults. So we might consider the change
