### ISSUE TITLE
[package] zstd/1.4.4: Missing cmake module file FindZstd.cmake

### ISSUE THREAD

**Issue by jmauffray** [conan-io/conan-center-index#1175]
To use find_package and other cmake commands a file FindZstd.cmake is necessary, ideally it would be a file zstd-config.cmake with exported targets but it seems requiring an update in zstd build system and source code.
Simpler solution seems to add FindZstd.cmake file in conan package distribution as already done in other packages.

**Comment by uilianries** [comment]
Hi @jmauffray The conan generator [cmake_find_package](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html) is not enough? Which features from findzstd.cmake are you looking for?

**Comment by madebr** [comment]
The current cmake_find_package name of zst is correct: it is `zstd`.
[Click here for the upstream installation](https://github.com/facebook/zstd/blob/f5029e285f65860e57edf3685285e1fb8bc92cf9/build/cmake/lib/CMakeLists.txt#L178-L181)

**Comment by jmauffray** [comment]
Hi, firstly thanks for your quick response and support.
Indeed with cmake_find_package conan generator findzstd.cmake is generated and correct but I already use several libraries (10 and more) with package-config.cmake generated in conan package.
I try to use conan_find_package generator but it breaks build in other part, so I come back to cmake generator and manually create my own FindZstd.cmake in my project.
Thanks @madebr for your suggestion I miss it,  package-config.cmake is well present in upstream but I do not find it in conan generated package.
As conclusion I found a way to avoid issue but maybe conan could publish  package-config.cmake in zstd package or if I understand idea in conan now is to not publish  package-config.cmake and FindPackage.cmake and using cmake_find_generator ?

**Comment by danimtb** [comment]
Yes, we believe the way to go is using generators and not package build system-specific files in the packages unless they provide some kind of utility to assist consumers in some sort of task related to the library (Like CMake macros). You can read more about this here https://github.com/conan-io/conan-center-index/wiki/FAQ#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged

**Comment by jmauffray** [comment]
Thanks a lot, it is clear now. I will see if I can upgrade project with this behavior.
