### ISSUE TITLE
[package] libcurl/7.69.1: Update openssl version to 1.1.1e

### ISSUE THREAD

**Issue by dheater** [conan-io/conan-center-index#1177]
Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.69.1**

Update to `openssl-1.1.1e`

Break on `openssl-1.1.1d` because I have another package that has already update to `openssl-1.1.1e`

**Comment by Croydon** [comment]
You can override the OpenSSL version in your own conanfile by adding OpenSSL as a dependency directly

**Comment by danimtb** [comment]
https://docs.conan.io/en/latest/using_packages/conanfile_txt.html?highlight=override#overriding-requirements

**Comment by dheater** [comment]
Interesting find. It seems that the override doesn't work when the package with the transitive dependency is under `[build_requires]` instead of `[requires]` in the root package.

conanfile.txt
```
[build_requires]
cbevent/0.2@cb/stable
cblogger/0.7.0@cb/stable
cbr-protobufs/0.9.4@cb/stable
approvaltests.cpp/8.3.0
boost/1.72.0
sqlite3/3.30.1
sqlite-ee/3.27.2-1@cb/stable
libcurl/7.69.1

[requires]
openssl/1.1.1e

[generators]
cmake
````
result
```
ERROR: Conflict in sqlite-ee/3.27.2-1@cb/stable:
    'sqlite-ee/3.27.2-1@cb/stable' requires 'openssl/1.1.1d' while 'conanfile.txt' requires 'openssl/1.1.1e'.
    To fix this conflict you need to override the package 'openssl' in your root package.
```

Once I moved the `libcurl` and the other (internal) package that referenced `openssl-1.1.1e` from `[build_requires]` to `[requires], the overide works.

conanfile.txt
```
[build_requires]
cbevent/0.2@cb/stable
cblogger/0.7.0@cb/stable
cbr-protobufs/0.9.4@cb/stable
approvaltests.cpp/8.3.0
boost/1.72.0
sqlite3/3.30.1

[requires]
sqlite-ee/3.27.2-1@cb/stable
libcurl/7.69.1
openssl/1.1.1e

[generators]
cmake
````
result
```
WARN: sqlite-ee/3.27.2-1@cb/stable: requirement openssl/1.1.1d overridden by your conanfile to openssl/1.1.1e                                                                                 
WARN: libcurl/7.69.1: requirement openssl/1.1.1d overridden by your conanfile to openssl/1.1.1e     
```

This is conan version 1.23

**Comment by dheater** [comment]
For the sake of this ticket, I'm curious... What is the policy regarding updating package dependencies without `conan-center-index`?

Should I close the PR? Or should the all package that depend on `openssl` be updated when `openssl` is updated in `conan-center-index`?

**Comment by Croydon** [comment]
Please keep the PR open. OpenSSL and similar security relevant libraries should always be updated to the latest patch level

**Comment by Croydon** [comment]
PS: **Upgrading** is an entire different discussion, but the patch level should be the latest 😄
