### ISSUE TITLE
[conan.io/center] Commas not displaying correctly in package description

### ISSUE THREAD

**Issue by bshoshany** [conan-io/conan-center-index#11782]
The title for my package [`bshoshany-thread-pool`](https://conan.io/center/bshoshany-thread-pool) is defined in `conanfile.py` as follows:

```python
description = "BS::thread_pool: a fast, lightweight, and easy-to-use C++17 thread pool library"
```

However, [on ConanCenter](https://conan.io/center/bshoshany-thread-pool) it is displayed as follows:

```none
BS::thread_pool: a fast\, lightweight\, and easy-to-use C++17 thread pool library 
```

As you can see, for some reason the two commas are escaped in the title. I noticed that this happens in other packages as well, e.g. [shaderc](https://conan.io/center/shaderc) and [libxcrypt](https://conan.io/center/libxcrypt). Can this be fixed?

Thanks.

**Comment by prince-chrismc** [comment]
Going to close this a duplicate of #11317
