### ISSUE TITLE
[package] benchmark/1.6.2: invalid sha256 signature

### ISSUE THREAD

**Issue by FranzPoize** [conan-io/conan-center-index#11801]
### Package and Environment Details

* Package Name/Version: **benchmark/1.6.2**
* Operating System+version: **Linux arch**
* Compiler+version: **clang 14**
* Conan version: **conan 1.48.0**
* Python version: **Python 3.10.5**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=14
compiler.libcxx=libstdc++11
build_type=Release
compiler.cppstd=20
[options]
[conf]
[build_requires]

### Steps to reproduce

conan install --build=missing benchmark/1.6.2@

### Logs

```
ERROR: benchmark/1.6.2: Error in source() method, line 43
	tools.get(**self.conan_data["sources"][self.version], destination=self._source_subfolder, strip_root=True)
	ConanException: sha256 signature failed for 'v1.6.2.tar.gz' file. 
 Provided signature: 6adf850c2be6aa15843c94ac63d0819d5bf9f5678ae41244f25a1f4bf9480827  
 Computed signature: a9f77e6188c1cd4ebedfa7538bf5176d6acc72ead6f456919e5f464ef2f06158
```

**Comment by Croydon** [comment]
I think they might have re-tagged 1.6.2...? //@dominichamon

https://github.com/google/benchmark/commit/7a2024e961b8741ce46e83f226378b90e457ead3 might have been the original one, now it is https://github.com/google/benchmark/commit/d845b7b3a27d54ad96280a29d61fa8988d4fddcf

However, the [pull request adding this version](https://github.com/conan-io/conan-center-index/pull/11794) is newer (17h ago) than the 1.6.2 git tag/[GitHub release](https://github.com/google/benchmark/releases/tag/v1.6.2) (22h ago), so the pull request should already have used the potentially re-tagged version. Not sure what is going on here...

**Comment by Croydon** [comment]
Turns out that GitHub allows to re-tag while linked GitHub releases exist. The 1.6.2 git tag is 5h old.

**Comment by dominichamon** [comment]
this is me following bad practices as a one-off break-fix, my apologies.  i will be avoiding this completely in the future.

**Comment by SirCosty** [comment]
15 days to fix a known bug is embarrassing. What if would have been an unknown cause bug? 15 years?
