### ISSUE TITLE
[package] fmt/8.1.1: Findfmt.cmake does not declare fmt_VERSION

### ISSUE THREAD

**Issue by knzivid** [conan-io/conan-center-index#11822]
### Package and Environment Details

* Package Name/Version: **fmt/8.1.1**
* Operating System+version: **Arch Linux**
* Compiler+version: **GCC 12.1.0**
* Conan version: **conan 1.48.2**
* Python version: **Python 3.10**

The `Findfmt.cmake` file generated by `cmake_find_package` no longer sets `fmt_VERSION`.

From a build that used to work,

```
set(fmt_VERSION "8.1.1")

find_package_handle_standard_args(fmt REQUIRED_VARS
                                  fmt_VERSION VERSION_VAR fmt_VERSION)
```

becomes 

```
set(fmt_VERSION "None")
find_package_handle_standard_args(fmt REQUIRED_VARS
        fmt_VERSION VERSION_VAR fmt_VERSION)
```

using the latest conan recipe for fmt/8.1.1. Using `find_package(fmt 8.1.1 REQUIRED)` does not work but `find_package(fmt REQUIRED)` works. 

### Conan profile

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by uilianries** [comment]
@knzivid The `fmt` package was updated yesterday to be compatible with Conan 2.0, which is in Beta right now. Old generators like `cmake_find_package` and `cmake_find_package_multi` will be replaced by (CMakeDeps)[https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html].

I encourage you adopting `CMakeDeps`, which makes `fmt_VERSION` available. If you can't update it now, due your project, I suggest you using [Lockfile](https://docs.conan.io/en/latest/versioning/lockfiles/introduction.html) to keep the same old package revision in your local copy.

Anyway, it's a behavior from Conan client, not from fmt package, and will affect more and more packages in the future. I'll talk to Devs to check if is possible to keep `xxx_VERSION` available anyway.

**Comment by Flow-It** [comment]
The `pkg_config` generator has the same issue of not providing a version. Is there already an issue in the conan client project where such needs or possible alternatives/workarounds can be discussed?

**Comment by uilianries** [comment]
@Flow-It Best option is open an issue directly to https://github.com/conan-io/conan asking for such feature. As more users start to ask for something, higher is the chance to be attended soon.

**Comment by uilianries** [comment]
@Flow-It Conan 1.51.1 has been released. Now, `Findfmt.cmake` should generate `fmt_VERSION` as expected. Please, confirm.

**Comment by Flow-It** [comment]
I can't reproduce the issue with conan 1.51.1.

**Comment by knzivid** [comment]
I'm in the process of testing 1.51.1 in our CI, but feel free to close this issue.

**Comment by uilianries** [comment]
Thanks for sharing!
