### ISSUE TITLE
[package] Doxygen/1.9.2: validate() fails for consumer when the package doesn't need to be built

### ISSUE THREAD

**Issue by datalogics-kam** [conan-io/conan-center-index#11830]
### Package and Environment Details

* Package Name/Version: **Doxygen/1.9.2**
* Operating System+version: **Debian stretch**
* Compiler+version: **GCC 6**
* Conan version: **conan 1.50.0**
* Python version: **Python 3.9.7**

### Conan profile

```
Configuration:

[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=gcc
compiler.cppstd=14
compiler.libcxx=libstdc++
compiler.version=6.3
os=Linux
os_build=Linux
doxygen:arch=armv8
doxygen:build_type=Release
cmake:arch=armv8
cmake:build_type=Release
ninja:arch=armv8
ninja:build_type=Release
swig:arch=armv8
swig:build_type=Release
b2:arch=armv8
b2:build_type=Release
innoextract:arch=armv8
innoextract:build_type=Release
m4:build_type=Release
m4:arch=armv8
autoconf:build_type=Release
autoconf:arch=armv8
automake:build_type=Release
automake:arch=armv8
[options]
shared=False
shared_icu=False
[build_requires]
[env]
```

### Steps to reproduce

Build Doxygen with Clang 7.0, but try to use it as a tool from a package that uses GCC 6.

The problem is that `validate()` causes a failure, but it doesn't matter what compiler is in the profile if the goal is to consume an already-built tool package from the cache/private Conan repository.

After all, the `package_id()` says:

```
    def package_id(self):
        del self.info.settings.compiler
```

Should `validate()` be called if not building? Is this the correct use of `validate()` for a tool, or is it a Conan bug?

### Logs

<details><summary>Click to expand log</summary>

```

Build requirements
    b2/4.8.0 from 'conan-center-dl-staging' - Downloaded
    doxygen/1.9.2 from 'conan-center-dl-staging' - Downloaded

Build requirements packages
    b2/4.8.0:b0bab81756b4971d42859e9b1bc6f8b3fa8e036e - Download
    doxygen/1.9.2:INVALID - Invalid

Installing (downloading, building) binaries...

ERROR: There are invalid packages (packages that cannot exist for this configuration):
doxygen/1.9.2: Invalid ID: Compiler version too old. At least 7 is required.
script returned exit code 6```

</details>

**Comment by SpaceIm** [comment]
It's a job for `self.compatible_packages`: for compiler versions raising in validate(), add a compatible package based on the min compiler version which doesn't raise in validate().

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

I'm closing this issue as `package_id` method has been removed from this recipe. 
Also, this problem of compatibility has been addressed in `conan v2`.
In a future, when `conan v1` gets officially deprecated we will no longer need (in most of the cases) to define the `_minimum_compiler_version` attribute as it is already mapped in conan. 

Nevertheless, it is a good point, we will enforce the `minimum compiler validation` in the `validate_build` method instead of in the `validate` method.

Happy coding 🐸
