### ISSUE TITLE
[package] zlib/1.2.12: sha256 signature failed

### ISSUE THREAD

**Issue by danimasa** [conan-io/conan-center-index#11841]
### Package and Environment Details

* Package Name/Version: **zlib/1.2.12**
* Operating System+version: **Windows 10**
* Compiler+version: **Visual Studio Community 2022**
* Conan version: **conan 1.50.0**
* Python version: **Python 3.10.5**

### Conan profile

Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

After doing a clean installation in a new PC my project starts crashing. I noticed that the sha256 checksum for zlib in presenting a different value in each iteration.

### Logs

<details><summary>Click to expand log</summary>

```
zlib/1.2.12: Configuring sources in C:\Users\daniel\.conan\data\zlib\1.2.12\_\_\source
ERROR: zlib/1.2.12: Error in source() method, line 58
	tools.get(**self.conan_data["sources"][self.version],
	ConanException: sha256 signature failed for 'zlib-1.2.12.tar.gz' file. 
 Provided signature: 91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9  
 Computed signature: 808448172261707c0db580abc81a15d911d6aec9defd9a89732c5ad5f6d3fedb
```

</details>

**Comment by uilianries** [comment]
@danimasa I can not reproduce your error, on Windows, Linux and OSX. Including on CI. I have to say it's something related to your environment not zlib.

You can do a direct test, Conan does not change anything related to the downloaded package, so you can download it:


```
λ wget https://zlib.net/fossils/zlib-1.2.12.tar.gz
--2022-07-22 11:27:31--  https://zlib.net/fossils/zlib-1.2.12.tar.gz
Resolving zlib.net (zlib.net)... 85.187.148.2
Connecting to zlib.net (zlib.net)|85.187.148.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1490071 (1.4M) [application/x-gzip]
Saving to: 'zlib-1.2.12.tar.gz'

zlib-1.2.12.tar.gz                                          100%[=========================================================================================================================================>]   1.42M  1.02MB/s    in 1.4s

2022-07-22 11:27:34 (1.02 MB/s) - 'zlib-1.2.12.tar.gz' saved [1490071/1490071]
λ sha256sum.exe zlib-1.2.12.tar.gz
91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9 *zlib-1.2.12.tar.gz
```

We have few projects which the checksum change for each download, usually, when they are downloaded from old Google source repository. They attach the timestamp to the generated tar file, which makes an unique checksum for each file.

Your problem should be more related to your network. Please, check it.

**Comment by danimasa** [comment]
I did the same process locally and the checksum was correct. Only running conan the problem appers, and only for this package.

Is there some cache being used? Can I overwrite the downloaded file with one that has the correct checksum? 

I don't understand why it keeps showing differents checksums

**Comment by uilianries** [comment]
You can try by removing your local cache for zlib:

    rmdir /s %USERPROFILE%/.conan/data/zlib

**Comment by danimasa** [comment]
I removed the cache but it didn't resolve.

Really the file downloaded was corrupted, I replaced the file in the folder and the checksum passed. Probably it was a cache in the proxy that was responding always with a corrupted file.

**Comment by sburton84** [comment]
There definitely seems to be some sort of problem here as I'm getting a lot of errors similar to this on our CI:
```
zlib/1.2.13: Configuring sources in C:\Users\runneradmin\.conan\data\zlib\1.2.13\_\_\source\src
ERROR: zlib/1.2.13: Error in source() method, line 51
	get(self, **self.conan_data["sources"][self.version],
	ConanException: sha256 signature failed for 'zlib-1.2.13.tar.gz' file. 
 Provided signature: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30  
 Computed signature: ed2aea0f72342d2f4ccd16573d91681ac06dc61b68a77db31104cfa7d7cdc1fb
```
Is there an issue with the server this file is downloaded from producing corrupted files? The error is frequent but intermittent, rerunning the build usually succeeds. It only seems to happen on our Windows build as well.

**Comment by farhadarab** [comment]
Hi every one.
I am trying to run curaengine from source code. I received this error too. I tried every thing: remove conan, remove data on conan but none of them help me. please help me if you have a solution for this buggggggggggg.
