### ISSUE TITLE
[conan.io/center] Markdown failed `cxxopts/3.0.0@#abceb30be06273a9a68eaabdfc454e87`

### ISSUE THREAD

**Issue by re2bit** [conan-io/conan-center-index#11849]
Reported as asked for.
"Markdown generator failed for reference 'cxxopts/3.0.0@#abceb30be06273a9a68eaabdfc454e87'. Please report [here]."

Page: https://conan.io/center/cxxopts?tab=useit&os=

**Comment by jgsogo** [comment]
fixed
