### ISSUE TITLE
[conan.io/center] Markdown failed `gtest/cci.20210126@#781d1fed9d992ffb25140aea029ee472`

### ISSUE THREAD

**Issue by CayOest** [conan-io/conan-center-index#11845]
conan install fails when I try to install gtest

![image](https://user-images.githubusercontent.com/61513085/180269919-f4ffc962-32ff-4f7a-a971-28449cc1e403.png)

**Comment by CayOest** [comment]
Sorry, the screenshot is for gtest/1.8.1, but no version of gtest works

**Comment by uilianries** [comment]
@CayOest You are asking for Visual Studio 2022 (17) packages, which are not available yet on Conan Center. Please, take a look on the supported configuration first: https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md

Please, follow the issue https://github.com/conan-io/conan-center-index/issues/8795
