### ISSUE TITLE
[conan.io/center] Markdown failed `qt/6.3.1@#818588ac8618e90e4916d1ffdfd3d48d`

### ISSUE THREAD

**Issue by Sofahamster** [conan-io/conan-center-index#11865]
There's something wrong with the release/debug builds in the QT recipe.
If you try and build a Qt Designer plugin, it will only work if the Qt recipe is installed as a debug build. If you install Qt as a release build, the (as release) compiled plugin will fail to load with an error message indicating that release- and debug-builds can't be mixed. 

Expected outcome: `conan install -s build_type=release --build=qt` should compile the tools (Designer, Linguist, etc.) as release builds, so that plugins in release mode are actually compatible.

**Comment by jgsogo** [comment]
We are working on a new implementation of the web that will generate again all these files
