### ISSUE TITLE
[openssl] failed to build openssl/v1.0.2s for armv7

### ISSUE THREAD

**Issue by n-bes** [conan-io/conan-center-index#1190]
### Description of Problem, Request, or Question
**ar** wrong prefix

```
arm-linux-gnueabi-arm-linux-gnueabi-ar \
   r ../libcrypto.a cryptlib.o mem.o mem_dbg.o cversion.o ex_data.o cpt_err.o ebcdic.o uid.o o_time.o o_str.o o_dir.o o_fips.o o_init.o fips_ers.o getenv.o armcap.o armv4cpuid.o
make[1]: arm-linux-gnueabi-arm-linux-gnueabi-ar: Command not found
Makefile:106: recipe for target '../libcrypto.a' failed
```

### Environment Details
Any **conanio/gcc-*-armv7** docker image

### Steps to reproduce (Include if Applicable)
```
cd recipes/libpq/all
conan create . libpq/11.5@dev/testing --build=missing -tf=None -owith_openssl=True
```

### Build logs (Include if Available)
[job.log](https://github.com/conan-io/conan-center-index/files/4388480/job.log)

### Additional information
```openssl/1.1.1d``` not affected

**Comment by n-bes** [comment]
Also, from log.
```
Configured for linux-armv4.
```
Should i setup profile?

**Comment by SSE4** [comment]
duplicates #940
