### ISSUE TITLE
[question] which url to use for not so maintained projects

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#1194]
Wanted to make conan deps ready for https://github.com/openthread/ot-commissioner/issues/17

Now cn-cbor was forked by someone and the ot-commissioner folks forked it again
Now i’l like to submit the first fork as it is maintained e.g. https://github.com/jimsch/cn-cbor/tree/complete

What are the guidelines in cci for this?

**Comment by danimtb** [comment]
Hi @gocarlos,

I have no experience with the library you mention and I am not into the details of why it was forked. Maybe the way to go is by asking the authors about what repo should be considered the official?

**Comment by gocarlos** [comment]
https://github.com/cabo/cn-cbor/issues/60

**Comment by danimtb** [comment]
Closing this one as #1313 got merged 😄
