### ISSUE TITLE
[package] boost/ALL: ImportError in conanfile.py

### ISSUE THREAD

**Issue by nilsnolde** [conan-io/conan-center-index#11955]
### Package and Environment Details

* Package Name/Version: **boost/all**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 9**
* Conan version: **conan 1.43.0**
* Python version: **Python 3.8**

### Steps to reproduce

Install any boost version with conan==1.43.0 and an `ImportError` is raised:
```
#14 2.116   File "/root/.conan/data/boost/1.71.0/_/_/export/conanfile.py", line 1, in <module>
#14 2.116     from conan.tools.build import cross_building
#14 2.116 ImportError: cannot import name 'cross_building' from 'conan.tools.build' (/usr/local/lib/python3.8/dist-packages/conan/tools/build/__init__.py)
```

seems like [a recent change](https://github.com/conan-io/conan-center-index/commit/abf40e34637400c5c3f625d230098bfaee39bc06#diff-cc14160728d1ad321c1444ffad82615139181e681f4acb7dfd045a005cc8bd66) to the `conanfile.py` introduced that. the conanfile.py says it's valid down until v1.43.0, however that import wasn't introduced until [1.43.4 or so](https://github.com/conan-io/conan/pull/10536/files#diff-74272a6f8877a3af1e97d287b5e9169050b4c836c436d7d3779cb6842dacef65).

### Logs

<details><summary>Click to expand log</summary>

</details>

**Comment by jwillikers** [comment]
I think the new import actually requires Conan 1.47.0. Conan 1.46.0 made it possible to import via `from conan.tools.build.cross_building import cross_building` which is slightly different from the path used here. The minimum required version should have been updated. I made that change due to a build error in the lint checks that would fail the build if the new import wasn't used.

**Comment by nilsnolde** [comment]
> I think the new import actually requires Conan 1.47.0
1.46 & 1.47 are the same, at least in their release branches: https://github.com/conan-io/conan/blob/release/1.47/conan/tools/build/__init__.py

you could've used `from conan.tools.build.cross_building import cross_building` directly in the conanfile.py, but `from conan.tools.build import cross_building` is still shorter;)
