### ISSUE TITLE
[conan.io/center] Markdown failed `sdbus-cpp/1.1.0@#991e65045d1f79b46d524706981394ed`

### ISSUE THREAD

**Issue by lvmaximlv** [conan-io/conan-center-index#11960]
When I try to open "Use it" tab for the https://conan.io/center/sdbus-cpp?tab=useit I get this kind of error: Markdown generator failed for reference 'sdbus-cpp/1.1.0@#991e65045d1f79b46d524706981394ed'.

**Comment by jgsogo** [comment]
fixed
