### ISSUE TITLE
[request] sdl/2.0.22

### ISSUE THREAD

**Issue by conr2d** [conan-io/conan-center-index#11971]
### Package Details
  * Package Name/Version: **sdl/2.0.22**
  * Changelog: **https://github.com/libsdl-org/SDL/releases/tag/release-2.0.22**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by jgsogo** [comment]
@conr2d , you can contribute the PR yourself. Adding a new version is very easy, you just need to modify a couple of files with metadata and the recipe should just work (given it is a patch version)

Thanks!

**Comment by zaslavskyv** [comment]
JFYI: there was a cross-building problem last time 2.0.22 was attempted — https://github.com/conan-io/conan-center-index/pull/10620

**Comment by tomconder** [comment]
There is existing PR in progress: https://github.com/conan-io/conan-center-index/pull/12186

**Comment by czoido** [comment]
Thanks for reporting, closing as newer versions are already in Conan Center.
