### ISSUE TITLE
[package] sdl_mixer/2.0.4: missing include directory

### ISSUE THREAD

**Issue by conr2d** [conan-io/conan-center-index#11972]
### Package and Environment Details

* Package Name/Version: **sdl_mixer/2.0.4**

### Steps to reproduce

Other SDL-related packages support including header from root or `SDL2/`.

For example, `SDL.h` can be included by:
``` c
#include <SDL2/SDL.h>
// or
#include <SDL.h>
```

[sdl](https://github.com/conan-io/conan-center-index/blob/master/recipes/sdl/all/conanfile.py#L388):
``` python
        self.cpp_info.components["libsdl2"].includedirs.append(os.path.join("include", "SDL2"))
```

[sdl_image](https://github.com/conan-io/conan-center-index/blob/master/recipes/sdl_image/all/conanfile.py#L135):
``` python
        self.cpp_info.includedirs.append(os.path.join("include", "SDL2"))
```

Unlike `sdl` or `sdl_image`, `sdl_mixer` replaces includedirs rather than appends.

[sdl_mixer](https://github.com/conan-io/conan-center-index/blob/master/recipes/sdl_mixer/all/conanfile.py#L139):
``` python
        self.cpp_info.includedirs = [os.path.join("include", "SDL2")]
```

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by SpaceIm** [comment]
I would say sdl & sdl_image recipes are too permissive, since official way to include SDL2 headers is `#include <SDL.h>` only.

**Comment by paulocoutinhox** [comment]
@conr2d i have added a PR:
https://github.com/conan-io/conan-center-index/pull/11973

**Comment by jgsogo** [comment]
As #11973 has been merged, I'm closing this issue.
