### ISSUE TITLE
[service] Header only option?

### ISSUE THREAD

**Issue by lasote** [conan-io/conan-center-index#120]
Some libraries, like boost, could have or have an option to create a package with only "header_only" we currently don't have a mechanism to take into account that option to generate the binary package corresponding to the `header_only` option. 

Should we?
Could it be confusing?

**Comment by Croydon** [comment]
Examples:

https://github.com/bincrafters/conan-kfr/blob/9accdb69d29f7ac2b7580030539d6b0d7765047a/conanfile.py#L18
https://github.com/bincrafters/conan-kfr/blob/9accdb69d29f7ac2b7580030539d6b0d7765047a/build.py#L9


https://github.com/bincrafters/conan-pugixml/blob/713d88a2eede204c5591454e2f1ad9aa20b0c783/conanfile.py#L26
https://github.com/bincrafters/conan-pugixml/blob/713d88a2eede204c5591454e2f1ad9aa20b0c783/build.py#L10


https://github.com/bincrafters/conan-fmt/blob/59c3f64ed0373d604847f855146fd1fdb53710b5/conanfile.py#L20
https://github.com/bincrafters/conan-fmt/blob/59c3f64ed0373d604847f855146fd1fdb53710b5/build.py#L22

https://github.com/bincrafters/conan-msgpack/blob/4a915d0e49a879310bbe3168691931af9b478557/conanfile.py#L20
https://github.com/bincrafters/conan-msgpack/blob/64f7a5637211ad329c044d44d0d6471cec5af42b/build.py#L11

________

We could give the `header_only` option a similar standardized special role as `shared`, i.e. tooling does react on this option accordingly and does add an extra build for header-only

**Comment by danimtb** [comment]
This feature was completed and now packages that have a `header_only` option are generated as stated in the wiki https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations
