### ISSUE TITLE
[package] stb/cci.20210910: Minimal example does not work (.cmake file not found)

### ISSUE THREAD

**Issue by andreastedile** [conan-io/conan-center-index#12036]
### Package and Environment Details

* Package Name/Version: **stb/cci.20210910**
* Operating System+version: **Fedora 36**
* Compiler+version: **gcc version 12.1.1**
* Conan version: **conan 1.50.0**
* Python version: **Python 3.10.5**

### Conan profile

Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conanfile.txt
```
[requires]
stb/cci.20210910

[generators]
cmake_find_package
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.14)
project(stbtest CXX)

find_package(stb REQUIRED)

add_executable(app main.cpp)
target_link_libraries(app stb::stb)
```

main.cpp
```
#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>

int main() {
    return 0;
}
```

### Logs

<details><summary>Click to expand log</summary>

```
$ mkdir build && cd build
$ conan install --build=missing ..
$ cmake ..
```

CMake's output is: 
```
-- The CXX compiler identification is GNU 12.1.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "Findstb.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "stb", but
  CMake did not find one.

  Could not find a package configuration file provided by "stb" with any of
  the following names:

    stbConfig.cmake
    stb-config.cmake

  Add the installation prefix of "stb" to CMAKE_PREFIX_PATH or set "stb_DIR"
  to a directory containing one of the above files.  If "stb" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/steddy/temp/b/CMakeFiles/CMakeOutput.log".
```

</details>

**Comment by SpaceIm** [comment]
- It's not a conan-center-index issue, your example can't work because there is no glue generator (like `CMakeToolchain` or `cmake`) or manual injection of CMAKE_MODULE_PATH.
- `target_link_libraries(stb REQUIRED)` is invalid CMake syntax.

**Comment by andreastedile** [comment]
> is invalid CMake syntax

My bad, I fixed the CMakeLists.txt: `target_link_libraries(app stb::stb)`.

I must admit I have not enough experience to fully understand what a "glue generator" is, but I have been able to overcome the issue by taking a closer look at the [documentation]: (https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html#in-a-conanfile-txt).
I simply added the line `include(${CMAKE_BINARY_DIR}/conan_paths.cmake)` in the top-level CMakeLists.txt, and now everything works. Thanks for your input nonetheless.

**Comment by SpaceIm** [comment]
Modern approach is:

CMakeToolchain + CMakeDeps generators

then when you call CMake in command line, you add `-DCMAKE_TOOLCHAIN_FILE=<path/to/conan_toolchain.cmake>`. It avoids to hardcode conan specific stuff in your CMakeLists like `include(${CMAKE_BINARY_DIR}/conan_paths.cmake)`.
