### ISSUE TITLE
[conan.io/center] sqlite3/3.39.2: Can't find SQLite3 using CMake with `cmake_paths` generator

### ISSUE THREAD

**Issue by tuduongquyet** [conan-io/conan-center-index#12040]
### Package and Environment Details

* Package Name/Version: **sqlite3/3.39.2**
* Operating System+version: **Windows 10**
* Compiler+version: **MSVC 19**
* Python version: **Python 3.10.5**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

- Create `conanfile.txt`
```
[requires]
sqlite3/3.39.2

[generators]
cmake_paths

[options]
*:shared=True

```
- And simple program
```
cmake_minimum_required(VERSION 3.15)
project(sqlite3_project C)

find_package(SQLite3 REQUIRED)

add_executable(${PROJECT_NAME} main.c)

# Use the global target
target_link_libraries(${PROJECT_NAME} SQLite::SQLite3)
```

```
#include <sqlite3.h>

int main() {
    printf("SQLite Version: %s\n", sqlite3_libversion());
    return 0;
}
```
- Build commands
```
conan install .. --build missing
cmake .. -DCMAKE_TOOLCHAIN_FILE=".\conan_paths.cmake"
```
- Error Log
```
-- Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY) 
```

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by SpaceIm** [comment]
@uilianries
Can be closed. Fixed by https://github.com/conan-io/conan-center-index/pull/12078 and/or https://github.com/conan-io/conan/pull/11883

**Comment by uilianries** [comment]
Thank you @SpaceIm !!
