### ISSUE TITLE
[package] clipper/4.10.0: Error in source() method

### ISSUE THREAD

**Issue by ShenMian** [conan-io/conan-center-index#12064]
### Package and Environment Details

* Package Name/Version: **clipper/4.10.0**
* Operating System+version: **Linux Ubuntu 20.04.4 LTS** and **Microsoft Windows Server 2022 10.0.20348 Datacenter**
* Compiler+version: **Clang 13**
* Conan version: **conan 1.51.0**

### Conan profile

I use the default profile.

### Steps to reproduce

1. My [Conanfile](https://github.com/ShenMian/Graphics/blob/78eef3b1d97a375a1644dad51fdc94b3d98349a4/conanfile.txt)->assimp->cliper.
2. Run [script](https://github.com/ShenMian/Graphics/blob/3a82c2d0c0c8b98c8218b464ea3eaaf86b7fae7d/Scripts/build.sh), [Full github workflow file](https://github.com/ShenMian/Graphics/blob/bd8708e667df5cf7c3d3a0ba511852ae2f369f17/.github/workflows/ubuntu.yml).

I have tried to run the workflow again, but the problem still exists. This problem has not occurred before.  

### Logs

<details><summary>Click to expand log</summary>

Ubuntu:  

```
WARN: Remotes registry file missing, creating default one in /home/runner/.conan/remotes.json
WARN: imguizmo/cci.20210223: requirement imgui/1.82 overridden by your conanfile to imgui/cci.20220621+1.88.docking 
ERROR: clipper/4.10.0: Error in source() method, line 50
	tools.get(**self.conan_data["sources"][self.version], destination=self._source_subfolder)
	NotFoundException: Not found: https://sourceforge.net/projects/polyclipping/files/Older%20versions/clipper_ver4.10.0.zip
```

Windows:  

```
WARN: Remotes registry file missing, creating default one in C:\Users\runneradmin\.conan\remotes.json
WARN: imguizmo/cci.20210223: requirement imgui/1.82 overridden by your conanfile to imgui/cci.20220621+1.88.docking 
-- Compiler is not EMSCRIPTEN
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY


CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY


ERROR: clipper/4.10.0: Error in source() method, line 50
	tools.get(**self.conan_data["sources"][self.version], destination=self._source_subfolder)
	NotFoundException: Not found: https://sourceforge.net/projects/polyclipping/files/Older%20versions/clipper_ver4.10.0.zip
```

Full workflow log files:  

- Ubuntu: [logs_1892.zip](https://github.com/conan-io/conan-center-index/files/9267351/logs_1892.zip).
- Windows: [logs_1893.zip](https://github.com/conan-io/conan-center-index/files/9267545/logs_1893.zip).

</details>

**Comment by uilianries** [comment]
@ShenMian The release 4.10.0 has been removed from the upstream: https://sourceforge.net/p/polyclipping/code/HEAD/tree/tags/

I recommend you using the latest version available in Conan Center: https://conan.io/center/clipper

We will need to drop the version 4.10.0, but you still could ask to the author about the missing version, if you really need it.

**Comment by SpaceIm** [comment]
assimp depends on 4.10.0, this version can't be removed in cci.

**Comment by SpaceIm** [comment]
https://sourceforge.net/p/polyclipping/bugs/214/

**Comment by jgsogo** [comment]
Packages/recipe won't be removed from CCI, so consumers will keep working (**only for existing configurations** aka package-ids). The problem is that we won't be able to build that reference from sources and consumers will be blocked if we create a PR that triggers new configurations 🧨 

If we manage to get the sources from those versions, we can store them as we do with `gsoap` (check https://github.com/conan-io/conan-center-index/blob/master/recipes/gsoap/all/conandata.yml) so everything keeps working.

So please, @ShenMian , if you manage to talk with the library maintainer, it would be great to restore those files.

**Comment by marcusl** [comment]
I'm working on a fix in #12291

**Comment by marcusl** [comment]
I've also emailed the author @AngusJohnson about restoring the files, but I did manage to get the source from svn history, so there's hope.

**Comment by jgsogo** [comment]
Is the SVN repository available? Can you point us in the right direction so we can get those sources as well?

**Comment by SpaceIm** [comment]
Already tested in other PR, the link generated by sourceforge is not persistent, and does not even generate a tarball with a reproducible hash.
Is it possible to put this tarball in c3i?

**Comment by jgsogo** [comment]
Sure, the only thing we need to do is to download the tarball ourselves and upload it to our repository. I though the sources were completely missing, but if we can download them, it is not a problem, we can follow the same approach we did for `gsoap`

**Comment by SpaceIm** [comment]
The original tarball is not available anymore, but you can generate one from sourceforge and upload it in c3i.

**Comment by AngusJohnson** [comment]
Hi. I'm the author of Clipper and the culprit for removing these files from SourceForge's server😱. 
And my apologies for the inconvenience this has evidently caused. 

Until the very recent release of [Clipper2](https://github.com/AngusJohnson/Clipper2), the previous stable realease of what I'm now calling Clipper1 was about 7 years ago (ver 6.4.2). My presumption was that pretty much everyone would have updated to that version. And I've now deleted these very old versions from my own PC, and  even my backups going back 2 yrs no longer have them. I had no idea that there would still be some using a build that was so old. (I certainly understand leaving code untouched in archived projects, but I don't understand why these source files aren't stored locally and why they'd still need to be accessed from SourceForge.)

Anyhow if someone has several of these zips files, I'd be happy to upload them again to SourceForge. Cheers Angus

**Comment by marcusl** [comment]
SVN repo at sourceforge is at https://sourceforge.net/p/polyclipping/code/HEAD/tree/

I am currently hosting the source in zips here: https://github.com/marcusl/clipper-archive and then just trying to learn conan enough to test this. The zips have a top-level dir which I need to remove. Work in progress!

**Comment by AngusJohnson** [comment]
> The zips have a top-level dir which I need to remove. Work in progress!

OK, once that's done, and I've downloaded these patched files, is there anything special I need to do at SourceForge? I do remember I stored them in a subfolder but don't remember what I named it. I guessing that that's important too.

**Comment by marcusl** [comment]
https://github.com/marcusl/clipper-archive <- 4.10.0 builds with conan  recipe . Not the 5.1.6 for some reaosn.

For now, just restore the 4.10.0 zip from my link above to Older%20versions/clipper_ver4.10.0.zip"

**Comment by AngusJohnson** [comment]
I've also just now uploaded clipper_ver5.1.6.zip but according to Marcus there's a problem with that package.

**Comment by marcusl** [comment]
Yeah, maybe the old 5.1.6 zip wasn't from the same revision that I pulled (it wasn't explicitly tagged, so I made an educated guess based on contents and commit comment). So, to get 5.1.6 back the conan recipe and/or the zip needs to be tweaked further, but I don't know how to proceed, and 4.10.0 is what assimp needs, so I'm happy with getting that running.

Someone added the 5.1.6 support to conan, so at onetime, someone was using that.

The SHA256 of my zip doesn't match the one in conan's recipe index, so I've resurrected my PR and am waiting for build access.

**Comment by marcusl** [comment]
Should be solved now. Ping if not! :)

**Comment by KonradNoTantoo** [comment]
I had a closely related issue, so I'm posting the workaround here for anyone else who might stumble upon it.

The root cause is that I still had a bad clipper package in local cache. I had to purge that with ```conan remove``` before I could benefit from the fix discussed here.

Thanks for the fix!

**Comment by SpaceIm** [comment]
There is still an issue in 5.1.6, source code is different than previous tarball downloaded by conan-center: https://github.com/conan-io/conan-center-index/pull/13530#issuecomment-1280072668

**Comment by marcus-sonestedt** [comment]
This broke again.

**Comment by marcus-sonestedt** [comment]
Seems like SF is in some temporary static offline mode right now. Hopefully it comes back up.

(Also, mental note for me: I should get conan caching sorted on our own CI docker containers to not pull this for every build.)
