### ISSUE TITLE
[package] fmt/9.0.0: Unable to load conanfile

### ISSUE THREAD

**Issue by ShenMian** [conan-io/conan-center-index#12086]
### Package and Environment Details

* Package Name/Version: **fmt/9.0.0**
* Operating System+version: **Windows 11 Pro 21H2**
* Compiler+version: **MSVC 19.33.31629**
* Conan version: **Conan version 1.50.0**
* Python version: **Python 3.10.6**

### Conan profile

```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce

Try installing fmt/9.0.0.  
I used to use fmt/8.1.1, everything is fine. But when I changed to fmt/9.0.0, conan will report this error.  

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: fmt/9.0.0: Cannot load recipe.
Error loading conanfile at 'C:\Users\sms\.conan\data\fmt\9.0.0\_\_\export\conanfile.py': Unable to load conanfile in C:\Users\sms\.conan\data\fmt\9.0.0\_\_\export\conanfile.py
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\sms\.conan\data\fmt\9.0.0\_\_\export\conanfile.py", line 5, in <module>
    from conan.tools.scm import Version
ModuleNotFoundError: No module named 'conan.tools.scm'
```

</details>

**Comment by uilianries** [comment]
@ShenMian It may be related to https://github.com/conan-io/conan/issues/11681

Please, update to Conan 1.51.0 and feedback us.

**Comment by ShenMian** [comment]
It seems that the error no longer exists, but it still throws a warning.  

```
WARN: Migration: Updating settings.yml
fmt/9.0.0: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
```

**Comment by uilianries** [comment]
@ShenMian Thank you for sharing! I'm glad that worked for you.
