### ISSUE TITLE
[question] Packaging fmtlib

### ISSUE THREAD

**Issue by ngrodzitski** [conan-io/conan-center-index#121]
Why fmt recepie removes cmake directory?

https://github.com/conan-io/conan-center-index/blob/a34458e886d2b5c1d0e3a091a559d281644631d5/recipes/fmt/all/conanfile.py#L69

With `fmt/5.3.0@bincrafters/stable` I was able to use `find_package( fmt 5.3.0 REQUIRED )` in cmake. Trying to upgrade to `fmt/6.0.0` breaks my cmake usage logic.

So what is the idiomatic way to introduce fmtlib in one's cmake project now?

**Comment by danimtb** [comment]
We know that using find_package and relying on the CMake behavior to find the dependencies is something that should be avoided in favor of the information provided by the package manager. 

Conan has an abstraction over the packages build system and description by using generators. Those generators translate the information of the dependency graph and create a suitable file that can be consumed by your build system.

In the past, we have found that the logic of some of the find and config files lead to broken scenarios with other dependencies and hardcoded paths that would make the package broken when shared and consumed.

Thus, we think that Conan already provides ways to consume those packages in the same way by using `cmake_find_package` generator: https://docs.conan.io/en/latest/reference/generators/cmake_find_package.html
That way all the information is consistent in the graph and you also point to the exact dependency package you want to use.

Please take a look at the integrations section to learn how to use it: https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html

Finally, by not allowing these files (and others such as pkg-config) we make packages agnostic to the consumer as the logic of those files is not in the package but in the way the consumer wants the information.

**Comment by danimtb** [comment]
As this might be a recurrent question, I have added this to the FAQ section of the wiki: https://github.com/conan-io/conan-center-index/wiki/FAQ#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged

**Comment by ngrodzitski** [comment]
Thanks for clarification. 
Consider it closed.

Wjile this approach definitely works, there might be some issues while migrating to it, I've got the following issue with gtest. I introduce it as following: 
```
find_package( GTest 1.8.0 REQUIRED)
```
And got en error:
```
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY) (Required is at least version "1.8.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.15/Modules/FindGTest.cmake:197 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:60 (find_package)
```

Using `find_package( gtest 1.8.0 REQUIRED)` avoids this issue.

**Comment by danimtb** [comment]
Yes, this is something we are aware of and recently introduced a new field for recipes to declare a different name that can be later used by those generators.

In the case of the requirement of `gtest/<version>`, the recipe could declare:

```
    ...
    def package_info(self):
        self.cpp_info.name = "GTest"
        ...
```

The generator will pick that name and something like `find_package(GTest <version> REQUIRED)` should just work 😄

Check `self.cpp_info.name` here https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info for more information

**Comment by jargonzombies** [comment]
@danimtb Could you please elaborate your answer regarding config files? The technical reason why config files are disavowed is not clear to me from the FAQ or the text here. Could you maybe provide some links to past issues?

**Comment by uilianries** [comment]
@jagansubramanian please take a look in https://github.com/conan-io/conan/issues/6269#issuecomment-570182130
