### ISSUE TITLE
[question] export all versions of a package or all packages in a folder 

### ISSUE THREAD

**Issue by WilliamBehrens** [conan-io/conan-center-index#12104]
I'm currently trying to setup a sort of mirror to the conan center index for use internally at a company. I have a directory structure similar to that of the conan center index and I'm using Jenkins for CD/CI. I've tried to have a Jenkins pipeline that parses all packages and package versions but it doesn't seem to work(an issue with Jenkins yaml parsing) so I thought I'd ask how it's done for conan center index? is there an easier way to export/create all the packages in a folder or even just all the versions of a recipe?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
@WilliamBehrens The true is Conan Center Index has an internal Jenkins library, which is a private project for now. So far, there is some documentation helping to integrate Jenkins with Conan: https://docs.conan.io/en/latest/integrations/ci/jenkins.html#jenkins-integration.

Answering your question shortly: No. You will need to implement a job which visits each folder and export each recipe.

**Comment by jgsogo** [comment]
@WilliamBehrens , as said before, nothing is provided from Conan/ConanCenter in this regard, you will need to write your own scripts to call Conan commands for every reference in your repository.

Just one piece of advice: as references depend on each other, it is easier if you first `conan export` all references and then you `conan install <reference> --build=missing` that way you can be sure that all references are available in your local cache. Of course, building times will be quite long, and depending on the number of configurations you are building you might need to implement some logic to trigger the builds in order so you can easily resume the process if something goes wrong.

I'm closing this issue, it's beyond the scope of CCI to provide these internal pipelines at the moment.

Thanks!
