### ISSUE TITLE
[request] GLFW/3.3.8 split into wayland and X11 versions

### ISSUE THREAD

**Issue by cchulo** [conan-io/conan-center-index#12117]
### Package Details
  * Package Name/Version: **glfw-x11/3.3.8** and **glfw-wayland/3.3.8**
  * Website: **https://www.glfw.org**
  * Source code: **https://github.com/glfw/glfw**

### Description Of The Library / Tool
There already exists GLFW, however it is compiled for X11. There are instructions for compiling for Wayland specifically. Most package managers now have this differentiation too (`glfw-x11` vs `glfw-wayland`)

Instructions for how to compile both variants can be found here: https://www.glfw.org/docs/latest/compile.html 

It sounds like we could just take the existing GLFW recipe and just change the dependencies to wayland to create the `glfw-wayland` variant.

**Comment by jgsogo** [comment]
Looks like an option for the `glfw` recipe, right?

**Comment by cchulo** [comment]
@jgsogo would this be simple change to the existing recipe? I wouldn't mind dipping in when I have the spare chance. I do wonder though: if I were to consume GLFW in my project with conanfile.txt, how would I be able to toggle between X11 and Wayland?

**Comment by jgsogo** [comment]
@cchulo , you can specify options in the `conanfile.txt` for your requirements:

```ini
[requires]
glfw/3.3.8

[options]
glfw:with_x11=True
```

Maybe `with_x11` is not the best name for that option and something like `backend` with values `x11` or `wayland` is more accurate... I don't have enough knowledge about the library to suggest a proper naming.

**Comment by cchulo** [comment]
@jgsogo i've been doing a bit of research into recipes and I think I got it, will look into making a pull request soon (unless someone beats me to it)
