### ISSUE TITLE
Failed `opencv/4.5.5@#18b6d4ea69d84464117246c73e814cbe`

### ISSUE THREAD

**Issue by anirul** [conan-io/conan-center-index#12126]
Couldn't make it work under Windows 11 in release mode. Some library doesn't build in this configuration libvpx imported from libffmpeg.

**Comment by jcar87** [comment]
Hi @anirul  - thanks for reporting this issue.

Could you provide more details about the Conan profile you are using, the Visual Studio version, and the command you are running so that we can try and replicate it from our end? Thanks!

**Comment by anirul** [comment]
Yes of course! I can try at least!

First sorry for the delay...

I m on windows 11 Home 21H2 OS build: 22000.856
conan version 1.50.0 (but it was affecting it since 1.47.x
And my crash seams to be a redifinition of TMP in  the build of libvpx (version 1.11.0) imported by OpenCV v4.5.5
```cmd
Item has already been added. Key in dictionary: 'TMP'  Key being added: 'tmp' [C:\users\frede\.conan\data\libvpx\1.11.0\_\_\build\d94be2eba52b158491477da31dd9925017bc6459\vpx.vcxproj]
```
I this this is the point of failure. I tried to reach preple from libvpx but windows is not their priority.

Tell me if you need any more help!

**Comment by jgsogo** [comment]
Regarding the markdown generated for the web: we are working on a new implementation of all the web, and it will regenerate all these files
