### ISSUE TITLE
[package] boost/1.7X.0: Using conan.tools.scm.Version breaks install with python & numpy

### ISSUE THREAD

**Issue by buddly27** [conan-io/conan-center-index#12137]
### Package and Environment Details

* Package Name/Version: **boost/1.70.0**, **boost/1.77.0**, **boost/1.79.0**
* Operating System+version: **Linux Ubuntu 20.04.2**
* Compiler+version: **GCC 9**
* Conan version: **conan 1.50.0**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

```
git clone https://github.com/conan-io/conan-center-index.git
cd conan-center-index/recipes/boost/all
conan create conanfile.py boost/1.79.0@ --options=boost:without_python=False
```

When installing any versions of boost after [this commit](https://github.com/conan-io/conan-center-index/commit/c6cddd31398abb61a5638d1b08bb9c233b9578dc), it fails to recognize that `boost_numpy38` and `boost_python38` are installed.

This is because these two dependencies are defined as follows:
* `boost_python{py_major}{py_minor}`
* `boost_numpy{py_major}{py_minor}`

Python version is being fetched [here](https://github.com/conan-io/conan-center-index/blob/c6cddd31398abb61a5638d1b08bb9c233b9578dc/recipes/boost/all/conanfile.py#L1575), but string format results in:
* `boost_python<bound method Version.major of '3.8'><bound method Version.minor of '3.8'>`
* `boost_numpy<bound method Version.major of '3.8'><bound method Version.minor of '3.8'>`

But even by modifying the code to properly call the method, we don't end up with expecting names:
* `boost_python3.Y.Z3.8.Z`
* `boost_numpy3.Y.Z3.8.Z`

Hence libraries are still flagged as missing.

Maybe the [conan.tools.scm.Version](https://docs.conan.io/en/latest/reference/conanfile/tools/scm/other.html#version) object which is defined as "experimental and subject to breaking changes" should not be used for now.

### Logs

<details><summary>Click to expand log</summary>

```
boost/1.79.0: WARN: Boost component 'numpy' is missing libraries. Try building boost with '-o boost:without_numpy'. (Option is not guaranteed to exist)
boost/1.79.0: WARN: Boost component 'python' is missing libraries. Try building boost with '-o boost:without_python'. (Option is not guaranteed to exist)
ERROR: boost/1.79.0: Error in package_info() method, line 1663
raise ConanException("These libraries were built, but were not used in any boost module: {}".format(non_used))
ConanException: These libraries were built, but were not used in any boost module: {'boost_numpy38', 'boost_python38'}```

</details>

**Comment by uilianries** [comment]
@buddly27 It has been fixed yesterday: https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py#L1579

Please, update your local copy and build again.

**Comment by buddly27** [comment]
@uilianries Great timing, thanks!

But is that a good call to use an experimental feature in this recipe to start with? Wouldn't it be wise to wait for [conan.tools.scm.Version](https://docs.conan.io/en/latest/reference/conanfile/tools/scm/other.html#version) to be stable?

**Comment by uilianries** [comment]
Ir will be change on next release due a bug, but it's not the usual case. Conan 1.x can break a behavior, so new features are released as experimental to keep open, but usually we forget to move to stable.

**Comment by buddly27** [comment]
Sounds good then, thanks for the quick reply!
