### ISSUE TITLE
[bug] Today's release 1.51.2 breaks boost/1.79.0

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan-center-index#12159]
* Conan version: 1.51.2

### Steps to reproduce (Include if Applicable)

Issuing the command:

    conan install boost/1.79.0@ --update --build=missing

Ends up with error:

```
ERROR: boost/1.79.0: Error in package_info() method, line 1568
        version = Version(self.version).as_list
        AttributeError: 'Version' object has no attribute 'as_list'
```

Happens on Windows and Ubuntu.
This was not an issue with Conan 1.51.1

**Comment by production-robots** [comment]
I am trying to use boost 1.79.0 on a fresh install of unbuntu 22.04 and am getting this:
```
ERROR: boost/1.79.0: Error in package_info() method, line 1547
        "toolset": "-{}".format(self._toolset_tag),
while calling '_toolset_tag', line 1348
        toolset_version = str(Version(self.settings.compiler.version).major(fill=False))
        TypeError: '_VersionItem' object is not callable
```

Is this the same or a similar issue?

**Comment by uilianries** [comment]
@production-robots please, read the comment above yours.

**Comment by uilianries** [comment]
@Adnn @production-robots please, update your local copy, a new Boost package has been released with a fix. Thanks!
