### ISSUE TITLE
[package] libtiff/4.3.0: Error building package (Version object not subscriptable)

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-center-index#12155]
### Package and Environment Details

* Package Name/Version: **libtiff/4.3.0**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **Clang 13**
* Conan version: **conan 1.51.2**
* Python version: **Python 3.10**

### Conan profile

Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=13
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
CC=clang-13
CXX=clang++-13

### Steps to reproduce

```
cd recipes/libtiff/all
conan create . libtiff/4.3.0@ --build missing
```

### Logs

```
ERROR: libtiff/4.3.0: Error in package_info() method, line 193
        self.cpp_info.set_property("pkg_config_name", "libtiff-{}".format(Version(self.version)[0]))
        TypeError: 'Version' object is not subscriptable
```

**Comment by planetmarshall** [comment]
Possibly related to https://github.com/conan-io/conan/pull/11830

**Comment by jcar87** [comment]
Hi @planetmarshall - thanks for reporting this! We have updated the recipe to fix this issue. Please let us know if you experience any further issues and we'll be here to help.
