### ISSUE TITLE
[package] Qt/6.x.x: Windows - Build fails because of strawberryperl self.deps_user_info => user_info update

### ISSUE THREAD

**Issue by szigetics** [conan-io/conan-center-index#12222]
### Package and Environment Details

* Package Name/Version: **zlib/1.2.8**
* Operating System+version: **MS Windows 10**
* Compiler+version: **MSVC 2019** and also **MSVC 2022**
* Conan version: **conan 1.51.1**
* Python version: **Python 3.10.6**

### Conan profile

Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MTd
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MT
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

### Steps to reproduce

Running : 
`conan create recipes/qt/6.x.x qt/6.3.1@_/_ --build=missing -s arch=x86_64 -s build_type=Debug --profile:build=default -o qt:gui=True -o qt:with_pcre2=True -o qt:with_glib=False -o qt:with_doubleconversion=True -o qt:with_harfbuzz=True -o qt:with_libjpeg=libjpeg-turbo -o qt:with_libpng=True -o qt:with_sqlite3=False -o qt:with_mysql=False -o qt:with_pq=False -o qt:with_odbc=False -o qt:with_brotli=False -o qt:with_openal=False -o qt:with_zstd=False -o qt:qtimageformats=False -o qt:qttranslations=True -o qt:qtactiveqt=False -o qt:qtdeclarative=True -o qt:qtsvg=True -o qt:qttools=True -o qt:qtshadertools=True -o zlib:shared=False -o harfbuzz:with_glib=False -o freetype:with_brotli=False -o qt:shared=True -o qt:widgets=False -o qt:opengl=dynamic -o qt:qtwebsockets=True -o qt:qtnetworkauth=True -o openssl:shared=True -s compiler.runtime=MDd`

produces this error : 
```
ERROR: qt/6.3.1@_/_: Error in build() method, line 750
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 710
	cmake.definitions["HOST_PERL"] = getattr(self, "user_info_build", self.deps_user_info)["strawberryperl"].perl
	AttributeError: 
```

This issue is caused by this change : 
https://github.com/conan-io/conan-center-index/pull/6338/files

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by szigetics** [comment]
I am opening the Pull Request with the fix for this one now.

**Comment by ericLemanissier** [comment]
thanks for the report. Did you really try with conan 1.18.0 only ? Please upgrade to at least 1.43.0, and then retry

**Comment by szigetics** [comment]
> thanks for the report. Did you really try with conan 1.18.0 only ? Please upgrade to at least 1.43.0, and then retry

Oooops. I just updated that part of the description.

**Comment by ericLemanissier** [comment]
I cannot reproduce your error, cf https://github.com/eirikb/proof-of-conan/runs/7856099252?check_suite_focus=true
Can you please retry with `-u` command line argument, to make sure you are using the latest recipes from conan-center-index, and the full log

**Comment by ericLemanissier** [comment]
I think this can be closed, as per https://github.com/conan-io/conan-center-index/pull/12223#issuecomment-1217776822
