### ISSUE TITLE
[conan.io/center] Markdown failed `qt/6.0.2@#bcd1f49a09819feee9565771bce191f3`

### ISSUE THREAD

**Issue by mikeb-ah** [conan-io/conan-center-index#12238]
Browser: Chrome 104.0.5112.81 (64 bit)
OS: Windows 10 Pro build 19044.1826

When trying to generate the Use It markdown for the Qt packages, the generator fails as shown in the attached screenshot.
![QtMarkdownFail2](https://user-images.githubusercontent.com/93139030/184655422-84ac8a07-26c3-4ea6-9be7-2758acfe2383.png)

This appears to happen for all Qt packages on CCI currently.

**Comment by jgsogo** [comment]
We are working on a new implementation of the web, that will regenerate all these files
