### ISSUE TITLE
[package] libevent: exposed targets with find package missing

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#1227]
the `find_package` generator generates `Libevent::Libevent` with conan
upstream exposes `event`, `event_core`, `event_extra`, `event_openssl`, `event_pthreads`  when using find_package

related to https://github.com/conan-io/conan-center-index/issues/419

**Comment by gocarlos** [comment]
same for mbedtls: `mbedtls`, `mbedx509`, `mbedcrypto`

**Comment by uilianries** [comment]
> same for mbedtls: `mbedtls`, `mbedx509`, `mbedcrypto`

mbedtls desires a separated issue.

**Comment by uilianries** [comment]
fixed by #2493
