### ISSUE TITLE
[package] date/2.4.1: broken when migrated from bincrafters

### ISSUE THREAD

**Issue by mristin** [conan-io/conan-center-index#1237]
Earlier, there used to be a conan package for a very popular date.h library (https://github.com/HowardHinnant/date):
date/2.4.1@bincrafters/stable

That conan package worked fine and included the time zone information.

The bincrafters' date package was obsoleted some 6 months ago:
https://github.com/bincrafters/conan-date

However, the new date package at:
https://conan.io/center/date/2.4.1/
(revision 1ca181b0a69ae13731469324fac)

breaks the "contract" of the bincrafter's package -- the time zone information is not included. This is very unfortunate -- most people use tz.h library together with date.h.

Could you please add the time zone information or help me with a hint or two where to start in order to add time zone information to date/2.4.1 package on conan center? Or is there a tz.h package that I am maybe not aware of?

Thanks a lot for your help!

**Comment by gocarlos** [comment]
Tried in https://github.com/conan-io/conan-center-index/pull/701 but too many issues with windows which i do not use/fully understand

**Comment by mristin** [comment]
@gocarlos I'll have a look at the logs tonight. Maybe I can figure out the error.

@uilianries since you originally migrated the package from bincrafters, do you maybe have any thoughts on the errors?

**Comment by uilianries** [comment]
@mristin take a look on https://github.com/conan-io/conan-center-index/pull/329#issuecomment-555964182 to understand why the package has been reduced.

**Comment by mristin** [comment]
@uilianries thanks for the clarification!

Any chance you could make a date-tz package? My conan knowledge is way too limited for starting a package from scratch, but I would really like to help as much as I can.

**Comment by uilianries** [comment]
@mristin You can try helping @gocarlos on #701

**Comment by mristin** [comment]
@uilianries thanks, I'll try to help.
