### ISSUE TITLE
[package] opencv/4.5.5: xorg/system: ERROR: while executing system_requirements(): Error 100 while executing apt-get update

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan-center-index#12374]
### Package and Environment Details

* Package Name/Version: **opencv/4.5.5**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 9**
* Conan version: **conan 1.50.2**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
[conf]
tools.system.package_manager:mode=install                                        

### Steps to reproduce

conan install opencv/4.5.5@

### Logs

<details><summary>Click to expand log</summary>

```
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
WARN: libtiff/4.3.0: requirement libwebp/1.2.3 overridden by opencv/4.5.5 to libwebp/1.2.2
WARN: ffmpeg/4.4: requirement libwebp/1.2.3 overridden by opencv/4.5.5 to libwebp/1.2.2
xorg/system: ERROR: while executing system_requirements(): Error 100 while executing apt-get update
ERROR: Error in system requirements
```

</details>

**Comment by Tumb1eweed** [comment]
it seems like two kinds of methods to solve this:
1. 
export CONAN_SYSREQUIRES_MODE="enabled"
export CONAN_SYSREQUIRES_SUDO="1"

2.
add this to profile
[conf]
    # Automatically install required system packages
    tools.system.package_manager:mode=install
    tools.system.package_manager:sudo=True

**Comment by uilianries** [comment]
@Tumb1eweed It's not a bug, but the expected behavior due the migration to Conan 2.0:

https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#new-tools-for-managing-system-package-managers

The Xorg package has been prepared to be supported by Conan 2.0
