### ISSUE TITLE
[conan.io/center] Markdown failed `boost/1.79.0@#7d526a3a7ae5802567a3f8e8cbe85bed`

### ISSUE THREAD

**Issue by ahamez** [conan-io/conan-center-index#12380]
As asked on the webpage, I open this issue because it failed to render Markdown.

<img width="1252" alt="Screenshot 2022-08-19 at 10 07 55" src="https://user-images.githubusercontent.com/199517/185573995-19238be4-0577-408d-979d-a48fe93467e6.png">

**Comment by jgsogo** [comment]
fixed
