### ISSUE TITLE
[conan.io/center] Libpng build error `libpng/1.6.37@#09a159e88fb60b483983f12e66b114b9`

### ISSUE THREAD

**Issue by Syndwar** [conan-io/conan-center-index#12391]
libpng/1.6.37 broke today. Something changed in the receipe that creates wrong variable:
build/generators/PNG-release-x86_64-data.cmake
set(libpng_LIBS_RELEASE libpng<bound method Version.major of '1.6.37'><bound method Version.minor of '1.6.37'>)

CMake Error at build/generators/cmakedeps_macros.cmake:44 (message):
  Library 'libpng<bound' not found in package.  If 'libpng<bound' is a system
  library, declare it with 'cpp_info.system_libs' property
 
 
Profile:
[settings]
build_type=Debug
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.runtime=MDd
compiler.cppstd=17
cryptopp:compiler.cppstd=14
[options]
[build_requires]
[env]

**Comment by SpaceIm** [comment]
see https://github.com/conan-io/conan-center-index/pull/11686/files#r950232617

**Comment by jgsogo** [comment]
I assume it was fixed by #11686. If not, please open the issue again or create a new report. Thanks
