### ISSUE TITLE
[conan.io/center] Markdown failed `tesseract/5.2.0@#5123a352d104794572fa7d1a37d5ab25`

### ISSUE THREAD

**Issue by moberer** [conan-io/conan-center-index#12395]
After clicking the "Use It" tab on the tesseract package ([https://conan.io/center/tesseract?tab=useit](here)), I get the following error message:

> Markdown generator failed for reference tesseract/5.2.0@#5123a352d104794572fa7d1a37d5ab25.
> command line: conan install tesseract/5.2.0@#5123a352d104794572fa7d1a37d5ab25 -g markdown --remote conancenter.
> profile:
> 
> include(default)
> [settings]
> arch=x86_64
> build_type=Release
> compiler=gcc
> compiler.libcxx=libstdc++11
> compiler.version=10
> os=Linux
> 
> Please report [here](https://github.com/conan-io/conan-center-index/issues/new?assignees=&labels=conan.io%2Fcenter&template=center_conan_io.md&title=%5Bconan.io%2Fcenter%5D+Markdown+failed+%60tesseract/5.2.0@%235123a352d104794572fa7d1a37d5ab25%60).

**Comment by jgsogo** [comment]
We are working on a new implementation of the web, that will regenerate all these files
