### ISSUE TITLE
[package] bump libiconv version in libarchive, libgettext, libqrencode, libtorrent, libxml2, log4cplus and odbc

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#1249]
Not a bug, but I don't know which Issue type to pick:

libiconv version can be updated (1.16) in those recipes:
- libarchive
- libgettext
- libqrencode
- libtorrent
- libxml2
- log4cplus
- odbc

**Comment by SSE4** [comment]
the @Croydon bot does amazing job by automatically fixing this as soon as someone touches the library
example: https://github.com/conan-io/conan-center-index/pull/1293

**Comment by SpaceIm** [comment]
I think I can close this issue.
