### ISSUE TITLE
[service] Not possible to get reproducible builds with conan-center 

### ISSUE THREAD

**Issue by patmantru** [conan-io/conan-center-index#12536]
Several times in recent weeks I've had builds fail because of changes to 3rd party libraries.  I had zero changes to the versions of the packages that I requested, zero changes in my build that should make a difference (an update to readme.md for example), yet a GitHub Actions build of my package that worked previously failed miserably because of a 3rd party package change.  Similarly, an app that uses my library package failed to build...because of those 3rd party changes.  My package didn't change.  My recipe didn't change.  My version dependencies didn't change.  The build worked one day, and failed the next.

That's just covering the cases that I noticed because there was a build failure.  How many changes went in silently that did not cause an obvious different result?

Why can't I get a reproducible build?

I attribute at least some of this to the use of the 'all' directory for recipes.  Package A releases 1.0, and puts the recipe in the 'all' directory.  Subsequently 1.1 is released, the 'updatable recipes' bot auto-generates an update that uses the same recipe.  1.2 is released, but there's a problem...something isn't working (some conan 2.0 preparedness lint check, a conan version update, whatever) and the recipe is updated...in the 'all' directory.  That change is now retroactive to 1.0 and 1.1 releases...and breaks something.

boost and ms-gsl were the most recent offenders, changes went into the 'all' recipe that broke stuff retroactively.  In the boost case, the fix cost about a day of downtime, and I discovered ms-gsl works...as long as you upgrade to a newer version of conan.

Ultimately I want (need!) to be able to pin the versions of everything: my package code, the 3rd party library code, the version of conan used, the version of the OS and compiler used, everything.  I should be able to create the same output every build.  I can't do that with the current conan-center approach.

Either:
a) Every recipe change needs to go in a new version-specific directory instead of the 'all' directory
b) Have some sort of patch system available to maintain the version-specific changes to the recipe
c) Have releases treated as completely independent recipes, the version becomes part of the directory name: myLibrary-1.2 that has no materials in common with myLibrary-1.1
d) Open to suggestions here?!?!?!
e) Give up on reproducible builds and just accept that some days it works, and the next day it doesn't

Help me out here.  I'm at 'e' in that list.  I need a solution that I can point a customer/co-worker/collaborator/evaluator to and say "here, use this" without having that fail for reasons I can't control.

Thanks-
Pat

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/blob/master/docs/consuming_recipes.md

**Comment by uilianries** [comment]
@patmantru I can see your situation, but we can't freeze recipes in addition to guarantee some stability. What we suggest is using [lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles/introduction.html), as SpaceIm pointed above. The recipe/package version is the same, what changes is the revision, so you can keep some specific dependencies graph and will not affect your project.

**Comment by patmantru** [comment]
I will try the lockfiles...  Thanks for the suggestion!
