### ISSUE TITLE
[request] boost/1.80.0

### ISSUE THREAD

**Issue by TheSalvator** [conan-io/conan-center-index#12564]
### Package Details
  * Package Name/Version: **boost/1.80.0**
  * Changelog: **https://www.boost.org/users/history/version_1_80_0.html**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

@jwillikers @datalogics-robb 
I saw you two were the last contributors
I'd be very grateful for this one

**Comment by jwillikers** [comment]
@TheSalvator I've started working on this. Just takes a while to go through all the patches.
