### ISSUE TITLE
[conan.io/center] expat description was not updated

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#1256]
expat description was "Recipe for Expat library" in conanfile.py before https://github.com/conan-io/conan-center-index/pull/1167
The new description "Fast streaming XML parser written in C." is not displayed in conan-center Web UI: https://conan.io/center/expat/2.2.9/?user=_&channel=_

**Comment by danimtb** [comment]
there was a bug in the data recollection process but was fixed before this PR got merged

**Comment by solvingj** [comment]
@SpaceIm this is currently being worked on.

**Comment by claremacrae** [comment]
This appears to be fixed now - perhaps the ticket could be closed?

![2021-09-01_09-48-04](https://user-images.githubusercontent.com/4840096/131641543-4e76fd16-7b67-43a7-9b8e-92c2cb887341.png)
