### ISSUE TITLE
[package] openssl/1.1.1p: Wrong url to fetch source

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan-center-index#12569]
### Package and Environment Details

* Package Name/Version: **zlib/1.2.8**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 8**
* Docker image: **conanio/gcc8**
* Conan version: **conan 1.18.0**
* Python version: **Python 3.7.4**

### Steps to reproduce

Tries to fetch file: 
https://www.openssl.org/source/openssl-1.1.1p.tar.gz 
and 
https://www.openssl.org/source/old/openssl-1.1.1p.tar.gz

The file is actually here: https://www.openssl.org/source/old/1.1.1/openssl-1.1.1p.tar.gz

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by uilianries** [comment]
The link [openssl.org/source/openssl-1.1.1p.tar.gz](https://www.openssl.org/source/openssl-1.1.1p.tar.gz) works for me.

Please, update your Conan client version, 1.18 is outdated.

**Comment by klausholstjacobsen** [comment]
It also does for me.....again!
Thx
