### ISSUE TITLE
zlib recipe overwrites ENV settings

### ISSUE THREAD

**Issue by zod** [conan-io/conan-center-index#1259]
I'm trying to build zlib using the following profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libc++

[env]
CC = clang-6.0
CXX = clang++-6.0
```

Building zlib fails because I don't have _clang_ binary but only _clang-6.0_ binary because it's overwritten by the recipe. You also can't build with a different clang version, only the one provided by your _clang_ binary.

https://github.com/conan-io/conan-center-index/blob/a025bb0e4d523db2cf08c4eb7730079c94368b8e/recipes/zlib/1.2.11/conanfile.py#L68

It was already metioned in #306 but it's still in the recipe.

**Comment by uilianries** [comment]
I see, we need to check is CC and CXX are configured.
