### ISSUE TITLE
[package] qt/6.3.1: with_vulkan option requires non existing vulkan-loader/1.3.221.0 package

### ISSUE THREAD

**Issue by jellespijker** [conan-io/conan-center-index#12601]
### Package and Environment Details

* Package Name/Version: **qt/6.3.1**
* Operating System+version: **Linux Manjaro**
* Conan version: **conan 1.51.3**
* Python version: **Python 3.10.4**

## host
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++
build_type=Release
compiler.cppstd=17
[options]
[conf]
[build_requires]
[env]
```

## build
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++
build_type=Release
compiler.cppstd=17
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce

`conan install qt/6.3.1@ -o qt:with_vulkan=True ......`

Fails on the fact that it can't find `vulkan-loader/1.3.221.0` in the conan-center. This should probably be: `vulkan-loader/1.3.221` because that version is available.

See: https://github.com/conan-io/conan-center-index/blob/a0d894ba926719a5a5057d126bfba7b6c7da60f5/recipes/qt/6.x.x/conanfile.py#L340

### Logs

```bash
$ conan search vulkan-loader -r conan-center
Existing package recipes:

vulkan-loader/1.2.154.0
vulkan-loader/1.2.162.0
vulkan-loader/1.2.170.0
vulkan-loader/1.2.172
vulkan-loader/1.2.182
vulkan-loader/1.2.189
vulkan-loader/1.2.190
vulkan-loader/1.2.198.0
vulkan-loader/1.3.204.0
vulkan-loader/1.3.204.1
vulkan-loader/1.3.211.0
vulkan-loader/1.3.216.0
vulkan-loader/1.3.221
```

**Comment by ericLemanissier** [comment]
Thanks for the report. You are right. Don't hesitate to make a pull request to fix this.

**Comment by SpaceIm** [comment]
I advice to only depend on "sdk" versions of vulkan-loader in CCI recipes (1.3.216.0).

**Comment by jellespijker** [comment]
Will create a PR somewhere today.
