### ISSUE TITLE
[conan.io/center] Search through topics 

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#1268]
It would be awesome if the search would search through the recipe topics too.

This would allow to not only search when I already know what I'm searching for, but also when I'm searching for **--some--** package to solve a problem

Example: I want to to use some library to parse command line arguments. Then I could search for terms like `cli` and `command line`

**Comment by Dattax** [comment]
We have it on the roadmap to introduce a topics-based search this quarter. If you have ideas about the best workflow or UI for this topic-based search - feel free to email me: deepd@jfrog.com. I would be happy to work with you on it!

**Comment by Croydon** [comment]
![topics](https://user-images.githubusercontent.com/1593194/95238152-63fa2d80-0809-11eb-8e7d-b63ebf07bf08.PNG)

This is now implemented. 

Thank you!
