### ISSUE TITLE
[package] jwt-cpp/0.6.0: Package doesn't compile because of missing picojson requirement

### ISSUE THREAD

**Issue by JorgenPo** [conan-io/conan-center-index#12706]
### Package and Environment Details

* Package Name/Version: **jwt-cpp/0.6.0**
* Package Revision: **9ba33a57e1b44045f50633246c660de4**
* Operating System+version: **Arch linux**
* Compiler+version: **GCC 11**
* Conan version: **conan 1.51.3**

### Conan profile

[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
os_build=Linux
arch_build=x86_64
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

1. Add jwt-cpp/0.6.0 dependency
2. Try to conan install with build=missing
3. Get an error: `.../jwt.h:8:10: fatal error: picojson.h: No such file or directory`

### Logs

<details><summary>Click to expand log</summary>

```
/home/popov/.conan/data/jwt-cpp/0.6.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/jwt-cpp/jwt.h:8:10: fatal error: picojson.h: No such file or directory
    8 | #include "picojson.h"
      |          ^~~~~~~~~~~~
```

</details>

**Comment by JorgenPo** [comment]
There is a check in the receipt:
```
if not self._supports_generic_json:
            self.requires("picojson/1.3.0")
```
In my case `_supports_generic_json` should return true so that's the reason why picojson isn't required. But in that case it seems like `JWT_DISABLE_PICOJSON` definition should be provided.

**Comment by SpaceIm** [comment]
Correct, can you submit a PR? Just need to add `self.cpp_info.defines.append("JWT_DISABLE_PICOJSON")` in `package_info()` if `self._supports_generic_json`.

**Comment by prince-chrismc** [comment]
firstly thanks for trying jwt-cpp (I am a contributor)!🤔 there's definitely something missing in the recipe

Adding the define it definitely a first step.

As for Space's suggestion, just two notes...

The test_package would still need a JSON library to compile, and you would need to `#undef JWT_DISABLE_PICOJSON` as well...
You are expected to add a JSON library so the disable is fine but you need to add the `traits/.../defaults.h` include for it to work in that case.
