### ISSUE TITLE
[package] sqlite3/3.36.0: cannot import name "is_apple_os" from "conan.tools.apple"

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan-center-index#12708]
### Package and Environment Details

* Package Name/Version: **sqlite/3.36.0**
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **GCC 9**
* Python version: **Python 3.8.10**
* Conan version: **1.50.2**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True
[build_requires]
[env]

### Steps to reproduce

conan install sqlite3/3.36.0@ -r=video9

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: sqlite3/3.36.0: Cannot load recipe.
Error loading conanfile at '/data/.data/sqlite3/3.36.0/_/_/export/conanfile.py': Unable to load conanfile in /data/.data/sqlite3/3.36.0/_/_/export/conanfile.py
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/.data/sqlite3/3.36.0/_/_/export/conanfile.py", line 3, in <module>
    from conan.tools.apple import is_apple_os
ImportError: cannot import name 'is_apple_os' from 'conan.tools.apple' (/home/chenrui04/.local/lib/python3.8/site-packages/conan/tools/apple/__init__.py)
```

</details>

**Comment by SpaceIm** [comment]
Not a bug. Latest RREV of sqlite3 recipe requires 1.51.3. Error message will be better with https://github.com/conan-io/conan/pull/11908 in conan 1.52.
