### ISSUE TITLE
[package] wayland/all: incompatible with latest (1.52.0) Conan version

### ISSUE THREAD

**Issue by dornbirndevelops** [conan-io/conan-center-index#12722]
### Package and Environment Details

* Package Name/Version: **wayland/1.20.0**
* Conan version: **conan 1.52.0**

### Steps to reproduce

conan export recipes/wayland/all wayland/1.20.0@

### Logs

<details><summary>Click to expand log</summary>

```
File "recipes/wayland/all/conanfile.py", line 5, in <module>
    from conan.tools.gnu.pkgconfigdeps.pc_files_creator import get_pc_files_and_content
ModuleNotFoundError: No module named 'conan.tools.gnu.pkgconfigdeps.pc_files_creator'; 'conan.tools.gnu.pkgconfigdeps' is not a package
```

</details>

**Comment by dornbirndevelops** [comment]
incompatibility caused most likely with this feature:
https://github.com/conan-io/conan/pull/11955

@franramirez688 do you have ideas how one could support `<1.52.0` and the latest?

**Comment by SpaceIm** [comment]
It was not part of official conan API and shouldn't have been imported in the first place in `wayland` recipe. But yes, let's see how to find a robust workaround.

**Comment by AndreyMlashkin** [comment]
How it could come to this state? Don't you make a minimal test with conan export for each recipe in conan-center-index before releasing a new version of conan client?...

**Comment by jcar87** [comment]
Hi @AndreyMlashkin - the guidelines for importing tools from `conan.tools` are in the documentation: https://docs.conan.io/en/latest/reference/conanfile/tools.html, and every publicly available `yyy` tool is explicitly made available as `conan.tools.xxx.yyy`, and is documented as such. Anything that is any further levels down or not documented is not considered public API. This was also warned by @franramirez688  on a related PR here: https://github.com/conan-io/conan-center-index/pull/11636#discussion_r930240901. When releasing Conan, we go to great lengths to retain backwards compatibility of the publicly documented APIs. 

I apologise that during the review process for the changes in the wayland recipe this was not flagged. Reviewers in conan-center-index deal with a high level of requests, and we try to do our best.

**Comment by jwillikers** [comment]
We should be able to patch this until Conan Center starts using Conan 1.52. I know the `xkbcommon` package has to do a similar workaround, but it was done differently [there](https://github.com/conan-io/conan-center-index/blob/master/recipes/xkbcommon/all/conanfile.py#L78).
