### ISSUE TITLE
protobuf: tests are run but cannot succeed if cross-compiling

### ISSUE THREAD

**Issue by solney-syn** [conan-io/conan-center-index#12863]
If one tries to build protobuf for armv8 from an x64 platform, the build succeeds, but the package test fails. This is because it tries to execute an armv8 binary.

E.g on Windows x64 machine
`conan create -s build_type=Release -s compiler.runtime=MT -s arch=armv8  recipes/protobuf/all protobuf/3.13.0@`

Fails with
```
-- Build files have been written to: C:/projects/conan-center/recipes/protobuf/all/test_package/build/7aa2b85ea92903b92d690fdbab8d0a1f5d061213
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Running cpp protocol buffer compiler on addressbook.proto
  This version of C:\projects\5513ff\1\bin\protoc.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\projects\conan-center\recipes\protobuf\all\te
st_package\build\7aa2b85ea92903b92d690fdbab8d0a1f5d061213\CMakeFiles\b92f4d5ca734465a01dffa5f9975d01c\addressbook.pb.h.rule;C:\projects\conan-center\recipes\protobuf\all\test_package\CMakeLists.txt' exited wi
th code 216. [C:\projects\conan-center\recipes\protobuf\all\test_package\build\7aa2b85ea92903b92d690fdbab8d0a1f5d061213\test_package.vcxproj]
ERROR: protobuf/3.13.0 (test package): Error in build() method, line 17
        cmake.build()
        ConanException: Error 1 while executing cmake --build C:\projects\conan-center\recipes\protobuf\all\test_package\build\7aa2b85ea92903b92d690fdbab8d0a1f5d061213 --config Release -- /m:12 /verbosity:minimal
```

I would have expected perhaps to get a warning instead, explaining that the tests cannot be run on the current host and to compile on an armv8 machine if one needs this.

A workaround is to append a `-tf None`

**Comment by SpaceIm** [comment]
Use 2 profiles for cross compilation.

**Comment by uilianries** [comment]
@solney-syn Use two profiles, as SpaceIm commented. It's documented here: https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer

Also, for Conan 2.0, dual profile will required always.

**Comment by solney-syn** [comment]
Thank you @SpaceIm  and @uilianries.
I have now tried this with explicit `--profile:build` and `--profile:host` profiles and that resolves the issue - Conan runs the package test using the arch from the build profile.

**Comment by uilianries** [comment]
@solney-syn thank you for your feedback!
