### ISSUE TITLE
[package] voropp/0.4.6: source download failed due to SSL certificate error

### ISSUE THREAD

**Issue by Renari** [conan-io/conan-center-index#12911]
### Package and Environment Details

* Package Name/Version: **voropp/0.4.6**
* Operating System+version: **Linux Mint 20.3**
* Compiler+version: **GCC 10**
* Conan version: **conan 1.52.0**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os.distro=Ubuntu20
os_build=Linux
[options]
[build_requires]
[env]

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: Error downloading file http://math.lbl.gov/voro++/download/dir/voro++-0.4.6.tar.gz: 'HTTPSConnectionPool(host='math.lbl.gov', port=443): Max retries exceeded with url: /voro++/download/dir/voro++-0.4.6.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))'
ERROR: voropp/0.4.6: Error in source() method, line 45
	tools.get(**self.conan_data["sources"][self.version],
	ConanException: Error downloading file http://math.lbl.gov/voro++/download/dir/voro++-0.4.6.tar.gz: 'HTTPSConnectionPool(host='math.lbl.gov', port=443): Max retries exceeded with url: /voro++/download/dir/voro++-0.4.6.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))'
CMake Error at cmake-build-debug/conan.cmake:522 (message):
  Conan install failed='1'

```

</details>

**Comment by Renari** [comment]
This download is still available from https://math.lbl.gov/voro++/download/ however there is now an SSL certificate that appears to have not been there previously which python fails to verify.

**Comment by uilianries** [comment]
@Renari There is an update available for your case, please, update your local copy and try again. We just ignored the certificate verification. Regards!
