### ISSUE TITLE
[conan.io/center] Markdown failed `boost/1.80.0@#3264cfe783d4202f76c96b7d5399ff17`

### ISSUE THREAD

**Issue by batunpc** [conan-io/conan-center-index#12981]
The "Use it" tab displays the following error message and it is the same case for other packages as well. I am using Firefox Dev edition

![boost CC++ Package - JFrog ConanCenter@2x](https://user-images.githubusercontent.com/71259399/190849255-92078ea2-d5b2-421a-b0aa-55c0c7e2e004.png)

**Comment by jgsogo** [comment]
Fixed
