### ISSUE TITLE
`mosquitto` recipe

### ISSUE THREAD

**Issue by madhat1** [conan-io/conan-center-index#12997]
Hi,
I'd like to know who builds and uploads the mosquitto package to conan.io.
It seems that the mosquitto codebase in github does not contain a conan recipe:
https://github.com/eclipse/mosquitto

How can package consumers know that the source is not malicious?

**Comment by jgsogo** [comment]
All the files involved in that package generation can be found in this repository: https://github.com/conan-io/conan-center-index/tree/master/recipes/mosquitto. PRs modifying them are reviewed before merging by users that have been approved in advance.

**Comment by madhat1** [comment]
Ok, thanks.
