### ISSUE TITLE
[conan.io/center] Markdown failed `sqlite3/3.39.2@#a33a9b365cf9c2bb99590250c115a2cb`

### ISSUE THREAD

**Issue by Terrabits** [conan-io/conan-center-index#12993]
I tried to access the "Use It" tab on the SQLite3 3.39.2 package page and received this error message.

<img width="797" alt="sqlite3-markdown-generator-failed" src="https://user-images.githubusercontent.com/1532047/190876666-76b0b00d-89c6-4bb6-8997-b2d229d9a1d9.png">

**Comment by jgsogo** [comment]
Fixed!
