### ISSUE TITLE
[request] opencv/4.3.0

### ISSUE THREAD

**Issue by leyewen** [conan-io/conan-center-index#1300]
### Package Details
  * Package Name/Version: **opencv/4.3.0**
  * Changelog: **https://github.com/opencv/opencv/releases**

Since OpenCV 4.3.0, OpenCV DNN accelerated by Inference Engine (DLDT). Please add https://github.com/conan-community/conan-opencv to `conan-center-index` and support 4.3.0 version! It an exciting version.

**Comment by Croydon** [comment]
OpenCV has many dependencies which we need to first get into CCI.

It is probably better to make a 4.3.0 release in conan-community in the meantime

**Comment by AndreyMlashkin** [comment]
Is there already a road-map when it will be included?

**Comment by Croydon** [comment]
CCI lives from contributions, so we can't give any deadlines or similar.

The more people help, the faster we move forward 😄

**Comment by Croydon** [comment]
In the meantime, conan-community got version 4.3

**Comment by uilianries** [comment]
I've started an effort over OpenCV 2.4, so we can use as base for 3.x and 4.x. I should publish a PR soon.

**Comment by Croydon** [comment]
OpenCV 4.5 is now available

Done via https://github.com/conan-io/conan-center-index/pull/3409

**Comment by leyewen** [comment]
Well done.
