### ISSUE TITLE
[question] libavif package is not availabe for arm

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#13001]
Hi!

`libavif` package is not available for `arm`:

```
libavif/0.9.3: WARN: Can't find a 'libavif/0.9.3' package for the specified settings, options and dependencies:
- Settings: arch=armv8, build_type=Release, compiler=apple-clang, compiler.version=12.0, os=Macos
- Options: fPIC=True, shared=False, with_decoder=dav1d, dav1d:assembly=True, dav1d:bit_depth=all, dav1d:fPIC=True, dav1d:shared=False, dav1d:with_tools=True, libaom-av1:fPIC=True, libaom-av1:shared=False, libjpeg:fPIC=True, libjpeg:shared=False, libyuv:fPIC=True, libyuv:shared=False, libyuv:with_jpeg=libjpeg
- Dependencies: libaom-av1/3.1.2, libyuv/cci.20201106, dav1d/0.9.1
- Requirements: dav1d/0.9.1, libaom-av1/3.Y.Z, libyuv/cci.20201106
- Package ID: 17961342dca26aa438063ee09e8a8555babdeda7
```

I'm trying to update the recipe for SAIL (https://github.com/conan-io/conan-center-index/pull/13000) which depends on libavif and fails to be built by the CI on arm because of that.

Q:

1. Why does `libavif` have no arm packages?
2. How can I address this in my recipe?

**Comment by HappySeaFox** [comment]
Well, it seems that `libavif` depends on `dav1d` which doesn't support cross-compilation:

```
    def validate(self):
        if hasattr(self, "settings_build") and tools.cross_building(self):
            raise ConanInvalidConfiguration("Cross-building not implemented")
```

This is why there are no `arm` packages for `dav1d` and obviously `libavif`.

Is there a way to handle this automatically in my recipe? Automatically = mark the current recipe configuration as invalid if one of its dependencies is invalid.

**Comment by SpaceIm** [comment]
`dav1d` recipe support cross-compilation since https://github.com/conan-io/conan-center-index/pull/12300, but last time libavif has been built by c3i it was not the case, thus these missing binaries.
