### ISSUE TITLE
[package] libcurl/7.85.0: links against libtool but only lists it as tool_requires

### ISSUE THREAD

**Issue by Cogitri** [conan-io/conan-center-index#13050]
### Package and Environment Details

* Package Name/Version: **libcurl/7.85.0** (and earlier)
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **Clang 12**
* Conan version: **conan 1.52.0**
* Python version: **Python 3.10.6**

Since `libtool` is only marked as tool_requires, `libltdl` isn't pulled in as runtime dependency, which causes issues when the resulting build is deployed on older machines which don't have `libltdl` of the right version.

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=12
compiler.libcxx=libstdc++
build_type=Release
compiler.cppstd=17
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install --build=missing libcurl/7.85.0@
ldd ~/.conan/data/libcurl/7.85.0/_/_/package/*/lib/libcurl.so

### Logs

<details><summary>Click to expand log</summary>

```
$HOME/.conan/data/libcurl/7.85.0/_/_/package/8e30aef01317ee7bcd761ed54212d56c98ca820b/lib/libcurl.so:
	linux-vdso.so.1 (0x00007ffc699aa000)
	libltdl.so.7 => /lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f1e9166c000)
	libssl.so.1.1 => /home/rasmus/Projects/ds4-util/build/bin/libssl.so.1.1 (0x00007f1e915b0000)
	libcrypto.so.1.1 => /home/rasmus/Projects/ds4-util/build/bin/libcrypto.so.1.1 (0x00007f1e91251000)
	libz.so.1 => /home/rasmus/Projects/ds4-util/build/bin/libz.so.1 (0x00007f1e9122b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1e91003000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1e90ffc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1e90ff7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1e91753000)
```
</details>

**Comment by SpaceIm** [comment]
It's a bug of legacy Autotools build helper with 1 profile, which inject libs of tool_requires during link. Try to compile again with 2 profiles instead.

**Comment by Cogitri** [comment]
Hm, even with two profiles it still links against `libltdl`:

```
$ conan profile list
default
dummy
```

**Comment by SpaceIm** [comment]
I mean with a command like `conan install libcurl/7.85.0@ -pr:b default -pr:h default -b missing` (I guess you also have `-o *:shared=True` in profile or command line since all your dependencies are shared, while default is conan-center is static).

**Comment by Cogitri** [comment]
Ah, I'll try that, thanks :)
Yeah, we build everything statically to distribute the libs to follow (L)GPL

**Comment by Cogitri** [comment]
Yup, that works, thanks!

**Comment by SpaceIm** [comment]
If you want to always call conan create/install with 2 profiles, without the need to have `-pr:b <profile>` in command line, you can create `global.conf` file in `~/.conan` folder, and add `core:default_build_profile=default`. In conan v2, it will be automatic (not more "1 profile" under the hood).

**Comment by SpaceIm** [comment]
For reference: https://github.com/conan-io/conan/issues/12159

**Comment by Cogitri** [comment]
Thanks for the tip, I just added this to our internal build-script so it's not an issue to specify it every time :)
