### ISSUE TITLE
[conan.io/center] Remove querystring (user and channel arguments) from URL (if not needed)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-center-index#1310]
Right now URLs for recipes without user and channel contain a querystring, i.e. `https://conan.io/center/libcurl/7.69.1/?user=_&channel=_`. This make them to fail in markdown generators like the one in Github:

 * copy/paste the link won't work: https://conan.io/center/libcurl/7.69.1/?user=_&channel=_
 * using the verbose format with `[]()` adds italics and renders an URL that is not valid (you cannot copy/paste it): [https://conan.io/center/libcurl/7.69.1/?user=_&channel=_](https://conan.io/center/libcurl/7.69.1/?user=_&channel=_)

URLs without the querystring are functional and they render properly: https://conan.io/center/libcurl/7.69.1/ so the request is **to not add these querystring arguments to the links generated in the search box when the recipe doesn't have user/channel**.

**Comment by danimtb** [comment]
Related to https://github.com/conan-io/conan-center-index/issues/768

**Comment by Croydon** [comment]
It is removed now, but the packages sites for packages which got into conan-center by the old way are now broken

Take libcurl as an example. if you use the search you get two results, but no matter which libcurl you click you always land on the CCI version

Also, even if you land on a package site for an older package, you get wrong information as the site now always hides the username/channel.

**Comment by prince-chrismc** [comment]
> It is removed now

Sounds like the original issue was fixed plus we have a new website going to close this :)
