### ISSUE TITLE
[qt/6.3.1] Text in labels is not rendered properly

### ISSUE THREAD

**Issue by matte86** [conan-io/conan-center-index#13139]
### Description

When consuming qt/6.3.1 from conan center under MacOS 12.6 text in labels is not rendered properly.

A mention to this issue is also available on the [qt forum](https://forum.qt.io/topic/126473/text-in-labels-is-not-rendered-properly).

### Package and Environment Details

* Package Name/Version: **qt/6.3.1**
* Operating System+version: **MacOS 12.5**
* Compiler+version: **Apple Clang 14.0**
* Conan version: **conan 1.52.0**
* Python version: **Python 3.9.12**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=14.0
compiler.libcxx=libc++
compiler.cppstd=17
build_type=Debug
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

Build a QML application that have some text in it.

### Logs

No issues are actually reported, neither during build nor execution.

**Comment by ericLemanissier** [comment]
I think you have to enable harfbuzz by setting option `qt:with_harfbuzz=True`
https://stackoverflow.com/questions/73256254/static-qt-build-messes-up-text

**Comment by matte86** [comment]
Thanks @ericLemanissier , under MacOS that worked like a charm!
I was hoping this fix to also make my app build and run successfully under Windows but unfortunately I cannot build Qt6 there.
Since this bug mentioned specifically MacOS I will close it and follow the discussion on StackOverflow.

**Comment by uilianries** [comment]
@ericLemanissier Thank you for helping!!
