### ISSUE TITLE
[conan.io/center] Markdown failed `protobuf/3.21.4@#2f747b7c62b3d9518800a092e534f556`

### ISSUE THREAD

**Issue by liwang54321** [conan-io/conan-center-index#13133]
I want to use the syntax of protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS ${CMAKE_CURRENT_SOURCE_DIR}/proto/examples.proto) to generate proto code, but it seems that there is no way to use conan to reference packages. Is there any other way?

**Comment by Croydon** [comment]
This is fixed
