### ISSUE TITLE
[request] qpdf/11.1.0; reviewers required

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [conan-io/conan-center-index#13153]
### Package Details
  * Package Name/Version: **qpdf/11.1.0**
  * Website: **https://qpdf.sourceforge.io/**
  * Source code: **https://github.com/qpdf/qpdf**

### Description Of The Library / Tool
qpdf provides command line binaries as well as c and c++ libraries. It is a 2.1k github stars project.

pull-request already there:
https://github.com/conan-io/conan-center-index/pull/13113

Locally it is working fine, even with a complete conan package test from qpdf examples generating a new pdf.
It is at the moment red in ci build states, just because of:
```
-- Configuring incomplete, errors occurred!
qpdf/11.1.0: 
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.16 or higher is required.  You are running version 3.15.7
```

How to cope here with the cmake version requirement mismatch between ci and the package? Especially interesting is that `boost-ext-ut/all/test_package/CMakeLists.txt` was already able to merge with such a high cmake requirement. How was that solved there?

**Comment by cguentherTUChemnitz** [comment]
Thanks for pointing out the way to go. I updated accordingly the PR

**Comment by ericLemanissier** [comment]
@cguentherTUChemnitz this can be closed. https://github.com/conan-io/conan-center-index/pull/13113 is merged

**Comment by uilianries** [comment]
Fixed by https://github.com/conan-io/conan-center-index/pull/13113.
