### ISSUE TITLE
[request] <mosquitto>/<2.0.15>

### ISSUE THREAD

**Issue by madhat1** [conan-io/conan-center-index#13207]
### Package Details
  * Package Name/Version: **mosquitto/2.0.15**
  * Changelog: **https://github.com/eclipse/mosquitto/releases/tag/v2.0.15**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by HappySeaFox** [comment]
https://github.com/conan-io/conan-center-index/pull/13254

**Comment by madhat1** [comment]
@HappySeaFox Thanks!
