### ISSUE TITLE
[request] OpenCL-CLHPP

### ISSUE THREAD

**Issue by iKoznov** [conan-io/conan-center-index#13239]
### Package Details
  * Package Name/Version: **opencl-hpp/2022.09.23**
  * Website: **https://github.com/KhronosGroup/OpenCL-CLHPP**
  * Source code: **https://github.com/KhronosGroup/OpenCL-CLHPP**

### Description Of The Library / Tool
OpenCL API C++ bindings

**Comment by ilya-lavrenov** [comment]
https://github.com/conan-io/conan-center-index/pull/17416
