### ISSUE TITLE
[request] <maven/3.8.6>

### ISSUE THREAD

**Issue by MartinDelille** [conan-io/conan-center-index#13231]
### Package Details
  * Package Name/Version: **maven/3.8.6**
  * Website: **https://maven.apache.org/**
  * Source code: **https://gitbox.apache.org/repos/asf?p=maven-sources.git;a=summary**

### Description Of The Library / Tool

Maven would allow me to add the following tools to CCI: https://github.com/OpenAPITools/openapi-generator

**Comment by valgur** [comment]
@MartinDelille Can be closed: https://conan.io/center/recipes/maven

**Comment by MartinDelille** [comment]
Thanks! I needed this to have https://conan.io/center/recipes/openapi-generator but it finally rely on https://conan.io/center/recipes/openjdk

I have little knowledge about java. Do you think we should update the openapi-generator recipe now ?
