### ISSUE TITLE
[package] mongo-c-driver/1.22.0: TemplateAssertionError: no test named 'boolean'

### ISSUE THREAD

**Issue by Jihadist** [conan-io/conan-center-index#13249]
### Description

mongo-c-driver.with_sasl = "cyrus"
```
mongo-c-driver/1.22.0: Configuring sources in /home/runner/.conan/data/mongo-c-driver/1.22.0/_/_/source/src
mongo-c-driver/1.22.0: 
mongo-c-driver/1.22.0: Copying sources to build folder
mongo-c-driver/1.22.0: Building your package in /home/runner/.conan/data/mongo-c-driver/1.22.0/_/_/build/4e52fd6ff738d80350d408c290dc83754762e1f6
mongo-c-driver/1.22.0: Generator txt created conanbuildinfo.txt
mongo-c-driver/1.22.0: Calling generate()
WARN: Remotes registry file missing, creating default one in /home/runner/.conan/remotes.json
WARN: spdlog/1.9.0: requirement fmt/8.0.1 overridden by userver/1.0.0 to fmt/8.1.1 
WARN: libcurl/7.68.0: requirement openssl/1.1.1o overridden by userver/1.0.0 to openssl/1.1.1q 
ERROR: mongo-c-driver/1.22.0: Error in generate() method, line 162
	tc.generate()
	TemplateAssertionError: no test named 'boolean'
```
https://github.com/conan-io/conan-center-index/blob/master/recipes/mongo-c-driver/all/conanfile.py#L162

I cannot reproduce this locally, only in github ci with github containers.

### Package and Environment Details

* Package Name/Version: **mongo-c-driver/1.22.0**
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **GCC 9.3.0**
* Conan version: **conan 1.52.0**
* Python version: **Python 3.8.2**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter mongo-c-driver/1.22.0@ -pr:b=default -pr:h=default

### Logs

<details><summary>Click to expand log</summary>

Log relates to https://github.com/Jihadist/userver/actions/runs/3164454605/jobs/5152751444

</details>

**Comment by SpaceIm** [comment]
Seems to be an issue coming from wrong Jinja2 version vs this line in conan client: https://github.com/conan-io/conan/blob/develop/conan/tools/cmake/toolchain/toolchain.py#L102

So it's not a CCI recipe issue. It should be transferred to conan client.
