### ISSUE TITLE
[question] opencv/4.5.5 use with_cuda doesn't have cuda header files

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan-center-index#13384]
![image](https://user-images.githubusercontent.com/27768261/194792237-f1afa271-cf2c-4386-96da-61354fcd35f7.png)
using opencv 4.5.5 and -o opencv:with_cuda=True -o opencv:contrib=True doesn't have those header files

and How can I build opencv from source using my own cuda conan package?

**Comment by wematan** [comment]
Same here, tried adding a whole lot of flags as well in order to get it build opencv-contrib, but had no success either.

**Comment by Tumb1eweed** [comment]
> Same here, tried adding a whole lot of flags as well in order to get it build opencv-contrib, but had no success either.

solve this problem, because opencv doesn't detect cuda toolkit, you need to use environment variable to let opencv find cuda "export CUDA_TOOLKIT_ROOT_DIR=/data/.data/cuda/11.1.1/_/_/package/c0519e2d9702ec12d057bb15adb7a02baaf18107/
export CUDA_BIN_PATH=/data/.data/cuda/11.1.1/_/_/package/c0519e2d9702ec12d057bb15adb7a02baaf18107/bin/".

**Comment by uilianries** [comment]
Yes, Conan does not provide a CUDA project and it should be managed by the environment. If you search `cuda` keyword on issues/PRs you will find more discussion about. Thanks for showing your solution.

**Comment by wematan** [comment]
@Tumb1eweed Big ups man, it worked Thanks! +1
