### ISSUE TITLE
[package] libjpeg/9d: Can't build on windows (hash mismatch)

### ISSUE THREAD

**Issue by saphiresouldier** [conan-io/conan-center-index#13417]
### Description

Whenever I try to build libjpeg on windows I get an error about a failed sha256 signature for 'jpehsrc.v9d.tar.gz' file.

### Package and Environment Details

* Package Name/Version: **libjpeg/9d**
* Operating System+version: **Windows 10**
* Compiler+version: **Visual Studio 16 2019**
* Conan version: **conan 1.53.0**
* Python version: **Python 3.9.5**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
[build_requires]
[env]

### Steps to reproduce

conan install libjpeg/9d@ -s build_type=Release -r conancenter --build libjpeg

### Logs

<details><summary>Click to expand log</summary>

```
> conan install libjpeg/9d@ -s build_type=Release -r conancenter --build libjpeg -pr release
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
[build_requires]
[env]

libjpeg/9d: Forced build from source
Installing package: libjpeg/9d
Requirements
    libjpeg/9d from 'artifactory' - Cache
Packages
    libjpeg/9d:3fb49604f9c2f729b85ba3115852006824e72cab - Build

Installing (downloading, building) binaries...
libjpeg/9d: WARN: Trying to remove corrupted source folder
libjpeg/9d: WARN: This can take a while for big packages
libjpeg/9d: Configuring sources in C:\Users\saphi\.conan\data\libjpeg\9d\_\_\source
Downloading jpegsrc.v9d.tar.gz completed [1006.75k]
ERROR: libjpeg/9d: Error in source() method, line 41
        tools.get(**self.conan_data["sources"][self.version])
        ConanException: sha256 signature failed for 'jpegsrc.v9d.tar.gz' file.
 Provided signature: 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee
 Computed signature: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a
```

</details>

**Comment by uilianries** [comment]
@saphiresouldier Indeed the checksum is different, I just download on Mac and it fits with your case. I don't believe the sha256sum in conandata.yml is incorrect, because that package was built using that same checksum. Usually what we have is when an author tag again a version and it changes its checksum.

**Comment by SpaceIm** [comment]
Again? It's not the first time they change checksum of their tarball. What a mess.

**Comment by AndreyMlashkin** [comment]
Has someone reported this upstream? Please, post a link in this case

**Comment by uilianries** [comment]
I sent a message to https://jpegclub.org/reference/contact/ asking about some hint. If someone has another mail list, forum, etc, please, keep us updated.

**Comment by uilianries** [comment]
Okay, I got an answer from the official contact:

> jpegsrc.v9d.tar.gz was last repackaged on 4 Jan 2022, and was uploaded to server with time preserve option. Can check that using "curl -R -O", and can also show that file is identical to local master source:

    Microsoft Windows [Version 10.0.19044.2130]
    (c) Microsoft Corporation. Alle Rechte vorbehalten.

    C:\Users\guido>d:

    D:\>curl -R -O http://ijg.org/files/jpegsrc.v9d.tar.gz
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 1006k  100 1006k    0     0   317k      0  0:00:03  0:00:03 --:--:--  317k

    D:\>fc /b D:\jpegsrc.v9d.tar.gz C:\Users\guido\Documents\ijg\files\jpegsrc.v9d.tar.gz
    Vergleichen der Dateien D:\jpegsrc.v9d.tar.gz und C:\USERS\GUIDO\DOCUMENTS\IJG\FILES\JPEGSRC.V9D.TAR.GZ
    FC: Keine Unterschiede gefunden


    D:\>


So it's safe to update the checksum in conandata.yml

**Comment by spectras** [comment]
They did it again…

 Provided signature: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a
 Computed signature: 83d4b17eb45588c6e19405b99038a137c78fe179d8d2f80b7b0f16450d581c31
