### ISSUE TITLE
[package] qt/5.*: Conflict in wayland/1.21.0

### ISSUE THREAD

**Issue by Psy-Kai** [conan-io/conan-center-index#13436]
### Description

The qt package is broken again thanks to https://github.com/conan-io/conan-center-index/commit/5e0941cde56e7591ed28da6c62232669f2c59816.

wayland and fontconfig both require `expat`. But `fontconfig` still requires `expat/2.4.8` while wayland now requires `expat/2.4.9`.

This version difference in requirements of the qt package happened multiple times now and is a little bit annoying :(

### Package and Environment Details

docker image `conanio/gcc10`

### Conan profile

default profile of the docker image

### Steps to reproduce

conan install -r conancenter qt/5.15.2@ -pr:b=default -pr:h=default

### Logs

```
Error: Conflic in wayland/1.21.0:
    'wayland/1.21.0' requires 'expat/2.4.9' while 'fontconfig/2.13.93' requires 'expat/2.4.8'.
```

**Comment by Psy-Kai** [comment]
Thanks @ericLemanissier for the fast fix :)

**Comment by jwillikers** [comment]
@Psy-Kai In the future, you should be able to use `--require-override expat/2.4.9` to override an error due to conflicting dependency versions.
