### ISSUE TITLE
[question] should we be using `msvc_version_to_vs_ide_version` in recipes

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#13555]
>  Not converted to new tools, can't be used as it's part of a private import.

_Originally posted by @uilianries in https://github.com/conan-io/conan-center-index/pull/13365#discussion_r996955447_

This has some useful benefits during the 2.0 migration period

**Comment by SpaceIm** [comment]
No because it's not part of conan API. It was requested in https://github.com/conan-io/conan/issues/11158, but not provided as is. I've raises some concern in https://github.com/conan-io/conan/issues/11158#issuecomment-1252341119, waiting an answer.

**Comment by prince-chrismc** [comment]
I opened this in the wrong repository :)
