### ISSUE TITLE
[service] macOS deployment target of uploaded binaries

### ISSUE THREAD

**Issue by kambala-decapitator** [conan-io/conan-center-index#13596]
[Supported platforms page](https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md#macos) says:

> Compilers: Apple-clang versions 11.0.3, 12.0.5, 13.0.0

if I understand correctly, that would be basically Xcode 11.3.1, Xcode 12.5 and Xcode 13.0.

I run macOS 10.15 and use Xcode 12.4 there. Using default detected profile I was able to install binaries from ConanCenter (`--build=never`). But when I built my project, I noticed linker warnings like "libminizip.dylib was built for newer version (11.3) than being linked (11.1)".

I know that if deployment target flag isn't provided to apple-clang explicitly, then it simply sets it to the SDK version used. In this case, Xcode 12.5 has macOS 11.3 SDK, that's why that warning appears. Besides, checking downloaded binaries with `vtool -show-build` also showed that their deployment target is 11.3, which of course doesn't make sense for my environment.

I strongly suggest to set `os.version` in CI profiles to a value that is viable for end users:
- Apple-clang 11 (Xcode 11.x): Xcode 11.0-11.3.1 can be used at least on macOS 10.14 => set `os.version=10.14`
- Apple-clang 12 (Xcode 12.x): Xcode 12.0-12.4 can be used at least on macOS 10.15 => set `os.version=10.15`
- Apple-clang 13 (Xcode 13.x): Xcode 13.0-13.2.1 can be used at least on macOS 11 => set `os.version=11.0`
- Apple-clang 14 (Xcode 14.x): Xcode 14.0-14.?? can be used at least on macOS 12 => set `os.version=12.0`

**Comment by uilianries** [comment]
> I strongly suggest to set os.version in CI profiles to a value that is viable for end users:

Unfortunately, it will not be possible.

Conan Center already servers more than 1000 recipes, generating more than 100 packages for each recipes. Thus, adding `os.version` would be required rebuilding ALL packages, which is not possible due resources, and most important: Breaking users, because `os.version` is not configured by default on the profile.

Those provided packages are more generic as possible for general users. In case you find an incompatibility error due the configuration, I strongly suggest you building from source and pushing to your personal Artifactory instance, so you can have your specialized packages. 

This issue is similar to cases where people ask for `glibc` version as part of settings on Linux, which would result on the same scenario.

**Comment by kambala-decapitator** [comment]
> onan Center already servers more than 1000 recipes, generating more than 100 packages for each recipes. Thus, adding os.version would be required rebuilding ALL packages, which is not possible due resources, and most important: Breaking users, because os.version is not configured by default on the profile.

I see, that makes sense. Would it be possible to use some environment variable like `CFLAGS` supplied externally in order not to break profile hashes?

> Those provided packages are more generic as possible for general users. In case you find an incompatibility error due the configuration, I strongly suggest you building from source and pushing to your personal Artifactory instance, so you can have your specialized packages.

But that's exactly my case: I'm a "general user" in this scenario. I cloned a project, now I need to install its dependencies. Only `shared` option is defined on some of dependencies, this lets me download binaries from ConanCenter using my default detected profile. Conan downloads everything, I'm happy that "it just worked" without building anything. Now I build the project and see strange linker warnings. Obviously the built project doesn't run because of wrong deployment target (higher than my OS version) in dependencies. (insert "black guy happy sad" meme here)

As you can see, there's a serious problem with what Conan thinks is compatible with my profile. Either the packages should be truly compatible with my compiler + OS version or there should at least be a big warning.

> This issue is similar to cases where people ask for glibc version as part of settings on Linux, which would result on the same scenario.

but is there a possibility that if you install ConanCenter binary without glibc in profile, then it won't work on your Linux? Sorry for asking, I'm not a Linux user.

P.S. I've checked deployment target of a random library (minizip) with `-s compiler.version=11.0`: it shows 10.15.6 (and same SDK version). I should probably be able to use it when building project with apple-clang 12.0. But I'm pretty sure that a "general user" wouldn't be able to figure out such a workaround. And if a user is on macOS 10.14 with Xcode 11.3.1 (11.0 compiler), he won't be able to consume ConanCenter's binaries, although Conan will download them thinking they're compatible.

**Comment by AndreyMlashkin** [comment]
@uilianries conan v2 is exactly a point, where breaking changes may be introduced

**Comment by uilianries** [comment]
@AndreyMlashkin Conan v2 also does not add os.version by default. And, CCI only follows the default profile values from Conan client. Thus, to add `os.version` to packages, first, it should be added to Conan client by default, so it's a discussion for Conan v2 (Conan client repository).

**Comment by kambala-decapitator** [comment]
@uilianries wouldn't it work if you use `[env]` settings for CFLAGS/LFLAGS/etc instead of `os.version` to prevent hash breakage?

**Comment by uilianries** [comment]
@kambala-decapitator you can customize compiler flags, but have to remember that is not reproducible. Also, consider using `tools.build.` from conf: https://docs.conan.io/en/latest/reference/config_files/global_conf.html

**Comment by kambala-decapitator** [comment]
trusting what's written in https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md#macos , the suggestion from this issue has been taken into account (Apple-clang 13 & deployment target = 11.0). Closing.
