### ISSUE TITLE
[package] <OpenSSL>/1.0.2u>: OpenSSL <1.1.0 fails to cross compile for armv7

### ISSUE THREAD

**Issue by jheaff1** [conan-io/conan-center-index#1361]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openssl/1.0.2u**
  * Operating System+version: **Linux CentOS 7.7.1908 18.04**
  * Compiler+version: **GCC 4.9**
  * Docker image: **conanio/gcc49-armv7**
  * Conan version: **conan 1.24.0**
  * Python version: **Python 3.6.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=armv7
arch_build=x86_64
compiler=gcc
compiler.version=4.9
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)
Try to build Conan recipe for OpenSSL version < 1.1.0 using the conanio/gcc49-armv7 docker image

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
make[1]: arm-linux-gnueabihf-gcc-ar-4.9m-linux-gnueabihf-gcc-ar-4.9: Command not found
```

</details>

If I comment out line 373 of the recipe conanfile.py (and add a dummy "pass" line to prevent indentation issues), the build is successful. This code is only exercised if CROSS_COMPILE is not set.
https://github.com/conan-io/conan-center-index/blob/2ec933286818d5846232f662473dc7b2d93f2360/recipes/openssl/all/conanfile.py#L373

It seems that this issue is caused by changes in pull request https://github.com/conan-io/conan-center-index/pull/149. What also concerning is that the build logs for this pull request appear to contain errors for OpenSSL versions < 1.1.0, which could indicate false positives in the build infrastructure. The logs are given in this comment: https://github.com/conan-io/conan-center-index/pull/149#issuecomment-553866236

**Comment by SSE4** [comment]
duplicates #940

**Comment by jheaff1** [comment]
@SSE4 May I just check that you acknowledge my comment above about potential false positives in the Conan build system?

**Comment by SSE4** [comment]
@jheaff1 I did. GitHub has some connectivity issues, but I've received email notifications.

**Comment by jheaff1** [comment]
@SSE4 Great, thanks for the update
