### ISSUE TITLE
how it is expected to be used as a dependency?

### ISSUE THREAD

**Issue by sanblch** [conan-io/conan-center-index#1363]
https://github.com/conan-io/conan-center-index/blob/8031e6e4845c9b9436798dedf3095e5e06e68c2f/recipes/c-ares/all/conanfile.py#L49

Somewhy cmake and pkg-config are being removed after installation. How it is expected to append as a dependency to other recipes, where cmake is used?

**Comment by Croydon** [comment]
https://github.com/conan-io/conan-center-index/wiki/FAQ#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged

**Comment by sanblch** [comment]
Very helpful! Thank you. It still requires further development, writing Find***.cmake or changing every package recipe among dozens because they use cmake way of dependencies not smth I want to do.

**Comment by Croydon** [comment]
You don't need to write any Find*.cmake files manually you can use Conan generators to generate them for you (like the FAQ mentions)
