### ISSUE TITLE
[question] Using different host and build profiles loads two different packages. Is it a bug?

### ISSUE THREAD

**Issue by abraaocsantana** [conan-io/conan-center-index#13657]
Using different host and build profiles loads two different packages in the `pkgconf 1.7.4` package test.
I'm using `conan 1.53.0` but the same happens in older versions.

The test fails because the PKG_CONFIG environment var set by the package being tested points to:
 `'/Users/xxxx/builds/99kfQebf/0/xxxx/conan-recipes/.temp/.conan/data/pkgconf/1.7.4/xxxx/testing/package/801752c0480319b8e090188c566245a78e9abcf4/bin/pkgconf'`
While the dependency rootpath (self.deps_cpp_info["pkgconf"].rootpath) points to:
`'/Users/xxxx/builds/99kfQebf/0/xxxx/conan-recipes/.temp/.conan/data/pkgconf/1.7.4/xxxx/testing/package/a9b1e972efd63d93ad36c44dace4b07ab865fe95'`
And the second is supposed to be a root path for the first.

The problem is happening when profiles are different on MacOS Big Sur like these, where one omits the os.version:

Configuration (profile_host):
```
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os.version=10.15
[options]
pkgconf:shared=False
[build_requires]
&: cmake/3.24.1@xxxx/testing
*/testing: cmake/3.24.1@xxxx/testing
*/candidate: cmake/3.24.1@xxxx/candidate
*/stable: cmake/3.24.1@xxxx/stable
[env]
```

Configuration (profile_build):
```
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
[options]
cmake.bootstrap=True
[build_requires]
&: cmake/3.24.1@xxxx/testing
*/testing: cmake/3.24.1@xxxx/testing
*/candidate: cmake/3.24.1@xxxx/candidate
*/stable: cmake/3.24.1@xxxx/stable
[env]
```

Is this:

- a bug in conan and the two packages should be the same? 
- a bug in the package that doesn't check for this somewhat case of cross-compilation?
- the intended way of how things should be?

~~I've tested on another MacOS machine (this new one using Apple Silicon and running Monterey instead of Big Sur) and it runs OK even with the same difference in the profiles, so it's somewhat confusing.~~ _Looks like it working in the newer system was due to caching in a local server, as more packages are presenting a similar weird behavior after cleaning the server._

**Comment by prince-chrismc** [comment]
This sounds normal to be. The settings are different which means different package ID are calculated.

For tools like this, we only disregard the compiler but we assumer different OS are not compatible and if you care about the OS version then presumably that's important too.

**Comment by abraaocsantana** [comment]
Hey, @prince-chrismc ! Thanks for the answer! Generating 2 different IDs sounds OK to me, they both being loaded in the test phase was the spooky part for me, but I guess it was the second case of my question, then: the tools should've checked for cross-compilation.
