### ISSUE TITLE
[question] can we automatically delete test_package/build ?

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#13653]
When I call `conan create xyz`, it will automatically build and run test_package.

If I do it again, the previous build files remain in the test_package, and can interfere with the next conan-create execution.

So now I typically do `rm -r test_*/build; conan create something`

**Comment by uilianries** [comment]
@paulharris Please, move this question to https://githug.com/conan-io/conan/issues

ConanCenterIndex is only related to recipes, not to Conan features.

**Comment by Croydon** [comment]
> @paulharris Please, move this question to https://githug.com/conan-io/conan/issues

Nice typo: `githug` 😄

**Comment by uilianries** [comment]
🤦

**Comment by paulharris** [comment]
Yeah I had a laugh that that!   Pretty good alternative name to github IMO !

**Comment by uilianries** [comment]
When I try to write `protobuf` I almost always write `protobug` instead 😂

**Comment by samuel-emrys** [comment]
For tracking, this was recreated in https://github.com/conan-io/conan/issues/12362
