### ISSUE TITLE
[package] pdfium/cci.20210730: Building on Windows fails

### ISSUE THREAD

**Issue by Cyriuz** [conan-io/conan-center-index#13744]
### Description

I've been looking at this lib for a while and was happy to see it in conan! However, while trying to use it on Windows I encountered some issues that I'm not sure how they are intended to work.

First off, there seems to be a compile error in the version used in the package that makes it not build on Windows:

```
'pdfium::clamp': ambiguous call to overloaded function
```

It is fixed in this commit https://github.com/chromium/pdfium/commit/c9d43c039b6fa6729bbb678e9594bd9cf00a4530 so it would be enough to just update that.

Secondly I get an error trying to use libjpeg-turbo:

```
...\66bb1f4\1\source_subfolder\core/fxcodec/jpeg/jpeg_common.h(29,10): fatal error C1083: Cannot open include file: 'third_party/libjpeg_turbo/jerror.h': No such file or directory (compiling source file ...66bb1f4\1\source_subfolder\core\fxcodec\jpeg\jpeg_common.cpp)
```

The code in `jpeg_common.h` expects the includes to exist in the `third_party` folder, how is that supposed to work? Is there a patch missing or something like that?

### Package and Environment Details

* Package Name/Version: **pdfium/cci.20210730**
* Operating System+version: **Windows 11**
* Compiler+version: **MSVC 19.29.30146.0**
* Conan version: **conan 1.53.0**
* Python version: **Python 3.7.2**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter pdfium/cci.20210730@ -pr:b=default -pr:h=default -b

### Logs

<details><summary>Click to expand log</summary>

```
...\66bb1f4\1\source_subfolder\core/fxcodec/jpeg/jpeg_common.h(29,10): fatal error C1083: Cannot open include file: 'third_party/libjpeg_turbo/jerror.h': No such file or directory (compiling source file ...\66bb1f4\1\source_subfolder\core\fxcodecjpeg\jpeg_common.cpp) [...\66bb1f4\1\pdfium-cmake\cmake\core\fxcodec\pdfium_core_fxcodec.vcxproj]
...\66bb1f4\1\source_subfolder\core/fxcodec/jpeg/jpeg_common.h(29,10): fatal error C1083: Cannot open include file: 'third_party/libjpeg_turbo/jerror.h': No such file or directory (compiling source file ...\66bb1f4\1\source_subfolder\core\fxcodecjpeg\jpegmodule.cpp) [...\66bb1f4\1\pdfium-cmake\cmake\core\fxcodec\pdfium_core_fxcodec.vcxproj]
pdfium/cci.20210730:
pdfium/cci.20210730: ERROR: Package 'c1ba6689584f05433266ed8165cb6b4c409c638e' build failed
```

</details>

**Comment by valgur** [comment]
Can probably be closed. The v2 migration PR built without issues on Windows.
