### ISSUE TITLE
[service] Improve YAML linter error message for missing keywords in conandata.yml

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#13778]
The PR #13274 help users to identify that `conandata.yml` need some update regarding those patches listed in the file. However, the current output looks more a bug from the linter than an useful information:

![Screenshot 2022-10-26 at 16-12-55 highway conan v2 support by SpaceIm · Pull Request #13747 · conan-io_conan-center-index](https://user-images.githubusercontent.com/4870173/198050848-f710e8dd-2f33-4339-b1ce-57794711906a.png)

It could be improved, adding a link to https://github.com/conan-io/conan-center-index/blob/master/docs/conandata_yml_format.md#patches-fields or more specific for those missing patch fields.

Also, the current message:

```
required key(s) 'patch_description', 'patch_type' not found in "<unicode_string>", line 22, column 1
```

It does not look helpful:

- The line 22 only can contain one keyword, so it can not add more patches fields there. It looks confuse.
- Column number does not help here, it could be removed, as only one field can be added for each line
- The line number does not look really useful IMO, because the linter already points to the wrong line which is broken. And when running pylint locally, the line number is part of the log itself.
- `"<unicode_string>"` it looks more an internal bug than a final message

IHMO it could be:

```
The patch 'patch_file/0.16.0-00010-fix-sys-random.patch' is missing a description. Please, add [patch_description](https://github.com/conan-io/conan-center-index/blob/master/docs/conandata_yml_format.md#patch_description) field
```

Same for other missing fields.

**Comment by SpaceIm** [comment]
Moreover the linter could handle a list in patch_source (yes sometimes one patch can be made of several upstream PR related to the same topic).

**Comment by prince-chrismc** [comment]
> Moreover the linter could handle a list in patch_source (yes sometimes one patch can be made of several upstream PR related to the same topic).

Several PRs should be seperate patches IMO. It's just a string so you can multi line add as many as you want (e.g there's two issues and PR). It would look like

```yaml
    patch_source: |
         https://whfudsugsdf.aosdhf;uiag/urhewurfhpwhfvp
         ... another here 
         ... etc
```

We can always fixup older recipes if the client gains functionality like maybe CVE tracking 🤷 I dont think we should do extra work unless it required.

For now the goal is to start tracking the information and provide a benefit to consumers -- once we decide how it can be used we can revisit the structures

**Comment by prince-chrismc** [comment]
As for improving the error message, we are limited to what already exists

I can do

***

**conandata.yml schema error**
required key(s) 'patch_description', 'patch_type' not found in
```yml
      - patch_file: patches/0.16.0-0 ... 
    ^ (line: 25)
```

***

If that enough?

**Comment by prince-chrismc** [comment]
Opened the PR :)

**Comment by prince-chrismc** [comment]
#14015 could use some reviews
