### ISSUE TITLE
[package] gtest/1.10.0 is removed

### ISSUE THREAD

**Issue by kexianda** [conan-io/conan-center-index#13803]
### Description

gtest >1.10.0 has an annoying compatibility issue.
gtest try to disable implicit conversion from 'enum class' to 'int'. it is ok, fmt::fmt also does not allow implicit conversion. 
in fmt::fmt, the user can add a templated customized version, source will be happily pass the compilation.
but in gtest(>1.10), the users are forced to write a customized version for every enum class type. it is very PAINFUL to do so when you has lots of enum class types. 

So, pls also support 1.10.  @prince-chrismc 

### Package and Environment Details

N/A

### Conan profile

N/A

### Steps to reproduce

N/A

### Logs

N/A

**Comment by uilianries** [comment]
@kexianda Please, update your title. No package is removed from Conan Center, including gtest.

GTest/1.10.0 is outdated and removing it simplified the recipe a lot, that was the main motivation.

> gtest try to disable implicit conversion from 'enum class' to 'int'. it is ok, fmt::fmt also does not allow implicit conversion.

Is it a recipe limitation or Gtest limitation? Why not opening an issue to Gtest to improve it instead?

> So, pls also support 1.10.

As ConanCenterIndex is open source you can open an PR, adding 1.10 to the build configuration 😉

**Comment by kexianda** [comment]
> ConanCenterIndex

Thanks for your reply. I will open an PR when I am free
