### ISSUE TITLE
[service] Version check not taking into account more than one conandata.yml

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#1386]
coming from conan-io/conan-center-index#1312 and https://github.com/conan-io/conan-center-index/pull/1385

Currently, there are some checks done to make sure the versions in the config.yml are as well in the conandata.yml. However, it covers only the cases where there is only one conandata.yml and not the one where there is one recipe per library version.

**Comment by Croydon** [comment]
Is the `config.yml` file really needed after all? 

Can't we just re-iterate over all first-level sub-directories and look into the respective `conandata.yml` files to get a list of versions?

**Comment by Croydon** [comment]
Having this duplication of information seems to cause continuously pain 🤔

**Comment by danimtb** [comment]
the config.yml can be omitted if the folder contains the *fixed* version of that recipe. However, er are seeing some libs that have a recipe for all of the 6.X.X versions and another one for all the 7.X.X ones.

Parsing the conandata.yml could be an option for this as you pointed out.

**Comment by uilianries** [comment]
> Parsing the conandata.yml could be an option for this as you pointed out.

Yes, please!

**Comment by danimtb** [comment]
Still, we have to consider if there could be a package in the future without conandata.yml. Something like a _proxy_ or virtual recipe

**Comment by ericLemanissier** [comment]
in the case of a proxy or virtual recipe, both yml are actually unneeded, because there is no source and no real version. In this case there could be `version = "virtual"` or `version = "proxy"` hard-coded in the conanfile.py.

**Comment by danimtb** [comment]
The original issue was fixed so I am closing this. Currently removing the config.yml cannot be done. We might reconsider this for the future. Thanks!
