### ISSUE TITLE
[question] sha256 for patches

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan-center-index#13870]
Current package templates contain "sha256" field not only for sources, but also for patches. I've tried using this field but values are completely ignored. Should recipes check sha256 for patch-files explicitly if they are present? Or is there some conan setting that enables this check?

**Comment by SpaceIm** [comment]
Indeed, conan client doesn't know at all this field in `apply_conandata_patches`, `patch` and `export_conandata_patches`, it's informational I guess.

https://github.com/conan-io/conan-center-index/pull/11713#issuecomment-1195272604

**Comment by prince-chrismc** [comment]
I wasn't privy to the original conversation but since we have "offical" and "backport" it might be helpful in the future. 

 it's best effort if you include it :)

**Comment by uilianries** [comment]
Please, keep filling `sha256`. I opened a new issue to Conan client, asking to support it:

https://github.com/conan-io/conan/issues/12455

**Comment by Croydon** [comment]
I don't understand the purpose of it as long as all patch files are local. Either you can trust local files (patch files + `conandata.yml` among others) or you can't. And if you can trust local files then you can just calculate the checksum on the fly if necessary.

I only see a point in it when we start supporting downloading patches from somewhere.

**Comment by prince-chrismc** [comment]
IT was removed fomr the docs so I will close this.

Thanks for poking this :)
