### ISSUE TITLE
[conan.io/center] Markdown failed `jsonformoderncpp/3.7.0@#41974b90ded06a98109b36f5250970ad`

### ISSUE THREAD

**Issue by AntAgna** [conan-io/conan-center-index#13930]
Going to https://conan.io/center/jsonformoderncpp?tab=useit
Gives: Markdown generator failed for reference 'jsonformoderncpp/3.7.0@#41974b90ded06a98109b36f5250970ad'. Please report [here](https://github.com/conan-io/conan-center-index/issues/new?assignees=&labels=conan.io%2Fcenter&template=center_conan_io.md&title=%5Bconan.io%2Fcenter%5D+Markdown+failed+%60jsonformoderncpp/3.7.0@%2341974b90ded06a98109b36f5250970ad%60).

**Comment by prince-chrismc** [comment]
You might want to use https://conan.io/center/nlohmann_json?tab=useit instead 😉

**Comment by AntAgna** [comment]
Yes. Thank you.
