### ISSUE TITLE
openssl/1.1.1n: Recipe works for VS2019 but not VS2022

### ISSUE THREAD

**Issue by gprosch** [conan-io/conan-center-index#13934]
### Description

When I run the following conan install command with compiler.version="16" it works.  But when I run it with compiler.version="17" (VS2022) it fails.

### Package and Environment Details

* Package Name/Version: **openssl/1.1.1n**
* Operating System+version: **Windows 11**
* Compiler+version: **Visual Studio 2022**
* Conan version: **conan 1.53.0**
* Python version: **Python 3.11.0**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce

conan install conanfile.txt" -s os="Windows" -s arch="x86_64" -s build_type="Release" -s compiler="Visual Studio" -s compiler.version="17" --update --build=missing

### Logs

<details><summary>Click to expand log</summary>

PS C:\dev\FieldRep.master\scripts> conan install "C:\dev\FieldRep.master\Projects\WebSDK\PreBuild\conanfile.txt" -s os="Windows" -s arch="x86_64" -s build_type="Release" -s compiler="Visual Studio" -s compiler.version="17" --update --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

openssl/1.1.1n: WARN: Package binary is corrupted, removing: 5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
conanfile.txt: Installing package
Requirements
    cef/91.1.22@trancite/stable from local cache - No remote
    imgsource/6.0.4@trancite/stable from local cache - No remote
    libcurl/7.77.0 from local cache - No remote
    libiconv/1.16 from local cache - No remote
    libxml2/2.9.10 from local cache - No remote
    msvc/14.29.30133@trancite/stable from local cache - No remote
    openssl/1.1.1n from local cache - No remote
    pplus/5.22.1@trancite/stable from local cache - No remote
    zlib/1.2.11 from local cache - No remote
Packages
    cef/91.1.22@trancite/stable:e9a552ebe8f994398de9ceee972f0ad207df0658 - Cache
    imgsource/6.0.4@trancite/stable:e9a552ebe8f994398de9ceee972f0ad207df0658 - Cache
    libcurl/7.77.0:2bc235d01a6774a90a27bed062f4b76de7ee3a40 - Build
    libiconv/1.16:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Cache
    libxml2/2.9.10:77c83943028aeda4b502557bd0b671409529a8bf - Cache
    msvc/14.29.30133@trancite/stable:e9a552ebe8f994398de9ceee972f0ad207df0658 - Cache
    openssl/1.1.1n:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Build
    pplus/5.22.1@trancite/stable:eea5bfae511651d5fb0bc68e1ac128740bb640a8 - Build
    zlib/1.2.11:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Cache
Build requirements
    nasm/2.15.05 from local cache - No remote
    strawberryperl/5.30.0.1 from local cache - No remote
Build requirements packages
    nasm/2.15.05:0a420ff5c47119e668867cdb51baff0eca1fdb68 - Cache
    strawberryperl/5.30.0.1:456f15897172eef340fcbac8a70811f2beb26a93 - Cache

Installing (downloading, building) binaries...
cef/91.1.22@trancite/stable: Already installed!
imgsource/6.0.4@trancite/stable: Already installed!
libiconv/1.16: Already installed!
libiconv/1.16: Appending PATH environment var: C:\Users\gregp\.conan\data\libiconv\1.16\_\_\package\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b\bin
msvc/14.29.30133@trancite/stable: Already installed!
nasm/2.15.05: Already installed!
nasm/2.15.05: Appending PATH environment variable: C:\Users\gregp\.conan\data\nasm\2.15.05\_\_\package\0a420ff5c47119e668867cdb51baff0eca1fdb68\bin
strawberryperl/5.30.0.1: Already installed!
strawberryperl/5.30.0.1: Appending PATH environment variable: C:\.conan\0aa2c9\1\bin
zlib/1.2.11: Already installed!
libxml2/2.9.10: Already installed!
libxml2/2.9.10: Appending PATH environment variable: C:\Users\gregp\.conan\data\libxml2\2.9.10\_\_\package\77c83943028aeda4b502557bd0b671409529a8bf\bin
openssl/1.1.1n: Applying build-requirement: strawberryperl/5.30.0.1
openssl/1.1.1n: Applying build-requirement: nasm/2.15.05
openssl/1.1.1n: WARN: Build folder is dirty, removing it: C:\Users\gregp\.conan\data\openssl\1.1.1n\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
openssl/1.1.1n: Copying sources to build folder
openssl/1.1.1n: Building your package in C:\Users\gregp\.conan\data\openssl\1.1.1n\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
openssl/1.1.1n: Generator txt created conanbuildinfo.txt
openssl/1.1.1n: Aggregating env generators
openssl/1.1.1n: Calling build()
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.3.6
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
openssl/1.1.1n:
openssl/1.1.1n: ERROR: Package '5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b' build failed
openssl/1.1.1n: WARN: Build folder C:\Users\gregp\.conan\data\openssl\1.1.1n\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
ERROR: openssl/1.1.1n: Error in build() method, line 757
        self._create_targets()
while calling '_create_targets', line 608
        ancestor = '[ "%s" ]' % self._ancestor_target
while calling '_ancestor_target', line 430
        compiler = "Visual Studio" if self.settings.compiler == "msvc" else self.settings.compiler
        ConanException: Invalid setting 'msvc' is not a valid 'settings.compiler' value.
Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'qcc', 'sun-cc']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
</details>

**Comment by prince-chrismc** [comment]
You need to check that your setting are updated, when the client is updated it will try to migrate the `setting.yml` to the newest version but it wont do so if it's been modified by the user.

in your `$CONAN_USER_HOME` folder there will be a `settings.yml` file, when it fails it created a `settings.yml.new` file.

There's a warning when it migrates. but it's very easy to miss

**Comment by gprosch** [comment]
@prince-chrismc That was precisely my issue.  Thank you for the resolution!
