### ISSUE TITLE
[question] Have recipes more autonomous

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan-center-index#13951]
Hi conan community,

I'm working in a continuous integration context based on Docker.
And i'm looking to use Docker images with minimal overhead, typically only conan and gcc.
But I'm often in case where a dependency need to be build and fails because of missing cmake, make, ... .
What do you think about update some tool_requires's recipe to have them more autonomous?
What do you think about update https://github.com/conan-io/conan-center-index/blob/master/docs/package_templates/cmake_package/all/conanfile.py#L102 to add cmake and ninja?
Currently I have issue with grpc and related recipes.

Regards.

**Comment by ericLemanissier** [comment]
Did you try using these images https://github.com/conan-io/conan-docker-tools?

**Comment by EstebanDugueperoux2** [comment]
Hi @ericLemanissier,

Yes I know conan-docker-tools, I use them for some of my projects.
But for others, having constraints, I would like to use tool_requires instead of having all build requirements in the docker images.
What do you think about this idea of minimal docker image?
To go further I see the there is a gcc recipe in conan center (https://conan.io/center/gcc) then in a corporate case, we could imagine all possible build requires even gcc. 
What do you think about?

Regards.

**Comment by SpaceIm** [comment]
> What do you think about update some tool_requires's recipe to have them more autonomous?

It's too much for CMake. Why don't you add it to tool_requires of conan profiles in your docker image?

**Comment by EstebanDugueperoux2** [comment]
Yes I can add all build requirements of my recipe in the build profile but in case a dependency, qt for example, need a new build, I must also have its build requirements, qmake in case of qt, in my profile.
And I must anticipate that case for all my dependencies and transitives ones.

**Comment by SpaceIm** [comment]
No, only a compiler toolchain & CMake are required on system as build tools. For all other build tools, conan-center recipes assume that they might not be installed.
