### ISSUE TITLE
[service] corrade/2019.10 has only Linux builds and most are outdated

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#1397]
For some reason I don't understand `corrade/2019.10` has only Linux builds and most of them are outdated.

Is this an error of the recipe or of the CI?

![corradebuilds](https://user-images.githubusercontent.com/1593194/79624377-94e28b00-8121-11ea-9551-f7acef5017cf.PNG)

https://github.com/conan-io/conan-center-index/tree/master/recipes/corrade

Latest PR: #1335

**Comment by danimtb** [comment]
Can this be related to #200?

**Comment by Croydon** [comment]
Not sure if this explains the outdated packages, but if so, there would still be the problem of missing Windows and macOS builds

**Comment by helmesjo** [comment]
Anything new here? Or is it resolved?

**Comment by danimtb** [comment]
See https://github.com/conan-io/conan-center-index/pull/2111#issuecomment-653416328 to know what was happening
