### ISSUE TITLE
[package] boost/1.78.0: undefined reference to 'test_main'

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan-center-index#13983]
### Description

/usr/bin/ld: /data/.data/boost/1.78.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/lib/libboost_test_exec_monitor.a(test_main.o): in function `boost::detail::function::void_function_obj_invoker0<test_main_caller, void>::invoke(boost::detail::function::function_buffer&)':
test_main.cpp:(.text._ZN5boost6detail8function26void_function_obj_invoker0I16test_main_callervE6invokeERNS1_15function_bufferE[_ZN5boost6detail8function26void_function_obj_invoker0I16test_main_callervE6invokeERNS1_15function_bufferE]+0x71): undefined reference to `test_main(int, char**)'

### Package and Environment Details

* Package Name/Version: **boost/1.78.0**
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **GCC 9**
* Conan version: **conan 1.51.3**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True
[build_requires]
[env]

### Steps to reproduce

find_package(Boost REQUIRED)
target_link_libraries(${PROJECT_NAME} boost::boost)

### Logs

<details><summary>Click to expand log</summary>

```
/usr/bin/ld: /data/.data/boost/1.78.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/lib/libboost_test_exec_monitor.a(test_main.o): in function `boost::detail::function::void_function_obj_invoker0<test_main_caller, void>::invoke(boost::detail::function::function_buffer&)':
test_main.cpp:(.text._ZN5boost6detail8function26void_function_obj_invoker0I16test_main_callervE6invokeERNS1_15function_bufferE[_ZN5boost6detail8function26void_function_obj_invoker0I16test_main_callervE6invokeERNS1_15function_bufferE]+0x71): undefined reference to `test_main(int, char**)'
```

</details>

**Comment by cqc-alec** [comment]
@Tumb1eweed What was the solution to this issue? I am getting the same error.

**Comment by Tumb1eweed** [comment]
oh, in my case I mistakenly used a source file lack of main function and use it to add_executable, at the same time link boost::filesystem, so the linker suppose the source file need test_main.

**Comment by daweifeng** [comment]
I am having the same issue. I fixed it by replacing ` target_link_libraries(${PROJECT_NAME} boost::boost)` with ` target_link_libraries(${PROJECT_NAME} boost::header)` since I am only using some of the header files in my code.

**Comment by poxerial** [comment]
I also encountered the same problem. It is the conflict between Boost's test library and gtest. I fixed it just by disabling the boost test.

**Comment by Molin-L** [comment]
In my case, it's also because gtest, just simply move `Gtest::gtest_main` to the top:
```cmake
target_link_libraries(${PROJECT_NAME}_tests
    GTest::gtest_main
    connection
    GTest::gtest
    libpcap::libpcap
    pthread
)
```
