### ISSUE TITLE
[package] jansson/2.12: unable to download sources error 503

### ISSUE THREAD

**Issue by timblechmann** [conan-io/conan-center-index#1399]
today i ran into:

```
jansson/2.12: Configuring sources in /home/ubuntu/.conan/data/jansson/2.12/_/_/source
Waiting 5 seconds to retry...
ERROR: Error 503 downloading file http://www.digip.org/jansson/releases/jansson-2.12.tar.gz
ERROR: jansson/2.12: Error in source() method, line 32
        tools.get(**self.conan_data["sources"][self.version])
        ConanException: Error 503 downloading file http://www.digip.org/jansson/releases/jansson-2.12.tar.gz
```

it seems that the recipe refers to the tarball on the upstream server, which is (currently?) down. since this kind of issues can always occur, i'm wondering what's the best strategy to avoid them to avoid downtimes? e.g. would it be possible to mirror the tarball on conan servers?

**Comment by SSE4** [comment]
such issues happen from time to time, we may mirror source to the bintray, as we did for bzip2 in the past

**Comment by Croydon** [comment]
Jansson has an official GitHub repo. Does the source download differ from there? https://github.com/akheron/jansson/releases

**Comment by danimtb** [comment]
sure, we can switch to the GitHub sources instead

**Comment by timblechmann** [comment]
thanks for all the replies. it seems that the upstream server is back again, but switching to github might reduce the risk of running into server downtimes
