### ISSUE TITLE
[package] libaec/1.0.6: suddenly getting cmake/ninja errors: multiple rules generate src/aec

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#14004]
### Description

I only recently upgraded the recipe for libaec for conan v2,
and I don't think anything has changed in my environment,
but suddenly I can't build the libaec package!

Error message is:

```
-- Generating done
CMake Error:
  Running

   '/build/msrap2/devenv/bin/ninja' '-C' '/build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1/build/Release' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:700: multiple rules generate src/aec [-w dupbuild=err]
```

It appears that cmake / ninja doesn't like the line:
`set_target_properties(aec_client PROPERTIES OUTPUT_NAME aec)`
in libaec's CMakeLists.txt

But the CI is using Makefile generators, not Ninja, so it isn't being detected by the CI.

Weirdly, I've been using Ninja locally the whole time, so I don't know why I didn't see this issue earlier,
AND,
why is this a problem at all?

The two targets in question in cmake are:
```
add_library(aec OBJECT encode.c encode_accessors.c decode.c)
```
```
add_executable(aec_client aec.c)
set_target_properties(aec_client PROPERTIES OUTPUT_NAME aec)
```

The first ends up as a PHONY target in Ninja,
the second's target isn't the same name, although yes it outputs to 'aec'.

Any ideas?

### Package and Environment Details

libaec, conan 1.53.0, linux

### Conan profile

gcc with Ninja generator

### Steps to reproduce

 conan create . libaec/1.0.6@ -c tools.cmake.cmaketoolchain:generator=Ninja

with the current libaec recipe

### Logs

[HOOK - conan-center.py] pre_export(): [DEPRECATED GLOBAL CPPSTD (KB-H001)] OK
[HOOK - conan-center.py] pre_export(): [REFERENCE LOWERCASE (KB-H002)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE METADATA (KB-H003)] OK
[HOOK - conan-center.py] pre_export(): [HEADER_ONLY, NO COPY SOURCE (KB-H005)] OK
[HOOK - conan-center.py] pre_export(): [FPIC OPTION (KB-H006)] OK
[HOOK - conan-center.py] pre_export(): [VERSION RANGES (KB-H008)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] Total recipe size: 16.9765625 KB
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] OK
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE FOLDER (KB-H024)] OK
[HOOK - conan-center.py] pre_export(): [META LINES (KB-H025)] OK
[HOOK - conan-center.py] pre_export(): [CONAN CENTER INDEX URL (KB-H027)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE MINIMUM VERSION (KB-H028)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - RUN ENVIRONMENT (KB-H029)] OK
[HOOK - conan-center.py] pre_export(): [SYSTEM REQUIREMENTS (KB-H032)] OK
[HOOK - conan-center.py] pre_export(): [CONANDATA.YML FORMAT (KB-H030)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO IMPORTS() (KB-H034)] OK
[HOOK - conan-center.py] pre_export(): [NO AUTHOR (KB-H037)] OK
[HOOK - conan-center.py] pre_export(): [NOT ALLOWED ATTRIBUTES (KB-H039)] OK
[HOOK - conan-center.py] pre_export(): [NO TARGET NAME (KB-H040)] OK
[HOOK - conan-center.py] pre_export(): [NO FINAL ENDLINE (KB-H041)] OK
[HOOK - conan-center.py] pre_export(): [NO REQUIRES.ADD() (KB-H044)] OK
[HOOK - conan-center.py] pre_export(): [DELETE OPTIONS (KB-H045)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE VERBOSE MAKEFILE (KB-H046)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE VERSION REQUIRED (KB-H048)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE WINDOWS EXPORT ALL SYMBOLS (KB-H049)] OK
[HOOK - conan-center.py] pre_export(): [DEFAULT OPTIONS AS DICTIONARY (KB-H051)] OK
[HOOK - conan-center.py] pre_export(): [CONFIG.YML HAS NEW VERSION (KB-H052)] OK
[HOOK - conan-center.py] pre_export(): [PRIVATE IMPORTS (KB-H053)] OK
[HOOK - conan-center.py] pre_export(): [SINGLE REQUIRES (KB-H055)] OK
[HOOK - conan-center.py] pre_export(): [TOOLS RENAME (KB-H057)] OK
[HOOK - conan-center.py] pre_export(): [ILLEGAL CHARACTERS (KB-H058)] OK
[HOOK - conan-center.py] pre_export(): [CLASS NAME (KB-H059)] OK
[HOOK - conan-center.py] pre_export(): [NO CRLF (KB-H060)] OK
[HOOK - conan-center.py] pre_export(): [NO BUILD SYSTEM FUNCTIONS (KB-H061)] OK
[HOOK - conan-center.py] pre_export(): [TOOLS CROSS BUILDING (KB-H062)] OK
[HOOK - conan-center.py] pre_export(): [INVALID TOPICS (KB-H064)] OK
[HOOK - conan-center.py] pre_export(): [NO REQUIRED_CONAN_VERSION (KB-H065)] OK
[HOOK - conan-center.py] pre_export(): [TEST_TYPE MANAGEMENT (KB-H068)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO DEFAULT OPTIONS (KB-H069)] OK
[HOOK - conan-center.py] pre_export(): [MANDATORY SETTINGS (KB-H070)] OK
[HOOK - conan-center.py] pre_export(): [PYLINT EXECUTION (KB-H072)] OK
[HOOK - conan-center.py] pre_export(): [TEST V1 PACKAGE FOLDER (KB-H073)] OK
Exporting package recipe
libaec/1.0.6 exports: File 'conandata.yml' found. Exporting it...
libaec/1.0.6 exports: Copied 1 '.yml' file: conandata.yml
libaec/1.0.6: Calling export_sources()
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] Saving conandata.yml: {'sources': {'1.0.6': {'url': 'https://gitlab.dkrz.de/k202009/libaec/uploads/45b10e42123edd26ab7b3ad92bcf7be2/libaec-1.0.6.tar.gz', 'sha256': '032961877231113bb094ef224085e6d66fd670f85a3e17f53d0f131abf24f2fd'}}, 'patches': {'1.0.6': [{'patch_file': 'patches/1.0.6-0001-fix-library-builds.patch'}]}}
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] New conandata.yml contents: patches:
  1.0.6:
  - patch_file: patches/1.0.6-0001-fix-library-builds.patch
sources:
  1.0.6:
    sha256: 032961877231113bb094ef224085e6d66fd670f85a3e17f53d0f131abf24f2fd
    url: https://gitlab.dkrz.de/k202009/libaec/uploads/45b10e42123edd26ab7b3ad92bcf7be2/libaec-1.0.6.tar.gz

[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] OK
[HOOK - conan-center.py] post_export(): [DEFAULT SHARED OPTION VALUE (KB-H050)] OK
[HOOK - conan-center.py] post_export(): [LICENSE PUBLIC DOMAIN (KB-H056)] OK
libaec/1.0.6: The stored package has not changed
libaec/1.0.6: Using the exported files summary hash as the recipe revision: 4211ff05de98df7dbf4ea3118bb2aea8 
libaec/1.0.6: Exported revision: 4211ff05de98df7dbf4ea3118bb2aea8
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.hack_dont_download_cci=True
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
boost:asio_no_deprecated=True
boost:filesystem_no_deprecated=True
boost:layout=tagged
boost:magic_autolink=False
boost:system_no_deprecated=True
boost:system_use_utf8=True
ffmpeg:avdevice=False
ffmpeg:avfilter=False
ffmpeg:postproc=False
ffmpeg:with_freetype=False
ffmpeg:with_libalsa=False
ffmpeg:with_programs=False
ffmpeg:with_pulse=False
ffmpeg:with_ssl=False
ffmpeg:with_xcb=False
libcurl:with_dict=False
libcurl:with_file=False
libcurl:with_ftp=False
libcurl:with_gopher=False
libcurl:with_imap=False
libcurl:with_mqtt=False
libcurl:with_pop3=False
libcurl:with_rtsp=False
libcurl:with_smb=False
libcurl:with_smtp=False
libcurl:with_symbol_hiding=True
libcurl:with_telnet=False
libcurl:with_tftp=False
libcurl:with_unix_sockets=False
libtiff:jpeg=libjpeg-turbo
qt:qtmultimedia=True
qt:qtsvg=True
qt:qttools=True
qt:shared=True
qt:with_libjpeg=libjpeg-turbo
qt:with_mysql=False
qt:with_odbc=False
qt:with_pq=False
qt:with_zstd=True
vtk:build_all_modules=False
vtk:group_enable_Rendering=WANT
vtk:module_enable_GUISupportQt=WANT
vtk:module_enable_RenderingQt=WANT
vtk:use_64bit_ids=False
vtk:use_source_from_git=True
[build_requires]
[env]
CC=/usr/lib/ccache/gcc-11
CCACHE_COMPRESS=1
CXX=/usr/lib/ccache/g++-11
[conf]
tools.build:jobs=4
tools.cmake.cmaketoolchain:generator=Ninja

libaec/1.0.6: Forced build from source
libaec/1.0.6 (test package): Installing package
Requirements
    libaec/1.0.6 from 'conancenter' - Cache
Packages
    libaec/1.0.6:0582ee0920dad9fef631620d3ef80b963208d3a1 - Build

Installing (downloading, building) binaries...
libaec/1.0.6: Copying sources to build folder
libaec/1.0.6: Building your package in /build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1
libaec/1.0.6: Generator txt created conanbuildinfo.txt
libaec/1.0.6: Calling generate()
libaec/1.0.6: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
libaec/1.0.6: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G Ninja -DCMAKE_TOOLCHAIN_FILE=/build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1/build/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0077=NEW -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
libaec/1.0.6: Aggregating env generators
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK. 'fPIC' option found and apparently well managed
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
libaec/1.0.6: Calling build()
libaec/1.0.6: CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/build/conandata/conan-data/libaec/1.0.6/_/_/package/0582ee0920dad9fef631620d3ef80b963208d3a1" -DCMAKE_POLICY_DEFAULT_CMP0077="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1/src"
-- Using Conan toolchain: /build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/gcc-11 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test HAVE_DECL___BUILTIN_CLZLL
-- Performing Test HAVE_DECL___BUILTIN_CLZLL - Success
-- Looking for snprintf
-- Looking for snprintf - found
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Configuring done
-- Generating done
CMake Error:
  Running

   '/build/msrap2/devenv/bin/ninja' '-C' '/build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1/build/Release' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:700: multiple rules generate src/aec [-w dupbuild=err]

  

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0077
    CMAKE_POLICY_DEFAULT_CMP0091

CMake Generate step failed.  Build files cannot be regenerated correctly.
libaec/1.0.6: 
libaec/1.0.6: WARN: Build folder is dirty, removing it: /build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1
libaec/1.0.6: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
libaec/1.0.6: ERROR: Package '0582ee0920dad9fef631620d3ef80b963208d3a1' build failed
libaec/1.0.6: WARN: Build folder /build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1/build/Release
ERROR: libaec/1.0.6: Error in build() method, line 79
	cmake.configure()
	ConanException: Error 1 while executing cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/build/conandata/conan-data/libaec/1.0.6/_/_/package/0582ee0920dad9fef631620d3ef80b963208d3a1" -DCMAKE_POLICY_DEFAULT_CMP0077="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/build/conandata/conan-data/libaec/1.0.6/_/_/build/0582ee0920dad9fef631620d3ef80b963208d3a1/src"

**Comment by paulharris** [comment]
Note that this works fine with the Makefile generator, because Make doesn't have quality checks (I guess).
Or is it that Ninja is wrong?

**Comment by SpaceIm** [comment]
Try to inject `set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)` in upstream CMakeLists.txt to avoid conflicts, it was injected by cmake generator, but not in CMakeToolchain so it can lead to issues in Ninja generator in builds overriding output target name with the same name than another target.

**Comment by paulharris** [comment]
Perfect, thanks!

**Comment by paulharris** [comment]
I assume there is nothing further to fix in conan related to this.
