### ISSUE TITLE
package <xerces-c>/<3.2.2>: Link to sources not working any more

### ISSUE THREAD

**Issue by keckxde** [conan-io/conan-center-index#1400]
The link in the conandata.yml is outdated, and not working any more

http://apache.rediris.es//xerces/c/3/sources/xerces-c-3.2.2.tar.bz2

A better link would be the following:

https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-3.2.2.tar.bz2

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **xerces-c/3.2.2**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.24.0**
  * Python version: **Python 3.8.2**

### Conan profile

independant - problem for all platforms, when building from source

### Steps to reproduce 

conan install . --build

**Comment by uilianries** [comment]
Hi @keckxde ! Thanks for reporting!

**Comment by keckxde** [comment]
Hi @uilianries  - Thank you for fixing!!!!
