### ISSUE TITLE
[cmake] cmake uses OpenSSL within its recipe but does not depend on it?

### ISSUE THREAD

**Issue by fulara** [conan-io/conan-center-index#1401]
There are mentions of openssl within the conanfile, and cmake can be build with openssl dependency to allow download for https stuff. see: 
https://github.com/conan-io/conan-center-index/blob/master/recipes/cmake/all/conanfile.py#L52

However recipe present in this repository has no dependency even conditional one on openssl. 
This causes issues like this:
```
 Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
CMake Error at Utilities/cmcurl/CMakeLists.txt:454 (message):
```
When trying to build it on the systems that dont have libssl-devel installed by default.
Any particular reason why openssl was not added as a build requires even a conditional one?

**Comment by SSE4** [comment]
@uilianries do you remember about this one?
might it be a circular dependency? (cmake -> openssl -> zlib -> cmake)

**Comment by fulara** [comment]
Hello @SSE4 , sorry to chip in - anyway according to your wiki:
`We generally consider tools like CMake as a standard tool to have installed in your system. `
So it will only be a problem if someone added `cmake` to build_requires. one could handle it by adding check in configure whether someone has not added `cmake` into build requires and throw an exception this.

raised https://github.com/conan-io/conan/issues/6881 anyway as I think that scenario should be possible and currently its conan limitation that it is not. (at least I think so. )

**Comment by uilianries** [comment]
Because we use Docker for any build. All docker images contain OpenSSL installed, because we need to download using HTTPS.

**Comment by uilianries** [comment]
Anyway, no one complained about it as an error, and CMake recipe is pretty old, more than 2 years (we ported from conan-community). Do we really need OpenSSL as requirement? I prefer to leave it as is

**Comment by uilianries** [comment]
@fulara So do you have a system without openssl installed and why do need cmake installer, any specific package?

**Comment by fulara** [comment]
hello @uilianries  whats my need:
I am using fresh rh7 build.
It does not have libssl-devel installed by default (not sure about libssl ).
I need to build custom cmake because system one is not build against libssl so its unable to fetch packages. (DOWNLOAD does not work with https )
On top of that I would like to build cmake in build_requires because I want to have modern versions.

**Comment by uilianries** [comment]
@fulara I see, your case sounds legit. Well, so we need to update the cmake package.

**Comment by SSE4** [comment]
@uilianries if OpenSSL is required for build, we need to make it a dependency in conan. libssl-dev might not be always available (and even if it's available, it makes build non-reproducible). that's easy to change, but I am very concerned here about introducing a circular dependency here, which is hard to break...

**Comment by fulara** [comment]
@SSE4  maybe its worth waiting for @jgsogo' xbuild functionality then?

**Comment by uilianries** [comment]
@SSE4 I think we can use openssl as private dependency to avoid it.

**Comment by ericLemanissier** [comment]
regarding the dependency cycle, CMake recipe already requires cmake, so how worse could it become ?

**Comment by jgsogo** [comment]
Using CMake as `build_requires` in the `cmake` recipe works with the new model 😉  Here you  can find an example for `gcc` using `gcc` (fake recipes, of course 😅 ): https://github.com/jgsogo/conan-xbuild

**Comment by Minimonium** [comment]
> libssl-dev might not be always available 

I've stumbled upon that issue on Arch, they don't provide static versions of stuff. :slightly_smiling_face:

**Comment by perseoGI** [comment]
Hi there!
I'm closing this very old issue as there have been plenty of changes in CMake recipe and this thread has become deprecated.
CMake is not compiled right now but instead, binaries are provided. 
If the problem remains, do not hesitate to create a new issue reporting the problem in an updated environment!

Happy coding 🐸
