### ISSUE TITLE
[service] msbuild package template has import incompatible with Conan 2.0

### ISSUE THREAD

**Issue by partiallyderived** [conan-io/conan-center-index#14098]
At https://github.com/conan-io/conan-center-index/blob/53ef0688c436c6697d8312d47fcdef68fe7e6955/docs/package_templates/msbuild_package/all/conanfile.py#L4, `vs_layout` is imported from `conan.tools.layout`. However, when using this import in [my PR](https://github.com/conan-io/conan-center-index/pull/13646), the CI informed me that the recipe was not ready for Conan v2, citing this import error:

```
ERROR: Error loading conanfile at '/home/conan/w/prod_cci_PR-13646/recipes/lzham/all/conanfile.py': Unable to load conanfile in /home/conan/w/prod_cci_PR-13646/recipes/lzham/all/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/conan/w/prod_cci_PR-13646/recipes/lzham/all/conanfile.py", line 8, in <module>
    from conan.tools.layout import vs_layout
ImportError: cannot import name 'vs_layout' from 'conan.tools.layout' (/opt/pyenv/versions/3.7.13/lib/python3.7/site-packages/conan/tools/layout/__init__.py)
```
Therefore, it seems the msbuild template should import `vs_layout` from `conan.tools.microsoft` instead.

**Comment by prince-chrismc** [comment]
Thank you so much for helping us fix the templates ❤️ we have been swamped and these little things make a world of difference and I just want to let you know it's appreciated

**Comment by partiallyderived** [comment]
happy to help :)
