### ISSUE TITLE
[service] Conan 2.0 is running beta 2 images

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#14093]
Currently there are no build beta4 images available

```sh
$ docker run -it conanio/gcc12-ubuntu16.04:2.0.0-pre
Unable to find image 'conanio/gcc12-ubuntu16.04:2.0.0-pre' locally
2.0.0-pre: Pulling from conanio/gcc12-ubuntu16.04
58690f9b18fc: Pull complete
b51569e7c507: Pull complete
...
8248de24211b: Pull complete
Digest: sha256:db3a75857d6edbbc95d638b7e5ee75f0b98c795277ace5fa38d904ab9eebaebe
Status: Downloaded newer image for conanio/gcc12-ubuntu16.04:2.0.0-pre
conan@82be81d87aaf:~$ conan --version
Conan version 2.0.0-beta3
conan@82be81d87aaf:~$
```

_Originally posted by @prince-chrismc in https://github.com/conan-io/conan-center-index/issues/14066#issuecomment-1305886821_

**Comment by uilianries** [comment]
Ops! Generating new images right now. Thank you for reporting!

**Comment by Croydon** [comment]
Those should also be switched to use the images based on Ubuntu 18.04

**Comment by uilianries** [comment]
@Croydon Yes, but it requires another task, because it will need Jenkins labels and ansible scripts. We have it listed to be done, but there are more tasks listed first related to the CI.

**Comment by danimtb** [comment]
this was fixed some time ago and images are now tagged with the beta number instead of using -pre
