### ISSUE TITLE
[package] <Catch2>/<3.1.0>: The global target name is the same as the target name in Catch2

### ISSUE THREAD

**Issue by GlebchanskyGit** [conan-io/conan-center-index#14121]
### Description

The problem is that the name of Global Target is the same as the name of targets in Catch2, so when you link Catch2::Catch2 it hooks Catch2::Catch2WithMain, because Global Target contains all the components of Catch2, you need to make global target have a different name, for example just with a small letter.

```cmake
########## GLOBAL TARGET ####################################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    if(NOT TARGET Catch2::Catch2)
        add_library(Catch2::Catch2 INTERFACE IMPORTED)
    endif()
    set_property(TARGET Catch2::Catch2 APPEND PROPERTY
                 INTERFACE_LINK_LIBRARIES "${Catch2_COMPONENTS}")
endif()
````

### Package and Environment Details

- Package Name/Version: catch2/3.1.0
- Operating System+version: Ubuntu 22.04
- Compiler+version: GCC 11.2
- Conan version: 1.53.0
- Python version: Python 3.10.6

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
compiler.cppstd=20
[options]
[conf]
[build_requires]
[env]
CC=gcc
CXX=g++

### Steps to reproduce

conan install catch2/3.1.0@ -g cmake_find_package -if . -pr default

### Logs

No logs

**Comment by SpaceIm** [comment]
It's not possible with the legacy cmake_find_package generator, it's a known limitation. You should use CMakeDeps generator instead.

**Comment by SpaceIm** [comment]
please try https://github.com/conan-io/conan-center-index/pull/14126
