### ISSUE TITLE
[package] gtest/1.10.0: Fails to build with gcc4.8

### ISSUE THREAD

**Issue by Stateford** [conan-io/conan-center-index#14143]
### Description

_Please don't forget to update the issue title._

When trying to build gtest with gcc4.8 it now breaks.

This change 2 months ago looks like the culprit
https://github.com/conan-io/conan-center-index/blob/master/recipes/gtest/all/conanfile.py#L48

This was changed on this line and it broke our pipelines on centos 7. We need to use the default compiler for our builds.

### Package and Environment Details

* Package Name/Version: **gtest/1.10.0**
* Operating System+version: **Centos7**
* Compiler+version: **GCC 4.8**
* Docker image: **private**
* Conan version: **conan 1.52.0**
* Python version: **Python 3.6.8**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=4.8
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter foobar/0.1.0@ -pr:b=default -pr:h=default

### Logs

<details><summary>Click to expand log</summary>

```
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Debug;-s;compiler=gcc;-s;compiler.version=4.8;-s;compiler.libcxx=libstdc++
-- Conan: checking conan executable
-- Conan: Found program /usr/local/bin/conan
-- Conan: Version found Conan version 1.52.0
-- Conan executing: /usr/local/bin/conan install . -s build_type=Debug -s compiler=gcc -s compiler.version=4.8 -s compiler.libcxx=libstdc++ -g=cmake_find_package_multi -g=cmake --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=4.8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    gtest/1.10.0 from 'conancenter' - Cache
Packages
    gtest/1.10.0:INVALID - Invalid

Installing (downloading, building) binaries...
ERROR: There are invalid packages (packages that cannot exist for this configuration):
gtest/1.10.0: Invalid ID: gtest/1.10.0 requires gcc 5. The current compiler is gcc 4.8.
CMake Error at out/conan.cmake:540 (message):
  Conan install failed='6'
Call Stack (most recent call first):
  out/conan.cmake:882 (old_conan_cmake_install)
  CMakeLists.txt:52 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/home/dapostal/git/bwsdk/out/CMakeFiles/CMakeOutput.log".
```

</details>

**Comment by SpaceIm** [comment]
Well actually gtest 1.10.0 has been removed in https://github.com/conan-io/conan-center-index/pull/13049 then restored improperly in https://github.com/conan-io/conan-center-index/pull/13833

**Comment by Stateford** [comment]
@SpaceIm I've tried newer versions of gtest and they have the same issue.

Is there a reason to remove older versions like this? It breaks known working configurations for developers. Conan has been very volatile in this regard.

**Comment by SpaceIm** [comment]
> Is there a reason to remove older versions like this? It breaks known working configurations for developers. Conan has been very volatile in this regard.

Question for @prince-chrismc and @uilianries 

IMHO, we should avoid as much as possible to drop versions in PR doing migrations of recipes to conan v2, to at least provide one RREV of each lib version with a valid conan v2 recipe.

**Comment by uilianries** [comment]
GTest 1.10.0 removing simplified a lot, but you are not the first which complained about. So we reverted.


@Stateford About GCC 4.8, it's an older versions which we don't run in CI, the oldest here is GCC 5, so we can't validate for older versions. CentOS users also open issues complaining about incompatibility sometimes. Anyway, you are free to open a PR providing a portability patch or fix.

**Comment by Stateford** [comment]
@SpaceIm Thank you for resolving this quickly. It's working for us now.

**Comment by prince-chrismc** [comment]
> IMHO, we should avoid as much as possible to drop versions in PR doing migrations of recipes to conan v2, to at least provide one RREV of each lib version with a valid conan v2 recipe.

I think we are generally on the same page -- considering it took 2 PR to put 1.10.0 back in I think it was a good call to drop it but yeah the most ideal world we wouldnt.

In #14377 I touched those docs so if anything is missing we can add it in.
