### ISSUE TITLE
[question] boost: how to specify multiple macros in `extra_b2_flags`

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [conan-io/conan-center-index#1415]
I tried (with a space between `define=X`):
`boost:extra_b2_flags="define=BOOST_BEAST_USE_STD_STRING_VIEW define=BOOST_ASIO_DISABLE_CONCEPTS"`
But this is not working as expected. What is the correct way?

**Comment by SSE4** [comment]
could you clarify what exactly doesn't work as expected? what's the resulting b2 command line?

**Comment by WPMGPRoSToTeMa** [comment]
Sorry. This is what I'm getting with the option above:
`boost/1.72.0: WARN: C:\Users\XXXXXX\.conan\data\b2\4.2.0\_\_\package\456f15897172eef340fcbac8a70811f2beb26a93\bin\b2.exe target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system --user-config=C:\.conan\79f2bb\1\boost_1_72_0\tools\build\user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 runtime-link=shared threading=multi link=static variant=debug --without-python toolset=msvc cxxflags=/std:c++17 pch=on  "define=BOOST_BEAST_USE_STD_STRING_VIEW define=BOOST_ASIO_DISABLE_CONCEPTS" install --prefix=C:\.conan\42ada6\1 -j6 --abbreviate-paths -d2 --debug-configuration --build-dir="C:\.conan\60d4fb\1"`

I also tried to add `boost:system_no_deprecated=True` option to see what is generated:
`boost/1.72.0: WARN: C:\Users\XXXXXX\.conan\data\b2\4.2.0\_\_\package\456f15897172eef340fcbac8a70811f2beb26a93\bin\b2.exe target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system --user-config=C:\.conan\79f2bb\1\boost_1_72_0\tools\build\user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 runtime-link=shared threading=multi link=static variant=debug --without-python toolset=msvc cxxflags=/std:c++17 define=BOOST_SYSTEM_NO_DEPRECATED=1 pch=on  "define=BOOST_BEAST_USE_STD_STRING_VIEW define=BOOST_ASIO_DISABLE_CONCEPTS" install --prefix=C:\.conan\2a2f9f\1 -j6 --abbreviate-paths -d2 --debug-configuration --build-dir="C:\.conan\a2408c\1"`

As you can see defines from `extra_b2_flags` are enclosed with quotes just like a single parameter. This is causing `-DBOOST_BEAST_USE_STD_STRING_VIEW define=BOOST_ASIO_DISABLE_CONCEPTS` to be generated instead of `-DBOOST_BEAST_USE_STD_STRING_VIEW -DBOOST_ASIO_DISABLE_CONCEPTS`.

**Comment by dskachan** [comment]
is there any solutions for that? 
thanks

**Comment by uilianries** [comment]
@dskachan check #2251
