### ISSUE TITLE
[package] <libiconv>/<1.17.0>: Change b41e73279691b581abc969bfd333d9f44294706d broke cross-compile

### ISSUE THREAD

**Issue by eugene1967** [conan-io/conan-center-index#14196]
### Description

Change b41e73279691b581abc969bfd333d9f44294706d has totally broken cross-compile on MacOS (and presumably Windows too). Eg. one is unable to compile libiconv as x86_64 on MacOS any more - any arch conan flags are simply ignored...

### Package and Environment Details

* Package Name/Version: **libiconv/1.17.0**
* Operating System+version: **MacOS Monterey**
* Compiler+version: **Xcode**
* Docker image: **N/A**
* Conan version: **conan 1.54.0**
* Python version: **Python 3.9.6**

### Conan profile

For Intel CPU:
----------------------------
[settings]
    arch=x86_64
    build_type=Release
    compiler=apple-clang
    compiler.version=13
    os=Macos
    os.version=10.9

[requires]

[options]
    fPIC=True
    shared=False

[full_settings]
    arch=x86_64
    build_type=Release
    compiler=apple-clang
    compiler.version=13
    os=Macos
    os.version=10.9

[full_requires]

[full_options]
    fPIC=True
    shared=False

[recipe_hash]
    477c88c579f61385e1f9751f3822ff29

[env]

For M1 CPU:
----------------------------
[settings]
    arch=armv8
    build_type=Release
    compiler=apple-clang
    compiler.version=13
    os=Macos
    os.version=10.9

[requires]

[options]
    fPIC=True
    shared=False

[full_settings]
    arch=armv8
    build_type=Release
    compiler=apple-clang
    compiler.version=13
    os=Macos
    os.version=10.9

[full_requires]

[full_options]
    fPIC=True
    shared=False

[recipe_hash]
    477c88c579f61385e1f9751f3822ff29

[env]

### Steps to reproduce

On MacOS with M1 CPU:

conan create libiconv libiconv/1.17.0@ -s compiler.cppstd=11 -tf None -s os.version=10.9 -s arch=x86_64 -s build_type=Release -s compiler.libcxx=libc++
conan create libiconv libiconv/1.17.0@ -s compiler.cppstd=11 -tf None -s os.version=10.9 -s arch=armv8 -s build_type=Release -s compiler.libcxx=libc++

observe both libiconv.a created are built for arm architecture..

### Logs

No logs

**Comment by SpaceIm** [comment]
Do you cross-build with 2 profiles?

**Comment by eugene1967** [comment]
Which two profiles?
I extract latest source from conan main recipe repo (this one) and run a script that effectively runs two of the above commands and then lipo then into one binary.

**Comment by SpaceIm** [comment]
Cross-build must be done with 2 profiles.

So assuming your have a `default` profile targeting macos M1, cross-build to x86_64 could be done like this:

```
conan create . libiconv/1.17.0@ -pr:b default -s arch=x86_64
```

**Comment by eugene1967** [comment]
conan is passing arch down to the libiconv project just fine and I posted above two conaninfo.txt from both builds. It is the actual conanfile.py recipe that is broken as it never passes arch to the Autotools so it is always using default platform..

**Comment by SpaceIm** [comment]
No, you don't understand. Just add `-pr:b default` to your conan create command and post full log if it still fails.

**Comment by eugene1967** [comment]
Thanks for your help. It worked! I never used profile flag and bizarre thing that I only have one profile default yet it somehow build for armv8 and for x86_64 but without -pr:b switch it built both as armv8...
Conan docs dont offer much help as to why?
Closing this ticket

**Comment by SpaceIm** [comment]
It's something I've mentioned many times to conan maintainers but conan v1 documentation is still showing legacy way to cross-build, and I agree that cross-build documentation is super confusing.

**Comment by eugene1967** [comment]
I found this [page](https://docs.conan.io/en/2.0/tutorial/consuming_packages/cross_building_with_conan.html) but it is still very confusing as they do say build will use two profiles but it is not actually building cross platform. One still need to run it twice with different arch argument and then lipo it manually..
