### ISSUE TITLE
[request] poco/1.12.4

### ISSUE THREAD

**Issue by Siarh199** [conan-io/conan-center-index#14215]
###Package Details

- Package Name/Version: poco/1.12.4
- Changelog: [https://raw.githubusercontent.com/pocoproject/poco/poco-1.12.4-release/CHANGELOG](https://raw.githubusercontent.com/pocoproject/poco/poco-1.12.4-release/CHANGELOG)

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by Nekto89** [comment]
Can be closed? #13963

**Comment by Siarh199** [comment]
Yes :+1:
