### ISSUE TITLE
[package] libtool/2.4.6: ERROR: Loop detected: 'lzma_sdk/9.20' requires 'msys2/20190524'

### ISSUE THREAD

**Issue by wodphoenix** [conan-io/conan-center-index#1422]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libtool/2.4.6**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 15**
  * Conan version: **conan 1.24.0**
  * Python version: **Python 3.7.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
>conan install . --build=missing -if "./build_x86" -s compiler="Visual Studio" -s arch="x86" -s build_type=Release -s compiler.version=15 -s arch_build="x86" -s os="Windows"

**Comment by sinall** [comment]
Have the same error when I'm trying to install tesseract/4.1.1.

**Comment by SpaceIm** [comment]
Yes, there is a loop in build requirements between `lzma_sdk`, `msys2` and `7zip`.

`msys2` build requires `7zip`
`7zip` build requires `lzma_sdk`
`lzma_sdk` build requires `msys2`

@uilianries @madebr I see that you have respectively added build requires to `7zip` and `lzma_sdk`. How to break this loop?

**Comment by madebr** [comment]
It looks like for `lzma_sdk` on Windows MSVC, msys2 is not required.

**Comment by guban** [comment]
I stumbled upon this loop for `arch=x86` builds but not for `arch=x86_64`. Setting `arch_build=x86_64`  seems to work around the problem.

**Comment by rockdreamer** [comment]
As a workaround, I built lzma_sdk with CONAN_BASH_PATH set in the environment, then built the rest.
