### ISSUE TITLE
[package] harfbuzz/5.3.1: ERROR: Dependency 'gobject-2.0' is required but not found.

### ISSUE THREAD

**Issue by rbrich** [conan-io/conan-center-index#14258]
### Description

Since recent update (https://github.com/conan-io/conan-center-index/pull/13942), my Windows build stopped working, because there is no gobject installed in the system, and the harfbuzz package started requiring it via meson, but not via Conan.

```
Run-time dependency gobject-2.0 found: NO (tried pkgconfig and cmake)
Not looking for a fallback subproject for the dependency gobject-2.0 because:
Use of fallback dependencies is disabled.

..\src\meson.build:103:0: ERROR: Dependency 'gobject-2.0' is required but not found.
```

It worked fine before, because gobject is disabled by default (see https://harfbuzz.github.io/building.html) and it's not needed for anything, while using Harfbuzz just as text shaping library.

### Package and Environment Details

* Package Name/Version: **harfbuzz/5.3.1**
* Operating System+version: **windows-2019** (Github Actions)
* Compiler+version: **VS 16**
* Conan version: **conan 1.54.0**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=20
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

### Steps to reproduce

```
conan install -r conancenter harfbuzz/5.3.1@ -pr:b=default -pr:h=default -o harfbuzz:with_glib=False -o freetype:with_brotli=False -o freetype:with_bzip2=False --build=missing
```

Reproducable also on Mac and probably Linux when libgobject-dev is not installed in the system.

### Logs

<details><summary>Click to expand log</summary>

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.20
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
harfbuzz/5.3.1: ERROR: Package '2a20d9c6a2ebe985fac22e461f32731dd56de1cc' build failed
harfbuzz/5.3.1: WARN: Build folder C:\.conan\601a44\1\build-release
The Meson build system
Version: 0.63.3
Source dir: C:\.conan\601a44\1\src
Build dir: C:\.conan\601a44\1\build-release
Build type: native build
Project name: harfbuzz
Project version: 5.3.1
C compiler for the host machine: cl (msvc 19.29.30146 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64")
C linker for the host machine: link link 14.29.30146.0
C++ compiler for the host machine: cl (msvc 19.29.30146 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64")
C++ linker for the host machine: link link 14.29.30146.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments /utf-8: YES 
Compiler for C++ supports link arguments -Bsymbolic-functions: NO 
Compiler for C++ supports arguments -fno-exceptions: NO 
Compiler for C++ supports arguments -fno-rtti: NO 
Compiler for C++ supports arguments -fno-threadsafe-statics: NO 
Compiler for C++ supports arguments -fvisibility-inlines-hidden: NO 
Compiler for C++ supports arguments -Wa,-mbig-obj: NO 
Library m found: NO
Found pkg-config: C:/Users/runneradmin/.conan/data/pkgconf/1.9.3/_/_/package/0a420ff5c47119e668867cdb51baff0eca1fdb68/bin/pkgconf.exe (1.9.3)
Run-time dependency freetype2 found: YES 2.12.1
Dependency glib-2.0 skipped: feature glib disabled
Found CMake: C:\Program Files\CMake\bin\cmake.EXE (3.24.2)
Run-time dependency gobject-2.0 found: NO (tried pkgconfig and cmake)
Not looking for a fallback subproject for the dependency gobject-2.0 because:
Use of fallback dependencies is disabled.

..\src\meson.build:103:0: ERROR: Dependency 'gobject-2.0' is required but not found.

A full log can be found at C:\.conan\601a44\1\build-release\meson-logs\meson-log.txt
harfbuzz/5.3.1: 
ERROR: harfbuzz/5.3.1: Error in build() method, line 150
	meson.configure()
	ConanException: Error 1 while executing meson setup --native-file "C:\.conan\601a44\1\build-release\conan\conan_meson_native.ini" "C:\.conan\601a44\1\build-release" "C:\.conan\601a44\1\src" -Dprefix="C:\.conan\7098ef\1"
Error: Process completed with exit code 1.
```

</details>

**Comment by ericLemanissier** [comment]
gobject is a component of glib, so it is already in the conan dependency graph. This looks like the same issue as https://github.com/conan-io/conan-center-index/issues/14176, it's probably related to https://github.com/conan-io/conan-center-index/issues/14125 and https://github.com/conan-io/conan/issues/12375
Can you check if "some" .pc files have been properly generated in harfbuzz's build folder ?

**Comment by rbrich** [comment]
Ok, let me reformulate the bug:
harfbuzz doesn't build with `harfbuzz:with_glib=False`

In other words, harfbuzz has option `with_glib`, which can be disabled, but the gobject dependency is hardcoded, it does not respect the option.

**Comment by ericLemanissier** [comment]
ok, so forget my last message 🙂 
Can you try with https://github.com/conan-io/conan-center-index/pull/14261 please ?

**Comment by rbrich** [comment]
Yes, this will work. But you have a linter error in there.

And I'm not sure gobject is really needed for anything. The [documentation](https://harfbuzz.github.io/integration.html#integration-glib) says:
> HarfBuzz uses it to build its Python bindings

But the Python bindings are not packaged, right? So maybe just disable it completely?
I think it was disabled before https://github.com/conan-io/conan-center-index/pull/13942 - there were these lines:
```
cmake.definitions["HB_HAVE_GOBJECT"] = False
cmake.definitions["HB_HAVE_INTROSPECTION"] = False
```
