### ISSUE TITLE
[conan.io/center] nit pick: title of tab starts always with a capital

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#1432]
e.g.
* libmodbus -> Libmodbus
* spdlog -> Spdlog

probably the tab should be the same as the library

**Comment by madebr** [comment]
What do you mean by *tab*?
The only capitalized `Libmodbus` I could find is the name of the conan class.
Names of class are capitalized because of the [PEP-8](https://www.python.org/dev/peps/pep-0008/#class-names) convention

**Comment by Croydon** [comment]
https://conan.io/center/libmodbus/3.1.6/?user=_&channel=_

@gocarlos Probably meant the website's `<title>`?

**Comment by gocarlos** [comment]
@Croydon as others have already noted, we cannot copy paste links from CCI to github comments, as those are not rendered correctly -> probably another issue with CCI

**Comment by jgsogo** [comment]
Looks like this is no longer an issue... or maybe I don't understand which was the problem. I cannot tell when it was fixed.

**Comment by gocarlos** [comment]
true, fixed
