### ISSUE TITLE
[package] opencv/4.5.5: opencv with cmake_paths

### ISSUE THREAD

**Issue by Jihadist** [conan-io/conan-center-index#14345]
### Description

_Please don't forget to update the issue title._

QtCreator provides integration with conan https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/src/share/3rdparty/package-manager/auto-setup.cmake#n87 that uses generator cmake_paths. But opencv couldn't be found with this generator (or I don't know how to)

```
opencv:with_ffmpeg=False
opencv:dnn=False
opencv:with_quirc=False
opencv:with_ade=False
opencv:with_jpeg2000=False
opencv:with_tiff=False
opencv:with_openexr=False
opencv:with_webp=False
opencv:with_jpeg=False
```

### Package and Environment Details

* Package Name/Version: **opencv/4.5.5**
* Operating System+version: **Windows 10**
* Compiler+version: **msvc 16**
* Conan version: **conan  1.54.0**
* Python version: **Python 3.10**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter opencv/4.5.5@ -pr:b=default -pr:h=default -g cmake_paths 

find_package(OpenCV REQUIRED)
I also tried opencv and OPENCV 

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by SpaceIm** [comment]
conan-center recipes do not package CMake config files, add CMakeDeps generator.

**Comment by Jihadist** [comment]
> conan-center recipes do not package CMake config files, add CMakeDeps generator.

Ok, should I use only CMakeDeps with cci recipes? 
CMakeDeps targets sometimes differ from the cmake_find_package targets and official imported by Find*.cmake. So I am not sure which generator is better for transparent integration.
