### ISSUE TITLE
[package] opencv/4.5.5: different targets with cmake generators

### ISSUE THREAD

**Issue by Jihadist** [conan-io/conan-center-index#14356]
### Description

_Please don't forget to update the issue title._

CmakeDeps generator output differs from cmake_find_package generator output
CmakeDeps targets:
```
-- Conan: Component target declared 'opencv_core'
-- Conan: Component target declared 'opencv::opencv_core_alias'
-- Conan: Component target declared 'opencv_flann'
-- Conan: Component target declared 'opencv::opencv_flann_alias'
-- Conan: Component target declared 'opencv_imgproc'
-- Conan: Component target declared 'opencv::opencv_imgproc_alias'
-- Conan: Component target declared 'opencv_ml'
-- Conan: Component target declared 'opencv::opencv_ml_alias'
-- Conan: Component target declared 'opencv_photo'
-- Conan: Component target declared 'opencv::opencv_photo_alias'
-- Conan: Component target declared 'opencv_features2d'
-- Conan: Component target declared 'opencv::opencv_features2d_alias'
-- Conan: Component target declared 'opencv_imgcodecs'
-- Conan: Component target declared 'opencv::opencv_imgcodecs_alias'
-- Conan: Component target declared 'opencv_videoio'
-- Conan: Component target declared 'opencv::opencv_videoio_alias'
-- Conan: Component target declared 'opencv_calib3d'
-- Conan: Component target declared 'opencv::opencv_calib3d_alias'
-- Conan: Component target declared 'opencv_highgui'
-- Conan: Component target declared 'opencv::opencv_highgui_alias'
-- Conan: Component target declared 'opencv_stitching'
-- Conan: Component target declared 'opencv::opencv_stitching_alias'
-- Conan: Component target declared 'opencv_video'
-- Conan: Component target declared 'opencv::opencv_video_alias'
-- Conan: Target declared 'opencv::opencv'
```
cmake_find_package
```
opencv::opencv_core
opencv::opencv_imgproc
opencv::opencv_flann
opencv::opencv_features2d
opencv::opencv_calib3d
opencv::opencv_video
opencv::video
opencv::opencv_stitching
opencv::stitching
opencv::opencv_imgcodecs
opencv::opencv_videoio
opencv::opencv_highgui
opencv::highgui
opencv::calib3d
opencv::videoio
opencv::imgcodecs
opencv::features2d
opencv::opencv_photo
opencv::photo
opencv::opencv_ml
opencv::ml
opencv::imgproc
opencv::flann
opencv::core
opencv::opencv
```
i.e. CmakeDeps creates targets ```opencv_core``` and ```opencv::opencv_core_alias``` while find_package creates ```opencv::core``` and ```opencv::opencv_core```. Both targets are different. So you need to change cmakelists if you change generator.

### Package and Environment Details

* Package Name/Version: **opencv/4.5.5**
* Operating System+version: **Windows 10**
* Compiler+version: **msvc 16**
* Conan version: **conan 1.54.0**
* Python version: **Python 3.10**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter opencv/4.5.5@ -pr:b=default -pr:h=default

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by SpaceIm** [comment]
cmake_find_package generator provides non-namespaced targets as well, it's just that cmake_find_package can't prevent to also create namespaced targets by design.

**Comment by Jihadist** [comment]
@SpaceIm anyway namespaced targets differ

**Comment by SpaceIm** [comment]
Ignore namespaced targets, they are workaround for cmake_find_package, nobody should use them.
