### ISSUE TITLE
[question] fPIC policy requirement for recipes

### ISSUE THREAD

**Issue by feltech** [conan-io/conan-center-index#14472]
Hello, we're looking to submit a recipe for [OpenAssetIO](https://github.com/OpenAssetIO/OpenAssetIO) asap.  However there is an open question regarding the `fPIC` option. 

Our project (hence recipe) provides several libraries. One of these libraries is a Python extension module (so is always `shared`). 

The Python extension module can either statically or dynamically link to the core library.  If statically linking, then PIC must of course be enabled on the core static library.

So, until now, we have more-or-less hardcoded PIC to be always-on (i.e. `CMAKE_POSITION_INDEPENDENT_CODE` is ignored).

But the ConanCenter recipe template, docs, FAQ and hook all seem to really want `fPIC` to be toggle-able.

How should we proceed? Is PIC-less output really a hard requirement? 

We could do some work to allow PIC-less static libraries and wrangle CMake so the Python extension module can still be built, but that's a lot of work we'd rather avoid if there's no good reason.

**Comment by SpaceIm** [comment]
fPIC option is not a hard requirement of conan center recipes. Hooks of c3i display a warning when there is a shared option without fPIC option, but that's all.

**Comment by feltech** [comment]
I'll close this as answered. Thanks @SpaceIm !
