### ISSUE TITLE
[package] qt/6.4.1: does not build with pcre2 > 10.37

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#14482]
### Description

The qt recipe includes this note:
```self.requires("pcre2/10.37") # needs to be < 10.38 or qt fails to detect visual studio static library```

Note, I'm using this recipe PR to test, as I imagine it'll be merged soon (but I don't want to delay the merge):
https://github.com/conan-io/conan-center-index/pull/13867

This should no longer be a problem with the newer QTs,
https://bugreports.qt.io/browse/QTBUG-104942?jql=text%20~%20%22pcre2%22
Quote: `There will be no more 6.3 releases. 6.4 already has 10.40. Giuseppe, can you check if those issues affect 10.40?`
and: `Those issues are fixed in 10.40, and Qt 6.3.1 ships with 10.40.`

So I wonder why I cannot build on Windows still?

### Package and Environment Details

* Package Name/Version: **qt/6.4.1**
* Operating System+version: **Windows 10**
* Compiler+version: **VS 17**
* Conan version: **conan 1.54.0**
* Python version: **Python 3.10.4**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=20
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows

[options]
qt:openssl=False
qt:qtmultimedia=True
qt:qtsvg=True
qt:qttools=True
qt:shared=True
qt:with_libjpeg=libjpeg-turbo
qt:with_mysql=False
qt:with_odbc=False
qt:with_openal=False
qt:with_pq=False
qt:with_zstd=True
[build_requires]
[env]
[conf]
tools.build:jobs=4
tools.cmake.cmaketoolchain:generator=Ninja

### Steps to reproduce

Building as a dep as part of the larger chain, but it should fail with a plain conan-install.
Have not tested that due to time constraints, main goal with this PR is to flag the issue.

### Logs

<details><summary>Click to expand log</summary>

```
Configuring submodule 'qtbase'
CMake Error at qtbase/cmake/QtBuildInformation.cmake:490 (message):
  Feature "system_pcre2": Forcing to "ON" breaks its condition:

      WrapSystemPCRE2_FOUND

  Condition values dump:

      WrapSystemPCRE2_FOUND = "FALSE"

Call Stack (most recent call first):
  qtbase/cmake/QtFeature.cmake:281 (qt_configure_add_report_error)
  qtbase/cmake/QtFeature.cmake:403 (qt_feature_check_and_save_internal_value)
  qtbase/cmake/QtFeature.cmake:155 (qt_evaluate_feature)
  qtbase/cmake/QtFeature.cmake:349 (qt_evaluate_config_expression)
  qtbase/cmake/QtFeature.cmake:606 (qt_evaluate_feature)
  qtbase/cmake/QtFeature.cmake:575 (qt_feature_module_end)
  qtbase/src/CMakeLists.txt:7 (qt_feature_evaluate_features)
```

</details>

**Comment by ericLemanissier** [comment]
so, qt does not try do detect the proper cmake target for pcre, cf https://github.com/qt/qtbase/blob/dev/cmake/FindWrapSystemPCRE2.cmake#L12, so cmake discovery always fails, regardless of pcre version. Then it tries [find_library](https://github.com/qt/qtbase/blob/dev/cmake/FindWrapSystemPCRE2.cmake#L34-L39) with fails because [the name of the library is incorrect when pcre is static and pcre > 10.38](https://github.com/conan-io/conan-center-index/blob/master/recipes/pcre2/all/conanfile.py#L204-L205)
I'll submit a change to qt, and integrate the patch in the recipe
