### ISSUE TITLE
[package] qt/6.4.1: qwebengine requires dbus on linux

### ISSUE THREAD

**Issue by EricAtORS** [conan-io/conan-center-index#14603]
### Description

When building qt 6.4.1 on linux with qwebengine, qwebengine requires dbus.
An extra validation is needed that qt is built with the `with_dbus` option enabled when compiling for linux.

I'm not sure how to handle the cross compilation case, so I did not open a PR.

### Package and Environment Details

* Operating System+version: **Alma linux 8.6**
* Compiler+version: **GCC 10**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
[conf]
tools.system.package_manager:mode=install
tools.cmake.cmaketoolchain:generator=Ninja

### Steps to reproduce

conan install -r conancenter qt/6.4.1@ -pr:b=default -pr:h=default -o shared=True -o qtwebengine=True -o qtwebchannel=True -o qtwebsockets=True

### Logs

<details><summary>Click to expand log</summary>

```
Configuring submodule 'qtwebchannel'
Configuring submodule 'qtwebengine'
-- Checking 'ulimit -n'
 -- Open files limit 1048576
-- Support check for QtWebEngine failed: Build requires dbus.
Configuring submodule 'qtwebview'
```

</details>

**Comment by ericLemanissier** [comment]
Don't hesitate to make a pull request. Cross compiling qtwebengine is not supported anyway
