### ISSUE TITLE
[package] grpc/1.48.0: Could not find gRPCConfig.cmake

### ISSUE THREAD

**Issue by fireinice** [conan-io/conan-center-index#14627]
### Description

`
cmake_minimum_required (VERSION 3.8)

project ("prj")

  include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
  conan_basic_setup()

  find_package(Protobuf REQUIRED)
  find_package(gRPC REQUIRED)
`

I can find gRPCConfig.cmake on location 
`
.conan/data/grpc/1.48.0/_/_/build/871e63f3f3123dd7bc0b9945601a118cdc32aad9/build_subfolder/source_subfolder/gRPCConfig.cmake
`

### Package and Environment Details

* Operating System+version: **Linux Debian 11**
* Conan version: **conan 1.55.0**
* Python version: **Python 3.9.2**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce
`
conan install .

cmake .
`
 
### Logs

<details><summary>Click to expand log</summary>

```
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /home/zigler/work/tvmp
-- Conan: Compiler GCC>=5, checking major version 12
-- Conan: Checking correct version: 12
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gRPC", but
  CMake did not find one.

  Could not find a package configuration file provided by "gRPC" with any of
  the following names:

    gRPCConfig.cmake
    grpc-config.cmake

  Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
  "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/zigler/work/tvmp/CMakeFiles/CMakeOutput.log".
```

</details>

**Comment by SpaceIm** [comment]
conan-center recipes don't package CMake config files, you have to generate them with CMakeDeps.

**Comment by fireinice** [comment]
> conan-center recipes don't package CMake config files, you have to generate them with CMakeDeps.

thanks for kinldly reply, so I have to write a conanfile.py when I want to use grpc in my project,  even the project will not produce a conan package?

**Comment by SpaceIm** [comment]
No, you just have to add `-g CMakeDeps` option when you call `conan install`. It will generate config files in current dir by default, then if you don't use `CMakeToolchain` generator as well (and pass the generated toolchain file to CMAKE_TOOLCHAIN_FILE CMake variable when you call cmake configuration on project), you're on your own to make these config files discoverable, but I advice to use `CMakeToolchain` (and not legacy `cmake` generator).

**Comment by SpaceIm** [comment]
From my understanding of your workflow, you should have something like this in your project root folder:

CMakeLists

```cmake
cmake_minimum_required(VERSION 3.8)
project (prj)

find_package(Protobuf REQUIRED)
find_package(gRPC REQUIRED)

...
```

conanfile.txt

```ini
[requires]
protobuf/x.y.z
grpc/x.y.z

[generators]
CMakeToolchain
CMakeDeps
```

Then to install dependencies from conan, and call CMake configuration & build:

```shell
mkdir build && cd build
conan install .. -b missing
cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release
```

**Comment by fireinice** [comment]
That's very helpful. I seek the docs and cannot find the detail explanations. Maybe the docs need be updated.

**Comment by fireinice** [comment]
and how could I link with the $CONAN_LIBS? It looks like the new generators do not `produce conanbuildinfo.cmake` , no more  `conan_target_link_libraries` and  `${CONAN_LIBS}` etc. I found these sugars were quite delicious.
