### ISSUE TITLE
[service] open62541 Windows test pipeline fail without reporting the failure

### ISSUE THREAD

**Issue by saukijan** [conan-io/conan-center-index#14656]
I am not certain that this is a service issue or something wrong with the package itself, but in [Package/open62541: bump to v1.3.4](https://github.com/conan-io/conan-center-index/pull/14537#top) all windows builds fail without reporting an issue that I can fix. 

Looking into [test_report](https://c3i.jfrog.io/c3i/misc/logs/pr/14537/12-configs/windows-visual_studio/open62541/1.1.6//1a91ec283cf2e411b2e9a729853507a3e7c84d4d-test.txt) it looks like that the toolchain path is in linux format, instead of windows, thus causing the build to fail. 

```bash
----Running------
> cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE="C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/open62541/all/test_package/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\J\w\prod\BuildSingleReference\conan-center-index\recipes\open62541\all\test_package\."
-----------------
-- Using Conan toolchain: C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/open62541/all/test_package/build/generators/conan_toolchain.cmake
-- Configuring incomplete, errors occurred!
CMake Error at build/generators/conan_toolchain.cmake:81 (set):
  Syntax error in cmake code at

    C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/open62541/all/test_package/build/generators/conan_toolchain.cmake:81

  when parsing string

    C:\J\w\prod\BuildSingleReference\.conan\data\ua-nodeset\padim-1.02-2021-07-21\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\res

  Invalid character escape '\J'.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:2 (project)


open62541/1.1.6 (test package): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
open62541/1.1.6 (test package): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
open62541/1.1.6 (test package): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
ERROR: open62541/1.1.6 (test package): Error in build() method, line 29
	cmake.configure()
	ConanException: Error 1 while executing cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE="C:/J/w/prod/BuildSingleReference/conan-center-index/recipes/open62541/all/test_package/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\J\w\prod\BuildSingleReference\conan-center-index\recipes\open62541\all\test_package\."
```

However, none of the information above is provided to the PR as a part of conan-center-bot report. The only problem that is reported is the Cmake warning for unused variables. 

What is even more puzzling, is that the test package is run and returns the expected result.

**Comment by saukijan** [comment]
Still, the same behavior in the latest commit.

Windows [test](https://c3i.jfrog.io/c3i/misc/logs/pr/14537/16-configs/windows-visual_studio/open62541/1.2.2//0f12fcb918a20c67dd406afb577edf6d2c54e0ad-test.txt) cases fail due to package path being set in Linux format instead of Windows in `conan_toolchain.cmake`

**Comment by ErikTempelaarVO** [comment]
I'm having trouble with this package as well (for mingw32), please let me know if this has a similar cause.

`-- Build files have been written to: C:/.conan/325c0d/1/build/Release
open62541/1.3.1: CMake command: cmake --build "C:\.conan\325c0d\1\build\Release" -- -j12
[  2%] Generating src_generated/open62541/types_generated.c, src_generated/open62541/types_generated.h, src_generated/open62541/types_generated_handling.h
[  2%] Generating src_generated/open62541/transport_generated.c, src_generated/open62541/transport_generated.h, src_generated/open62541/transport_generated_handling.h
[  4%] Generating src_generated/open62541/nodeids.h
[  6%] Generating src_generated/open62541/statuscodes.h, src_generated/open62541/statuscodes.c
Traceback (most recent call last):
  File "C:\.conan\325c0d\1\source\tools\generate_datatypes.py", line 95, in <module>
    parser.create_types()
  File "C:\.conan\325c0d\1\source\tools\nodeset_compiler\type_parser.py", line 384, in create_types
    self.parse_types()
  File "C:\.conan\325c0d\1\source\tools\nodeset_compiler\type_parser.py", line 411, in parse_types
    self.parseTypeDefinitions(outname_import, file_import)
  File "C:\.conan\325c0d\1\source\tools\nodeset_compiler\type_parser.py", line 304, in parseTypeDefinitions
    xmlDoc = etree.iterparse(
  File "C:\msys64\mingw32\lib\python3.10\xml\etree\ElementTree.py", line 1272, in iterparse
    next(it)
  File "C:\msys64\mingw32\lib\python3.10\xml\etree\ElementTree.py", line 1249, in iterator
    source = open(source, "rb")
OSError: [Errno 22] Invalid argument: 'C;C:\\msys64\\.conan\\325c0d\\1\\source\\deps\\ua-nodeset\\Schema\\Opc.Ua.Types.bsd'
make[2]: *** [CMakeFiles/open62541-generator-transport.dir/build.make:78: src_generated/open62541/transport_generated.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:281: CMakeFiles/open62541-generator-transport.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Built target open62541-generator-statuscode
[  6%] Built target open62541-generator-types
make: *** [Makefile:156: all] Error 2
open62541/1.3.1:
open62541/1.3.1: ERROR: Package '20830eb56f1ecdef1a5c780a55afcec67b17c1fd' build failed
open62541/1.3.1: WARN: Build folder C:\.conan\325c0d\1\build\Release
ERROR: open62541/1.3.1: Error in build() method, line 381
        cmake.build()
        ConanException: Error 2 while executing cmake --build "C:\.conan\325c0d\1\build\Release" -- -j12`

**Comment by saukijan** [comment]
Hey @ErikTempelaarVO, thanks for the info! 

The base path to conan package resources is incorrect, hence the error. 

```bash
'C;C:\\msys64\\.conan\\325c0d\\1\\source\\deps\\ua-nodeset\\Schema\\Opc.Ua.Types.bsd'
```

should be 
```bash
'C:\\msys64\\.conan\\325c0d\\1\\source\\deps\\ua-nodeset\\Schema\\Opc.Ua.Types.bsd'
```

This might be caused by an incorrect path variable in `conan_toolchain.cmake` or it could be something a bit simpler, like incorrect conan profile settings, a bad conan install command, or an error in your conanfile.

Could you post what conan version you are using (you can check it by running `conan --version` in cmd/powershell) as well as the profile you are using (to see what conan profiles you have, type in cmd/powershell `conan profile list` and to see your profile's content type in `conan profile show ${PROFILE_NAME}`) 

Also, how are you generating the package? Are you using `conan install open62541/1.3.1` explicitly or are you using a config file like `conanfile.txt` or `conanfile.py`? (If you are using a config file, could you post it as well as the command/process you use to build the package?)

**Comment by ErikTempelaarVO** [comment]
Currently still on the previous conan version.
`Conan version 1.56.0`

I attempt to install it via the following command:
`conan install --build=missing open62541/1.3.1@`

My profile cross-compiles for Windows, from x64 to x86, using msys2/ming32.
```
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=7
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=MSYS Makefiles
[conf]
tools.cmake.cmaketoolchain:generator=MSYS Makefiles
tools.build:compiler_executables={'cpp': 'C:/msys64/mingw32/bin/g++.exe', 'c': 'C:/msys64/mingw32/bin/gcc.exe'}

Installing package: open62541/1.3.1
Requirements
    open62541/1.3.1 from 'conancenter' - Cache
Packages
    open62541/1.3.1:1a2ad87d2cbd66bf6a29d169da971bdcebd6bcb5 - Build

Cross-build from 'Windows:x86_64' to 'Windows:x86'
Installing (downloading, building) binaries...
open62541/1.3.1: Copying sources to build folder
open62541/1.3.1: Building your package in C:\.conan\f58f64\1
open62541/1.3.1: Generator txt created conanbuildinfo.txt
open62541/1.3.1: Calling generate()
open62541/1.3.1: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
open62541/1.3.1: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
open62541/1.3.1: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "MSYS Makefiles" -DCMAKE_TOOLCHAIN_FILE=C:\.conan\f58f64\1\build\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0077=NEW -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
open62541/1.3.1: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
open62541/1.3.1: Aggregating env generators
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
open62541/1.3.1: Calling build()
open62541/1.3.1: Apply patch (portability): Use Cmake find_package(*) to resolve external dependencies
open62541/1.3.1: CMake command: cmake -G "MSYS Makefiles" -DCMAKE_TOOLCHAIN_FILE="C:/.conan/f58f64/1/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/.conan/470ff7/1" -DCMAKE_POLICY_DEFAULT_CMP0077="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\.conan\f58f64\1\source"
-- Using Conan toolchain: C:/.conan/f58f64/1/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw32/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python3: C:/msys64/mingw32/bin/python3.10.exe (found version "3.10.9") found components: Interpreter
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.22.0.windows.1")
-- open62541 Version: v1.3.1
-- The selected architecture is: win32
-- Test CC flag -std=c99

... CMake tests redacted for brevity

-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
-- Could NOT find LATEX (missing: LATEX_COMPILER)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/.conan/f58f64/1/build/Release
open62541/1.3.1: CMake command: cmake --build "C:\.conan\f58f64\1\build\Release" -- -j12
[  2%] Generating src_generated/open62541/types_generated.c, src_generated/open62541/types_generated.h, src_generated/open62541/types_generated_handling.h
[  2%] Generating src_generated/open62541/transport_generated.c, src_generated/open62541/transport_generated.h, src_generated/open62541/transport_generated_handling.h
[  4%] Generating src_generated/open62541/nodeids.h
[  6%] Generating src_generated/open62541/statuscodes.h, src_generated/open62541/statuscodes.c
```

Appreciate the reply, let me know if you need anything else.

**Comment by saukijan** [comment]
hey @ErikTempelaarVO, your conan profile looks correct, so I do not know where the `;` char is coming from. 

Could you also post the generated `conanbuildinfo.txt` file? It should be in `C:\.conan\f58f64\1\build` directory

`conanbuildinfo.txt` will tell me the base paths used by conan to generate the package, so if there is something confidential in there, you can replace it with `[MASKED]` , all that I am looking for is if some paths start or end with `C;`

**Comment by ErikTempelaarVO** [comment]
Here's the full content on the file
```
"C:\.conan\f58f64\1\build\Release\conanbuildinfo.txt"
```

There wasn't anything to redact, the file contains very little.

``` 
[includedirs]


[libdirs]


[bindirs]


[resdirs]


[builddirs]


[libs]


[system_libs]


[defines]


[cppflags]


[cxxflags]


[cflags]


[sharedlinkflags]


[exelinkflags]


[sysroot]


[frameworks]


[frameworkdirs]



```

I searched the entire folder for that particular string, but nothing stands out:

```
Search "C;" (17 hits in 8 files of 191 searched)
  C:\.conan\f58f64\1\build\Release\CMakeFiles\3.25.0\CMakeCCompiler.cmake (5 hits)
	Line 38: set(CMAKE_C_SOURCE_FILE_EXTENSIONS c;m)
	Line 39: set(CMAKE_C_IGNORE_EXTENSIONS h;H;o;O;obj;OBJ;def;DEF;rc;RC)
	Line 70: set(CMAKE_C_IMPLICIT_LINK_LIBRARIES "mingw32;gcc;moldname;mingwex;kernel32;pthread;advapi32;shell32;user32;kernel32;mingw32;gcc;moldname;mingwex;kernel32")
	Line 71: set(CMAKE_C_IMPLICIT_LINK_DIRECTORIES "C:/msys64/mingw32/lib/gcc/i686-w64-mingw32/12.2.0;C:/msys64/mingw32/lib/gcc;C:/msys64/mingw32/i686-w64-mingw32/lib;C:/msys64/mingw32/lib")
  C:\.conan\f58f64\1\build\Release\CMakeFiles\3.25.0\CMakeRCCompiler.cmake (1 hit)
	Line 4: set(CMAKE_RC_SOURCE_FILE_EXTENSIONS rc;RC)
  C:\.conan\f58f64\1\build\Release\CMakeFiles\3.25.0\CompilerIdC\CMakeCCompilerId.c (1 hit)
	Line 839: int main(argc, argv) int argc; char *argv[];
  C:\.conan\f58f64\1\build\Release\CMakeFiles\CMakeOutput.log (3 hits)
	Line 301:   implicit libs: [mingw32;gcc;moldname;mingwex;kernel32;pthread;advapi32;shell32;user32;kernel32;mingw32;gcc;moldname;mingwex;kernel32]
	Line 303:   implicit dirs: [C:/msys64/mingw32/lib/gcc/i686-w64-mingw32/12.2.0;C:/msys64/mingw32/lib/gcc;C:/msys64/mingw32/i686-w64-mingw32/lib;C:/msys64/mingw32/lib]
  C:\.conan\f58f64\1\build\Release\doc_src\open62541.png (2 hits)
	Line  40: ºÄK‡cÞ*õ·åúXÞº˜–µ9y•Ê¢ŒF:gº<ÿ4äöªÏ›Üñlé‚^œÃ‹*ÿBø”Kk¬ôzx>7Ù§)Fûô&èÕ ØåÓÛSíÆÑ‰@fÝžQö ö×E}Ò£¸Š:ôlñ]¥ÌÍ±õ»«ºÜ¤~×UÀ.úÞ|ˆÁÔÇ¼uFýíHúXU•¿Ðµ¾ !Ãc;ë,úQÞZœæÔ“ª›¬ó¸ƒcÀõg
	Line  73: Ïñ·éÅþ|ìÁß°ŒqÞ¡˜å5Ê[üì™æ-æù@ûÄ>6ÙíC;Ú S•sÑm®ÙÑzpQ	8ÃØÅ9>ÓÀ¶Ë[ülÖ¦ßFö}ÜÜÿv\¡\à
  C:\.conan\f58f64\1\build\Release\doc_src\ua-wireshark-pubsub.png (2 hits)
	Line 167: O™¸“ç´ß6£y9ñ§µ7èó-3´ßæKq®7DéôB&‰¿ÇY5t ñ°Iÿ”@¡Z‚Ýv“øu±¯".½®Wiˆý\Ä?O]¼:cóXž/Õ$…o
	Line 475: ÂcÁßfjuAãÝ¡îÕ?H¹ÿX¼ÅÌdE`E°ï:
  C:\.conan\f58f64\1\build\Release\open62541Targets.cmake (1 hit)
	Line 54:   INTERFACE_INCLUDE_DIRECTORIES "C:/.conan/f58f64/1/source/arch;C:/.conan/f58f64/1/source/src;C:/.conan/f58f64/1/source/arch/win32;C:/.conan/f58f64/1/source/include;C:/.conan/f58f64/1/source/plugins/include;C:/.conan/f58f64/1/source/deps;C:/.conan/f58f64/1/source/src/pubsub;C:/.conan/f58f64/1/build/Release/src_generated"
  C:\.conan\f58f64\1\build\Release\src_generated\open62541\types_generated.h (2 hits)
	Line  292:     UA_Double c;
	Line 1983:     UA_Boolean symmetric;
```

**Comment by saukijan** [comment]
Hey @ErikTempelaarVO, I just noticed that all of the paths used by conan are in `C:/.conan/*`, but the path to nodeID declarations is `C;C:\\msys64\\.conan\\*`,  which is really similar to the problem I documented here. Luckily the [issue was found](https://github.com/conan-io/conan-center-index/pull/14537#discussion_r1073673245) and will be solved with the release of open62541 v1.3.4

Sadly, I can not say when it will be released, since it is not up to me to release it. 

However, in the meantime, you can use conan v1 generators like `cmake`, `cmake_paths` or `cmake_find_package` when building the package.  These generators do not have this problem, since the package paths are set in a different way than the v2 toolchain paths.

**Comment by ErikTempelaarVO** [comment]
Thank you for looking into this, good to know that a fix is pending. I'm looking forward to the updated v1.3.4!

Could you elaborate on howto select another (conan v1) generator as a work around?
I assumed it would be something like this:
```
conan install -g cmake open62541/1.3.1@ --build=missing
``` 

Or this setting in global.conf
```
tools.cmake.cmaketoolchain:generator=cmake
```

But that results in the same error.

**Comment by saukijan** [comment]
Hey @ErikTempelaarVO, generally, I use a config file, at the root of the project I need. That way anyone using the project would install the same dependencies.

You could create a test project directory with the **conanfile.txt** which contains

```text
[requires]
open62541/1.3.1

[generators]
cmake
cmake_paths 
cmake_find_package 
```

and run `conan install .`  in the config file directory, however, the way you use v1 generators should work too. 

I am starting to suspect, that this might be a separate issue. 

Could you check your conan data directory? CMake generator should have created `conanbuildinfo.cmake` and `cmake_install.cmake` files in open62541 package directory. These files will tell me what path variables conan sets internally for the cmake command. Just add these files as attachments, so I can open them in an IDE a bit more easily.

**Comment by ErikTempelaarVO** [comment]
[cmake_install.cmake.txt](https://github.com/conan-io/conan-center-index/files/10469178/cmake_install.cmake.txt)
[conanbuildinfo.cmake.txt](https://github.com/conan-io/conan-center-index/files/10469179/conanbuildinfo.cmake.txt)
[build.make.txt](https://github.com/conan-io/conan-center-index/files/10469218/build.make.txt)

It seems to create a weird mix of paths for executables and arguments.
`/C/msys64/mingw32/bin/python3.10.exe C:/.conan/522304/1/source_subfolder/tools/generate_datatypes.py`

But the same error occurs when I remove python 3.10 from the mingw32 path and the Windows Python 3.8 executes the generate_datatypes.

**Comment by saukijan** [comment]
Hey @ErikTempelaarVO, sorry for the long silence, I was ill over the weekend and the first half of the week. 

Your `cmake_install.cmake` and `conanbuildinfo.cmake` files are as they should be, so it does not seem that this is caused by conan at all. 

Your right, `build.make` is quite interesting and something is definitely wonky with the MSYS generator, all of the local path variables are set in linux format. Great example, `CMAKE_COMMAND = "/C/Program Files/CMake/bin/cmake.exe"`. 

I don't have much experience with compiling on windows, but I don't thing calling `/C/Program Files/CMake/bin/cmake.exe --version` in powershell or cmd would work at all.  (For me at least, I get `/C/Program : The name "/C/Program" was not recognized as the name of a cmdlet, function, script file, or executable program.` error in powershell)

Just to eliminate conan as a problem entirely, could you try compiling open62541 nativelly with Visual Studio Compiler? Conan Center Index usually compiles with 2017 and 2019 compilers as stated [here](https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md#windows). 

To do so, you will need to install VSCompiler, and then create a new profile with [`conan profile new vsc --detect`](https://docs.conan.io/en/latest/reference/profiles.html), it should auto-detect VSCompiler and configure the profile accordingly, but double check it if it is correct by running `conan profile show vsc`, it should return something like this: 

```bash
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[tool_requires]
[env]
```

If something is incorrect, you can fix it by editing `C:\.conan\profiles\vsc` file. 

Let me know how it goes!

**Comment by ErikTempelaarVO** [comment]
No need to apologize, hope you're feeling better now.

You are right that the generated paths do not work. Your error is more related to the space in the path, but even with quotes it's not valid. Windows can deal with both styles for the separator, but /C/ is not is valid replacement for C:/

```
C:\Users\RXQ>conan profile new vsc --detect
Found Visual Studio 16
Found gcc 12.2
Profile created with detected settings: C:\Users\RXQ\.conan\profiles\vsc
``` 

```
Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
[conf]
tools.cmake.cmaketoolchain:generator=cmake
``` 

Selecting that as both the host- and build profile does the trick, the build completes without issues.
```
C:\open62541_conan>conan install . -pr:h=vsc -pr:b=vsc --build
```

```
c:\msys64\mingw32>conan search open62541/1.3.1@
Existing packages for recipe open62541/1.3.1:

    Package_ID: ccad181bb4bdab371fc098660c2dd4b788c8b0ea
        [options]
            compiled_nodeset_descriptions: True
            cpp_compatible: False
            data_access: True
            discovery: semaphore
            discovery_semaphore: True
            dynamic_nodes: True
            encryption: False
            hardening: True
            historize: False
            imutable_nodes: False
            json_support: False
            logging_level: Info
            methods: True
            multithreading: None
            namespace_zero: FULL
            pub_sub: False
            pub_sub_encryption: False
            query: False
            readable_statuscodes: True
            shared: False
            single_header: False
            subscription: True
            typenames: True
            web_socket: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 16
            os: Windows
        Outdated from recipe: False
```

I'm not sure what conclusion to draw from this. It seems that it's not a problem in the recipe?
And it's not related to this issue either? It's probably best if I open another then.

**Comment by saukijan** [comment]
@ErikTempelaarVO , you are correct, in this case, it is not a problem with the recipe. 

It might be that open62541 does not support your cross-compiler or how it is set up. 

You could try compiling [open62541/1.3.1](https://github.com/open62541/open62541/tree/v1.3.1) from source, to check if it compiles at all.  

If it compiles, then something might be messed up on the conan side, in which case you could open an issue on [conan](https://github.com/conan-io/conan). 

If it fails to compile, then it's either a problem with your cross-compiler or open62541. 

In that case, I would first suggest to double check your cross-compiler by trying to compile a basic hello world program. 

If that works, then it's worth opening an issue at [open62541](https://github.com/open62541/open62541/issues). 

If it does not, I would look into doing a clean install of your cross-compiler, moving to the compilation platform, or changing the compiler altogether.

Hope this helps!

**Comment by ErikTempelaarVO** [comment]
It seems that my environment was crippled due to mixing Windows/msys2 tooling
i.e. cmake & conan under windows, that's apparently a [bad ](https://www.msys2.org/docs/filesystem-paths/#windows-unix-path-conversion) idea.
Now I installed both python3/conan/mingw-w64-i686-cmake in msys2 the recipe builds successfully.

@saukijan Thanks again for your help, I wouldn't have been able to resolve this without it.

**Comment by saukijan** [comment]
Thanks for the update @ErikTempelaarVO. I am glad you were able to solve the issue! I'll close the issue now since the original problem is also resolved in the new recipe.
