### ISSUE TITLE
[question] Why CMakeToolchain.variables doesn't affect my CMakeLists.txt?

### ISSUE THREAD

**Issue by igormironchik** [conan-io/conan-center-index#14659]
Let's say I have `conanfile.py` with the following methods:

```python
def layout(self):
        cmake_layout(self)

def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["BUILD_EXAMPLES"] = False
        tc.variables["BUILD_TESTS"] = False
        if Version(self.version) >= "0.2.9":
            tc.variables["USE_INTERNAL_ARGS_PARSER"] = False
        tc.generate()
        deps = CMakeDeps(self)
        deps.generate()

def build(self):
        cmake = CMake(self)
        cmake.configure(build_script_folder=self.source_folder)
        cmake.build()
```

I see in the toolchain file set variables, like

```cmake
# Variables
set(BUILD_EXAMPLES OFF CACHE BOOL "Variable BUILD_EXAMPLES conan-toolchain defined")
set(BUILD_TESTS OFF CACHE BOOL "Variable BUILD_TESTS conan-toolchain defined")
set(USE_INTERNAL_ARGS_PARSER OFF CACHE BOOL "Variable USE_INTERNAL_ARGS_PARSER conan-toolchain defined")
```

Ok, in my `CMakeLists.txt` I have:

```cmake
option( BUILD_EXAMPLES "Build examples? Default ON." ON )
option( BUILD_TESTS "Build tests? Default ON." ON )
```

Great. But `cmake.configure(...)` fails because `BUILD_EXAMPLES` and `BUILD_TESTS` are `ON`.

What did I do wrong? How to set my options to build examples and tests to `OFF`?

**Comment by Nekto89** [comment]
Have you tried using "cache_variables" instead?
https://github.com/conan-io/conan-center-index/blob/master/docs/v2_migration.md#cmaketoolchain

**Comment by igormironchik** [comment]
`cache_variables` solves the problem. Thanks.

**Comment by jcar87** [comment]
Hi @igormironchik  - indeed the recommendation would be to use `cache_variables` - these are set up in such a way that will provided when cmake is first invoked. If they are toolchain variables, they will only be set when the toolchain file is loaded during the first call to `project()` - in this instance, is there a chance the calls to `option()` are done _before_ the first call to `project()` in the top-level `CMakeLists.txt`?

**Comment by igormironchik** [comment]
@jcar87 

> is there a chance the calls to `option()` are done _before_ the first call to `project()` in the top-level `CMakeLists.txt`?

Sure, it's so. Look.

```cmake
cmake_minimum_required( VERSION 3.19 )

set( CFGFILE_VERSION "0.2.11" )

option( BUILD_EXAMPLES "Build examples? Default ON." ON )
option( BUILD_TESTS "Build tests? Default ON." ON )

if( NOT CMAKE_BUILD_TYPE )
	set( CMAKE_BUILD_TYPE "Release"
		CACHE STRING "Choose the type of build."
		FORCE)
endif( NOT CMAKE_BUILD_TYPE )

SET( CMAKE_CXX_STANDARD 14 )

SET( CMAKE_CXX_STANDARD_REQUIRED ON )

project( cfgfile )
```
