### ISSUE TITLE
[service] Update CMake to 3.19

### ISSUE THREAD

**Issue by igormironchik** [conan-io/conan-center-index#14665]
I need minimum required version of CMake 3.19 to build my libraries. Due to Conan v2 migration process some things were replaced with new functionality, many was simplified, and I can use my own native `CMakeListst.txt` in Conan packaging, where I need CMake 3.19. Could you update CMake in your CI to 3.19? Thanks.

As example look [here](https://github.com/conan-io/conan-center-index/pull/14662).

**Comment by Croydon** [comment]
Add CMake as a tool_require if you need some very recent version

**Comment by igormironchik** [comment]
Thanks. It works.
