### ISSUE TITLE
[request] hana/1.7.0

### ISSUE THREAD

**Issue by dongkeren** [conan-io/conan-center-index#14709]
### Package Details
  * Package Name/Version: **hana/1.7.0**
  * Website: **https://boostorg.github.io/hana/index.html**
  * Source code: **https://github.com/boostorg/hana**

Please put hana/1.7.0 back. This is a header-only lib that does not rely on any other dependencies, I don't see any goodness to simply remove it and replace with the tremendous boost lib. And such an action is just so not nice to users, unless you feel happy to see how many projects build that you can break.

**Comment by prince-chrismc** [comment]
It was migrated to v2 and update in #14690 so it is still available but we will not be actively maintaining it. It will always be available. https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/sources_and_patches.md#removing-old-versions

> Please, note that even if those versions are removed from this repository, the packages will always be accessible in ConanCenter remote associated to the recipe revision used to build them.

I'd love to hear from others but out sentiment should be captured [here](https://github.com/conan-io/conan-center-index/pull/14674/files#diff-9a0d263d27f331b7f71ed0a2f4e39864d4e1ba6df602130a0094d84b52109612R420)

**Comment by frkami123** [comment]
I would love this package to be maintained again, same reasons @dongkeren has mentioned. I couldn't get the available versions ("invalid packages"), look like a bug but since the package is deprecated i can't report bugs.

**Comment by frkami123** [comment]
They changed release schedule and version number, [haha/boost-1.81.0](https://github.com/boostorg/hana/releases/tag/boost-1.81.0) can standalone and basically the same thing as the 1.7.0. boost-1.81.0 just newer. [request] "hana/boost-1.81.0" moving forward would be nice.

**Comment by prince-chrismc** [comment]
If hana was distributed as a standalone package it would be less error prone https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#can-we-add-package-which-are-parts-of-bigger-projects-like-boost for consumers. This is what asio project does for reference.

Per hana's docs at this time
![image](https://user-images.githubusercontent.com/16867443/219495956-8649e813-5127-4f84-854c-711322746e07.png)

We will refrain from maintaining it as it's no longer the desire of the author. 

Feel free to fork this recipe and have your on copy, you can host your own conan server with a private recipe that suites your needs :) it's not required to be public in ConanCenter for you to take full advantage of Conan.

**Comment by perseoGI** [comment]
Hi there! I'm closing this issue as this library is now part of Boost as @prince-chrismc said a long ago.
We have no plans to bring this recipe back to CCI.

Happy coding 🐸
