### ISSUE TITLE
[package] openssl/1.1.1d on Windows: strawberry perl error

### ISSUE THREAD

**Issue by floriansimon1** [conan-io/conan-center-index#1476]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openssl/1.1.1d**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 15 (Visual Studio 2017)**
  * Conan version: **conan 1.24.0**
  * Python version: **Python 3.7.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86
build_type=RelWithDebInfo
compiler=Visual Studio
compiler.runtime=MT
compiler.version=15
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
`conan install --build=missing --profile:build "F:\conan\profiles\profile" --profile:host "F:\conan\profiles\profile" openssl/1.1.1d@_/_`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
openssl/1.1.1d: Copying sources to build folder
openssl/1.1.1d: Building your package in C:\Users\fsimon2\.conan\data\openssl\1.1.1d\_\_\build\33bc954080da4a576fa6b68c025ee043497105fd
openssl/1.1.1d: Generator txt created conanbuildinfo.txt
openssl/1.1.1d: Calling build()
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.19
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
openssl/1.1.1d:
openssl/1.1.1d: ERROR: Package '33bc954080da4a576fa6b68c025ee043497105fd' build failed
openssl/1.1.1d: WARN: Build folder C:\Users\fsimon2\.conan\data\openssl\1.1.1d\_\_\build\33bc954080da4a576fa6b68c025ee043497105fd
ERROR: openssl/1.1.1d: Error in build() method, line 596
        env_vars = {"PERL": self._perl}
while calling '_perl', line 534
        return os.path.join(self.deps_cpp_info["strawberryperl"].rootpath, "bin", "perl.exe")
        KeyError: 'strawberryperl'
```

</details>

**Comment by floriansimon1** [comment]
With the following patch:

```diff
diff --git a/recipes/openssl/1.x.x/conanfile.py b/recipes/openssl/1.x.x/conanfile.py
index c1361d1f..65f09301 100644
--- a/recipes/openssl/1.x.x/conanfile.py
+++ b/recipes/openssl/1.x.x/conanfile.py
@@ -100,7 +100,10 @@ class OpenSSLConan(ConanFile):
     def build_requirements(self):
         if tools.os_info.is_windows:
             if not self._win_bash:
+                print("ADD STRAW")
                 self.build_requires("strawberryperl/5.30.0.1")
+            else:
+                print("NOT ADD STRAW")
             if not self.options.no_asm and not tools.which("nasm"):
                 self.build_requires("nasm/2.14")
         if self._win_bash:
@@ -531,6 +534,7 @@ class OpenSSLConan(ConanFile):
     def _perl(self):
         if tools.os_info.is_windows and not self._win_bash:
             # enforce strawberry perl, otherwise wrong perl could be used (from Git bash, MSYS, etc.)
+            print(self.deps_cpp_info.deps)
             return os.path.join(self.deps_cpp_info["strawberryperl"].rootpath, "bin", "perl.exe")
         return "perl"
```

It shows "ADD STRAW", then `dict_keys([])` when I print `self.deps_cpp_info.deps`.

**Comment by memsharded** [comment]
Hi @floriansimon1 

Can you please try?:

```bash
$ conan install --build=openssl openssl/1.1.1d@ -s arch=x86 -s arch_build=x86_64
```

I guess your current platform is Windows 64 bits, so you need to provide ``-s arch_build=x86_64``  not ``arch_build=x86`` (there are no binaries for it in ConanCenter)

**Comment by floriansimon1** [comment]
I got the same error when my script was doing "cross building". I've been doing some troubleshooting, and I found out this could be related to this change: https://github.com/conan-io/conan/commit/33652d590a4eb32d0d29d8718c0c624010dae426#diff-763c60e9852172df23dc152b08051e53R496

Why did you add the `if` check here? To check for cross-building? Inconditionally setting `deps_cpp_info`  seems to fix the issue.

**Comment by floriansimon1** [comment]
To better answer your request:

**Comment by floriansimon1** [comment]
I am currently retrying the same thing without the `--profile:host` command line parameter.

**Comment by floriansimon1** [comment]
OK, so if you use `--profile:build` or `--profile:host`, then the code inside the `else` branch of the `else` branch mentioned in the previous comment is ran and `deps_cpp_info` is not set.

I suppose it is a bit weird that if I manually copy the profile file in ~/.conan/profiles/default, then run my command with `--profile` it works, but if I use the `--profile:build` and/or `--profile:host` parameters, it doesn't work. That sounds like a Conan bug, is it not?

**Comment by memsharded** [comment]
> EDIT: I just tried it, and it works. Is there a problem with the OpenSSL recipe, Conan or is it just PEBKAC?

Yes, I don't think that any of the ConanCenter recipes is ready to be processed with the new ``--profile:build`` and ``--profile:host``. If they work, it might be luck.

There is still ongoing work for this feature to be complete:
- https://github.com/conan-io/conan/pull/6769/files
- https://github.com/conan-io/conan/pull/6778/files

After that, we hopefully will be able to start improving recipes in ConanCenter to use this new paradigm. So if using the ConanCenter recipes, it is better to keep using the old approach at the moment, and something like ``$ conan install --build=openssl openssl/1.1.1d@ -s arch=x86 -s arch_build=x86_64``.

Not sure if I understood it correctly, but ``$ conan install --build=openssl openssl/1.1.1d@ -s arch=x86_64 -s arch_build=x86_64`` (changing to arch=x86_64) also works correctly here.

**Comment by floriansimon1** [comment]
Thanks!
