### ISSUE TITLE
[feature] Print the conan version number during conan-create and conan-install

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#14775]
### What is your suggestion?

When upgrading recipes, it is important to know what version of conan the CI machines have, so I know when I can use features from the new conan version.

eg, when I can change `from conans.tools import stdcpp_library` to a conan v2 import.

Perhaps it is displayed in a PR somewhere, but I'd like to be able to look at a build log and see the version so there can be no doubt what was used, eg:

https://c3i.jfrog.io/artifactory/misc/logs/pr/13799/41-linux-gcc/libvpx/1.10.0/21a66396f9ee4dc0210d632a784f63f7f3e1d95b-build.txt

Just put it as the first line!
It would also help when people paste logs in slack or whatever...

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by uilianries** [comment]
All configuration versions running in Conan Center CI is listed in https://github.com/conan-io/conan-center-index/blob/master/.c3i. Said that, the current Conan version running is listed in https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6 and the CI always obey that version.
