### ISSUE TITLE
[conan.io/center] Add a Date to All Versions and Revisions

### ISSUE THREAD

**Issue by coofercat** [conan-io/conan-center-index#14812]
### What is your problem/feature request?

Would it be possible to add dates to all package versions and recipe revisions?

Taking for example, a page such as this: https://conan.io/center/boost?version=1.79.0&revision=99be8543779dd15e9a8c24efcd99c1d4

The questions I specifically would like to answer are:
1) What date was boost/1.79 first created on conan center?
2) When was the recipe revision I have selected first created?
3) Is the revision I have selected really the most recent?

If you don't currently record when these things occurred, then by all means leave the date out for older entries, but in such a case, can we have dates for all new entries, at least, please?

**Comment by AbrilRBS** [comment]
Sorry that we did not answer back when proposed back them, but this has been a feature ever since Conan 2 launched! :)
