### ISSUE TITLE
[package] gsl/2.7: Could NOT find GSL

### ISSUE THREAD

**Issue by Jihadist** [conan-io/conan-center-index#14818]
### Description

I tried to install gsl with cmake_find_package_multi but something went wrong. I don't install only gsl, cmake can find other packages but not gsl

### Package and Environment Details

* Package Name/Version: **gsl/2.7**
* Operating System+version: **WIndows 10**
* Compiler+version: **MSVC 16**
* Conan version: **conan 1.54.0**
* Python version: **Python 3.7.4**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce

conan install gsl/2.7 -g cmake_find_package_multi

### Logs

<details><summary>Click to expand log</summary>

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    gsl/2.7 from 'conancenter' - Cache
Packages
    gsl/2.7:3fb49604f9c2f729b85ba3115852006824e72cab - Cache

Installing (downloading, building) binaries...
gsl/2.7: Already installed!

conanfile.txt: Generator cmake_find_package_multi created GSLConfigVersion.cmake
conanfile.txt: Generator cmake_find_package_multi created GSLTarget-release.cmake
conanfile.txt: Generator cmake_find_package_multi created GSLTargets.cmake
conanfile.txt: Generator cmake_find_package_multi created GSLConfig.cmake

conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo

Cmake configuration:

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GSL (missing: GSL_INCLUDE_DIR GSL_LIBRARY GSL_CBLAS_LIBRARY)
  (found version "")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindGSL.cmake:151 (find_package_handle_standard_args)
  CMakeLists.txt:41 (find_package)

</details>

**Comment by SpaceIm** [comment]
There is not enough information. I would say your issue is not related to conan-center-index, but a misusage of CMake.

- Find modules have precedence over config files by default
- CMake ships a FindGSL.cmake module file.

So the obvious solution is to either use `CMakeToolchain` to properly setup everything so that config files generated by conan have precedence, or rely on `cmake_find_package` instead of `cmake_find_package_multi`.

**Comment by Jihadist** [comment]
> 

You are right, I need to use cmake_find_package_multi with CMakeDeps and override MODULE_PATH and PREFIX_PATH to enable gsl properly
But looks like gsl doesn't work correctly out-of-the-box

**Comment by SpaceIm** [comment]
Consuming conan dependencies can't work out of the box with CMake since conan is not a system package manager, that's not new, libraries are not installed in system locations. CMakeToolchain is your friend.
