### ISSUE TITLE
[service] Lint errors are excessive when patch_description & patch_type are missing

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#14865]
### What is your problem/feature request?

Preventing to merge because these fields are missing (since https://github.com/conan-io/conan-center-index/pull/14015) is excessive since they don't change the core logic or build quality of the recipe, it's purely informative and optional in conan source code.

There are several recipes out there with tones of patches without these fields (hello Boost), and the next poor contributor who will open a PR against these recipes will have to understand all these patches to deduce proper description and patch type, even if PR is unrelated. It will just lead to poor descriptions because they may not have the background to understand these patches, or they may just give up due to frustration of having to fix something unrelated to their PR.
I think it's a lot of effort for little benefit (I prefer to see more libraries in CCI & robust builds rather than pretty patch descriptions).

/cc @prince-chrismc @danimtb @SSE4

**Comment by uilianries** [comment]
I added this issue to be discussed in the CCI meeting.

**Comment by RubenRBS** [comment]
Hi, thanks for bringing this to our attention. We've decided to relax the requirements as you suggested, and we'll be implementing a few changes shortly:
 - Clarify in the docs that those files would be good to have from the current "fields are required" wording.
 - Make the linter still show up in as an annotation, but make it be a notice/warning and not exit with a fail status

I hope that with both those options things get a little bit easier for maintainers, reviewers and contributors alike :)
