### ISSUE TITLE
[package] cryptopp/8.7.0: Compile fails on Visual Studio

### ISSUE THREAD

**Issue by ottoryynanen** [conan-io/conan-center-index#14868]
### Description

When including the cryptopp 8.7.0 to my project, the recipe pulls in cmake 3.24.0 and this causes an attempt to build cmake 3.24.0, which is unnecessary as my installation has CMake already installed and in use.

Problematic code: conan-center-index/recipes/cryptopp/all/conanfile.py:41
`self.tool_requires("cmake/3.24.0")`

Even if this dependency could not be removed, this version of CMake cannot be built with my version of Visual Studio, as reported here: ( https://gitlab.kitware.com/cmake/cmake/-/issues/24162 )
In general the requirement to build a new instance of CMake to the setup should be replaced with requirement that a local install of CMake with version 3.24.0 or newer is used for building the project.
If this is not possible, then the version should be changed to 3.25.0 where the compiler error has been fixed.

### Package and Environment Details

* Package Name/Version: **cryptopp/8.7.0**
* Operating System+version: **Windows 10 Enterprise 20H2**
* Compiler+version: **MSVC 19.34.31937.0**
* Docker image: **-**
* Conan version: **conan 1.55.0**
* Python version: **Python 3.9.9**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan_cmake_configure(
REQUIRES
    cryptopp/8.6.0
}

in CMakeLists.txt

### Logs

C:\.conan\data\cmake\3.24.0\_\_\build\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\source_subfolder\Source\cmGlobalVisualStudioGenerator.cxx(633,47): error C2280: "std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const wchar_t *)" : Es wurde versucht, auf eine gelÃ¶schte Funktion zu verweisen [C:\.conan\data\cmake\3.24.0\_\_\build\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\Source\CMakeLib.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\ostream(965,31): message : Siehe Deklaration von "std::operator <<" [C:\.conan\data\cmake\3.24.0\_\_\build\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\Source\CMakeLib.vcxproj]
C:\.conan\data\cmake\3.24.0\_\_\build\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\source_subfolder\Source\cmGlobalVisualStudioGenerator.cxx(633,47): error C2088: "<<": UngÃ¼ltig fÃ¼r class [C:\.conan\data\cmake\3.24.0\_\_\build\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\Source\CMakeLib.vcxproj]
cmake/3.24.0: 
cmake/3.24.0: WARN: Package binary is corrupted, removing: ca33edce272a279b24f87dc0d4cf5bbdcffbc187
cmake/3.24.0: WARN: Build folder is dirty, removing it: C:\.conan\data\cmake\3.24.0\_\_\build\ca33edce272a279b24f87dc0d4cf5bbdcffbc187
cmake/3.24.0: ERROR: Package 'ca33edce272a279b24f87dc0d4cf5bbdcffbc187' build failed
cmake/3.24.0: WARN: Build folder C:\.conan\data\cmake\3.24.0\_\_\build\ca33edce272a279b24f87dc0d4cf5bbdcffbc187
ERROR: cmake/3.24.0: Error in build() method, line 108
	cmake.build()
	ConanException: Error 1 while executing cmake --build C:\.conan\data\cmake\3.24.0\_\_\build\ca33edce272a279b24f87dc0d4cf5bbdcffbc187 -- /m:4 /verbosity:minimal
CMake Error at CMake/conan.cmake:392 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  CMakeLists.txt:112 (conan_cmake_install)
-- Configuring incomplete, errors occurred!
See also "C:/app/build/CMakeFiles/CMakeOutput.log".
See also "C:/app/build/CMakeFiles/CMakeError.log".

**Comment by SpaceIm** [comment]
There is this kind of pattern which can be useful in recipes requiring CMake > 3.15, sadly it's not widely used in CCI recipes. It allows to not bring cmake as a build requirement if a suitable version is already available on build machine: https://github.com/conan-io/conan-center-index/blob/9fca6f45cef2f85f6cea0018a335a92084bafb97/recipes/wavelet_buffer/all/conanfile.py#L83-L96

**Comment by RubenRBS** [comment]
Hi! You're right that this pattern is used in other recipes, but I just wanted to lay down our options here (As discussed with @jcar87):
 - Check for an existing `cmake` and only try to get a new one if it's not new enough as @SpaceIm suggests
 - Only force this requirement for Linux, as both Windows and macOS use valid `cmake` in CCI ([Doc here](https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md#linux))
 - Submit a backport patch to `cmake`, and use 3.18.3 in CCI
 - Find a magical better solution? We can always dream

If we had infinite time, I think a mix of 1) and 3) would be ideal, but I don't love how the cmake versions are checked though.
