### ISSUE TITLE
[package] qt/5.13.2: ConanException during qt build in libx11

### ISSUE THREAD

**Issue by Reavolt** [conan-io/conan-center-index#14863]
### Description

When I try to build QT, libx11 is also built, where I get a not very clear error related to ConanException

### Package and Environment Details

* Package Name/Version: **qt/5.13.2**
* Operating System+version: **Linux Сentos7 i686**
* Compiler+version: **GCC 9.4**
* Docker image: **i386/centos:7**
* Conan version: **conan 1.55.0**
* Python version: **Python 3.8.12** Compiled from source

### Conan profile

[settings]
os=Linux
os.distro=CentOS7
os_build=Linux
arch=x86
arch_build=x86
compiler=gcc
compiler.version=9.4
compiler.libcxx=libstdc++11
build_type=Release
[options]
caf:shared=False
boost:without_stacktrace = True
[build_requires]
[env]
CC=/usr/local/bin/i686-redhat-linux-gcc
CXX=/usr/local/bin/i686-redhat-linux-g++

### Steps to reproduce

conan create . qt/5.13.2 -pr linux_x86 --build missing

### Logs

<details><summary>Click to expand log</summary>
libx11/1.6.8@bincrafters/stable: WARN: Build folder is dirty, removing it: /root/.conan/data/libx11/1.6.8/bincrafters/stable/build/d563ae366f958b80e281fffef987bb13a158abdd
libx11/1.6.8@bincrafters/stable: Copying sources to build folder
libx11/1.6.8@bincrafters/stable: Building your package in /root/.conan/data/libx11/1.6.8/bincrafters/stable/build/d563ae366f958b80e281fffef987bb13a158abdd
libx11/1.6.8@bincrafters/stable: Generator pkg_config created xtrans.pc
libx11/1.6.8@bincrafters/stable: Generator pkg_config created xcb.pc
libx11/1.6.8@bincrafters/stable: Generator pkg_config created xcb-proto.pc
libx11/1.6.8@bincrafters/stable: Generator pkg_config created util-macros.pc
libx11/1.6.8@bincrafters/stable: Generator pkg_config created xau.pc
libx11/1.6.8@bincrafters/stable: Generator pkg_config created pthread-stubs.pc
libx11/1.6.8@bincrafters/stable: Generator pkg_config created xdmcp.pc
libx11/1.6.8@bincrafters/stable: Generator pkg_config created xorgproto.pc
libx11/1.6.8@bincrafters/stable: Generator pkg_config created xproto.pc
libx11/1.6.8@bincrafters/stable: Aggregating env generators
libx11/1.6.8@bincrafters/stable: Calling build()
libx11/1.6.8@bincrafters/stable: Calling:
 > ./configure '--disable-dependency-tracking' '--disable-shared' '--enable-static' '--prefix=/root/.conan/data/libx11/1.6.8/bincrafters/stable/package/d563ae366f958b80e281fffef987bb13a158abdd' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' --build=x86_64-linux-gnu --host=x86-linux-gnu
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86-unknown-linux-gnu
checking for x86-linux-gnu-gcc... /usr/local/bin/i686-redhat-linux-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/local/bin/i686-redhat-linux-gcc accepts -g... yes
checking for /usr/local/bin/i686-redhat-linux-gcc option to accept ISO C89... none needed
checking whether /usr/local/bin/i686-redhat-linux-gcc understands -c and -o together... yes
checking how to run the C preprocessor... /usr/local/bin/i686-redhat-linux-gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86-linux-gnu-strip... no
checking for strip... strip
configure: WARNING: using cross tools not prefixed with host triplet
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of /usr/local/bin/i686-redhat-linux-gcc... none
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by /usr/local/bin/i686-redhat-linux-gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... no
checking for x86-linux-gnu-dumpbin... no
checking for x86-linux-gnu-link... no
checking for dumpbin... no
checking for link... link -dump
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for x86-linux-gnu-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for x86-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86-linux-gnu-ar... no
checking for ar... ar
checking for archiver @FILE support... @
checking for x86-linux-gnu-strip... strip
checking for x86-linux-gnu-ranlib... no
checking for ranlib... ranlib
checking command to parse nm output from /usr/local/bin/i686-redhat-linux-gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for x86-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/local/bin/i686-redhat-linux-gcc supports -fno-rtti -fno-exceptions... no
checking for /usr/local/bin/i686-redhat-linux-gcc option to produce PIC... -fPIC -DPIC
checking if /usr/local/bin/i686-redhat-linux-gcc PIC flag -fPIC -DPIC works... yes
checking if /usr/local/bin/i686-redhat-linux-gcc static flag -static works... no
checking if /usr/local/bin/i686-redhat-linux-gcc supports -c -o file.o... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -c -o file.o... (cached) yes
checking whether the /usr/local/bin/i686-redhat-linux-gcc linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking for /usr/local/bin/i686-redhat-linux-gcc option to accept ISO C99... none needed
checking whether __clang__ is declared... no
checking whether __INTEL_COMPILER is declared... no
checking whether __SUNPRO_C is declared... no
checking for x86-linux-gnu-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=unknown-warning-option... no
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=unused-command-line-argument... no
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wall... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wpointer-arith... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wmissing-declarations... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wformat=2... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wstrict-prototypes... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wmissing-prototypes... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wnested-externs... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wbad-function-cast... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wold-style-definition... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wdeclaration-after-statement... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wunused... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wuninitialized... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wshadow... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wmissing-noreturn... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wmissing-format-attribute... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wredundant-decls... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Wlogical-op... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=implicit... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=nonnull... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=init-self... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=main... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=missing-braces... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=sequence-point... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=return-type... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=trigraphs... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=array-bounds... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=write-strings... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=address... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=int-to-pointer-cast... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=pointer-to-int-cast... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -pedantic... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror... yes
checking if /usr/local/bin/i686-redhat-linux-gcc supports -Werror=attributes... yes
checking whether make supports nested variables... (cached) yes
checking whether to build functional specifications... yes
checking for xmlto... no
configure: WARNING: xmlto not found - documentation targets will be skipped
checking for xsltproc... no
configure: WARNING: xsltproc not found - cannot transform XML documents
checking for X.Org SGML entities >= 1.10... no
checking for cpp... /usr/local/bin/cpp
checking if /usr/local/bin/cpp requires -undef... yes
checking if /usr/local/bin/cpp requires -traditional... yes
checking for perl... /usr/bin/perl
checking for x86-linux-gnu-pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc
checking for x86-linux-gnu-pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking if Xtrans should support UNIX socket connections... yes
checking if Xtrans should support TCP socket connections... yes
checking for library containing socket... none required
checking for library containing gethostbyname... none required
checking for getaddrinfo... yes
checking if IPv6 support should be built... yes
checking for struct sockaddr_in.sin_len... no
checking for socklen_t... yes
checking for struct msghdr.msg_control... yes
checking if Xtrans should support os-specific local connections... no
checking for strcasecmp... yes
checking for strlcpy... no
checking if run-time linking is supported... checking for library containing dlopen... -ldl
checking for dlfcn.h... (cached) yes
yes
checking if loadable i18n module support should be enabled... no
checking if loadable Xcursor library support should be enabled... yes
checking sys/filio.h usability... no
checking sys/filio.h presence... no
checking for sys/filio.h... no
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for strtol... yes
checking for seteuid... yes
checking for reallocarray... no
checking whether issetugid is declared... no
checking for issetugid... no
checking for getresuid... yes
checking for shmat... yes
checking for launchd... no
checking for getpwuid_r in -lc... yes
checking for pthread_self in -lc... yes
checking for poll... yes
checking keysym definitions...  /root/.conan/data/xproto/7.0.31/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/X11/keysymdef.h /root/.conan/data/xproto/7.0.31/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/X11/XF86keysym.h /root/.conan/data/xproto/7.0.31/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/X11/Sunkeysym.h /root/.conan/data/xproto/7.0.31/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/X11/DECkeysym.h /root/.conan/data/xproto/7.0.31/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/X11/HPkeysym.h
checking if XLOCALEDIR support should be enabled... yes
checking for BIGFONT... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... no
checking for nl_langinfo... yes
checking for X11... yes
checking whether malloc(0) returns NULL... configure: error: in `/root/.conan/data/libx11/1.6.8/bincrafters/stable/build/d563ae366f958b80e281fffef987bb13a158abdd/source_subfolder':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
libx11/1.6.8@bincrafters/stable: 
libx11/1.6.8@bincrafters/stable: ERROR: Package 'd563ae366f958b80e281fffef987bb13a158abdd' build failed
libx11/1.6.8@bincrafters/stable: WARN: Build folder /root/.conan/data/libx11/1.6.8/bincrafters/stable/build/d563ae366f958b80e281fffef987bb13a158abdd
ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/usr/local/lib/python3.8/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method
    conanfile.build()
  File "/root/.conan/data/libx11/1.6.8/bincrafters/stable/export/conanfile_base.py", line 64, in build
    autotools = self._configure_autotools()
  File "/root/.conan/data/libx11/1.6.8/bincrafters/stable/export/conanfile_base.py", line 51, in _configure_autotools
    self._autotools.configure(args=args, pkg_config_paths=self.build_folder)
  File "/usr/local/lib/python3.8/site-packages/conans/client/build/autotools_environment.py", line 205, in configure
    self._conanfile.run(command, win_bash=self._win_bash, subsystem=self.subsystem)
  File "/usr/local/lib/python3.8/site-packages/conans/model/conan_file.py", line 464, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 1 while executing ./configure '--disable-dependency-tracking' '--disable-shared' '--enable-static' '--prefix=/root/.conan/data/libx11/1.6.8/bincrafters/stable/package/d563ae366f958b80e281fffef987bb13a158abdd' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' --build=x86_64-linux-gnu --host=x86-linux-gnu
</details>

**Comment by ericLemanissier** [comment]
The packages you are using do not come from conan center, and have not been maintained for years. Please retry with one of the versions on https://conan.io/center/qt

**Comment by Reavolt** [comment]
I was able to fix the error by separating profiles into build and host for cross compilation

build
[settings]
os=Linux
os.distro=CentOS7
arch=x86_64
compiler=gcc
compiler.version=9.4
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

host
[settings]
os=Linux
os.distro=CentOS7
arch=x86
compiler=gcc
compiler.version=9.4
compiler.libcxx=libstdc++11
build_type=Release
[options]
caf:shared=False
boost:without_stacktrace = True
[build_requires]
[env]
CC=/usr/local/bin/i686-redhat-linux-gcc
CXX=/usr/local/bin/i686-redhat-linux-g++
