### ISSUE TITLE
[request] sqlcipher/4.5.3

### ISSUE THREAD

**Issue by shiena** [conan-io/conan-center-index#14917]
### Package Name/Version

sqlcipher/4.5.3

### Changelog

https://www.zetetic.net/blog/2022/12/19/sqlcipher-4.5.3-release/

### Context about the new update

I tried to update to 4.5.2 with https://github.com/conan-io/conan-center-index/pull/12084 , but it failed to migrate to conan v2 and was closed.
Please add this version.

**Comment by czoido** [comment]
Thanks for reporting, closing this as newer versions are already available.
