### ISSUE TITLE
[service] Consider that the conan-center-bot is minimizing its old PR comments 

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#1491]
The pull requests comments can grow pretty quickly.

The bot is supporting this tendency by posting a comment for every single push. In order to help getting an overview over pull requests, it might be helpful if the bot is minimizing its own old comments when posting the results of a new build.

**Comment by danimtb** [comment]
What do you mean by "minimizing"? Like deleting old comments?

**Comment by Croydon** [comment]
I meant hiding (which does not completely hide a comment, but actually minimizes it, so that it can be extended on a click)

**Comment by Croydon** [comment]
Like this one

**Comment by danimtb** [comment]
Nice! Sure, that would be a great addition

**Comment by Croydon** [comment]
Thanks for implementing! This should help to be more focused in pull requests
