### ISSUE TITLE
Compile Cantera from source

### ISSUE THREAD

**Issue by khaledcomb** [conan-io/conan-center-index#14950]
### What is your question?

Hello everyone,
I'm new user in python and I want to use cantera to convert from yaml file to chemkin file, I follow instruction in https://cantera.org/install/compiling-install.html#sec-compiling but when I use scons build command I got this error:

(base) PS C:\Users\DELL> scons build

scons: *** No SConstruct file found.
File "C:\Users\DELL\anaconda3\lib\site-packages\SCons\Script\Main.py", line 945, in _main
(base) PS C:\Users\DELL> cd cantera
(base) PS C:\Users\DELL\cantera> scons build
scons: Reading SConscript files ...
SCons 4.4.0 is using the following Python interpreter:
    C:\Users\DELL\anaconda3\python.exe (Python 3.9)
Compiling with MSVC version 14.3
Compiling with MSVC toolset 14.3 (default)
Compiling for architecture: amd64
Compiling using the following toolchain(s): ['default']
INFO: Compiling on 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel'
INFO: Building Cantera from git commit '2ce92eac2'
INFO: Configuration variables read from 'cantera.conf' and command line:

INFO: Adding conda include and library paths: C:\Users\DELL\anaconda3
Checking for C++ header file cmath... yes
Checking for C++ header file fmt/ostream.h... no
INFO: Using private installation of fmt library.
INFO: Found fmt version 6.2.1
Checking for YAML::Node().Mark()... no
INFO: Using private installation of yaml-cpp library.
Checking for C++ header file gtest/gtest.h... yes
Checking for C++ header file gmock/gmock.h... yes
INFO: Using system installation of Googletest
Checking for C++ header file eigen3/Eigen/Dense... no
Checking for C++ header file Eigen/Dense... no
INFO: Using private installation of Eigen.
INFO: Found Eigen version
Checking whether __GLIBCXX__ is declared... no
Checking whether _LIBCPP_VERSION is declared... no
Checking whether __clang__ is declared... no
Checking for C++ library iomp5... no
Checking for C++ library omp... no
Checking for C++ library gomp... no
ERROR: Boost could not be found. Install Boost headers or set 'boost_inc_dir' to point to the boost headers.

See 'config.log' for details.

I tried to download Boost headers  from https://www.boost.org/users/download/ and install it manually using the following step:
-Go to the directory C:\Program Files\boost_1_81_0\tools\build.
-Run bootstrap.bat and bootstrap.sh 
-Run b2 install --prefix=--prefix=PREFIX 
-Add PREFIX\bin to your PATH environment variable. 

I also got the error: 

(base) PS C:\Users\DELL\cantera> b2 install --prefix=cantera
b2 : Le terme «b2» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme
exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct
et réessayez.
Au caractère Ligne:1 : 1
+ b2 install --prefix=cantera
+ ~~
    + CategoryInfo          : ObjectNotFound: (b2:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I don't understand exactly what should I do if someone helps it would be very appreciated.
Best,

**Comment by NelDav** [comment]
I do not understand, why you ask this question at this repository, but have you already tried to state the `boost_inc_dir` option as suggested by the error message?
