### ISSUE TITLE
[package] msys2/20161025: x86 package missing

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#150]
A x86 package of `msys2/20161025` is missing.
See appveyor output: https://ci.appveyor.com/project/madebr/conan-cc65-installer/builds/27782963/job/lxvodkiitlog977m#L328

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **msys2/20161025**
  * Operating System+version: **Windows** (Appveyor)
  * Compiler+version: **gcc**
  * Conan version: **conan 1.18.5**
  * Python version: **Python 3.7.x**

### Steps to reproduce (Include if Applicable)
Use `msys2/20161025` as a build requirement with `arch_build=x86` on Windows

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
msys2/20161025: WARN: Can't find a 'msys2/20161025' package for the specified settings, options and dependencies:
- Settings: arch_build=x86, os_build=Windows
- Options: additional_packages=None, exclude_files=*/link.exe, packages=base-devel,binutils,gcc
- Dependencies: 
- Package ID: 02335dedca0a2cdcde89828f81194929ef12d610
```

</details>

**Comment by Croydon** [comment]
CCI does not build any x86 packages on purpose. You can see all supported configurations here: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Comment by madebr** [comment]
Thanks!
