### ISSUE TITLE
[package] opentelemetry-cpp/1.8 1: option to enable Logs support  with ENABLE_LOGS_PREVIEW

### ISSUE THREAD

**Issue by MrSparc** [conan-io/conan-center-index#15024]
### Description

This is not a bug actually but a request to improvement for the current recipe because this library support this setting. 

The Logs feature in opentelemetry-cpp 1.8.1 is still experimental but can be enabled via the define ENABLE_LOGS_PREVIEW that is handled by CMake  ` WITH_LOGS_PREVIEW`.
 I would like to be able set this via an recipe option. 
This will allow us to enable this support in our `conanfile.txt` like this:

```
[requires]
opentelemetry-cpp/1.8.1

[generators]
cmake

[options]
opentelemetry-cpp:with_logs_preview=True
```
This option is required in order to build the includes and libs that support ostream, OTLP HTTP and gRPC exporters for logs especification.

Here is my proposal of PR for the package maintainer: 
https://github.com/MrSparc/conan-center-index/commit/88c94d0400f4ef2210bceb5949f9ba7ad504b7fc

### Package and Environment Details

* Package Name/Version: **opentelemetry-cpp/1.8.1**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 11.3**
* Conan version: **conan 1.53.0**

### Conan profile

N/A

### Steps to reproduce

N/A.

### Logs

N/A.

**Comment by justinmcbride** [comment]
@MrSparc I took your changes and simply opened a PR with them (from your repo): #15198

**Comment by MrSparc** [comment]
@justinmcbride I signed now the CLA. 
But I think that is not enough to be merged since it requires LGTM from 3 reviewers.
