### ISSUE TITLE
Include files path in rapidxml/1.13 package (should they be under include/rapidxml/*.hpp?)

### ISSUE THREAD

**Issue by roalz** [conan-io/conan-center-index#1504]
I'm not sure if this may be better filed as issue, so I just make a question for now.
I'm having problems on any c++ code I write that uses rapidxml and is compiled on both Windows, Linux with distro librapidxml-dev package and other Linux with dependencies managed using conan.

On Windows and Linux with rapidxml installed as distro package,
the library include files are under .../include/rapidxml/, thus I use:
`#include <rapidxml/rapidxml.hpp>`

but with the conan rapidxml package, include files are directly under .../package/.../include/,
so the above #include fails (it works if I directly `#include <rapidxml.hpp>`, but then it would fail in other target platforms.

I understand rapidxml is a header-only library and does not force to have a "rapidxml" sub-directory under include/, but this would be more adherent to other conan packages and distro packages (as well as, IMHO, to general best practices for library packaging).

Would it be possible and acceptable for the conan rapidxml/1.13 package to be modified to have all include files (just 4 .hpp) in both _include/_ AND _include/rapidxml/_ ?
This would mean duplicating a few files (ugly), but keeping back (and forth) compatibility.

Should I add an issue for this problem?

**Comment by danimtb** [comment]
Sure! Take a look at the PR proposed by @SpaceIm here #1507
