### ISSUE TITLE
[libjpeg/9e]: sha256 signature failed for 'jpegsrc.v9e.tar.gz' file

### ISSUE THREAD

**Issue by Wuqiqi123** [conan-io/conan-center-index#15044]
### Package and Environment Details

* Package Name/Version: **libjpeg/9e:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

### Steps to reproduce

 conan install libjpeg/9e@ -r=conancenter --build=libjpeg

### Logs

Requirements
    libjpeg/9e from 'conancenter' - Cache
Packages
    libjpeg/9e:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Build

Installing (downloading, building) binaries...
libjpeg/9e: WARN: Build folder is dirty, removing it: C:\Users\wqq\.conan\data\libjpeg\9e\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
libjpeg/9e: WARN: Trying to remove corrupted source folder
libjpeg/9e: WARN: This can take a while for big packages
libjpeg/9e: Configuring sources in C:\Users\wqq\.conan\data\libjpeg\9e\_\_\source\src
Downloading jpegsrc.v9e.tar.gz completed [4200.00k]                                      libjpeg/9e:
ERROR: libjpeg/9e: Error in source() method, line 66
        destination=self.source_folder, strip_root=True)
        ConanException: sha256 signature failed for 'jpegsrc.v9e.tar.gz' file.
 Provided signature: 4077d6a6a75aeb01884f708919d25934c93305e49f7e3f36db9129320e6f4f3d
 Computed signature: 5d5349c3aacc978dfcbde11f7904d2965395261dd818ce21c15806f736b8911e

**Comment by Wuqiqi123** [comment]
This libjpeg often go wrong for the same reason， why?

**Comment by SpaceIm** [comment]
Yes, it's a running gag: https://github.com/conan-io/conan-center-index/issues/13417

**Comment by uilianries** [comment]
> Yes, it's a running gag: #4151 #8921 #13417

@SpaceIm thank you for mapping it!
