### ISSUE TITLE
[package] fft/cci.20061228: verify certificate for http and failed

### ISSUE THREAD

**Issue by shelper** [conan-io/conan-center-index#15124]
### Description

Trying to install fft/cci.20061228 from source as I need to build it for android, so conan tries to download the source from http://www.kurims.kyoto-u.ac.jp/~ooura/fft2d.tgz but failed. 
I tried to download using curl and was told the file has been moved to an https link so i think the recipe needs to be updated.

but then i disabled the verify_ssl for conan-center i still get error:
> ERROR: fft/cci.20061228: Error in source() method, line 74
        get(self, **self.conan_data["sources"][self.version],
        ConanException: Error downloading file http://www.kurims.kyoto-u.ac.jp/~ooura/fft2d.tgz: 'HTTPSConnectionPool(host='www.kurims.kyoto-u.ac.jp', port=443): Max retries exceeded with url: /~ooura/fft2d.tgz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))'

Did i miss anything here for this verify_ssl option? 

BTW, i also tried for linux build on ubuntu and same thing happens. so i think it does not matter for environment & profile

### Package and Environment Details

* Package Name/Version: **fft/cci.20061228**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **clang 9**
* Python version: **Python 3.10.6**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

### Steps to reproduce

conan install fft/cci.20061228@_/_ -b

### Logs

<details><summary>Click to expand log</summary>

```
fft/cci.20061228: Forced build from source
Installing package: fft/cci.20061228
Requirements
    fft/cci.20061228 from 'conancenter' - Cache
Packages
    fft/cci.20061228:6af9cc7cb931c5ad942174fd7838eb655717c709 - Build

Installing (downloading, building) binaries...
fft/cci.20061228: WARN: Trying to remove corrupted source folder
fft/cci.20061228: WARN: This can take a while for big packages
fft/cci.20061228: Configuring sources in /home/mpnv38/.conan/data/fft/cci.20061228/_/_/source/src
fft/cci.20061228: ERROR: Error downloading file http://www.kurims.kyoto-u.ac.jp/~ooura/fft2d.tgz: 'HTTPSConnectionPool(host='www.kurims.kyoto-u.ac.jp', port=443): Max retries exceeded with url: /~ooura/fft2d.tgz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))'
fft/cci.20061228: Waiting 5 seconds to retry...
ERROR: fft/cci.20061228: Error in source() method, line 74
        get(self, **self.conan_data["sources"][self.version],
        ConanException: Error downloading file http://www.kurims.kyoto-u.ac.jp/~ooura/fft2d.tgz: 'HTTPSConnectionPool(host='www.kurims.kyoto-u.ac.jp', port=443): Max retries exceeded with url: /~ooura/fft2d.tgz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))'
```

</details>

**Comment by jcar87** [comment]
Hi @shelper - thanks for reporting this issue.

Would you be able to test if this issue is fixed by switching this file: https://github.com/conan-io/conan-center-index/blob/master/recipes/fft/all/conandata.yml#L3 to use the `https` URL instead?

```
git clone https://github.com/conan-io/conan-center-index.git
cd conan-center-index/recipes/fft/all

#edit the file and update the URL

conan create . cci.20061228@
```

If that works we can easily update the URL, assuming the checksum has not changed - this is probably for the best either way, as `https` is much preferred. Unclear why it fails after resolving the redirect!

**Comment by shelper** [comment]
still the same error, see the log below. and i also tried to disable the verify ssl still error
not sure if i understand correctly but why it still goes through ssl certificate verify after i disable it in conan remote?


> Exporting package recipe
fft/cci.20061228 exports: File 'conandata.yml' found. Exporting it...
fft/cci.20061228 exports: Copied 1 '.yml' file: conandata.yml
fft/cci.20061228 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
fft/cci.20061228 exports_sources: Copied 1 '.c' file: fft_build.c
fft/cci.20061228 exports_sources: Copied 4 '.h' files: fft.h, fft2.h, fft3.h, dct.h
fft/cci.20061228: The stored package has not changed
fft/cci.20061228: Using the exported files summary hash as the recipe revision: a568a5733407c8637e42a02bee8fd22e
fft/cci.20061228: Source folder is corrupted, forcing removal
fft/cci.20061228: Exported revision: a568a5733407c8637e42a02bee8fd22e
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

fft/cci.20061228: Forced build from source
fft/cci.20061228 (test package): Installing package
Requirements
    fft/cci.20061228 from 'conancenter' - Cache
Packages
    fft/cci.20061228:6af9cc7cb931c5ad942174fd7838eb655717c709 - Build

Installing (downloading, building) binaries...
fft/cci.20061228: WARN: Build folder is dirty, removing it: /home/mpnv38/.conan/data/fft/cci.20061228/_/_/build/6af9cc7cb931c5ad942174fd7838eb655717c709
fft/cci.20061228: Configuring sources in /home/mpnv38/.conan/data/fft/cci.20061228/_/_/source/src
fft/cci.20061228: ERROR: Error downloading file https://www.kurims.kyoto-u.ac.jp/~ooura/fft2d.tgz: 'HTTPSConnectionPool(host='www.kurims.kyoto-u.ac.jp', port=443): Max retries exceeded with url: /~ooura/fft2d.tgz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))'
fft/cci.20061228: Waiting 5 seconds to retry...
ERROR: fft/cci.20061228: Error in source() method, line 74
        get(self, **self.conan_data["sources"][self.version],
        ConanException: Error downloading file https://www.kurims.kyoto-u.ac.jp/~ooura/fft2d.tgz: 'HTTPSConnectionPool(host='www.kurims.kyoto-u.ac.jp', port=443): Max retries exceeded with url: /~ooura/fft2d.tgz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))'

**Comment by SpaceIm** [comment]
Works fine for me. Are you behind a proxy?

**Comment by shelper** [comment]
@SpaceIm i am using my companies computer. i dont think i am behind proxy but i do have some security software, e.g. corp firewall enabled, which i cannot disable... however, on the other hand, i am able to download using requests as below
```
r = requests.get("https://www.kurims.kyoto-u.ac.jp/~ooura/fft2d.tgz", verify=False)
open('fft2d.tgz', 'wb').write(r.content)
```

of course if i dont set verify to false it will fail with message below

> SSLError: HTTPSConnectionPool(host='www.kurims.kyoto-u.ac.jp', port=443): Max retries exceeded with url: /~ooura/fft2d.tgz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

what i dont understanding is then, why i still get the error after i set conan remote to disable verify_ssl?

**Comment by SpaceIm** [comment]
It's very common in companies, your conan client is not properly configured to use your company certificate.

**Comment by shelper** [comment]
so is there document tells how to sync the client with the company certificate? if i know where the certificate file is?

**Comment by shelper** [comment]
Just another note, I manually download the src and try to build it locally with the recipe provided here but I got error of not finding 'alloc.h'...
Did I miss anything here?

**Comment by shelper** [comment]
i believe it is due to the zscaler, after i put the root cert of zscaler to conan's cacert.pem, the source canb e downloaded, and everything works.
