### ISSUE TITLE
[service] Incorrect `Failed` label on PRs

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-center-index#15130]
### What is your problem/feature request?

A "lot" of pull requests currently in flight have a `Failed` label, even if all CI finished successfully. I'm listing them below in order to show the magnitude of the problem, and to encourage reviewers to go review these ones too (because the bot seems to merge PRs that are approved, even if they have the `Failed` label):
- https://github.com/conan-io/conan-center-index/pull/15199
- https://github.com/conan-io/conan-center-index/pull/15198
- https://github.com/conan-io/conan-center-index/pull/15160
- https://github.com/conan-io/conan-center-index/pull/15135
- https://github.com/conan-io/conan-center-index/pull/15128
- https://github.com/conan-io/conan-center-index/pull/15126
- https://github.com/conan-io/conan-center-index/pull/15116
- https://github.com/conan-io/conan-center-index/pull/15081
- https://github.com/conan-io/conan-center-index/pull/15077
- https://github.com/conan-io/conan-center-index/pull/15064
- https://github.com/conan-io/conan-center-index/pull/15048
- https://github.com/conan-io/conan-center-index/pull/15034
- https://github.com/conan-io/conan-center-index/pull/15029
- https://github.com/conan-io/conan-center-index/pull/15019
- https://github.com/conan-io/conan-center-index/pull/15018
- https://github.com/conan-io/conan-center-index/pull/15011
- https://github.com/conan-io/conan-center-index/pull/14996
- https://github.com/conan-io/conan-center-index/pull/14987
- https://github.com/conan-io/conan-center-index/pull/14986
- https://github.com/conan-io/conan-center-index/pull/14981
- https://github.com/conan-io/conan-center-index/pull/14958
- https://github.com/conan-io/conan-center-index/pull/14956
- https://github.com/conan-io/conan-center-index/pull/14933
- https://github.com/conan-io/conan-center-index/pull/14931
- https://github.com/conan-io/conan-center-index/pull/14923
- https://github.com/conan-io/conan-center-index/pull/14894
- https://github.com/conan-io/conan-center-index/pull/14878
- https://github.com/conan-io/conan-center-index/pull/14864
- https://github.com/conan-io/conan-center-index/pull/14843
- https://github.com/conan-io/conan-center-index/pull/14834
- https://github.com/conan-io/conan-center-index/pull/14823
- https://github.com/conan-io/conan-center-index/pull/14803
- https://github.com/conan-io/conan-center-index/pull/14744
- https://github.com/conan-io/conan-center-index/pull/14718
- https://github.com/conan-io/conan-center-index/pull/14635
- https://github.com/conan-io/conan-center-index/pull/14489
- https://github.com/conan-io/conan-center-index/pull/13048

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pulls?page=1&q=is%3Apr+is%3Aopen+-is%3Adraft+status%3Asuccess

**Comment by jwillikers** [comment]
@ericLemanissier Thanks for opening this issue. I think this is effecting what shows up for review at https://prince-chrismc.github.io/conan-center-index-pending-review/

**Comment by prince-chrismc** [comment]
It is

**Comment by prince-chrismc** [comment]
I've manually gone back and fixed as many as I good. Feel free to reopen if I missed anything
