### ISSUE TITLE
[question] Missing prebuilt protobuf for c++17?

### ISSUE THREAD

**Issue by jtbandes** [conan-io/conan-center-index#15223]
### What is your question?

I'm trying to use the [conanio/clang13-ubuntu16.04](https://hub.docker.com/r/conanio/clang13-ubuntu16.04/) docker image to build an executable.

I have these commands in my dockerfile to set up c++17 support:
```
RUN conan config init
RUN conan profile update settings.compiler.cppstd=17 default
```

My dependencies look like this:

```
#0 8.051 Requirements
#0 8.051     asio/1.24.0 from 'conancenter' - Downloaded
#0 8.051     nlohmann_json/3.10.5 from 'conancenter' - Downloaded
#0 8.051     openssl/1.1.1s from 'conancenter' - Downloaded
#0 8.051     protobuf/3.21.4 from 'conancenter' - Downloaded
#0 8.051     websocketpp/0.8.2 from 'conancenter' - Downloaded
#0 8.051     zlib/1.2.13 from 'conancenter' - Downloaded
#0 8.051     foxglove-websocket/0.0.1 from user folder - Editable
#0 8.051 Packages
#0 8.051     asio/1.24.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
#0 8.052     nlohmann_json/3.10.5:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
#0 8.052     openssl/1.1.1s:63c2a85d57849e261f98f935b93ecac31ba71b84 - Download
#0 8.052     protobuf/3.21.4:2b471b60d03a9d59f138a492b962f734618de80a - Missing
#0 8.052     websocketpp/0.8.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
#0 8.052     zlib/1.2.13:63c2a85d57849e261f98f935b93ecac31ba71b84 - Download
#0 8.052     foxglove-websocket/0.0.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Editable
```

But `conan install` produces an error:

```
#0 8.052 
#0 8.053 Installing (downloading, building) binaries...
#0 8.054 
#0 8.060 ERROR: Missing binary: protobuf/3.21.4:2b471b60d03a9d59f138a492b962f734618de80a
#0 8.060 protobuf/3.21.4: WARN: Can't find a 'protobuf/3.21.4' package for the specified settings, options and dependencies:
#0 8.060 - Settings: arch=x86_64, build_type=Release, compiler=clang, compiler.cppstd=17, compiler.libcxx=libstdc++, compiler.version=13, os=Linux
#0 8.060 - Options: debug_suffix=True, fPIC=True, lite=False, shared=False, with_rtti=True, with_zlib=True, zlib:fPIC=True, zlib:shared=False
#0 8.060 - Dependencies: zlib/1.2.13
#0 8.060 - Requirements: zlib/1.Y.Z
#0 8.060 - Package ID: 2b471b60d03a9d59f138a492b962f734618de80a
#0 8.060 
#0 8.060 ERROR: Missing prebuilt package for 'protobuf/3.21.4'
#0 8.060 Use 'conan search protobuf/3.21.4@ --table=table.html -r=remote' and open the table.html file to see available packages
#0 8.060 Or try to build locally from sources with '--build=protobuf'
#0 8.060 
#0 8.060 More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
#0 8.060 
```

However, when I look at this `table.html`, it looks like the requirements are satisfied:

<img width="1956" alt="image" src="https://user-images.githubusercontent.com/14237/211905356-ce489f56-663c-4437-807a-58e849d57ebf.png">

(Plus, it does seem like `openssl` and `zlib` provide prebuilt packages that work with this configuration.)

When I remove the cppstd=17 configuration from my dockerfile, I get a prebuilt package. But I need c++17 support for my project.

What am I doing wrong?

**Comment by SpaceIm** [comment]
conan-center doesn't provide pre-built packages of C++ libraries for `compiler.cppstd=17`. You have to build from source with `-b missing`.
`compiler.cppstd` doesn't contribute to package id of C libraries like `zlib` or `openssl`. This is why you can find pre-built packages for these recipes regardless of `compiler.cppstd` value, but not for C++ libraries like `protobuf`.

**Comment by jtbandes** [comment]
Thanks for the explanation, that makes sense. Is there a plan to provide pre-built packages for `compiler.cppstd=17`? Seems like that would be a pretty common requirement these days?

**Comment by uilianries** [comment]
>  Is there a plan to provide pre-built packages for compiler.cppstd=17? Seems like that would be a pretty common requirement these days?

@jtbandes Yes, but only for Conan 2.x: https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v2.yml#L129

For Conan 1.x it will not occur, first, because it will be replaced by Conan 2.x, and because cppstd was included after 1.x, so, by default, all users have `cppstd=None`.
