### ISSUE TITLE
[package] : xz_utils/5.2.5 fail to cross build for android

### ISSUE THREAD

**Issue by shelper** [conan-io/conan-center-index#15220]
### Description

I used the same profile to build many other packages for android by cross compiling, so basically the attached profile should work. it should be the recipe for this package that needs to be fixed for android platform

### Package and Environment Details

* Package Name/Version: **xz_utils/5.2.5 **
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **clang 9**
* Conan version: **conan 1.56.0**
* Python version: **Python 3.10.6**

### Conan profile

[settings]
os=Android
os_build=Linux
arch=armv8
arch_build=x86_64
compiler=clang
compiler.version=9
compiler.libcxx=libc++
build_type=Release
os.api_level=21
[options]
[conf]
tools.android:ndk_path=/PATH/TO/android-ndk-r21
[build_requires]
[env]
PATH=['/PATH/TO/android-ndk-r21/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin']
CHOST=aarch64-linux-android
AR=aarch64-linux-android-ar
AS=aarch64-linux-android-as
LD=aarch64-linux-android-ld
STRIP=aarch64-linux-android-strip
RANLIB=aarch64-linux-android-ranlib
CC=aarch64-linux-android21-clang
CXX=aarch64-linux-android21-clang++
CONAN_CMAKE_TOOLCHAIN_FILE=/PATH/TO/conan/profiles/../toolchains/toolchain_android_armv8a.cmake

### Steps to reproduce

 conan install xz_utils/5.2.5@ -pr android_clang_9_armv8a_r21-ndk-preinstalled -b missing

### Logs

<details><summary>Click to expand log</summary>

```
Initializing Automake:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... aarch64-linux-android21-clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/home/mpnv38/.conan/data/xz_utils/5.2.5/_/_/build/d90c6937a846904107bf4cebd7a8705bc34c61ab/build-release':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
xz_utils/5.2.5:
xz_utils/5.2.5: ERROR: Package 'd90c6937a846904107bf4cebd7a8705bc34c61ab' build failed
xz_utils/5.2.5: WARN: Build folder /home/mpnv38/.conan/data/xz_utils/5.2.5/_/_/build/d90c6937a846904107bf4cebd7a8705bc34c61ab/build-release
ERROR: xz_utils/5.2.5: Error in build() method, line 173
        autotools.configure()
        ConanException: Error 1 while executing "/home/mpnv38/.conan/data/xz_utils/5.2.5/_/_/build/d90c6937a846904107bf4cebd7a8705bc34c61ab/src/configure" '--disable-shared' '--enable-static' '--prefix=/' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--disable-doc'
```

</details>

**Comment by SpaceIm** [comment]
`xz_utils` recipe has been migrated to conan v2 build helpers, therefore it doesn't listen anymore env vars defined in `[env]`, and there is nothing conan-center can do against that. You should duplicate these env vars into `[buildenv]` of your profile.
see https://github.com/conan-io/conan-center-index/issues/14781

@memsharded there are many issues opened due to lack of backward compatibility of `[env]` in conan v2 build helpers, it's not a good thing I believe.

**Comment by shelper** [comment]
i added the following lines to the generate() method of the conanfile and it solves the problem 

```python
            # add support for android cross compiling
            if self.settings.os == "Android":
                if self.settings.arch == "armv7":
                    tc.configure_args.append("--host=arm-linux-androideabi")
                elif self.settings.arch == "armv8":
                    tc.configure_args.append("--host=aarch64-linux-android")
                else: 
                    raise ConanException(f"Unknown arch for Android {self.settings.arch}")
```
not sure if this is the right solution but at least it works for me, if it is good, i can open a PR

**Comment by shelper** [comment]
same fix works for libjpeg as well. just to note...
