### ISSUE TITLE
[package] nlohmann_json/3.7.3: No CMake configuration files for cmake_paths generator

### ISSUE THREAD

**Issue by Ansoulom** [conan-io/conan-center-index#1527]
### Package and Environment Details
  * Package Name/Version: **nlohmann_json/3.7.3**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Clang 10.0**
  * Conan version: **conan 1.24.1**
  * Python version: **Python 3.8**

### Conan profile
```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=clang
build_type=Release
[options]
[build_requires]
[env]
```

### Description
Trying to find the nlohmann_json package in CMake results in failure after installing with the cmake_paths generator. CMake cannot find any package configuration files for the package. I checked in the package folder and can confirm that there are indeed no CMake configuration files present for this package. My conan_paths.cmake file gets set up correctly and another package that I use works without problem.

My conanfile.txt:
```
[requires]
Catch2/2.11.1@catchorg/stable
nlohmann_json/3.7.3

[generators]
cmake_paths
```
The relevant part of my CMakeLists.txt:
```
find_package(nlohmann_json 3.7.3 REQUIRED)
target_link_libraries(job_graph_serializer PRIVATE nlohmann_json::nlohmann_json)
```

**Comment by Ansoulom** [comment]
I just tried replacing `nlohmann_json/3.7.3` with `jsonformoderncpp/3.7.3@vthiery/stable` in my conanfile.txt and it works now. Though that's a different package for the same library and I had to add
```
compiler.version=10
compiler.libcxx=c++_shared
```
to my profile for that package to install without an error message.

**Comment by danimtb** [comment]
This is not a bug but something intended. We are not relying on CMake generated files but on the ones generated by Conan with generators. You can find more information in the wiki: https://github.com/conan-io/conan-center-index/wiki/FAQ#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged

**Comment by Ansoulom** [comment]
Hmm, so does this mean that the package is simply not intended to work when using the `cmake_paths` generator? Since that generator does not generate any config files and relies on the config files provided by the library author, if I understand it correctly.

Also, I guess this is a matter of opinion, but I don't agree that `find_package()` is something that should be avoided. This is the idiomatic way to consume packages in CMake and ensures that your build scripts are package manager-agnostic. If the library authors export their configurations correctly, there really shouldn't be a problem.

**Comment by danimtb** [comment]
That's right, packages cannot be consumed with `cmake_paths` generator for the reasons pointed in the link above.

We have strong experience with CMake files and many of them include hardcoded paths to other libraries or options that do not reflect the desire of consumers. Many others look for libraries in your system and you might not notice. Not to say that a lot of libraries do not provide CMake files and cannot be consumed this way.

We think the agnostic information of a package should be in the _conanfile.py_ and generators should expose that information accordingly as consumer's wish (even of libraries that do not provide CMake find or config files). We believe that the `find_package(`) interface is fine to declare dependencies in CMake build system, however, the information about them and the retrieval of the packages should be done by the package manager to achieve a reliable way of using the dependencies you want and not the ones CMake decides to use based on find_package non-deterministic behavior.

**Comment by Ansoulom** [comment]
Alright, turns out that I can achieve the same result by using `cmake_find_package` together with `cmake_paths`. I think the documentation for `cmake_paths` could use some updating to make it clear that using it standalone is discouraged and that it should be combined with `cmake_find_package` instead.

I still think it makes more sense to use the CMake configuration files already provided by the library authors rather than generating new ones, but as this has clearly caused some problems I am just gonna close the issue rather than arguing further.

**Comment by danimtb** [comment]
Thanks a lot for the feedback. We will include that information in the documentation to better explain this. Glad you make it work with the ``cmake_find_package`` generator finally! :smile:

**Comment by OznOg** [comment]
I know this issue is closed, but I strongly agree with @Ansoulom. Relying on CMake config files provided by authors should always be the first choice; if software is badly installed and/or written, I agree than conan package could wrap things so that conan users can use it. So I don't really know the direction taken for conan about this, but I'd really like to have updates about it.

**Comment by danimtb** [comment]
As the documentation was moved from the wiki long time ago, I am referencing the new location of the FAQ referenced above in my previous comment https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged
