### ISSUE TITLE
[package] hdf5/1.13.1 - uploaded recipe not listed in available revisions in CCI

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#15319]
### Description

HDF5 has a new recipe in December:
```
commit 0bd6915176067b51f74ed245fa9128a10b6e4da3
Author: Paul Harris <harris.pc@gmail.com>
Date:   Wed Dec 14 00:06:52 2022 +0800

    (#13605) hdf5 - upgrade for conan v2, simplify szip import
```

And yet, in CCI, the most recent revision is in November!

```
$ conan search hdf5/1.13.1@ -r conancenter --revisions
Revisions for 'hdf5/1.13.1' at remote 'conancenter':
bb3137f67d85190a7a1049893c61884d (2022-11-08 21:10:39 UTC)
1ad1f7f1010460f0a544ca279004ae9c (2022-11-05 14:36:48 UTC)
c25ea62db933036794a8c50b0ccc1be0 (2022-07-03 18:57:03 UTC)
```

### Package and Environment Details

N/A

### Conan profile

N/A

### Steps to reproduce

N/A

### Logs

N/A

**Comment by danimtb** [comment]
Hi @paulharris. Thanks for the report. I am having a look at it, let's see if we can regenerate it.

**Comment by paulharris** [comment]
I don't understand, yes I know #13992 was merged first (Nov 16),
I merged the master into #13605 on Nov 29 (ie merging 13992),
and then #13605 was merged into master Dec 14.

So the latest recipe is still #13605, Dec 14.
Personally, I had guessed that the merge+build was caught during a C3I problem and was dropped from the queue.

**Comment by danimtb** [comment]
@paulharris yes, you are right. What happened in the merge was not clear to me either, probably it was a connection issue or a race condition. Anyway, as #15094 has been merged, now the latest recipe revision should be fine.

```
$ conan search hdf5/1.13.1@ -r conancenter --revisions

Revisions for 'hdf5/1.13.1' at remote 'conancenter':
bb15cf99d40bc2045142e2ec67bea288 (2023-01-11 21:13:23 UTC)
bb3137f67d85190a7a1049893c61884d (2022-11-08 21:10:39 UTC)
1ad1f7f1010460f0a544ca279004ae9c (2022-11-05 14:36:48 UTC)
c25ea62db933036794a8c50b0ccc1be0 (2022-07-03 18:57:03 UTC)
```

**Comment by paulharris** [comment]
Great, thanks!  I see it :)
