### ISSUE TITLE
[request]  DiligentEngine /v2.4.e

### ISSUE THREAD

**Issue by markusgod** [conan-io/conan-center-index#1533]
### Package Details
  * Package Name/Version: **DiligentEngine /v2.4.e**
  * Website: **http://diligentgraphics.com/diligent-engine/**
  * Source code: **https://github.com/DiligentGraphics/DiligentEngine**

### Description Of The Library / Tool
Diligent Engine is a lightweight cross-platform graphics API abstraction library and rendering framework. It is designed to take full advantage of Direct3D12, Vulkan and Metal, while supporting older platforms via Direct3D11, OpenGL and OpenGLES. Diligent Engine exposes common front-end API and uses HLSL as universal shading language on all platforms and rendering back-ends. Platform-specific shader representations (GLSL, DX bytecode or SPIRV) can be used with corresponding back-ends. The engine is intended to be used as graphics subsystem in a game engine or any other 3D application. It is distributed under Apache 2.0 license and is free to use.

**Comment by SpaceIm** [comment]
This library has probably a lot of dependencies. Looking at their README, I see at least `vulkan-loader` which is not yet in CCI.

**Comment by markusgod** [comment]
By the way, can CCI packages depend on bincrafters? There is glew/2.1.0@bincrafters/stable

**Comment by SpaceIm** [comment]
No.

**Comment by madebr** [comment]
About DiligentCore/API240064:

spirv-cross, spirv-tools and spirv-headers are forked by diligent.
- spirv-tools and spirv-headers look the same as upstream, albeit old.
- spirv-cross contains adaptations, and is also based on an old release.

I don't know whether the more recent releases packaged by cci will work.

**Comment by hnOsmium0001** [comment]
spirv-cross, spirv-tools, glew, glslang, volk have all been ported/added to CCI. @markusgod maybe update the table?

**Comment by markusgod** [comment]
| library | url | In CCI |
| --- | --- | --- |
spirv-cross | https://github.com/KhronosGroup/SPIRV-Cross | :heavy_check_mark:
spirv-tools | https://github.com/KhronosGroup/SPIRV-Tools | :heavy_check_mark:
spirv-headers | https://github.com/KhronosGroup/SPIRV-Headers | :heavy_check_mark:
glew | http://glew.sourceforge.net | :heavy_check_mark:
glslang | https://github.com/KhronosGroup/glslang | :heavy_check_mark:
stb | https://github.com/nothings/stb | :heavy_check_mark:
volk | https://github.com/zeux/volk | :heavy_check_mark:
vulkan-headers | https://github.com/KhronosGroup/Vulkan-Headers | :heavy_check_mark:
vulkan-loader | https://github.com/KhronosGroup/Vulkan-Loader | :x:  https://github.com/conan-io/conan-center-index/issues/1346

**Comment by SpaceIm** [comment]
Everything is in CCI, if someone wants to package DiligentEngine.

**Comment by saphiresouldier** [comment]
Any news on this? Would be great to have this!

**Comment by mnesarco** [comment]
Hello Friends,
Any news on this?

**Comment by AndreyMlashkin** [comment]
@markusgod, have you hidden or deleted your implementation? I would gladly use it as basis for a recipe

**Comment by markusgod** [comment]
I've deleted it since it was too far off from Conan packaging standards.

**Comment by AndreyMlashkin** [comment]
As I see, Diligent is using it's own SPIRV-Tools.

if you look here https://github.com/DiligentGraphics/SPIRV-Tools/tree/master
DiligentGraphics/SPIRV-Tools forked from KhronosGroup/SPIRV-Tools
This branch is 13 commits ahead, 5 commits behind KhronosGroup:master.

What's the best way to proceed here? Is it ok to create another spirv-tools recipe, that will compile this forked modification? Or set another version/channel to it.

**Comment by madebr** [comment]
If a forked project is really needed, you can add it with a namespace. e.g. `diligentgraphics-spirv-tools`.
We have `crashpad` and `sentry-crashpad`, `breakpad` and `sentry-breakpad`.

**Comment by SpaceIm** [comment]
Did you try to use a release of spirv-tools instead? If it doesn't work, you can compile diligent engine as is, without creating an alternative recipe of spirv-tools.

**Comment by madebr** [comment]
That would not work when cross building, using a current version of conan.

**Comment by AndreyMlashkin** [comment]
I have tried to use conan SPIRV-Tools instead and it does not work.
I will play around with both approaches, thank you for the ideas!

**Comment by AndreyMlashkin** [comment]
I have started to implement a diligent recipe in my branch
https://github.com/AndreyMlashkin/conan-center-index/tree/add_diligent

first I need to create dirigent-* versions of all dependent libraries, as they are not versioned properly and also some of them have local modifications as mentioned by a maintainer here
https://github.com/DiligentGraphics/DiligentCore/issues/250#issuecomment-867899973

**Comment by AndreyMlashkin** [comment]
I need a community help here. Please, checkout my branch or build log from attachment
[build_log.txt](https://github.com/conan-io/conan-center-index/files/6740321/build_log.txt)

**Comment by madebr** [comment]
I can reproduce the error on gcc11@Linux, but don't know how to fix it.

A `diligent_spirv_cross::Compiler` object is passed and used here:
https://github.com/DiligentGraphics/DiligentCore/blob/84bc33c5693557eb6914043d10101c17c3f30ba4/Graphics/ShaderTools/src/SPIRVShaderResources.cpp#L41-L44

But I can only find the forward declaration of this class:
https://github.com/DiligentGraphics/DiligentCore/blob/84bc33c5693557eb6914043d10101c17c3f30ba4/Graphics/ShaderTools/include/SPIRVShaderResources.hpp#L52

**Comment by AndreyMlashkin** [comment]
It comes from
DiligentCore/ThirdParty/SPIRV-Cross/spirv_cross.hpp

**Comment by AndreyMlashkin** [comment]
I think I know, why does it happens: from DiligentCore/ThirdParty/CMakeLists.txt
>     set(SPIRV_CROSS_NAMESPACE_OVERRIDE diligent_spirv_cross CACHE STRING "Override the namespace used in the C++ API.")

Diligent overrides namespace name, while compiling spirv-cross library...

What's the best way to handle such things? add a conan option for spirv-cross recipe?
Honestly, I don't see other options, as namespace name is compiled into object code...

**Comment by AndreyMlashkin** [comment]
But from the other hand, it should be possible to link spirv-cross multiple times just with a different namespace override... Conan supports this, right? I just need to declare it as a "private" requirement

**Comment by AndreyMlashkin** [comment]
I am already in a state to be able to build with with_glslang=False

**Comment by AndreyMlashkin** [comment]
To continue, I need https://github.com/conan-io/conan-center-index/pull/6092 to be resolved. So, standby for now.

for those, who would try the recipe out, use this script:

cd conan-center-index/recipes/spirv-headers/all
conan create . spirv-headers/cci.20210526@
cd ../../spirv-tools/all/
conan create . spirv-tools/cci.20210601@
cd ../../spirv-cross/all/
conan create . spirv-cross/cci.20210601@
cd ../../diligent-core/all
conan create . diligent-core/2.5@

**Comment by AndreyMlashkin** [comment]
I have detected another dependency of dirent:
https://github.com/conan-io/conan-center-index/issues/2932

**Comment by uilianries** [comment]
@AndreyMlashkin For custom versions: https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases

Custom Forks, I suggest you using the project's name as package prefix.

**Comment by AndreyMlashkin** [comment]
@uilianries, I have already opened PR the way you proposed
https://github.com/conan-io/conan-center-index/pull/7867#pullrequestreview-794035620

https://github.com/conan-io/conan-center-index/pull/7868#event-5547788477

**Comment by uilianries** [comment]
Thank you!

**Comment by AndreyMlashkin** [comment]
@markusgod, could you please try my recipe? Does it work for you?

**Comment by markusgod** [comment]
Sorry I'm moved on since then quite a bit, and in process switched stack to rust.

**Comment by AndreyMlashkin** [comment]
Done.
now we have 3 recipes:
diligent-core
diligent-tools
diligent-fx

**Comment by AndreyMlashkin** [comment]
Here are the versions available with conan:

diligent-core/api.250014
diligent-core/2.5.1
diligent-core/2.5.2
diligent-fx/cci.20211112
diligent-fx/cci.20220219
diligent-tools/cci.20211009

There is no diligent-tools/2.5.2 yet.

**Comment by SSE4** [comment]
> > Done. now we have 3 recipes: diligent-core diligent-tools diligent-fx
> 
> I know this issue is a little bit stale, but diligent-tools appears to not be working - I suspect because it depends on an older version of diligent-core than I was trying to use? Should I create an issue for this? 😄

by `appears to not be working` - what exactly do you mean? do you get build failure? does it crash? do you have some logs? it would be nice, if you could be a bit more specific, e.g. what are you trying to do, what do you expect to get, what are you getting instead, etc.

**Comment by SK83RJOSH** [comment]
I was getting compilation errors due to a function signature changing
between versions. I was intentionally vague as I wanted to know if it was
PEBKAC or not – it unfortunately was as I was overriding the core version
by mistake not realizing tools and fx depend on an older version. 🙂

Unfortunately the recipes don't set some defines for determining what
graphics backends are supported – at least as far as I could tell. I
ultimately I used .gitmodules to pull these in and forgot to follow up with
a confirmation of my silliness. Long day of build system struggles so my
apologies.
