### ISSUE TITLE
[question] how to solve dependency conflict 

### ISSUE THREAD

**Issue by Wuqiqi123** [conan-io/conan-center-index#15359]
### What is your question?

My conan file is 
```
[requires]
qt/5.15.7
eigen/3.4.0
spdlog/1.11.0
nlohmann_json/3.11.2
pybind11/2.10.0
gtest/1.12.1
magic_enum/0.8.1
cpython/3.10.0

```

with error 
```
ERROR: Conflict in cpython/3.10.0:
    'cpython/3.10.0' requires 'zlib/1.2.11' while 'libpng/1.6.38' requires 'zlib/1.2.13'.
    To fix this conflict you need to override the package 'zlib' in your root package.
```

How to solve this issue, Can we upgrade cpython's dependency "zlib" to 1.2.13 as same as Qt's.

**Comment by SpaceIm** [comment]
That's more a question for conan client. There are two main solutions for users when there is a version conflict:
- `--require-override="zlib/1.2.13"` when you call conan install or conan create
- add `zlib/1.2.13` in `[requires]` of your `conanfile.txt`, or `self.requires("zlib/1.2.13", override=True)` if you have a `conanfile.py`.

**Comment by Wuqiqi123** [comment]
> That's more a question for conan client. There are two main solutions for users when there is a version conflict:
> 
> * `--require-override="zlib/1.2.13"` when you call conan install or conan create
> * add `zlib/1.2.13` in `[requires]` of your `conanfile.txt`, or `self.requires("zlib/1.2.13", override=True)` if you have a `conanfile.py`.

This works! Thanks a lot!
