### ISSUE TITLE
[package] opencv/4.5.5: Missing RUNPATH $ORIGIN

### ISSUE THREAD

**Issue by MaxKarel** [conan-io/conan-center-index#15363]
### Description

Using opencv with option shared=True is not possible.
It creates .so files which are not able to find their own dependencies since their RUNPATH is empty (`readelf -d libopencv_core.so`). During linking stage of my project it fails with when linking `libopencv_imgcodecs` which cannot find `libopencv_imgproc`

### Package and Environment Details

* Package Name/Version: **opencv/4.5.5**
* Operating System+version: **Linux Ubuntu 17.04**
* Compiler+version: **GCC 7.2**
* Docker image: **conanio/gcc7**
* Conan version: **conan 1.57.0**
* Python version: **Python 3.7.13**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

install system requirements

`apt install libx11-xcb-dev libfontenc-dev libxaw7-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxres-dev libxss-dev libxt-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev libvdpau-dev libva-dev libgtk2.0-dev -y`

`conan install opencv/4.5.5@ -oshared=True`

### Logs

<details><summary>Click to expand log</summary>

```
conan@c8c633d548d8:~/.conan/data/opencv/4.5.5/_/_/package/1d7b4d367aca1f48e1d6bcd54f5782bc06b2bf4b/lib$ readelf libopencv_imgproc.so -d

Dynamic section at offset 0x57ebf8 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_core.so.405]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libopencv_imgproc.so.405]
 0x000000000000000c (INIT)               0x66dc0
 0x000000000000000d (FINI)               0x4a4500
 0x0000000000000019 (INIT_ARRAY)         0x764c20
 0x000000000000001b (INIT_ARRAYSZ)       88 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x764c78
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1f0
 0x0000000000000005 (STRTAB)             0x5c30
 0x0000000000000006 (SYMTAB)             0xf98
 0x000000000000000a (STRSZ)              36449 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x77f000
 0x0000000000000002 (PLTRELSZ)           12528 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x63cd0
 0x0000000000000007 (RELA)               0xf208
 0x0000000000000008 (RELASZ)             346824 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0xf0f8
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0xea92
 0x000000006ffffff9 (RELACOUNT)          12648
 0x0000000000000000 (NULL)               0x0
conan@c8c633d548d8:~/.conan/data/opencv/4.5.5/_/_/package/1d7b4d367aca1f48e1d6bcd54f5782bc06b2bf4b/lib$ ldd libopencv_imgproc.so       
	linux-vdso.so.1 =>  (0x00007fffadf16000)
	libopencv_core.so.405 => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4b0c16e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4b0bde8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4b0bbd1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b0b7f1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b0ccea000)

```

</details>

**Comment by SpaceIm** [comment]
conan-center recipes don't set `RPATH`. This why there is `VirtualRunEnv`.

**Comment by StellaSmith** [comment]
if you execute the following you will see that it can find the shared object, as conan will populate an environment file with the proper `DYLD_LIBRARY_PATH` & `LD_LIBRARY_PATH` environment variables so the linker can find the libraries installed by conan.
```sh
conan install opencv/4.5.5@ -oshared=True -if /tmp/build
source /tmp/build/conanrun.sh
ldd libopencv_imgproc.so
```

If you intend to deploy a binary that requires these libraries, and distribute the binaries of the library, you should take a look into Conan V2's deploy documentation. Alternatively (since conan2 is not production ready) you can copy the libraries manually, and set `RPATH` of your executable to `$ORIGIN/../lib` or create an script like so:
```sh
here=$(dirname $0)/lib
export LD_LIBRARY_PATH="$here/lib":LD_LIBRARY_PATH
exec $here/bin/myexec
```

**Comment by MaxKarel** [comment]
Thank you @SpaceIm , yes I misspoke and its a problem with the loader. And it seems that VirtualRunEnv will solve the issue. But may I suggest including a link to it from https://docs.conan.io/en/latest/howtos/manage_shared_libraries/rpaths.html here?

I was not aware of that generator and google directed me only to that wiki page when searching for problems with RPATHS.

@StellaSmith yes right now I am manually patching libraries for deployment, so thank you for bringing Conan v2 to my attention
