### ISSUE TITLE
[package] cppcheck/2.9.3: "Failed to load library configuration file 'std.cfg'"

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan-center-index#15421]
### Description

Hi conan community,

I use cppcheck 2.9.3 as tool_requirement to get a code quality analysis.
But since several days I get an error about a missing std.cfg as in this old issue #5831.

I think this is a regression from https://github.com/conan-io/conan-center-index/pull/15322
On stackoverflow, https://stackoverflow.com/questions/22486573/cppcheck-std-cfg-not-found-error-when-std-cfg-file-is-available, it talk about a CFGDIR config option to set.

@ericLemanissier are you aware of this kind of issue?

Regards.

### Package and Environment Details

* Package Name/Version: **cppcheck/2.9.3**
* Docker image: **conanio/gcc8-ubuntu18.04**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce

cppcheck is invoced from a custom cmake function through a custom cppcheck target.

### Logs

<details><summary>Click to expand log</summary>

```
ppcheck -v -j 20 --enable=style,performance,portability,information,missingInclude --std=c++14 --project=compile_commands.json --project-configuration=Debug --suppress=missingIncludeSystem --report-progress --xml --output-file=cppcheck.xml source
FAILED: CMakeFiles/cppcheck /builds/rjvJpVxe/0/unite/jupiter2g/CMakeFiles/cppcheck 
cd /builds/rjvJpVxe/0/unite/jupiter2g && cppcheck -v -j 20 --enable=style,performance,portability,information,missingInclude --std=c++14 --project=compile_commands.json --project-configuration=Debug --suppress=missingIncludeSystem --report-progress --xml --output-file=cppcheck.xml source
cppcheck: Failed to load library configuration file 'std.cfg'. File not found
        <error id="failedToLoadCfg" severity="information" msg="Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with FILESDIR set to &quot;/home/conan/w/prod/BuildSingleReference/.conan/data/cppcheck/2.9.3/_/_/package/51125fcc9f0b15c997fcd78c366540a8cb67d811/res&quot; and will therefore search for std.cfg in /home/conan/w/prod/BuildSingleReference/.conan/data/cppcheck/2.9.3/_/_/package/51125fcc9f0b15c997fcd78c366540a8cb67d811/res/cfg." verbose="Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with FILESDIR set to &quot;/home/conan/w/prod/BuildSingleReference/.conan/data/cppcheck/2.9.3/_/_/package/51125fcc9f0b15c997fcd78c366540a8cb67d811/res&quot; and will therefore search for std.cfg in /home/conan/w/prod/BuildSingleReference/.conan/data/cppcheck/2.9.3/_/_/package/51125fcc9f0b15c997fcd78c366540a8cb67d811/res/cfg."/>
ninja: build stopped: subcommand failed.
```

</details>

**Comment by ericLemanissier** [comment]
Could you please try with https://github.com/conan-io/conan-center-index/pull/15424 ?

**Comment by EstebanDugueperoux2** [comment]
It fix my issue.
Thanks @ericLemanissier for your fast reply and fix.
