### ISSUE TITLE
[request] librdkafka/v1.4.0 

### ISSUE THREAD

**Issue by paultomas** [conan-io/conan-center-index#1543]
### Package Details
  * Package Name/Version: **librdkafka/1.4.0**
  * Website: **https://github.com/edenhill/librdkafka**
  * Source code: **https://github.com/edenhill/librdkafka**

### Description Of The Library / Tool
the Apache Kafka C/C++ client library

**Comment by uilianries** [comment]
Already available: https://github.com/conan-io/conan-center-index/commit/fbed10a99eedcb465fb2c85e51f8a6e329a28cc8
