### ISSUE TITLE
[package] boost/*: package_info fails if host architecture is wasm

### ISSUE THREAD

**Issue by ovostrikov** [conan-io/conan-center-index#15448]
### Description

Boost package creation fails for WebAssembly if host profile is set up correctly.

### Package and Environment Details

* Package Name/Version: boost/1.80.0
* Operating System+version: WSL Ubuntu 20.04
* Compiler+version: Emscripten 3.1.24
* Conan version: conan 1.53.0
* Python version: Python 3.8.10

### Conan profile

```
[settings]
os=Emscripten
os_build=Linux
arch=wasm
arch_build=x86_64
compiler=clang
compiler.version=15
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce

conanfile.txt

```
[requires]
boost/1.80.0
[options]
boost:without_context=True
```
emscripten.profile

```
include(default)
[settings]
os=Emscripten
arch=wasm
compiler=clang
compiler.version=15
compiler.libcxx=libc++
[options]
[env]
#setup enviroment variable for emscripten
```

Call
`conan install . --build --profile:host=emscripten.profile --profile:build=default`

package_info method fails because _b2_architecture variable is empty since [wasm is not in the list of b2 supported architectures](https://www.boost.org/doc/libs/1_81_0/tools/build/doc/html/index.html#bbv2.overview.builtins.features).

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: boost/1.80.0: Error in package_info() method, line 1586
        libsuffix_data["arch"] = f"-{self._b2_architecture[0]}{self._b2_address_model}"
        TypeError: 'NoneType' object is not subscriptable
```

</details>

**Comment by unfor19** [comment]
@ovostrikov are you able to build `boost` for `wasm` after the fix?
