### ISSUE TITLE
[service] `print_run_commands = True` to improve logs

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#155]
I think, setting `print_run_commands` to `True` would be interesting to have more verbose logs.
Because right now, the commands are not logged in the stdout.

**Comment by uilianries** [comment]
I see no problem adding such feature. @lasote do you know if this suggestion could increase much storage?

**Comment by lasote** [comment]
I don't think storage is a problem.

**Comment by SSE4** [comment]
I had problems with `print_run_commands` once in the past, as if you try to capture the output of conan, it will contain unexpected line

**Comment by lasote** [comment]
Mhh, but it should only print the command to be executed, actually, the output of the command is printed already.

**Comment by lasote** [comment]
e.g:

```
----Running------
> ls -la .
-----------------
```

**Comment by madebr** [comment]
Currently, the logs contain the executed commands.
So the original problem of this issue has been addressed.
