### ISSUE TITLE
[tuplet] v2.0.0 or later: support c++17

### ISSUE THREAD

**Issue by lukester1975** [conan-io/conan-center-index#15533]
### Description

Tuplet as of 2.0.0 supports c++17: https://github.com/codeinred/tuplet/tree/v2.0.0#additional-features

Current recipe mandates c++20.

### Package and Environment Details

Any

### Conan profile

Any

### Steps to reproduce

Any

### Logs

Any

**Comment by toge** [comment]
@lukester1975 
Thank you for your report.

I missed the release notes of tuplet since 2.0.0.
I create PR to solve it.
Please wait a moment to merge this.
