### ISSUE TITLE
[package] ConanException: sha256 signature failed (Seems lots of github projects are being affeted)

### ISSUE THREAD

**Issue by offa** [conan-io/conan-center-index#15571]
### Description

Installation of Catch2 v3.3.0 fails due to hash mismatches since today:

```
catch2/3.3.0: Configuring sources in /github/home/.conan/data/catch2/3.3.0/_/_/source/src
ERROR: catch2/3.3.0: Error in source() method, line 92
	get(self, **self.conan_data["sources"][self.version], destination=self.source_folder, strip_root=True)
	ConanException: sha256 signature failed for 'v3.3.0.tar.gz' file. 
 Provided signature: fe2f29a54ca775c2dd04bb97ffb79d398e6210e3caa174348b5cd3b7e4ca887d  
 Computed signature: 48f06c98e685ac809db092364a7ef5604ed51f3e9edacca1b4beb84cdd147038
```

### Package and Environment Details

* Package Name/Version: **catch2/3.3.0**
* Operating System+version: **Linux (various) / Windows / Mac OS**
* Compiler+version: **Linux (various GCC and Clang) / MSVC / OS X Clang**
* ~~Docker image: **N/A**~~
* Conan version: **conan 1.57.0**
* Python version: **Python 3.10**

### Conan profile

_Default Linux (GCC / Clang), Windows (MSVC) and Mac OS (Clang)_

### Steps to reproduce

1. Install catch2/3.3.0
2. Installation fails with hash mismatch 

### Logs

<details><summary>Click to expand log</summary>

```
catch2/3.3.0: Configuring sources in /github/home/.conan/data/catch2/3.3.0/_/_/source/src
ERROR: catch2/3.3.0: Error in source() method, line 92
	get(self, **self.conan_data["sources"][self.version], destination=self.source_folder, strip_root=True)
	ConanException: sha256 signature failed for 'v3.3.0.tar.gz' file. 
 Provided signature: fe2f29a54ca775c2dd04bb97ffb79d398e6210e3caa174348b5cd3b7e4ca887d  
 Computed signature: 48f06c98e685ac809db092364a7ef5604ed51f3e9edacca1b4beb84cdd147038
```

</details>

**Comment by kbarry-aurora** [comment]
I'm also seeing this for some other packages: `libpqxx/7.7.4`, `fmt/8.1.1`, `protobuf/3.21.4`

**Comment by SpaceIm** [comment]
Yes, all auto generated tarball from github seem to be affected.

**Comment by prince-chrismc** [comment]
Thanks for reporting, I am pinning this issue since it's kinda beyond our control 😱

**Comment by daniel-heater-imprivata** [comment]
@prince-chrismc Is the response going to be to update all of the affect SHA in Conan or do we know that yet?

**Comment by fpelliccioni** [comment]
Do you know if the issue is just with `.tar.gz` files?
What about `.zip` files?
Is it a Github issue?

**Comment by SpaceIm** [comment]
https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1409362685

**Comment by ericriff** [comment]
It looks like a generalized issue on GitHub
https://github.com/orgs/community/discussions/45830

**Comment by SpaceIm** [comment]
https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

**Comment by prince-chrismc** [comment]
RIP

**Comment by ericriff** [comment]
I hope they roll this back or every packaging system will be broken

**Comment by Hopobcn** [comment]
> Hey,
> 
> I'm one of the engineers in the Git Systems org at GitHub. I think there's been a misinterpretation of what we guarantee as far as stability.
> 
> If you generate a release for a particular tag, and you upload your own assets, such as a tarball or binaries, we'll guarantee those don't change. However, the automated "Source code (tar.gz)" and "Source code (zip)" links, as well as any automated archives we generate, aren't guaranteed to be stable. That's because Git doesn't guarantee stability here and we rely on Git to generate those archives on the fly, so as we upgrade, things may change.
> 
> If you need a stable source code archive, please generate a release and upload your own archive as part of this process, and then you can reference those with stable hashes.
> 
> To give you an example as to what's stable and what's not, if you look at the latest Git LFS release at https://github.com/git-lfs/git-lfs/releases/tag/v3.3.0, all of the Assets entries _except_ the two "Source code" links at the bottom are guaranteed to be stable (since those two are autogenerated). You'll notice we ship our own stable tarball and signed hashes as part of the assets, and that works.
> 
> I apologize for the confusion here, and hopefully this clarifies things.

ouch.. 

Is this an opportunity to mirror everything? :-D

**Comment by SpaceIm** [comment]
This is why conan-center must always try to dowwload stable archives instead of autogenerated github tarball, but lot of projects don't generate source code tarball of their releases... Yet, my understanding is that current issue only changed checksum of autogenerated .tar.gz, .tar.zip should not be affected (anybody can confirm?).

**Comment by ericriff** [comment]
What about projects that don't even do releases?

**Comment by SpaceIm** [comment]
No hope for these projects.

**Comment by ericriff** [comment]
The amount of backslash on github is huge. The broke a lot of things with this. Hopefully they roll it back.
This comment gets me lol
https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1409404725

**Comment by ericriff** [comment]
yay
https://github.com/orgs/community/discussions/45830#discussioncomment-4823799

**Comment by hizkifw** [comment]
Looks like the rollback is finished, I'm seeing my packages build again.

**Comment by offa** [comment]
Indeed, it works again.

**Comment by SpaceIm** [comment]
https://github.com/orgs/community/discussions/46034
