### ISSUE TITLE
[request] cpr/1.10

### ISSUE THREAD

**Issue by tomdavsmi** [conan-io/conan-center-index#15715]
### Package Name/Version

cpr/1.10

### Changelog

https://github.com/libcpr/cpr/releases/tag/1.10.0

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by toge** [comment]
Thank for your request.
I already created PR for it.
https://github.com/conan-io/conan-center-index/pull/15522
Please wait until merged.

**Comment by tomdavsmi** [comment]
Awesome! It completely slipped my mind to check for open PRs, thank you!
