### ISSUE TITLE
libjpeg-turbo/2.1.3: fail compilation on MacOS-12 github instance

### ISSUE THREAD

**Issue by victor1234** [conan-io/conan-center-index#15711]
### Description

Seems new revision #15586  broke CI of [WaveletBuffer](https://github.com/panda-official/WaveletBuffer)

### Package and Environment Details

* Package Name/Version: **libjpeg-turbo/2.1.3**
* Operating System+version: **github macos-12**
* Compiler+version: **apple-clang-14.0**
* Conan version: **conan 1.56**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=14.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

### Steps to reproduce

conan install libjpeg-turbo/2.1.3

### Logs

```
ERROR: libjpeg-turbo/2.1.3: Error in build() method, line 155
	self._patch_sources()
while calling '_patch_sources', line 143
	apply_conandata_patches(self)
	FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/.conan/data/libjpeg-turbo/2.1.3/_/_/build/0e3e7d817b8289a1f748361498cd69f24c354dd8/patches/2.1.3-0001-fix-cmake.patch'
```

[full log](https://github.com/panda-official/WaveletBuffer/actions/runs/4087117538/jobs/7047246539)

**Comment by SpaceIm** [comment]
local cache of your CI is corrupted, there is no `apply_conandata_patches(self)` as shown in your log in latest RREV of libjpeg-turbo.

**Comment by victor1234** [comment]
> local cache of your CI is corrupted, there is no `apply_conandata_patches(self)` as shown in your log in latest RREV of libjpeg-turbo.

Yes
