### ISSUE TITLE
[package] libfdk_aac/2.0.2: latest recipe builds with static CRT on msvc

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#15808]
### Description

Copy-pasted from my comment on PR #15350 ... and then more info added.

@SpaceIm - this PR #15350 has changed what CRT the static lib links to on Windows MSVC

* I built before and after on Windows, DOS environment, MSVC compiler.
* I checked dumpbin -symbols fdk-aac.lib for both
* PREVIOUS has symbol: calloc
* NEW has symbol __imp_calloc

The previous build also printed out a lot of "ignoring unknown option '/dynamic'" lines, so I assume the linker call also had /dynamic in the previous build, but not in the new build.

-----

I diff'd the before and after build folders...

CMakeCache.txt
* Previous has an extra `/MD` added to `CMAKE_CXX_FLAGS_RELEASE` (and others)
```
 //Flags used by the CXX compiler during RELEASE builds.
-CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
+CMAKE_CXX_FLAGS_RELEASE:STRING=/O2 /Ob2 /DNDEBUG
```

Out of interest, here is a selection of other lines that the new CMakeCache.txt was missing compared to the previous version (perhaps these are in the toolchain file? or changed to other things):
```
-//No help, variable specified on the command line.
-CMAKE_EXPORT_NO_PACKAGE_REGISTRY:UNINITIALIZED=ON

.... some lines further down ....

-//No help, variable specified on the command line.
-CONAN_CMAKE_CXX_EXTENSIONS:UNINITIALIZED=OFF
-
-//No help, variable specified on the command line.
-CONAN_CMAKE_CXX_STANDARD:UNINITIALIZED=20
-
-//No help, variable specified on the command line.
-CONAN_COMPILER:UNINITIALIZED=msvc
-
-//No help, variable specified on the command line.
-CONAN_COMPILER_VERSION:UNINITIALIZED=193
-
-//No help, variable specified on the command line.
-CONAN_EXPORTED:UNINITIALIZED=1
-
-//No help, variable specified on the command line.
-CONAN_IN_LOCAL_CACHE:UNINITIALIZED=ON
-
-//No help, variable specified on the command line.
-CONAN_LINK_RUNTIME:UNINITIALIZED=/dynamic
-
-//No help, variable specified on the command line.
-CONAN_STD_CXX_FLAG:UNINITIALIZED=/std:c++20
```

I wonder where this key line was transformed into in the new version? `-CONAN_LINK_RUNTIME:UNINITIALIZED=/dynamic`

### Package and Environment Details

Windows
Conan 1.58.0

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows
os_build=Windows

### Steps to reproduce

conan create . libfdk_aac/2.0.2@paul/test2

### Logs

No log for now.

**Comment by SpaceIm** [comment]
```
PREVIOUS has symbol: calloc
NEW has symbol __imp_calloc
```

Previous was wrong (calloc means that is was linked to static CRT while __imp_calloc is dynamic one) since legacy cmake generator doesn't properly support the new `compiler=msvc` (and specially it doesn't honor its runtime from profile). CMakeToolchain honors runtime of both legacy Visual Studio and new msvc profiles.

**Comment by paulharris** [comment]
hrm.  Something has changed ...
On my windows, I can't build the current ffmpeg recipe.
It will find and link to fdk-aac.lib (with complains about the runtime)... and then fails to find and link to libmp3lame.
but with the new libfdk_aac recipe, it can't find and link fdk-aac.lib.
I don't understand why ...

**Comment by SpaceIm** [comment]
You are trying to build ffmpeg with the new `compiler=msvc` in profile while its recipe still relies on legacy `AutotoolsBuildEnvironment`, which doesn't properly support this profile. As I said conan maintainers have decided to not provide forward compatibility in legacy generators against this new settings for Visual Studio. So obviously you have a mess of runtime inconsistencies.

**Comment by paulharris** [comment]
Ok thanks @SpaceIm, I am trying to use msvc and push forward into conan v2, I didn't recognise that this was an msvc-profile issue, that explains things...

**Comment by SpaceIm** [comment]
I'll submit a PR to migrate ffmpeg to AutotoolsToolchain

**Comment by paulharris** [comment]
I'm having a go now.  I'll push what I have in maybe 30 mins, feel free to discard and work from scratch.  I'm starting from Martin's.

**Comment by paulharris** [comment]
Please see #15818
