### ISSUE TITLE
[service] Build packages for Clang 10

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#1580]
Now where https://github.com/conan-io/conan-docker-tools/pull/193 is merged, the service should generate packages for Clang 10.

If added, the wiki should be updated as well: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Comment by mathbunnyru** [comment]
Friendly ping.

Could you please tell what has to be done, to build packages for clang-10?
Maybe github users (including myself) could help with that?

**Comment by uilianries** [comment]
It requires internal update in CCI service. We already have a Docker image with Clang 10: https://github.com/conan-io/conan-docker-tools/blob/37eb4f2f140dddf21992fb99013a1c3df91da61b/clang_10/Dockerfile. It will happen but not soon I think.

**Comment by uilianries** [comment]
The main problem: we will need to build all packages, but respecting their dependencies tree, and using parallel jobs (which is faster) will result more than one package requesting for a third package, but is not ready yet. The solution is a job which will cover those dependencies, not only for a new compiler, but also for regular days, when for some reason, we lose a package from CCI.

**Comment by mathbunnyru** [comment]
Oh, wow, I didn't think about it. Thank you for the explanation.

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/4636

Thanks!
