### ISSUE TITLE
[question] How to pass CMake variable to a package in configure step?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan-center-index#15812]
### What is your question?

For example, opencv (with_cuda) version need to get CUDA location, one solution is to set CUDAToolkit_PATH or set CUDA_BIN_PATH, but I don't want to set variable manually but set this in conanfile, lik
```
def configure(self)：
    self.options["opencv"].CUDAToolkit = xxx
```
Can it be achieved?

**Comment by samuel-emrys** [comment]
Yes, this is possible with this exact syntax. The only question is whether the recipe supports what you want to do. I can't see a `CUDAToolkit` option on the recipe - the closest i see is `with_cuda`, which sets the CMake variable `WITH_CUDA`: https://github.com/conan-io/conan-center-index/blob/master/recipes/opencv/4.x/conanfile.py#L43

If this isn't what you're after, you'd need to request or submit a PR with the necessary changes to the recipe to allow this option to be set.
