### ISSUE TITLE
[question] Patches: exports_sources and in conanmanifest.txt but cannot download

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#1581]
I would like to download the patches for a given recipe. 

```
$ conan get boost/1.72.0 conanmanifest.txt
1587637618
conandata.yml: 7e0f1dc49a536a16096dcc45024e0095
conanfile.py: e501fec10af9b8c101504791cc27eda3
export_source/patches/0001-beast-fix-moved-from-executor.patch: e975a68726f7a7ce04c7260da7ff25af
export_source/patches/0001-revert-cease-dependence-on-range.patch: 37084e013c02b27d54281e6d16526284
export_source/patches/bcp_namespace_issues_1_70.patch: 31ae02ec50c32c96a16830f736482f3b
export_source/patches/bcp_namespace_issues_1_71.patch: a166a71b0038da9af53679706b471814
export_source/patches/bcp_namespace_issues_1_72.patch: febd145cb9fa48920fbd7177fcd04e33
export_source/patches/boost_build_asmflags.patch: 22554bcd543d6c4cc661b399427c8d32
export_source/patches/boost_build_qcc_fix_debug_build_parameter.patch: 9f8bc5f88dd2098905fa4502d60f2144
export_source/patches/boost_core_qnx_cxx_provide___cxa_get_globals.patch: 22753ece63845c7ac1cee6b34816cb52
export_source/patches/boost_log_filesystem_no_deprecated_1_72.patch: 423ce6c9b31f9699352fae8cd3da88fb
export_source/patches/python_base_prefix.patch: d8cfed887ffa9841aaa60de954b904a9
export_source/patches/solaris_pthread_data.patch: f2e595438f18d0dcbbb184cdd47415ee
export_source/patches/static_object_init.patch: bd2c8dd59b5bbb7448d5616c0dc618e3
export_source/patches/support_msvc_2019.patch: 041d4c099d252e3f1c863764c8638d77
```

Which clearly lists all the various patches. But for arguments sake lets try the conandata file!

```
$ conan get boost/1.72.0 conandata.yml
patches:
  1.72.0:
  - base_path: boost_1_72_0
    patch_file: patches/bcp_namespace_issues_1_72.patch
  - base_path: boost_1_72_0
    patch_file: patches/boost_build_qcc_fix_debug_build_parameter.patch
  - base_path: boost_1_72_0
    patch_file: patches/boost_core_qnx_cxx_provide___cxa_get_globals.patch
  - base_path: boost_1_72_0
    patch_file: patches/python_base_prefix.patch
  - base_path: boost_1_72_0
    patch_file: patches/solaris_pthread_data.patch
  - base_path: boost_1_72_0
    patch_file: patches/0001-revert-cease-dependence-on-range.patch
  - base_path: boost_1_72_0
    patch_file: patches/boost_log_filesystem_no_deprecated_1_72.patch
sources:
  1.72.0:
    sha256: 59c9b274bc451cf91a9ba1dd2c7fdcaf5d60b1b3aa83f2c9fa143417cc660722
    url: https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
```

Firstly, I am shocked this does not contain all the data, the other versions are missing! Than I was wondering why **all** the patches are exported.

But regardless, it works as anticipated.

So trying the very last patch in the manifest

```
$ conan get boost/1.72.0 export_source/patches/support_msvc_2019.patch
ERROR: The specified path doesn't exist
```

When I look in my `.conan/data` there's no export_source folder (whereas with some old bincrafters the folder is there after install)

<hr/>

Is it possible to use the conan api to get patches or the cmake wrapper?

**Comment by jgsogo** [comment]
Hi! Files in the `export_sources` folder are retrieved only if Conan is going to build the library (you can check in the sources for something like `complete_recipe_sources`).

Right now I'm not aware of any command you could use to get the sources from a remote to the `export_sources` folder in the cache. I recommend you to open an issue in the Conan repo if this is something useful for you, it can be a feature request.

Thanks!

PS.- I would like to reduce the patches exported according to the information remaining in the `conandata.yml`, I'll think about it.

**Comment by prince-chrismc** [comment]
> Files in the `export_sources` folder are retrieved only if Conan is going to build the library

ahhh, that makes sense, limit the downloads for using packages is the best approach.

In the end there were too many other challenges with the approach I was looking at, so I changed directs with feedback from the Conan team

Since this is the expected behavoir, closed!
