### ISSUE TITLE
[question] Need help designing recipes for `googleapis` / `grpc-protos` / `grpc` and `google-cloud-cpp`.

### ISSUE THREAD

**Issue by coryan** [conan-io/conan-center-index#15823]
### What is your question?

I am a bit stumped by these errors in #15817, and I am beginning to wonder if (1) I don't understand something very important, or (2) the recipes related to `googleapis` need to be restructured.

It seems that the CI build will only compile `google-cloud-cpp/2.5.0` using existing pre-compiled binaries in conan center.  Fair enough.  It also seems that the existing binaries for `grpc-proto` and `grpc` are based on `googleapis/cci.20220711`:

> WARN: grpc/1.50.1: requirement googleapis/cci.20220711 overridden by google-cloud-cpp/2.5.0 to googleapis/cci.20221108 
> WARN: grpc-proto/cci.20220627: requirement googleapis/cci.20220711 overridden by grpc/1.50.1 to googleapis/cci.20221108 

That also seems fair.

But `google-cloud-cpp/2.5.0` really does require `googleapis/cci.20221108`.  It will not work with older versions.  It assumes the proto files contain RPC definitions that only become available in newer versions of `googleapis/cci.*`.

Should I update the requirements for `grpc-proto` and `grpc` before sending an update to `google-cloud-cpp`?

That would make maintenance rather tedious.  Each new release of `google-cloud-cpp` (they happen monthly) would require 4 PRs in sequence.

I understand the desire to "unvendor" packages. But it seems like the approach taken by conan center is overkill.  `grpc-protos` really uses a **single** proto file from `googleapis`:

https://github.com/grpc/grpc-proto/blob/6956c0ef3b8c21efb44992edc858fbae9414aa05/BUILD.bazel#L243

https://github.com/googleapis/googleapis/blob/334d2d9752be2f35fb80e31e1d37b27b74ed8973/google/rpc/BUILD.bazel#L9-L13

Outside comments, the contents of that file have not changed in years:

https://github.com/googleapis/googleapis/blame/master/google/rpc/code.proto

Nor are they likely to change.  That list of values is part of the protocol between RPC servers and clients, adding or removing a value would be massively breaking.

Should we consider a tiny library, say `googleapis-rpc-code-proto` that just unvendors the one proto file used by all these other packages?  Then `google-cloud-cpp` can continue to vendor in all the other protos.  

I am the upstream maintainer, I can change `google-cloud-cpp` to just support a small unvendoring like this.

Thoughts?

**Comment by coryan** [comment]
Without more information it seems that the way forward is to:

- Update `grpc-proto` to require the latest `googleapis`, and then 
- Update `grpc` to require the latest `googleapis`, and then
- Update `google-cloud-cpp` to use the latest `googleapis`.

I will prepare the PRs.

**Comment by jiaoew1991** [comment]
I have another question, all of them depend on protobuf/3.21.4, and the `build_requires` cannot be overwritten by conanfile.py, but my project depends on protobuf/3.21.4, how to solve the conflict 😅
