### ISSUE TITLE
[question] ERROR: boost/1.74.0: Cannot load recipe on pipeline

### ISSUE THREAD

**Issue by prashantwilson** [conan-io/conan-center-index#15979]
### What is your question?

Hello,
We are facing the below issue during build job on the pipeline:

boost/1.74.0: Downloaded recipe revision 0
ERROR: boost/1.74.0: Cannot load recipe.
Error loading conanfile at '/root/.conan/data/boost/1.74.0/_/_/export/conanfile.py': Unable to load conanfile in /root/.conan/data/boost/1.74.0/_/_/export/conanfile.py
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan/data/boost/1.74.0/_/_/export/conanfile.py", line 3, in <module>
    from conan.tools.apple import is_apple_os, to_apple_arch, XCRun
ImportError: cannot import name 'to_apple_arch' from 'conan.tools.apple' (/usr/local/lib/python3.10/dist-packages/conan/tools/apple/__init__.py)

Versions used on the pipeline runner image are as below:
Conan:1.51.3
Python3 version: Python 3.10.4
Ubuntu version: Ubuntu 22.04.1 LTS.

Any support to help in getting the above issue resolved would be great. Thank you for time in advance.

Thanks and regards,
Prashant

**Comment by SpaceIm** [comment]
latest RREV of boost recipe requires conan >= 1.53.0.

conan learned to fail gracefully in conan 1.52.0 when there is something like `required_conan_version = ">=1.53.0"` (like in boost recipe), but since you are still running conan 1.51.3, error message is not meaningful.
