### ISSUE TITLE
[conan.io/center] List of binary packages do not show all packages

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#1600]
In Mac, you are able to move the pointer to the list of packages and scroll down to show more packages. However, the scrolling is not working in Windows Chrome and you think that there are only 10 packages available in the screenshot below.

![image](https://user-images.githubusercontent.com/10808592/81566498-4086a000-939b-11ea-842e-fa714593ff7a.png)

This should be fixed and I think the scroll bar should be visible so it is more intuitive to search for more packages.

**Comment by Dattax** [comment]
Thanks - we'll look into this.

**Comment by ankushchadha** [comment]
This should be fixed now. @danimtb can you check again?

**Comment by danimtb** [comment]
yes, it is working now! thank you
