### ISSUE TITLE
libbacktrace/cci.20210118: ERROR: Package '2035f2979c51f092f64bdbe7d89c66d96dabffd9' build failed

### ISSUE THREAD

**Issue by prashantwilson** [conan-io/conan-center-index#16007]
### What is your question?

Hello,
We are having the below issue during build job for QNX target on the pipeline:

checking whether we are cross compiling... configure: error: in `/root/.conan/data/libbacktrace/cci.20210118/_/_/build/2035f2979c51f092f64bdbe7d89c66d96dabffd9/build-release':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
libbacktrace/cci.20210118: 
WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
ms-gsl/4.0.0: WARN: ms-gsl/4.0.0 requires C++14. Your compiler is unknown. Assuming it supports C++{self._minimum_cpp_standard}.
bzip2/1.0.8: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
libbacktrace/cci.20210118: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
libbacktrace/cci.20210118: ERROR: Package '2035f2979c51f092f64bdbe7d89c66d96dabffd9' build failed
libbacktrace/cci.20210118: WARN: Build folder /root/.conan/data/libbacktrace/cci.20210118/_/_/build/2035f2979c51f092f64bdbe7d89c66d96dabffd9/build-release
ERROR: libbacktrace/cci.20210118: Error in build() method, line 93
	autotools.configure()
	ConanException: Error 1 while executing "/root/.conan/data/libbacktrace/cci.20210118/_/_/build/2035f2979c51f092f64bdbe7d89c66d96dabffd9/src/configure" '--disable-shared' '--enable-static' '--prefix=/' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' 
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1

Versions used on the pipeline runner image are as below:
Conan:1.56.0
Python3 version: Python 3.8.10
Ubuntu version: Ubuntu 20.04.5 LTS
 
Configuration: 
arch=armv8
arch_build=x86_64
os=Neutrino
os.version=7.0

Any support to help in getting the above issue resolved would be great. Thank you for time in advance.

Thanks and regards,
Prashant

**Comment by jcar87** [comment]
Hi @prashantwilson, thanks for reporting this. Do you have the ability to test the package creation locally? Unfortunately we don't have a QNX toolchain to test. 

Would you able to provide us with: 
* the `config.log` inside the build folder, this should point us in the right direction
* the full log of running configure (anything that appears before the error)
* the full Conan profile, and if the environment variables to build for QNX are not defined there, whether this is defined in Docker or someplace else


I have a suspicion that what's happening is that if the default compiler is qcc, but the `./configure` doesn't know it is cross-building, it will try to run a test executable during the configuration phase, and fail (and it will fail with a non-intuitive error of not being able to find the dynamic linker). 
My advise would be to try using two profiles for the build:
```
conan install libbacktrace/cci.20210118@ --build missing --profile:host your-qnx-profile --profile:build a-linux-x86-profile`
```

**Comment by prashantwilson** [comment]
> Hi @prashantwilson, thanks for reporting this. Do you have the ability to test the package creation locally? Unfortunately we don't have a QNX toolchain to test.
> 
> Would you able to provide us with:
> 
> * the `config.log` inside the build folder, this should point us in the right direction
> * the full log of running configure (anything that appears before the error)
> * the full Conan profile, and if the environment variables to build for QNX are not defined there, whether this is defined in Docker or someplace else
> 
> I have a suspicion that what's happening is that if the default compiler is qcc, but the `./configure` doesn't know it is cross-building, it will try to run a test executable during the configuration phase, and fail (and it will fail with a non-intuitive error of not being able to find the dynamic linker). My advise would be to try using two profiles for the build:
> 
> ```
> conan install libbacktrace/cci.20210118@ --build missing --profile:host your-qnx-profile --profile:build a-linux-x86-profile`
> ```

Thank you for the quick response.

**Comment by FaiqueAli** [comment]
Hi I am trying to cross-compile from linux to qnx and i am getting the same error.
when I use the command 
> `conan install libbacktrace/cci.20210118@ --build missing --profile:host your-qnx-profile --profile:build a-linux-x86-profile`

I am getting unrecognized argument.
