### ISSUE TITLE
[package] boost/1.81.0: Header only boost depending on libbacktrace

### ISSUE THREAD

**Issue by daniel-heater-imprivata** [conan-io/conan-center-index#16072]
### Description

I pull Conan packages from my local Artifactory instance with `--build=never` to control the packages available.

Previously, I was building my application using the boost Conan package with `boost:header_only=True` and that worked fine.  I rebuilt the boost package that I deploy to Artifactory yesterday and now I get an error:

```
ERROR: Failed requirement 'libbacktrace/cci.20210118' from 'boost/1.81.0'
ERROR: Unable to find 'libbacktrace/cci.20210118' in remotes
```

It looks like this [PR](https://github.com/conan-io/conan-center-index/pull/15840) introduced `libbracktrace` as a new dependency in the `boost:header_only` case. 

### Package and Environment Details

* Package Name/Version: **boost/1.81.0**
* Operating System+version: **Linux Centos 7**
* Compiler+version: **GCC 11**
* Conan version: **conan 1.57.0**
* Python version: **Python 3.8.13**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

scl enable devtoolset-11 "conan install boost/1.81.0@ -r artifactory"

### Logs

<details><summary>Click to expand log</summary>

```
boost/1.81.0: Not found in local cache, looking in remotes...
boost/1.81.0: Trying with 'sl-artifactory'...
Downloading conanmanifest.txt completed [0.35k]
Downloading conanfile.py completed [80.99k]
Downloading conan_export.tgz completed [1.38k]
Decompressing conan_export.tgz completed [0.00k]
boost/1.81.0: Downloaded recipe revision 8dcd9d9df9e0d320714b83cceddbe120
zlib/1.2.13: Not found in local cache, looking in remotes...
zlib/1.2.13: Trying with 'sl-artifactory'...
Downloading conanmanifest.txt completed [0.28k]
Downloading conanfile.py completed [4.04k]
Downloading conan_export.tgz completed [0.29k]
Decompressing conan_export.tgz completed [0.00k]
zlib/1.2.13: Downloaded recipe revision 13c96f538b52e1600c40b88994de240f
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'sl-artifactory'...
Downloading conanmanifest.txt completed [0.17k]
Downloading conanfile.py completed [4.09k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
bzip2/1.0.8: Downloaded recipe revision 23cc41191fd58460207c5db046033507
libbacktrace/cci.20210118: Not found in local cache, looking in remotes...
libbacktrace/cci.20210118: Trying with 'sl-artifactory'...
ERROR: Failed requirement 'libbacktrace/cci.20210118' from 'boost/1.81.0'
ERROR: Unable to find 'libbacktrace/cci.20210118' in remotes
```

</details>

**Comment by daniel-heater-imprivata** [comment]
I tried setting `boost:with_stacktrace_backtrace=False` as a temp workaround but that fails on Windows.

**Comment by SpaceIm** [comment]
libbacktrace is not a dependency of boost recipe when header_only is True, before or after PR you linked. Your local artifactory has an alternative version of boost recipe with some bug I would say, but for sure not any RREV of conan-center boost recipe.

**Comment by jcar87** [comment]
Hi @daniel-heater-imprivata, thanks for reporting this.

The Boost recipe in Conan center has `header_only` defaulted to `False` - running the command you have pasted `conan install boost/1.81.0@` would result in the library version of boost being pulled (including libbacktrace).

However, if I specify the option when running Conan install:
```
conan install boost/1.81.0@ -o boost:header_only=True
```

I get the header only version of boost which has no other dependencies.  You mention your application specifies `boost:header_only=True` - how does it achieve it? On the other hand, if you host a variant of the Conan Center recipes yourselves, any chance that the recipes were modified to override the default options? (Which is perfectly valid, but does require some care when bringing in upstream changes)

**Comment by daniel-heater-imprivata** [comment]
Yes. You are right. I omitted the `-o boost:header_only=True` option in my reproduction steps. Sorry!

I don't modify the Conan recipes. I just have a single job that pulls the latest recipes, builds with my set of options, and pushes them to Artifactory. All other jobs pull only from Artifactory.

But yes. I've been unable to reproduce with CCI, so its likely a problem on my side (cache?)

**Comment by daniel-heater-imprivata** [comment]
Added a step to clean the conan cache (`conan remove "*" -f`) before doing the build in CI. That fixed the problem.

Not sure why the cache would have anything since its building in a fresh Docker container every time and the container doesn't even have a `.conan/data` directory before I build??!! Also only occurs in CI and not when using the container locally?!   ¯\_(ツ)_/¯

Thanks for looking into it though!!
