### ISSUE TITLE
[package] qt/5.15.8: fails to build if dbus is enabled

### ISSUE THREAD

**Issue by mourogurt** [conan-io/conan-center-index#16084]
### Description

Qt 5.15.8 just fails to build on linux if dbus is needed.

### Package and Environment Details

* Package Name/Version: **qt/5.15.8**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **clang 14**
* Conan version: **conan 1.57.0**
* Python version: **Python 3.11.0**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=14
compiler.libcxx=libstdc++11
build_type=Release
cppstd=17
[options]
[build_requires]

[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++

### Steps to reproduce

conan install -r conancenter qt/5.15.8@ -pr clang14 -o qt:with_dbus=True -b missing

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: qt/5.15.8: Error in package_info() method, line 1060
        _create_module("Gui", gui_reqs)
while calling '_create_module', line 992
        self.cpp_info.components[componentname].requires = _get_corrected_reqs(requires)
while calling '_get_corrected_reqs', line 972
        assert corrected_req in self.cpp_info.components, f"{corrected_req} required but not yet present in self.cpp_info.components"
        AssertionError: qtDBus required but not yet present in self.cpp_info.components
```

</details>

**Comment by ericLemanissier** [comment]
Could you please try with https://github.com/conan-io/conan-center-index/pull/16086 ?

**Comment by mourogurt** [comment]
Yep, it worked out.

**Comment by tsondergaard** [comment]
Fixes the problem for me too.
