### ISSUE TITLE
[request] tensorflow-lite/2.11.0

### ISSUE THREAD

**Issue by vdsbenoit** [conan-io/conan-center-index#16192]
### Package Name/Version

tensorflow-lite/2.11.0

### Changelog

https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Could you add this version ? It contains security fixes.

**Comment by EstebanDugueperoux2** [comment]
@vdsbenoit as 2.12.0 is available in conan center, is this issue still relevant?

**Comment by czoido** [comment]
Thanks for reporting, closing this as newer versions are already available.
