### ISSUE TITLE
[package] ffmpeg/5.0: xlib dependency is not handled by the recipe

### ISSUE THREAD

**Issue by gergo-h** [conan-io/conan-center-index#16206]
### Description

From version 5.0+ the ./configure script of ffmpeg automatically finds libX11 and links to it if present without conan knowing about it. The corresponding enable-/disable-xlib flag is not being managed by conan which leads to the following problem: if the system on which the package was built had Xlib installed then the produced package will have an Xorg dependency that is also not managed.

Proposed solution:
There is an enable-/disable-xlib switch added in ffmpeg's build system that could be used to handle this dependency using a `with_xlib` option.

### Package and Environment Details

* Package Name/Version: ffmpeg/5.0
* Operating System+version: MacOS 14
* Compiler+version: Apple clang
* Docker image: ?
* Conan version: conan 1.58.0
* Python version: Python 3.11.1

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

1. brew install libX11 pkg-config
2. conan install -r conancenter -o ffmpeg:shared=True ffmpeg/5.0@
3. verify that the resulting .so links against Xlib

optional:
4. upload resulting package to a repo
5. download from repo on another system without Xlib installed and watch the package break

### Logs

[log.txt](https://github.com/conan-io/conan-center-index/files/10794052/log.txt)

**Comment by uilianries** [comment]
Issue addressed on the PR #24879. Please, feel free to test locally.
