### ISSUE TITLE
[request] mattiasgustavsson/libs

### ISSUE THREAD

**Issue by intelligide** [conan-io/conan-center-index#1622]
### Package Details
  * Package Name/Version: **???/???**
  * Source code: **https://github.com/mattiasgustavsson/libs**

### Description Of The Library / Tool

Single-file public domain libraries for C/C++

Required by #1544 

I don't know how I can name this recipe !!!

**Comment by Croydon** [comment]
In case of a too generic name we use the owner as a prefix, so it is going to be `mattiasgustavsson-libs`

Since the project makes no releases we use a date based versioning like `20200513`
