### ISSUE TITLE
[package] qt/5.x.x: Add support for conan 2.0

### ISSUE THREAD

**Issue by rainman110** [conan-io/conan-center-index#16249]
### Description

The conan qt5  package does not seem to be conan 2.0 ready. When trying to install it,  I get import errors (conans.tools).

See log below.

### Package and Environment Details

* Package Name/Version: **qt/5.15.8**
* Operating System+version: **Windows**
* Compiler+version: **msvc 2019**
* Docker image: **-**
* Conan version: **conan 2.0.0**
* Python version: **Python 3.9.16**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows

### Steps to reproduce

Note: `conan install package_reference` is not available in conan 2.0 anymore

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: Package 'qt/5.15.8' not resolved: qt/5.15.8: Cannot load recipe.
Error loading conanfile at 'C:\Users\XXXXX\.conan2\p\qtf43facf17546a\e\conanfile.py': Unable to load conanfile in C:\Users\XXXXX\.conan2\p\qtf43facf17546a\e\conanfile.py
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\XXXXX\.conan2\p\qtf43facf17546a\e\conanfile.py", line 8, in <module>
    from conans import tools, RunEnvironment
ImportError: cannot import name 'tools' from 'conans' (c:\local\miniforge3\lib\site-packages\conans\__init__.py)
```

</details>

**Comment by chen-tianjian** [comment]
Just FYI, A lot of other packages (e.g. cmake 3.24.0) will report the same error `cannot import name 'tools' from 'conans'` in Conan 2.0.
* Is there a quick way to solve this **locally** before the conan.io fixes all of the packages?
* Is there a quick way to check if a package/version is Conan 2.0 compatible?

**Comment by Croydon** [comment]
> Just FYI, A lot of other packages (e.g. cmake 3.24.0) will report the same error `cannot import name 'tools' from 'conans'` in Conan 2.0.
> 
>     * Is there a quick way to solve this **locally** before the conan.io fixes all of the packages?
> 
>     * Is there a quick way to check if a package/version is Conan 2.0 compatible?


Everyone can create pull requests, so feel free to help with migrations of recipes

For CMake the migration is done, but you have to update to a version that is currently supported by us. Either `3.24.3` or `3.25.2` at the time of writing https://github.com/conan-io/conan-center-index/blob/master/recipes/cmake/3.x.x/conandata.yml


> Is there a quick way to check if a package/version is Conan 2.0 compatible?

Not really. Quickest way is probably opening the recipe and having a look if it imports from `conans`

**Comment by rainman110** [comment]
@ericLemanissier I had a quick check on the recipe, whether I can upgrade it to conan 2.0. It is though pretty complex. 😏  Since you wrote this initially, could you please have a check, whether this package can be ported to 2.0?

In particular, the class `qt` derived from generator puzzles me. What is it used for and how can we resolve the now missing Generator class?

**Comment by ericLemanissier** [comment]
I see no reason that would make the recipe not portable to conan 2. The qt generator is responsible to create this file https://doc.qt.io/qt-6/qt-conf.html. as a first porting step I guess it could be simply removed. Cmake consumers won't be affected. If we find out qt.conf is actually still needed, we could integrate the generator in conan itself.
I won't have time for qt recipe in the coming weeks, so please don't hesitate to try the porting, and ask me if you need help on specific issues

**Comment by rainman110** [comment]
>The qt generator is responsible to create this file https://doc.qt.io/qt-6/qt-conf.html. as a first porting step I guess it could be simply removed. Cmake consumers won't be affected. If we find out qt.conf is actually still needed, we could integrate the generator in conan itself.

Thanks for the explanation. I am gonna try to port it.  Maybe we can avoid the creation of qt.conf. Where in the recipe is the qt generator actually used?

**Comment by rainman110** [comment]
Some problems here. After small tweaks to the conanfile.py , I get an Assertion in conan itself:

```
(base) C:\src\conan-center-index\recipes\qt\5.x.x>conan create  . --version 5.15.8 --build=missing

======== Exporting recipe to the cache ========
qt/5.15.8: Exporting package recipe: C:\src\conan-center-index\recipes\qt\5.x.x\conanfile.py
qt/5.15.8: exports: File 'conandata.yml' found. Exporting it...
qt/5.15.8: Calling export()
qt/5.15.8: Calling export_sources()
qt/5.15.8: Copied 1 '.yml' file: conandata.yml
qt/5.15.8: Copied 1 '.py' file: conanfile.py
qt/5.15.8: Copied 1 '.conf' file: qtmodules5.15.8.conf
qt/5.15.8: Copied 4 '.patch' files: 0001-Find-fontconfig-using-pkg-config.patch, 337f28c9ab-5.15.8.patch, chromium-skia-missing-iterator-include.patch, chromium-v8-missing-constexpr.patch
qt/5.15.8: Copied 4 '.diff' files: aa2a39dea5.diff, c72097e.diff, fix-macdeployqt.diff, skia-cd397f3.diff
qt/5.15.8: Exported to cache folder: C:\Users\XXXX\.conan2\p\qt5dfeb7d0d7016\e
qt/5.15.8: Exported: qt/5.15.8#de4534c1b01115d1b17983bdbd4755da (2023-02-27 10:35:02 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows


======== Computing dependency graph ========
Graph root
    cli
Requirements
    brotli/1.0.9#ffbecf553112bc3e25a08c91c28b8b68 - Cache
    bzip2/1.0.8#23cc41191fd58460207c5db046033507 - Cache
    double-conversion/3.2.1#0e6c00f6a48471b4b13163f01bd6bbb2 - Cache
    freetype/2.12.1#98d8601ae19d2aa9d640ea0ba358534f - Cache
    libjpeg/9e#68269859e4325ddc3f995d1fd3fc9187 - Cache
    libpng/1.6.39#deca555b0890e584fc895ba756e83c06 - Cache
    libpq/14.5#76d5e0452fcfa19f8f7ed250bcd7a525 - Cache
    md4c/0.4.8#6724c3bee6da8d4d9a17d16d35756e9a - Cache
    opengl/system#7c9316636990f3f64a7a6f6b24e0718f - Cache
    openssl/1.1.1s#5449870f797dec26045f2765d6fc7b5a - Cache
    pcre2/10.40#58467e19b38a61f5c3f065006fb684f6 - Cache
    qt/5.15.8#de4534c1b01115d1b17983bdbd4755da - Cache
    sqlite3/3.39.4#d69fe4efe5e21fb8a1ce472e5d09cf5e - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Cache
    zstd/1.5.2#06005e955668e51adf7f86f60785309a - Cache
Build requirements
    jom/1.1.3#e50a5f5e4115f259eb6d1f87d10af85f - Cache
    nasm/2.15.05#799d63b1672a337584b09635b0f22fc1 - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache

======== Computing necessary packages ========
double-conversion/3.2.1: Checking 2 compatible configurations:
double-conversion/3.2.1: 'dfa8c31b225ffb8dfcf6a48ffd071f448777ae71': compiler.cppstd=17
double-conversion/3.2.1: '88783055ab9f2e8198b56fdcaf04496aaa3d4a9b': compiler.cppstd=20
jom/1.1.3: Compatible package ID 522dcea5982a3f8a5b624c16477e47195da2f84f equal to the default package ID
strawberryperl/5.32.1.1: Compatible package ID 522dcea5982a3f8a5b624c16477e47195da2f84f equal to the default package ID
Traceback (most recent call last):
  File "c:\local\miniforge3\lib\site-packages\conan\cli\cli.py", line 264, in main
    cli.run(args)
  File "c:\local\miniforge3\lib\site-packages\conan\cli\cli.py", line 167, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "c:\local\miniforge3\lib\site-packages\conan\cli\command.py", line 130, in run
    info = self._method(conan_api, parser, *args)
  File "c:\local\miniforge3\lib\site-packages\conan\cli\commands\create.py", line 77, in create
    conan_api.graph.analyze_binaries(deps_graph, build_modes, remotes=remotes,
  File "c:\local\miniforge3\lib\site-packages\conan\api\subapi\graph.py", line 190, in analyze_binaries
    binaries_analyzer.evaluate_graph(graph, build_mode, lockfile, remotes, update)
  File "c:\local\miniforge3\lib\site-packages\conans\client\graph\graph_binaries.py", line 324, in evaluate_graph
    self._evaluate_package_id(node)
  File "c:\local\miniforge3\lib\site-packages\conans\client\graph\graph_binaries.py", line 292, in _evaluate_package_id
    compute_package_id(node, self._cache.new_config)  # TODO: revise compute_package_id()
  File "c:\local\miniforge3\lib\site-packages\conans\client\graph\compute_pid.py", line 44, in compute_package_id
    options=conanfile.options.copy_conaninfo_options(),
  File "c:\local\miniforge3\lib\site-packages\conans\model\options.py", line 341, in copy_conaninfo_options
    assert not self._deps_package_options
AssertionError

ERROR:
```

**Comment by ericLemanissier** [comment]
It looks like so. Could you please publish your recipe on a git repo, so that the problem can be replicated on https://eirikb.github.io/proof-of-conan/, and possibly report it on https://github.com/conan-io/conan afterwards ?

**Comment by rainman110** [comment]
I pushed the qt5 package to https://github.com/rainman110/conan-qt5.

I tried to run proof-of-conan, but failed due to an error "Unable to find any artifacts for the associated workflow":
https://github.com/eirikb/proof-of-conan/actions/runs/4282191957

I set up the path `5.x.x` on the main branch. I don't know, what I have done incorrectly

**Comment by rainman110** [comment]
Here' s the link to the conan issue: https://github.com/conan-io/conan/issues/13256

**Comment by ericLemanissier** [comment]
well, proof-of-conan is currently broken, since conan 2 upgrade. I proposed some fixes in https://github.com/eirikb/proof-of-conan/pull/30
FYI, you need to enter https://github.com/rainman110/conan-qt5/tree/masteras URL, then manually update branch to `master`, package to `qt`, and pathto package to `.`
This is because your repo does not have the same structure as CCI.

**Comment by rainman110** [comment]
Done. I moved branch "main" to "master". One step further 😄 

Now, the build seem to miss a build profile though. I think this is what you meant
