### ISSUE TITLE
[qt] QT/6.4.2: Package does not include Quick or QuickWidgets

### ISSUE THREAD

**Issue by zethon** [conan-io/conan-center-index#16301]
### Description

Using conan to build an application that uses Qt 6.4.2, the component QuickWidget is not found on Windows. This works fine on Mac.

### Package and Environment Details

* Package Name/Version: **qt/6.4.2**
* Operating System+version: **Windows 10**
* Compiler+version: **Visual Studio 17 2022**
* Conan version: **conan 1.58.0**
* Python version: **Python 3.11**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

I am using the Conan CMake script, like so: 

```
    include(CMake/conan.cmake)
    conan_cmake_configure(
        REQUIRES
            openssl/1.1.1t
            qt/6.4.2
        GENERATORS
            cmake_find_package
            cmake_paths
        OPTIONS
            qt:shared=True
    )

    conan_cmake_autodetect(settings)

    conan_cmake_install(PATH_OR_REFERENCE .
        BUILD
            missing
        REMOTE
            conancenter
        SETTINGS
            ${settings}
    )
```

And then in my CMake script I am using: 
```
find_package(Qt6 REQUIRED COMPONENTS 
    Core 
    Gui 
    Widgets 
    QuickWidgets
)
```

The actual code can be viewed here: https://github.com/lulzapps/CuteOwl/tree/dev

### Logs

<details><summary>Building gives this error</summary>

```
-- Conan: Using autogenerated FindQt6.cmake
-- Conan: Component 'Core' found in package 'Qt6'
-- Conan: Component 'Gui' found in package 'Qt6'
-- Conan: Component 'Widgets' found in package 'Qt6'
CMake Error at bin.relwithdebinfo/FindQt6.cmake:6 (message):
  Conan: Component 'QuickWidgets' NOT found in package 'Qt6'
Call Stack (most recent call first):
  bin.relwithdebinfo/FindQt6.cmake:91 (conan_message)
  src/CuteOwl/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!
```

</details>

**Comment by zethon** [comment]
I also tried adding `qt:qtshadertools=True` per [this issue](https://github.com/conan-io/conan-center-index/issues/9092), but it did not work.

**Comment by zethon** [comment]
Doh! It wasn't immediate obvious but I needed to add `qt:qtdeclarative=True`

I'm updating this issue for anyone who might run into a similar problem. 

Anyone know why Mac doesn't require that?

**Comment by senhypevr** [comment]
Thanks @zethon ! You saved my day!
