### ISSUE TITLE
[ninja] ninja/1.11.1:  `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan-center-index#16314]
### Description

Hello conan community,
today I test conan 2.0.0 with a simple project on my Redhat 8 and I get following error:

```
   /xusers/ed103615/.conan2/p/ninja9152e907f8c1a/p/bin/ninja: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /xusers/ed103615/.conan2/p/ninja9152e907f8c1a/p/bin/ninja)
```

When executing "strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX" on my Redhat 8, the latest symbol is GLIBCXX_3.4.25 but when checking on Docker conan official images:

- conanio/gcc8-ubuntu16.04 => GLIBCXX_3.4.21
- conanio/gcc8-ubuntu18.04 => GLIBCXX_3.4.25

The ninja binary fetched seems built on a more recent system.
I reproduce this issue also on conanio/gcc8-ubuntu18.04.

This is due to current conan center CI in service maintenance?

Regards.

### Package and Environment Details

* Package Name/Version: **ninja/1.11.1**
* Operating System+version: **Redhat 8,**
* Compiler+version: **GCC 8**
* Docker image: **conanio/gcc8-ubuntu18.04**
* Conan version: **conan 1.59.0**
* Python version: **Python 3.7.4**

### Conan profile

[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release

### Steps to reproduce

docker run --rm -ti -v ${PWD}:/home/conan/project conanio/gcc8-ubuntu18.04
cd project

conan create . --profile:build .conan/profiles/gcc8 --profile:host .conan/profiles/gcc8 --build missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

### Logs

<details><summary>Click to expand log</summary>

```
   /xusers/ed103615/.conan2/p/ninja9152e907f8c1a/p/bin/ninja: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /xusers/ed103615/.conan2/p/ninja9152e907f8c1a/p/bin/ninja)
```

</details>

**Comment by tbsuht** [comment]
See this issue, where `libsystemd` is also affected: https://github.com/conan-io/conan-center-index/issues/16744
