### ISSUE TITLE
[package] zlib/1.2.11: Cannot load recipe.

### ISSUE THREAD

**Issue by ShenMian** [conan-io/conan-center-index#16324]
### Description

Try running the example: <https://github.com/conan-io/examples2/tree/main/tutorial/consuming_packages/simple_cmake_project>.  

After conan was updated to 2.0, I found that the packages installed with conan had similar problems, and then tried to run the example, and found that the same problem also existed.  

### Package and Environment Details

* Package Name/Version: **zlib/1.2.11**
* Operating System+version: **6.1.12-1-MANJARO**
* Compiler+version: **clang 15.0.7**
* Conan version: **conan 2.0.0**
* Python version: **Python 3.10.9**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=12
os=Linux

### Steps to reproduce

https://github.com/conan-io/examples2/blob/83a1cd20b15fe300def44376646c6ece1cb4462e/tutorial/consuming_packages/simple_cmake_project/run_example.sh

conan install . --output-folder=build --build=missing

### Logs

<details><summary>Click to expand log</summary>

```
++ dirname ./run_example.sh
+ BASEDIR=.
+ pushd .
~/Repos/examples2/tutorial/consuming_packages/simple_cmake_project ~/Repos/examples2/tutorial/consuming_packages/simple_cmake_project
+ rm -rf build
+ conan install . --output-folder=build --build=missing

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=12
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=12
os=Linux


======== Computing dependency graph ========
Graph root
    conanfile.txt: /home/sms/Repos/examples2/tutorial/consuming_packages/simple_cmake_project/conanfile.txt
*********************************************************
Recipe 'zlib/1.2.11' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check it is updated to 2.0
*********************************************************

ERROR: Package 'zlib/1.2.11' not resolved: zlib/1.2.11: Cannot load recipe.
Error loading conanfile at '/home/sms/.conan2/p/zlib774aa77541f8b/e/conanfile.py': /home/sms/.conan2/p/zlib774aa77541f8b/e/conanfile.py not found!
```

</details>

**Comment by StellaSmith** [comment]
Your local cache might be corrupted, try `rm -r ~/.conan2/{.conan.db,p}`

**Comment by ShenMian** [comment]
> Your local cache might be corrupted, try `rm -r ~/.conan2/{.conan.db,p}`

After executing the command, conan still gives the same error output.

**Comment by SpaceIm** [comment]
`conan install --require=zlib/1.2.11 -b missing` works fine for me. There is something wrong on your side.

**Comment by ShenMian** [comment]
I don't remember what I did, but now my conan can install the package normally and show "Install finished succesfully". 
Thank you for your help
