### ISSUE TITLE
[package] qt/6.4.2: conan create fails with qt/6.4.2:shared=True and qt/6.4.2:qtdeclarative=True on linux

### ISSUE THREAD

**Issue by pratman** [conan-io/conan-center-index#16327]
### Description
When calling conan create on a project "my_project" on linux (works on windows) I'm getting the error:

```
...
expat/2.5.0:3242ee86fec793e7767fb97cb42848d950351d05 - Cache
...
expat/2.5.0: Already installed!
...
my_project/0.0.3: Generator cmake_find_package created FindEXPAT.cmake
...
-- Dependency EXPAT already found
...
...
CMake Error at CMakeLists.txt:28 (add_library):
  Target "my_project" links to target "EXPAT::EXPAT" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
...
```
### Package and Environment Details
Package Name/Version: qt/6.4.3 (and others as well)
Operating System+version: Linux Ubuntu 22.04.1
Compiler+version: gcc 11
Conan version: 1.58.0
Python version: Python 3.10.6
Conan profile
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-11
CXX=/usr/bin/g++-11
[conf]
tools.system.package_manager:mode=install

### Recipe
```
from conan import ConanFile
from conan.tools.cmake import CMake

class my_project(ConanFile):
    settings = "os", "compiler", "build_type", "arch"

    requires = "doctest/2.4.9", "spdlog/1.11.0", "qt/6.4.2" 

    options = {"shared": [True, False]}
    default_options = {"shared": True, "qt/*:shared": True, "qt/*:qtdeclarative": True,"spdlog/*:shared": True}

    generators = "CMakeToolchain", "cmake_find_package"

    exports_sources = "CMakeLists.txt", "CMakePresets.json", "src/*", "include/*", "test/*", "res/*"


    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["my_project"]
```

### Steps to reproduce
conan create . --profile linux_x64_debug.txt

**Comment by ericLemanissier** [comment]
`cmake_find_package` generator is now legacy. Please migrate to [CMakeDeps](https://docs.conan.io/en/1.46/reference/conanfile/tools/cmake/cmakedeps.html), and tell us if the problem persists

**Comment by SpaceIm** [comment]
Yep, don't mixup CMakeToolchain & cmake_find_package.
Due to CMAKE_FIND_PACKAGE_PREFER_CONFIG ON in conan_toolchain.cmake, it can lead to pernicious issues.

I guess that expat-config.cmake has been found in a system location of your Linux distro, instead of FindEXPAT.cmake from cmake_find_package, and target from expat config file is expat::expat instead of EXPAT::EXPAT in official Find file, something which couldn't happen with CMakeDeps.

**Comment by pratman** [comment]
Thanks! I will give it a try and close it if it solved the issue.
