### ISSUE TITLE
[package] flatbuffers/2.0.6: 'self.options' access in 'package_id()' method is forbidden

### ISSUE THREAD

**Issue by zerom0** [conan-io/conan-center-index#16406]
### Description

I wanted to build flatbuffers using conan v2 which failed with the following error

```
ERROR: flatbuffers/2.0.6: Error in package_id() method, line 67
        if self.options.header_only and not self._has_flatc:
        ConanException: 'self.options' access in 'package_id()' method is forbidden
```

### Package and Environment Details

* Package Name/Version: **flatbuffers/2.0.6**
* Operating System+version: **macOS Ventura 13.2.1**
* Compiler+version: **Apple clang version 14.0.0 (clang-1400.0.29.202)**
* Conan version: **conan 2.0.0**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=14
os=Macos

### Steps to reproduce

conan install . --build=missing --settings=build_type=Debug --output-folder=conan/mac-x64-debug

### Logs

<details><summary>Click to expand log</summary>

```
% conan install . --build=missing --settings=build_type=Debug --output-folder=conan/mac-x64-debug

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=14
os=Macos

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=14
os=Macos


======== Computing dependency graph ========
flatbuffers/2.0.6: Not found in local cache, looking in remotes...
flatbuffers/2.0.6: Checking remote: conancenter
Decompressing conan_export.tgz
flatbuffers/2.0.6: Downloaded recipe revision 8051082b510bfb01d65c6504a1c168ec
Graph root
...
Requirements
...

======== Computing necessary packages ========
ERROR: flatbuffers/2.0.6: Error in package_id() method, line 67
        if self.options.header_only and not self._has_flatc:
        ConanException: 'self.options' access in 'package_id()' method is forbidden
```

</details>

**Comment by SpaceIm** [comment]
Yes, https://github.com/conan-io/conan-center-index/pull/16269 will fix that, but c3i has been under maintenance for 2 weeks, so not merged yet.
