### ISSUE TITLE
[request] simple-websocket-server/2.0.2

### ISSUE THREAD

**Issue by SchneiderROS** [conan-io/conan-center-index#16428]
### Package Name/Version

simple-websocket-server/2.0.2

### Webpage

https://gitlab.com/eidheim/Simple-WebSocket-Server

### Source code

https://gitlab.com/eidheim/Simple-WebSocket-Server

### Description of the library/tool

The library was already in the usable with conan 1.X, but not with 2.X

**Comment by perseoGI** [comment]
Hi there, 
We appreciate your request.

I'm closing this issue as this version is already in CCI:
See https://conan.io/center/recipes/simple-websocket-server?version=2.0.2

Happy coding! 🐸
