### ISSUE TITLE
[service] Conan v2 pipeline missing prebuilt package for 'libcurl/7.84.0'

### ISSUE THREAD

**Issue by FaerHack** [conan-io/conan-center-index#16449]
### What is your problem/feature request?
Conan v2 pipeline missing prebuilt package for 'libcurl/7.84.0'
Logs: https://c3i.jfrog.io/c3i/misc-v2/logs/pr/16336/7-linux-gcc/tgbot/1.2.1//a59834da9f90ce440805c9d4eac4899423d4f7f7-build.txt

**Comment by SpaceIm** [comment]
Why don't you bump libcurl in tgbot recipe? CCI recipes must not get stuck to old versions of their dependencies, otherwise it leads to versions conflicts.
