### ISSUE TITLE
[package] nas/1.9.5: Build failure on ARM linux

### ISSUE THREAD

**Issue by dariusarnold** [conan-io/conan-center-index#16490]
### Description

Configuring the package nas/1.9.5 fails on ARM linux due to an old config.guess version. The error from `conan install nas/1.9.5@` is attached. I am building ARM64 binaries on ARM64, no cross compiling involved.

I used the fix suggested by [this blog post](https://blog.conan.io/2021/09/21/m1.html) which consists of copying a current version of the config.guess and config.guess file to overwrite the old versions. After that the recipe works. 

I would like to contribute the fix as a pull request and would welcome any advice. For now I updated both files irrespective of the actual systems architecture, since I can't think of any ill effects. If there are any objections, I can change it.

### Package and Environment Details

* Package Name/Version: **nas/1.95.0**
* Operating System+version: **Linux Ubuntu 22.04.1 LTS**
* Compiler+version: **gcc 11**
* Conan version: **conan 1.59.0**
* Python version: **Python 3.10.6**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=armv8
arch_build=armv8
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

Execute `conan install nas/1.9.5@ --build=missing` on system with ARM architecture

### Logs

<details><summary>Click to expand log</summary>

```
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2005-08-03, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2005-08-03

uname -m = aarch64
uname -r = 5.15.0-1029-oracle
uname -s = Linux
uname -v = #35-Ubuntu SMP Tue Jan 24 15:21:05 UTC 2023

/usr/bin/uname -p = aarch64
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = aarch64
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 5.15.0-1029-oracle
UNAME_SYSTEM  = Linux
UNAME_VERSION = #35-Ubuntu SMP Tue Jan 24 15:21:05 UTC 2023
configure: error: cannot guess build type; you must specify one
make[2]: *** [Makefile:1062: config.h] Error 1
make[2]: Leaving directory '/home/ubuntu/.conan/data/nas/1.9.5/_/_/build/92da54bcd02b84dbdeb006b236462459a6160bee/src/config'
make[1]: *** [Makefile:1244: includes] Error 2
make[1]: Leaving directory '/home/ubuntu/.conan/data/nas/1.9.5/_/_/build/92da54bcd02b84dbdeb006b236462459a6160bee/src'
make: *** [Makefile:1081: World] Error 2
nas/1.9.5: 
nas/1.9.5: ERROR: Package '92da54bcd02b84dbdeb006b236462459a6160bee' build failed
nas/1.9.5: WARN: Build folder /home/ubuntu/.conan/data/nas/1.9.5/_/_/build/92da54bcd02b84dbdeb006b236462459a6160bee/build-release
ERROR: nas/1.9.5: Error in build() method, line 92
	autotools.make(target="World", args=["-j1"] + self._imake_make_args)
	ConanException: Error 2 while executing make World -j1 IRULESRC=/home/ubuntu/.conan/data/xorg-cf-files/1.0.7/_/_/package/7817f107796230a15b21ce2e6730484bddd548d0/lib/X11/config IMAKE_DEFINES=-DUsrLibDir=/home/ubuntu/.conan/data/nas/1.9.5/_/_/package/92da54bcd02b84dbdeb006b236462459a6160bee/lib
```

</details>

**Comment by dariusarnold** [comment]
FYI: https://github.com/conan-io/conan-center-index/pull/16491

**Comment by jcar87** [comment]
Hi @dariusarnold - thanks for raising this issue and the PR to address it.

May I ask a question: do you use `nas` and its functionality directly, or is this an issue due to this being a requirement for `sdl2`? Thanks!

**Comment by dariusarnold** [comment]
I was using it as a requirement for SDL2.

**Comment by jcar87** [comment]
> I was using it as a requirement for SDL2.

I see, thanks for answering so quickly! As a workaround until aarch64 is supported, I would suggest adding the option `-o "sdl2*:nas = False` when installing sdl2.  My understanding is that `sdl2` is mainly used for keyboard/joystick/mouse, and that other avenues are used when audio is needed. I doubt functionality will be impacted - `nas` is not an SDL2 dependency on most other package managers or Linux distros, so we are currently considering dropping it as a default requirement on SDL2 as well.

**Comment by jcar87** [comment]
I've started a manual run of your PR as well, as it looks good :) 
I apologize that the build results were not properly published.

**Comment by dariusarnold** [comment]
Okay, thank you very much for your suggestion. I didn't even check if the `nas` requirement could be configured away. I am using SDL for drawing and audio as well, but not networked audio. I was using the forked `nas` recipe with a build in my local conan cache instead. But I will try disabling the dependency.
All is well, just tell me if there is anything required from me for merging this PR.

**Comment by dariusarnold** [comment]
Closing since my PR to fix this was merged.
