### ISSUE TITLE
[question] Conan v2 Pipeline failed because of missing binaries

### ISSUE THREAD

**Issue by igormironchik** [conan-io/conan-center-index#16525]
### What is your question?

I did a #16522 that failed to build with `Conan` v2 pipeline because of missing binaries:

```
ERROR: Missing binary: uriparser/0.9.7:4f5b3adbcde761a3f78610cf2f3649fd2c3deb70
```
Should I do something in my recipe? Or this is an issue of your CI?

Thanks.

**Comment by SpaceIm** [comment]
Many v2 packages are missing, there is nothing you can do except asking to conan team to generate these packages or open a PR related to recipe for which packages are missing. I've opened https://github.com/conan-io/conan-center-index/pull/16527

**Comment by igormironchik** [comment]
Thank you.
