### ISSUE TITLE
[conan.io/center] Upload dependency graph for every package

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan-center-index#1653]
Please upload the dependency graph html file (` conan info . --graph=conan_dependency_graph.html  `) for every package on the website.

When I scroll through a package I want to immediately see all the dependencies!

**Comment by Dattax** [comment]
Dependencies tab has been added to ConanCenter. https://conan.io/center/boost?tab=dependencies

**Comment by AbrilRBS** [comment]
Fixed with the release of Conan 2 a while back and the new CCI website, thanks for reporting it in the first time, sorry that we didn't circle back to the issue in time :)
