### ISSUE TITLE
[package] openldap/2.6.1: Does not build on MacOS

### ISSUE THREAD

**Issue by vlebourl** [conan-io/conan-center-index#16555]
### Description

OpenLDAP doesn't build on Linux because of this: https://github.com/conan-io/conan-center-index/blob/faef79fd825aeab50336eddb12933b72e50287da/recipes/openldap/all/conanfile.py#L48

Could this limitation be lifted? 

Cheers

### Package and Environment Details

* Package Name/Version: **openldap/2.6.1**
* Operating System+version: **MacOS 12.6.2**
* Compiler+version: **AppleClang 15**
* Conan version: **conan 1.59.0** (not on 2.0 yet because of missing packages)
* Python version: **Python 3.10.9**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

inside a fork of conan-center-index/recipes/openldap/all/
```sh
conan install . --build=missing
```

### Logs

<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=14
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

WARN: cyrus-sasl/2.1.27: requirement openssl/1.1.1t overridden by openldap/None to openssl/1.1.1q
conanfile.py (openldap/None): Installing package
Requirements
    cyrus-sasl/2.1.27 from 'conancenter' - Cache
    openssl/1.1.1q from 'conancenter' - Cache
Packages
    cyrus-sasl/2.1.27:7e7af0ed7931a161b325bff1e2f6c62e8ff7cc0a - Cache
    openssl/1.1.1q:6841fe8f0f22f6fa260da36a43a94ab525c7ed8d - Cache

Installing (downloading, building) binaries...
openssl/1.1.1q: Already installed!
cyrus-sasl/2.1.27: Already installed!
conanfile.py (openldap/None): ERROR: Invalid ID: openldap is only supported on Linux. Trying to install dependencies, but this configuration will fail to build a package
conanfile.py (openldap/None): Generator txt created conanbuildinfo.txt
conanfile.py (openldap/None): Aggregating env generators
conanfile.py (openldap/None): Generated conaninfo.txt
conanfile.py (openldap/None): Generated graphinfo
```

</details>

**Comment by uilianries** [comment]
I just opened the PR #23652 with such support.
