### ISSUE TITLE
[question] Crosscompiling protobuf

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#1658]
Hi guys, I've been looking into integrating `protobuf` to my project and I need to crosscompile.
Right now the recipe fails because it tries to download `protoc` for a non x86 architecture. My first thought was to add `protoc` as a `build_requirement` but I've been looking around into old PRs and I saw that you decided to go this road instead.
What is the reason for this? Having `protoc` as a `build_requirement` seams really convenient. 
Is there any suggested approach if you need to use `protoc` in a non x86 architecture?
Thanks!

**Comment by SpaceIm** [comment]
I have the same issue for capnproto packaging. I think that for those 2 similar libs, executables sould go in a separate recipe (always built with static libs).

**Comment by 0x8000-0000** [comment]
Can you please try out https://github.com/0x8000-0000/conan-recipes/tree/master/recipes/protobuf_compiler ?

**Comment by ericriff** [comment]
Sure, thanks. But I'm not asking for a `protoc` recipe. There's one on Bincrafters too.
What I'm asking is for the recommended way to address this situation. I'm working on a large codebase and this changes need a lot of approvals so I don't want to use `protoc` as a `build_requirement` and have to change it later if there is a better way to do it.
I'm guessing there is a better (or a least different) way to do this since the PR to have a `protoc` installer recipe got canceled.

**Comment by ericriff** [comment]
I'm trying to keep my conan as Vanilla as possible :)

**Comment by 0x8000-0000** [comment]
> Sure, thanks. But I'm not asking for a `protoc` recipe. There's one on Bincrafters too.

Mine is based on the Bincrafters' just updated to match the Protobuf library proper.

> What I'm asking is for the recommended way to address this situation. I'm working on a large codebase and this changes need a lot of approvals so I don't want to use `protoc` as a `build_requirement` and have to change it later if there is a better way to do it.

I think we're all learning how to use these packages in the C++ world. With the new "components" feature, the Conan developers are working towards generating Conan packages with multiple internal targets. But I don't know how this will combine with the fact that separate profiles create separate binary packages.

> I'm guessing there is a better (or a least different) way to do this since the PR to have a `protoc` installer recipe got canceled.

Are you talking about #1179  ?

**Comment by 0x8000-0000** [comment]
> I'm trying to keep my conan as Vanilla as possible :)

Me too (see that I have just removed the Abseil recipe since my upstream update got merged), but at the same time I have other stuff to do than wait around, plus learning packaging is useful as we are starting to package our internal bits with Conan as well.

**Comment by 0x8000-0000** [comment]
Please this see note https://github.com/conan-io/conan-center-index/pull/1199#pullrequestreview-394573563

**Comment by ericriff** [comment]
> > Sure, thanks. But I'm not asking for a `protoc` recipe. There's one on Bincrafters too.
> 
> Mine is based on the Bincrafters' just updated to match the Protobuf library proper.
> 
> > What I'm asking is for the recommended way to address this situation. I'm working on a large codebase and this changes need a lot of approvals so I don't want to use `protoc` as a `build_requirement` and have to change it later if there is a better way to do it.
> 
> I think we're all learning how to use these packages in the C++ world. With the new "components" feature, the Conan developers are working towards generating Conan packages with multiple internal targets. But I don't know how this will combine with the fact that separate profiles create separate binary packages.
> 
> > I'm guessing there is a better (or a least different) way to do this since the PR to have a `protoc` installer recipe got canceled.
> 
> Are you talking about #1179 ?

I'm talking about [#65](https://github.com/conan-io/conan-center-index/pull/65)

**Comment by Manu343726** [comment]
Just for reference, my tinyrefl reflection tool is packaged in two separate packages for exactly this reason. The tool can be build required by the host toolchain and the client lib required and cross compiled by the target toolchain.

See https://github.com/Manu343726/raytracer for am example of usage.

**Comment by ericriff** [comment]
Hi guys, 
I ended up creating a custom recipe to pack protoc based on all the links that you shared here.
I'm closing this.
Thanks for all the help!
