### ISSUE TITLE
[package] mpir: sources are no longer available at mpir.org 

### ISSUE THREAD

**Issue by artem-ogre** [conan-io/conan-center-index#16595]
### Description

The package sources can't be obtained from mpir.org as the domain no longer belongs to the library maintainers.

**Comment by artem-ogre** [comment]
Any update? Recipe for [mpir](https://github.com/conan-io/conan-center-index/tree/master/recipes/mpir) is broken because the `sources` url ("http://mpir.org/mpir-3.0.0.zip") in [conandata.yml](https://github.com/conan-io/conan-center-index/blob/master/recipes/mpir/all/conandata.yml) is dead.

**Comment by jcar87** [comment]
Hi @artem-ogre - it appears `mpir` is unmaintained. 

Please check https://web.archive.org/web/20220331072605/http://www.mpir.org/downloads.html - there appears there are two forks where development might continue, and the original 3.0.0 seems like an older release.

The original .zip file that matches the shasum recorded in the recipe can be retrieved from the wayback machine, if you'd like to be able to build this locally, you can download that zip file, clone the `conan-center-index` repository and point the conandata.yml to a file in your local filesystem (`file:///path/to/your/file.zip`) - I would discourage referencing URLs from the wayback machine as it is not a service intended for that purpose.

However, it is useful to see the original contents of the zip file to compare against the current forks:
* https://github.com/wbhart/mpir
* https://github.com/BrianGladman/mpir

From what I can see, the `3.0.0` referenced here https://github.com/wbhart/mpir/releases/tag/mpir-3.0.0 largely matches the contents of the missing zip file, but the recipe may have to be tweaked further to call autoreconf. 

I'd encourage you to contact the original authors to clarify the status of the project. We will welcome contributions to update the recipe to point to the one of the surviving forks in github - but for version 3.0.0 we would only do this if there is solid evidence the sources are the same.

**Comment by artem-ogre** [comment]
@jcar87 Thank you for the info! Is there any preferred place for hosting sources that are no longer available? We could re-upload the zip there to make sure it's exactly the same.

**Comment by jcar87** [comment]
> @jcar87 Thank you for the info! Is there any preferred place for hosting sources that are no longer available? We could re-upload the zip there to make sure it's exactly the same.

If would probably suggest a GitHub fork, where the releases feature can be used to host the original zip file, matching the exact checksum of the original file. We could then add that as a mirror in the recipe for version 3.0.0. I would however, make it clear in the README that it is a fork and unrelated to the original maintainers - to avoid any confusion.

Otherwise, identifying the differences between the original file and  https://github.com/wbhart/mpir/releases/tag/mpir-3.0.0 , and updating the recipe accordingly could be a good option, provided we have an assurance the source code is indeed the same.

**Comment by Ahajha** [comment]
@jcar87 I believe this can be closed - the mpir recipe now clones from `wbhart`'s fork.

**Comment by AbrilRBS** [comment]
Thanks for the heads-up @Ahajha!
