### ISSUE TITLE
[request] Hyperscan/5.2.1

### ISSUE THREAD

**Issue by Flig** [conan-io/conan-center-index#1662]
### Package Details
  * Package Name/Version: **Hyperscan/5.2.1**
  * Website: **https://www.hyperscan.io/**
  * Source code: **https://github.com/intel/hyperscan**

### Description Of The Library
Hyperscan is a high-performance multiple regex matching library. It follows the regular expression syntax of the commonly-used libpcre library, but is a standalone library with its own C API.

Hyperscan uses hybrid automata techniques to allow simultaneous matching of large numbers (up to tens of thousands) of regular expressions and for the matching of regular expressions across streams of data.

Hyperscan is typically used in a DPI library stack.

> Conan center already has `ragel` and `pcre` packages, that `hyperscan` depends on

**Comment by Flow-It** [comment]
I do have a working hyperscan recipe locally and I'd love to contribute. It needs a bit more work though, especially the test_package which is quite rudimentary. I'll try to bring it into good shapes in the next few days.

**Comment by SpaceIm** [comment]
@uilianries @SSE4 @prince-chrismc hyperscan has been added by https://github.com/conan-io/conan-center-index/pull/4260, so this issue can be closed.

**Comment by prince-chrismc** [comment]
Thanks

**Comment by uilianries** [comment]
Thank you!
