### ISSUE TITLE
[request] libssh2/1.10.0 Migration to 2.0

### ISSUE THREAD

**Issue by kevind992** [conan-io/conan-center-index#16644]
### Package Name/Version

libssh2/1.10.0

### Webpage

https://www.libssh2.org/

### Source code

https://github.com/libssh2/libssh2

### Description of the library/tool

Looking to get libssh2 migrated over to Conan 2.0

Thanks in advance

**Comment by gegles** [comment]
We would definitely need this one? Any updates?
