### ISSUE TITLE
[request] 7zip/22.01 (and Conan v2)

### ISSUE THREAD

**Issue by rettenbs** [conan-io/conan-center-index#16642]
### Package Name/Version

7zip/22.01

### Changelog

https://7-zip.org/history.txt

### Context about the new update

The current package version 19.00. The recipe is also outdated and does not work with Conan v2. The package for the underlying library is even older. https://github.com/conan-io/conan-center-index/issues/13025

This is also blocking the MinGW migration to Conan v2: https://github.com/conan-io/conan-center-index/pull/16318

**Comment by Ahajha** [comment]
I believe this is resolved now, 7zip has 22.01 and works with conan2.

**Comment by czoido** [comment]
Thanks for reporting, closing this as newer versions are already available.
