### ISSUE TITLE
[package] readerwriterqueue/1.0.6: Fails for conan 1.59 since v2 upgrade

### ISSUE THREAD

**Issue by tobiashienzsch** [conan-io/conan-center-index#16651]
### Description

The package was updated for v2 support yesterday since then it causes errors in "1.59" mode.

The package installs correctly, CMake configures correctly but it can't find the headers during compilation.

### Package and Environment Details

* Package Name/Version: **readerwriterqueue/1.0.6**
* Operating System+version: **Win 11**
* Compiler+version: **VS 2022**
* Conan version: **conan 1.59.0**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.version=17
compiler.runtime=MD

[options]
[build_requires]
[env]

[conf]
tools.cmake.cmaketoolchain:generator=Ninja

### Steps to reproduce

- Link against readerwriterqueue
- Try Compile

### Logs

None

**Comment by SpaceIm** [comment]
A log would have helped. It guess it fails to include `readerwritercircularbuffer.h`, correct?
