### ISSUE TITLE
[package] spdlog/1.11.0: option 'shared' doesn't exist

### ISSUE THREAD

**Issue by bigcat26** [conan-io/conan-center-index#16652]
### Description

Setting `header_only` option to `True` in both project A and B while B depends on A may cause conan to report an error of `ConanException: option 'shared' doesn't exist` during `conan install`

The possible reason is the `configure` function in `conanfile.py` has been invoked twice. the `shared` option was removed during the second invocation, so Conan complains that the option 'shared' doesn't exist.

### Package and Environment Details

* Package Name/Version: **spdlog/1.11.0**
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **GCC 9**
* Docker image: **conanio/gcc9**
* Conan version: **conan 1.59.0**
* Python version: **Python 3.9.13**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

The possible way to reproduce the issue:

1. Create a static library project A which depends on spdlog/1.11.0 with "option:header_only=True"
2. Build library A then export it.
3. Create an executable project B which depends on both library A and spdlog/1.11.0 with "option:header_only=True"
4. Run conan install in project B
5. Error occours

```
ERROR: spdlog/1.11.0: Error in configure() method, line 47
        if self.options.shared:
        ConanException: option 'shared' doesn't exist
Possible options are ['header_only', 'wchar_support', 'wchar_filenames', 'no_exceptions']
```

### Logs

<details><summary>Click to expand log</summary>

```
$ cat ../conanfile.txt 
[requires]
spdlog/1.11.0
ProjectA/v1.0.0
[generators]
cmake_find_package
[options]
spdlog:header_only=True

$ conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: spdlog/1.11.0: Error in configure() method, line 47
        if self.options.shared:
        ConanException: option 'shared' doesn't exist
Possible options are ['header_only', 'wchar_support', 'wchar_filenames', 'no_exceptions']
```

</details>

**Comment by SpaceIm** [comment]
It doesn't seem to be a recipe bug, but a conan client bug.

**Comment by SpaceIm** [comment]
Could you open an issue in https://github.com/conan-io/conan please?

**Comment by bigcat26** [comment]
> Could you open an issue in https://github.com/conan-io/conan please?

Issue created: https://github.com/conan-io/conan/issues/13498
