### ISSUE TITLE
[request] gstreamer/1.22.1

### ISSUE THREAD

**Issue by mercierd** [conan-io/conan-center-index#16721]
### Package Name/Version

gstreamer/1.22.1

### Changelog

https://gstreamer.freedesktop.org/releases/1.22#1.22.1

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Can you add this version ?

**Comment by czoido** [comment]
Thanks for reporting, closing this as newer versions are already available.
