### ISSUE TITLE
[request] libssh/0.10.3

### ISSUE THREAD

**Issue by grabowski-d** [conan-io/conan-center-index#16747]
### Package Name/Version

libssh/0.10.3

### Webpage

https://www.libssh.org/

### Source code

https://git.libssh.org/

### Description of the library/tool

Library description by authors:
libssh is a multiplatform C library implementing the SSHv2 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel, manage public keys and much more.

I wish to create a recipe for this package by myself.
Any concerns?

**Comment by gjasny** [comment]
The recipe needs Conan 2 conversion as well. I'll give it a try.

**Comment by gjasny** [comment]
> I wish to create a recipe for this package by myself.

Oh sorry, I missed that. I'm under the impression that `[request]` issues are to request recipes from others. I picked up the stale and closed PR #13449 and updated it according to the cmake packaging template: #16899 .

**Comment by grabowski-d** [comment]
Sure, go ahead. I didn't start yet :)

**Comment by uilianries** [comment]
The libssh is available in Conan Center. See #23230
