### ISSUE TITLE
[package] freetype/2.13.0: Wrong cmake target with CMakeDeps

### ISSUE THREAD

**Issue by Jihadist** [conan-io/conan-center-index#16824]
### Description

Conan generates wrong cmake target with CMakeDeps generator. Cmake FindFreetype https://cmake.org/cmake/help/latest/module/FindFreetype.html exports Freetype::Freetype target while conan generated freetypeTargets exports freetype target

### Package and Environment Details

* Package Name/Version: **freetype/2.13.0**
* Operating System+version: **Windows 10**
* Compiler+version: **MSVC 2019**
* Conan version: **conan 1.57.0**
* Python version: **Python  3.10.1**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

### Steps to reproduce

conan install freetype/2.13.0@ -g CMakeDeps

### Logs

<details><summary>Click to expand log</summary>

freetypeTargets.cmake
```
# Load the debug and release variables
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB DATA_FILES "${_DIR}/freetype-*-data.cmake")

foreach(f ${DATA_FILES})
    include(${f})
endforeach()

# Create the targets for all the components
foreach(_COMPONENT ${freetype_COMPONENT_NAMES} )
    if(NOT TARGET ${_COMPONENT})
        add_library(${_COMPONENT} INTERFACE IMPORTED)
        message(STATUS "Conan: Component target declared '${_COMPONENT}'")
    endif()
endforeach()

if(NOT TARGET freetype)
    add_library(freetype INTERFACE IMPORTED)
    message(STATUS "Conan: Target declared 'freetype'")
endif()
# Load the debug and release library finders
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/freetype-Target-*.cmake")

foreach(f ${CONFIG_FILES})
    include(${f})
endforeach()
```

</details>

**Comment by SpaceIm** [comment]
Call `find_package(Freetype REQUIRED MODULE)`, and you'll get correct target from https://cmake.org/cmake/help/latest/module/FindFreetype.html

see https://github.com/conan-io/conan/issues/10387

**Comment by SpaceIm** [comment]
Actually target of config file can be extended to Freetype::Freetype, they have fixed this upstream: https://github.com/freetype/freetype/commit/55a97b0cb133b7a5dc28dfabec77a1b9f742c301

**Comment by Jihadist** [comment]
> Call `find_package(Freetype REQUIRED MODULE)`, and you'll get correct target from https://cmake.org/cmake/help/latest/module/FindFreetype.html

Thank you, it works!
