### ISSUE TITLE
conan-sigcpp testing/2.10.1 (or "lost in the weeds")

### ISSUE THREAD

**Issue by ThePowerTool** [conan-io/conan-center-index#16884]
Hi,

I'm a newb only talented at cloning projects.

I'm attempting to build WorldForge with conan.  I was ableo to update some of the conanfiles to 2.0 (the simple ones that pretty-much matched the examples you provided for upgrading to 2.0).  It fails on
```
*********************************************************
Recipe 'sigc++/2.10.0@worldforge/stable' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'sigc++/2.10.0@worldforge/stable' not resolved: sigc++/2.10.0@worldforge/stable: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py", line 1, in <module>
    from conans import ConanFile, tools, MSBuild, AutoToolsBuildEnvironment
ImportError: cannot import name 'ConanFile' from 'conans' (/usr/lib/python3.10/site-packages/conans/__init__.py)
```

So I started by cloning conan-sigcpp and replacing /root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py with ./conan-sigcpp/conanfile.py with little hope because I'd already read the "migration to conan 2.0" article and knew the new conventions were not present.

I went to https://github.com/bincrafters/conan-sigcpp which I *think* said to look for the new recipe here.

Here I found a reference to "check if a recipe is already existing in conan-center, conan-community or Bincrafters."  So I checked:
[https://conan.io/center/search/conan-sigcpp](url)
[https://jfrog.com/community?search=conan-sigcpp](url)
[https://github.com/search?q=org%3Abincrafters+conan-sigcpp](url)

I don't understand the status of conan-sigcpp--it seemed to me it was saying it's obsolete and conan-center-index replaces it but again, I'm the newb here.

I need a conan-sigcpp/conanfile.py that's updated to conan 2.0.

I would sincerely appreciate any help!

**Comment by SpaceIm** [comment]
I don't know what is conan-sigcpp. I guess you are looking for libsigcpp recipe in conancenter.

**Comment by ThePowerTool** [comment]
OK, I didn't know:  Apparently your "guess" is similar to Mr. Spock's.

I blindly copied https://github.com/conan-io/conan-center-index/blob/7d5cd85df85ff82887f3f1a79c788ec5442f648b/recipes/libsigcpp/3.x.x/conanfile.py into my /root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py and the problem seems to be resolved.

Thank you for your help :-)
