### ISSUE TITLE
[request] taocpp-pegt/3.2.7

### ISSUE THREAD

**Issue by GaeaKat** [conan-io/conan-center-index#16895]
### Package Name/Version

taocpp-pegt/3.2.7

### Changelog

https://github.com/taocpp/PEGTL/releases/tag/3.2.7

### Context about the new update

The recipe in the repo currently is specific to Conan 1 only, and does not work for Conan 2. 
If this is possible to work for Conan 2 it would be of great assistance

**Comment by czoido** [comment]
Thanks for reporting, closing this as it's already available.

**Comment by GaeaKat** [comment]
> Thanks for reporting, closing this as it's already available.

It hasn't though, the available recipe is STILL only Conan 1

**Comment by GaeaKat** [comment]
https://conan.io/center/recipes/taocpp-pegtl shows 3.2.7 was released on 03-09-2023 ... the Conan v2 fix was commited in 04-08-2023 .. So while Conan v2 has been added, it looks like it has not been uploaded to the site?
