### ISSUE TITLE
Version Conflict

### ISSUE THREAD

**Issue by alLiucb** [conan-io/conan-center-index#16935]
### What is your question?

- conan 2.0.3
- cmake 3.26.2
- Software：Clion

confile.txt：
[requires]
eigen/3.4.0
openssl/1.1.1t
zlib/1.2.12
sqlite3/3.36.0
qt/5.15.5
gdal/3.1.0
[generators]
cmake_find_package
[options]
qt*:shared=True

and showed error
======== Computing dependency graph ========
Graph root
    conanfile.txt: D:\CodeBase\pipeline\RSPGUITools-master\cmake-build-debug\conanfile.txt
Requirements
    eigen/3.4.0#2e192482a8acff96fe34766adca2b24c - Cache
    openssl/1.1.1t#7d9fc949345908e1b8609d9d9f528a08 - Cache
    qt/5.15.5#0c219a005daa86ec92bed9694374e6f2 - Cache
    sqlite3/3.36.0#a28e9cdc62d449874c25fa05744c9c95 - Cache
    zlib/1.2.12#b1fd071d8a2234a488b3ff74a3526f81 - Cache
Build requirements
    nasm/2.15.05#799d63b1672a337584b09635b0f22fc1 - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache
ERROR: Version conflict: qt/5.15.5->zlib/1.2.13, None->zlib/1.2.12.

**Comment by a120471** [comment]
I met the same problem. If I remember correctly, when I use conan 1.x, I can use "zlib/1.2.13" in conanfile.txt to force override the version. But I didn't find out how to do this with conanfile.txt in conan 2.x. 
The documents I've checked, https://docs.conan.io/2/tutorial/consuming_packages/intro_to_versioning.html, https://docs.conan.io/2/tutorial/versioning/conflicts.html, FYI.

**Comment by SpaceIm** [comment]
You can't in a conanfile.txt, only in conanfile.py: https://github.com/conan-io/conan/issues/13201#issuecomment-1442573111

**Comment by a120471** [comment]
> You can't in a conanfile.txt, only in conanfile.py: [conan-io/conan#13201 (comment)](https://github.com/conan-io/conan/issues/13201#issuecomment-1442573111)

Thanks, I'll take a look at how to use a conanfile.py. Hope it's as easy as conanfile.txt. :)

**Comment by AlienLcb** [comment]
> 你不能在 conanfile.txt 中，只能在 conanfile.py 中：[conan-io/conan#13201（评论）](https://github.com/conan-io/conan/issues/13201#issuecomment-1442573111)

I tried this way to solve my problem
https://github.com/conan-io/conan/issues/13648#issuecomment-1501321873
