### ISSUE TITLE
[request] cryptopp/8.7.0.1 cmake

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan-center-index#16956]
### Package Name/Version

cryptopp/8.7.0

### Changelog

https://github.com/abdes/cryptopp-cmake/releases/tag/CRYPTOPP_8_7_0_1

### Context about the new update

There is newer version of CMake helper (8.7.0.1) for cryptopp/8.7.0. It fixes several issues. For example, it makes possible to cross-compile from Apple Silicon (armv8) to x86_64.

**Comment by coffeeaddict19** [comment]
Seconded, please do this.
