### ISSUE TITLE
qt/5.15.7: WebEngine will not build

### ISSUE THREAD

**Issue by Gernatch** [conan-io/conan-center-index#16998]
### Description

When attempting to build QT 5.15.7 on Ubuntu using a Conan docker image, I'm experiencing an issue with NSS and FontConfig not being "suitable" versions. Will provide some steps to help reproduce. @memsharded 

### Package and Environment Details

* Package Name/Version: qt/5.15.7
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 8**
* Docker image: **conanio/gcc8**
* Conan version: **conan 1.59.0**
* Python version: **Python 3.7.13** (and Python 2.7 for WebEngine)
* Note, the python binary should be called python2, it can't be called python2.7 or webengine will fail

### Conan profile

[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release

[options]
zlib:shared=True

qt:shared=True
qt:qtwebengine=True
qt:qtdeclarative=True
qt:qtlocation=True
qt:qtwebchannel=True
qt:qtmultimedia=True

### Steps to reproduce

1. Pull the docker image from conanio/gcc8:1.59.0
2. Download Python2 (required for WebEngine to build): sudo apt-get install python2.7
3. Clone conan-center-index
4. Use the profile information I shared here
5. Export recipes... (I have a specific list, but I use a custom script to export them)
6. I disable all remotes so I'm certain everything builds freshly
7. Use conan create . qt/5.15.7@ -pr <profile> --build=missing

This fails fairly early on in the QT build.

### Logs

Below is the errors/warnings I get. Note, if I install nss with apt-get, the nss warning goes away. But then the same kind of warning returns for fontconfig. I would think nss and fontconfig should be getting resolved through Conan since they are both in the "requires" for QT.
---
Note: Disabling X11 Accessibility Bridge: D-Bus or AT-SPI is missing.

Note: The following modules are not being compiled in this configuration:
    webenginecore
    webengine
    webenginewidgets

WARNING: A suitable version of nss required to build QtWebEngine could not be found.

WARNING: QtWebEngine will not be built.

ERROR: Feature 'webengine-system-opus' was enabled, but the pre-condition 'config.unix && libs.webengine-opus' failed.

**Comment by ericLemanissier** [comment]
thanks for the report. The issue should be fixed by https://github.com/conan-io/conan-center-index/pull/17009. You also need to use option qt:with_dbus=True
Can you please try ?

**Comment by Gernatch** [comment]
> thanks for the report. The issue should be fixed by #17009. You also need to use option qt:with_dbus=True Can you please try ?

This came extremely close to finishing building today, but I see this and not sure how to get past it:
rm -f libQt5WebEngineCore.so.5.15.10 libQt5WebEngineCore.so libQt5WebEngineCore.so.5 libQt5WebEngineCore.so.5.15
linking ../../lib/libQt5WebEngineCore.so.5.15.10
/opt/anss/ado/.conan/data/fontconfig/2.13.93/_/_/package/b5a93aab3076fc5237b82afcab1ad866c1b5945d/lib/libfontconfig.a(fcfreetype.c.o): In function `FcFreeTypeQueryFaceInternal':
fcfreetype.c:(.text+0x3072): undefined reference to `FT_Get_BDF_Property'
fcfreetype.c:(.text+0x30a2): undefined reference to `FT_Get_BDF_Property'
fcfreetype.c:(.text+0x3190): undefined reference to `FT_Get_BDF_Property'
fcfreetype.c:(.text+0x31ef): undefined reference to `FT_Get_BDF_Property'
fcfreetype.c:(.text+0x33f9): undefined reference to `FT_Get_BDF_Property'
/opt/anss/ado/.conan/data/fontconfig/2.13.93/_/_/package/b5a93aab3076fc5237b82afcab1ad866c1b5945d/lib/libfontconfig.a(fcfreetype.c.o):fcfreetype.c:(.text+0x3413): more undefined references to `FT_Get_BDF_Property' follow
collect2: error: ld returned 1 exit status

I do build fontconfig and freetype. But not sure why this is coming up as undefined. I checked the original freetype library, and it's defined properly. But this libfontconfig.a seems to be causing trouble. Any idea?

Thanks again for the earlier suggestion, which did get me past that problem. I do want to note that I had to install this in order to get this to nearly build: `sudo yum install alsa-lib-devel`

**Comment by ericLemanissier** [comment]
You probably need to set option fontconfig:shared=True

**Comment by Gernatch** [comment]
> You probably need to set option fontconfig:shared=True

Is it not possible to build it with fontconfig:shared=False? 

When I began building QT, I was given a request to use a static version, but it seems just making sure there is no fontconfig on the system might be a viable alternative. 

Original Request:
> "We need to compile against a static build of fontconfig so that font setup does not make a query against an X11 server. Querying X11 directly often breaks remote-desktop environments. [...] The trick is figuring out the right way to tweak the Qt build so that fontconfig is statically linked.  This may require inspecting the Qt config system to see if there's an option, documented or not, for static linkage of fontconfig.  If not, then moving the dynamic fontconfig libraries out of the system directory(s) and rebuilding can also accomplish the same thing.  Similarly, I had to move both static and dynamic system libraries for jpeg and png when specifying our own libraries as Qt was adamant about using the system versions even though I specified ours."

I can try to set this to true and see if this becomes a non-issue since I don't have fontconfig.so anywhere on the system.
