### ISSUE TITLE
[package] qt/5.15.8: Problem with spaces in path during install

### ISSUE THREAD

**Issue by bsespede** [conan-io/conan-center-index#17004]
**Package and Environment Details (include every applicable attribute)**

Package Name/Version: qt/5.15.8
Operating System+version: Windows 10
Compiler+version: MSVC 17
Conan version: conan 1.58.0
Python version: Python 3.9

**Conan profile (output of conan profile show default or conan profile show <profile> if custom profile is in use)**

```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

**Steps to reproduce (Include if Applicable)**

Using the following settings when installing:
```
[requires]
qt/5.15.8
[options]
qt/*:qtdeclarative=True
qt/*:qtquickcontrols2=True
qt/*:gui=True
qt/*:shared=False
[generators]
CMakeDeps
CMakeToolchain
```

Leads to the following error:
```
        C:\.conan\e9a2ff\1\bin\jom.exe -f Makefile.Release
QtQmlDepends
        C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe C:/.conan/4f953f/1/qt5/qtdeclarative/src/3rdparty/masm/yarr/create_regex_tables > .generated\release\RegExpJitTables.h
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
qlalr C:\.conan\4f953f\1\qt5\qtdeclarative\src\qml\parser\qqmljs.g 
jom: C:\.conan\f8b74a\1\build_folder\qtdeclarative\src\qml\Makefile.Release [.generated\release\RegExpJitTables.h] Error 1
jom: C:\.conan\f8b74a\1\build_folder\qtdeclarative\src\qml\Makefile [release] Error 2
jom: C:\.conan\f8b74a\1\build_folder\qtdeclarative\src\Makefile [sub-qml-make_first-ordered] Error 2
jom: C:\.conan\f8b74a\1\build_folder\qtdeclarative\Makefile [sub-src-make_first] Error 2
jom: C:\.conan\f8b74a\1\build_folder\Makefile [module-qtdeclarative-make_first] Error 2
qt/5.15.8: 
qt/5.15.8: ERROR: Package '16dcf27dfe8a408291b7d10cac077c70ab2e583f' build failed
qt/5.15.8: WARN: Build folder C:\.conan\f8b74a\1
ERROR: qt/5.15.8: Error in build() method, line 794
        self.run(self._make_program(), run_environment=True)
        ConanException: Error 2 while executing jom
```

Looks like jom doesnt like spaces in in path names? I'm not sure how to fix this from my side

**Comment by bsespede** [comment]
Solved it by removing the spaces in my python path. Closing issue.

**Comment by liurunjieuk** [comment]
qt 5.15.14 win10 ,ming810_64，qnx sdp 7.0
![image](https://github.com/user-attachments/assets/3d9031d4-2452-4da0-a342-7f55565bda7a)

`cd build\qtdeclarative\src\qm`
`cat .generated\RegExpJitTables.h`
you will find RegExpJitTables.h is empty，
then delete RegExpJitTables.h,
`cd build\qtdeclarative\src\qml\`
`mkdir  .generated`
`python.exe D:/qt5/qtdeclarative/src/3rdparty/masm/yarr/create_regex_tables > .generated\RegExpJitTables.h,`
it constains static const char _wordcharData[65536]
