### ISSUE TITLE
[request] isl/0.25

### ISSUE THREAD

**Issue by LoeschMaximilian** [conan-io/conan-center-index#17123]
### Package Name/Version

isl/0.25

### Changelog

https://repo.or.cz/isl.git/blob_plain/HEAD:/ChangeLog

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

Also this recipe needs to be updated to conan 2.

It is the last dependency of gcc to make it build with conan v2.

**Comment by doocman** [comment]
I have a fix for conan v2. I can see if I can extend it with the version 0.25 as well.

**Comment by doocman** [comment]
https://github.com/conan-io/conan-center-index/pull/17157
It is, however, my first attempt at Conan, so thing may not be perfect. There was a test for a "CONAN_BASH_PATH" in which if it was not set, the Conan script required some msys stuff. This feels like a non-ideal way of doing.. something, and I'd like some help in understanding what should be done instead.

**Comment by czoido** [comment]
Thanks for reporting, closing this as newer versions are already available.
