### ISSUE TITLE
[package] pybind11/2.10.1: Cannot provide another python

### ISSUE THREAD

**Issue by Jihadist** [conan-io/conan-center-index#17145]
### Description

I use pybind with CMakeDeps generator.
```find_package(pybind11 REQUIRED)``` works correctly, but it uses system python
What if I need to use another python executable and libraries?
I can do this:
```
find_package(Python REQUIRED)
find_package(pybind11 REQUIRED)
```
and provide some hints for find_package(Python REQUIRED) but it does not work
```Unknown CMake command "python_add_library".```

Looks like here https://github.com/pybind/pybind11/blob/master/tools/pybind11Common.cmake#L175 we include pybind11NewTools.cmake and this case does not be covered by test_package.

### Package and Environment Details

* Package Name/Version: **pybind11/2.10.1**
* Operating System+version: **Windows 10**
* Compiler+version: **msvc 2019**
* Conan version: **conan 1.57.0**
* Python version: **Python 3.10.1**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install pybind11/2.10.1@ -g CMakeDeps

### Logs

<details><summary>Click to expand log</summary>

```
-- Found Python: C:/Users/user/AppData/Local/Programs/Python/Python310/python.exe (found version "3.10.1") found components: Interpreter 
-- Conan: Component target declared 'pybind11::headers'
-- Conan: Component target declared 'pybind11::pybind11'
-- Conan: Component target declared 'pybind11::embed'
-- Conan: Component target declared 'pybind11::module'
-- Conan: Component target declared 'pybind11::python_link_helper'
-- Conan: Component target declared 'pybind11::windows_extras'
-- Conan: Component target declared 'pybind11::lto'
-- Conan: Component target declared 'pybind11::thin_lto'
-- Conan: Component target declared 'pybind11::opt_size'
-- Conan: Component target declared 'pybind11::python2_no_register'
-- Conan: Target declared 'pybind11_all_do_not_use'
-- Conan: Including build module from 'C:/Users/user/.conan/data/pybind11/2.10.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/pybind11/pybind11Common.cmake'
CMake Error at C:/Users/user/.conan/data/pybind11/2.10.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/pybind11/pybind11NewTools.cmake:187 (python_add_library):
  Unknown CMake command "python_add_library".
```

</details>

**Comment by Jihadist** [comment]
Can be fixed with ```find_package(Python COMPONENTS Interpreter Development REQUIRED)```

**Comment by qgbcs** [comment]
Unknown CMake command "python_add_library".
