### ISSUE TITLE
[request] botan/2.19.3 - Upgrade conanfile to 2.x format

### ISSUE THREAD

**Issue by Maaown** [conan-io/conan-center-index#17247]
### Package Name/Version

botan/2.19.3

### Changelog

.

### Context about the new update

The recipe for botan v2.19.3 already exists, however we use it at work and since moving to 2.x is underway, we may soon have the need for an updated recipe.
I am available to perform the operation.

**Comment by Maaown** [comment]
Edit : Will also update to Botan 3.0.0, 2.19.3 will be left untouched and 3.0.0 will be added instead, using 2.x format

**Comment by lieser** [comment]
I also started the work to update the recipe to Conan 2 a few weeks ago. Should have probably created an issue for it to let others know 😅.

You can find the work I did so far in https://github.com/lieser/conan-center-index/tree/botan_conan2, which is mostly tested with VisualStudio so far. MacOS definitely still has an issue (`tools.apple_deployment_target_flag()` not being exposed), but that seems not be resolved in your draft PR so far too.

For me it does not matter if the works continue in your draft PR, or if we take my branch as the base. Regardless I think it would be good if you take a quick look at the changes I did. I think it includes some improvements (especially arround VS compatibility) that are missing in your PR.

I did no work on Botan 3.0.0 so far, that was planned as a separate step.
