### ISSUE TITLE
[package] benchmark/1.5.0: 64 bit only arm processors fails

### ISSUE THREAD

**Issue by willadsen** [conan-io/conan-center-index#1726]
### Package and Environment Details
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 7**
  * Conan version: **conan 1.25.2**
  * Python version: **Python 3.6.9**

### Conan profile 
```
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
When trying to compile (not cross) with a 64-bit only ARM processor, the build fails because of the naïve way of checking if it's a 64 bit processor in conanfile.py
```
cmake.definitions["BENCHMARK_BUILD_32_BITS"] = "ON" if "64" not in str(self.settings.arch) else "OFF"
```
which triggers the lib to set the ```-m32``` compiler flag

**Comment by perseoGI** [comment]
Hi! I'm recovering some old issues like this one.
I'm closing this issue as this `benchmark` version is no longer supported and the problem seems to be solved time ago.

If this problem persists, do not hesitate to create a new issue! 😄
