### ISSUE TITLE
[package] libsystemd/251.4: cross-compilation not working with [buildenv] but [env]

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan-center-index#17270]
### Description

See this post in linked issue, the cross-compilation problems are not yet solved: https://github.com/conan-io/conan-center-index/issues/16744#issuecomment-1494241358

### Package and Environment Details

Package Name/Version: libsystemd/251.4
Conan version: conan 2.0.2

### Conan profile
```
[buildenv]
CC=/usr/bin/aarch64-linux-gnu-gcc
CXX=/usr/bin/aarch64-linux-gnu-g++
STRIP=/usr/bin/aarch64-linux-gnu-strip
RANLIB=/usr/bin/aarch64-linux-gnu-ranlib
AR=/usr/bin/aarch64-linux-gnu-ar
AS=/usr/bin/aarch64-linux-gnu-as
OBJCOPY=/usr/bin/aarch64-linux-gnu-objcopy
LD=/usr/bin/aarch64-linux-gnu-ld
ARCH=arm64

[options]
*:shared=True
pcre2/*:shared=False

[settings]
os=Linux
arch=armv8
compiler=gcc

compiler.version=10.2
compiler.libcxx=libstdc++11
compiler.cppstd=gnu17
```
### Steps to reproduce

conan install --requires=libsystemd/251.4@ --build missing -pr:h armv8 -pr:b default -s build_type=Release

### Logs

See logs in linked issue

**Comment by prince-chrismc** [comment]
Please open a PR to fix the recipe for your use case 🙏

**Comment by tbsuht** [comment]
@prince-chrismc Well, I would, if it would be clear to me how the passing of the linker is related to the recipe. Especially the `[buildenv]` block compared to `[env]`.

**Comment by tbsuht** [comment]
ok, i found the root cause. There seems to be a difference between `[buildenv]` and `[env]`

This is working:
```
[env]
CC=/usr/bin/aarch64-linux-gnu-gcc
CXX=/usr/bin/aarch64-linux-gnu-g++
STRIP=/usr/bin/aarch64-linux-gnu-strip
RANLIB=/usr/bin/aarch64-linux-gnu-ranlib
AR=/usr/bin/aarch64-linux-gnu-ar
AS=/usr/bin/aarch64-linux-gnu-as
OBJCOPY=/usr/bin/aarch64-linux-gnu-objcopy
LD=/usr/bin/aarch64-linux-gnu-ld
ARCH=arm64
```

but not this
```
[buildenv]
CC=/usr/bin/aarch64-linux-gnu-gcc
CXX=/usr/bin/aarch64-linux-gnu-g++
STRIP=/usr/bin/aarch64-linux-gnu-strip
RANLIB=/usr/bin/aarch64-linux-gnu-ranlib
AR=/usr/bin/aarch64-linux-gnu-ar
AS=/usr/bin/aarch64-linux-gnu-as
OBJCOPY=/usr/bin/aarch64-linux-gnu-objcopy
LD=/usr/bin/aarch64-linux-gnu-ld
ARCH=arm64
```

The linker variable needs to be changed to 
```
[buildenv]
CCLD=/usr/bin/aarch64-linux-gnu-ld
CXXLD=/usr/bin/aarch64-linux-gnu-ld
```

Why is that the case? Otherwise build & host linker are wrongly detected.
This is the same for Conan 1.x and 2.x.

**Comment by jwillikers** [comment]
Are you sure the required variables aren't `CC_LD` and `CXX_LD` as documented [here](https://mesonbuild.com/Reference-tables.html#compiler-and-linker-selection-variables)? I'm not sure that this is an issue with the recipe, but instead it might be a requirement when cross-compiling Meson projects. That said, I'm not quite sure why it works with the `env` section.

**Comment by tbsuht** [comment]
Imo it's a problem of conan handling `LD` for meson projects, see the related issues https://github.com/conan-io/conan/issues/13824 and https://github.com/conan-io/conan/issues/14028.

So we can probably close this here as it is indeed not a problem with the recipe.

**Comment by jwillikers** [comment]
I've proposed conan-io/conan#14174 to resolve this.
