### ISSUE TITLE
zlib package cannot download sources

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan-center-index#17277]
### Description

zlib.net is down and appears to have been down for over a week!
![zlib](https://user-images.githubusercontent.com/48069914/234850101-31265dbe-4c28-45a6-8fb5-06b45286b9f6.PNG)

Is there a way for me to use the conancenter recipe but specify an alternate download site like github?

Regards
Klaus

### Package and Environment Details

Package Name/Version: zlib/1.2.12
Operating System+version: Linux Ubuntu 22.04 wsl
Compiler+version: GCC 9
Conan version: conan 1.58.0

### Conan profile

Any

### Steps to reproduce

conan install -r conancenter zlib/1.2.12

### Logs

None

**Comment by SpaceIm** [comment]
zlib.net is not down, I have access to it.

**Comment by vladd12** [comment]
This is a good reason to get zlib sources from another place.  If I'm not mistaken [this](https://github.com/madler/zlib) is the official gihub repository of zlib project.

**Comment by vladd12** [comment]
> zlib.net is not down, I have access to it.

A few minutes ago zlib.net was unavailable.

**Comment by SpaceIm** [comment]
Feel free to open a PR in order to add mirror url to conandata.yml of zlib. For example for 1.2.13 there is https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz is the same tarball than https://zlib.net/fossils/zlib-1.2.13.tar.gz, but official tarball of 1.2.12 is not available on github.

**Comment by klausholstjacobsen** [comment]
zlib.net is indeed up again!
I guess I was fooled by the fact that it was reported as having been down for over a week.

Thx

**Comment by SpaceIm** [comment]
I've opened https://github.com/conan-io/conan-center-index/pull/17280 in order to add a mirror to 1.2.13
