### ISSUE TITLE
[request] arrow/12.0.0

### ISSUE THREAD

**Issue by vient** [conan-io/conan-center-index#17409]
### Package Name/Version

arrow/12.0.0

### Changelog

https://arrow.apache.org/release/12.0.0.html

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

Current version in conan is 10.0.1, I don't know if adding 11.0.0 is necessary.

**Comment by czoido** [comment]
Thanks for reporting, closing this as newer versions are already available.
