### ISSUE TITLE
[package] openssl/1.1.1s|3.1.0: Fails on Android Cross Compile

### ISSUE THREAD

**Issue by tamuseanmiller** [conan-io/conan-center-index#17405]
### Description

Cross-compiling OpenSSL for Android using conan 2.0 is producing errors. I'll try and detail what I've done below:
First of all, just using the generic profile from the documentation:
```
[settings]
os=Android
os.api_level=21
arch=armv8
compiler=clang
compiler.version=14
compiler.libcxx=c++_static
compiler.cppstd=17
build_type=Release

[conf]
tools.android:ndk_path=/usr/local/share/android-ndk
```
Yields an error:
```sh
...
gcc  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -fPIC -pthread -fPIC -O3 -fPIC -O3 -fPIC -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/seanmi/.conan2/p/t/opensc043d1318ca2c/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -I/Users/seanmi/.conan2/p/zlibd34c201b5ba83/p/include -D__ANDROID_API__=21  -DNDEBUG -MMD -MF crypto/modes/libcrypto-lib-ccm128.d.tmp -MT crypto/modes/libcrypto-lib-ccm128.o -c -o crypto/modes/libcrypto-lib-ccm128.o crypto/modes/ccm128.c
crypto/uid.c:42:13: fatal error: 'sys/auxv.h' file not found
#   include <sys/auxv.h>
            ^~~~~~~~~~~~
1 error generated.
make[1]: *** [crypto/libcrypto-lib-uid.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [build_sw] Error 2

openssl/3.1.0: ERROR: 
Package 'bbbe791eda09458d8cc0efbbd04941a452976935' build failed
openssl/3.1.0: WARN: Build folder /Users/seanmi/.conan2/p/t/opensc043d1318ca2c/b/build-release
```

So since this was failing, I then attempted to include sys/auxv and all of the NDK includes manually by adding these to the `[buildenv]` section of the profile:
```
...
[buildenv]
CPPFLAGS+=-I/usr/local/share/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/aarch64-linux-android
CPPFLAGS+=-I/usr/local/share/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/
```
But when attempting with this, I get some linker errors:
```sh
gcc  -Iapps -I. -Iinclude -Iapps/include  -pthread -fPIC -O3 -fPIC -O3 -fPIC -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -I/Users/seanmi/.conan2/p/zlibd34c201b5ba83/p/include -D__ANDROID_API__=21  -DNDEBUG -I/usr/local/share/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/aarch64-linux-android -I/usr/local/share/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/ -MMD -MF apps/openssl-bin-x509.d.tmp -MT apps/openssl-bin-x509.o -c -o apps/openssl-bin-x509.o apps/x509.c
gcc -fPIC -pthread -fPIC -O3 -fPIC -O3 -fPIC -L. -Wl,-z,defs -Wl,-znodelete -shared -Wl,-Bsymbolic -L/Users/seanmi/.conan2/p/zlibd34c201b5ba83/p/lib  \
		-o providers/legacy.so -Wl,--version-script=providers/legacy.ld \
		providers/legacy-dso-legacyprov.o \
		providers/liblegacy.a providers/libcommon.a -lcrypto -lz -ldl -pthread 
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [providers/legacy.so] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [build_sw] Error 2

openssl/3.1.0: ERROR: 
Package 'bbbe791eda09458d8cc0efbbd04941a452976935' build failed
```
Or when building for x86 I get this:
```sh
clang  -I. -Iinclude -fPIC -pthread -m64 -fPIC -O3 -fPIC -O3 -fPIC -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/res\"" -DENGINESDIR="\"//lib/engines-1.1\"" -DNDEBUG -DNDEBUG -D__ANDROID_API__=31  -I/usr/local/share/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/x86_64-linux-android -I/usr/local/share/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/ -DNDEBUG -MMD -MF crypto/lhash/lhash.d.tmp -MT crypto/lhash/lhash.o -c -o crypto/lhash/lhash.o crypto/lhash/lhash.c
In file included from crypto/init.c:13:
include/crypto/rand.h:24:12: fatal error: 'Availability.h' file not found
#  include <Availability.h>
```

Either way, I don't think adding CPPFLAGS to the profile is the right idea. I think the recipe is wrong here somewhere.

### Package and Environment Details

* Package Name/Version: **openssl/1.1.1s|3.1.0**
* Operating System+version: **MacOS Ventura 13.3.1**
* Compiler+version: **Android NDK r25c clang 14**
* Conan version: **conan 2.0.4**
* Python version: **Python 3.11.2**

### Conan profile

Profile host:
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.cppstd=17
compiler.libcxx=c++_static
compiler.version=14
os=Android
os.api_level=21
[conf]
tools.android:ndk_path=/usr/local/share/android-ndk

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=17
os=Macos

### Steps to reproduce

Add `openssl/1.1.1s` or `openssl/3.1.0` to a conanfile and build with...
conan install . -pr android-armv8-static -r conancenter --build=missing

### Logs

<details><summary>Click to expand log</summary>

```
Open the log:
```
[conan_log.txt](https://github.com/conan-io/conan-center-index/files/11407209/conan_log.txt)
</details>

**Comment by SpaceIm** [comment]
Such "naive" host profile can't work for non-CMake recipes (maybe it can also work for Meson based recipes). I think conan v2 documentation (https://docs.conan.io/2/examples/cross_build/android/ndk.html#examples-cross-build-android-ndk) is misleading.

You have to specify some buildenv vars like CC, CXX AR, AS, RANLIB, STRIP, NM, LD, CHOST, SYSROOT etc, to make your profile robust to any recipe.
Or just add android-ndk recipe to tool_requires of your host profile.

**Comment by tamuseanmiller** [comment]
> Such "naive" host profile can't work for non-CMake based recipes (maybe it can also work for Meson based recipes). I think conan v2 documentation (https://docs.conan.io/2/examples/cross_build/android/ndk.html#examples-cross-build-android-ndk) is misleading.
> 
> You have to specify some buildenv vars like CC, CXX AR, AS, RANLIB, STRIP, NM, LD, CHOST, SYSROOT etc, to make your profile robust to any recipe. Or just add android-ndk recipe to tool_requires of your host profile.

Do you mean using something like this?
https://docs.conan.io/1/integrations/cross_platform/android.html#using-android-ndk-package-tool-require

**Comment by SpaceIm** [comment]
Yes, it's the second solution. As you can see in https://github.com/conan-io/conan-center-index/blob/4556e63d540a946a193553da70994d91e55a20cc/recipes/android-ndk/all/conanfile.py#L273-L321, android-ndk recipe doesn't only define `tools.android:ndk_path`, but many env vars or other conf, in order to be robust to any build system.

**Comment by tamuseanmiller** [comment]
> Yes, it's the second solution. As you can see in
> 
> https://github.com/conan-io/conan-center-index/blob/4556e63d540a946a193553da70994d91e55a20cc/recipes/android-ndk/all/conanfile.py#L273-L321
> 
> , android-ndk recipe doesn't only define `tools.android:ndk_path`, but many env vars or other conf, in order to be robust to any build system.
> If you decide to create your own Android profile without this recipe in tool_requires (so an Android-NDK not managed by a conan recipe), you have to define all these env vars yourself in this profile, otherwise it's not robust.

That makes quite a bit more sense. I think the old conan 1.x Android docs may still be more updated than the 2.0 if this is the case for non-CMake build systems. Either way, this all worked on my side. Super appreciate your help @SpaceIm after banging my head against this for so long. :)
