### ISSUE TITLE
[request] armadillo/12.2.x

### ISSUE THREAD

**Issue by doocman** [conan-io/conan-center-index#17404]
### Package Name/Version

armadillo/12.2.x

### Webpage

https://arma.sourceforge.net/

### Source code

https://gitlab.com/conradsnicta/armadillo-code

### Description of the library/tool

Armadillo is a high quality C++ library for linear algebra and scientific computing, aiming towards a good balance between speed and ease of use.

**Comment by valgur** [comment]
Recipe update for v12.2.0: #17320

**Comment by valgur** [comment]
@doocman Can be closed: https://conan.io/center/recipes/armadillo

**Comment by czoido** [comment]
Closing this as looks fixed, please feel free to reopen if you have more issues.
