### ISSUE TITLE
flex/2.6.4: cross-compile not supported

### ISSUE THREAD

**Issue by thkowa** [conan-io/conan-center-index#1743]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **flex/2.6.4**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Target Platform: **armv7hf** (Linux)
  * OS Compiler+version: **GCC 7**
  * Cross Compiler+version: **arm-linux-gnueabihf 7.5.0** 
  * Docker image: 
  * Conan version: **conan 1.25.2**
  * Python version: **Python 3.6.9**

### Conan profile
```
$ conan profile show default
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Debug
[options]
[build_requires]

$ conan profile show linux-x64-to-arm
Configuration for profile linux-x64-to-arm:

[settings]
os=Linux
os_build=Linux
arch=armv7hf
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Debug
[options]
[build_requires]
[env]
CONAN_CMAKE_FIND_ROOT_PATH=/usr/arm-linux-gnueabi
CHOST=arm-linux-gnueabihf
AR=arm-linux-gnueabihf-ar
AS=arm-linux-gnueabihf-as
RANLIB=arm-linux-gnueabihf-ranlib
LD=arm-linux-gnueabihf-ld
CC=arm-linux-gnueabihf-gcc
CXX=arm-linux-gnueabihf-g++
CXXFLAGS=-Wno-psabi
STRIP=arm-linux-gnueabihf-strip
```
### Problem

This package was recently added from bincrafters: https://github.com/conan-io/conan-center-index/pull/1195#. The cross-compilation was disabled, because it didn't work with the original recipe from bincrafters.  The bincrafters recipe had the following part in the build() method:
```
if self.cross_building:
                # stage1flex must be built on native arch: https://github.com/westes/flex/issues/78
                self.run("./configure %s" % " ".join(configure_args))
                env_build.make(args=["-C", "src", "stage1flex"])
                self.run("mv src/stage1flex src/stage1flex.build")
                env_build.make(args=["distclean"])
                with tools.environment_append(env_build.vars):
                    env_build.configure(args=configure_args)
                    cpu_count_option = "-j%s" % tools.cpu_count()
                    self.run("make -C src %s || true" % cpu_count_option)
                    self.run("mv src/stage1flex.build src/stage1flex")
                    self.run("touch src/stage1flex")
                    env_build.make(args=["-C", "src"])
```

The problem is the first `configure` call which is done manually with `self.run()`. As the cross-compile profile sets environment variables like _CC_, _CXX_, etc. which are picked up by `configure`, the configure fails.

The following workaround gets it correctly compiled, but seems to me not quite correct:
```
            if self.cross_building:
                # stage1flex must be built on native arch: https://github.com/westes/flex/issues/78
                with tools.environment_append({"AR": None,
                                               "AS": None,
                                               "RANLIB": None,
                                               "LD": None,
                                               "CC": None,
                                               "CXX": None, 
                                               "CXXFLAGS": None,
                                               "STRIP": None}):
                    self.run("./configure %s" % " ".join(configure_args))
                    env_build.make(args=["-C", "src", "stage1flex"])
                    self.run("mv src/stage1flex src/stage1flex.build")
                env_build.make(args=["distclean"])
                with tools.environment_append(env_build.vars):
                    env_build.configure(args=configure_args)
                    cpu_count_option = "-j%s" % tools.cpu_count()
                    self.run("make -C src %s || true" % cpu_count_option)
                    self.run("mv src/stage1flex.build src/stage1flex")
                    self.run("touch src/stage1flex")
                    env_build.make(args=["-C", "src"])
```

See also: 
- https://github.com/conan-io/conan-center-index/pull/1195#issuecomment-634597635
- https://github.com/conan-io/conan-center-index/pull/1195#issuecomment-634607787

**Comment by thkowa** [comment]
I made a new test for cross-compile and the latest recipe. The recipe explicitly avoids cross-compile with the following test in build() method:
```
    def build(self):
        if tools.cross_building(self.settings, skip_x64_x86=True):
            raise ConanInvalidConfiguration("This recipe does not support cross building atm (missing conan support)")
```

I disabled the check and tried again. It seems to work correctly. I can see that the stage1flex is build in build context using _gcc_ and the lib is build with arm compiler _arm-linux-gnueabihf-gcc_.

[flex-build.log](https://github.com/conan-io/conan-center-index/files/4728721/flex-build.log)

What I am not sure about is that the flex binary is linked again with arm compiler. First thought is that this should/must also be linked in build context?

Unfortunately I cannot test the build also, as I have no arm machine at the moment...

**Comment by notzain** [comment]
Has there been any progress in this?

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as cross compilation was enabled in https://github.com/conan-io/conan-center-index/pull/15234 when migration to conan 2 was made.

If the problem remains, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using conan v2.

Happy coding 🐸
