### ISSUE TITLE
[question] About the type (dynamic or static) of glib for windows with cross-compile on macOS

### ISSUE THREAD

**Issue by CaiJingLong** [conan-io/conan-center-index#17466]
### What is your question?

`glib` is used in a lot of libraries, but I find the artifacts of this library weird.

I don't know if it's the recipe's problem, or the glib itself.

When I compile libvips on macOS and deploy it, `glib` generates a dynamic library, while other libraries are static libraries

<img width="476" alt="image" src="https://user-images.githubusercontent.com/14145407/236989237-bbfa2f73-cad7-47be-8cb4-33f43fd7e351.png">

---

I cross compile windows lib in macOS with mingw-w64.

And get result like this:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/14145407/236989517-de48dcb6-7d9a-4878-9f6b-89d9b75820b5.png">

The glib ext name is `dll.a`, other lib ext name is `.a`.

---

By the way, how should cross compiling for windows with mingw-w64 compile usable dll files, not dll.a or .a files

**Comment by SpaceIm** [comment]
By default, shared option of CCI recipes is False (which means static). There are few exceptions. glib is shared by default. You can change options values if you want.

When you compile with MinGW, `dll.a` is the default extension name of import libs of dll, while `.a` is the extension of static libs. dll are located in bin folder of package.
