### ISSUE TITLE
[package] diligent-core/api.252009 : Version conflict with vulkan-headers

### ISSUE THREAD

**Issue by sambady** [conan-io/conan-center-index#17482]
### Description

Error with install diligent-core

diligent-core depends from vulkan-validationlayers/1.3.224.1 
diligent-core depends from vulkan-headers/1.3.224.1 
vulkan-validationlayers depends from vulkan-headers/1.3.224.0

### Package and Environment Details

* Package Name/Version: **diligent-core/api.252009**
* Operating System+version: **Windows 10**
* Compiler+version: **Visual Studio 2022**
* Conan version: **conan 2.0.4**
* Python version: **Python  3.11.3**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

### Steps to reproduce

conanfile.txt

[requires]
diligent-core/api.252009

[generators]
CMakeDeps
CMakeToolchain

conan install .

### Logs

<details><summary>Click to expand log</summary>

C:\MyProject>conan install . -b=missing -of=ConanBuild

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

======== Computing dependency graph ========
Graph root
    conanfile.txt: C:\MyProject\conanfile.txt
Requirements
    diligent-core/api.252009#548b4091849d70662de486113e4c352e - Cache
    glslang/1.3.224.0#2b09fe001e9ce4ec230504386f0862d7 - Cache
    opengl/system#b29589c04d6df84c110d6acb066ab653 - Cache
    robin-hood-hashing/3.11.5#6287c40b3396bea819b4751ef6bf8737 - Cache
    spirv-cross/1.3.224.0#a6abc63541499089423a8472cfbe2388 - Cache
    spirv-headers/1.3.224.0#1d19c94434cb2355a2c67823fe18c74b - Cache
    spirv-tools/1.3.224.0#1206029bb3925f75827551cb95a12087 - Cache
    vulkan-headers/1.3.224.1#623f4062ac76621d8e4758ab0ddab80f - Cache
    vulkan-validationlayers/1.3.224.1#23e0df1cb7c3f9163908e63f8e80b5aa - Cache
ERROR: Version conflict: vulkan-validationlayers/1.3.224.1->vulkan-headers/1.3.224.0, None->vulkan-headers/1.3.224.1.

</details>

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

I'm closing this issue as this is already resolved!
Take a look at:

https://github.com/conan-io/conan-center-index/blob/17f3c60b7960158c34deb3c7eb3f20f6d3ecf321/recipes/diligent-core/all/conanfile.py?plain=1#L123-L124

https://github.com/conan-io/conan-center-index/blob/17f3c60b7960158c34deb3c7eb3f20f6d3ecf321/recipes/vulkan-validationlayers/all/dependencies/dependencies-1.3.224.1.yml?plain=1#L3

Happy coding 🐸
