### ISSUE TITLE
Why is conandata.yml so restrictive?

### ISSUE THREAD

**Issue by rweickelt** [conan-io/conan-center-index#1754]
By design, conandata.yml and conanfile.py complement each other very well. Developers can split their recipes into a declarative part (yml) and an imperative part (recipe). According to the [conan documentation](https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html), the format is flexible.

Unfortunately, the format of conandata.yml in conan-center is very restrictive; overly restrictive in my opinion. It allows only source and patch URLs and integrity information. This forces developers to spill declarative data over their recipes and leaves most of the benefits of the yml file unused. See https://github.com/conan-io/conan-center-index/blob/master/recipes/cspice/all/conanfile.py#L31 for example which perverts the idea behind conandata.yml.

That brings me to the question: What is the motivation behind the current restriction?

If it is for consistency, wouldn't it be better, to define some basic rules and give developers a bit more freedom so that they move all declarative data out of their recipe?

See also #1411.

**Comment by Croydon** [comment]
Consistency is important for CCI. If every contributor modifies just a little bit here and there it is like a snowball effect and we are ending up with fundamental different recipes structures

We are extending the structure of the `conandata.yml` when necessary, for example, we can now add download mirrors, which was not the case at the beginning

I'm assuming you find the structure too restrictive mostly because you want to re-package binaries which we try to avoid. If you download source code, it should be the same for all platforms and targets

**Comment by rweickelt** [comment]
> I'm assuming you find the structure too restrictive mostly because you want to re-package binaries which we try to avoid. If you download source code, it should be the same for all platforms and targets

Have you actually looked at my motivational example linked above? It has nothing to do with repackaging binaries.

https://github.com/conan-io/conan-center-index/blob/master/recipes/cspice/all/conanfile.py#L31

**Comment by Croydon** [comment]
I had a quick look, but confused it with your qbs PR, sorry.

`conandata.yml` was invented with the start of CCI to have downloads in a declarative way which can be controlled and checked. So yes, in these cases it might be slightly annoying, but so far this seems to be edge cases 🤔

**Comment by uilianries** [comment]
Indeed it's an edge case. What @Croydon said before fits very well the conandata.yml design. If we allow your case, we will need to allow any other edge and so on, but we don't want a crazy stuff in conandata.yml, that's why we allow only what's usual.

**Comment by jgsogo** [comment]
I'm closing this issue. We can open the discussion again if we find more recipes that would benefit from more flexibility.

Thanks!
