### ISSUE TITLE
[package] expat/all: EXPAT_LARGE_SIZE not defined / no option 

### ISSUE THREAD

**Issue by duncanspumpkin** [conan-io/conan-center-index#17541]
### Description

Some Expat features do not work when xml files are >2GB on some systems (Windows or any system with 32bit `long`). It would be useful if the EXPAT_LARGE_SIZE configuration option was exposed within the conan configuration. According to expat "It may not be supported by all compilers, and is turned off by default." (imho I think it should be on by default)

The test code within conan-centre is actually already designed around having the flag as configuring with EXPAT_LARGE_SIZE should set the XML_LARGE_SIZE define. This would need to be taken into account if adding this option.

### Package and Environment Details

* Package Name/Version: **expat/2.x**
* Operating System+version: **Windows 10**
* Compiler+version: **MSVC 2017**
* Conan version: **conan 1.56**
* Python version: **Python 3.8**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.toolset=v142
compiler.version=16
compiler.cppstd=17
os=Windows
os_build=Windows
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

`conan install -r expat/2.5.0`

Open a very large xml file. Use `XML_GetCurrentByteIndex` on an element that is beyond the 2GB line. Return value will be invalid.

### Logs

N/A

**Comment by toge** [comment]
@duncanspumpkin 
Thank you for your information.

I created a PR to solve it.
Please point out if this PR is not appropriate.
