### ISSUE TITLE
[gtest] 'cmake' is not recognized when building from sources

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan-center-index#176]
Since cmake is needed to build from sources, shouldn't the `cmake_installer` be declared as a `build_requires`?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **gtest/1.8.1**
  * Operating System+version: **Linux**
  * Compiler+version: **GCC 7**
  * Conan version: **conan 1.18.4**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
compiler.exception=sjlj
compiler.threads=win32
os_build=Windows
arch_build=x86_64
os=Windows
arch=x86_64
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
1. add gtest as a requirement

`self.requires("gtest/1.8.1@bincrafters/stable")`

2. try install the dependency, building from sources

```
mkdir build
cd build
conan install .. --build=missing
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
gtest/1.8.1@bincrafters/stable: Copying sources to build folder
gtest/1.8.1@bincrafters/stable: Building your package in C:\Users\<user>\.conan\data\gtest\1.8.1\bincrafters\stable\build\20bb622ab675bc6573366bc235363499e62d112e
gtest/1.8.1@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
gtest/1.8.1@bincrafters/stable: Calling build()
'cmake' is not recognized as an internal or external command,
operable program or batch file.
gtest/1.8.1@bincrafters/stable:
gtest/1.8.1@bincrafters/stable: ERROR: Package '20bb622ab675bc6573366bc235363499e62d112e' build failed
gtest/1.8.1@bincrafters/stable: WARN: Build folder C:\Users\<user>\.conan\data\gtest\1.8.1\bincrafters\stable\build\20bb622ab675bc6573366bc235363499e62d112e
ERROR: gtest/1.8.1@bincrafters/stable: Error in build() method, line 62
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 57
        cmake.configure()
        ConanException: Error 1 while executing
...
```
</details>

**Comment by danimtb** [comment]
This is a good question and something we should document. We generally consider CMake as a standard tool to have installed in your system. Having "cmake_installer" as a build require in all the recipes that use it will be an overkill. However, I think the "cmake_installer" could be useful to use in your profile:

```
[build_requires]
cmake_installer/....@....
```
Also notice, that the `gtest` you are using is the one from Bincrafters, not from Conan Center Index, that should be just `gtest/1.8.1` (without user and channel)

**Comment by GordonJess** [comment]
Hmm I wonder why this  would be overkill exactly?  Even if it is a requirement in all recipes, conan will only download and install it once, right?  As long as the versions are compatible.

I already have `cmake_installer` for recipes which are built with cmake, including the recipe which is dependent on gtest.  I want to be able to see in my dependency graph which version of cmake my packages were built with.  I didn't expect I'd have to define it globally too.

**Comment by SSE4** [comment]
@GordonJess it doesn't scale well - each CMake-based recipe has to refer to `cmake_installer`.
and besides `cmake_installer`, you will also need `make` to build it, so should it contain also `make_installer` reference (as CMake doesn't build thing itself, it's just meta build system). and make by itself depends on other software (e.g. BSD install, coreutils, etc.), so how deep should we go in this case? I think it's better to be practical in this case, and assume developer has minimal set of tools installed already.

**Comment by Croydon** [comment]
Also by not adding it into the recipes it is easier to leave it to consumers which versions and tools they use and how they are managed

**Comment by GordonJess** [comment]
Ah ok, makes sense.  So is adding the cmake installer to the profile requires the recommended way of using it?  And I should remove it from all my recipe requires to avoid any version conflicts?

**Comment by danimtb** [comment]
that is the recommended way indeed

**Comment by SSE4** [comment]
@danimtb do you think if it's good to update `FAQ` and close the issue?

**Comment by danimtb** [comment]
Sure, I will add it to the FAQ

**Comment by danimtb** [comment]
Added to the FAQ https://github.com/conan-io/conan-center-index/wiki/FAQ#why-recipes-that-use-build-tools-like-cmake-that-have-packages-in-conan-center-do-not-use-it-as-a-build-require-by-default

Thanks!
