### ISSUE TITLE
[package] libjpeg/9d: Broken cross compilation using Autotools instead of AutoToolsBuildEnvironment 

### ISSUE THREAD

**Issue by Thiesius** [conan-io/conan-center-index#17630]
### Description

The recipe used AutoToolsBuildEnvironment before and everything was working fine. However this recipe received an update since then and cross-compilation no longer works as the script fails to invoke configure in cross-compile mode.

I managed to hotfix this by restoring what was in original recipe.
at line 127 in build()
I changed
```
            autotools = Autotools(self)
            autotools.configure()
```
to         
```
            autotools = AutoToolsBuildEnvironment(self)
            autotools.configure(configure_dir=self.source_folder)
```

And also added the import 
`from conans import AutoToolsBuildEnvironment`

If you check the log, you can see that I get the line: `Cross-build from 'Linux:x86_64' to 'Linux:armv8'`
from conan. However the configure is invoked incorrectly anyways.

Btw.: package **xz_utils** have the same issue. I didn't investigate any further and just copied the prebuilt cache from CI/CD and changed metadata.

### Package and Environment Details

* Package Name/Version: **libjpeg/9d**
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **Custom cross GCC 11.2 targeting AARCH64**
* Docker image: **proprietary**
* Conan version: **conan 1.60.0**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
arch=armv8
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
OpenCV:build_opencv_python2=False
OpenCV:shared=False
OpenCV:with_1394=False
OpenCV:with_cuda=False
OpenCV:with_ffmpeg=True
OpenCV:with_gstreamer=True
OpenCV:with_gtk=True
OpenCV:with_ipp=False
OpenCV:with_itt=False
OpenCV:with_png=True
OpenCV:with_tbb=False
OpenCV:with_tiff=False
OpenSSL:no_zlib=True
OpenSSL:shared=True
[build_requires]
[env]
AR=aarch64-cortex_a57-linux-gnu-ar
AS=aarch64-cortex_a57-linux-gnu-as
CC=aarch64-cortex_a57-linux-gnu-gcc
CHOST=aarch64-cortex_a57-linux-gnu
CONAN_CMAKE_POSITION_INDEPENDENT_CODE=1
CONAN_CMAKE_TOOLCHAIN_FILE=/home/username/PATH_TO_REPO/cmake/ToolchainBLABLA.cmake
CXX=aarch64-cortex_a57-linux-gnu-g++
RANLIB=aarch64-cortex_a57-linux-gnu-ranlib
RC=aarch64-cortex_a57-linux-gnu-windres
STRIP=aarch64-cortex_a57-linux-gnu-strip
TARGET_ROOTFS=/target_env/rootfs

### Steps to reproduce

I suppose downloading the aarch64 cross-compiler and using it as compiler could do the trick. I cannot provide full environment.

`/usr/local/bin/conan install libjpeg/9d@ --build missing --env CONAN_CMAKE_TOOLCHAIN_FILE=/home/username/PATH_TO_REPO/cmake/ToolchainBLABLA.cmake --env TARGET_ROOTFS=/target_env/rootfs --profile /home/username/PATH_TO_REPO/conan_profiles/aarch64/GNU-11
`

### Logs

<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=armv8
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
OpenCV:build_opencv_python2=False
OpenCV:shared=False
OpenCV:with_1394=False
OpenCV:with_cuda=False
OpenCV:with_ffmpeg=True
OpenCV:with_gstreamer=True
OpenCV:with_gtk=True
OpenCV:with_ipp=False
OpenCV:with_itt=False
OpenCV:with_png=True
OpenCV:with_tbb=False
OpenCV:with_tiff=False
[build_requires]
[env]
AR=aarch64-cortex_a57-linux-gnu-ar
AS=aarch64-cortex_a57-linux-gnu-as
CC=aarch64-cortex_a57-linux-gnu-gcc
CHOST=aarch64-cortex_a57-linux-gnu
CONAN_CMAKE_POSITION_INDEPENDENT_CODE=1
CONAN_CMAKE_TOOLCHAIN_FILE=/home/username/PATH_TO_REPO/cmake/ToolchainBLABLA.cmake
CXX=aarch64-cortex_a57-linux-gnu-g++
RANLIB=aarch64-cortex_a57-linux-gnu-ranlib
RC=aarch64-cortex_a57-linux-gnu-windres
STRIP=aarch64-cortex_a57-linux-gnu-strip
TARGET_ROOTFS=/target_env/rootfs
Installing package: libjpeg/9d
Requirements
    libjpeg/9d from 'conancenter' - Cache
Packages
    libjpeg/9d:115c8fa606e08a868a5ec8073c26c1a096c7263b - Build

Cross-build from 'Linux:x86_64' to 'Linux:armv8'
Installing (downloading, building) binaries...
libjpeg/9d: Copying sources to build folder
libjpeg/9d: Building your package in /home/username/.conan/data/libjpeg/9d/_/_/build/115c8fa606e08a868a5ec8073c26c1a096c7263b
libjpeg/9d: Generator txt created conanbuildinfo.txt
libjpeg/9d: Calling generate()
libjpeg/9d: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
libjpeg/9d: Aggregating env generators
libjpeg/9d: Calling build()
libjpeg/9d: Apply patch (portability): Add support to generate DLL on Windows
libjpeg/9d: Calling:
 > "/home/username/.conan/data/libjpeg/9d/_/_/build/115c8fa606e08a868a5ec8073c26c1a096c7263b/src/configure" '--disable-shared' '--enable-static' '--prefix=/' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' 
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... aarch64-cortex_a57-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/home/username/.conan/data/libjpeg/9d/_/_/build/115c8fa606e08a868a5ec8073c26c1a096c7263b/build-release':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
libjpeg/9d: 
libjpeg/9d: ERROR: Package '115c8fa606e08a868a5ec8073c26c1a096c7263b' build failed
libjpeg/9d: WARN: Build folder /home/username/.conan/data/libjpeg/9d/_/_/build/115c8fa606e08a868a5ec8073c26c1a096c7263b/build-release
ERROR: libjpeg/9d: Error in build() method, line 127
    autotools.configure()
    ConanException: Error 1 while executing "/home/username/.conan/data/libjpeg/9d/_/_/build/115c8fa606e08a868a5ec8073c26c1a096c7263b/src/configure" '--disable-shared' '--enable-static' '--prefix=/' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' 

```

</details>

**Comment by Thiesius** [comment]
Tried alternative way to replicate:

1) Pull `dockcross/linux-arm64-full:latest` from dockerhub
2) Start it with `docker run -it dockcross/linux-arm64-full:latest /bin/bash`
3) Inside `pip3 install conan==1.60 --upgrade`
4) Paste the profile I provided before. Remove `CONAN_CMAKE_TOOLCHAIN_FILE` and change all tools name from
`aarch64-cortex_a57-linux-gnu-XXX` to `aarch64-buildroot-linux-gnu-XXX`
5) Run `conan install libjpeg/9d@ --build missing --profile PROF_YOU_HAVE_SAVED`

Once again correct `Cross-build from 'Linux:x86_64' to 'Linux:armv8'` followed by incorrect

```
libjpeg/9d: Calling:
 > "/root/.conan/data/libjpeg/9d/_/_/build/bef5299822e42e96f0e878760beb2bf99ad4cd55/src/configure" '--disable-shared' '--enable-static' '--prefix=/' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include'
 ```

```
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
```

Be aware that if your kernel has in-built support for running aarch64 binaries with binfmt you might be able to pass configure as the configure will be able to run the "test" program. However what's important: configure should get `--host` passed as in the case  with AutoToolsBuildEnvironment

**Comment by SpaceIm** [comment]
Your profile is broken with recipes migrated to v2 API. You must use 2 profiles for cross-compilation.

**Comment by Thiesius** [comment]
Thank you kindly for the hint. Seems like using two profiles did the trick as suggested. 

Still a bit confusing that the `Cross-build from 'Linux:x86_64' to 'Linux:armv8'` message gets shown. It's not the first time some of the recipes got broken for us (even native build) when the new revision was published, so I automatically expected it was just a recipe issue. 

I suppose that moving the working "recipe set" to private conan remote would be a way to ensure the build system doesn't randomly break on us, since we rely on conan.cmake which doesn't support Conan V2 yet.

Thanks again 😄
