### ISSUE TITLE
[request] openimageio/2.4.11.1

### ISSUE THREAD

**Issue by birsoyo** [conan-io/conan-center-index#17674]
### Package Name/Version

openimageio/2.4.11.1

### Changelog

https://github.com/OpenImageIO/oiio/releases/tag/v2.4.11.1

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by czoido** [comment]
Thanks for reporting, closing this as newer versions are already available.
