### ISSUE TITLE
[request] di/1.3.0

### ISSUE THREAD

**Issue by yehorror** [conan-io/conan-center-index#17696]
### Package Name/Version

di/1.3.0

### Changelog

https://github.com/boost-ext/di/releases/tag/v1.3.0

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.
I found no changelogs for new release except bugfixes: https://github.com/boost-ext/di/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+closed%3A2020-07-21..2023-05-23+

**Comment by czoido** [comment]
Thanks for reporting, closing this it's already available.
