### ISSUE TITLE
[proposal] reorganize grpc, grpc-proto, googleapis and google-cloud-cpp

### ISSUE THREAD

**Issue by coryan** [conan-io/conan-center-index#17755]
## Objective 

Create recipes for `google-cloud-cpp`, `grpc`, and `Protobuf` that work correctly and can be upgraded with minimal effort.

## Background

[googleapis/googleapis] contains just service definitions as proto files, and Bazel rules to generate the gRPC and Protobuf code from these proto files. It is not considered a "package" by the teams that maintain it at google, just a location where other projects can find the proto files *and* they can use to generate the packages for each language.

[google-cloud-cpp](https://github.com/googleapis/google-cloud-cpp) vendors-in the protos from [googleapis/googleapis]. It contains code designed to work with specific versions of googleapis/googleapis.  It almost never works with older versions. It may work with newer versions, but there are no guarantees.  `google-cloud-cpp` depends on `grpc`.

[gRPC](https://github.com/grpc/grpc) *appears* to (but in fact does not) vendor some protos from [googleapis/googleapis]. It also appears to vendor some protos from [grpc-proto](https://github.com/grpc/grpc-proto).

* Most of the proto files that are copied into gRPC are used only for tests.
* A few proto files are used via [upb](https://github.com/protocolbuffers/upb). upb is intended for "direct consumption", meaning it is intended to be vendored in.  The team does not plan to release packages.
* The CMake commands to [download googleapis](https://github.com/grpc/grpc/blob/acbac3deee35708b2da1722948bce42caac7ac33/CMakeLists.txt#L354-L362) never execute in Conan builds, as the directory guarding their download always exists.

Note that there is no conflict between the `googleapis` files used by `google-cloud-cpp` and the files used in the `grpc`. Either the files are used in tests, or they are compiled with different "protobuf" libraries, designed to produce different symbols.

Meanwhile, it is impossible to make `grpc` or `grpc-proto` use a range of `googleapis` versions. Ranges for the googleapis versioning scheme (`cci.${date}`) do no work on CCI with Conan v1 (see #17598).

## Problem

Un-vendoring `googleapis` and `grpc-proto` from the `grpc` and `google-cloud-cpp` recipes has made these recipes hard to maintain, and practically impossible to upgrade.

## Proposal

Vendor-in `googleapis` into `google-cloud-cpp` and break the dependency between `grpc` and `grpc-proto`. This would appear to "vendor-in" some protos into `grpc`, but for the reasons mentioned above, this is not the case. The protos are unused in the recipe, or compiled with `upb`.

## See Also

* https://github.com/conan-io/conan-center-index/pull/17598#issuecomment-1568463325
* https://github.com/conan-io/conan-center-index/pull/16438#issuecomment-1520207786

[googleapis/googleapis]: https://github.com/googleapis/googleapis

**Comment by coryan** [comment]
@jcar87 how would you like me to handle the current version of the recipes.  I can see two ways forward:

- Change the recipes to stop using `googleapis` with their current versions.  That seems cleaner, but will make it impossible for people to reproduced their older builds.
- Change the recipes to stop using `googleapis` in newer versions.  I am not sure the extra complexity is worth it, but I not as familiar with the needs of the Conan community as you are.

**Comment by coryan** [comment]
I have taken the first of the two options outlined above.

**Comment by jcar87** [comment]
Hi @coryan - thanks for the detailed report.

I believe the first option is probably the easiest solution. If it helps, perhaps consider starting with the google-cloud-cpp directly (to revert back to using the vendored-in version), in case that unblocks the overall efforts.

> That seems cleaner, but will make it impossible for people to reproduced their older builds.

Recipes in Conan Center are all stored in the remote with recipe revisions enabled (which is opt-in in Conan 1.x, and the behaviour in Conan 2.0), so the ability of using earlier revisions of recipe for reproducibility is there, ideally via lockfiles (either via [lockfiles](https://docs.conan.io/2.0/tutorial/versioning/lockfiles.html)), although users also have the option to specify the required recipe revision in a `self.requires()` statement.
