### ISSUE TITLE
[package] gtest/1.10.0: The cmake generator sometimes creates the target CONAN_PKG::GTest instead of the expected CONAN_PKG::gtest

### ISSUE THREAD

**Issue by Knitschi** [conan-io/conan-center-index#1775]
I have a cmake based project that I build on Windows and Linux. 
I use
````
include(${some_path}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
````
in order to get the `CONAN_PKG::` targets.

The problem is, that the `conanbuildinfo.cmake` file creates a `CONAN_PKG::GTest` target on the Windows machine and a `CONAN_PKG::gtest` target on a Linux machine. This forces me to add some extra cmake code to compensate for the difference in the used cases. I would rather have conan provide the same target name on all platforms.

### Package and Environment Details Windows
  * Package Name/Version: gtest/1.10.0
  * Operating System+version 1: Windows 10
  * Compiler+version 1: Visual Studio 2019 16.6.0
  * Conan version: 1.25.2
  * Python version: Python 3.6.6

### Package and Environment Details Linux
  * Package Name/Version: gtest/1.10.0
  * Operating System+version 1: Ubuntu 20.04 LTS
  * Compiler+version 1: GCC 9
  * Conan version: 1.25.1
  * Python version: Python 3.8.2

### Conan profile Windows

```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.toolset=v142
build_type=Debug
[options]
[build_requires]
[env]
```

### Conan profile Linux

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
build_type=Debug
compiler.libcxx=libstdc++11
[options]
[build_requires]
```

### Conanfile

```
[requires]
qt/5.12.6@bincrafters/stable
gtest/1.10.0
gsl-lite/0.36.0


[options]
openssl:no_asm=True
qt:shared=True
# These features were removed to fix compile errors in the Qt package
qt:with_mysql=False
qt:with_sqlite3=False
qt:with_pq=False
qt:with_harfbuzz=False
qt:openssl=False
qt:with_libjpeg=False
[generators]
cmake
```

**Comment by uilianries** [comment]
I can't see the problem, Windows is non-case-sensitive, thus CONAN_PKG::gtest also works on Windows.

**Comment by Knitschi** [comment]
It is not a problem caused by names in the file system. It is a problem of the CMake code in the generated `conanbuildinfo.cmake` file. As far as I know CMake code is case sensitve on Linux and Windows.

**Comment by Knitschi** [comment]
It is getting misterious now. I just ran the same conan command on a different Windows 10 machine and here I suddenly get the lower case target name in the `conanbuildinfo.cmake` file. I made sure that both machines use the same conan version which is now `1.26.0`. 

To counter the problem I use the following CMake code now:
```
if(TARGET CONAN_PKG::gtest)
	set(CONAN_PKG_GTEST CONAN_PKG::gtest)
elseif(TARGET CONAN_PKG::GTest)
	set(CONAN_PKG_GTEST CONAN_PKG::GTest)
endif()
```

**Comment by Croydon** [comment]
Did you make sure that both recipes use the same recipe version of gtest?

Either remove your local versions or use `conan install --update` or similar

**Comment by Croydon** [comment]
You should have at least these changes in your local copies 

https://github.com/conan-io/conan-center-index/commit/b0263a877ecaaf69a8764f669475ba4071f5f87e#diff-0eff0fe00b28eaa1742e09c6900a6cde

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as this should have been fixed in latest versions.
Feel free to reopen this issue or create a new ticket if the problem persists.
Happy coding! 😄
