### ISSUE TITLE
[request] mongo-cxx-driver/3.7.1

### ISSUE THREAD

**Issue by cdalessio0131** [conan-io/conan-center-index#17792]
### Package Name/Version

mongo-cxx-driver/3.7.1

### Changelog

https://github.com/mongodb/mongo-cxx-driver/releases/tag/r3.7.1

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by toge** [comment]
@cdalessio0131 
Thank you for your request.
Although mongo-cxx-driver 3.7.2 has already been released, 
I have created a recipe for 3.7.2.
If you need mongo-cxx-driver 3.7.1, please notice me.
