### ISSUE TITLE
[request] LibXft/2.3.8 conan2 migration

### ISSUE THREAD

**Issue by jasuramme** [conan-io/conan-center-index#17818]
### Package Name/Version

libxft/2.3.8

### Changelog

https://gitlab.freedesktop.org/xorg/lib/libxft/-/blob/master/NEWS

### Context about the new update

I kindly ask to help with migration libxft to the conan 2.0
The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by jasuramme** [comment]
Created related PR
https://github.com/conan-io/conan-center-index/pull/17817

**Comment by czoido** [comment]
Thanks for reporting, closing this it's already available.
