### ISSUE TITLE
[service] Conan v2 pipeline fails with "Invalid JSON String" error

### ISSUE THREAD

**Issue by Woazim** [conan-io/conan-center-index#17847]
### What is your problem/feature request?

I try to update the recipe for imagl. It is widely inspired from working recipes of other packages. But for this one, I have a not helping ["Invalid JSON String" error](https://github.com/conan-io/conan-center-index/pull/16698#issuecomment-1579039855) from @conan-center-bot with no log.

Is it possible to have a more helping message from CI? (a raw log, or something that can be used to understand what's wrong.)

Thank you in advance.

**Comment by uilianries** [comment]
There is a `print` in the recipe causing trouble when capturing the output to generate the JSON file. Removing the print fixes the situation.
