### ISSUE TITLE
[request] Metal Cpp By Apple

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan-center-index#17848]
### Package Name/Version

n/a

### Webpage

https://developer.apple.com/metal/cpp/

### Source code

https://developer.apple.com/metal/cpp/

### Description of the library/tool

Hi,

Apple launch the metal-cpp:
https://developer.apple.com/metal/cpp/

Maybe you can add support for the Apple official metal library implementation for C++.

Thanks.

**Comment by irieger** [comment]
Hey, just saw your request when checking if someone already started a PR on metalcpp. Wanted to inform that I started to work on this today as I use it myself and would like to switch from having a copy in my source tree to having a package. Will update you when it works and I have the pull request created.
