### ISSUE TITLE
[package] nodejs/18.15.0: glibc version check might fail on some linux distributions

### ISSUE THREAD

**Issue by nbukuli** [conan-io/conan-center-index#17913]
### Description

In case of linux ``nodejs`` conan recipe checks the version of glibc on the build machine. The version of the installed glibc is figured out via the first line of the output of ``ldd --version`` command. 

This line may vary among the various linux distibutions. To name some of them:

| distro | version| output |
| ---- | ---- | ---- | 
| gentoo | head | ldd (Gentoo 2.34-r13 p17) 2.34 |
| ubuntu | 18.04.6 | ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27 |
| debian | 11 | ldd (Debian GLIBC 2.31-13+deb11u6) 2.31|
| fedora | 276 | ldd (GNU libc) 2.26 |

The current regular expression checks literal ``GLIBC`` then the major and minor part of the version number **inside the parentheses**, however as we can see from the table above ``GLIBC`` is not always present.

It might be more roboust to check the version number **at the end of the line.**

### Package and Environment Details

* Package Name/Version: **nodejs/18.15.0**
* Operating System+version: **Linux gentoo 28 (head)**
* Compiler+version: **GCC 7.5.0**
* Docker image: **N/A**
* Conan version: **conan 1.60.0**
* Python version: **Python 3.9.13**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan create recipes/nodejs/all nodejs/18.15.0 -pr default

### Logs

<details><summary>Click to expand log</summary>

```
# ...
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] OK
[HOOK - conan-center.py] post_export(): [DEFAULT SHARED OPTION VALUE (KB-H050)] OK
[HOOK - conan-center.py] post_export(): [LICENSE PUBLIC DOMAIN (KB-H056)] OK
nodejs/18.15.0: A new conanfile.py version was exported
nodejs/18.15.0: Folder: /home/nbukuli/.conan/data/nodejs/18.15.0/_/_/export
nodejs/18.15.0: Using the exported files summary hash as the recipe revision: 461f35fe0fe2215b362cf52f4684c775 
nodejs/18.15.0: Package recipe modified in export, forcing source folder removal
nodejs/18.15.0: Use the --keep-source, -k option to skip it
nodejs/18.15.0: Removing the local binary packages from different recipe revisions
nodejs/18.15.0: Exported revision: 461f35fe0fe2215b362cf52f4684c775
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: nodejs/18.15.0: Error in validate() method, line 51
        if Version(self._glibc_version) < '2.27':
while calling '_glibc_version', line 41
        return str(re.search(r'GLIBC (\d{1,3}.\d{1,3})', buff.getvalue()).group(1))
        AttributeError: 'NoneType' object has no attribute 'group'
```

</details>

**Comment by wdobbe** [comment]
In addition to the distros mentioned in the description, the current nodejs package also fails on OpenSuse.
ldd --version output on OpenSuse 15.5 is:
```
ldd (GNU libc) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by wdobbe** [comment]
@uilianries So what you are saying is that the check for the glibc version should be removed from the recipe ?

I have zero knowledge of nodejs but it is a dependency of qtwebengine. The current recipe breaks the build on any Linux distro that is not (derived from) Debian because the check for the glibc version fails, not because of glibc incompatability.

**Comment by tsondergaard** [comment]
@uilianries ,

> This is not a bug, but an expected behavior.
> 
> All Linux packages are generated using Docker images listed here: https://github.com/conan-io/conan-docker-tools/
> 
> As we have a range of versions to be attended, we prefer keeping more older compiler versions to obey an older version of GLIBC. The result is supporting backward versions, but as trade-off, some newer features are not available.
> 
> For Conan 2.x docker images, we use Ubuntu 16.04 to build any package, but with Conan 1.x is a mix, we have until 20.04.
> 
> In case you are having failures due GLIBC incompatibility, the recommendation is building the package from sources, so you can the most aligned GLIBC possible version.

No, it is a bug that prevents the nodejs package from building on lots of distributions, including Fedora and RHEL. See #22169 and  #21079 for more context.
