### ISSUE TITLE
Is unicode a reasonable default for log4cplus

### ISSUE THREAD

**Issue by ngrodzitski** [conan-io/conan-center-index#1791]
By default the recipie for log4cplus uses unicode characters.
Is this is a deliberate choice? IMO, ordinary character set must be a default option.

https://github.com/conan-io/conan-center-index/blob/c9c9a1d28aebe54ea207cae2b23becafde713b16/recipes/log4cplus/all/conanfile.py#L33

**Comment by SSE4** [comment]
I don't see any reason why Unicode shouldn't be a default in 2020. supporting multiple languages and scripts is somewhat absolutely common right now, and it's very easy to encounter characters from foreign languages due to the globalization.

**Comment by ngrodzitski** [comment]
Well the problem is that with unicode enabled it uses only `wstring` and messages with `std::string`s becomes unacepted.

Examining libs:
```
$ readelf -Ws path_no_unicode/liblog4cplus.a | c++filt -n | fgrep "log4cplus::Logger::log"
   100: 0000000000000610    27 FUNC    GLOBAL DEFAULT   14 log4cplus::Logger::log(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int, char const*) const
   102: 0000000000000660    10 FUNC    GLOBAL DEFAULT   14 log4cplus::Logger::log(log4cplus::spi::InternalLoggingEvent const&) const

$ readelf -Ws path_no_unicode/liblog4cplus.a | c++filt -n | fgrep "log4cplus::Logger::log"
   100: 0000000000000610    27 FUNC    GLOBAL DEFAULT   14 log4cplus::Logger::log(int, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, char const*, int, char const*) const
   102: 0000000000000660    10 FUNC    GLOBAL DEFAULT   14 log4cplus::Logger::log(log4cplus::spi::InternalLoggingEvent const&) const
```
So in the exclusive-condition case (only chars or only wchars) is it still a better option to select unicode only?

**Comment by SSE4** [comment]
I understand, but if project doesn't support enabling both `std::wstring` and `std::string` simultaneously you only have two choice:
1. use `std::string`, this means no Unicode on certain platforms (e.g. Windows), also you'll need to convert from `std::wstring` to `std::string` when passing strings from system APIs to log4cplus (and vice versa)
2. use `std::wstring`, this means convert from `std::string` to `std::wstring` when passing strings from system APIs to log4cplus (and vice versa).
the option #2 sounds like a better default. for your project you always may override defaults (e.g. by using `log4cplus:unicode=False`. you also may leverage per-system profiles (using `std::string` on Linux, `std::wstring` on Windows).
