### ISSUE TITLE
Setting CMake variable for dependency package

### ISSUE THREAD

**Issue by ViktarHasiul231862** [conan-io/conan-center-index#17974]
Hi,

I am using Conan 2.0.4 and I have wt/4.9.1 as a dependency in my package. I want to set two variables, so they are used by dependency package CMake during building phase. In current recipe one of these variables is not set at all and the other one is always set to false:
tc.variables["ENABLE_HARU"] = False

Is it possible to overwrite these variables that were set in the original recipe from my conanfile.py? Should I create an issue to change the original recipe?

Best regards

**Comment by Jihadist** [comment]
> Is it possible to overwrite these variables that were set in the original recipe from my conanfile.py?

No, conan does not support overriding from user recipe. It should be managed with conan options

> Should I create an issue to change the original recipe?

Yep, or you may create pull request with fix :)

**Comment by ViktarHasiul231862** [comment]
Thank you:)
