### ISSUE TITLE
[request] sfml/2.6.0

### ISSUE THREAD

**Issue by ChrisThrasher** [conan-io/conan-center-index#17989]
### Package Name/Version

sfml/2.6.0

### Changelog

https://github.com/SFML/SFML/releases/tag/2.6.0

### Context about the new update

SFML 2.6.0 was released earlier today.

https://github.com/conan-io/conan-center-index/compare/master...ChrisThrasher:conan-center-index:sfml/2.6.0

I attempted this myself and made some progress. I was able to fix some broken patches and remove two patches that are now no longer necessary. The blocking issue was that we need to include glad/gl.h from the extlibs/ directory, however that whole directory gets deleted. I don't believe glad/gl.h is actually part of glad since as you can see in the above patch I depended on glad but the compiler still could not find that header. Using the in-tree version may be suitable.

There were also some issues not being able to find Audio module dependencies like Vorbis and FLAC that I couldn't make sense of either.

**Comment by toge** [comment]
@ChrisThrasher 
Thank you for your information.
It help me a lot.

>  I don't believe glad/gl.h is actually part of glad since as you can see in the above patch I depended on glad but the compiler still could not find that header. Using the in-tree version may be suitable.

I agree with you.
`glad/gl.h` seems to be generated from https://gen.glad.sh/.
I decided to use `glad` in `extlibs`.

If possible, please review https://github.com/conan-io/conan-center-index/pull/18069.
