### ISSUE TITLE
[service] Add GCC 9 support

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#18]
The service should generate packages for GCC 9.
If added the wiki should be updated as well: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Comment by uilianries** [comment]
Me: spent days working on this, no errors found
Croydon: 2 min after the release, "Hey, some compilers are missing"
Me: :man_facepalming:

**Comment by lasote** [comment]
Gcc9 packages have been generated for all the packages already merged and also for the open PRs! From now on, the PRs will build also GCC9 configs.
Thanks, @Croydon !!

**Comment by lasote** [comment]
Note: The packages will be available on Bintray conan-center during tomorrow. I've pending the "promotion" task. But any build on this index repository depending on gcc9 and clang8 will find the packages.
