### ISSUE TITLE
[package] sqlite3/3.29.0: Invalid cross-building from OSX to iOS

### ISSUE THREAD

**Issue by krisanovdev** [conan-io/conan-center-index#1806]
### Package and Environment Details
  * Package Name/Version: sqlite3/3.29.0
  * Operating System+version: MacOS 10.13
  * Compiler+version: clang 10.0
  * Conan version: 1.20.4
  * Python version: 3.7.2

### Conan profile (ios_profile.txt)
[settings]
os=iOS
os.version=7.0
arch=armv8
os_build=Macos
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
cppstd=14
build_type=Release

### Conanfile.txt
[requires]
sqlite3/3.29.0@bincrafters/stable

[generators]
make

### Steps to reproduce
1. conan install <conanfile.txt> --profile <ios_profile>
2. check resulting libsqlite3.a architecture

## AR
sqlite3 library has x86_64 architecture

## ER
sqlite3 library has arm64 architecture

**Comment by SSE4** [comment]
thanks for the feedback! appears to be a conan issue, I'll create a new ticket

**Comment by perseoGI** [comment]
I'm closing this issue as it was solved in https://github.com/conan-io/conan/pull/7164
