### ISSUE TITLE
[request] kangaru/4.2.4

### ISSUE THREAD

**Issue by AGreat1** [conan-io/conan-center-index#1807]
### Package Details
  * Package Name/Version: gracicot/kangaru/4.2.4
  * Website: https://github.com/gracicot/kangaru/wiki
  * Source code: https://github.com/gracicot/kangaru

### Description Of The Library / Tool
This is a straight-forward **header-only** library that provides a DI mechanism.

**Comment by gracicot** [comment]
Even though it's a header only library, I rely on CMake to generate some configuration header. I properly export a CMake target and the library is installable. It expects either to be installed or used from the build tree.

**Comment by uilianries** [comment]
Hi @AGreat1 ! Thanks for your request. May you interested in creating this recipe? It would be great having you contribution.

There is a full tutorial here how to contribute: https://github.com/conan-io/conan-center-index/wiki#adding-packages-to-conancenter

Regards!

**Comment by AGreat1** [comment]
I'll give it a try.

**Comment by AGreat1** [comment]
I'm not sure here, but am I correct that [this](https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#kb-h019-cmake-file-not-in-build-folders) paragraph is out-dated, and `builddirs` is now `build_modules` ?

**Comment by AGreat1** [comment]
also [this](https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#kb-h041-no-final-endline) is a problem not with the package itself, rather with the library being packaged, right?

**Comment by uilianries** [comment]
> I'm not sure here, but am I correct that [this](https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#kb-h019-cmake-file-not-in-build-folders) paragraph is out-dated, and `builddirs` is now `build_modules` ?

No, it means if you need to copy any cmake file to package folder, you need to declare it in builddirs, but only for very specific cases when the cmake file provides a macro, otherwise, it should be removed. For example:

https://github.com/conan-io/conan-center-index/blob/554f6e8c0e922c4dc5c1f13252b45e8743384542/recipes/doctest/2.x.x/conanfile.py#L41

**Comment by uilianries** [comment]
> also [this](https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#kb-h041-no-final-endline) is a problem not with the package itself, rather with the library being packaged, right?

No, only the the package. The library won't be checked. However, all files (custom cmake file, patches, test_package) in your package will be checked.

**Comment by AGreat1** [comment]
> No, it means if you need to copy any cmake file to package folder, you need to declare it in builddirs, but only for very specific cases when the cmake file provides a macro, otherwise, it should be removed.

I removed it.

> No, only the the package. The library won't be checked. However, all files (custom cmake file, patches, test_package) in your package will be checked.

Later I realized the error included the problematic file. Trailing whitespace removed.

**Comment by AGreat1** [comment]
@gracicot In the package I made the reverse_destruction option true by default, contrary to your decision your cmake file. The rationale behind it is that you kept it that way for compatibility reasons, but this package has no predecessor to keep that compatibility with. If you don't like that, then I'll change it.

**Comment by gracicot** [comment]
@AGreat1 your assumption is correct. This is kept off by default in the CMake only for compatibility reasons.
