### ISSUE TITLE
[question] how to solve problem KB-H019

### ISSUE THREAD

**Issue by xiazhibin** [conan-io/conan-center-index#181]
I get error on `conan install `:
```
fmt/5.3.0@bincrafters/stable: Already installed!
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] The *.cmake files have to be placed in a folder declared as `cpp_info.builddirs`. Currently folders declared: [''] (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H019)
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] Found files:
./lib/cmake/fmt/fmt-config.cmake
./lib/cmake/fmt/fmt-targets-release.cmake
./lib/cmake/fmt/fmt-config-version.cmake
./lib/cmake/fmt/fmt-targets.cmake (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H019)
```

From the error message, Do I need to move the `*.cmake` to somewhere? where is `builddirs defaults ['']`

**Comment by danimtb** [comment]
You should place the `*.cmake` file in the root of your package

**Comment by uilianries** [comment]
Hi @xiazhibin !

Cmake target files, config and find are not allowed in CCI:
https://github.com/conan-io/conan-center-index/wiki/FAQ#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged

**Comment by danimtb** [comment]
Sorry, I thought you were packaging a CMake file with a special functionality. Then @uilianries is right, follow the link for a complete answer. Thanks!
