### ISSUE TITLE
Why is the cmake configuration in Boost deleted when packaging ?

### ISSUE THREAD

**Issue by sflis** [conan-io/conan-center-index#1818]
Why is the cmake configuration in Boost deleted when packaging?

https://github.com/conan-io/conan-center-index/blob/ca5040f1ccfcd896daf2e8e1b1f5ea9fdb07e476/recipes/boost/all/conanfile.py#L826

From boost 1.70 boost provides its own cmake configuration file which depracated the BoostFindModule.cmake that cmake provides. If I chose to use cmake for package discovery by using  find_package( ) together with the `cmake_paths` generator in conan it will not find the configuration file since it is removed in the conan package. Instead it will pick up the BoostFindModule.cmake.  

This does not follow cmake best practices. I would like to propose to remove that line and ship boost with it's cmake configuration.

**Comment by TimSimpson** [comment]
My understanding is Conan itself supports being able to save CMake config files in Conan packages, but Conan Center doesn't believe this is a good practice. The reasoning is when the CMake config files are called they create their own graph for all of a project's transitive dependencies which may or may not match up to Conan's, which leads to problems. The example I was given is that they may include a system installed version of openssl while other dependencies from the same project are using a newer version specified by Conan.

However my understanding is recent additions to Conan enable it to emulate most things the "official" CMake package config files are doing. It's possible to use `self.cpp_info.names` for instance to tell Conan to generate CMake files that give targets the same names used by their "official" CMake created config files, and macros found in the CMake package config files can be exported to modules set by `self.cpp_info.build_modules` which are then included. So basically, the hope is Conan can replicate whatever the CMake package config script does while better controlling the dependency graph.

**Comment by uilianries** [comment]
@sflis The motivation for removing: https://github.com/conan-io/conan-center-index/wiki/FAQ#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged

About the modules for Boost, there is an initial effort: #1925

> I would like to propose to remove that line and ship boost with it's cmake configuration.

This won't happen. Conan 1.26 provides a new support for modules, involving cmake_find_package generator. It should be enough for generating the correct FindBoost.cmake file (including the modules), it's just a matter of time until having that PR available.

**Comment by jgsogo** [comment]
If needed, please continue on this issue https://github.com/conan-io/conan-center-index/issues/209. I suppose this is not specific to Boost itself and it is easier to try to centralize things.

Thanks!
