### ISSUE TITLE
[gdcm] cannot be used with fontconfig on linux (libuuid conflict)

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan-center-index#18203]
### Description

On linux, if your package require both gdcm and fontconfig the conan install command fails with the following error:
```
ERROR: At least two recipes provides the same functionality:
 - 'libuuid' provided by 'libuuid/1.0.3', 'util-linux-libuuid/2.39'
```
This issue appeared with https://github.com/conan-io/conan-center-index/pull/17995

Note we do not use directly gdcm or fontconfig, but qt requires fontconfig and itk requires gdcm.

### Package and Environment Details

* Package Name/Version: **gdcm/3.0.21**
* Operating System+version: **Linux Ubuntu 22.10**
* Compiler+version: **GCC 10**
* Conan version: **conan 1.60.1**
* Python version: **Python 3.10.7**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

`conan new test_libuuid/1.0.0`

Add
```
    def requirements(self):
        self.requires("gdcm/3.0.21")
        self.requires("fontconfig/2.13.93")
        self.requires("expat/2.5.0")
```

conan install . --update

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: At least two recipes provides the same functionality:
 - 'libuuid' provided by 'libuuid/1.0.3', 'util-linux-libuuid/2.39'
```

</details>

**Comment by jwillikers** [comment]
Thanks for reporting the issue. I've submitted  #18211 to fix this.
