### ISSUE TITLE
[pkgconf] pkgconf/1.9.3: Sources are not available

### ISSUE THREAD

**Issue by Gernatch** [conan-io/conan-center-index#18214]
### Description

The sources from the conandata.yml no longer exist. I'm struggling to find an alternative though.
``` 
sources:
  "1.9.3":
    url: "https://distfiles.dereferenced.org/pkgconf/pkgconf-1.9.3.tar.xz"
    sha256: "5fb355b487d54fb6d341e4f18d4e2f7e813a6622cf03a9e87affa6a40565699d"
  "1.7.4":
    url: "https://distfiles.dereferenced.org/pkgconf/pkgconf-1.7.4.tar.xz"
    sha256: "d73f32c248a4591139a6b17777c80d4deab6b414ec2b3d21d0a24be348c476ab"
  "1.7.3":
    url: "https://distfiles.dereferenced.org/pkgconf/pkgconf-1.7.3.tar.xz"
    sha256: "b846aea51cf696c3392a0ae58bef93e2e72f8e7073ca6ad1ed8b01c85871f9c0"

### Package and Environment Details

* Package Name/Version: **pkgconf/1.9.3**
* Operating System+version: **CentOS7**
* Compiler+version: **GCC 8**
* Docker image: **conanio/gcc8**
* Conan version: **conan 1.59.0**
* Python version: **Python 3.7.6**


### Conan profile

[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Debug

### Steps to reproduce

Try to download this source from a browser, or via conan:
https://distfiles.dereferenced.org/pkgconf/pkgconf-1.9.3.tar.xz

### Logs

ConanException: Error downloading file https://distfiles.dereferenced.org/pkgconf/pkgconf-1.9.3.tar.xz: 'HTTPSConnectionPool(host='distfiles.dereferenced.org', port=443): Max retries exceeded with url: /pkgconf/pkgconf-1.9.3.tar.xz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f53c5d23400>, 'Connection to distfiles.dereferenced.org timed out. (connect timeout=3600.0)'))'

**Comment by ericLemanissier** [comment]
This should be reported in https://github.com/pkgconf/pkgconf/issues
As an alternative we could use https://github.com/pkgconf/pkgconf/tags, but the SHAs will be different

**Comment by jcar87** [comment]
I've been able to retrieve the original file for version 1.9.3 - at least, one that matches the exact checksum in `conandata.yml`, and the github sources are not exactly the same - usual case of having to run autoreconf if we want the configure scripts.

```
 % diff -r ./pkgconf-pkgconf-1.9.3 /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3
Only in ./pkgconf-pkgconf-1.9.3: .gitattributes
Only in ./pkgconf-pkgconf-1.9.3: .github
Only in ./pkgconf-pkgconf-1.9.3: .gitignore
Only in ./pkgconf-pkgconf-1.9.3: .mailmap
Only in ./pkgconf-pkgconf-1.9.3: .woodpecker.yml
Only in ./pkgconf-pkgconf-1.9.3: CODE_OF_CONDUCT.md
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: Makefile.in
Only in ./pkgconf-pkgconf-1.9.3: Makefile.lite
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: aclocal.m4
Only in ./pkgconf-pkgconf-1.9.3: autogen.sh
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: compile
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: config.guess
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: config.sub
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: configure
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: depcomp
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: install-sh
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3/libpkgconf: config.h.in
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: ltmain.sh
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3/m4: libtool.m4
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3/m4: ltoptions.m4
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3/m4: ltsugar.m4
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3/m4: ltversion.m4
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3/m4: lt~obsolete.m4
Only in /path/to/pkgconf-1.9.3-from-github/pkgconf-1.9.3: missing
```

@Gernatch  - this could be a transient issue, it's not entirely unusual for this to happen from time to time. In fact from what I can see, other package repositories that reference the same sources are also affected.

If you hare fully blocked and but have the ability to modify the recipe to retrieve the sources from somewhere else, I would suggest:

* download the sources for the pkgconf package from cygwin - this includes the _original_ file with the original contents and sha256 sum, e.g. https://cygwin.mirror.uk.sargasso.net/x86_64/release/pkgconf/pkgconf-1.9.3-1-src.tar.zst - note that you will need the zstd tool to unpack the file
* unpack the file, e.g. `tar --use-compress-program=unzstd -xvf pkgconf-1.9.3-1-src.tar.zst`
* the `pkgconf-1.9.3-1.src` contains `pkgconf-1.9.3.tar.xz` - original contents as the one referenced by the recipe, you can double check this by computing its sha256 sum.

You have the ability to clone conan-center-index and build from there - you can modify `conandata.yml` for `pkgconf` such that it points to the file you just downloaded, by adding another url entry pointing to a local file, e.g.:

```
sources:
  "1.9.3":
    url: "https://distfiles.dereferenced.org/pkgconf/pkgconf-1.9.3.tar.xz"
    url: "file:///Users/luisc/dev/tmp/pkgconf/pkgconf-1.9.3-1.src/pkgconf-1.9.3.tar.xz"
    sha256: "5fb355b487d54fb6d341e4f18d4e2f7e813a6622cf03a9e87affa6a40565699d"
```

This will cause Conan to use the local file as a mirror, and will still validate the checksum.

Alternatively, if you have the ability to host it on Artifactory or a webserver that's accessible to you, you can use a regular https:// URL.

Hope this helps, until the situation is resolved!! We have a new feature coming in a future release of Conan 2.0 that will allow backing up these files at recipe creation time, to use as a backup transparently for cases like this.

**Comment by Gernatch** [comment]
The workaround is a good one, and I think the source is also already fixed as I can now download from it.
