### ISSUE TITLE
[request] tracy/0.9.1

### ISSUE THREAD

**Issue by neobrain** [conan-io/conan-center-index#18278]
### Package Name/Version

tracy/0.9.1

### Changelog

https://github.com/wolfpld/tracy/releases/tag/v0.9.1

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

Tracy 0.9.1 adds a couple of nice QoL improvements. This mainly affects the profiler, which isn't packaged by Conan itself but I normally build it from Conan's source checkout instead of setting up a dedicated install.

From quick testing, it looks like 0.9.1 packages fine with the 0.9 Conan recipe.

**Comment by toge** [comment]
@neobrain 
Thank you for your request.

tracy/0.9.1 has been added already.
https://github.com/conan-io/conan-center-index/pull/18097

Please try it!

**Comment by neobrain** [comment]
Ah, yes. What coincidental timing :)

The recipe is working perfectly fine of course. My bad for not checking I'm using the latest available recipe locally 🙈
Thanks a lot!
