### ISSUE TITLE
[package] thrift/0.13.0: build fails using --profile but works using --profile:host and --profile:build

### ISSUE THREAD

**Issue by thkowa** [conan-io/conan-center-index#1829]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **thrift/0.13.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 7**
  * Conan version: **conan 1.25.2**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile linux-x64:
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Debug
[options]
*:fPIC=True
*:shared=True
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
I have a package that uses _thrift/0.13.0_ as build requirement (thrift compiler) and as normal requirement (thrift libs). When I build and create my package with

```conan create . --profile:host linux-x64 --profile:build linux-x64```

the build works perfectly, the thrift sources are compiled with the thrift compiler. When I  use

```conan create . --profile linux-x64```

the build fails when using the thrift compiler. The difference is that in the first case, the binary directories of all build requirement packages are added to PATH environment during build and in the second case, nothing is added to PATH. The cmake build of my package expects the thrift compiler being in PATH.

I was not sure if this is really a package bug and not a conan bug. Sorry if this was the wrong place.

**Comment by uilianries** [comment]
@thkowa Take a look https://github.com/conan-io/conan-center-index/pull/1822

**Comment by thkowa** [comment]
@uilianries 
> @thkowa Take a look #1822

I have seen this and I have seen that the PATH setting was missing. I made a quick test and it works. But I still wonder that the behavior is different with _profile:host_ and _profile:build_.

Sorry for the duplication. I'll close this issue again.
