### ISSUE TITLE
[request] qt/5.12 qt/5.15

### ISSUE THREAD

**Issue by thkowa** [conan-io/conan-center-index#1833]
### Package Details
  * Package Name/Version: **qt/5.12**
  * Website: **https://qt.io/**
  * Source code: **https://download.qt.io/archive/qt/**

At least the LTS versions 5.12 and 5.15, see https://en.wikipedia.org/wiki/Qt_version_history

### Description Of The Library / Tool
Cross-platform software development for embedded & desktop

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/1759

**Comment by ericLemanissier** [comment]
qt 5.15.2 is now on conan-center: https://conan.io/center/qt

**Comment by SpaceIm** [comment]
@uilianries this PR can be closed I guess
