### ISSUE TITLE
[service] Update wiki to clarify language on commit date based versioning

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#1837]
There are projects which don't do any releases. For those we pick the source code from a specific date and name the release after the date in a `YYYYMMDD` schema 

https://github.com/conan-io/conan-center-index/wiki/FAQ#what-version-should-packages-use-for-libraries-without-official-releases

However, the current explanation has a false sentence

> Thus we use a datestamp to show when the package was created.

That would mean that when I'm creating a new package today I would name it `name/20200605`, but it should have the day of the revision of the source code I'm using.

The last sentence in the wiki is somewhat better: 

>  An example of this is the NanoRange library, where its package reference is nanorange/20191001 and its sources are locked the latest commit on that date

This needs updating

**Comment by danimtb** [comment]
I have updated that sentence in the wiki, thanks for reporting. Also, we plan to improve the documentation in order to make it more collaborative

**Comment by jgsogo** [comment]
Closed via https://github.com/conan-io/conan-center-index/pull/2437
