### ISSUE TITLE
[question] libpq/11.5 static and shared libraries both in lib folder

### ISSUE THREAD

**Issue by egendron93** [conan-io/conan-center-index#1844]
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
libpq:shared=False
[build_requires]
[env]
```
```
conan install libpq/11.5@ -o libpq:shared=False --build missing
```
When using the libpq/11.5 package it seems no matter what the value of the shared option is the recipe will produce both the static and shared versions of the library inside of the package's lib folder. This in combination with the collect_libs function creates a non deterministic solution for linking the the libpq package according to [this comment](https://github.com/conan-io/conan/issues/3708#issuecomment-428551618) that I found when researching the issue. The same warning even shows up once the libpq package completes the build:
```
libpq/11.5: WARN: Library 'pq' was either already found in a previous 'conanfile.cpp_info.libdirs' folder or appears several times with a different file extension
```

I wasnt sure if I was missing something or maybe the libpq build doesnt allow for this seperation? Let me know if I need to provide any further information. Thank you!

**Comment by SpaceIm** [comment]
It will be fixed by https://github.com/conan-io/conan-center-index/pull/1620
