### ISSUE TITLE
[service] PR builds trigger on PR description edits

### ISSUE THREAD

**Issue by valgur** [conan-io/conan-center-index#18780]
### What is your problem/feature request?

I noticed that all of the PRs that I recently updated the description on for a status update triggered a new build shortly after.
That's not necessarily an issue, but it's probably not something worth spending the limited CI capacity on either. Should this perhaps be disabled?

**Comment by valgur** [comment]
@jcar87

**Comment by valgur** [comment]
@jcar87 The need for more context info in the description is usually proportional to the size of the PR, which in turn usually depends on the complexity of the recipe and the project. And the more complex PRs usually need incremental updates as more bugs and edge cases get uncovered. I guess I'll just re-trigger a multi-hour CI run each time in these cases then?

**Comment by uilianries** [comment]
> ### What is your problem/feature request?
> 
> I noticed that all of the PRs that I recently updated the description on for a status update triggered a new build shortly after. That's not necessarily an issue, but it's probably not something worth spending the limited CI capacity on either. Should this perhaps be disabled?

It's not something we can manage easily, because it's a webhook that triggers the build to Jenkins, but in jenkins side is much harder to filter it.

You still can add a new comment in the PR, reviewers should read anything. Better having a separated comment than an empty description.

**Comment by valgur** [comment]
Should be fixed in the new CI setup: #25772
