### ISSUE TITLE
[request] hunspell for conan 2 and version 1.7.2 

### ISSUE THREAD

**Issue by CJCombrink** [conan-io/conan-center-index#18828]
### Package Name/Version

hunspell/1.7.2

### Changelog

https://github.com/hunspell/hunspell/releases/tag/v1.7.2

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

Also upgrade to conan 2

**Comment by czoido** [comment]
Thanks for reporting, closing this as already available.
