### ISSUE TITLE
[package] paho-mqtt-c/1.3.4: ssl option throws exception constructing async_client using 'wss' protocol broker url

### ISSUE THREAD

**Issue by keysight-daryl** [conan-io/conan-center-index#1882]
Updated paho-mqtt-cpp package to using the new paho-mqtt-c/1.3.4 package and with the default option 'ssl'=True.  Creating both packages appears to work however there seems to be a couple issues...

1. regardless of the settings of the options 'ssl', 'asynchronous', or 'shared' the end package appears to contain all variants of the library binaries both static and dynamic, with and without ssl, and asynchronous and synchronous clients.  Normally I would expect to see the single library binary for just the specific variant being optioned in the recipe.
2. consuming application tries to call async client constructor using a 'wss' url (requiring ssl support) throws an exception saying that protocol isn't supported.  stepping into the library in a debugger sees the internal 'OPENSSL' define as undefined.

It appears to either not be linking to the correct variant of the library supporting ssl or the cpp defines are not working properly between the packaged library and the consuming application, or both.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: paho-mqtt-c/1.3.4 via bumped paho-mqtt-cpp
  * Operating System+version: Windows
  * Compiler+version: Visual Studio 2018
  * Conan version: 1.24.0
  * Python version: 3.7.7

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Debug
compiler.runtime=MDd
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Set recipe ssl option True
create package
consume package from your application respecting the ssl option as True
construct an async_client with a url starting with 'wss://'
constructor throws exception

**Comment by icraggs** [comment]
PR #1888 should allow either static or shared libraries to be built.  It's possible to build both types at the same time on OSes other than Windows where I think the file names will conflict.

**Comment by uilianries** [comment]
@icraggs Conan packages only allow by convention, OR static OR shared in package. Both are considered an error, only the case where the project requires it to work, but I don't think that's the case here.

**Comment by icraggs** [comment]
No, it's not the case that both need to be built.  It can be either/or.

**Comment by icraggs** [comment]
@keysight-daryl is this fixed now?

**Comment by keysight-daryl** [comment]
Yes
