### ISSUE TITLE
[question] Add a project that already uses conan

### ISSUE THREAD

**Issue by hedtke** [conan-io/conan-center-index#18876]
### What is your question?

How do I add a project/library to conan-center that already uses conan? Do I have to copy the conanfile, or can I just state in the yaml file that for version X everything can be found at location Y and the build services does the rest?

**Comment by hedtke** [comment]
This project for example: https://github.com/scipopt/SCIPpp

**Comment by prince-chrismc** [comment]
Sadly, ConanCenter infra can not do this, so you will need to follow the usually "adding package" workflow and create a new recipe in this repository that downloads the source code.

You'll probably be able to keep the rest of the logic, just copy paste :)

**Comment by Croydon** [comment]
Sounds like a continuation of https://github.com/conan-io/conan-center-index/issues/22
