### ISSUE TITLE
[request] OpenSUSE <opengl>/<system>

### ISSUE THREAD

**Issue by chriztheanvill** [conan-io/conan-center-index#18912]
### Package Name/Version

opengl/system

### Changelog

https://github.com/nigels-com/glew/releases/tag/glew-2.2.0

### Context about the new update

Hi.
In opensuse trying to install glew, install opengl/system, and shows this message:
```
opengl/system: RUN: rpm -q glproto-devel
package glproto-devel is not installed

ERROR: opengl/system: Error in system_requirements() method, line 39
        zypper.install(["Mesa-libGL-devel", "glproto-devel"], update=True, check=True)
        ConanException: System requirements: 'glproto-devel' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'

```

In opensuse the package glproto-devel does not exist. Solving: edit: .conan2/p/opengc3fc46f257b85/e/conanfile.py

```
38        zypper = package_manager.Zypper(self)
39        zypper.install(["Mesa-libGL-devel", "glproto-devel"], update=True, check=True)

to this
38        zypper = package_manager.Zypper(self)
39        zypper.install(["Mesa-libGL-devel"], update=True, check=True)

```

**Comment by ericLemanissier** [comment]
Did you try what the error message says: `Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'`
The systems test of opengl on opensuse does pass on https://github.com/bincrafters/system-packages-checks/actions/runs/5655446415/job/15320677068#step:6:420 and https://github.com/bincrafters/system-packages-checks/actions/runs/5655446415/job/15320677266#step:6:347

**Comment by chriztheanvill** [comment]
Yes.

> Did you try what the error message says: `Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'` The systems test of opengl on opensuse does pass on https://github.com/bincrafters/system-packages-checks/actions/runs/5655446415/job/15320677068#step:6:420 and https://github.com/bincrafters/system-packages-checks/actions/runs/5655446415/job/15320677266#step:6:347
> 
> see also https://pkgs.org/search/?q=glproto-devel&on=provides

Yes, tried and no success.

**Comment by ericLemanissier** [comment]
Please show the full console log with the -c... argument

**Comment by chriztheanvill** [comment]
> Please show the full console log with the `-c tools.system.package_manager:mode=install` argument (and possibly `-c tools.system.package_manager:sudo=True` too)


opengl/system: RUN: zypper --non-interactive ref
Root privileges are required to run this command.

ERROR: opengl/system: Error in system_requirements() method, line 39
        zypper.install(["Mesa-libGL-devel", "glproto-devel"], update=True, check=True)
        ConanException: Command 'zypper --non-interactive ref' failed

**Comment by ericLemanissier** [comment]
@chriztheanvill as you can see in the error message you pasted: `Root privileges are required to run this command`
The solution is in my last message: `-c tools.system.package_manager:sudo=True`

**Comment by neobrain** [comment]
openSUSE Tumbleweed provides this package under the name `xorgproto-devel`. It's surprising that bincrafters builds it fine, but maybe they're running an older distribution and the package got renamed recently?

On TW, zypper actually installs `xorgproto-devel` when asking for the non-existent `glproto-devel`, but Conan somehow interprets this as failure. Generally it looks like zypper support is a bit wonky as indicated by the other messages posted by @chriztheanvill .

**Comment by ericLemanissier** [comment]
Until now, all the error messages posted in this issue showed that the configuration of the user was incorrect:
`set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'` and the same for `tools.system.package_manager:sudo=True`

If you get an error with these two configurations properly set, please paste a full log.

**Comment by neobrain** [comment]
It does work with these two options set (thanks!), but it shouldn't be needed: I already had `xorgproto-devel` installed, so the zypper invocation didn't actually do anything. But Conan can't proceed without checking as root.

Looking under the hood apparently Conan's check is implemented using `rpm -q <package_name>`, which isn't capability aware. Using `rpm -q --whatprovides <package_name>` would be more suited here since it can check without root. Is this an option for Conan?

In fact, from the looks of it the current behavior is to `check + install` any time Conan hits a case like this. With the proper check, Conan would be able to skip the no-op install.

**Comment by czoido** [comment]
Hi @chriztheanvill,
Thanks for reporting, I think the changes in https://github.com/conan-io/conan-center-index/pull/23015 should fix your problem.
