### ISSUE TITLE
[package] protobuf/3.17.1 or newer: CMake build issue "The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by ibosnic00** [conan-io/conan-center-index#18927]
### Description

Issue:
When compiling C++ project with CMake and Visual Studio 17 generator, error pops out:

Running cpp protocol buffer compiler on C:/Users/user.name/cppTest/proto/ecu_state.proto
  The filename, directory name, or volume label syntax is incorrect.
I have created demo project to easily reproduce the issue.

Steps to reproduce:

git clone https://github.com/ibosnic00/demo_cmake_conan.git
cd demo_cmake_conan
start build_and_compile.bat script
Note:
In conanfile.py, line 22 make sure the version of **protobuf is 3.17.1** or newer _self.requires("protobuf/3.17.1")_

This **can be fixed** by changing lines 260 & 261 in _conanfile.py:_

        for generator in ["cmake_find_package", "cmake_find_package_multi"]:
            self.cpp_info.components["libprotobuf"].build_modules[generator] = build_modules
            
            to:
            
            
        self.cpp_info.components["libprotobuf"].build_modules = build_modules
        
       **or** by manually adding protoc bin dir to PATH (not great)

### Package and Environment Details

* Package Name/Version: **protobuf/3.21.9**
* Operating System+version: **Windows 10**
* Compiler+version: **msvc 14.36.32532 - Visual Studio 2022**
* Conan version: **conan 1.57.0**
* Python version: **Python 3.10.11**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Debug

### Steps to reproduce

git clone https://github.com/ibosnic00/demo_cmake_conan.git
cd demo_cmake_conan
start build_and_compile.bat script

### Logs

PS C:\Users\user.name\Desktop\temp\cppTest> .\build_and_compile.bat
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.py (demo_app/1.0.0): Installing package
Requirements
    protobuf/3.21.9 from 'conancenter' - Cache
    zlib/1.2.13 from 'conancenter' - Cache
Packages
    protobuf/3.21.9:e315da8ae56228bce9e0908c3fa6cfb1a4018b9e - Cache
    zlib/1.2.13:164640aad040835ac89882393a96d89200694f04 - Cache

Installing (downloading, building) binaries...
zlib/1.2.13: Already installed!
protobuf/3.21.9: Already installed!
protobuf/3.21.9: PATH is: []
protobuf/3.21.9: PATH is: ['C:\\.conan\\9bebdf1\\1\\bin']
conanfile.py (demo_app/1.0.0): Generator txt created conanbuildinfo.txt
conanfile.py (demo_app/1.0.0): Generator cmake created conanbuildinfo.cmake
conanfile.py (demo_app/1.0.0): Aggregating env generators
conanfile.py (demo_app/1.0.0): Generated conaninfo.txt
conanfile.py (demo_app/1.0.0): Generated graphinfo
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.36.32535.0
-- The CXX compiler identification is MSVC 19.36.32535.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: C:/Users/user.name/Desktop/temp/cppTest/build
-- Found Protobuf: C:/.conan/9bebdf1/1/lib/libprotobufd.lib (found version "3.21.9")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/user.name/Desktop/temp/cppTest/build
MSBuild version 17.6.3+07e294721 for .NET Framework

  Checking Build System
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(208,5): warning MSB8062: Custom build for item "C:\Users\user.name\Desktop\temp\cppTest\build\CMake 
Files\4ee73c421772a9cd0da84d1d1bd20386\ecu_state.pb.h.rule" specifies invalid path "C:\Users\user.name\Desktop\temp\cppTest\build\protobuf::protoc" as an additional dependency. This may cause incremental build to 
 work incorrectly. [C:\Users\user.name\Desktop\temp\cppTest\build\demo_app.vcxproj]
  Running cpp protocol buffer compiler on C:/Users/user.name/Desktop/temp/cppTest/proto/ecu_state.proto
  The filename, directory name, or volume label syntax is incorrect.
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5): error MSB8066: Custom build for 'C:\Users\user.name\Desktop\temp\cppTest\build\CMakeFiles\4 
ee73c421772a9cd0da84d1d1bd20386\ecu_state.pb.h.rule;C:\Users\user.name\Desktop\temp\cppTest\CMakeLists.txt' exited with code 123. [C:\Users\user.name\Desktop\temp\cppTest\build\demo_app.vcxproj]

**Comment by Ahajha** [comment]
I realize it's has been a while, but this _should_ be a Conan 1.x problem only. Have you tried using the new Conan generators (CMakeDeps/CMaketoolchain)?
