### ISSUE TITLE
[package] GDAL/3.1.0: error: no matching function for call to 'GDALOpen'. macOS

### ISSUE THREAD

**Issue by dec0dOS** [conan-io/conan-center-index#1892]
### Package and Environment Details
  * Package Name/Version: **gdal/3.1.0**
  * Operating System+version: **macOS 10.15.5**
  * Compiler+version: **clang 11**
  * Conan version: **conan 1.26.0**
  * Python version: **Python 3.7.7**

### Conan profile
```

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce
Compiling application with GDAL.

### Logs
<details><summary>Click to expand log</summary>

```
 error: no matching function for call to 'GDALOpen'
    GDALDataset *dataset = GDALOpen(fileName, GA_ReadOnly);
                           ^~~~~~~~
```

</details>

**Comment by SpaceIm** [comment]
`GDALOpen` returns opaque type `GDALDatasetH`.

**Comment by dec0dOS** [comment]
Whoops. Sorry for typo. Neither with GDALDatasetH it works.

**Comment by dec0dOS** [comment]
Cmakelists seems to be correct

```
add_definitions(-DUSE_GDAL)
find_package(GDAL REQUIRED)
include_directories(${GDAL_INCLUDE_DIR})
set(LIBS ${LIBS} ${GDAL_LIBRARIES})

target_link_libraries(${PROJECT_NAME} ${LIBS})
```

**Comment by SpaceIm** [comment]
Can't test on Mac, but on Windows I don't have any issue with `GDALOpen` in a toy C++ program like:

```c++
#include <gdal_priv.h>
#include <cpl_conv.h>

#include <iostream>

int main(int argc, char **argv) {
  if (argc < 2) {
    std::cerr << "Need at least one argument\n";
    return 1;
  }

  GDALAllRegister();
  GDALDataset *poDataset = reinterpret_cast<GDALDataset *>(GDALOpen(argv[1], GA_ReadOnly));
}
```

About your CMakeFile, it's would be probably better to use CMake targets if you can (`GDAL::GDAL`) but I think it should work. Moreover, if it was not found, you would have errors about missing headers I guess.

**Comment by dec0dOS** [comment]
Thanks for the help!
Could you share your toy project CMakeLists?

> Moreover, if it was not found, you would have errors about missing headers I guess.
So, nothing complains about missing headers. It is strange. Something is wrong on linking stage maybe.

**Comment by SpaceIm** [comment]
It's simply the one of test_package in GDAL recipe. You would probably prefer to use `find_package(GDAL)` (with conan's `cmake_find_package` generator, or maybe relying on cmake built-in one), then `target_link_libraries(my_program PRIVATE GDAL::GDAL)`

```cmake
cmake_minimum_required(VERSION 2.8.11)
project(test_package)

set(CMAKE_VERBOSE_MAKEFILE TRUE)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(${PROJECT_NAME} test_package.cpp)
target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 11)

add_executable(${PROJECT_NAME}_c test_package.c)
target_link_libraries(${PROJECT_NAME}_c ${CONAN_LIBS})
```
