### ISSUE TITLE
[question] Adding options to an existing recipe

### ISSUE THREAD

**Issue by qchateau** [conan-io/conan-center-index#1897]
Hi,

What's the correct way of adding an option to an existing recipe that would not be compatible with all previously published versions of the package ?

Quentin.

**Comment by uilianries** [comment]
Hi @qchateau ! You can use conditional options.

Reference: https://docs.conan.io/en/latest/mastering/conditional.html

Real example: https://github.com/conan-io/conan-center-index/blob/af2e33436aca927fc25d58c6d7de1e93b9514ef9/recipes/openssl/1.x.x/conanfile.py#L147

**Comment by qchateau** [comment]
Ah perfect, thank you
