### ISSUE TITLE
[service] Add Clang 8 support

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#19]
The service should generate packages for Clang 8.
If added the wiki should be updated as well: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Comment by lasote** [comment]
Clang8 packages have been generated for all the packages already merged and also for the open PRs! From now on, the PRs will build also Clang8 configs.
Thanks again @Croydon !!

**Comment by lasote** [comment]
Note: The packages will be available on Bintray conan-center during tomorrow. I've pending the "promotion" task. But any build on this index repository depending on gcc9 and clang8 will find the packages.
