### ISSUE TITLE
[request] fast-dds/2.11.1

### ISSUE THREAD

**Issue by AndreaFinazzi** [conan-io/conan-center-index#19013]
### Package Name/Version

fast-dds/2.11.1

### Changelog

https://github.com/eProsima/Fast-DDS/releases/tag/v2.11.1

### Context about the new update

The Conan Center Bot detects the updatable recipe in #3470.
Open CCB branch [qchateau/conan-center-index/ccb-fast-dds-2.11.1](https://github.com/qchateau/conan-center-index/tree/ccb-fast-dds-2.11.1)

**Comment by czoido** [comment]
Thanks for reporting, closing this as there are newer versions already available.
