### ISSUE TITLE
[question] Keychain Module of Qt5

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#19045]
### What is your question?

@ericLemanissier it's a question mostly for you as the main Qt recipe maintainer.
Is it possible to build a Keychain module of Qt?

I was trying to implement a conan recipe for openfortigui and it failing, while Keychain is never found.
find_package(Qt5 REQUIRED Core Widgets Network **Keychain** DBus)

**Comment by ericLemanissier** [comment]
If you are talking about https://packages.debian.org/sid/qtkeychain-qt5-dev it is a library which is not part of qt : https://github.com/frankosterfeld/qtkeychain so don't hesitate to make a new recipe

**Comment by AndreyMlashkin** [comment]
Thanks for you answer!
I was just confused, that openfortclient requires it just as a Qt submodule
https://github.com/theinvisible/openfortigui/blob/a240c6b166cb68968c0366872efd0e878bcee0bc/CMakeLists.txt#L13

**Comment by AndreyMlashkin** [comment]
Follow up

https://github.com/conan-io/conan-center-index/issues/19046
