### ISSUE TITLE
[bug] Missing zlib build

### ISSUE THREAD

**Issue by robert-shade** [conan-io/conan-center-index#19107]
### Environment details

* Operating System+version: RHEL 8.8
* Compiler+version:  gcc 8.5.0
* Conan version: 1.60.1
* Python version: 3.10

### Steps to reproduce

The latest build of zlib doesn't have a build for gcc 8.  https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/17280/2/zlib/1.2.13//summary.json

**Comment by robert-shade** [comment]
oh, sorry! I see now it got removed a few months ago.  That's very unfortunate for folks on RHEL 8, though.  It wouldn't be so bad if it didn't fail to build locally, but I can file a separate bug for that.

**Comment by uilianries** [comment]
@robert-shade You still can use Conan docker images with GCC8 in case you don't want to setup an entire new environment for building: https://hub.docker.com/r/conanio/gcc8

Please, note that we no longer generate new images for GCC8, so you will need to update the Conan client version installed in the image. Or, you can build a new image with the latest version available. All Docker recipes are available at https://github.com/conan-io/conan-docker-tools/
