### ISSUE TITLE
[service] Is CI backlog caught up yet?  My PR is still waiting

### ISSUE THREAD

**Issue by patmantru** [conan-io/conan-center-index#19121]
### What is your problem/feature request?

I submitted a recipe update on 24 July, over 2 weeks ago.  I know there was an outage recently that was resolved about 5 days ago.  My submission still shows the CI status as 'Expected - waiting for status to be reported', so either it's still waiting for the backlog to clear, or it's stuck and I should abandon it and create a new PR for the update.  Given that the site status statements explicitly requested that folks do NOT resubmit PRs, I'm losing faith that I've done the right thing by abiding by that.

https://github.com/conan-io/conan-center-index/pull/18896

Any guidance on how much longer I should expect it to take to get this (very simple) recipe update through the process and merged?

Thanks-
Pat

**Comment by RubenRBS** [comment]
Hi! Thanks a lot for the ping. While the CI has been running ok for a bit now, some PRs did not get properly relaunched automatically. I've done so now for yours, and will review it once it finishes :)

**Comment by patmantru** [comment]
Thank you!
