### ISSUE TITLE
[question] How could i know which packages cause conflict?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan-center-index#19182]
### What is your question?

ERROR: At least two recipes provides the same functionality:
 - 'libjpeg' provided by 'libjpeg-turbo/2.0.5', 'libjpeg/9d'

I don't know which package cause these conflict...

**Comment by AbrilRBS** [comment]
Closing as solved, if you have any other questions, please feel free to reopen/create a new issue, happy to help where needed!
