### ISSUE TITLE
[service] Upgrade conan version on builders to 1.26.0

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#1918]
My [cpython recipe](https://github.com/conan-io/conan-center-index/pull/1510) uses the experimental [msbuild generator](https://docs.conan.io/en/latest/reference/generators/msbuild.html).
This generator is added in conan 1.26.0

Please upgrade the conan version on the CI to the most recent.
See https://github.com/conan-io/conan-center-index/wiki/Deployment-Changelog

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/wiki/Deployment-Changelog#24-june-2020---1055-cest

**Comment by madebr** [comment]
What about our friend the :penguin:?

**Comment by prince-chrismc** [comment]
Not enough consumer demand? 

Totally missed that!
