### ISSUE TITLE
[boost] boost/1.70: MinGW build tries to use MSVC

### ISSUE THREAD

**Issue by firewave** [conan-io/conan-center-index#192]
### Package and Environment Details
  * Package Name/Version: **boost/1.70**
  * Operating System+version: **Windows 10 Version 1903**
  * Compiler+version: **MinGW 8.1.0**
  * Conan version: **conan 1.19.1**
  * Python version: **Python 3.7.4**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
compiler.exception=seh
compiler.threads=posix
[options]
[build_requires]
*: mingw_installer/1.0@conan/stable, msys2_installer/latest@bincrafters/stable, cmake_installer/3.14.5@conan/stable
[env]
```

### Steps to reproduce

Using MinGW I am no longer able to build. It selects `gcc` as the bootstrap compiler, but somehow falls back to `msvc`. This was working with an earlier recipe or boost version. I never had Visual Studio installed on this system.

 I am using the following configuration in the `conanfile.txt`:
```
boost:bzip2 = False
boost:namespace = boost_ns
boost:namespace_alias = True
boost:magic_autolink = True
```

### Logs
<details><summary>Click to expand log</summary>

```
boost/1.70.0@local/testing: Calling build()
boost/1.70.0@local/testing: bootstrap.bat gcc
Bootstrapping the build engine

Bootstrapping is done. To build, run:

    .\b2 --prefix=DIR install

boost/1.70.0@local/testing: WARN: C:\.conan\8011029\1\boost_1_70_0\tools\build\b2.exe -j8 --abbreviate-paths -d2
warning: No toolsets are configured.
warning: Configuring default toolset "msvc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html

warning: Did not find command for MSVC toolset. If you have Visual Studio 2017 installed you will need to specify the full path to the command, set VS150COMNTOOLS for your installation, or build from the 'Visual Studio Command Prompt for VS 2017'.
```

</details>

**Comment by SSE4** [comment]
@firewave I see now, if using `namespace` option, build of `bcp` doesn't utilize the toolset

**Comment by firewave** [comment]
I can confirm this is working now. Thanks!

**Comment by firewave** [comment]
Unfortunately this fix is strangely causing build failures on Linux now... I am investigating.

**Comment by firewave** [comment]
I updated to the latest recipe and I can confirm this is working fine.

**Comment by danimtb** [comment]
Tahnks for reporting @firewave. Glad it finally worked! 😄
