### ISSUE TITLE
[request] exiv2/0.28.0

### ISSUE THREAD

**Issue by solarispika** [conan-io/conan-center-index#19249]
### Package Name/Version

exiv2/0.28.0

### Changelog

https://github.com/Exiv2/exiv2/blob/v0.28.0/doc/ChangeLog

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by toge** [comment]
@solarispika 
Thank you for your request.
The PR for exiv2/0.28.0 is already created in https://github.com/conan-io/conan-center-index/pull/18149.
Please wait for merge.

**Comment by solarispika** [comment]
Oops I didn't found that one.
Thanks!
