### ISSUE TITLE
[question] Package component dependencies and non-standard names

### ISSUE THREAD

**Issue by stefan-floeren** [conan-io/conan-center-index#19241]
### What is your question?

I'm currently developing an internal library which uses components and references packages on conan center as well.

With the current version of conan, it is possible to add dependencies to components from requirements, for example boost components.

I have uploaded a short reference to https://github.com/stefan-floeren/conan-package-components-test based on the conan2 examples. The `ai` package depends on both an internal component (`algorithms`) and an external one (`boost::container`). This works as expected.

When I now uncomment the dependency to [utf8cpp](https://github.com/stefan-floeren/conan-package-components-test/blob/main/conanfile.py#L20), I get problems.

- If I uncomment as is, I get the error: `ERROR: game-engine/1.0: Required package 'utf8proc' not in component 'requires'`.
- When I add the component as `"utf8cpp"`, I get `ERROR: game-engine/1.0: Internal components not found: ['utf8cpp']`. It seems conan detects everything with colons as external and everything without as internal.

So far so good, unfortunately `utf8cpp` does not define components yet. There is PR #19018 trying to fix that.

The reason for the question now is that this PR does not work for this use case. With a dependency of `"utf8::cpp"`, conan complains `ERROR: game-engine/1.0: required component package 'utf8::' not in dependencies`.

This means conan supports only dependencies on components, if the dependency has at least a main component as well and the base name before the colon is the same as the package name.

The question now is how to solve this:
- Add aliases including the base name for all recipes affected (I have no idea how many those are)?
- Force packets to only use their base name?
- Add support for generic base names to conan (should I open a ticket in conan)?
- Other ideas?

**Comment by SpaceIm** [comment]
Is there is not a confusion between CMake target names and conan components (https://github.com/conan-io/conan-center-index/pull/19018 adds a CMake target alias, not conan components, and your issue is about how to refer to conan components)?

There are utfcpp and utf8proc recipes conan-center, there is no utf8cpp recipe. I guess you are talking about utfcpp. This recipe doesn't need components, it doesn't make sense. In requires of your package_info, you just have to refer to `utfcpp::utfcpp` (`recipeName::recipeName`).

**Comment by stefan-floeren** [comment]
Yes, I meant utfcpp, my bad.

OK, then this is a confusion between CMake and conan components on my end. That was not obvious for me.
