### ISSUE TITLE
[package] dbus/1.15.8: compilation fails with Visual Studio 2022 (and C++20?)

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#19421]
### Description

Compilation fails with Visual Studio 2022 (and C++20?).

There are errors like `error C2061: syntax error: identifier 'atomic_bool'` or `error C2079: 'refcount' uses undefined struct 'DBusAtomic'`

### Package and Environment Details

* Package Name/Version: **dbus/1.15.8**
* Operating System+version: **Windows 11**
* Compiler+version: **Visual Studio 2022 (17.7.2)**
* Conan version: **conan 2.0.9**
* Python version: **Python 3.11.1**

### Conan profile

```ini
[settings]
os=Windows
arch=x86_64
compiler=msvc
compiler.version=193
compiler.runtime=dynamic
compiler.cppstd=20
build_type=Release
```

### Steps to reproduce

```
conan install --requires dbus/1.15.8 -b missing
```

### Logs

[build.log](https://github.com/conan-io/conan-center-index/files/12442485/build.log)

**Comment by tsondergaard** [comment]
I've created https://gitlab.freedesktop.org/dbus/dbus/-/issues/494 for this issue.
