### ISSUE TITLE
[question] Is there a reason why nodejs recipe doesn't remove compiler from package_id?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#19454]
### What is your question?

`nodejs` recipe downloads pre-built binaries based on `os` and `arch`, but not `compiler`, so `compiler` doesn't contribute to package id of these packages. So why `compiler` is not removed in `package_id()` of `nodejs` recipe?

Moreover, by not removing `compiler` in `package_id()` of `nodejs`, it leads to a side effect in `emsdk` recipe: because `nodejs` is a `requires` of `emsdk`, `compiler` contribution to package id of `nodejs` leaks into package id of `emsdk` (conan v2), and therefore when compiler in build profile of users is not the same than the one in host profile used by CI to create emsdk package, conan v2 resolves a different package id.

**Comment by RubenRBS** [comment]
After checking, yeah seems like an oversight, thanks for taking the time to report _and_ address the issue :)
