### ISSUE TITLE
[request] uchardet/0.0.7

### ISSUE THREAD

**Issue by jaimesalvador** [conan-io/conan-center-index#19485]
### Package Name/Version

uchardet/0.0.7

### Webpage

https://www.freedesktop.org/wiki/Software/uchardet/

### Source code

https://www.freedesktop.org/wiki/Software/uchardet/

### Description of the library/tool

Currently, uchardet/0.0.7 works with conan 1.60.c, but there is not a port to work with Conan 2.x.

There is not update  since 2022-04-27.

Thanks

**Comment by toge** [comment]
@jaimesalvador 
Thank you for youre request.
uchardet PR for migration conan v2 is already created.
https://github.com/conan-io/conan-center-index/pull/18751

Please wait for merged.

**Comment by jaimesalvador** [comment]
Thanks for the update

**Comment by valgur** [comment]
@jaimesalvador uchardet has been migrated: #18751. Can be closed.

**Comment by czoido** [comment]
Closing this as looks fixed, please feel free to reopen if you have more issues.
