### ISSUE TITLE
[request] SWIG/4.1.1

### ISSUE THREAD

**Issue by Ad-ya** [conan-io/conan-center-index#19498]
### Package Name/Version

swig/4.1.1

### Changelog

https://sourceforge.net/p/swig/news/2022/11/-swig-411-released/

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version to conan2. Also the swig older versions is not compatible with Conan2.

**Comment by valgur** [comment]
You can give the recipe in #19058 a try. It's nearly complete, just need to fix some corner cases.
