### ISSUE TITLE
[package] gtest/all: The no_main option is ignored on package consumption

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan-center-index#195]
In the recipe, the `no_main` option is deleted from the `package_id`:
https://github.com/conan-io/conan-center-index/blob/master/recipes/gtest/all/conanfile.py#L73

It's incorrect since the option is important for consumption:
* If you don't want the main function - you provide your own. Having a second one in the binary is an error.
* If you want the main function - the binaries may be missing the main function if they were built without one.

**Comment by SSE4** [comment]
@Minimonium I think it's controlled by `package_info` method, right?
I mean package contents are the same, for `no_main=True` and `no_main=False`, you just don't link extra libraries if you don't need them

**Comment by Minimonium** [comment]
@SSE4 Ah, indeed. Sorry, seems that I've got very confused by the 
https://github.com/conan-io/conan-center-index/blob/master/recipes/gtest/all/conanfile.py#L53
and an issue in Slack. 

Yes, the library is always in the package.
