### ISSUE TITLE
[package] arrow/10.0.1: build error with Conan 1.60.0

### ISSUE THREAD

**Issue by jaimesalvador** [conan-io/conan-center-index#19504]
### Description

Build my project with conan1.60.0 and arrow 10.0.1 failed with error:

```
arrow/10.0.1: ERROR: Package '99cc3cb38a10a56564f22c8da6309bd1bfaaec6c' build failed
arrow/10.0.1: WARN: Build folder C:\.conan\62752a\1\build
ERROR: arrow/10.0.1: Error in build() method, line 527
	cmake.configure(build_script_folder=os.path.join(self.source_folder, "cpp"))
```

Two weeks ago, it was working fine without errors

conanfile.txt:

```
[requires]
#zlib/1.2.13
#fmt/10.0.0
thrift/0.17.0

boost/1.80.0
openssl/3.1.0
libxml2/2.11.4
antlr4-cppruntime/4.13.0
libgettext/0.21
spdlog/1.11.0
uchardet/0.0.7
libiconv/1.17
protobuf/3.21.9
leveldb/1.23
cli11/2.3.2
arrow/10.0.1
leveldb/1.23

[generators]
CMakeDeps
CMakeToolchain 

[options]
thrift/*:shared=False
arrow/*:shared=False
arrow/*:encryption=True
arrow/*:with_csv=True
arrow/*:with_zstd=True
arrow/*:parquet=True
arrow/*:with_openssl=True
arrow/*:with_boost=True

#[imports]
#bin, *.dll -> dist/bin
#lib, *.lib -> dist/lib

```

### Package and Environment Details

* Package Name/Version: **arrow/10.0.1**
* Operating System+version: **Windows 11**
* Compiler+version: **MSVC 16**
* Conan version: **conan 1.60.0**

### Conan profile

Configuration (profile_host):

```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce

conan install . --install-folder=conan-release --settings=build_type=Release --build=missing -pr:b=default

### Logs

<details><summary>Click to expand log</summary>

```
-- Configuring incomplete, errors occurred!
arrow/10.0.1: 
WARN: Remotes registry file missing, creating default one in C:\Users\VssAdministrator\.conan\remotes.json
WARN: thrift/0.17.0: requirement boost/1.82.0 overridden by your conanfile to boost/1.80.0 
WARN: thrift/0.17.0: requirement openssl/[>=1.1 <4] overridden by your conanfile to openssl/3.1.0 
WARN: libevent/2.1.12: requirement openssl/[>=1.1 <4] overridden by thrift/0.17.0 to openssl/3.1.0 
WARN: arrow/10.0.1: requirement boost/1.82.0 overridden by your conanfile to boost/1.80.0 
WARN: arrow/10.0.1: requirement openssl/1.1.1t overridden by your conanfile to openssl/3.1.0 
arrow/10.0.1: ERROR: Package '99cc3cb38a10a56564f22c8da6309bd1bfaaec6c' build failed
arrow/10.0.1: WARN: Build folder C:\.conan\62752a\1\build
ERROR: arrow/10.0.1: Error in build() method, line 527
	cmake.configure(build_script_folder=os.path.join(self.source_folder, "cpp"))
	ConanException: Error 1 while executing cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:/.conan/62752a/1/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/.conan/31271e/1" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\.conan\62752a\1\src\cpp"
##[error]Cmd.exe exited with code '1'.
Finishing: Conan install release

```

</details>

**Comment by SpaceIm** [comment]
Where is the relevant part of the log? There is a configuration error but you have skipped this important part.

**Comment by jaimesalvador** [comment]
The relevant parto of the LOG is:

```
arrow/10.0.1: ERROR: Package '99cc3cb38a10a56564f22c8da6309bd1bfaaec6c' build failed
arrow/10.0.1: WARN: Build folder C:\.conan\62752a\1\build
ERROR: arrow/10.0.1: Error in build() method, line 527
	cmake.configure(build_script_folder=os.path.join(self.source_folder, "cpp"))
```

**Comment by alexk101** [comment]
That error is from the python stack trace and does not include the error in the underlying build, which is where the problem actually is. This doesn't help in identifying your problem. You should find another error somewhere higher up in the log. Better yet, just post the whole output.

**Comment by jaimesalvador** [comment]
You are right, the error is from python stack. I guess the error is in the conan-package description of arrow/10.0.1

Please check https://github.com/conan-io/conan-center-index/blob/master/recipes/arrow/all/conanfile.py, line 527:

![image](https://github.com/conan-io/conan-center-index/assets/1667126/0f90b02c-b228-4a75-8aaf-27cf213dfd55)

Right now, I tested with a linux machine (Ubuntu 22.04) using conan 1.60.2 (installed via a DEBIAN package) without python and i get the same error:

![image](https://github.com/conan-io/conan-center-index/assets/1667126/75c3ddef-1e95-45d7-b42c-99f5f06ba8a8)

**Comment by jaimesalvador** [comment]
I found the issue.

In the las update, there is a "with_thrift" property, I set:

arrow/*:with_thrift=True

and the compilation is ok

**Comment by jtanx** [comment]
This still sounds like a problem with the recipe to me, with_parquet should imply with_thrift. @raulcd  thoughts?

**Comment by raulcd** [comment]
Sorry, that makes sense to me. @kou does that make sense to you?

**Comment by jaimesalvador** [comment]
Also, you have to add 

```
arrow/*:with_re2=True
```

**Comment by kou** [comment]
Hmm. It's strange. We already did it:

https://github.com/conan-io/conan-center-index/blob/d9066ea9ed9869e56ee98b280981d628fa5c29b6/recipes/arrow/all/conanfile.py#L262-L266

For `re2`:

https://github.com/conan-io/conan-center-index/blob/d9066ea9ed9869e56ee98b280981d628fa5c29b6/recipes/arrow/all/conanfile.py#L207-L215
