### ISSUE TITLE
[request] libtins/4.5

### ISSUE THREAD

**Issue by GLaDOS-418** [conan-io/conan-center-index#19545]
### Changelog

https://github.com/mfontanini/libtins/releases/tag/v4.5

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

the version is already identified in #3470 as an updatable recipe.

**Comment by toge** [comment]
@GLaDOS-418 
Thank you for your request!
I create PR for it.
Please wait for merged.
