### ISSUE TITLE
[package] nlohmann_json/3.8.0: conan-package does not include the generated cmake-package configuration

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan-center-index#1954]
We tried to use this package today.
The main documentation regarding the [project usage with CMake](https://github.com/nlohmann/json#external) states that:
> To use this library from a CMake project, you can locate it directly with find_package() and use the namespaced imported target from the generated package configuration

Sadly, the downloaded prebuild package for our environment (macOS) does not include any CMake package configuration.

**Comment by Adnn** [comment]
And we suspect this line is the culprit:
https://github.com/conan-io/conan-center-index/blob/8fa1a9aa5735f195f2444156ccf0f854dabffa98/recipes/nlohmann_json/all/conanfile.py#L44

**Comment by SpaceIm** [comment]
You should use `cmake_find_package` generator, it will mimic find cmake file so that you can call `find_package(nlohmann_json)` and then link `nlohmann_json::nlohmann_json` target.

**Comment by uilianries** [comment]
@Adnn take a look on `cmake_find_package` documentation:

https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html

**Comment by Adnn** [comment]
We are currently building our whole product line with the `cmake_path` generator, and try to keep away from other generators that "do too much".

In particular, we are surprised with the recommended approach:

> Except in few recipes, CCI recipes always remove pkgconfig and cmake targets/config files. The baseline for consumers is to use cmake_find_package, cmake_find_package_multi or pkg_config generator to achieve non intrusive conan integration

This seems to directly conflict with the CMake packaging documentation:
https://cmake.org/cmake/help/v3.18/manual/cmake-packages.7.html#creating-a-package-configuration-file

In particular, a CMake-package configuration script can introduce arbitrarily complex logic, **which is maintained and tested by the project implementers**. Only in trivial cases (such as nlohmann_json, which is header only) does it seem safe to disregard the actual configuration.

It is probably not a discussion scoped to this particular recipe, yet this decision force users to use `cmake_find_package`, even for projects that claim native CMake package support. It does not feel like "non-intrusive Conan" in our current project infrastructure.

Thank you for your responses and explanations,

**Comment by prince-chrismc** [comment]
> EDIT: To elaborate on _why_ we think the `cmake_find_package` approach is make Conan more intrusive. This is actually an important property for our organization: all our code can be built with Conan, or without Conan by gathering dependencies "manually" then calling CMake explicitly.

As a conan user, with an anonymous "we" behind me, I was given the same requirement... I opted for the `cmake_find_pacakge` generator. Funny how two people with the same requirement make different decision.

**Comment by jgsogo** [comment]
Hi! Please, continue the discussion on this other issue https://github.com/conan-io/conan-center-index/issues/209, let's try to gather things together.

I only need to point out that those `.cmake` files are being removed in recipes in ConanCenter, it is not something built-in in Conan. There are different efforts to provide actual transparent integration with existing CMakeLists.txt files (check comment [here](https://github.com/conan-io/conan-center-index/issues/209#issuecomment-660067373)) while adding more robustness and flexibility to a dependency graph (conflict resolution, cross-building,...).

I really think that _components_, _filenames_ and _build_modules_ add all the flexibility that could be needed to consume ConanCenter recipes (with a `cmake_find_package[_multi]` generator) in a completely transparent way. I really think that these files do not "do too much", they are as straightforward as possible (not like the magical `cmake` generator 😅 )

On the other hand, generating these files from Conan guarantee that they contain the same information for CMake, Meson, SCons, or other build system the consumer might be using; which is something that project implementers are not providing.

**Comment by Croydon** [comment]
I think we can close this issue in favor of #209
