### ISSUE TITLE
[question] working with requirements in conanfile.py

### ISSUE THREAD

**Issue by ilya-lavrenov** [conan-io/conan-center-index#19627]
### What is your question?

Hi, 

I have a recipe https://github.com/conan-io/conan-center-index/pull/19164 and the following questions, which I cannot answer myself during enabling of my package:

- I want to configure several requirements for my package and managed to do it locally, but Conan CI reports missed dependencies (looks like it cannot provide packages with non-default options). E.g. I don't need library in `flatbuffers` requirement and thus I set `header_only = True`, but such package is not available. Ok, I temporarily commented this out, but then Conan reports that `flatbuffers` is not used in any `requires` section of my components. Yes, it's really not used, because it's used on build stage since I need only compiler and don't require library. How to handle it? Play with different flags in `self.requires()` ? should I set `visible = False` to completely hide this dependency? It's not stated in docs under what condition Conan decides that requirement must be listed at `requires` Finally, how set `header_only` and make Conan CI happy at the same time? 

- More interesting case with `protobuf`, which must be `shared = False` for our package. So, I set `options["protobuf"].shared = False`, but some profiles in Conan CI have `*/*:shared=True` and looks like it overrides option in my recipe and still dynamic protobuf is passed to my package. I have added an invalid exception throwing in `build_validate` section, but it's ignored anyway and thus `test_package` fails because my package cannot work with dynamic protobuf. Can Conan documentation be improved with examples how to play with this option? E.g. what to set if static library consumes by dynamic one? can Conan provide detailed configuration for each installed requirement? because currently it installs some protobuf and I don't even know whether it's dynamic or static; I understand it dynamic just because my tests started to fail. E.g.

```
protobuf/3.21.12: Retrieving package 2dbf65f76c0469903ce48756c39d50cd4e721678 from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
protobuf/3.21.12: Package installed 2dbf65f76c0469903ce48756c39d50cd4e721678
protobuf/3.21.12: Downloaded package revision dbe5ad525a64a3eb38f04f92c71c47be
```
How these multiple hashes help me to understand what options does this `protobuf` package have? These hashes are useless for developers, developers needs human readable package description. CC @memsharded 

- I have other dependencies like `pugixml`, which are used privately. And still Conan reports it's missed in  `requires` section. How to handle it depending on whether `pugixml` static or shared? E.g. in dynamic case I agree to add it to `requires` for one  of my components, while for static `pugixml` + dynamic `openvino`, `pugixml` is fully hidden as linked statically into dynamic library. Why Conan does not detect it? How should (and should I) reflect it in my recipe? Similar with `xbyak` which is header only and used privately - by default Conan wants me to add it to `requires`, hence it's a dependency of my package, while it's a build dependency. Any normal examples in documentation?

- Sometimes I see that in `Debug` mode linker stage is killed (likely OOM) - how to handle it? Currently, I just disabled `Debug` build. How many memory is available during the build?

CC @RubenRBS @

**Comment by samuel-emrys** [comment]
> Yes, it's really not used, because it's used on build stage since I need only compiler and don't require library

Flatbuffers is a build requirement in this case, so you should use a `tool_requires` to use it.

```python
def build_requirements(self):
    self.tool_requires("flatbuffers/x.y.z")
```

> More interesting case with `protobuf`, which must be `shared = False` for our package.

You need to validate this in the host context, not the build context - this is a host concern.
```python
def validate(self):
    if self.options["protobuf"].shared: # this might actually have to use self.dependencies
        raise ConanInvalidConfiguration("This library only supports protobuf/*:shared=False")
```

> I have other dependencies like `pugixml`, which are used privately

It sounds like you're using components - if you use any components, you have to model all of your host requirements explicitly. You need to identify which components depend on `pugixml` and add it as a requires to those components as well.

> Sometimes I see that in `Debug` mode linker stage is killed (likely OOM) - how to handle it? Currently, I just disabled `Debug` build. How many memory is available during the build?

This might be a reason to run your build on an xl node, if really required.

It seems to me like you would benefit from some review of the difference between build and host requirements/profiles. This illustrates it using a cross compilation example, but hopefully it also illuminates the difference from a requirements perspective: https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html
