### ISSUE TITLE
[service] Reproducibility of build in Conan CI

### ISSUE THREAD

**Issue by ilya-lavrenov** [conan-io/conan-center-index#19625]
### What is your problem/feature request?

I have the following report from Conan CI https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/19164/82-linux-gcc/openvino/2023.1.0//summary.json where we can see that build with gcc-11 has failed with:
```
Inconsistency detected by ld.so: dl-close.c: 811: _dl_close: Assertion `map->l_init_called' failed!
openvino/2023.1.0 (test package): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
openvino/2023.1.0 (test package): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
ERROR: openvino/2023.1.0 (test package): Error in test() method, line 49
	self.run(bin_path, env="conanrun")
	ConanException: Error 127 while executing ./test_package
```
How can I reproduce the issue? What system is used? 
Our cmake reports that system has glibc 2.23 (which is quite old) and I actually don't know old systems with gcc-11 on board. Is it a custom docker container? How users can pull it?

In fact, Conan CI reports some issues, which I cannot reproduce locally. Any help is appreciated.

**Comment by Nekto89** [comment]
If I'm not mistaken, CI uses docker images that are listed here
https://docs.conan.io/1/howtos/run_conan_in_docker.html#available-docker-images

**Comment by ilya-lavrenov** [comment]
@Nekto89 thanks! I managed to reproduce the issue inside the docker container.
But faced another issue - since Ubuntu 16.04 is deprecated for a while, `apt-get update` does not work and I cannot even install `gdb` to debug the issue. 

@memsharded do you plan to update base images for containers? Why deprecated OS is used?

**Comment by samuel-emrys** [comment]
> But faced another issue - since Ubuntu 16.04 is deprecated for a while, `apt-get update` does not work and I cannot even install `gdb` to debug the issue.

```bash
$ sudo apt update
$ sudo apt install gdb
```
worked fine for me. If you need something more modern than 7.11.1 you can always install from source: https://sourceware.org/gdb/download/

old versions of ubuntu are used to control the glibc version used to compile the binaries for wide availability. You can read about the conan glibc strategy in the readme of https://github.com/conan-io/conan-docker-tools

**Comment by ilya-lavrenov** [comment]
> > But faced another issue - since Ubuntu 16.04 is deprecated for a while, `apt-get update` does not work and I cannot even install `gdb` to debug the issue.
> 
> ```shell
> $ sudo apt update
> $ sudo apt install gdb
> ```
> 
> worked fine for me. If you need something more modern than 7.11.1 you can always install from source: https://sourceware.org/gdb/download/
> 
> old versions of ubuntu are used to control the glibc version used to compile the binaries for wide availability. You can read about the conan glibc strategy in the readme of https://github.com/conan-io/conan-docker-tools

I know how to use `apt`, but it fails by timeout for some repositories, which are not maintained anymore.

> old versions of ubuntu are used to control the glibc version used to compile the binaries for wide availability

The rest of the world is using centos7 for such needs..
