### ISSUE TITLE
[xz_utils/5.2.5] SHA256 signature fails

### ISSUE THREAD

**Issue by gouriano** [conan-io/conan-center-index#19655]
### Description

Starting today I get the following error when trying to use xz_utils/5.2.5:

    Downloading xz-5.2.5.tar.gz completed [0.73k]                                            xz_utils/5.2.5: 
    ERROR: xz_utils/5.2.5: Error in source() method, line 77
        get(self, **self.conan_data["sources"][self.version],
        ConanException: sha256 signature failed for 'xz-5.2.5.tar.gz' file. 
    Provided signature: f6f4910fd033078738bd82bfba4f49219d03b17eb0794eb91efbae419f4aba10  
    Computed signature: 251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed

On Linux:

    $wget https://tukaani.org/xz/xz-5.2.5.tar.gz
    $ shasum -a 256 xz-5.2.5.tar.gz 
    251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed  xz-5.2.5.tar.gz

while the recipe says

    "5.2.5":
    url: "https://tukaani.org/xz/xz-5.2.5.tar.gz"
    sha256: "f6f4910fd033078738bd82bfba4f49219d03b17eb0794eb91efbae419f4aba10"

here:
https://github.com/conan-io/conan-center-index/blob/master/recipes/xz_utils/all/conandata.yml

Unfortunately, this is a serious issue. I am unable to do anything.

### Package and Environment Details

* Package Name/Version: **xz_utils/5.2.5**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

    $wget https://tukaani.org/xz/xz-5.2.5.tar.gz
    $ shasum -a 256 xz-5.2.5.tar.gz 
    251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed  xz-5.2.5.tar.gz

### Logs

Put your log output here

**Comment by ericLemanissier** [comment]
it's a sourceforge problem, same as https://github.com/conan-io/conan-center-index/issues/19651

There should be news on https://fosstodon.org/@sourceforgestatus

**Comment by gouriano** [comment]
yeah... "wget" gets a plain text file with the error message. I see now.
