### ISSUE TITLE
[package] libjpeg-turbo/2.1.5: Error: Provided and Computed signature different (was working few weeks)

### ISSUE THREAD

**Issue by FrancoisDn** [conan-io/conan-center-index#19651]
### Description

   Hi,
I delete my home folder of .conan2, and since that, I have error when conan get and compile `libjpeg-turbo`.
I try with version 2.0.6, 2.1.5 and 3.0.0 but in all case I have an error with provided signature which is different from computed signature.

Few weeks ago (perhaps ~2 months), I'm sure it was working. But since I remove my conan cache folder, I'm not able to use that library anymore.

Note that I have conan 2.0.10.

```
libjpeg-turbo/2.1.5: Calling source() in /home/xxxx/.conan2/p/libjpe672b41500ae4/s/src
ERROR: libjpeg-turbo/2.1.5: Error in source() method, line 89
	get(self, **self.conan_data["sources"][self.version], strip_root=True)
	ConanException: sha256 signature failed for 'libjpeg-turbo-2.1.5.tar.gz' file. 
 Provided signature: bc12bc9dce55300c6bf4342bc233bcc26bd38bf289eedf147360d731c668ddaf  
 Computed signature: 251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed
```

### Package and Environment Details

* Package Name/Version: **libjpeg-turbo/2.1.5**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **clang 14**
* Conan version: **conan 2.0.10**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=14
compiler.libcxx=libstdc++11
build_type=Debug
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install -of=/home/fjean/Projects/fetoly_cpp/main/build/Debug-clang-14 -b=missing -r=conancenter --requires libjpeg-turbo/2.1.5 -s=compiler.cppstd=17 -s=compiler=clang -s=compiler.version=14 -s=build_type=Debug

### Logs

<details><summary>Click to expand log</summary>

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=17
compiler.version=14
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    libjpeg-turbo/2.1.5#1186fc7201b915ca136ae2807b986d88 - Cache
Build requirements
    nasm/2.15.05#ca1c14c2060af0ec151048b54ced9262 - Cache

======== Computing necessary packages ========
Requirements
    libjpeg-turbo/2.1.5#1186fc7201b915ca136ae2807b986d88:48df117a13f1c0fec2091412acc9f6cb6e658110 - Build
Build requirements
    nasm/2.15.05#ca1c14c2060af0ec151048b54ced9262:3593751651824fb813502c69c971267624ced41a#eba14be08be22f3ee2a36952c86dcddd - Cache

======== Installing packages ========
nasm/2.15.05: Already installed! (1 of 2)
libjpeg-turbo/2.1.5: WARN: Trying to remove corrupted source folder
libjpeg-turbo/2.1.5: WARN: This can take a while for big packages
libjpeg-turbo/2.1.5: Calling source() in /home/xxxx/.conan2/p/libjpe672b41500ae4/s/src
ERROR: libjpeg-turbo/2.1.5: Error in source() method, line 89
	get(self, **self.conan_data["sources"][self.version], strip_root=True)
	ConanException: sha256 signature failed for 'libjpeg-turbo-2.1.5.tar.gz' file. 
 Provided signature: bc12bc9dce55300c6bf4342bc233bcc26bd38bf289eedf147360d731c668ddaf  
 Computed signature: 251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed
```

</details>

**Comment by ericLemanissier** [comment]
it's a temporary sourceforge outage, as I got in https://github.com/conan-io/conan-center-index/pull/19648 (pay attention to the Computed signature, it's the same for all failures).
cf https://sourceforge.net/projects/libpng/files/libpng16/1.6.40/libpng-1.6.40.tar.xz

**Comment by ericLemanissier** [comment]
you can follow news on https://fosstodon.org/@sourceforgestatus/111022248071061762

**Comment by FrancoisDn** [comment]
thank you !

**Comment by ericLemanissier** [comment]
This can be closed, now that sourceforge is back on track
