### ISSUE TITLE
[question] libmysqlclient : missing tool requirement ?

### ISSUE THREAD

**Issue by oleurodecision** [conan-io/conan-center-index#19654]
### What is your question?

When trying to consume _libmysqlclient_ (as a requirement) on a far-from-homogenous Linux system (project build with some user-built compiler, different from the system one, with different _glibc_), the build of _libmysqlclient_ fails because of _glibc_ incompatibilities.  
Something like

```
-- Found Doxygen: /usr/bin/doxygen  found components: doxygen dot 
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/bin/doxygen)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/bin/doxygen)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /usr/bin/doxygen)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libclang-14.so.13)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libclang-cpp.so.14)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libclang-cpp.so.14)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /lib/x86_64-linux-gnu/libclang-cpp.so.14)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /lib/x86_64-linux-gnu/libLLVM-14.so.1)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libLLVM-14.so.1)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libLLVM-14.so.1)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libz3.so.4)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libz3.so.4)
/usr/bin/doxygen: /opt/gcc-10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libicuuc.so.72)
```

Well, there are many ways to solve this issue.  The easiest and generalised one being to add _Doxygen_ as a tool requirement in the profile used for the build, like
```
[tool_requires]
doxygen/1.9.4
```

But it still seems to me that _Doxygen_ *should* have been added as a tool requirement in the recipe, as it is mandatory for the build to success in this kind of setup

Am I wrong ?

If requirement miss is confirmed, I can submit the PR.

Thanks

**Comment by SpaceIm** [comment]
doxygen is not missing because if it's not there it builds and produce the same binaries in package folder. Instead libmysqlclient recipe should disable build of documentation and not try to find doxygen (or not try to build doc even if doxygen is found).

**Comment by RubenRBS** [comment]
> Instead libmysqlclient recipe should disable build of documentation in CMakeLists and not try to find doxygen (or not try to build doc even if doxygen is found).

Agree, I'll try to open a PR to address this
