### ISSUE TITLE
[package] zlib/1.2.11: Fails to build locally on linux

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan-center-index#1966]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.11**
  * Operating System+version: **Linux Redhat 7**
  * Compiler+version: **GCC 8.3.1**
  * Conan version: **conan 1.25.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Debug
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
* add requirement to zlib/1.2.11
* run: conan install .. --profile=my_profile --build zlib
* Get error:
ERROR: zlib/1.2.11: Error in source() method, line 42
	tools.patch(patch_file="minizip.patch", base_path=self._source_subfolder)
	FileNotFoundError: [Errno 2] No such file or directory: 'minizip.patch'

**Comment by uilianries** [comment]
Hi @rconde01 !

Your recipe is outdated, the current recipe doesn't apply minizip patch. Maybe is it from conan-community? Please, review the provider of your recipe and update it to the newest version.

**Comment by rconde01** [comment]
ok - indeed, I deleted the cache, re-ran and it worked.

**Comment by uilianries** [comment]
@rconde01 thanks for your feedback!

**Comment by maichmueller** [comment]
Hi, i am facing the same issue when running conan from cmake inside a github action script. The conanfile reads:
```
[requires]
gtest/1.10.0
boost/1.73.0

[generators]
cmake
```
and during github workflow activation runs into the error 
```
Installing (downloading, building) binaries...
b2/4.2.0: Already installed!
bzip2/1.0.8: Already installed!
gtest/1.10.0: Already installed!
zlib/1.2.11: Configuring sources in /home/michael/.conan/data/zlib/1.2.11/_/_/source

zlib/1.2.11: WARN: Package is corrupted, removing folder: /home/michael/.conan/data/zlib/1.2.11/_/_/package/6b7ff26bfd4c2cf2ccba522bfba2d2e7820e40da
zlib/1.2.11: WARN: Build folder is dirty, removing it: /home/michael/.conan/data/zlib/1.2.11/_/_/build/6b7ff26bfd4c2cf2ccba522bfba2d2e7820e40da
zlib/1.2.11: WARN: Trying to remove corrupted source folder
zlib/1.2.11: WARN: This can take a while for big packages
ERROR: zlib/1.2.11: Error in source() method, line 42
	tools.patch(patch_file="minizip.patch", base_path=self._source_subfolder)
	FileNotFoundError: [Errno 2] No such file or directory: 'minizip.patch'
```

However this error doesn't occur locally for me when running conan from cmake with this setup, which is a little puzzling. Is this a bad dependency in Boost using the old recipe on a github runner? And if so, can I mitigate it?

**Comment by uilianries** [comment]
Hi @maichmueller please, open a new issue on the next time and point this one as related, so we can count how many issues (or people) exist related to the same problem.

Anyway, my answer is same as before, you are using an outdated version of zlib.

The package Boost 1.73 will consume the latest zlib/1.2.11 available. Thus, or you are using a specific revision (lockfiles), or you have a cache to avoid downloading all packages for every new build (boost is a big package, so caching sounds be a good option). Please, check your github yaml file for the cache feature.  Also, you could force a cache removal before building, like `conan remove -f "*"`, if there is a cached folder, it will remove all packages from there.

Regards
