### ISSUE TITLE
[question] Use only one recipe for sentry-native/crashpad/breakpad

### ISSUE THREAD

**Issue by MartinDelille** [conan-io/conan-center-index#19675]
### What is your question?

After talking to the sentry-native developer [here](https://github.com/getsentry/sentry-native/pull/872#issuecomment-1693542784) he advised me that we should have only one recipe instead of three:
- sentry-native
- sentry-crashpad
- sentry-breakpad

I wondered what was the thought of the community and why the recipe had been splited originally.

I ping @madebr who originaly created the sentry-breakpad/crashpad recipe and @paulharris who recently pushed a fix the sentry-crashpad.

**Comment by madebr** [comment]
Please read the original prs that created these packages instead of asking. I think the original idea is explained there.
If it's not valid anymore, or has become unworkable, feel free to deprecate the sentry-* packages, and merge them in sentry-native.

**Comment by MartinDelille** [comment]
I indeed read the [following comment](https://github.com/conan-io/conan-center-index/pull/5536#issuecomment-848669431) where you explain clearly why you created these two recipes.

I spoke also to the conan team about it and they will come back to us regarding what they would recommand.
