### ISSUE TITLE
[question] Way to control build flags for packages?

### ISSUE THREAD

**Issue by dvhwgumby** [conan-io/conan-center-index#19690]
### What is your question?

Some packages have configs controlled by CMake options (which can be passed in as environment variables to cmake).  For example spdlog has SPDLOG_FMT_EXTERNAL.  Is there any way to pass these via `conan install` or in the conanfiles.txt?

**Comment by SpaceIm** [comment]
No. It's controlled by recipe, and eventually exposed as an option.

**Comment by dvhwgumby** [comment]
Thanks.  Someday it would be nice to have the options listed in the "how to use" on conan center in some automated fashion, but with that clue it is now pretty easy to find what I need by looking at the recipe, and _that_ is easy to get to from conan center.

Actually it would be good someday if conan center could autogenerate the "how to use" containing options and also the cmake `find_package` and `target_link_libraries`. But there are far more important features to add, especially when one can so easily look in the recipe!
