### ISSUE TITLE
[spdlog/1.6.1] : CMake Config files not available

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan-center-index#1970]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spdlog/1.6.1**
  * Operating System+version: **Windows 10** (But it will happen on any OS)
  * Compiler+version: **MSVC 2019**
  * Conan version: **conan 1.23.0**
  * Python version: **Python 3.8.1**

### Conan profile
```
$ conan profile show vs16Debug
Configuration for profile vs16Debug:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.runtime=MDd
build_type=Debug
[options]
[build_requires]
[env]```


### Steps to reproduce (Include if Applicable)
Consume spdlog/1.6.1 with the conan client. Then try to consume the **spdlog** from other project being configured with CMake, as it is advised here:

https://github.com/gabime/spdlog/blob/v1.x/example/CMakeLists.txt

When running CMake, I have the following error:
```bash
CMake Error at cmake/findDependencies.cmake:8 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake
```

### More details

The problem seems to be that in the spdlog conan recipe, some directories are removed in the package step (and one of these folders is the CMake one).

https://github.com/conan-io/conan-center-index/blob/master/recipes/spdlog/all/conanfile.py

I do not understand why this folder is removed, when it is a valuable resource being installed in spdlog:

https://github.com/gabime/spdlog/blob/22a169bc319ac06948e7ee0be6b9b0ac81386604/CMakeLists.txt#L274-L324

**Comment by uilianries** [comment]
Hi @piponazo !

Please, read [here](https://github.com/conan-io/conan-center-index/wiki/FAQ#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged) to understand why they are not packaged.

As alternative, you should use [cmake_find_package](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html) generator. It will generate `Findxxx.cmake`. If it doesn't work, please, open an issue reporting, because that generator is the way, so we should fix the recipe for any problem.

Regards.

**Comment by Croydon** [comment]
@piponazo If you have further questions, please ask them.

For now I guess we can close this one

**Comment by piponazo** [comment]
Hi, sorry for the late response, somehow I forgot about this issue.

I think I understood the issue, you can close it. Thanks for the feedback.

Just for future reference, the link provided by @uilianries is not valid anymore (in case you want to fix it 😉 )

**Comment by Croydon** [comment]
The documentation got moved

the new location for this FAQ particular is https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged
