### ISSUE TITLE
[service] Don't merge PRs that break packages

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#19734]
### What is your problem/feature request?

I've just noticed that the V2 version of my recipe `sail` suddenly disappeared from the center. This was caused by https://github.com/conan-io/conan-center-index/pull/18454

Please please please don't merge pull requests that break packages.

**Comment by RubenRBS** [comment]
Hi. There are checks in place to avoid exactly this: Once a package is v2 ready, it should won't be allowed to get a new PR merged that breaks it.

What could have happened is this:

sail gets ported to conan 2 -> a bot opens a PR to put it on the main list, _but_ it needs manual approval from us, so it stayed unmerged for some amount of time, in which the linked PR got posted and merged

What we can do is to fix it in another PR and the packages will be published transparently, so thanks for the ping :)

(Note that this can't happen nowadays, as v2 is now mandatory and so no PR is actually merged if it's not Conan v2 compatible)
