### ISSUE TITLE
package: HDF5 , All versions, Enhancement:Add build option, FORTRAN

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan-center-index#1974]
For:

- hdf5/1.8.21
- hdf5/1.10.6
- hdf5/1.12.0
-

I would like you to add the following build options to the recipe  ( as listed here:https://support.hdfgroup.org/HDF5/release/chgcmkbuild.html )

Options to add:
- FORTRAN_LIBRARIES

I saw where you added threadsafe recently

**Comment by dgokcin** [comment]
any updates on this?

**Comment by ShamanTcler** [comment]
Not needed for me anymore ... I retired :)  And I highly recommend retirement, though I just left a FreeCad developers meeting

**Comment by perseoGI** [comment]
Hahahahaha that is not in my future plans hahaha, still have a lot to work!
Happy to hear you still into dev meeting, once a dev, always a dev!
