### ISSUE TITLE
[package] coin-utils/2.11.6: Cannot load recipe

### ISSUE THREAD

**Issue by shellshocked2003** [conan-io/conan-center-index#19752]
### Description

I include coin-clp as a required package for my build. When I run conan install, coin-utils must be built since coin-clp depends on it. However, I get the following error message:

![image](https://github.com/conan-io/conan-center-index/assets/10856474/33ee3c0e-654c-44c2-a33e-c77d56cf9459)

It's not clear to me why the recipe cannot load, since it looks like it's been updated for conan2...

### Package and Environment Details

* Package Name/Version: **coin-utils/2.11.6**
* Operating System+version: **Scientific Linux 7.9**
* Compiler+version: **GCC 12.1.0**
* Conan version: **conan 2.0.6**
* Python version: **Python 3.7.9**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

### Steps to reproduce

conan install . --output-folder=build --build=missing -s build_type=Release --profile:build=gcc12 --profile:host=gcc12

### Logs

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

======== Computing dependency graph ========
Graph root
    conanfile.txt: /global/scratch/projects/fc_demlbm/mhgardner/WorkSpace/waLBerla-Reno/conanfile.txt
Requirements
    coin-clp/1.17.7#fb18520c2691b592e406158a5e1d490b - Cache
    eigen/3.3.7#3e0da8490c5baaa197f40586827740a0 - Cache
    nlohmann_json/3.7.0#9b8810ba7286dabedb8cd1496f09cd64 - Cache
    zlib/1.2.13#e377bee636333ae348d51ca90874e353 - Cache
*********************************************************
Recipe 'coin-utils/2.11.6' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'coin-utils/2.11.6' not resolved: coin-utils/2.11.6: Cannot load recipe.
Error loading conanfile at '/global/home/users/mhgardner/.conan2/p/coin-973cab011163a/e/conanfile.py': /global/home/users/mhgardner/.conan2/p/coin-973cab011163a/e/conanfile.py not found!.

**Comment by SpaceIm** [comment]
Your conan cache seems to be corrupted. Remove coin-utils and try again.

**Comment by shellshocked2003** [comment]
That did the trick, thanks! How did you know this was the case? Was it because of the "broken recipe" output?

**Comment by SpaceIm** [comment]
Because of this error `conanfile.py not found`. All conan recipes have a conanfile.py, so if it's missing it means that your cache was corrupted.

**Comment by shellshocked2003** [comment]
Got it, thanks. Appreciate your help!
