### ISSUE TITLE
[package] boost/1.73.0: b2-default option messes up include directory

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan-center-index#1979]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.73.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019**
  * Conan version: **conan 1.26.0**
  * Python version: **Python 3.7.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
1. Use the following conanfile.txt
```
[requires]
boost/1.73.0

[options]
boost:shared=True
boost:layout=b2-default
```
2. Run `conan install . --profile=..\my-profile -r conan-center --build boost`
3. The generated include directory will contain boost-1_73/boost/... rather than boost/...
4. This will cause include search to fail

**Comment by SSE4** [comment]
I think this layout is how boost install works itself - right now we're not changing layout and not copying files manually, we're fully relying on `b2 install` command to properly copy headers and libraries. it ensures files could be properly located by the `find_package`, `pkg-config` or any other means.
I am going to check locally if it causes any troubles and let you know.
/cc @grafikrobot
