### ISSUE TITLE
[question] SHORT DESCRIPTION

### ISSUE THREAD

**Issue by denys-valchuk-vm** [conan-io/conan-center-index#19809]
### What is your question?

With the new interface how I can view list of existent recipe revisions (for the same version of conan package)

**Comment by RubenRBS** [comment]
Hi @denys-valchuk-vm, thanks for your question.

When designing the new interface, we identified that having access to recipe revisions was a super specific niche that very few people ask for (and which has not too many uses!), and that we could save backend complexity by dropping that, so we did.

For more advanced queries, we recommend using the conan client CLI for those tasks - Specially in Conan 2.X, the `conan list` command is capable of showing pretty much any information to that regard that you might need :)
