### ISSUE TITLE
[service] default C++17 standard for gcc >= 9 (and others)

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan-center-index#1984]
I've noticed that default cpp standard for gcc9 is 14, however gcc has complete support for C++ 17 starting with version 9 and to me it makes sense to increase the default.

We want to use modern compilers with modern C++ and it's unfortunate surprise that there are no prebuilt packages in CCI for 17.

This may be an issue for Conan to generate default profile with updated setting because having consistent detected profile is a big plus.

**Comment by SSE4** [comment]
seems to be correct, running on `conanio/gcc9`:
```
conan@7a5aefa54a1c:~$ g++ -dM -E -x c++ /dev/null | grep __cplusplus
#define __cplusplus 201402L
```

**Comment by ytimenkov** [comment]
Ah, that's how autodetect works...
According to the internet default change only in gcc-11 😞

I wonder if it's still possible for cci to have another default...

**Comment by SSE4** [comment]
@ytimenkov I think it would be misleading if we change default in conan, most of users will expect conan default to be same as compiler default (IMO). you still may specify custom `compiler.cppstd` and build from sources, if needed.

**Comment by ytimenkov** [comment]
🤷‍♂️ makes sense.
