### ISSUE TITLE
[question] Migrating from VisualStudioBuildEnvironment to Conan V2

### ISSUE THREAD

**Issue by SkyWhiteEagle** [conan-io/conan-center-index#19954]
### What is your question?

Hello,

I am trying to migrate the pango recipe to Conan V2. I'm new to the Meson helpers, and there are usage of `VisualStudioBuildEnvironment` in that recipe. I found it in the [Conan V1](https://docs.conan.io/1/reference/build_helpers/visual_studio.html) version but not in V2 and haven't found any upgrade path.

Is there an example of how to migrate such usage?

Thanks in advance.

**Comment by SpaceIm** [comment]
`VisualStudioBuildEnvironment` in legacy Meson helper was a workaround, you don't need this trick with MesonToolchain + Meson.

**Comment by SpaceIm** [comment]
see Meson package template: https://github.com/conan-io/conan-center-index/blob/master/docs/package_templates/meson_package/all/conanfile.py

**Comment by SkyWhiteEagle** [comment]
Thank you. I'll try to give it a look soon and hopefully have a PR for pango.

**Comment by SpaceIm** [comment]
FYI, there are already 3 PRs attempting to migrate pango to conan v2:
https://github.com/conan-io/conan-center-index/pull/12382
https://github.com/conan-io/conan-center-index/pull/17655
https://github.com/conan-io/conan-center-index/pull/18874

**Comment by SkyWhiteEagle** [comment]
Oh, thanks a lot, I only searched the issues, forgot to do a separate search in PR.
