### ISSUE TITLE
[service] Check for config.yml when bumping a version

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#2001]
CCI PR to bump a version are simple, only add a new version on config.yml and conandata.yml

Sometimes, people can forget about update the config.yml (when required) and the reviewers can approve and merge without that config. Silently, CCI won't generate the new version, but the CI result will be green. It's seems be impossible, but it happened in the past and I see new PRs with config.yml missing

**Comment by madebr** [comment]
Adding some simple tests to a github action would give people faster feedback.

**Comment by uilianries** [comment]
@danimtb 
> Do you have a link to a CCI pull request that reproduced a different behavior for the same case?

https://github.com/conan-io/conan-center-index/pull/1924

**Comment by danimtb** [comment]
this was done a long time ago, closing. Thanks!
