### ISSUE TITLE
[package] taocpp-pegtl/2.8.3: CMake find_package compatibility

### ISSUE THREAD

**Issue by rbrich** [conan-io/conan-center-index#2003]
I think the recipe should contain `cpp_info.name = "pegtl"` as [documented here](https://docs.conan.io/en/latest/reference/generators/cmake_find_package_multi.html#generated-files) to allow `find_package(pegtl)` instead of `find_package(taocpp-pegtl)`. The first variant is what [PEGTL docs](https://github.com/taocpp/PEGTL/blob/master/doc/Installing-and-Using.md#find_package) recommend and it's also used by system package managers like Debian, Homebrew etc.

[Example of a package doing this.](https://github.com/conan-io/conan-center-index/blob/master/recipes/catch2/2.x.x/conanfile.py#L58)

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **taocpp-pegtl/2.8.3**
  * OS etc.: *not relevant*

### Steps to reproduce (Include if Applicable)

1. Create `conanfile.txt` like this one:
```
[requires]
taocpp-pegtl/2.8.3

[generators]
cmake_find_package_multi
```

2. Create `CMakeLists.txt`:

```
cmake_minimum_required(VERSION 3.9)
project(TryPegtl CXX)
list(APPEND CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})
find_package(pegtl REQUIRED)
```

3. Try to generate build files:
```
conan install .
cmake .
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
-- The CXX compiler identification is GNU 10.1.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "Findpegtl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pegtl", but
  CMake did not find one.

  Could not find a package configuration file provided by "pegtl" with any of
  the following names:

    pegtlConfig.cmake
    pegtl-config.cmake

  Add the installation prefix of "pegtl" to CMAKE_PREFIX_PATH or set
  "pegtl_DIR" to a directory containing one of the above files.  If "pegtl"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

</details>

**Comment by madebr** [comment]
It should provide a `taocpp::pegtl` target.
See https://github.com/taocpp/PEGTL/blob/b46c696ced0f164cde79871d22333612e8e256e1/CMakeLists.txt#L70-L77
Can conan do this? @danimtb

**Comment by prince-chrismc** [comment]
Blocked by https://github.com/conan-io/conan/issues/7254

**Comment by prince-chrismc** [comment]
this has been fixed https://github.com/conan-io/conan-center-index/pull/2823
