### ISSUE TITLE
[question] Creating and hosting your own ConanCenter binaries

### ISSUE THREAD

**Issue by unfor19** [conan-io/conan-center-index#20055]
### What is your question?

Hey Diego (@memsharded), I'm reaching out here so the community can benefit from your tremendous support.

Regarding [Creating and hosting your own ConanCenter binaries](https://docs.conan.io/2/devops/conancenter/hosting_binaries.html#devops-conancenter-hosting-your-own-conancenter-fork), the current suggested process -

1. Create a fork of [conan-center-index](https://github.com/conan-io/conan-center-index).
2. Create a list of packages that you need and add it to the fork.
3. Create a script that first `conan export` all the packages in your list, then `conan create --build=missing` them.
4. Upload your build packages to your own server that you use in production instead of ConanCenter.

I want to focus on point **3** - what about indirect dependencies? How can I make sure they are built from my fork, rather than attempting to access the public ConanCenter?

When doing the `conan export` and `conan create`, the default remote is `conancenter`, and if I change it to my remote, it is empty, so I'm trying to realize the benefit of the fork if either way I'll build my packages for the first time using `conancenter`.

Is there a way to instruct the `conan` CLI to build recipes from a local directory? Here's a tweak for point 3, if it's possible

3. Create a script that first `conan export` all the packages in your list, then `conan create --build=missing` them. **ADDED** - add `--recipes-path` to build all packages from a local clone of `conan-center-index`.

That way, the fork is meaningful, and I'm creating packages according to a specific point in time (commit).

Can you please share your thoughts about the process? I feel a bit lost

**Comment by memsharded** [comment]
Hi @unfor19 

> I want to focus on point 3 - what about indirect dependencies? How can I make sure they are built from my fork, rather than attempting to access the public ConanCenter?

Good point. This is exactly one of the things that we are trying to improve UX with new tools.
At the moment the recommendation is:
- Remove ``conancenter`` remote completely
- When something fails, add the missing package to the list of packages to export from your fork

It is an iterative process that will take you some minutes until you collect the transitive dependencies, but maintaining it from there will be straightforward.
As you suggested, it is possible to make it automatic, a script that iterates, checks the build-missing error messages adds to the list and repeat. In practice it is relatively simple to do it by hand, not a huge issue. And the tools like the one you are suggesting is how we are thinking to automate this with new conan tools.


Please let me know if this helps.

**Comment by unfor19** [comment]
@memsharded Sounds like a plan
For now, we've decided to write a script that does the following-
1. Iterate over all recipes; for each recipe, `conan export` and `conan upload` - this will be according to the `config.yml` of each recipe
2. Build the "list of required 3rd parties" and upload all to internal artifactory server -  `conan install --build=missing` and `conan upload --all`
3. Build internal applications with references to the built 3rd parties

I just wanted to make sure we're doing something legit, sounds like we are :)
