### ISSUE TITLE
[package] armadillo/12.2.0 Doesn't use upstream cmake target

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan-center-index#20067]
### Description

CMake has a published [`FindArmadillo.cmake`](https://cmake.org/cmake/help/latest/module/FindArmadillo.html) module that defines the filename to be `Armadillo` and the target to be `Armadillo::Armadillo`. This is in contrast to the default recipe `armadillo::armadillo` currently used.

This should be updated to reflect the upstream convention.

### Package and Environment Details

N/A

### Conan profile

N/A

### Steps to reproduce

N/A

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by SpaceIm** [comment]
There is `Armadillo::Armadillo` target in https://cmake.org/cmake/help/latest/module/FindArmadillo.html

**Comment by samuel-emrys** [comment]
Thanks for the clarification @SpaceIm. You're right, there are a few things missing. To clarify, if `cmake_file_name` is modified to `Armadillo`, shouldn't the target also be `Armadillo::Armadillo`? It looks like the official FindArmadillo.cmake file doesn't define a target at all and advocates usage as follows:

```cmake
find_package(Armadillo REQUIRED)
include_directories(${ARMADILLO_INCLUDE_DIRS})
add_executable(foo foo.cc)
target_link_libraries(foo ${ARMADILLO_LIBRARIES})
```

We obviously want to support this, but wouldn't we also want to support the following?

```cmake
find_package(Armadillo REQUIRED)
add_executable(foo foo.cc)
target_link_libraries(foo Armadillo::Armadillo)
target_link_libraries(foo Armadillo) # or this?
target_link_libraries(foo armadillo::armadillo) # seems the least desirable given other defaults
```
