### ISSUE TITLE
[package] ncurses/6.4: Seems to not be conan2 compatible

### ISSUE THREAD

**Issue by benny-edlund** [conan-io/conan-center-index#20084]
### Description

Was told this package may not have been updated to conan/2 as i was updating my own project

### Package and Environment Details

* Package Name/Version: **ncurses/6.4**
* Operating System+version: **Linux Ubuntu 20.04 (win10 wsl2)**
* Compiler+version: **GCC 9.4**
* Conan version: **conan 2.0.10**
* Python version: **Python 3.8.10**

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

### Steps to reproduce
git  clone https://github.com/benny-edlund/task-pool/
cd task-pool/examples
git checkout conan_examples_update
conan install . --output-folder=build --build=missing --settings=build_type=Release

### Logs

<details><summary>Click to expand log</summary>

```
*********************************************************
Recipe 'ncurses/6.3' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'ncurses/6.3' not resolved: ncurses/6.3: Cannot load recipe.
Error loading conanfile at '/home/benny/.conan2/p/ncurse90fb70e239f8/e/conanfile.py': Unable to load conanfile in /home/benny/.conan2/p/ncurse90fb70e239f8/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/benny/.conan2/p/ncurse90fb70e239f8/e/conanfile.py", line 1, in <module>
    from conans import AutoToolsBuildEnvironment, ConanFile, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conans' (/home/benny/.local/lib/python3.8/site-packages/conans/__init__.py)```

</details>

**Comment by SpaceIm** [comment]
There are 2 PRs: https://github.com/conan-io/conan-center-index/pull/17805 & https://github.com/conan-io/conan-center-index/pull/18568
