### ISSUE TITLE
[question] how to build (e.g. libgettext) for x86_64 on an Apple Silicon Mac?

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan-center-index#20103]
### What is your question?

Hi!

i am trying to build x86_64 binaries on an M2 Mac but at least the packages using autotools seem to be built for armv8 still.
There is a libgettext/0.21 binary package for x86_64 available on the ConanCenter remote but for a different apple-clang version.

Here are my host and build profiles:
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
build_type=Release
```

There is just "build system type" and "host system type" "aarch64-apple-darwin22.3.0" in the "configure output and "-m64" used as commandline parameter for the gcc so arm64 binaries are produced.
For packages using Meson or CMake it seems to work though.

**Comment by jcar87** [comment]
HI @petermbauer - thanks for your question.

What version of Conan are you using? With the most recent 1.x versiona and 2.0, you have to use the two profile model:

`--profile:host xxx --perofile:build yyy`
where the `xxx` profile has `arch=x86_64` and the build profile has `arch=armv8` (the native architecture of the machine where the build is happening).

This should cause Conan to use the cross-building logic when interfacing with things that are built with autotools

**Comment by petermbauer** [comment]
Hi @jcar87 , thanks a lot for the hint regarding the build profile, this was exactly what i missed.
