### ISSUE TITLE
[package] protobuf/*: incorrect RPATH on MacOS w/ with_zlib=True

### ISSUE THREAD

**Issue by Cogitri** [conan-io/conan-center-index#20102]
### Description

When building protobuf on MacOS with `with_zlib=True`, the package_folder of `zlib` isn't included in `protobuf`'s RPATH. As such, running `protoc` fails because it can't find `@rpath/zlib.dylib`.

### Package and Environment Details

* Package Name/Version: **protobuf/3.21.12**
* Operating System+version: **MacOS 13.5.1**
* Compiler+version: **Apple clang version 15.0.0 (clang-1500.0.40.1)**
* Conan version: **conan 2.0.9**
* Python version: **Python 3.11.3**

### Conan profile

[settings]
arch = x86_64
build_type = Release
compiler = apple-clang
compiler.cppstd = 20
compiler.libcxx = libc++
compiler.version = 15
os = Macos
os.version = 10.15

### Steps to reproduce

conan install -r conancenter--requires=protobuf/3.21.12 -o "*:shared=True"

### Logs

<details><summary>Click to expand log</summary>

```
dyld[44252]: Library not loaded: @rpath/libz.1.dylib
  Referenced from: <12487EAF-0251-3D44-A4C3-7E4721B31A02> /Users/dev/.conan2/p/b/proto7bde3c2dd0ea7/p/lib/libprotobufd.3.21.12.0.dylib
  Reason: tried: '/Users/dev/.conan2/p/b/proto7bde3c2dd0ea7/p/lib/libz.1.dylib' (no such file), '/Users/dev/.conan2/p/b/proto7bde3c2dd0ea7/p/lib/libz.1.dylib' (no such file), '/Users/dev/.conan2/p/b/proto7bde3c2dd0ea7/p/bin/../lib/libz.1.dylib' (no such file), '/Users/dev/.conan2/p/b/proto7bde3c2dd0ea7/p/bin/../lib/libz.1.dylib' (no such file)
```

</details>

**Comment by SpaceIm** [comment]
> When building protobuf on MacOS with with_zlib=True, the package_folder of zlib isn't included in protobuf's RPATH. As such, running protoc fails because it can't find @rpath/zlib.dylib.

Adding zlib to `LC_RPATH` of protoc is not a long term solution, since zlib path in conan cache can change (if protobuf has been built on another machine, or if another version of zlib than the one used during build and not leading to a rebuild of protobuf is injected in the dependency graph).

Apple SIP reseting `DYLD_LIBRARY_PATH` is a blocker, and there is nothing conan can do against this anti-developer feature.

**Comment by Cogitri** [comment]
Ah, that makes sense. We'll just have to build protobuf w/ zlib:shared=False then
