### ISSUE TITLE
[package] cmake: Windows 10 Cygwin, cmake not found

### ISSUE THREAD

**Issue by ngerke** [conan-io/conan-center-index#2015]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cmake/3.17.3**
  * Operating System+version: **Windows 10**
  * Conan version: **conan 1.24.1**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[build_requires]
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler=Visual Studio
compiler.version=15
compiler.toolset=v141
build_type=Release
arch_build=x86_64
os_build=Windows
[options]
[env]
```

### Steps to reproduce (Include if Applicable)
In our CI-Environment we start conan from a Cygwin Shell. Former we maintained CMake packages ourselves, which work fine by appending the path:

```python
    def package_info(self):
        self.env_info.path.append(os.path.join(str(self.package_folder), "bin"))
```

We now wanted to use the conan-center version, but cmake is not found on our Windows nodes when used as build requirement in other Recipes (I'm not trying to build CMake):

```
'cmake' is not recognized as an internal or external command
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>
</details>

**Comment by Croydon** [comment]
If you build CMake from source you need CMake. Afterwards you can start using Conan to deploy your newly build CMake binaries

So the solution is to install CMake by some other means on your CI or re-use the binaries CCI provides

**Comment by ngerke** [comment]
I updated the issue. I'm not trying to build CMake im tying to build pkgs with CMake from conan-center

**Comment by Croydon** [comment]
Oh, sorry I got this wrong.

Are you using the virtuelenv generators? The example even uses CMake

https://docs.conan.io/en/latest/mastering/virtualenv.html

**Comment by ngerke** [comment]
Uh sorry I solved it, after deeper digging I found out that there was a mistake in our scripting which let conan to use the wrong profile. Now it's working
