### ISSUE TITLE
[request] llvm/13.0.0

### ISSUE THREAD

**Issue by JafrinNevis** [conan-io/conan-center-index#20163]
### Package Name/Version

llvm/13.0.0

### Changelog

https://github.com/conan-io/conan-center-index/blob/master/recipes/llvm-core/all/conanfile.py

### Context about the new update

This recipe is not working for conan version 2.0, conan v2  doesn't support the generator used here

**Comment by Croydon** [comment]
Please close this as a duplicate of #20339

**Comment by uilianries** [comment]
Closing this issue as duplicated. Please, commented in the issue #20339
