### ISSUE TITLE
ffmpeg/6.0: One of ffmpeg's dependencies, libiconv/1.17, throws an "Error in build() method, line 126, autotools.make()" 

### ISSUE THREAD

**Issue by Odinaka-git** [conan-io/conan-center-index#20164]
### Description

I'm trying to download the ffmpeg library for a project I'm working on, so far most of it's dependencies have been installed successfully. But errors start to occur once libiconv/1.17 needs to be installed. other than the "Error in build() method, line 126 autotools.make()" and "ConanException: Error 2 while executing make -j16" exception it throws, It also lists the following errors:
error: invalid use of undefined type ‘const struct _stati64’, and
conflicting types for ‘rpl_stat’; have ‘int(const char *, struct _stati64 *)’

### Package and Environment Details

* Package Name/Version: **ffmpeg/6.0** **libiconv**
* Operating System+version: **windows 11**
* Compiler+version: **GCC 13.1**
* Docker image: **not downloaded**
* Conan version: **conan 1.61.0**
* Python version: **Python 3.11.5**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conanfile.txt give below:
[requires]
ffmpeg/6.0

[generators]
CMakeDeps
CMakeToolchain

[layout]
cmake_layout

[imports]
bin, *.dll -> ./bin # Copies all dll files from packages bin folder to my "bin" folder
lib, *.dylib* -> ./bin # Copies all dylib files from packages lib folder to my "bin" folder

command used: conan install conanfile.txt --build=missing

### Logs

<details><summary>Click to expand log</summary>

In file included from /c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.c:21:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_atime_ns’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:69:10: note: in expansion of macro ‘STAT_TIMESPEC’
   69 |   return STAT_TIMESPEC (st, st_atim).tv_nsec;
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_ctime_ns’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:82:10: note: in expansion of macro ‘STAT_TIMESPEC’
   82 |   return STAT_TIMESPEC (st, st_ctim).tv_nsec;
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_mtime_ns’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:95:10: note: in expansion of macro ‘STAT_TIMESPEC’
   95 |   return STAT_TIMESPEC (st, st_mtim).tv_nsec;
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_atime’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:121:10: note: in expansion of macro ‘STAT_TIMESPEC’
  121 |   return STAT_TIMESPEC (st, st_atim);
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_ctime’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:135:10: note: in expansion of macro ‘STAT_TIMESPEC’
  135 |   return STAT_TIMESPEC (st, st_ctim);
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_mtime’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:149:10: note: in expansion of macro ‘STAT_TIMESPEC’
  149 |   return STAT_TIMESPEC (st, st_mtim);
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_birthtime’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:167:7: note: in expansion of macro ‘STAT_TIMESPEC’
  167 |   t = STAT_TIMESPEC (st, st_birthtim);
      |       ^~~~~~~~~~~~~
make[2]: *** [Makefile:1780: libicrt_a-stat-time.o] Error 1
In file included from /c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat.c:54:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_atime_ns’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:69:10: note: in expansion of macro ‘STAT_TIMESPEC’
   69 |   return STAT_TIMESPEC (st, st_atim).tv_nsec;
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_ctime_ns’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:82:10: note: in expansion of macro ‘STAT_TIMESPEC’
   82 |   return STAT_TIMESPEC (st, st_ctim).tv_nsec;
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_mtime_ns’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:95:10: note: in expansion of macro ‘STAT_TIMESPEC’
   95 |   return STAT_TIMESPEC (st, st_mtim).tv_nsec;
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_atime’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:121:10: note: in expansion of macro ‘STAT_TIMESPEC’
  121 |   return STAT_TIMESPEC (st, st_atim);
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_ctime’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:135:10: note: in expansion of macro ‘STAT_TIMESPEC’
  135 |   return STAT_TIMESPEC (st, st_ctim);
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_mtime’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:149:10: note: in expansion of macro ‘STAT_TIMESPEC’
  149 |   return STAT_TIMESPEC (st, st_mtim);
      |          ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h  In function ‘get_stat_birthtime’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:52:43: error: invalid use of undefined type ‘const struct _stati64’
   52 | #  define STAT_TIMESPEC(st, st_xtim) ((st)->st_xtim)
      |                                           ^~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:167:7: note: in expansion of macro ‘STAT_TIMESPEC’
  167 |   t = STAT_TIMESPEC (st, st_birthtim);
      |       ^~~~~~~~~~~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat.c: At top level:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat.c:112:1: error: conflicting types for ‘rpl_stat’; have ‘int(const char *, struct _stati64 *)’
  112 | rpl_stat (char const *name, struct stat *buf)
      | ^~~~~~~~
In file included from /c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat.c:51:
./sys/stat.h:1363:18: note: previous declaration of ‘rpl_stat’ with type ‘int(const char * restrict,  struct _stati64 * restrict)’
 1363 | _GL_EXTERN_C int stat (const char *restrict name, struct stat *restrict buf)
      |                  ^~~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat.c: In function ‘rpl_stat’:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat.c:420:33: warning: passing argument 2 of ‘orig_stat’ from incompatible pointer type [-Wincompatible-pointer-types]
  420 |   int result = orig_stat (name, buf);
      |                                 ^~~
      |                                 |
      |                                 struct _stati64 *
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat.c:37:47: note: expected ‘struct stat *’ but argument is of type ‘struct _stati64 *’
   37 | orig_stat (const char *filename, struct stat *buf)
      |                                  ~~~~~~~~~~~~~^~~
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat.c:436:45: warning: passing argument 2 of ‘stat_time_normalize’ from incompatible pointer type [-Wincompatible-pointer-types]
  436 |       result = stat_time_normalize (result, buf);
      |                                             ^~~
      |                                             |
      |                                             struct _stati64 *
In file included from /c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat.c:54:
/c/users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/src/srclib/stat-time.h:211:58: note: expected ‘struct _stati64 *’ but argument is of type ‘struct _stati64 *’
  211 | stat_time_normalize (int result, _GL_UNUSED struct stat *st)
make[2]: *** [Makefile:1774: libicrt_a-stat.o] Error 1
make[2]: Leaving directory '/c/Users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/build-release/srclib'
make[1]: *** [Makefile:1500: all] Error 2
make[1]: Leaving directory '/c/Users/7000035176/.conan/data/libiconv/1.17/_/_/build/2af389744c9359a88f48705607388dba92ee989e/build-release/srclib'
make: *** [Makefile:34: all] Error 2
libiconv/1.17:
libiconv/1.17: ERROR: Package '2af389744c9359a88f48705607388dba92ee989e' build failed
libiconv/1.17: WARN: Build folder C:\Users\7000035176\.conan\data\libiconv\1.17\_\_\build\2af389744c9359a88f48705607388dba92ee989e\build-release
ERROR: libiconv/1.17: Error in build() method, line 126
        autotools.make()
        ConanException: Error 2 while executing make -j16

</details>

**Comment by SpaceIm** [comment]
How did you install MinGW? You should also explicitly provide paths to your gcc and g++ compilers to tools.build:compiler_executables conf in your profile, to avoid any ambiguity.

**Comment by Odinaka-git** [comment]
I used msys2 to install MinGw. And yes my compiler version 13.1.0 (rev6, built by MSYS2 project). I put GCC 11 in my profile because that was the only way to find a matching package. And please how exactly would i provide paths to my gcc and g++ compilers to tools.build:compiler_executables conf.

**Comment by Odinaka-git** [comment]
I changed my gcc compiler to 13.1, but i still got the same error

**Comment by SpaceIm** [comment]
> I put GCC 11 in my profile because that was the only way to find a matching package.

I don't understand why you mean, there is no pre-built packages for gcc on Windows, gcc 11 or gcc 13, so it will build from source in both cases.

> And please how exactly would i provide paths to my gcc and g++ compilers to tools.build:compiler_executables conf.

```ini
[conf]
tools.build:compiler_executables={"c": "/path/to/gcc", "cpp": "/path/to/g++"}
```

If you run conan from msys2 (and not from powershell or cmd), you have to give to conan this information in `tools.microsoft.bash:active` and `tools.microsoft.bash:path`.

**Comment by Odinaka-git** [comment]
Okay, I'm running it on cmd, not msys2

**Comment by SpaceIm** [comment]
Not related to your issue I think, but I realize that logic in conancenter recipes when consumers rely on `tools.microsoft.bash:active=True` but don't set `tools.microsoft.bash:path` (which is perfectly valid) is broken.

**Comment by Odinaka-git** [comment]
tools.build:compiler_executables={"cpp": "C:\msys64\mingw64\bin\g++", "c": "C:\msys64\mingw64\bin\gcc"}
sorry just wanted to ask if I got the format right?

**Comment by Odinaka-git** [comment]
sorry if I'm asking very obvious questions, but I'm kind of new to this whole Conan thing.
