### ISSUE TITLE
[service] Add a hook or linter to check whether url value in conandata.yml of any newly added version is the same than any url of previous versions

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#20171]
### What is your problem/feature request?

There are sometimes mistakes in bump versions, when a contributor adds a new version, conanbot flags PR as bump version, and it's merged without any check except successful build and even if url is incorrect nobody can block this PR before it get merged (because it's so fast that we don't have the time to notice that this PR was submitted, or because it's catched by a community reviewer, not a conan team member).

The most common mistake from contributors is to copy/paste previous version block of conandata.yml, change version field but not url field.

Checking whether url is valid for a given version is not easy, but checking that url is not the same than any previous url listed in conandata.yml should be sufficient (though sometimes recipes always download the same extra file like a LICENSE and this url doesn't change, maybe hook could only check the first url when there is a list of url for a given version).

Example: https://github.com/conan-io/conan-center-index/pull/17546 catched in https://github.com/conan-io/conan-center-index/issues/20170 (not very good example because reviewers have approved this PR).

If anybody can lie to users by providing incorrect url, you can't trust conancenter recipes.

**Comment by RubenRBS** [comment]
You make a very good point, thanks a lot for noticing

Note that the bot DOES ensure that the link in the bump version belongs to the same family of URLs as the previous ones, so at _wrost_, downloading one version actually downloads an older one like you mention, but not unrelated code. We'll be implementing this check asap :)

**Comment by RubenRBS** [comment]
Just checked with a script, and seems like osmanip also has this problem with its 4.4.0 version

**Comment by ericLemanissier** [comment]
I made a bot which scans conandata.yml files : https://ericlemanissier.github.io/conan-center-lint-conandata/

You can find urls which do not contain the version string by searching for "does not contain version"
Also, you can find urls and hashes which are present several times in a conandata.yml file by searching for "is present twice for version"

**Comment by AbrilRBS** [comment]
Closing as solved, the new linter has some heuristics to check for cases like these
