### ISSUE TITLE
[package] abseil/20200225.2 : Couldn't find abslConfig.cmake

### ISSUE THREAD

**Issue by SemyonDuB** [conan-io/conan-center-index#2019]
I would like to create gRPC package, but the abseil recipe removes the cmake directory in the lib. Moreover, package directory doesn't have anything like abslConfig.cmake. But I've noticed that abslConfig.cmake is in the build directory, so I'm thinking of removing this line at all:  ```tools.rmdir(os.path.join(self.package_folder, "lib", "cmake"))```
Maybe I'm missing something?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **abseil/2020225.2**
  * Operating System+version: **Fedora 32**
  * Compiler+version: **GCC 10**
  * Conan version: **conan 1.26.0**
  * Python version: **Python 3.8.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
CMake Error at cmake/abseil-cpp.cmake:38 (find_package):
  Could not find a package configuration file provided by "absl" with any of
  the following names:

    abslConfig.cmake
    absl-config.cmake

  Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
  "absl_DIR" to a directory containing one of the above files.  If "absl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:219 (include)


-- Configuring incomplete, errors occurred!

```

</details>

**Comment by Croydon** [comment]
Please consider contributing to my existing grpc recipe which I will push to CCI when it is ready https://github.com/inexorgame/conan-grpc

Please see https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#kb-h016-cmake-modules-config-files as an explanation for why we don't package CMake files. This is on purpose and you need to use Conan generators.

**Comment by SemyonDuB** [comment]
Ok, thanks! I didn't know that someone was already developing a package for gRPC.
