### ISSUE TITLE
[package] opencv/4.5.5: Version conflict libwebp

### ISSUE THREAD

**Issue by j-brent** [conan-io/conan-center-index#20285]
### Description

Apparently `opencv/4.5.5` has an internal dependency conflict. 

To reproduce just create a _conanfile.txt_ with a single `requires`:
```ini
[requires]
opencv/4.5.5
```
and call `conan install .`. It results in the following error:
```sh
ERROR: Version conflict: libtiff/4.5.1->libwebp/1.3.2, opencv/4.5.5->libwebp/1.3.1.
```

Here is the dependency graph:

![conflict](https://github.com/conan-io/conan-center-index/assets/23211446/251137b9-b4d7-45c7-b575-2200ab496266)

created with the command.
```sh
$ conan graph info . --format=html > conanfile.html
```

I tried to override the dependency "in the root project" by adding `libwebp/1.3.2` to the _conanfile.txt_, but this does not seem to work in Conan 2.0.

I would really not like to have to create a python conan recipe just to have to override a dependency conflict which resides entirely in another package. Which according to all the documentation is just a workaround anyway.

So my first question is: Is there any way to override dependency conflicts in a _conafile.txt_ in Conan 2.0?

And my second question is: How can this even happen? Doesn't `conan install` get called on the `opencv/4.5.5` recipe before it gets merged into the `conan-center-index`? Wouldn't any dependency conflict show up there, regardless of what machine it is running on?

Thanks in advance.

### Package and Environment Details

* Package Name/Version: **opencv/4.5.5**
* Operating System+version: **Windows 10 Home, Version 22H2**
* Compiler+version: **msvc 193**
* Conan version: **conan 2.0.13**
* Python version: **Python 3.10.2**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

### Steps to reproduce

_conanfile.txt_
```ini
[requires]
opencv/4.5.5
```
command
```sh
conan install .
```

### Logs

<details><summary>Click to expand log</summary>

```sh
$ conan install .

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    conanfile.txt: F:\dev\cpp\bild\conanfile.txt
Requirements
    ade/0.1.2a#b569ff943843abd004e65536e265a445 - Cache
    eigen/3.4.0#2e192482a8acff96fe34766adca2b24c - Cache
    imath/3.1.9#ff1999f4d4a6885b68a84d0b039a5847 - Cache
    jasper/4.0.0#c2a1cfb970fd5f28ad99880d0735776a - Cache
    jbig/20160605#2d29fa02aacd76902e0d2cbbc24631ef - Cache
    libdeflate/1.18#3697b637656a9af04cabcbed50db9a7e - Cache
    libjpeg/9e#68269859e4325ddc3f995d1fd3fc9187 - Cache
    libpng/1.6.40#0337b7b87ac125307ed70fd064c31eea - Cache
    libtiff/4.5.1#7664d7c224504734ff5e25a54befeb27 - Cache
    opencv/4.5.5#7d07b377070251361a21f3e380985aeb - Cache
    openexr/3.1.9#9ab003042b2ae07ee7d147d17ca9f3d7 - Cache
    protobuf/3.21.12#8210c0b1bb46b08ff2814614ec091a9c - Cache
    xz_utils/5.4.4#f7cff24c0eadb6e51001dd86695e823d - Cache
    zlib/1.2.13#e377bee636333ae348d51ca90874e353 - Cache
    zstd/1.5.5#93372fe14bb7883bd4de82914e0a1841 - Cache
Resolved version ranges
    zlib/[>=1.2.11 <2]: zlib/1.2.13
ERROR: Version conflict: libtiff/4.5.1->libwebp/1.3.2, opencv/4.5.5->libwebp/1.3.1.
```

</details>

**Comment by wildernesscoder** [comment]
Am also seeing this behavior.

**Comment by RubenRBS** [comment]
Hi! Thanks for your report. We noticed yesterday and the PR to fix the conflict is already up (See https://github.com/conan-io/conan-center-index/pull/20254), thanks a lot to both of you for taking the time to report the issue :)

**Comment by shreyashgupta** [comment]
Experiencing the same issue. 
# Package and Environment Details
Package Name/Version: opencv/4.5.5
OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.19045 N/A Build 19045
Compiler+version: msvc 193
Conan version: conan 2.0.11
Python version: Python 3.9.9

# Conan profile
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows


Another observation, conan center indicates there should be no conflict
   
![image](https://github.com/conan-io/conan-center-index/assets/47035994/afdb480c-faf0-437d-af15-99a5638044b5)
