### ISSUE TITLE
[request] libvpx/1.13.1

### ISSUE THREAD

**Issue by pwuertz** [conan-io/conan-center-index#20280]
### Package Name/Version

libvpx/1.13.1

### Changelog

https://chromium.googlesource.com/webm/libvpx/+/refs/tags/v1.13.1

### Context about the new update

The latest `libvpx` version `1.11.0` in conan-center is quite old and needs to be updated, most importantly because the recently released version `1.13.1` fixes a critical security vulnerability (https://www.openwall.com/lists/oss-security/2023/09/28/5).

**Comment by czoido** [comment]
Thanks for reporting, closing this as already available.
