### ISSUE TITLE
[request] aravis/0.8.25

### ISSUE THREAD

**Issue by fixstars-sonali** [conan-io/conan-center-index#20338]
### Package Name/Version

aravis/0.8.25

### Changelog

https://github.com/AravisProject/aravis/releases/tag/0.8.25

### Context about the new update

I have a dependency on the above-mentioned version released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by czoido** [comment]
Closing as newer versions are available. Thanks for reporting!
