### ISSUE TITLE
[package] openimageio/2.4.7.1: upstream sha256 has changed

### ISSUE THREAD

**Issue by svenpilz** [conan-io/conan-center-index#20365]
### Description

Building `openimageio/2.4.7.1` fails with 

```
files.get(
	ConanException: sha256 signature failed for 'v2.4.7.1.tar.gz' file. 
 Provided signature: fd298f71e44c6776863db4b37c4a1388dba0d2eb37378afea95ab07a7cd6ecd4  
 Computed signature: a3dc6fdb3693eb5f1e22191e41c05800a4944f3c76daffe90bd203f956180126
```

Manually downloading and checking the signature confirms the change.

### Package and Environment Details

* Operating System+version: **Linux Ubuntu 20.04**, **Arch**, **Windows**
* Conan version: **conan 1.59.0**

### Conan profile

Fails for different profiles and operating systems.

### Steps to reproduce

conan create openimageio/all "2.4.7.1@"

### Logs

<details><summary>Click to expand log</summary>

```
files.get(
	ConanException: sha256 signature failed for 'v2.4.7.1.tar.gz' file. 
 Provided signature: fd298f71e44c6776863db4b37c4a1388dba0d2eb37378afea95ab07a7cd6ecd4  
 Computed signature: a3dc6fdb3693eb5f1e22191e41c05800a4944f3c76daffe90bd203f956180126
```

</details>

**Comment by svenpilz** [comment]
Maybe because they moved to https://github.com/AcademySoftwareFoundation/OpenImageIO?

**Comment by RubenRBS** [comment]
Hi! Thanks a lot for your report and for checking with the authors for a clarification, once we know more, we'll happily modify it if they confirm it's not unexpected :)

**Comment by svenpilz** [comment]
They think this maybe related to renaming/moving the repository, but cannot test this as the old archives are no longer available on GitHub.

The base folder in the archive might be named after the repository and thus it generated a different archive now. Which they did not anticipate as a side effect.

See https://github.com/AcademySoftwareFoundation/OpenImageIO/issues/4003#issuecomment-1750002206.

**Comment by svenpilz** [comment]
As a side note, I suppose the issue might happen with other repositories in https://github.com/AcademySoftwareFoundation as well (if they moved recently).

**Comment by svenpilz** [comment]
@RubenRBS, would you call this a reasonable explanation, or does that scream supply-chain issue and changing the expected signatures would a no-go at the moment?

**Comment by RubenRBS** [comment]
Okey, let's go ahead and change the sha checksums in the conandata.yml files, thanks a lot for your patience :)

I'm proposing this PR https://github.com/conan-io/conan-center-index/pull/18904 to implement the needed changes (Pinging @valgur)

**Comment by svenpilz** [comment]
Thanks. Can I help, or is the PR ready to merge? I cannot read the log output from the failing job there.

**Comment by RobertRapidshape** [comment]
Hi there,
is there already a solution? We still observe a wrong package id for the latest supported OpenImageIO package (2.4.7.1) as initially issued...

**Comment by uilianries** [comment]
@svenpilz @RobertRapidshape You could open a PR only fixing the checksum. The original recipe is still not ported to Conan 2.x, but do not worry, if it's a blocker, we still can merge manually, but only because is breaking you and others users.

**Comment by svenpilz** [comment]
Thanks, will open one.

**Comment by svenpilz** [comment]
@uilianries, please see https://github.com/conan-io/conan-center-index/pull/20910.

**Comment by irieger** [comment]
Think this can be closed as we merged #19950 last week which updates the URLs.

@uilianries @RubenRBS

**Comment by svenpilz** [comment]
Cannot test this at the moment. But if it builds in the CI, this would be fine from my side.

**Comment by irieger** [comment]
2.4.7.1, 2.4.17.0, 2.5.6.0, 2.5.9.0 are currently supported and build in the CI. The older ones I removed when migrating to conan 2.

**Comment by svenpilz** [comment]
This would fix the issue for me.

Thank you :).
