### ISSUE TITLE
[package] dcmtk/3.6.7: conanfile.py bool options not working

### ISSUE THREAD

**Issue by xeospetrov** [conan-io/conan-center-index#20376]
### Description

After commit [5d8800386dc399dfd2f01cd599d4a88ff0dc9801](https://github.com/conan-io/conan-center-index/commit/5d8800386dc399dfd2f01cd599d4a88ff0dc9801), our builds using dcmtk started failing due to the dcmtk package from conan-center not using the STL anymore by default (enabled via `enable_stl`/`DCMTK_ENABLE_STL`).

It seems that the commit broke the bool options by directly assigning the option (type `PackageOption`) to the cmake variable. This was confirmed by building dcmtk and looking at the build output stating whether the use of STL is enabled or disabled (ex: `Info: STL string support disabled`).

Explicitly converting the option to a boolean inside conanfile.py fixes the problem:
`tc.variables["DCMTK_ENABLE_STL"] = bool(self.options.enable_stl)`)

This issue blocks our team. As far as I am aware we cannot temporarily workaround it by specifying in conan install to use the previous version. Only possible workaround we could think of is downgrading to 3.6.5 or 3.6.6, which still uses the old code.

Relevant code in recipes/dcmtk/all/conanfile.py:
Before
```python
cmake = CMake(self)
if self.options.enable_stl:
    cmake.definitions["DCMTK_ENABLE_STL"] = "ON"
else:
    cmake.definitions["DCMTK_ENABLE_STL"] = "OFF"
```
After
```python
tc = CMakeToolchain(self)
tc.variables["DCMTK_ENABLE_STL"] = self.options.enable_stl
```

### Package and Environment Details

* Package Name/Version: **dcmtk/3.6.7**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 7**
* Conan version: **conan 1.58.0**
* Python version: **Python 3.7.16**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

```
conan install dcmtk/3.6.7@ -s build_type=Debug -s compiler=gcc -s compiler.version=7 -s compiler.libcxx=libstdc++11 -g=cmake --build=dcmtk
```

### Logs

<details><summary>Conan output</summary>
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

WARN: libxml2/2.11.4: requirement zlib/[>=1.2.11 <2] overridden by dcmtk/3.6.7 to zlib/1.3
WARN: openssl/3.1.3: requirement zlib/[>=1.2.11 <2] overridden by dcmtk/3.6.7 to zlib/1.3
WARN: libpng/1.6.40: requirement zlib/[>=1.2.11 <2] overridden by dcmtk/3.6.7 to zlib/1.3
WARN: libtiff/4.6.0: requirement zlib/[>=1.2.11 <2] overridden by dcmtk/3.6.7 to zlib/1.3
dcmtk/3.6.7: Forced build from source
Version ranges solved
    Version range '>=1.2.11 <2' required by 'dcmtk/3.6.7' resolved to 'zlib/1.3' in local cache
    Version range '>=1 <4' required by 'dcmtk/3.6.7' resolved to 'openssl/3.1.3' in local cache
    Version range '>=1.2.11 <2' required by 'libxml2/2.11.4' valid for downstream requirement 'zlib/1.3'
    Version range '>=1.2.11 <2' required by 'openssl/3.1.3' valid for downstream requirement 'zlib/1.3'
    Version range '>=1.2.11 <2' required by 'libpng/1.6.40' valid for downstream requirement 'zlib/1.3'
    Version range '>=1.2.11 <2' required by 'libtiff/4.6.0' valid for downstream requirement 'zlib/1.3'

Installing package: dcmtk/3.6.7
Requirements
    dcmtk/3.6.7 from 'conan-center' - Cache
    jbig/20160605 from 'conan-center' - Cache
    libdeflate/1.18 from 'conan-center' - Cache
    libiconv/1.17 from 'conan-center' - Cache
    libjpeg/9e from 'conan-center' - Cache
    libpng/1.6.40 from 'conan-center' - Cache
    libtiff/4.6.0 from 'conan-center' - Cache
    libwebp/1.3.2 from 'conan-center' - Cache
    libxml2/2.11.4 from 'conan-center' - Cache
    openssl/3.1.3 from 'conan-center' - Cache
    xz_utils/5.4.4 from 'conan-center' - Cache
    zlib/1.3 from 'conan-center' - Cache
    zstd/1.5.5 from 'conan-center' - Cache
Packages
    dcmtk/3.6.7:551e81bb383048c5b113d89b5d9dc830e9a8594c - Build
    jbig/20160605:750638cf23cead9db659f780b325aa2bdf8da149 - Cache
    libdeflate/1.18:db2ca884c9793e0b0fb54ec3f846326d1addacc8 - Cache
    libiconv/1.17:db2ca884c9793e0b0fb54ec3f846326d1addacc8 - Cache
    libjpeg/9e:db2ca884c9793e0b0fb54ec3f846326d1addacc8 - Cache
    libpng/1.6.40:c36a08bdeab72584e73fab8b5dbd4c8b47e2e05c - Cache
    libtiff/4.6.0:cef954e3ac3551d9503a594f6b443d04c171986c - Cache
    libwebp/1.3.2:ce62aa3898a1a975c72a782a8dbac43f4838298f - Cache
    libxml2/2.11.4:bbed4996f92168718aacae9d460f773a07e904ef - Cache
    openssl/3.1.3:4bc83487f3b55dba3dfcd27c3c7dba75869dcb0d - Cache
    xz_utils/5.4.4:db2ca884c9793e0b0fb54ec3f846326d1addacc8 - Cache
    zlib/1.3:db2ca884c9793e0b0fb54ec3f846326d1addacc8 - Cache
    zstd/1.5.5:dac470d835ff8559b0e466edd0e7a9bf152e1195 - Cache

Installing (downloading, building) binaries...
jbig/20160605: Already installed!
libdeflate/1.18: Already installed!
libiconv/1.17: Already installed!
libjpeg/9e: Already installed!
libwebp/1.3.2: Already installed!
xz_utils/5.4.4: Already installed!
zlib/1.3: Already installed!
zstd/1.5.5: Already installed!
libpng/1.6.40: Already installed!
libtiff/4.6.0: Already installed!
libxml2/2.11.4: Already installed!
libxml2/2.11.4: Appending PATH environment variable: /home/dev/.conan/data/libxml2/2.11.4/_/_/package/bbed4996f92168718aacae9d460f773a07e904ef/bin
openssl/3.1.3: Already installed!
dcmtk/3.6.7: WARN: Build folder is dirty, removing it: /home/dev/.conan/data/dcmtk/3.6.7/_/_/build/551e81bb383048c5b113d89b5d9dc830e9a8594c
dcmtk/3.6.7: Copying sources to build folder
dcmtk/3.6.7: Building your package in /home/dev/.conan/data/dcmtk/3.6.7/_/_/build/551e81bb383048c5b113d89b5d9dc830e9a8594c
dcmtk/3.6.7: Generator txt created conanbuildinfo.txt
dcmtk/3.6.7: Calling generate()
dcmtk/3.6.7: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
dcmtk/3.6.7: Preset 'debug' added to CMakePresets.json. Invoke it manually using 'cmake --preset debug'
dcmtk/3.6.7: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/dev/.conan/data/dcmtk/3.6.7/_/_/build/551e81bb383048c5b113d89b5d9dc830e9a8594c/build/Debug/generators/conan_toolchain.cmake -DDCMTK_USE_FIND_PACKAGE=ON -DDCMTK_DEFAULT_DICT=external -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Debug'
dcmtk/3.6.7: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
dcmtk/3.6.7: Aggregating env generators
dcmtk/3.6.7: Calling build()
dcmtk/3.6.7: Apply patch (conan): CMake: robust discovery with find_package() and use imported targets
dcmtk/3.6.7: Apply patch (conan): CMake: fix OpenSSL compatibility checks
dcmtk/3.6.7: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/dev/.conan/data/dcmtk/3.6.7/_/_/build/551e81bb383048c5b113d89b5d9dc830e9a8594c/build/Debug/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/dev/.conan/data/dcmtk/3.6.7/_/_/package/551e81bb383048c5b113d89b5d9dc830e9a8594c" -DDCMTK_USE_FIND_PACKAGE="ON" -DDCMTK_DEFAULT_DICT="external" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "/home/dev/.conan/data/dcmtk/3.6.7/_/_/build/551e81bb383048c5b113d89b5d9dc830e9a8594c/src"

...

</details> 

<details><summary>Relevant DCMTK build output</summary>

-- Info: STL vector support disabled
-- Info: STL algorithm support disabled
-- Info: STL limits support disabled
-- Info: STL list support disabled
-- Info: STL map support disabled
-- Info: STL memory support disabled
-- Info: STL stack support disabled
-- Info: STL string support disabled
-- Info: STL type_traits support disabled
-- Info: STL tuple support disabled
-- Info: STL system_error support disabled

</details>

**Comment by RubenRBS** [comment]
Hi @xeospetrov thanks a lot for your report: Indeed the change has broken the logic. It was not caught in review because due to historical reasons logic does work in 1 case, namely `cache_variables`, but we didn't realize it was not used in the proper place.

The solution would be to homegeneously cast the values in every recipe in every case to avoid confusion, but we don't want to rebuild the whole CCI just for that, so we need to be more careful about what logic is passed to the integrations. Pinging the PR's author @SpaceIm as an FYI :)


Also! Seeing that this change blocked you, I would suggest please reading https://docs.conan.io/2/devops/using_conancenter.html which deals with our recommendations on using CCI in production, and touches upon strategies to avoid exactly this issue :)

We'll close this issue when the bug is fixed, thanks again for reporting it!

**Comment by SpaceIm** [comment]
Yep. Honestly conan should cast options, it's so misleading.

For the specific case of `DCMTK_ENABLE_STL`, it works with `bool(self.options.enable_stl)` only by chance, because conan casts to ON or OFF, but it could be casted to TRUE/FALSE which are valid CMake option values. Actually I've checked and DCMTK_ENABLE_STL must be ON and no other value (TRUE doesn't work, they do a crazy STREQUAL comparison), to properly enable stl support.

**Comment by SpaceIm** [comment]
Anyway I'll push a fix.

**Comment by xeospetrov** [comment]
> For the specific case of DCMTK_ENABLE_STL, it works with bool(self.options.enable_stl) only by chance, because conan casts variables to ON or OFF if they are bool, but it could be casted to TRUE/FALSE which are valid CMake option values. Actually I've checked and DCMTK_ENABLE_STL must be ON and no other value (TRUE doesn't work, they do a crazy STREQUAL comparison), to properly enable stl support.

Aha, I was suspecting that the DCMTK CMake might have been doing something weird!

**Comment by xeospetrov** [comment]
Thank you for the fix and the amazingly fast response! 👍
