### ISSUE TITLE
[package] assimp/5.2.2: error: 'M_PI' was not declared in this scope

### ISSUE THREAD

**Issue by algarcia-ujaen** [conan-io/conan-center-index#20471]
### Description

IDE: CLion 2023.2.2 with Conan plugin 2.0.2 (using the conan installed in the system)
CMake 3.27.4 installed in the system as standalone (added to system path)
Conan 2.0.10 installed in the system as standalone (added to system path)

When assimp is added to an empty project, the download is correct, but when the source code is compiled, an "error: 'M_PI' was not declared in this scope" message appears, and the compilation is aborted.

### Package and Environment Details

* Package Name/Version: **assimp/5.2.2**
* Operating System+version: **Windows 10**
* Compiler+version: **GCC 13.1.0**
* Conan version: **conan 2.0.10**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Windows

### Steps to reproduce

- Create an empty project
- Configure the conan plugin (use Conan installed in the system)
- Add assimp to the project through the conan plugin
- Add the corresponding find_package and target_link_libraries instructions to CMakeLists.txt
- Reload the CMake project

### Logs

....

poly2tri/cci.20130502: Running CMake.build()
poly2tri/cci.20130502: RUN: cmake --build "C:\Users\admin\.conan2\p\b\poly2ca8dc7da62214\b\build\Debug" -- -j8
[1/6] Building CXX object CMakeFiles/poly2tri.dir/src/poly2tri/sweep/advancing_front.cc.obj
[2/6] Building CXX object CMakeFiles/poly2tri.dir/src/poly2tri/sweep/cdt.cc.obj
[3/6] Building CXX object CMakeFiles/poly2tri.dir/src/poly2tri/sweep/sweep.cc.obj
FAILED: CMakeFiles/poly2tri.dir/src/poly2tri/sweep/sweep.cc.obj 
C:\Users\admin\AppData\Local\Programs\CLion\bin\mingw\bin\g++.exe   -m64 -g -std=c++17 -fdiagnostics-color=always -MD -MT CMakeFiles/poly2tri.dir/src/poly2tri/sweep/sweep.cc.obj -MF CMakeFiles\poly2tri.dir\src\poly2tri\sweep\sweep.cc.obj.d -o CMakeFiles/poly2tri.dir/src/poly2tri/sweep/sweep.cc.obj -c C:/Users/admin/.conan2/p/b/poly2ca8dc7da62214/b/src/poly2tri/sweep/sweep.cc
In file included from C:/Users/admin/.conan2/p/b/poly2ca8dc7da62214/b/src/poly2tri/sweep/sweep.cc:35:
C:/Users/admin/.conan2/p/b/poly2ca8dc7da62214/b/src/poly2tri/common/utils.h:43:29: error: 'M_PI' was not declared in this scope
   43 | const double PI_3div4 = 3 * M_PI / 4;
      |                             ^~~~
[4/6] Building CXX object CMakeFiles/poly2tri.dir/src/poly2tri/common/shapes.cc.obj
[5/6] Building CXX object CMakeFiles/poly2tri.dir/src/poly2tri/sweep/sweep_context.cc.obj
ninja: build stopped: subcommand failed.

poly2tri/cci.20130502: ERROR: 
Package '26c25a003bb3b7e4442c6036ea3f34cf49de4264' build failed
poly2tri/cci.20130502: WARN: Build folder C:\Users\admin\.conan2\p\b\poly2ca8dc7da62214\b\build\Debug
*********************************************************
Recipe 'poly2tri/cci.20130502' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: poly2tri/cci.20130502: Error in build() method, line 52
	cmake.build()
	ConanException: Error 1 while executing
CMake Error at conan_provider.cmake:386 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  conan_provider.cmake:477 (conan_install)
  CMakeLists.txt:8 (find_package)

CMake Warning at CMakeLists.txt:8 (find_package):
  By not providing "Findassimp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "assimp", but
  CMake did not find one.

  Could not find a package configuration file provided by "assimp" with any
  of the following names:

    assimpConfig.cmake
    assimp-config.cmake

  Add the installation prefix of "assimp" to CMAKE_PREFIX_PATH or set
  "assimp_DIR" to a directory containing one of the above files.  If "assimp"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

[Failed to reload]

**Comment by SpaceIm** [comment]
So you have build failure of poly2tri recipe, not assimp directly.

**Comment by algarcia-ujaen** [comment]
poly2tri is part of the assimp package. Isn't it?

I have only included assimp in the project. I do not know if poly2tri is an additional separate package, that is downloaded as an additional dependency.

**Comment by SpaceIm** [comment]
website is quite experimental AFAIK.

assimp has dependencies: https://github.com/conan-io/conan-center-index/blob/d27d76e493caa35fd5e8bfba3af785fd76a2e69b/recipes/assimp/5.x/conanfile.py#L166-L190

poly2tri is one of them.
