### ISSUE TITLE
[package] eastl/3.21.12: find_package(EASTL) fails.

### ISSUE THREAD

**Issue by KilluaAoki** [conan-io/conan-center-index#20494]
### Description

I use CLion Conan Plugin compatible with 2.X

When I installed the EASTL library using Conan and tried to use it in a new project, I followed the instructions and added `find_package(EASTL)` and `target_link_libraries(exe_name EASTL::EASTL)` as directed. However, CMake complained:
```
  Could not find a package configuration file provided by "EASTL" with any of
  the following names:

    EASTLConfig.cmake
    eastl-config.cmake

  Add the installation prefix of "EASTL" to CMAKE_PREFIX_PATH or set
  "EASTL_DIR" to a directory containing one of the above files.  If "EASTL"
  provides a separate development package or SDK, be sure it has been
  installed.
```

### Package and Environment Details

* Package Name/Version: **eastl/3.21.12**
* Operating System+version: **Windows11**
* Conan version: **conan 2.X**
* Cmake version: **Cmake 3.26**

### Conan profile

requirements:
  - "eastl/3.21.12"

### Steps to reproduce

"D:\Program Files\JetBrains\CLion\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_MAKE_PROGRAM=D:/Program Files/JetBrains/CLion/bin/ninja/win/x64/ninja.exe" "-DCMAKE_C_COMPILER=C:/Program Files/mingw64/bin/clang.exe" "-DCMAKE_CXX_COMPILER=C:/Program Files/mingw64/bin/clang++.exe" -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake -G Ninja -S D:\WorkSpace\IDE\JetBrains\CLion\C++\Play -B D:\WorkSpace\IDE\JetBrains\CLion\C++\Play\cmake-build-debug

### Logs

<details><summary>Click to expand log</summary>

```
"D:\Program Files\JetBrains\CLion\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_MAKE_PROGRAM=D:/Program Files/JetBrains/CLion/bin/ninja/win/x64/ninja.exe" "-DCMAKE_C_COMPILER=C:/Program Files/mingw64/bin/clang.exe" "-DCMAKE_CXX_COMPILER=C:/Program Files/mingw64/bin/clang++.exe" -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake -G Ninja -S D:\WorkSpace\IDE\JetBrains\CLion\C++\Play -B D:\WorkSpace\IDE\JetBrains\CLion\C++\Play\cmake-build-debug
CMake Error at conan_provider.cmake:462 (find_program):
  Could not find CONAN_COMMAND using the following names: conan
Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)


CMake Error at CMakeLists.txt:5 (find_package):
  Could not find a package configuration file provided by "EASTL" with any of
  the following names:

    EASTLConfig.cmake
    eastl-config.cmake

  Add the installation prefix of "EASTL" to CMAKE_PREFIX_PATH or set
  "EASTL_DIR" to a directory containing one of the above files.  If "EASTL"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!

```

</details>

**Comment by SpaceIm** [comment]
I guess https://github.com/conan-io/conan-clion-plugin/issues is more appropriate to report your issue. eastl recipe properly defines this config file and target, so it's likely a conan-clion-plugin integration issue. I don't know what conan_provider.cmake, seems to be specific to this plugin.

In command line you would add CMakeToolchain and CMakeDeps to generators, and pass conan_toolchain.cmake to cmake configuration. I don't know how it works in this plugin.

**Comment by KilluaAoki** [comment]
> 我想https://github.com/conan-io/conan-clion-plugin/issues更适合报告您的问题。eastl Recipe 正确定义了此配置文件和目标，因此这可能是 conan-clion-plugin 集成问题。我不知道 conan_provider.cmake 是什么，它似乎是特定于这个插件的。
> 
> 在命令行中，您可以将 CMakeToolchain 和 CMakeDeps 添加到生成器，并将 conan_toolchain.cmake 传递给 cmake 配置。我不知道这个插件是如何工作的。


When I use the command line, I did find the EASTLConfig.cmake file. This might be a problem specific to my current environment, or it could be a plugin issue. I will close this issue. Thank you very much.
