### ISSUE TITLE
[question] util-linux-libuuid requires gcc8 with debug build_type

### ISSUE THREAD

**Issue by Zvicii** [conan-io/conan-center-index#20512]
### What is your question?

my ci only support gcc7 for now, and util-linux-libuuid requires gcc8 under debug build_type.
Is this configured specifically or can the version requirement be changed to gcc 4 like release?
![image](https://github.com/conan-io/conan-center-index/assets/36950948/5fa10c73-5b06-4ecb-a027-06b0ad314f0a)

**Comment by Nekto89** [comment]
Old gcc versions can't handle it.

https://c3i.jfrog.io/c3i/misc/logs/pr/17664/1-linux-gcc/util-linux-libuuid/1.3.0//b1b85bfdc2206d81b3ed6a49e78498182bb98ef3-build.txt

https://godbolt.org/z/611Mxo3TG
