### ISSUE TITLE
[service] c3i: Wait for availability of package with default `shared` option value before running test_package of other `shared` flavor

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#20534]
### What is your problem/feature request?

Several recipes with a `shared` option in conancenter have to put tested recipe both in requirements and build requirements of test package, and it can break randomly with non-default shared flavor (usually `shared=True`) depending on availability of package with default shared value (usually `shared=False`).

Indeed, c3i builds for default shared option, and also the other flavor. But since c3i doesn't enforce shared option in build context (only in host context), test_package drags the default shared flavor in build requirements, and it may not be available yet while testing the non-default shared flavor in host context. So before running tests of a shared flavor, c3i should wait availability of package of build profile.

Another solution would be to enforce the same shared value in host & build context, but as you know (or you should know), it can become a nightmare on macOS due to SIP when there are executables linked to shared libs in build context and called at build time.

See also this comment https://github.com/conan-io/conan-center-index/pull/20089#issuecomment-1751727953

For example:
- libtool (https://github.com/conan-io/conan-center-index/pull/19501)
- protobuf (https://github.com/conan-io/conan-center-index/pull/20089)
- grpc (https://github.com/conan-io/conan-center-index/pull/19972)

**Comment by RubenRBS** [comment]
I think since https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md#06-oct-2023---1015-cest this should be a thing

**Comment by SpaceIm** [comment]
Well for grpc, It still fails in v2 pipeline with missing static package in test package of shared flavor: https://github.com/conan-io/conan-center-index/pull/19972#issuecomment-1769241511

**Comment by AbrilRBS** [comment]
We're moving away from complex test_packages with multiple requirements to simplify cases like these, so I'm closing this as a non-goal for now
