### ISSUE TITLE
[package] qt/6.6.0: missing __qt_internal_cmake_apple_support_files_path

### ISSUE THREAD

**Issue by tamaskenezlego** [conan-io/conan-center-index#20574]
### Description

In the original Qt installation `lib/CMake/Qt6/Qt6Config.cmake` sets the `__qt_internal_cmake_apple_support_files_path` CMake variable. It's used in `QtPublicAppleHelpers.cmake/_qt_internal_copy_info_plist()` to locate the `lib/CMake/Qt6/macos/Info.plist.app.in` file.

In conan-built Qt `Qt6Config.cmake` is conan-generated and does not set `__qt_internal_cmake_apple_support_files_path`. 

The result is that configuring a Qt/MacOS bundle executable (`qt_add_executable(... MACOSX_BUNDLE ...)`) prints the following error:

```
CMake Error: File /Info.plist.app.in does not exist.
```

### Package and Environment Details

* Package Name/Version: **qt/6.6.0**
* Operating System+version: **MacOS**
* Conan version: **conan 1.61.0**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=15
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

Run cmake-configure on a helloworld-qt application (MacOS) where the executable is added with:

```
qt_add_executable(target_name MACOSX_BUNDLE main.cpp)
```

### Logs

The conan-log is not relevant.

**Comment by DoomHammer** [comment]
Still present in Qt 6.7.1

**Comment by DoomHammer** [comment]
@jcar87 @ericLemanissier do you know where is this generated? I could try to fix it, but looking at conanfile.py I have no idea where to start.

**Comment by uilianries** [comment]
Hello @tamaskenezlego and @DoomHammer !! The PR #24642 has been merged and a hotfix is not available in the Conan Center. Please, update your local copy:

    conan install -r conancenter --update --requires-"qt/<version>"

**Comment by DoomHammer** [comment]
Thanks!

For some reason, though, I'm still getting:

```
CMake Error: File /Users/doomhammer/.conan2/p/b/qtd17264e33cd40/p/res/macos/Info.plist.app.in does not exist.
```

`/Users/doomhammer/.conan2/p/b/qtd17264e33cd40/p/lib/cmake/Qt6/macos/Info.plist.app.in` is, however, present.
