### ISSUE TITLE
[question] When will CI build packages with gcc 10?

### ISSUE THREAD

**Issue by vvilpas** [conan-io/conan-center-index#2057]
I have checked some recipes bumped recently (for example amqp-cpp),  and it seems there are no builds for gcc 10. When will this happen?

**Comment by Croydon** [comment]
Effectively a duplicate of #1587 

But when it will happen has someone to answer from the Conan team 😄

**Comment by uilianries** [comment]
Adding a new images requires a LOT of jobs, and solve all dependencies graph first. It's scheduled, but requires more people involved. @danimtb can some idea.

**Comment by danimtb** [comment]
please continue the conversation in https://github.com/conan-io/conan-center-index/issues/1587
