### ISSUE TITLE
[conan.io/center] Invalid instructions in developing_recipes_locally.md - conan config set

### ISSUE THREAD

**Issue by eyalroz** [conan-io/conan-center-index#20601]
### What is your problem/feature request?

<sub>(Background: I'm a package author and I'm trying to follow the instructions to submit/upload my package to conan. I already tried this about a year ago, and failed at the stage of authoring an appropriate recipe. I'm now trying again from scratch.)</sub>

So, I'm following the instructions in [developing_recipes_locally.md](https://github.com/conan-io/conan-center-index/blob/master/docs/developing_recipes_locally.md#clone-your-fork) (the Clone Your Fork section). Specifically, it tells me to execute:
```
conan config install https://github.com/conan-io/hooks.git -sf hooks -tf hooks
conan config set hooks.conan-center
```
The first command runs fine; the second command - doesn't:
```
$ conan config set hooks.conan-center
usage: conan config [-h] [-v [V]] {home,install,list,show} ...
conan config: error: argument subcommand: invalid choice: 'set' (choose from 'home', 'install', 'list', 'show')
ERROR: Exiting with code: 2
```
Is this perhaps a conan1 vs conan2 issue?

----
My system details:

* Devuan Excalibur GNU/Linux
* Kernel:  6.5.0-1-amd64
* Conan client: 2.0.13
* Python: 3.11.6

**Comment by RubenRBS** [comment]
Hi @eyalroz thanks a lot for the report, we surely can make this a bit more obvious for the reader

> Is this perhaps a conan1 vs conan2 issue?

Yep, the docs mention that ["Warning: This is not yet supported with Conan 2.0"](https://github.com/conan-io/conan-center-index/blob/master/docs/developing_recipes_locally.md#installing-the-conancenter-hooks), but you're right that it's not maybe too visible, will double check, thansk!

(Pinging @uilianries who is working on adding support for v2 hooks)

**Comment by eyalroz** [comment]
@uilianries  : If there is a version of that document for conan 2, I'd be happy to try it out (and report issues if you like). I assume I can continue following those instructions from the section after the one I got a failure in?

**Comment by uilianries** [comment]
Hello @eyalroz, thank you for your interesting on hooks with Conan 2.x! 

Indeed is not officially supported CCI hooks with Conan 2.x, but there are some consideration in case you want to give a try:

- The hooks activation on Conan 2.x is different, once the file is installed in the hooks folders, it's activated already. It's documented here: https://docs.conan.io/2/reference/extensions/hooks.html#storage-activation-and-sharing
- In case you want to deactivate a hook, you could remove the file, or rename it by changing the prefix `hook_`. The `.py` also matters.
- There is an on going effort for CCI hook with Conan 2.x here: https://github.com/conan-io/hooks/pull/514
- In case you want to try locally, you need to download the file https://raw.githubusercontent.com/conan-io/hooks/2b35fe794c82567e240cb6c59f325a5b24fc8a91/hooks/hook_conan_center.py. Probably you will find false-positives, so be careful. 

Anyway, the CCI is not well documented about Hooks and Conan 2.x, so it deserves an update.
