### ISSUE TITLE
conan_paths.cmake alternative in Conan 2.xx?

### ISSUE THREAD

**Issue by VicKov1975** [conan-io/conan-center-index#20630]
Back in Conan 1.xx, I was using the generator "cmake_paths" to produce a conan_paths.cmake file in my build folder.
That file contained the variable 'CONAN_QT_ROOT' that I needed to find out where the Qt library was installed.

But I have noticed that this generator is not available in Conan 2.xx.

What would be the alternative?

**Comment by Ahajha** [comment]
All the CMake generators in Conan 1.xx have been replaced with the CMakeDeps and CMakeToolchain generators.
https://docs.conan.io/1/reference/conanfile/tools/cmake/cmakedeps.html#cmakedeps
https://docs.conan.io/1/reference/conanfile/tools/cmake/cmaketoolchain.html#conan-cmake-toolchain

I'm not familiar with QT (other than that it is complicated), do you specifically need to find where the package is, or is there something else you're trying to get from it?

**Comment by VicKov1975** [comment]
> All the CMake generators in Conan 1.xx have been replaced with the CMakeDeps and CMakeToolchain generators. https://docs.conan.io/1/reference/conanfile/tools/cmake/cmakedeps.html#cmakedeps https://docs.conan.io/1/reference/conanfile/tools/cmake/cmaketoolchain.html#conan-cmake-toolchain
> 
> I'm not familiar with QT (other than that it is complicated), do you specifically need to find where the package is, or is there something else you're trying to get from it?

Yes, I am already using these two generators.

The reason why I need to find the installation path of Qt is to launch windeployqt6.exe in my CMake install step.
This tool (windeployqt6) helps to package my executable by providing all the required DLLs.
And I need to call it using its full absolute path. Right now I have it hard-coded, e.g.:

`C:/Users/Vic/.conan2/p/b/qt4c7415c4b15bd/p/bin/windeployqt6.exe`

**Comment by Jihadist** [comment]
@VicKov1975 there is a problem with cmakedeps, it does not provide the root folder of the package. Generated files try to the same as possible to the original recipe files. It maybe a problem sometimes. If qt original recipe provide something it should be added in conan too, otherwise try to use include_dir of qt::core/../bin

**Comment by VicKov1975** [comment]
> @VicKov1975 there is a problem with cmakedeps, it does not provide the root folder of the package. Generated files try to the same as possible to the original recipe files. It maybe a problem sometimes. If qt original recipe provide something it should be added in conan too, otherwise try to use include_dir of qt::core/../bin

@Jihadist 
Can you give an example on where and how to use that include_dir?

**Comment by Jihadist** [comment]
@VicKov1975 i found another solution, try
```cmake
    get_target_property(QT_QMAKE_EXE Qt${QT_VERSION_MAJOR}::qmake IMPORTED_LOCATION)
    get_filename_component(QT_BIN_DIR ${QT_QMAKE_EXE} DIRECTORY)
    find_program (WINDEPLOYQT windeployqt.exe PATHS ${QT_BIN_DIR} REQUIRED)

    message(STATUS "Qt binaries directory: " ${QT_BIN_DIR})
    message(STATUS "windeployqt: " ${WINDEPLOYQT})
```

**Comment by VicKov1975** [comment]
@Jihadist 
Thanks, it worked.
