### ISSUE TITLE
[request] simdjson/0.4.0

### ISSUE THREAD

**Issue by mgranville** [conan-io/conan-center-index#2065]
### Package Details
  * Package Name/Version: **simdjson/0.4.0**
  * Changelog: **https://github.com/simdjson/simdjson/releases/tag/v0.4.0**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by uilianries** [comment]
I requires more than a bump, I quickly checked and the cmake file not same, some new options, some deprecated.

**Comment by prince-chrismc** [comment]
Closed by #2623 #2832
