### ISSUE TITLE
[bug] libiconv.res.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'

### ISSUE THREAD

**Issue by cyberflashguru** [conan-io/conan-center-index#20689]
### Environment details

* Operating System+version: Microsoft Windows 11 Pro, 10.0.22621 N/A Build 22621
* Compiler+version:  Visual Studio 2022 C++17
* Conan version: 1.60.2
* Python version: 3.10.11

### Steps to reproduce

This bug was initially reported here: https://lists.defectivebydesign.org/archive/html/bug-gnu-libiconv/2021-01/msg00002.html
and I'm currently running into the same error.

Below are the libiconv build steps, the fatal error and a suggested patch.

**Creating the libiconv library**
1. Clone the repository:

git clone https://github.com/conan-io/conan-center-index.git

2. Navigate to the directory:

cd conan-center-index/recipes/libiconv/all

**Build of x86 libiconv/1.17**
1. Remove any existing libiconv/1.17 conan package:

conan remove libiconv/1.17

2. Export this recipe to your local Conan cache:

conan export c:\Projects\conan-center-index\recipes\libiconv\all libiconv/1.17@_/_

3. Build an x86 libiconv/1.17 version and notice the fatal error:

...
libtool: compile:  windres -DPACKAGE_VERSION_STRING=\\\"1.17\\\" -DPACKAGE_VERSION_MAJOR=1 -DPACKAGE_VERSION_MINOR=17 -DPACKAGE_VERSION_SUBMINOR=0 -i /c/users/johnsmith/.conan/data/libiconv/1.17/_/_/build/e7f407375b48ca2f89135f6704b636cb32edd0ff/src/lib/../windows/libiconv.rc --output-format=coff -o libiconv.res.obj
/bin/sh ../libtool --mode=link /c/users/johnsmith/.conan/data/libiconv/1.17/_/_/build/e7f407375b48ca2f89135f6704b636cb32edd0ff/src/build-aux/compile cl -nologo -debug  -MT -Zi -O2 -Ob1 -FS  -o libiconv.la -rpath /lib -version-info 8:1:6 -no-undefined iconv.lo localcharset.lo relocatable.lo  libiconv.res.lo
libtool: link: /c/users/johnsmith/.conan/data/libiconv/1.17/_/_/build/e7f407375b48ca2f89135f6704b636cb32edd0ff/src/build-aux/ar-lib lib cr .libs/iconv.lib  iconv.obj localcharset.obj relocatable.obj libiconv.res.obj
**libiconv.res.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'**
make[1]: *** [Makefile:77: libiconv.la] Error 88
make[1]: Leaving directory '/c/Users/johnsmith/.conan/data/libiconv/1.17/_/_/build/e7f407375b48ca2f89135f6704b636cb32edd0ff/build-relwithdebinfo/lib'
make: *** [Makefile:33: all] Error 2
libiconv/1.17:
libiconv/1.17: ERROR: Package 'e7f407375b48ca2f89135f6704b636cb32edd0ff' build failed
libiconv/1.17: WARN: Build folder C:\Users\johnsmith\.conan\data\libiconv\1.17\_\_\build\e7f407375b48ca2f89135f6704b636cb32edd0ff\build-relwithdebinfo
ERROR: libiconv/1.17: Error in build() method, line 126
autotools.make()
ConanException: Error 2 while executing make -j16
Executing error: Program conan: returned error code: 1
...

I tried 3 ways to resolve this error:

1. Created a patch file called C:\Projects\conan-center-index\recipes\libiconv\all\patches\windres-options.patch

--- src/windows/windres-options
+++ src/windows/windres-options
@@ -34 +33,0 @@ q
-  echo "--target=pe-i386 "

and updated conandata.yml as follows:

patches:
  "1.16":
    - patch_file: "patches/0001-libcharset-fix-linkage.patch"
  "1.17":
    - patch_file: "patches/ windres-options.patch" 

but, ran into this error

C:\Users\johnsmith\.conan\data\libiconv\1.17\_\_\build\e7f407375b48ca2f89135f6704b636cb32edd0ff\patches/windres-options.patch: source/target file does not exist:
[Config:x86] --- b'src/windows/windres-options'
[Config:x86] +++ b'src/windows/windres-options'

2. Using the patch.exe, I ran this command from the conanfile.py and got an access violation:

self.run(r'"C:\Program Files\Git\usr\bin\patch.exe" -p0 -R --binary < {}'.format(patch_file_path), cwd=parent_build_folder, output=True)

so no luck with this method.

3. The following method did work! It patches "windres-options" directly with the option `--target=pe-i386`

**Creating the libiconv resource Patch**

Navigate to the directory:

cd conan-center-index/recipes/libiconv/all

**conanfile.py Modifications:**

Added a new function called `apply_resource_patch()`

```
def apply_resource_patch(self):
    if self.settings.arch == "x86":
        windres_options_path = os.path.join(self.source_folder, "windows", "windres-options")
        self.output.info("Applying {} resource patch: {}".format(self.settings.arch, windres_options_path))
        with open(windres_options_path, 'r') as file:
            lines = file.readlines()
        lines.insert(8, 'echo "--target=pe-i386"\n')
        with open(windres_options_path, 'w') as file:
            file.writelines(lines)

def build(self): 
    apply_conandata_patches(self)
    self.apply_resource_patch()
    autotools = Autotools(self)
    autotools.configure()
    autotools.make()
```

which correctly added this option `--target=pe-i386` to the windres commandline during the build:

libtool: compile:  windres **--target=pe-i386** -DPACKAGE_VERSION_STRING=\\\"1.17\\\" -DPACKAGE_VERSION_MAJOR=1 -DPACKAGE_VERSION_MINOR=17 -DPACKAGE_VERSION_SUBMINOR=0 -i /c/users/johnsmith/.conan/data/libiconv/1.17/_/_/build/e7f407375b48ca2f89135f6704b636cb32edd0ff/src/lib/../windows/libiconv.rc --output-format=coff -o libiconv.res.obj

Everything now builds successfully and that patch resolves the x86 build error:

`libiconv.res.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'`

I'd like to be able to use the standard apply_conandata_patches() method for libiconv instead of modifying the file directly via  the custom patch function apply_resource_patch(). 

There are 3 proposed patch methods above:

1. Use the standard approach `apply_conandata_patches()`
2. Use `patch.exe` to apply the patch
3. Use python code to call `apply_conandata_patches()`

Hopefully a patch can be added to resolve the x86 only fatal error.

Thanks!

**Comment by memsharded** [comment]
When you do a PR, you can add in the comment a ``Close https://github.com/conan-io/conan-center-index/issues/20689`` to automatically close this ticket when your PR gets merged. Thanks again for the feedback and contribution!

**Comment by jcar87** [comment]
Ended up in this issue by way of https://github.com/conan-io/conan-center-index/issues/26445  - what a rollercoaster

`windres.exe` will target, by default, the first architecture it is configuration. So the `windres.exe` for the x86_64 toolchain will target.. x86_64, and the `windres.exe` for i686 will target that 

The actual issue here is that the profile or msys2 or the toolchain are misconfigured and the wrong windres.exe is picked up first in the path - so the issue here is that the x86_64 windres.exe is being seen by autotools when targetting i686 - and the reason the proposed fix works is because the x86_64 windres.exe can also output the i686 format. 

mingw32 _does_ provide its own windres.exe and it should work without modifications - so it's a matter of investigating how the profile is composed and which packages have a windres.exe in them - an alternative solution may be to set `RC` in the buildenv or the `rc` in the compiler.executables conf - to point to the right file, or to ensure the correct bin folder is first in the PATH
