### ISSUE TITLE
[package] cpython/3.10.0: Issue with libuuid

### ISSUE THREAD

**Issue by hiteshdasikamw** [conan-io/conan-center-index#20695]
### Description

I have a conan project with the following dependencies
`    requires = [
        "gtest/cci.20210126", 
        "boost/1.78.0",
        "libunwind/1.6.2",
        "batteries/0.5.17@tastolfi+batteries/stable",
        "cli11/2.2.0",
        "protobuf/3.20.0",
        "lua/5.4.4",
        "libzip/1.8.0",
        "xz_utils/5.4.2",
        "zlib/1.2.13",
        "openssl/3.1.3",
    ]`

The moment I include "cpython/3.10.0" , I end up getting the below error:

ERROR: At least two recipes provides the same functionality:
 - 'libuuid' provided by 'libuuid/1.0.3', 'util-linux-libuuid/2.39'

Below is my linux distro info

Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

### Package and Environment Details

* Package Name/Version: **cpython/3.10.0**
* Operating System+version: **Debian 11**
* Compiler+version: **GCC 10.2**
* Conan version: **conan 1.60.0**
* Python version: **Python 3.9.2**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

make install

### Logs

<details><summary>Click to expand log</summary>

```
WARN: boost/1.78.0: requirement zlib/[>=1.2.11 <2] overridden by mps_universal_runtime/0.2.1 to zlib/1.2.13 
WARN: libunwind/1.6.2: requirement xz_utils/5.4.4 overridden by mps_universal_runtime/0.2.1 to xz_utils/5.4.2 
WARN: libunwind/1.6.2: requirement zlib/[>=1.2.11 <2] overridden by mps_universal_runtime/0.2.1 to zlib/1.2.13 
WARN: protobuf/3.20.0: requirement zlib/[>=1.2.11 <2] overridden by mps_universal_runtime/0.2.1 to zlib/1.2.13 
WARN: libzip/1.8.0: requirement zlib/[>=1.2.11 <2] overridden by mps_universal_runtime/0.2.1 to zlib/1.2.13 
WARN: libzip/1.8.0: requirement openssl/[>=1.1 <4] overridden by mps_universal_runtime/0.2.1 to openssl/3.1.3 
WARN: openssl/3.1.3: requirement zlib/[>=1.2.11 <2] overridden by libzip/1.8.0 to zlib/1.2.13 
WARN: cpython/3.10.0: requirement zlib/1.2.11 overridden by mps_universal_runtime/0.2.1 to zlib/1.2.13 
WARN: cpython/3.10.0: requirement openssl/1.1.1l overridden by mps_universal_runtime/0.2.1 to openssl/3.1.3 
WARN: cpython/3.10.0: requirement xz_utils/5.2.5 overridden by mps_universal_runtime/0.2.1 to xz_utils/5.4.2 
WARN: tcl/8.6.10: requirement zlib/[>=1.2.11 <2] overridden by tk/8.6.10 to zlib/1.2.13 
WARN: fontconfig/2.13.93: requirement expat/2.5.0 overridden by tk/8.6.10 to expat/2.4.1 
WARN: freetype/2.13.0: requirement zlib/[>=1.2.10 <2] overridden by fontconfig/2.13.93 to zlib/1.2.13 
WARN: libpng/1.6.40: requirement zlib/[>=1.2.11 <2] overridden by freetype/2.13.0 to zlib/1.2.13 
ERROR: At least two recipes provides the same functionality:
 - 'libuuid' provided by 'libuuid/1.0.3', 'util-linux-libuuid/2.39'
ur log output here
```

</details>

**Comment by Ahajha** [comment]
I think https://github.com/conan-io/conan-center-index/issues/19084 and https://github.com/conan-io/conan-center-index/pull/18558 are related
