### ISSUE TITLE
[package] m4/1.4.18: Does not compile with Clang

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/conan-center-index#2073]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **m4/1.4.18**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **Clang 10**
  * Conan version: **conan 1.26.1**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```sh
$ conan profile show clang
Configuration for profile clang:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

```sh
$ conan install m4/1.4.18@_/_ -pr clang -b missing
```

### Logs (Include/Attach if Applicable)

```sh
$ conan install m4/1.4.18@_/_ -pr clang -b missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

m4/1.4.18: WARN: Package is corrupted, removing folder: /home/wouter/.conan/data/m4/1.4.18/_/_/package/91a4ede3f059ef52815958df6195330b87cd719c
Installing package: m4/1.4.18
Requirements
    m4/1.4.18 from 'conan-center' - Cache
Packages
    m4/1.4.18:91a4ede3f059ef52815958df6195330b87cd719c - Build

Installing (downloading, building) binaries...
m4/1.4.18: WARN: Build folder is dirty, removing it: /home/wouter/.conan/data/m4/1.4.18/_/_/build/91a4ede3f059ef52815958df6195330b87cd719c
m4/1.4.18: Copying sources to build folder
m4/1.4.18: Building your package in /home/wouter/.conan/data/m4/1.4.18/_/_/build/91a4ede3f059ef52815958df6195330b87cd719c
m4/1.4.18: Generator txt created conanbuildinfo.txt
m4/1.4.18: Calling build()
m4/1.4.18: Calling:
 > source_subfolder/configure '--prefix=/home/wouter/.conan/data/m4/1.4.18/_/_/package/91a4ede3f059ef52815958df6195330b87cd719c' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/wouter/.conan/data/m4/1.4.18/_/_/build/91a4ede3f059ef52815958df6195330b87cd719c':
configure: error: C compiler cannot create executables
See `config.log' for more details
m4/1.4.18: 
m4/1.4.18: ERROR: Package '91a4ede3f059ef52815958df6195330b87cd719c' build failed
m4/1.4.18: WARN: Build folder /home/wouter/.conan/data/m4/1.4.18/_/_/build/91a4ede3f059ef52815958df6195330b87cd719c
ERROR: m4/1.4.18: Error in build() method, line 75
	autotools = self._configure_autotools()
while calling '_configure_autotools', line 42
	self._autotools.configure(args=conf_args, configure_dir=self._source_subfolder)
	ConanException: Error 77 while executing source_subfolder/configure '--prefix=/home/wouter/.conan/data/m4/1.4.18/_/_/package/91a4ede3f059ef52815958df6195330b87cd719c' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' 
```

**Comment by madebr** [comment]
Your profile does not set any environment variables.
The configure script will use `/usr/bin/cc`, which probably symlinks to `/usr/bin/gcc`.
See your log:
```
checking for gcc... gcc
```
Does adding these lines to your profile change something?
```
[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
```
If it doesn't, can you share your `config.log`?
This file is created in the root build folder.

**Comment by wouterbeek** [comment]
@madebr Thanks!  Defining the compiler type twice (once under `[settings]` and once under `[env]`) indeed solves the issue.  (I'm not sure why this must be configured in two places, but this is probably due to a lack of knowledge on my side.)

Quickly closing this issue...

**Comment by madebr** [comment]
From what I understand:
The settings sections is used to populate the `settings` object.
But the build helpers won't automagically find/use the correct build toolchain.
e.g. for cross building the gcc compiler might have a `aarch64-linux-gnu-` prefix.
So you can set `CC=aarch64-linux-gnu-gcc` in the env section.

**Comment by wouterbeek** [comment]
@madebr Of course, the different configurations are for cross-building!  I'm still waiting for that first good book on Conan to come out...  (like https://crascit.com/professional-cmake/ for CMake).

**Comment by steakhal** [comment]
I encountered the same issue - even with the `CC` and `CXX` envvars configured.

```bash
$ conan profile show gnu10
Configuration for profile gnu10:

[settings]
os=Linux
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-10
CXX=/usr/bin/g++-10

$ /usr/bin/gcc-10 --version
gcc-10 (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0

$ which gcc-10 g++-10
/usr/bin/gcc-10
/usr/bin/g++-10

$ cat ../conanfile.txt
[requires]
bison/3.7.1
flex/2.6.4

[generators]
cmake

$ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
$ conan remove -f *
$ conan install .. -pr gnu10 --build
[...]
configure: no bison program found: only required for maintainers
checking for flex... no
checking for lex... no
checking for gcc... (cached) /usr/bin/gcc-10
checking whether we are using the GNU C compiler... (cached) yes
checking whether /usr/bin/gcc-10 accepts -g... (cached) yes
checking for /usr/bin/gcc-10 option to accept ISO C89... (cached) none needed
checking whether /usr/bin/gcc-10 understands -c and -o together... (cached) yes
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/home/steak/.conan/data/flex/2.6.4/_/_/build/21011818b664ba5f28bbba5f38f3117d33c4b91b/source_subfolder':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
flex/2.6.4:
flex/2.6.4: ERROR: Package '21011818b664ba5f28bbba5f38f3117d33c4b91b' build failed
flex/2.6.4: WARN: Build folder /home/steak/.conan/data/flex/2.6.4/_/_/build/21011818b664ba5f28bbba5f38f3117d33c4b91b
ERROR: flex/2.6.4: Error in build() method, line 65
        autotools = self._configure_autotools()
while calling '_configure_autotools', line 57
        self._autotools.configure(args=configure_args)
        ConanException: Error 1 while executing ./configure '--disable-nls' 'HELP2MAN=/bin/true' 'M4=m4' '--disable-shared' '--enable-static' 'ac_cv_func_malloc_0_nonnull=yes' 'ac_cv_func_realloc_0_nonnull=yes' 'ac_cv_func_reallocarray=no' '--prefix=/home/steak/.conan/data/flex/2.6.4/_/_/package/21011818b664ba5f28bbba5f38f3117d33c4b91b' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share'
```

Here is the [config.log](https://github.com/conan-io/conan-center-index/files/5736846/config.log).

**Comment by madebr** [comment]
@steakhal 
Your problem is with `flex`, not with `m4`.
Looking at your logs, you're building on WSL(2). Is that correct?
Can you try adding `CC_FOR_BUILD=/usr/bin/gcc-10` to the environment of your profile?

**Comment by steakhal** [comment]
> @steakhal
> Your problem is with `flex`, not with `m4`.
> Looking at your logs, you're building on WSL(2). Is that correct?
You are correct.
> Can you try adding `CC_FOR_BUILD=/usr/bin/gcc-10` to the environment of your profile?
Wow, it solved.
At least it builds now, thank you.

BTW shouldn't conan populate such envvars for the build those are required?
I'm not sure if I should spew a lot of different envvars into my conan profile just to make different projects buildable.

**Comment by madebr** [comment]
> > @steakhal


> > Can you try adding `CC_FOR_BUILD=/usr/bin/gcc-10` to the environment of your profile?
> > Wow, it solved.

> At least it builds now, thank you.

Great to hear!

> BTW shouldn't conan populate such envvars for the build those are required?
> I'm not sure if I should spew a lot of different envvars into my conan profile just to make different projects buildable.

Now that we know that flex is able to build with setting `CC_FOR_BUILD` explicitly, I can modify the flex recipe to copy, if set, the `CC` env variable to `CC_FOR_BUILD`.

**Comment by madebr** [comment]
Please remove the `CC_FOR_BUILD=` from your profile and try https://github.com/conan-io/conan-center-index/pull/4003

**Comment by steakhal** [comment]
> Please remove the `CC_FOR_BUILD=` from your profile and try #4003
Seems to work for me with both gcc-10 and clang-10 this way.
Thank you for your effort.
