### ISSUE TITLE
[question] qt/6.6.0 does not have StateMachine module

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#20754]
### What is your question?

@ericLemanissier is there a way of adding StateMachine module to qt/6.6.0?

**Comment by ericLemanissier** [comment]
With option `qt:qtscxml=True` ?

**Comment by ericLemanissier** [comment]
@AndreyMlashkin if the question is answered, please consider closing the issue

**Comment by AndreyMlashkin** [comment]
Sure, thank you for a quick response!

**Comment by AndreyMlashkin** [comment]
Thx
