### ISSUE TITLE
Cpython 

### ISSUE THREAD

**Issue by jellespijker** [conan-io/conan-center-index#20768]
### Package Name/Version

cpython/3.12.0

### Changelog

https://docs.python.org/3/whatsnew/changelog.html

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

one of our main dependencies for https://github.com/Ultimaker/Cura is CPython, this recipe is also the only recipe which is blocking us for moving forward to using Conan 2.0 instead of Conan 1.x

We're currently investigating how much effort it will be to switch from using CPython 3.10.4 to 3.12 and will probably make the actual switch in a month or so. Having 3.12.x in the CCI would be a huge help for us.

3.12 has ~25% speed improvements along the board compared to 3.10.x and I'm sure other project would also benefit from having 3.12 in the CCI

**Comment by jellespijker** [comment]
@memsharded can I lobby with you to give this recipe a bit of priority? We at UltiMaker are ofcourse more than willing to also put in the effort to get CPython 3.12 in the CCI so we can start upgrading to Conan 2.0

**Comment by samuel-emrys** [comment]
The blocker for cpython at the moment is ncurses in conan 2, for which there have been a few attempts:
* https://github.com/conan-io/conan-center-index/pull/20355
* https://github.com/conan-io/conan-center-index/pull/18568
* https://github.com/conan-io/conan-center-index/pull/17805

Some of these are close, but haven't been able to pass the full complement of CI tests. I haven't had the time to invest in continuing my draft PR - if you have that time/effort available then that would be useful work to do.

**Comment by jellespijker** [comment]
That is good to known, thank you @samuel-emrys I might do some personal digging in that recipe this weekend. What is the policy of the CCI with regards to updating recipes without full Conan v2 support?

Or stack is currently still stuck on using Conan v1, but we need to update our CPython versions because of the deprecation of OpenSSL1.1.1 If we can update the CPython recipe to 3.12 without fully supporting Conan v2 would that be acceptable?

**Comment by valgur** [comment]
I have a branch with ongoing work for the CPython recipe, but it still has some linking issues against third-party libraries that I have not figured out: https://github.com/valgur/conan-center-index/tree/migrate%2Fcpython/recipes%2Fcpython
I would love to see the recipe both migrated and updated to 3.12. I'm personally looking forward to making use of the new stable ABI for forwards-compatible binary modules.
If anyone is interested in collaborating on getting the recipe migrated and/or updated,  get in touch on the cpplang Slack or here.
