### ISSUE TITLE
[package] zeromq/4.3.4: Recipe 'zeromq/4.3.4' seems broken.

### ISSUE THREAD

**Issue by LarsLeferenz** [conan-io/conan-center-index#20780]
### Description

The simple conanfile.txt
```
[requires]
zeromq/4.3.4
```
fails with:
```
*********************************************************
Recipe 'zeromq/4.3.4' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************
```

### Package and Environment Details

* Package Name/Version: **zeromq/4.3.4**
* Operating System+version: **Windows 11**
* Compiler+version: **MSVC**
* Conan version: **conan 2.0.13**
* Python version: **Python 3.11.6**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

### Steps to reproduce

`conan install -of build conanfile.txt --build=missing`

### Logs

<details><summary>Click to expand log</summary>

```

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    conanfile.txt: C:\Users\Lars\Documents\SenSimComTest\conanfile.txt
*********************************************************
Recipe 'zeromq/4.3.4' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'zeromq/4.3.4' not resolved: zeromq/4.3.4: Cannot load recipe.
Error loading conanfile at 'C:\Users\Lars\.conan2\p\zeromb8b601cae17ed\e\conanfile.py': C:\Users\Lars\.conan2\p\zeromb8b601cae17ed\e\conanfile.py not found!.
```

</details>

**Comment by uilianries** [comment]
Hello @LarsLeferenz I believe you have something cached that's sabotaging you, because zeromq package is ported to Conan 2.x already and available in Conan Center.

Could you please run the follow commands:

    conan remove zeromq -c
    conan install --requires=zeromq/4.3.3 -r conancenter --build=missing

I tested locally, but on Mac OSX and is working.

**Comment by LarsLeferenz** [comment]
That fixed it, thank you very much^^
