### ISSUE TITLE
[service] policy of deleting cmake config files breaks PMM

### ISSUE THREAD

**Issue by barcharcraz** [conan-io/conan-center-index#208]
PMM  (https://github.com/vector-of-bool/pmm) uses the cmake conan generator, but only calls `conan_define_targets()` and `conan_set_paths()` relevant code is in `pmm/conan.cmake` in the macro `_pmm_conan_do_setup`

For some reason this causes things to not work for the following conanfile.txt:
```
[requires]
fmt/6.0.0
```
and the following cmakelists

```
cmake_minimum_required(VERSION 3.16)

project(mailing_to_rdf LANGUAGES CXX)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/cmake)
include(pmm)
pmm(VERBOSE CONAN BINCRAFTERS)
find_package(fmt REQUIRED)
file(GLOB_RECURSE mailing_to_rdf_src CONFIGURE_DEPENDS src/*.cpp)
add_executable(mailing_to_rdf)
target_sources(mailing_to_rdf PRIVATE ${mailing_to_rdf_src})
target_link_libraries(mailing_to_rdf
    PRIVATE
        fmt::fmt)
```

**Comment by danimtb** [comment]
Answered here: https://github.com/conan-io/conan-center-index/issues/209#issuecomment-542595803
