### ISSUE TITLE
[package] grpc/1.54.3: Shared build creates a broken 'grpc_cpp_plugin' executable

### ISSUE THREAD

**Issue by jorisguex** [conan-io/conan-center-index#20823]
### Description

When using the `grpc_cpp_plugin` executable to generate C++ gRPC code from .proto files, building `grpc` as `shared` causes it to fail. This is because the executable requires shared object files (such as `libgrpc_plugin_support.so.1.54` and `libprotoc.so.32`) but no rpath or runpath is provided so they cannot be found.

I'm not sure if this is an upstream issue, a conan center issue, or if I am doing something wrong.

### Package and Environment Details

* Package Name/Version: **grpc/1.54.3#b9dab567bb1de36e1fababfa2ee5edac**
* Host Operating System+version: **Mac OS 13.1 (22C65)**
* Docker Operating System+version: **Debian 12 (bookworm)**
* Compiler+version: **GCC 12.2.0**
* Docker image: **python:3.12@sha256:335fec226532b1148af600b058a431fe677191115721702215b6f5fcc8a75bc8**
* Conan version: **conan 2.0.13**
* Python version: **Python 3.12.0**

### Conan profile

[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

### Steps to reproduce

Full Dockerfile showing the issue here:
```
# Install Python, Conan and CMake
FROM python:3.12@sha256:335fec226532b1148af600b058a431fe677191115721702215b6f5fcc8a75bc8
RUN apt update && apt install -y cmake
RUN pip install conan==2.0.13

# Create new Conan recipe with grpc requirement (latest version and revision)
RUN conan profile detect
RUN conan new cmake_exe -d name=example -d version=0.1.0
RUN echo '    requires = "grpc/1.54.3#b9dab567bb1de36e1fababfa2ee5edac"' >> conanfile.py

# Add grpc file generation to CMakeLists.txt
RUN echo 'find_package(gRPC REQUIRED)' >> CMakeLists.txt
RUN echo 'find_package(protobuf REQUIRED)' >> CMakeLists.txt
RUN echo 'add_library(example-grpc /example.proto)' >> CMakeLists.txt
RUN echo 'target_include_directories(example-grpc PUBLIC ${CMAKE_CURRENT_BINARY_DIR})' >> CMakeLists.txt
RUN echo 'target_link_libraries(example-grpc gRPC::grpc++ protobuf::libprotobuf)' >> CMakeLists.txt
RUN echo 'protobuf_generate(TARGET example-grpc \
                            LANGUAGE cpp IMPORT_DIRS / \
                            PROTOC_OUT_DIR ${CMAKE_CURRENT_BINARY_DIR})' \
    >> CMakeLists.txt
RUN echo 'protobuf_generate(TARGET example-grpc \
                            LANGUAGE grpc \
                            GENERATE_EXTENSIONS .grpc.pb.h .grpc.pb.cc \
                            PLUGIN protoc-gen-grpc=$<TARGET_FILE:gRPC::grpc_cpp_plugin> \
                            IMPORT_DIRS / \
                            PROTOC_OUT_DIR ${CMAKE_CURRENT_BINARY_DIR})' \
    >> CMakeLists.txt

# Create new blank proto file for testing purposes
RUN echo 'syntax = "proto3";' >> example.proto

# Shared=False works fine (as expected)
RUN conan create . --build=missing --options *:shared=False && echo "Build succeeded!"

# Shared=True fails (unexpectedly)
RUN conan create . --build=missing --options *:shared=True || echo "Build failed!"

# Shared=True works fine after manually setting the library paths
RUN export LD_LIBRARY_PATH="$(dirname $(find / -wholename */lib/libgrpc_plugin_support.so.1.54)):$(dirname $(find / -wholename */lib/libprotoc.so.32))"; \
       conan create . --build=missing --options *:shared=True && echo "Build succeeded!"
```

### Logs
[Full docker log](https://github.com/conan-io/conan-center-index/files/13198219/build.log)

**Comment by SpaceIm** [comment]
It's unlikely a conancenter issue. You have to use VirtualBuildEnv (or VirtualRunEnv in build scope) for your build, it depends how you require grpc and protobuf.

**Comment by jorisguex** [comment]
Thank you for the reply and help @SpaceIm

I had tried using `VirtualBuildEnv` but I missed the key step of using the `build` scope.
It is now working exactly as expected, closing this issue now.
