### ISSUE TITLE
[New Feature] libcurl/7.71.0

### ISSUE THREAD

**Issue by rushikesh90** [conan-io/conan-center-index#2082]
### Package Details
  * Package Name/Version: libcurl/7.71.0
  * Website: https://curl.haxx.se
 * Source code: https://github.com/curl/curl

### Description Of The Library / Tool
The curl has option to use various ssl vendors. Currently no recipe is present using wolfssl instead of openssl in curl configuration.

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/2053

**Comment by rushikesh90** [comment]
@Croydon How this adds wolfssl? I don't understand

**Comment by rushikesh90** [comment]
@SSE4 I think it is wrongly closed

**Comment by uilianries** [comment]
> The curl has option to use various ssl vendors

@rushikesh90 could you please show us such reference? (link to source file + lines)

**Comment by Croydon** [comment]
@rushikesh90 Sorry, I misinterpreted your issue

This is another case where we would have needed a `Package: New Feature` issue template to make it clear. I guess I will soon-ish open a PR adding such a template 🤔

**Comment by rushikesh90** [comment]
@uilianries The link is https://curl.haxx.se/docs/install.html. On this page if you go to **_Select TLS backend_** heading, you can find it. Also I am pasting the configure options below.



GnuTLS: --without-ssl --with-gnutls.
wolfSSL: --without-ssl --with-wolfssl
NSS: --without-ssl --with-nss
mbedTLS: --without-ssl --with-mbedtls
schannel: --without-ssl --with-schannel
secure transport: --without-ssl --with-secure-transport
MesaLink: --without-ssl --with-mesalink
BearSSL: --without-ssl --with-bearssl

**Comment by rushikesh90** [comment]
Done in #2270

**Comment by GirtsR** [comment]
There was a bug in the current implementation of wolfSSL in the conanfile, for which I filed a PR: https://github.com/conan-io/conan-center-index/pull/2317
