### ISSUE TITLE
[paho-mqtt-cpp] libpaho-mqttpp3/1.2.0: Shared option broken

### ISSUE THREAD

**Issue by agouby** [conan-io/conan-center-index#20831]
### Description

After migrating to Conan 2.0, `paho-mqtt-cpp` seems to be broken when compiled with shared option.

Trying to link with the lib will throw:
`error while loading shared libraries: libpaho-mqtt3as.so.1: cannot open shared object file: No such file or directory`

From the logs it seems that on `build/Release/src/libpaho-mqttpp3.so.1.2.0` `RUNPATH` is correctly set, but the installed lib in `lib/libpaho-mqttpp3.so.1.2.0` is not. (`libpaho-mqtt3as.so.1 => not found`)

Not sure if these warnings have anything to do with it.
```
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: paho-mqtt-c/1.3.9, zlib/1.3, openssl/3.1.3, paho-mqtt-cpp/1.2.0
WARN: deprecated:     'cpp_info.build_modules' used in: openssl/3.1.3
WARN: deprecated:     'env_info' used in: openssl/3.1.3
```

From conan center I can see that the documentation describes steps to use the lib only in static mode.\
I don't know if that means shared mode is not supported yet if if it's truly a bug.

### Package and Environment Details

* Package Name/Version: **paho-mqtt-cpp/1.2.0*
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **GCC 13**
* Conan version: **conan 2.0.13**
* Python version: **Python 3.10.12**

### Conan profile

[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=13
compiler.libcxx=libstdc++11

### Steps to reproduce

conan install --requires=paho-mqtt-cpp/1.2.0 --build=missing -s build_type=Debug -o shared=True

### Logs

<details><summary>Click to expand log</summary>

```
~:~/.conan2/p/b/paho-550df1062c78b$ find -name *.so*
./p/lib/libpaho-mqttpp3.so.1
./p/lib/libpaho-mqttpp3.so.1.2.0
./p/lib/libpaho-mqttpp3.so
./b/build/Release/src/libpaho-mqttpp3.so.1
./b/build/Release/src/libpaho-mqttpp3.so.1.2.0
./b/build/Release/src/libpaho-mqttpp3.so
~:~/.conan2/p/b/paho-550df1062c78b$ ldd ./p/lib/libpaho-mqttpp3.so.1.2.0
        linux-vdso.so.1 (0x00007fff9b9f7000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f695b400000)
        libpaho-mqtt3as.so.1 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f695b000000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f695b6b1000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f695b3e0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f695b2f9000)
~:~/.conan2/p/b/paho-550df1062c78b$ ldd ./b/build/Release/src/libpaho-mqttpp3.so.1.2.0
        linux-vdso.so.1 (0x00007ffe603cb000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdb1da00000)
        libpaho-mqtt3as.so.1 => /home/agouby/.conan2/p/b/paho-1cc2d4b8f8264/p/lib/libpaho-mqtt3as.so.1 (0x00007fdb1d200000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdb1ce00000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdb1dcf9000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdb1dc6e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdb1d919000)
~:~/.conan2/p/b/paho-550df1062c78b$ 
```

</details>

**Comment by SpaceIm** [comment]
That's expected, RUNPATH is not set in shared libs packaged by conancenter, it's not related to conancenter. You are supposed to use `VirtualRunEnv` if you want to find runtimes.

**Comment by uilianries** [comment]
Hello @agouby ! Please, check if your environment is correctly configured. The Conan tutorial shows how to consume a shared library here: https://docs.conan.io/2/tutorial/consuming_packages/different_configurations.html#modifying-options-linking-the-application-dependencies-as-shared-libraries. Please, take a read.

In Conan 1.x we had `[env]` entry for ld library path, but it changed in 2.x, now we consume it separated as build env (useful for tooling) and run env.

**Comment by agouby** [comment]
I figured out when happens.

Basically I made a simple test lib to migrate to conan 2.0.\
On my old version, I would get ` libpaho-mqtt3as.so.1` directly linked with my lib and not on my test lib.\
The reason behind seems to be that the lib appears as a direct dependency once I call the `subscribe` function from Paho.\
Because of that it links the C library directly..

Full lib
```
Dynamic Section:
  NEEDED               libpaho-mqttpp3.so.1
  NEEDED               libpaho-mqtt3as.so.1
  NEEDED               libspdlogd.so.1.12
  NEEDED               libfmtd.so.10
  NEEDED               libstdc++.so.6
  NEEDED               libc.so.6
  NEEDED               libgcc_s.so.1
  SONAME               libpza-cxx.so.0
  RUNPATH              /home/agouby/.conan/data/paho-mqtt-cpp/1.2.0/_/_/package/9c64cbf3180043b8f0950a6a1e3b7b45cddd6eb4/lib:/home/agouby/.conan/data/paho-mqtt-c/1.3.9/_/_/package/0b31e7ec7f2e18597a8ab426423397b425f30a84/lib:/home/agouby/.conan/data/openssl/3.1.3/_/_/package/2e9d8e0eec75a61d51a41bf7e44f817a623926da/lib:/home/agouby/.conan/data/zlib/1.3/_/_/package/22905c179f7cf3ff81235b81b25a25f81a5442b8/lib:/home/agouby/.conan/data/spdlog/1.12.0/_/_/package/5eeb527cd5ecf65f4dfefa2bf26b35a5903459ae/lib:/home/agouby/.conan/data/fmt/10.1.1/_/_/package/86d13f5bd1effc52067c5ae36dfcba0ecedc2c1c/lib:
```
Test lib
```
Dynamic Section:
  NEEDED               libpaho-mqttpp3.so.1
  NEEDED               libstdc++.so.6
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2
  NEEDED               libgcc_s.so.1
  SONAME               libpza-cxx.so.0
  RUNPATH              /home/agouby/.conan/data/paho-mqtt-cpp/1.2.0/_/_/package/9c64cbf3180043b8f0950a6a1e3b7b45cddd6eb4/lib:/home/agouby/.conan/data/paho-mqtt-c/1.3.9/_/_/package/0b31e7ec7f2e18597a8ab426423397b425f30a84/lib
  ```
  
  So what happend was that for my full lib I would not need `VirtualRunEnv`, but that's out of luck kindof.\
  
  So no problem in the end, thanks for the help folks :+1:
