### ISSUE TITLE
[request] icu/74.1

### ISSUE THREAD

**Issue by AshleighAdams** [conan-io/conan-center-index#20878]
### Package Name/Version

icu/74.1

### Changelog

https://github.com/unicode-org/icu/releases/tag/release-74-1

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

In addition, for me specifically, I'm looking to use ICU with MSVC/C++20, which previous ICU versions fails to build under.

**Comment by SpaceIm** [comment]
There is PR already: https://github.com/conan-io/conan-center-index/pull/20873

**Comment by AshleighAdams** [comment]
That PR is merged, will close now
