### ISSUE TITLE
[service] Unable to create PR from updatable-recipes bot link

### ISSUE THREAD

**Issue by patmantru** [conan-io/conan-center-index#20881]
### What is your problem/feature request?

I visited https://qchateau.github.io/conan-center-bot/#/updatable hoping to do a version bump PR to update the recipe to include the newest 1.5.6 release of opentdf-client.  I clicked the link, it filled in the PR template, I updated the text, but when I hit 'Create Pull Request', it errored with "Pull request creation failed. Validation failed: must be a collaborator"

Has something changed about the way this works?  Do I need to be re-validated as someone who updates that recipe?

Thanks-
Pat

**Comment by patmantru** [comment]
@qchateau

**Comment by uilianries** [comment]
@patmantru Please, open an issue directly to https://github.com/qchateau/conan-center-bot/issues. That bot is not part of Conan Center Index, neither an official tool.
