### ISSUE TITLE
[package] usockets/0.8.6: install of `usockets` with option `with_ssl=openssl` fails with `TypeError`

### ISSUE THREAD

**Issue by jmdaly** [conan-io/conan-center-index#20896]
### Description

When attempting to install the `usockets` library from conancenter, it installs correctly if the default package options are used. However, when I attempt to install `usockets` and enable openssl, I get a Python `TypeError` as follows:

```
ERROR: usockets/0.8.6: Error in validate() method, line 125
        minimum_version = self._minimum_compilers_version(self._min_cppstd)
        TypeError: UsocketsConan._minimum_compilers_version() missing 1 required positional argument: 'cppstd'
```

I believe there might be a bug in the recipe around line 125.

### Package and Environment Details

* Package Name/Version: **usockets/0.8.6**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.0.13**
* Python version: **Python 3.10.12**

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

### Steps to reproduce

conan install --requires=usockets/0.8.6 -o "usockets/0.8.6:with_ssl=openssl"

### Logs

<details><summary>Click to expand log</summary>

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
usockets/0.8.6:with_ssl=openssl

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux


======== Computing dependency graph ========
usockets/0.8.6: Not found in local cache, looking in remotes...
usockets/0.8.6: Checking remote: conancenter
usockets/0.8.6: Downloaded recipe revision a6ee6e3cb0a37ddbffdad6d1732ace2e
Graph root
    cli
Requirements
    openssl/3.0.7#0 - Cache
    usockets/0.8.6#a6ee6e3cb0a37ddbffdad6d1732ace2e - Downloaded (conancenter)
    zlib/1.2.13#0 - Cache
Resolved version ranges
    openssl/[>=1.1 <4]: openssl/3.0.7

======== Computing necessary packages ========
ERROR: usockets/0.8.6: Error in validate() method, line 125
        minimum_version = self._minimum_compilers_version(self._min_cppstd)
        TypeError: UsocketsConan._minimum_compilers_version() missing 1 required positional argument: 'cppstd'
```

</details>

**Comment by SpaceIm** [comment]
Should be fixed by https://github.com/conan-io/conan-center-index/pull/20898. Could you try please?

**Comment by jmdaly** [comment]
Thanks for the quick reply! I copied your changes to a local recipe, and they work for me. I wasn't sure how to configure the conan client to use the `fix/usockets-compiler-min-version` branch in your fork as a remote, but I think your changes resolve the issue!
