### ISSUE TITLE
[question] Cross-building for Emscripten on Windows

### ISSUE THREAD

**Issue by tuccio** [conan-io/conan-center-index#20901]
Hi, I have been trying to setup cross-building for `Emscripten` on `Windows`, but I can't seem to get `CMake` to find the `MinGW` binaries as I would expect. I am wondering if I'm doing something wrong or I just have the wrong expectations.

I am currently using these profiles:
```
Profile host:
[settings]
arch=wasm
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=17
os=Emscripten
[tool_requires]
*: emsdk/3.1.44, cmake/3.27.7, msys2/cci.latest
[conf]
tools.build:cxxflags=['-matomics', '-mbulk-memory', '-msimd128']

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows
```

Conan install on my consumer `conanfile.py` fails when building requirements:
```
fmt/8.0.1: Building from source
fmt/8.0.1: Package fmt/8.0.1:4c91864639ef514e5756af0ee2942b39955593f3
fmt/8.0.1: Copying sources to build folder
fmt/8.0.1: Building your package in C:\Users\Davide Tuccilli\.conan2\p\b\fmta56e3a8ba2465\b
fmt/8.0.1: Calling generate()
fmt/8.0.1: Generators folder: C:\Users\Davide Tuccilli\.conan2\p\b\fmta56e3a8ba2465\b\build\Release\generators
fmt/8.0.1: CMakeToolchain generated: conan_toolchain.cmake
fmt/8.0.1: CMakeToolchain generated: CMakePresets.json
fmt/8.0.1: CMakeToolchain generated: ..\..\..\src\CMakeUserPresets.json
fmt/8.0.1: Generating aggregated env files
fmt/8.0.1: Generated aggregated env files: ['conanbuild.bat', 'conanrun.sh']
fmt/8.0.1: Calling build()
fmt/8.0.1: apply_conandata_patches(): No patches defined in conandata
fmt/8.0.1: Running CMake.configure()
fmt/8.0.1: RUN: cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="C:/Users/Davide Tuccilli/.conan2/p/b/fmta56e3a8ba2465/b/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/Davide Tuccilli/.conan2/p/b/fmta56e3a8ba2465/p" -DFMT_DOC="OFF" -DFMT_TEST="OFF" -DFMT_INSTALL="ON" -DFMT_LIB_DIR="lib" -DFMT_OS="ON" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:\Users\Davide Tuccilli\.conan2\p\b\fmta56e3a8ba2465\b\src"
-- CMake version: 3.27.7
-- Using Conan toolchain: C:/Users/Davide Tuccilli/.conan2/p/b/fmta56e3a8ba2465/b/build/Release/generators/conan_toolchain.cmake
The system cannot find the path specified.
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
```

I can somewhat work around the issue by adding the directory to the `MinGW` binaries to my `PATH` environment variable, but I had the impression this should not be necessary with `msys2/cci.latest` in my `tool_requires`.

What I would have expected is that, in this particular case, the generated `conanbuildenv-release-wasm.bat` in the build folder of `fmt` would also add the binary folder for `msys2` to `PATH`, but that is not the case for `cmake` or `msys2`, although `emsdk` and its dependencies are being added there.

I would appreciate any clarification on how this should work.

**Comment by uilianries** [comment]
Maybe adding more configuration to your host profile: https://docs.conan.io/2/reference/config_files/global_conf.html

- tools.gnu:make_program: Indicate path to make program
- tools.microsoft.bash:subsystem
- tools.build:compiler_executables: Defines a Python dict-like with the compilers path to be used. Allowed keys {'c', 'cpp', 'cuda', 'objc', 'objcxx', 'rc', 'fortran', 'asm', 'hip', 'ispc'}

NOTE: I didn't test locally.

**Comment by tuccio** [comment]
Hi,
Thank you for your answer.

Hardcoding the path of make through `tools.gnu:make_program` also works, but I was trying to avoid dong that because I want to share the profile with others and CI, and I was hoping the build requires would just take care of paths for me, like it does for `cmake` and `emsdk`.

I did try setting `tools.microsoft.bash:subsystem=msys2` and `self.win_bash=True` in `build_requires` in my consumer `conanfile.py`, but that didn't seem to do anything either.

**Comment by uilianries** [comment]
So `tools.gnu:make_program` looks the correct way, Conan has no way to predict what is the correct `make` to be used, it should be explicit indeed. You still can share you profile, but each person/CI has the liberty to have it installed in a different folder.

> I was hoping the build requires would just take care of paths for me, like it does for cmake and emsdk.

It does not take, it uses the cmake from your PATH and that's it, but is fragile as well in case you have more than one version installed.

**Comment by tuccio** [comment]
> It does not take, it uses the cmake from your PATH and that's it, but is fragile as well in case you have more than one version installed.

Well I would have thought it's intended behavior, but my `conanbuildenv-release-wasm.bat` from the original example contains
```bat
set "PATH=C:\Users\Davide\.conan2\p\b\emsdkad8a0348992fa\p\bin;C:\Users\Davide\.conan2\p\b\emsdkad8a0348992fa\p\bin\upstream\emscripten;C:\Users\Davide\.conan2\p\nodej33a9f7e739198\p\bin;C:\Users\Davide\.conan2\p\cmake9ed6bb793264d\p\bin;%PATH%"`
```

Which include `emsdk` and `cmake` that I specified in `tool_requires`, since they might be needed to build. What I wasn't able to figure out is how to get `msys` to be added as well.
