### ISSUE TITLE
[package] boost/all-versions: Fails to install attempting to write to C:\\.conan

### ISSUE THREAD

**Issue by shoreadmin** [conan-io/conan-center-index#2090]
### Package and Environment Details
  * Package Name/Version: **boost/1.73**
  * Operating System+version: **Windows 10 x64**
  * Compiler+version: **Visual Studio 2017/2019**
  * Conan version: **conan 1.26.0**

### Conan profile
```
C:\dev\test\build>conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce
I've just tried to run the most basic use-case and it has failed!  I've installed conan using the Windows installer: `conan-win-64_1_26_0.exe` onto my Windows 10 dev machine as an administrator (not per-user), created a directory with the following into the` C:\dev\test\conanfile.txt`:
```
[requires]
boost/1.73.0

[generators]
cmake_find_package
cmake_paths
```

I've had success installing other packages, though:
* nlohmann_json/3.8.0
* zlib/1.2.11
* fmt/6.2.0
* libpng/1.6.37
* spdlog/1.6.1

Also fails on `boost/1.69.0`.

Note also that this PC is domain joined, and I don't have write access to the root of C:\ drive.

### Logs
<details><summary>Click to expand log</summary>

```
PS C:\dev\test\build> conan install ..
Auto detecting your dev setup to initialize the default profile (C:\Users\<myusername>\.conan\profiles\default)
Found Visual Studio 16
Default settings
        os=Windows
        os_build=Windows
        arch=x86_64
        arch_build=x86_64
        compiler=Visual Studio
        compiler.version=16
        build_type=Release
*** You can change them in C:\Users\<myusername>\.conan\profiles\default ***
*** Or override with -s compiler='other' -s ...s***


WARN: Remotes registry file missing, creating default one in C:\Users\<myusername>\.conan\remotes.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

boost/1.73.0: Not found in local cache, looking in remotes...
boost/1.73.0: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [1.26k]
Downloading conanfile.py completed [40.72k]
Downloading conan_export.tgz completed [0.36k]
Decompressing conan_export.tgz completed [0.00k]
boost/1.73.0: Downloaded recipe revision 0
zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.31k]
Downloading conanfile.py completed [7.88k]
Downloading conan_export.tgz completed [0.31k]
Decompressing conan_export.tgz completed [0.00k]
zlib/1.2.11: Downloaded recipe revision 0
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.17k]
Downloading conanfile.py completed [2.07k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
bzip2/1.0.8: Downloaded recipe revision 0
Traceback (most recent call last):
  File "conan\conans\client\command.py", line 2035, in run
  File "conan\conans\client\command.py", line 506, in install
  File "conan\conans\client\conan_api.py", line 92, in wrapper
  File "conan\conans\client\conan_api.py", line 578, in install
  File "conan\conans\client\manager.py", line 56, in deps_install
  File "conan\conans\client\graph\graph_manager.py", line 109, in load_graph
  File "conan\conans\client\graph\graph_manager.py", line 236, in _resolve_graph
  File "conan\conans\client\graph\graph_manager.py", line 346, in _load_graph
  File "conan\conans\client\graph\graph_manager.py", line 277, in _recurse_build_requires
  File "conan\conans\client\graph\graph_binaries.py", line 343, in evaluate_graph
  File "conan\conans\client\graph\graph_binaries.py", line 167, in _evaluate_node
  File "conan\conans\client\graph\graph_binaries.py", line 208, in _process_node
  File "conan\conans\paths\package_layouts\package_cache_layout.py", line 31, in wrap
  File "conan\conans\util\windows.py", line 82, in path_shortener
  File "conan\conans\util\files.py", line 275, in mkdir
  File "os.py", line 220, in makedirs
PermissionError: [WinError 5] Access is denied: 'C:\\.conan'
```

</details>

**Comment by uilianries** [comment]
@shoreadmin You error is related to your environment, I can sure it's not related to Boost recipe, otherwise we would have tons of the same issue.

Take a look on https://github.com/conan-io/conan/issues/6560#issuecomment-590793970

If disabling the antivirus (even native one in Windows), I recommend you opening an issue to https://github.com/conan-io/conan/issues/

**Comment by SpaceIm** [comment]
boost recipe uses `short_paths`. Default behavior of conan on Windows for such recipes is to create packages in `C:\.conan`. You can modify default `short_paths` folder (where you have write access for example), see https://docs.conan.io/en/latest/reference/config_files/conan.conf.html

**Comment by shoreadmin** [comment]
Thanks, @SpaceIm - that's what it was!  I hadn't come across that feature yet! 

@uilianries - you're right that it was caused by the environment - we can't write to `C:\`.  That said - I'm pretty sure I've read that writing to the root path (or anywhere that isn't your user directory?) is "discouraged" in Windows now?  Perhaps the `shore_paths` feature should be opt-in during installation on Windows (for admin install), or maybe it should be set to a default within your user directory and warn if it doesn't meet the 50 character limit?  A problem for conan itself, I guess.

**Comment by uilianries** [comment]
@shoreadmin Thanks for your feedback! 

You can disable short_paths, or change the base path if you want: https://docs.conan.io/en/latest/reference/env_vars.html#conan-user-home-short

The main reason for using C:\ is because on Windows file paths can have 256 characters at least. However, you can change the default behavior on Windows: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#short-paths-reference

Regards!

**Comment by forry** [comment]
Can anybody explain why is this (short_paths) behaviour forced on the level of the package (which doesn't know where it will be deployed) on some (not all) packages like boost, bullet, etc., and not on others? Why is this even an attribute?
This is making it hard for me as a kind of an admin to explain to some users why the conan suddenly creates a folder somewhere else or in the worst case why it failed because of insufficient privileges. And telling everyone to set CONAN_USER_HOME_SHORT=None even when the platform has no path length limitation.
