### ISSUE TITLE
[request] protobuf/3.21.8

### ISSUE THREAD

**Issue by noahbkim** [conan-io/conan-center-index#20937]
### Package Name/Version

protobuf/3.21.8

### Changelog

https://github.com/protocolbuffers/protobuf/releases/tag/v3.21.8

### Context about the new update

Hi! This is an outdated version so I understand if this request has low precedence. This is the version used by the Counter-Strike 2 dedicated server, so I'd like to be able to pin it as a dependency.

**Comment by noahbkim** [comment]
After doing a bit more reading (about Conan + looking through the blame), it's unclear if this is the right approach. It looks like previous versions of `protobuf` have been intentionally purged from conancenter--this is a problem in scenarios like mine where my project will always depend on a fixed version of protobuf.

Is there a way to vendor a custom protobuf recipe locally? I've been reading through the documentation but it doesn't seem like it.

**Comment by noahbkim** [comment]
No worries, I managed to get a local package working :)

Feel free to close this ticket, I just wanted to ask one quick thing while I've got someone's attention:

I'm running into the following

```
CMake Warning (dev) at /usr/local/lib/python3.8/dist-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (Protobuf)
  does not match the name of the calling package (protobuf).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /cache/conan/data/b/proto008cc9ef49562/p/lib/cmake/protobuf/protobuf-module.cmake:162 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  build/gcc-9-x86_64-gnu14-release/generators/protobuf-config.cmake:37 (include)
  CMakeLists.txt:5 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

but I can't figure out what permutation of 

```
        self.cpp_info.set_property("cmake_module_file_name", "Protobuf")
        self.cpp_info.set_property("cmake_file_name", "protobuf")
        # ...
        self.cpp_info.filenames["cmake_find_package"] = "Protobuf"
        self.cpp_info.filenames["cmake_find_package_multi"] = "protobuf"
```

to adjust. If you recognize this issue, do you have any ideas?

Thanks again!

**Comment by czoido** [comment]
Closing as newer versions are available. Thanks for reporting!
