### ISSUE TITLE
[package] pybind11: missing targets

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#2099]
The documentation of pybind11 says it provides the targets `pybind11::module` and `pybind11::embed` to integrate it with CMake.
See: https://pybind11.readthedocs.io/en/stable/compiling.html#advanced-interface-library-target

This targets are not present in the package created by conan, which breaks builds that depend on them.
Is this something that the new feature `components` could fix?

This targets are created with `pybind11Config.cmake` (which is manually deleted on the recipe [here](https://github.com/conan-io/conan-center-index/blob/master/recipes/pybind11/all/conanfile.py#L43)) and `pybind11Targets.cmake` (which is not being generated with this recipe since the main `CMakeLists.txt` detects pybind11 is being built as a subproject).

**Comment by uilianries** [comment]
The name of feature is `modules`, not `components`, and yes, it can be used to add new targets, and assign what you want:

https://docs.conan.io/en/latest/creating_packages/package_information.html#using-components
https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info-attributes-reference

**Comment by ericriff** [comment]
This has been fixed.
