### ISSUE TITLE
[question] What's the policy on name collisions. 

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan-center-index#21]
It would be useful to **explicitly** state the repository policies on different problems that could occur.

For example, since the repository will use the `project/version` format it's a very big chance that there will be conflicts, legal ones included (experience from the npm).

**Comment by SSE4** [comment]
for instance: GSL is `GNU Scientific Library` and `Guidelines Support Library` as well

**Comment by uilianries** [comment]
Use the same name, create distinction by the version :smiling_imp: 

What they did in npm @Minimonium ?

**Comment by Minimonium** [comment]
https://www.npmjs.com/policies
https://docs.npmjs.com/misc/disputes.html

There could be a different solution, but obviously it's wise to follow the lead of industry giants. :slightly_smiling_face:

**Comment by uilianries** [comment]
I looked into VCPKG, what I found:

- gsl is GNU project
- ms-gsl is Guidelines

So they used a prefix. It sounds good, as Microsoft is the maintainer of GSL.

**Comment by SSE4** [comment]
another collision:
https://github.com/jedisct1/libsodium
https://github.com/SodiumFRP/sodium-cxx

**Comment by danimtb** [comment]
> another collision:
> https://github.com/jedisct1/libsodium
> https://github.com/SodiumFRP/sodium-cxx

first should be `libsodium` and the second one just `sodium`?

**Comment by danimtb** [comment]
Hi all!

Currently, we are not very concern about this issue as the C/C++ number of popular libraries is not as big as in other languages. However, we will try to follow popular libraries and common names in order of contribution and review them before PRs are merged.

We have added this question to the FAQ: https://github.com/conan-io/conan-center-index/wiki/FAQ#what-is-the-policy-on-recipe-name-collisions

Hope all this helps to answer the question. Thanks!

**Comment by danimtb** [comment]
Now that this issue is covered in the FAQ, I would call it closed. There is a new discussion about dashes `-` in #109 that is related to this (you take naming seriously!!). Thanks to everyone for the feedback!
