### ISSUE TITLE
[package] freetype/2.12.1: Missing prebuilt package blocking CI checks

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan-center-index#21029]
### Description

The `c3i/conan-v2/pr-merge` in https://github.com/conan-io/conan-center-index/pull/21015 that are required to pass before merge are failing with this error:

```
ERROR: Missing prebuilt package for 'freetype/2.12.1'
Check the available packages using 'conan list freetype/2.12.1:* -r=remote'
or try to build locally from sources using the '--build=freetype/2.12.1' argument
```

I'm not aware of any way that I, as a contributor, am able to get that freetype package uploaded. My general expectation is that any failing checks would be due to my code changes, which I would have full control over fixing.

### Package and Environment Details

* Package Name/Version: **freetype/2.12.1**
* Operating System+version: **Linux (unsure on specific version, but since it's the CI environment I suspect you can look it up?)**
* Compiler+version: **GCC 11**
* Docker image: **(no idea, info not shown in CI logs)**
* Conan version: **conan 2, but the specific version is not shown in the CI logs**
* Python version: **(no idea, info not shown in CI logs)**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=11
os=Linux
[options]
fPIC=True
shared=False
subpixel=False
with_brotli=True
with_bzip2=True
with_png=True
with_zlib=True
[requires]
brotli/1.1.Z
bzip2/1.0.Z
libpng/1.6.Z
zlib/1.3.Z

### Steps to reproduce

1. Click Update Branch button in https://github.com/conan-io/conan-center-index/pull/21015
2. Wait for `c3i/conan-v2/pr-merge` to fail and see the error message (posted below) in an email sent to me

### Logs

<details><summary>Click to expand log</summary>

```
The v2 pipeline failed. Please, review the errors and note this is required for pull requests to be merged. In case this recipe is still not ported to Conan 2.x, please, ping @conan-io/barbarians on the PR and we will help you.

See details:
Failure in build 3 (acd09819e55db5d23ef3ea848175ace9ee548e4b):

sdl_ttf/2.20.1:

 xenial/main amd64 libxcb-util-dev amd64 0.4.0-0ubuntu3 [9,974 B]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 9,974 B in 0s (136 kB/s)
Selecting previously unselected package libxcb-util-dev:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 20599 files and directories currently installed.)
Preparing to unpack .../libxcb-util-dev_0.4.0-0ubuntu3_amd64.deb ...
Unpacking libxcb-util-dev:amd64 (0.4.0-0ubuntu3) ...
Setting up libxcb-util-dev:amd64 (0.4.0-0ubuntu3) ...


======== Installing packages ========
ERROR: Missing binary: freetype/2.12.1:739e41967cd8e90e567861f59c4c6a1087fe7977

freetype/2.12.1: WARN: Can't find a 'freetype/2.12.1' package binary '739e41967cd8e90e567861f59c4c6a1087fe7977' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=11
os=Linux
[options]
fPIC=True
shared=False
subpixel=False
with_brotli=True
with_bzip2=True
with_png=True
with_zlib=True
[requires]
brotli/1.1.Z
bzip2/1.0.Z
libpng/1.6.Z
zlib/1.3.Z

ERROR: Missing prebuilt package for 'freetype/2.12.1'
Check the available packages using 'conan list freetype/2.12.1:* -r=remote'
or try to build locally from sources using the '--build=freetype/2.12.1' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
sdl_ttf/2.20.2:
Didn't run or was cancelled before finishing

sdl_ttf/2.0.18:
Didn't run or was cancelled before finishing

sdl_ttf/2.0.15:
Didn't run or was cancelled before finishing
```

</details>

**Comment by uilianries** [comment]
Sorry about that, I just started an internal build to generate freetype/2.12.1 right now.

**Comment by ssrobins** [comment]
> Sorry about that, I just started an internal build to generate freetype/2.12.1 right now.

Thank you for the quick resolution! https://github.com/conan-io/conan-center-index/pull/21015/ is now merged so I'm closing this.
