### ISSUE TITLE
[service] Add Clang 9 support

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#211]
The service should generate packages for Clang 9.

If added, the wiki should be updated as well: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Comment by Croydon** [comment]
Blocked by https://github.com/conan-io/conan-docker-tools/pull/154

**Comment by uilianries** [comment]
It's already available: https://hub.docker.com/r/conanio/clang9

**Comment by Mirko-von-Leipzig** [comment]
+1 for this issue.

**Comment by uilianries** [comment]
@lasote @danimtb Any update for this issue?

**Comment by danimtb** [comment]
I don't know if this requires any action from my side to configure the new images. It will have to wait

**Comment by danimtb** [comment]
I have proposed the update to generate a profile for clang 9 packages in Jenkins. We will have to wait for confirmation on how to add the new docker images

**Comment by uilianries** [comment]
Okay, thanks for you clarification.

**Comment by uilianries** [comment]
Habemus Clang 9!

![Holy Clang Smoke](https://media.giphy.com/media/TYfZuDl9tz3zy/giphy.gif)

**Comment by danimtb** [comment]
We have added the new configuration and we will need to regenerate the packages already merged. We will report here

**Comment by uilianries** [comment]
Great! Gracias!

**Comment by lasote** [comment]
Still, pending infra and package regeneration only merged code to be prepared.

**Comment by danimtb** [comment]
After the issues described in #503, finally, the clang 9 packages for the merged recipes are now available in the central repo. The new configuration has been activated in PRs so now packages for Linux Clang 9 will be generated automatically

**Comment by uilianries** [comment]
![Finally](https://media.giphy.com/media/BQAk13taTaKYw/giphy.gif)

Thanks everyone!

**Comment by Croydon** [comment]
Please update the wiki page

Great job!

**Comment by danimtb** [comment]
Wiki updated! Thanks for the reminder @Croydon
