### ISSUE TITLE
[package] ninja/1.10.0: failed to install from source

### ISSUE THREAD

**Issue by munkhong** [conan-io/conan-center-index#2110]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ninja/1.10.0**
  * Operating System+version: **SUSE Linux Enterprise Server 12 SP3 **
  * Compiler+version: **GCC 8**
  * Docker image: **N/A**
  * Conan version: **conan 1.27.0**
  * Python version: **Python 3.7.3**
 

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.version=8.2
os=Linux
os_build=Linux
compiler.libcxx=libstdc++11
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-8
CXX=/usr/bin/g++-8
```
 

### Steps to reproduce (Include if Applicable)
conanfile.py requires ninja/1.10.0
conan install conanfile.py -b=missing

The same setup for ninja 1.9.0 works fine

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Installing (downloading, building) binaries...

ninja/1.10.0: Copying sources to build folder
ninja/1.10.0: Building your package in <mypath>
ninja/1.10.0: Generator cmake created conanbuildinfo.cmake
ninja/1.10.0: Calling build()
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Compiler GCC>=5, checking major version 8.2
-- Conan: Checking correct version: 8.2
-- Conan: C++ stdlib: libstdc++11
-- IPO / LTO enabled
-- Configuring done
-- Generating done
CMake Warning:

  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR


-- Build files have been written to: <my_path>
make[2]: *** No rule to make target 'src/lexer.in.cc', needed by 'lexer.cc'.  Stop.
CMakeFiles/Makefile2:124: recipe for target 'source_subfolder/CMakeFiles/libninja-re2c.dir/all' failed
make[1]: *** [source_subfolder/CMakeFiles/libninja-re2c.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target libninja
[ 17%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/build_log.cc.o
[ 28%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/clean.cc.o
[ 28%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/clparser.cc.o
[ 28%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/build.cc.o
[ 28%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/dyndep_parser.cc.o
[ 28%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/debug_flags.cc.o
[ 28%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/dyndep.cc.o
[ 28%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/deps_log.cc.o
[ 32%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/disk_interface.cc.o
[ 39%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/edit_distance.cc.o
[ 39%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/eval_env.cc.o
[ 42%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/graph.cc.o
[ 46%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/graphviz.cc.o
[ 53%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/line_printer.cc.o
[ 53%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/manifest_parser.cc.o
[ 57%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/metrics.cc.o
[ 60%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/parser.cc.o
[ 64%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/state.cc.o
[ 71%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/string_piece_util.cc.o
[ 71%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/util.cc.o
[ 75%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/version.cc.o
[ 78%] Building CXX object source_subfolder/CMakeFiles/libninja.dir/src/subprocess-posix.cc.o
[ 78%] Built target libninja
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
ninja/1.10.0:
```
</details>

**Comment by iangodin** [comment]
I am having the same problem, and have not found a workaround.
The build system is looking for 'src/lexer.in.cc', which is in fact in 'source_folder/src/lexer.in.cc'.
But I am too new at conan to have a fix or workaround for this.

**Comment by munkhong** [comment]
FWIW, I encountered this due to meson updated their dependency to ninja 1.10.x couple weeks ago. My current work around is to force my revision of meson to a version that still uses the previous version of conanfile.py which still uses ninja 1.9.x.

**Comment by iangodin** [comment]
Thanks for the quick response!  I did try that, but the oldest version of meson found by conan is meson 0.51.2, which still requires ninja 1.10.  Perhaps you had an older meson version in your cache? This is my first "real" project using conan... so no luck there.
Which version of meson did you end up using?  Perhaps if I blindly put in an older meson version, conan will still find it, even if it doesn't list it when I search.

**Comment by munkhong** [comment]
I'm using "meson/0.52.0#ddcdac2e4af170727130b5c08ac8e091"

bintray: https://bintray.com/conan/conan-center/meson%3A_/0.52.0%3A_#files/_/meson/0.52.0/_/ddcdac2e4af170727130b5c08ac8e091

Note that conanfile.py for this revision would still have ninja 1.9.x dependency
https://bintray.com/conan/conan-center/download_file?file_path=_%2Fmeson%2F0.52.0%2F_%2Fddcdac2e4af170727130b5c08ac8e091%2Fexport%2Fconanfile.py

**Comment by iangodin** [comment]
I was unable to force conan to use that version of meson everywhere (likely I don't understand conan well enough).
However, I was able to work around the problem: uninstall or remove re2c, and ninja can build correctly (it uses the premade lexer.cc file in that case).
So to reproduce this problem, you need to have re2c installed.
This may be a problem with the upstream ninja 1.10.0 package, I have not tried building it outside of conan.
But at least, I can move on and continue now!

**Comment by perseoGI** [comment]
Hi there!
I'm closing this very old issue as `ninja/1.10.0` is no longer supported by CCI and this issue has been resolved.
Happy coding 🐸
