### ISSUE TITLE
[package] Zlib/1.2.11: Cross compiling android on osx fails after #2081 was merged.

### ISSUE THREAD

**Issue by Timen** [conan-io/conan-center-index#2113]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.11**
  * Operating System+version: **OSX Catalina**
  * Compiler+version: **Clang**

Cross compiling zlib for android from osx seems to have broken since #2081 went in yesterday. I'm not exactly sure why this is the case, but it seems the path for the XCode 12 fix does not get resolved correctly.

The following error is thrown:
  | zlib/1.2.11: Copying sources to build folder
  | zlib/1.2.11: Building your package in /Users/builder/.conan/data/zlib/1.2.11/_/_/build/98884c274d9eed68f50d292208009c6b826cd612
  | zlib/1.2.11: Generator cmake created conanbuildinfo.cmake
  | zlib/1.2.11: Calling build()
  | zlib/1.2.11:
  | zlib/1.2.11: ERROR: Package '98884c274d9eed68f50d292208009c6b826cd612' build failed
  | zlib/1.2.11: WARN: Build folder /Users/builder/.conan/data/zlib/1.2.11/_/_/build/98884c274d9eed68f50d292208009c6b826cd612
  | ERROR: zlib/1.2.11: Error in build() method, line 40
  | self._build_zlib()
  | while calling '_build_zlib', line 84
  | tools.patch(**patch)
  | FileNotFoundError: [Errno 2] No such file or directory: 'patches/0001-gzguts-xcode12-compile-fix.patch'

**Comment by danimtb** [comment]
cc/ @timblechmann

**Comment by uilianries** [comment]
@Timen did you update your local copy? Seems like the patch file is not in your local cache.

**Comment by SSE4** [comment]
unfortunately, this doesn't reproduce for me, running `conan install zlib/1.2.11@ -pr android --build missing` shows no errors, a profile is:
```
➜  ~ conan profile show android
Configuration for profile android:

[settings]
os=Android
os_build=Macos
arch=armv7
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
os.api_level=21
[options]
[build_requires]
*: android_ndk_installer/r19c@bincrafters/stable
[env]
```

@Timen please try to run `conan remove "zlib*" -f`, then try to install it again. probably, something was corrupted in your local cache (probably, it might happen if you have edited some files manually, or download/install was interrupted).

[android_zlib.txt](https://github.com/conan-io/conan-center-index/files/4878489/android_zlib.txt)
