### ISSUE TITLE
Conan download the cpprestsdk with a different package ID.

### ISSUE THREAD

**Issue by JamieLuo** [conan-io/conan-center-index#21145]
Hi,

My project was using the conan to download the dependencies, at first everything is ok with conan. But few days ago, my project has got a compile issue that caused by the dependencies. The problem is the conan downloaded the cpprestsdk with a different package ID from the conancenter compare with the old one.

I just want to know is there any way to specify the package revision when download the dependencies from remote, so I don't need to worry about the changes in the remote server.

My conan is 1.47.
cpprestsdk is 2.10.18
the old package id is 93d6dfb11d488385466d54ff3d5a25ee606fbd62 ( still exists? )
the current one is c53ef8905fb7e9822e7b7b274a4200ef6b0a6f03

Thanks!

**Comment by RubenRBS** [comment]
Hi @JamieLuo thanks a lot for your question.

You have a few ways to ensure future reproducibility of your builds/ensuring the same revision of the _recipe_ is used every time, and those are mostly listed on https://docs.conan.io/2/devops/using_conancenter.html - The three major ways would be to [use lockfiles](https://docs.conan.io/2/tutorial/versioning/lockfiles.html#tutorial-versioning-lockfiles), [pin up to the recipe revision in your requirement](https://docs.conan.io/2/tutorial/consuming_packages/intro_to_versioning.html#revisions) (Probably the easiest and fastest to implement), or [forking CCI and host only the binaries you're interested in yourself](https://docs.conan.io/2/devops/conancenter/hosting_binaries.html)

**Comment by JamieLuo** [comment]
Hi @RubenRBS, thanks for your quick reply.

I tried to pin up the recipe revision for the cpprestsdk in the conan file.
[requires]
boost/1.80.0 
cpprestsdk/2.10.18            ->        cpprestsdk/2.10.18#93d6dfb11d488385466d54ff3d5a25ee606fbd62

 And when downloading from the conan center it has below logs:

> cpprestsdk/2.10.18: Downloaded recipe revision 93d6dfb11d488385466d54ff3d5a25ee606fbd62
> openssl/1.1.1s: Not found in local cache, looking in remotes...
> openssl/1.1.1s: Trying with 'conancenter'...
> Downloading conanmanifest.txt
> Downloading conanfile.py

But looks like it did not get the revision as I expected and still downloaded a latest revision.

> cpprestsdk/2.10.18: Package installed c53ef8905fb7e9822e7b7b274a4200ef6b0a6f03
> cpprestsdk/2.10.18: Downloaded package revision 0

Do you know why? or just my pinning is not correct. Thanks. : )

**Comment by AbrilRBS** [comment]
Sorry for the lack of response, this should have not happened.

If this is still an issue, `Downloaded package revision 0` seems to imply that Conan 1 is running without revisions, which has been discouraged for a long while now. Trying to use revisions might be the only approach that works (Conan 2 has them mandatory, as an upgrade hint towards it)

Again, sorry that this got no response back then, closing as stale for now, but if this is still an issue/the above tip does not help, please feel free to reopen/create new issues, we're happy to help :)
