### ISSUE TITLE
export pre-binary so file, can not skip rpath

### ISSUE THREAD

**Issue by siweilvxing** [conan-io/conan-center-index#21181]
### What is your question?

I have a third party library build output so file, so I use conan export-pkg export this library.
but when my cmake projects link this so, my binary RPATH have /root/.conan2/p/b/xxx.
in cmakelists.txt I set(CMAKE_SKIP_RPATH TRUE), but it doesn't work.
how can I remove .conan RPATH

**Comment by SpaceIm** [comment]
It doesn't seem related to conancenter. You should ask in https://github.com/conan-io/conan
