### ISSUE TITLE
grpc/1.54.3: Missing dependancy to systemd on Linux builds

### ISSUE THREAD

**Issue by ashley-b** [conan-io/conan-center-index#21253]
### Description

Linking to gRPC on Linux fails with missing symbols to systemd lib

My current workaround is to add systemd to my app which fixes the link error

### Package and Environment Details

* Package Name/Version: **grpc/1.54.3**
* Operating System+version: **Linux Fedora 39**
* Compiler+version: **`gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)`**
* Conan version: **Conan version 2.0.13**
* Python version: **Python 3.12.0**

### Conan profile

Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

### Steps to reproduce

Sample program to demonstrate error
```
git clone https://gist.github.com/ashley-b/6225252eefcb8d359448f352ec844678 test
cd test
conan install .
cmake --preset conan-release
cmake --build --preset conan-release
```

### Logs

<details><summary>Click to expand log</summary>
Output from `cmake --build --preset conan-release`

```
[ 50%] Building CXX object CMakeFiles/test.dir/test.cpp.o
[100%] Linking CXX executable test
/usr/bin/ld: .conan2/p/b/grpcdbe9182d7c00b/p/lib/libgrpc.a(systemd_utils.cc.o): in function `set_matching_sd_unix_fd(grpc_tcp_server*, grpc_resolved_address const*, int, int)':
systemd_utils.cc:(.text+0x5a): undefined reference to `sd_is_socket_unix'
/usr/bin/ld: .conan2/p/b/grpcdbe9182d7c00b/p/lib/libgrpc.a(systemd_utils.cc.o): in function `set_matching_sd_inet_fd(grpc_tcp_server*, grpc_resolved_address const*, int, int, int, int)':
systemd_utils.cc:(.text+0x14b): undefined reference to `sd_is_socket_inet'
/usr/bin/ld: systemd_utils.cc:(.text+0x169): undefined reference to `sd_is_socket_sockaddr'
/usr/bin/ld: .conan2/p/b/grpcdbe9182d7c00b/p/lib/libgrpc.a(systemd_utils.cc.o): in function `set_matching_sd_fds(grpc_tcp_server*, grpc_resolved_address const*, int)':
systemd_utils.cc:(.text+0x1de): undefined reference to `sd_listen_fds'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/test.dir/build.make:166: test] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

```

</details>

**Comment by Nekto89** [comment]
It looks like a bug in grpc recipe. I don't see any mention of systemd in it. I assume that build env of CCI had system libsystemd which was found during cmake generation.
https://github.com/grpc/grpc/blob/42284424acd2ba4ba649599984592f5d2eade919/CMakeLists.txt#L344C1-L347C8

**Comment by ashley-b** [comment]
@Nekto89 To clarify I can build the grpc/1.54.3 package and the test_package passes. It's only when I consume the package and when the final link occurs it fails.

The older version of grpc package's use to build, so am guessing gRPC has introduced systemd as a dependency at some stage

Also I did find this issue on the gRPC project to do with disabling systemd as a dependency, probably not related.
https://github.com/grpc/grpc/issues/34304

**Comment by AndreyMlashkin** [comment]
> @Nekto89 To clarify I can build the grpc/1.54.3 package and the test_package passes. It's only when I consume the package and when the final link occurs it fails.
> 
> The older version of grpc package's use to build, so am guessing gRPC has introduced systemd as a dependency at some stage
> 
> Also I did find this issue on the gRPC project to do with disabling systemd as a dependency, probably not related. [grpc/grpc#34304](https://github.com/grpc/grpc/issues/34304)

My PR fixes the problem for me. @ashley-b, could you also validate it? does updated grpc work for your purposes?

**Comment by ashley-b** [comment]
@AndreyMlashkin ive tried your PR #22436 and it does fix the issue.

**Comment by AndreyMlashkin** [comment]
You can close this one
