### ISSUE TITLE
pcl:with_qhull=True does not set HAVE_QHULL

### ISSUE THREAD

**Issue by DevlBert** [conan-io/conan-center-index#21290]
### What is your question?

Hi,

I've build pcl/1.13.1 with apple-clang 15.0 and pcl:with_qhull=True because I need pcl::ConcaveHull in my application. 
The absence of setting HAVE_QHULL prevents the include or linking with concave_hull.

My conanfile:
```
[requires]
    pcl/1.13.1

[generators]
    CMakeDeps
    CMakeToolchain
```
pcl:with_qhull is default True and it doesn't change if I add this to the options or not. 

In pcl_config.h.in:
`#cmakedefine HAVE_QHULL 1`

This should result in setting HAVE_QHULL in pcl_config.h, but:
`/* #undef HAVE_QHULL */`

Is there an option to set HAVE_QHULL?

**Comment by uilianries** [comment]
@DevlBert Thank for reporting the case, I'll take a look.
