### ISSUE TITLE
[package] libiconv/1.17: cross compilation doesn't create binary for desired host architecture

### ISSUE THREAD

**Issue by actondev** [conan-io/conan-center-index#21291]
### Description

Probably related issue: https://github.com/conan-io/conan-center-index/issues/19598
I'm having the exact issue of not being able to cross compile boost (arm -> x86_64), but I think I've narrowed it down to libiconv itself.
When compiling from build arch armv8 to host arch x86_64, the resulting `libiconv.a` library is compiled for arm.

Same process for `zlib/1.2.13` for example works (gives `libz.a` of architecture `x86_64`)

### Package and Environment Details

* Package Name/Version: **libiconv/1.17**
* Operating System+version: **MacOS Ventura 13.4.1**
* Compiler+version: **Apple clang version 14.0.3 (clang-1403.0.22.14.1)**
* Conan version: **conan 1.62.0**
* Python version: **Python 3.11.5**

### Conan profile

[settings]
os=Macos
os_build=Macos
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
compiler.cppstd=20
arch=x86_64
arch_build=armv8
build_type=Release

[env]
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

### Steps to reproduce

`conan install libiconv/1.17@ -pr ./macos-cross --build=missing -r conancenter`
Then inspecting the resutling .a file: `lipo -info [..]/lib/libiconv.a` gives

> Non-fat file: ./libiconv.a is architecture: arm64

### Logs

Attaching the `conan install libiconv/1.17@ -pr ./macos-cross --build=missing -r conancenter` complete log (reached the maximum char limit the the issue body)
[libiconv.log](https://github.com/conan-io/conan-center-index/files/13425101/libiconv.log)

**Comment by SpaceIm** [comment]
Cross compilation doesn't work like this anymore in conan. It may work incidentally for CMake based project but you shouldn't do that.
You have to use 2 profiles.

**Comment by SpaceIm** [comment]
See https://docs.conan.io/1/systems_cross_building/cross_building.html

**Comment by actondev** [comment]
Oh 🤦‍♂️ Thanks for the tip. Managed to install both libiconv & boost by using 2 profiles. For anyone interested:

build profile
```
[settings]
os=Macos
os_build=Macos
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
compiler.cppstd=20
arch=armv8
arch_build=armv8
build_type=Release

[env]
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

host profile
```
[settings]
os=Macos
os_build=Macos
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
compiler.cppstd=20
arch=x86_64
arch_build=armv8
build_type=Release

[env]
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```
`conan install libiconv/1.17@ -pr:b macos-cross-build -pr:h macos-cross-host`

**Comment by SpaceIm** [comment]
env is deprecated and not listened at all by helpers used in libiconv recipe. Use appropriate conf instead.
