### ISSUE TITLE
[service] Missing binary: libavif/1.0.2:c8ed2051db207a3f625eb5758398efaa74796bd7

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#21326]
### What is your problem/feature request?

My PR cannot be built because of missing `libavif` packages, see https://github.com/conan-io/conan-center-index/pull/20788

FYI `libavif` has been recently updated in https://github.com/conan-io/conan-center-index/pull/21220

**Comment by uilianries** [comment]
I just started a new CI build to generate libavif. The build result should be available at https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/prod-v2/TapaholesRepo/192/summary.json as soon the job finishes.

**Comment by uilianries** [comment]
Done. I restart the CI build for the PR #20788 now.
