### ISSUE TITLE
[service] License check is stuck

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#21321]
### What is your problem/feature request?

Hi! The license check node is stuck: https://github.com/conan-io/conan-center-index/pull/21220 Could you please restart the PR possibly by merging the master branch (and look into the issue)?

**Comment by uilianries** [comment]
@HappySeaFox Thank you for reporting. Unfortunately, the CLA assistant fails to run from time to time, but is not one of Conan services, but an external bot:

https://cla-assistant.io/

But we still can re-run bot, actually, anyone is able to do it, just need to open the cla page (actually is a http get, so could be a curl command too):

https://cla-assistant.io/check/conan-io/conan-center-index?pullRequest=21220

The PR number can be changed.

**Comment by uilianries** [comment]
I just executed the cla bot again and is working. The PR is now ready to be merged. Thank you.
