### ISSUE TITLE
[service] Link to download sha256 tool for windows is broken

### ISSUE THREAD

**Issue by NelDav** [conan-io/conan-center-index#21345]
### Link to download sha256 tool for windows is broken 

In the documentation of `conandata.yml`, there is a part explaining the intend of the sha256 field. (https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conandata_yml_format.md#sha256)
In this chapter, there is a link named "windows" that forwards the user to a strange lottery page:

<details>
  <summary>Image of the website</summary>
  <img src="https://github.com/conan-io/conan-center-index/assets/34069438/d93c3a16-93a3-44c3-b6b1-6a43d43e68ae" alt="Image of the website"/>
</details>

**Comment by Nekto89** [comment]
cmake -E sha256sum "file" can also be used on all platforms

**Comment by uilianries** [comment]
@Nekto89 Thank you for your suggestion, I really didn't know about that cmake feature :nerd_face:

**Comment by NelDav** [comment]
That was very fast, thank you for taking care of this.
