### ISSUE TITLE
[service] Long paths can cause build failures on CI

### ISSUE THREAD

**Issue by p-podsiadly** [conan-io/conan-center-index#2140]
I've encountered this problem when working on OpenImageIO PR: https://github.com/conan-io/conan-center-index/pull/2017#issuecomment-653792903 and https://github.com/conan-io/conan-center-index/pull/2017#issuecomment-653818398

MS Build fails to compile objects with paths such as `C:/J/workspace/onan-center-pull-request_PR-2017/17/pr_2017_17_0_2/.conan/data/openimageio/2.1.17.0/_/_/build/bd228a38828943184ee89718c7a3cda89f5e789e/source_subfolder/src/libOpenImageIO/OpenImageIO.dir/RelWithDebInfo/__/cineon.imageio/libcineon/ElementReadStream.cpp.obj`

Could you shorten the path to `.conan/data/` directory?

**Comment by p-podsiadly** [comment]
Turns out there's already [`short_paths`](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#short-paths-reference) attribute for this purpose. I didn't know about.

**Comment by uilianries** [comment]
@p-podsiadly you can force short paths by env vars: https://docs.conan.io/en/latest/reference/env_vars.html#conan-use-always-short-paths
