### ISSUE TITLE
[package] sqlite3/all: how to use components to mimic findSQLite3 and imported target SQLite::SQLite3

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#2144]
According to CMake documentation https://cmake.org/cmake/help/v3.14/module/FindSQLite3.html:
- namespace of sqlite3 is `SQLite` (imported target is `SQLite::SQLite3`)
- we have to use `find_package(SQLite3)`

conan components doesn't seem to provide a way to handle this case.

**Comment by jgsogo** [comment]
This should be the last mile needed fo this transparent integration: https://github.com/conan-io/conan/issues/7254

And then something like
```
cpp_info.filename = `SQLite3`
cpp_info.names["cmake_find_package"] = `SQLite`
cpp_info.components["all"].names["cmake_find_package"] = `SQLite3`
```

**Comment by SpaceIm** [comment]
Nice.

Maybe https://github.com/conan-io/conan is a better place to discuss about this, but there are also recipes defining several imported targets without namespace, like if there was multiple distinct libraries. How to deal with that?

**Comment by jgsogo** [comment]
> * libraries defining several imported targets without namespace, like if there was multiple distinct libraries (SPIRV-Tools and SPIRV-Cross for example).

When you consume a library via `find_package(...)` I would say that you _always_ get the imported libraries inside a namespace. How are people usually _finding_ SPIRV out there? Is there any widely used `FindSPIRV.cmake` (without namespaces) that we can use as a reference?

> * libraries defining an official namespace and a deprecated one (PROJ for example)

IMO, this is like a project changing its name, we should focus on the new name and forget about the deprecated one. 

> * libraries having a common namespace in multiple distinct libraries (Vulkan ecosystem, Qt and Boost I guess if they were modularized).

Here it is an example: https://github.com/conan-io/conan/issues/7254#issuecomment-649715581, different packages providing targets in the same namespace

**Comment by SpaceIm** [comment]
For `SPIRV-Tools`, here a subpart of the 4 `LibTarget.cmake` files:

`SPIRV-ToolsTarget.cmake`
```cmake
...
# Create imported target SPIRV-Tools
add_library(SPIRV-Tools STATIC IMPORTED)

set_target_properties(SPIRV-Tools PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
...
```

`SPIRV-Tools-optTargets.cmake`
```cmake
...
# Create imported target SPIRV-Tools-opt
add_library(SPIRV-Tools-opt STATIC IMPORTED)

set_target_properties(SPIRV-Tools-opt PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SPIRV-Tools"
)
...
```

`SPIRV-Tools-linkTargets.cmake`
```cmake
...
# Create imported target SPIRV-Tools-link
add_library(SPIRV-Tools-link STATIC IMPORTED)

set_target_properties(SPIRV-Tools-link PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SPIRV-Tools-opt"
)
...
```

`SPIRV-Tools-reduceTarget.cmake`
```cmake
...
# Create imported target SPIRV-Tools-reduce
add_library(SPIRV-Tools-reduce STATIC IMPORTED)

set_target_properties(SPIRV-Tools-reduce PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SPIRV-Tools;SPIRV-Tools-opt"
)
...
```

**Comment by jgsogo** [comment]
I see. My personal opinion is that sometimes we need to be a little bit opinionated and try to force some changes when there is an outlier. I don't know if this library is one of those cases or we need to add an exception to the hook because this is an exception but everyone expects (and wants) to consume it that way.

**Comment by SpaceIm** [comment]
This issue can be closed, sqlite3 recipe now properly mimics official sqlite3 imported target and module filename.
