### ISSUE TITLE
[service] Create toc for build logs of a recipe

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#2145]
When the CI builds all packages for a recipe, it stores the logs in subdirectories names after its hash.
e.g. the build logs of libevent at https://c3i.jfrog.io/c3i/misc/logs/pr/2142/3/libevent/2.1.12/

When I want to check the log of a build created with e.g. MSVC, I have to look in multiple directories.

I think it would be useful to create a toc file in the test root directory that contains the profile of all combinations.

I don't think it matters much whether this file is a yml or a html.
As long as it is possible to do a CTRL+F.

**Comment by jgsogo** [comment]
I would like the report from CCI to be something like this:

----

Summary of build N (`commit - sha`):

... something smart and useful here ...


<details><summary>Details</summary>
<p>

Take this as [HTML]() and open locally to run filters,...

| os      | arch   | compiler      | compiler.version | ... | profile | stdout | result  |
|---------|--------|---------------|------------------|-----|---------|--------|---------|
| Windows | x86_64 | Visual Studio | 16               |     | [link]()  | [link]() | SUCCESS |
| Windows | x86_64 | Visual Studio | 15               |     | [link]()  |        | NOT RUN |
| Macos   | x86_64 | apple-clang   | 11.0             |     | [link]()  | [link]() | FAILURE |
| ...   | ... | ...   | ...             |     | ...  | ... | ... |

(this is potentially a long table)

</p>
</details>

**Comment by jgsogo** [comment]
To keep the hype high: internally, we are starting to generate a JSON file with the information from all the builds, and reporting more structured information (more columns will be shown, of course, and links to the profile and logs):

![image](https://user-images.githubusercontent.com/1406456/93308942-35d58f00-f803-11ea-85b3-d73babb93d0a.png)

Now we are focused on other functionalities, but as soon as you start helping us with the reviews 😄  we will have more time to implement other features in the CI.

**Comment by madebr** [comment]
@jgsogo @danimtb 
Is there an update on this?
This would help https://github.com/conan-io/conan-center-index/pull/3148#issuecomment-706224419

**Comment by danimtb** [comment]
We are still working on different issues to improve the general work of the pipeline and to extract information from packages to improve https://conan.io/center. We are still not using such report outputs in the job that builds the PRs but we already have the plans to make the swift soon. We will continue updating, thanks!
