### ISSUE TITLE
[bug] cpython/3.10.0 unable to install due to conflict in libuuid

### ISSUE THREAD

**Issue by MaxKarel** [conan-io/conan-center-index#21501]
### Environment details

* Operating System+version: Ubuntu 20
* Compiler+version: gcc 9
* Conan version: 1.59.0
* Python version: Python 3.8.10

### Steps to reproduce

conan install cpython/3.10.0@

### Logs

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7.5
cuda=v11.7
os=Linux
os.distro=Ubuntu-20
os_build=Linux
[options]
[build_requires]
[env]

WARN: tcl/8.6.10: requirement zlib/[>=1.2.11 <2] overridden by tk/8.6.10 to zlib/1.2.13 
WARN: fontconfig/2.13.93: requirement expat/2.5.0 overridden by tk/8.6.10 to expat/2.4.1 
WARN: freetype/2.13.2: requirement zlib/[>=1.2.10 <2] overridden by fontconfig/2.13.93 to zlib/1.2.13 
WARN: libpng/1.6.40: requirement zlib/[>=1.2.11 <2] overridden by freetype/2.13.2 to zlib/1.2.13 
ERROR: At least two recipes provides the same functionality:
 - 'libuuid' provided by 'libuuid/1.0.3', 'util-linux-libuuid/2.39.2'

```

**Comment by Ahajha** [comment]
The Conan 2.0 migration should (hopefully) be done soon, so I think we could close the 1.x deps update PR, and just wait for the 2.0 migration to be merged.

Thoughts, anyone?

**Comment by MaxKarel** [comment]
Thanks @Ahajha I was able to use the partial fix from your PR https://github.com/conan-io/conan-center-index/pull/21426 as a temporary solution. So we can close this
