### ISSUE TITLE
[package] libselinux/3.0: libselinux misses gettid symbol

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#2150]
When linking a program that requires libselinux, the following error is printed:
```
/usr/bin/ld: /home/maarten/.conan/data/libselinux/3.0/_/_/package/6b0384e3aaa343ede5d2bd125e37a0198206de42/lib/libselinux.a(procattr.o): in function `openattr':
procattr.c:(.text+0x123): undefined reference to `gettid'
collect2: error: ld returned 1 exit status
```

`libselinux` is an option for `dpkg`.
I will open a pr adding its recipe soon :crossed_fingers: 

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libselinux/3.0**
  * Operating System+version: **Fedora Linux 30**
  * Compiler+version: **GCC 9.3.1**
  * Conan version: **conan 1.26.1**
  * Python version: **Python 3.7.7**

### Conan profile
```
[settings]
os=Linux
arch=x86_64
os_build=Linux
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Build dpkg as `conan create dpkg/1.20.4@`

### Extra

the manual of `gettid` contains the following:

```
Glibc does not provide a wrapper for this system call; call it using syscall(2).
```

/cc @ericLemanissier

**Comment by ericLemanissier** [comment]
isn't this a case of different libc used for compiling libselinux vs consuming libselinux ?

**Comment by madebr** [comment]
Yup!
```
The gettid() system call first appeared on Linux in kernel 2.4.11.
       Library support was added in glibc 2.30.  (Earlier glibc versions did
       not provide a wrapper for this system call, necessitating the use of
       syscall(2).)
```
