### ISSUE TITLE
[question] raylib 4.0.0 cannot be built

### ISSUE THREAD

**Issue by robiarth** [conan-io/conan-center-index#21523]
### What is your question?

Hi, i'm trying to compile a simple test project with raylib on windows with Conan 2.0, and I have some problems with the build

Here is my error :
[build error raylib.txt](https://github.com/conan-io/conan-center-index/files/13515477/build.error.raylib.txt)

Do you have any solution ?

**Comment by SpaceIm** [comment]
Try https://github.com/conan-io/conan-center-index/pull/21524
