### ISSUE TITLE
[package] libpqxx/7.8.1:  broken because of untested OpenSSL upgrade

### ISSUE THREAD

**Issue by Enhex** [conan-io/conan-center-index#21547]
### Description

when trying to construct `pqxx::connection` the following error happens:
"no PostgreSQL user name specified in startup packet" from `pqxx::connection::complete_init()`.
this happens with the recent OpenSSL 3.2.0, but not with the previous version 3.1.4.

`libpqxx` depends on `libpq` which automatically uses the latest OpenSSL version without testing if it works:
https://github.com/conan-io/conan-center-index/blob/master/recipes/libpq/all/conanfile.py#L71

### Package and Environment Details

* Package Name/Version: **libpqxx/7.8.1**
* Operating System+version: **Linux Manjaro**
* Compiler+version: **GCC 13.2.1**
* Conan version: **conan 1.62.0**
* Python version: **Python 3.11.6**

### Conan profile

[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=13.2
compiler.libcxx=libstdc++11
compiler.cppstd=20
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

try to connect to a database with `pqxx::connection`

### Logs

N/A

**Comment by Cogitri** [comment]
Sorry for the breakage, I've just submitted a PR which should fix this.
