### ISSUE TITLE
Build Issue with Boost 1.76.0 on Conan 2.0

### ISSUE THREAD

**Issue by mouscar** [conan-io/conan-center-index#21624]
### What is your problem/feature request?

I am currently facing issues while building the Boost version 1.76.0 package with Conan 2.0. The error I am encountering is as follows: 
boost/1.76.0: ERROR:
Package '2e3dc882beff57104175b58a8ae52ee371906e30' build failed
boost/1.76.0: WARN: Build folder C:\Users\ABOUBACAR\.conan2\p\b\boostec535f438279c\b\build-release
*********************************************************
Recipe 'boost/1.76.0' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: boost/1.76.0: Error in build() method, line 887
        self.run(full_command)
        ConanException: Error 1 while executing

**Comment by SpaceIm** [comment]
There is no information in your bug report which could indicate what's wrong. Please follow https://github.com/conan-io/conan-center-index/issues/new?assignees=&labels=bug&projects=&template=package_bug.yml&title=%5Bpackage%5D+%3CLIBRARY-NAME%3E%2F%3CLIBRARY-VERSION%3E%3A+SHORT+DESCRIPTION

**Comment by uilianries** [comment]
Closing this issue due missing information to track the bug.

Please, feel free re-open it in case having more information to be shared.
