### ISSUE TITLE
[package] boost/1.73.0 missing patches

### ISSUE THREAD

**Issue by mgranville** [conan-io/conan-center-index#2163]
### Package Details
  * Package Name/Version: **boost/1.73.0**
  * Changelog: **https://www.boost.org/users/history/version_1_73_0.html**

This package already exists as a recipe, but the following two patches from the changelog are not included:
https://www.boost.org/patches/1_73_0/0001-outcome-assert.patch
https://www.boost.org/patches/1_73_0/0002-beast-coroutines.patch

**Comment by prince-chrismc** [comment]
>Known Issues

>These are patches from library authors which were found too late to be fixed in the release. Be careful as they have not been through the normal testing process. 

I am not sure the patches are required :thinking:

**Comment by Croydon** [comment]
> I am not sure the patches are required 🤔

I agree. As package maintainers we should only fix critical bugs, e.g. when they prevent building. We are not responsible of fixing regular upstream bugs.

If those patches aren't even tested with the regular upstream process that is another red flag.

**Comment by mgranville** [comment]
This does prevent building with boost beast on GCC 10.1. See e.g.

https://github.com/boostorg/beast/issues/1993
https://github.com/boostorg/beast/issues/1968
https://github.com/boostorg/beast/issues/1925
https://github.com/boostorg/beast/issues/1916

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/pull/16930#issuecomment-1499943541
