### ISSUE TITLE
Package: Improvement of recipe for OpenSSL - Addition of custom default OPENSSL_TLS_SECURITY_LEVEL

### ISSUE THREAD

**Issue by jmalopoy** [conan-io/conan-center-index#21707]
Latest releases of OpenSSL have modified what ciphers are assigned to the security level 0 ("X509 certificates signed using SHA1 are no longer allowed at security level 1 and above" in v3.0 [https://www.openssl.org/news/cl30.txt](https://www.openssl.org/news/cl30.txt) ) and the default security level defined at build time ("The default SSL/TLS security level has been changed from 1 to 2." in v3.2 [https://www.openssl.org/news/cl32.txt](https://www.openssl.org/news/cl32.txt) ).
Unfortunately not everybody is able to upgrade / adapt to such security enhancements so it would be great if the current recipe provides a setting to set / relax the default security level of the library.

**Comment by Croydon** [comment]
#21708 is merged, can be closed

**Comment by czoido** [comment]
Closing this as looks fixed, please feel free to reopen if you have more issues.
