### ISSUE TITLE
[question] Inconsistent usage of versions

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan-center-index#21710]
### What is your question?

Hi,

I noticed that dependencies of recipes are updated in isolation without doing this consistently across conan-center-index.
This leads to version conflicts if I want to fork this repo and build the projects I need.

Example: 
libarchive uses version 5.4.4 of xz_utils
https://github.com/conan-io/conan-center-index/blob/262eec05f634fe235d75f9b22d434bbe3869a13b/recipes/libarchive/all/conanfile.py#L106

elfutils uses version 5.4.5 of xz_utils
https://github.com/conan-io/conan-center-index/blob/262eec05f634fe235d75f9b22d434bbe3869a13b/recipes/elfutils/all/conanfile.py#L76

The moment I use both in the same dependency tree, I have to adjust versions myself.
This creates a lot of effort to consume recipes, as this is just an example.

Can the versions be updated consistently across conan-center-index?

**Comment by uilianries** [comment]
@tbsuht Indeed packages are updated in separated PRs, and may result in version conflicts.

https://docs.conan.io/2/tutorial/versioning/conflicts.html

Currently, there is the PR https://github.com/conan-io/conan-center-index/pull/21711 to fix it.

Thank you for reporting.

**Comment by tbsuht** [comment]
This was more a general question, not about reporting a single problem.

How to handle this? If I fork conan-center and will run into version conflicts ... that is not very easy to handle.

What about updating dependencies consistently?

**Comment by SpaceIm** [comment]
Long term solution is to use version range in all requirements.

**Comment by uilianries** [comment]
@tbsuht Please, read https://github.com/conan-io/conan-center-index/blob/master/docs/consuming_recipes.md

**Comment by tbsuht** [comment]
> @tbsuht Please, read https://github.com/conan-io/conan-center-index/blob/master/docs/consuming_recipes.md

I don't see how this is related to my question.

Yes, I'm isolating myself from upstream changes via a fork and a local artifactory. This will not help for the problem described as the situation is introduced once I pull from upstream.
Yes, there will be (breaking) changes in recipes. The question is whether they are done consistently (I'm only talking about dependency relationships) across conan-center or in isolation for a single recipe.


> Long term solution is to use version range in all requirements, but currently conancenter allows version range when requirement is zlib, openssl, cmake or libcurl.

Ok, seems promising. But what about short to mid-term?

**Comment by SpaceIm** [comment]
What you can do is to override versions in case of conflict in your conanfile, and lock that.
