### ISSUE TITLE
[request] gtlab-logging/4.4.1

### ISSUE THREAD

**Issue by rainman110** [conan-io/conan-center-index#21739]
### Package Name/Version

gtlab-logging/4.4.1

### Webpage

https://github.com/dlr-gtlab/gt-logging

### Source code

https://github.com/dlr-gtlab/gt-logging

### Description of the library/tool

A simple logging library based on Qslog with optional Qt support.

**Comment by uilianries** [comment]
@rainman110 The `gtlab-logging` project is now available in Conan Center and can be installed:

```
$ conan search -r conancenter gtlab-logging                                                                                                                                                                                       
Found 1 pkg/version recipes matching gtlab-logging in conancenter
conancenter
  gtlab-logging
    gtlab-logging/4.4.1

$ conan install -r conancenter --requires=gtlab-logging/4.4.1 --build=missing
```

Soon, it should be available on https://conan.io/center too.

**Comment by rainman110** [comment]
@uilianries Thank you so much ! :)
