### ISSUE TITLE
[package] ninja/1.11.1: the package cannot be built within conan-2.0.14

### ISSUE THREAD

**Issue by dpronin** [conan-io/conan-center-index#21741]
### Description

ninja/1.11.1 package cannot be built with conan-2.0.14 due to absence of build_type setting, although it is provided via command line within `conan install` call

### Package and Environment Details

* Package Name/Version: **ninja/1.11.1**
* Operating System+version: **Gentoo Linux**
* Compiler+version: **GCC 13**
* Conan version: **conan 2.0.14**
* Python version: **Python 3.11.6**

### Conan profile

[settings]
arch=x86_64
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

[buildenv]
CXX=g++
CC=gcc

### Steps to reproduce

```
conan install -s build_type=Debug -pr clang --build=missing -o with_cairo=True -s ninja:build_type=Release -of out/native/clang/release --update .
```

option **with_cairo** enables libcairo as a dependency that entails, in its turn, as a dependency ninja, that fails to be configured with cmake due to absence of build_type setting

### Logs

<details><summary>Click to expand log</summary>

```
ninja/1.11.1: Running CMake.build()
ninja/1.11.1: ERROR: 
Package '63fead0844576fc02943e16909f08fcdddd6f44b' build failed
ninja/1.11.1: WARN: Build folder /home/dpronin/.conan2/p/b/ninjaaae2e8355e295/b/build/None
*********************************************************
Recipe 'ninja/1.11.1' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: ninja/1.11.1: Error in build() method, line 41
  cmake.build()
  ConanException: build_type setting should be defined.
```

</details>

**Comment by SpaceIm** [comment]
You need a build_type in your profile, it's not optional.

**Comment by dpronin** [comment]
@SpaceIm thanks, I am closing the issue
