### ISSUE TITLE
[conan.io/center] Invalid github repo link

### ISSUE THREAD

**Issue by sersoftin** [conan-io/conan-center-index#21742]
### What is your problem/feature request?

Conan center link: https://conan.io/center/recipes/kangaru?version=4.3.1
In Recipe info, home located to https://github.com/gracicot/kangaru/wiki instead of https://github.com/gracicot/kangaru

**Comment by Croydon** [comment]
I don't consider this an error. The info should link to some kind of homepage. Many projects don't have an own website, so we oftentimes link to their repository, but the wiki can be used as a landing page too, so it is fine.

Issue can probably be closed.

**Comment by AbrilRBS** [comment]
I agree with @Croydon, thanks for the report, but I don't think changing the URL deserves a new recipe revision, and there does not seem to be extra necessary changes needed for it either

Either way, thanks for taking the time to report it and thanks for the response Croydon!
