### ISSUE TITLE
[package] libxslt/1.1.34: Build failed configure: error: Could not find libxml2 anywhere.

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan-center-index#2181]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libxslt/1.1.34**
  * Operating System+version: **Linux OpenSUSE Leap 42.3  Docker**
  * Compiler+version: **GCC 8**
  * Conan version: **conan 1.27.0**
  * Python version: **Python 3.8.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
checking for xml2-config... /opt/conan/.conan/data/libxml2/2.9.10/_/_/package/ec0397574a2fd7fb24fd216e1ac0e4bac5a67812/bin/xml2-config
checking for LIBXML... no
/opt/conan/.conan/data/libxslt/1.1.34/_/_/build/e038b68eb396a494bdef03888a1211f29be9f31f/source_subfolder/configure: line 14833: --static: command not found
configure: error: Could not find libxml2 anywhere, check ftp://xmlsoft.org/.
libxslt/1.1.34:
libxslt/1.1.34: ERROR: Package 'e038b68eb396a494bdef03888a1211f29be9f31f' build failed
libxslt/1.1.34: WARN: Build folder /opt/conan/.conan/data/libxslt/1.1.34/_/_/build/e038b68eb396a494bdef03888a1211f29be9f31f
ERROR: libxslt/1.1.34: Error in build() method, line 58
        self._build_with_configure()
while calling '_build_with_configure', line 143
        env_build.configure(args=configure_args, build=build, configure_dir=self._full_source_subfolder)
        ConanException: Error 1 while executing
```

</details>

**Comment by dmn-star** [comment]
Bin folder doesn't exist /opt/conan/.conan/data/libxml2/2.9.10/_/_/package/ec0397574a2fd7fb24fd216e1ac0e4bac5a67812/**bin**/xml2-config

But _xml2-config_ can be found in /opt/conan/.conan/data/libxml2/2.9.10/_/_/package/ec0397574a2fd7fb24fd216e1ac0e4bac5a67812/xml2-config

**Comment by dmn-star** [comment]
From libxslt recipe
 xml_config = tools.unix_path(self.deps_cpp_info["libxml2"].rootpath) + "/**bin**/xml2-config"

**Comment by SSE4** [comment]
seems like should be easy enough to fix

**Comment by dmn-star** [comment]
I took a closer look at this. It is not the better way to set configure options --with-libxml-... in recipe directly?
    --with-libxml-prefix=...
    --with-libxml-include-prefix=...
    --with-libxml-libs-prefix=...
