### ISSUE TITLE
[question] How do boost targets work?

### ISSUE THREAD

**Issue by aaaaaaaaargh** [conan-io/conan-center-index#2200]
First things first, I'm very sorry for this rather silly question, but I've been running into the same issue over and over again when it comes to using the official boost packages found in conan center. I was looking for an answer, but couldn't find any for a while, so without further ado here is my simple example:

_conanfile.txt_
```
[requires]
boost/1.73.0

[generators]
cmake
```

__CmakeLists.txt__
```
project(Example)
# Stuff not important here
target_link_libaries(Example PUBLIC CONAN_PKG::boost)
```

Fair enough, this is working. However, how do I select only certain components here? What if I just wanted to use _boost_regex_ for example? Am I missing something? Also, what is being used here at all? From looking at the generated _conanbuildinfo.cmake_ it looks like all the libraries are being linked which is definitely not what anyone would want. So, in conclusion I think I am missing something here, maybe a __find_package__ directive i am not aware, but information about this is really hard to find.

As a side note, I do not want to use modular boost packages found in Bintray as these seem to be constantly outdated.

Thank you very much for you answers.

**Comment by uilianries** [comment]
Hi @aaaaaaaaargh 

It's not available yet for Boost, but it's under development: https://github.com/conan-io/conan-center-index/pull/2097

It's a big challenge actually, boost has many modules.

**Comment by uilianries** [comment]
Closing as it's available via [CMakeDeps](https://docs.conan.io/2/reference/tools/cmake/cmakedeps.html):

```cmake
find_package(Boost COMPONENTS regex REQUIRED)
...
target_link_libraries(${PROJECT_NAME} PRIVATE Boost::regex)
```

More examples: https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/test_package/CMakeLists.txt#L19
