### ISSUE TITLE
[request] cudatoolkit/11.6.0

### ISSUE THREAD

**Issue by rymut** [conan-io/conan-center-index#22083]
### Package Name/Version

cudatoolkit/11.6.0

### Webpage

https://developer.nvidia.com/cuda-toolkit

### Source code

N/A

### Description of the library/tool

CUDA Toolkit is quite important for deployment/development of NN/AI/CV solutions. When using, creating own forks for recipes is required due to conan not supporting/patching sources for CUDA.

Creation of package for CUDA Toolkit was possible since conan 1.x, but it required use of cmake undefined behavior (changing CMAKE_GENERATOR_TOOLSET during cmake run) of to work with visual studio generators - so contributing package was out of question.

Since conan 2.0 it is possible to skip relying on undefined behavior for CUDA Toolkit to work fine with all generators, so here is my package recipe for windows/linux: https://github.com/rymut/conan-center-index/tree/cudatoolkit/11.6.0

Discussion points:
- Why only CUDA Toolkit 11.6.0 - already had a package for it under Visual Studio, newer >=12 and older version <=10 of cuda have a bit different directory structure after extraction so adding it would only require changing copy locations,
- Recipe works on Visual Studio generator by passing setting `tools.cmake.cmaketoolchain:toolset_arch` to `f"x64,cuda={self.package_folder.replace(os.sep, '/')}")` - which is a bit of a hack since comma denotes cuda toolset and not arch.
- Recipe supports NVIDIA CUDA Deep Neural Network library (cuDNN) https://developer.nvidia.com/cudnn - not enabled by default, since it must be manually downloaded after registering & requesting library - pointing to location of archive is done by environment variable `CUDNN_PATH`.
- MSVC MSBuild CUDA x.y.props - to allow long link commands cmd is limited to about 8191 characters, but using "&&" with commands can overcome the issue in most cases - it really happens only if you link a lot of libraries in conan/1.x using long paths (`WriteLinesToFile` would be a future prof solution), 
- Adding CUDA to recipe require adding `tool_requires` for nvcc, and `requires` for CUDAToolkit libraries.
- Windows package have a 'legacy' installation layout due to cmake enable language commands using only legacy layout on Visual Studio generator, linux uses more 'modern' layout (msbuild extension can be patched to detect cuda toolkit layout and choose correct path for cmake).

Any suggestions are greatly appreciated.

**Comment by valgur** [comment]
A couple of thoughts:
* I would target CUDA 12 right away, if possible, as it has quite a few backwards incompatible changes in the project structure.
* The `cccl` package containing `cub` and `thrust` should be packaged separately.
* I would seriously consider splitting `nvcc-compiler` into a separate package to allow the compiler and runtime libraries to be kept separate. You can build quite a few CUDA projects without the runtime being installed at all and the compiler component is just a couple of hundred MB in size vs gigabytes for the CUDA toolkit as a whole.
* Does your package replace the standard `FindCUDAToolkit.cmake` with a custom version?
* It's not clear to me whether the licensing terms are acceptable for CCI.

**Comment by rymut** [comment]
> * I would target CUDA 12 right away, if possible, as it has quite a few backwards incompatible changes in the project structure.

No problem, I will leave 11.6 due to it being highest currently supported cuda on some VM on Azure platform.

> * The `cccl` package containing `cub` and `thrust` should be packaged separately.

Question about that since https://github.com/NVIDIA/cccl/discussions/520 thrust/cub/libcudacxx is packaged into single package - thrust/cub/libcudacxx repositories are being archived - so quesiton is: should I update thrust/cub/libcudacxx based on cccl repository or create new cccl package that implements thrust & cub?

> * I would seriously consider splitting `nvcc-compiler` into a separate package to allow the compiler and runtime libraries to be kept separate. You can build quite a few CUDA projects without the runtime being installed at all and the compiler component is just a couple of hundred MB in size vs gigabytes for the CUDA toolkit as a whole.

No problem, so every library will be separate package, but to create each package recipe would need to download CUDA x.y installer - to extract required files.

> * Does your package replace the standard `FindCUDAToolkit.cmake` with a custom version?

FindCUDAToolkit.cmake is replaced with components defined in `def package_info(self)`, user_toolchain is used to define CMake variables that are defined by CUDAToolkit - but cannot be declared directly in `package_info` - such as CMAKE_CUDA_ARCHITECTURES.

> * It's not clear to me whether the licensing terms are acceptable for CCI.

The main idea is to distribute only recipe without prebuild package, installation of CUDA requires accepting EULA - components (libraries) can be distributed, of course libraries build on top of CUDA can be freely distributed.

Having recipe, or even "dummy" recipe would allow to creation of package recipes that requires or supports CUDA (OpenCV comes to mind) that end-user would be able to easily recompile the library using recipe (`--build=missing`).

**Comment by jcar87** [comment]
We understand the need for this and we are working towards making something available.

However please be aware that we are unable to distribute CUDA Toolkit binaries from Conan Center, as per our understanding of the EULA, and will not accept any contribution that would imply Conan Center distributing these binaries.

The team is currently working towards a solution where binaries are not distributed by us, but at least a recipe is, and may be able to share this targeting early Q2 2024.

**Comment by jcar87** [comment]
> I would seriously consider splitting nvcc-compiler into a separate package to allow the compiler and runtime libraries to be kept separate. You can build quite a few CUDA projects without the runtime being installed at all and the compiler component is just a couple of hundred MB in size vs gigabytes for the CUDA toolkit as a whole.

The nvcc configuration file looks for the targets directory relative to the location of nvcc. Even if NVIDIA provides `nvcc` as a standalone downloadable package, all their reference implementations _do_ install all components in the same prefix. Installing libraries in other directories (which would be a consequence of how the Conan cache works), means that we would need to find alternative ways of letting the nvcc compiler where to find these libraries, which may be too much of a maintenance burden.


> Having recipe, or even "dummy" recipe would allow to creation of package recipes that requires or supports CUDA (OpenCV comes to mind) that end-user would be able to easily recompile the library using recipe (--build=missing).

If the cuda toolkit is installed at the system level in a standard location, for OpenCV passing the `with_cuda` option should result in a new package ID being required, and `--build=missing` should do the trick and still build the right thing without additional effort. We do lose the ability of CUDA being recorded as a Conan dependency in the package ID - but for the average user I believe this should be sufficient.

**Comment by rymut** [comment]
Thanks, I was expecting that PR will be closed due to Nvidia EULA.

I moved whole code from pull request https://github.com/conan-io/conan-center-index/pull/22173 to separate repository https://github.com/rymut/cuda-toolkit-conan-package where whole nvidia toolkit will be available as a separate packages. 

As for the overhead with different locations the metapackage cuda-toolkit used for `find_package(CUDAToolkit)` resolves the issue for me - the each package declare alias target "CUDA::xxxx` for component declared in CMake `FindCUDAToolkit.cmake`.

This way when I add `self.tool_requires("cuda-toolkit/12.3.1")` and `self.requires("cuda-runtime/12.3.1")` when `with_cuda` is used by OpenCV.

Any way closing the request and looking forward to Q2 2024.
