### ISSUE TITLE
[package] openal-soft/1.22.2 : Website down, no mirror, impossible to build libalsa

### ISSUE THREAD

**Issue by GDelevoye** [conan-io/conan-center-index#22150]
### Description

The website seems down from conan, but also in a web-browser, which makes it impossible to download the sources to build it from source. It's been more than a week now (see [this issue](https://github.com/kcat/openal-soft/issues/956) )

Think it's rather a problem for the library maintainers, but still posting here just in case the recipe can be fixed by someone else by mirroring the sources elsewhere. Think the software license allows it

Maybe also [the github releases](https://github.com/kcat/openal-soft/releases) can be used in case the first one doesn't work

### Package and Environment Details

* Package Name/Version: **openal-soft/1.22.2**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 12.3**
* Conan version: **conan 2.0.13**
* Python version: **Python 3.10.12**

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

### Steps to reproduce

Conan file

```
[requires]
spdlog/1.12.0
boost/1.82.0
lyra/1.5.1
nlohmann_json/3.10.2
imgui/cci.20230105+1.89.2.docking
sfml/2.6.0
entt/3.10.1
gtest/1.14.0
libudev/system

[generators]
CMakeDeps
CMakeToolchain
```

Then ran

```bash
conan install . --output-folder=build --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
```

### Logs

<details><summary>Click to expand log</summary>

```
Got : 

```console
openal-soft/1.22.2: Calling source() in /home/delevoye/.conan2/p/openaca3b552cbecd7/s/src
openal-soft/1.22.2: ERROR: Error downloading file https://openal-soft.org/openal-releases/openal-soft-1.22.2.tar.bz2: 'HTTPSConnectionPool(host='openal-soft.org', port=443): Max retries exceeded with url: /openal-releases/openal-soft-1.22.2.tar.bz2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efd699bb970>, 'Connection to openal-soft.org timed out. (connect timeout=30)'))'
openal-soft/1.22.2: Waiting 5 seconds to retry...
openal-soft/1.22.2: ERROR: Error downloading file https://openal-soft.org/openal-releases/openal-soft-1.22.2.tar.bz2: 'HTTPSConnectionPool(host='openal-soft.org', port=443): Max retries exceeded with url: /openal-releases/openal-soft-1.22.2.tar.bz2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efd699b9570>: Failed to establish a new connection: [Errno 113] No route to host'))'
openal-soft/1.22.2: Waiting 5 seconds to retry...
ERROR: openal-soft/1.22.2: Error in source() method, line 92
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        ConanException: Error downloading file https://openal-soft.org/openal-releases/openal-soft-1.22.2.tar.bz2: 'HTTPSConnectionPool(host='openal-soft.org', port=443): Max retries exceeded with url: /openal-releases/openal-soft-1.22.2.tar.bz2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efd699b8c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))'
```
```

</details>

**Comment by valgur** [comment]
I updated #21221 to use sources from GitHub.

**Comment by lprc** [comment]
Is there a quick workaround while waiting for the PR to be merged?

**Comment by Bobini1** [comment]
@lprc You can download the recipe from the PR and run `conan create` on it.

**Comment by lprc** [comment]
Nice, thank you, that worked. If anyone else needs it, here's what I've done:

```
git clone https://github.com/conan-io/conan-center-index.git
cd conan-center-index
git fetch origin pull/21221/head:pr21221
git switch pr21221
conan create recipes/openal-soft/all --version=1.22.2 --build=libalsa/1.2.10 --build=openal-soft/1.22.2
```
