### ISSUE TITLE
[onnxruntime] build fails if we override the nlohmann_json/protobuf/gsl version

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan-center-index#22153]
### Description

The cmake files of onnxruntime expect a given version of nlohmann_json/protobuf/gsl and fail to retrieve the configuration generated by conan if we change them.

### Package and Environment Details

* Conan version: **conan 2.0.16**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[replace_requires]
nlohmann_json/*: nlohmann_json/3.9.0

### Steps to reproduce

conan install --requires=onnxruntime/1.14.1

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by czoido** [comment]
Thanks a lot for opening the issue, I'm declaring this as fixed by https://github.com/conan-io/conan-center-index/pull/23409 but please feel free to reopen if you have any more questions.
