### ISSUE TITLE
[package] openexr: add components

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#2219]
OpenEXR exports two config files:

| Config file | Targets |
|-----------|---------|
| OpenEXRConfig.cmake | `OpenEXR::IlmImfConfig`, `OpenEXR::IlmImf`, `OpenEXR::IlmImfUtil` |
| IlmBaseConfig.cmake | `IlmBase::IlmBaseConfig`, `IlmBase::Half`, `IlmBase::Iex`, `IlmBase::IexMath`, `IlmBase::Imath`, `IlmBase::IlmThread` |

**Comment by perseoGI** [comment]
I there!
I'm closing this issue as this components were added time ago.
See https://github.com/conan-io/conan-center-index/blob/master/recipes/openexr/2.x/conanfile.py?plain=1#L157
