### ISSUE TITLE
Installing packages with arch=x86 and build_type=Debug results in error

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan-center-index#22213]
### What is your question?

I have been trying to install boost and gtest in x86 Debug version. Things were fine until last week but since today afternoon they seem to be broken. I even reinstalled conan 2 and created the profiles again but no go.

However it works when I use x86_64 Release version. Does it have anything to do with my default profile?

Below are the commands with errors:
`conan install --requires=boost/1.71.0 -s arch=x86 -s build_type=Debug -r conancenter -g CMakeDeps -of "C:\generated\Debug" -b missing` 

> ERROR: boost/1.71.0: Error in source() method, line 568
>         destination=self.source_folder, strip_root=True)
>         ConanException: sha256 signature failed for 'boost_1_71_0.tar.bz2' file.
>  Provided signature: d73a8da01e8bf8c7eda40b4c84915071a8c8a0df4a6734537ddde4a8580524ee
>  Computed signature: 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff

`conan install --requires=gtest/1.8.1 -s arch=x86 -s build_type=Debug -r conancenter -g CMakeDeps -of "C:\generated\Debug" -b missing`

> gtest/1.8.1: ERROR:
> Package '2de5ace1836506e2a5b2585bc50412299db76987' build failed
> gtest/1.8.1: WARN: Build folder C:\Users\z0049e7r\.conan2\p\b\gtest53fc5f52f5ec6\b\build
> *********************************************************
> Recipe 'gtest/1.8.1' cannot build its binary
> It is possible that this recipe is not Conan 2.0 ready
> If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
> If it is your recipe, check if it is updated to 2.0
> *********************************************************
> 
> ERROR: gtest/1.8.1: Error in build() method, line 135
>         cmake.configure()
>         ConanException: Error 1 while executing

My default profile is:

> [settings]
> arch=x86_64
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.version=193
> os=Windows

If I change it to the below, then it works but then I have problem building for release and x86-64(both Debug & Release)

> [settings]
> arch=x86
> build_type=Debug
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.version=193
> os=Windows

I have also created custom profile for 

> x86_Debug, x86_Release,x64_Debug adn x64_Release

 and provide it as a `-pr` argument but still don't seem to work :(

I am not sure if anything was updated on the conan center.

Any help is appreciated.

**Comment by memsharded** [comment]
> ERROR: boost/1.71.0: Error in source() method, line 568
destination=self.source_folder, strip_root=True)
ConanException: sha256 signature failed for 'boost_1_71_0.tar.bz2' file.
Provided signature: d73a8da01e8bf8c7eda40b4c84915071a8c8a0df4a6734537ddde4a8580524ee
Computed signature: 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff

This error seems problematic, it would mean that ``boost`` changed its published file, which would be unwanted.
I will ask for help for someone in the team to check it.

**Comment by uilianries** [comment]
I checked the checksum and it looks good:

```
% wget https://boostorg.jfrog.io/artifactory/main/release/1.71.0/source/boost_1_71_0.tar.bz2
--2024-01-09 11:38:29--  https://boostorg.jfrog.io/artifactory/main/release/1.71.0/source/boost_1_71_0.tar.bz2
Resolving boostorg.jfrog.io (boostorg.jfrog.io)... 100.64.1.12
Connecting to boostorg.jfrog.io (boostorg.jfrog.io)|100.64.1.12|:443... connected.
HTTP request sent, awaiting response... 302 
boost_1_71_0.tar.bz2                                                100%[===================================================================================================================================================================>]  95,49M  5,84MB/s    in 28s     

2024-01-09 11:38:58 (3,44 MB/s) - ‘boost_1_71_0.tar.bz2’ saved [100124647/100124647]
% sha256sum boost_1_71_0.tar.bz2 
d73a8da01e8bf8c7eda40b4c84915071a8c8a0df4a6734537ddde4a8580524ee  boost_1_71_0.tar.bz2
```

@sandybhat16 There is no distinction between x86 and x86_64 source files, both use the very same tar.bz2. I suspect your cache is corrupted, please, remove your boost packages, then try it again.

    conan remove -c boost/1.71.0

**Comment by sandybhat16** [comment]
Thank you @uilianries . Yes, that solved. Although I had done this multiple times yesterday. It worked today :)
