### ISSUE TITLE
[request] protobuf/3.25.1

### ISSUE THREAD

**Issue by fchucholowski** [conan-io/conan-center-index#22220]
### Package Name/Version

protobuf/3.25.1

### Changelog

https://github.com/protocolbuffers/protobuf/releases/tag/v25.1

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by Ahajha** [comment]
Should be fixed by https://github.com/conan-io/conan-center-index/pull/21622 (WIP but nearly done)

**Comment by jcar87** [comment]
This is now available as 4.25.3: https://github.com/conan-io/conan-center-index/pull/24154
(we use the C++ versioning)
