### ISSUE TITLE
[package] boost/1.83.0: Invalid setting 'intel' is not a valid 'settings.compiler' value

### ISSUE THREAD

**Issue by frogarian** [conan-io/conan-center-index#22222]
### Description

Building boost package for Neutrino using QCC Compiler fails due to a compiler check against 'intel'.
The following patch should fix this issue:

```diff
--- a/conanfile.py
+++ b/conanfile.py
@@ -1335,7 +1335,7 @@ class BoostConan(ConanFile):
             return str(self.settings.compiler)
         if self.settings.compiler == "sun-cc":
             return "sunpro"
-        if self.settings.compiler == "intel":
+        if self.settings.compiler == "intel-cc":
             return {
                 "Macos": "intel-darwin",
                 "Windows": "intel-win",
```

### Package and Environment Details

* Package Name/Version: **boost/1.81.0**
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **QCC 8**
* Conan version: **conan 2.0.14**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
os=Neutrino
os.version=7.1
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=qcc
compiler.version=8.3
compiler.libcxx=cxx
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install --requires boost/1.83.0 -b boost -b missing

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: boost/1.83.0: Error in build() method, line 872
        self._create_user_config_jam(self._boost_build_dir)
while calling '_create_user_config_jam', line 1217
        contents += f'\nusing "{self._toolset}" : {self._toolset_version} : '
while calling '_toolset', line 1338
        if self.settings.compiler == "intel":
        ConanException: Invalid setting 'intel' is not a valid 'settings.compiler' value.
Possible values are ['sun-cc', 'gcc', 'msvc', 'clang', 'apple-clang', 'intel-cc', 'qcc', 'mcst-lcc']
Read "http://docs.conan.io/2/knowledge/faq.html#error-invalid-setting"
```

</details>

**Comment by uilianries** [comment]
Thank you for reporting! 

![Conan the frogarian](https://media4.giphy.com/media/nkbHJf196TV7y/giphy.gif)

**Comment by alanb-sony** [comment]
@uilianries any progress on fixing this?

**Comment by uilianries** [comment]
@alanb-sony I just opened a PR fixing the situation: https://github.com/conan-io/conan-center-index/pull/24514 Sorry the delay.
