### ISSUE TITLE
[request] physx/4.1.2

### ISSUE THREAD

**Issue by zbendefy** [conan-io/conan-center-index#22273]
### Package Name/Version

physx/4.1.2

### Changelog

https://gameworksdocs.nvidia.com/PhysX/4.1/release_notes.html

### Context about the new update

Code is available on physx4 github repo, using the latest commit: https://github.com/NVIDIAGameWorks/PhysX/commits/4.1/

The latest version is: [4.1.2.29882248](https://github.com/NVIDIAGameWorks/PhysX/commit/c3d5537bdebd6f5cd82fcaf87474b838fe6fd5fa)

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by valgur** [comment]
@zbendefy Do you need v4.1.2, specifically, or would the latest v5.3.1 from https://github.com/NVIDIA-Omniverse/PhysX also work?

**Comment by zbendefy** [comment]
@valgur , Thanks yes 5.3.1 would also be good, probably even better.
