### ISSUE TITLE
[package] spdlog/1.6.1: embedded fmt conflicts with conan fmt 

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan-center-index#2228]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spdlog/1.6.1**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 2019**
  * Conan version: **conan 1.26.0**
  * Python version: **Python 3.7.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
* create a conan file with a requirement on fmt/7.0.1 and spdlog/1.6.1
* when building spdlog gets an error because it embeds fmt/6.2.1
* workaround is to use fmt/6.2.1

This one is admittedly a bit weird...it's really a library problem but it can potentially be fixed in the recipe. I guess the most you can hope for is that spdlog pulls in fmt/6.2.1 via a conan requirement, and then you get a nice error message from conan saying there's a conflict rather than trying to extract the real problem from the compilation errors.

**Comment by SpaceIm** [comment]
spdlog recipe has `SPDLOG_FMT_EXTERNAL ON`, so embeded one shouldn't be used.
spdlog >= 1.5.0 seems to require fmt 6.2.x : https://github.com/conan-io/conan-center-index/blob/8658ae021ce225d889fa4ee38d30cb80877a7c75/recipes/spdlog/all/conanfile.py#L51

Unfortunately, since CCI forbids version range, there is no way to warn users about overridden versions... :(

**Comment by rconde01** [comment]
Ah i missed that detail...oh well?

**Comment by Croydon** [comment]
> spdlog recipe has SPDLOG_FMT_EXTERNAL ON, so embeded one shouldn't be used.

If it is so easy to switch, then this should be probably switched OFF and fmt should be used from the Conan package?

**Comment by SpaceIm** [comment]
spdlog recipe already relies on fmt conan package.

**Comment by uilianries** [comment]
So it's no a package bug, but a spdlog limitation, we can add an exception to avoid new fmt versions. 

The spdlog https://github.com/gabime/spdlog/releases/tag/v1.7.0 support fmt 7.x, so it should not be a block.

**Comment by Croydon** [comment]
@SpaceIm Sorry, I read your previous post wrong 🙈
