### ISSUE TITLE
[package] glu/system: local variable 'packages' referenced before assignment

### ISSUE THREAD

**Issue by zhangyoufu** [conan-io/conan-center-index#2229]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glu/system**
  * Operating System+version: **Linux NeoKylin 7.0**
  * Conan version: **conan 1.27.1**

### Logs (Include/Attach if Applicable)
```
glu/system: ERROR: while executing system_requirements(): local variable 'packages' referenced before assignment
```

### Code
https://github.com/conan-io/conan-center-index/blob/8658ae021ce225d889fa4ee38d30cb80877a7c75/recipes/glu/all/conanfile.py#L17-L32

The local variable `packages` is not initialized for `else` branch.

**Comment by chriztheanvill** [comment]
Hi.
For openSUSE Tumbleweed is: 
```
elif tools.os_info.with_zypper:
                packages = ["glu-devel"]
```
