### ISSUE TITLE
[Conan v1] Recipe Export Check

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-center-index#2232]
2023-10-10

Hook validation run successfully for 4965 recipes :tada:
 * recipes: https://github.com/conan-io/conan-center-index (`*/master`)
 * hooks: https://github.com/conan-io/hooks.git@master
 * error level: ERROR

Packages references without errors: 4964

                    
<details>
<summary>Packages references with errors when running conan export command: 0</summary>

```

```

</details>

Looking forward to those fixes! Thanks!

**Comment by jgsogo** [comment]
..

**Comment by mathbunnyru** [comment]
For now 53 recipes create an error because of `cmake_minimum_required` in the test_package

`ag -Q "cmake_minimum_required" | grep "test_package/CMakeLists.txt" | grep -c "VERSION 2"` gives 53

I think I can create simple python script, which fixes the error, pushes to my fork and creates the PR (I might do the last part manually, if it's easier).

I won't be able to check that other hooks are fixed, but I think most of the recipes will be fixed after that.

**Comment by mathbunnyru** [comment]
Ok, I see that people like the idea, I will do that :)

**Comment by ericLemanissier** [comment]
@jgsogo do you think @conan-center-bot could add in the first message of this issue the errors which happened, as full text, kb number, or anything else ? That would make it possible to open the PR directly, without having to manually check all files of the recipes, or try to export the recipe.

**Comment by mathbunnyru** [comment]
First 10 done. I will address other small hooks issues in these PRs if there are any problems. After some progress, will do 10 more.

https://github.com/conan-io/conan-center-index/pull/4103
https://github.com/conan-io/conan-center-index/pull/4104
https://github.com/conan-io/conan-center-index/pull/4105
https://github.com/conan-io/conan-center-index/pull/4106
https://github.com/conan-io/conan-center-index/pull/4107
https://github.com/conan-io/conan-center-index/pull/4108
https://github.com/conan-io/conan-center-index/pull/4109
https://github.com/conan-io/conan-center-index/pull/4110
https://github.com/conan-io/conan-center-index/pull/4111
https://github.com/conan-io/conan-center-index/pull/4112

**Comment by Croydon** [comment]
@mathbunnyru If I'm allowed to do some advertising here.. things which can be automated fixed like Hook 048, can be fixed by running [bincrafters-conventions ](github.com/bincrafters/bincrafters-conventions/)

Basically

`pip install --user bincrafters-conventions` to install it 

`bincrafters-conventions` to run it in a directory with a `conanfile.py`

**Comment by mathbunnyru** [comment]
Thanks, @Croydon 👍 
I will take a look at this tool, didn't know something like that existed.

**Comment by mathbunnyru** [comment]
First 30 recipes (out of 53) are sent on review.
I will first address most of these recipes, and after that will create PRs for the remaining ones.

**Comment by mathbunnyru** [comment]
Remaining work:

Merged, not yet updated in the table:
- `jemalloc`
- `opencolorio`
- `ninja`

Done, waiting for a review:

- `indicators` - https://github.com/conan-io/conan-center-index/pull/4135
- `nameof` -  https://github.com/conan-io/conan-center-index/pull/4185
- `pdcurses` - https://github.com/conan-io/conan-center-index/pull/4187
- `replxx` - https://github.com/conan-io/conan-center-index/pull/4192

Some troubles
- `easyhttpcpp` - https://github.com/conan-io/conan-center-index/pull/4109
Poco doesn't work well by default on Windows, blocked by https://github.com/conan-io/conan-center-index/pull/4205
I hope I will be able to fix Poco pretty soon, but not sure.
- `libarchive`- weird error under one windows configuration, https://github.com/conan-io/conan-center-index/pull/3778

The weirdness is that it's the same configuration, as in my poco review:
https://github.com/conan-io/conan-center-index/pull/4205#issuecomment-757566806
The log doesn't have any errors, all the text is in the right place.
@madebr @uilianries that might be not just coincidence, but I'm not sure at all.

**Comment by mathbunnyru** [comment]
Please, do not hesitate to approve PRs for 4 recipes, which have successful builds, mentioned above.
And if you have any ideas about the recipes with some troubles, do not hesitate to help the authors ❤️

**Comment by mathbunnyru** [comment]
Yep, all the existing recipes are finally fixed 🎉

But as soon as we merge the PRs to hooks and update the hooks in the cci, there will be new errors, which is totally fine.

**Comment by ericLemanissier** [comment]
The current task seems to call `conan export` but this cannot cover all hooks, because the binaries are not inspected. The coverage would improve if the task used `conan install` instead.

**Comment by jgsogo** [comment]
The problem is that `conan install` depends on the configuration/profile, and we cannot afford to run it for all the profiles... and still, it won't cover hooks that are executed before/after build or package. Here it is just a quick check, something cheap, PRs are the ones that execute every hook.

**Comment by mathbunnyru** [comment]
It would be actually great if all the recipes were easily PR'able.

Because sometimes infrastructure changes or the dependency changes in an incompatible way (we try to avoid this, but I think there might be some bad cases), and it becomes painful to implement a new feature in a recipe because you need to understand what's wrong with the existing recipe.

But I think the computation cost is enormous to check this. But I might be wrong.
There are 407,599 Versions Indexed right now for example.

**Comment by ericLemanissier** [comment]
> There are 407,599 Versions Indexed right now for example.

I don't understand, why is the bot reporting 1642 recipes?

**Comment by mathbunnyru** [comment]
@ericLemanissier because it's the number of versions of all recipes, I suppose.

**Comment by mathbunnyru** [comment]
And the number I gave is the number of actual configurations, which is much higher.

**Comment by prince-chrismc** [comment]
Can this be unpinned and replaced with #3470 pretty please?

**Comment by ericLemanissier** [comment]
Bye, issue, see you next year when a new hook is merged!

**Comment by SpaceIm** [comment]
Does it still run periodically?

Would it be possible to also have a list of recipes reporting hooks warnings? Indeed these hooks report warnings instead of errors to avoid forcing contributors to fix unrelated changes, but they should be turned to errors as soon as most recipes are fixed. But since we don't know how many recipes are in this situation, it's hard to know what needs to be fixed or if there severity level can be increased any time soon.

**Comment by Croydon** [comment]
It might be a good idea to migrate this to GitHub Actions 🤔

**Comment by uilianries** [comment]
> Does it still run periodically?

Yes, once a week. But for some reason is not longer updating, we need to check. There is a Jenkins job which runs with a cron. We should document it in CCI for better transparency for sure. The CI job takes ~2 hours to run conan export command for each recipe and take their result. 

> Would it be possible to also have a list of recipes reporting hooks warnings?

Totally. Indeed, we already have a parameter to configure the logging level, so there is zero effort to show warnings.

**Comment by uilianries** [comment]
> It might be a good idea to migrate this to GitHub Actions 🤔

That's another good option! I'll put it in discussion with Conan team. I remember in the past we thought to use GH Actions instead of Jenkins, but for some reason we kept there in Jenkins, need to check my notes.

**Comment by uilianries** [comment]
We have a new hotfix, it should be available on next C3I release!

**Comment by uilianries** [comment]
Back on rails! The automatic job is working again! 🚂

**Comment by uilianries** [comment]
> Does it still run periodically?
> 
> Would it be possible to also have a list of recipes reporting hooks warnings? Indeed these hooks (missing system libs & also new hook about non-relocatable shared libs on macOS) report warnings instead of errors to avoid forcing contributors to fix unrelated changes, but their severity level is not related to the true severity of the issue they are reporting, so they should be turned to errors as soon as most recipes are fixed. But since we don't know how many recipes are in this situation, it's hard to know which recipe has to be fixed and if severity level of these hooks can be increased any time soon (for example once we know there are only 50 recipes to fix).

@SpaceIm it's possible to elevate to warning level, but not showing the warning message. The GH description body has a character limit, and it was out last problem. So we can update the level, but adding detailed message may fail to push messages on GH.

**Comment by uilianries** [comment]
Closing, the CI Bot re-opened by mistake.
