### ISSUE TITLE
[question] How to depend on header-only recipe?

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#22341]
### What is your question?

Hi! :slightly_smiling_face: 

My recipe depends on `nanosvg` which is a header-only package, so I need it during the compilation phase only. I added the following command into my recipe: `self.requires("nanosvg/cci.20231025")`, however the PR fails with `Required package 'nanosvg' not in component 'requires'`.

What's the correct way to depend on `nanosvg` in this use-case?

My PR: https://github.com/conan-io/conan-center-index/pull/22291

**Comment by uilianries** [comment]
Hello @HappySeaFox !

You see, the Sail recipe has some components listed in the package_info: https://github.com/conan-io/conan-center-index/pull/22291/files#diff-04c36e36f21cede26cb4d2639fe2f01c5585d0b4fdabb4ff98a940c0dd3ed5a3R149

So, the nanosvg should be listed to which requirement (one or more) it's used. For instance:

```
if self.options.with_highest_priority_codecs:
    self.cpp_info.components["sail-codecs"].requires.append("nanosvg::nanosvg")
```

**Comment by HappySeaFox** [comment]
@uilianries Thanks for the response! `nanosvg` is needed during the compilation phase only, it's a header-only library. I guess we can add it as a dependency as you suggested, but I'd like not to expose `nanosvg` publicly for end users (there is no technical need for that). Is there a way to do that?

**Comment by HappySeaFox** [comment]
Oh, I see. Thanks 👍
