### ISSUE TITLE
[package] libcurl/7.66.0: build with_brotli=True fails

### ISSUE THREAD

**Issue by lagner** [conan-io/conan-center-index#2234]
It's impossible to build libcurl with `with_brotli` option turned on. 

libcurl configure script expects a path to **brotli** library.
`./configure --help` says that format is `--with-brotli=PATH`

But the current version uses the option without path parameter. 
https://github.com/lagner/conan-center-index/blob/master/recipes/libcurl/all/conanfile.py#L172

Moreover, it does not have an optional dependency on **brotli** library at all.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.66.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **Clang 10**
  * Conan version: **conan 1.27.1**
  * Python version: **Python 3.8.2**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=10
compiler.libcxx=libc++
build_type=Release
cppstd=17
[options]
[build_requires]
[env]
CC=clang
CXX=clang++
```

### Steps to reproduce (Include if Applicable)
Create *conanfile.txt* with following body
```
[requires]
libcurl/7.66.0

[options]
libcurl:with_brotli=True
```
run `conan install`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```checking brotli/decode.h usability... no
checking brotli/decode.h presence... no
checking for brotli/decode.h... no
configure: error: BROTLI libs and/or directories were not found where specified!
libcurl/7.66.0: 
libcurl/7.66.0: ERROR: Package '486010ccf0bc2a48c34a45132fd130dae3598a16' build failed
libcurl/7.66.0: WARN: Build folder /home/lagner/.conan/data/libcurl/7.66.0/_/_/build/486010ccf0bc2a48c34a45132fd130dae3598a16
ERROR: libcurl/7.66.0: Error in build() method, line 149
	self._build_with_autotools()
while calling '_build_with_autotools', line 304
	autotools, autotools_vars = self._configure_autotools()
while calling '_configure_autotools', line 396
	self._autotools.configure(vars=autotools_vars, args=configure_args)
	ConanException: Error 1 while executing ./configure '--without-libidn2' '--without-librtmp' '--without-libmetalink' '--without-libpsl' '--with-brotli' '--with-ssl=/home/lagner/.conan/data/openssl/1.1.1d/_/_/package/2b1e5ff9df96aaf5924c273e1368c632fcb32dd2' '--without-libssh2' '--with-nghttp2=/home/lagner/.conan/data/libnghttp2/1.40.0/_/_/package/06cde106f0128e68499c55f5e2801b7fc6e3ef9b' '--with-zlib=/home/lagner/.conan/data/zlib/1.2.11/_/_/package/2b1e5ff9df96aaf5924c273e1368c632fcb32dd2/lib' '--disable-shared' '--enable-static' '--disable-ldap' '--prefix=/home/lagner/.conan/data/libcurl/7.66.0/_/_/package/486010ccf0bc2a48c34a45132fd130dae3598a16' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' 
```

</details>

**Comment by SpaceIm** [comment]
Actually, in configure.ac, `with-brotli` without path to brotli library will use pkg-config. But indeed, brotli library was not requested in `requirements` method of libcurl recipe. https://github.com/conan-io/conan-center-index/pull/2880 should fix this issue.
