### ISSUE TITLE
[service] CI bug: system dependencies are not installed if the recipe does not change in the MR

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan-center-index#22356]
### What is your problem/feature request?

Issue seen when trying to do a MR on the qt package: https://github.com/conan-io/conan-center-index/pull/22151 with @ericLemanissier

> It's a bug in conan-center CI: when the recipe is not modified, it reuses the existing binary for the test, but it does not install system dependencies. The workaround is to modify the recipe in order to trigger a new build.

This is very painful to create a fake recipe update for every commit.

**Comment by RubenRBS** [comment]
We have had identified the issue for a bit now and we have been working on a fix that we will push libe shortly, thanks a lot for the report :)

**Comment by AbrilRBS** [comment]
Update: The current idea is that for the CI, images should already come with the necessary packages, so that we can run with `tools.system.package_manager:mode=check`, and thus no actual installation will be needed

**Comment by AbrilRBS** [comment]
And closing this as solved, as the new CI pipeline correctly handles the test packages for system dependencies, installing them accordingly. Thanks!
