### ISSUE TITLE
[request] Thrift/0.9.3

### ISSUE THREAD

**Issue by jheaff1** [conan-io/conan-center-index#2239]
### Package Details
  * Package Name/Version: **thrift/0.9.3**
  * Changelog: **https://github.com/apache/thrift/blob/master/CHANGES.md#093**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by Croydon** [comment]
This is an older version that we currently have (`0.13.0`). Do you have another dependency which does not work with 0.13.0?

**Comment by jheaff1** [comment]
Hi @Croydon, thanks for your message.

My team develop an application that is dependent on 0.9.3. I am looking to change the build system to use Conan. Sadly we are not in a position to change to 0.13.0 and perform the required regression tests.

**Comment by uilianries** [comment]
Fair enough, I'm not oppose when an older version is requested because an enterprise limitation. @jheaff1 could you please open a PR with such version? If it require more than version change, like a patch, we can help you.

**Comment by gjasny** [comment]
@jheaff1 is this still needed?

**Comment by jheaff1** [comment]
Nope 👍🏻
