### ISSUE TITLE
[package] spirv-tools/v2020.3: missing packages

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#2242]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spirv-tools/v2020.3**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 14**
  * Conan version: **conan 1.27.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MTd
compiler.version=14
os=Windows
os_build=Windows
[options]
glslang:shared=False
```

### Steps to reproduce (Include if Applicable)

`conan create . glslang/8.13.3559`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: Missing binary: spirv-tools/v2020.3:d084c2ccdca32f9d73952fc7db2f8ff3aad4db9a
spirv-tools/v2020.3: WARN: Can't find a 'spirv-tools/v2020.3' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Debug, compiler=Visual Studio, compiler.runtime=MTd, compiler.version=14, os=Windows
- Options: shared=True
- Dependencies: spirv-headers/1.5.3
- Requirements: spirv-headers/1.Y.Z
- Package ID: d084c2ccdca32f9d73952fc7db2f8ff3aad4db9a

ERROR: Missing prebuilt package for 'spirv-tools/v2020.3'
Try to build from sources with "--build=spirv-tools"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

```

</details>

**Comment by madebr** [comment]
Maybe this helps:
https://github.com/madebr/conan-spirv_tools

**Comment by danimtb** [comment]
Regarding the result in https://github.com/conan-io/conan-center-index/pull/1360#issuecomment-662415304, was this issue fixed?

**Comment by SpaceIm** [comment]
Yes I close it ;)
