### ISSUE TITLE
[qt] qt/5.x.x: qt3d option cannot be used without qtgamepad

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan-center-index#22435]
### Description

If we set qt3d option to True but leave qtgamepad to False, we get an error during the packaging.

### Package and Environment Details

* Package Name/Version: **qt/5.15.11**
* Operating System+version: **Windows 11**
* Compiler+version: **msvc192**
* Conan version: **conan 2.0.17**
* Python version: **Python 3.10.3**

### Conan profile

[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=192
os=Windows
[options]
qt/*:shared=True
qt/*:qtsvg=True
qt/*:qtdeclarative=True
qt/*:qttools=True
qt/*:qtxmlpatterns=True
qt/*:qttranslations=True
qt/*:qtdoc=True
qt/*:qt3d=True
qt/*:qtimageformats=True
qt/*:qtgraphicaleffects=True
qt/*:qtquickcontrols=True
qt/*:qtquickcontrols2=True
qt/*:qtcharts=True
qt/*:qtdatavis3d=True
qt/*:qtquick3d=True
qt/*:qtwinextras=True

### Steps to reproduce

conan install --requires=qt/5.15.11 --build=missing

### Logs

<details><summary>Click to expand log</summary>

```
qt/5.15.11: Package 'ae88675d4c216f5711e871278709c9aa2a2de395' created
qt/5.15.11: Full package reference: qt/5.15.11#97a1ebd4c4cd3b90311946cf7a75ba89:ae88675d4c216f5711e871278709c9aa2a2de395#ed35d6b1e0f401e38b5350dba1f3d613
qt/5.15.11: Package folder C:\.c\p\b\qt4c0dc61cfa0a2\p
ERROR: qt/5.15.11: Error in package_info() method, line 1344
        _create_module("3DInput", ["3DCore", "Gamepad", "Gui"])
while calling '_create_module', line 1021
        self.cpp_info.components[componentname].requires = _get_corrected_reqs(requires)
while calling '_get_corrected_reqs', line 993
        assert corrected_req in self.cpp_info.components, f"{corrected_req} required but not yet present in self.cpp_info.components"
        AssertionError: qtGamepad required but not yet present in self.cpp_info.components
```

</details>

**Comment by fdgStilla** [comment]
Note: related to https://github.com/conan-io/conan-center-index/issues/16113

@ericLemanissier I am not sure how to fix this one so I don't have a PR

**Comment by ericLemanissier** [comment]
@fdgStilla can you please try with https://github.com/conan-io/conan-center-index/pull/22437 ?

**Comment by fdgStilla** [comment]
It works thanks!
