### ISSUE TITLE
[request] wagyu/0.5.0

### ISSUE THREAD

**Issue by casperlamboo** [conan-io/conan-center-index#22579]
### Package Name/Version

wagyu/0.5.0

### Webpage

https://github.com/mapbox/wagyu

### Source code

https://github.com/mapbox/wagyu

### Description of the library/tool

Wagyu is a header only "Geometry Processing Library". It supports multiple operations on two dimensional polygons like booleans AND, boolean OR, etc and polygon offsetting.

**Comment by toge** [comment]
@casperlamboo 
Thank you for your request!
I created simple PR for this.
If you find any problems about it, please notice me.

**Comment by casperlamboo** [comment]
@toge, thanks for picking this up so quickly! I will give this a look tomorrow at work.
