### ISSUE TITLE
[package] boost/1.83.0: Pass `tools.build:defines` to `b2` (Boost.Build)

### ISSUE THREAD

**Issue by stevenwdv** [conan-io/conan-center-index#22619]
### Description

While e.g. `tools.build:cxxflags` is passed to `b2`, `tools.build:defines` is not. This means something like `tools.build:defines=["_WIN32_WINNT=0x0601"]` does not get passed to the compiler when compiling Boost, possibly causing linking issues when the value *is* used when compiling the consumer package, see #14097.

A workaround is to include `'extra_b2_flags': ' '.join(f'define={d}' for d in self.conf.get('tools.build:defines', [])) or None` in the consumer conanfile when requiring Boost.

### Package and Environment Details

* Package Name/Version: **boost/1.83.0**
* Operating System+version: N/A
* Compiler+version: N/A
* Docker image: N/A
* Conan version: **conan 2.0.17**
* Python version: N/A

### Conan profile

```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.version=192
compiler.runtime=dynamic
os=Windows

[conf]
tools.build:defines=["_WIN32_WINNT=0x0601"]
```

### Steps to reproduce

Run `conan install ./ --build="boost/*" -vvv` with some `tools.build:defines` and observe how no `define=...` is passed to `b2`.

### Logs

Important part:

```
boost/1.83.0: RUN: b2 -q numa=on target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system --user-config=C:\Users\StevenWdV\.conan2\p\boostb64db50bc1f06\s\src\tools\build\user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=off --disable-iconv runtime-link=shared runtime-debugging=off threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-fiber --with-filesystem --with-graph --with-iostreams --with-json --with-locale --with-log --with-math --with-nowide --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure --with-url --with-wave toolset=msvc cxxflags=/std:c++20 pch=on linkflags="" cxxflags="-fPIC" install --prefix=C:\Users\StevenWdV\.conan2\p\b\boost567381a1bbdb5\p -j8 --abbreviate-paths -d0 --debug-configuration --build-dir="C:\Users\StevenWdV\.conan2\p\b\boost567381a1bbdb5\b\build-release"
```

**Comment by Cogitri** [comment]
What makes this a bit more problematic is that starting with boost 1.84.0, windows 10 is the default target: https://github.com/boostorg/winapi/commit/85d7889e9b90c3c35bc592013b942f72d5475baf
