### ISSUE TITLE
icu/74.2 recipe is broken : src link is broken

### ISSUE THREAD

**Issue by eltanardo** [conan-io/conan-center-index#22635]
### What is your question?

Hello, 
Conan recipe for icu/74.2 does not work anymore : the src link may have changed : the link https://github.com/unicode-org/icu/releases/download/release-74-2/icu4c-74_2-src-FIXED.tgz is broken.

**Comment by uilianries** [comment]
Duplicated with https://github.com/conan-io/conan-center-index/issues/22632

@eltanardo Please, follow #22632 for further information.
