### ISSUE TITLE
[package] icu/74.2: Wrong url 

### ISSUE THREAD

**Issue by lukasz-matysiak** [conan-io/conan-center-index#22632]
### Description

The `recipes/icu/all/conandata.yml` file contains a wrong url for the ICU 74.2 package.
Following the link present in the file (https://github.com/conan-io/conan-center-index/blob/master/recipes/icu/all/conandata.yml#L3)  (https://github.com/unicode-org/icu/releases/download/release-74-2/icu4c-74_2-src-FIXED.tgz) leads to a page that does not exist.
Because of that, the package fails to compile.

### Package and Environment Details

* Package Name/Version: **icu/74.2**
* Operating System+version: **Fedora 39**
* Compiler+version: **GCC 13**
* Conan version: **conan 2.0.17**
* Python version: **Python 3.12.1**

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

### Steps to reproduce

Use the following `conanfile.txt`:
```
[requires]
icu/74.2

```
And run
`conan install conanfile.txt --build=missing`

### Logs

<details><summary>Click to expand log</summary>

```
$ conan install conanfile.txt --build=missing

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux


======== Computing dependency graph ========
icu/74.2: Not found in local cache, looking in remotes...
icu/74.2: Checking remote: conancenter
icu/74.2: Downloaded recipe revision 2c5797e68b97c6d12883397c753880cc
Graph root
    conanfile.txt: /tmp/testconanicu/conanfile.txt
Requirements
    icu/74.2#2c5797e68b97c6d12883397c753880cc - Downloaded (conancenter)

======== Computing necessary packages ========
icu/74.2: Checking 11 compatible configurations
icu/74.2: Compatible configurations not found in cache, checking servers
icu/74.2: '1f74f54dcdb0f015a11c683b99d47509e144db17': compiler.cppstd=98
icu/74.2: '81e8f91e945ac04beae5c6e2a995890a26079207': compiler.cppstd=gnu98
icu/74.2: 'bf1def7a498458fe993cf9da5d0f58d018f5e9ab': compiler.cppstd=11
icu/74.2: 'ec43fc90f927474690d7fef1bfcb2f041abfe013': compiler.cppstd=gnu11
icu/74.2: 'baf07421fb70c8a9633a5c971801f61451455790': compiler.cppstd=14
icu/74.2: 'a20886735c18ecd9e539d79959338b3a0c535cdc': compiler.cppstd=gnu14
icu/74.2: 'd014ba15f7536341c1f9e11eaef960fcb0ae0b3e': compiler.cppstd=17
icu/74.2: '523b8590abf65b60b8f674f3d6c3c53e8c1ed021': compiler.cppstd=20
icu/74.2: '3a9ae0c8892ccf019033a77014173b0a2103201d': compiler.cppstd=gnu20
icu/74.2: 'a388238db738bdcb0f9ec08f26c45966ff4ef237': compiler.cppstd=23
icu/74.2: '36405503cfab793166db37e0651378f1345116e3': compiler.cppstd=gnu23
Requirements
    icu/74.2#2c5797e68b97c6d12883397c753880cc:430296d1819f1a8aee49318795ad2dc50dbbf14b - Build

======== Installing packages ========
icu/74.2: Sources downloaded from 'conancenter'
icu/74.2: Calling source() in /home/lm/.conan2/p/icu47fff46ebbd0a/s/src
ERROR: icu/74.2: Error in source() method, line 103
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        NotFoundException: Not found: https://github.com/unicode-org/icu/releases/download/release-74-2/icu4c-74_2-src-FIXED.tgz
```

</details>

**Comment by uilianries** [comment]
Hello @lukasz-matysiak ! Thank you for reporting this bug. It seems like the upstream changed its release, because that package was built once in Conan Center. 

I opened the PR #22633 to fix it.

**Comment by lukasz-matysiak** [comment]
Hi @uilianries 
Thanks for taking care of it so quickly!
