### ISSUE TITLE
[question] glib: ConanInvalidConfiguration on Windows, why?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#2271]
bincrafters `glib` recipe can be built on Windows with Visual Studio (but I have link errors to libiconv with MinGW). Any reason why CCI recipe raise `ConanInvalidConfiguration` on Windows?

https://github.com/conan-io/conan-center-index/blob/3ecfa04d41684fa340eadfabb72ac4958d8e24c3/recipes/glib/all/conanfile.py#L100

**Comment by ericLemanissier** [comment]
yes, pkg-config is needed, so it is blocked by https://github.com/conan-io/conan-center-index/pull/1013
