### ISSUE TITLE
[package] opengl/system: Library name wrong when cross-building with mingw

### ISSUE THREAD

**Issue by Bigpet** [conan-io/conan-center-index#2273]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **opengl/system**
  * Operating System+version: **Linux Debian Stretch**
  * Compiler+version: **GCC 9**
  * Docker image: **dockcross/windows-static-x64**
  * Conan version: **conan 1.25.2**
  * Python version: **Python 2.7.13**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile ./config/conan/profiles/x86_64-w64-mingw32:

[settings]
os=Windows
arch=x86_64
compiler=gcc
compiler.exception=seh
compiler.threads=posix
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Debug
[options]
[build_requires]
[env]
CC=x86_64-w64-mingw32-gcc
RC=x86_64-w64-mingw32-windres
RANLIB=x86_64-w64-mingw32-ranlib
CXX=x86_64-w64-mingw32-g++
AS=x86_64-w64-mingw32-as
AR=x86_64-w64-mingw32-ar
CHOST=x86_64-w64-mingw32
STRIP=x86_64-w64-mingw32-strip
CONAN_CMAKE_SYSTEM_NAME=Windows

```

### Steps to reproduce (Include if Applicable)
Try to build something that links against opengl32

### Logs (Include/Attach if Applicable)
<details><summary> link error
</summary>

```
/usr/src/mxe/usr/bin/x86_64-w64-mingw32.static.posix-ld: cannot find -lOpenGl32
collect2: error: ld returned 1 exit status
```

</details>

The issue is that the windows SDK calls the import library `OpenGL32.lib` (even though the library is opengl.dll) and MXE mingw calls the library `libopengl.a` which both link correctly on Windows because it normally has a case-insensitive filesystem active.

But when cross-building from MXE the library can't be found under the name "OpenGL32". 

**I haven't found a simple solution to detect if the target is using mingw or a native Windows SDK**. But just changing this line here: https://github.com/conan-io/conan-center-index/blob/master/recipes/opengl/all/conanfile.py#L72 to be "opengl32" solves the problem for me.

But that would be technically wrong, so if it's possible to distinguish mingw from the official windows SDK that would be great.

**Comment by SSE4** [comment]
interesting. the Windows SDK contains `OpenGL32.lib` (in that case). MinGW has `libopengl32.a`. probably should be a different branch...
