### ISSUE TITLE
[package] arrow/10.0.1: Cannot build arrow fligt with protobuf 3.21.12

### ISSUE THREAD

**Issue by Bronomor** [conan-io/conan-center-index#22776]
### Description

I create own package and I need to build arrow with option `with_flight_rpc` set to True. But I have an error message 
`ERROR: Version conflict: grpc/1.50.0 ->protobuf/3.21.12, arrow/10.0.1 ->protobuf/3.21.9.`

Can we allow to use protobuf 3.21.12 by arrow ( or `[protobuf/[>=3.21.9 <=3.21.12]` )

### Package and Environment Details

* Package Name/Version: **arrow/10.0.1**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.0.14**
* Python version: **Python 3.8**

### Conan profile

[settings]
os=Linux
os_build=Linux
compiler=gcc
compiler.version=17
compiler.libcxx=libc++
build_type=Release

### Steps to reproduce

As far I understand correctly to do this i need to also use the following options:
```
"arrow/*:with_flight_rpc": True,
"arrow/*:with_openssl": True,
"arrow/*:with_grpc": True,
"arrow/*:with_protobuf": True
```

In requirements I have only
```
self.requires("arrow/10.0.1")
```

### Logs

But I have an error message 
ERROR: Version conflict: grpc/1.50.0 ->protobuf/3.21.12, arrow/10.0.1 ->protobuf/3.21.9.

**Comment by danimtb** [comment]
Should be fixed at https://github.com/conan-io/conan-center-index/pull/23480. See https://github.com/conan-io/conan-center-index/issues/23475 as well. Thanks!
