### ISSUE TITLE
[service] Generate Wiki according docs changes

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#2283]
Now both docs/ and Wiki are duplicated, we could put both in the Thunderdome, or just remove the Wiki.

UPDATE: @Croydon [suggestion](https://github.com/conan-io/conan-center-index/issues/2283#issuecomment-665006275) sounds more better, we can keep both.

**Comment by SSE4** [comment]
I don't think we should remove it. getting 404s would be annoying. you know people may visit wiki from google searches or from existing references from various blogs, twits, etc.
probably, existing pages should redirect to the new docs. if redirection is not possible, probably it should include some text and link to the corresponding section within new docs.

**Comment by uilianries** [comment]
Indeed! Redirect is not possible, but we can add the links from docs.

**Comment by danimtb** [comment]
First, we have to change the link from the KBs of the hook and point them to the *docs* folder, then we can put a link in every page of the wiki to redirect people there

**Comment by Croydon** [comment]
I would like to suggest once more, that we use `docs/` as the only source of truth and use CI to push its content to the GitHub wiki

GitHub's file preview isn't as nice as a wiki page when it comes to readability and  and GitHub's file listing isn't a real navigation either

**Comment by uilianries** [comment]
> that we use `docs/` as the only source of truth and use CI to push its content to the GitHub wiki

![I-Am-Once-Again-Asking-For](https://i.imgflip.com/49p0vz.jpg)

Agreed! But of course, it requires internal work. I gonna update my description and title. Thanks for the idea @Croydon !

**Comment by jgsogo** [comment]
The plan is as follows:
 1. Remove content from the wiki and substitute with a link to the docs
 2. When GA, remove/close the wiki in Github
 3. In the future, docs can be generated and published as a web page

**Comment by jgsogo** [comment]
Done.
