### ISSUE TITLE
[request] <protobuf>/<4.25.3>

### ISSUE THREAD

**Issue by Amenallah07** [conan-io/conan-center-index#22850]
Dear Conan Center maintainers,

I would like to request that protobuf version 4.25.3 be added to conancenter.io.

protobuf is a popular protocol buffers library for serializing structured data. The latest release, 4.25.3 contains important bug fixes and improvements over the current version available in conancenter (3.21.12).

Some key details about protobuf 4.25.3:

Changelog: https://github.com/protocolbuffers/protobuf/blob/master/CHANGES
Download URL: https://github.com/protocolbuffers/protobuf/releases/tag/v4.25.3

Maintaining the latest stable version of protobuf in conancenter would be valuable for users who depend on fixes/features in recent releases. It would also help avoid compatibility issues that could arise from mixing protobuf versions across Conan packages.

I appreciate you maintaining conancenter and helping keep packages up-to-date.

Thank you for your consideration.

Regards,

**Comment by Ahajha** [comment]
Should be fixed by https://github.com/conan-io/conan-center-index/pull/21622

**Comment by jcar87** [comment]
https://github.com/conan-io/conan-center-index/pull/24154

4.25.3 and 5.27.0 are now available
