### ISSUE TITLE
[question] How is RPATH handle in Conan 2?

### ISSUE THREAD

**Issue by Wayonb** [conan-io/conan-center-index#22866]
### What is your question?

I am migrating our Conan 1 recipes to Conan 2.
Conan 1 documentation contains information on how RPATH is set up using the ``conan_basic_setup(KEEP_RPATHS)`` for macOS.  
https://docs.conan.io/1/howtos/manage_shared_libraries/rpaths.html#default-conan-approach

I am not finding much information on how RPATH is handled in Conan 2.  It seems the ``conan_basic_setup()`` was removed. Is there a replacement for this?

**Comment by Wayonb** [comment]
I did not see any info about RPATH in the migration section - https://docs.conan.io/1/conan_v2.html

**Comment by jcar87** [comment]
Hi @Wayonb - we now expect to use CMake defaults when it comes to RPATH handling - so if your recipes or CMake scripts were doing anything special, it should no longer be necessary. 

Roughly:
* For packaged `*.dylib` on macOS, the install name should start with `@rpath/`. If packaged binaries (executables or dylibs) have any rpath entries themselves, pointing to other libraries within the package, these should be relative (would typically start with `@executable_path` or `@loader_path`)
* For packaged `.so` on Linux, there should be no RPATH entries pointing to absolute paths. Relative ones (relative to `$ORIGIN`) are potentially okay if they point to files within the same package.

For the most part, the default `cmake install` behaviour will already to the right thing and there's nothing special that needs to be done in the recipe. For recipes of libraries that are built with Autotools (or other systems other than CMake), we may have to do call the `fix_apple_shared_install_name(self)()` helper in the `package()` method. See: https://docs.conan.io/2.1/reference/tools/apple/other.html#conan-tools-apple-fix-apple-shared-install-name

**Comment by Wayonb** [comment]
Thanks @jcar87 for the info
