### ISSUE TITLE
[package] xz_utils/5.4.5 Package sources/tar not found at URL

### ISSUE THREAD

**Issue by Lnk2past** [conan-io/conan-center-index#22863]
### Description

I tried installing `xz_utils/5.4.5` and Conan times out because the URL in the package is not correct.

```text
xz_utils/5.4.5: WARN: network: Error downloading file https://tukaani.org/xz/xz-5.4.5.tar.xz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.4.5.tar.xz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))'
```

I think the problem is that the website https://tukaani.org is no longer valid, and should be https://xz.tukaani.org/. The links to the actual tars look different now too; so I think all of the URLs in conandata.yml are incorrect.

### Package and Environment Details

* Package Name/Version: **xz_utils/5.4.5**
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **GCC 10.2**
* Docker image: N/A
* Conan version: **conan 2.0.17**
* Python version: **Python 3.9.2**

### Conan profile

[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

### Steps to reproduce

conan install --requires=xz_utils/5.4.5 -r conancenter --build=missing

### Logs

<details><summary>Click to expand log</summary>

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    xz_utils/5.4.5#a26a2d42ab9c3dabc151bbe1bf898e53 - Cache

======== Computing necessary packages ========
Requirements
    xz_utils/5.4.5#a26a2d42ab9c3dabc151bbe1bf898e53:1a9fda660de0c747d126d629ab86cd194228796f - Build

======== Installing packages ========
xz_utils/5.4.5: WARN: Trying to remove corrupted source folder
xz_utils/5.4.5: WARN: This can take a while for big packages
xz_utils/5.4.5: Calling source() in /root/.conan2/p/xz_ute033bfcacc0c2/s/src
xz_utils/5.4.5: WARN: network: Error downloading file https://tukaani.org/xz/xz-5.4.5.tar.xz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.4.5.tar.xz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))'
xz_utils/5.4.5: Waiting 5 seconds to retry...
xz_utils/5.4.5: WARN: network: Error downloading file https://tukaani.org/xz/xz-5.4.5.tar.xz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.4.5.tar.xz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))'
xz_utils/5.4.5: Waiting 5 seconds to retry...
ERROR: xz_utils/5.4.5: Error in source() method, line 77
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        ConanException: Error downloading file https://tukaani.org/xz/xz-5.4.5.tar.xz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.4.5.tar.xz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))'
```

</details>

**Comment by Ahajha** [comment]
I wonder if there was some temporary outage or config issue on your end, since it works for me.

**Comment by Ahajha** [comment]
That said, it looks like they've moved to github releases for their latest versions (including 5.6.0, released last week). I'm going to make a PR and starting with that version it will use the github releases.

**Comment by Ahajha** [comment]
Seems related to [this](https://github.com/tukaani-project/xz/issues/78), which seems to also support that it was a temporary outage.

**Comment by Ahajha** [comment]
The latest xz_utils (5.6.0) uses sources from Github, and it seems this issue was a temporary outage. This is similar to https://github.com/conan-io/web/issues/152.

@RubenRBS FYI, I think this can be closed?

**Comment by RubenRBS** [comment]
Hood catch, thanks @Ahajha :)

**Comment by Lnk2past** [comment]
gotcha, thanks all!
