### ISSUE TITLE
[package] libcurl/7.66.0: Error in package_info()

### ISSUE THREAD

**Issue by Segel10** [conan-io/conan-center-index#2290]
Might be doing something wrong but since #2156 i am getting the error:
```
ERROR: libcurl/7.66.0: Error in package_info() method, line 527
   self.cpp_info.components["curl"].requires.append("zlib::zlib")
   AttributeError: 'Component' object has no attribute 'requires'
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.66.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual studio 2017 with ISO C++17 Standard (/std:c++17) (Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27038**
  * Conan version: **conan 1.24.0**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=15
cppstd=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Relevant parts of Conanfile.py.
```
	requires = 'libcurl/7.66.0',
	settings = "os", "compiler", "build_type", "arch"
	generators = "cmake"

	def configure(self):
		if self.settings.os == "Windows":
			self.options["libcurl"].with_openssl = False
			self.options["libcurl"].with_winssl = True

	def _configure_cmake(self):
		cmake = CMake(self)
		cmake.configure()
		return cmake

	def build(self):
		cmake = self._configure_cmake()
		cmake.build()
```

**Comment by Segel10** [comment]
Updated to conan 1.27.0 and now it is working. Is it expected that it shouldn't work with an older version of conan?

**Comment by uilianries** [comment]
No. CCI expects that all users run the latest Conan version. However, this is hard to track and very implicit to users, so there will be a new feature in Conan 1.28 to set the required Conan version in the recipe: https://github.com/conan-io/conan/issues/7138
