### ISSUE TITLE
[question] What to do when package maintainers lose interest, Should this conanfile work?

### ISSUE THREAD

**Issue by gazzatav** [conan-io/conan-center-index#23065]
Several utilities and services that I have written depend on a package for which the authors appear to have lost interest (in packaging for Conan -  taocpp-json/1.0.0-beta.11 for example).  The recipes for this and others have not been upgraded for conan 2.  What's worse is that the authors have retrospectively restructured their repository for the given checked out branch/tag and api so that just correcting the conanfile.py won't work either.

It is a header only library and I have checked out the necessary header files and made this simple conanfile.py to locally repackage the headers so that I can depend on them:

```
from conan import ConanFile
from conan.tools.files import copy


class TaocppJsonLocalConan(ConanFile):
    name = "taocpp_json_local"
    version = "1.0.11-beta"
    # No settings/options are necessary, this is header only
    exports_sources = "include/*"
    # We can avoid copying the sources to the build folder in the cache
    no_copy_source = True


    def package(self):
         # This will also copy the "include" folder
         copy(self, "*.h", self.source_folder, self.package_folder)
         copy(self, "*.hpp", self.source_folder, self.package_folder)

    def package_info(self):
         # For header-only packages, libdirs and bindirs are not used
         # so it's necessary to set those as empty.
         self.cpp_info.bindirs = []
         self.cpp_info.libdirs = []
         self.cpp_info.set_property("cmake_file_name", "taocpp_json")
         self.cpp_info.set_property("cmake_target_name", "local::taocpp_json")

    def package_id(self):
        self.info.clear()
```
I have been going round in circles trying to get all my services and utilities to rebuild but I keep getting errors like this:

```
CMake Error at src/CMakeLists.txt:25 (target_link_libraries):
  Target "cs_utility" links to:

    local::taocpp_json

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

Now that's fine and I can correct it if it's just me and I'm missing something because I've been staring at it for so long.  What I would like to know is if my simple conanfile.py is correct and whether it should indeed create the cmake find package and the target so that cmake can find it.

When I build one utility I see:

Conan: Target declared 'taocpp_json_local::taocpp_json_local'

And

Conan: Target declared 'local::taocpp_json

This could easily be my fault from leftovers of the previous package but makes me worry that I have not set the target correctly (or if it is being deleted by the package_id method and only created accidentally by a CMakeLists.txt with an ALIAS).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I am having a look to ``conan-center-index`` repo.

I am not sure what you mean. The recipe seems updated to Conan 2, it is working fine, this works in Conan 2:
```bash
$ conan install --requires="taocpp-json/1.0.0-beta.14" -s compiler.cppstd=17
```

**Comment by gazzatav** [comment]
My services are depending on taocpp-json/1.0.0-beta.11 and that is 14.  I have had to change some function names already because the repo has changed 'under my feet'.  I'll try 14.

**Comment by gazzatav** [comment]
Things seem to be going better with taocpp-json/1.0.0-beta.14.  I would still like to know though, was my header only package conanfile.py above correct and should the find package and target work from it?

**Comment by uilianries** [comment]
Hello @gazzatav just to clarify, will you use `taocpp-json/1.0.0-beta.14`? 

The correct CMake target to link Taocpp JSON is `taocpp::json`: https://github.com/taocpp/json/blob/1.0.0-beta.14/CMakeLists.txt#L82

In beta.11 there was no official cmake target, it was declared after that.

**Comment by gazzatav** [comment]
Yes, I am currently changing everything to require taocpp-json/1.0.0-beta.14 and yes, I believe the target was previously created with an alias in CMakeLists.txt.

**But** this question is really about whether my simple conanfile.py above will correctly produce the target and find package name that I specified given that self.info is cleared in the package_id method.

ps One of the problems with the beta.11 was that it tried to import 'Version' from, IIRC conan.version, and caused a frozen library error.  Coupled with all the deprecation warnings that made me think that the recipe had been neglected.

**Comment by uilianries** [comment]
> this question is really about whether my simple conanfile.py above will correctly produce the target and find package name that I specified given that self.info is cleared in the package_id method.

Your `conanfile.py` will produce the file `taocpp_json-config.cmake` when using the Conan generator `CMakeDeps`. Plus, it will have the CMake targets `taocpp_json_local::taocpp_json_local` (the general one) and `local::taocpp_json` that you defined.

> One of the problems with the beta.11 was that it tried to import 'Version' from, IIRC conan.version, and caused a frozen library error. Coupled with all the deprecation warnings that made me think that the recipe had been neglected.

The `Version` should be imported from `conan.tools.scm`

**Comment by gazzatav** [comment]
@uilianries Thank you.  I originally put CMakeDeps in my conanfile.py but then removed because something I read suggested it was only used when there is building to be done whereas this is header only.  I want to consume this header-only library using a target alias in target_link_libraries, should I be doing something else?

**Comment by uilianries** [comment]
> I originally put CMakeDeps in my conanfile.py but then removed because something I read suggested it was only used when there is building to be done whereas this is header only.

@gazzatav The `CMakeDeps` should be added to your recipe, only case using CMake to build the project AND, you need to install dependencies (e.g. openssl). It's not your case because taocpp-json is standalone, so you are right removing it from your recipe.

>  I want to consume this header-only library using a target alias in target_link_libraries, should I be doing something else?

To consume the Conan package created is a different context, you need to know where those headers are installed, pass compiler definitions (when explicit in the recipe), ... So you need to consume using CMakeToolchain and CMakeDeps. The CMakeToolchain will configure your build to match with your the Conan profile, it's really important. Second, the CMakeDeps will generate taocpp_json-config.cmake, which you should consume via find_package and then link via target_link_libraries. Using only CMakeToolchain or only CMakeDeps will not work when consuming the package, need to use both, otherwise you will have a mismatch when building.

**Comment by gazzatav** [comment]
@uilianries Thank you again.  I understand this much better, now it seems obvious.  I've had it the wrong way round in my head for a long time but now I see, it's not the package that produces its own 'find_package' files it is the consumer using the info and objects from the recipe which then feeds into the build.

**Comment by uilianries** [comment]
@gazzatav I'm glad it helped!

**Comment by uilianries** [comment]
>  I was not sure about how ConanCenter packages were maintained and thought they might remain the 'exclusive property' or 'domain' of the contributors. 

@gazzatav Anyone can send new recipes, bugfix or maintenance patch to ConanCenterIndex here in Github. We have a large documentation about how to contribute in case you are interested: https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md

Thank you for your feedback!
