### ISSUE TITLE
[package] mysql-connector-c/6.1.11: Unable to load conanfile

### ISSUE THREAD

**Issue by flybull** [conan-io/conan-center-index#23180]
### Description

Unable to load conanfile

self.requires("mysql-connector-c/6.1.11")

### Package and Environment Details

* Package Name/Version: **mysql-connector-c/6.1.11**
* Operating System+version: **Linux Centos 7.9**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.10**
* Python version: **Python 3.11.4**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++
compiler.version=11
os=Linux

### Steps to reproduce

conan create .

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: Package 'mysql-connector-c/6.1.11' not resolved: mysql-connector-c/6.1.11: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/mysql4ba304fc1fc98/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/mysql4ba304fc1fc98/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/mysql4ba304fc1fc98/e/conanfile.py", line 1, in <module>
    from conans import ConanFile, CMake, tools
ImportError: cannot import name 'ConanFile' from 'conans' (/root/miniconda3/lib/python3.11/site-packages/conans/__init__.py)

```

</details>

**Comment by Ahajha** [comment]
Looks like it hasn't been migrated to Conan 2.0. The recipe looks fairly simple, I can probably make a PR soon.
