### ISSUE TITLE
[sbepp] <sbepp>/<1.2.0>: Decrease minimum compiler version to gcc 8.5

### ISSUE THREAD

**Issue by ujos** [conan-io/conan-center-index#23205]
### Description

Because of restrictions on the project I'm working on, I cannot use gcc9. Instead we use gcc 8. When I run `connan install` command, I get the following error:

```
sbepp/1.2.0: Invalid ID: sbepp/1.2.0 requires C++17, which your compiler does not support.
```
I've checked the `conanfile.py` and found following code:

```py
   def _compilers_minimum_version(self):
        if self.options.with_sbeppc:
            return {
                "gcc": "9",
                "clang": "9",
                "apple-clang": "11"
            }
        else:
            return {
                "gcc": "4.8.1",
                "clang": "3.3",
                "apple-clang": "9.4"
            }
```

This code sets the minimum required gcc version to 9 in case if `with_sbeppc=True`.

I've downloaded the source code of the sbepp/1.2.0 library and successfully built it with gcc 8.5. So theoretically we can use the `sbepp` library as a git module, however I'd like to use it from the Conan.

Taking into account the information above, could you please update the minimum GCC version requirements to v8.5?

### Package and Environment Details

* Package Name/Version: **sbepp/1.2.0**
* Operating System+version: **CentOS Linux release 7.9.2009 (Core)**
* Compiler+version: **GCC 8.5**
* Docker image: **centos7.9.2009**
* Conan version: **conan 1.58.0**
* Python version: **Python 3.6.8**

### Conan profile

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11

[options]

[build_requires]

[buildenv]
CC=/home/dev/bin/GCC-8.5-abi/bin/gcc
CXX=/home/dev/bin/GCC-8.5-abi/bin/g++

```

### Steps to reproduce

1. Install gcc 8.5
```
yum update
yum install texinfo gcc gcc-c++ wget bzip2 make

wget https://ftp.gnu.org/gnu/gcc/gcc-8.5.0/gcc-8.5.0.tar.gz
tar xvf gcc-8.5.0.tar.gz
cd gcc-8.5.0
./contrib/download_prerequisites
cd ..
mkdir obj
../gcc-8.5.0/configure --prefix=$HOME/bin/GCC-8.5-abi --disable-multilib --enable-languages=c,c++ --disable-libsanitizer
make -j 8
```
2. Create `conanfile.txt`
```
[requires]
sbepp/1.2.0

[generators]
CMakeDeps
CMakeToolchain
```

3. Run conan
 
```
target_directory=build

[ -e $target_directory ] || mkdir $target_directory
cd $target_directory

GCC_HOME=~/bin/GCC-8.5-abi/

export PATH=$PATH:$GCC_ROOT/bin
export CC=$GCC_ROOT/bin/gcc
export CXX=$GCC_ROOT/bin/g++
export LD_LIBRARY_PATH=$GCC_ROOT/lib64:$LD_LIBRARY_PATH

conan install \
   --build=missing \
   --profile:host=gcc8-abi \
   --profile:build=gcc8-abi \
   --settings build_type=Debug \
   ../conanfile.txt
```

### Logs

<details><summary>Click to expand log</summary>

```
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
[buildenv]
CC=/home/dev/bin/GCC-8.5-abi/bin/gcc
CXX=/home/dev/bin/GCC-8.5-abi/bin/g++

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
[buildenv]
CC=/home/dev/bin/GCC-8.5-abi/bin/gcc
CXX=/home/dev/bin/GCC-8.5-abi/bin/g++

conanfile.txt: Installing package
Requirements
    fmt/10.2.0 from 'conancenter' - Cache
    pugixml/1.14 from 'conancenter' - Cache
    sbepp/1.2.0 from 'conancenter' - Cache
Packages
    fmt/10.2.0:ab262367005d9815ff9c0df299cf52bb8511be00 - Build
    pugixml/1.14:038f8796e196b3dba76fcc5fd4ef5d3d9c6866ec - Build
    sbepp/1.2.0:INVALID - Invalid

Installing (downloading, building) binaries...
ERROR: There are invalid packages (packages that cannot exist for this configuration):
sbepp/1.2.0: Invalid ID: sbepp/1.2.0 requires C++17, which your compiler does not support.
```

</details>

**Comment by RubenRBS** [comment]
Hi! Thanks a lot for the report. Are you planning on opening the PR yourself now that you have done most of the work?

**Comment by ujos** [comment]
Ok, let me try if gcc 8.1 can compile the code too.

**Comment by ujos** [comment]
Waiting for the access approve: https://github.com/conan-io/conan-center-index/issues/4#issuecomment-2017855162

**Comment by ujos** [comment]
Done

**Comment by OleksandrKvl** [comment]
For the reference, it shouldn't work with `gcc-8.x` because it uses `std::filesystem` and [here](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017) you can find that on `gcc-8.x` it requires to link against `stdc++fs` which `sbepp` doesn't (and won't) do. When I tried it locally, I could build it but it crashed at run-time so I don't know how @ujos made it work, maybe they compiled it with newer `libstdc++` version or added `-lstdc++fs` flag manually somehow. On [godbolt](https://godbolt.org/z/9156Ej3ej) it doesn't even link.

**Comment by ujos** [comment]
@OleksandrKvl I built gcc8 on CentOS 7.5 and now additional parameters were provided

**Comment by ujos** [comment]
Maybe CMake added `-lstdc++fs`
