### ISSUE TITLE
[request] SDL/1.2.15

### ISSUE THREAD

**Issue by bb010g** [conan-io/conan-center-index#2343]
### Package Details
  * Package Name/Version: **SDL/1.2.15**
  * Website: **https://www.libsdl.org/download-1.2.php**
  * Source code: **https://www.libsdl.org/release/SDL-1.2.15.tar.gz**

### Description Of The Library / Tool
Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D.

<https://github.com/bincrafters/conan-sdl2>{,_{[image](https://github.com/bincrafters/conan-sdl2_image),[mixer](https://github.com/bincrafters/conan-sdl2_mixer),[ttf](https://github.com/bincrafters/conan-sdl2_ttf)}} exist, but only they only cover SDL2. Ideally, there'd be SDL, SDL_gfx, SDL_mixer, SDL_net, and SDL_ttf recipes.

**Comment by Croydon** [comment]
As Bincrafters we are migrating all packages eventually, but often we need to port many other dependencies first or even create new Conan features first before we can do it.

SDL2, SDL2_image, SDL2_mixer and SDL2_ttf will certainly be migrated at some point, until then feel free to continue using the Bincrafers' variants

For the other SDL libraries someone would need to step up and create such recipes. But also please keep library requests atomic, so if you want all of them please create individual issues for them

**Comment by valgur** [comment]
Can be closed. SDL is available on CCI: https://conan.io/center/recipes/sdl

**Comment by Croydon** [comment]
@valgur This is specifically about SDL 1 which is not compatible with SDL 2. This issue is still relevant.

**Comment by perseoGI** [comment]
Hi there, I'm closing this issue as SDL1 is not available in GitHub nor in SDL webpage. 
SDL2 was first released 2 years after this issue were open and right now the stable version is `2.30.9`. 

There is also an open PR for adding support to SDL3 (which is still not stable) in https://github.com/conan-io/conan-center-index/pull/25873

See https://libsdl.org/

Happy coding 🐸

**Comment by Croydon** [comment]
> SDL1 is not available in GitHub nor in SDL webpage.

It is available here https://github.com/libsdl-org/SDL-1.2

> SDL2 was first released 2 years after this issue were open

SDL 2 exists since 2013, https://github.com/libsdl-org/SDL/tree/release-2.0.0


But yeah, might not be relevant anymore to have SDL1 native. Sdl12-compat might be more interesting https://github.com/libsdl-org/sdl12-compat
