### ISSUE TITLE
[service] No space left on device

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#2344]
Some windows agents report `No space left on device` but apparently the machines have enough space available for the execution

Jobs affected:
- https://github.com/conan-io/conan-center-index/pull/2251#issuecomment-666541983
- https://github.com/conan-io/conan-center-index/pull/2334#issuecomment-666472063

**Comment by madebr** [comment]
Maybe this has something to do with the aws-sdk-cpp recipe at https://github.com/conan-io/conan-center-index/pull/1146#issuecomment-667414635 ?
