### ISSUE TITLE
[conan.io/center] Some fields should match the recipe revision

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#2346]
When new packages are uploaded some fields override values that should remain untouched. For example

![image](https://user-images.githubusercontent.com/10808592/89023162-692b8f80-d323-11ea-855a-ddd97819e0dd.png)

The above information shows the `optional-lite` page with the information correct.

Then we changed the "description" field to "Fake description" in the recipe and a new recipe revision and the package is generated, showing this:

![image](https://user-images.githubusercontent.com/10808592/89023294-a1cb6900-d323-11ea-8390-53efcaa60d9d.png)

That info is correct as well, however, when selecting the old recipe revision, the description has been updated as well, which is not correct:

![image](https://user-images.githubusercontent.com/10808592/89023419-d8a17f00-d323-11ea-939d-15aad60fb87b.png)
![image](https://user-images.githubusercontent.com/10808592/89023449-e1925080-d323-11ea-88ab-160f88868b86.png)

The information of each recipe revision should be kept and not updated to the latest recipe revision. Navigating through different recipe revision should provide the information the package had at that point. 

Note that this is showing the description, but any other information should behave the same: topics, URLs, dependencies, license...

**Comment by danimtb** [comment]
Maybe this just a UI issue and the data coming from the database is fine, pinging @aarvyved here

**Comment by danimtb** [comment]
@ankushchadha @shrajfr12 we have to check if the information is correct in the DB and this is just a UI issue.

Both requests for both recipe revision were done with flag `force = true`, but not sure if that is related.

**Comment by danimtb** [comment]
I did another test here https://github.com/conan-io/conan-center-index/pull/2347 in production (`force` flag is NOT used)  changing the description but got no update in the UI 😞

**Comment by Croydon** [comment]
I think that this is effectively a duplicate of https://github.com/conan-io/conan-center-index/issues/831

Both issues describe the problem that all meta data is the same for a recipe regardless of version and revision

**Comment by danimtb** [comment]
yep, #831 but in a more general sense in this issue. I will keep both open as this one provides useful information over the other issue. thanks

**Comment by danimtb** [comment]
This is an old issue referencing the "old" web. With the current one, this is not a problem anymore. Closing this issue as solved.
