### ISSUE TITLE
[question][simdjson]: why block gcc 9 with libstdc++11 when they work just fine?

### ISSUE THREAD

**Issue by Jie-Cheng** [conan-io/conan-center-index#23474]
### What is your question?

gcc 9 with libstdc++11 is explicitly banned in the [recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/simdjson/all/conanfile.py#L75-L80). I commented these lines out and was able to install simdjson locally, I tried using the library in the code everything worked just fine.

**Comment by Ahajha** [comment]
Looks like it was added here: https://github.com/conan-io/conan-center-index/commit/0b0039e68ee6ea5956877b387bf78427a0566dfc

My guess is that an earlier version had a bug that has since been fixed.
