### ISSUE TITLE
PROJ 9.4.0

### ISSUE THREAD

**Issue by dvargas74** [conan-io/conan-center-index#23482]
### What is your question?

Hi!
I would like to know when PROJ 9.4.0 will be available in Conancenter
Thanks,

**Comment by dvargas74** [comment]
Hello guys!

Any update about this?

**Comment by valgur** [comment]
@dvargas74 There's an open PR #21512 for it. It's almost ready to be merged. Just needs to be reviewed.

**Comment by dvargas74** [comment]
Thank you so much!

**Comment by dvargas74** [comment]
Hi!

Do you have any update?
