### ISSUE TITLE
[service] macos cross-compilation ordering

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-center-index#23558]
### What is your problem/feature request?

comes from https://cpplang.slack.com/archives/C41CWV9HA/p1711022464815949

I think there an ordering problem between conan 2 macos-clang and macos-m1-clang runners (cf https://github.com/conan-io/conan-center-index/pull/23191#issuecomment-2012071902)
In case of a package building an executable, the macos ARM (M1) should be built first, because it is used both when targetting the ARM and X86_64 arch. In other words, native compilation has to be scheduled before cross-compilation, which seems to be sequenced backwards currently.
see also
https://github.com/conan-io/conan-center-index/pull/21622#issuecomment-2011268669
https://github.com/conan-io/conan-center-index/pull/22378#issuecomment-1976439636

@danimtb @RubenRBS @uilianries 

PS: retriggering build never works around this situation, because the order is always wrong.

**Comment by ericLemanissier** [comment]
The team clearly stated that this won't happen. The following recipes now need contributors to fix them and make sure that the test_package does not `tool_requires` the tested reference:
```
libtool/all/test_package/conanfile.py
mbits-lngs/all/test_package/conanfile.py
mfast/all/test_package/conanfile.py
extra-cmake-modules/all/test_package/conanfile.py
grpc/all/test_package/conanfile.py
tree-gen/all/test_package/conanfile.py
flatcc/all/test_package/conanfile.py
btyacc/all/test_package/conanfile.py
protobuf-c/all/test_package/conanfile.py
wayland/all/test_package/conanfile.py
cfgfile/all/test_package/conanfile.py
libtasn1/all/test_package/conanfile.py
ignition-cmake/all/test_package/conanfile.py
gsoap/all/test_package/conanfile.py
flex/all/test_package/conanfile.py
```
(list comes from https://github.com/conan-io/conan-center-index/pull/23594#issuecomment-2060996942)

Qt is not worth changing anything, because the recipe does not support cross-compilation, and won't do in a foreseeable future

**Comment by RubenRBS** [comment]
Thanks for the recipe traceability on what needs fixing @ericLemanissier - appreciated :)
