### ISSUE TITLE
[question] new versions of glib 

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-center-index#23557]
### What is your question?

Since glib 2.79.0, glib uses python's `packaging` [module ](https://pypi.org/project/packaging/) (cf https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3740 at build time and run time. this module is not installed in conan-center CI runners, which prevents from building all versions of glib since 2.79.0 (cf https://github.com/conan-io/conan-center-index/pull/21874 https://github.com/conan-io/conan-center-index/pull/23093)
Conan team rejected all the solutions proposed by the community(https://github.com/conan-io/conan-docker-tools/pull/554 https://github.com/conan-io/conan-center-index/pull/23091)
glib does not intend to drop the dependency on this `packaging` module : https://gitlab.gnome.org/GNOME/glib/-/issues/3301

What's the plan ? 

@uilianries @memsharded

**Comment by valgur** [comment]
I'm feeling foolish enough to take this one on... Here's my humble attempt: #23559

**Comment by ericLemanissier** [comment]
https://github.com/conan-io/conan-center-index/pull/24165
