### ISSUE TITLE
[package] qt/5.x: Recipe validation errors are hard to diagnose

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-center-index#23567]
### Description

I realise this is probably not a particularly high priority, but it's difficult to diagnose:

```
ERROR: conanfile.py (qt/5.15.13): Error in configure() method, line 271
	_enablemodule(module)
while calling '_enablemodule', line 260
	setattr(self.options, mod, True)
	ConanException: Incorrect attempt to modify option 'qtmultimedia' from 'False' to 'True'
```

As meaning that I have to set `qt/*:essential_modules=False` in order for the recipe to validate. I can probably fix this myself but it might be a quick fix for someone more familiar with the recipe.

### Package and Environment Details

* Package Name/Version: **qt/5.15.13**
* Conan version: **conan 2.2.2**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

### Steps to reproduce

```
conan create recipes/qt/5.x.x/ --version 5.15.13 -o 'qt/*:qtmultimedia=False' --build missing
```

### Logs

```
======== Computing dependency graph ========
ERROR: conanfile.py (qt/5.15.13): Error in configure() method, line 271
	_enablemodule(module)
while calling '_enablemodule', line 260
	setattr(self.options, mod, True)
	ConanException: Incorrect attempt to modify option 'qtmultimedia' from 'False' to 'True'

```

**Comment by ericLemanissier** [comment]
@planetmarshall can you try with https://github.com/conan-io/conan-center-index/pull/23571 ?

**Comment by planetmarshall** [comment]
LGTM, thanks.
