### ISSUE TITLE
[package] libglvnd/1.7.0: Cannot load recipe

### ISSUE THREAD

**Issue by Mercotui** [conan-io/conan-center-index#23620]
### Description

While trying to consume glfw/3.4 and glew/2.2.0, I got errors about libglvnd.
The error messages told me to report the error, so here we are.

### Package and Environment Details

* Package Name/Version: **libglvnd/1.7.0**
* Operating System+version: **Linux Fedora 39**
* Compiler+version: **GCC 13**
* Conan version: **conan 2.1.0**
* Python version: **Python 3.12.2**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

### Steps to reproduce

 conan install -u -pr:b=default -pr:h=default --build=missing .

### Logs

<details><summary>Click to expand log</summary>

```
*********************************************************
Recipe 'libglvnd/1.7.0' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'libglvnd/1.7.0' not resolved: libglvnd/1.7.0: Cannot load recipe.
Error loading conanfile at '/home/menno/.conan2/p/libgl1dfa7c5ed10cc/e/conanfile.py': Current Conan version (2.1.0) does not satisfy the defined one (>=1.64.0 <2 || >=2.2.0)..
```

</details>

**Comment by Mercotui** [comment]
I see the recipe requires conan >=1.64.0 <2 || >=2.2.0, but is that really a sane requirement?

I see fedora 40 will even ship with conan 2.1.0, how many users are running the absolute latest version of this tool?

**Comment by jwillikers** [comment]
Thanks for reporting! Holdup, Fedora is shipping Conan?! Wow, I had no idea!

Unfortunately, that requirement was bumped to accommodate a functional change in Conan 1.64.0 and Conan 2.2.0, which was necessary for #23500. The Meson generator switched from needing absolute paths to using relative paths for `xxxdir` variables. It might be possible for me change the paths are set based on the Conan version to support older Conan versions. Otherwise, you'd have to pin a revision but that would be bad in this situation since that is an important fix. @franramirez688 Would you have any input on this?

**Comment by jwillikers** [comment]
I'm surprised that your pulling in `libglvnd` since my PR's to switch `glew` and `glfw` over to that haven't been merged yet.

**Comment by Mercotui** [comment]
Profile pic checks out, yeah fedora ships conan :sweat_smile: 

Thanks for the quick response, 
If it helps at all, it seems this happens when I require `glew/2.2.0`:

<details><summary>Click to expand conanfile</summary>

```
from conan import ConanFile
from conan.tools.cmake import cmake_layout


class MyRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def requirements(self):
        self.requires("glew/2.2.0")

    def layout(self):
        cmake_layout(self)
```

```
$ conan install -u -pr:b=default -pr:h=default --build=missing .

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux


======== Computing dependency graph ========
glew/2.2.0: Checking remote: conancenter
opengl/system: Checking remote: conancenter
mesa-glu/9.0.3: Checking remote: conancenter
libglvnd/1.7.0: Checking remote: conancenter
Graph root
    conanfile.py: /home/menno/Workspace/redacted/conanfile.py
Requirements
    glew/2.2.0#7ed80001a1a9686f00ccf4f4680c5f73 - Cache (conancenter)
    mesa-glu/9.0.3#94609f918d5ca4e5fea0f7a985b29f68 - Cache (conancenter)
    opengl/system#4df6fecde4084386beded3ed0e56e4ea - Cache (conancenter)
*********************************************************
Recipe 'libglvnd/1.7.0' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'libglvnd/1.7.0' not resolved: libglvnd/1.7.0: Cannot load recipe.
Error loading conanfile at '/home/menno/.conan2/p/libgl1dfa7c5ed10cc/e/conanfile.py': Current Conan version (2.1.0) does not satisfy the defined one (>=1.64.0 <2 || >=2.2.0)..

```
</details>

And a small note that I am not very invested in getting this working on my system, I was only installing this package to compile some example code, which I managed by installing the dependencies via yum :grimacing:

**Comment by Mercotui** [comment]
Hey,
With "sane" I meant that the conan version I use is 2 months old, and I am surprised that it is not supported by these packages. I thought this might have been an error or oversight.

As far as updating my conan.. I used the version my OS packages,
so to upgrade in this case means to install it via a different path.

Updating conan is possible, but for me it is more work than not using conan.
I was 5 minutes into my project with conan, and instead I decided to use yum to install my dependencies.

I found I don't need glew or glfw at this point in time, so I'll try to continue to use conan 2.1.0 unless I run into similar issues with packages that I do want.

**Comment by Mercotui** [comment]
I ran into this conan version issue again, this time with `wayland/1.22.0`, and I really want the package.

So I did the following:

```
sudo yum remove conan
sudo yum install pipx
pipx install conan
```

Which I guess is a good compromise for me.
I hope this gives me the latest version of conan,
without having to deal with python dependency pain.

**Comment by franramirez688** [comment]
@Mercotui did you have any problem installing the latest one?
If not, I think that we could close this ticket as solved.

**Comment by Mercotui** [comment]
Sure I'll close the ticket as resolved,
I am satisfied with my current setup.

Thanks for sharing your insight :+1:
