### ISSUE TITLE
[package] zlib/1.2.11: cmake find_package generates wrong filename

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan-center-index#237]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.11**
  * Conan version: **conan 1.19.1**
  * Python version: **Python 3.7.4**

### Conan profile 
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)
Create conanfile.txt with contents:

```
[requires]
boost/1.71.0

[generators]
cmake_find_package
cmake_paths
```

CMakeLists.txt:

```
include(${CMAKE_BINARY_DIR}/conan_paths.cmake)

find_package(boost REQUIRED)
```

Run

```
$ mkdir build && cd build
$ conan install ..
$ cmake ..
```

Expected: boost is found by CMake.

Actual: 
```
By not providing "Findzlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "zlib", but
  CMake did not find one.
```

I'm pretty sure this is the offending commit: https://github.com/conan-io/conan-center-index/commit/eda6295c4d5cfa725bf2f00a7dd15f35c306018c but I suspect there was a reason for making the change. If I rename `FindZLIB.cmake` to `Findzlib.cmake`, it finds the package successfully. This is because the generated `Findboost.cmake` contains this line:

```
    find_dependency(zlib REQUIRED)
```

cc @uilianries

**Comment by sztomi** [comment]
Oh, I see this is the PR: https://github.com/conan-io/conan-center-index/pull/217

I think it would be best to revert that, or rename the zlib package to ZLIB, otherwise everything depending on it will be broken when using the cmake find_package generator.

**Comment by SSE4** [comment]
@sztomi see https://github.com/conan-io/conan/pull/5973, to be fixed in conan 1.9.3

**Comment by sztomi** [comment]
@SSE4 Thanks for the heads-up, but conan has a stability guarantee for 1.x, and this recipe will be broken with prior versions unless that change is rolled back.

**Comment by SSE4** [comment]
@sztomi I believe this stability guarantee applies to the conan client itself.
as for recipes I guess the policy is to be compatible with the latest release
https://github.com/conan-io/conan-center-index/wiki
```
Make sure you are using the latest Conan client version, the recipes might evolve introducing features of the newer Conan releases
```

**Comment by sztomi** [comment]
Fair enough!

**Comment by danimtb** [comment]
@sztomi was your question solved? Can we close this issue? thanks
