### ISSUE TITLE
[request] libcbor/0.7.0

### ISSUE THREAD

**Issue by afedechko** [conan-io/conan-center-index#2385]
Is this possible to update the recipe for the cbor package, so that it provides possibility to configure library. 

The libcbor library has a define that changes how the library works: https://libcbor.readthedocs.io/en/v0.5.0/api/item_reference_counting.html#using-custom-allocator

Currently, I'm not sure if there is a way to "tell" via conan that once library is build it should also include some specific defines.

Would it be possible to extend (change) https://conan.io/center/libcbor/0.7.0/?revision=&os=&tab=recipe so that consumers can just add something like:

```
[options]
libcbor:custom_alloc=true/false
```
and the recipe it self would be:

```
...
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "custom_alloc": [True, False],
    }
...
    def _configure_cmake(self):
        if self._cmake:
            return self._cmake
        self._cmake = CMake(self)
        self._cmake.definitions["WITH_EXAMPLES"] = False
        self._cmake.definitions["SANITIZE"] = False
        if (self.options.custom_alloc == True)
            cmake.definitions["CBOR_CUSTOM_ALLOC"] = ''
...
```
initial discussion has been started here: https://github.com/PJK/libcbor/issues/147

Thanks

**Comment by uilianries** [comment]
Hi @afedechko , please feel free opening a new PR with that change, but try something simpler:


```python
options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "custom_alloc": [True, False],
    }
...
    def _configure_cmake(self):
        if self._cmake:
            return self._cmake
        self._cmake = CMake(self)
        self._cmake.definitions["WITH_EXAMPLES"] = False
        self._cmake.definitions["SANITIZE"] = False
        self._cmake.definitions["CBOR_CUSTOM_ALLOC"] = self.options.custom_alloc
...

```

CBOR_CUSTOM_ALLOC is a boolean option and CMake helper is able to convert Python bool to CMake "ON"/ "OFF" automatically.

Please, read the [How to collaborate](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for further information. If you have any question, feel free to ask.

**Comment by afedechko** [comment]
Thank you, @uilianries 
I'll create one (finally understood what PR means ;) )

However, I'd like to ask you about the hook, to test the package. 
Can the hook (https://github.com/conan-io/hooks#conan-center) be used to test if the changes I added into the recipe affects the library compilation ?

**Comment by uilianries** [comment]
> Can the hook (https://github.com/conan-io/hooks#conan-center) be used to test if the changes I added into the recipe affects the library compilation ?

What do mean, the library generated? No. For now, CCI hooks is more a linter than a binary sanitizer.
