### ISSUE TITLE
[request] <folly>/<v2024.05.02.00>

### ISSUE THREAD

**Issue by AndreyKulikov2022** [conan-io/conan-center-index#23892]
### Package Name/Version

folly/v2024.05.02.00

### Changelog

https://github.com/facebook/folly/releases

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

Downloading the latest existing version `folly/2022.01.31.00` with Conan 2.0 leads to a message:
```
Recipe 'folly/2022.01.31.00' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
```
And an error:
```
 ERROR: Package 'folly/2022.01.31.00' not resolved: folly/2022.01.31.00: Cannot load recipe.
Error loading conanfile at '/pawemm/build-ci/.conan2/p/follyb9f3904b291ef/e/conanfile.py': Unable to load conanfile in /pawemm/build-ci/.conan2/p/follyb9f3904b291ef/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/pawemm/build-ci/.conan2/p/follyb9f3904b291ef/e/conanfile.py", line 6, in <module>
    from conans import CMake, tools
ImportError: cannot import name 'CMake' from 'conans' (/usr/local/lib/python3.11/dist-packages/conans/__init__.py)
```

**Comment by uilianries** [comment]
@AndreyKulikov2022 Indeed Folly is not ported to Conan 2.x yet, buy the pull request https://github.com/conan-io/conan-center-index/pull/21109 is doing its port. Please, take a look there if you have suggestions.

**Comment by AndreyKulikov2022** [comment]
I see, thank you!

**Comment by uilianries** [comment]
Version 2024.08.12.00 of Folly is now available in Conan Center. Also, it's available for Conan 2.x now.
