### ISSUE TITLE
libwebsockets: error building when not using OpenSSL

### ISSUE THREAD

**Issue by jcar87** [conan-io/conan-center-index#23899]
@jcar87  I think I found the  issue. I am building libwebsockets withnout ssl : `"libwebsockets:with_ssl": False,` 
This cause this failure. When I remove this option then the build succeeds

@memsharded @uilianries FYI 🙏🙏

Thanks

_Originally posted by @oavitzur in https://github.com/conan-io/conan-center-index/issues/23831#issuecomment-2094689371_

**Comment by jcar87** [comment]
thanks @oavitzur, will fix this

**Comment by ericLemanissier** [comment]
=> https://github.com/conan-io/conan-center-index/pull/23853
