### ISSUE TITLE
[package] yasm/1.3.0: Non-ascii character in description causes python error

### ISSUE THREAD

**Issue by alanbirtles** [conan-io/conan-center-index#239]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **yasm/1.3.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 7.4**
  * Conan version: **conan 1.19.2**
  * Python version: **Python 2.7.15+*

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Put your profile output here
```

### Steps to reproduce (Include if Applicable)

Install yasm/1.3.0

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
yasm/1.3.0: Not found in local cache, looking in remotes...
yasm/1.3.0: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 106/106 [00:00<00:00, 101kB/s]
Downloading conanfile.py: 100%|##########| 3.05k/3.05k [00:00<00:00, 3.24MB/s]
Downloading conan_export.tgz: 100%|##########| 257/257 [00:00<00:00, 231kB/s]
Decompressing conan_export.tgz: 265B [00:00, 207kB/s]                    
yasm/1.3.0: Downloaded recipe revision 0
ERROR: Error loading conanfile at '/home/gbbirtla/.conan/data/yasm/1.3.0/_/_/export/conanfile.py': Unable to load conanfile in /home/gbbirtla/.conan/data/yasm/1.3.0/_/_/export/conanfile.py
  File "/home/gbbirtla/.conan/data/yasm/1.3.0/_/_/export/conanfile.py", line 10
SyntaxError: Non-ASCII character '\xe2' in file /home/gbbirtla/.conan/data/yasm/1.3.0/_/_/export/conanfile.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

</details>

**Comment by uilianries** [comment]
Well, @jgsogo warned us about this situation ... We could add the encoding information, but it seems be easier to be fixed.
