### ISSUE TITLE
[package] open62541/1.3.3: mbedtls/2.16.3 integration issue

### ISSUE THREAD

**Issue by james94** [conan-io/conan-center-index#23930]
### Description

When I created open62541 conan package with encryption set to mbedtls, I get an integration issue where open62541 complains about not being able to find mbedtls headers.

I did find a solution to solve this integration issue by updating the mbedtls conan recipe. So, I will later create a follow up PR for mbedtls that allows us to create open62541 conan package with encryption set to mbedtls.

### Package and Environment Details

* Package Name/Version: **open62541/1.3.3**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 11.4.0**
* Docker image: My Own Docker Image on Ubuntu 22.04 and GCC 11.4.0
* Conan version: **conan 2.2.3**
* Python version: **Python 3.10.12**

### Conan profile

[settings]
os=Linux
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=11
[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True
[options]

### Steps to reproduce

Create Open62541 Conan Package with encryption set to mbedtls:

~~~bash
pushd open62541/all

# path to profile will be different, but you can use the profile I shared above
conan create . --version=1.3.3 --user=minifi --channel=dev --build=missing -pr=$HOME/src/james/pipeline/nifi-minifi-cpp/etc/build/conan/profiles/release-linux
~~~

### Logs

<details><summary>Logs not included. I will include a proposed solution</summary>

```
open62541 will complain about not being able to find mbedtls headers.
```

</details>

**Comment by czoido** [comment]
Hi @james94,

Thanks a lot for reporting this and sorry for the late response. I could reproduce and will submit a fix for this to the Open62541 recipe.
