### ISSUE TITLE
[package] boost / 1.71.0 : missing package ca891ed5c8e67ebb3e46639c100abdbca6d8b11e

### ISSUE THREAD

**Issue by ansnsaterno** [conan-io/conan-center-index#23947]
### Description

Without any local changes multiple internal builds started failing on May 8 with the following error:

Installing (downloading, building) binaries...
ERROR: Missing binary: boost/1.71.0:ca891ed5c8e67ebb3e46639c100abdbca6d8b11e

Did not expect the error as the builds had run fine for months with the boost / 1.71.0 package.  Found a workaround solution yesterday that uses a local copy of the boost / 1.71.0 package from our artifactory server.

Convienently, a co-worker had saved a conan search for the boost / 1.71.0 package the week prior.  A zip file has been attached with the two search results for boost / 1.71.0, one from May 2, and one from May 8.  There are 23 different package_ids from the May 2nd search, and only 14 package_ids from the May 8th search.

[ConanBoostSearchResults.zip](https://github.com/conan-io/conan-center-index/files/15274958/ConanBoostSearchResults.zip)

### Package and Environment Details

* Package Name/Version: **boost/1.71.0**
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **GCC 9**
* Conan version: **conan 1.60.0**
* Python version: **Python 3.11**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11

ipopt:compiler.version=8.2

[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True

[options]
ipopt:mkl_link=static
ipopt:mkl_version=2023.1.0

### Steps to reproduce

conan install -r conancenter boost/1.71.0@ -pr:b=default -pr:h=default

### Logs

<details><summary>Click to expand log</summary>

```
Installing (downloading, building) binaries...
ERROR: Missing binary: boost/1.71.0:9122dbc53b72d49447592b7c1471ee184105ccbd
ERROR: Missing binary: bzip2/1.0.8:53b5fd22ba061620078deefdae9a437c5f693201
ERROR: Missing binary: zlib/1.3.1:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b

bzip2/1.0.8: WARN: Can't find a 'bzip2/1.0.8' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=17, os=Windows
- Options: build_executable=True, shared=False
- Dependencies:
- Requirements:
- Package ID: 53b5fd22ba061620078deefdae9a437c5f693201

ERROR: Missing prebuilt package for 'boost/1.71.0', 'bzip2/1.0.8', 'zlib/1.3.1'
Use 'conan search bzip2/1.0.8@ --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=boost --build=bzip2 --build=zlib'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

</details>

**Comment by uilianries** [comment]
@ansnsaterno Hello, the package for Boost 1.71.0, built with GCC 9 is available in Conan Center:

```
conan search -r conancenter "boost/1.71.0@" -q "compiler=gcc AND compiler.version=9"                                                                                                                                     
Existing packages for recipe boost/1.71.0:

Existing recipe in remote 'conancenter':

    Package_ID: 15e881cf4fa352877c6f626d88a3b9471860ac90
        [options]
            addr2line_location: /usr/bin/addr2line
            asio_no_deprecated: False
            buildid: None
            bzip2: True
            diagnostic_definitions: False
            error_code_header_only: False
            extra_b2_flags: None
            filesystem_no_deprecated: False
            filesystem_use_std_fs: False
            header_only: False
            i18n_backend_iconv: libc
            i18n_backend_icu: False
            layout: system
            lzma: False
            magic_autolink: False
            multithreading: True
            namespace: boost
            namespace_alias: False
            numa: True
            segmented_stacks: False
            shared: True
            system_no_deprecated: False
            system_use_utf8: False
            visibility: hidden
            with_stacktrace_backtrace: True
            without_atomic: False
            without_chrono: False
            without_container: False
            without_context: False
            without_contract: False
            without_coroutine: False
            without_date_time: False
            without_exception: False
            without_fiber: False
            without_filesystem: False
            without_graph: False
            without_graph_parallel: True
            without_iostreams: False
            without_locale: False
            without_log: False
            without_math: False
            without_mpi: True
            without_program_options: False
            without_python: True
            without_random: False
            without_regex: False
            without_serialization: False
            without_stacktrace: False
            without_system: False
            without_test: False
            without_thread: False
            without_timer: False
            without_type_erasure: False
            without_wave: False
            zlib: True
            zstd: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.libcxx: libstdc++11
            compiler.version: 9
            os: Linux
        [requires]
            bzip2/1.0.8:da606cf731e334010b0bf6e85a2a6f891b9f36b0
            libbacktrace/cci.20210118:6af9cc7cb931c5ad942174fd7838eb655717c709
            zlib/1.3.1:6af9cc7cb931c5ad942174fd7838eb655717c709
        Outdated from recipe: False
``` 

The package ID that you are looking for `ca891ed5c8e67ebb3e46639c100abdbca6d8b11e` does not match. Probably, you are using different combination of options and settings. Please, check your Conan cache, trying cleaning it by remove Boost package and its recipes, than installing again.

```
conan remove --force "boost"
conan install -r conancenter boost/1.71.0@ -pr:b=default -pr:h=default
```

Please, also confirm your profiles, because you described as GCC, but your log shows Windows MSVC.

**Comment by ansnsaterno** [comment]
Hello @uilianries I accidentally tried re-creating locally on windows instead of the Linux build machine.  Here is the error from linux, using:

conan install -r conancenter boost/1.71.0@ -pr:b=default -pr:h=default

Looking for the shared = false version

Is there a reason there would be fewer configurations in the package from last week?

user@892bc4d091b9:/src/Build$ cat conanprofile.txt
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release

[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=true

[options]
[build_requires]
[env]
user@892bc4d091b9:/src/Build$ conan remove --force "boost"
WARN: Remotes registry file missing, creating default one in /home/user/.conan/remotes.json
WARN: No package recipe matches 'boost'
user@892bc4d091b9:/src/Build$ conan install -r conancenter boost/1.71.0@ -pr:b=default -pr:h=default
Auto detecting your dev setup to initialize the default profile (/home/user/.conan/profiles/default)
Found gcc 9
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************

Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/home/user/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************



Default settings
        os=Linux
        os_build=Linux
        arch=x86_64
        arch_build=x86_64
        compiler=gcc
        compiler.version=9
        compiler.libcxx=libstdc++
        build_type=Release
*** You can change them in /home/user/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

boost/1.71.0: Retrieving from server 'conancenter'
boost/1.71.0: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [1.23k]
Downloading conanfile.py completed [93.20k]
Downloading conan_export.tgz completed [1.65k]
Decompressing conan_export.tgz completed [0.00k]
boost/1.71.0: Downloaded recipe revision 89112620cd950284bec3c01635a69a64
zlib/1.3.1: Retrieving from server 'conancenter'
zlib/1.3.1: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.18k]
Downloading conanfile.py completed [4.09k]
Downloading conan_export.tgz completed [0.43k]
Decompressing conan_export.tgz completed [0.00k]
zlib/1.3.1: Downloaded recipe revision f52e03ae3d251dec704634230cd806a2
bzip2/1.0.8: Retrieving from server 'conancenter'
bzip2/1.0.8: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.17k]
Downloading conanfile.py completed [4.00k]
Downloading conan_export.tgz completed [0.31k]
Decompressing conan_export.tgz completed [0.00k]
bzip2/1.0.8: Downloaded recipe revision 457c272f7da34cb9c67456dd217d36c4
libbacktrace/cci.20210118: Retrieving from server 'conancenter'
libbacktrace/cci.20210118: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.28k]
Downloading conanfile.py completed [3.84k]
Downloading conan_export.tgz completed [0.41k]
Decompressing conan_export.tgz completed [0.00k]
libbacktrace/cci.20210118: Downloaded recipe revision ec1aa63bbc10145c6a299e68e711670c
Version ranges solved
    zlib/* versions found in 'conancenter' remote
    Version range '>=1.2.11 <2' required by 'boost/1.71.0' resolved to 'zlib/1.3.1' in remote 'conancenter'

Installing package: boost/1.71.0
Requirements
    boost/1.71.0 from 'conancenter' - Downloaded
    bzip2/1.0.8 from 'conancenter' - Downloaded
    libbacktrace/cci.20210118 from 'conancenter' - Downloaded
    zlib/1.3.1 from 'conancenter' - Downloaded
Packages
    boost/1.71.0:adf48b8e4446dcb68f440fe42ff08878d5c7feed - Missing
    bzip2/1.0.8:da606cf731e334010b0bf6e85a2a6f891b9f36b0 - Download
    libbacktrace/cci.20210118:6af9cc7cb931c5ad942174fd7838eb655717c709 - Download
    zlib/1.3.1:6af9cc7cb931c5ad942174fd7838eb655717c709 - Download

Installing (downloading, building) binaries...
ERROR: Missing binary: boost/1.71.0:adf48b8e4446dcb68f440fe42ff08878d5c7feed

boost/1.71.0: WARN: Can't find a 'boost/1.71.0' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++, compiler.version=9, os=Linux
- Options: addr2line_location=/usr/bin/addr2line, asio_no_deprecated=False, buildid=None, bzip2=True, debug_level=0, diagnostic_definitions=False, error_code_header_only=False, extra_b2_flags=None, fPIC=True, filesystem_no_deprecated=False, filesystem_use_std_fs=False, filesystem_version=None, header_only=False, i18n_backend=deprecated, i18n_backend_iconv=libc, i18n_backend_icu=False, layout=system, lzma=False, magic_autolink=False, multithreading=True, namespace=boost, namespace_alias=False, numa=True, pch=True, python_executable=None, python_version=None, segmented_stacks=False, shared=False, system_no_deprecated=False, system_use_utf8=False, visibility=hidden, with_stacktrace_backtrace=True, without_atomic=False, without_chrono=False, without_container=False, without_context=False, without_contract=False, without_coroutine=False, without_date_time=False, without_exception=False, without_fiber=False, without_filesystem=False, without_graph=False, without_graph_parallel=True, without_iostreams=False, without_locale=False, without_log=False, without_math=False, without_mpi=True, without_program_options=False, without_python=True, without_random=False, without_regex=False, without_serialization=False, without_stacktrace=False, without_system=False, without_test=False, without_thread=False, without_timer=False, without_type_erasure=False, without_wave=False, zlib=True, zstd=False, bzip2:build_executable=True, bzip2:fPIC=True, bzip2:shared=False, libbacktrace:fPIC=True, libbacktrace:shared=False, zlib:fPIC=True, zlib:shared=False
- Dependencies: zlib/1.3.1, bzip2/1.0.8, libbacktrace/cci.20210118
- Requirements: bzip2/1.Y.Z, libbacktrace/cci.20210118, zlib/1.Y.Z
- Package ID: adf48b8e4446dcb68f440fe42ff08878d5c7feed

ERROR: Missing prebuilt package for 'boost/1.71.0'
Use 'conan search boost/1.71.0@ --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=boost'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

**Comment by Nekto89** [comment]
You should probably change `compiler.libcxx=libstdc++` to `compiler.libcxx=libstdc++11` in your profile

**Comment by uilianries** [comment]
@ansnsaterno You described a custom profile (conanprofile.txt) with `compiler.libcxx=libstdc++11`, but you used your default profile instead:

    user@892bc4d091b9:/src/Build$ conan install -r conancenter boost/1.71.0@ -pr:b=default -pr:h=default
    
You need to use your profile instead:

    $ conan install -r conancenter boost/1.71.0@ -pr:b=default -pr:h=conanprofile.txt

----

BTW, I see you are still using Conan 1.x. I strongly recommend you migrating to Conan 2.x, which is stable andis >1 year old now. Conan 1.x no longer receives new features, only bug and security fixes.

**Comment by uilianries** [comment]
Closing this issue as looks fixed and was a misconfiguration, not a recipe bug.

Please, feel free to re-open it in order to share your feedback. Regards.
