### ISSUE TITLE
[package] zstd/1.5.6: unknown warning option

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan-center-index#23969]
### Description

zstd recipe injects compile option that isn't supported by compiler.

### Package and Environment Details

* Package Name/Version: **zstd/1.5.6**
* Operating System+version: **Linux Debian Bullseye 11.9**
* Compiler+version: **clang 11**
* Docker image: **-**
* Conan version: **conan 2.3.0**
* Python version: **Python 3.9.2**

### Conan profile

[settings]
arch=x86_64
os=Linux
compiler=clang
compiler.version=11
compiler.cppstd=17
compiler.libcxx=libstdc++11
build_type=Release
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:compiler_executables={"c":"/usr/local/bin/cc","cpp":"/usr/local/bin/c++"}

### Steps to reproduce

conan install -pr:b default -pr:h default --build=missing conanfile.py

### Logs

There is the same warning for each *.c
<details><summary>Click to expand log</summary>

```
[1/64] Building C object lib/CMakeFiles/libzstd_static.dir/mnt/ccache/.conan2/p/b/zstd963d8984462ca/b/src/lib/common/debug.c.o
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
```

</details>

**Comment by uilianries** [comment]
@Nekto89 Hello! Conan avoids touching the compiler configuration provided by upstream. The error you see is related to the upstream project, not the package. I would suggest ask the the upstream about that warning.

Doing a quick search, I found is a "bug" in LLVM: https://bugs.llvm.org/show_bug.cgi?id=24979

**Comment by Nekto89** [comment]
> @Nekto89 Hello! Conan avoids touching the compiler configuration provided by upstream. The error you see is related to the upstream project, not the package. I would suggest ask the the upstream about that warning.
> 
> Doing a quick search, I found is a "bug" in LLVM: https://bugs.llvm.org/show_bug.cgi?id=24979

https://github.com/conan-io/conan-center-index/blob/e6836d3f7920e92efdcc6d3db46c35fdedc4916a/recipes/zstd/all/conanfile.py#L59C13-L59C71

**Comment by uilianries** [comment]
> [`e6836d3`/recipes/zstd/all/conanfile.py#L59C13-L59C71](https://github.com/conan-io/conan-center-index/blob/e6836d3f7920e92efdcc6d3db46c35fdedc4916a/recipes/zstd/all/conanfile.py#L59C13-L59C71)

Ops! I'll take a look for a hotfix.
