### ISSUE TITLE
[package] boost/1.83.0 build failed with gcc==4.8

### ISSUE THREAD

**Issue by Rickylss** [conan-io/conan-center-index#23973]
### Description

Build boost/1.83.0 failed with gcc==4.8.  

### Package and Environment Details

* Package Name/Version: **boost/1.83.0**
* Operating System+version: **Linux Ubuntu 16.04**
* Compiler+version: **GCC 4.8**
* Conan version: **conan 1.59.0**
* Python version: **Python 2.7.12**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=4.8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter boost/1.83.0@ -pr:b=default -pr:h=default

### Logs

![企业微信截图_17156010749901](https://github.com/conan-io/conan-center-index/assets/25975144/6cfb503e-e5d9-4c82-8f1d-1b253ed3eae0)

**Comment by Rickylss** [comment]
By examining the code, I have discovered that the issue is caused by an incorrect judgment.

```diff
index 48dad5b67..9154a553e 100644
--- a/recipes/boost/all/conanfile.py
+++ b/recipes/boost/all/conanfile.py
@@ -265,7 +265,7 @@ class BoostConan(ConanFile):
             return valid_min_cppstd(self, 11)
         compiler_version = self._min_compiler_version_default_cxx11
         if compiler_version:
-            return (Version(self.settings.compiler.version) >= compiler_version) or "11" in supported_cppstd(self)
+            return (Version(self.settings.compiler.version) >= compiler_version) and "11" in supported_cppstd(self)
 
     @property
     def _has_cppstd_14_supported(self):
```
I have fixed this issue by making the modifications mentioned above.

**Comment by uilianries** [comment]
@Rickylss Thank you for providing an analyze over the case. I'll take a look on this.
