### ISSUE TITLE
protobuf latest to be available than protobuf/3.21.12

### ISSUE THREAD

**Issue by sgavathe** [conan-io/conan-center-index#24035]
### What is your question?

I have been looking for a higher version of protobuf c++ than this version `protobuf/3.21.12` , which is the highest version available under conan eco system https://conan.io/center/recipes/protobuf. 

Is work under way to have higher versions available , higher than `4025000`? 

Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
https://github.com/conan-io/conan-center-index/pull/24154

Made available this morning. Closing this as fixed, but please reopen if this is not suitable, thanks!
