### ISSUE TITLE
[package] spdlog: conandata specifies patches that no long exist

### ISSUE THREAD

**Issue by Tridacnid** [conan-io/conan-center-index#2412]
The spdlog recipe specifies patches in the conandata file but the patches were removed in https://github.com/conan-io/conan-center-index/commit/793cc487ff9a54eebbf6f4f66640f91013a18be2#diff-b4759c470525d43087a388ef7c108d54
Should the patches section of the conandata file be removed?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spdlog**

**Comment by madebr** [comment]
Indeed, the recipe does not do any `tools.patch`'ing and no patches are present.
That section can safely be removed.
