### ISSUE TITLE
[package] <SDL>/<2.30.3>: Library SDL2main not found in package

### ISSUE THREAD

**Issue by Jark5455** [conan-io/conan-center-index#24264]
### Description

attempting to use the latest version of SDL2 results in 

```
Library 'SDL2main' not found in package.  If 'SDL2main' is a system
  library, declare it with 'cpp_info.system_libs' property
```

### Package and Environment Details

* Package Name/Version: **sdl/2.30.3**
* Operating System+version: **Arch Linux**
* Compiler+version:  **GCC 14**
* Conan version: **conan 2.3.2**
* Python version: **Python 3.12.3**

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

### Steps to reproduce

call  `find_package(SDL)` in CMakeLists.txt.

### Logs

<details><summary>Click to expand log</summary>

```
-- Using Conan toolchain: /path/to/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 20 with extensions OFF
-- Conan: Component target declared 'SDL2::SDL2'
-- Conan: Component target declared 'SDL2::SDL2main'
CMake Error at cmake-build-release/cmakedeps_macros.cmake:67 (message):
  Library 'SDL2main' not found in package.  If 'SDL2main' is a system
  library, declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  cmake-build-release/SDL2-Target-release.cmake:24 (conan_package_library_targets)
  cmake-build-release/SDL2Targets.cmake:28 (include)
  cmake-build-release/SDL2Config.cmake:16 (include)
  core/CMakeLists.txt:3 (find_package)```

</details>

**Comment by RubenRBS** [comment]
Hi! Thanks a lot for your report. We've been trying to narrow this down a little these past few days, and I just realized you used:
> call find_package(SDL) in CMakeLists.txt.

but the Conan package sets the target name as `SDL2` (That's how it's used in its test package). Can you try changing it? Does that help?

**Comment by Jark5455** [comment]
Yes that worked!
