### ISSUE TITLE
[package] benchmark/1.8.4: Mac x86_64 package not found

### ISSUE THREAD

**Issue by cel-io** [conan-io/conan-center-index#24302]
### Description

When installing benchmark/1.8.4 on Mac x86_64, no package is found to be downloaded. conan.io informs that the package exists but when consulting the package table with `conan search` it appears that in fact, no Mac x86_64 builds exist, only Mac armv8 do.

I also checked some older versions and they were all missing the same package.

This might coincide with the update on 2024-05-26, since I encountered this issue on 05-28.

Using the `--build=missing` flag is the current workaround.

### Package and Environment Details

* Package Name/Version: **benchmark/1.8.4**
* Operating System+version: **macOS Monterey 12.6.5**
* Compiler+version: **apple-clang 13.1.6**
* Conan version: **conan 1.58.0**
* Python version: **Python 3.9.16**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=13.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce

`conan install -r conancenter benchmark/1.8.4@`

### Logs

<details><summary>Click to expand log</summary>

```
benchmark/1.8.4: WARN: Can't find a 'benchmark/1.8.4' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.libcxx=libc++, compiler.version=13.0, os=Macos
- Options: enable_exceptions=True, enable_lto=False, fPIC=True, shared=False
- Dependencies:
- Requirements:
- Package ID: 9e63fd2936c0b4a43222b423ad03ee6f6975cbfb

ERROR: Missing prebuilt package for 'benchmark/1.8.4'
Use 'conan search benchmark/1.8.4@ --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=benchmark'
```

</details>

**Comment by czoido** [comment]
Hi @cel-io 

Thanks for reporting, and sorry for the late response.

We are not updating the Conan 1.X repo any more, so I'm afraid that there will not be packages for this configuration. Please read this blogpost about the freeze: https://blog.conan.io/2024/09/30/Conan-Center-will-stop-receiving-updates-for-Conan-1.html

I'm closing the issue but please feel free to reopen or open a new one if you have any more questions.
