### ISSUE TITLE
[request] faker-cxx/1.0.0

### ISSUE THREAD

**Issue by meftunca** [conan-io/conan-center-index#24325]
### Package Name/Version

faker-cxx/1.0.0

### Webpage

https://cieslarmichal.github.io/faker-cxx/

### Source code

https://github.com/cieslarmichal/faker-cxx

### Description of the library/tool

It helps us create test data for the projects we develop with C++. It is designed to be similar to the faker-js library in Javascript.

**Comment by uilianries** [comment]
Let's keep it open. The PR #24018 will close the issue automatically as soon the PR is merged.

**Comment by uilianries** [comment]
@meftunca The package faker-cxx is now available in Conan Center:

```
$ conan search -r conancenter faker-cxx                                                                                                                                                                                         
Found 1 pkg/version recipes matching faker-cxx in conancenter
conancenter
  faker-cxx
    faker-cxx/2.0.0
```
