### ISSUE TITLE
[package] tensorflow/2.12.0: Cannot build with with_xnnpack=False - pthreadpool target was not found

### ISSUE THREAD

**Issue by msanna-asaphus** [conan-io/conan-center-index#24359]
### Description

I'm trying to create the package from scratch for tensorflow-lite and if I pass the option "&:with_xnnpack=False" the cmake step fails because with the target pthreadpool not found

I'm on master (https://github.com/conan-io/conan-center-index/tree/522505bd045b9f8d4417b8cd7b16a98181353f99)

### Package and Environment Details

* Package Name/Version: **tensorflow/2.12.0**
* Operating System+version: **Linux Ubuntu 22.04/WSL**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.4.1**
* Python version: **Python 3.11.9***

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

### Steps to reproduce

conan create recipes/tensorflow-lite/all --version 2.12.0 -o "&:with_xnnpack=False"

### Logs

<details><summary>Click to expand log</summary>

======== Exporting recipe to the cache ========
tensorflow-lite/2.12.0: Exporting package recipe: /home/msanna/libraries/conan-center-index/recipes/tensorflow-lite/all/conanfile.py
tensorflow-lite/2.12.0: exports: File 'conandata.yml' found. Exporting it...
tensorflow-lite/2.12.0: Calling export_sources()
tensorflow-lite/2.12.0: Copied 1 '.py' file: conanfile.py
tensorflow-lite/2.12.0: Copied 1 '.yml' file: conandata.yml
tensorflow-lite/2.12.0: Copied 3 '.patch' files: 2.12.0-0003-use-cci-dependencies.patch, 2.12.0-0002-disable-fetch-content.patch, 2.12.0-0001-remove_simple_memory_arena_debug_dump.patch
tensorflow-lite/2.12.0: Exported to cache folder: /home/msanna/.conan2/p/tenso2698f17023a1e/e
tensorflow-lite/2.12.0: Exported: tensorflow-lite/2.12.0#efaff37bc6be68c2c36a21a04d074054 (2024-06-17 08:58:43 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
&:with_xnnpack=False

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

======== Computing dependency graph ========
abseil/20230125.3: Not found in local cache, looking in remotes...
abseil/20230125.3: Checking remote: conancenter
abseil/20230125.3: Downloaded recipe revision a402cb19abb5639d7aef2ecdf48d2f02
eigen/3.4.0: Not found in local cache, looking in remotes...
eigen/3.4.0: Checking remote: conancenter
eigen/3.4.0: Downloaded recipe revision 2e192482a8acff96fe34766adca2b24c
farmhash/cci.20190513: Not found in local cache, looking in remotes...
farmhash/cci.20190513: Checking remote: conancenter
farmhash/cci.20190513: Downloaded recipe revision af6593f545dd2b496e6bd019f1deb66f
fft/cci.20061228: Not found in local cache, looking in remotes...
fft/cci.20061228: Checking remote: conancenter
fft/cci.20061228: Downloaded recipe revision 76a056c8ad3656ad557071c230f0f50c
flatbuffers/23.3.3: Not found in local cache, looking in remotes...
flatbuffers/23.3.3: Checking remote: conancenter
flatbuffers/23.3.3: Downloaded recipe revision 9ae28c67104fca222622513355755d3e
gemmlowp/cci.20210928: Not found in local cache, looking in remotes...
gemmlowp/cci.20210928: Checking remote: conancenter
gemmlowp/cci.20210928: Downloaded recipe revision 28483fa833aa47549961bb9c5ab84bfa
ruy/cci.20220628: Not found in local cache, looking in remotes...
ruy/cci.20220628: Checking remote: conancenter
ruy/cci.20220628: Downloaded recipe revision 81a2ef59e9f38e838fbcb8bf8246133c
cpuinfo/cci.20231129: Not found in local cache, looking in remotes...
cpuinfo/cci.20231129: Checking remote: conancenter
cpuinfo/cci.20231129: Downloaded recipe revision 15e94782b128bee8bfd047f6102a4d21
intel-neon2sse/cci.20210225: Not found in local cache, looking in remotes...
intel-neon2sse/cci.20210225: Checking remote: conancenter
intel-neon2sse/cci.20210225: Downloaded recipe revision 56e8b51d756e9ae2a612e3489039e07b
fxdiv/cci.20200417: Not found in local cache, looking in remotes...
fxdiv/cci.20200417: Checking remote: conancenter
fxdiv/cci.20200417: Downloaded recipe revision 0b3afe4c9d1b8d05f5f017984c8cb15a
cmake/3.29.5: Not found in local cache, looking in remotes...
cmake/3.29.5: Checking remote: conancenter
cmake/3.29.5: Downloaded recipe revision 56dbff3ff8af6bcd4b9c170fbd4da068
Graph root
    cli
Requirements
    abseil/20230125.3#a402cb19abb5639d7aef2ecdf48d2f02 - Downloaded (conancenter)
    cpuinfo/cci.20231129#15e94782b128bee8bfd047f6102a4d21 - Downloaded (conancenter)
    eigen/3.4.0#2e192482a8acff96fe34766adca2b24c - Downloaded (conancenter)
    farmhash/cci.20190513#af6593f545dd2b496e6bd019f1deb66f - Downloaded (conancenter)
    fft/cci.20061228#76a056c8ad3656ad557071c230f0f50c - Downloaded (conancenter)
    flatbuffers/23.3.3#9ae28c67104fca222622513355755d3e - Downloaded (conancenter)
    fxdiv/cci.20200417#0b3afe4c9d1b8d05f5f017984c8cb15a - Downloaded (conancenter)
    gemmlowp/cci.20210928#28483fa833aa47549961bb9c5ab84bfa - Downloaded (conancenter)
    intel-neon2sse/cci.20210225#56e8b51d756e9ae2a612e3489039e07b - Downloaded (conancenter)
    ruy/cci.20220628#81a2ef59e9f38e838fbcb8bf8246133c - Downloaded (conancenter)
    tensorflow-lite/2.12.0#efaff37bc6be68c2c36a21a04d074054 - Cache
Build requirements
    cmake/3.29.5#56dbff3ff8af6bcd4b9c170fbd4da068 - Downloaded (conancenter)
Resolved version ranges
    cmake/[>=3.16 <4]: cmake/3.29.5

======== Computing necessary packages ========
abseil/20230125.3: Compatible package ID 8631cf963dbbb4d7a378a64a6fd1dc57558bc2fe equal to the default package ID: Skipping it.
abseil/20230125.3: Checking 7 compatible configurations
abseil/20230125.3: Compatible configurations not found in cache, checking servers
abseil/20230125.3: 'c01616259c2d166eadec282346c9fb6dce0e3530': compiler.cppstd=14
abseil/20230125.3: '99c9bcacb68e3379fad0ffaab3c0268baafd0cd2': compiler.cppstd=gnu14
abseil/20230125.3: '13be611585c95453f1cbbd053cea04b3e64470ca': compiler.cppstd=17
abseil/20230125.3: Main binary package '8631cf963dbbb4d7a378a64a6fd1dc57558bc2fe' missing. Using compatible package '13be611585c95453f1cbbd053cea04b3e64470ca': compiler.cppstd=17
ruy/cci.20220628: Compatible package ID 126de38667ac17b2138c0ca6c1afe343cf472405 equal to the default package ID: Skipping it.
ruy/cci.20220628: Checking 7 compatible configurations
ruy/cci.20220628: Compatible configurations not found in cache, checking servers
ruy/cci.20220628: '0096115d01b9210305ef805e4602ec47d22eded8': compiler.cppstd=14
ruy/cci.20220628: 'cb4f103207adb8fa0c717f190169701a2814eb31': compiler.cppstd=gnu14
ruy/cci.20220628: 'c39acf83d1f21fd035711f00c547153c4aa32cb4': compiler.cppstd=17
ruy/cci.20220628: Main binary package '126de38667ac17b2138c0ca6c1afe343cf472405' missing. Using compatible package 'c39acf83d1f21fd035711f00c547153c4aa32cb4': compiler.cppstd=17
tensorflow-lite/2.12.0: Forced build from source
Requirements
    abseil/20230125.3#a402cb19abb5639d7aef2ecdf48d2f02:13be611585c95453f1cbbd053cea04b3e64470ca#ed0b3d81406c9540a12bd97893ff51b3 - Download (conancenter)
    cpuinfo/cci.20231129#15e94782b128bee8bfd047f6102a4d21:8564f588e8ad9d446bd3cb91bf674bc926e61eb4#e00c2540c14f4638d64265dc056fd1f6 - Download (conancenter)
    eigen/3.4.0#2e192482a8acff96fe34766adca2b24c:da39a3ee5e6b4b0d3255bfef95601890afd80709#b2e7c2d86c5d1dbefc534889aa72e12c - Download (conancenter)
    farmhash/cci.20190513#af6593f545dd2b496e6bd019f1deb66f:580bece66513a03b5d04e503a7a174349141fc7e#2baa1979af9a9590f6b74dce4e99fc82 - Download (conancenter)
    fft/cci.20061228#76a056c8ad3656ad557071c230f0f50c:6f60b3524dba59257e53b3efa5fbb11c79afd1a8#78f6e4797a81fc3f7ff7f755f3db2d80 - Download (conancenter)
    flatbuffers/23.3.3#9ae28c67104fca222622513355755d3e:f592eb6241339f322be7110248321688986d0f87#bf7478400e11ad03f413513974f47322 - Download (jfrog)
    fxdiv/cci.20200417#0b3afe4c9d1b8d05f5f017984c8cb15a:da39a3ee5e6b4b0d3255bfef95601890afd80709#99822879bdd86a69aa08623a42893b48 - Download (conancenter)
    gemmlowp/cci.20210928#28483fa833aa47549961bb9c5ab84bfa:8631cf963dbbb4d7a378a64a6fd1dc57558bc2fe#666d4074a6f8c2ec775f171ac9f66880 - Download (conancenter)
    intel-neon2sse/cci.20210225#56e8b51d756e9ae2a612e3489039e07b:da39a3ee5e6b4b0d3255bfef95601890afd80709#e86e987114e7f78601bcb5230eec9ca7 - Download (conancenter)
    ruy/cci.20220628#81a2ef59e9f38e838fbcb8bf8246133c:c39acf83d1f21fd035711f00c547153c4aa32cb4#d2d7be45bca817d32a04ab4c0cf7f315 - Download (conancenter)
    tensorflow-lite/2.12.0#efaff37bc6be68c2c36a21a04d074054:fd84657929830dbe80914507ca581a62623c28b2 - Build
Build requirements
    cmake/3.29.5#56dbff3ff8af6bcd4b9c170fbd4da068:63fead0844576fc02943e16909f08fcdddd6f44b#96b8ea57ee8ae3516c1ffc387ef340f7 - Download (conancenter)

======== Installing packages ========

-------- Downloading 11 packages --------
abseil/20230125.3: Retrieving package 13be611585c95453f1cbbd053cea04b3e64470ca from remote 'conancenter' 
abseil/20230125.3: Package installed 13be611585c95453f1cbbd053cea04b3e64470ca
abseil/20230125.3: Downloaded package revision ed0b3d81406c9540a12bd97893ff51b3
cmake/3.29.5: Retrieving package 63fead0844576fc02943e16909f08fcdddd6f44b from remote 'conancenter' 
cmake/3.29.5: Downloading 43.8MB conan_package.tgz
cmake/3.29.5: Decompressing 43.8MB conan_package.tgz
cmake/3.29.5: Package installed 63fead0844576fc02943e16909f08fcdddd6f44b
cmake/3.29.5: Downloaded package revision 96b8ea57ee8ae3516c1ffc387ef340f7
cpuinfo/cci.20231129: Retrieving package 8564f588e8ad9d446bd3cb91bf674bc926e61eb4 from remote 'conancenter' 
cpuinfo/cci.20231129: Package installed 8564f588e8ad9d446bd3cb91bf674bc926e61eb4
cpuinfo/cci.20231129: Downloaded package revision e00c2540c14f4638d64265dc056fd1f6
eigen/3.4.0: Retrieving package da39a3ee5e6b4b0d3255bfef95601890afd80709 from remote 'conancenter' 
eigen/3.4.0: Package installed da39a3ee5e6b4b0d3255bfef95601890afd80709
eigen/3.4.0: Downloaded package revision b2e7c2d86c5d1dbefc534889aa72e12c
farmhash/cci.20190513: Retrieving package 580bece66513a03b5d04e503a7a174349141fc7e from remote 'conancenter' 
farmhash/cci.20190513: Package installed 580bece66513a03b5d04e503a7a174349141fc7e
farmhash/cci.20190513: Downloaded package revision 2baa1979af9a9590f6b74dce4e99fc82
fft/cci.20061228: Retrieving package 6f60b3524dba59257e53b3efa5fbb11c79afd1a8 from remote 'conancenter' 
fft/cci.20061228: Package installed 6f60b3524dba59257e53b3efa5fbb11c79afd1a8
fft/cci.20061228: Downloaded package revision 78f6e4797a81fc3f7ff7f755f3db2d80
flatbuffers/23.3.3: Retrieving package f592eb6241339f322be7110248321688986d0f87 from remote 'jfrog' 
flatbuffers/23.3.3: Package installed f592eb6241339f322be7110248321688986d0f87
flatbuffers/23.3.3: Downloaded package revision bf7478400e11ad03f413513974f47322
fxdiv/cci.20200417: Retrieving package da39a3ee5e6b4b0d3255bfef95601890afd80709 from remote 'conancenter' 
fxdiv/cci.20200417: Package installed da39a3ee5e6b4b0d3255bfef95601890afd80709
fxdiv/cci.20200417: Downloaded package revision 99822879bdd86a69aa08623a42893b48
gemmlowp/cci.20210928: Retrieving package 8631cf963dbbb4d7a378a64a6fd1dc57558bc2fe from remote 'conancenter' 
gemmlowp/cci.20210928: Package installed 8631cf963dbbb4d7a378a64a6fd1dc57558bc2fe
gemmlowp/cci.20210928: Downloaded package revision 666d4074a6f8c2ec775f171ac9f66880
intel-neon2sse/cci.20210225: Retrieving package da39a3ee5e6b4b0d3255bfef95601890afd80709 from remote 'conancenter' 
intel-neon2sse/cci.20210225: Package installed da39a3ee5e6b4b0d3255bfef95601890afd80709
intel-neon2sse/cci.20210225: Downloaded package revision e86e987114e7f78601bcb5230eec9ca7
ruy/cci.20220628: Retrieving package c39acf83d1f21fd035711f00c547153c4aa32cb4 from remote 'conancenter' 
ruy/cci.20220628: Package installed c39acf83d1f21fd035711f00c547153c4aa32cb4
ruy/cci.20220628: Downloaded package revision d2d7be45bca817d32a04ab4c0cf7f315
cmake/3.29.5: Appending PATH environment variable: /home/msanna/.conan2/p/cmake33f87d8fd6850/p/bin
tensorflow-lite/2.12.0: Calling source() in /home/msanna/.conan2/p/tenso2698f17023a1e/s/src
tensorflow-lite/2.12.0: Downloading 69.7MB v2.12.0.tar.gz

-------- Installing package tensorflow-lite/2.12.0 (12 of 12) --------
tensorflow-lite/2.12.0: Building from source
tensorflow-lite/2.12.0: Package tensorflow-lite/2.12.0:fd84657929830dbe80914507ca581a62623c28b2
tensorflow-lite/2.12.0: Copying sources to build folder
tensorflow-lite/2.12.0: Building your package in /home/msanna/.conan2/p/b/tenso5255123a63b80/b
tensorflow-lite/2.12.0: Calling generate()
tensorflow-lite/2.12.0: Generators folder: /home/msanna/.conan2/p/b/tenso5255123a63b80/b/build/Release/generators
tensorflow-lite/2.12.0: CMakeToolchain generated: conan_toolchain.cmake
tensorflow-lite/2.12.0: CMakeToolchain generated: /home/msanna/.conan2/p/b/tenso5255123a63b80/b/build/Release/generators/CMakePresets.json
tensorflow-lite/2.12.0: CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(absl)
    find_package(Eigen3)
    find_package(farmhash)
    find_package(fft)
    find_package(flatbuffers)
    find_package(gemmlowp)
    find_package(ruy)
    find_package(NEON_2_SSE)
    find_package(fxdiv)
    target_link_libraries(... abseil::abseil Eigen3::Eigen farmhash::farmhash fft::fft flatbuffers::flatbuffers gemmlowp::gemmlowp ruy::ruy NEON_2_SSE::NEON_2_SSE fxdiv::fxdiv)
tensorflow-lite/2.12.0: Generating aggregated env files
tensorflow-lite/2.12.0: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
tensorflow-lite/2.12.0: Calling build()
tensorflow-lite/2.12.0: Apply patch (conan): Shared build fails on Windows with error LNK2005. Resolve the conflict by removing the conflicting implementation for now.
tensorflow-lite/2.12.0: Apply patch (conan): Fail if the CMake build script tries to fetch external dependencies
tensorflow-lite/2.12.0: Apply patch (conan): Dependency compatibility: Patch CMakeLists.txt, updating package names, target names, etc
tensorflow-lite/2.12.0: Running CMake.configure()
tensorflow-lite/2.12.0: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/msanna/.conan2/p/b/tenso5255123a63b80/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/msanna/.conan2/p/b/tenso5255123a63b80/b/src/tensorflow/lite"
-- Using Conan toolchain: /home/msanna/.conan2/p/b/tenso5255123a63b80/b/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: C++ Standard 17 with extensions ON
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Component target declared 'absl::config'
-- Conan: Component target declared 'absl::dynamic_annotations'
-- Conan: Component target declared 'absl::core_headers'
-- Conan: Component target declared 'absl::pretty_function'
-- Conan: Component target declared 'absl::fast_type_id'
-- Conan: Component target declared 'absl::prefetch'
-- Conan: Component target declared 'absl::algorithm'
-- Conan: Component target declared 'absl::counting_allocator'
-- Conan: Component target declared 'absl::hashtable_debug_hooks'
-- Conan: Component target declared 'absl::node_slot_policy'
-- Conan: Component target declared 'absl::non_temporal_arm_intrinsics'
-- Conan: Component target declared 'absl::non_temporal_memcpy'
-- Conan: Component target declared 'absl::leak_check'
-- Conan: Component target declared 'absl::flags_commandlineflag_internal'
-- Conan: Component target declared 'absl::log_internal_config'
-- Conan: Component target declared 'absl::log_internal_nullguard'
-- Conan: Component target declared 'absl::log_internal_voidify'
-- Conan: Component target declared 'absl::type_traits'
-- Conan: Component target declared 'absl::meta'
-- Conan: Component target declared 'absl::bits'
-- Conan: Component target declared 'absl::int128'
-- Conan: Component target declared 'absl::numeric'
-- Conan: Component target declared 'absl::numeric_representation'
-- Conan: Component target declared 'absl::exponential_biased'
-- Conan: Component target declared 'absl::periodic_sampler'
-- Conan: Component target declared 'absl::random_seed_gen_exception'
-- Conan: Component target declared 'absl::random_internal_traits'
-- Conan: Component target declared 'absl::random_internal_fast_uniform_bits'
-- Conan: Component target declared 'absl::random_internal_iostream_state_saver'
-- Conan: Component target declared 'absl::random_internal_wide_multiply'
-- Conan: Component target declared 'absl::random_internal_fastmath'
-- Conan: Component target declared 'absl::random_internal_pcg_engine'
-- Conan: Component target declared 'absl::random_internal_platform'
-- Conan: Component target declared 'absl::random_internal_randen_slow'
-- Conan: Component target declared 'absl::random_internal_randen_hwaes_impl'
-- Conan: Component target declared 'absl::random_internal_uniform_helper'
-- Conan: Component target declared 'absl::cordz_update_tracker'
-- Conan: Component target declared 'absl::civil_time'
-- Conan: Component target declared 'absl::time_zone'
-- Conan: Component target declared 'absl::compare'
-- Conan: Component target declared 'absl::atomic_hook'
-- Conan: Component target declared 'absl::errno_saver'
-- Conan: Component target declared 'absl::log_severity'
-- Conan: Component target declared 'absl::raw_logging_internal'
-- Conan: Component target declared 'absl::base_internal'
-- Conan: Component target declared 'absl::throw_delegate'
-- Conan: Component target declared 'absl::scoped_set_env'
-- Conan: Component target declared 'absl::strerror'
-- Conan: Component target declared 'absl::algorithm_container'
-- Conan: Component target declared 'absl::common_policy_traits'
-- Conan: Component target declared 'absl::hashtable_debug'
-- Conan: Component target declared 'absl::container_common'
-- Conan: Component target declared 'absl::debugging_internal'
-- Conan: Component target declared 'absl::function_ref'
-- Conan: Component target declared 'absl::memory'
-- Conan: Component target declared 'absl::random_internal_generate_real'
-- Conan: Component target declared 'absl::random_internal_randen_hwaes'
-- Conan: Component target declared 'absl::cordz_functions'
-- Conan: Component target declared 'absl::bad_any_cast_impl'
-- Conan: Component target declared 'absl::span'
-- Conan: Component target declared 'absl::bad_optional_access'
-- Conan: Component target declared 'absl::bad_variant_access'
-- Conan: Component target declared 'absl::utility'
-- Conan: Component target declared 'absl::spinlock_wait'
-- Conan: Component target declared 'absl::base'
-- Conan: Component target declared 'absl::endian'
-- Conan: Component target declared 'absl::cleanup_internal'
-- Conan: Component target declared 'absl::cleanup'
-- Conan: Component target declared 'absl::compressed_tuple'
-- Conan: Component target declared 'absl::fixed_array'
-- Conan: Component target declared 'absl::inlined_vector_internal'
-- Conan: Component target declared 'absl::inlined_vector'
-- Conan: Component target declared 'absl::container_memory'
-- Conan: Component target declared 'absl::hash_policy_traits'
-- Conan: Component target declared 'absl::crc_cpu_detect'
-- Conan: Component target declared 'absl::crc_internal'
-- Conan: Component target declared 'absl::stacktrace'
-- Conan: Component target declared 'absl::demangle_internal'
-- Conan: Component target declared 'absl::debugging'
-- Conan: Component target declared 'absl::any_invocable'
-- Conan: Component target declared 'absl::bind_front'
-- Conan: Component target declared 'absl::city'
-- Conan: Component target declared 'absl::low_level_hash'
-- Conan: Component target declared 'absl::log_internal_conditions'
-- Conan: Component target declared 'absl::random_internal_distribution_caller'
-- Conan: Component target declared 'absl::random_internal_randen'
-- Conan: Component target declared 'absl::strings_internal'
-- Conan: Component target declared 'absl::bad_any_cast'
-- Conan: Component target declared 'absl::optional'
-- Conan: Component target declared 'absl::variant'
-- Conan: Component target declared 'absl::malloc_internal'
-- Conan: Component target declared 'absl::random_bit_gen_ref'
-- Conan: Component target declared 'absl::random_internal_mock_helpers'
-- Conan: Component target declared 'absl::random_internal_randen_engine'
-- Conan: Component target declared 'absl::strings'
-- Conan: Component target declared 'absl::str_format_internal'
-- Conan: Component target declared 'absl::graphcycles_internal'
-- Conan: Component target declared 'absl::time'
-- Conan: Component target declared 'absl::any'
-- Conan: Component target declared 'absl::layout'
-- Conan: Component target declared 'absl::crc32c'
-- Conan: Component target declared 'absl::crc_cord_state'
-- Conan: Component target declared 'absl::symbolize'
-- Conan: Component target declared 'absl::examine_stack'
-- Conan: Component target declared 'absl::failure_signal_handler'
-- Conan: Component target declared 'absl::flags_path_util'
-- Conan: Component target declared 'absl::flags_commandlineflag'
-- Conan: Component target declared 'absl::flags_private_handle_accessor'
-- Conan: Component target declared 'absl::hash'
-- Conan: Component target declared 'absl::log_internal_globals'
-- Conan: Component target declared 'absl::log_internal_proto'
-- Conan: Component target declared 'absl::log_internal_nullstream'
-- Conan: Component target declared 'absl::log_internal_append_truncated'
-- Conan: Component target declared 'absl::log_globals'
-- Conan: Component target declared 'absl::log_initialize'
-- Conan: Component target declared 'absl::log_entry'
-- Conan: Component target declared 'absl::log_sink'
-- Conan: Component target declared 'absl::random_distributions'
-- Conan: Component target declared 'absl::random_internal_seed_material'
-- Conan: Component target declared 'absl::random_internal_pool_urbg'
-- Conan: Component target declared 'absl::random_internal_salted_seed_seq'
-- Conan: Component target declared 'absl::random_internal_nonsecure_base'
-- Conan: Component target declared 'absl::str_format'
-- Conan: Component target declared 'absl::cord_internal'
-- Conan: Component target declared 'absl::kernel_timeout_internal'
-- Conan: Component target declared 'absl::synchronization'
-- Conan: Component target declared 'absl::flags_program_name'
-- Conan: Component target declared 'absl::flags_config'
-- Conan: Component target declared 'absl::flags_marshalling'
-- Conan: Component target declared 'absl::flags_internal'
-- Conan: Component target declared 'absl::log_internal_format'
-- Conan: Component target declared 'absl::log_internal_log_sink_set'
-- Conan: Component target declared 'absl::log_sink_registry'
-- Conan: Component target declared 'absl::sample_recorder'
-- Conan: Component target declared 'absl::random_seed_sequences'
-- Conan: Component target declared 'absl::random_internal_distribution_test_util'
-- Conan: Component target declared 'absl::cordz_statistics'
-- Conan: Component target declared 'absl::cordz_handle'
-- Conan: Component target declared 'absl::cordz_info'
-- Conan: Component target declared 'absl::cordz_sample_token'
-- Conan: Component target declared 'absl::cordz_update_scope'
-- Conan: Component target declared 'absl::cord'
-- Conan: Component target declared 'absl::btree'
-- Conan: Component target declared 'absl::hash_function_defaults'
-- Conan: Component target declared 'absl::hashtablez_sampler'
-- Conan: Component target declared 'absl::raw_hash_set'
-- Conan: Component target declared 'absl::log_internal_message'
-- Conan: Component target declared 'absl::log_internal_strip'
-- Conan: Component target declared 'absl::log_internal_structured'
-- Conan: Component target declared 'absl::log_structured'
-- Conan: Component target declared 'absl::random_random'
-- Conan: Component target declared 'absl::status'
-- Conan: Component target declared 'absl::statusor'
-- Conan: Component target declared 'absl::flat_hash_set'
-- Conan: Component target declared 'absl::node_hash_set'
-- Conan: Component target declared 'absl::raw_hash_map'
-- Conan: Component target declared 'absl::log_internal_check_op'
-- Conan: Component target declared 'absl::log_internal_log_impl'
-- Conan: Component target declared 'absl::absl_log'
-- Conan: Component target declared 'absl::log'
-- Conan: Component target declared 'absl::log_streamer'
-- Conan: Component target declared 'absl::flat_hash_map'
-- Conan: Component target declared 'absl::node_hash_map'
-- Conan: Component target declared 'absl::flags_reflection'
-- Conan: Component target declared 'absl::flags'
-- Conan: Component target declared 'absl::flags_usage_internal'
-- Conan: Component target declared 'absl::flags_usage'
-- Conan: Component target declared 'absl::flags_parse'
-- Conan: Component target declared 'absl::log_internal_check_impl'
-- Conan: Component target declared 'absl::log_internal_flags'
-- Conan: Component target declared 'absl::absl_check'
-- Conan: Component target declared 'absl::check'
-- Conan: Component target declared 'absl::die_if_null'
-- Conan: Component target declared 'absl::log_flags'
-- Conan: Target declared 'abseil::abseil'
-- Conan: Including build module from '/home/msanna/.conan2/p/absei258afdd8414bd/p/lib/cmake/conan_trick/cxx_std.cmake'
-- Conan: Component target declared 'Eigen3::Eigen'
-- Conan: Target declared 'farmhash::farmhash'
-- Conan: Target declared 'fft::fft'
-- Conan: Component target declared 'flatbuffers::libflatbuffers'
-- Conan: Target declared 'flatbuffers::flatbuffers'
-- Conan: Including build module from '/home/msanna/.conan2/p/flatbe0ae7ff701be7/p/lib/cmake/FlatcTargets.cmake'
-- Conan: Including build module from '/home/msanna/.conan2/p/flatbe0ae7ff701be7/p/lib/cmake/BuildFlatBuffers.cmake'
-- Conan: Component target declared 'gemmlowp::eight_bit_int_gemm'
-- Conan: Target declared 'gemmlowp::gemmlowp'
-- Conan: Component target declared 'cpuinfo::cpuinfo'
-- Conan: Target declared 'ruy::ruy'
-- Conan: Target declared 'NEON_2_SSE::NEON_2_SSE'
-- Configuring done (0.7s)
CMake Error at CMakeLists.txt:546 (target_link_libraries):
  Target "tensorflow-lite" links to:

    pthreadpool::pthreadpool

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

tensorflow-lite/2.12.0: ERROR: 
Package 'fd84657929830dbe80914507ca581a62623c28b2' build failed
tensorflow-lite/2.12.0: WARN: Build folder /home/msanna/.conan2/p/b/tenso5255123a63b80/b/build/Release
ERROR: tensorflow-lite/2.12.0: Error in build() method, line 139
	cmake.configure(build_script_folder=join("tensorflow", "lite"))
	ConanException: Error 1 while executing

</details>

**Comment by RubenRBS** [comment]
Hi! Thanks a lot for taking the time to report the issue, I've identified the root cause and will create a new PR to fix it later today :)

**Comment by msanna-asaphus** [comment]
thank you very much. while I have your attention, may I ask also why the requirement for `ruy` is always enabled?
Not only there is an option to build without ruy, it's built by default without it.

**Comment by RubenRBS** [comment]
Hi @msanna-asaphus sorry for the delay.
ruy is always built by default because upstream CMakeLists always runs `find_package(ruy)` and links against it, so we need to always fetch it even if the option is then disabled (Which changes some things in the upstream cml)
