### ISSUE TITLE
[bug] Openssl enable problem in beauty/1.0.3 via Conan(inconistent conan files)

### ISSUE THREAD

**Issue by barbacar** [conan-io/conan-center-index#24363]
### Describe the bug

Hello,

To use openssl in the newer versions of beauty,

"BEAUTY_ENABLE_OPENSSL" flag needs to be set.

As a default, in conanfile(https://github.com/dfleury2/beauty/blob/1.0.3/conanfile.py) it is already set as "True"

but,
when i try to use via conan it never sets, also if you try to set it manually it gives the error at the below,

ERROR: beauty/1.0.3: option 'openssl' doesn't exist Possible options are ['shared', 'fPIC'] CMake Error at cmake/conan.cmake:826 (message): Conan install failed='1'

When i deeply investigated i realized that "openssl" option is not exists in conan-center conan file.

https://github.com/conan-io/conan-center-index/blob/master/recipes/beauty/all/conanfile.py

So you can never enable openssl in beauty if you use it from conan-center.

There is an incosistency between original conan file and conan-center conan file.

Best Regards,

**Comment by barbacar** [comment]
Yes exactly, because of definition is missing, it is impossible to set it, in original conan file it is settled as True as default.

Thanks

**Comment by uilianries** [comment]
@barbacar Thank you for reporting it. Indeed it's a bug in the recipe not passing that option.

I just opened the PR https://github.com/conan-io/conan-center-index/pull/24364 fixing it and adding 1.0.4.

**Comment by barbacar** [comment]
@uilianries Thank you for quick support & action,

Best Regards
