### ISSUE TITLE
[package] libffi/3.3: Complains about MTd runtime when using MDd

### ISSUE THREAD

**Issue by ohanar** [conan-io/conan-center-index#2440]
When trying to install libffi/3.3 with the MDd msvc runtime, you get the error
```
ERROR: libffi/3.3: Invalid configuration: This version of libffi does not support MTd runtime
```

It should either say that it doesn't support the MDd runtime, or it should work.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libffi/3.3**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 16**
  * Conan version: **conan 1.28.0**
  * Python version: **Python 3.7.2**

### Conan profile
```
[settings]
arch=x86_64
arch_build=x86_64
os=Windows
os_build=Windows
compiler=Visual Studio
compiler.version=16
compiler.runtime=MDd
build_type=Debug
[options]
[build_requires]
[env]
CC=cl
CXX=cl
```

### Steps to reproduce (Include if Applicable)

Use above profile with `conan install libffi/3.3@`.

**Comment by madebr** [comment]
https://github.com/libffi/libffi/issues/456#issuecomment-564644804

**Comment by SpaceIm** [comment]
I've tried, but I'm not even able to compile libffi 3.3 with MD runtime (Windows 10 and Visual Studio 2019). It fails with `libffi/3.3: ar: src/x86/win64_intel.obj: No such file or directory`

**Comment by ericLemanissier** [comment]
IIRC, the message is wrong, [but the check is right](https://github.com/conan-io/conan-center-index/blob/master/recipes/libffi/all/conanfile.py#L61) : the recipes actually fails with both MTd and MDd runtime when I tested withtout the check

**Comment by ohanar** [comment]
@ericLemanissier Yes, I did manage to test this. Indeed, the message is wrong, but the check is right.

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue due to its inactivity.
If the problem is still present, do not hesitate to reopen this issue and add more updated information.

Happy coding 🐸
