### ISSUE TITLE
[SDL2] <sdl_ttf, sdl_image>/<>: Version discrepancy

### ISSUE THREAD

**Issue by rdbruce** [conan-io/conan-center-index#24406]
### Description

I have issues downloading the SDL2 packages sdl, sdl_ttf, and sdl_image due to a conflict with the libpng dependency. 
![image](https://github.com/conan-io/conan-center-index/assets/29234483/5df75c5e-7557-453e-8ef2-0be2f9c0777a)
I decided to use the SDL versions in this post just to check. 
https://blog.conan.io/2023/07/20/introduction-to-game-dev-with-sdl2.html
I think there is a discrepancy between the recipes causing the issue.
In the sdl_image recipe we have `self.requires("libpng/1.6.40")` [here on 105](https://github.com/conan-io/conan-center-index/blob/master/recipes/sdl_image/all/conanfile.py) however in the sdl_ttf freetype dependency recipe we have `self.requires("libpng/[>=1.6 <2]")` [here on 61](https://github.com/conan-io/conan-center-index/blob/master/recipes/freetype/all/conanfile.py).
I think this is causing a version mismatch.

I am sorry if this post was a waste of time. I am a novice programmer.

### Package and Environment Details

* Package Name/Version: **zlib/1.2.8**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 8**
* Docker image: **conanio/gcc8**
* Conan version: **conan 1.18.0**
* Python version: **Python 3.7.4**

### Conan profile

my conanfile.py

from conan import ConanFile
from conan.tools.cmake import cmake_layout

class ExampleRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

def requirements(self):
    # self.requires("sdl/[~2.30]")
    self.requires("sdl_ttf/2.0.18")
    self.requires("sdl_image/2.0.5")

def layout(self):
    cmake_layout(self)

### Steps to reproduce

conan install .

### Logs

robert@junk:~/code/Cstuff/SDL/final_pendulum$ conan install .

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

======== Computing dependency graph ========
Graph root
    conanfile.py: /home/robert/code/Cstuff/SDL/final_pendulum/conanfile.py
Requirements
    autoconf/2.71#f9307992909d7fb3df459340f1932809 - Cache
    automake/1.16.5#058bda3e21c36c9aa8425daf3c1faf50 - Cache
    brotli/1.1.0#d56d7bb9ca722942aba17369cb5c0519 - Cache
    bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4 - Cache
    egl/system#068ac3037d8cf01f768d0e001e6dcd76 - Cache
    expat/2.6.2#2d385d0d50eb5561006a7ff9e356656b - Cache
    flac/1.4.2#d4051f8b37ee93725dea40dfd6a10168 - Cache
    freetype/2.13.2#7934d59c447d72edcd56025dc60e1aeb - Cache
    jbig/20160605#2d29fa02aacd76902e0d2cbbc24631ef - Cache
    libalsa/1.2.10#8b568d62190ef588cd5dcdd81171c289 - Cache
    libcap/2.69#7ef2d60864c2e58e89db957be936dc49 - Cache
    libdeflate/1.19#3ea74a4549efc14d4b1202dc4bfbf602 - Cache
    libffi/3.4.4#72cccac6139293b6e97ec9cd676547ff - Cache
    libiconv/1.17#73fefc1b696e069df90fd1d18aa63edd - Cache
    libjpeg/9e#3cd27a78643419450ee6d3739514d25c - Cache
    libmp3lame/3.100#44b12d19316eb2b223d98d3e75dae438 - Cache
    libpng/1.6.43#c219d8f01983bac10c404fc613605eef - Cache
    libsndfile/1.2.2#b3662f832e29507e8d9840a43737cc14 - Cache
    libtiff/4.6.0#51d0e7e15d032aeec1b64e65c44ecd9f - Cache
    libtool/2.4.7#08316dad5c72c541ed21e039e4cf217b - Cache
    libunwind/1.8.0#045502d366b4ce2bc52a492648e62d2b - Cache
    libwebp/1.3.2#52f69c4a31c5cf033fdd9230d77a8e38 - Cache
    libxml2/2.12.7#737a1eba03113d1aa22d67579ced7d5e - Cache
    m4/1.4.19#b38ced39a01e31fef5435bc634461fd2 - Cache
    mpg123/1.31.2#ce831c936b2284e2066ab3dc58a2628e - Cache
    ogg/1.3.5#062626875f5c8c59f069f76f148098ef - Cache
    opengl/system#4df6fecde4084386beded3ed0e56e4ea - Cache
    openssl/3.2.1#64189bfad173ff6dfcf60441d4e26bbe - Cache
    opus/1.4#54631f551fc450783fb2df8cd63f80a2 - Cache
    pulseaudio/14.2#bedb313afed20242c7caa27ae3e10af8 - Cache
    sdl/2.28.3#80647ebd83596b1b39f1f4b6e9daac37 - Cache
    sdl_image/2.0.5#33c8f5f63070430ae0e8ec9c3fccaaa7 - Cache
    sdl_ttf/2.0.18#a02859d1e05d8241caf2808ad2fdea9c - Cache
    vorbis/1.3.7#37e58f52e59a6232199b34ef402714a6 - Cache
    wayland/1.22.0#284b56bdbe57868770f46100784e3b4d - Cache
    xkbcommon/1.6.0#dababe41c183634d88ad56ef4740c045 - Cache
    xkeyboard-config/system#57dd5c08e72ab06bc2ee0e756c0a2c41 - Cache
    xorg/system#f626cbdd0ba57d9c53bce2d8b9362fad - Cache
    xz_utils/5.4.5#51e5a6e6564f4ea3afd79def01f035ad - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Cache
    zstd/1.5.5#1f239731dc45147c7fc2f54bfbde73df - Cache
Build requirements
    autoconf/2.71#f9307992909d7fb3df459340f1932809 - Cache
    automake/1.16.5#058bda3e21c36c9aa8425daf3c1faf50 - Cache
    bison/3.8.2#ed1ba0c42d2ab7ab64fc3a62e9ecc673 - Cache
    cmake/3.29.6#1a639e3e7401ea46e16c83ec9c5a7922 - Cache
    expat/2.6.2#2d385d0d50eb5561006a7ff9e356656b - Cache
    flex/2.6.4#e35bc44b3fcbcd661e0af0dc5b5b1ad4 - Cache
    gettext/0.21#a2bd3513f212013764c9040f4c70ed69 - Cache
    gnu-config/cci.20210814#dc430d754f465e8c74463019672fb97b - Cache
    libffi/3.4.4#72cccac6139293b6e97ec9cd676547ff - Cache
    libiconv/1.17#73fefc1b696e069df90fd1d18aa63edd - Cache
    libtool/2.4.7#08316dad5c72c541ed21e039e4cf217b - Cache
    libxml2/2.12.7#737a1eba03113d1aa22d67579ced7d5e - Cache
    m4/1.4.19#b38ced39a01e31fef5435bc634461fd2 - Cache
    meson/1.2.2#04bdfb85d665c82b08a3510aee3ffd19 - Cache
    meson/1.3.0#67eebe98438326590a9285377c37cea2 - Cache
    meson/1.3.2#d1125ba555ec1a94f165a3412fdf7f88 - Cache
    meson/1.4.0#024dfac41ea5570cb1aec3ea6fe34d0a - Cache
    ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21 - Cache
    pkgconf/2.0.3#f996677e96e61e6552d85e83756c328b - Cache
    pkgconf/2.1.0#27f44583701117b571307cf5b5fe5605 - Cache
    wayland/1.22.0#284b56bdbe57868770f46100784e3b4d - Cache
    wayland-protocols/1.33#b9e56b7662c2a25f30bfb4eb72df9ad6 - Cache
    yasm/1.3.0#fb800a15413dca19bfaef9e4b5d50694 - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Cache
Resolved version ranges
    cmake/[>3.27 <4]: cmake/3.29.6
    cmake/[>=3.16 <4]: cmake/3.29.6
    cmake/[>=3.18 <4]: cmake/3.29.6
    expat/[>=2.6.2 <3]: expat/2.6.2
    libpng/[>=1.6 <2]: libpng/1.6.43
    libxml2/[>=2.12.5 <3]: libxml2/2.12.7
    openssl/[>=1.1 <4]: openssl/3.2.1
    zlib/[>=1.2.11 <2]: zlib/1.3.1
ERROR: Version conflict: Conflict between libpng/1.6.40 and libpng/1.6.43 in the graph.
Conflict originates from sdl_image/2.0.5

Run 'conan graph info ... --format=html > graph.html' and open 'graph.html' to inspect the conflict graphically.

**Comment by czoido** [comment]
Hi @rdbruce,

Thanks for reporting, I will check those recipes and see if we can also introduce version ranges for feetype so that we can avoid conflicts. Anyway, I have checked and a `conan graph info .` for the `conanfile.txt` of the example here: https://github.com/conan-io/examples2/blob/main/examples/libraries/sdl2/introduction/conanfile.txt
is not producing errors, so that may be happening because you already have a version of `libpng` in your local Cache.
I'm sorry for the late response. Please, do not hesitate to ask any questions about Conan in the[ Conan repo](https://github.com/conan-io/conan) or about Conan Center Index packages here.
