### ISSUE TITLE
[package] libpq/15.5: Missing OpenSSL 3.2.x Fix Patch

### ISSUE THREAD

**Issue by aniederl** [conan-io/conan-center-index#24440]
### Description

libpq/15.5 is missing the patch with description "Fix libpq w/ openssl >=3.2.x".
Upstream fixed this issue however only starting from version 15.6 ... see https://www.postgresql.org/docs/release/15.6/

NOTE: Package/Environment Details, Conan profile and Logs section not filled out as they are irrelevant in this case.

### Package and Environment Details

n/a

### Conan profile

n/a

### Steps to reproduce

See merged PR https://github.com/conan-io/conan-center-index/pull/22615 with the description of the issue that is fixed by this patch.
Using libpq/15.5 together with openssl/3.2.x can lead to crashes when opening database connections via TLS.

### Logs

n/a

**Comment by aniederl** [comment]
> Hi @aniederl thanks a lot for your report. Are you planning on opening a PR by yourself, or should we move forwards ourselves? Thanks!

Hi!
Whatever works best for you. I can open a PR if you like.

**Comment by RubenRBS** [comment]
We'd happily review your pr then! Thanks :)
