### ISSUE TITLE
[package] arrow/16.1.0: Version conflict if arrow*:parquet=True

### ISSUE THREAD

**Issue by maximiliank** [conan-io/conan-center-index#24455]
### Description

I want to consume the arrow/16.1.0 with parquet option and run into a version conflict for boost due to different version requirements in arrow and thrift. Here is my `conanfile.txt`:

```
[requires]
arrow/16.1.0

[layout]
cmake_layout

[generators]
CMakeDeps

[options]
arrow*:parquet=True
arrow*:with_boost=True
arrow*:with_thrift=True
```

It results in the following conflict:
```
ERROR: Version conflict: Conflict between boost/1.85.0 and boost/1.84.0 in the graph.
Conflict originates from thrift/0.17.0
```

### Package and Environment Details

* Package Name/Version: **arrow/16.1.0**
* Operating System+version: **RHEL 9**
* Compiler+version: **GCC 13.2.1**
* Conan version: **conan 2.4.1**
* Python version: **Python 3.11.7**

### Conan profile

[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

### Steps to reproduce

`conan install .` with the above `conanfile.txt´.

### Logs

<details><summary>Click to expand log</summary>

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

======== Computing dependency graph ========
Graph root
    conanfile.txt: <path_to>/conanfile.txt
Requirements
    arrow/16.1.0#f484da4c4c27c1eb3ead5d61b70635cd - Cache
    thrift/0.17.0#c79319d67eaaf8637e5bd8fb31a364fa - Cache
ERROR: Version conflict: Conflict between boost/1.85.0 and boost/1.84.0 in the graph.
Conflict originates from thrift/0.17.0

Run 'conan graph info ... --format=html > graph.html' and open 'graph.html' to inspect the conflict graphically.

</details>

**Comment by perseoGI** [comment]
I'm closing this issue as it has been resolved in https://github.com/conan-io/conan-center-index/pull/24458
Thank you!
