### ISSUE TITLE
[package] glib/2.78.3:  Python is not a valid python or it is missing distutil (Win11)

### ISSUE THREAD

**Issue by h5b** [conan-io/conan-center-index#24549]
### Description

While building meson, build of glib/2.78.3 fails in case Python 3.12 has been installed on the build host system (Windows 11) with the following error:

```
..\src\meson.build:2329:26: ERROR: <PythonExternalProgram 'python3' -> ['C:\\Program Files\\Python312\\python.exe']> is not a valid python or it is missing distutils

glib/2.78.3: ERROR:
Package '5f7da365cc170b1e7f1153809bda9cc5a73e82d6' build failed
glib/2.78.3: WARN: Build folder C:\Users\<USER>\.conan2\p\b\glib95ba65c087be0\b\build-debug
ERROR: glib/2.78.3: Error in build() method, line 136
        meson.configure()
        ConanException: Error 1 while executing
```

### Package and Environment Details

* Package Name/Version: **glib/2.78.3**
* Operating System+version: **Windows 11**
* Compiler+version: **Visual Studio 2022**
* Conan version: **conan 2.4.0**
* Python version: **Python 3.12.4**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows
[conf]

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

### Steps to reproduce

conan install -vv --build=glib/2.78.3 --build=missing -pr:b=<profile> -pr:h=<profile> .

### Logs

<details><summary>Click to expand log</summary>

```
..\src\meson.build:2329:26: ERROR: <PythonExternalProgram 'python3' -> ['C:\\Program Files\\Python312\\python.exe']> is not a valid python or it is missing distutils

glib/2.78.3: ERROR:
Package '5f7da365cc170b1e7f1153809bda9cc5a73e82d6' build failed
glib/2.78.3: WARN: Build folder C:\Users\<USER>\.conan2\p\b\glib95ba65c087be0\b\build-debug
ERROR: glib/2.78.3: Error in build() method, line 136
        meson.configure()
        ConanException: Error 1 while executing```

</details>

**Comment by AbrilRBS** [comment]
Hi @h5b - Our own @ErniGH submitted https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4133 and it got merged for the next release, which will drop the need for distutils in glib, and we're in the process of backporting this to older versions, thanks a lot for your patience! :)

**Comment by h5b** [comment]
Thanks for the update and clarification, much appreciated.

**Comment by AbrilRBS** [comment]
Closing as solved - we've merged the backports and glib should now be usable again, thanks a lot for taking the time to report this :)
