### ISSUE TITLE
[question] tool_requires("doxygen/1.9.4") does not provide doxygen utilities at build time

### ISSUE THREAD

**Issue by lucas066001** [conan-io/conan-center-index#24588]
### What is your question?

- **Conan version, Operating System, compiler:**
Conan[2.3.2]
Windows10[22H2]
Msvc[v143]
- **Situation, how to reproduce:**
   - Create a sample program that compiles well using CMake and Conan (make sure you are able to retreive package using ```self.requires()```)
   - Add ```self.tool_requires("doxygen/1.9.1")``` to your conanfile.py
   - Try to access doxygen within your cmake file using ```find_package(Doxygen REQUIRED)```, ```find_package(doxygen REQUIRED)``` or ```doxygen_add_docs(YourTarget)```
   -  You should not be able to access it...
- **Expected behavior:**
   - Being able to access doxygen utilities to produce a full documentation of the project without the need to execute manual commands.
- **Important note:**
  - I'm aware that ```tool_requires()``` does not act like ```requires()```. To make sure doxygen has been retreived well **I've manually launched ```conanbuild.ps1``` within my powershell and here I'm able to execute _doxygen_ commands** and produce documentation.
- **Question :**
  - How is supposed to act ```tool_requires()``` in my case ? When the virtual env is used during my cmake build ? How can I generate doxygen documentation for my current project setup ?
  

### Sources : 

conanfile.py : 
```python
from conan import ConanFile
from conan.tools.env import Environment

class DocsGenerator(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def build_requirements(self):
        self.tool_requires("doxygen/1.9.1")
```

CMakeLists.txt :
```cmake
cmake_minimum_required (VERSION 3.25)
project (MyProject)

# specify the C++ standard
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)

add_compile_definitions(WINDOWS_IGNORE_PACKING_MISMATCH)

# Enable Hot Reload for MSVC compilers if supported.
if (POLICY CMP0141)
  set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "$<IF:$<AND:$<C_COMPILER_ID:MSVC>,$<CXX_COMPILER_ID:MSVC>>,$<$<CONFIG:Debug,RelWithDebInfo>:EditAndContinue>,$<$<CONFIG:Debug,RelWithDebInfo>:ProgramDatabase>>")
endif()

#Make my scripts accessibles
include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/docs_generate.cmake")

#Builds my project as intended
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/src")

#Trigger the build process for documentation
if(DEFINED BUILD_DOC)
  add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/docs")
endif()
```

**_No need to share conan_install.cmake as it works well for the build of my project_**

docs/CMakeLists.txt : 
```cmake
set(CONAN_OUT ${CMAKE_CURRENT_SOURCE_DIR}/_out/conan/${CURRENT_PRESET})
set(CMAKE_PREFIX_PATH ${CONAN_OUT})
conan_install(${CMAKE_CURRENT_SOURCE_DIR} ${CONAN_OUT})

#Bellow find the different things I've tried :

##1st try : 
set (doxygen_cmd "doxygen")
execute_process(COMMAND ${doxygen_cmd} RESULT_VARIABLE rv)
message("rv='${rv}'")
##returns rv='no such file or directory'

##2nd try : 
add_custom_target(
    docs
    COMMAND ${DOXYGEN_EXECUTABLE} ${DOXYGEN_OUT}
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    COMMENT "Generating API documentation with Doxygen"
    VERBATIM
)
#Nothing shows up

##3rd try :
find_package(Doxygen REQUIRED)
doxygen_add_docs(MyTarget)
##returns Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)

##4th try :
find_package(doxygen REQUIRED)
doxygen_add_docs(MyTarget)
##returns Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE), Doxygen was not found, needed by doxygen_add_docs()
```

conan profile : 
```yml
[settings]
arch=x86
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows

[conf]
tools.env.virtualenv:powershell=True
```

I'm struggling with that for 3 days now, I would really appreciate some help and clarifications.

P.S: I'm aware of the [conan docs example](https://docs.conan.io/2/tutorial/consuming_packages/use_tools_as_conan_packages.html) but it didn't helped me so far...

**Comment by SpaceIm** [comment]
It's a question for conan, not conan-center-index. But If you call CMake yourself, not through conanfile, you have to run conanbuildenv script before.

**Comment by lucas066001** [comment]
> It's a question for conan, not conan-center-index. But If you call CMake yourself, not through conanfile, you have to manually run conanbuild script before, otherwise folders of executables coming from build requirements won't be visible in PATH env var.
> 
> Unix systems (you can transpose to powershell, I don't remember how .ps1 is called)
> 
> ```shell
> cd build-release
> conan install .. -s build_type=Release
> source conanbuild.sh
> cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
> cmake --build . --config Release
> ```
> 
> (if you rely on CMakePresets.json generated by CMakeToolchain instead, it may work without the need to call conanbuild)

Thanks for your answer, I will work on with your advises and if I still get stuck I will reopen a ticket on conan repo (sorry for the confusion)
