### ISSUE TITLE
[question] Directory for DLL is not the same as for LIB in Boost recipe

### ISSUE THREAD

**Issue by Alexolut** [conan-io/conan-center-index#24688]
I found the old thread https://github.com/bincrafters/community/issues/84 with request to make different result directories in Boost recipe for *.dll and *.lib files. That request wasn't satisfied. 

Despite that, currently the [recipe used for Boost 1.85](https://conan.io/center/recipes/boost?version=1.85.0) results in different directories for *.dll (`bin` dir) and for *.lib (`lib` dir). 

Is there an option in recipe to specify the same output dir (e.g. `lib` dir) for all .lib and .dll files as the result of `conan install boost/1.85.0@ -o shared=True --build=missing` command?

**Comment by uilianries** [comment]
@Alexolut We avoid changing the project layout directly in the recipe to avoid breaking users that are expecting the same behavior as when building/installing from the upstream. The folder layout for Boost was not change recently, which means, in case the layout changed in 1.85.0, is result of b2 or Boost itself. 

In case you want a custom layout, you could try deploy and change the target folders: https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html#deploy

**Comment by Alexolut** [comment]
@uilianries thank you for your answer. For me it's still not clear what directory tree we should expect from Boost recipe on conan-center? Will both *.lib and *.dll files be located in `lib` folder of conan package (as far as I understand it's default way for Boost), or they will be split into `lib` and `bin` folders respectively  (general conan approach)?

**Comment by uilianries** [comment]
@Alexolut Speaking specifically about Boost, it will be the folder `bin` for all .dll files:

https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py#L1709

Closing this issue as it's answered. Please, feel free to re-open in case needing further clarification.
