### ISSUE TITLE
[package]ffmpeg/6.1.1: build uses dependencies

### ISSUE THREAD

**Issue by Drllap** [conan-io/conan-center-index#24689]
### Description

Running `conan build .` fails. According to [this](https://docs.conan.io/1/reference/conanfile/dependencies.html#dependencies-interface)
> At the moment, this information should only be used in generate() and validate() methods. Any other use, please submit a Github issue.

I'm very obedient so I'm creating a Gitub issue.

### Package and Environment Details

* Package Name/Version: **ffmpeg/6.1.1**
* Operating System+version: **Windows 10**
* Compiler+version: **MSVC 16**
* Docker image: **N/A**
* Conan version: **conan 1.64.0**
* Python version: **Python 3.9.19**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
compiler=Visual Studio
build_type=Debug
[options]
[build_requires]
[env]

### Steps to reproduce

```
cd ./recipes/ffmpeg/all
conan1 install . ffmpeg/6.1.1@ -pr d64 
conan1 build .
```

### Logs

<details><summary>Click to expand log</summary>

```
WARN: *** Conan 1 is legacy and on a deprecation path ***
WARN: *** Please upgrade to Conan 2 ***
Using lockfile: 'C:\Development\conan-center-index\recipes\ffmpeg\all/conan.lock'
Using cached profile from lockfile
conanfile.py (ffmpeg/6.1.1): Calling build()
AFAFAFAFAFA
ERROR: conanfile.py (ffmpeg/6.1.1): Error in build() method, line 705
        self._patch_sources()
while calling '_patch_sources', line 407
        [f"-l{lib}" for lib in self.dependencies["openssl"].cpp_info.aggregated_components().libs])
        AttributeError: 'NoneType' object has no attribute 'dependencies'
```

</details>

**Comment by uilianries** [comment]
@Drllap Thank you for your report! Building a recipe, using Conan 1.x and with development flow, instead of running `conan create` may fail for you, depending the case. We have a past discussion about a similar cases: https://github.com/conan-io/conan/issues/5165

Your report fits a violation, as it's documented to use `self.dependencies` only in `generate` and `validate`: https://docs.conan.io/2/reference/conanfile/methods/generate.html#dependencies-interface

I opened the PR https://github.com/conan-io/conan-center-index/pull/24762, which should fix your case. Please, test it locally if possible and check it. I tested using Conan 1.64.0 and 2.5.0, both are working. You need to run `conan source ...` as well (not listed in your report).

**Comment by Drllap** [comment]
@uilianries Thank you. I tested your branch. I can confirm that the
```
ERROR: conanfile.py (ffmpeg/6.1.1): Error in build() method, line 705
        self._patch_sources()
while calling '_patch_sources', line 407
        [f"-l{lib}" for lib in self.dependencies["openssl"].cpp_info.aggregated_components().libs])
        AttributeError: 'NoneType' object has no attribute 'dependencies'
```
error is now gone.

Unfortunately, I now get this error:
```
ERROR: conanfile.py (ffmpeg/6.1.1): Error in build() method, line 694
        autotools.configure()
        ConanException: Cannot wrap command with different envs, ['C:\\Development\\conan-center-index\\recipes\\ffmpeg\\all\\build-d
ebug\\conan\\conanbuild.bat'] - ['C:\\Development\\conan-center-index\\recipes\\ffmpeg\\all\\build-debug\\conan\\conanbuild.sh'] - []
```
I already posted a question about this here: https://github.com/conan-io/conan/issues/16713 so I think we can close this issue when the PR is merged

**Comment by uilianries** [comment]
@Drllap Thank you for you feedback! I tested only on Linux, but I see your scenario is even more complicated as you are using Windows + msys. I Would recommend using `conan create` to build recipes in CCI, as I commented before, using development flow may not work for every case.
