### ISSUE TITLE
[question] spdlog - find_package

### ISSUE THREAD

**Issue by IceflowRE** [conan-io/conan-center-index#247]
https://github.com/conan-io/conan-center-index/blob/master/recipes/spdlog/1.4.x/conanfile.py#L85-L87

This removes the possibility to use `find_package(spdlog 1.4.2 REQUIRED)`.
The [bincrafters versions](https://github.com/bincrafters/conan-spdlog/blob/testing/1.4.2/conanfile.py) actually allows this. Is there any reason why it was changed this way?

**Comment by tt4g** [comment]
The spdlog CMake package module has been removed, but `cmake_generator` has been added instead.

https://github.com/conan-io/conan-center-index/blob/16518b491139c33d330a934c238d4094e2d61f5a/recipes/spdlog/1.4.x/conanfile.py#L14

It is introduced in the document: https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html

**Comment by IceflowRE** [comment]
Good point. But actually `find_package` is still not working (win10, VS) or do i have to edit `CMAKE_MODULE_PATH` manually?
Anyway iam unsure where the right place is, to discuss this.

**Comment by ericLemanissier** [comment]
as mentionned in https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html, if are trying to consume spdlog from a conanfile.py, just use `    generators = "cmake_find_package"` and the CMake build helper will automatically adjust the CMAKE_MODULE_PATH. If you are using a conanfile.txt file, you need to use cmake_find_package and cmake_paths generators to adjust the CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH variables automatically.

**Comment by IceflowRE** [comment]
Pretty interesting as my `CMAKE_MODULE_PATH` get adjusted but is missing the install folder.
I will just add it manually,
Thanks for your help.
