### ISSUE TITLE
[docs] Add information about VS 2015 version used

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-center-index#2473]
> 
> 
> ```
> C:\J\c3ipr\s\PR-2453\1\0_2\5126f9\1\build_subfolder\source_subfolder\CLHEP\CLHEP/Geometry/BasicVector3D.h(349): error C2580: 'HepGeom::BasicVector3D<float>::BasicVector3D(const HepGeom::BasicVector3D<float> &)': multiple versions of a defaulted special member functions are not allowed
> ```
> 
> Bug in Visual Studio 2015? Which version runs in CI, `MSVC 2015 Update 2`?

@ping @jgsogo @danimtb 

We can add this information in docs/

_Originally posted by @uilianries in https://github.com/conan-io/conan-center-index/pull/2453#issuecomment-670627353_

**Comment by danimtb** [comment]
The information in https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md#windows is not enough? that "update 2" is something else to document?

**Comment by jgsogo** [comment]
Info for 2015 is not added.
