### ISSUE TITLE
[question] Link errors with vulkan-headers on Raspberry Pi 5

### ISSUE THREAD

**Issue by VicKov1975** [conan-io/conan-center-index#24782]
### What is your question?

I have started a new C++ demo project with Conan 2.5.0 and Vulkan on a Raspberry Pi 5.

So I have made my conanfile.py and my CMakeLists.txt exactly like in the instructions on this page:
https://conan.io/center/recipes/vulkan-headers?version=1.3.268.0

But when I try to compile it, I am getting link errors such as:

```
undefined reference to 'vkCreateInstance'
undefined reference to 'vkDestroyInstance'
undefined reference to 'vkEnumerateInstanceVersion'
...
```

Any suggestions?

EDIT: I am  running on Raspbian 12 Bookworm 64-bit.

**Comment by SpaceIm** [comment]
You have to add vulkan-loader to your dependencies and link to it.

**Comment by jcar87** [comment]
Hi @VicKov1975 - thank you for reporting this.

Could you provide a minimal example of the C or C++ sources you are building? thanks

**Comment by VicKov1975** [comment]
> You have to add vulkan-loader to your dependencies and link to it.

Thanks, it worked.
