### ISSUE TITLE
[question] Rationale of default_options

### ISSUE THREAD

**Issue by pasbi** [conan-io/conan-center-index#24813]
### What is your question?

When building one of my projects (which uses opencv) using conan, I faced the issue that the opencv-conan-package doesn't support the PFM image codec.

Took me quite a while to figure out that PFM codec is turned off by default: [conanfile.py:200](https://github.com/conan-io/conan-center-index/blob/master/recipes/opencv/4.x/conanfile.py#L200C1-L200C36).

In [OpenCV/CMakeLists.txt:476](https://github.com/opencv/opencv/blob/4.x/CMakeLists.txt#L476), the codec is available by default.
PFM is super simple, it should be available pretty much anywhere with zero dependencies and it's size is probably negligible.
Hence, I see no reason to set it to `OFF` by default.

I think it's crucial to keep the default close to what people expect.
OpenCV has a ton of options and re-building its package takes forever.

Is there a general aim to keep the conanfile.py defaults close to the defaults defined in the package's original CMakeLists.txt (if applicable)?

Is there a particular reason for the `with_imgcodec_pfm`-option defaulting to `False`? Can we change it to `True`?

**Comment by valgur** [comment]
The question is better suited for https://github.com/conan-io/conan-center-index

>  Is there a general aim to keep the conanfile.py defaults close to the defaults defined in the package's original CMakeLists.txt (if applicable)?

The recipes generally try to stick to the default values set by the project, yes.

Regarding the PFM option, if you look at the PR that added it (https://github.com/conan-io/conan-center-index/pull/6802), the rationale was to keep the existing behavior of having them disabled. Since adding features is generally not considered a breaking change, enabling them by default should be acceptable, imo. Consider opening a PR on CCI to continue the discussion there.

/cc @SpaceIm

**Comment by jcar87** [comment]
Closed via https://github.com/conan-io/conan-center-index/pull/24814

As a note on `default_options` -  I think there's different approaches. Traditionally Conan Center has been following "the defaults from the library maintainers" - however sometimes the libraries maintainers will expose too many options, or will default to "depend on everything if found on the system", even if it is for some optional functionality that may not be in the critical path for a library to fulfil its purpose.

We are likely to revisit our guidance in the future - the goal should be for the defaults to provide a library that fulfils its core functionality, finding a good balance between defaults provided, recipe complexity, and number of dependencies (which would increase build times for users with configurations not provided by Conan Center). 

I think in the case for the pfm codec in OpenCV,  I don't even see a point in having it as an exposed option in the first place - it should just be built unconditionally. Perhaps there's a very niche use case where a users may want the smallest possible size of libraries by shedding optional functionality.
