### ISSUE TITLE
[package] libsndfile/1.0.28: Invalid configuration for Windows

### ISSUE THREAD

**Issue by MartinDelille** [conan-io/conan-center-index#2491]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libsndfile/1.0.28**
  * Operating System+version: **Windows 7**
  * Compiler+version: **Visual Studio 15**
  * Docker image: **N/A**
  * Conan version: **concan 1.28.1**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
PS C:\dev> conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Try to run conan with the following `conanfile.txt`:

```
[requires]
libsndfile/1.0.28@bincrafters/stable

[generators]
qmake
```

And the following command: `conan install .. --build missing --update -o libsndfile:with_alsa=False`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
conan install .. --build missing --update -o libsndfile:with_alsa=False
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
libsndfile:with_alsa=False
[build_requires]
[env]
ERROR: libsndfile/1.0.28@bincrafters/stable: Invalid configuration: The project libsndfile can not be built by Visual Studio.
```

</details>

**Comment by Croydon** [comment]
`@username/channel` is optional for a while now.

All packages in the Conan Center Index don't have a `@username/channel` anymore. Packages with a `@username/channel` do come from places like [conan-community](https://github.com/conan-community) (`@conan)`) and [Bincrafters](https://github.com/bincrafters) (`@bincrafters)`) .

Please migrate to `libsndfile/1.0.28`

That said, it still won't work with VS. This is more a feature request than a bug

**Comment by madebr** [comment]
Soon. You'll have to wait until 1.0.29.
https://github.com/erikd/libsndfile/pull/539

**Comment by MartinDelille** [comment]
Ok since it is released (https://github.com/erikd/libsndfile/releases/tag/v1.0.29), what would it take to have  it in conan center?

**Comment by uilianries** [comment]
@MartinDelille You can open a PR bumping its version. Only add the new release URL and sha256 in conandata.yml, and add 1.0.29 in config.yml.

**Comment by madebr** [comment]
@uilianries 
That's why I opened #2556 .
We currently build libsndfile using the autotools scripts.
But since the previous release, libsndfile has learned cmake which has built-in MSVC support.
To make maintenance easier, we should add a new cmake-only recipe.
But that requires renaming the folder of the previous and adding a new recipe folder, hence requiring 2 pr's.
That is a lot of things to expect from a newcomer.
Hence #2556.

**Comment by MartinDelille** [comment]
Ok I felt adventurous and opened the two pull requests 😄 !

The second (in draft) is failing locally for now: https://github.com/conan-io/conan-center-index/pull/2597
