### ISSUE TITLE
GLOG 0.4.0 : unresolved external symbol google::InitGoogleLogging

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan-center-index#2494]
Package Name/Version: **glog/0.4.0**
Operating System+version: **Win 10**
Compiler+version: **MSVS 2015 & MSVS 2019**
Conan version: **1.28.0**
cmake version:**3.18.0**
Ninja version:**1.10.0**

This may be similar to: https://github.com/conan-io/conan-center-index/issues/1691

Using conan-cmake:
``` Bash
conan_cmake_run(
            REQUIRES
                glog/0.4.0
            IMPORTS
                ${CONANIMPORTS}
            BASIC_SETUP
                CMAKE_TARGETS
            )

add_executable( ${PROJECT_NAME} ${SOURCES}   )
target_link_libraries(${PROJECT_NAME} CONAN_PKG::glog)

```

main.cpp is simple enough:

```Bash

#include <glog/logging.h>

int main(int argc, char* argv[]) {


     // Initialize Google's logging library.
     google::InitGoogleLogging(argv[0]);

     LOG(INFO) << "This is an info  message";
     LOG(WARNING) << "This is a warning message";
     LOG(ERROR) << "This is an error message";
     LOG(FATAL) << "This is a fatal message";

     return 0;
}
```

Log attached below.
[Conan_GLOG_Fail.log](https://github.com/conan-io/conan-center-index/files/5062714/Conan_GLOG_Fail.log)

**Comment by SpaceIm** [comment]
Looking at test_package in glog recipe, it injects a definition if windows and not minw. This definition should be in cpp_info.

**Comment by ShamanTcler** [comment]
Ok so your comments are welcome, but they go right over my head.

But I read so .... the recipe has 
```Bash
       if self.settings.os == "Windows":
            del self.options.fPIC
```
So the recipe deletes the fPIC option? As opposed to resetting it to False?

Not sure how this really helps me at the moment... just ignorant on how to use the information

**Comment by SpaceIm** [comment]
Not related with PIC.

In test_package:
```c++
#include <iostream>
#ifdef _WIN32
#ifndef __MINGW32__
#define GOOGLE_GLOG_DLL_DECL 
#endif
#endif
#include <glog/logging.h>

int main(int argc, char** argv) {
    google::InitGoogleLogging(argv[0]);
    LOG(INFO) << "It works";
    return 0;
}
```

These `GOOGLE_GLOG_DLL_DECL` should be injected by cmake target, not manually added by consumers. So it's a bug in glog recipe.

**Comment by ShamanTcler** [comment]
Good that means I dodged that built, not my fault.

Thanks
