### ISSUE TITLE
[package] libx265/3.2.1: hash of source tar.gz changed

### ISSUE THREAD

**Issue by cbecker** [conan-io/conan-center-index#2497]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libx265/3.2.1**
  * Operating System+version: **Linux Ubuntu 18.04 and 20.04 **
  * Compiler+version: **GCC 7.5 and 8**
  * Conan version: **conan 1.28.1**
  * Python version: **Python 3.6.8**

### Conan profile
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7.5
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Try to build libx265/3.2.1 from source. 

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: libx265/3.2.1: Error in source() method, line 50
	tools.get(**self.conan_data["sources"][self.version])
	ConanException: sha256 signature failed for 'x265_3.2.1.tar.gz' file. 
 Provided signature: 7cf8ed2927fcb2914cdca51c974594770da705cb43288beea62b69c53725b5d7  
 Computed signature: fb9badcf92364fd3567f8b5aa0e5e952aeea7a39a2b864387cec31e3b58cbbcc (edited) 
```

</details>

I'm surprised that this wasn't caught earlier. Indeed, when downloading the file manually and computing the sha256sum I get the same as the computed signature above. What's the best way to make a PR for this? Would we bump the recipe version or just overwrite the current 3.2.1?

**Comment by madebr** [comment]
This might be a upstream problem.
Maybe start by opening an issue at https://bitbucket.org/multicoreware/x265/issues

**Comment by uilianries** [comment]
Even the homepage shows the new checksum: https://bitbucket.org/multicoreware/x265/wiki/Home

Upstream's issue: https://bitbucket.org/multicoreware/x265/issues/565

**Comment by cbecker** [comment]
Thanks Ulian, indeed, I don't know what happened here. Here we noticed this issue when building the package from source.

**Comment by cbecker** [comment]
The repository doesn't exist anymore, seems to be that it was a mercurial repo and bitbucket finally stopped support for mercurial (https://bitbucket.org/multicoreware/x265/)

@madebr which alternative URL were you using?

**Comment by madebr** [comment]
@cbecker 
See the discussion in #2587
pr #2625 is using the github release.
It's not the official tarball, but has more recent releases.
