### ISSUE TITLE
[package] sdbus-cpp/2.0.0: custom CMake configuration variables have wrong names

### ISSUE THREAD

**Issue by nyibbang** [conan-io/conan-center-index#25000]
### Description

Since [this commit](https://github.com/Kistler-Group/sdbus-cpp/commit/0074c79e7fd7983dda3c2a4e4ac7febe67751a28) merged since v2.0.0 of sdbus-cpp, the project now uses variables names with a `SDBUSCPP_` prefix. The [conanfile.py recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/sdbus-cpp/all/conanfile.py) for this project however still pass the old variable names (without the prefix).

```python
    def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["BUILD_CODE_GEN"] = self.options.with_code_gen
        tc.variables["BUILD_DOC"] = False
        tc.variables["BUILD_TESTS"] = False
        tc.variables["BUILD_LIBSYSTEMD"] = False
        tc.variables["SDBUSCPP_BUILD_DOCS"] = False
        tc.variables["SDBUSCPP_SDBUS_LIB"] = self._with_sdbus
        tc.generate()
```

One of the symptoms of this bug is that setting the `with_code_gen=True` options in a consumer package has no effect (the `bin` folder is not present in the package, and the `sdbus-c++-xml2cpp` executable is not built).

The variables that have been changed are the following:

| Old variable  | New variable |
| ------------- | ------------- |
| BUILD_LIBSYSTEMD | SDBUSCPP_BUILD_LIBSYSTEMD |
| LIBSYSTEMD_VERSION | SDBUSCPP_LIBSYSTEMD_VERSION |
| LIBSYSTEMD_EXTRA_CONFIG_OPTS | SDBUSCPP_LIBSYSTEMD_EXTRA_CONFIG_OPTS |
| BUILD_CODE_GEN | SDBUSCPP_BUILD_CODEGEN |
| BUILD_EXAMPLES | SDBUSCPP_BUILD_EXAMPLES |
| BUILD_DOC | SDBUSCPP_BUILD_DOCS |
| BUILD_TESTS | SDBUSCPP_BUILD_TESTS |
| ENABLE_PERF_TESTS | SDBUSCPP_BUILD_PERF_TESTS |
| ENABLE_STRESS_TESTS | SDBUSCPP_BUILD_STRESS_TESTS |
| INSTALL_TESTS | none, the tests are always installed with the rest of the project if they're built. |
| TESTS_INSTALL_PATH | SDBUSCPP_TESTS_INSTALL_PATH |

The build recipe needs to be updated for versions 2.0.0 and above to use the new variable names, while maintaining compatibility with previous versions that use the old ones.

### Package and Environment Details

* Package Name/Version: **sbus-cpp/2.0.0**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.6.0**
* Python version: **Python 3.10.12**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

### Steps to reproduce

N/A

### Logs

N/A

**Comment by perseoGI** [comment]
Hi @nyibbang, thanks for your report!
Could you test again with the changes introduced in https://github.com/conan-io/conan-center-index/pull/24747 
This should be already fixed!

**Comment by nyibbang** [comment]
Hello,

It seems like it should fix my problem, thank you. I'll try it as soon as possible.
On a side note, it seems that it that PR, only the CODEGEN variable was changed, but not the others ? it might have unexpected effects.

**Comment by perseoGI** [comment]
Yes, I've seen it! 
I'm considering on making a PR but all variables are default to False in upstream CMakeLists
