### ISSUE TITLE
Missing prebuilt package for 'p7zip/16.02'-- Conan V2.6.0

### ISSUE THREAD

**Issue by sabapathim** [conan-io/conan-center-index#25059]
### Description

While installing p7zip/16.02 in a fresh pc Ubuntu 22.04,
It fails to install with the error message Missing prebuilt package for 'p7zip/16.02' , please find the relevant settings and log below

### Package and Environment Details

* Package Name/Version: **p7zip/16.02**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.6.0**
* Python version: **Python 3.10.6**

### Conan profile

conan profile detect
detect_api: Found cc=gcc- 11.4.0
detect_api: gcc>=5, using the major as version
detect_api: gcc C++ standard library: libstdc++11

Detected profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

### Steps to reproduce

1. Fresh Ubuntu 22.04
2. conan profile detect
3. conan install --requires p7zip/16.02 -r conancenter

### Logs

<details><summary>Click to expand log</summary>

```
conan install --requires p7zip/16.02 -r conancenter

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux


======== Computing dependency graph ========
p7zip/16.02: Not found in local cache, looking in remotes...
p7zip/16.02: Checking remote: conancenter
p7zip/16.02: Downloaded recipe revision 174a0c0e12c06fb6a3739c062df12c55
Graph root
    cli
Requirements
    p7zip/16.02#174a0c0e12c06fb6a3739c062df12c55 - Downloaded (conancenter)

======== Computing necessary packages ========
p7zip/16.02: Compatible package ID 3593751651824fb813502c69c971267624ced41a equal to the default package ID: Skipping it.
Requirements
    p7zip/16.02#174a0c0e12c06fb6a3739c062df12c55:3593751651824fb813502c69c971267624ced41a - Missing
ERROR: Missing binary: p7zip/16.02:3593751651824fb813502c69c971267624ced41a

p7zip/16.02: WARN: Can't find a 'p7zip/16.02' package binary '3593751651824fb813502c69c971267624ced41a' for the configuration:
[settings]
arch=x86_64
build_type=Release
os=Linux

ERROR: Missing prebuilt package for 'p7zip/16.02'. You can try:
    - List all available packages using 'conan list "p7zip/16.02:*" -r=remote'
    - Explain missing binaries: replace 'conan install ...' with 'conan graph explain ...'
    - Try to build locally from sources using the '--build=p7zip/16.02' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
```

</details>

**Comment by AbrilRBS** [comment]
Hi @sabapathim sorry for the lack of communication on our side on a timely manner.
The issue for the missing binaries for most platforms was due to how the recipe was handling its own test package.

I've now submitted the linked above PR to try to address the issue and publish the rest of the missing packages, but note that after team review the approach of the PR might still yet change before merging - Thanks again for your patience :)
