### ISSUE TITLE
jwt-cpp/0.7.0 : "picojson.h" is not found

### ISSUE THREAD

**Issue by sophieeihpos** [conan-io/conan-center-index#25070]
### Description

jwt-cpp/include/jwt-cpp/traits/kazuho-picojson/traits.h:7:10: fatal error: picojson.h: No such file or directory #include "picojson.h"

There is no "picojson.h" in the package; and the picojson library is not a dependency. It is not clear which "picojson.h" should be used and why.

### Package and Environment Details

* Package Name/Version: **jwt-cpp/0.7.0**
* Operating System+version: **Linux rhel7**
* Compiler+version: **GCC 8**
* Conan version: **conan 1.65.0**
* Python version: **Python 3.10.10**

### Conan profile

[settings]
os=Linux
os_build=Linux
os.distro=ubi7
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8.2
compiler.libcxx=libstdc++11
compiler.cppstd=17
build_type=Release

### Steps to reproduce

conan install --build=missing .

<conanfile.txt>
[requires]
jwt-cpp/0.7.0
openssl/1.1.1s
zlib/1.2.13
[options]
*:shared=True

### Logs

<details><summary>Click to expand log</summary>

```
jwt-cpp/include/jwt-cpp/traits/kazuho-picojson/traits.h:7:10: fatal error: picojson.h: No such file or directory #include "picojson.h"

```

</details>

**Comment by SpaceIm** [comment]
Do you link to `jwt-cpp::jwt-cpp` CMake target, so that `JWT_DISABLE_PICOJSON` can be defined?

**Comment by sophieeihpos** [comment]
The header is always included even if `JWT_DISABLE_PICOJSON` is defined. https://github.com/Thalhammer/jwt-cpp/blob/v0.7.0/include/jwt-cpp/traits/kazuho-picojson/traits.h#L7

**Comment by sophieeihpos** [comment]
We do include the specific file directly, and picojson is used actually. So we want to unset `JWT_DISABLE_PICOJSON`. I will add an option 'enable_picojson' in the recipe.
