### ISSUE TITLE
[request] hidapi/0.9.0

### ISSUE THREAD

**Issue by Psy-Kai** [conan-io/conan-center-index#2515]
### Package Details
  * Package Name/Version: **hidapi/0.9.0**
  * Source code: **https://github.com/libusb/hidapi**

### Description Of The Library / Tool
HIDAPI is a multi-platform library which allows an application to interface with USB and Bluetooth HID-Class devices on Windows, Linux, FreeBSD, and macOS.
Since June 4th, 2019 hidapi was forked by the people of libusb which will continue to maintain hidapi.

**Comment by Croydon** [comment]
Done by #5157
