### ISSUE TITLE
[package] yaml-cpp/0.6.3: ConanException: 'settings.compiler.cppstd' doesn't exist for 'Visual Studio'

### ISSUE THREAD

**Issue by MartinDelille** [conan-io/conan-center-index#2525]
[yaml-cpp/0.6.3](https://conan.io/center/yaml-cpp/0.6.3) doesn't works on windows although [yaml-cpp/0.6.2 from bincrafters](https://bintray.com/bincrafters/public-conan/yaml-cpp%3Abincrafters) works.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **yaml-cpp/0.6.3**
  * Operating System+version: **Windows 7**
  * Compiler+version: **Visual Studio 15**
  * Docker image: **N/A**
  * Conan version: **conan 1.28.1**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
C:\dev> conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Try to run conan with the following conanfile.txt:

```
[requires]
libsndfile/0.6.3

[generators]
qmake
```

And the following command: conan install .. --build missing --update

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
yaml-cpp/0.6.3: Not found in local cache, looking in remotes...
yaml-cpp/0.6.3: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
yaml-cpp/0.6.3: Downloaded recipe revision 0
ERROR: yaml-cpp/0.6.3: Error in configure() method, line 35
	if self.settings.compiler.cppstd:
	ConanException: 'settings.compiler.cppstd' doesn't exist for 'Visual Studio'
'settings.compiler' possible configurations are ['runtime', 'toolset', 'version']
```

</details>

**Comment by ericLemanissier** [comment]
you need to upgrade your settings.yml file. mine has:
```
compiler:
[...]
    Visual Studio: &visual_studio
        runtime: [MD, MT, MTd, MDd]
        version: ["8", "9", "10", "11", "12", "14", "15", "16"]
        toolset: [None, v90, v100, v110, v110_xp, v120, v120_xp,
                  v140, v140_xp, v140_clang_c2, LLVM-vs2012, LLVM-vs2012_xp,
                  LLVM-vs2013, LLVM-vs2013_xp, LLVM-vs2014, LLVM-vs2014_xp,
                  LLVM-vs2017, LLVM-vs2017_xp, v141, v141_xp, v141_clang_c2, v142]
        cppstd: [None, 14, 17, 20]
```

**Comment by MartinDelille** [comment]
Indeed.
