### ISSUE TITLE
opentelemetry-cpp/1.14.2: Missing library when building for grpc

### ISSUE THREAD

**Issue by nic-godz** [conan-io/conan-center-index#25293]
https://github.com/conan-io/conan-center-index/blob/be0cfa4278546d5931236365772fbe6c59cb1556/recipes/opentelemetry-cpp/all/conanfile.py#L308

This line is missing above in order to get the proto grpc library:
`libraries.append("opentelemetry_proto_grpc")`

https://github.com/conan-io/conan-center-index/blob/be0cfa4278546d5931236365772fbe6c59cb1556/recipes/opentelemetry-cpp/all/conanfile.py#L398

This line is missing above in order to get the complete components for grpc:
`"opentelemetry_proto_grpc",`

**Comment by AbrilRBS** [comment]
Thanks for taking the time to report the issue! Are you planning on opening a PR to address it yourself?

**Comment by nic-godz** [comment]
@AbrilRBS Sounds good. I will open an PR!

**Comment by AbrilRBS** [comment]
Closed by https://github.com/conan-io/conan-center-index/pull/25338, thanks a lot!
