### ISSUE TITLE
[request] libcurl/7.64.1 - I don't know if it should add to conan center, please advice

### ISSUE THREAD

**Issue by BillHoo** [conan-io/conan-center-index#254]
### Package Details
  * Package Name/Version: **libcurl/7.64.1**
  * Website: **https://curl.haxx.se/libcurl/**
  * Source code: **https://curl.haxx.se/download/curl-7.64.1.tar.gz**

Hi Conan team,

I'm using `libcurl/7.64.1@bincrafters/stable` for a long time, but when I see your `conan-center-index` project, I'm wondering if you could provide `libcurl/7.64.1` as an official recipe? I don't know what's the relationship between conan center and bincrafters, i feel this two are the same organization, so to use `libcurl/7.64.1` is more clear now than `libcurl/7.64.1@bincrafters/stable`

Thank you!

**Comment by Croydon** [comment]
Bincrafters is working towards getting all recipes eventually into Conan Center Index.

However, due to the sheer amount of recipes and a high quality assurance for the Conan Center Index, this will take quite some time.

libcurl is work in progress right now: https://github.com/conan-io/conan-center-index/pull/238

**Comment by jgsogo** [comment]
I've added the _closes_ keyword to the PR so this issue will be automatically fixed when merged.

@BillHoo , feel free to contribute to Conan-Center with other recipes you are already using.

**Comment by BillHoo** [comment]
@Croydon @jgsogo Thank you for let me know! That's really a good news for me.

BTW, will Conan Center Index's CI system check all the main stream platform's build? I'm always cross-compile recipes from Macos to Android, Macos to iOS, Windows, Linux etc, sometimes I will find bugs when cross-compiling, but if your CI could check it at the very first time, that's really a big enhancement of Conan Center's quality.

**Comment by Croydon** [comment]
Check out the wiki: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Comment by danimtb** [comment]
@BillHoo the building service is not cross-building packages at this moment. We only support the configurations linked above. However, PRs that improve recipes to support cross-building or any other platform are always welcomed 😄
