### ISSUE TITLE
[package] cpython/3.9.19: Won't propagate downstream

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan-center-index#25463]
### Description

Hello,

I am unsure whether this belongs to the main conan repo or to this one. I opened https://github.com/conan-io/conan/issues/16927 but as I do not have the rights to move it, I am opening a duplicate here.

### Package and Environment Details

* Package Name/Version: **cpython/3.9.19**
* Operating System+version: **Rocky Linux 9.3**
* Compiler+version: **CLANG 17.0.6**
* Conan version: **conan 2.7.1**
* Python version: **Python 3.9.18**
* Docker image: **rockylinux:9.3-minimal**

### Conan profile

{% set compiler, version, compiler_exe = detect_api.detect_clang_compiler(compiler_exe="clang") %}
{% set version = detect_api.default_compiler_version(compiler, version) %}

[settings]
arch={{detect_api.detect_arch()}}
build_type=Release
compiler={{compiler}}
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version={{version}}
os={{detect_api.detect_os()}}

[conf]
test*/*:tools.cmake.cmaketoolchain:generator=Ninja
test*/*:tools.cmake.cmake_layout:build_folder_vars = ["settings.os", "settings.compiler"]
tools.build:compiler_executables = {"c": "clang", "cpp": "clang++", "rc": "llvm-rc"}
test*/*:tools.build:cxxflags=["-fansi-escape-codes -fcolor-diagnostics"]
test*/*:tools.build:exelinkflags=["-fuse-ld=lld"]
test*/*:tools.build:sharedlinkflags=["-fuse-ld=lld"]

### Steps to reproduce

- Run the docker container `docker run -it --rm rockylinux:9.3-minimal`
- Install some system packages:
```bash
microdnf install --enablerepo=crb --assumeyes --nodocs --noplugins --setopt=install_weak_deps=0 --setopt=keepcache=0 \
	llvm-toolset-17.0.6-5.el9 \
	git \
	make \
	perl-4:5.32.1-481.el9 \
	python3-3.9.18-3.el9_4.5 \
	python3-devel-3.9.18-3.el9_4.5 \
	python3-pip-21.2.3-8.el9 \
	python3-setuptools-53.0.0-12.el9_4.1
```
- Then install pip packages:
```bash
python3 -m pip install conan==2.7.1 cmake==3.28.3 ninja==1.11.1.1 numpy==1.26.4 --no-cache-dir
```

- Clone the example:
```bash
git clone --depth 1 https://github.com/Todiq/test_conan && cd test_conan && python3 build.py
```

### Logs

<details><summary>Click to expand log</summary>

```bash
======== Calling build() ========
conanfile.py (test_beta/1.0): Calling build()
conanfile.py (test_beta/1.0): Running CMake.configure()
conanfile.py (test_beta/1.0): RUN: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/workspace/test_conan/beta" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/workspace/test_conan/beta"
-- Using Conan toolchain: /workspace/test_conan/beta/build/linux-clang/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=OFF (options.fPIC)
-- Conan toolchain: Defining architecture flag: -m64
-- Conan toolchain: Defining libcxx as C++ flags: -stdlib=libstdc++
-- Conan toolchain: C++ Standard 17 with extensions OFF
-- Conan toolchain: Setting BUILD_SHARED_LIBS = ON
-- Configuring done (0.6s)
CMake Error at betaimpl/CMakeLists.txt:10 (target_link_libraries):
  Target "betaimpl" links to:

    Python::Python

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done (0.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

ERROR: conanfile.py (test_beta/1.0): Error in build() method, line 63
        cmake.configure()
        ConanException: Error 1 while executing
Traceback (most recent call last):
  File "/workspace/test_conan/build.py", line 21, in <module>
    run(f"conan build --profile:all {profile} beta --no-remote")
  File "/workspace/test_conan/build.py", line 8, in run
    raise Exception(f"Failed CMD: {cmd}")
Exception: Failed CMD: conan build --profile:all ./profiles/clang beta --no-remote
```

</details>

**Comment by Ahajha** [comment]
I notice that `alpha` does `find_package(Python ...)`, but `beta` does `find_package(Python3 ...)`. This might be a/the cause of the error, or maybe it's unrelated.

The CPython package is a little special with its CMake support, it leverages CMake's built in FindPython(3) support. There are 2 wrapper files (one for FindPython, one for FindPython3) that are generated as part of the CPython package (https://github.com/conan-io/conan-center-index/blob/master/recipes/cpython/all/conanfile.py#L673). It's possible this relatively unique interaction is related.

**Comment by Ahajha** [comment]
I was able to get your example working (on Ubuntu 22.04) with the following patch:
```patch
diff --git a/alpha/CMakeLists.txt b/alpha/CMakeLists.txt
index 03cb64e..e2a6d62 100644
--- a/alpha/CMakeLists.txt
+++ b/alpha/CMakeLists.txt
@@ -21,7 +21,7 @@ if (WIN32)
 endif()
 
 find_package(Boost COMPONENTS REQUIRED boost filesystem log program_options python QUIET)
-find_package(Python COMPONENTS Development QUIET)
+find_package(Python3 COMPONENTS Development QUIET)
 
 # Library
 
@@ -43,7 +43,7 @@ target_include_directories(${PROJECT_NAME}
 target_link_libraries(${PROJECT_NAME}
 	PUBLIC
 		Boost::python
-		Python::Python
+		Python3::Python
 )
 
 install(TARGETS ${PROJECT_NAME})
\ No newline at end of file
diff --git a/beta/betaimpl/CMakeLists.txt b/beta/betaimpl/CMakeLists.txt
index 8c11038..66c94a4 100644
--- a/beta/betaimpl/CMakeLists.txt
+++ b/beta/betaimpl/CMakeLists.txt
@@ -7,10 +7,12 @@ target_sources(${PROJECT_NAME}
 		src/betaimpl.cpp
 )
 
+find_package(Python3 COMPONENTS Development QUIET)
+
 target_link_libraries(${PROJECT_NAME}
 	PRIVATE
         Alpha::test
-		Python::Python
+		Python3::Python
 )
 
 target_include_directories(${PROJECT_NAME}
```

A couple of things do seem off to me though:
- cpython::cpython seems to be using Python3::Python rather than Python::Python
- The need for the extra `find_package(Python3 ...)` is suspicious. There was a bug a few years back (around Conan 1.51 or so) about find_packages being sensitive where they were called in the directory tree, perhaps somehow there's something going on there. It's also possible the nested `project` call is related, it's not a pattern I use personally so I don't know the nuance there.

Hopefully the patch can get you working again, but I think there's probably a bug in the CPython package somewhere.

**Comment by Todiq** [comment]
Hello @Ahajha,

That did the trick, thanks a lot!
