### ISSUE TITLE
[package] xerces-c/3.2.5: dependency on nsl

### ISSUE THREAD

**Issue by valiko-ua** [conan-io/conan-center-index#25502]
### Description

The following PR: https://github.com/conan-io/conan-center-index/pull/25060
("xerces-c: Fix clang compilation issue on Windows")
broke compilation of our stuff on Red Hat 9.
The PR says it's for Windows but it introduces dependency on nsl library for Linux:
```
elif self.settings.os in ["Linux", "FreeBSD"]:
    self.cpp_info.system_libs.extend(["pthread", "nsl"])
```
The libnsl.so library seems unnecessary for xerces-c on Red Hat 9.

Problematic version of xerces-c recipe: dac49cb4f4b99435670ed8ea0b03fa11
Previous version of this recipe works fine: eaa4f49d6f4fa9351c8b706957ef0a99

### Package and Environment Details

* Package Name/Version: **xerces-c/3.2.5**
* Operating System+version: **Red Hat Enterprise Linux 9.4 (Plow)**
* Compiler+version: **GCC 11**
* Docker image: **redhat/ubi9**
* Conan version: **conan 1.65.0**
* Python version: **Python 3.9.18**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

N/A

### Logs

```
[ 34%] Linking CXX shared library libblablabla.so
/usr/bin/ld: cannot find -lnsl
```

**Comment by curlybeast** [comment]
This affects us too. We've had to work around this by duplicating the recipe and reverting this change.

**Comment by jcar87** [comment]
Apologies, this was an oversight - we'll look into it and fix it

**Comment by jcar87** [comment]
Fix proposed in https://github.com/conan-io/conan-center-index/pull/25593
(turns out nsl is not used anyway)

**Comment by valiko-ua** [comment]
Thanks, it works now.
