### ISSUE TITLE
[question] Recipes cannot build due to not specifying CMake as tool/build requirements

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan-center-index#25533]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

There are recipes that uses CMake to build, but they do not specify CMake as a `tool_requires` or `build_requires`.
For example `ninja/1.10.2`: https://github.com/conan-io/conan-center-index/blob/master/recipes/ninja/1.10.x/conanfile.py
So when there are no binaries for the particular configuration, and the recipe needs to build them, it does not find the `cmake` binary in the path.

Also a lot of these recipes do not yet use `CMakeDeps` and `CMakeToolchain` but still uses the legacy `cmake` generator.

We are essentially building a set of reusable base Conan recipes and profiles and to isolate ourselves from ConanCenter changes we host 3rd party recipes on our own Artifactory server. For now, we just upload the recipes and have clients build the binaries themselves to their local cache.
This is how this problem became visible: the `ninja/1.10.2` recipe was on our own Artifactory store and when we define `ninja` as a build requirement, it could not be built as `cmake` was not in the path **even though we specify `cmake/3.19.4` as a build requirement ourselves as well** (which does [update](https://github.com/conan-io/conan-center-index/blob/master/recipes/cmake/3.x.x/conanfile.py#L112) the `self._env_info.PATH` to include its binary path to the `cmake` binary), but this never gets triggered as the `ninja/1.10.2` recipe does not set cmake as a dependency of its own.

How is this supposed to be solved? What is the general approach here?

**Comment by AbrilRBS** [comment]
Closing for the reasons mentioned above, the policy for CCI is still to expect some tools/toolchains to already be present in the developer machine, and CMake is one of them.

Either way, thanks for taking the time to open the issue in the first place, we appreciate it :)
