### ISSUE TITLE
[question] How to specify windows version for Boost conan package?

### ISSUE THREAD

**Issue by Alexolut** [conan-io/conan-center-index#25555]
I use Boost 1.84 package from [conan.io][1]. Since Boost 1.84 [default version of Windows API][2] is set to Windows 10.

```none
By default use Windows 10 API on compilers that support it and latest versions on the others
```

I need to specify other, in particular `_WIN32_WINNT_WIN7 0x0601`. As far as I understand it can be achieved by passing define like `BOOST_USE_WINAPI_VERSION=0x0601` to conan recipe somehow. How can I do this?

Tried the following changes in `export/conanfile.py`, but no luck:

```
cxx_flags.append(f"-DBOOST_USE_WINAPI_VERSION=0x0601")
self.cpp_info.components["headers"].defines.append("BOOST_USE_WINAPI_VERSION=0x0601")
```

I use conan 1.65

  [1]: https://conan.io/center/recipes/boost?version=
  [2]: https://www.boost.org/doc/libs/1_84_0/boost/winapi/config.hpp

**Comment by uilianries** [comment]
Hello @Alexolut !

> I need to specify other, in particular _WIN32_WINNT_WIN7 0x0601. As far as I understand it can be achieved by passing define like BOOST_USE_WINAPI_VERSION=0x0601 to conan recipe somehow. How can I do this?

You can use Conan config to pass directly to b2 when building the package, without changing the recipe: https://docs.conan.io/2/reference/config_files/global_conf.html

You can add to your Conan profile directly, or pass via command with `-c `:

```
# boost profile
[conf]
tools.build:defines=["BOOST_USE_WINAPI_VERSION=0x0601"]
```

Or, via command line: 

    conan install -r conancenter --requires=boost/1.84.0 --build=boost -c:a 'tools.build:defines=["BOOST_USE_WINAPI_VERSION=0x0601"]'
    
The Boost recipe is using a wrapper for B2, but is capable to read that configuration and pass directly to the compiler.

Please, note that Conan 1.x will no longer be supported by next month (November-2024), please, update your Conan client to 2.x asap. More info: https://github.com/conan-io/conan-center-index/discussions/25461

**Comment by uilianries** [comment]
> Can I distinguish binary packages built with and without such define?

Yes. Still in the configuration, the `tools.info.package_id:confs` is capable to customize the package ID, based on specific configurations. To this specific case, you would need to add:

    tools.info.package_id:confs=['tools.build:defines']
    
This will create a new package ID, based on the hash to of that value, so in case you change the defines value, it will generate another package ID.

**Comment by Alexolut** [comment]
> Still in the configuration, the `tools.info.package_id:confs`

It seems that this option is not available in Conan 1.x. I don't see it in the list returned by `conan config list` call. 

Even in case of Conan 2.x how can I specify additional definition only for one particular recipe? Because I don't want that new macro definition will affect all other recipes' package_id.

What other way I can use to add additional compile definition during building Boost recipe? Maybe the easiest option is to modify default conan.io recipe and just add extra string option to recipe?

**Comment by uilianries** [comment]
> It seems that this option is not available in Conan 1.x. I don't see it in the list returned by conan config list call.

Unfortunately Conan 1.x has no such configuration, just checked too: https://docs.conan.io/1/reference/config_files/global_conf.html

> Even in case of Conan 2.x how can I specify additional definition only for one particular recipe? Because I don't want that new macro definition will affect all other recipes' package_id.

You can use Profile Patterns to filter configuration by packages: https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns

> What other way I can use to add additional compile definition during building Boost recipe? Maybe the easiest option is to modify default conan.io recipe and just add extra string option to recipe?

That's an option, but then you will need to merge manually when doing updates related to Conan Center, as both recipes will diverge.

**Comment by Alexolut** [comment]
> then you will need to merge manually when doing updates related to Conan Center, as both recipes will diverge.

What do you think, maybe it's worth to make an option for recipe (in conan.io) specifying WinAPI version? Or what the criteria for something to be on the options level?

**Comment by uilianries** [comment]
Closing issues as it's answered.
