### ISSUE TITLE
[service] Allow building of multiple recipes of same package in one PR

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#2556]
Current CI does not allow changing 2 recipes for one package in one pr.

e.g. modifying:
- `recipes/zlib/1.2.8/conanfile.py`
- `recipes/zlib/1.2.12/conanfile.py`

in **one** pull request is impossible, because the CI will fail immediately.

This should become possible. It would also make maintaining recipes **a lot easier**

Imho, this is a high priority request, because arbitrary rules like these scare people of.

**Comment by uilianries** [comment]
Indeed it's annoying and as consumer I can't see the limitation because is the same project. On the other hand, as server maintainer, it requires a new feature because all current implementation involving config.yml. 

/cc @danimtb

**Comment by Croydon** [comment]
But does it really make a huge difference in the implementation? (Friendly reminder of #30) 

First step is like always reading the content of `config.yml` and this contains the path information. And then there is probably an explicit check if those paths differ. But all of the logic afterwards can probably stay the same?

**Comment by uilianries** [comment]
This is under investigation, but not in short time, because will require not an update in Jenkins, but an entire new build flow.

**Comment by ericLemanissier** [comment]
@uilianries it already works : https://github.com/conan-io/conan-center-index/pull/22929 this issue is about building several recipes of the SAME package only

**Comment by uilianries** [comment]
Sorry, I misread the "same package". I meant several recipes from different packages.
