### ISSUE TITLE
[package] bzip2/1.0.8: error loading conanfile

### ISSUE THREAD

**Issue by villarrealcesar** [conan-io/conan-center-index#25566]
### Description

Recipe does not work I get these errors:
ERROR: Package 'bzip2/1.0.8' not resolved: bzip2/1.0.8: Cannot load recipe.
Error loading conanfile at 'C:\Users\Alejandro\.conan2\p\bzip21c7034df28bd4\e\conanfile.py': Unable to load conanfile in C:\Users\Alejandro\.conan2\p\bzip21c7034df28bd4\e\conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Alejandro\.conan2\p\bzip21c7034df28bd4\e\conanfile.py", line 3, in <module>
    from conans import ConanFile, CMake, tools
ImportError: cannot import name 'ConanFile' from 'conans' (C:\Users\Alejandro\AppData\Local\Programs\Python\Python310\lib\site-packages\conans\__init__.py)

### Package and Environment Details

* Package Name/Version: **bzip2/10.8**
* Operating System+version: **Windows 10**
* Compiler+version: **msvc**
* Conan version: **conan 2.8.0**
* Python version: **Python 3.10.11**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=192
os=Windows

### Steps to reproduce

conan install conanfile.txt -s build_type=Release -s arch=x86_64 -s compiler.runtime=static -s compiler.version=192 --build=missing -r=conancenter

### Logs

<details><summary>Click to expand log</summary>
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=static
compiler.runtime_type=Release
compiler.version=192
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows

======== Computing dependency graph ========
Graph root
    conanfile.txt: C:\Development\examsoft-softestv12\ThirdParty\conan\win\conanfile.txt
*********************************************************
Recipe 'bzip2/1.0.8' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'bzip2/1.0.8' not resolved: bzip2/1.0.8: Cannot load recipe.
Error loading conanfile at 'C:\Users\Alejandro\.conan2\p\bzip21c7034df28bd4\e\conanfile.py': Unable to load conanfile in C:\Users\Alejandro\.conan2\p\bzip21c7034df28bd4\e\conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Alejandro\.conan2\p\bzip21c7034df28bd4\e\conanfile.py", line 3, in <module>
    from conans import ConanFile, CMake, tools
ImportError: cannot import name 'ConanFile' from 'conans' (C:\Users\Alejandro\AppData\Local\Programs\Python\Python310\lib\site-packages\conans\__init__.py)

</details>

**Comment by uilianries** [comment]
@villarrealcesar Hello! I can see your error is pointing to the old imports conans:

> ImportError: cannot import name 'ConanFile' from 'conans' 

The current recipe in ConanCenterIndex uses `conan`, including the version available in Conan Center: https://conan.io/center/recipes/bzip2

You are consuming an outdated recipe revision, with support for Conan 1.x only. You have to update it in order to use bzip with Conan 2.x:

    conan install -r conancenter --update --requires=bzip2/1.0.8 --build=bzip2/1.0.8 -s compiler.runtime=static -s compiler.version=192
    
As you are using a conanfile.txt, you could use the same `--update` argument to force updating the packages and recipes in your cache. In Conan client finds a newer recipe revision to any package listed in your conanfile.txt, or their dependencies, Conan will update it and try to install a compatible pre-built package.

**Comment by uilianries** [comment]
Thank you for your feedback!
