### ISSUE TITLE
[package] libarchive/3.7.4 (and other versions too): Calling convention conflict on Windows x86 with zlib.

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan-center-index#25565]
### Description

We are facing a `__cdecl` vs `__stdcall` issue in one of our projects on Windows when targeting x86. This projects requires both zlib/1.2.13 and libarchive/3.7.4.

Basically, when linking the final application, we get linker errors such as:

> archive.lib(archive_write_set_format_7zip.obj) : error LNK2019: unresolved external symbol _crc32@12 referenced in func
> tion __7z_close [our.vcxproj]
> archive.lib(archive_write_set_format_zip.obj) : error LNK2001: unresolved external symbol _crc32@12 [our.vcxproj]
>     Hint on symbols that are defined and could potentially match:
>       _crc32

To confirm the problem `dumpbin /SYMBOLS zlib.lib` list defined symbols such as `crc32`, whereas `dumpbin /SYMBOLS archive.lib` shows UNDEF symbols such as `_crc32@12`.

It appears that the recipe for zlib on Conancenter does not define ZLIB_WINAPI macro, resulting in `__cdecl` convention for the library. Yet, digging into libarchive recipe [we found patches](https://github.com/conan-io/conan-center-index/blob/08d6b641f8a6b9c95379986c846c447b95a2b786/recipes/libarchive/all/patches/0001-3.7.4-zlib-winapi.patch) that override a test intended to deduce if zlib was compiled with ZLIB_WINAPI (see [zlibCompileFlags() in the manual](https://zlib.net/manual.html)), and always define the macro instead, creating an inconsistency in this situation.

### Package and Environment Details

* Package Name/Version: **libarchive/3.7.4**
* Operating System+version: **Windows 10**
* Compiler+version: **msvc**
* Conan version: **conan 2.5.0**

### Conan profile

[settings]
arch=x86
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=static
compiler.runtime_type=Release
compiler.version=193
os=Windows
[options]
libarchive/*:with_lzma=True
[tool_requires]
*: cmake/3.27.7

### Steps to reproduce

Please see PR #25567.

### Logs

<details><summary>Click to expand log</summary>

```
archive.lib(archive_write_set_format_7zip.obj) : error LNK2019: unresolved external symbol _crc32@12 referenced in func
tion __7z_close [our.vcxproj]
archive.lib(archive_write_set_format_zip.obj) : error LNK2001: unresolved external symbol _crc32@12 [our.vcxproj]
    Hint on symbols that are defined and could potentially match:
      _crc32
```

</details>

**Comment by jcar87** [comment]
Thanks for reporting this @Adnn - I'm looking into this

I think there's two issues

zlib recipe:
> It appears that the recipe for zlib on Conancenter does not define ZLIB_WINAPI macro,

is the recipe supposed to? in what scenarios is this macro supposed to be defined ? any insights are appreciated !

> Yet, digging into libarchive recipe [we found patches](https://github.com/conan-io/conan-center-index/blob/08d6b641f8a6b9c95379986c846c447b95a2b786/recipes/libarchive/all/patches/0001-3.7.4-zlib-winapi.patch) that override a test intended to deduce if zlib was compiled with ZLIB_WINAPI (see [zlibCompileFlags() in the manual](https://zlib.net/manual.html)), and always define the macro instead, creating an inconsistency in this situation.

will fix this - apologies for the disruption!

**Comment by jcar87** [comment]
Hi @Adnn  - this should restore the check in libarchive https://github.com/conan-io/conan-center-index/pull/25596
the patch predates the fix in the recipe that actually made the patch work - unfortunately there was no record of the specific error behind this in the original PR. Since then, we now require contributors for these sort of fixes to please detail exactly _what error_ is being fixed, so that we can have this for reference in the future.

**Comment by Adnn** [comment]
Hi @jcar87 , and thank you very much for taking the time to address this issue!

You are right that the issue is because of the interactions between both `zlib` and `libarchive`.

> is the recipe supposed to [define ZLIB_WINAPI]? in what scenarios is this macro supposed to be defined ? any insights are appreciated !

I must admit I only learnt about this macro to try to understand this issue, so I will not be in a position to give a satisfying answer. But as an attempt to give the information I found while investigating:
[The intent of `ZLIB_WINAPI`](https://github.com/madler/zlib/blob/d476828316d05d54c6fd6a068b121b30c147b5cd/zconf.h#L344C1-L347C4) is as the name indicate to build zlib with the "winapi" calling convention (which uses the `__stdcall` calling convention on x86 host).

As far as I could observe while investigating this issue, we can mix both `__stdcall` and `__cdecl` calling conventions in a compiled binary (as long as the function declarations match, of course), so the macro is not necessary in the common use case of building a C or Cpp application.
Yet, [from the FAQ](https://github.com/madler/zlib/blob/d476828316d05d54c6fd6a068b121b30c147b5cd/win32/DLL_FAQ.txt#L186-L199), it seems that some environments, such as loading a DLL in Visual Basic, might requires a specific calling convention. I suppose this is the rationale to allow such control.

As far as I understand, I don't think zlib recipe should define it by default. Yet, if the recipe was intended to also support scenarios such as binding to Visual Basic, it should probably be offered as a recipe option. (And it seems that it shoud then become part of the recipe exported package_info, removing the burden from downstream to try and retrieve this information).
