### ISSUE TITLE
[package] bgfx/cci.20230216: Add MSVC version 194

### ISSUE THREAD

**Issue by danniesim** [conan-io/conan-center-index#25619]
### Description

The latest version of MSVC 2022 presents as version 194; there is no key to handle that number, resulting in a key error when building.

### Package and Environment Details

* Package Name/Version: ** bgfx/cci.20230216**
* Operating System+version: **Windows 10**
* Compiler+version: **MSVC 194 (VS 2022)**
* Conan version: **2.8.0**
* Python version: **Python 3.10.13**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=194
os=Windows

### Steps to reproduce

conan install -r conancenter bgfx/cci.20230216@ -pr:b=default -pr:h=default

### Logs

<details><summary>Click to expand log</summary>

```
Key error 194
```

</details>

**Comment by danniesim** [comment]
Pull request: #25606

**Comment by AbrilRBS** [comment]
Closing as solved, thanks!
