### ISSUE TITLE
[package] cpython/*: Python interpreter not accessible at build time (cannot find libpython3.9.so) when Shared=True

### ISSUE THREAD

**Issue by NormanT7** [conan-io/conan-center-index#25681]
### Description

We have several projects that need to both build against libpython and also run the interpreter at build time. The use case is building a python extension module and then creating and running tests of the resulting extension module. 

The recipe puts the python interpreter on the build environment PATH variable but does not add the lib folder to the LD_LIBRARY_PATH. The consequence is that python interpreter is found but produces the following error when running it:
".conan2/data/b/cpyth347c65398e299/p/bin/python: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory"

The lib folder is correctly added to the conan run environment. However, we need it in the build environment because that is what conan activates while running the build() method. 

Setting cpython as a build requirement (build=True for the requirement trait) isn't a valid solution because we are also linking against libpython and want it to behave like a normal requirement and be propagated to downstream dependencies.

Can the cpython package_info method be updated to append the lib folder to the LD_LIBRARY_PATH in the case of OS=Linux and Shared=True?

On Windows, the dll sits right next to the python.exe in the conan package, so it doesn't have any issues finding it.

### Package and Environment Details

* Package Name/Version: **cpython/3.9.19**
* Operating System+version: **Linux REHL 8.10 **
* Compiler+version: **GCC 12**
* Conan version: **conan 2.8.0**

### Conan profile

[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=12
compiler.cppstd=17
compiler.libcxx=libstdc++11
build_type=Release

### Steps to reproduce

1. Install cpython package on Linux with cpython/*:shared=True
2. Activate the build environment that conan produces (e.g. build/Release/generators/conanbuild.sh)
3. Run python

### Logs

None

**Comment by SpaceIm** [comment]
```
Setting cpython as a build requirement (build=True for the requirement trait) isn't a valid solution because we are also linking against libpython and want it to behave like a normal requirement and be propagated to downstream dependencies.
```

Sorry but cpython is a build requirement of your project. It's both a requirement and a build requirement. You can use `<host_version>` in build requirement to ensure that both versions in build & host requirements are the same.

**Comment by NormanT7** [comment]
@SpaceIm Thanks for your response. Sorry for my ignorance regarding this Conan functionality. I didn't realize I could specify the same requirement twice in Conan, as both a normal requires and a tool_requires. Using this approach, I was able to get a build environment where I could find and use the interpreter using CMake as well as link against the python libraries.

As an aside, I could only get the line "find_package (Python COMPONENTS Interpreter Development)" to work in my CMakeLists.txt if Conan was using the exact same cpython package for both the requires and the tool_requires. Otherwise, the cmake configure would fail with the following:

-- Conan: Including build module from '/home/xxxx/.conan2/data/b/cpyth347c65398e299/p/lib/cmake/use_conan_python.cmake'
CMake Error at /xxxx/cmake/cmake-3.30.4-linux-x86_64/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  **Could NOT find Python (missing: Interpreter Development Development.Module**
  Development.Embed) (found version "3.9.19")
Call Stack (most recent call first):
  /xxxx/cmake/cmake-3.30.4-linux-x86_64/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  /xxxx/cmake/cmake-3.30.4-linux-x86_64/share/cmake-3.30/Modules/FindPython.cmake:673 (find_package_handle_standard_args)
  /home/xxxx/work/.conan2/data/b/cpyth347c65398e299/p/lib/cmake/use_conan_python.cmake:14 (include)
  build/Release/generators/FindPython.cmake:38 (include)
  MyProject/CMakeLists.txt:8 (find_package)

 Maybe that is to be expected. Either way, I have a path forward and this issue can be closed.
