### ISSUE TITLE
[package] CLI11 should not be header only

### ISSUE THREAD

**Issue by vasama** [conan-io/conan-center-index#25737]
### Description

CLI11 supports building as a static library, but the Conan recipe is always header only.

### Package and Environment Details

N/A

### Conan profile

N/A

### Steps to reproduce

N/A

### Logs

N/A

**Comment by uilianries** [comment]
Correct. The CLI11 project offers an option to build static library: https://github.com/CLIUtils/CLI11/blob/v2.4.2/CMakeLists.txt#L82

I would suggest adding header-only option and enabling it by default, so we will not affect the current Package ID for users.

**Comment by vasama** [comment]
I implemented this here: https://github.com/vasama/conan-center-index/tree/cli11-precompiled
Waiting for access in https://github.com/conan-io/conan-center-index/issues/4.

**Comment by YanzhaoW** [comment]
Hi

Is it possible to add fPIC flag as well? I can't use the static library version as it's not compiled with `-fPIC` flag.

 My system is Fedora 42 and compiler is gcc15.

**Comment by uilianries** [comment]
@YanzhaoW Hello! Good catch, it should contain fPIC option as well. Please, feel free to open a PR contributing with that fix. Your contribution will be very welcome! 😄
