### ISSUE TITLE
[package]  paho-mqtt-c/1.3.4+: default value for shared should be False

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#2574]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **paho-mqtt-c/1.3.4**

For  paho-mqtt-c >= 1.3.4 the default value for `shared` should be `False`
For < 1.3.4 the default should remain `True`

Background:
https://github.com/conan-io/conan-center-index/pull/1888#pullrequestreview-430147184
https://github.com/conan-io/conan-center-index/issues/2566
https://github.com/conan-io/hooks/issues/217

**Comment by Croydon** [comment]
So, can we change the values of `default_options` based on the recipe version without having to split them in two recipes?

 * `init()` does not work, because `self.version` isn't yet available 
 * adding an `if` directly within the `default_options` dict does not work because `self.version` isn't available yet
 * setting `self.default_options["shared"] = True` in `config_options()` has no effect - why exactly is this?
 * doing anything in `configure()` and later is too late as options are set

**Comment by a4z** [comment]
No, the default value should be static, if you need a Windows special build, set it to dynamic in your profile.

Beside the fact that I have a hard time believing that the static build does not work on windows, since I am pretty sure I have build static libs of mqtt-c and mqtt-cpp on Windows, it is never good to make the edge case the default

**Comment by Croydon** [comment]
> No, the default value should be static, if you need a Windows special build, set it to dynamic in your profile.

shared = False is static 😄 

> Beside the fact that I have a hard time believing that the static build does not work on windows

Please read https://github.com/conan-io/conan-center-index/pull/1888#pullrequestreview-430147184. I think that the library authors knows best 😃

**Comment by uilianries** [comment]
> setting self.default_options["shared"] = True in config_options() has no effect - why exactly is this?

Default options is loaded just after initializing the ConanFile instance, after that, Conan won't look again at default_options. Instead, it will consult self.options.

https://github.com/conan-io/conan/blob/1ba01e69166c5c82c43c494e982d358450690583/conans/model/conan_file.py#L28

But are able to change the default option, according the version:

```
from conans import ConanFile, tools


class MyPackage(ConanFile):
    name = "package"
    options = {"foo": [True, False]}
    default_options = {"foo": True}

    def config_options(self):
        if Version(self.version) >= "1.0.0":
            self.options.foo = False

    def configure(self):
        print("FOO: %s" % self.options.foo)
```

As `config_options` is executed before processing the options, you can override its value. That will work as `default_options`. Whatever you pass by command line (e.g -o package:foo=True), will be processed only after `config_options`.

**Comment by Croydon** [comment]
> As config_options is executed before processing the options, you can override its value. 

Ooops. I was thinking way too complicated. Thanks @uilianries!

**Comment by a4z** [comment]
> > No, the default value should be static, if you need a Windows special build, set it to dynamic in your profile.
> 
> shared = False is static 😄

Ok, as long as the right default is the default, that is always static, I am happy :-) 

> > Beside the fact that I have a hard time believing that the static build does not work on windows
> 
> Please read [#1888 (review)](https://github.com/conan-io/conan-center-index/pull/1888#pullrequestreview-430147184). I think that the library author knows best 😃

Maybe, mayby not, looking at the cmake build scripts of libs like paho-mqtt-c and paho-mqtt-cpp ...but anyhow.... 

soemthing different, there are 2  cmake patches,  0003-fix-cmake-install.patch and 0004-fix-cmake-install.patch ? this looks a bit ... chaotic ? 
and is hard to debug if something is not how it should be
or do I get something wrong? are they not for the same file ?

**Comment by SpaceIm** [comment]
Just to mention that https://github.com/conan-io/conan-center-index/pull/2575 breaks `paho-mqtt-cpp` on Windows if `paho-mqtt-cpp` static (and `paho-mqtt-cpp` can't be shared on Windows...).
Why? Because:
- `paho-mqtt-cpp` overrides shared option of `paho-mqtt-c` with its own value. (`paho-mqtt-cpp` static => `paho-mqtt-c` static).
- `paho-mqtt-c` also overrides its own shared option if version < "1.3.4", in order to be always shared but... in `config_options`, which has not effect I guess (should happen in `configure` method).
- `paho-mqtt-c` then raise a `ConanInvalidConfiguration` if shared=False and Windows and version < 1.3.4, and it raises obviously.

**Comment by Croydon** [comment]
From the `paho-mqtt-cpp` readme:

> The Paho C++ library requires the Paho C library, v1.3.1 or greater

https://github.com/eclipse/paho.mqtt.cpp#building-from-source

Assuming that it is indeed compatible, we can update the `paho-mqtt-c` version in `paho-mqtt-cpp` to `1.3.4` and it should be fine?
