### ISSUE TITLE
[request] cli/2.2.0

### ISSUE THREAD

**Issue by daniele77** [conan-io/conan-center-index#25742]
### Package Name/Version

cli/2.2.0

### Changelog

https://github.com/daniele77/cli/releases/tag/v2.2.0

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by AbrilRBS** [comment]
Thanks @toge for providing the new issue, super appreciated as always :)
