### ISSUE TITLE
[package] wayland-protocol/1.33: seems broken or not ready for conan 2

### ISSUE THREAD

**Issue by shackra** [conan-io/conan-center-index#25764]
### Description

ERROR: Package 'wayland-protocols/1.33' not resolved: wayland-protocols/1.33: Cannot load recipe.
Error loading conanfile at '/home/jorge/.conan2/p/waylacf485377ad282/e/conanfile.py': Current Conan version (2.0.17) does not satisfy the defined one (>=1.64.0 <2 || >=2.2.0)..

### Package and Environment Details

not relevant

### Conan profile

[requires]
eastl/3.21.12
joltphysics/3.0.1
diligent-core/api.252009

[generators]
CMakeDeps
CMakeToolchain

### Steps to reproduce

conan install conanfile.txt

### Logs

<details><summary>Click to expand log</summary>

💀  conan install conanfile.txt

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

======== Computing dependency graph ========
eastl/3.21.12: Not found in local cache, looking in remotes...
eastl/3.21.12: Checking remote: conancenter
eastl/3.21.12: Downloaded recipe revision 67185fecd6fc1439394cc7e6cdf4b6aa
eabase/2.09.12: Not found in local cache, looking in remotes...
eabase/2.09.12: Checking remote: conancenter
eabase/2.09.12: Downloaded recipe revision abdc26b253aece76cc2bfe0d7e21e04a
joltphysics/3.0.1: Not found in local cache, looking in remotes...
joltphysics/3.0.1: Checking remote: conancenter
joltphysics/3.0.1: Downloaded recipe revision 3f0ab4e3593371b937e239bdc22702c3
cmake/3.30.5: Not found in local cache, looking in remotes...
cmake/3.30.5: Checking remote: conancenter
cmake/3.30.5: Downloaded recipe revision 540068cc37f1d21b42b729c82d6bcb29
diligent-core/api.252009: Not found in local cache, looking in remotes...
diligent-core/api.252009: Checking remote: conancenter
diligent-core/api.252009: Downloaded recipe revision 88cf924aeaa270e277383d0e88661513
opengl/system: Not found in local cache, looking in remotes...
opengl/system: Checking remote: conancenter
opengl/system: Downloaded recipe revision 4df6fecde4084386beded3ed0e56e4ea
wayland/1.22.0: Not found in local cache, looking in remotes...
wayland/1.22.0: Checking remote: conancenter
wayland/1.22.0: Downloaded recipe revision 284b56bdbe57868770f46100784e3b4d
libffi/3.4.4: Not found in local cache, looking in remotes...
libffi/3.4.4: Checking remote: conancenter
libffi/3.4.4: Downloaded recipe revision 72cccac6139293b6e97ec9cd676547ff
libxml2/2.13.4: Not found in local cache, looking in remotes...
libxml2/2.13.4: Checking remote: conancenter
libxml2/2.13.4: Downloaded recipe revision 72b3bfba0c37dfe22f20c587cc468f4c
zlib/1.3.1: Not found in local cache, looking in remotes...
zlib/1.3.1: Checking remote: conancenter
zlib/1.3.1: Downloaded recipe revision f52e03ae3d251dec704634230cd806a2
libiconv/1.17: Not found in local cache, looking in remotes...
libiconv/1.17: Checking remote: conancenter
libiconv/1.17: Downloaded recipe revision 73fefc1b696e069df90fd1d18aa63edd
pkgconf/2.1.0: Not found in local cache, looking in remotes...
pkgconf/2.1.0: Checking remote: conancenter
pkgconf/2.1.0: Downloaded recipe revision 27f44583701117b571307cf5b5fe5605
meson/1.2.2: Not found in local cache, looking in remotes...
meson/1.2.2: Checking remote: conancenter
meson/1.2.2: Downloaded recipe revision 21b73818ba96d9eea465b310b5bbc993
ninja/1.12.1: Not found in local cache, looking in remotes...
ninja/1.12.1: Checking remote: conancenter
ninja/1.12.1: Downloaded recipe revision fd583651bf0c6a901943495d49878803
expat/2.6.3: Not found in local cache, looking in remotes...
expat/2.6.3: Checking remote: conancenter
expat/2.6.3: Downloaded recipe revision 39b80d3109fbe578fddfe4951f0b1d57
meson/1.4.0: Not found in local cache, looking in remotes...
meson/1.4.0: Checking remote: conancenter
meson/1.4.0: Downloaded recipe revision 2262941cc8fbb0099dd0c196ca2a6c01
spirv-cross/1.3.224.0: Not found in local cache, looking in remotes...
spirv-cross/1.3.224.0: Checking remote: conancenter
spirv-cross/1.3.224.0: Downloaded recipe revision a6abc63541499089423a8472cfbe2388
spirv-tools/1.3.224.0: Not found in local cache, looking in remotes...
spirv-tools/1.3.224.0: Checking remote: conancenter
spirv-tools/1.3.224.0: Downloaded recipe revision 7f77f3d8f50f62fee8353f7ab716711d
spirv-headers/1.3.224.0: Not found in local cache, looking in remotes...
spirv-headers/1.3.224.0: Checking remote: conancenter
spirv-headers/1.3.224.0: Downloaded recipe revision 1d19c94434cb2355a2c67823fe18c74b
glslang/1.3.224.0: Not found in local cache, looking in remotes...
glslang/1.3.224.0: Checking remote: conancenter
glslang/1.3.224.0: Downloaded recipe revision 2b09fe001e9ce4ec230504386f0862d7
vulkan-headers/1.3.224.0: Not found in local cache, looking in remotes...
vulkan-headers/1.3.224.0: Checking remote: conancenter
vulkan-headers/1.3.224.0: Downloaded recipe revision 84576deff1b71bce4b32d788e9f3c3b8
vulkan-validationlayers/1.3.224.1: Not found in local cache, looking in remotes...
vulkan-validationlayers/1.3.224.1: Checking remote: conancenter
vulkan-validationlayers/1.3.224.1: Downloaded recipe revision 9cd669ed657179df6ab38a8ba7aa30b0
robin-hood-hashing/3.11.5: Not found in local cache, looking in remotes...
robin-hood-hashing/3.11.5: Checking remote: conancenter
robin-hood-hashing/3.11.5: Downloaded recipe revision 6287c40b3396bea819b4751ef6bf8737
xorg/system: Not found in local cache, looking in remotes...
xorg/system: Checking remote: conancenter
xorg/system: Downloaded recipe revision 98f82cb669e4ebc6b4d9d8a4f3f1faf4
volk/1.3.224.0: Not found in local cache, looking in remotes...
volk/1.3.224.0: Checking remote: conancenter
volk/1.3.224.0: Downloaded recipe revision e570fd26523c2205edf10f2a35abbb31
xxhash/0.8.1: Not found in local cache, looking in remotes...
xxhash/0.8.1: Checking remote: conancenter
xxhash/0.8.1: Downloaded recipe revision 7bf1cd1fe3d31f1fbcc758d93c907e8d
xkbcommon/1.4.1: Not found in local cache, looking in remotes...
xkbcommon/1.4.1: Checking remote: conancenter
xkbcommon/1.4.1: Downloaded recipe revision 2bfdfd2d0177ae112d7e4a090b0ce8d0
xkeyboard-config/system: Not found in local cache, looking in remotes...
xkeyboard-config/system: Checking remote: conancenter
xkeyboard-config/system: Downloaded recipe revision 57dd5c08e72ab06bc2ee0e756c0a2c41
meson/1.3.2: Not found in local cache, looking in remotes...
meson/1.3.2: Checking remote: conancenter
meson/1.3.2: Downloaded recipe revision 26ce8a76a36cc275cdfee1d757bc6561
bison/3.8.2: Not found in local cache, looking in remotes...
bison/3.8.2: Checking remote: conancenter
bison/3.8.2: Downloaded recipe revision ed1ba0c42d2ab7ab64fc3a62e9ecc673
m4/1.4.19: Not found in local cache, looking in remotes...
m4/1.4.19: Checking remote: conancenter
m4/1.4.19: Downloaded recipe revision b38ced39a01e31fef5435bc634461fd2
flex/2.6.4: Not found in local cache, looking in remotes...
flex/2.6.4: Checking remote: conancenter
flex/2.6.4: Downloaded recipe revision e35bc44b3fcbcd661e0af0dc5b5b1ad4
wayland-protocols/1.33: Not found in local cache, looking in remotes...
wayland-protocols/1.33: Checking remote: conancenter
wayland-protocols/1.33: Downloaded recipe revision ff1b6deb00cb3ddd949261217588a4de
Graph root
    conanfile.txt: /home/jorge/code/prodigy-ge/prodigy/conanfile.txt
Requirements
    diligent-core/api.252009#88cf924aeaa270e277383d0e88661513 - Downloaded (conancenter)
    eabase/2.09.12#abdc26b253aece76cc2bfe0d7e21e04a - Downloaded (conancenter)
    eastl/3.21.12#67185fecd6fc1439394cc7e6cdf4b6aa - Downloaded (conancenter)
    expat/2.6.3#39b80d3109fbe578fddfe4951f0b1d57 - Downloaded (conancenter)
    glslang/1.3.224.0#2b09fe001e9ce4ec230504386f0862d7 - Downloaded (conancenter)
    joltphysics/3.0.1#3f0ab4e3593371b937e239bdc22702c3 - Downloaded (conancenter)
    libffi/3.4.4#72cccac6139293b6e97ec9cd676547ff - Downloaded (conancenter)
    libiconv/1.17#73fefc1b696e069df90fd1d18aa63edd - Downloaded (conancenter)
    libxml2/2.13.4#72b3bfba0c37dfe22f20c587cc468f4c - Downloaded (conancenter)
    opengl/system#4df6fecde4084386beded3ed0e56e4ea - Downloaded (conancenter)
    robin-hood-hashing/3.11.5#6287c40b3396bea819b4751ef6bf8737 - Downloaded (conancenter)
    spirv-cross/1.3.224.0#a6abc63541499089423a8472cfbe2388 - Downloaded (conancenter)
    spirv-headers/1.3.224.0#1d19c94434cb2355a2c67823fe18c74b - Downloaded (conancenter)
    spirv-tools/1.3.224.0#7f77f3d8f50f62fee8353f7ab716711d - Downloaded (conancenter)
    volk/1.3.224.0#e570fd26523c2205edf10f2a35abbb31 - Downloaded (conancenter)
    vulkan-headers/1.3.224.0#84576deff1b71bce4b32d788e9f3c3b8 - Downloaded (conancenter)
    vulkan-validationlayers/1.3.224.1#9cd669ed657179df6ab38a8ba7aa30b0 - Downloaded (conancenter)
    wayland/1.22.0#284b56bdbe57868770f46100784e3b4d - Downloaded (conancenter)
    xkbcommon/1.4.1#2bfdfd2d0177ae112d7e4a090b0ce8d0 - Downloaded (conancenter)
    xkeyboard-config/system#57dd5c08e72ab06bc2ee0e756c0a2c41 - Downloaded (conancenter)
    xorg/system#98f82cb669e4ebc6b4d9d8a4f3f1faf4 - Downloaded (conancenter)
    xxhash/0.8.1#7bf1cd1fe3d31f1fbcc758d93c907e8d - Downloaded (conancenter)
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Downloaded (conancenter)
Build requirements
    bison/3.8.2#ed1ba0c42d2ab7ab64fc3a62e9ecc673 - Downloaded (conancenter)
    cmake/3.30.5#540068cc37f1d21b42b729c82d6bcb29 - Downloaded (conancenter)
    expat/2.6.3#39b80d3109fbe578fddfe4951f0b1d57 - Downloaded (conancenter)
    flex/2.6.4#e35bc44b3fcbcd661e0af0dc5b5b1ad4 - Downloaded (conancenter)
    libffi/3.4.4#72cccac6139293b6e97ec9cd676547ff - Downloaded (conancenter)
    libiconv/1.17#73fefc1b696e069df90fd1d18aa63edd - Downloaded (conancenter)
    libxml2/2.13.4#72b3bfba0c37dfe22f20c587cc468f4c - Downloaded (conancenter)
    m4/1.4.19#b38ced39a01e31fef5435bc634461fd2 - Downloaded (conancenter)
    meson/1.2.2#21b73818ba96d9eea465b310b5bbc993 - Downloaded (conancenter)
    meson/1.3.2#26ce8a76a36cc275cdfee1d757bc6561 - Downloaded (conancenter)
    meson/1.4.0#2262941cc8fbb0099dd0c196ca2a6c01 - Downloaded (conancenter)
    ninja/1.12.1#fd583651bf0c6a901943495d49878803 - Downloaded (conancenter)
    pkgconf/2.1.0#27f44583701117b571307cf5b5fe5605 - Downloaded (conancenter)
    wayland/1.22.0#284b56bdbe57868770f46100784e3b4d - Downloaded (conancenter)
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Downloaded (conancenter)
Resolved version ranges
    cmake/[>=3.16 <4]: cmake/3.30.5
    expat/[>=2.6.2 <3]: expat/2.6.3
    libxml2/[>=2.12.5 <3]: libxml2/2.13.4
    ninja/[>=1.10.2 <2]: ninja/1.12.1
    zlib/[>=1.2.11 <2]: zlib/1.3.1
*********************************************************
Recipe 'wayland-protocols/1.33' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'wayland-protocols/1.33' not resolved: wayland-protocols/1.33: Cannot load recipe.
Error loading conanfile at '/home/jorge/.conan2/p/waylacf485377ad282/e/conanfile.py': Current Conan version (2.0.17) does not satisfy the defined one (>=1.64.0 <2 || >=2.2.0)..
</details>

**Comment by SpaceIm** [comment]
"Package and Environment Details" are actually very relevant in your issue.

`wayland-protocols` is not broken or not conan v2 ready. Error is quite explicit: this recipe requires conan >= 2.2.0 while you are using conan 2.0.17

**Comment by shackra** [comment]
Yeah, sorry. I updated Conan and the error was no more.

El miércoles 30 de octubre del 2024, SpaceIm escribió:

> "Package and Environment Details" are actually very relevant in 
> your issue.
>
> wayland-protocols is not broken or not conan v2 ready. Error is 
> quite explicit: this recipe requires conan >=
> 2.2.0 while you are using conan 2.0.17
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 
Jorge Araya

Contacto:
 Telegram: t.me/shackra · Signal: Shackra.28

**Comment by jcar87** [comment]
Glad to hear it's resolved! Closing this - but feel free to reopen or open a new one if any issues arise.
