### ISSUE TITLE
[service] Released package is not found/listed by conan CLI

### ISSUE THREAD

**Issue by josephbirkner** [conan-io/conan-center-index#25845]
### What is your problem/feature request?

When I try to install `simfil/0.3.3` (released yesterday via [this PR](https://github.com/conan-io/conan-center-index/pull/25829)) on any OS, I get the error that it was not found on the `conancenter` remote. However, it is shown as available here: https://conan.io/center/recipes/simfil

Output from `conan list --remote conancenter simfil`:

```
conancenter
  simfil
    simfil/0.1.1
    simfil/0.1.2
    simfil/0.1.3
    simfil/0.2.1
    simfil/0.3.0
    simfil/0.3.1
    simfil/0.3.2
```

Compare with the screenshot of https://conan.io/center/recipes/simfil/ :

![image](https://github.com/user-attachments/assets/e55176a2-4495-4a53-bc4b-62cba14b0f7e)

So, something seems to have gone wrong internally with the release.

**Comment by jcar87** [comment]
HI @josephbirkner  - apologies for this. Starting this week we have frozen the `https://center.conan.io` remote - 

in the past couple of days we have been ensuring things work well internally before a wider announcement. You can update your remote settings 

```
conan remote update --url https://center2.conan.io conancenter
```

Any recipe and package updates from 4-Nov-2024 will be published in the new remote `https://center2.conan.io` - the legacy remote is still up and running, but will no longer be updated. All recipes/packages known to be compatible with Conan 2 are available in the new endpoint

**Comment by josephbirkner** [comment]
Thanks for the quick response - duly noted!
