### ISSUE TITLE
[package] libssh2/1.11.1: Build fail on Windows with "#error:  "no cryptography backend selected"" when using mbedtls

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [conan-io/conan-center-index#25855]
### Description

i tried both libssh2/1.11.1 and libssh2/1.11.0 and got the same results.
Conan version 2.9.1

building libssh2 with mbedtls gave me the following error: 
```
C:\Users\mbarbier\.conan2\p\b\libss0b5b55d50878c\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss0b5b55d50878c\b\src\src\userauth_kbd_packet.c) [C:\Users\mbarbier\.conan2\p\b\libss0b5b55d50878c\b\build\src\libssh2_static.vcxproj]
```

### Package and Environment Details

* Package Name/Version: **libssh2/1.11.1**
* Operating System+version: **Windows 11 23h2 **
Visual Studio 2022
* Conan version: **conan 1.9.1*
* Python version: **Python 3.8.10**
MSBuild version 17.11.9+a69bbaaf5

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=194
os=Windows

Build profile:
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=194
os=Windows

### Steps to reproduce

```py

from conan import ConanFile

class dummyConanFile(ConanFile):
	settings = "os", "compiler", "build_type", "arch"

	def requirements(self):
		self.requires("libssh2/1.11.1")

	def configure(self):
		self.options["libssh2"].crypto_backend = "mbedtls"
```

`conan install . -of build`

### Logs

<details><summary>Click to expand log</summary>

-------- Installing package libssh2/1.11.1 (31 of 48) --------
libssh2/1.11.1: Building from source
libssh2/1.11.1: Package libssh2/1.11.1:22ab11539248eb726aba891df523e56626ab512c
libssh2/1.11.1: Copying sources to build folder
libssh2/1.11.1: Building your package in C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b
libssh2/1.11.1: Calling generate()
libssh2/1.11.1: Generators folder: C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\generators
libssh2/1.11.1: CMakeToolchain generated: conan_toolchain.cmake
libssh2/1.11.1: CMakeToolchain generated: C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\generators\CMakePresets.json
libssh2/1.11.1: CMakeToolchain generated: C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\CMakeUserPresets.json
libssh2/1.11.1: Generating aggregated env files
libssh2/1.11.1: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
libssh2/1.11.1: Calling build()
libssh2/1.11.1: Running CMake.configure()
libssh2/1.11.1: RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/mbarbier/.conan2/p/b/libss84b599e1202d2/p" -DENABLE_ZLIB_COMPRESSION="ON" -DENABLE_CRYPT_NONE="OFF" -DENABLE_MAC_NONE="OFF" -DENABLE_DEBUG_LOGGING="OFF" -DCRYPTO_BACKEND="mbedTLS" -DBUILD_EXAMPLES="OFF" -DBUILD_TESTING="OFF" -DBUILD_STATIC_LIBS="ON" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_TRY_COMPILE_CONFIGURATION="Debug" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:/Users/mbarbier/.conan2/p/b/libss84b599e1202d2/b/src"
-- Using CMake version 3.30.5
-- Using Conan toolchain: C:/Users/mbarbier/.conan2/p/b/libss84b599e1202d2/b/build/generators/conan_toolchain.cmake
-- Conan toolchain: CMAKE_GENERATOR_TOOLSET=v143
-- Conan toolchain: Setting CMAKE_MSVC_RUNTIME_LIBRARY=$<$<CONFIG:Debug>:MultiThreadedDebugDLL>
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.36.32546.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: Component target declared 'MbedTLS::mbedcrypto'
-- Conan: Component target declared 'MbedTLS::mbedx509'
-- Conan: Component target declared 'MbedTLS::mbedtls'
-- Conan: Target declared 'ZLIB::ZLIB'
CMake Warning at src/CMakeLists.txt:254 (message):
  Bad lib in library list: ZLIB::ZLIB

-- The following features have been enabled:

 * Static library, creating libssh2 static library
 * Crypto backend, mbedTLS
 * Compression, using zlib for compression

-- The following REQUIRED packages have been found:

 * MbedTLS
 * ZLIB

-- The following features have been disabled:

 * Shared library, creating libssh2 shared library (.so/.dll)
 * Logging, Logging of execution with debug trace
 * Without deprecated APIs

-- Configuring done (2.0s)
-- Generating done (0.1s)
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_CRYPT_NONE
    ENABLE_MAC_NONE

-- Build files have been written to: C:/Users/mbarbier/.conan2/p/b/libss84b599e1202d2/b/build

libssh2/1.11.1: Running CMake.build()
libssh2/1.11.1: RUN: cmake --build "C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build" --config Debug
MSBuild version 17.11.9+a69bbaaf5 for .NET Framework

  1>Checking Build System
  Building Custom Rule C:/Users/mbarbier/.conan2/p/b/libss84b599e1202d2/b/src/src/CMakeLists.txt
  agent.c
  bcrypt_pbkdf.c
  channel.c
  comp.c
  chacha.c
  cipher-chachapoly.c
  crypt.c
  crypto.c
  global.c
  hostkey.c
  keepalive.c
  kex.c
  knownhost.c
  mac.c
  misc.c
  packet.c
  pem.c
  poly1305.c
  publickey.c
  scp.c
  session.c
  sftp.c
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con
an2\p\b\libss84b599e1202d2\b\src\src\comp.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\channel.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
  transport.c
  userauth.c
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\agent.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con
an2\p\b\libss84b599e1202d2\b\src\src\bcrypt_pbkdf.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con
an2\p\b\libss84b599e1202d2\b\src\src\cipher-chachapoly.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
  userauth_kbd_packet.c
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\knownhost.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
  version.c
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\hostkey.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con
an2\p\b\libss84b599e1202d2\b\src\src\crypt.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\kex.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\crypto.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\global.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\chacha.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\misc.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\mac.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\keepalive.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\poly1305.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\sftp.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\pem.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\publickey.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\scp.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\session.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\packet.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con
an2\p\b\libss84b599e1202d2\b\src\src\userauth.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con 
an2\p\b\libss84b599e1202d2\b\src\src\transport.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con
an2\p\b\libss84b599e1202d2\b\src\src\userauth_kbd_packet.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]
C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\src\src\crypto.h(55,1): fatal  error C1189: #error:  "no cryptography backend selected" (compiling source file C:\Users\mbarbier\.con
an2\p\b\libss84b599e1202d2\b\src\src\version.c) [C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build\src\libssh2_static.vcxproj]

libssh2/1.11.1: ERROR:
Package '22ab11539248eb726aba891df523e56626ab512c' build failed
libssh2/1.11.1: WARN: Build folder C:\Users\mbarbier\.conan2\p\b\libss84b599e1202d2\b\build
ERROR: libssh2/1.11.1: Error in build() method, line 110
        cmake.build()
        ConanException: Error 1 while executing

</details>

**Comment by jcar87** [comment]
Hi @Marc-Pierre-Barbier - thanks for reporting this. I've given this a go in this PR: https://github.com/conan-io/conan-center-index/pull/25860
