### ISSUE TITLE
[package] trompeloeil/49: Not found in conancenter

### ISSUE THREAD

**Issue by offa** [conan-io/conan-center-index#25861]
### Description

trompeloeil/49 was recently added to conancenter (#25541), but it can't be installed:

```
conan install --requires=trompeloeil/49
[…]
ERROR: Package 'trompeloeil/49' not resolved: Unable to find 'trompeloeil/49' in remotes.
```

### Package and Environment Details

* Package Name/Version: **trompeloeil/49**
* Operating System+version: **Arch Linux** /  **Ubuntu 20.04**
* Compiler+version: **GCC 14**
* Docker image: -
* Conan version: **conan 2.9.1**
* Python version: **Python 3.13 / 3.12**

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

### Steps to reproduce

```
conan install --requires=trompeloeil/49
```

_(or use a conanfile)_

### Logs

<details><summary>Click to expand log</summary>

```
[…]
======== Computing dependency graph ========
trompeloeil/49: Not found in local cache, looking in remotes...
trompeloeil/49: Checking remote: conancenter
Graph root
    cli
ERROR: Package 'trompeloeil/49' not resolved: Unable to find 'trompeloeil/49' in remotes.

```

</details>

**Comment by jcar87** [comment]
Apologies for this - this is part of the migration to our new CI pipeline and deprecation path for COnan 1.x

From my earlier comment - 
https://github.com/conan-io/conan-center-index/issues/25845#issuecomment-2459582093

```
conan remote update --url https://center2.conan.io conancenter
```

The legacy repository is no longer updated (but still up and running). This will be all announced tomorrow more formally.

**Comment by offa** [comment]
Thanks!
