### ISSUE TITLE
[package] libx265/3.2.1: sha256 signature failed

### ISSUE THREAD

**Issue by omaralvarez** [conan-io/conan-center-index#2587]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: *libx265/3.2.1**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9.3.0**
  * Conan version: **conan 1.28.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Downloading x265_3.2.1.tar.gz completed [1392.83k]                                       
ERROR: libx265/3.2.1: Error in source() method, line 50
	tools.get(**self.conan_data["sources"][self.version])
	ConanException: sha256 signature failed for 'x265_3.2.1.tar.gz' file. 
 Provided signature: 7cf8ed2927fcb2914cdca51c974594770da705cb43288beea62b69c53725b5d7  
 Computed signature: fb9badcf92364fd3567f8b5aa0e5e952aeea7a39a2b864387cec31e3b58cbbcc

```

</details>

**Comment by Croydon** [comment]
See

https://bitbucket.org/multicoreware/x265/issues/565/why-has-the-x265-checksum-changed

and we have some open PR which I can't find right now

**Comment by omaralvarez** [comment]
There is a new version available. Could I make a pull request with the new one?

**Comment by madebr** [comment]
eigen is in the same position:
https://github.com/conan-io/conan-center-index/issues/2612

So yeah, changing the source+sha256 seems(+homepage?) looks like the logical thing to do.

**Comment by Croydon** [comment]
Now I'm confused. I were thinking that Bitbucket removed mercury repositories a while ago. Since just yesterday I could browse the repo I didn't think this is a related issue

So, what is the new home of x265?

**Comment by omaralvarez** [comment]
Not really sure, VLC has a release repo, but I don't think it is the same:

https://github.com/videolan/x265

http://ftp.videolan.org/pub/videolan/x265/

**Comment by Croydon** [comment]
The commit which is tagged as 3.2.1 on GitHub does not match the one on Bitbucket

https://bitbucket.org/multicoreware/x265_git/commits/96cd17207ab6645dc9aaae38262c0620d5269163
https://github.com/videolan/x265/releases/tag/3.2.1

**Comment by madebr** [comment]
Here is their their development mercurial: http://hg.videolan.org/x265
But I don't see a way to download packages.

**Comment by Croydon** [comment]
I'm assuming the difference in the git commits origins from different ways of converting their former mercurial repo to git repos

Since the VLC GitHub org seems legit, I guess we can use the GitHub archive downloads. WDYT?

**Comment by madebr** [comment]
Sounds good.
I also had to change the sha256 of eigen because bitbucket and gitlab created different tarballs from a commit/tag.

**Comment by omaralvarez** [comment]
Should I create a PR then?

**Comment by Croydon** [comment]
> Should I create a PR then?

Yes, please

Use e.g. `https://github.com/videolan/x265/archive/3.2.1.tar.gz`

**Comment by madebr** [comment]
I would use http://ftp.videolan.org/pub/videolan/x265/x265_3.2.1.tar.gz

**Comment by omaralvarez** [comment]
Got it, will do it first thing tomorrow morning.

**Comment by Croydon** [comment]
Would be fine with me too. But I have zero experience how good availability and steadiness is for their FTP. We had such problems with downloads in the past, hence my GitHub-download-by-default approach 😁

**Comment by madebr** [comment]
I see, then github sounds good.
Because github creates these files from tags, it also has the newer releases.

**Comment by omaralvarez** [comment]
PR ready.
