### ISSUE TITLE
[service] Some PRs do not trigger the CI service

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#259]
When some PRs are opened, that event does not trigger the CI job. Having a look at the event log it shows:

```
Checking pull request #255
      '.jenkins/Jenkinsfile' not found
Does not meet criteria
```

Searching this error leads to the following issues in Jenkins:

- https://issues.jenkins-ci.org/browse/JENKINS-54126
- https://issues.jenkins-ci.org/browse/JENKINS-57206 (this one could have happened when opening #255)

Re-scanning the repo as suggested in those threads made the job start

**Comment by jgsogo** [comment]
Probably nothing we can do here, right? Unless we add a man-in-the-middle that monitors jobs that haven't started.

...or we activate the branch-indexing, which, IMO, we should, but that's a different story.

Closing, we can move it to the infra repo if needed.
