### ISSUE TITLE
[service] PRs hanging on CI status update

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-center-index#25905]
### What is your problem/feature request?

Hi - I've got a few PRs that appear to be hanging on CI status updates - 

* https://github.com/conan-io/conan-center-index/pull/25771
* https://github.com/conan-io/conan-center-index/pull/25717
* https://github.com/conan-io/conan-center-index/pull/24317

**Comment by planetmarshall** [comment]
@jcar87 Liking the new CI by the way - much better for seeing immediate feedback especially for larger and more complex recipes.

**Comment by jcar87** [comment]
> @jcar87 Liking the new CI by the way - much better for seeing immediate feedback especially for larger and more complex recipes.

Happy to hear it! :)
