### ISSUE TITLE
[package] opencv/4.10.0: use `libjpeg-turbo` instead of `libjpeg` per default

### ISSUE THREAD

**Issue by danteu** [conan-io/conan-center-index#25946]
### Description

Since OpenCV version 3.4.2, `libjpeg-turbo` is used as the default library for JPEG support instead of `libjpeg`. The support for `libjpeg` has been deprecated (see https://github.com/opencv/opencv/tree/4.x/3rdparty#readme).

In PR #24814 the default values in the conanfile were set such that they match the defaults from OpenCV. However, the `"with_jpeg"` option was left unchanged.

The default option should be set to `libjpeg-turbo`.

### Package and Environment Details

* Package Name/Version: **opencv/4.10.0**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

### Steps to reproduce

conan install --requires=opencv/4.10.0

### Logs

<details><summary>Click to expand log</summary>

```
[...]
Requirements
[...]
    libiconv/1.17#73fefc1b696e069df90fd1d18aa63edd - Downloaded (conancenter)
    libjpeg/9e#68269859e4325ddc3f995d1fd3fc9187 - Cache
    libmp3lame/3.100#44b12d19316eb2b223d98d3e75dae438 - Downloaded (conancenter)
[...]
```

</details>

**Comment by jcar87** [comment]
Please see https://github.com/conan-io/conan-center-index/pull/25947#issuecomment-2476960829 for additional contesxt, but this is currently intentional.
