### ISSUE TITLE
glew/2.1.0: compile error in RelWithDebInfo mode

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#2595]
### Package and Environment Details
  * Package Name/Version: glew/2.1.0
  * Operating System Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version 1.25.2
  * Python version: Python 3.8.3

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=RelWithDebInfo
compiler=Visual Studio
compiler.cppstd=14
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
*:shared=False
*:static=True
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
conan install glew/2.1.0@ -u -r conan-center

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
opengl/system: WARN: Current package is newer than remote upstream one
glu/system: WARN: Current package is newer than remote upstream one
glew/2.1.0: WARN: Can't update, no package in remote
Installing package: glew/2.1.0
Requirements
    glew/2.1.0 from 'conan-center' - Cache
    glu/system from 'conan-center' - Cache
    opengl/system from 'conan-center' - Cache
Packages
    glew/2.1.0:3e836731753ab9a9211763df32b0af3056a15284 - Cache
    glu/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    opengl/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
opengl/system: Already installed!
glu/system: Already installed!
glew/2.1.0: Already installed!
ERROR: glew/2.1.0: Error in package_info() method, line 80
        self.cpp_info.filenames["cmake_find_package"] = "GLEW"
        TypeError: '_CppInfo' object does not support item assignment
```

</details>

**Comment by Croydon** [comment]
Your Conan version is too old. Please update

**Comment by AndreyMlashkin** [comment]
updating to conan 1.28.1 solved the issue, thank you!
