### ISSUE TITLE
[package] openssl/3.2.1: Linker/Compiler Error when building for Android

### ISSUE THREAD

**Issue by sereksim** [conan-io/conan-center-index#25972]
## Description

I want to build [OpenSSL](https://github.com/openssl/openssl) for Android, as a dependency of my C++-application which is built via Conan. The conan build (`conan install /.../my_project -pr:h android34-armv8-clang-17-c++_shared -pr:b default --build=missing`) otherwise works as expected.

In the repository of OpenSSL there are multiple documents explaining the build process, [NOTES_ANDROID.md](https://github.com/openssl/openssl/blob/master/NOTES-ANDROID.md), [INSTALL.md](https://github.com/openssl/openssl/blob/master/INSTALL.md) and the configuration file [15-android.conf](https://github.com/openssl/openssl/blob/master/Configurations/15-android.conf). I tried to follow the instructions there, so the environment variable ANDROID_NDK_ROOT is set and I checked that -D__ANDROID_API_\_ is set to the right target API.

Conan correctly identifies the dependencies (e.g. openssl/3.2.1 ) and starts a cross-build ("`Cross-build from 'Linux:x86_64' to 'Android:armv8'`").

The behaviour of the build for openssl then depends on the environment variables `CC` and `CXX`. If they are set to `/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang` and `/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++` the following happens:

```shell
openssl/3.2.1: Calling generate()
openssl/3.2.1: using target: conan-Debug-Android-armv8-clang-17 -> linux-generic64
openssl/3.2.1: my %targets = (
    "conan-Debug-Android-armv8-clang-17" => {
        inherit_from => [ "linux-generic64" ],
        cflags => add("-g"),
        cxxflags => add("-g"),
        
        lflags => add(""),
        
        
        
        perlasm_scheme => "linux64",
    },
);

openssl/3.2.1: Aggregating env generators
openssl/3.2.1: Calling build()
openssl/3.2.1: apply_conandata_patches(): No patches defined in conandata
openssl/3.2.1: Running: perl ./Configure "conan-Debug-Android-armv8-clang-17" shared --prefix=/ --libdir=lib --openssldir="/home/user/.conan/data/openssl/3.2.1/_/_/package/307503e24fa1e7276c553bf27b1fc9befa5ee61a/res" no-unit-test threads PERL=perl no-tests --debug  -D__ANDROID_API__=34 -fPIC enable-fips no-md2 zlib --with-zlib-include="/home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/include" --with-zlib-lib="/home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/lib"
Configuring OpenSSL version 3.2.1 for target conan-Debug-Android-armv8-clang-17
Using os-specific seed configuration
...
OpenSSL has been successfully configured       
...
```

So the configuration appears to work, but the build process later fails:

```shell
/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -fPIC -pthread -g -g -fPIC -Wl,-z,defs -Wl,-znodelete -shared -Wl,-Bsymbolic -L/home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/lib  \
	-o providers/fips.so -Wl,--version-script=providers/fips.ld \
	providers/fips/fips-dso-fips_entry.o \
	providers/libfips.a -lz -ldl -pthread 
ld.lld: error: /home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/lib/libz.a(adler32.c.o) is incompatible with elf64-x86-64
ld.lld: error: /home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/lib/libz.a(compress.c.o) is incompatible with elf64-x86-64
ld.lld: error: /home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/lib/libz.a(crc32.c.o) is incompatible with elf64-x86-64
ld.lld: error: /home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/lib/libz.a(deflate.c.o) is incompatible with elf64-x86-64
ld.lld: error: /home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/lib/libz.a(gzclose.c.o) is incompatible with elf64-x86-64
...
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:25460: providers/fips.so] Error 1
make[1]: *** Waiting for unfinished jobs....
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:26026: util/quicserver] Error 1
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:5727: libcrypto.so.3] Error 1
make[1]: Leaving directory '/home/user/.conan/data/openssl/3.2.1/_/_/build/307503e24fa1e7276c553bf27b1fc9befa5ee61a/src'
make: *** [Makefile:3232: build_sw] Error 2
```

I think the problem here is a mismatch between the compilation targets. The dependency zlib is compiled for armv8, which is correct, because that is the architecture of my target android phone. For some reason the build-process of OpenSSL expects it to be x86 and crashes because of that mismatch.
The target for openssl (`conan-Debug-Android-armv8-clang-17`) is automatically created by the [conanfile of OpenSSL](https://github.com/conan-io/conan-center-index/blob/master/recipes/openssl/3.x.x/conanfile.py), which explicitly mentions that "Android targets are very broken".

On the other hand, if I **explicitly set `CC` and `CXX` to their versions targeting ARM** (`/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/arch64-linux-android34-clang` and `/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang++` ). The configuration is slightly different, but still fails:

```shell
openssl/3.2.1: Calling generate()
openssl/3.2.1: using target: conan-Debug-Android-armv8-clang-17 -> android-arm64
openssl/3.2.1: my %targets = (
    "conan-Debug-Android-armv8-clang-17" => {
        inherit_from => [ "android-arm64" ],
        cflags => add("-g"),
        cxxflags => add("-g"),
        
        lflags => add(""),
        
        
        
        perlasm_scheme => "linux64",
    },
);

openssl/3.2.1: Aggregating env generators
DEBUG :build.py       [11]: Call conanfile.build() with files in build folder: ['conanbuildinfo.txt', 'conan'] [2024-11-18 09:26:28,739]
openssl/3.2.1: Calling build()
openssl/3.2.1: apply_conandata_patches(): No patches defined in conandata
openssl/3.2.1: Running: perl ./Configure "conan-Debug-Android-armv8-clang-17" shared --prefix=/ --libdir=lib --openssldir="/home/user/.conan/data/openssl/3.2.1/_/_/package/307503e24fa1e7276c553bf27b1fc9befa5ee61a/res" no-unit-test threads PERL=perl no-tests --debug  -D__ANDROID_API__=34 -fPIC enable-fips no-md2 zlib --with-zlib-include="/home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/include" --with-zlib-lib="/home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/lib"
Configuring OpenSSL version 3.2.1 for target conan-Debug-Android-armv8-clang-17
Using os-specific seed configuration
...
OpenSSL has been successfully configured 
...
34-clang  -I. -Iinclude -Iapps/include  -fPIC -pthread -g -g -fPIC -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/home/user/.conan/data/openssl/3.2.1/_/_/package/307503e24fa1e7276c553bf27b1fc9befa5ee61a/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DZLIB -I/home/user/.conan/data/zlib/1.3.1/_/_/package/023d2329c8205a068e7539cdd05ad94dd88a0fab/include -D__ANDROID_API__=34  -c -o apps/lib/libapps-lib-opt.o apps/lib/opt.c
/bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: /bin/sh: 1: 34-clang: not found34-clang: not found34-clang: not found34-clang: not found34-clang: not found34-clang: not found34-clang: not found34-clang: not found34-clang: not found34-clang: not found34-clang: not found
34-clang: not found
34-clang: not found
/bin/sh: 1: 34-clang: not found
34-clang: not found
make[1]: *** [Makefile:3091: apps/lib/libapps-lib-app_libctx.o] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:3095: apps/lib/libapps-lib-app_provider.o] Error 127
make[1]: *** [Makefile:3097: apps/lib/libapps-lib-app_rand.o] Error 127
...
make[1]: *** [Makefile:3093: apps/lib/libapps-lib-app_params.o] Error 127
/bin/sh: 1: 34-clang: not found
make[1]: *** [Makefile:3111: apps/lib/libapps-lib-engine_loader.o] Error 127
make[1]: Leaving directory '/home/user/.conan/data/openssl/3.2.1/_/_/build/307503e24fa1e7276c553bf27b1fc9befa5ee61a/src'
make: *** [Makefile:1516: build_sw] Error 2
```

~~What is `34-clang`?~~
### Edit (19.11.): 
The error here seems to be that the environment variable `CC` is interpreted incorrectly. `CC` ends with `arch64-linux-android34-clang`, and the script tries to execute "34-clang".

## Package and Environment Details

* Package Name/Version: **openssl/3.2.1** and its dependency zlib/1.3.1
* Operating System+version: **Linux Ubuntu 22.04.5 LTS**
* Compiler+version: **Android Clang 17.0.2** (gcc 11.4 is also installed on the system)
* Conan version: **conan 1.61.0**
* Python version: **Python 3.10.12**

### pr:b default:
```shell
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### pr:h android34-armv8-clang-17-c++_shared
```shell
[settings]
os=Android
arch=armv8
compiler=clang
compiler.version=17
compiler.libcxx=c++_shared
build_type=Debug
os.api_level=34
[options]
[build_requires]
[buildenv]
ANDROID_NDK_HOME=/home/user/Android/Sdk/ndk/26.3.11579264
ANDROID_NDK=$ANDROID_NDK_HOME
ANDROID_NDK_ROOT=/home/user/Android/Sdk/ndk/26.3.11579264
ANDROID_SDK_ROOT=$ANDROID_HOME
ANDROID_NDK_VERSION=26.3.11579264
CC=/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
CXX=/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
RANLIB=/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
AR=/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
[env]
ANDROID_NDK_HOME=/home/user/Android/Sdk/ndk/26.3.11579264
ANDROID_NDK_ROOT=/home/user/Android/Sdk/ndk/26.3.11579264
ANDROID_NDK=$ANDROID_NDK_HOME
ANDROID_SDK_ROOT=$ANDROID_HOME
ANDROID_NDK_VERSION=26.3.11579264
CC=/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
CXX=/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
RANLIB=/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
AR=/home/user/Android/Sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
[conf]                                                                                                                       
tools.android:ndk_path=/home/user/Android/Sdk/ndk/26.3.11579264/
```

## Steps to reproduce

my_project with requirements zlib/1.3.1 and openssl/3.2.1 

Android SDK and NDK are installed locally (see environment variables in conan profile)

`conan install /.../my_project -pr:h android34-armv8-clang-17-c++_shared -pr:b default --build=missing

## Logs

Logs: https://gist.github.com/sereksim/a65871a1fe45122426c866db24f57729
(As Github Gist, because they are too long for the issue)

**Comment by uilianries** [comment]
@sereksim Thank you for your detailed report, I should take a look closer into this issue by tomorrow, when I'll be connected to my Linux machine.

Bear in mind ConanCenterIndex no longer supports Conan 1.x, and your issue is destined to 1.61.0. More info: https://github.com/conan-io/conan-center-index/discussions/25461

The OpenSSL uses a autoconf flavored script for its building steps, and it's a bit more trick when talking about cross-building. As your steps are well documented, I guess I'll have not problems reproducing your scenario.

**Comment by uilianries** [comment]
@sereksim I just tried to reproduce your error, but is working for me.

I tried two different scenarios, first, I used the Conan package for Android NDK. That package configures the compiler and other important variables, include the ndk path:

[openssl-3.2.1-android-tool-req.log](https://github.com/user-attachments/files/17826792/openssl-3.2.1-android-tool-req.log)

Second, I tried to use a profile consuming a NDK installed in my system. See that my profile pretty simple, only ndk path and compilers, nothing more. It's working as well.

[openssl-3.2.1-android-system.log](https://github.com/user-attachments/files/17826789/openssl-3.2.1-android-system.log)

Please, tried to reproduce my profile, it should be working for you as well.

**Comment by uilianries** [comment]
@sereksim Thank you for your feedback! I'm glad that's working for you now!
