### ISSUE TITLE
[service] Document tools installed in slaves

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#260]
We have recently faced some issues about tools not installed in slaves that are needed in order to build some packages. While we discuss how packages could indicate that such system tools are needed, we would need to have a list of the tools installed in the slaves we have the information and can track what is available.

related to #https://github.com/conan-io/conan-center-index/pull/255#issuecomment-548292904, https://github.com/conan-io/conan-center-index/pull/238#issuecomment-548258039

**Comment by danimtb** [comment]
cc/ @maheshjfrog

**Comment by maheshjfrog** [comment]
Sure. We should have an official documented list of tools in our jenkins slaves (linux, mac and windows).

**Comment by danimtb** [comment]
Seems there are some missing tools:
- Windows: `devenv` https://github.com/conan-io/conan-center-index/pull/350
- Apple: `libtool` https://github.com/conan-io/conan-center-index/pull/267

**Comment by theodelrieu** [comment]
I think that `nmake` is missing as well: see #351 error log on windows

**Comment by danimtb** [comment]
@theodelrieu, both `devenv` and `nmake` require `vcvars` to be activated. Please use the `vcvars` tool befor runing any `nmake` command and `MSBuild()` build helper instead of `build_sln_command()` thanks!

**Comment by theodelrieu** [comment]
I didn't even spot this vcvars tool...

**Comment by danimtb** [comment]
I think this section in the docs already covers this issue https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md

It is even updated automatically!
