### ISSUE TITLE
[package] libssh2/1.11.0: Requirement on cmake 3.30.5

### ISSUE THREAD

**Issue by DevAGCO** [conan-io/conan-center-index#26062]
### Description

With the latest version 1.11.1 a new tool depedency has appeared (to cmake 3.30.5).

It looks like previous versions of libssh2 (tested with 1.11.0 and 1.10.0) have suddenly also inherited from that new requirement. Breaking existing builds that are not able to build cmake (e.g. armv7 platform). 

### Package and Environment Details

* Package Name/Version: libssh2/1.11.0
* Operating System+version: Raspbian armv7
* Compiler+version: GCC 8.3.0
* Python version: Python 3.7.3

### Conan profile

[settings]
arch=armv7
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

### Steps to reproduce

Simply trying to build the package

### Logs

<details><summary>Click to expand log</summary>

```
...
Build requirements
    cmake/3.30.5#540068cc37f1d21b42b729c82d6bcb29:7a99b07c654f17f335428a58b7f18cae9b625984 - Invalid
ERROR: There are invalid packages:
cmake/3.30.5: Invalid: CMake binaries are only provided for x86_64 and armv8 architectures
```

</details>

cf https://github.com/conan-io/conan-center-index/pull/25639

**Comment by jcar87** [comment]
Hi @DevAGCO  - thanks for reporting this.

As a workaround, if you have a recent-enough CMake version installed on your system, could you try adding the following to your profile?

```
[platform_tool_requires]
cmake/[>=3.15 <4]
```

this should cause Conan to skip the cmake dependency altogether and assume it is installed system wide

**Comment by AbrilRBS** [comment]
Hi @DevAGCO thanks a lot for your report. You're right that the dependency for CMake in this case was incorrectly added. I'll be rolling back this change alongside some improvements to the recipe, but for now @jcar87's suggestion might help solve the issues in the meantime :)

**Comment by DevAGCO** [comment]
@AbrilRBS Great, thanks! :)

@jcar87 I tried this and other similar attempts to overrule the requirement coming from the libssh2 recipe. But did not manage to make it work (yet)...

**Comment by DevAGCO** [comment]
Thanks for your care @jcar87.
`cmake version 3.24.4` (built from source)
`Conan version 2.6.0`
Raspberry Pi 4 Model B Rev 1.1
`uname -m` : `armv7l`
`dpkg --print-architecture` : `armhf`

Depending on when @AbrilRBS 's fix will be available in conan-center, I can simply wait for it... And as a side note, I will be afk next week.

In any case, thanks for your work guys!

**Comment by AbrilRBS** [comment]
Hi @DevAGCO:

As per https://docs.conan.io/2/reference/config_files/profiles.html#platform-tool-requires, the proper `[platform_tool_requires]` syntax would be

```
[platform_tool_requires]
cmake/3.x.y
```

where 3.x.y is the result of running `cmake --version` on your build platform, so no version ranges here. Could you try this, see if it fixes your issue with the new cmake requirement? Thanks!

**Comment by DevAGCO** [comment]
That worked! Thanks a lot!

**Comment by DevAGCO** [comment]
Should I keep this open? Or will you fix the wrong dependency from the PR?

**Comment by AbrilRBS** [comment]
@DevAGCO we can keep this open, the PR should be close to the finish line now :)

**Comment by jcar87** [comment]
The tool requirement on CMake is correct for 1.11.0 (as reported in this issue) - the PR only fixes it for older versions on the odd chance someone is using an older version on a platform where the cmake recipe won't run.

Closing this as solved - the solution in this case is to use the `platform_tool_requires` - although we will continue exploring avenues for building the CMake recipe from source where appropriate.
```
[platform_tool_requires]
cmake/3.x.y
```

@DevAGCO, as a side note: Raspberry Pi 4B supports 64-bit operating systems - newer versions of Raspberry Pi OS running on 64-bit mode is what I would recommend (unless one has a specific need for 32-bit mode)

**Comment by DevAGCO** [comment]
@jcar87  Just want to clarify: Actually what I wrote in the initial post is that the dependency for cmake/3.30.5 **is also** present for libss2/1.11.0 and libssh2/1.10.0. Tested right now and it's still the case, which does not reflect the claim that libssh2/1.10.0 has no dependency in conan center.

The workaround with platform_tool_requires that you mentioned is great and I believe will cover all these situations where cmake's recipe cannot be run. Thanks again.

As per your side note: Thank you, that's nice of you to suggest. I am aware of that and I would love to upgrade. The issue lies in the fact that we are using an old image that is already distributed, so for maintenance reasons we need to still be able to build our applications for that image.

**Comment by AbrilRBS** [comment]
> Tested right now and it's still the case

@DevAGCO few things that might be worth checking:

* Are you using the updated Conan 2 remote? Recall that for Conan 2, this changed and `conan remote update conancenter --url https://center2.conan.io` is necessary to get the latest changes
* If so, have you updated the recipe? Conan will prefer to use your recipe from the cache unless told otherwise with the `--update` flag (You can specify only libssh2 to be updated with `--update=libssh2`

Let me know if this helps!

**Comment by DevAGCO** [comment]
Alright. I was using an old setting file with the old conancenter url.
The dependency is now removed. Thank you!

**Comment by DevAGCO** [comment]
@AbrilRBS  Did you get my previous message?
