### ISSUE TITLE
eigen/3.3.7: can not compile

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#2612]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: eigen/3.3.7
  * Operating System+version: windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version 1.28.1
  * Python version: **Python 3.8.5**

### Conan profile
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=20
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
*:shared=False
*:static=True
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conan install eigen/3.3.7@  --build "*"

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
eigen/3.3.7: Forced build from source
Installing package: eigen/3.3.7
Requirements
    eigen/3.3.7 from 'artifactory' - Cache
Packages
    eigen/3.3.7:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build

Installing (downloading, building) binaries...
eigen/3.3.7: WARN: Build folder is dirty, removing it: C:\Users\ContainerAdministrator\.conan\data\eigen\3.3.7\_\_\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
eigen/3.3.7: WARN: Trying to remove corrupted source folder
eigen/3.3.7: WARN: This can take a while for big packages
eigen/3.3.7: Configuring sources in C:\Users\ContainerAdministrator\.conan\data\eigen\3.3.7\_\_\source
ERROR: eigen/3.3.7: Error in source() method, line 20
        tools.get(**self.conan_data["sources"][self.version])
        AuthenticationException: 403: Forbidden
```

</details>

**Comment by madebr** [comment]
`wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2` fails as well.

Going to https://bitbucket.org/eigen/eigen shows the problem:
*Bitbucket no longer supports Mercurial repositories.*

**Comment by uilianries** [comment]
Interesting, I thought it was related to a maintenance from yesterday, but now it all green: https://bitbucket.status.atlassian.com/
