### ISSUE TITLE
[package] Arrow/18.1.0: Can't be installed

### ISSUE THREAD

**Issue by jaimesalvador** [conan-io/conan-center-index#26214]
### Description

I use the command:

```
conan search arrow* -r=conan-center
```

shows the message:

````ERROR: Remote 'conan-center' can't be found or is disabled```

And when I try to install as dependency:

```
from conan import ConanFile
from conan.tools.cmake import cmake_layout


class ExampleRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def requirements(self):
        self.requires("arrow/18.1.0")

    def layout(self):
        cmake_layout(self)
```
I get the error: `ERROR: Package 'arrow/18.1.0' not resolved: Unable to find 'arrow/18.1.0' in remotes.`

### Package and Environment Details

* Package Name/Version: **arrow/18.1.0**
* Operating System+version: **Windows 11 Pro**
* Compiler+version: **MSVC 2019**
* Conan version: **conan 2.9.x and 2.10.x**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=192
os=Windows

### Steps to reproduce

conan install . --settings=build_type=Release --build=missing -s compiler.cppstd=17

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: Package 'arrow/18.1.0' not resolved: Unable to find 'arrow/18.1.0' in remotes.
```

</details>

**Comment by davidsanfal** [comment]
Hi @jaimesalvador

Could you send us the output of the `conan remote list` command? thanks!

**Comment by jaimesalvador** [comment]
```
C:\>conan remote list
conancenter: https://center.conan.io [Verify SSL: True, Enabled: True]
WARN: deprecated: The remote 'https://center.conan.io' is now frozen and has been replaced by 'https://center2.conan.io'.
Starting from Conan 2.9.2, the default remote is 'center2.conan.io'.
It is recommended to update to the new remote using the following command:
'conan remote update conancenter --url="https://center2.conan.io"'
```

**Comment by jcar87** [comment]
Awesome, great to hear @jaimesalvador ! This makes sense

We were confused by `ERROR: Remote 'conan-center' can't be found or is disabled` - but indeed it is called `conancenter`

Glad it's been fixed, closing this issue - let us know if there's anything else we can help with
