### ISSUE TITLE
[package] scnlib/4.01: GCC 11 is no longer unsupported

### ISSUE THREAD

**Issue by alanb-sony** [conan-io/conan-center-index#26224]
### Description

The scnlib recipe rejects building with GCC 11 but this issue has been fixed since scnlib 3.0.2 https://github.com/eliaskosunen/scnlib/commit/a0e0ebe1c4fc9393bddd299ccc3cbdb3935400f4

### Package and Environment Details

* Package Name/Version: **scnlib/4.0.1**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 1**
* Conan version: **conan 2.6.0**
* Python version: **Python 3.10.12**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

### Steps to reproduce

conan install -r conancenter --requires scnlib/4.0.1@

### Logs

<details><summary>Click to expand log</summary>

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[conf]
tools.cmake.cmaketoolchain:generator=Ninja

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[conf]
tools.cmake.cmaketoolchain:generator=Ninja


======== Computing dependency graph ========
Graph root
    cli
Requirements
    fast_float/6.1.0#f6088e57bf83ac9f9b3abf37fe766cea - Cache
    scnlib/4.0.1#ebd4223ea5648b564b36db596337d00b - Cache
Build requirements
    cmake/3.31.0#ba7dbf3b2fc9e70653b4c0fb5bbd2483 - Cache
Resolved version ranges
    cmake/[>=3.16 <4]: cmake/3.31.0

======== Computing necessary packages ========
Requirements
    scnlib/4.0.1#ebd4223ea5648b564b36db596337d00b:9661beb3a679f3ea04773c79664c1ce60f7f1850 - Invalid
Build requirements
Skipped binaries
    fast_float/6.1.0, cmake/3.31.0
ERROR: There are invalid packages:
scnlib/4.0.1: Invalid: scnlib/4.0.1 doesn't support gcc 11.x due to std::regex_constants::multiline is not defined
```

</details>

**Comment by AbrilRBS** [comment]
Hi @alanb-sony thanks a lot for the report, we appreciate it! I've now proposed https://github.com/conan-io/conan-center-index/pull/26232 to address this, thanks a lot!

**Comment by AbrilRBS** [comment]
Closed by the linked PR, thanks!
