### ISSUE TITLE
[question] How to get the GitHub package tester runner to use a newer CMake?

### ISSUE THREAD

**Issue by eyalroz** [conan-io/conan-center-index#26264]
### What is your question?

I maintain a library which recently upped its minimum CMake version to 3.25. When I upload a PR for the version with this change - the GitHub actions/checks [fail](https://github.com/conan-io/conan-center-index/pull/26256/checks?check_run_id=34846610620).

How can I "tell" GitHub, or the runner performing this action, that my library/recipe requires the use of a newer CMake? I tried adding:
```
    def build_requirements(self):
        self.tool_requires("cmake/[>=3.25.0 <4]")
```
into my recipe class, imitating what I've seen in some other recipes but that did not help, nor did I get an error I could use in order to figure out what to do.

So - one of several options:

* If my recipe is fine, and the runner refuses to respect it - that's a bug.
* If my recipe is broken/contains some error - I should be getting some error message about the recipe itself.
* In both cases - when getting the error about an insufficient CMake version - it would be a good idea if the runner were to also issure a message explaining how to require a higher version of CMake.

**Comment by Nekto89** [comment]
There are probably several issues with your change:

1) that recipe from your link doesn't use CMake at all. It is header-only library that just copies src folder without running CMake.
2) you have failure because you've increased cmake version for test_package for whatever reason but you didn't add cmake to test package build requirements
3) you've changed name of target with some name that isn't provided through conan recipe so it will fail

**Comment by eyalroz** [comment]
@Nekto89 : First, thank you - for a quick and helpful answer. 

Just one point I didn't quite understand: How do I tell Conan, or the GitHub runner, the names of the CMake target my library provides? I don't believe I was indicating that before the change.

> There are probably several issues with your change:
> 
>     1. that recipe from your link doesn't use CMake at all. It is header-only library that just copies src folder without running CMake.
> 
>     2. you have failure because you've increased cmake version for test_package for whatever reason but you didn't add cmake to test package build requirements
> 
>     3. you've changed name of target to some name that isn't provided through conan recipe so it will fail

**Comment by Nekto89** [comment]
> @Nekto89 : First, thank you - for a quick and helpful answer.
> 
> Just one point I didn't quite understand: How do I tell Conan, or the GitHub runner, the names of the CMake target my library provides? I don't believe I was indicating that before the change.

https://github.com/conan-io/conan-center-index/blob/4622ac85d1cec8cb7a2fcc8a1796d4b73bff285e/docs/package_templates/header_only/all/conanfile.py#L73C9-L81C76

**Comment by eyalroz** [comment]
To summarize the (eventual) answer:

1. Distinguish between *library* build and *test package* build; they each have their own `conanfile.py`
2. Your syntax is fine - but put this in the test package's `conanfile.py`
3. Since the CMake target(s) you export don't have the default name (i.e. it's not `mylibrary::mylibrary`), you also have to specify the target name, in the library's `conanfile.py` like so:
    ```
    def package_info(self):
        # etc. etc.
        self.cpp_info.set_property("cmake_target_name", "cuda-api-wrappers::runtime-and-driver")
    ```
