### ISSUE TITLE
[request] gdcm/3.0.7

### ISSUE THREAD

**Issue by feliwir** [conan-io/conan-center-index#2641]
### Package Details
  * Package Name/Version: **gdcm/3.0.7**
  * Website: **https://http://gdcm.sourceforge.net/**
  * Source code: **https://github.com/malaterre/GDCM**

### Description Of The Library / Tool
A library for loading / manipulating DICOM images, similar to DCMTK. I've created a rule already over here: https://github.com/feliwir/conan-gdcm
@Croydon suggested that this is a better place than the bincrafters repository.

With best regards

**Comment by akalali** [comment]
Maybe this is useful: https://git.ircad.fr/conan/conan-gdcm

**Comment by intelligide** [comment]
| Library | In CCI |
| --- | --- |
| Poppler | :x: |
| libjpeg | :heavy_check_mark: |
| openjpeg | :heavy_check_mark: |
| charls | :heavy_check_mark: |
| zlib | :heavy_check_mark: |
| zlib | :heavy_check_mark: |
| zlib | :heavy_check_mark: |

**Comment by feliwir** [comment]
@intelligide i think all of these are optional dependencies

**Comment by intelligide** [comment]
socketxx is required by MessageExchangeDefinition (gdcmMEXD).
poppler and papyrus3 are optional, you're right.

**Comment by feliwir** [comment]
@intelligide well it does also compile without socketxx, i tested that for my rule.

**Comment by Nekto89** [comment]
git.ircad.fr link to conan-gdcm requires logging in.

I've tried creating recipe for gdcm/3.0.9 from scratch. Unfinished recipe can be found here if anyone would like to use it as starting point https://github.com/Nekto89/conan-center-index/commit/3fe0097af36b40ce7da4f27fea7a344b322ba541

One of the problems: conan-center-index has recipe only for charls/2.1.0. gdcm currently doesn't support any versions except 2.0.0 - it seems to be using deprecated methods so I don't know what will be the consequences even if compilation will be fixed through patches.

Another problem: I don't think that libjpeg can be reused from cci. gdcm has patched version that allows building multiple versions of libjpeg (with 8/12/16-bit support) and using them simultaneously with mangled prefixes for all methods. If I understood correctly, version 6b was used for this.

**Comment by Nekto89** [comment]
https://github.com/conan-io/conan-center-index/pull/5705

**Comment by feliwir** [comment]
Hey i just tested this recipe. I'm missing the GDCMConfig.cmake though :-/
