### ISSUE TITLE
sentry-native/0.4.1

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#2688]
### Package Details
  * Package Name/Version: **sentry-native/0.4.1**
  * Website: **https://sentry.io**
  * Source code: **https://github.com/getsentry/sentry-native**

### Description Of The Library / Tool
The Sentry Native SDK is an error and crash reporting client for native applications, optimized for C and C++. Sentry allows to add tags, breadcrumbs and arbitrary custom context to enrich error reports.

There is already one outdated unofficial recipe, sentry-native/0.2.6, but it is working only for linux

**Comment by Croydon** [comment]
> There is already one outdated unofficial recipe, sentry-native/0.2.6, but it is working only for linux

Which one do you mean?

**Comment by Croydon** [comment]
Actually, we already have sentry-native https://conan.io/center/sentry-native/0.2.6/

Please use the issue template for new versions next time 😄

**Comment by AndreyMlashkin** [comment]
ok, I will close this one :)
