### ISSUE TITLE
[package] fftw/3.8.8: fftw.f not packaged

### ISSUE THREAD

**Issue by peterSW** [conan-io/conan-center-index#2693]
The CMake wrapper trick is making the use of CMAKE_SOURCE_DIR in the upstream CMakeLists.txt fail.

As a result this:
```
if (EXISTS ${CMAKE_SOURCE_DIR}/api/fftw3.f)
  install (FILES api/fftw3.f api/fftw3l.f03 api/fftw3q.f03 DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
endif ()
```
from the upstream CMakeLists.txt does not have the intended effect and fftw3.f is not installed.

A potential fix would be to add:
```
        tools.replace_in_file(self._source_subfolder + "/CMakeLists.txt",
                              "CMAKE_SOURCE_DIR",
                              "CMAKE_CURRENT_SOURCE_DIR",
                              )
```
to the source method of the Conan recipe.

Having fftw3.f installed by this package would make it much more useful for use with Fortran,

**Comment by Croydon** [comment]
Sounds reasonable. Should also probably be upstreamed
