### ISSUE TITLE
[package] gsl-lite/0.37.0: Error on install

### ISSUE THREAD

**Issue by redpandamonium** [conan-io/conan-center-index#2713]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **gsl-lite/0.37.0**
  * Operating System+version: **Manjaro Linux**
  * Compiler+version: **clang 10.0.1**
  * Conan version: **conan 1.24.1**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Debug
[options]
[build_requires]
[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
```

### Steps to reproduce (Include if Applicable)
Include gsl-lite/0.37.0 into the conanfile and install. 

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
$ conan install --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
conanfile.txt: Installing package
Requirements
    gsl-lite/0.37.0 from 'conan-center' - Cache
Packages
    gsl-lite/0.37.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
gsl-lite/0.37.0: Already installed!
ERROR: gsl-lite/0.37.0: Error in package_info() method, line 55
        self.cpp_info.filenames["cmake_find_package"] = "gsl-lite"
        TypeError: '_CppInfo' object does not support item assignment
```

</details>

**Comment by SSE4** [comment]
@redpandamonium you need to update your conan client to the latest version
