### ISSUE TITLE
[package] fftw/3.3.8: single precision does not link to correct library (at least on linux)

### ISSUE THREAD

**Issue by GavinNL** [conan-io/conan-center-index#2746]
I am attempting to compile an application on Linux that uses fftw/3.3.8 with `option:precision=single` and it does not link to the correct library:

```
/usr/bin/ld: cannot find -lfftw3
```

A quick search of the package/lib folder shows that the library should be `fftw3f`

```
$ ls $HOME/.conan/data/fftw/3.3.8/_/_/package/619e12106db48101cbfa69aa6351c5295f11ff75/lib
libfftw3f.a
```
I do not know if this is the case for all operating systems.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **fftw/3.3.8**
  * Operating System+version: **Linux Mint 19**
  * Compiler+version: **GCC 7**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.24.0**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

```

**Comment by SpaceIm** [comment]
Correct.
fftw adds a suffix based on precison:
default precision (double) => no suffix
float (single) => f
long double (longdouble) => l
quad precision (not implemented in recipe) => q

```cmake
set (PREC_SUFFIX)
if (ENABLE_FLOAT)
  set (FFTW_SINGLE TRUE)
  set (BENCHFFT_SINGLE TRUE)
  set (PREC_SUFFIX f)
endif ()

if (ENABLE_LONG_DOUBLE)
  set (FFTW_LDOUBLE TRUE)
  set (BENCHFFT_LDOUBLE TRUE)
  set (PREC_SUFFIX l)
endif ()

if (ENABLE_QUAD_PRECISION)
  set (FFTW_QUAD TRUE)
  set (BENCHFFT_QUAD TRUE)
  set (PREC_SUFFIX q)
endif ()
set (fftw3_lib fftw3${PREC_SUFFIX})
```

I'll fix that

**Comment by SpaceIm** [comment]
It also affects:
- fftw3 openmp lib
- fftw3 threads lib
- pkg config name
- CMake config file name and CMake imported target
