### ISSUE TITLE
[question] How to find the full text of the Conan-Center-Index project CLA 

### ISSUE THREAD

**Issue by rzheleva** [conan-io/conan-center-index#2757]
Hello Team, 

I am looking for the full text of the Conan-Center-Index project CLA, may you please assist me to locate it?

The text of the CLA that is available for signing with the CLA Assistant tool ends with point 3. Source of Contribution, which looks incomplete, since usually there is a bit more to a CLA. I have attached a screenshot for reference. 

May you please point to the location of the full CLA?

Thanks,
Radi
![Screen Shot 2020-09-02 at 10 56 36 AM](https://user-images.githubusercontent.com/68892346/91954815-0014ae80-ed0b-11ea-87d3-37b5d11b5233.png)

**Comment by prince-chrismc** [comment]
Ohh maybe there could be a copy in the docs/ folder in the repo?

**Comment by rzheleva** [comment]
Thank you, Chris!

After going through the documentation as you suggested, I still wasn't able to find a copy. Is there a chance you may provide one for me? 

Thanks, 
Radi

**Comment by prince-chrismc** [comment]
Im sorry for wasting your time! I was suggesting the CLA gets added to the repo!

We need a copy of the CLA in git!

**Comment by uilianries** [comment]
@rzheleva The CLA is simple indeed, it's not incomplete. All CLA description is correct, CCI is using CLA assistant. Also, the project is under MIT license.

**Comment by rzheleva** [comment]
Thank you, @uilianries, for confirming that this what is available in the CLA Assistant is the full CLA text 😄
