### ISSUE TITLE
[package] Error building OpenSSL for Android

### ISSUE THREAD

**Issue by TcT2k** [conan-io/conan-center-index#28]
While building OpenSSL for android on macOS I've seen the following issue when building for arm:

`openssl/conanfile.py` modifies `Makefile.org` with a string replace `AR=arm-linux-androideabi-ar` this replace is somehow triggered two times resulting in `AR=arm-linux-androideabi-arm-linux-androideabi-ar`.

I think the problem always triggers when using an `arm-` prefix as this also matches searching for `AR=ar`

My conanfile.txt:
```
[requires]
OpenSSL/1.0.2s@conan/stable
Poco/1.9.3@pocoproject/stable

[generators]
cmake
```

My profile:
```
ndk_root=$HOME/Library/Android/sdk/ndk-bundle
standalone_toolchain=$HOME/Development/toolchains/android-16-arm/
target_host=arm-linux-androideabi
cc_compiler=clang
cxx_compiler=clang++

[settings]
compiler=clang
compiler.version=8
compiler.libcxx=libc++
os=Android
os.api_level=16
arch=armv7
build_type=Release

[env]
CONAN_CMAKE_TOOLCHAIN_FILE=$ndk_root/build/cmake/android.toolchain.cmake
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=\$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
STRIP=$target_host-strip
CFLAGS= -fPIE -fPIC -I$standalone_toolchain/include/c++/4.9.x
CXXFLAGS= -fPIE -fPIC -I$standalone_toolchain/include/c++/4.9.x
LDFLAGS= -pie

```

**Comment by Croydon** [comment]
The openssl recipe version here in the conan-center-index is NOT

`OpenSSL/1.0.2s@conan/stable`

please change it to `openssl/1.0.2s` and try again

**Comment by TcT2k** [comment]
I've changed the requires to :
```
[requires]
poco/1.9.3
```

Results in the same issue if I do not use `AR=\` instead of `AR`

**Comment by SSE4** [comment]
@TcT2k I've found the problem - we have used too weak replace pattern `AR=ar`, therefore `AR=arm-linux-androideabi-ar` matched as it starts from the same prefix. I've made a PR that fixes that.
