### ISSUE TITLE
[package] Duplicate package: jsonformoderncpp and nlohmann_json

### ISSUE THREAD

**Issue by hnOsmium0001** [conan-io/conan-center-index#2835]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: `jsonformoderncpp`, `nlohmann_json`
  * `nlohmann_json` has way more version than `jsonformoderncpp` (which only has `3.7.0`)

This might be really hard to fix, as consumers may depend on `jsonformoderncpp` and removing it would be a breaking change.

**Comment by intelligide** [comment]
`jsonformoderncpp` is the old name for `nlohmann_json`. `jsonformoderncpp` is now deprecated(see [here](https://github.com/conan-io/conan-center-index/blob/master/recipes/jsonformoderncpp/all/conanfile.py#L15)) and it no longer receives updates (only recipe bug fixes).

Just like you say, removing it would be a huge breaking change. I think it's better to keep `jsonformoderncpp` as long as it's not a problem.
