### ISSUE TITLE
[package] arrow/1.0.0: Debug build fails with parquet=True and static thrift

### ISSUE THREAD

**Issue by gierdo** [conan-io/conan-center-index#2881]
Building arrow with parquet enabled fails due to thrift appending a debug suffix to the library and the suffix not being added correctly when attempting to link the library.

### Package and Environment Details:
  * Package Name/Version: **arrow/1.0.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 8.4.0**
  * Conan version: **conan 1.28.2**
  * Cmake version: **3.16.3**

### Steps to reproduce:

  * Build arrow/1.0.0 with **parquet=True**, "thirft:shared=False" and **build_type=Debug**

### Result:
The build fails with:

```
--   No package 'thrift' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Thrift (missing: THRIFT_STATIC_LIB) (found suitable version
  "0.13.0", minimum required is "0.11.0")
```
### Expected Result:
The build passes, all is well.

**Comment by gierdo** [comment]
This issue will be fixed with https://github.com/conan-io/conan-center-index/pull/2664

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as `arrow/1.0.0` was dropped support a long time ago and this issue was also solved!
Happy coding 🐸
