### ISSUE TITLE
[package] jasper/2.0.14: Now incompatible with OpenCV

### ISSUE THREAD

**Issue by rems4e** [conan-io/conan-center-index#2883]
Hi,

Since commit 1fd9b35bcc83e87b246b81d08f3401f2e46ee157 

the jpegturbo enabling option has been renamed, which breaks opencv/4.1.1. OpenCV explicitely sets the jpeg-turbo option the old way, which makes Conan complain this way:

```
jasper/2.0.14: Downloaded recipe revision aaafcadc016757fbd39cc5cbf19be5c6
ERROR: jasper/2.0.14: option 'jpegturbo' doesn't exist
Possible options are ['shared', 'fPIC', 'with_libjpeg']
```

I don't see how this could be sorted out easily, but probably having a conanfile per version of jasper or so would be a solution.

Thanks in advance!

**Comment by SpaceIm** [comment]
Indeed, jpegturbo option should be restored, and marked deprecated.

**Comment by uilianries** [comment]
@rems4e Which OpenCV recipe? We don't have OpenCV in CCI, only in Conan-Community, so your reference doesn't match.

**Comment by rems4e** [comment]
Sure, the reference is `opencv/4.1.1@conan/stable`. But the main point remains, that some packages in the wild that reference `jasper/2.0.14` or older need the older option.

The implementation proposed by @SpaceIm is going in the right direction I think.
