### ISSUE TITLE
[conan.io/center] Browse contents + download package

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#2885]
When I want to debug a build failure on a platform I don't own, I often need to see/download the contents of the package.

e.g. recently I see errors on Macos about missing jasper headers (see https://github.com/conan-io/conan-center-index/pull/2735#issuecomment-689813914).
[The jasper page on conan.io/center](https://conan.io/center/jasper/2.0.19/?user=_&channel=_&revision=&os=Macos&tab=config) does not have a link to see the contents of the package or a link to download it.

I now have to manually navigate to [the correct package on bintray](https://bintray.com/package/files/conan/conan-center/jasper%3A_?order=asc&sort=name&basePath=_%2Fjasper%2F2.0.19%2F_%2Fac16356832b7eb5f1c3b5368b1d674de%2Fpackage%2F68e5748c492e93890c4703b734202208b89c46d0%2F9937612ce253d6c955123c083b811e07&tab=files).
This can be done automatically by adding a link.

**Comment by madebr** [comment]
Using the bintray workaround is not possible anymore.
It would be nice to download the manifest.

**Comment by AbrilRBS** [comment]
Note that with Conan 2, this can be done with `conan download`
