### ISSUE TITLE
[request] bazel/3.5.0 (latest)

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#2897]
### Package Details
  * Package Name/Version: **bazel/3.5.0**
  * Website: **https://bazel.build/**
  * Source code: **https://github.com/bazelbuild/bazel/releases/tag/3.5.0**

### Description Of The Library / Tool
Google's build system.

The documentation on https://docs.bazel.build/versions/3.5.0/install-compile-source.html says that bootstrapping bazel requires java sdk.
So #2756 or something similar is required first.

**Comment by intelligide** [comment]
Bazel bootstrap requires `zip`, `unzip` and `patch` on msys2. Is it safe to use pacman like [this](https://github.com/bincrafters/conan-bazel_installer/blob/testing/0.27.1/conanfile.py#L48) in CCI recipe ?

**Comment by madebr** [comment]
I must admit that the msys2 recipe is the only offender, as it connects to the internet to fetch the packages at install time.

**Comment by Croydon** [comment]
For the case that it helps: https://github.com/bincrafters/conan-bazel_installer

**Comment by jgsogo** [comment]
Bazel 4.0.0 is already available (https://conan.io/center/bazel), do we need this older version?

**Comment by valgur** [comment]
Can be closed.
