### ISSUE TITLE
[service] Expose build logs

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#29]
Hi!

When a PR fails I receive 3 logs, the profile, error log (stderr) and the regular build log (stdout). So far, so good, but how could I check if a successfully build is missing something? For now I can't read all build logs as exposed when running Appveyor or any other CI service.

Possible solution: Generates a table with profiles, where we can read the logs based on package id a specific setting, like compiler version.

**Comment by lasote** [comment]
When a configuration fails I'm linking now a URL for the folder containing folders with the `package_ids` and all the log files and profile for that build. See an example here:

https://github.com/conan-io/conan-center-index/pull/43

In case the build is a success I think it is not a priority to show it so I didn't implement it (it had other considerations).

Let me know if it is enough for now.

**Comment by danimtb** [comment]
@uilianries did you see the new link to the logs? WDYT?

**Comment by danimtb** [comment]
See "access to all the logs" here for example https://github.com/conan-io/conan-center-index/pull/49#issuecomment-530480076

**Comment by uilianries** [comment]
I see, but is not enough. The question is about when a CI job is okay by the build result, but something can be missing (e.g. some header files or a lib). 

That's the advantage of Travis and other CI services, I can check all logs to be sure about all artifacts in he package.

**Comment by danimtb** [comment]
I understand the solution is not complete, but you can actually navigate the link and access the log of any build without waiting for the bot to post the link when an error is thrown. I know it is not neat but it is something at least for now

**Comment by uilianries** [comment]
In fact, but is not public yet, that's why I asked something more public. Any user should be able to check all builds. Look vcpkg, until one month ago no one was able to know about their build process, a black box. So, they opened all build logs and all community like the idea (which was expected by months).

**Comment by lasote** [comment]
@uilianries If I provide the same list of logs even if the build ends correctly would be better then? I know you want to access the pipeline-interface, but let's be pragmatic. What do you need exactly?

**Comment by uilianries** [comment]
> @uilianries If I provide the same list of logs even if the build ends correctly would be better then?

That's it!

**Comment by lasote** [comment]
Done!

**Comment by uilianries** [comment]
a BIG thank you!
