### ISSUE TITLE
[service] Update MSBuild version

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-center-index#2920]
Needed here https://github.com/conan-io/conan-center-index/pull/2901

**Comment by newlawrence** [comment]
We also have [this one](https://github.com/conan-io/conan-center-index/pull/3375#discussion_r519203040) (#3375) @jgsogo.

**Comment by jgsogo** [comment]
I see the latest version is Visual Studio 2019 MSBuild 16.8: https://docs.microsoft.com/visualstudio/releases/2019/release-notes, let's ask the infra team to upgrade it (we will run some testing in our staging environment before upgrading production)

**Comment by uilianries** [comment]
Vote +1

**Comment by jgsogo** [comment]
All Windows machines have been running `cl.exe 19.28.29333` for a while
