### ISSUE TITLE
[service] upgrade to conan 1.29.1

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-center-index#2929]
CCI should upgrade to conan 1.29, because several PR's are blocked until then:
- [atk](https://github.com/conan-io/conan-center-index/pull/2301)
- [gstreamer](https://github.com/conan-io/conan-center-index/pull/2303)
- [xorg](https://github.com/conan-io/conan-center-index/pull/2741)
- [cairo](https://github.com/conan-io/conan-center-index/pull/2847)
- [opusfile](https://github.com/conan-io/conan-center-index/pull/2758)

the corresponding CPT PR is https://github.com/conan-io/conan-docker-tools/pull/219

**Comment by uilianries** [comment]
We should provide the Docker image as soon as we have 1.29.1 I think

**Comment by ericLemanissier** [comment]
conan 1.29.1 is out now. Do you think it's the good time to upgrade C3I ?

**Comment by danimtb** [comment]
merged https://github.com/conan-io/conan-docker-tools/pull/219. Waiting until the images are available in docker hub to perform the update in windows and mac agents

**Comment by danimtb** [comment]
Upgraded! https://github.com/conan-io/conan-center-index/pull/2959

**Comment by Croydon** [comment]
Thanks!

It can be closed then?

**Comment by ericLemanissier** [comment]
It seems apple-clang 9.1 and windows are not yet upgraded: https://github.com/conan-io/conan-center-index/pull/2303#issuecomment-695026802

**Comment by danimtb** [comment]
It is working now

**Comment by ericLemanissier** [comment]
yes, thanks !
