### ISSUE TITLE
[service] Display logs in browser without downloading them

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#2965]
When ever we need to check the output of a build, we are forced to download the file locally.

For example...

![image](https://user-images.githubusercontent.com/16867443/93657846-fb871000-fa03-11ea-99b5-46e78ac739b5.png)

Would it be possible to have a `Content-Disposition: inline` to prevent this behavior?

**Comment by prince-chrismc** [comment]
❤️ love this seems to have been merged

**Comment by Croydon** [comment]
Awesome!

**Comment by prince-chrismc** [comment]
This seems to have disappeared with the new build system backend

**Comment by danimtb** [comment]
This is working fine! closing the issue as completed 😄
