### ISSUE TITLE
rocksdb: rocksdb/6.10.2: Error in requirements() method, line 151

### ISSUE THREAD

**Issue by faddat** [conan-io/conan-center-index#2967]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **rocksdb/6.10.2**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.7.4**

Only affects arm64

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Put your profile output here
```

### Steps to reproduce (Include if Applicable)
Spin up an AWS gravitron (arm64) instance and attempt to use rocksdb/6.10.2.

It will fail because it cannot find with_tbb.

### Logs (Include/Attach if Applicable)
Once I fire it up again, I'll post here, the instance is deleted now.

```
Put your log output here
```

</details>

**Comment by gocarlos** [comment]
can you try https://conan.io/center/tbb/2020.2

**Comment by Croydon** [comment]
Please fill out the issue template entirely, including your Conan profile + your build log

**Comment by SpaceIm** [comment]
@gocarlos The issue is in rockstb recipe itself:

```python
    def config_options(self):
        ...
        if self.settings.arch != "x86_64":
            del self.options.with_tbb
```

Then `with_tbb` is used without any check or get_safe in `requirements` and `_configure_cmake` methods.

**Comment by gocarlos** [comment]
@SpaceIm is there am MR open for the fix?

**Comment by SpaceIm** [comment]
No, I remember I faced some troubles trying to fix another thing. I can open a PR fixing with_tbb and CMake imported target.

**Comment by faddat** [comment]
Hey thanks guys.  

It was a pitifully documented issue and seems you nailed it anyway.

If there's anything else you need let me know.  I'll try the PR out and see if it builds now.
