### ISSUE TITLE
[package] Wt/4.4.0: conan-center cmake target name wt::wt not compatible with upstream Wt::Wt

### ISSUE THREAD

**Issue by wdobbe** [conan-io/conan-center-index#2978]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **wt/4.4.0**
  * Operating System+version: **all**
  * Compiler+version: **all**

  * Conan version: **conan 1.29.1**
  * Python version: **Python 3.6.10**

### Description
The upstream cmake targets for the Wt library are Wt::Wt, Wt::HTTP, Wt::DboSqlite3,Wt::Dbo etc.

When using generator cmake_paths and cmake_find_package, Conan generates a Findwt.cmake that defines cmake target wt::wt. As a result, existing code that starts to use Conan breaks.

A full fix would probably include conan components but as a start we could add the following lines to the Wt conanfile.py (analog to what the Boost Conan recipe does):
```
self.cpp_info.names["cmake_find_package"] = "Wt"
self.cpp_info.names["cmake_find_package_multi"] = "Wt"
```

Motivation: our application that uses Wt builds with the Yocto framework (bitbake), which has it own package dependency management. For development on desktop we use Conan for dependency management. So I can't change the cmake files and have to use the cmake_paths. Because conan-center unfortunately removes the upstream Cmake config files, I also have to use the cmake_find_package generator. 

If this change is approved I can create a pull request.

**Comment by SpaceIm** [comment]
Will be fixed by https://github.com/conan-io/conan-center-index/pull/2559

**Comment by wdobbe** [comment]
Thanks for your changes, you beat me to it :-) .
