### ISSUE TITLE
[package] Fontconfig/*: error loading default config file

### ISSUE THREAD

**Issue by Dark-Passenger** [conan-io/conan-center-index#2981]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: ** fontconfig/* **
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.29.0**
  * Python version: **Python 3.7.4**

When running fontconfig it fails to load the default config file

the reason is https://github.com/conan-io/conan-center-index/blob/563bf4416f2d76392ab483e5300486759567b160/recipes/fontconfig/all/conanfile.py#L47

I don't think it makes sense to set the package folder as the system config directory, I think it should be `/etc/fonts` which
makes more sense when fontconfig is used on a client device (and is static linked).

**Comment by madebr** [comment]
Recipes can't install to subdirectories of root directories because all files must be packaged.
installing it there would make the package not relocatable to other machines because the file won't be there.

What the recipe maybe should do, assuming it is not relocatable, is set some environment variables.
fontconfig reads the following environment variables; `FONTCONFIG_FILE`, `FONTCONFIG_PATH`, `FONTCONFIG_USE_MMAP` nad `FONTCONFIG_SYSROOT`.
So maybe it should do `self.env_info.FONTCONFIG_SYSROOT=os.path.join(self.package_folder, "bin", "etc")`?

I don't know whether the line above is correct, or sufficient.

**Comment by Dark-Passenger** [comment]
> Recipes can't install to subdirectories of root directories because all files must be packaged.
> installing it there would make the package not relocatable to other machines because the file won't be there.
> 
> What the recipe maybe should do, assuming it is not relocatable, is set some environment variables.
> fontconfig reads the following environment variables; `FONTCONFIG_FILE`, `FONTCONFIG_PATH`, `FONTCONFIG_USE_MMAP` nad `FONTCONFIG_SYSROOT`.
> So maybe it should do `self.env_info.FONTCONFIG_SYSROOT=os.path.join(self.package_folder, "bin", "etc")`?
> 
> I don't know whether the line above is correct, or sufficient.

I don't mean to say that recipies should copy files to system root directories, what I ment was recipies should default to system defaults instead of package specific configurations

This configuration isn't developer specific but rather consumer specific (used via qt) and I don't think having the environment variables modified on a consumer is a logical resolution.

**Comment by madebr** [comment]
If we don't pass `--sysconfdir` to the configure script, then the files will be installed to `$prefix/etc`. Which has the same problem as you described.
(the files are installed in a subdirectory of bin to circumvent a check)

The paths given to the configure script are used for 2 purposes:
- install location;
- and default search patch

There is also a default config path variable, which we don't touch.
(`/usr/share/fonts` on my machine)

But if you want to use a static fontconfig build, and want to be really independent of the host machine, I think you should use your own configuration script, and set the environment variables yourself (using `setenv` or a wrapper script), before calling the fontconfig routines.
You should provide your own configuration scripts, as these might be missing or incompatible.

**Comment by Dark-Passenger** [comment]
Thanks for the explanation, well this sucks but it seems the only solution is to set the environment variables myself.

Thanks for the help 🙂
