### ISSUE TITLE
[question] Why pegtl/2.8.1@taocpp/stable has channel and user?

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#2982]
Why pegtl/2.8.1@taocpp/stable has channel and user?

Almost all recipes don't have them in conan-center-index

**Comment by madebr** [comment]
We have a `taocpp-pegtl` recipe.
We apparently prefix the taocpp recipes to avoid potential collisions.
This is because the names of the taocpp subprojects are very short.

**Comment by Croydon** [comment]
`@username/channel` is optional for a while now.

All packages in the Conan Center Index don't have a `@username/channel` anymore. Packages with a `@username/channel` do come from places like [conan-community](https://github.com/conan-community) (`@conan)`) and [Bincrafters](https://github.com/bincrafters) (`@bincrafters)`) or in this case from taocpp.

Before conan-center-index was born, there was another way to include packages in conan-center, hence all packages in conan-center with a `@username/channel` are from this time period.
