### ISSUE TITLE
[package] libffi/3.3: Installs to the wrong directory

### ISSUE THREAD

**Issue by matslil** [conan-io/conan-center-index#2983]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libffi/3.3**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **GCC 5.4.0**
  * Docker image: **N/A**
  * Conan version: **conan 1.21.1**
  * Python version: **Python 2.7.12**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Put your profile output here
```

### Steps to reproduce (Include if Applicable)
sudo CONAN_USER_HOME=/opt/Linux/x86_64 conan install -g cmake_find_package libffi/3.3@ -b --install-folder "/opt/Linux/x86_64"

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

The output goes to "/opt/linux/x86_64", while the build is done in "/opt/Linux/x86_64" (note lower-case l and upper-case L in Linux).

This makes the build fail.

**Comment by uilianries** [comment]
Hello @matslil You problem seems be related to Conan, not to that package. Anyway, could you please shared your command log? I can reproduce your case:

```
$ CONAN_USER_HOME=/opt/Linux/x86_64 conan install -g cmake_find_package libffi/3.3@ -b --install-folder "/opt/Linux/x86_64"
Auto detecting your dev setup to initialize the default profile (/opt/Linux/x86_64/.conan/profiles/default)
CC and CXX: /usr/bin/gcc, /usr/bin/g++ 
Found gcc 9
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/opt/Linux/x86_64/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************



Default settings
	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=gcc
	compiler.version=9
	compiler.libcxx=libstdc++
	build_type=Release
*** You can change them in /opt/Linux/x86_64/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


WARN: Remotes registry file missing, creating default one in /opt/Linux/x86_64/.conan/remotes.json

```

**Comment by matslil** [comment]
Upgraded Conan to 1.29.2, which solved the problem. So you were quite right, that this wasn't a problem with the package, but rather with Conan. Closing this issue.
