### ISSUE TITLE
[fontconfig] fontconfig/*: FontConfig does not include the system fonts on macos

### ISSUE THREAD

**Issue by Dark-Passenger** [conan-io/conan-center-index#2990]
fontconfig on macos does not include the system fonts

based on some google fu I found https://github.com/conda-forge/fontconfig-feedstock/blob/c0f637ba8e697c12d6335d3f62221c389e9fa19c/recipe/build.sh#L69

which basically points to https://github.com/Homebrew/homebrew-core/blob/master/Formula/fontconfig.rb

homebrew adds the system font paths to font config as extra font directories this option is not exposed in the package.

I think a good solution would be to expose this as a package option that takes a string and passes it forward as is or add the system paths like homebrew does.

currently a workable solution is to write a config file and ship it along with the application, but with additional directories option this won't be required.

**Comment by madebr** [comment]
FYI,
the paths passed to `--with-add-fonts` only end up in the config file [here](https://github.com/freedesktop/fontconfig/blob/dbef9d10de19288e56f58b7c1aa880d447e6ae85/fonts.conf.in#L28).

Note the disclaimer at the top:
```
	DO NOT EDIT THIS FILE.
	IT WILL BE REPLACED WHEN FONTCONFIG IS UPDATED.
	LOCAL CHANGES BELONG IN 'local.conf'.

	The intent of this standard configuration file is to be adequate for
	most environments.  If you have a reasonably normal environment and
	have found problems with this configuration, they are probably
	things that others will also want fixed.  Please submit any
	problems to the fontconfig bugzilla system located at fontconfig.org

	Note that the normal 'make install' procedure for fontconfig is to
	replace any existing fonts.conf file with the new version.  Place
	any local customizations in local.conf which this file references.

	Keith Packard
```

**Comment by Dark-Passenger** [comment]
So passing in our own config is the only way, okay then thank you for your time.

**Comment by madebr** [comment]
@Dark-Passenger 
There's nothing keeping you from modifying your fontconfig fork,
but I don't see an *official* way to do this.

I didn't check thoroughly, but maybe there's a `fontconfig_add_fonts_dir` function (or similar).

**Comment by Dark-Passenger** [comment]
>There's nothing keeping you from modifying your fontconfig fork,

That would defeat the purpose of using conan IMO 😜 

>but I don't see an official way to do this.

I see it's slightly cumbersome but not impossible 😁  Thanks for the help.
