### ISSUE TITLE
[question] Availability of "c3i" Jenkins Library

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan-center-index#30]
Hi, 
it is really interesting to see the setup of this repository. We're hosting all third-party libraries for in-house consumption in a similar way.

So I am wondering if the Jenkins library code for building / checking all recipes is publicly available somewhere. That would be very, very interesting to see how you are handling it, because we are still struggling on deciding when and what to to rebuild on a PR / how to handle packages which support only one platform / and so on.

Thanks for the feedback!

**Comment by Croydon** [comment]
It would be wonderful if this library would be open sourced as well 😄

**Comment by danimtb** [comment]
Hi all!

We know that the library could help to learn and understand new approaches to deal with CI flows using Conan. We are planning to give some interesting recommendations to achieve optimized flows and take advantage of the core features of Conan.

However, the purpose of the "c3i" library is far from that. Here we are massively creating packages for a bunch of configuration and rebuilding many packages to deal with changes in recipes. Also, the recipes have to be prepared to build in a wide spread of platforms and configurations and this is something not so typical inside an organization.

For these reasons, currently, it is not a priority to release the orchestration library behind this build service but we will consider writing about it for future documentation or posts on our blog.

We have added this to the new FAQ section in the wiki: https://github.com/conan-io/conan-center-index/wiki/FAQ#is-the-jenkins-orchestration-library-publicly-available

Thanks

**Comment by KerstinKeller** [comment]
Thanks for the info!

> However, the purpose of the "c3i" library is far from that. Here we are massively creating packages for a bunch of configuration and rebuilding many packages to deal with changes in recipes. Also, the recipes have to be prepared to build in a wide spread of platforms and configurations and this is something not so typical inside an organization.

Unfortunately, I think it is. Not so much for our internal packages, but for sure for the thirdparty packages, as we can't use the official packages and have to host everything in-house. This is one of the strong points of Conan. Being able to instantly port a project to a new compiler, new platform, which is unthinkable right now. But the CI needs to be able to deal with it.

> For these reasons, currently, it is not a priority to release the orchestration library behind this build service but we will consider writing about it for future documentation or posts on our blog.

Please do, will be looking forward to read about it :smile:

**Comment by danimtb** [comment]
We will cover that in the documentation once we talk about the CI flows. ·rd party libraries should be managed by the CI in the same way, just that the updates will not be so frequent.

I have opened a new issue in our blog repo and closing this due to the reasons given above. Please feel free to comment there and thanks a lot for the feedback! 😄

**Comment by Croydon** [comment]
I'm disappointed about this decision.
This library plays a huge role in the Conan ecosystem going forward and not open sourcing it is a huge bummer

**Comment by uilianries** [comment]
This about this library as the Predator, without the mask is a ugly monster, but you only see mask right now. It was made to attend Conan ecosystem. To share anything, first we need to improve and prepare it better.
