### ISSUE TITLE
[package] ixwebsocket/10.2.5: is locked by another concurrent conan process, wait...

### ISSUE THREAD

**Issue by bugproof** [conan-io/conan-center-index#3002]
### Package and Environment Details
  * Package Name/Version: **ixwebsocket/10.2.5**
  * Operating System+version: **Windows 10 2004**
  * Compiler+version: **MSVC19**
  * Conan version: **conan 1.29.2**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
It works with ixwebsocket/9.6.4 but it breaks with 10.2.5 and removing locks doesn't help.

**Comment by madebr** [comment]
This is not a recipe/package bug but a problem (bug?) with conan not releasing locks.

I have encountered similar problem too in the past. What I do is just remove the packages from my conan home.
On Linux, this is done by removing e.g. `~/.conan/data/ixwebsocket`.
On Windows, this can be done by removing `/users/bugproof/.conan/data/ixwebsocket`.
Let us know if that helps you further.

**Comment by bugproof** [comment]
I'm gonna try that and update this comment, so far I've tried `conan remove --locks` and it didn't work so maybe manually removing it will do the trick.

**Comment by bugproof** [comment]
That helped seems like a bug with `conan remove --locks` then thanks a lot @madebr .

**Comment by madebr** [comment]
Thanks @bugproof for coming back to us.

@uilianries @jgsogo @memsharded 
Just a FYI that there is a bug with locks on packages not being released.
No reproducer known atm.

**Comment by blackliner** [comment]
I had the same on my machine today with `catch2/2.13.3@`. Hopefully not very common, had to delete the package from the local cache, `conan remove --locks` did not help much 😞

**Comment by blackliner** [comment]
Ok, now our CI is stuck with that message: `acado/1.2.2-beta is locked by another concurrent conan process, wait...`

**Comment by madebr** [comment]
A lock is not released properly if conan is closed incorrectly or killed.
I can reproduce it by pressing `CTRL + \` when executing `conan create`.
A second `conan create` will block indefinitely.

**Comment by blackliner** [comment]
As I mentioned, this happened on our CI. Such a kill might happen quite frequently, when for example one pipeline fails while another pipeline is doing the conan install (we do not do conan create though!)

**Comment by blackliner** [comment]
maybe related to https://github.com/conan-io/conan/issues/7181 ?
