### ISSUE TITLE
[package] boost/1.73.0: header-only version has (unnecessary) dependency to b2

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan-center-index#3028]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.73.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Put your profile output here
```

### Steps to reproduce (Include if Applicable)

Build boost with the following command line:

    conan create -s compiler.version=10 -o boost:header_only=True -o boost:error_code_header_only=True . boost/1.73.0@fschoenm/testing

This should create a header-only package of boost but still has a build dependency to b2. Commenting out that dependency still creates the package so it seems to be not needed.

**Comment by madebr** [comment]
`b2` is added as a build requirement, which means it's only added while creating the boost package.
So when using the header-only boost package, `b2` will not be inserted in the dependency tree.

But indeed, the `b2` should be added conditionally when `self.options.header_only` is true.

**Comment by fschoenm** [comment]
> b2 is added as a build requirement, which means it's only added while creating the boost package.

Yeah I know. Still it's unnecessary and I don't have it on my machine. So it'd be nice if it could be removed.
