### ISSUE TITLE
Incorrect link on https://conan.io/center

### ISSUE THREAD

**Issue by mathbunnyru** [conan-io/conan-center-index#3034]
Link on https://conan.io/center named `Click here to learn more about Adding New Packages to ConanCenter` leads to https://github.com/conan-io/conan-center-index/wiki

It should lead to: https://github.com/conan-io/conan-center-index/blob/master/docs/contributing.md

**Comment by Dattax** [comment]
Yes :) The wiki pages were updated and moved. We will fix this on our next release. Thank you for logging it as an issue.

**Comment by Dattax** [comment]
This has been fixed.

**Comment by mathbunnyru** [comment]
Great, closing the issue.
