### ISSUE TITLE
[conan] ModuleNotFoundError: No module named 'conans'

### ISSUE THREAD

**Issue by handhikadj** [conan-io/conan-center-index#3041]
I got it while cmake compiles my program

### Package and Environment Details (include every applicable attribute)
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9.3.0**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[requires]
boost/1.74.0
rang/3.1.0
date/2.4.1
poco/1.10.1
rttr/0.9.6

[generators]
cmake
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=9;-s;compiler.libcxx=libstdc++11
-- Conan: checking conan executable
-- Conan: Found program /usr/bin/conan
-- Conan: Version found Traceback (most recent call last):
  File "/usr/bin/conan", line 5, in <module>
    from conans.conan import run
ModuleNotFoundError: No module named 'conans'

-- Conan executing: /usr/bin/conan install /home/me/myProject/conanfile.txt -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -g=cmake --build=missing
Traceback (most recent call last):
  File "/usr/bin/conan", line 5, in <module>
    from conans.conan import run
ModuleNotFoundError: No module named 'conans'
CMake Error at build/conan.cmake:402 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  build/conan.cmake:497 (conan_cmake_install)
  CMakeLists.txt:18 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/home/me/myProject/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

```

</details>

**Comment by SpaceIm** [comment]
Seems that it fails in you own CMakeLists, so it's not related to conan-center-index, maybe https://github.com/conan-io/cmake-conan?

**Comment by prince-chrismc** [comment]
Whats the output for `pip show conan` ?

**Comment by madebr** [comment]
@handhikadj 
Can you try running `conan install <path to conanfile.txt>` in your binary directory?
If that succeeds, conan is installed correctly, and you are able to fetch the conan dependencies.

I think you are battling with conan's cmake integration at the moment. See https://github.com/conan-io/cmake-conan/issues/281
Please close this issue after you fixed your problem(s).
Thakns!

**Comment by handhikadj** [comment]
i can run the command pretty smoothly but the message on this post title still appears

**Comment by madebr** [comment]
How did you install conan?
The line
```
/usr/bin/conan install /home/me/myProject/conanfile.txt -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -g=cmake --build=missing
```
shows that conan is installed in your root `/usr/bin/`.

**Comment by handhikadj** [comment]
installed it using `pip3 install --user conan`

**Comment by madebr** [comment]
Weird. When installing as a user, it should be installed to a directory in your home directory. Not in the root directory.
On my Linux machine:
```
$ which conan
~/.local/bin/conan
```
I suggest **completely** removing conan (you might have installed multiple conan versions) and reinstall.
And please install conan as an ordinary user, not as root.

**Comment by handhikadj** [comment]
conan is also in the `~/.local/bin/conan` on mine. 
how do I completely remove it? just `pip3 uninstall conan`?

**Comment by madebr** [comment]
@handhikadj 
Yes, `pip3 uninstall conan` should do.
conan is uninstalled successfully when running `conan` returns a `command not found...` error.

> conan is also in the `~/.local/bin/conan` on mine.

In your first message, the output of cmake contained `/usr/bin/conan`.
You should investigate that further.

**Comment by handhikadj** [comment]
what are the likelihood the culprit was?

**Comment by madebr** [comment]
One way or another, you installed it as root user (using pip, your package manager).
I can't really tell you as I am not your system administrator.

**Comment by uilianries** [comment]
Probably you installed using a different pip version from your python version. e.g. pip is under python2.7, but when your default python is 3. The safest way for installing a package is running `python -m pip install conan`

**Comment by handhikadj** [comment]
@madebr `/usr/bin/conan is symbolic linked to the `~/.local/bin/conan`

@uilianries there's only one python on my linux, that is python v3.8.2, from the linux's stock apps

**Comment by handhikadj** [comment]
it appears i should use `sudo python3 -m pip install conan` and it works flawlessly 
thank you all . GBYA

**Comment by madebr** [comment]
Glad we could help you.
Please Google for `sudo python pip`, because you're not supposed to use wifi with pip.

**Comment by askunix** [comment]
我还没有解决

**Comment by wxheartbeat** [comment]
> 我还没有解决
建议升级conan版本，低版本的Conan会跟你的系统环境有很多冲突，比如conan本身的一些依赖
