### ISSUE TITLE
[package] zlib/1.2.11: cannot compile zlib with clang 9

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#306]
gcc 8, 9 as well as clang 8 work well

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.8**
  * Operating System+version: **Linux Ubuntu 19.10**
  * Compiler+version: **clang 9**
  * Conan version: **conan 1.20.2**
  * Python version: **Python 3.7.5**

### Conan profile
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

```bash
export CC=/usr/bin/clang-9
export CXX=/usr/bin/clang++-9
cat << EOF > conanfile.txt
[requires]
zlib/1.2.11
[generators]
cmake_find_package
cmake_paths
EOF
conan install . --build missing
```
 

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

zlib/1.2.11: WARN: Package is corrupted, removing folder: /home/gocarlos/.conan/data/zlib/1.2.11/_/_/package/961755854760682044d37dabfc2d998658edf961
conanfile.txt: Installing package
Requirements
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    zlib/1.2.11:961755854760682044d37dabfc2d998658edf961 - Build

zlib/1.2.11: WARN: Build folder is dirty, removing it: /home/gocarlos/.conan/data/zlib/1.2.11/_/_/build/961755854760682044d37dabfc2d998658edf961
zlib/1.2.11: Copying sources to build folder
zlib/1.2.11: Building your package in /home/gocarlos/.conan/data/zlib/1.2.11/_/_/build/961755854760682044d37dabfc2d998658edf961
zlib/1.2.11: Generator cmake created conanbuildinfo.cmake
zlib/1.2.11: Calling build()
zlib/1.2.11: Calling:
 > ../configure '--prefix=/home/gocarlos/.conan/data/zlib/1.2.11/_/_/package/961755854760682044d37dabfc2d998658edf961' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' 
Compiler error reporting is too harsh for ../configure (perhaps remove -Werror).
** ../configure aborting.
zlib/1.2.11: 
zlib/1.2.11: ERROR: Package '961755854760682044d37dabfc2d998658edf961' build failed
zlib/1.2.11: WARN: Build folder /home/gocarlos/.conan/data/zlib/1.2.11/_/_/build/961755854760682044d37dabfc2d998658edf961
ERROR: zlib/1.2.11: Error in build() method, line 45
        self._build_zlib()
while calling '_build_zlib', line 102
        self._build_zlib_autotools()
while calling '_build_zlib_autotools', line 70
        env_build.configure("../", build=False, host=False, target=False)
        ConanException: Error 1 while executing ../configure '--prefix=/home/gocarlos/.conan/data/zlib/1.2.11/_/_/package/961755854760682044d37dabfc2d998658edf961' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' 
```

</details>

**Comment by uilianries** [comment]
Hi @gocarlos !

Sorry, but I can't reproduce your error. Are you using a specific Docker image or maybe a different Linux distro?

Here is my log:

<details>
$ conan install zlib/1.2.11@ --build zlib
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

zlib/1.2.11: Forced build from source
Installing package: zlib/1.2.11
Requirements
    zlib/1.2.11 from local cache - Cache
Packages
    zlib/1.2.11:961755854760682044d37dabfc2d998658edf961 - Build

zlib/1.2.11: Copying sources to build folder
zlib/1.2.11: Building your package in /home/conan/.conan/data/zlib/1.2.11/_/_/build/961755854760682044d37dabfc2d998658edf961
zlib/1.2.11: Generator cmake created conanbuildinfo.cmake
zlib/1.2.11: Calling build()
zlib/1.2.11: Calling:
 > ../configure '--prefix=/home/conan/.conan/data/zlib/1.2.11/_/_/package/961755854760682044d37dabfc2d998658edf961' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' 
Checking for shared library support...
Building shared library libz.so.1.2.11 with clang.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o adler32.o ../adler32.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o crc32.o ../crc32.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o deflate.o ../deflate.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o infback.o ../infback.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o inffast.o ../inffast.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o inflate.o ../inflate.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o inftrees.o ../inftrees.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o trees.o ../trees.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o zutil.o ../zutil.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o compress.o ../compress.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o uncompr.o ../uncompr.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o gzclose.o ../gzclose.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o gzlib.o ../gzlib.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o gzread.o ../gzread.c
clang -m64 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -include zconf.h -c -o gzwrite.o ../gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
zlib/1.2.11: Package '961755854760682044d37dabfc2d998658edf961' built
zlib/1.2.11: Build folder /home/conan/.conan/data/zlib/1.2.11/_/_/build/961755854760682044d37dabfc2d998658edf961
zlib/1.2.11: Generated conaninfo.txt
zlib/1.2.11: Generated conanbuildinfo.txt
zlib/1.2.11: Generating the package
zlib/1.2.11: Package folder /home/conan/.conan/data/zlib/1.2.11/_/_/package/961755854760682044d37dabfc2d998658edf961
zlib/1.2.11: Calling package()
zlib/1.2.11 package(): Packaged 2 '.h' files: zlib.h, zconf.h
zlib/1.2.11 package(): Packaged 1 '.a' file: libz.a
zlib/1.2.11 package(): Packaged 1 file: LICENSE
zlib/1.2.11: Package '961755854760682044d37dabfc2d998658edf961' created
zlib/1.2.11: Created package revision afcafe8a649da9400894ec0c2d158164

</details>

**Comment by gocarlos** [comment]
Minimal Example to reproduce:

```Dockerfile
FROM ubuntu:19.10

RUN apt update -y && apt install -y clang-9 python3-pip
RUN pip3 install conan --upgrade

RUN mkdir -p /tmp/test/ && cd /tmp/test/

RUN echo '\n\
    [requires]\n\
    zlib/1.2.11\n\
    [generators]\n\
    cmake_find_package\n\
    cmake_paths\n'\
    >> /tmp/test/conanfile.txt

RUN cat /tmp/test/conanfile.txt

RUN cd /tmp/test/ && \
    export CC=/usr/bin/clang-9 && \
    export CXX=/usr/bin/clang++-9 && \
    conan install . --build missing
```

**Comment by gocarlos** [comment]
smaller example: 

```Dockerfile
FROM ubuntu:19.10

RUN apt update -y && apt install -y clang-9 python3-pip
RUN pip3 install conan --upgrade
RUN export CC=/usr/bin/clang-9 && \
    export CXX=/usr/bin/clang++-9 && \
    conan install zlib/1.2.11@ --build zlib
```

**Comment by gocarlos** [comment]
using gcc 9 works: 

```Dockerfile
FROM ubuntu:19.10

RUN apt update -y && apt install -y clang-9 python3-pip
RUN pip3 install conan --upgrade
RUN conan install zlib/1.2.11@ --build zlib
```

**Comment by uilianries** [comment]
Thanks for your exemplification, I'll use it to reproduce your scenario.

**Comment by uilianries** [comment]
@gocarlos I've checked with conanio/clang9 docker recipe, you need to declare:

```
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-9 100 \
&& update-alternatives --install /usr/bin/clang clang /usr/bin/clang-9 100 \
&& update-alternatives --install /usr/bin/cc cc /usr/bin/clang-9 100 \
&& update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-9 100 \
&& update-alternatives --install /usr/bin/cpp cpp /usr/bin/clang++-9 100
```

**Comment by Croydon** [comment]
@gocarlos Is there a specific reason why you don't use the official Conan docker images?

**Comment by gocarlos** [comment]
I was using plain ubuntu due to company restrictions on docker containers in CI environments (gitlab ci)... 

thanks for clarify the issue :+1:

**Comment by uilianries** [comment]
hmm, I used Gitlab for many years, all Conan docker images work fine with Gitlab CI. Also you can download the Docker recipe and build at your company if they can't use external images. All recipes are here: https://github.com/conan-io/conan-docker-tools
