### ISSUE TITLE
[package] pcre/8.41: fail to compile

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#3067]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **pcre/8.41**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 2019**
  * Conan version: **conan 1.28.1** and **1.29.2**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.cppstd=14
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conan install pcre/8.41@ -r conan-center -pr debug --build outdated -u

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
> conan install pcre/8.41@ -r conan-center -pr debug --build outdated -u
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.cppstd=14
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
[build_requires]
[env]

bzip2/1.0.8: WARN: Can't update, no package in remote
bzip2/1.0.8: Package is up to date
zlib/1.2.11: WARN: Can't update, no package in remote
zlib/1.2.11: Package is up to date
pcre/8.41: WARN: Package is corrupted, removing folder: C:\Users\malas\.conan\data\pcre\8.41\_\_\package\bc41b64ba6c37efe48137d2bb0b024f3d580dc29
Installing package: pcre/8.41
Requirements
    bzip2/1.0.8 from 'conan-center' - Cache
    pcre/8.41 from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    bzip2/1.0.8:cc781f9bb12181ae8241d49eb8f67780d0c9e108 - Cache
    pcre/8.41:bc41b64ba6c37efe48137d2bb0b024f3d580dc29 - Build
    zlib/1.2.11:402cf37ea699030d7c8abcaa214949592ce22e9b - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
zlib/1.2.11: Already installed!
pcre/8.41: WARN: Build folder is dirty, removing it: C:\Users\malas\.conan\data\pcre\8.41\_\_\build\bc41b64ba6c37efe48137d2bb0b024f3d580dc29
ERROR: The 'pcre/8.41' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.
```

</details>

**Comment by madebr** [comment]
The error looks similar to https://github.com/conan-io/conan-center-index/issues/3032
I think the recipe/source/package are out of sync.
Please try my suggestion of #3032 but with the requirements of your project.

**Comment by AndreyMlashkin** [comment]
This fixed my problem:
conan remove pcre/8.41@

Maybe auto-detection of cache corruption should be a conan feature? Should I raise it as a separate ticket?

**Comment by madebr** [comment]
> Maybe auto-detection of cache corruption should be a conan feature? Should I raise it as a separate ticket?

Yes please!
Something tells me you'll not be the last one.
