### ISSUE TITLE
[package] jsonformoderncpp/all: cmake exported name is different than upstream

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#307]
according to upstream:
https://github.com/nlohmann/json#cmake

cmake should use `nlohmann_json` as target name.
conan index is using `jsonformoderncpp` and `jsonformoderncpp::jsonformoderncpp`

this should be fixed with e.g. `self.cpp_info.name` in the recipe

**Comment by Croydon** [comment]
//@iceflowre

**Comment by danimtb** [comment]
ok, I think renaming the library to the original name makes sense.

We should continue with the PR proposed #309 but we will need to add a deprecation message or a general invalid configuration one in the `jsonformoderncpp` recipe indicating that the name of the library has changed

**Comment by danimtb** [comment]
I have just realized that if we rename the recipe in this repo we will not be able to add a deprecation warning in the "old" `jsonformodercpp` recipe as there will be no sources

**Comment by danimtb** [comment]
Creating a copy instead of doing a rename will solve the issue but the list of contributors to that recipe will be lost

**Comment by danimtb** [comment]
Ok, after some internal discussion we have decided to go with the copy instead of the renaming. This will allow keeping the recipe repo (this) consistent with the packages uploaded to the center and it will be easier to understand.
