### ISSUE TITLE
[request] implot/0.8

### ISSUE THREAD

**Issue by seanballais** [conan-io/conan-center-index#3105]
### Package Details
  * Package Name/Version: **implot/0.8**
  * Website: **https://github.com/epezent/implot**
  * Source code: **https://github.com/epezent/implot**

### Description Of The Library / Tool
Implot is an advanced 2D plotting library for Dear ImGui.

---

I'd like to contribute a recipe for this.

**Comment by jgsogo** [comment]
Currently we have versions 0.11, 0.12 and 0.13.
