### ISSUE TITLE
[request] pdfium/4284

### ISSUE THREAD

**Issue by dsvensson** [conan-io/conan-center-index#3124]
### Package Details
  * Package Name/Version: **pdfium/4284**
  * Website: **https://pdfium.googlesource.com/pdfium/**
  * Source code: **https://pdfium.googlesource.com/pdfium/**

### Description Of The Library / Tool
A capable and efficient PDF rendering library powering for example the Chromium browser.

**Comment by paulo-coutinho** [comment]
I made an isolated project for desktop and mobile for this and can be used for reference:
https://github.com/paulo-coutinho/pdfium-lib
