### ISSUE TITLE
[request] Request a new library(CGAL) to be added

### ISSUE THREAD

**Issue by wanlizhu** [conan-io/conan-center-index#314]
**Name**: CGAL
**Version**: 5.0 
**License**: GNU General Public License
**Link to the project**: https://www.cgal.org/
**Link to the source**: https://github.com/CGAL/cgal

* **Popular**:
Github Stars: 1.6k

* **Header only**:
Since version 5.0, CGAL is a header-only library. 

* **Dependencies**:
 Boost 1.57.0 or newer

* **What is CGAL**:
The Computational Geometry Algorithms Library (CGAL) is a C++ library that aims to provide easy access to efficient and reliable algorithms in computational geometry. CGAL 5.0 Release Information: https://www.cgal.org/2019/11/08/cgal50/

**Comment by uilianries** [comment]
https://github.com/CGAL/cgal/wiki/Use-Conan-for-CGAL-on-Windows

**Comment by czoido** [comment]
@wanlizhu cgal 5.0 is now merged! 🥳
