### ISSUE TITLE
[question] Is it possible to freeze which conanfile.py version to use when fetching from conan-center-index

### ISSUE THREAD

**Issue by Timen** [conan-io/conan-center-index#3175]
I have run into the issue multiple times of a conanfile.py being updated in the conan-center-index and it breaking a local build of a package. While I'm aware of how someone can specify which version of the package should be installed, what isn't clear is the best way to freeze the conanfile.py version of a certain package.

Is this possible at all? If not what is the best way to freeze a conanfile.py version of a recipe in this repo? Is the only option a copy of the packages to an internal server?

**Comment by SpaceIm** [comment]
You can enable revision mode in `your conan.conf` (`revisions_enabled = True`). Then you can require a specific recipe revision (RREV).
