### ISSUE TITLE
[package] paho-mqtt-c/1.3.5: cmake_find_package_multi issue during conan create

### ISSUE THREAD

**Issue by keysight-daryl** [conan-io/conan-center-index#3176]
Tried using the latest paho-mqtt-c package here but targeting 1.3.5 of the library and during my conan create I am getting a bunch of cmake_find_package_multi errors that I don't quite know what to make of them.  Before the most recent additions of this feature here I was able to create the package fine.  The same issues are also happening with the latest paho.mqtt.cpp package which also added this new feature.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **paho-mqtt-c & paho-mqtt-cpp/latest**
  * Operating System+version: **Windows**
  * Compiler+version: **VS2017**
  * Conan version: **conan 1.24.0**
  * Python version: **Python 3.7.7**
  * cmake: **3.17.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile vs-15-debug:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Debug
compiler.runtime=MDd
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

conan create . k3p/stable -tf test_package -pr vs-15-debug --build missing

### Logs (Include/Attach if Applicable)

[find-package-multi-issue.txt](https://github.com/conan-io/conan-center-index/files/5366396/find-package-multi-issue.txt)

</details>

**Comment by Croydon** [comment]
I'm not sure if this would fix it, but there were many changes in the generators in recent Conan versions. Your version is rather old and in CCI we assume always the latest version. Are you able to update to a newer version?

**Comment by keysight-daryl** [comment]
Sure what version was this tested with?

**Comment by keysight-daryl** [comment]
both cmake and conan and python if possible just so i am on the same setup

**Comment by keysight-daryl** [comment]
Only issue with me upgrading the toolchain is our CI uses these versions too so that might break other peoples builds etc.

**Comment by Croydon** [comment]
CMake and Python versions are fine.

Conan is backwards compatible, so new versions should not break old packages. If you can update to `1.30.1` (most recent version) that would be good

**Comment by keysight-daryl** [comment]
weird is in the test package build folder i do see the eclipse-paho-mqtt-cConfig.cmake file...
![Screen Shot 2020-10-12 at 1 21 08 PM](https://user-images.githubusercontent.com/40178586/95774178-e6fa0880-0c8d-11eb-8d40-a16aca5bc0df.png)

**Comment by keysight-daryl** [comment]
Spot on brother, that seems to have fixed it for the paho.mqtt.c project at least now I will try again with the cpp one.  Is there a way to perhaps enforce the minimum conan version on a recipe with some error message to upgrade similar to how cmake has a minimum version?  Otherwise this is totally confusing

**Comment by keysight-daryl** [comment]
our CI is on conan 1.26.0, is this recent enough?

**Comment by keysight-daryl** [comment]
So now the paho.mqtt.cpp create package errors out still while looking for OpenSSL which we have as a different capitalization to what's in conan-center-index.  Ours is 'OpenSSL' instead of 'openssl' incase this matters?

[paho.mqtt.cpp find_package issue.txt](https://github.com/conan-io/conan-center-index/files/5366793/paho.mqtt.cpp.find_package.issue.txt)

**Comment by keysight-daryl** [comment]
Our version of OpenSSL was created perhaps previous to this new find_package behavior using a much older version of conan.  Would this need to be bumped and re-created?

**Comment by madebr** [comment]
The errors in https://github.com/conan-io/conan-center-index/issues/3176#issuecomment-707265571 are due to your openssl recipe not creating the cmake openssl targets.
Compare its `package_info` function with the one of cci master.

**Comment by keysight-daryl** [comment]
right it doesn't use this new cmake find multi feature.  It was a recipe created a year or so ago and just bumped along.  it sounds like this move to cmake find multi thing requires the entire stack of dependencies to be upgraded to using it.  we have dozens of packages in house and hundred of projects depending on them.  is there a better way forward and exactly what does this new feature 'buy us'?

**Comment by keysight-daryl** [comment]
I'm assuming it will also require updated zlib and derivative poco and other projects?

**Comment by madebr** [comment]
Components make the generated `FindXXX.cmake` modules more similar with the upstream ones.
They are not 100% equal yet, but by creating the same imported targets as the upstream project, switching between conan and e.g. system linux development libraries becomes much easier.

For e.g. OpenSSL, [the cmake documentation](https://cmake.org/cmake/help/latest/module/FindOpenSSL.html) explicitly lists the targets, so it is reasonable to expect our generated `FindOpenSSL.cmake` module to also generate these targets.

cci was started in september last year, so some of your recipes might be from other sources.
Where possible, please consider upstreaming some of your recipes to cci.
This will greatly easy future migrations, and will benefit conan.

**Comment by keysight-daryl** [comment]
Our copy of OpenSSL recipe was from what the conan-center-index was pre the move to this repo.  Our Poco is the same and will probably need updated as well for the same reasons.  We have a number of other recipes though that were pulled in from whoever was contributing them at the time.  I guess the big issue here is this feature seems to make new requirements on all dependencies below it so it doesn't really support such a mixed recipe source environment.

**Comment by keysight-daryl** [comment]
It's a little disappointing to be honest as I would have hoped these things to have been worked out in a more backwards compatible way as it is causes considerable pain.

**Comment by madebr** [comment]
Indeed, conan component support is supported in conan since [1.26.0](https://docs.conan.io/en/latest/changelog.html#id142).
The recipes at conan-center-index assume an up-to-date conan version.
So to be sure you don't use any recent additions, you should use the cci master of the beginning of june 2020.
But I would advise against this, as this will bite you later.

**Comment by SpaceIm** [comment]
> 
> 
> Spot on brother, that seems to have fixed it for the paho.mqtt.c project at least now I will try again with the cpp one. Is there a way to perhaps enforce the minimum conan version on a recipe with some error message to upgrade similar to how cmake has a minimum version? Otherwise this is totally confusing. It would make sense to enforce some minimum conan version check on all recipes in here

Starting from conan 1.28, there is `required_conan_version`: https://github.com/conan-io/conan-center-index/blob/a79d9f7f0c2b61c3e137720a917313c717761720/recipes/any-lite/all/conanfile.py#L4

**Comment by keysight-daryl** [comment]
We have been nursing an in house repo of conan packages roughly mirroring that of things like cci but since years now so maintaining these projects across all these packages and internally is quite the train wreck when fundamental requirements on dependencies changes like this.  For example we need the latest paho but we don't need the latest openssl, poco, zlib, fmt, aes, ...

**Comment by keysight-daryl** [comment]
I do think if there is any way to at least standardize the cci recipes all on the minimum required conan version that would help a little to prevent just throwing random errors that makes no sense.

**Comment by Croydon** [comment]
If you mirror the versions, then you can make the active decision when to pull in new revisions and this might very well require new Conan version. If you would use CCI directly via the remote than you can use the revision feature to pin it down.

Since CCI lives from contributions, it is unreasonable to promise to support old Conan versions. We often need new features for making progress with certain recipes. Maybe that changes one day with Conan 2.0, who knows, but for the moment, the current CCI revision can only promise to support the most recent Conan version.

If you mirror many recipes into your private setup I would recommend to find a way to automate this. Also, if you pull in a new revision of one of your needed recipes, you should probably pull in new revisions for all. Otherwise they might not work together anymore as you described.

**Comment by keysight-daryl** [comment]
Right what you say sounds great in principle were it not for this being a company managed repo across dozens of teams all doing their own things about it and often forking and modifying these recipes to suit some local issues.  It would be nice to somehow have it all automated but this isn't the case unfortunately and it doesn't even seem very likely given how they are used internally.

**Comment by keysight-daryl** [comment]
The problem isn't the desire to stay latest greatest in cci the problem is in how the consumer of cci manage the reality of long term projects growing up within the ecosystem of it all and how changing standards of recipe creation can have avalanche effects on everything around it.

**Comment by Croydon** [comment]
I see. The best scenario would be, as @madebr said, to contribute back to fix those encountered issues if you are allowed to do so, then you can de-fork your recipes. If you are forking those, you are more or less on your own unfortunately and you are having much more work in the long run.

**Comment by keysight-daryl** [comment]
Right but most of those mods are entirely only useful within our company, for example we make custom hardware so the vanilla 'target' we don't have any of those.

**Comment by keysight-daryl** [comment]
Closing this issue as I have managed to sort through all the required updates and other packages that were needed to get by.  The short of the answer here is you need to be using conan 1.26 or better and you need to possibly update all requirement packages to also use this new mechanism of cmake_find_package_multi.
