### ISSUE TITLE
CPR is no longer compatible with libcurl

### ISSUE THREAD

**Issue by FohlenAFK** [conan-io/conan-center-index#3206]
The CPR package is no longer compatible with the libcurl package because the following changes: 27c119a06fc0303efa89c2d8cbbace35f32db1b6

Building CPR e.g 1.4.0 fails on this line: https://github.com/conan-io/conan-center-index/blob/7fafb4675b4af4a9af227fdb3f9d660e044a2a0a/recipes/cpr/all/conanfile.py#L39 with

```
$ conan install .. cpr/1.4.0
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=10
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
libcurl/7.71.1: WARN: with_openssl, with_winssl, darwin_ssl and with_wolfssl options are deprecated. Use with_ssl option instead.
cpr/1.4.0: WARN: OpenSSL support is not stable yet. whoshuu/cpr#31
WARN: cpr/1.4.0: requirement libcurl/7.67.0 overridden by your conanfile to libcurl/7.71.1
ERROR: option 'with_openssl' doesn't exist
Possible options are ['shared', 'fPIC', 'with_ssl', 'with_ldap', 'with_libssh2', 'with_libidn', 'with_librtmp', 'with_libmetalink', 'with_libpsl', 'with_largemaxwritesize', 'with_nghttp2', 'with_zlib', 'with_brotli']
```

because the option on this line is deleted:

https://github.com/conan-io/conan-center-index/blob/7fafb4675b4af4a9af227fdb3f9d660e044a2a0a/recipes/libcurl/all/conanfile.py#L125

**Comment by SpaceIm** [comment]
Could you provide more information? conan version? What is your conanfile? I guess that it fails only if libcurl is also a direct dependency in your own conanfile.

Maybe deprecated options should be removed in package_id, not configure.
