### ISSUE TITLE
[request] rangesnext

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/conan-center-index#3243]
### Package Details
  * Package Name/Version: **rangesnext**
  * Website: **https://github.com/cor3ntin/rangesnext**
  * Source code: **https://github.com/cor3ntin/rangesnext**

### Description Of The Library / Tool

Extensions to standard library ranges that did not make it into C++20 and that may make it into C++23.  Until C++23 is out, this library is necessary to fill in some of the gaps in the C++20 ranges library.

**Comment by tapia** [comment]
Library included on PR #5339. Thanks @wouterbeek for the suggestion.
