### ISSUE TITLE
[question] Documentation on imgui self.cpp_info.srcdirs

### ISSUE THREAD

**Issue by Hopobcn** [conan-io/conan-center-index#3251]
Reading imgui package, I noticed this:

 https://github.com/conan-io/conan-center-index/blob/e00cb6ae6df4e2124cc3287c9b4df77f8311a1ed/recipes/imgui/all/conanfile.py#L68

but apparently it's not documented here **https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info**

Any info regarding this `srcdirs`? Is this propagated somehow?

**Comment by SpaceIm** [comment]
It's documented in methods but not in attributes: https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-info

No idea on how it's propagated.

**Comment by Hopobcn** [comment]
Thanks!

**Comment by xahon** [comment]
@Hopobcn how did you "include" these headers in your code? I've stuck on that moment a bit

**Comment by xahon** [comment]
Ok, i've just copied them with
```
def imports(self):
        self.copy("*.h", "imported/imgui", "%s/bindings/" % (self.deps_cpp_info["imgui"].res_paths[0]))
        self.copy("*.cpp", "imported/imgui", "%s/bindings/" % (self.deps_cpp_info["imgui"].res_paths[0]))
```
as shown here (https://github.com/bilke/dear-imgui-conan-example/blob/78295ca0304bfac72912314fb9ed5a96bbdb4a7a/conanfile.txt)
Very weird approach
