### ISSUE TITLE
[service] Build packages for Clang 11

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#3269]
Now where conan-io/conan-docker-tools#225 is merged, the service should generate packages for Clang 11.

If added, the documentation has to be updated too: https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md

**Comment by uilianries** [comment]
Yes, but first you need tapaholes working well. The idea is a service which check what is missing and build/upload on background. Otherwise, we would need trigger all projects at once, but respecting the correct build order due the dependencies (not easy).

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/4636

Thanks!
