### ISSUE TITLE
[package] protobuf/3.11.4: needs components

### ISSUE THREAD

**Issue by Talkless** [conan-io/conan-center-index#3275]
Other libraries like Google ORTools expectes `probobuf::libprotobuf` and `protobuf:protoc` targerts. I had to patch ORTools like this to make it build with Conan-ized Protobuf:
```
        for root, _, files in os.walk(self.source_subfolder):
            for filename in files:
                if fnmatch.fnmatch(filename, "*.cmake") or filename == "CMakeLists.txt":
                    full_filename = os.path.join(root, filename)
                    tools.replace_in_file(full_filename, "protobuf::libprotobuf", "Protobuf::Protobuf", False)
                    tools.replace_in_file(full_filename, "protobuf::protoc", "protoc", False)
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **protobuf/3.11.4**
  * Operating System+version: **Debian 10 (buster)**
  * Compiler+version: **GCC 8.3.0**
  * Conan version: **conan 1.29.0**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by Croydon** [comment]
See #2037

**Comment by perseoGI** [comment]
I there!
I'm closing this issue as this has been resolved time ago.
Happy coding 🐸
