### ISSUE TITLE
How can I re-create the conan gtest package?

### ISSUE THREAD

**Issue by kobi-ca** [conan-io/conan-center-index#3281]
Hi,

How can I re-create the conan gtest package?
I'd like to recreate it with different source tgz.
what's the process for this?

thanks,
Kobi

**Comment by uilianries** [comment]
You have to manipulate the conandata.yml and change both URL and SHA256. You can't do it by conan install command, you have to download the recipe, change the file and run conan create command.

Which specific tgz do you want?

**Comment by kobi-ca** [comment]
hi @uilianries thanks for the reply. I managed to resolve it last night. Thanks!
