### ISSUE TITLE
[question] Set a general policy on library sources for recipes

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#3296]
Despite conan-center-index having general guidelines on how to contribute recipes, we still don't have any kind of policy of what recipes this repository should support. Also, we have some undocumented "rules" that we all apply to develop recipes that we should start to put together in order to help other contributors or just for the shake of the center documentation.

Mostly related to the sources of libraries, we can name some of them like:

- Recipes should build packages from library sources.
- Library sources should come from an official origin like the library source code repository or the official release/download webpage. Source forks or unofficial origin of sources are not allowed.
- In case the library sources cannot be downloaded from their official origin or cannot be consumed directly due to their format, we might consider alternative solutions for hosting or repackaging them whenever their license allows it.
- In case the library sources are not available or if it is necessary for some other reasons, we can make exceptions and package precompiled binaries in case the license of the project allows them to be redistributed.
- When packaging precompiled libraries, those should come from official sources like release/download webpages as well.

I think the above points are nothing new to everybody at this repo but we think it is good to have them as general points to follow. Any other points that should be added regarding sources?

**Comment by boussaffawalid** [comment]
@danimtb does conan-center-index allow packaging precompiled libraries ?

**Comment by SSE4** [comment]
sometimes yes, e.g. msys2 is precompiled AFAIK

**Comment by boussaffawalid** [comment]
I want to add a recipe for tensorflow however building it from source is tricky. 
Google provides pre compiled binaries for all platforms https://www.tensorflow.org/install/lang_c#download
So the question is, is that allowed ?

**Comment by danimtb** [comment]
@boussaffawalid we should be able to add a recipe that builds it from sources. I think many users will benefit from that in case they want to debug or build their own configurations

**Comment by jgsogo** [comment]
This is blocking this PR: https://github.com/conan-io/conan-center-index/pull/2850 (we need the place for those files)

**Comment by danimtb** [comment]
After talking about this with the ConanCenter maintainers we agreed on not supporting the download of sources from sites that are not the official ones and in the case of #2850, we don't want to support libraries that are not open sourcing their libraries.

I will open a PR with the updated policy from the description of this issue

**Comment by danimtb** [comment]
Proposal here https://github.com/conan-io/conan-center-index/issues/3296
