### ISSUE TITLE
[question] Repeatable code to handle fPIC

### ISSUE THREAD

**Issue by klimkin** [conan-io/conan-center-index#3297]
I see this boilerplate in almost all packages. Why not to incorporate the logic into the base class? Delete `fPIC` if option exists and:
* Windows OS
* `shared` option exists and set

~~~python
    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            del self.options.fPIC
~~~

**Comment by uilianries** [comment]
That's not a bad idea, as most of recipes follow it, but it would break Conan behavior. We could consider for Conan 2.0. Could you please move this issue to conan-io/conan ? Here is only related to CCI recipes, not Conan client.

**Comment by klimkin** [comment]
Moved to https://github.com/conan-io/conan/issues/7931
