### ISSUE TITLE
[package] catch2/2.13.2: unable to install or download

### ISSUE THREAD

**Issue by PinkySan** [conan-io/conan-center-index#3302]
Even if the package can be found by `conan search catch2 -r conan-center` the package cannot be downloaded. Conan is a header only library, therefore i do not expect it to address issues regarding the compiler or the os

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **catch2/2.13.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 16**
  * ~Docker image: **conanio/gcc8**~
  * Conan version: **conan 1.30.2**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```
[requires]
catch2/2.13.2

[generators]
cmake_paths
```
or 
`conan download catch2/2.13.2 --remote conan-center`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: Requested 'catch2/2.13.2' but found case incompatible 'Catch2'
Case insensitive filesystem can't manage this
```

</details>

**Comment by Croydon** [comment]
As the error message says you are having a different case package of Catch2 installed  (probably `Catch2`) and Windows can't handle this

You have to remove the different cased package first, before you can install the lower case package

**Comment by PinkySan** [comment]
i do not have any package at all. Already cleaned up my whole cache
`conan remove -f *`

After that i`ve seen, that there still was an folder within the cache, which i had to delete manually. 

After that it worked. Thank you really much, @Croydon 
Your hint was the key
