### ISSUE TITLE
[package] ceres-solver/1.14.0: include folder missing when using internal miniglog

### ISSUE THREAD

**Issue by ThomasHauth** [conan-io/conan-center-index#3319]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ceres-solver/1.14.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9.3**
  * Conan version: **conan 1.30.2**
  * Python version: **Python 3.8.5**

### Conan profile
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```
### Steps to reproduce (Include if Applicable)
If the flag use_glog=False (which is the default) the miniglog header distributed with the ceres source are used instead of an external glog library. The ceres CMakeLists sets the include folder to minilog in order to use this internal version:

```
...
if (MINIGLOG)
  message("-- Compiling minimal glog substitute into Ceres.")
  set(GLOG_INCLUDE_DIRS internal/ceres/miniglog)
...
```
This include path also needs to be set for the ceres conan package, otherwise a build using the ceres package with use_glog=False will result in this error:

```
 In file included from <...>/.conan/data/ceres-solver/1.14.0/_/_/package/658ec09d0d450b9034a9b299908f1ed5dd82c9fb/include/ceres/internal/autodiff.h:147,
                 from <...>/.conan/data/ceres-solver/1.14.0/_/_/package/658ec09d0d450b9034a9b299908f1ed5dd82c9fb/include/ceres/autodiff_cost_function.h:132,
                 from <...>/.conan/data/ceres-solver/1.14.0/_/_/package/658ec09d0d450b9034a9b299908f1ed5dd82c9fb/include/ceres/ceres.h:37,
                 from <...>.cpp:3:
<...>/.conan/data/ceres-solver/1.14.0/_/_/package/658ec09d0d450b9034a9b299908f1ed5dd82c9fb/include/ceres/internal/fixed_array.h:39:10: fatal error: glog/logging.h: No such file or directory
   39 | #include "glog/logging.h"
      |          ^~~~~~~~~~~~~~~~
```

Please note that this error will not occur if a system glog is installed because the system headers for glog will silently be picked-up.

I have created a branch with a possible fix for the ceres conan package:

https://github.com/ThomasHauth/conan-center-index/commit/8ed668915aa2a7d546b309532815e0972be98150

and can create a PR with these changes if this is the way to go.

Thanks !

**Comment by prince-chrismc** [comment]
this can be closed since ur PR was merged!
