### ISSUE TITLE
[bug] provides doesn't allow for package conflicts

### ISSUE THREAD

**Issue by Renari** [conan-io/conan-center-index#3330]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linuxmint 20 ulyana
  * Compiler+version: gcc 9
  * Conan version: 1.30.2
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)
Set conanfile.txt to include dependencies for `qt/5.14.1@bincrafters/stable`, `opencv/3.4.5@conan/stable` and `libjpeg-turbo/2.0.5`. `libjpeg-turbo` says that it provides `libjpeg` however the version mismatch between `qt` and `opencv` requires you put `libjpeg` in your conanfile.txt. This check should also check if another library provides `libjpeg` and treat that as a resolution between the conflict.

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
ERROR: Conflict in qt/5.14.1@bincrafters/stable:
    'qt/5.14.1@bincrafters/stable' requires 'libjpeg/9d' while 'opencv/3.4.5@conan/stable' requires 'libjpeg/9c@bincrafters/stable'.
    To fix this conflict you need to override the package 'libjpeg' in your root package.
```

**Comment by jgsogo** [comment]
You can find more comments about this issue in [this PR](https://github.com/conan-io/conan-center-index/pull/2730#issuecomment-693193451). The `provides` feature should be used only for recipes that are incompatible in the same graph (ODR violation, linking issues). 

Previous efforts have added an option `"jpeg": [False, "libjpeg-turbo", "libjpeg"],` to these recipes, so you can choose the requirement to consume per recipe and fix the conflict this way. Not sure if the recipes you are consuming provide these options or not. I also think that the approach using the _proxy_/_abstract_ recipe would be more maintainable in the long-term, but it doesn't exist yet in ConanCenter.

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/2948 aims to provide a virtual libjpeg recipe, so that all others recipes depending on libjpeg could require this virtual package and solve this issue. Then consumers would just have to select libjpeg implementation (libjpeg, libjpeg-turbo or mozjpeg) through libjpeg virtual package option.

Unfortunately, there is currently no progress in this PR.

**Comment by Croydon** [comment]
> That is, you might want to use https://conan.io/center/opencv package, which will be opencv/4.3.0, without the conan/stable part.

FYI, openvc/4.3.0 is not yet in CCI. This is a bug in the online UI which is not displaying username/channel anymore, see also https://github.com/conan-io/conan-center-index/issues/3360
