### ISSUE TITLE
[conan.io/center] CAF recipe appears to be caf/0.17.6@ but only caf/0.17.6@bincrafters exists in conan-center repo

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan-center-index#3360]
When you search for `caf` in Conan Center everything in the UI makes it appear that the reference is a regular Conan Center reference without user/channel.  For example:
```
All Available Versions:
caf/0.17.6       Revisions (1)
caf/0.17.3       Revisions (1)
caf/0.17.0       Revisions (1)
```
But when if you search for `caf` in the `conan-center` repo only `bincrafters/stable` references are returned:
```
$ conan search -r conan-center caf
Existing package recipes:

caf/0.15.5@bincrafters/stable
caf/0.15.6@bincrafters/stable
caf/0.15.7@bincrafters/stable
caf/0.16.0@bincrafters/stable
caf/0.16.1@bincrafters/stable
caf/0.16.3@bincrafters/stable
caf/0.17.0@bincrafters/stable
caf/0.17.3@bincrafters/stable
caf/0.17.6@bincrafters/stable
```

We did want to get CAF into Conan Center proper - I forgot where we were with that.

**Comment by madebr** [comment]
Indeed, the [recipe in conan-center is from bincrafters](https://conan.io/center/caf?version=0.17.6&tab=recipe).

**Comment by Croydon** [comment]
This is a general UI bug. The website does not seem to display any username/channel anymore

**Comment by prince-chrismc** [comment]
![image](https://user-images.githubusercontent.com/16867443/207727927-61bb3796-f684-45ba-8dd6-1d782f8a82ae.png)

Since this was added https://github.com/conan-io/conan-center-index/blob/master/recipes/caf/all/conanfile.py I can only see the one CCI so I will mark this as closed. Feel free to open if you find a new one
