### ISSUE TITLE
[service] Missing packages on conan-center

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#3365]
Just ran into this problem again, figured I'd open an issue for it.

```
$ conan search -r conan-center -rev spdlog/1.8.1@
Revisions for 'spdlog/1.8.1' at remote 'conan-center':

$ conan search -r conan-center -rev spdlog/1.8.0@
Revisions for 'spdlog/1.8.0' at remote 'conan-center':
a4a3e8f6f3cd5b62992585ca9eb50dfc (2020-09-07 16:09:40 UTC)
```

_Originally posted by @prince-chrismc in https://github.com/conan-io/conan-center-index/pull/3055#issuecomment-702461845_

**Comment by jgsogo** [comment]
Having a look at the commit history, it doesn't show the check for [that commit](https://github.com/conan-io/conan-center-index/commits/master?after=2ef3776b65dd896d96fafc18a553d6e5eb5ef358+209&branch=master) 😕 

![image](https://user-images.githubusercontent.com/1406456/98098967-4a431900-1e8f-11eb-82b2-779d618fbbd1.png)

It was not notified by Github and it didn't run in the CI.

We are now preparing a job to test that all the revisions corresponding to the latest commit are uploaded to ConanCenter, that job will run daily and it would solve this kind of issue. Right now the easiest way to fix it is to create a new PR for that version.

**Comment by prince-chrismc** [comment]
I might not of been the only one 
![image](https://user-images.githubusercontent.com/16867443/98118589-72278200-1e79-11eb-8acc-c855890e4a6a.png)

**Comment by prince-chrismc** [comment]
Service disruptions are normal on the internet
