### ISSUE TITLE
[package] poco/1.9.4: Windows build fails on expat/2.2.10 dependency

### ISSUE THREAD

**Issue by paul-reilly** [conan-io/conan-center-index#3379]
I am following the [Getting Started example](https://docs.conan.io/en/latest/getting_started.html#an-md5-hash-calculator-using-the-poco-libraries) on Windows 10, using MSVC, but the `poco/1.9.4` build is failing on the `expat/2.2.10` dependency. Here is the error:
```
ERROR: Failed requirement 'expat/2.2.10' from 'poco/1.9.4'
ERROR: Requested 'expat/2.2.10' but found case incompatible 'Expat'
Case insensitive filesystem can't manage this
```
I have pasted the output of the `conan install ..` command below.

### Profile/Command + Output 
<details><summary>Click to expand profile/command + output</summary>

```
➜  build conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

poco/1.9.4: Not found in local cache, looking in remotes...
poco/1.9.4: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.59k]
Downloading conanfile.py completed [11.04k]
Downloading conan_export.tgz completed [0.30k]
Decompressing conan_export.tgz completed [0.00k]
poco/1.9.4: Downloaded recipe revision 0
ERROR: Failed requirement 'expat/2.2.10' from 'poco/1.9.4'
ERROR: Requested 'expat/2.2.10' but found case incompatible 'Expat'
Case insensitive filesystem can't manage this
```

</details>

**Comment by Croydon** [comment]
You have to remove the uppercase `Expat` first in order to install the lowercase `expat`

@jgsogo @danimtb IMHO, we are getting way too many bug reports of people who are confused about this message. Maybe the message needs to get improved somehow?

**Comment by paul-reilly** [comment]
Okay thanks, so there's an `expat` package and an `Expat` package which must have been installed with one of the packages I'd previously tried installing.

That's `Expat` removed, but the poco package build is now failing on `sqlite3/3.33.0` (which I have removed and tried reinstalling):
```
ERROR: sqlite3/3.33.0: Error in package_info() method, line 128
        self.cpp_info.filenames["cmake_find_package"] = "SQLite3"
        TypeError: '_CppInfo' object does not support item assignment
```

**Comment by Croydon** [comment]
Your Conan version is too old, please update if you can

**Comment by paul-reilly** [comment]
That's the one, all working now thanks!

**Comment by jgsogo** [comment]
> You have to remove the uppercase `Expat` first in order to install the lowercase `expat`
> 
> @jgsogo @danimtb IMHO, we are getting way too many bug reports of people who are confused about this message. Maybe the message needs to get improved somehow?

Maybe @paul-reilly can suggest a better message, something he would have found more useful.

**Comment by paul-reilly** [comment]
He he, happy to share my startled rabbit stage wisdom!

Well I didn't even consider that there were two packages with the same name, except for a capital letter. Wasn't on the radar at all so maybe something that makes it explicit that it's a package. Looking back, "Expat" is the only package mentioned without a version number too. Maybe something like:

```
ERROR: Requested 'expat/2.2.10' but case incompatible package 'Expat/6.6.6' is already installed
Case insensitive filesystem can't manage this. To retry, please uninstall the case incompatible package.
```

?
