### ISSUE TITLE
[request] libheif/1.9.1 [WIP]

### ISSUE THREAD

**Issue by theirix** [conan-io/conan-center-index#3388]
### Package Details
  * Package Name/Version: **libheif/1.9.1**
  * Website: **https://github.com/strukturag/libheif**
  * Source code: **https://github.com/strukturag/libheif**

### Description Of The Library / Tool

libheif is an HEIF and AVIF file format decoder and encoder.

Packaging in progress.

**Comment by SpaceIm** [comment]
Requires https://github.com/conan-io/conan-center-index/pull/3385
