### ISSUE TITLE
[service] List all available packages on the conan center website 

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan-center-index#339]
A search form is not enough.

Please add a list all available modules in conan center directly on the website
like it is done here:
https://cpp.libhunt.com
So I can scroll through all libraries and maybe find something which might be interesting for me to use.

**Comment by Croydon** [comment]
The UI could be better, but https://bintray.com/conan/conan-center is working

What do you think?

**Comment by memsharded** [comment]
Yes, something like https://bintray.com/beta/#/conan/conan-center?tab=packages in the new UI would make sense. Probably adding the descriptions of the packages too.

As a plus, navigation of packages per topic would also probably be interesting (but very low priority)

**Comment by derived-coder** [comment]
The search in bintray was always a little bit strange for me. E.g. I cannot find qt with it.
Having a category list (serialization, Network, UI, etc..) would be very helpful too

**Comment by derived-coder** [comment]
any update on this issue? The landing page looks very empty: https://conan.io/center
with such a grouping it would invite to try out new libraries.

**Comment by danimtb** [comment]
https://conan.io/center but it will be improved over time. Thanks for the suggestion!

**Comment by uilianries** [comment]
You can use https://conda-forge.org/feedstocks/ as reference. Each package in the list is a link to the package info.

**Comment by Dattax** [comment]
This is on the roadmap for this quarter and will be released by the end of June. We are just starting to look at the best UI/display for this.

**Comment by derived-coder** [comment]
Here you can see what the competitors are doing so far:
https://vcpkg.info/
https://vcpkgx.com/

This tags option is quite handy. I guess it should be available also in the conan recipe already.
Scrolling through all recipes it also very nice experience IMHO, instead of an empty white landing page.

**Comment by Dattax** [comment]
This page has been added and will continue to evolve: https://conan.io/center/allpackages

**Comment by danimtb** [comment]
You can reach that page by clicking here in the main www.conan.io/center web page:

![image](https://user-images.githubusercontent.com/10808592/95485575-3b516f80-0992-11eb-8e77-3cbfaff18c65.png)

**Comment by claremacrae** [comment]
> You can reach that page by clicking here in the main [www.conan.io/center](http://www.conan.io/center) web page:
> 
> ![image](https://user-images.githubusercontent.com/10808592/95485575-3b516f80-0992-11eb-8e77-3cbfaff18c65.png)

It's good to know what that button does - I must admit I had not noticed it, and would not have guessed it...

But, as you say, the page does exist, so maybe you want to close this ticket?
