### ISSUE TITLE
[question] Should we export the recipe's license?

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#34]
Hi!

Before Conan-Center Index, we had a license for each recipe repository.
However, now we have only one main license (MIT).

The question is, should we export it? We would need to use a relative path I think:

    exports = "../../../LICENSE"

/cc @SSE4 @Croydon

Regards!

**Comment by Croydon** [comment]
I think we should continue to export the license. Having the same license file everywhere is kinda pointless, so I guess using relative paths is the best approach.

**Comment by danimtb** [comment]
Hi!

Discussing this issue, we feel that adding the same license for all the recipes having a root license in this repo is a bit pointless too. If there is a license in the root it means that the whole contents of this repo are under that license.

Probably we will need to specify so in the license file or in the repo readme.

Meanwhile, we have added this question to the FAQ: https://github.com/conan-io/conan-center-index/wiki/FAQ#should-recipes-export-a-recipes-license

**Comment by Croydon** [comment]
> Discussing this issue, we feel that adding the same license for all the recipes having a root license in this repo is a bit pointless too.

From the perspective of this repository, sure. However, as soon as you export the Conan recipe there is no more repository to look at, therefore no license whatsoever

**Comment by danimtb** [comment]
Also, this will mean that a new file is exported for all the recipes and a new download and decompress will be triggered. Additionally, using the relative maths will make more difficult to use this recipe outside of this repo as the parent dirs will make no sense

**Comment by danimtb** [comment]
I am closing this issue considering it has been answered in the FAQ. Thanks!
