### ISSUE TITLE
[request] embree/3.12.0

### ISSUE THREAD

**Issue by KaoCC** [conan-io/conan-center-index#343]
### Package Details
  * Package Name/Version: **embree/3.12.0**
  * Website: **https://www.embree.org/**
  * Source code: **https://github.com/embree/embree**

### Description Of The Library / Tool
Intel® Embree is a collection of high-performance ray tracing kernels, developed at Intel. The target users of Intel® Embree are graphics application engineers who want to improve the performance of their photo-realistic rendering application by leveraging Embree's performance-optimized ray tracing kernels. The kernels are optimized for the latest Intel® processors with support for SSE, AVX, AVX2, and AVX-512 instructions.

Please note that I already have a personal working recipe in my repository in [here](https://github.com/KaoCC/conan-packages/tree/master/embree/embree)

I'm willing to support the integration if approved and needed.

**Comment by Croydon** [comment]
Your recipe needs some smaller updates but looks pretty solid, I would say go ahead and create a pull request 😄

**Comment by KaoCC** [comment]
Thanks. A PR is created 😄

**Comment by KaoCC** [comment]
Note: upgraded to 3.12.0
