### ISSUE TITLE
[package] libuuid/1.0.3: Does not produce the correct cmake file or target

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#3441]
Currently the package info is very minimal:

https://github.com/conan-io/conan-center-index/blob/24311c41e61a428eb20c6b715e14ce6e420fbbe9/recipes/libuuid/all/conanfile.py#L64-L66

From the official [cmake module](https://gitlab.kitware.com/cmake/cmake/blob/e1409101c99f7a3487990e9927e8bd0e275f564f/Source/Modules/FindLibUUID.cmake) it's `FindLibUUID.cmake`

>Imported Targets
>^^^^^^^^^^^^^^^^
>
>An :ref:`imported target <Imported targets>` named
>``LibUUID::LibUUID`` is provided if LibUUID has been found.

**Comment by SpaceIm** [comment]
I don't see this module file in CMake documentation nor in installation folder of CMake.

**Comment by madebr** [comment]
@prince-chrismc 
That `FindLibUUID.cmake` file you're referring to is only used while building CMake.
[Its directory](https://gitlab.kitware.com/cmake/cmake/-/tree/e1409101c99f7a3487990e9927e8bd0e275f564f/Source/Modules) contains some external dependencies of CMake.
[The root /Modules folder](https://gitlab.kitware.com/cmake/cmake/-/tree/e1409101c99f7a3487990e9927e8bd0e275f564f/Modules) contains all modules that are installed. I can't find `uuid` in this folder.

**Comment by prince-chrismc** [comment]
That's very interesting... google might be fouling me but it's the top result 🤔  
![Screenshot_20201107-153058_Chrome](https://user-images.githubusercontent.com/16867443/98450867-630d3200-210e-11eb-8a70-1b4e9f927f2e.jpg)

**Comment by madebr** [comment]
And the first response on the vcpkg issue says to use `find_library` instead of `find_package`.

- libuuid only installs a `uuid.pc` file.
- [FindLibUUID.cmake on the cmake doc site (currently) returns a 404](https://cmake.org/cmake/help/git-master/module/FindLibUUID.html) (or cannot be found at [cmake-modules](https://cmake.org/cmake/help/git-master/manual/cmake-modules.7.html))
