### ISSUE TITLE
[request] opencascade/7.5.0

### ISSUE THREAD

**Issue by mnesarco** [conan-io/conan-center-index#3450]
### Package Details
  * Package Name/Version: **opencascade/7.5.0**
  * Website: **https://www.opencascade.com/open-cascade-technology/**
  * Source code: **https://old.opencascade.com/content/latest-release**

### Description Of The Library / Tool
Open CASCADE Technology (OCCT) is a world-known 3D modeling kernel, freely available in open source. It's a software development kit (SDK) intended for the development of applications dealing with 3D CAD data. OCCT includes a set of C++ class libraries providing services for 3D surface and solid modeling, visualization, data exchange and rapid application development.

**Comment by madebr** [comment]
The source package cannot be downloaded without an account.

**Comment by mnesarco** [comment]
Hi @madebr, 
This github repo is the official mirror: https://github.com/Open-Cascade-SAS/OCCT

**Comment by mnesarco** [comment]
Hi Friends, I know you are very busy maintaining this amazing conan index, but is it any progress with OpenCascade package?

**Comment by fjcp** [comment]
Hi, I have also a lot of interest in this product. Thank you

**Comment by SpaceIm** [comment]
The recipe in https://github.com/conan-io/conan-center-index/pull/4094 is functional, but fot the moment I think there is an issue in Visual Studio agents preventing to build all configurations.

**Comment by Croydon** [comment]
Done via #4094

**Comment by taoyouh** [comment]
The package is already usable and the issue can be closed.
