### ISSUE TITLE
[package] icu/64.2: Cross compilation fails

### ISSUE THREAD

**Issue by Forbinn** [conan-io/conan-center-index#3461]
### Package and Environment Details
  * Package Name/Version: **icu/64.2**
  * Docker image: **conanio/gcc7-armv8**
  * Conan version: **conan 1.29.2**

### Conan profile
```
+-----------------------------+
| Profile                     |
|-----------------------------|
| include(default)            |
|                             |
| [settings]                  |
| arch=armv8                  |
| build_type=Release          |
| compiler=gcc                |
| compiler.libcxx=libstdc++11 |
| compiler.version=7          |
| [options]                   |
|                             |
| [env]                       |
|                             |
| [build_requires]            |
+-----------------------------+
```

### Steps to reproduce

In my case ICU was compiled because it is a dependency of `qt/5.15.0@bincrafters/stable` package.
I'm cross-compiling qt using official conanio docker images (and conan package tools) and the build fails due to a missing option on the ICU package.

I'm unsure if I need to report this here or a the qt package. But regarding the error I assume here was the best.

### Logs
<details><summary>Click to expand log</summary>

```
icu/64.2: Configuring sources in /home/conan/.conan/data/icu/64.2/_/_/source
icu/64.2: Copying sources to build folder
icu/64.2: Building your package in /home/conan/.conan/data/icu/64.2/_/_/build/9c95a360e2ee4af85650c60ccf5861cf5929e74d
icu/64.2: Generator txt created conanbuildinfo.txt
icu/64.2: Calling build()
export CPP= CC=gcc CXX=g++ CPPFLAGS=-DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=1 CFLAGS=-O3 -O3 -s CXXFLAGS=-O3 -O3 -s LDFLAGS= MAKE=
Running ./configure  --prefix=/home/conan/.conan/data/icu/64.2/_/_/package/9c95a360e2ee4af85650c60ccf5861cf5929e74d --with-library-bits=64 --disable-samples --disable-layout --disable-layoutex --disable-extras --build=x86_64-linux-gnu --host=aarch64-linux-gnu --with-data-packaging=archive --datarootdir=/home/conan/.conan/data/icu/64.2/_/_/package/9c95a360e2ee4af85650c60ccf5861cf5929e74d/lib --sbindir=/home/conan/.conan/data/icu/64.2/_/_/package/9c95a360e2ee4af85650c60ccf5861cf5929e74d/bin --disable-static --enable-shared --disable-tests for Linux using the GNU C++ compiler
checking for ICU version numbers... release 64.2, library 64.2, unicode version 12.1
checking build system type... x86_64-pc-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking whether to build debug libraries... no
checking whether to build release libraries... yes
checking for aarch64-linux-gnu-clang... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for aarch64-linux-gnu-pkg-config... /usr/bin/aarch64-linux-gnu-pkg-config
checking pkg-config is at least version 0.20... yes
checking for ICULEHB... no
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for python3... python3
checking for gmake... no
checking for gnumake... no
configure: error: Error! Cross compiling but no --with-cross-build option specified - please supply the path to an executable ICU's build root
../source/runConfigureICU: ./configure failed
icu/64.2: 
```

</details>

**Comment by Mightrider** [comment]
Hey Forbinn, I ran into the same problem. Did you come up with a workaround?

**Comment by Forbinn** [comment]
Hi @Mightrider. Unfortunately no, for the moment I compiled without using the docker image, directly on device to avoid the cross-compile flag issue. This is far from ideal because it takes a very long time for some project.

**Comment by Mightrider** [comment]
That's to bad. 
I managed to add the `--with-cross-build` option by modifing the conanfile.py but only with an hardcoded path to the x86_64 build dir.
I did not manage to build the x86_64 build inside the recipe...

**Comment by nichmj01** [comment]
I ran into this problem yesterday with icu/68.2 and ended up just compiling on the device and uploading the build packages. I tried to get the --with-cross-build options working in a custom recipe but I couldn't get it working right away and decided to build on device to be able to make progress.

**Comment by cguentherTUChemnitz** [comment]
I ran into this problem as well using clang aarch64-linux-gnu triplet to cross compile for raspberry pi 4. This is really sad, since it is a dependency of boost and this is the last one holding me back from getting my project ready for raspberry cross-compilation.

**Comment by perseoGI** [comment]
Hi there!
Sorry to catch up this late, I was reviewing old issues and found this one!
`icu/64.2` version is no longer supported by CCI.
In the other hand, cross compiling issues have been already addressed.
See some updated compilation logs:

```
$  conan install --requires icu/75.1 --build=missing -c tools.build.cross_building:cross_build=True
======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos
[conf]
tools.build.cross_building:cross_build=True

...
[100%] Built target test_package

======== Testing the package: Executing test ========
icu/75.1 (test package): Running test()
```

If for some reason the problem persists, do not hesitate to open a new ticket with up to dated information.
Happy coding 🐸
