### ISSUE TITLE
[service] Add xcode 12.0

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#3463]
As of 9NOV2020, [xcode 9.1, 10.0 and 11.0 are built and tested by c3i](https://github.com/conan-io/conan-center-index/blob/337f0cdc5cc51a3e2c66bb7bcc013ff1cff57d7e/docs/supported_platforms_and_configurations.md#macos).

But I just found a bug with problems with xcode 12.0: https://github.com/conan-io/conan-center-index/issues/3008
More will probably follow

So I think it may be worth it to add xcode 12.0 to the test matrix.

([gcc 10](https://github.com/conan-io/conan-center-index/issues/1587) is also missing)

**Comment by danimtb** [comment]
These configurations are already built by the service. Thanks
