### ISSUE TITLE
[package] openexr/all: CMake generators does not reflect installed config files and targets

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#3464]
Yes, this recipe needs Conan components but it can't be fully modeled on CMake side because two config files should be generated, with two different namespaces:

`OpenEXRConfig.cmake`: `OpenEXR::IlmImfConfig`, `OpenEXR::IlmImf`, `OpenEXR::IlmImfUtil`
`IlmBaseConfig.cmake`: `IlmBase::IlmBaseConfig`, `IlmBase::Half`, `IlmBase::Iex`, `IlmBase::IexMath`, `IlmBase::Imath`, `IlmBase::IlmThread`

_Originally posted by @SpaceIm in https://github.com/conan-io/conan-center-index/pull/3454#issuecomment-723994868_

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openexr/1.2.8**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.30.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
https://c3i.jfrog.io/c3i/misc/logs/pr/3454/1/openexr/2.5.3/10ebe76393760b5ddd19f7b1726da594a3050f23/profile.txt

### Steps to reproduce (Include if Applicable)
_CI is sufficient_

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

https://c3i.jfrog.io/c3i/misc/logs/pr/3454/1/openexr/2.5.3/10ebe76393760b5ddd19f7b1726da594a3050f23/create_stdout.txt

</details>

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/9887 doesn't fix openexr < 3
