### ISSUE TITLE
[bug] curl.exe linking fail on windows/gcc/shared

### ISSUE THREAD

**Issue by bialasjaroslaw** [conan-io/conan-center-index#3475]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Pro 64bit
  * Compiler+version: g++ (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
  * Conan version: 1.31.0
  * Python version: 3.9.0

### Steps to reproduce (Include if Applicable)
> conan install libcurl/7.73.0@ -s compiler=gcc -s compiler.libcxx=libstdc++11 -s compiler.version=8.1 -s compiler.exception=seh -s compiler.threads=posix -o libcurl:shared=True --build=missing

### Logs (Executed commands with output) (Include/Attach if Applicable)

At the end of building stage:

>   CCLD     curl.exe
curl-slist_wc.o:slist_wc.c:(.text+0xd): undefined reference to `__imp_curl_slist_append'
curl-slist_wc.o:slist_wc.c:(.text+0x6e): undefined reference to `__imp_curl_slist_free_all'
curl-slist_wc.o:slist_wc.c:(.text+0x92): undefined reference to `__imp_curl_slist_free_all'
curl-tool_cb_dbg.o:tool_cb_dbg.c:(.text+0x164): undefined reference to `__imp_curl_msnprintf'

~260 lines more of this

Build without shared libraries on is Ok, so it might be related to symbol visibility

**Comment by SpaceIm** [comment]
In libcurl recipe, there is a comment:

```python
        # patch autotools files
        # for mingw builds - do not compile curl tool, just library
        # linking errors are much harder to fix than to exclude curl tool
```

Maybe some modifications in upstream build files invalidate this patch and require different modifications to avoid build of curl.exe if mingw.

**Comment by bialasjaroslaw** [comment]
I dig up little more and I found out that all object files are built with dynamic library mangling but as it is shown below static library is linked instead. There is no dynamic library in any of build directories, so it might be an issue with receipe itself as @memsharded mentioned.

> libtool: link: gcc -Werror-implicit-function-declaration -O2 -Wno-system-headers -o .libs/curl.exe curl-slist_wc.o curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_filetime.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_progress.o curl-tool_strdup.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeout.o curl-tool_writeout_json.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-nonblock.o ../lib/curl-warnless.o ../lib/curl-curl_ctype.o ../lib/curl-curl_multibyte.o ../lib/curl-version_win32.o ../lib/curl-dynbuf.o  -L/c/users/admin/.conan/data/zlib/1.2.11/_/_/package/9199c3934c4d90a3a182a8dfe3ee7ece16613625/lib/lib -L/c/users/admin/.conan/data/openssl/1.1.1h/_/_/package/9199c3934c4d90a3a182a8dfe3ee7ece16613625/lib ../lib/.libs/libcurl.a -lssl -lcrypto -lcrypt32 -lgdi32 -lz -lws2_32
