### ISSUE TITLE
[question] Do the header only libraries need to specify settings?

### ISSUE THREAD

**Issue by anagno** [conan-io/conan-center-index#3482]
Hello Everyone, 

I noticed in the [eigen recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/eigen/all/conanfile.py#L13) that we are specifying settings. Eigen (i think) is a header only library. Why do we need to specify settings? In general, what settings should be specified in a header only library?

KR,
Vasileios

**Comment by intelligide** [comment]
Some settings can be required for header-only. For example, [eigen need to check the os](https://github.com/conan-io/conan-center-index/blob/master/recipes/eigen/all/conanfile.py#L44). But "compiler", "build_type" and "arch" aren't needed.

**Comment by anagno** [comment]
Thanks for the info! I thought that was the case too. I open a PR to remove the unnecessary settings :)
