### ISSUE TITLE
[service] Potentially conflicting recipes

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-center-index#3517]
The following table lists all the pull requests modifying files belonging to the same recipe.
It is automatically generated by https://github.com/ericLemanissier/conan-center-conflicting-prs so don't hesitate to report issues/improvements there.
| Library | Pull requests |
| --- | --- |
| boost | #3522, #3362, #3205, #2842, #2657, #2097, #1925, #1704 |
| cose-c | #3569, #1314 |
| gettext | #2969, #1424 |
| glib | #2925, #2867 |
| libxml2 | #3080, #2714 |
| netcdf | #3350, #2060 |
| open62541 | #1856, #1687 |
| opencv | #3465, #3409 |
| openssl | #3367, #2054 |
| pybind11 | #3545, #3305 |

The following pull requests modify several recipes, so they were ignored:
| Pull request | Libraries |
| --- | --- |
| #3282 | coz, libelfin |

**Comment by ericLemanissier** [comment]
this is much inspired by @qchateau 's https://github.com/conan-io/conan-center-index/issues/3470 and https://github.com/qchateau/conan-center-bot. Thanks for giving me the kick I needed to implement this idea which floated in my head for months!

**Comment by jgsogo** [comment]
Thanks! This will be really useful. I think we should ping this issue (and #3470) but we need to unpin some others... shall we create an index-like issue to these other ones (updatable recipes, conflicting PRs and hooks validation)? wdyt @danimtb

**Comment by SSE4** [comment]
IMO this is not necessarily an issue, as changing the same recipe doesn't necessarily result in conflict - PRs may change different files in the recipe or different lines of the file in the recipe, which is totally okay

**Comment by ericLemanissier** [comment]
Yes, most of the recipes signaled here are probably not "real" conflicts according to git's definition. Still I find int very interesting to know which PRs are in flight on a library, because sometimes a PR supersedes another (some "Fix hooks" PRs can be already handled in another PR, there can be several version bump PRs etc.)
eg in my closed non merged PRS: #3258 #2862 #2766 #2760

**Comment by madebr** [comment]
@ericLemanissier 
Nice tool!
#3452 makes it unusable though, because it modifies multiple recipes.
Would it be possible to ignore *illegal* PR's?

**Comment by ericLemanissier** [comment]
currently the list is not ordered, but I'll order it by library name. You are right that illegal recipes should not interfere with legal recipes. I'll remove them the main table.

**Comment by ericLemanissier** [comment]
ownership transferred to @ericLemanissierBot #3571
