### ISSUE TITLE
[service] md5 not supported in conandata.yml

### ISSUE THREAD

**Issue by PierreRamoin** [conan-io/conan-center-index#355]
Hi,
I'm currently working on a recipe, but as I tried to add the md5 checksum in my ```conandata.yml```, the hook throw an error as "md5" in not accepted:
```
ERROR: [CONANDATA.YML FORMAT (KB-H030)] Additional entry ['md5'] no
t allowed in 'sources':'10.1_2' of conandata.yml (https://github.com/conan-io/conan-center-index/wiki/Erro
r-Knowledge-Base#KB-H030)
```
But the wiki says:
```
You must specify one or more checksums, being also valid md5, sha1 or sha256
```
Is it a bug or did you remove the support and not updated the wiki?

Thanks,
Cheers,
Pierre

**Comment by uilianries** [comment]
Hi @PierreRamoin !

You found a bug in our Wiki, thanks for reporting. The preferred format is sha256 because is safer than md5. Please, update the checksum to SHA-256

**Comment by PierreRamoin** [comment]
Ok thanks.
As the maintainer is providing a md5, it would be easier (and safer as it's the provider checksum), but ok, I'll compute the SHA256

**Comment by uilianries** [comment]
Done, the Wiki has been updated.

**Comment by uilianries** [comment]
> As the maintainer is providing a md5, it would be easier (and safer as it's the provider checksum), but ok, I'll compute the SHA256

I see, but all packages are using sha256, so it works like a "pattern", which helps when reviewing

**Comment by PierreRamoin** [comment]
ok, thanks for the feedback ;)

**Comment by danimtb** [comment]
Actually I think the hook is a little bit restrictive and we could check for a mandatory sha256 and leave md5 and sha1 as optional fields. WDYT?

**Comment by SSE4** [comment]
now md5 and sha1 fields are allowed (with https://github.com/conan-io/hooks/commit/e6e278f5b5ad4334fb420b084ff1e39ee7972797)
