### ISSUE TITLE
[package] cjson/1.7.14: Does not copy cJSON_Utils.h to the include directory.

### ISSUE THREAD

**Issue by dertuxmalwieder** [conan-io/conan-center-index#3559]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cjson/1.7.14**
  * Operating System+version: **macOS 11.0.1**
  * Compiler+version: **Apple clang version 12.0.0 (clang-1200.0.32.21)**
  * Conan version: **conan 1.32.0-dev**
  * Python version: **Python 3.8.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Add cJSON to a C project with a Conan file:

```
[build_requires]
cjson/1.7.14

[generators]
cmake_find_package
cmake_paths

[options]
cjson:shared=True
```

Then try to use `cjson/cJSON.h` and `cjson/cJSON_Utils.h`:

```c
#include "cjson/cJSON.h"
#include "cjson/cJSON_Utils.h" /* for sorting */

/* Some code here that uses it */
```

Find that Conan has lost half of the files:

```
fatal error: 'cjson/cJSON_Utils.h' file not found
```

Which is surprising because both files exist in `source_subfolder`:

```
./source/source_subfolder/cJSON.h
./source/source_subfolder/cJSON_Utils.h
```

Yet, only `cJSON.h` is copied to the include directories. Looks like a bug to me.

**Comment by prince-chrismc** [comment]
It seems the recipe is missing an option 🤔 

https://github.com/DaveGamble/cJSON/blob/2f6fc7f0f28b4dab68a3d7fcf447beabefd04afb/CMakeLists.txt#L172

https://github.com/conan-io/conan-center-index/blob/2ee5f4615f91454f3ec2a00a0a28642bc5044de6/recipes/cjson/all/conanfile.py#L15-L19

**Comment by dertuxmalwieder** [comment]
That could be the reason. Can I fix that locally or will the maintainer have to be notified?

**Comment by prince-chrismc** [comment]
> Can I fix that

💯 feel free to open a PR to close this! Link the PR and are a reviewer Ill do my best to help!

**Comment by dertuxmalwieder** [comment]
I’ll need to investigate how Conan packaging works first. Give me some time ;-)...

**Comment by SpaceIm** [comment]
This option is disabled by default in upstream CMakeLists.txt. An option could be added in cjson's recipe as @prince-chrismc suggested.
It adds a new component (with a dependency on cjson lib).

**Comment by SpaceIm** [comment]
Missed your PR...
