### ISSUE TITLE
[request] mozjpeg/4.0.0

### ISSUE THREAD

**Issue by theirix** [conan-io/conan-center-index#3563]
### Package Details
  * Package Name/Version: **mozjpeg/4.0.0**
  * Changelog: **https://github.com/mozilla/mozjpeg/releases/tag/v4.0.0**

Big release!

> Rebased MozJPEG changes on libjpeg-turbo v2, which includes lots of bug fixes and performance improvements.
>
> Because libjpeg-turbo has switched to cmake, MozJPEG has too. MozJPEG can now be built using either cmake or Cargo.

**Comment by Croydon** [comment]
Done
