### ISSUE TITLE
[service] cairo is not available

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#3566]
Just an issue so that this is not getting lost

https://github.com/conan-io/conan-center-index/pull/2847#issuecomment-727255681

// @ericLemanissier @jgsogo @danimtb

**Comment by jgsogo** [comment]
Cairo is ready! https://conan.io/center/cairo

We've prepared a new job (https://github.com/conan-io/conan-center-index/pull/3598) that will run in the background and will take care of these issues. 

![image](https://user-images.githubusercontent.com/1406456/99547500-e143c100-29b7-11eb-9793-76c421652e69.png)

**Comment by ericLemanissier** [comment]
Thank you !!
