### ISSUE TITLE
Cleanup for newest pybind11 (2.6.0) conanfile required?

### ISSUE THREAD

**Issue by andioz** [conan-io/conan-center-index#3574]
I'm glad to see the updated recipe for pybind11 2.6.0. I skimmed over the new code, and struggled starting with this line.

https://github.com/conan-io/conan-center-index/blob/ffb05bf377e93fc91e055017a3782f51180aab27/recipes/pybind11/all/conanfile.py#L70

It will work, of course, but looks really ugly, a inner function and empty line in code before. Is it planed to refactor this recipe?

**Comment by madebr** [comment]
Empty lines are fine to mentally separate code blocks.

The use of a function is a choice by the recipe author.
He could also have used a lambda or not used a function at all.

The *ugly* argument is subjective and I don't agree with that.
What I agree with is that the name of the function is not good.

You can open a pr with your suggestions (or comment at #3545).
Ideal would be to read the discussion in #3305 and see what's missing/not working and add that.

**Comment by andioz** [comment]
You are right, I agree, I should take care of my words. What I really mean is it took me some minutes to understand this piece of code, I know the syntax for inner functions, but this is an unusual use case, I think.  I followed loosely the discussions about line length, pep8, etc.

OK, I will try to use the new recipe and to figure out whats missing.
