### ISSUE TITLE
[package] protobuf cannot be compiled as shared

### ISSUE THREAD

**Issue by Hopobcn** [conan-io/conan-center-index#3582]
Apparently an `if` protecting code supposed to be only for Windows was removed during last PR development and we have this on master:
```
$ conan create . protobuf/3.12.4@ -o protobuf:shared=True
Exporting package recipe
protobuf/3.12.4 exports: File 'conandata.yml' found. Exporting it...
protobuf/3.12.4 exports: Copied 1 '.yml' file: conandata.yml
protobuf/3.12.4 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
protobuf/3.12.4 exports_sources: Copied 2 '.patch' files: upstream-issue-7567-no-export-template-define.patch, upstream-pr-7761-cmake-regex-fix.patch
protobuf/3.12.4: A new conanfile.py version was exported
protobuf/3.12.4: Folder: /home/pfarre/.conan/data/protobuf/3.12.4/_/_/export
protobuf/3.12.4: Exported revision: fcab376e471eb6443f1f3fd012065226
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
protobuf:shared=True
[build_requires]
[env]

ERROR: protobuf/3.12.4: Invalid configuration: On Windows Protobuf can only be built with Visual Studio 2015 or higher.

```

_Originally posted by @Hopobcn in https://github.com/conan-io/conan-center-index/pull/2037#discussion_r524673470_

**Comment by mipark56** [comment]
I am seeing the same issue in a conan Bamboo docker install.  This error popped up recently, within the past week.

`
18-Nov-2020 02:50:45 | Requirement already satisfied: pyparsing>=2.0.2 in ./.local/lib/python3.6/site-packages (from packaging->deprecation<2.1,>=2.0->conan) (2.4.7)
-- | --
18-Nov-2020 02:50:46 | Configuration:
18-Nov-2020 02:50:46 | [settings]
18-Nov-2020 02:50:46 | arch=x86_64
18-Nov-2020 02:50:46 | arch_build=x86_64
18-Nov-2020 02:50:46 | build_type=Release
18-Nov-2020 02:50:46 | compiler=gcc
18-Nov-2020 02:50:46 | compiler.libcxx=libstdc++
18-Nov-2020 02:50:46 | compiler.version=7
18-Nov-2020 02:50:46 | os=Linux
18-Nov-2020 02:50:46 | os_build=Linux
18-Nov-2020 02:50:46 | [options]
18-Nov-2020 02:50:46 | [build_requires]
18-Nov-2020 02:50:46 | [env]
18-Nov-2020 02:50:46 |  
18-Nov-2020 02:50:46 | ERROR: protobuf/3.9.1: Invalid configuration: On Windows Protobuf can only be built with Visual Studio 2015 or higher.
`
