### ISSUE TITLE
[package] Update openssl dependency in libssh2 recipe

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#359]
While testing libgit2 from PR #286 a found the following message:

```
WARN: libssh2/1.8.2: requirement openssl/1.0.2t overridden by libgit2/0.28.3 to openssl/1.1.1d
```

As an effort to keep the graph consistent, we should update the openssl version in the libssh2 recipe if possible.

**Comment by Croydon** [comment]
Wrong tag, should be `[package]` instead of `[service]` 😃

**Comment by danimtb** [comment]
You are right, better to be tagged as a package issue

**Comment by SSE4** [comment]
that's weird error, as **libssh2** uses **openssl/1.1.1d**:
https://github.com/conan-io/conan-center-index/blob/master/recipes/libssh2/all/conanfile.py#L52
PR also uses **openssl/1.1.1d**:
https://github.com/conan-io/conan-center-index/pull/286/files#diff-d42751b194b0f5d72fcf43e6ae0b23faR76

**Comment by SSE4** [comment]
issue reproduces locally
@danimtb seems like recipe on bintray is somehow outdated... e.g. downloaded **libssh/1.8.2** really has a dependency on **openssl/1.0.2t**. therefore:
- need to understand how come we have packages with recipes outdated from the repository
- rebuild/re-upload outdated recipes
seems like it's previous revision: https://github.com/conan-io/conan-center-index/commit/02c5c82705a45b1be0a3e637ba49a13a3c311b72#diff-e8b6fdc6e1231ddedea5999302aab006

**Comment by danimtb** [comment]
Seems the underlying issue was an error in the merge job done by jenkins:

- There 2 PRs open to update `libssh2`: https://github.com/conan-io/conan-center-index/pull/261 and https://github.com/conan-io/conan-center-index/pull/281
- #281 was merged first and generated recipe revision `527de5df15ca28f2449042a62b97b828` for `libssh2/1.8.2` (as example)
- Then, #261 was merged without the latest changes on master and generated recipe revision `e178ac4fb3e1befad24bfb37e661fa6c` for `libssh2/1.8.2`

As a result, the changes from #281 where lost in the process showing the result reported in PR #286

---------------------

This happened before the merge check and alert was deployed as reported in here: https://github.com/conan-io/conan-center-index/issues/141#issuecomment-552804338

- PRs we merged on the 2019-11-07
- The check was introduced the 2019-11-12

---------------------

To finally fix the issue we will create an internal build with the latest changes in the current master branch

**Comment by danimtb** [comment]
Packages for all versions and configurations of `libssh2` we regenerated with an internal job. @SSE4 could you please check it again?

**Comment by SSE4** [comment]
@danimtb all good now with libgit/libssh2. I hope it didn't affect more recipes.
