### ISSUE TITLE
[package] Poco/all: Cmake upstream uses Poco, not poco

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#360]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **poco/all**

Upstream is using Poco and not poco and here. this issue is simuliar to #357 

### Steps to reproduce (Include if Applicable)
conanfile.txt
```txt
[requires]
poco/1.9.4 
[generators]
cmake_find_package
cmake_paths
```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.10.0)
project(MyProject VERSION 0.1.0)
# does not work with conan
find_package(Poco REQUIRED COMPONENTS Foundation Net Zip )
# does work with conan
find_package(poco REQUIRED COMPONENTS Foundation Net Zip )
add_executable(my_exe main.cpp)
# does work with conan
target_link_libraries(my_exe PUBLIC Poco::Foundation Poco::Zip Poco::Net)
```

**Comment by uilianries** [comment]
There is no official CMake module for Poco in CMake modules, but Poco project offers its own version: https://github.com/pocoproject/poco/tree/master/cmake
