### ISSUE TITLE
[conan.io/center] conan.io/center does not correctly handle semver ordering

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#3618]
According to the website `0.6.10` is the latest release when really it's `0.6.12`. 

![image](https://user-images.githubusercontent.com/16867443/99748346-5a234580-2aaa-11eb-9e7d-fcb178683c96.png)

**Comment by jgsogo** [comment]
Closing in favor of #9418, it is more concrete about the problem and alternate solutions... and better to centralize it all in the same issue.

Thanks!
