### ISSUE TITLE
[package] <cmake>/<3.18.4>: Loop detected in context host

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan-center-index#3625]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cmake/3.18.4**
  * Operating System+version: **macOS Catalina (Android cross-build)**
  * Compiler+version: **clang 9**
  * Python version: **Python 3.7.4**
  * Conan version: **Conan 1.31.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os_build=Macos
arch_build=x86_64

compiler=clang
compiler.version=9
compiler.libcxx=libc++

os=Android
os.api_level=21
arch=armv7
build_type=Release

[build_requires]
android_ndk_installer/r21d@bincrafters/stable
cmake/3.18.4
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
conan install ./conanfile.txt --build missing --profile ./profiles/android
Configuration:
[settings]
arch=armv7
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=9
os=Android
os.api_level=21
os_build=Macos
[options]
[build_requires]
*: android_ndk_installer/r21d@bincrafters/stable, cmake/3.18.4
[env]

WARN: cpprestsdk/2.10.16: requirement openssl/1.1.1g overridden by your conanfile to openssl/1.1.1h 
WARN: libxslt/1.1.33@bincrafters/stable: requirement libxml2/2.9.9 overridden by your conanfile to libxml2/2.9.10 
ERROR: Loop detected in context host: 'cmake/3.18.4' requires 'openssl/1.1.1h' which is an ancestor too
```

</details>

**Comment by Croydon** [comment]
Please provide your used profile, the build command you executed and the full log of the build

**Comment by dmn-star** [comment]
Profile added. I tried cmake/3.17.5..3.18.4 same error.

**Comment by dmn-star** [comment]
Logs too.

**Comment by madebr** [comment]
Is the problem the same when using build and host profiles?
https://docs.conan.io/en/latest/reference/profiles.html#build-profiles-and-host-profiles

**Comment by dmn-star** [comment]
No. This is new feature. I can try it, but the "old" should work too.

**Comment by madebr** [comment]
I don't think it will, because the "old" way assumes build requirements to use arch_build and os_build, which are not used in cmake/m4

**Comment by dmn-star** [comment]
Hmm. Ok i rewrite my "old" profile.

**Comment by Croydon** [comment]
We pretty much stopped using arch_build and os_build in CCI, so I think it is fair to say that the new way is required

**Comment by dmn-star** [comment]
After hours of research: I think it is impossible now to use the "new" way for Android cross-build.

**Comment by dmn-star** [comment]
Not a _cmake_ recipe problem.

**Comment by n-eq** [comment]
Hey @dmn-star, I have pretty much the same issue where building for MacOS is flawless but cross-compiling to an Android target results in this loop detection error.

Did you figure a workaround/fix please?
Thanks.

**Comment by dmn-star** [comment]
Hi, try to  use the new two-profile (build/host) approach
https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer
https://github.com/conan-io/conan-center-index/issues/4220#issuecomment-758486060
