### ISSUE TITLE
[package] cspice/0066: Build breaks in clang 12

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan-center-index#3669]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: cspice/0066
  * Operating System+version: MacOS Big Sur 
  * Compiler+version: apple-clang 12

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
1) Build the package
2) You get the following compilation error

cspice/inquire.c:24:7: error: implicit declaration of function 'access' [-Werror,-Wimplicit-function-declaration]
                x = access(buf,0) ? -1 : 0;
                    ^
This is documented [here](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes)

`Clang now reports an error when you use a function without an explicit declaration when building C or Objective-C code for macOS (-Werror=implicit-function-declaration flag is on). This additional error detection unifies Clang’s behavior for iOS/tvOS and macOS 64-bit targets for this diagnostic. (49917738)`

**Comment by SpaceIm** [comment]
fixed by yourself https://github.com/conan-io/conan-center-index/pull/3670

**Comment by SpaceIm** [comment]
@uilianries this issue can be closed ;)
