### ISSUE TITLE
[service] CI job passed with success when package is missing

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#368]
Hi!

The PR #354 illustrates the current case. The new recipes requires `tbb`, but with a specific option (tbb:tbbmalloc) which is not available as pre-built package.

The CI job finished with success, https://github.com/conan-io/conan-center-index/pull/354#issuecomment-555957647, however, both stderr_output and stdout_output have an error related to the missed package.

https://c3i.jfrog.io/c3i/misc/logs/pr/354/3/embree/3.6.1/ff2591ab8f785e87d0f787b51c9e1a552e96864a/create_stderr.txt

/cc @danimtb @lasote

**Comment by danimtb** [comment]
Thanks for reporting. I have tried to reproduce this with a test but got the expected behavior. Will try on staging env

**Comment by danimtb** [comment]
Mysteriously, the issue has been raised with a relaunch of the CI: https://github.com/conan-io/conan-center-index/pull/354#issuecomment-558259008

**Comment by danimtb** [comment]
I don't think this is happening anymore, right? WDYT @uilianries?

**Comment by uilianries** [comment]
@danimtb I think so, let's close this one.
