### ISSUE TITLE
[question] OpenCV 4.5.0 - support for Andoid, iOS, MacOS

### ISSUE THREAD

**Issue by andioz** [conan-io/conan-center-index#3715]
Hi, I'm glad to see a brand new recipe for the recent OpenCV version. Unfortunately, I cannot use it for an Android build, `conan install` fails. I guess the current version doesn't support it? Any plans to add support for other platforms? I would need Android, iOS and MacOS in addition to Linux.  Currently we use a slightly modified version from https://bintray.com/conan-community/conan/opencv%3Aconan/4.1.1%3Astable. Thanks!

**Comment by andioz** [comment]
Update: I see, MacOS should be supported out of the box. I didn't try yet. Still missing Android and iOS.

**Comment by Croydon** [comment]
Contributions to add recipe support for Android and iOS are welcome

CCI does not offer pre-builds for those targets however. Have a look at https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md

**Comment by andioz** [comment]
Thanks for the quick response. Yes I understand there are no pre-builds for that platforms. But I wonder why I could not use the recipe in combination with an Android profile file like that (we use this with the previously mentioned recipe to build from source).

```ini
include(default)

[settings]
arch=armv8
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=21

[build_requires]
android_ndk_installer/r20@bincrafters/stable

[options]
[env]
```
Maybe there is a problem on a different location, I have to check again.

If I'm able to contribute regarding this, I will try :slightly_smiling_face:

**Comment by andioz** [comment]
OK, I tried again (build machine: Ubuntu 20.04):

```sh
$ conan install opencv/4.5.0@_/_ --build=always --profile /path/to/android_profile
Configuration:
[settings]
arch=armv8
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=21
os_build=Linux
[options]
[build_requires]
*: android_ndk_installer/r20@bincrafters/stable
[env]

ERROR: The recipe is contraining settings. Invalid setting 'Android' is not a valid 'settings.os' value.
Possible values are ['Linux']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```
Maybe someone give me a hint, I cannot see where the `Possible values are ['Linux']` restriction is set? Not in the recipe I think...

**Comment by ericLemanissier** [comment]
please retry with `-u` argument, the recipe was updated two days ago to solve a similar problem

**Comment by andioz** [comment]
Wow, indeed, now it starts to compile! I guess my problem comes from the `gtk` dependency, which was not disabled correctly. Now it compiles the dependencies and starts with opencv itself, stopping with this error:

```
CMake Error at source_subfolder/samples/android/15-puzzle/CMakeLists.txt:3 (add_android_project):
  Unknown CMake command "add_android_project".
```

But I guess this is a completely different story. Thanks @ericLemanissier for the hint!

**Comment by prince-chrismc** [comment]
Merged! Feel free to close the issue 👏 great work!
