### ISSUE TITLE
[question] Is `/permissive-` flag necessary in range-v3

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-center-index#3739]
The `/permissive-` flag was added to the `range-v3` recipe as part of #2742 - Is it strictly necessary? It's causing a lot of compilation errors in a large project (including with `boost::interprocess`)

Will see if I can put together a minimal example but thought I'd pose the question before raising a bug.

**Comment by SSE4** [comment]
yes, this is pretty strict requirement:
```
Visual Studio 2019 (or later) on Windows, with some caveats due to range-v3's strict conformance requirements:
range-v3 needs /permissive- and either /std:c++latest or /std:c++17
```
maybe, if `/permissive` isn't acceptable, you may use `std::range` (conditionally)?

**Comment by planetmarshall** [comment]
OK, thanks. To be honest this is more a problem with some legacy code in our codebase that is non-conformant. I'll see if i can restructure things to enable ranges use. I can't use `std::ranges` as we use Eigen extensively, which does not currently compile with C++20.
