### ISSUE TITLE
[package] <gsl-lite>/<0.37.0>: pkg-config generator fails parsing description

### ISSUE THREAD

**Issue by hdhauk** [conan-io/conan-center-index#3745]
The description in the gsl-lite recipe is a tuple which seems to break the pkg-config generator when it attempts to parse it. 

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **gsl-lite/0.37.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Conan version: **conan 1.31.3**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```ini
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Run `conan install` with the following `conanfile.txt`
```ini
[requires]
gsl-lite/0.37.0

[generators]
pkg_config
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
conanfile.txt: Installing package
Requirements
    gsl-lite/0.37.0 from 'conan-center' - Cache
Packages
    gsl-lite/0.37.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
gsl-lite/0.37.0: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: ERROR: Traceback (most recent call last):
  File "/home/hdhauk/.local/lib/python3.6/site-packages/conans/client/generators/__init__.py", line 102, in write_generators
    content = generator.content
  File "/home/hdhauk/.local/lib/python3.6/site-packages/conans/client/generators/pkg_config.py", line 64, in content
    comp_gennames)
  File "/home/hdhauk/.local/lib/python3.6/site-packages/conans/client/generators/pkg_config.py", line 125, in global_pc_file_contents
    lines.append("Description: %s" % description)
TypeError: not all arguments converted during string formatting

conanfile.txt: ERROR: Generator pkg_config(file:None) failed
not all arguments converted during string formatting
ERROR: not all arguments converted during string formatting
```

</details>

**Comment by madebr** [comment]
Indeed, feel free to open a pull request

**Comment by uilianries** [comment]
That's a Conan bug, not a recipe bug. Your fix is palliative only. I'll open an issue to Conan. Thanks for reporting.

**Comment by uilianries** [comment]
I've submitted a fix for Conan. https://github.com/conan-io/conan/pull/8143

Conan 1.32 should be released soon, this week probably, thus your PR can accepted as it provides a fix for older Conan versions.
