### ISSUE TITLE
[request] hiredis/0.14.0

### ISSUE THREAD

**Issue by andre-cunha** [conan-io/conan-center-index#375]
### Package Details
  * Package Name/Version: hiredis/0.14.0
  * Website: https://github.com/redis/hiredis
  * Source code: https://github.com/redis/hiredis

### Description Of The Library / Tool
Hiredis is a minimalistic C client library for the Redis database.

**Comment by uilianries** [comment]
Hello @andre-cunha !

Would do you like to contribute with this recipe? I've found two Conan recipes for this project when Googling. We you can help you!

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/1763
