### ISSUE TITLE
Is there a way to find a package maintainer's email?

### ISSUE THREAD

**Issue by fanxinping** [conan-io/conan-center-index#3753]
I cannot find the maintainer's email for any package, for example, https://conan.io/center/librdkafka?os=  .

Does anyone  know? Thanks

**Comment by memsharded** [comment]
Plus, in many cases, contributors, collaborators, and even if a package in ConanCenter is mainly maintained by one person, they rarely want to be contacted by email, but rather in Github, and that is easy to get from the repo. So I think this issue can be closed, getting emails from maintainers in ConanCenter packages is not expected.
