### ISSUE TITLE
[conan.io/center] Add link to the recipe GitHub folder

### ISSUE THREAD

**Issue by mathbunnyru** [conan-io/conan-center-index#3755]
I think it would be nice to be able to go directly to GitHub from the conan website.
For example, I don't see a button to get from here: https://conan.io/center/valijson to this folder: https://github.com/conan-io/conan-center-index/tree/master/recipes/valijson

**Comment by mathbunnyru** [comment]
Wow, I didn't know that it's possible to transfer issues this way. So cool 👍 

No worries :)

**Comment by Croydon** [comment]
This is done, there is a `View recipe on GitHub` link 

https://conan.io/center/recipes/zlib
