### ISSUE TITLE
[package] nng/1.3.2: can't build with Visual Studio 2017

### ISSUE THREAD

**Issue by db4** [conan-io/conan-center-index#3757]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **nng/1.3.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2017**

I can't build nng/1.3.2 from sources with Visual Studio 2017. The problem is old enough cmake included into Visual Studio distribution. So cmake configuration fails:
```
CMake Error at source_subfolder/CMakeLists.txt:28 (cmake_minimum_required):
  CMake 3.13 or higher is required.  You are running version
  3.12.18081601-MSVC_2


-- Configuring incomplete, errors occurred!
```

Probably `cmake_installer` package should be used by the recipe as a build requirement.

**Comment by madebr** [comment]
See https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-recipes-that-use-build-tools-like-cmake-that-have-packages-in-conan-center-do-not-use-it-as-a-build-require-by-default

You can add `cmake/3.19.1` to the build requirements of your (default) profile.

While you're correct by saying that cmake is a build requirement of this particular recipe,
all conan scripts assume that a recent enough cmake version is used.
None of the conan recipes require cmake or check for its version.
I think the gain by checking for this would be negligible.

It also does this for other platforms.

**Comment by db4** [comment]
Sounds reasonable. But then I need to make `cmake/3.19.1` a default build requirement in my CI environment. I'm surprised it's not yet possible via conan CLI: https://github.com/conan-io/conan/issues/6887
