### ISSUE TITLE
[package] paho-mqtt-cpp/1.1: build fails with error "Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)"

### ISSUE THREAD

**Issue by isnullxbh** [conan-io/conan-center-index#3760]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **paho-mqtt-cpp/1.1**
  * Operating System+version: **Arch Linux 5.9.11**
  * Compiler+version: **Clang 11**
  * Conan version: **conan 1.31.4**
  * Python version: **Python 3.9.0**

### Conan profile
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

#### Step 1. Check helper cmake file

Link:
https://github.com/eclipse/paho.mqtt.cpp, branch: v1.1

In file cmake/FindPahoMqttC.cmake:

```cmake
# add suffix when using static Paho MQTT C library variant
if(PAHO_BUILD_STATIC)
    set(_PAHO_MQTT_C_LIB_NAME ${_PAHO_MQTT_C_LIB_NAME}-static)
endif()
```

#### Step 2. Check paho-mqtt-c build

In ~/.conan/data/paho-mqtt-c/.../package/.../lib:

```sh
libpaho-mqtt3as.a # Pay attention - no '-static' suffix
```

#### Step 3. Check out the latest changes

Commit:
https://github.com/conan-io/conan-center-index/commit/a79d9f7f0c2b61c3e137720a917313c717761720

```diff
def requirements(self):
-   if tools.Version(self.version) >= "1.1":
-       self.requires("paho-mqtt-c/1.3.1")
-   else:
-       self.requires("paho-mqtt-c/1.3.0")
+   self.requires("paho-mqtt-c/1.3.5")
```

#### Step 4. Compare CMake files for paho-mqtt-c v1.3.1/v1.3.5

v1.3.1
https://github.com/eclipse/paho.mqtt.c/blob/d34c51214f4172f2e12bb17532c9f44f72a57dd4/src/CMakeLists.txt#L164

v1.3.5
https://github.com/eclipse/paho.mqtt.c/blob/153dfd3a4a1d510697c5d55e169fa158db16e04a/src/CMakeLists.txt#L244

CMakeLists.txt (v1.3.5) contains the following instructions:

> SET_TARGET_PROPERTIES(paho-mqtt3cs-static PROPERTIES OUTPUT_NAME paho-mqtt3cs) \
> SET_TARGET_PROPERTIES(paho-mqtt3as-static PROPERTIES OUTPUT_NAME paho-mqtt3as)

So, paho-mqtt-cpp v1.1 search for the paho-mqtt-c library which name contains '-static' suffix, but the new version of paho-mqtt-c (v1.3.5) doesn't append that suffix.

#### Quick fix (for lib clients)

```sh
# In ~/.conan/data/paho-mqtt-c/.../package/.../lib
cp libpaho-mqtt3as.a libpaho-mqtt3as-static.a
```

Run Conan again.

### Steps to reproduce (Include if Applicable)

Just launch Conan install from CMake:

```cmake
if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
    file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/master/conan.cmake"
        "${CMAKE_BINARY_DIR}/conan.cmake")
endif()

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_run(REQUIRES paho-mqtt-cpp/1.1
    BASIC_SETUP
    BUILD missing)
```

**Comment by bowb** [comment]
I am having the same type of issue when compiling on armv8

Conan Profile:

[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

I am able to work around the issue by doing the following:

run the following command
```
conan config set general.revisions_enabled=True
```
In my conanfile.txt I need to specify a specific version of recipe

```
paho-mqtt-c/1.3.5@#acc9376a7232c5a50ac898a9131c6c82
```

It now compiles. Something has changed in the latest recipe that breaks the build.

**Comment by bowb** [comment]
I am working on a pull request for this issue. It appears that the recipe for paho-mqtt-c/1.3.5 was changed to generated eclipse-paho-mqtt-c instead of PahoMqttC and the cmake files was being incorrectly generated for paho-mqtt-cpp/1.1.

[https://github.com/conan-io/conan-center-index/pull/3974](https://github.com/conan-io/conan-center-index/pull/3974)

**Comment by voidbar** [comment]
https://github.com/conan-io/conan-center-index/pull/4096 by @bowb  indeed fixes the issue. Just fixed it locally on my machine.

**Comment by martinpeniak** [comment]
Hi guys, any idea when I could start using this version please?

paho-mqtt-cpp/1.2.0

I still get:
ERROR: Unable to find 'paho-mqtt-cpp/1.2.0' in remotes

**Comment by jayjupdhig** [comment]
Similar problem here:

https://github.com/eclipse/paho.mqtt.c/issues/1059
