### ISSUE TITLE
[request]  jpeg-compressor 

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#3801]
### Package Details
  * Package Name/Version: **jpeg-compressor/latest**
  * Website: **https://github.com/richgel999/jpeg-compressor**
  * Source code: **https://github.com/richgel999/jpeg-compressor**

### Description Of The Library / Tool

C++ JPEG compression/fuzzed low-RAM JPEG decompression codec with Public Domain or Apache 2.0 license

**Comment by intelligide** [comment]
https://github.com/richgel999/jpeg-compressor/pull/14
