### ISSUE TITLE
[request] QT/6.0.0

### ISSUE THREAD

**Issue by IceflowRE** [conan-io/conan-center-index#3845]
### Package Details
  * Package Name/Version: **qt/6.0.0**
  * Website: **https://www.qt.io/**
  * Source code: **https://code.qt.io/cgit/qt/qt5.git/**

### Description Of The Library / Tool
Qt is a free and open-source widget toolkit for creating graphical user interfaces as well as cross-platform applications that run on various software and hardware platforms such as Linux, Windows, ...

**About the QT6 build system** (cmake hooray)
https://wiki.qt.io/Building_Qt_6_from_Git
https://doc.qt.io/qt-6/qt6-buildsystem.html

**Conan profiles for QT6**
https://code.qt.io/cgit/qt/qt-conan-config.git/

**Additional Libraries via Conan**
https://www.qt.io/blog/qt-6-additional-libraries-via-package-manager

---

Related: #1759

**Comment by SpaceIm** [comment]
Didn't test, but is it not possible to modularize Qt6 now?

**Comment by ericLemanissier** [comment]
it should be yes

**Comment by IceflowRE** [comment]
I think with the options you can already do it like that.

**Comment by anton-danielsson** [comment]
The work in https://github.com/conan-io/conan-center-index/pull/4412 looks pretty great :)

**Comment by anton-danielsson** [comment]
I think this issue can be closed since https://github.com/conan-io/conan-center-index/pull/4412 is merged already.
