### ISSUE TITLE
[package] boost/*: ios variant misses two define exports

### ISSUE THREAD

**Issue by qwertzui11** [conan-io/conan-center-index#3867]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.74.0**
  * Operating System+version: **iOS**
  * Compiler+version: **clang 12**
  * Conan version: **conan 1.31.0**
  * Python version: **Python 3.8.5**

### Conan profiles

build.profile
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

host.profile (ios Simulator)
```
[settings]
os=iOS
os.version=12.0
arch=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Debug
[options]
[build_requires]
[env]
```

### Steps to reproduce

I'm cross compiling boost from MacOS to iOS Simulator (x86_64). Which works quite well. Awesome job!
However when consuming the library weird runtime crashes occur due to invalid memory access.
Two days of debugging and address sanitizer showed that the consuming product has two defines missing. `-DBOOST_SP_USE_PTHREADS` and `-DBOOST_AC_USE_PTHREADS`.

https://github.com/conan-io/conan-center-index/blob/d956a467dab31503f0054face5c09f83b7a05f68/recipes/boost/all/conanfile.py#L764-L767

May I suggest that you add the flags `-DBOOST_SP_USE_PTHREADS` and `-DBOOST_AC_USE_PTHREADS` to the `package_info` method? https://github.com/conan-io/conan-center-index/blob/d956a467dab31503f0054face5c09f83b7a05f68/recipes/boost/all/conanfile.py#L1014

Thanks for your time!

**Comment by madebr** [comment]
When googling for `ios BOOST_AC_USE_PTHREADS BOOST_SP_USE_PTHREADS`,
I indeed get results with problems.

Reading https://www.boost.org/doc/libs/1_74_0/libs/smart_ptr/doc/html/smart_ptr.html#shared_ptr_thread_safety,
it looks like the *lock-free platform-specific implementation* does not work on iOS.

Could you please report this at https://github.com/boostorg/smart_ptr/issues and/or https://github.com/boostorg/atomic/issues?

**Comment by qwertzui11** [comment]
conan does everything right and boost too... the issue seems to be the projects USING the compiled ios boost version. because smart_ptr is header-only the USING projects must declare `BOOST_AC_USE_PTHREADS` and `BOOST_SP_USE_PTHREADS` too. 

so in my opinion `package_info` should declare something like this:

```python3
def package_info(self):
  if self.settings.os == "iOS":
    self.cpp_info.components["no idea"].defines = ["BOOST_AC_USE_PTHREADS", "BOOST_SP_USE_PTHREADS"]
```

**Comment by madebr** [comment]
Sounds good,
I will add
```python
def package_info(self):
  if self.settings.os == "iOS":
    self.cpp_info.components["headers"].extend(["BOOST_AC_USE_PTHREADS", "BOOST_SP_USE_PTHREADS"])
```
to the pr at #3872

**Comment by madebr** [comment]
Do you happen to know wheter `watchOS` and `tvOS` suffer from the same problem?

**Comment by qwertzui11** [comment]
> Do you happen to know whether `watchOS` and `tvOS` suffer from the same problem?

No, no idea. And don't have the hardware. I can test the simulators if would like so? However, I'm quite sure, all iOS devices are affected.

**Comment by madebr** [comment]
Thanks, but only if it does not require much time.

I'm still thinking it would be interesting to open an issue at the boostorg repo(s).
It's always interesting to let them know that the default smartptr/atomic backend causes problems on iOS.
It's hard to believe that this problem appears now.

**Comment by SSE4** [comment]
I think it more or less going from https://stackoverflow.com/questions/14692802/boost-threads-in-ios-thread-info-object-is-being-destructed-before-the-thread

**Comment by madebr** [comment]
I'm just saying that the upstream project needs to be made aware of the problem.
They know their code the best.
