### ISSUE TITLE
OpenCV recipe update not available in Conan Center

### ISSUE THREAD

**Issue by andioz** [conan-io/conan-center-index#3879]
Hi, there is still a problem with OpenCV 4.5.0 for Android update (PR #3728). The recipe update is is approved and merged now for more than one week, But still not available on Conan Center. I guess this is because the final step was failing - building all prebuilds for the center?

I cannot see any details about the problems, only a "all checks have failed". And as far as I can say, no automatic retry is triggered? How can we solve this? I'm waiting for this update desperately :smirk:

**Comment by jgsogo** [comment]
Hi! Thanks for noticing. Indeed I see the merge commit for that PR was broken. We have some nightly jobs to try to avoid these issues, but now some of them are being bitten by the `eoan` issue (https://github.com/conan-io/conan-docker-tools/pull/234). I'm working on this _manually_, I expect to have them ready soon.

**Comment by jgsogo** [comment]
Packages for OpenCV are already available (there is one missing due to the docker image issue).

https://conan.io/center/opencv

```
conan search opencv/4.5.0@ -r conan-center --table=output.html
```

![image](https://user-images.githubusercontent.com/1406456/102121979-20452500-3e45-11eb-8959-57f121458a76.png)

**Comment by andioz** [comment]
Wow cool! Great work, thanks!
