### ISSUE TITLE
[request] SFML/2.5.1

### ISSUE THREAD

**Issue by Rdna123** [conan-io/conan-center-index#3888]
### Package Details
  * Package Name/Version: **SFML/2.5.1**
  * Website: **https://www.sfml-dev.org/**
  * Source code: **https://github.com/SFML/SFML**

#### SFML is multi-media
SFML provides a simple interface to the various components of your PC, to ease the development of games and multimedia applications. It is composed of five modules: system, window, graphics, audio and network.

#### SFML is multi-platform
With SFML, your application can compile and run out of the box on the most common operating systems: Windows, Linux, macOS and soon Android & iOS.

**Comment by Croydon** [comment]
WIP: https://github.com/conan-io/conan-center-index/pull/2467
