### ISSUE TITLE
[package] Boost: Allow unknown platforms

### ISSUE THREAD

**Issue by n-bes** [conan-io/conan-center-index#392]
### Package and Environment Details (include every applicable attribute)
  * Operating System+version: **Linux Mint 19.1**

I have a private cross-compiler (linux-x86_64 to [e2k](https://en.wikipedia.org/wiki/Elbrus_2000)) and i can't build 'boost', for example, [for this reason](https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py#L623) 
```
raise Exception("I'm so sorry! I don't know the appropriate ABI for your architecture. :'(")
```

Can we use warning instead of error in this case? May be, **conan** also should support it?

**Comment by uilianries** [comment]
Hi @n1-b !

Do you know if e2k requires extra args? You can open a PR skipping that error.

**Comment by SSE4** [comment]
we definitely should allow arbitrary platforms and only issue a warning for the unknown things, not preventing them

**Comment by n1-b** [comment]
> Do you know if e2k requires extra args?

Think that no. I know that current version of compiler flags similar with ~gcc-5.5, but additional args also can be passed from profile if it needed.

**Comment by SSE4** [comment]
so far, only ARM hard-float required special flags. I guess we should use no flags for all unknown platforms and just print warning, that should be enough.

**Comment by n1-b** [comment]
@danimtb Boost was just as an example, should i create new issues for another packages?

**Comment by danimtb** [comment]
@n1-b yes, create issues for other packages with the trace.

Also, keep in mind that we cannot test all the configurations, so recipes might not build with a specific setting. Some of these configurations are difficult to test and set up the environment can be tricky, so we will not be able to fix them in some cases. Any collaboration with pull requests to improve the recipes will be the best option. Thanks
