### ISSUE TITLE
[package] bullet3/all: Expose option for defining BT_ENABLE_PROFILE

### ISSUE THREAD

**Issue by NiklasJonsson** [conan-io/conan-center-index#3928]
### Package Details
  * Package Name/Version: **bullet3/all**

bullet supports querying profiling information but only if it is compiled with BT_ENABLE_PROFILE. If I understand correctly, the best way to expose this is via an option in the conan recipe.

**Comment by madebr** [comment]
I can find only one reference to `BT_ENABLE_PROFILE`: https://github.com/bulletphysics/bullet3/blob/afa4fb54505fd071103b8e2e8793c38fd40f6fb6/src/LinearMath/btQuickprof.h#L64
It's not defined by a cmake script.

`BT_NO_PROFILE` is used in some places: https://github.com/bulletphysics/bullet3/search?q=BT_NO_PROFILE
But nowhere is it defined by a cmake script.

So I don't think this is supported by upstream.

**Comment by NiklasJonsson** [comment]
Sorry for the late reply, long christmas vacation.

Doesn't the fact that it is used in official examples mean that it is supported? Or do all preprocessor defines need to be exposed via cmake? For what it's worth, it's in the official documentation as well: https://raw.githubusercontent.com/bulletphysics/bullet3/master/docs/Bullet_User_Manual.pdf (pages 10-11)

and here is a issue (from 2018) that references being able to log performance from the python api: https://github.com/bulletphysics/bullet3/issues/1649#issuecomment-391875920

The performance logging feature is also listed in the python quickstart guide: (pages 41-42) https://raw.githubusercontent.com/bulletphysics/bullet3/master/docs/pybullet_quickstartguide.pdf

**Comment by madebr** [comment]
Indeed, it's documented and `BT_PROFILE` is used more often.
The fact remains that the cmake script does not have profile support.
Perhaps first a pr should be submitted to bullet3 that adds this definition.
e.g. add the following to the main cmake script
```cmake
OPTION(BULLET_PROFILE "Enable Timing and Performance Profiling" OFF)
IF(BULLET_PROFILE )
    ADD_DEFINITIONS(-DBT_ENABLE_PROFILE)
ENDIF()
```

**Comment by NiklasJonsson** [comment]
While looking at creating an MR on the bullet repo I noticed that the BT_PROFILE macro doesn't seem to resolve to any real function call by default. If I follow the call chain, it's `BT_PROFILE -> CProfileSample -> btEnterProfileZone ->bts_enterFunc -> btEnterProfileZoneDefault`, it resolves to an empty function regardless of if BT_NO_PROFILE is set. It seems like it is not supported after all.

Judging from this commit: https://github.com/bulletphysics/bullet3/commit/750133694c83ac33bd33b7baee5b2e6d3a7cc8fc
other functions are used for profiling. I will close this issue, thank you for the help regardless!
