### ISSUE TITLE
[question] There is no algorithm for boost package

### ISSUE THREAD

**Issue by CAMOBAP** [conan-io/conan-center-index#3961]
There is no `algorithm` for `boost` package https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py#L23-L53.

Should we add it?

**Comment by prince-chrismc** [comment]
Yes 💯 

#3894 is an example of missing libs if I recall correctly

**Comment by madebr** [comment]
Isn't `algorithm` a header-only library?
The options are for boost components building libraries.

Does boost's build system allow to build/install only certain header-only libraries?
This might cause problems because other header libraries depend on algorithm.

**Comment by CAMOBAP** [comment]
> Isn't algorithm a header-only library?

Yes it is

> Does boost's build system allow to build/install only certain header-only libraries?
> This might cause problems because other header libraries depend on algorithm.

@madebr Thanks for the clarification.
My motivation is that the CMake code like `FIND_PACKAGE(Boost REQUIRED COMPONENTS algorithm)` should work but currently, it doesn't.

**Comment by madebr** [comment]
I tried the following:
```cmake
cmake_minimum_required(VERSION 3.17)
project(test)
find_package(Boost REQUIRED COMPONENTS algorithm)
```

Running cmake on this script gives the following:
```
-- The C compiler identification is GNU 9.3.1
-- The CXX compiler identification is GNU 9.3.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:2003 (message):
  No header defined for algorithm; skipping header check (note: header-only
  libraries have no designated component)
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)


CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: algorithm) (found version "1.69.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2162 (find_package_handle_standard_args)
  CMakeLists.txt:3 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/a/build/CMakeFiles/CMakeOutput.log".
```

If you want the Boost.algorithm headers, then you need to do:
```cmake
find_package(Boost REQUIRED)
...
target_link_libraries(your_library PRIVATE Boost::headers)
```

**Comment by CAMOBAP** [comment]
@madebr you are right, I'm closing this one
