### ISSUE TITLE
[question] How to handle installers

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#397]
While looking at #358, I noticed gmp uses bison and flex which are not (yet) packaged by CCI.

These packages consist of an installer and library component.
Is there a protocol/consensus about how to handle such packages?

**Comment by Croydon** [comment]
The Bincrafters version required m4 https://github.com/bincrafters/conan-gmp/blob/2867e59717792767ae7b60d11465aa73d96ce77a/conanfile.py#L22

In my humble opinion we should wait until all (reasonable build) requirements are available in CCI

**Comment by madebr** [comment]
I'm not only talking only about bison or flex. There are a lot of projects who create binaries + libraries that might be useful for developers.
A policy on this topic would be useful.
The sooner a consensus is made, the less changes should be made to packages (and to its consumers).

**Comment by uilianries** [comment]
I would say to split them when possible.

As we know, we saw many problems in the past related to mixing both for Bincrafters packages.

/cc @danimtb @SSE4

**Comment by danimtb** [comment]
As previously discussed, we will split packages if the executable is likely to be used as a tool for building or as build require for other recipes in the index. This is due to the fact that if packages are not split, there are problems when cross-building.

If the executable is not likely to be used as a build require, it can be packaged with the library

**Comment by madebr** [comment]
Thanks.
Will we adopt the same naming convention as bincrafters?
- `bison` and `bison_installer`
- Will we be ok with copying the code for these two relevant packages?
- Adding 2 folders `bison` and `bison_installer` and requiring 2 pull requests for such packages, won't this become a maintenance hell?

**Comment by uilianries** [comment]
> bison and bison_installer?

bison for the installer and libbison for the library

> Will we be ok with copying the code for these two relevant packages?

Yes for now, because we don't have a mechanism on Jenkins which can solve this situation. I'm not sure if relative path will work there, like shared a common folder.

> Adding 2 folders bison and bison_installer and requiring 2 pull requests for such packages, won't this become a maintenance hell?

![This is fine!](https://cdn.frankerfacez.com/emoticon/296572/4)

I would say keep doing it for now, but we can improve it in the future.

**Comment by madebr** [comment]
> bison for the installer and libbison for the library

Nice alternative!

> 
> > Will we be ok with copying the code for these two relevant packages?
> 
> Yes for now, because we don't have a mechanism on Jenkins which can solve this situation. I'm not sure if relative path will work there, like shared a common folder.
> 

It would be nice if it a `conanfile_base.py` file is allowed in a recipe folder.
That way merging/diffing said `bison` and `libbison` would get easier.

> 
> I would say keep doing it for now, but we can improve it in the future.

I hope sooner than late.

**Comment by Croydon** [comment]
We moved on to have executables and libraries in a single package.

I guess this issue can be closed 🤔

**Comment by uilianries** [comment]
Yes. Now, with [context](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer) feature we don't need to split them.

We still can't close because is marked as `docs`. Let's add a topic on FAQs about it to close this issue.

**Comment by SSE4** [comment]
Yes

**Comment by madebr** [comment]
I think it's safe to say this issue got resolved.
