### ISSUE TITLE
[package] libcurl/7.66.0 WinSSL not enabled with CMake build

### ISSUE THREAD

**Issue by netgeck** [conan-io/conan-center-index#3976]
I'm trying to build libcurl/7.66.0 with WINSSL option enabled for my project. But option is disabled in CMakeCache.txt after building is done.
Recipe libcurl/7.66.0 (Latest Revision be0504c6acf1da62622a18855ce40cb2) trying to set only CMAKE_USE_SCHANNEL while configuring CMake. And it does not set CMAKE_USE_WINSSL

It doesn't matter if I use Recipe's option `:with_winssl=True` or `:with_ssl=schannel`. The first one only results in warning:
 _libcurl/7.66.0: WARN: with_openssl, with_winssl, darwin_ssl and with_wolfssl options are deprecated. Use with_ssl option instead._

libcurl-7.66 does not have an option CMAKE_USE_SCHANNEL in CMakeLists.txt. The option was added in later versions. 
There is only option CMAKE_USE_WINSSL and  variables: SSL_ENABLED, USE_SCHANNEL, USE_WINDOWS_SSPI depending on it.
```
if(CMAKE_USE_WINSSL)
  set(SSL_ENABLED ON)
  set(USE_SCHANNEL ON) # Windows native SSL/TLS support
  set(USE_WINDOWS_SSPI ON) # CMAKE_USE_WINSSL implies CURL_WINDOWS_SSPI
  list(APPEND CURL_LIBS "crypt32")
endif()
```

Generated CMakeCache.txt:
```
//No help, variable specified on the command line.
CMAKE_USE_SCHANNEL:UNINITIALIZED=True

//enable Windows native SSL/TLS
CMAKE_USE_WINSSL:BOOL=OFF
```

**Environment details:**
Operation system: Windows 10
Conan version 1.31.2

Profile msvc16StaticDebug64:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.runtime=MTd
build_type=Debug
[options]
[build_requires]
[env]

```
My conanfile.txt:
```
[requires]
libcurl/7.66.0

[generators]
cmake_find_package

[options]
libcurl:with_ssl=schannel
```

**Step to reproduce:**
conan install --profile msvc16StaticDebug64 --build=missing ..\conanfile.txt

**Comment by netgeck** [comment]
Can anyone suggest how to set specific revision of package Recipe in conanfile.txt?
I found that the last Recipe which set the CMAKE_USE_WINSSL option is _27fb52e6411dc107de4b121c55a46ae5_

**Comment by madebr** [comment]
The `CMakeLists.txt` of libcurl 7.74.0 has the following line:
```
if(CMAKE_USE_WINSSL)
  message(FATAL_ERROR "The cmake option CMAKE_USE_WINSSL was renamed to CMAKE_USE_SCHANNEL.")
endif()
```

**Comment by netgeck** [comment]
Here is CMakeLists.txt of libcurl 7.66.0: https://github.com/curl/curl/blob/curl-7_66_0/CMakeLists.txt
There is no `CMAKE_USE_SCHANNEL`

**Comment by madebr** [comment]
Indeed, I was wrong.
The change in `7.72.0`, `CMAKE_USE_WINSSL` -> `CMAKE_USE_SCHANNEL`

**Comment by madebr** [comment]
Does #3984 fix this for you?

**Comment by netgeck** [comment]
Yes. I think these edits in conanfile.py will help. Thank you!
