### ISSUE TITLE
[package] flatbuffers/1.12.0: How to use instead of flatc?

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan-center-index#4013]
I had flatc as my build requirement and flatbuffers as an ordinary (quite logical tool / library split IMHO, which I like).

However I noticed that flatcc is deprecated in favor of plain flatbuffers recipe in PR #3843 .

So I tried to replace my build requirement:
```python
    requires = [
        "flatbuffers/1.12.0",
    ]

    build_requires = [
        "flatbuffers/1.12.0",
#        "flatc/1.12.0",
    ]
```

When I tried to install it with host / build profiles (`-pr:h gcc -pr:h conan/dev -pr:b default`)
```
Make Error at conanbuildinfo.cmake:402 (message):
  Detected a mismatch for the compiler version between your conan profile
  settings and CMake:

  Compiler version specified in your conan profile: 9

  Compiler version detected in CMake: 10.2

  Please check your conan profile settings (conan profile show
  [default|your_profile_name])

  P.S.  You may set CONAN_DISABLE_CHECK_COMPILER CMake variable in order to
  disable this check.
Call Stack (most recent call first):
  conanbuildinfo.cmake:484 (conan_error_compiler_version)
  conanbuildinfo.cmake:587 (check_compiler_version)
  conanbuildinfo.cmake:141 (conan_check_compiler)
  CMakeLists.txt:5 (conan_basic_setup)


-- Configuring incomplete, errors occurred!
See also "/home/dev/.conan/data/flatbuffers/1.12.0/_/_/build/b15c982a8e4c6181ad73cec4fd6d9d3a257c8741/CMakeFiles/CMakeOutput.log".
flatbuffers/1.12.0: 
```

my `default` profile (which I use to build tools) comes from `--detect` and uses system compiler (and release configuration) while I need to build my code with different compiler (i.e. gcc-10 in my case).

**Comment by ytimenkov** [comment]
@Croydon any thoughts?

@memsharded Is it legal to have same requirement both as build and an ordinary requirement? It seems to not work well with lockfiles: `conan install --lockfile` complains that it can't find the package in build requirements.

**Comment by uilianries** [comment]
@ytimenkov Could you please share your profiles and how you are consuming flatc? Are you using CMake, how? Could you share you cmake file for instance?

**Comment by ytimenkov** [comment]
> Could you please share your profiles 

profile `gcc` (for target, requirements):
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
compiler.cppstd=20
build_type=Release
[options]
[build_requires]
*: cmake/3.18.4
[env]
CC=gcc-10
CXX=g++-10
AR=gcc-ar-10
RANLIB=gcc-ranlib-10
```

Profile `default` (build tools):
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
[options]
[build_requires]
[env]
```

flatc was (and still is) a build requirement, while flatbuffers is an ordinary requirement.

I use CMake in toolchain, so `CMakeLists.txt` is fairly simple. See https://github.com/ytimenkov/eems (conanfile is there too).

**Comment by ytimenkov** [comment]
My bad 🤦‍♂️😞

Apparently after system upgrade the default compiler `g++` became `g++-10`. Solved by forcing conan to generate new profile.
