### ISSUE TITLE
[question] flatc/1.12.0 deprecated yet flatbuffers doesn't contain flatc executable

### ISSUE THREAD

**Issue by p-groarke** [conan-io/conan-center-index#4039]
Flatc 1.12.0 has been deprecated `flatc/1.12.0: WARN: Recipe 'flatc/1.12.0' is deprecated in favor of 'flatbuffers'. Please, consider changing your requirements.` It recommends using flatbuffers instead. However, I couldn't find `flatc.exe` in the flatbuffers recipe.

What is the expected flatbuffer compiling workflow? Am I missing something?
ty

**Comment by Croydon** [comment]
Flatc got unfortunately marked as deprecated before the executable got added into the flatbuffers package. That was a timing issue

There is still a PR open for that, which I can't find right now for some reason.....

Just continue to use the flatc recipe for now

**Comment by p-groarke** [comment]
@Croydon Ah that makes sense. Merging both recipes will be nice indeed, thank you for clarifying.
