### ISSUE TITLE
[request] icc/1.0.0

### ISSUE THREAD

**Issue by redradist** [conan-io/conan-center-index#4049]
**Package Details**

- Package Name/Version: **icc/1.0.0**
- Source code: https://github.com/redradist/Inter-Component-Communication

**More info**

This project has already contained recipe https://github.com/redradist/Inter-Component-Communication/blob/develop/conanfile.py

**Description Of The Library / Tool**

This is a library created to simplify communication between components inside of single application. It is thread safe and could be used for creating components that works in different threads.

**Comment by redradist** [comment]
@SpaceIm @madebr Can somebody check it, and also is there a way to add external recipe from other github repository like in my case ?

**Comment by SpaceIm** [comment]
You mean a submodule? Doesn't seem to be used during build. Anyway in CCI we download archive.

**Comment by redradist** [comment]
> 
> 
> You mean a submodule? Doesn't seem to be used during build. Anyway in CCI we download archive.
> 
> Try to submit a PR if you want to add your project in CCI, it will be easier for us to review.
> 
> Basically you'll have to:
> 
>     * remove `author` and `version` attributes
> 
>     * add `homepage` attribute
> 
>     * add `fPIC` option (and delete this option if windows in `config_options()` + delete if shared in `configure()`)
> 
>     * add a `CMakeLists.txt` wrapper to properly inject flags according to conan profile.
> 
>     * download an archive instead of git clone/checkout
> 
>     * not package shared and static together (shared option should control what is built and installed)
> 
>     * add a test_package
> 
>     * follow CCI recipes layout: https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md
> 
>     * some lines are useless in `package_info()` (all of them except `self.cpp_info.libs`)

@SpaceIm I mean someway to add link to externally supported recipe for package
This recipe is proper !! I tested it separately, I will added it in build system later

Why should I remove `author` ?
Why should I add option `fPIC` ?

**Comment by redradist** [comment]
@SpaceIm Pull-request is added https://github.com/conan-io/conan-center-index/pull/5111

**Comment by redradist** [comment]
PR for this library was merged
