### ISSUE TITLE
[package] yaml-cpp/all: wrong cmake name according to upstream

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#405]
upstream is using `yaml::yaml` and `yaml-cpp` -> https://github.com/jbeder/yaml-cpp/blob/master/CMakeLists.txt#L64
conan is using `yaml-cpp::yaml-cpp` as target name in cmake

**Comment by gocarlos** [comment]
eventually fixing this upstream: https://github.com/jbeder/yaml-cpp/pull/792

**Comment by gocarlos** [comment]
Fixed upstream master... waiting for release

**Comment by gocarlos** [comment]
closing this issue as master upstream is now the same target name as conan

**Comment by uilianries** [comment]
Thanks @gocarlos !
