### ISSUE TITLE
[package] libiconv/1.16: Package build fails on MSVC

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-center-index#4055]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libiconv/1.16**
  * Operating System+version: **Windows Server 2019**
  * Compiler+version: **MSVC 19**
  * Conan version: **conan 1.32.1**
  * Python version: **Python 3.8.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
        os=Windows
	os_build=Windows
	arch=x86_64
	arch_build=x86_64
	compiler=Visual Studio
	compiler.version=16
	build_type=Release
```
### Expected outcome

Package builds successfully

### Actual outcome

Package build errors with
```
/usr/bin/sh: C:/Program: No such file or directory
```

following from 
```
/bin/sh ../libtool --mode=compile --tag=RC windres --target=pe-x86-64 `C:/Program Files/Git/usr/bin/sh.exe ./../windows/windres-options --escape 1.16` -i ./../windows/libiconv.rc -o libiconv.res.lo --output-format=coff
```

### Steps to reproduce (Include if Applicable)

Reproducibility depends on the installation location of various UNIX tools on Windows, as it has to do with Windows Paths handling - but is reproducible on the Github-Actions windows-2019 image

See [Github Actions Log](https://github.com/planetmarshall/conan-center-index/runs/1636277144)

Reproducible in bash or native shell.
```
cd recipes/libiconv/all
conan create . libiconv/1.16@ --build missing --build libiconv
```

### Logs (Include/Attach if Applicable)

[Logs Attached](https://github.com/conan-io/conan-center-index/files/5760113/logs_2.zip)

**Comment by dmn-star** [comment]
I think the `C:/Program Files/` should be quoted like this **"**c:\Program Files**"** . Maybe you can use  the environment variables %ProgramFiles% or %ProgramFiles(x86)% instead.

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as this problem seems to be fixed long time ago.

If the problem remains, do not hesitate to reopen this issue or create a new ticket.
Happy coding 🐸
