### ISSUE TITLE
autotools builds not working on apple silicon native

### ISSUE THREAD

**Issue by maddanio** [conan-io/conan-center-index#4059]
### Package and Environment Details (include every applicable attribute)
  * Operating System+version: **macos 11.0.1**
  * Compiler+version: **apple clang**
  * Conan version: **conan 1.32.1**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

require any library built with autotools, like libjpeg, yasm, iconv...

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
yasm/1.3.0: 
yasm/1.3.0: WARN: Package binary is corrupted, removing: 3eb32b976fb0626f3c40a8b87ace72156aa44204
yasm/1.3.0: WARN: Build folder is dirty, removing it: /Users/daniel/.conan/data/yasm/1.3.0/_/_/build/3eb32b976fb0626f3c40a8b87ace72156aa44204
yasm/1.3.0: ERROR: Package '3eb32b976fb0626f3c40a8b87ace72156aa44204' build failed
yasm/1.3.0: WARN: Build folder /Users/daniel/.conan/data/yasm/1.3.0/_/_/build/3eb32b976fb0626f3c40a8b87ace72156aa44204
ERROR: yasm/1.3.0: Error in build() method, line 67
	autotools = self._configure_autotools()
while calling '_configure_autotools', line 60
	self._autotools.configure(args=conf_args, configure_dir=self._source_subfolder)
	ConanException: Error 77 while executing source_subfolder/configure '--enable-debug=no' '--disable-rpath' '--disable-nls' '--prefix=/Users/daniel/.conan/data/yasm/1.3.0/_/_/package/3eb32b976fb0626f3c40a8b87ace72156aa44204' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' --build=x86_64-apple-darwin --host=aarch64-apple-darwin
```

</details>

**Comment by maddanio** [comment]
at least in the conanfile for yasm ([here](https://github.com/conan-io/conan-center-index/blob/master/recipes/yasm/all/conanfile.py)) there is nothing specific to macos, so it seems that `AutoToolsBuildEnvironment` makes some wrong choices in what to pass to `configure,` namely these arguments to `configure` seem suspicious:
`--build=x86_64-apple-darwin --host=aarch64-apple-darwin`

**Comment by SSE4** [comment]
probably, this is due to the arm64 mis-detection: https://github.com/conan-io/conan/pull/8262

**Comment by maddanio** [comment]
Ah, ok, so guess i will need to test with master?

**Comment by maddanio** [comment]
But does that also fix build arch? My profile seens to require armv8?

**Comment by maddanio** [comment]
ok, tested, didnt change anything :(. btw, why do i need to manually set the profile? shouldnt conan detect it as default?

**Comment by maddanio** [comment]
phew, trying to debug, its all rather confusing. as far as I can see it all goes wrong in `AutoToolsBuildEnvironment._get_host_build_target_flags` which seems should return `None, None, target` if not cross building, but in order to do so it would actually have to find the target settings. these it wants from `get_target_os_arch` from the conan file which would require `os_target` and `arch_target` there. I specify those in my profile, but that doesnt seem to get it into `conanfile.settings` which only contains `os` and `arch`, albeit those two being correct (`Macos` and `armv8` respectively). is there a concept behind all of this and is it documented?

**Comment by maddanio** [comment]
first off: what are target, build, and host os/arch? and to which of these does the plain os/arch settings belong?

**Comment by maddanio** [comment]
ok, so it seems to work if I hack host/target/build to be the gnu triplet derived from the `os` and `arch` settings being `aarch64-apple-darwin`, now just need to hack autotols env in a sensible way...I guess....

**Comment by maddanio** [comment]
ok, actually iconv still fails, will check more on monday...

**Comment by jmarrec** [comment]
Any update on this? I have trouble with libffi on an M1 chip. Seems like the tripplet is badly recognized as `arm-apple-darwin20.3.0` and it fails with missing symbols during testing. If I hack the recipe by adding build=`aarch64-apple-darwin20.3.0` then it seems to work

https://github.com/conan-io/conan-center-index/blob/30d525e52e3ac73a8d9fe7c6204181b606ca830e/recipes/libffi/all/conanfile.py#L126

**Comment by maddanio** [comment]
I gave up and we moved to a modified version of cget

**Comment by SSE4** [comment]
@jmarrec what's your conan profile? what's the output of the following command:
```
conan profile new xxx --detect && conan profile show xxx
```
as I understand, after https://github.com/conan-io/conan/pull/8262 it should contain `arch = armv8`.

I don't have M1 machine to test, but as far as I can tell, there are several evidences it should compute `aarch64-apple-darwin` instead of `arm-apple-darwin` on M1:
#3966
#4692

e.g. both logs contain `--host=aarch64-apple-darwin`.

/cc @a4z @theodelrieu

**Comment by a4z** [comment]
I would say, to spot the problem you need to look into the whole configure part, not just one line

```
   def _configure_autotools(self):
        if self._autotools:
            return self._autotools
        self._autotools = AutoToolsBuildEnvironment(self, win_bash=tools.os_info.is_windows)
        yes_no = lambda v: "yes" if v else "no"
        config_args = [
            "--enable-debug={}".format(yes_no(self.settings.build_type == "Debug")),
            "--enable-shared={}".format(yes_no(self.options.shared)),
            "--enable-static={}".format(yes_no(not self.options.shared)),
        ]
        self._autotools.defines.append("FFI_BUILDING")
        if self.options.shared:
            self._autotools.defines.append("FFI_BUILDING_DLL")
        if self.settings.compiler == "Visual Studio":
            if "MT" in str(self.settings.compiler.runtime):
                self._autotools.defines.append("USE_STATIC_RTL")
            if "d" in str(self.settings.compiler.runtime):
                self._autotools.defines.append("USE_DEBUG_RTL")
        build = None
        host = None
        if self.settings.compiler == "Visual Studio":
            build = "{}-{}-{}".format(
                "x86_64" if "64" in platform.machine() else "i686",
                "pc" if self.settings.arch == "x86" else "w64",
                "cygwin")
            host = "{}-{}-{}".format(
                "x86_64" if self.settings.arch == "x86_64" else "i686",
                "pc" if self.settings.arch == "x86" else "w64",
                "cygwin")
        else:
            if self._autotools.host and "x86-" in self._autotools.host:
                self._autotools.host = self._autotools.host.replace("x86", "i686")
        self._autotools.configure(args=config_args, configure_dir=self._source_subfolder, build=build, host=host)
        return self._autotools
```

because there are packages building with autotools on M1 (have libcurl for example) 

my guess: the else part from `if self.settings.compiler == "Visual Studio":` looks a little bit hardcoded to one architecture

so I do not think that the general statement, that autotools builds not working, can be made

**Comment by jmarrec** [comment]
@SSE4 conan does detect `arch=armv8`

```
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by a4z** [comment]
of course it does @jmarrec  , but you might need to update your conan installation to a recent version

```
[a4z@41012:~/elux](09:45:12)
M1::) conan --version
Conan version 1.34.1

[a4z@41012:~/](09:45:17)
M1::) conan profile new --detect defaultM1
Found apple-clang 12.0
Profile created with detected settings: /Users/a4z/.conan/profiles/defaultM1

[a4z@41012:~/](09:45:34)
M1::) conan profile show defaultM1
Configuration for profile defaultM1:

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by jmarrec** [comment]
I use 1.34.1. I set up this dev machine last friday, so everything is bleeding edge.

**Comment by SSE4** [comment]
okay, seems like we have a bug where autotools host/build/arch isn't correctly computed for M1 in some cases. I can't debug it, as I don't have machine, but I can point places where to look.
tools.get_gnu_triplet should be the right place to check: https://github.com/conan-io/conan-center-index/blob/d01317696fa93e0a8239e17070a75039862c7d50/recipes/json-c/all/conanfile.py#L54
the easiest way to check if it works:
```
$ python                                                                                                                                                                                                                   Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from  conans.client.tools.oss import get_gnu_triplet
>>> get_gnu_triplet('Macos', 'armv8')
'aarch64-apple-darwin'
```

**Comment by a4z** [comment]
```
[a4z@41012:~/](09:45:41)
M1::) python3
Python 3.8.2 (default, Dec 21 2020, 15:06:03)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from  conans.client.tools.oss import get_gnu_triplet
>>> get_gnu_triplet('Macos', 'armv8')
'aarch64-apple-darwin'
```

**Comment by jmarrec** [comment]
(I'd like to provide an answer, but I'm having trouble connecting to that remote machine at the moment... sorry)

**Comment by SSE4** [comment]
no problem, not urgent.
I want to understand where are these coming from first:
```
checking build system type... arm-apple-darwin20.3.0
checking host system type... arm-apple-darwin20.3.0
checking target system type... arm-apple-darwin20.3.0
```
if you have a complete log, it would be nice (e.g. one containing the full command line).
I have a suspicion that conan might not be passing `--build`/`--host`/`--target` at all, but it's auto-detected by `config.sub` or `config.guess` of the project itself.

**Comment by jmarrec** [comment]
```
(py39)irvinemac@git$ conan--version
Conan version 1.34.1

(py39)irvinemac@git$ python --version
Python 3.9.2

(py39)irvinemac@git$ cat ~/.conan/profiles/default 
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

(py39)irvinemac@git$ python
Python 3.9.2 (default, Mar 26 2021, 04:14:33) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from  conans.client.tools.oss import get_gnu_triplet
>>> get_gnu_triplet('Macos', 'armv8')
'aarch64-apple-darwin'
>>> 
```

And I got disconnected by Teamviewer after 30 seconds again... So I can't give a full libffi log. The machine being in another country where everyone is sleeping, there's no much I can do at the moment. I'll try again in 4 hours...

What I can say is that I had built libffi by checking out conan-center index, using my default profile above.

```bash
cd recipes/libffi/all
create create . libffi/3.3@ -b missing
```

**Comment by SSE4** [comment]
probably, it might be possible that it's not a conan fault, see https://github.com/libffi/libffi/pull/576
e.g. 3.3 still contains the old `config.guess`: https://github.com/libffi/libffi/blob/v3.3/config.guess#L1298

**Comment by jmarrec** [comment]
That seems pretty spot-on indeed, good sleuthing @sse4 !

Now is left the question of what conan should do about it?

* work around it by passing `build_type` in conanfile.py
* Patch v3.3 sources to bring the new config.guess and config.sub
* Nothing (which I would dislike very much, 5 years have passed between libffi 3.2.1 and 3.3)

**Comment by SSE4** [comment]
workaround in recipe is okay. you may even explicitly pass `--build`/`--host`/`--target` for M1, or just add the same patch to update `config.sub`/`config.guess` from the upstream.
feel free to submit PR.
I personally prefer second approach (updating `config.guess`), as it should potentially fix more platforms than just M1 - so will make the recipe more portable in general.

**Comment by jmarrec** [comment]
@SSE4 I'll make a patch and submit a PR, thanks for your help.
