### ISSUE TITLE
[feature] Do not allow to raise ConanInvalidConfiguration in `build()`

### ISSUE THREAD

**Issue by mathbunnyru** [conan-io/conan-center-index#4062]
Now as we have the `validate()` method, which is run after the dependency graph has been resolved, raising in the `build()` method should be rare.
I do believe, that the most common reason to raise in the `build()` method is being unable to tell if some dependency has good options for the current package. And `validate()` is exactly for this type of situation.

An example with the change for `mongo-cxx-driver`: https://github.com/conan-io/conan-center-index/pull/4057 

More info: https://blog.conan.io/2020/12/14/New-conan-release-1-32.html

Inspired by fail-fast :)
https://en.wikipedia.org/wiki/Fail-fast

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
I've proposed the changes to the CI library. If any configuration raises a `ConanInvalidConfiguration` the CI will fail asking the user to move the checks from `build()` method to `validate()`. Anyone submitting a PR, even if this error is unrelated to their changes, should be able to fix it 🚀

**Comment by mathbunnyru** [comment]
Great, thanks!

**Comment by jgsogo** [comment]
...and we need to spread the word 🗣️  https://github.com/conan-io/conan-center-index/pull/4634
