### ISSUE TITLE
[question] protobuf/3.9.1: set_cmake_flags in recipe

### ISSUE THREAD

**Issue by jacobandersen** [conan-io/conan-center-index#407]
In the protobuf/3.9.1 conanfile.py:51, the set_cmake_flags property is set to True. Is this necessary - and why? It is breaking my build system when I use it with profiles building for Android, as it overrides (and deletes) CXX_FLAGS set in my Conan profile.

If it is not possible to set this property to false by default, would it be okay to make it optional. I could provide a pull request if need be?

**Comment by uilianries** [comment]
I can't remember why we did it, but I'll check it. Thanks for reporting.

**Comment by jacobandersen** [comment]
Much appreciated, thanks :-)
