### ISSUE TITLE
[package] boost/1.75.0: Boost.Locale is not built with i18n_backend=icu

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan-center-index#4073]
Hello,

It seems this commit (552189c144dea0ef9287c208a2cc5cf03a568e62) broke Boost.Locale build.
It was working well two weeks ago.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.75.0**
  * Operating System+version: **macOS x86_64 BigSur**
  * Compiler+version: **apple-clang 12.0**
  * Conan version: **conan 1.32.1**
  * Python version: **Python 3.8.5**

### Steps to reproduce (Include if Applicable)

`conan install boost/1.75.0@ --build missing -o boost:i18n_backend=icu -o boost:without_locale=False`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

b2 output
```
- has statx syscall        : no
    - has_icu builds           : no
    - zlib                     : yes
    - bzip2                    : yes
    - icu                      : no
    - icu (lib64)              : no
- Boost.Locale needs either iconv or ICU library to be built.
- Boost.Locale needs either iconv or ICU library to be built.
```

conan output
```
boost/1.75.0: WARN: Boost component 'locale' is missing libraries. Try building boost with '-o boost:without_locale'.
ERROR: boost/1.75.0: Error in package_info() method, line 1331
	raise ConanException("These libraries were expected to be built, but were not built: {}".format(non_built))
	ConanException: These libraries were expected to be built, but were not built: {'boost_locale'}
```

</details>

**Comment by theodelrieu** [comment]
I've dug a bit and I've another build issue on Windows, Boost.Locale ICU detection is broken for several reasons:

* It looks for `icuXX` lib names, but on Windows ICU adds prefixes and suffixes
* One could pass `ICU_LINK` to workaround that, but Boost.Regex emits an error when `ICU_LINK` is defined (https://github.com/boostorg/regex/commit/fc4dc17dc745a9fc4ab1849cef3710354a6b7782#diff-322788b77c72dedcc9b4a12bf0233ceb8451b4a6baa6d851173ecd5320ac14aeR38)

There's several solutions:

* Strip prefixes/suffixes from ICU lib names
* Patch Boost.Locale `Jamfile.v2` to take a `LOCALE_ICU_LINK` var, and pass the correct link flags to it

I'd like to hear your input on this, thanks.

**Comment by Cogitri** [comment]
Unfortunately I've hit this too, even with `boost:i18n_backend_icu=True` set `boost::locale:::localization_backend_manager::global().get_all_backends()` returns an empty vector.

**Comment by Cogitri** [comment]
Actually, it appears that the ICU backend works when building with boost:shared=True and ich:shared=True

**Comment by uilianries** [comment]
Closing this issue due its age and the reported error seems be gone:

Full build logs checking the current issue are available here: https://gist.github.com/uilianries/17bc2863edbcb00f999da1ffb7b8318c

Please, feel free to re-open it in case this error still persists.
