### ISSUE TITLE
[question] [CI] How can i know which CMake version was used to build?

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan-center-index#4092]
Please see also https://github.com/conan-io/conan-center-index/pull/4048#issuecomment-754172393

**Comment by ericLemanissier** [comment]
as a debug mean, you can use `message(">>>>>>>> CMAKE_VERSION ${CMAKE_VERSION}")` in your CMakeLists, or add a call `self.run("cmake --version")` in your recipe, and check what's on the log.

**Comment by Croydon** [comment]
For Windows/macOS it just be mentioned in the changelog when it gets updated https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md

For Linux it can be looked up, for example, here:

https://github.com/conan-io/conan-docker-tools/blob/master/update_cmake.py#L7
https://github.com/conan-io/conan-docker-tools/blob/master/clang_11/Dockerfile#L6
