### ISSUE TITLE
[request] libsrtp/2.3.0

### ISSUE THREAD

**Issue by triangulumlabs** [conan-io/conan-center-index#4099]
### Package Details
  * Package Name/Version: **libsrtp/2.3.0**
  * Website: **https://github.com/cisco/libsrtp**
  * Source code: **https://github.com/cisco/libsrtp**

### Description Of The Library / Tool
This package provides an implementation of the Secure Real-time Transport Protocol (SRTP), the Universal Security Transform (UST), and a supporting cryptographic kernel. The SRTP API is documented in include/srtp.h, and the library is in libsrtp2.a (after compilation).

**Comment by blackliner** [comment]
I will give this a try

**Comment by blackliner** [comment]
https://github.com/conan-io/conan-center-index/pull/4119
