### ISSUE TITLE
[package] boost/1.75.0: slow no-op

### ISSUE THREAD

**Issue by Enhex** [conan-io/conan-center-index#4203]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.75.0**
  * Operating System+version: **Manjaro**
  * Compiler+version: **Clang 11**
  * Conan version: **conan 1.32.1**
  * Python version: **Python 3.9.1**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=11
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
LD=ld.lld
```

### Steps to reproduce (Include if Applicable)
Boost 1.75.0 introduced a several seconds delay when checking if the package is already installed.

In the logs you can see that it stops for ~6 seconds after the line:
`boost/1.75.0: Library layout suffix: ''`

On Windows 10 it happens after the line:
`boost/1.75.0: Disabled magic autolinking (smart and magic decisions)`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
[16:21:46] Installing (downloading, building) binaries...
[16:21:46] brotli/1.0.9: Already installed!
[16:21:46] bzip2/1.0.8: Already installed!
[16:21:46] generic_serialization/master@enhex/stable: Already installed!
[16:21:46] glad/0.1.34: Already installed!
[16:21:46] libiconv/1.16: Already installed!
[16:21:46] libiconv/1.16: Appending PATH environment var: /home/desktop/.conan/data/libiconv/1.16/_/_/package/2ffa9ae5fcbd719c06fb12a94eee2561d60590e5/bin
[16:21:46] opengl/system: Already installed!
[16:21:46] rang/master@enhex/stable: Already installed!
[16:21:46] strong_type/master@enhex/stable: Already installed!
[16:21:46] xorg/system: Already installed!
[16:21:47] zlib/1.2.11: Already installed!
[16:21:47] boost/1.75.0: Already installed!
[16:21:47] boost/1.75.0: Library layout suffix: ''
[16:21:53] freetype/2.10.4: Already installed!
[16:21:53] glfw/3.3.2: Already installed!
[16:21:53] Deco/master@enhex/stable: Already installed!
[16:21:53] nanovg/master@enhex/stable: Already installed!

```

</details>

**Comment by TheStormN** [comment]
On Windows the slowdown is even greater...

**Comment by madduci** [comment]
I've also found out that the version 1.75.0 doesn't work on Apple/clang target. See here for the error as example (previously, with Boost 1.73.0 was working perfectly) https://github.com/madduci/openE57/runs/1707161256?check_suite_focus=true

**Comment by Enhex** [comment]
the offending code is this for loop:
https://github.com/conan-io/conan-center-index/blob/fb7071db584ccc4685c753f34683160249b27cd9/recipes/boost/all/conanfile.py#L1291

@madebr @mathbunnyru @axalon900 you guys are shown as the authors of the commit it was added in, perhaps
one of you is familiar with the code and know how to fix it?

**Comment by mathbunnyru** [comment]
Thanks for the tip, @Enhex, that was helpful.
I made the PR, which will resolve the issue.

@Enhex @madduci @TheStormN it would be great, if you could test my patch on your machine, but I think everything should work great.

**Comment by TheStormN** [comment]
@mathbunnyru Thank you for the fix! I hope it gets merged soon. However I have a question. For example why the previous version of the Boost package didn't had that issue if the caching was not present there?

**Comment by madduci** [comment]
hi, thanks for the fix, I don't have myself a mac system, I was relying on the official recipe of boost on GitHub Actions.

**Comment by mathbunnyru** [comment]
> @mathbunnyru Thank you for the fix! I hope it gets merged soon. However I have a question. For example why the previous version of the Boost package didn't had that issue if the caching was not present there?

The number of libraries increased.
`_all_dependent_modules` in a way that it doesn't reuse previous computations.
So, if you have a new module added and it depends on the previous modules, you will end up reading the file much more times, than you expected.
And I think 1.75 was a version, where a number of file reads was so big, that we started to notice it.

Note: it is possible to implement cache for this function as well. But I would like to keep it simple, because boost is already quite complicated.

**Comment by mathbunnyru** [comment]
> hi, thanks for the fix, I don't have myself a mac system, I was relying on the official recipe of boost on GitHub Actions.

It happens not only on Mac, but on all platforms. So if you have a setup where you can check it, it would be great.

**Comment by TheStormN** [comment]
@mathbunnyru I see, thank you for the explanation! After this gets merged I wouldn't mind to also do caching for the other function. :P

**Comment by Enhex** [comment]
tested it and there's no noticeable delay now :+1:

**Comment by mathbunnyru** [comment]
> tested it and there's no noticeable delay now 👍

Great, thanks for the test 👍

**Comment by TheStormN** [comment]
Does someone know when the fix will show up in Conan repo?

**Comment by andioz** [comment]
Normally it should be available after some hours, at least on next day. Don't forget to use `--update` flag with `conan install`, or remove `~/.conan/data/boost/1.75.0` to be sure.

**Comment by TheStormN** [comment]
I've deleted all the cache but still no luck. I also verified the revision here https://conan.io/center/boost and it's still only one. From my observations a new revision should come up when the new recipe is published.

**Comment by andioz** [comment]
Yeah, sometimes it takes more time as expected, depending on CD system overload... Especially `boost` is a huge library with many versions supported, and for 3 platforms with different compilers... Pre-building takes time.

If you are in a hurry, make a local copy of the recipes repo and install it from local filesystem, should work the same way.
