### ISSUE TITLE
[package] libjpeg/9d: does not expose transupp.h

### ISSUE THREAD

**Issue by nminkov** [conan-io/conan-center-index#4217]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libjpeg/9d**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio**

<details><summary>Conan recipe does not expose transupp.h</summary>
transupp.h is part of libjpeg, however the recipe does not copy it to "includes"  directory (jinclude.h is also needed). This .h necessary for lossless jpeg image transformations (e.g. rotation without reencode)

Patch
```
diff --git "a/recipes/libjpeg/all/conanfile.py" "b/recipes/libjpeg/all/conanfile.py"
index fc42f440..bda9352b 100644
--- "a/recipes/libjpeg/all/conanfile.py"
+++ "b/recipes/libjpeg/all/conanfile.py"
@@ -12,8 +12,8 @@ class LibjpegConan(ConanFile):
     homepage = "http://ijg.org"
     exports_sources = ["Win32.Mak", "patches/**"]
     settings = "os", "arch", "compiler", "build_type"
-    options = {"shared": [True, False], "fPIC": [True, False]}
-    default_options = {"shared": False, "fPIC": True}
+    options = {"shared": [True, False], "fPIC": [True, False], "transform_supported": [True, False]}
+    default_options = {"shared": False, "fPIC": True, "transform_supported" : False}
 
     _autotools = None
 
@@ -105,7 +105,11 @@ class LibjpegConan(ConanFile):
         if self.settings.compiler == "Visual Studio":
             for filename in ["jpeglib.h", "jerror.h", "jconfig.h", "jmorecfg.h"]:
                 self.copy(pattern=filename, dst="include", src=self._source_subfolder, keep_path=False)
-            
+
+            if self.options.transform_supported:
+                for filename in ["jinclude.h", "transupp.h", "jconfig.h", "jmorecfg.h"]:
+                    self.copy(pattern=filename, dst="include", src=self._source_subfolder, keep_path=False)
+
             self.copy(pattern="*.lib", dst="lib", src=self._source_subfolder, keep_path=False)
             if self.options.shared:
                 self.copy(pattern="*.dll", dst="bin", src=self._source_subfolder, keep_path=False) 
```

</details>

PS. This is my first report, hopefully respects the correct format and rules.

**Comment by madebr** [comment]
The header of ´transupp.h´ says:
´´´
/*
 * transupp.h
 *
 * Copyright (C) 1997-2019, Thomas G. Lane, Guido Vollbeding.
 * This file is part of the Independent JPEG Group's software.
 * For conditions of distribution and use, see the accompanying README file.
 *
 * This file contains declarations for image transformation routines and
 * other utility code used by the jpegtran sample application.  These are
 * NOT part of the core JPEG library.  But we keep these routines separate
 * from jpegtran.c to ease the task of maintaining jpegtran-like programs
 * that have other user interfaces.
 *
 * NOTE: all the routines declared here have very specific requirements
 * about when they are to be executed during the reading and writing of the
 * source and destination files.  See the comments in transupp.c, or see
 * jpegtran.c for an example of correct usage.
 */
´´´

It's not really a standard header.
Ubuntu packages also don's install it: https://packages.ubuntu.com/xenial/amd64/libjpeg9-dev/filelist

Can you please explain the reasons behind your need for it?

**Comment by nminkov** [comment]
Actually, my patch is not enough to add it. The make file must be changed too and that will break the libjpeg.lib deployment logic.
So you are right. I must find another way.

**Comment by madebr** [comment]
Modifying `automake.am` + running `autoreconf` is indeed a big change.
Though, it is always possible to manually copy some headers to the include directory.
```python
self.copy("transupp.h", src=self._source_subfolder, dst="include"
```
I'm just surprised your need for it, since no distros have it available.

**Comment by nminkov** [comment]
I've been using it forever to perform lossless image transformations on JPEG files. E.g. rotate jpeg without reencoding it. The same functionality from jpegtrans app, built in in any app.  Before using conan, I was building manually libjpeg and always added the transupp in the lib itself. Now I am inline including it, but not great because have keep conan version and local version of jpeg files in sync. 

For inclusion in conan recept, it's complicated because transupp.c must be added in the build process. The patch that I posted adds just transupp.h and jinclude.h for copy to includes dir, but not transupp.c to Makefile.am, which is not difficult in itself, but is a concept question.  I am all for it, but can understand if you don't do it.

**Comment by madebr** [comment]
I think I understand your problem.
I don't think linking `transupp.c` inside the libjpeg library is not the correct approach.
We want to keep the library as *standard* as possible.

What we can do is e.g.:
- copy `transupp.c` to `self.package_folder/res` and `transupp.h` to `self.package_folder/include`.
- build `transupp.c` ourself in an extra (optional) library named e.g. `jpegextra`.

I think my first suggestion is the easiest.
This would require you to add this to you cmake script:
```cmake
add_executable(your_exe your_source.c
    "${CONAN_LIBJPEG_ROOT}/res/transupp.c"
)
```
(there is also `CONAN_RES_DIRS_LIBJPEG`)

**Comment by nminkov** [comment]
I think your suggestion is a perfect compromise madebr! Please also include jinclude.h which is needed for transupp compilation.
Thank you!!!
