### ISSUE TITLE
[question] Using libraries that stopped using semver

### ISSUE THREAD

**Issue by mjvankampen** [conan-io/conan-center-index#4222]
For example Google test will stop doing releases (https://github.com/google/googletest/issues/3124). What is the best way forward in this case?

**Comment by Croydon** [comment]
https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases

**Comment by mjvankampen** [comment]
So it is no issue to combine both ways of tagging in a single package?

**Comment by Croydon** [comment]
No problem. We are already doing that for a dozens of packages. `cci.date` and semver versions can co-exist. That said `cci.date` versions will be ignored for version ranges if you use them in your conanfiles
