### ISSUE TITLE
[request] pybind/2.4.3

### ISSUE THREAD

**Issue by darcamo** [conan-io/conan-center-index#424]
### Package Details
  * Package Name/Version: **pybind/2.4.3**
  * Changelog: **Not available**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Note**: The last version of pybind in conan-center is 2.3.0. After that version, four other versions were released upstream: 2.4.0, 2.4.1, 2.4.2 and finally 2.4.3.

**Comment by uilianries** [comment]
Hi @darcamo !

Thanks for your request, are you interested in helping us with this package? Pybind recipe is already available in Conan Community, so basically you need to copy from there a follow the Wiki rules.

https://github.com/conan-community/conan-pybind11
