### ISSUE TITLE
[package] yasm/1.3.0: unhashable type: 'SettingsItem'

### ISSUE THREAD

**Issue by rea-yseop** [conan-io/conan-center-index#4246]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **yasm/1.3.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 2019**
  * Conan version: **conan 1.30.1**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
os=Windows
os_build=Windows
compiler=Visual Studio
compiler.version=16
build_type=Release

[build_requires]
yasm/1.3.0@_/_#9a335fbdb76566ef33759a9cdedf72b8
```

### Steps to reproduce (Include if Applicable)
conan install yasm/1.3.0@ --build yasm --update

### Logs (Include/Attach if Applicable)
![image](https://user-images.githubusercontent.com/46320869/104482898-c95b7880-55c7-11eb-9598-f7eb7b9ed046.png)

I am aware that this exact same issue has been reported and solved already https://github.com/conan-io/conan-center-index/issues/3257. 
However the default revision installed is `36883a5983014d78c958af86a4406547` which does not include the fix.
It still installs the above revision even when adding a specific revision in `build_requires` and setting `revisions_enabled=1 ` in my config (https://docs.conan.io/en/latest/versioning/revisions.html)

**Comment by Croydon** [comment]
I had the same error quite some time ago (don't remember the details)

Are we sure that this isn't a regression in Conan?

**Comment by rea-yseop** [comment]
> I had the same error quite some time ago (don't remember the details)
> 
> Are we sure that this isn't a regression in Conan?
> 
> Newer Conan versions shouldn't break recipes

Thanks. So i tried to change to 1.32.1 and it worked the first time. But when i changed the revision again, it stayed the same as before. And I removed the package and used --update. Tried to mess by reinstalling conan and different versions of it but still fails.

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as new yasm revision of this version already solves this problem.
If problem persists, do not hesitate to reopen this issue or create a new ticket.
Happy coding 🐸
