### ISSUE TITLE
[service] Access to CI pipeline

### ISSUE THREAD

**Issue by n1-b** [conan-io/conan-center-index#428]
Hi. I want to improve CI scripts (PR pipeline). How can i get access for it?
Should i use appveyor / travis instead of Jenkins?
p.s. are current scripts running on the same server that https://conan-ci.jfrog.info/?
Thank you in advance.

**Comment by danimtb** [comment]
Hi @n1-b,

The Jenkins scripts generating the packages are not available as answered here #336. What do you mean with "improve CI scripts"?

Do you have a feature request for the service or you just want to improve the recipes?

**Comment by n1-b** [comment]
I talk about ```conan-center-bot``` logic (where/how to build/test/upload recipes).

I think that recipes should build with a lot compilers(I want to configure this), but [conan-center](https://bintray.com/conan/conan-center) may contains only recipes without prebuilt files.

**Comment by danimtb** [comment]
This service supports a set of configurations described here https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

Those configurations are internal and users access nor modify them.

In case you want to generate packages massively with your machine or infrastructure, I'd suggest you to take a look at the [conan-io/conan-package-tools](https://github.com/conan-io/conan-package-tools) project

**Comment by n1-b** [comment]
> Those configurations are internal and users access nor modify them.

I understand it, Anyway, I will create ```travis.yml``` if you accept it and enable check on PRs.

> In case you want to generate packages massively with your machine or infrastructure,

I haven't problems with a local build environment. I want to improve this repo.

**Comment by danimtb** [comment]
There is no need to add travis or appveyor files. When a PR is submitted a Jenkins job will be triggered and you will recipe reports in the PR github comments and links to the logs with the errors.

**Comment by n1-b** [comment]
Starting from begin. How can i get access to Jenkins job files? (i see that they private / internal).

**Comment by danimtb** [comment]
No, it is not possible, sorry 😕

**Comment by ericLemanissier** [comment]
job logs are freely accessible, just not live : see `Access to all the logs` in https://github.com/conan-io/conan-center-index/pull/462#issuecomment-564306204

**Comment by n1-b** [comment]
Logs are not enough.
