### ISSUE TITLE
[package] icu/68.2 does not compile on Windows with MSVC

### ISSUE THREAD

**Issue by tjwrona** [conan-io/conan-center-index#4301]
I am trying to use the ICU library to add unicode support to one of my projects but I get an error when conan install tries to compile it.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **icu/68.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019 16.9.0 Preview 2**
  * Conan version: **conan 1.29.2**
  * Python version: **Python 3.7.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
I am using the `cmake-conan` library to automatically detect the compiler info so I'm not sure how to get the exact profile info used. https://github.com/conan-io/cmake-conan

At the start of the run it does spit out this information though that might be what you are looking for:
```
1> [CMake] Configuration:
1> [CMake] [settings]
1> [CMake] arch=x86_64
1> [CMake] arch_build=x86_64
1> [CMake] build_type=Debug
1> [CMake] compiler=Visual Studio
1> [CMake] compiler.cppstd=17
1> [CMake] compiler.runtime=MDd
1> [CMake] compiler.version=16
1> [CMake] os=Windows
1> [CMake] os_build=Windows
1> [CMake] [options]
1> [CMake] [build_requires]
1> [CMake] [env]
```

### Steps to reproduce (Include if Applicable)
ICU fails near the end of the build during the `conan install` step

```
1> [CMake] icu/68.2: make[0]: Making `all' in `data'
1> [CMake] icu/68.2: mkdir ./out/build
1> [CMake] icu/68.2: mkdir ./out/build/icudt68l
1> [CMake] icu/68.2: Unpacking ../../source/data/in/icudt68l.dat and generating out/tmp/icudata.lst (list of data files)
1> [CMake] icu/68.2: make[0]: Making `all' in `ThisIsATest'
1> [CMake] icu/68.2: /bin/sh: line 10: cd: ThisIsATest: No such file or directory
1> [CMake] icu/68.2: make: *** [Makefile:153: all-recursive] Error 1
1> [CMake] icu/68.2: icu/68.2: 
1> [CMake] ERROR: Package 'fe49e44f647bd3bafc9ae07ede6a7bfcf148996c' build failed
1> [CMake] icu/68.2: WARN: Build folder C:\Users\tjwro\.conan\data\icu\68.2\_\_\build\fe49e44f647bd3bafc9ae07ede6a7bfcf148996c
1> [CMake] ERROR: icu/68.2: Error in build() method, line 101
1> [CMake] 	self.run(command, win_bash=tools.os_info.is_windows)
1> [CMake] 	ConanException: Error 2 while executing make --silent -j 8
1> [CMake] CMake Error at out/build/x64-Debug (default)/conan.cmake:402 (message):
1> [CMake]   Conan install failed='1'
1> [CMake] Call Stack (most recent call first):
1> [CMake]   out/build/x64-Debug (default)/conan.cmake:497 (conan_cmake_install)
1> [CMake]   out/build/x64-Debug (default)/_deps/cmakemodules-src/modules/tnt/project/Project.cmake:139 (conan_cmake_run)
1> [CMake]   CMakeLists.txt:21 (tnt_project_ConanInstall)
1> [CMake] -- Configuring incomplete, errors occurred!
```

This issue is likely related to ICU not working with Boost: https://github.com/conan-io/conan-center-index/issues/4297

**Comment by tjwrona1992** [comment]
I created a `conanfile.txt` that does nothing more than require `icu/68.2`.

conanfile.txt:
```
[requires]
icu/68.2
```

Then I did a `conan install . --build` to test it out. I don't think it used the same `profile` settings that the `cmake-conan` run used because it failed for a different reason, but this build also failed. I have attached the log (The conan profile settings are listed at the top)

[log.txt](https://github.com/conan-io/conan-center-index/files/5832932/log.txt)

**Comment by SpaceIm** [comment]
> I created a `conanfile.txt` that does nothing more than require `icu/68.2`.
> 
> conanfile.txt:
> 
> ```
> [requires]
> icu/68.2
> ```
> 
> Then I did a `conan install . --build` to test it out. I don't think it used the same "profile" settings that the `cmake-conan` run automatically detected because it failed for a different reason, but this build also failed. I have attached the log (The conan profile settings are listed at the top)
> 
> [log.txt](https://github.com/conan-io/conan-center-index/files/5832932/log.txt)

msys2 fails to build (actually it seems to fail to access several urls). There is no information about icu in this log. Try to build icu only.

**Comment by dmn-star** [comment]
>msys2 fails to build (actually it seems to fail to access several urls). 

You can try the new msys2 version.
https://github.com/conan-io/conan-center-index/pull/4286

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as `icu/68.2` is no longer supported by CCI.

If problem persists in newer issues, do not hesitate create a new ticket.
Happy coding 🐸
