### ISSUE TITLE
[package] xz_utils/5.2.5: Cannot build with Visual Studio Build Tools

### ISSUE THREAD

**Issue by db4** [conan-io/conan-center-index#4318]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **xz_utils/5.2.5**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio Build Tools 2017**
  * Conan version: **conan 1.32.1**

I'm trying to rebuild the package from sources using `conan install xz_utils/5.2.5@ --build xz_utils`. On Visual Studio Professional 2017 it builds OK, but on Visual Studio Build Tools 2017 it fails with

```
xz_utils/5.2.5: Calling build()
xz_utils/5.2.5: Skipped sln project upgrade
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  tuklib_cpucores.c
  tuklib_physmem.c
  check.c
  crc32_fast.c
  crc32_table.c
  crc64_fast.c
  crc64_table.c
  sha256.c
c:\users\containeradministrator\.conan\data\xz_utils\5.2.5\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\source_subfolder\src\common\sysdefs.h(33): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\..\src\liblzma\check\crc32_fast.c) [C:\Users\ContainerAdministrator\.conan\data\xz_utils\5.2.5\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\source_subfolder\windows\vs2017\liblzma.vcxproj]
```
Obviously, `cl.exe` cannot find system includes. And I see why:

https://github.com/conan-io/conan-center-index/blob/d54d5dfd77845558c67c8ff28b393004d4796adb/recipes/xz_utils/all/conanfile.py#L80

Removing `use_env=False` resolves the issue. So my question to @uilianries: why did you use this option when created the recipe? No other msbuild-based recipe in conan-center-index ever uses it.

**Comment by madebr** [comment]
Feel free to open a pr removing the option.
Your suggested fix looks fine to me.
