### ISSUE TITLE
[Eigen] Licensing issues

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#4333]
Eigen recipe advertises itself as being `MPL-2.0` licenced.
https://github.com/conan-io/conan-center-index/blob/b19b07beef5915423f6571db1045fb0bd7bab92f/recipes/eigen/all/conanfile.py#L11

This is only true if `EIGEN_MPL2_ONLY` is defined. Otherwise it includes code licenced under `LGPL`
http://eigen.tuxfamily.org/index.php?title=Main_Page (See Licence entry)

We could enforce the licence by adding `self.cpp_info.defines = ["EIGEN_MPL2_ONLY"]` to the Eigen recipe, but this could break other packages that uses the LGPL portions of Eigen.
A differnt approach would be to make the inclusion of that define opt-in, with a conan option. In that case I guess we should change the licence in the recipe to LGPL?

Can the recipe change the licence depending on a conan option? 

I'm opening this thread to get some feedback on what would be the best solution, since if I understand correctly, linking against LGPL code staticaly forces you to open source your project and therefore some people don't want to use it.

**Comment by intelligide** [comment]
> Can the recipe change the licence depending on a conan option?

Yes and (probably) no. I don't think it is possible to change the value of the `license` field based on an option (however, the `license` field can be a list of string in case of multiple licenses). But it's possible to define `EIGEN_MPL2_ONLY` with an option.

**Comment by ericriff** [comment]
In that case we can make
```
licence = "MPL-2.0" , "LGPL"
..
options = 'MLP2_only'
defalut_options = {'MLP2_only': False} #So we maintain current package behavior
..
package_info(self):
  if self.options.MLP2_only:
    self.cpp_info.defines = ["EIGEN_MPL2_ONLY"]
```
If the comunity is OK with this I'll open a PR.

**Comment by intelligide** [comment]
Looks good to me. (use lowercase option like `mpl2_only`)

**Comment by ericriff** [comment]
I know that the convention is lowercase for options, but I think MPL being an acronym should be capitalized.
