### ISSUE TITLE
[service] Request table of contents in markdown docs in conan-center-index

### ISSUE THREAD

**Issue by claremacrae** [conan-io/conan-center-index#4367]
When looking at long pages like [how_to_add_packages.md](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) it's currently necessary to scroll down the entire page, looking at headings, to establish whether the content one is looking for is present.

It would be really nice to be able to glance at a table of contents to quickly the structure and content of any page in the CCI markdown docs.

**Comment by claremacrae** [comment]
If acceptable, I'm happy to add a pull-request to automate this, on every push to the main branch, using [mdsnippets](https://github.com/simonCropp/MarkdownSnippets)...

**Comment by claremacrae** [comment]
Other good example pages:

https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md
https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md

**Comment by memsharded** [comment]
I think this would be a nice feature.

**Comment by claremacrae** [comment]
Thanks - I've implemented it for several projects - it would be really easy for me to do...

**Comment by claremacrae** [comment]
And I'd love to help :-)

**Comment by danimtb** [comment]
agree this could be very convenient

**Comment by claremacrae** [comment]
One issue to be aware of is the special way that anchors are provided in the knowledge-base page... to make sure the links in to that from the hooks are kept working...

**Comment by claremacrae** [comment]
I closed that PR due to bot policies... will create two separate ones instead....

**Comment by claremacrae** [comment]
Based on bot feedback on the first PR, I created 3 separate ones:

- https://github.com/conan-io/conan-center-index/pull/4372
- https://github.com/conan-io/conan-center-index/pull/4373
- https://github.com/conan-io/conan-center-index/pull/4375

Please can I ask someone here to look at the builds of those issues - I suspect I'm touching directories that users are not expected to touch - I've done the best I can for now...

**Comment by claremacrae** [comment]
I'm closing this, 3 weeks on...

The PR for adding the tables of contents was added - thanks! - And I've closed the tickets around automating the update process.

I can do the updating manually, periodically - using the mdsnippets command. See the description of #4594.
