### ISSUE TITLE
[package] glfw/3.3.2: cannot specify link libraries for target "glfw" 

### ISSUE THREAD

**Issue by matheusgomes28** [conan-io/conan-center-index#4369]
GLFW fails to build on my pipeline, failing at the CMake configure stage with the following error:

```
CMake Error at /conan/.conan/data/glfw/3.3.2/_/_/package/8079fc83fb68fa859e894d3bcf2b6f0ef0e129c3/lib/cmake/conan-official-glfw-targets.cmake:3 (target_link_libraries):
  Cannot specify link libraries for target "glfw" which is not built by this
  project.
Call Stack (most recent call first):
  build/Findglfw3.cmake:187 (include)
  graphics/CMakeLists.txt:3 (find_package)
```
It is interesting because the very same project pulls `glfw` fine with `conan`. So when I build this project on my local machines (Windows and Ubuntu, both have the same version of `conan` as specified below), there are no issues.

Is my runner missing something? As far as I know, I have installed all the system dependencies.

### Package and Environment Details (include every applicable attribute)
  * Operating System+version: **Linux Ubuntu**
  * Compiler+version: **GCC 7**
  * Conan version: **conan 1.33**

### Conan profile 
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

**Comment by SpaceIm** [comment]
Interesting.

I can't reproduce this error with `cmake`, `cmake_find_package` or `cmake_find_package_multi` on Windows with Visual Studio.

Which conan generators? Could your `CMakeLists.txt`?

**Comment by matheusgomes28** [comment]
I cannot reproduce it on my local machines either. However, when `ssh`ing into my [pipeline's docker image](https://hub.docker.com/layers/134542567/mattgomes28/wavytune/comp86_64v1/images/sha256-a4b85d9df3eace48fa37f073444374279a0f3348a8bbc2c4b13b3f58d1ff48e8?context=explore), then I can reproduce it when cloning and trying to build my personal project.

The generator I am using is `cmake_find_package`. Here are copies of the relevant `CMakeLists.txt` (but you can find the whole picture in [my repo](https://github.com/matheusgomes28/wavytune_cmake/).

### root cmake lists
```
cmake_minimum_required(VERSION 3.10)
project(wavy_tune VERSION 0.1 LANGUAGES CXX)

find_package(GLEW REQUIRED)

add_subdirectory(data_structures)
add_subdirectory(fourier)
add_subdirectory(graphics)
add_subdirectory(matrix)

# Only build if the options were given
if(CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME)
    include(CTest)
endif()

if(CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME AND BUILD_TESTING)
    add_subdirectory(tests)
endif()

add_executable(wavy_main source/main.cpp)
target_link_libraries(wavy_main PRIVATE
    GLEW::GLEW
    data_structures
    fourier
    graphics
    matrix)
```
### failing subdirectory's CMakeLists (graphics dir)
```

find_package(GLEW REQUIRED)
find_package(glm REQUIRED)
find_package(glfw3 REQUIRED)
find_package(Microsoft.GSL REQUIRED)

add_library(graphics
	Camera.cpp
	Shader.cpp
	window.cpp
	ShaderProgram.cpp)

target_include_directories(graphics PUBLIC include)

target_link_libraries(graphics PUBLIC 
  GLEW::GLEW
	data_structures
	glm::glm
	glfw::glfw)

target_link_libraries(graphics PRIVATE
	Microsoft.GSL::GSL)
```

Thanks for taking your time @SpaceIm

**Comment by matheusgomes28** [comment]
Digging a little deeper, the contents of the CMake file where it's failing is copied below.

```
if(TARGET glfw::glfw AND NOT TARGET glfw)
    add_library(glfw INTERFACE IMPORTED)
    target_link_libraries(glfw INTERFACE glfw::glfw)
endif()
```
This implies that the target `glfw` is not being set by the `add_library(glfw INTEFACE IMPORTED)` line. Perhaps it's expecting the target to be set somewhere else? Is there a system dependency it's looking for? Maybe my runner is missing something.

**Comment by SpaceIm** [comment]
This is a recent addition to glfw recipe, allowing to provide official CMake importe target for glfw (which is not `glfw::glfw` but `glfw` without namespace). I don't understand why it fails in this specific environment.

**Comment by matheusgomes28** [comment]
I saw the addition and I was also trying to understand why it was failing only in my basic runner. I can see that my runner doesn't have any system `glfw` targets interfering. 

If I understand well, lines 2 & 3 of that `cmake` file are aliasing `glfw::glfw` to `glfw`. Perhaps using the `add_library(<name> ALIAS <target>)` version would help. 

I'll try this and let you know what happens.

**Comment by matheusgomes28** [comment]
Did not realise you cannot alias an imported target with CMake. Another great random restriction by CMake :smile:

**Comment by matheusgomes28** [comment]
@SpaceIm I think I figured out what the issue is. It is not a bug on the recipe or the CMake files you created/edited.

### Aliases Restrictions On Imported Targets

It turns out that CMake didn't allow aliases to be created for imported targets until recently. Googling "cmake alias imported targets"  will bring up quite a few forum querries with the same issue. Perhaps, under the hood the `add_library(<alias> ALIAS <target>)` used the same technique you used in the "conan-official-glfw-targets.cmake", i.e. creating an `IMPORTED` target for `glfw` and then adding `glfw::glfw` as an `INTERFACE` dependency, which fails in older verisons of CMake.

Now, my runner was using CMake 3.10 and both `add_library(<alias> ALIAS <target>)` and your method of simulating this alias fail on that version. 

On both my local machines, the CMake version is 3.16 and both of the aliasing methods work. So we know this "restriction" was removed along the way.

### The Fix
Needless to say, if you are getting this same issue it implies that your CMake is not allowing aliases to `IMPORTED` targets. So **just upgrade CMake** to the latest version and the problem should _hopefully_ disappear. 

### Notes
Perhaps we can find which version of CMake started allowing aliases to `IMPORTED` targets and require that version in your `conanfile`. I'm not even sure if `conan` allows these version hints for CMake, but it would definitely help in this case.

Also, since an alias is all you need for `glfw::glfw`, perhaps you can use the `add_library(glfw ALIAS glfw::glfw)` line instead of we currently have in the CMake file. The error message you would get with that would certainly be more helpful than the obscure, not helpful error I got.

**Comment by SpaceIm** [comment]
Does it work with `set_property(TARGET glfw PROPERTY INTERFACE_LINK_LIBRARIES glfw::glfw)` instead of `target_link_libraries(glfw INTERFACE glfw::glfw)`?

**Comment by matheusgomes28** [comment]
@SpaceIm  it does indeed. Tried with CMake 3.10 where the alias is not being allowed. Good thinking, you might want to push that.

**Comment by SpaceIm** [comment]
Great ! I've opened https://github.com/conan-io/conan-center-index/pull/4374

**Comment by SpaceIm** [comment]
@matheusgomes28 Could you confirm that the latest revision of glfw recipe in conan-center fixed your issue?

**Comment by matheusgomes28** [comment]
@SpaceIm It does. I tried it again this morning with the latest revision of the recipe and it worked like a charm. Just to be clear, I linked both `glfw::glfw` and `glfw` libraries, and my project built on CMake 3.10 just fine. Either way, I have also updated my runner's CMake because why not. 

If anyone was having this issue before, it should have now disappeared.
