### ISSUE TITLE
[pybind11] Error with duplicated pybind11::pybind11 target (Conan 1.33)

### ISSUE THREAD

**Issue by 3ddiddE** [conan-io/conan-center-index#4407]
I am using the cmake_find_package method to include conan installed packages.
One of the package is pybind11, Now I immediately get an error after calling find_package(pybind11 REQUIRED)
>/home/x/.conan/data/pybind11/2.6.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/pybind11/pybind11Common.cmake|48 error|  add_library cannot create imported target "pybind11::pybind11" because
||   another target with the same name already exists.
|| Call Stack (most recent call first):
/home/x/.conan/data/pybind11/2.6.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/pybind11/pybind11Install.cmake|249| include
build/Findpybind11.cmake|174| include
src/tools/CMakeLists.txt|80| find_package

In case the other modules are relevant, here is the conanfile content:
```
[requires]
nlohmann_json/3.9.1
eigen/3.3.8
ceres-solver/2.0.0
glog/0.4.0
boost/1.75.0
opencv/4.5.1
pybind11/2.6.1
glew/2.1.0
opengl/system

[generators]
cmake_find_package
cmake_paths
```

Am I doing something wrong or is this a bug?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SpaceIm** [comment]
Yes last pybind11 modifications were too fragile: https://github.com/conan-io/conan-center-index/pull/3305#discussion_r512819055

**Comment by songmeixu** [comment]
The same error happened to me for pybind11/2.6.2. Did this issue get resolved? Otherwise, I would like to help.

**Comment by dilawar** [comment]
Same here with pybind11/2.6.1. I had to revert back to using `conan_cmake_run` for pybind11 from `conan_cmake_configure`.
