### ISSUE TITLE
[service] Boost PR are never marked stale

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#4414]
It seems the amount of Boost PR is causing some conflicts each time one gets merged https://github.com/conan-io/conan-center-index/commit/a9e2407fbcb374e22c6575b04057fcc80d1ad467. This has the side effect of force an update in the GItHub API and there can never be marked stale.

All of them got update when the commit above was merged.
![image](https://user-images.githubusercontent.com/16867443/106282754-0736de80-620f-11eb-8db2-e48c1c2947e4.png)

Stale: #3900 and #3918

Fixed: #3959

**Comment by danimtb** [comment]
Closing as solved. Thank you!
