### ISSUE TITLE
[request] Add sqlcipher/4 to conan-center

### ISSUE THREAD

**Issue by pagikiw552** [conan-io/conan-center-index#442]
### Package Details
  * Package Name/Version: sqlcipher/4.2.0
  * Website: https://www.zetetic.net/sqlcipher/
  * Source code: https://github.com/sqlcipher/sqlcipher

### Description Of The Library / Tool
SQLCipher is an SQLite extension that provides 256 bit AES encryption of database files.
Source code: https://github.com/sqlcipher/sqlcipher

I assume it should share most of the code for already exisiting sqlite package.

**Comment by uilianries** [comment]
Hi @pagikiw552 !

Thanks for requesting this new library. Are you interested in creating a recipe for this library? We can help you if you have no experience writing Conan recipes. Regards!

**Comment by SpaceIm** [comment]
This issue can be closed (sqlcipher added in https://github.com/conan-io/conan-center-index/pull/714)
