### ISSUE TITLE
[package] bison/3.7.1: Implicit dependency on system libreadline.so

### ISSUE THREAD

**Issue by GenuineAster** [conan-io/conan-center-index#4443]
bison has a dependency on libreadline, but that dependency isn't in conan so it uses a system dependency instead. I guess it should probably use a conan libreadline dependency instead.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: bison/3.7.1
  * Operating System+version: Linux Debian Bullseye
  * Compiler+version: Clang 10.0.1
  * Docker image: custom
  * Conan version: conan 1.31.3
  * Python version: 3.8.6

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
root@c2a08a111625:/tmp/conan-swig# conan profile show default
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=10
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
1. Install a prebuilt `bison/3.7.1` from e.g bincrafters
2. run `bison --version`
3. If you don't have libreadline installed, this will fail with a missing libreadline.so
3a. If you don't have the same readline version as what was used to build this, this will also fail

Workaround: Install libreadline and install deps with --build=bison

</details>

**Comment by madebr** [comment]
We have a libreadline package that can be used.
I didn't check bison's configure script, but maybe it is also possible to disable readline support.
(readline is mostly used for command history in cli utils)

**Comment by taoyouh** [comment]
I locally built the bison package, but the `bison` executable does not link to libreadline at all.

I ran this:
```
conan install bison/3.7.1@ -g virtualrunenv -s compiler=clang -s compiler.version=10 -s compiler.libcxx=libstdc++ --build=bison
source activate_run.sh
ldd $(which bison)
```
getting this:
>         linux-vdso.so.1 (0x00007ffd2b9f4000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fad810e3000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007fad81376000)

But the prebuilt version from CCI does links to libreadline.so.7

There must be something that controls linking to libreadline

**Comment by taoyouh** [comment]
It seems that bison has removed linking of libreadline since 2020-10: https://lists.gnu.org/r/bug-bison/2020-10/msg00003.html

**Comment by taoyouh** [comment]
Update:

I can reproduce the problem when building using the https://hub.docker.com/r/conanio/clang10/ docker image.

I ran this:
```
conan install bison/3.7.1@ -g virtualrunenv -s compiler=clang -s compiler.version=10 -s compiler.libcxx=libstdc++ --build=bison
source activate_run.sh
ldd $(which bison)
```
getting this:

>         linux-vdso.so.1 (0x00007ffd279ae000)
>         libreadline.so.7 => /lib/x86_64-linux-gnu/libreadline.so.7 (0x00007fb7ddbcd000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb7dd7dc000)
>         libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fb7dd5b2000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007fb7dde16000)
