### ISSUE TITLE
Extending list of available binary packages

### ISSUE THREAD

**Issue by IvanRibakov** [conan-io/conan-center-index#4481]
I've been reading up on the [`ERROR: Missing prebuilt package`](https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package) Conan error and the documentation says following:

> By default, Conan doesn’t build packages from sources. 

But as far as I can see, Conan does store **some** binaries which typically can be seen in the "Configurations" tab under "List of available binary packages:"

![image](https://user-images.githubusercontent.com/3639958/106886432-2dafba80-66e4-11eb-9b94-4f1f96d713a9.png)

All my search attempts over the documentation lead me to the https://docs.conan.io/en/latest/creating_packages/existing_binaries.html but I'm not sure if that's the only way to submit binaries or if there is some other way.

So, my question is - what control do I as package author/contributor have over the list of binary packages that Conan will store (cache) and offer for direct consumption without local build?

**Comment by SpaceIm** [comment]
conan client doesn't build from source by default (without options -b or -b <recipename> or -b missing etc).

`conan-center` remote provides pre build binaries of `conan-center-index` recipes for these triplets: https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md

Does this answer your question?

**Comment by IvanRibakov** [comment]
> - conan-center remote provides pre build binaries of conan-center-index recipes for these triplets: https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md. These pre build binaries are called packages and have a hash (package id). If by any mean conan client computes that you need a different hash (based on your settings, recipe options, transitive dependencies major version and so on) than packages available in your remotes, you have to build from source.

Thanks, this is what I was looking for (apparently in the wrong place).
