### ISSUE TITLE
[question] Bincrafters package marked as legacy

### ISSUE THREAD

**Issue by IvanRibakov** [conan-io/conan-center-index#4506]
I just noticed that a `@bincrafters/stable` package that I have been using for about 6 months is marked as "legacy" in the Conan-center: https://conan.io/center/sqlite_orm

I don't think it had this label when I started using it a while ago.

2 Questions:
1. Can someone explain or point me to the relevant part of the docs where the implications of the "legacy" label are explained?
2. Is it ok to submit existing package recipe as it appears in Conan-center to Conan-center as a new PR (assuming it would get rid of the "legacy" label)?

**Comment by Croydon** [comment]
All packages that are included in conan-center, but are not in conan-center-index, are marked as legacy

sqlite_orm can be ported to conan-center-index as all dependencies are in it already. Helping hands are welcome, just give credits to the [original source](https://github.com/bincrafters/conan-sqlite_orm) when opening a PR

**Comment by SpaceIm** [comment]
Saw this issue and submitted https://github.com/conan-io/conan-center-index/pull/4514 few minutes ago.

**Comment by Croydon** [comment]
The package is now migrated. You should use now `sqlite_orm/1.6` (without username and channel) instead of the Bincrafters' packages

Thanks @SpaceIm

**Comment by IvanRibakov** [comment]
Thank you, @SpaceIm! 👏🏻
