### ISSUE TITLE
[question] OpenSSL: casing issues in CMake module

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-center-index#452]
Hi! I've just realized that the OpenSSL has some casing issues. According to the [CMake module](https://cmake.org/cmake/help/v3.4/module/FindOpenSSL.html):

```
OpenSSL::SSL
OpenSSL::Crypto
```
 

but,

```
OPENSSL_FOUND
OPENSSL_INCLUDE_DIR
OPENSSL_CRYPTO_LIBRARY
OPENSSL_SSL_LIBRARY
OPENSSL_LIBRARIES
OPENSSL_VERSION
```

So, not even the `cpp_info.names["cmake_***"]` or the `cpp_info.name` will be able to deal with it, right? Am I missing something?

Thanks!

**Comment by madebr** [comment]
I asked something similar at https://github.com/conan-io/conan/issues/5717#issuecomment-549075318

**Comment by jgsogo** [comment]
Do you think we should go for the `build_modules` approach (add it to OpenSSL), or shall I modify the consumer to match the casing (I found this issue package `tgbot`)?

**Comment by SSE4** [comment]
I don't think it's possible to generate multiple CMake targets without the components feature

**Comment by jgsogo** [comment]
Right, my problem is related to the upper/lower case of the variables. `tgbot` consumes `OPENSSL_LIBRARIES`, but we have `OpenSSL_LIBRARIES`.

**Comment by SSE4** [comment]
very inconsistent, as usual, e.g. 
https://cmake.org/cmake/help/v3.16/module/FindBZip2.html
vs
https://cmake.org/cmake/help/v3.16/module/FindBoost.html
and the most contradictory:
https://cmake.org/cmake/help/v3.16/module/FindLibXml2.html
notice **LibXml2_FOUND** vs **LIBXML2_INCLUDE_DIR**
without very flexible customization in generator, it's hard to satisfy every case
seems like it's very random, there is no logic, no standard, no specification...

**Comment by jgsogo** [comment]
Probably we should follow the comment linked by @madebr and we shouldn't try to recreate the CMake mess. It would be better to patch the build scripts of the consumers when there is some inconsistency, don't you think so?

**Comment by SSE4** [comment]
I agree, it's impossible to provide drop-in-replacement for something that is not well-defined, unfortunately.

**Comment by madebr** [comment]
I've gone the manual way and started to add these variables in some of my pull requests:
- bullet3: https://github.com/conan-io/conan-center-index/pull/440
- libpng: https://github.com/conan-io/conan-center-index/pull/434

Isn't this the same question as https://github.com/conan-io/conan-center-index/issues/419

**Comment by jgsogo** [comment]
Yes, I think #419 is exactly the same (more general and better explained). I'm closing this one then
