### ISSUE TITLE
[package] <Qt/5>: Components support

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#4529]
Now we have a recipe for Qt5 (and Qt6 is on the way!) :partying_face: 
Unfortunately there is no support for components in them.
I'm not familiar enough with components & Qt to drive this so I'm leaving this request here hoping that someone from the community takes it.

Keep up the good work!

**Comment by maksim-0** [comment]
This is a must have for production use

**Comment by ohanar** [comment]
Indeed, our team will continue to use the bincrafters recipe until this is resolved.

**Comment by szigetics** [comment]
I can just agree with all the things that were said before me. 
Not having components support makes it impossible to use : 
```
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)
```

I get these errors when I try to use them :  
```
  AUTOGEN: No valid Qt version found for target <masked>.  AUTOMOC disabled.
  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Core)

  to your CMakeLists.txt file.
```
and
```
  AUTOGEN: No valid Qt version found for target <masked>.
  AUTOMOC, AUTOUIC and AUTORCC disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Widgets)

  to your CMakeLists.txt file.
```
These error messages are originating from CMake : 
https://github.com/Kitware/CMake/blob/master/Source/cmQtAutoGenGlobalInitializer.cxx#L138
https://github.com/Kitware/CMake/blob/master/Source/cmQtAutoGenGlobalInitializer.cxx#L140

**Comment by ericLemanissier** [comment]
if you have working projects on qt6, I'll happily take some feedback on https://github.com/conan-io/conan-center-index/pull/4763. I'll start the work on qt5 when qt6 is merged.

**Comment by irobot-ros** [comment]
Hi, any update on this?
We are looking into getting qt5 via Conan, but the lack of components support make it not possible

**Comment by xahon** [comment]
Why is it closed? I still encounter the same problem with conan's center recipe of qt5

**Comment by ericLemanissier** [comment]
because https://github.com/conan-io/conan-center-index/commit/82a909e608c8baf8a5d626488db74cc602e300e1 added components to qt recipe. Please report a new issue with full information if you still have a problem.
