### ISSUE TITLE
[package] mariadb-connector-c/3.1.11: Missing includes

### ISSUE THREAD

**Issue by floriansimon1** [conan-io/conan-center-index#4530]
### Package and Environment Details
  * Package Name/Version: **mariadb-connector-c/3.1.11**
  * Operating System+version: **Windows 10 x64**
  * Compiler+version: **MSVC 15 and 16**
  * Conan version: **conan 1.32.1**
  * Python version: **Python 3.8.5**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

If you look at the includes in the package, you'll find that [the mysqld_error.h header](https://github.com/mariadb-corporation/mariadb-connector-c/blob/3.1/include/mysqld_error.h) is missing.

In [their CMake setup](https://github.com/mariadb-corporation/mariadb-connector-c/blob/67cd96f141f9b3f7b987f7adcb2eb51922923c84/include/CMakeLists.txt#L15), that file is being conditionally added to the list of includes that CMake's `install` target is supposed to install. `IS_SUBPROJECT` is defined in the [root](https://github.com/mariadb-corporation/mariadb-connector-c/blob/3.1/CMakeLists.txt#L22) `CMakeLists.txt` with the following call:
```
get_directory_property(IS_SUBPROJECT PARENT_DIRECTORY)
```

**Comment by SpaceIm** [comment]
closed by https://github.com/conan-io/conan-center-index/pull/4532
