### ISSUE TITLE
[request] flecs/v2.3.1

### ISSUE THREAD

**Issue by rawbby** [conan-io/conan-center-index#4541]
### Package Details
  * Package Name/Version: **flecs/v2.3.1**
  * Website: **https://github.com/SanderMertens/flecs**
  * Source code: **https://github.com/SanderMertens/flecs**
  * Platform/Compiler:
     * Windows: msvc
     * Ubuntu: gcc (7, 8, 9, 10), clang (8, 9)
     * MacOS: gcc 10, clang 9
  * Conan recipe repository: https://github.com/rawbby/conan-flecs
    (As I am new to the Conan Community I dont know if the package is perfectly polished yet)

### Description Of The Library / Tool
Flecs is a fast and lightweight Entity Component System with a focus on high performance game development.

**Comment by Croydon** [comment]
Since you already have a recipe, feel free to create a pull request
