### ISSUE TITLE
[question] Where is Boost::process?

### ISSUE THREAD

**Issue by helmesjo** [conan-io/conan-center-index#4542]
So after _component support_ [was added to the Boost package](https://github.com/conan-io/conan-center-index/pull/2097), I figured I'd use `Boost::process` directly instead of linking everything, but then noticed [it's missing](https://github.com/conan-io/conan-center-index/blob/9c73f9463f38a38aa7ce4bd95ec6acbec0529dff/recipes/boost/all/conanfile.py).

How come?

**Comment by SpaceIm** [comment]
AFAIK, there is no `Boost::process` imported target nor `process` component in official FindBoost. It's part of `Boost::headers`

**Comment by helmesjo** [comment]
Oh, I knew it was something trivial... Thanks!
