### ISSUE TITLE
[request] thrift/0.14.0

### ISSUE THREAD

**Issue by helmesjo** [conan-io/conan-center-index#4545]
### Package Details
  * Package Name/Version: **thrift/0.14.0**
  * Changelog: **https://github.com/apache/thrift/blob/v0.14.0/CHANGES.md#0140**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by helmesjo** [comment]
Related to this is that thrift should nowadays only require `Boost::headers`. [No need to link the runtime libraries](https://thrift.apache.org/lib/cpp.html#dependencies).

**Comment by ericLemanissier** [comment]
this was fixed in https://github.com/conan-io/conan-center-index/pull/5087

**Comment by helmesjo** [comment]
@ericLemanissier Ah, cool! And just as of today we got 1.4.2 😇
