### ISSUE TITLE
[question] Abseil: Path length error when building grpc

### ISSUE THREAD

**Issue by floriansimon1** [conan-io/conan-center-index#4588]
Hi!

I tried building gRPC with the inexorgame ([see my message in the grpc recipe issue tracker](https://github.com/inexorgame/conan-grpc/issues/38#issuecomment-779870162)) recipe, but `abseil` prevents me from building it because it doesn't have the `short_paths` option set to `True`. Is that an error that should be fixed in abseil or an error with the grpc recipe?

**Comment by floriansimon1** [comment]
My username is actually 7 characters long, so I don't think it's a lot.

I didn't know about the conan.conf option, I'll try it, thanks!

Should we consider the abseil thing to be a bug in the abseil recipe? I guess having a 7 chars long username is not that uncommon.

**Comment by SpaceIm** [comment]
I would say that short_paths True or False in a recipe is never a bug, it's a workaround for windows users who can't enable long paths in Windows.

But yes, I guess that short_paths could be enabled in abseil recipe.

**Comment by floriansimon1** [comment]
Should I submit a PR for that?

Sorry for asking silly questions, I want to make sure I got it right :)

**Comment by SpaceIm** [comment]
Sure
