### ISSUE TITLE
[package] <openCV/2.x|3.x: Usage of Lena image on test_package

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#4609]
Hi all,

This is not really a bug report but just a comment on the openCV recipes. On version 2.x and 3.x the test packages include the very controversial 'Lena' (or 'Lenna') test image.

https://github.com/conan-io/conan-center-index/blob/master/recipes/opencv/2.x/test_package/lena.jpg

This has been an accepted test image forever but lately it is being replaced with other alternatives due to licencing and sexism concerns, since it is part of a Playboy cover.

See this Wikipedia entry for reference: https://en.wikipedia.org/wiki/Lenna#Criticism

This is a popular alternative to the Lena image, called peppers.
https://homepages.cae.wisc.edu/~ece533/images/peppers.png

If you think it is a good idea to change this picture let me know and I'll open a PR.

**Comment by intelligide** [comment]
Although I don't completely agree with the criticism, there are no valid technical reasons not to change the image. I think you can open such a PR. ;)

**Comment by uilianries** [comment]
I don't care about the picture, actually we don't need that. You can open a PR not only removing (not replacing), but also simplifying the test package. Usually pictures are larger files and CCI is getting weight fast as we are receiving new PRs.

**Comment by ericriff** [comment]
I don't really care about the picture either, but I had to remove it from an internal mirror due to company policies. Some other developer may encounter the same issues.

**Comment by uilianries** [comment]
Please, go ahead, feel free opening a PR. Thank you for reporting it.
