### ISSUE TITLE
[package] BZip2/1.0.8: Invalid CMake module path when using cmake_paths generator

### ISSUE THREAD

**Issue by FiniteReality** [conan-io/conan-center-index#4655]
### Package and Environment Details
  * Package Name/Version: BZip2/1.0.8
  * Operating System+version: Windows 10 20H2 19042.631
  * Compiler+version: MSVC 19.28.298.0
  * Docker image: None?
  * Conan version: conan 1.33.1
  * Python version: Python 3.9.2

I'm reporting this on behalf of @RubyNova as we are working together on a project.

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler = Visual Studio
compiler.version=16
[options]
[build_requires]
[env]
```

### Steps to reproduce

Use the `cmake_paths` generator to build something which requires BZip2.

### Extra information

I looked through the conanfile for BZip2 and found that this appears to be broken by https://github.com/conan-io/conan-center-index/pull/4623

The issue is that with this PR, the `CMAKE_PREFIX_PATH` variable gets set to `/path/to/bzip2/version/lib/cmake` rather than the expected `/path/to/bzip2/version/`. I can work around this by using `CONAN_BZIP2_ROOT` but that means writing a custom FindBzip2 script to specifically use it, or manually adding `CONAN_BZIP2_ROOT` to `CMAKE_PREFIX_PATH`.

### Logs
<details><summary>Click to expand log</summary>

```
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) (Required
  is at least version "1.0.8")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindBZip2.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/NovelRT/CMakeLists.txt:1 (find_package)
```

</details>

**Comment by SpaceIm** [comment]
Is it better if you replace `self.cpp_info.builddirs= [self._module_subfolder]` by `self.cpp_info.builddirs.append(self._module_subfolder)` in bzip2 conanfile?

**Comment by SpaceIm** [comment]
@SSE4 @uilianries 
Why do we have to set both builddirs and build_modules?
I understand that:
- builddirs are appended to CMAKE_PREFIX_PATH and CMAKE_MODULE_PATH.
- build_modules are included in cmake files generated by conan generators.

If a build_module is not supposed to be included directly by consumers, but used for internal purpose, what's the point of builddirs since build_modules already have proper relative path? It seems to be redundant.

**Comment by SpaceIm** [comment]
Recipes overriding `cpp_info.builddirs` (package folder removed from builddirs) instead of appending new paths:
bzip2
catch2
cereal
cern-root
corrade
extra-cmake-modules
glfw
ignition-cmake
jinja2cpp
libgeotiff
meson
mfast
open62541
pybind11
raylib
swig
verilator
