### ISSUE TITLE
[package] nasm: Pulling sources from non-https url

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#4657]
On `nasm` we're pulling the sources from the official webpage, which is not `https`.
https://github.com/conan-io/conan-center-index/blob/master/recipes/nasm/all/conandata.yml#L1-L13

This was fine before but now it is giving me issues 
```
ERROR: Error downloading file http://www.nasm.us/pub/nasm/releasebuilds/2.14/nasm-2.14.tar.gz: 'HTTPSConnectionPool(host='www.nasm.us', port=443): Max retries exceeded with url: /pub/nasm/releasebuilds/2.14/nasm-2.14.tar.gz (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))'
```

And if you try to manually download the sources with a browser you get a similar warning.

According to the official webpage they moved the sources to github last year. [Here](https://www.nasm.us/).
```
Infrastructure Change
On July 1, 2020, the official NASM git repository moved to github.

The previous repository on repo.or.cz is no longer maintained.
```

I did a quick test and start pulling the sources from github is not 100% trivial since, at least in version 2.14, the `configure` script is not there and running `autoreconf -fiv` isn't enough since the build failed further down the line.
Unfortunately I can't work on this now so I'm leaving it here just in case someone can pick it up.

**Comment by ericriff** [comment]
This is what fails on version 2.14, the one I was using
https://bugzilla.nasm.us/show_bug.cgi?id=3392557

2.15 fails during autoreconf.

**Comment by ericriff** [comment]
It looks like the nasm site is now fixed and it's not being flagged as insecure anymore. Regardless I think we should consider switching to github anyways.

**Comment by SpaceIm** [comment]
We can replace http by https in urls.
