### ISSUE TITLE
[package] benchmark/1.5.2: Cannot compile on arm64

### ISSUE THREAD

**Issue by jhurliman** [conan-io/conan-center-index#4677]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **benchmark/1.5.2**
  * Operating System+version: **Linux Ubuntu 18.04, NVIDIA Jetson Xavier AGX (arm64)**
  * Compiler+version: **clang-10**
  * Conan version: **conan 1.33.1**
  * Python version: **Python 3.6.9**

### Conan profile
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=armv8
arch_build=armv8
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Attempt to install Google Benchmark (`benchmark/1.5.2` or any previous version in the conan index) on an arm64 platform. The following line (https://github.com/conan-io/conan-center-index/blob/master/recipes/benchmark/all/conanfile.py#L62):

```
self._cmake.definitions["BENCHMARK_BUILD_32_BITS"] = "ON" if "64" not in str(self.settings.arch) else "OFF"
```

Does not account for the fact that `armv8` does not include the string `64`, so this check fails and the `-m32` compiler flag is appended to the build causing it to fail.

**Comment by ralfholly** [comment]
@jhurliman FYI I already created a PR some time ago: #4653

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as this problem has been addressed. 
Tested locally with oldest most similar version to `1.5.2` deprecated one with `armv8`:

```
$ conan create recipes/benchmark/all --version 1.5.6 -b=missing
... 
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

...
[100%] Linking CXX executable test_package
[100%] Built target test_package


======== Testing the package: Executing test ========
benchmark/1.5.6 (test package): Running test()
benchmark/1.5.6 (test package): RUN: ./test_package
Unable to determine clock rate from sysctl: hw.cpufrequency: No such file or directory
2024-09-04T17:27:00+02:00
Running ./test_package
Run on (14 X 24.0628 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x14)
  L1 Instruction 128 KiB (x14)
  L2 Unified 4096 KiB (x3)
Load Average: 4.84, 2.80, 2.26
------------------------------------------------------------
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
BM_StringCreation      0.260 ns        0.260 ns   1000000000
BM_StringCopy          0.248 ns        0.248 ns   1000000000
```

If the problem remains, do not hesitate to open a new ticket!
Happy coding 🐸
