### ISSUE TITLE
[package] catch2/2.13.0: Incompatible to Android

### ISSUE THREAD

**Issue by Linux13524** [conan-io/conan-center-index#4691]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **catch2/2.13.0**
  * Docker image: **conanio/android-clang8**

### Conan profile (output of `conan profile show default`)
```
[settings]
os=Android
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.cppstd=17
compiler.libcxx=libc++
build_type=Release
os.api_level=21
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Create simple application that includes `catch2/catch.hpp` and try to build for Android.

### Extra information

Hi. I just tried to build one of our projects with one of the android docker images and it fails with the attached error message. I could solve the problem by linking agains `log` in our projects `CMakeLists.txt` or adding `log` as library to our projects `cpp_info`, but I think this should be fixed in the catch2 recipe. 

So my proposal is to conditionally add `log` as library to the `cpp_info` attribute in the recipe. I can open a pull request for that, but I was not sure if it would be `self.cpp_info.system_libs` or `self.cpp_info.libs`.

Thanks in advance!

### Logs (Include/Attach if Applicable)

```
/home/conan/.conan/data/catch2/2.13.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/catch2/catch.hpp:10360: error: undefined reference to '__android_log_write'
/home/conan/.conan/data/catch2/2.13.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/catch2/catch.hpp:10360: error: undefined reference to '__android_log_write'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by SSE4** [comment]
yes, `log` should be in `self.cpp_info.system_libs` for Android. feel free to submit PR with fix.
