### ISSUE TITLE
[service] Add CI for x86 architecture

### ISSUE THREAD

**Issue by db4** [conan-io/conan-center-index#4694]
I understand the teams' decision to remove x86 binary packages from CCI (discussed in https://github.com/conan-io/conan-center-index/issues/1869). But this has a side effect: package recipes are no longer tested for x86 compatibility that reduces their quality.  Right now I'm trying to figure out why the recent `boost/1.74.0` recipe fails on Linux/x86, while its fall 2020 revision did just fine. What about adding at least one x86 configuration to conan-center-index CI infrastructure **without** deploying the build results? It doesn't seem like a big additional load for conan servers...

**Comment by uilianries** [comment]
Hi @db4! 

After some years of package distribution, Conan team and Bincrafters collected stats from Bintray to understand how many people were using x86, and only a very few of them were downloading, less than 10%. So a decision was made for CCI, bringing back it will cost double of CCI resources (building time, CI storage, maintainability, etc ...). Thus, it's not possible.

If you are in trouble with some package, please, open a new issue. You are not the first with problem  on x86 and won't be the last. Same for other architectures like ARM and OS like Android and iOS.

**Comment by db4** [comment]
@uilianries OK, your point is well taken.

**Comment by db4** [comment]
@uilianries just one extra question: if CCI does not support x86 anymore, why e.g. bzip2 x86 packages (although outdated) are there? When I do `conan install bzip2/1.0.8@` on Linux/x86, I've got an outdated (and actually broken) binary package:
```
bzip2/1.0.8: Package installed 1b84e761682c3bf79bb7bcfb98f705af68d4c781
```
Can you get rid of outdated binary packages at CCI?

**Comment by uilianries** [comment]
@db4 They are still supported and there is no reason for drop x86 support, however, CCI doesn't test directly, it requires community support instead.

If a package is outdated and you can't install, it's a bug and should be reported, you still can open an issue (a new one, don't mix with this question related to building CI support).
