### ISSUE TITLE
[package] bison/3.7.1: m4 subprocess failed

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/conan-center-index#4699]
I'm unable to use Bison because of an issue with m4.  The m4 dependency is correctly installed, but the Bison executable is not able to find the m4 executable.  The specific error message is as follows:

```
m4 subprocess failed: No such file or directory
```

This may be similar/identical to #1498, but that bug was fixed in the past, while I'm still getting this error with the latest Bison package.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **bison/3.7.1**
  * Operating System+version: **Linux Ubuntu 20.10**
  * Compiler+version: **GCC 10.2.0**
  * Conan version: **conan 1.34.0**
  * Python version: **Python 3.8.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

1. Install Bison through Conan:

    ```sh
    conan install bison/3.7.1@_/_
    ```

2. Call Bison over an input file:

   ```sh
   ~/.conan/data/bison/3.7.1/_/_/package/21011818b664ba5f28bbba5f38f3117d33c4b91b/bin/bison test.yy
   ```

3. Notice that the following error is emitted:

    ```sh
    /home/{user}/.conan/data/bison/3.7.1/_/_/package/21011818b664ba5f28bbba5f38f3117d33c4b91b/bin/bison: m4 subprocess failed: No such file or directory
    ```

**Comment by SSE4** [comment]
bison requires m4 executable to be in PATH, or M4 environment variable to be set
consider using [virtualrunenv](https://docs.conan.io/en/latest/reference/generators/virtualrunenv.html) generator.

**Comment by wouterbeek** [comment]
Thanks!  That indeed fixed it.

**Comment by snikulov** [comment]
@SSE4 your explanation not exactly what I expecting.
bison/3.7.1 has dependency from m4, so it builds but can not be used without additional configuration?
Is it possible to set environment variable `M4={conan installed dependency}` for conan's `cmake` generator somwhere?

**Comment by ajlekcahdp4** [comment]
> bison requires m4 executable to be in PATH, or M4 environment variable to be set consider using [virtualrunenv](https://docs.conan.io/en/latest/reference/generators/virtualrunenv.html) generator.

It's not clear for me either. What M4 environmental variable should be set to?
I consider it a serious bug in bison recipe that we need to set any environmental variables at all. Should we reopen this issue? It would be great to have a proper fix.
