### ISSUE TITLE
[package] qt/6.0.1: Unable to use in CMake

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/conan-center-index#4706]
When a Qt6 Conan dependency is used in CMake, the following error is emitted:

```
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" (requested
  version 6.0.1) with any of the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
```

In line with the official Qt documentation ([link](https://doc.qt.io/qt-6/cmake-get-started.html)), I'm looking for Qt from CMake in the following way:

```cmake
find_package(Qt6 6.0.1 REQUIRED
  COMPONENTS Core Gui OpenGLWidgets Widgets)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)
target_link_libraries(app
  PRIVATE Qt::Core
          Qt::Gui
          Qt::OpenGLWidgets
          Qt::Widgets)
```

I have also tried to specify the Qt dependency without a `find_package` invocation, but linking against a target like `CONAN_PKG::qt` also does not work.  (<--- I also have not seen this latter approach documented anywhere yet; I'm assuming Qt6 still requires a dedicated `find_package` invocation because it may still some custom MOC/UIC/RCC support in CMake?)

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.0.1**
  * Operating System+version: **Linux Ubuntu 20.10**
  * Compiler+version: **GCC 10.2.0**
  * Conan version: **conan 1.34.0**
  * Python version: **Python 3.8.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

1. Write a Conan file where `qt/6.0.1` is included in the requires and build_requires sections, and where the generators `cmake` and `virtualenv` are included.
2. Write a CMake file where Qt6 is included according to online documentation / best practices.
3. Run `conan install` over the Conan file.
4. Run `source activate.sh` to load the build environment.
5. Run `cmake ..` to generate the build; observe the above reported error message.

**Comment by prince-chrismc** [comment]
> Write a Conan file where `qt/6.0.1` is included in the requires and build_requires sections, and where the generators `cmake`

You are using https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_generator.html which does not generate the `FindPackage.cmake` files

Try using https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html which offers this functionality!

---

You should not need it in both requires and build_requires

**Comment by prince-chrismc** [comment]
>  but linking against a target like CONAN_PKG::qt also does not work. (<--- I also have not seen this latter approach documented anywhere yet

I believe you are referring to the Qt documentation? If yes, then I think it's natural they have not documented a very Conan specific way of including the project.

**Comment by SpaceIm** [comment]
@prince-chrismc CONAN_PKG::qt doesn't work because package_info() of qt recipe is broken (there is a big FIXME). So qt recipe is currently unusable in CMake based projects, because all generators are broken in this recipe.

**Comment by ericLemanissier** [comment]
The fact that it does not have components does not prevent all use of the recipe. What problems do you encounter when basing your cmake file on https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/test_package/CMakeLists.txt ?

**Comment by SpaceIm** [comment]
> The fact that it does not have components does not prevent all use of the recipe. What problems do you encounter when basing your cmake file on https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/test_package/CMakeLists.txt ?

Doesn't test_package work by luck in the CMake example because it relies on just few components (QtCore, QtGui and QtWidgets I guess?), so that it doesn't hit undefined references due to bad ordering in `self.cpp_info.libs`?

**Comment by wouterbeek** [comment]
@prince-chrismc Adding the `cmake_find_package` generator indeed generates a `Findqt.cmake` file.  But this does not fix my original problem, which was that the files `qtConfig.cmake` and/or `qt-config.cmake` cannot be found:

```
  Could not find a package configuration file provided by "qt" with any of
  the following names:

    qtConfig.cmake
    qt-config.cmake
```

Maybe I'm making a mistake somewhere?  These are my steps:

  1. Generate the `Findqt.cmake` file: `conan install .. -b missing`
  2. Activate the build environment (I have added Qt under `build_requires` since I expect that some Qt binaries are needed to process MOC/UIC/RCC files): `source activate.sh`
  3. Generate the build with CMake: `cmake .. -D CMAKE_BUILD_TYPE:STRING=Debug`

Inside the CMake file I'm following the `find_package` and `target_link_libraries` invocations from [the test file](https://github.com/conan-io/conan-center-index/blob/3fec29f20012fb87e2d6d3e0751065ed3be4d608/recipes/qt/6.x.x/test_package/CMakeLists.txt).

**Comment by SpaceIm** [comment]
You must add to `CMAKE_MODULE_PATH` the path where the file Findqt.cmake was generated (your build folder I guess).

So your cmake invocation would become `cmake .. -D CMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_MODULE_PATH=<path where conan install was run>`

Don't put qt in `build_requires`, but in `requires` (strictly speaking it should be in both).

**Comment by mjvankampen** [comment]
I tried it with a more complex project and still works. I think because qtcore happens to be one of the first libs. But of course the integration is quite different from the original qt and some features won't work (or are harder).

**Comment by wouterbeek** [comment]
Thanks for the good feedback!  I'm not able to combine all the moving parts into something that works ATM.  But I think this is mostly me not knowing enough to pull it off.

I will wait for Qt6/CMake/Conan combinations created by others to appear online over time.  Maybe the above comments are helpful for those who will create the first such combinations.
