### ISSUE TITLE
[request] Sentry Crashpad support

### ISSUE THREAD

**Issue by kangsheng89** [conan-io/conan-center-index#4751]
I saw bincrafter has this package https://github.com/bincrafters/conan-crashpad, by any chance this package will be available in cci, and can b use with Sentry?

**Comment by ericriff** [comment]
We have `crashpad` available here now https://github.com/conan-io/conan-center-index/tree/master/recipes/crashpad
And also sentry's fork of crashpad here https://github.com/conan-io/conan-center-index/tree/master/recipes/sentry-crashpad
For now `sentry` only takes the official package https://github.com/conan-io/conan-center-index/blob/master/recipes/sentry-native/all/conanfile.py#L64
But IMO we should make it consume sentry's fork by default. 
What do you think @madebr?

**Comment by ericriff** [comment]
OK so the PR to change the `breakpad` package used is already up
https://github.com/conan-io/conan-center-index/pull/5717/commits

**Comment by madebr** [comment]
@ericriff 
Indeed, crashpad is available + sentry's fork is used by default. Google's crashpad is (currently) missing some symbols on Windows.

@kangsheng89 
I think this issue can be closed:
- crashpad + sentry-crashpad are available in cci
- sentry-native has support for crashpad

**Comment by kangsheng89** [comment]
Thanks @madebr and @ericriff !! Highly appreciate
