### ISSUE TITLE
[package] libnghttp2/1.39.2: not building with Linux Clang 9

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#482]
The recipe for `libnghttp2/1.39.2` does not build under Linux Clang 9.

After generating all the index packages for Clang 9, the ones for this library failed to compile.

Related to #211 

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libnghttp2/1.39.2**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **Clang 9**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.7.4**

**Comment by uilianries** [comment]
@danimtb during the build I found:

```
configure: WARNING: Package 'cunit', required by 'virtual:world', not found
checking for CU_initialize_registry in -lcunit... no
checking for ev_time in -lev... yes
checking ev.h usability... yes
checking ev.h presence... yes
checking for ev.h... yes
checking for OPENSSL... no
configure: Package 'ZLIB', required by 'openssl', not found
checking for LIBCARES... yes
checking for LIBEVENT_OPENSSL... yes
checking for JANSSON... yes
checking for LIBXML2... yes
configure: error: applications were requested (--enable-app) but dependencies are not met.
```

This fix requires https://github.com/conan-io/conan/issues/6222

<details>
conan create . 1.39.2@ -pr clang9
[HOOK - conan-center.py] pre_export(): [DEPRECATED GLOBAL CPPSTD (KB-H001)] OK
[HOOK - conan-center.py] pre_export(): [REFERENCE LOWERCASE (KB-H002)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE METADATA (KB-H003)] OK
[HOOK - conan-center.py] pre_export(): [HEADER_ONLY, NO COPY SOURCE (KB-H005)] OK
[HOOK - conan-center.py] pre_export(): [FPIC OPTION (KB-H006)] OK
[HOOK - conan-center.py] pre_export(): [VERSION RANGES (KB-H008)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] Total recipe size: 7.88671875 KB
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] OK
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: ['CMakeLists.txt']
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE FOLDER (KB-H024)] OK
[HOOK - conan-center.py] pre_export(): [META LINES (KB-H025)] OK
[HOOK - conan-center.py] pre_export(): [CONAN CENTER INDEX URL (KB-H027)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE MINIMUM VERSION (KB-H028)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - RUN ENVIRONMENT (KB-H029)] OK
[HOOK - conan-center.py] pre_export(): [CONANDATA.YML FORMAT (KB-H030)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO IMPORTS() (KB-H034)] OK
[HOOK - conan-center.py] pre_export(): [NO AUTHOR (KB-H037)] OK
[HOOK - export_metadata.py] pre_export(): ERROR: Target file to write metadata already exists: '/tmp/conan-center-index/recipes/libnghttp2/all/metadata.json'. Use environment variable 'CONAN_HOOK_METADATA_FILENAME' to set a different filename
[HOOK - spdx_checker.py] pre_export(): recipe doesn't have a license attribute
Exporting package recipe
libnghttp2/1.39.2 exports: File 'conandata.yml' found. Exporting it...
libnghttp2/1.39.2 exports: Copied 1 '.yml' file: conandata.yml
libnghttp2/1.39.2 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] Saving conandata.yml: {'sources': {'1.39.2': {'sha256': '92a23e4522328c8565028ee0c7270e74add7990614fd1148f2a79d873bc2a1d0', 'url': 'https://github.com/nghttp2/nghttp2/releases/download/v1.39.2/nghttp2-1.39.2.tar.bz2'}}}
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] New conandata.yml contents: sources:
  1.39.2:
    sha256: 92a23e4522328c8565028ee0c7270e74add7990614fd1148f2a79d873bc2a1d0
    url: https://github.com/nghttp2/nghttp2/releases/download/v1.39.2/nghttp2-1.39.2.tar.bz2

[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] OK
libnghttp2/1.39.2: The stored package has not changed
libnghttp2/1.39.2: Exported revision: 70862956140c4945f5491de271b022a8
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
libnghttp2/1.39.2: Forced build from source
libnghttp2/1.39.2 (test package): Installing package
Requirements
    c-ares/1.15.0 from 'conan-center' - Cache
    jansson/2.12 from 'conan-center' - Cache
    libev/4.25 from 'conan-center' - Cache
    libiconv/1.15 from 'conan-center' - Cache
    libnghttp2/1.39.2 from local cache - Cache
    libxml2/2.9.9 from 'conan-center' - Cache
    openssl/1.0.2t from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    c-ares/1.15.0:961755854760682044d37dabfc2d998658edf961 - Cache
    jansson/2.12:d0094dd6c4311c5b04dcf0e7b230e8266547e888 - Cache
    libev/4.25:961755854760682044d37dabfc2d998658edf961 - Cache
    libiconv/1.15:961755854760682044d37dabfc2d998658edf961 - Cache
    libnghttp2/1.39.2:198b8a41fb2f3a05d3baa89c0f565efdadf07eff - Build
    libxml2/2.9.9:3506d251b1b94b790afde3772882f37891aeecc4 - Cache
    openssl/1.0.2t:9de5bc6401cdef5fe3faeb686f8f0b96f5878e0b - Cache
    zlib/1.2.11:961755854760682044d37dabfc2d998658edf961 - Cache

c-ares/1.15.0: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
jansson/2.12: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libev/4.25: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libiconv/1.15: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
zlib/1.2.11: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libxml2/2.9.9: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
openssl/1.0.2t: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
libnghttp2/1.39.2: WARN: Build folder is dirty, removing it: /home/uilian/.conan/data/libnghttp2/1.39.2/_/_/build/198b8a41fb2f3a05d3baa89c0f565efdadf07eff
libnghttp2/1.39.2: Copying sources to build folder
libnghttp2/1.39.2: Building your package in /home/uilian/.conan/data/libnghttp2/1.39.2/_/_/build/198b8a41fb2f3a05d3baa89c0f565efdadf07eff
libnghttp2/1.39.2: Generator cmake created conanbuildinfo.cmake
libnghttp2/1.39.2: Generator pkg_config created openssl.pc
libnghttp2/1.39.2: Generator pkg_config created c-ares.pc
libnghttp2/1.39.2: Generator pkg_config created libev.pc
libnghttp2/1.39.2: Generator pkg_config created libxml2.pc
libnghttp2/1.39.2: Generator pkg_config created jansson.pc
libnghttp2/1.39.2: Generator pkg_config created zlib.pc
libnghttp2/1.39.2: Generator pkg_config created libiconv.pc
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK. 'fPIC' option found and apparently well managed
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
libnghttp2/1.39.2: Calling build()
libnghttp2/1.39.2: Calling:
 > ./configure '--disable-shared' '--enable-static' '--enable-hpack-tools' '--enable-app' '--disable-examples' '--disable-python-bindings' '--without-jemalloc' '--without-systemd' '--without-libxml2' '--without-boost' '--prefix=/home/uilian/.conan/data/libnghttp2/1.39.2/_/_/package/198b8a41fb2f3a05d3baa89c0f565efdadf07eff' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' 
checking for gcc... /usr/bin/clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/clang accepts -g... yes
checking for /usr/bin/clang option to accept ISO C89... none needed
checking whether /usr/bin/clang understands -c and -o together... yes
checking how to run the C preprocessor... /usr/bin/clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by /usr/bin/clang... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from /usr/bin/clang object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/bin/clang supports -fno-rtti -fno-exceptions... yes
checking for /usr/bin/clang option to produce PIC... -fPIC -DPIC
checking if /usr/bin/clang PIC flag -fPIC -DPIC works... yes
checking if /usr/bin/clang static flag -static works... yes
checking if /usr/bin/clang supports -c -o file.o... yes
checking if /usr/bin/clang supports -c -o file.o... (cached) yes
checking whether the /usr/bin/clang linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of /usr/bin/clang... gcc3
checking whether make supports nested variables... (cached) yes
checking for gcc... (cached) /usr/bin/clang
checking whether we are using the GNU C compiler... (cached) yes
checking whether /usr/bin/clang accepts -g... (cached) yes
checking for /usr/bin/clang option to accept ISO C89... (cached) none needed
checking whether /usr/bin/clang understands -c and -o together... (cached) yes
checking whether we are using the GNU C++ compiler... yes
checking whether /usr/bin/clang++ accepts -g... yes
checking how to run the C++ preprocessor... /usr/bin/clang++ -E
checking for ld used by /usr/bin/clang++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the /usr/bin/clang++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for /usr/bin/clang++ option to produce PIC... -fPIC -DPIC
checking if /usr/bin/clang++ PIC flag -fPIC -DPIC works... yes
checking if /usr/bin/clang++ static flag -static works... yes
checking if /usr/bin/clang++ supports -c -o file.o... yes
checking if /usr/bin/clang++ supports -c -o file.o... (cached) yes
checking whether the /usr/bin/clang++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking dependency style of /usr/bin/clang++... gcc3
checking how to run the C preprocessor... /usr/bin/clang -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.20... yes
checking for a Python interpreter with version >= 2.7... python
checking for python... /opt/python/pyenv/versions/3.8.0/bin/python
checking for python version... 3.8
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.8/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.8/site-packages
checking for cython.py... no
checking for cython... no
checking whether /usr/bin/clang++ supports C++14 features with -std=c++14... yes
checking whether std::future is available... yes
checking whether std::map::emplace is available... yes
checking whether std::atomic_* overloads for std::shared_ptr are available... yes
checking whether thread_local storage class specifier is available.... yes
checking for ZLIB... yes
checking for library containing dlopen... none required
checking for CUNIT... no
configure: WARNING: Package 'cunit', required by 'virtual:world', not found
checking for CU_initialize_registry in -lcunit... no
checking for ev_time in -lev... yes
checking ev.h usability... yes
checking ev.h presence... yes
checking for ev.h... yes
checking for OPENSSL... no
configure: Package 'ZLIB', required by 'openssl', not found
checking for LIBCARES... yes
checking for LIBEVENT_OPENSSL... yes
checking for JANSSON... yes
checking for LIBXML2... yes
configure: error: applications were requested (--enable-app) but dependencies are not met.
libnghttp2/1.39.2: 
libnghttp2/1.39.2: ERROR: Package '198b8a41fb2f3a05d3baa89c0f565efdadf07eff' build failed
libnghttp2/1.39.2: WARN: Build folder /home/uilian/.conan/data/libnghttp2/1.39.2/_/_/build/198b8a41fb2f3a05d3baa89c0f565efdadf07eff
ERROR: libnghttp2/1.39.2: Error in build() method, line 130
	self._build_with_autotools()
while calling '_build_with_autotools', line 121
	env_build.configure(args=args)
	ConanException: Error 1 while executing ./configure '--disable-shared' '--enable-static' '--enable-hpack-tools' '--enable-app' '--disable-examples' '--disable-python-bindings' '--without-jemalloc' '--without-systemd' '--without-libxml2' '--without-boost' '--prefix=/home/uilian/.conan/data/libnghttp2/1.39.2/_/_/package/198b8a41fb2f3a05d3baa89c0f565efdadf07eff' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share'
</details>

**Comment by danimtb** [comment]
Thanks a lot for the investigation @uilianries. Let's wait for the fix to be merged then.

**Comment by gocarlos** [comment]
fixed?

**Comment by uilianries** [comment]
Yes.

Log detail: https://gist.github.com/uilianries/83b6485f76b6b648e730e0ae9aed801d
