### ISSUE TITLE
[boost] Static build of boost with python

### ISSUE THREAD

**Issue by Marcin-Radecki** [conan-io/conan-center-index#4822]
Hi, 
I have a doubt with regards to boost recipe build with python.  My package depends on boost (from CCI) build as static libraries, as well on python package that is a a wrapper of Python static libs:

```
default_options = (
    "boost:shared=False",
     "boost:without_python=False",
     "python:shared=False",
)

requires = [
        "boost/1.75.0",
        "python/3.7.9",
]
```

The conan recipe of boost already discovers python libs, and they're aligned with version of Python used when linking above package.

Now this package is built and run on two different servers, and while Python3 is available on build one, it's not on box when conan package runs. So conan install fails since it tries to autodetect Python:
```
boost/1.75.0: running "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('%s.%s' % (sys.version_info[0], sys.version_info[1]))"
boost/1.75.0: (failed)
ERROR: boost/1.75.0: Invalid configuration: detected python version None doesn't match conan option 3.6
```

My question is, is it expected given that both python and boost are linked statically to my app, why it still needs Python to be on the box where it runs? My understanding is that all code from Python libs are baked already in an app, so neither Python libs nor Python executable is required for an app to run.

Other question is, is it possible to bypass this check somehow using some option in recipe, and if not it is a viable feature request? 

Operating system is  Redhat 7.7.

**Comment by datalogics-robb** [comment]
Python is an interpreted language, and modules are typically compiled as shared objects and `dlopen()`ed to load them. 
So what do you mean when you say 

> both python and boost are linked statically to my app

?    I think that part needs a longer explanation because Python isn't a library but an interpreted language implemented as C  shared libraries and an executable.

**Comment by Marcin-Radecki** [comment]
After second thought I'm closing this one as no longer relevant.
