### ISSUE TITLE
Adding recipes to conan-index that are already part of a third party remote

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#483]
Hi,
As the tittle says, I would like to know if conan-index accepts PRs to add recipes that are already part of a third party remote. As an example, I'm working with libusb which is not present in conan-index but is present in the Bincrafters remote.
I know that Conan is decentralized but I think it would be nice to have most of the recipes here so they're easier to find and maintain.
Thanks.
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by ericLemanissier** [comment]
@ericriff you should sync with @uilianries : https://github.com/conan-io/conan-center-index/pull/430
