### ISSUE TITLE
[package] tesseract/4.1.1: not linking with openjpeg

### ISSUE THREAD

**Issue by henryborchers** [conan-io/conan-center-index#4848]
Building tesseract with leptonica:with_openjpeg=True is ignored.

after trying `tesseract --version` I always get the following on every os I've tried
```

tesseract 4.1.1

   leptonica-1.80.0

    libjpeg 9d : libpng 1.6.37 : libtiff 4.2.0 : zlib 1.2.11 : libwebp 1.1.0
```

Linux

### Package and Environment Details 
  * Package Name/Version: **tesseract/4.1.1**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9**
  * Docker image: **ubuntu:20.04**
  * Conan version: **conan 1.34.1**
  * Python version: **Python 3.9**

### Conan profile
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
[options]
[build_requires]
 [env]

```
Windows

### Package and Environment Details 
  * Package Name/Version: **tesseract/4.1.1**
  * Operating System+version: ** Windows Server 2019**
  * Compiler+version: **MSC v.1928**
  * Docker image: **mcr.microsoft.com/dotnet/framework/sdk:4.8**
  * Conan version: ** conan 1.34.1**
  * Python version: **Python 3.9**

### Conan profile
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

MacOS

### Package and Environment Details 
  * Package Name/Version: **tesseract/4.1.1**
  * Operating System+version: **macOS Catalina 10.15.7**
  * Compiler+version: **Apple clang version 12.0.0**
  * Conan version: ** conan 1.33.1**
  * Python version: **Python 3.9**

### Conan profile
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[build_requires]
[env]

```

**Comment by SpaceIm** [comment]
I don't know if this issue comes from tesseract or leptonica. Could you try to build leptonica and tesseract from source with these modifications in leptonica recipe https://github.com/conan-io/conan-center-index/pull/4849?

**Comment by henryborchers** [comment]
Looks like building it from source from this pull request works on Catalina as well. 

I hope that this can merged into main.
