### ISSUE TITLE
[package] spdlog/1.4.2: Android build includes -lpthread if build on linux

### ISSUE THREAD

**Issue by iamcgn** [conan-io/conan-center-index#487]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spdlog/1.4.2**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **clang**
  * Docker image: **N/A**
  * Conan version: **conan 1.20.5**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Android
os_build=Linux
arch=armv7
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
os.api_level=21
[options]
[build_requires]
*: android_ndk_installer/r20@bincrafters/stable
[env]
ANDROID_ABI=armeabi-v7a
CONAN_CMAKE_TOOLCHAIN_FILE=<NDK PATH>/android.toolchain.cmake
```

### Steps to reproduce (Include if Applicable)

Using the above profile try to include spdlog in an Android build. The issue seems to be this line:
```
    def package_info(self):
...
        if tools.os_info.is_linux:
            self.cpp_info.libs.append("pthread")
```
This assumes that because you're building on linux you're running on linux. It should only append "pthread" here if the target OS is linux. 

</details>

**Comment by perseoGI** [comment]
Hi there! I'm closing this old issue as minimum supported `spdlog` version is `1.8.5` right now. 

If this issue remains, do not hesitate to reopen it! 😄
