### ISSUE TITLE
[question] fftw/all

### ISSUE THREAD

**Issue by thebrandre** [conan-io/conan-center-index#488]
The fftw package was originally found [here](https://github.com/bincrafters/conan-fftw/tree/stable/3.3.8) had support for "cmake_paths" by including the subdirectory lib/cmake/fftw3 in package_info() instead of removing it in package().

This feature got explicitly removed when moving to conan-center-index. What was the rationale behind that? It worked fine for me so far with the old package. So I'd appreciated if we could add that again unless there are any reasons not to.

**Comment by madebr** [comment]
If I'm reading this correct, is this #419?
Are you missing the `FFTW3::fftw3` target exported by `FFTW3Config.cmake?

**Comment by thebrandre** [comment]
It seems kind of related but that shoudn't be an issue here (from my understanding). FFTW3 doesn't come as a standard cmake module according to this [list](https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html).
On my system (Fedora 31, system package of FFTW3 *not* installed) , `find_package(FFTW3 REQUIRED)` with cmake version 3.14.5 and conan's fftw/3.3.8 just leads to:

```
CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "FindFFTW3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FFTW3", but
  CMake did not find one.
```

**Comment by madebr** [comment]
Fedora's fftw-devel provides `FFTW3Config.cmake`: see http://rpmfind.net/linux/RPM/fedora/devel/rawhide/x86_64/f/fftw-devel-3.3.8-6.fc31.x86_64.html
If you know how to generate packages, does adding
```
self.cpp_info.names["cmake"] = "FTTW3"
self.cpp_info.names["cmake_find_package"] = "FTTW3"
self.cpp_info.names["cmake_find_package_multi"] = "FTTW3"
```
to the `package()` method of fftw's `conanfile.py`  help?

**Comment by thebrandre** [comment]
Fedora's fftw-devel package is also broken when it comes to `find_package`. I have already reported that [here](https://bugzilla.redhat.com/show_bug.cgi?id=1729652). Ironically, that was the reason why I switched to conan. ;-)

Thanks for your advice! But I am not sure if this is what one would be going for with FFTW. The library comes in [different versions depending on your floating-point precision](http://www.fftw.org/fftw3_doc/Precision.html). One can use all of them in one project:
```cmake
find_package (FFTW3)
find_package (FFTW3f)
find_package (FFTW3l)
```
and link them together in one executable. Explicitly stated [here](http://www.fftw.org/fftw3_doc/Precision.html).
That's a well-established mess with FFTW. Should the conan package mimic this?
Instead,
```python
self.cpp_info.builddirs = ["", "lib/cmake/fftw3"]
```
as used in the [original conan-fftw package](https://github.com/bincrafters/conan-fftw/blob/stable/3.3.8/conanfile.py), solves the problem. However, this feature seems to have been removed on purpose and I am wondering why.

**Comment by danimtb** [comment]
This is something that has been discussed in other issues and the answer was added to the FAQ https://github.com/conan-io/conan-center-index/wiki/FAQ#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged

We'd recommend to use conan's generated find/config files with the `cmake_find_package` generator
