### ISSUE TITLE
[request] openssl/1.1.0g

### ISSUE THREAD

**Issue by CfirTsabari** [conan-io/conan-center-index#4881]
### Package Details
  * Package Name/Version: **openssl/1.1.0g**
  * Changelog: **https://www.openssl.org/news/openssl-1.1.0-notes.html**

The above-mentioned version is previously released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by prince-chrismc** [comment]
As mentioned in your PR we have a version which is a perfect API ABI match so may you please this issue?
