### ISSUE TITLE
[package] glu/system: Wrong package installed when using zypper

### ISSUE THREAD

**Issue by adrianjrg** [conan-io/conan-center-index#4885]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glu/system**
  * Operating System+version: **OpenSuse Tumbleweed**
  * Compiler+version: **GCC 10**
  * Conan version: **conan 1.34.1**
  * Python version: **Python 3.8.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
package Mesa-libGLU-devel is not installed
ERROR: The following packages need to be installed:
 Mesa-libGLU-devel
glu/system: ERROR: while executing system_requirements(): Aborted due to CONAN_SYSREQUIRES_MODE=verify. Some system packages need to be installed
ERROR: Error in system requirements
```

</details>

I believe the package needed is called `glu-devel`, which shows up when searching zypper for the `Mesa-libGLU-devel` capability.
```
$ zypper search Mesa-libGLU-devel
Loading repository data...
Reading installed packages...
No matching items found.

$ zypper search --provides Mesa-libGLU-devel
Loading repository data...
Reading installed packages...

S  | Name            | Summary                           | Type
---+-----------------+-----------------------------------+--------
i+ | glu-devel       | Development files for the GLU API | package
   | glu-devel-32bit | Development files for the GLU API | package
```

Editing the line below in my cache to use `glu-devel` fixes the issue for me.

https://github.com/conan-io/conan-center-index/blob/608918cd5bbaa350e923b34d0da51ed423a16219/recipes/glu/all/conanfile.py#L27

**Comment by Croydon** [comment]
Did it change with some release or was this always the case?

**Comment by ericLemanissier** [comment]
AFAIK there is no mistake in the package name: https://github.com/bincrafters/system-packages-checks/runs/2110477169?check_suite_focus=true#step:6:153
Did you try to set environment variable `CONAN_SYSREQUIRES_MODE=enabled` ?

**Comment by adrianjrg** [comment]
That solves the issue, thanks!

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as problem was resolved!
Happy coding 🐸
