### ISSUE TITLE
[package]  libmysqlclient/8.0.17: incorrect GCC version check

### ISSUE THREAD

**Issue by db4** [conan-io/conan-center-index#4909]
### Package and Environment Details
  * Package Name/Version: **libmysqlclient/8.0.17**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **GCC 5.4**
  * Docker image: **conanio/gcc5**
  * Conan version: **conan 1.34.1**

### Conan profile
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce
Try to install the package, see the following error:
`libmysqlclient/8.0.17: Invalid configuration: GCC 5.3 or newer is required`

This is due to
https://github.com/conan-io/conan-center-index/blob/6e7eb066137aad9df2386db56c22512a87ff0b82/recipes/libmysqlclient/all/conanfile.py#L64-L65

I believe it's not correct and prevents using GCC 5.x (Conan ignores GCC minor version for GCC >= 5)

**Comment by SpaceIm** [comment]
Yes, there is a pattern to not exclude a compiler if the version in profile is not accurate enough:
https://github.com/conan-io/conan-center-index/blob/6e7eb066137aad9df2386db56c22512a87ff0b82/recipes/vk-bootstrap/all/conanfile.py#L45-L58

**Comment by db4** [comment]
> So in `libmysqlclient`, it could become:
> 
> ```python
>         def lazy_lt_semver(v1, v2):
>             lv1 = [int(v) for v in v1.split(".")]
>             lv2 = [int(v) for v in v2.split(".")]
>             min_length = min(len(lv1), len(lv2))
>             return lv1[:min_length] < lv2[:min_length]
>         
>         if self.settings.compiler == "gcc" and lazy_lt_semver(str(self.settings.compiler.version), "5.3"):
>            raise ConanInvalidConfiguration("GCC 5.3 or newer is required") 
> ```
@SpaceIm looks good, thanks.  Who do you think is the best person to make an appropriate PR?

**Comment by perseoGI** [comment]
Hi there!
Sorry to catch up this late.
`libmysqlclient/8.0.17` is no longer supported by CCI.
Anyways, this problem was resolved when `loose_lt_semver` was introduced. 
See https://github.com/conan-io/conan-center-index/blob/1cebce44f4218a6f238f89c84735936496fbe57c/recipes/libmysqlclient/all/conanfile.py?plain=1#L90

Happy coding 🐸
