### ISSUE TITLE
[package] qt/<any>: shared=False might be putting users in violation of the LGPL

### ISSUE THREAD

**Issue by ruilvo** [conan-io/conan-center-index#4944]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/any**

I noticed the `qt` recipe uses the `shared=False` default. This might put less attentive users in violation of the LGPL, where you either have to do dynamic linking or distribute object files. I would argue for a `shared=True` default for `qt`.

**Comment by Croydon** [comment]
Having static builds is much more portable and the default across all recipes unless it is technically not possible to use libraries as static or less supported upstream etc.

I don't think we should add license consideration into this mix. Qt is not the only (L)GPL licensed library, if we do this, the default values for `shared` get pretty chaotic.

Whenever projects use work from other projects they have to evaluate the licenses. Using Conan makes no difference here.

**Comment by ruilvo** [comment]
I think that's fair. But you know that when people use their OS package manager or the online installer, they install the shared versions without even thinking. But yeah, I get that's not a conan concern. Disregard.
