### ISSUE TITLE
[package] mfast/1.2.1: missing file mfast_static.lib [windows]

### ISSUE THREAD

**Issue by blogdarkspot** [conan-io/conan-center-index#4945]
I have been trying to use the mFast recipe, call the conan install is ok, therefore when I call the cmake command occurs an error in cmake function **conan_basic_steps()**, see the log bellow.

  * Package Name/Version: **zlib/1.2.8**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 16 2019 MSVC 19.28.29910.0**
  * Conan version: **conan 1.34.1**
  * Python version: **Python 3.9.2**

### conanfile.txt
[requires]
gtest/1.10.0
benchmark/1.5.2
mfast/1.2.1

[generators]
cmake

### CMakeLists.txt

cmake_minimum_required(VERSION 3.18)

project (Sample VERSION 1.0.0 LANGUAGES C CXX)
cmake_policy(SET CMP0091 NEW)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
message("Compile with static runtime")
add_definitions("-std=c++17")

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)

conan_basic_setup()

### Steps to reproduce (Include if Applicable)
- create a conanfile.txt and a CMakeLists.txt with config above.
- create a build directory and change to it.
- run conan install --build=missing .. 
- run cmake ..

the error will occur.

### Logs 

-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.28.29910.0
-- The CXX compiler identification is MSVC 19.28.29910.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Compile with static runtime
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: C:/Projects/feeder/build
CMake Error at C:/.conan/3aff74/1/res/mFASTTargets.cmake:76 (message):
  The imported target "mfast_static" references the file

     "C:/J/w/BuildSingleReference@2/s/82f656/1/lib/mfast_static.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

     "C:/.conan/3aff74/1/res/mFASTTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/.conan/3aff74/1/res/mFASTTools.cmake:12 (include)
  build/conanbuildinfo.cmake:1564 (include)
  build/conanbuildinfo.cmake:1040 (conan_include_build_modules)
  CMakeLists.txt:11 (conan_basic_setup)

```
Put your log output here
```

</details>

**Comment by SpaceIm** [comment]
There is something wrong in this recipe, all this block is suspicious:
https://github.com/conan-io/conan-center-index/blob/0ee26b2e01bee6a273da9c63a84d4a76e6760f38/recipes/mfast/all/conanfile.py#L82-L90

What I understand is that:
- this recipe keeps the config file with a trick, which is bad bad bad in CCI
- the config/targets file generated by mFAST build system are not relocatable, so it breaks

**Comment by SpaceIm** [comment]
Could you try with modifications in https://github.com/conan-io/conan-center-index/pull/4951 please?

**Comment by blogdarkspot** [comment]
sorry answer later, I'll try now
