### ISSUE TITLE
[package] boost/1.74.0 :  shared builds of numa do not link on mac

### ISSUE THREAD

**Issue by Firefly35** [conan-io/conan-center-index#4950]
This bug seems related to the introduction of the numa build option from commit: 552189c1
In this changeset obviously, the shared build on windows disable the numa option, but not on mac OS.
Are macOS boost build tested upon commits ?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.74.0**
  * Operating System+version: **macOS Catalina**
  * Compiler+version: **Apple clang version 12.0.0 (clang-1200.0.32.27)**
  * Conan version: **conan 1.34.0**
  * Python version: **Python 2.7.16**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
conan install -o boost:shared=True -o boost:zlib=False -o boost:bzip2=False -s arch=x86_64 -s compiler.cppstd=17 -s build_type=Debug --build=missing boost/1.74.0@

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>
Undefined symbols for architecture x86_64:
  "boost::fibers::context::active()", referenced from:
      boost::fibers::numa::algo::work_stealing::pick_next() in work_stealing.o
  "boost::fibers::context::attach(boost::fibers::context*)", referenced from:
      boost::fibers::numa::algo::work_stealing::pick_next() in work_stealing.o
  "boost::fibers::context::detach()", referenced from:
      boost::fibers::numa::algo::work_stealing::awakened(boost::fibers::context*) in work_stealing.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...skipped <p/.conan/data/boost/1.74.0/_/_/package/9468156e6755c34daf1a1b8a98c1643cf64a2c6f/lib>libboost_fiber_numa.dylib for lack of <p/.conan/data/boost/1.74.0/_/_/build/9468156e6755c34daf1a1b8a98c1643cf64a2c6f/boost/bin.v2/libs/fiber/build/clng-drwn-12.0/dbg/nm-on/thrd-mlt/vsblt-hdn>libboost_fiber_numa.dylib...
...failed updating 1 target...
boost/1.74.0: 
boost/1.74.0: ERROR: Package '9468156e6755c34daf1a1b8a98c1643cf64a2c6f' build failed
boost/1.74.0: WARN: Build folder /.conan/data/boost/1.74.0/_/_/build/9468156e6755c34daf1a1b8a98c1643cf64a2c6f
ERROR: boost/1.74.0: Error in build() method, line 671
	self.run(full_command, run_environment=True)
	ConanException: Error 1 while executing DYLD_LIBRARY_PATH="/.conan/data/libiconv/1.16/_/_/package/d98fae1010d1fb9e7f79a1e8a72bbf129d8660a2/lib" DYLD_FRAMEWORK_PATH="" b2 -q numa=on target-os=darwin architecture=x86 address-model=64 binary-format=mach-o abi=sysv --layout=system --user-config=/.conan/data/boost/1.74.0/_/_/source/source_subfolder/tools/build/user-config.jam -sNO_ZLIB=1 -sNO_BZIP2=1 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.iconv=on boost.locale.icu=off --disable-icu threading=multi visibility=hidden link=shared variant=debug --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-fiber --with-filesystem --with-graph --with-iostreams --with-locale --with-log --with-math --with-nowide --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure --with-wave toolset=clang-darwin cxxflags=-std=c++17 pch=on -sICONV_PATH=/.conan/data/libiconv/1.16/_/_/package/d98fae1010d1fb9e7f79a1e8a72bbf129d8660a2 linkflags="-stdlib=libc++" cxxflags="-fPIC -stdlib=libc++" install --prefix=/.conan/data/boost/1.74.0/_/_/package/9468156e6755c34daf1a1b8a98c1643cf64a2c6f -j16 --abbreviate-paths -d0 --debug-configuration --build-dir="/.conan/data/boost/1.74.0/_/_/build/9468156e6755c34daf1a1b8a98c1643cf64a2c6f"
</details>

**Comment by dmn-star** [comment]
My workaround https://github.com/conan-io/conan-center-index/issues/4339#issuecomment-766172860

**Comment by Firefly35** [comment]
I used another workaround : I set boost:numa=false when boost:shared is True in my package dependencies description.
