### ISSUE TITLE
[service] tools.vswhere() raise exception in CI

### ISSUE THREAD

**Issue by Woazim** [conan-io/conan-center-index#4954]
Using `tools.vswhere()` in `validate()` function of a recipe raises a `ConanException: Cannot locate vswhere in 'Program Files'/'Program Files (x86)' directory nor in PATH` when run by CCI CI/CD.

This is a: [use case](https://github.com/conan-io/conan-center-index/pull/4630#issuecomment-786731580).

There is no problem when recipe is created on my computer or windows docker images using MS build tools.

Could you investigate this bug?
_vswhere.exe_ should be located in _C:\Program Files (x86)\Microsoft Visual Studio\Installer_

Using vswhere in validate() function could be used to determine the exact version of Visual Studio (major and minor version numbers). This information can be important to know which new C++ features the compiler supports and to throw ConanInvalidConfiguration when not supported.

**Comment by jgsogo** [comment]
This is not a bug. The `validate()` method will be executed in a Linux container before delegating the build to a Windows machine. If the `validate()` computes a ConanInvalidConfiguration then the build won't take place.

Let's move to the recipe and see how can we work on this issue for that use-case.
