### ISSUE TITLE
[package] flann/1.9.1: Add option to not remove embedded lz4

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan-center-index#4969]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **flann/1.9.1**

This is more a feature request but wasn't sure the best place to put it. 

The existing flann/1.9.1 recipe strips out the embedded lz4 code and adds it as an external dependency. When building pcl 1.9.1 with the provided cmake files this leads to a linking error since it can't find lz4/doesn't link against the external lz4. I'd like to add an option to have the consumer choose if the flann recipe should remove the embedded lz4 code or not, which will make it easier for us to build pcl 1.9.1, with minimal changes to the pcl 1.9.1 provided CMakeLists.txt.

I already have some proposed changes and will create a PR.

**Comment by SpaceIm** [comment]
You can use `pkg-config` generator for PCL 1.9.1: https://github.com/PointCloudLibrary/pcl/blob/pcl-1.9.1/cmake/Modules/FindFLANN.cmake, and issues with flann should vanish.

**Comment by nichmj01** [comment]
Thanks! I will look at it when I get a chance.

**Comment by madebr** [comment]
Can you please post the complete build log (=stdout/stderr + configure.log)? 
#4970 is not a pleasing solution and might cause problems as soon as some library needs lz4 too.

**Comment by SpaceIm** [comment]
You can also check how flann is handled in the PR adding PCL 1.11.1 in CCI: https://github.com/conan-io/conan-center-index/pull/1891
Note than between 1.9.1 and 1.11.1 PCL build files have slightly changed the way they find flann libraries to something more robust.

**Comment by madebr** [comment]
@nichmj01
On what compiler+os+arch are you encountering this problem?
Also, where can I find the pcl recipe that is causing problems?

**Comment by nichmj01** [comment]
@madebr 
Thanks for following up on this and sorry for the delay in responding. I've already moved on from this problem by modifying the recipe from conan-center to do what I need and at this point pursuing the solutions presented here is not worth the effort.

I understand the resistance to my PR and can agree, in principle, to the underlying philosophy and reasoning. However, to abide by that philosophy incurs more overhead than is acceptable at this time. The strong resistance was also a bit surprising considering that what I was asking for was to have the flann recipe create a binary that is equivalent to what would be created from the official flann 1.9.1 release. Was it bad that flann embedded lz4 into their code? sure, maybe; it depends on their goals. Does it make upgrading lz4 more difficult later? Definitely. However, they did what they did and I have to work with this specific version. Can I modify pcl 1.9.1 to point to a non-embedded lz4? Sure, but that means I have to dig into the pcl build to understand how to do that; which adds time and effort. It may be "easy" to do; but if I don't know to do it, it's not easy. I was hoping that I could make a small/simple change to the pcl cmake files to use conan packages (ie add the lines to include the conan generated .cmake files) but it seems that isn't possible; primarily due to a philosophical decision. Again, I don't think that philosophy is wrong; I just think it creates an artificial barrier.
