### ISSUE TITLE
[package] libgeotiff/1.6.0: Add the rpath option

### ISSUE THREAD

**Issue by arttet** [conan-io/conan-center-index#4976]
If the option "shared" is True, the requirements cannot be found. We should use the "rpath".

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libgeotiff/1.6.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
libgeotiff:shared = True
```

### Steps to reproduce (Include if Applicable)
```
ldd libgeotiff.so
```
```
  	libtiff.so.5 => not found

	libproj.so.9 => not found
```
https://github.com/conan-io/conan-center-index/pull/4975

**Comment by SpaceIm** [comment]
Please provide a reproducible example, I'm not sure but I think you're not properly using conan.

**Comment by arttet** [comment]
You are right. This receipt already works well. I had the problem because I used the old version of libgeotiff/1.4.2.
