### ISSUE TITLE
[package] eigen/3.3.9 is missing CMake configuration files

### ISSUE THREAD

**Issue by maxnoe** [conan-io/conan-center-index#4979]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **eigen/3.3.9**
  * Operating System+version: **Manaro Linux (following the arch repositories)**
  * Compiler+version: **GCC 10.2.0**
  * Conan version: **conan 1.34.1**
  * Python version: **Python 3.8.7**

The eigen package is not installing the cmake config files needed to `find_package(Eigen3)`, making the use of the `cmake_paths` approach impossible.

These files are shipped with my system eigen package:

```
/usr/share/eigen3/cmake/Eigen3Config.cmake
/usr/share/eigen3/cmake/Eigen3ConfigVersion.cmake
/usr/share/eigen3/cmake/Eigen3Targets.cmake
/usr/share/eigen3/cmake/UseEigen3.cmake
```

But are not part of the conan package:

```
❯ ll /home/maxnoe/.conan/data/eigen/3.3.9/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
total 56K
drwxr-xr-x 3 maxnoe maxnoe 4,0K 19. Mär 15:00 include
drwxr-xr-x 2 maxnoe maxnoe 4,0K 19. Mär 15:00 licenses
-rw-r--r-- 1 maxnoe maxnoe  292 19. Mär 15:00 conaninfo.txt
-rw-r--r-- 1 maxnoe maxnoe  43K 19. Mär 15:00 conanmanifest.txt
```

(No share directory)

**Comment by SpaceIm** [comment]
Yes, like all CCI recipes, please use `cmake_find_package` and/or `cmake_find_package_multi` generators

**Comment by maxnoe** [comment]
Thanks, but that approach doesn't seem to work with boost. I have a library both depending on Boost and Eigen and only want to enable using conan to install those, not require it.

**Comment by SpaceIm** [comment]
It should work with boost CCI recipe, what's the issue?
By "not require it", you mean you want a transparent integration of conan? cmake_find_package and cmake_find_package_multi are exactly the appropriate generators.

**Comment by maxnoe** [comment]
It seems that `FindPackage(Boost REQUIRED)` uses the cmake default find boost and not the conan provided one and then fails.

I was able to fix it by doing


```
find_package(Boost CONFIG)
if(NOT Boost_FOUND)
  find_package(Boost REQUIRED)
endif()
```

Is that the way to go? Or is there a better solution?

**Comment by SpaceIm** [comment]
The way to go is to use `cmake_find_package` if at least one of your dependency has also a built-in module file in cmake (which is the case for Boost), and `cmake_find_package_multi` for others libraries.
Just use both generators, and write an agnostic CMakeLists (no CONFIG in find_package(Boost))

**Comment by maxnoe** [comment]
Thank you very much for you time, specifying both generators and using `CMAKE_PREFIX_PATH` to point to the directory with the generated files works!
