### ISSUE TITLE
[request] imgui/1.82

### ISSUE THREAD

**Issue by SetoKaiba** [conan-io/conan-center-index#5005]
### Package Details
  * Package Name/Version: **imgui/1.82**
  * Changelog: **https://github.com/ocornut/imgui/releases/tag/v1.82**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by anton-danielsson** [comment]
@SetoKaiba Seems to be fixed in https://github.com/conan-io/conan-center-index/pull/5070?
Close issue?

**Comment by SetoKaiba** [comment]
ok
