### ISSUE TITLE
[question] Cyclical dependencies from zlib and minizip

### ISSUE THREAD

**Issue by anagno** [conan-io/conan-center-index#5009]
Hello Everyone,

I was wondering what is the difference between the minizip and the zlib libraries. Both 
libraries use the same source (i.e. the zlib source code, but from different sources) 
and they have cyclical (invisible) dependencies. The zlib library is building the minizip
library (with CMakeLists_minizip) and the minizip library has a dependency from zlib. 
Is that necessary? Am I missing something? Can it be re-factored somehow? 

KR,
Vasileios

**Comment by uilianries** [comment]
> I was wondering what is the difference between the minizip and the zlib libraries. 

https://zlib.net/zlib_faq.html#faq41

> Can it be re-factored somehow?

Yes. We have separated packages now, it just need a re-factory. In the past we tried to keep both at same package, because both are in same folder.
