### ISSUE TITLE
[package] spdlog/1.8.2: no exception thrown if libstdc++ standard is not fulfilled

### ISSUE THREAD

**Issue by MaxSac** [conan-io/conan-center-index#5013]
I try to install the spdlog package at multiple machines. If the libstdc++ is not libstdc++11 the installation passes, but the linking process crashes. I think the error could be thrown due to installation that it is incompatible with libstdc++ and libstdc++11 is required.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spdlog/1.8.2**
  * Operating System+version: **Arch/MacOs**
  * Compiler+version: **GCC 10**
  * Conan version: **conan 1.33.1**
  * Python version: **Python 3.9.2**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Minimal working example

example.cxx:
``` 
#include "spdlog/spdlog.h"
int main()
{
    spdlog::info("Hello, {}!", "World");
}
```

 CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.14)

project(test)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_executable(example example.cxx)
target_link_libraries(example CONAN_PKG::spdlog)
```

conanfile.txt:
``` 
[requires]
spdlog/1.8.2
[generators]
cmake
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

/usr/bin/ld: CMakeFiles/example.dir/example.cxx.o: in function `void spdlog::logger::log_<fmt::v7::basic_string_view<char>, char const (&) [6]>(spdlog::source_loc, spdlog::level::level_enum, fmt::v7::basic_string_view<char> const&, char const (&) [6])':
example.cxx:(.text._ZN6spdlog6logger4log_IN3fmt2v717basic_string_viewIcEEJRA6_KcEEEvNS_10source_locENS_5level10level_enumERKT_DpOT0_[_ZN6spdlog6logger4log_IN3fmt2v717basic_string_viewIcEEJRA6_KcEEEvNS_10source_locENS_5level10level_enumERKT_DpOT0_]+0x257): undefined reference to `spdlog::logger::err_handler_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: example.cxx:(.text._ZN6spdlog6logger4log_IN3fmt2v717basic_string_viewIcEEJRA6_KcEEEvNS_10source_locENS_5level10level_enumERKT_DpOT0_[_ZN6spdlog6logger4log_IN3fmt2v717basic_string_viewIcEEJRA6_KcEEEvNS_10source_locENS_5level10level_enumERKT_DpOT0_]+0x2cc): undefined reference to `spdlog::logger::err_handler_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status

</details>

**Comment by SpaceIm** [comment]
Why test_package works with libstdc++ if it is not supported?

**Comment by MaxSac** [comment]
Oh I seem to have overlooked something. Thanks anyway for the help and sorry for the confusion!
