### ISSUE TITLE
[gdal/3.2.1] need a build for  visual studio 2015/2017 on Windows.

### ISSUE THREAD

**Issue by nowgain-nowpain** [conan-io/conan-center-index#5016]
I am still using visual studio 2015. Want to upgrade gdal to 3.2.1, but noticed that gdal/3.2.1 on Windows 10 requires visual studio 2019. Could you please have a build for vs2015 and vs 2017 with options shared and settings for both debug and release? 
Thanks you so much.

**Comment by SpaceIm** [comment]
I requires https://github.com/conan-io/conan-center-index/issues/4195 since gdal 3.2.1 requires ATL.

**Comment by ceng1996** [comment]
Would it be possible to update the recipe to wrap lines 208-210 around checking an option that would allow someone wanting to build this recipe for Visual Studio 2015?  Currently, we are not able to build this recipe with our own Visual Studio 2015 because an exception gets thrown.
