### ISSUE TITLE
[package] openssl/any: Fix OpenSSL versions 1.1.1 & newer for watchOS

### ISSUE THREAD

**Issue by paulo-coutinho** [conan-io/conan-center-index#5025]
fork() is unavailable on watchOS. This adds and applies a patch file when
building for watchOS and sets an argument for the compiler.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openssl/any**

Make the same thing done for tvOS, but adding on IFs the watchOS:
https://github.com/conan-io/conan-center-index/pull/1586/files

**Comment by paulo-coutinho** [comment]
I made a PR:
https://github.com/conan-io/conan-center-index/pull/5026

**Comment by madebr** [comment]
@paulo-coutinho 
This issue can be closed.
Thanks for the pr!
