### ISSUE TITLE
[request] aeron/1.31.2

### ISSUE THREAD

**Issue by lukaszlaszko** [conan-io/conan-center-index#5033]
### Package Details
  * Package Name/Version: **aeron/1.31.2**
  * Website: **https://github.com/real-logic/aeron/wiki**
  * Source code: **https://github.com/real-logic/aeron**

### Description Of The Library / Tool

Aeron offers efficient reliable UDP unicast, UDP multicast, and IPC message transport - with a core design goal of reaching the highest throughput with the lowest and most predictable latency of any messaging system. Aeron Archive allows message streams to be recorded to persistent storage for later, or real-time, replay. Aeron Cluster provides fault tolerant total ordering across multiple streams. Aeron is an open source project, hosted on GitHub.

**Comment by helmesjo** [comment]
FWIW I have an old [`conan-aeron`](https://github.com/helmesjo/conan-aeron) repository.

**Comment by lukaszlaszko** [comment]
Thanks Fred, indeed I took inspiration from your repo for the spin up. Good repository. The issue I ended up with seems to be coming from the test component, due to incompatibility of linked vs C runtimes.

**Comment by helmesjo** [comment]
@lukaszlaszko Oh, sorry, didn't see that you already had a PR ready for inclusion 😇
