### ISSUE TITLE
[package] qt/6.x.x: Missing QmlImportScanner component

### ISSUE THREAD

**Issue by mjvankampen** [conan-io/conan-center-index#5040]
The QmlImportScanner target (which looks like an alias to Qt6Qml to me) is missing, leading to failed builds if they rely on it.

**Comment by ericLemanissier** [comment]
we already declare [`qmlimportscanner`](https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L555). Do we miss an alias with different casing ? Do you think it's the same for all the other targets declared in https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L543-L556 ?

**Comment by mjvankampen** [comment]
Will check I think it is casing indeed.

**Comment by mjvankampen** [comment]
Seems to be just this one. It is exposed as a component not just a target (as the rest).
