### ISSUE TITLE
[package] itk/5.1.0: Cannot open include file: 'Eigen/Eigenvalues'

### ISSUE THREAD

**Issue by akalali** [conan-io/conan-center-index#5043]
I'm trying to build [dcmqi](https://github.com/QIICR/dcmqi), which requires DCMTK and ITK. I'm using [cmake-conan 0.15](https://github.com/conan-io/cmake-conan) and specify the ITK requirement for ITK 5.1.0. I use the recently changed conan-center-recipe - before it was updated I had problems with the [`UseITK.cmake`](https://github.com/conan-io/conan-center-index/issues/4712) not existing.

In order to make dcmqi aware of ITK I added
```
-DITK_INCLUDE_DIRS:PATH=${CONAN_INCLUDE_DIRS_ITK}
```
to `ExternalProject_Add(DCMQI`. Another variable, `${ITK_LIBRARIES}` is still empty (same for DCMTK).
I wonder why this error occurs and if it has something to do with the missing list of libraries.
Also, I don't know how to fill this empty variable. I don't see anything similar to `CONAN_INCLUDE_DIRS_ITK` for libraries. 

### Package and Environment Details
  * Package Name/Version: **itk/5.1.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 15**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.34.1**
  * Python version: **Python 3.8.2**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
------ Build started: Project: dcmqi, Configuration: Release x64 ------
ConverterBase.cpp
c:\.conan\f6dd46\1\include\itk-5.1\itkSymmetricEigenAnalysis.h(23): fatal error C1083: Cannot open include file: 'Eigen/Eigenvalues': No such file or directory
ImageSEGConverter.cpp
c:\.conan\f6dd46\1\include\itk-5.1\itkSymmetricEigenAnalysis.h(23): fatal error C1083: Cannot open include file: 'Eigen/Eigenvalues': No such file or directory
ParaMapConverter.cpp
c:\.conan\f6dd46\1\include\itk-5.1\itkSymmetricEigenAnalysis.h(23): fatal error C1083: Cannot open include file: 'Eigen/Eigenvalues': No such file or directory
Generating Code...
Done building project "dcmqi.vcxproj" -- FAILED.
```

</details>

**Comment by SpaceIm** [comment]
Use `cmake_find_package_multi` generator.

**Comment by akalali** [comment]
I do use that generator.
My call to `conan_run` is
```
conan_cmake_run(REQUIRES dcmtk/3.6.5
                         itk/5.1.0
                BASIC_SETUP
                GENERATORS cmake_find_package_multi
                OPTIONS ${DCMTK_CONAN_OPTIONS}
                        ${ITK_CONAN_OPTIONS}
                BUILD missing
)
```

As a result the following files are generated:
```
Eigen3Config.cmake
Eigen3ConfigVersion.cmake
Eigen3Target-release.cmake
Eigen3Targets.cmake
```

**Comment by akalali** [comment]
This is still open.

I also stumbled upon something:
I have a project where DCMQI is used as an ExternalProject and DCMTK and ITK are also included as ExternalProject.
In that project, the call to `ExternalProject` looks like this:
```
ExternalProject_Add(DCMQI
  GIT_REPOSITORY https://github.com/QIICR/dcmqi.git
  GIT_TAG v1.2.4
  UPDATE_COMMAND ""
  INSTALL_COMMAND ""
  CMAKE_GENERATOR ${gen}
  CMAKE_GENERATOR_PLATFORM ${gen_platform}
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DDCMQI_BUILD_APPS:BOOL=OFF
    -DDCMTK_DIR:PATH=${DCMTK_DIR}
    -DITK_DIR:PATH=${ITK_DIR}
    -DITK_NO_IO_FACTORY_REGISTER_MANAGER:BOOL=ON
    -DDCMQI_SUPERBUILD:BOOL=OFF
  DEPENDS ${proj_DEPENDENCIES}
)
```

whereas in my new project, where I want to combine DCMQI as an ExternalProject with DCMTK and ITK being installed via Conan, the call to `ExternalProject` looks like this:
```
ExternalProject_Add(DCMQI
  GIT_REPOSITORY https://github.com/QIICR/dcmqi.git
  GIT_TAG ea4f0809c8ba771e262a69b5f81d547a3945b264
  UPDATE_COMMAND ""
  INSTALL_COMMAND ""
  CMAKE_CACHE_ARGS
    -DCMAKE_MODULE_PATH:PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_PREFIX_PATH:PATH=${CMAKE_PREFIX_PATH}
    -DDCMTK_INCLUDE_DIRS:PATH=${CONAN_INCLUDE_DIRS_DCMTK}
    -DITK_INCLUDE_DIRS:PATH=${CONAN_INCLUDE_DIRS_ITK}
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DDCMQI_BUILD_APPS:BOOL=OFF
    -DITK_USE_FILE:PATH=${ITK_BUILD_MODULES_PATHS_RELEASE}
    -DITK_NO_IO_FACTORY_REGISTER_MANAGER:BOOL=ON
    -DDCMQI_SUPERBUILD:BOOL=OFF
)
```

I wonder what the difference is between using
```
-DDCMTK_DIR:PATH=${DCMTK_DIR}
-DITK_DIR:PATH=${ITK_DIR}
```

in the first variant and

```
-DDCMTK_INCLUDE_DIRS:PATH=${CONAN_INCLUDE_DIRS_DCMTK}
-DITK_INCLUDE_DIRS:PATH=${CONAN_INCLUDE_DIRS_ITK}
```

in the second variant?

Should I be able to also point DCMQI to the `DCMTK_DIR:PATH` and the `ITK_DIR_PATH` in the second variant, after using `find_package` on these packages?

**Comment by SpaceIm** [comment]
`package_info()` of ITK recipe is not properly modeled for the moment. The best you can do is to link to `ITK::ITK` imported target generated through `cmake_find_package_multi`, or contribute to this recipe in CCI.
`${ITK_LIBRARIES}` doesn't exist in `cmake_find_package_multi`, you may prefer `cmake_find_package` in this case.

**Comment by akalali** [comment]
Thank you for your reply. I wouldn't know how to link to `ITK::ITK`. I'm simply downloading the ITK package and setting the path to ITK for the DCMQI project. As far as I can see there is nothing I could do to change how DCMQI handles ITK, at least I don't want to modify the DCMQI project by patching it or similar.

I can not use `cmake_find_package` since DCMQI uses `find_package(ITK NO_MODULE REQUIRED)` to find ITK.

**Comment by perseoGI** [comment]
Hi there!
I was reviewing old issues and I have come across this one.
This issue is really related with how conan v1 handle and exposes the libraries.

I'm closing this issue as it doesn't make much sense anymore. 
If for some reason this problem remains, do not hesitate to reopen this issue adding new traces for this problem. Preferably using conan v2.

Happy coding 🐸
