### ISSUE TITLE
[package] libpq/13.2: needless option "with_zlib"

### ISSUE THREAD

**Issue by sabelka** [conan-io/conan-center-index#5055]
The recipe for libpq contains the option `with_zlib`, which is then passed as `--with-zlib` to the configure script of PostgreSQL.

However, zlib is not used at all in libpq (it is used in only in other parts of PostgreSQL, e.g. `pg_dump`).
libpq can be built completely without zlib, without any loss in functionality.

Therefore, the option `with_zlib` in the recipe for libpq is redundant. Enabling it, just adds an unnecessary dependency on zlib.
It can be completely removed, and `--without-zlib` always passed to the configure script of PostgreSQL.

**Comment by SSE4** [comment]
related: #5020

**Comment by SpaceIm** [comment]
@sabelka could you submit a PR with these modifications?

**Comment by sabelka** [comment]
I'll try ;-)
