### ISSUE TITLE
[question] Build requirement `cmake`

### ISSUE THREAD

**Issue by kebadopp** [conan-io/conan-center-index#5091]
In my environment setup for conan I have not installed `cmake`. I rather set a build requirement to `cmake` for my own packages.
But some external packages coming from conan-io e.g. `gtest` need to be build from scratch, which is not possible due to missing `cmake`.

So my question regards the policy / best practice for the environment running conan.
Why is `cmake` not added generally as requirement for conan packages using `cmake` to build?

E.g. add
```python
def build_requirements(self):
   self.build_requires("cmake/[^3.16.2]")
```
to https://github.com/conan-io/conan-center-index/blob/master/recipes/gtest/all/conanfile.py

**Comment by uilianries** [comment]
Adding cmake to all packages can be boring and hard to maintain. You can fix a single version, which will guarantee same behavior in your [profile](https://docs.conan.io/en/latest/reference/profiles.html):

```ini 
# ~/.conan/profiles/default
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
cmake/3.15.0
[env]
```

**Comment by kebadopp** [comment]
solved
