### ISSUE TITLE
Harfbuzz 2.8.0 on MacOS

### ISSUE THREAD

**Issue by jszirani** [conan-io/conan-center-index#5110]
Hi,

We're currently experiencing issues when to use the harfbuzz library on macos

The configuration is the following

```
    [conan] Configuration:
    [conan] [settings]
    [conan] arch=x86_64
    [conan] arch_build=x86_64
    [conan] build_type=Release
    [conan] compiler=apple-clang
    [conan] compiler.cppstd=17
    [conan] compiler.libcxx=libc++
    [conan] compiler.version=11.0
    [conan] os=Macos
```

and the first failure is

```
    [conan] -- Performing Test COMPILER_SUPPORTS_CXX11
    [conan] -- Performing Test COMPILER_SUPPORTS_CXX11 - Failed
    [conan] -- The compiler /Library/Developer/CommandLineTools/usr/bin/c++ has no C++11 support. Please use a different C++ compiler.
```

and later 

`    
[conan] /Users/svc-gsp/.conan/data/harfbuzz/2.8.0/_/_/build/782bd26019daaaa6e0984ffabd10aa8ada93b2d4/source_subfolder/src/hb-meta.hh:123:23: error: 'auto' not allowed in function return type
`

harfbuzz library needs c++ 11

The reason for the failure has been tracked down to

```
        del self.settings.compiler.libcxx
        del self.settings.compiler.cppstd
```

in harfbuzz's conan file (see https://github.com/conan-io/conan-center-index/blob/master/recipes/harfbuzz/all/conanfile.py line 53)

it is unclear while this line is needed, but in our local experiments, if we remove this line it works

Cheers

**Comment by SpaceIm** [comment]
It's a mistake, those lines are for C libraries, but harfbuzz is a C++ library with C API. I see also several others flaws in this recipe, I'll try to submit a PR.

**Comment by jszirani** [comment]
Cool!

It appears that the c++ version has to be set to 17.

**Comment by SpaceIm** [comment]
Could you try https://github.com/conan-io/conan-center-index/pull/5136 please?

**Comment by jszirani** [comment]
Hey, so we test on windows and macos and it works with 5136 

On mac, we still witness a

-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Failed

but it compiles nonetheless, it's surely related to the fact that del self.settings.compiler.libcxx is still present 

thanks!
