### ISSUE TITLE
[package] qt/6.0.2 : can't create a package

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#5112]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.0.2**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.35.0**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
cd conan-center-index/recipes/qt/6.x.x
conan create . qt/6.0.2@

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Exporting package recipe
qt/6.0.2 exports: File 'conandata.yml' found. Exporting it...
qt/6.0.2 exports: Copied 1 '.yml' file: conandata.yml
qt/6.0.2: Calling export()
qt/6.0.2 export() method: Copied 1 '.conf' file: qtmodules6.0.2.conf
qt/6.0.2: A new conanfile.py version was exported
qt/6.0.2: Folder: /home/andrei/.conan/data/qt/6.0.2/_/_/export
qt/6.0.2: Using the exported files summary hash as the recipe revision: 93b6a2a2475b64f61974865d44d2003e 
qt/6.0.2: Package recipe modified in export, forcing source folder removal
qt/6.0.2: Use the --keep-source, -k option to skip it
qt/6.0.2: Removing the local binary packages from different recipe revisions
qt/6.0.2: Exported revision: 93b6a2a2475b64f61974865d44d2003e
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

qt/6.0.2: Forced build from source
ERROR: Conflict in cmake/3.19.1:
    'cmake/3.19.1' requires 'openssl/1.1.1i' while 'qt/6.0.2' requires 'openssl/1.1.1j'.
    To fix this conflict you need to override the package 'openssl' in your root package.

```

</details>

**Comment by paulo-coutinho** [comment]
You can override and fix this conflict like here:
https://github.com/ezored/ezored/blob/master/files/targets/linux_app/conan/recipe/conanfile.py#L65

**Comment by AndreyMlashkin** [comment]
I know. I am just wondering, how does it work in CI?

**Comment by paulo-coutinho** [comment]
Maybe it was built before conflict, i think

**Comment by prince-chrismc** [comment]
> Maybe it was built before conflict, i think

The is most certainly always it. At some point in time there was a recipe revision of `cmake` which used the same openssl version as the `qt` recipe that was being merged.

Now that you are trying to install `qt` it is downloading a newer recipe revision which has a different version of openssl...

It's in part related to the Conan graph not including the effect of build requirements when it makes package IDs

Hopefully that helps explain where this comes from =)

**Comment by ericLemanissier** [comment]
This conflict is now solved. You need to update your local cache by using `-u` command line argument
