### ISSUE TITLE
[service] Please remove user mentions from merge commit body

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#5135]
There's a lot of notifications. Recently a few contributors tagged 👤 me in commit message which have been merged. Now each time a fork pushes one to master 📣  I get a notification which is hard to filter since it's a notification from CCI which in the past from been worthwhile.

Please remove `@` when the bot merges PR 🙏 to reduce notification. It would be absolutely appreciated!

**Comment by uilianries** [comment]
I usually create email rules to filtering, but of course, we can do it better.

**Comment by SpaceIm** [comment]
https://github.community/t/i-am-getting-notifications-due-to-being-mentioned-in-a-commit/172531

**Comment by prince-chrismc** [comment]
That might explains why it's gotten to bad! Thanks for the link I had not thought to check the forum.

**Comment by jgsogo** [comment]
Thanks for finding the issue in the community forum. I expect the Octocat will take care of this one :octocat:

**Comment by prince-chrismc** [comment]
This has been fixed =)
