### ISSUE TITLE
[package] openssl/1.0.2u: 2 undefined symbols

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan-center-index#5140]
It feels like the conan-center-index recipe and test package were updated for v1.1.x of openssl but perhaps weren't tested against older versions still mentioned in conandata.yml such as 1.0.2u?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openssl/1.0.2u**
  * Operating System+version: **Windows Server 2019 Version 1809**
  * Compiler+version: **MSFT VisualStudio 2015**
  * Docker image: **NA**
  * Conan version: **conan 1.32.0**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
E:\DevelopBp\mmaguir1\src\conan\conan-center-index\recipes\openssl\1.x.x\test_package>conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
compiler=Visual Studio
compiler.version=14
compiler.toolset=v140
arch=x86_64
arch_build=x86_64
compiler.runtime=MDd
build_type=Debug
[options]
[build_requires]
*: cmake/3.19.3@bloomberg/stable, strawberryperl/5.30.0.1@bloomberg/stable, cmake/3.19.3@bloomberg/stable, strawberryperl/5.30.0.1@bloomberg/stable, cmake/3.19.3@bloomberg/stable, strawberryperl/5.30.0.1@bloomberg/stable
[env]
```

### Steps to reproduce (Include if Applicable)

```
E:\DevelopBp\mmaguir1\src\conan\conan-center-index\recipes\openssl\1.x.x>conan export . 1.0.2u@PORT/stable
E:\DevelopBp\mmaguir1\src\conan\conan-center-index\recipes\openssl\1.x.x>conan install openssl/1.0.2u@PORT/stable --build=openssl
E:\DevelopBp\mmaguir1\src\conan\conan-center-index\recipes\openssl\1.x.x>cd test_package
E:\DevelopBp\mmaguir1\src\conan\conan-center-index\recipes\openssl\1.x.x\test_package>conan test . openssl/1.0.2u@PORT/stable
```

### Logs (Include/Attach if Applicable)

```
E:\nX\nX_nightlybuild\workspace\Conan_pipeline\recipes\openssl\1.x.x\test_package\digest.cpp(52): warning C4101: 'digest_len': unreferenced local variable [E:\nX\nX_nightlybuild\workspace\Conan_pipeline\recipes\openssl\1.x.x\test_package\build\315c29ff567efe21f537dcf6dadd9297a265db62\digest.vcxproj]
digest.obj : error LNK2019: unresolved external symbol OpenSSL_version referenced in function main [E:\nX\nX_nightlybuild\workspace\Conan_pipeline\recipes\openssl\1.x.x\test_package\build\315c29ff567efe21f537dcf6dadd9297a265db62\digest.vcxproj]
digest.obj : error LNK2019: unresolved external symbol OPENSSL_init_ssl referenced in function main [E:\nX\nX_nightlybuild\workspace\Conan_pipeline\recipes\openssl\1.x.x\test_package\build\315c29ff567efe21f537dcf6dadd9297a265db62\digest.vcxproj]
E:\nX\nX_nightlybuild\workspace\Conan_pipeline\recipes\openssl\1.x.x\test_package\build\315c29ff567efe21f537dcf6dadd9297a265db62\bin\digest.exe : fatal error LNK1120: 2 unresolved externals [E:\nX\nX_nightlybuild\workspace\Conan_pipeline\recipes\openssl\1.x.x\test_package\build\315c29ff567efe21f537dcf6dadd9297a265db62\digest.vcxproj]
```

**Comment by michaelmaguire** [comment]
Asked for help in the #conan cpplang slack chat:

https://cpplang.slack.com/archives/C41CWV9HA/p1617713165065500

> Eric Lemanissier 14:46
> I just ran conan test . openssl/1.0.2u@ successfully in conan-center-index\recipes\openssl\1.x.x\test_package (but it's compiler.version=16 ) (edited)
> 14:47
> can you try conan create openssl/1.0.2u@PORT/stable --build=openssl instead of conan export,conan export and conan test ?
> 

We retried internally with `compiler.version=16` and still got the same error:

```
2021-04-12 11:27:00 |  [Conan_pipeline_master] $ cmd.exe /C "conan create . 1.0.2r@PORT/stable --json conanCreateOutput_vs2019_16_v142_Debug.json --build=missing --lockfile=package_per_profile_deps_vs2019_16_v142_Debug.lock && exit %%ERRORLEVEL%%"
2021-04-12 11:27:01 |  Using lockfile: 'D:\J\workspace\Conan_pipeline_master\package_per_profile_deps_vs2019_16_v142_Debug.lock'
2021-04-12 11:27:01 |  Exporting package recipe
2021-04-12 11:27:01 |  OpenSSL/1.0.2r@PORT/stable: The stored package has not changed
2021-04-12 11:27:01 |  OpenSSL/1.0.2r@PORT/stable: Using the exported files summary hash as the recipe revision: 51ab7ea3aec1fee6a466911ad679518e 
2021-04-12 11:27:01 |  OpenSSL/1.0.2r@PORT/stable: Exported revision: 51ab7ea3aec1fee6a466911ad679518e
2021-04-12 11:27:01 |  Installing and building OpenSSL/1.0.2r@PORT/stable
2021-04-12 11:27:01 |  Configuration:
2021-04-12 11:27:01 |  [settings]
2021-04-12 11:27:01 |  arch=x86_64
2021-04-12 11:27:01 |  arch_build=x86_64
2021-04-12 11:27:01 |  build_type=Debug
2021-04-12 11:27:01 |  compiler=Visual Studio
2021-04-12 11:27:01 |  compiler.runtime=MDd
2021-04-12 11:27:01 |  compiler.toolset=v142
2021-04-12 11:27:01 |  compiler.version=16
2021-04-12 11:27:01 |  os=Windows
2021-04-12 11:27:01 |  os_build=Windows
2021-04-12 11:27:01 |  [options]
2021-04-12 11:27:01 |  [build_requires]
2021-04-12 11:27:01 |  *: cmake/3.19.3@bloomberg/stable, strawberryperl/5.30.0.1@bloomberg/stable
2021-04-12 11:27:01 |  [env]
[...]
2021-04-12 11:34:56 |    Checking Build System
2021-04-12 11:34:57 |    Building Custom Rule D:/J/workspace/Conan_pipeline_master/test_package/CMakeLists.txt
2021-04-12 11:34:57 |    md5.cpp
2021-04-12 11:34:57 |  D:\J\workspace\Conan_pipeline_master\test_package\md5.cpp(21,10): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\J\workspace\Conan_pipeline_master\test_package\build\3f7af1af95bd2e1558a8c298c35a71c2eaaa2419\md5.vcxproj]
2021-04-12 11:34:58 |  md5.obj : error LNK2019: unresolved external symbol OpenSSL_version referenced in function main [D:\J\workspace\Conan_pipeline_master\test_package\build\3f7af1af95bd2e1558a8c298c35a71c2eaaa2419\md5.vcxproj]
2021-04-12 11:34:58 |  md5.obj : error LNK2019: unresolved external symbol OPENSSL_init_ssl referenced in function main [D:\J\workspace\Conan_pipeline_master\test_package\build\3f7af1af95bd2e1558a8c298c35a71c2eaaa2419\md5.vcxproj]
2021-04-12 11:34:58 |  D:\J\workspace\Conan_pipeline_master\test_package\build\3f7af1af95bd2e1558a8c298c35a71c2eaaa2419\bin\md5.exe : fatal error LNK1120: 2 unresolved externals [D:\J\workspace\Conan_pipeline_master\test_package\build\3f7af1af95bd2e1558a8c298c35a71c2eaaa2419\md5.vcxproj]
2021-04-12 11:34:58 |
```

**Comment by madebr** [comment]
`openssl`'s test_package contains
https://github.com/conan-io/conan-center-index/blob/0705e3fbafb3e9379d37afcea88eaf6ebd106074/recipes/openssl/1.x.x/test_package/digest.cpp#L56-L60 and https://github.com/conan-io/conan-center-index/blob/0705e3fbafb3e9379d37afcea88eaf6ebd106074/recipes/openssl/1.x.x/test_package/digest.cpp#L94-L98. So I find it weird that these symbols end up used in `1.0.2u`.

Can you manually open the test_package solution in Visual Studio
```
cmake --open D:\J\workspace\Conan_pipeline_master\test_package\build\3f7af1af95bd2e1558a8c298c35a71c2eaaa2419
```
and check the value of `OPENSSL_VERSION_NUMBER`?

**Comment by ericLemanissier** [comment]
What is this md5.cpp file? Please try the recipe and test package currently in https://github.com/conan-io/conan-center-index/tree/master/recipes/openssl/1.x.x

**Comment by michaelmaguire** [comment]
> What is this md5.cpp file? Please try the recipe and test package currently in https://github.com/conan-io/conan-center-index/tree/master/recipes/openssl/1.x.x

We've tried both https://github.com/conan-io/conan-center-index/tree/master/recipes/openssl/1.x.x and also in desperation reverted back to older forks of https://github.com/conan-community/conan-openssl which previous had https://github.com/conan-community/conan-openssl/blob/5bfe36a23df0a8f8987f257d8e28e8ef192b317e/test_package/md5.cpp

**Comment by madebr** [comment]
Don't use the test_package of conan-community you linked to.
It's not designed to work with other versions then openssl 1.1.X.

Use https://github.com/conan-io/conan-center-index/blob/0705e3fbafb3e9379d37afcea88eaf6ebd106074/recipes/openssl/1.x.x/test_package/digest.cpp

**Comment by michaelmaguire** [comment]
> Don't use the test_package of conan-community you linked to.
> It's not designed to work with other versions then openssl 1.1.X.
> 
> Use https://github.com/conan-io/conan-center-index/blob/0705e3fbafb3e9379d37afcea88eaf6ebd106074/recipes/openssl/1.x.x/test_package/digest.cpp

We *did* try conan-center-index first --  see above https://github.com/conan-io/conan-center-index/issues/5140#issue-851373937 ) for Visual Studio 2015 or 2019.

We require a 1.0.2x version of OpenSSL, because 1.1.X made binary breaking changes my team is not ready to adjust to yet.

In one case above, we also tried falling back to our fork of an older version of the https://github.com/conan-community/conan-openssl. The commit we have for that is back from 2018 and is for 1.0.2p: https://github.com/conan-community/conan-openssl/commit/321c807d9629a808ef895fd7df3c38e3134eccdcc -- so it should have worked, e.g. for 1.0.2p.  

But neither conan-io/conan-center-index nor deprecated conan-community/conan-openssl worked for us for either VisualStudio 2015 or 2019.

We are trying to figure out what has changed, because we did build this once before in house a year or so ago.  

The one think that has changed is that we stopped using ActiveState perl, and started using strawberryperl.

**Comment by madebr** [comment]
> We _did_ try conan-center-index first -- see above [#5140 (comment)](https://github.com/conan-io/conan-center-index/issues/5140#issue-851373937) ) for Visual Studio 2015 or 2019.

Ok, can you please check the cmake test_package project?
See https://github.com/conan-io/conan-center-index/issues/5140#issuecomment-818240539

The `OPENSSL_VERSION_NUMBER` macro determines the version of the openssl headers.

> We require a 1.0.2x version of OpenSSL, because 1.1.X made binary breaking changes my team is not ready to adjust to yet.

Your use case is completely valid.

It looks like when compiling the test source, the compiler incorrectly thinks a 1.0.x openssl version is used.
But when linking, the 1.0.x symbols are not found.

> The one think that has changed is that we stopped using ActiveState perl, and started using strawberryperl.

The error is in the test package. Perl is only used when building openssl.

Also, please make sure to work with the most recent openssl conan-center-index recipe.

**Comment by michaelmaguire** [comment]
> Ok, can you please check the cmake test_package project?
> See [#5140 (comment)](https://github.com/conan-io/conan-center-index/issues/5140#issuecomment-818240539)

Will do, thanks for the suggestion.

> The error is in the test package. Perl is only used when building openssl.

I would like to hope the only error is with the test package, but was concerned there's something about the building of openssl causing the test package linking to fail.

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as `openssl/1.0.2u` is no longer supported by CCI.

Consider using newer versions of this recipe.
Happy coding 🐸
