### ISSUE TITLE
[request] cpr/1.6.0

### ISSUE THREAD

**Issue by zhaohuaxishi** [conan-io/conan-center-index#5141]
### Package Details
  * Package Name/Version: **cpr/1.6.0**
  * Changelog: **https://github.com/whoshuu/cpr/releases/tag/1.6.0**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by prince-chrismc** [comment]
Tons a build system changes https://github.com/whoshuu/cpr/compare/1.5.2...1.6.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR33-R39
