### ISSUE TITLE
[package] libiconv/1.15: failes to build with VS2010

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan-center-index#5168]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: libiconv/1.15
  * Operating System+version: Windows 10
  * Compiler+version: VS2010 / msvc 16.00
  * Conan version: conan 1.35.0
  * Python version: Python 3.9.2

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=10
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
conan create libiconv\all libiconv/1.15@jenkins/stable --build=libiconv

### Problem
The autotools configure stage fails as the conan recipe provides the flag "FS" to the autotools.flags
https://github.com/conan-io/conan-center-index/blob/ca6f7d48528d2ee4a0ee79271a29068f885fc1bb/recipes/libiconv/all/conanfile.py#L108
This flag is not supported in VS2010 / msvc 16.xx. I do not know if VS2012 supports this but I have tested the proposed changes with VS2010 and it built fine.

### Proposed Changes
Added the method ```_is_msvc_equal_or_newer_than_1800```.
```python
    @property
    def _is_msvc_equal_or_newer_than_1800(self):
        compiler = self.settings.get_safe("compiler")
        compiler_version = self.settings.get_safe("compiler.version")
        if ((not compiler) or (not compiler_version)):
            return False
        elif (compiler == "Visual Studio") and (tools.Version(compiler_version) >= "12"):
            return True
        elif (compiler == "msvc") and (tools.Version(compiler_version) >= "18"):
            return True
        return False
```
Modified the FS flag addition check to the newly provided method.
https://github.com/conan-io/conan-center-index/blob/ca6f7d48528d2ee4a0ee79271a29068f885fc1bb/recipes/libiconv/all/conanfile.py#L107
```
        if self._is_msvc_equal_or_newer_than_1800:
            self._autotools.flags.append("-FS")
```

Best regards

**Comment by perseoGI** [comment]
Hi there!
I was reviewing old issues and found this one, sorry for the delay 😅 

It seems this request have been addressed time ago, see https://github.com/conan-io/conan-center-index/blob/e50cb79d90fef64ce7f448f3f145593ab7072c17/recipes/libiconv/all/conanfile.py?plain=1#L104

This should have fix your problem!
Happy coding 🐸
