### ISSUE TITLE
[request] utfcpp/3.1

### ISSUE THREAD

**Issue by AndWass** [conan-io/conan-center-index#519]
### Package Details
  * Package Name/Version: **utfcpp/3.1**
  * Website: **https://github.com/nemtrif/utfcpp**
  * Source code: **https://github.com/nemtrif/utfcpp**

### Description Of The Library / Tool
UTF-8 with C++ in a Portable Way.
This is a small, C++98 compatible generic library. For anybody used to work with STL algorithms and iterators, it should be easy and natural to use. The library has been used a lot in the past ten years both in commercial and open-source projects and is considered feature-complete now.

**Comment by uilianries** [comment]
Hi @AndWass !

Thanks for requesting this package. I see that utfcpp is a header-only project and should be easy the be packaged. Don't you are interested in trying this one? We can help you writing the recipe. Also, we have some examples, for instance toml11: https://github.com/conan-io/conan-center-index/blob/43a118c23113c5f70da7be60b990483aaa09f74f/recipes/toml11/all/conanfile.py

Regards!

**Comment by AndWass** [comment]
Hi @uilianries 

I have made an attempt with #524 but think something is missing maybe?

**Comment by uilianries** [comment]
Hi @AndWass ! Thanks a lot!

Please, request your inclusion as Beta user in #4 

Conan Center Index is under Early Access Program, so only Beta user are able to open a PR.

Thanks again!
