### ISSUE TITLE
Policy wrt to dependencies of old versions of packages (cpprestsdk -> boost in this case)

### ISSUE THREAD

**Issue by TobiSchluter** [conan-io/conan-center-index#5196]
For instance this line:
https://github.com/conan-io/conan-center-index/blob/0705e3fbafb3e9379d37afcea88eaf6ebd106074/recipes/cpprestsdk/all/conanfile.py#L58
makes cpprestsdk depend on boost version 1.75.0. This was unconditionally changed when adding cpprestsdk/2.10.17. This implies that users of cpprestsdk/2.10.16 will suddenly get a different version of boost when they delete and rebuild their conan cache.

Is this intended? I actually ran into this when a rebuild suddenly failed while building openssl and/or bzip2 because I suddenly required inconsistent versions of boost, and while I understand the bookkeeping headaches it brings to maintain a list of versions for older releases, I find the current policy suboptimal.

**Comment by jgsogo** [comment]
Hi, @TobiSchluter . Conan provides a way to _lock_ your dependency graph and ensure every build will use exactly the same versions (and revisions) of every package in your dependency graph: [lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles.html?highlight=lockfile). If you use lockfiles you won't get affected by changes in the remotes, you will always retrieve the same [revision](https://docs.conan.io/en/latest/versioning/revisions.html) of every recipe (all revisions are available in remote conan-center).

If you _live at HEAD_ and get the latest revision of the recipes you might find some dependency changes (like the one you report) and also changes in the source code of the recipe (that can affect your build, of course). 

In ConanCenter the policy is to tend to use the _latests_ versions of the libraries (we update them when we make other changes to the recipes), trying to avoid version conflicts in the graph.

**Comment by TobiSchluter** [comment]
Thank you for the explanation. I will investigate lockfiles and especially how to distribute them within my organisation.

**Comment by jgsogo** [comment]
If you have any doubts, probably @solvingj can help you and advise you about the best way to manage these files within your organization.

**Comment by TobiSchluter** [comment]
Thanks. I see that it is still an in-development feature, but it will be very useful, and I'll definitely free some time to explore it.
