### ISSUE TITLE
unknown error downloading boost 1.72.0

### ISSUE THREAD

**Issue by wpadala420** [conan-io/conan-center-index#5198]
Please help, I got error downloading boost 1.72.0 :
boost/1.72.0: ERROR: Error downloading binary package: 'boost/1.72.0:84aa75c7e2b2b3d1cb01af39298d01342cf8d782'
ERROR: Exceeded 30 redirects.. [Remote: conan-center]

after this error , conan finishes work without checking the rest of packages

my conanfile:
[requires]
icu/64.2@bincrafters/stable
boost/1.72.0
openssl/1.0.2s
libpq/11.5
libpqxx/7.0.5
nlohmann_json/3.9.1

[generators]
cmake

[options]
icu:shared=True
boost:i18n_backend=iconv

[imports]
lib, *.so* -> ./bin

**Comment by Jean1995** [comment]
See issue #5197, this is a general problem at the moment

**Comment by jgsogo** [comment]
Everything should be back to normal now. Please, refer to that issue if something is not working.

Thanks for your patience.
