### ISSUE TITLE
[package] rapidcheck/20210107: MSVC Build failed when /std:c++latest was enabled

### ISSUE THREAD

**Issue by objectx** [conan-io/conan-center-index#5205]
This issue is caused by the MSVC's [`__cplusplus` value handling](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-160) and resolved in https://github.com/emil-e/rapidcheck/commit/fc616114a95a3198514f8b4ec9e354865fd6ecfc

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **rapidcheck/20210107**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 16.10.0 preview 1.0**
  * Docker image: **N/A**
  * Conan version: **conan 1.35.0**
  * Python version: **Python 3.9.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile vs2019-preview:
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
CC=c:/tools/MSVS/2019/Preview/VC/Tools/MSVC/14.29.29917/bin/HostX64/x64/cl.exe
CXX=c:/tools/MSVS/2019/Preview/VC/Tools/MSVC/14.29.29917/bin/HostX64/x64/cl.exe
```

### Steps to reproduce (Include if Applicable)
Use the rapidcheck/20210107 under the `/std:c++latest` enabled project.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
D:\dev\.conan\data\rapidcheck\20210107\_\_\package\fdbc383a9e967fa46b5abfb1a08af034f6a4acc5\include\rapidcheck/Compat.hpp(10): error C2039: 'result_of': is not a member of 'std'
c:\tools\MSVS\2019\Preview\VC\Tools\MSVC\14.29.29917\include\sstream(20): note: see declaration of 'std'```
</details>

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue as new newer version, `cci.20210702` introduced in https://github.com/conan-io/conan-center-index/issues/7026 solved this issue.

`std::result_of` was deprecated in C++17 https://es.cppreference.com/w/cpp/types/result_of, and despite it was not removed from standard until C++20, your latest version of std++ MSVC was not handling it well as you specified above.

Solution: use newer versions of this recipe!
Happy coding 🐸
