### ISSUE TITLE
[package] pkgconf/1.7.3: tools.get: file could not be opened successfully.

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan-center-index#5208]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **pkgconf/1.7.3**
  * Operating System+version: **OpenSUSE Leap  42.3 Docker**
  * Compiler+version: **GCC 8**
  * Docker image: **opensuse/leap:42.3**
  * Conan version: **conan 1.35.1**
  * Python version: **Python 3.9.4**

### Error
ERROR: pkgconf/1.7.3: Error in source() method, line 46
        tools.get(**self.conan_data["sources"][self.version])
        ReadError: file could not be opened successfully

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Put your profile output here
```

### Steps to reproduce (Include if Applicable)
conan install pkgconf/1.7.3@ --build

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
pkgconf/1.7.3: Configuring sources in /opt/conan/.conan/data/pkgconf/1.7.3/_/_/source
Downloading pkgconf-1.7.3.tar.xz completed [286.28k]                                     

ERROR: pkgconf/1.7.3: Error in source() method, line 46
        tools.get(**self.conan_data["sources"][self.version])
        ReadError: file could not be opened successfully
c6ca8cda3b1f:/ # ls /opt/conan/.conan/data/pkgconf/1.7.3/_/_/source
conandata.yml  patches  pkgconf-1.7.3.tar.xz
c6ca8cda3b1f:/ # 
```

</details>

**Comment by dmn-star** [comment]
@SpaceIm maybe you have a quick idea what the problem is?

**Comment by SSE4** [comment]
might be a python issue, similar reports:
https://github.com/conan-io/conan/issues/8503
https://github.com/conan-io/conan-center-index/issues/3384

**Comment by dmn-star** [comment]
The python issue would be really inappropriate now. :-(

**Comment by danimtb** [comment]
I was not able to reproduce this in Windows, python 3.9.4 and Conan 1.35.1. Might be an issue related only to OpenSUSE?

**Comment by SpaceIm** [comment]
Same for me, did you try to clear your cache?

**Comment by dmn-star** [comment]
Thanks for looking in. I will now check the python installation in Docker.

**Comment by agn0stico** [comment]
I'm having issues as well with pkgconf, but my log is a bit different:

```
$ conan install pkgconf/1.7.3@ --build

[...]

pkgconf/1.7.3: Configuring sources in /home/conan/.conan/data/pkgconf/1.7.3/_/_/source
ERROR: Error downloading file https://distfiles.dereferenced.org/pkgconf/pkgconf-1.7.3.tar.xz: 'HTTPSConnectionPool(host='distfiles.dereferenced.org', port=443): Max retries exceeded with url: /pkgconf/pkgconf-1.7.3.tar.xz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))'
Waiting 5 seconds to retry...
ERROR: pkgconf/1.7.3: Error in source() method, line 46
        tools.get(**self.conan_data["sources"][self.version])
        ConanException: Error downloading file https://distfiles.dereferenced.org/pkgconf/pkgconf-1.7.3.tar.xz: 'HTTPSConnectionPool(host='distfiles.dereferenced.org', port=443): Max retries exceeded with url: /pkgconf/pkgconf-1.7.3.tar.xz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))'
```

**Comment by dmn-star** [comment]
Python in docker was built without lzma support. Installing xz-devel and rebuilding python fixed the problem.

@agn0stico I was able to build pkgconf today, possibly a temporary problem and SSL cert have already been updated.
