### ISSUE TITLE
[package] sqlite3/3.35.4: Targets fail to link with -dl (cmake_find_package generator)

### ISSUE THREAD

**Issue by whyman** [conan-io/conan-center-index#5221]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sqlite3/3.35.4**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 10**
  * Conan version: **conan 1.35.1**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile grb-debug:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
compiler.cppstd=17
build_type=Release
[options]
[build_requires]
[env]
CC=gcc-10
CXX=g++-10
```

### Steps to reproduce (Include if Applicable)
Using the cmake_find_package generator, the SQLite3 target does not include the required system libs for linking to work as expected.

### Logs (Executed commands with output) (Include/Attach if Applicable)
Code is simply:

```cmake
target_link_libraries(mylib PUBLIC SQLite::SQLite3)
target_link_libraries(myapp PUBLIC mylib)
```

```
/usr/bin/ld: /home/user/.conan/data/sqlite3/3.35.4/_/_/package/d9f1064aa2f2acf9923d422dfbae3fc448b4d5ab/lib/libsqlite3.a(sqlite3.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
...
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
```
As you can see we need to link `dl` here (which is also encoded in the recipe)

**Comment by uilianries** [comment]
@whyman Could you please provide your entire cmake file? Only with your example we can't reproduce your scenario.

**Comment by SpaceIm** [comment]
Likely an issue with GLIBC version, try to build from source.

**Comment by uilianries** [comment]
True! Thanks @SpaceIm !

**Comment by whyman** [comment]
Thanks for the suggestion @SpaceIm!

I tried it with a locally built version and still no dice, same error.

When I add in an test `target_link_libraries(libgerbera PUBLIC "dl")` it links and runs as expected.

The conanfile is https://github.com/gerbera/gerbera/blob/master/conanfile.py, pretty standard stuff

I added in a couple of `cmake_print_properties` for the properties I would expect to see set
```-- 
 Properties for TARGET SQLite::SQLite3:
   SQLite::SQLite3.INTERFACE_LINK_LIBRARIES = <NOTFOUND>

-- 
 Properties for TARGET SQLite::SQLite3:
   SQLite::SQLite3.INTERFACE_LINK_OPTIONS = <NOTFOUND>
```
But of course, other properties may be set, its hard to dump an entire target in CMake as far as I can tell.

**Comment by SpaceIm** [comment]
Are you sure that your project properly find the file generated by cmake_find_package, and not built-in `FindSQLite3` provided by CMake?

By the way, this branching is not required anymore: https://github.com/gerbera/gerbera/blob/96df78513d8613c53f17b3dc64049637ba16e65d/CMakeLists.txt#L409-L413

**Comment by whyman** [comment]
> Are you sure that your project properly find the file generated by cmake_find_package, and not built-in `FindSQLite3` provided by CMake? It doesn't come for free, you need to prepend the path where this file has been generated in `CMAKE_MODULE_PATH` (usually through cmake command line, to avoid hardcoded values in your CMakeLists.txt).

I will triple check this

> I see also this file in your project: https://github.com/gerbera/gerbera/blob/master/cmake/FindSQLite3.cmake, could it be the one which is being found? It shouldn't, because this file is too fragile (optional system libs like dl are not taken into account).

Amusingly this file is directly from the CMake tree (at the time of CMake 3.14)

> By the way, this branching is not required anymore: https://github.com/gerbera/gerbera/blob/96df78513d8613c53f17b3dc64049637ba16e65d/CMakeLists.txt#L409-L413, imported target of sqlite3 in `cmake_find_package` has been fixed 8 months ago.

Yes, thanks to whoever sorted that out, I have a local branch with that tidying already.

**Comment by SpaceIm** [comment]
I think that the issue is here: https://github.com/gerbera/gerbera/blob/96df78513d8613c53f17b3dc64049637ba16e65d/CMakeLists.txt#L13-L30

`${CMAKE_BINARY_DIR}` is appended after `${CMAKE_SOURCE_DIR}/cmake/modules`, so find_package looks first for Find modules in `${CMAKE_SOURCE_DIR}/cmake/modules`

**Comment by whyman** [comment]
Yeah, I think you're right there.

Ive made a patch to prefix the `${CMAKE_BINARY_DIR}` and works as expected.

Apologies for the noise, and thanks for conan, its a cool project.

I ended up with https://github.com/gerbera/gerbera/pull/1406
