### ISSUE TITLE
[question] how to add a compile option to a recipe?

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#5226]
I have my proprietary recipe and for one of the files, I am getting an error, while compiling with MSVC:

C:\.conan\c577bb\1\source\BodyModel3D\FittingEngine3DImpl.cpp : fatal error C1128: number of sections exceeded objec
t file format limit: **compile with /bigobj** [C:\.conan\c577bb\1\pictofitcore.vcxproj]
cl : command line error D8040: error creating or communicating with child process [C:\.conan\c577bb\1\pictofitcore.v
cxproj]
pictofitcore/v22.12.0-6-g63d13104b@AndreiMalashkin/testing:
pictofitcore/v22.12.0-6-g63d13104b@AndreiMalashkin/testing: ERROR: Package '150d246cde3da31024d9207093959bb8ea74aaa2' build failed
pictofitcore/v22.12.0-6-g63d13104b@AndreiMalashkin/testing: WARN: Build folder C:\.conan\c577bb\1
ERROR: pictofitcore/v22.12.0-6-g63d13104b@AndreiMalashkin/testing: Error in build() method, line 141
        cmake.build()
        ConanException: Error 1 while executing cmake --build C:\.conan\c577bb\1 --config Debug -- /m:12 /verbosity:minimal

solution would be to add /bigobj option for windows. A question is - **how to do this**?

**Comment by SpaceIm** [comment]
@AndreyMlashkin this question is related to conan client, not conan-center-index. You should ask in https://github.com/conan-io/conan/issues.
I can say that this kind of compiler option should be added to underlying build files of your project, not injected through conan.
