### ISSUE TITLE
[question] Are there any cross-platform GUI frameworks here which work out-of-the-box?

### ISSUE THREAD

**Issue by SamuelMarks** [conan-io/conan-center-index#5227]
I've recently been trying to get an open-source cross-platform GUI library—in C or C++—working with an open-source cross-platform C/C++ package manager.

Experience with [`vcpkg`](https://github.com/microsoft/vcpkg):

  - [nanogui](https://github.com/mitsuba-renderer/nanogui) @ https://github.com/microsoft/vcpkg/issues/17052
  - [fltk](https://github.com/fltk/fltk) @ https://github.com/microsoft/vcpkg/issues/17053
  - [libui](https://github.com/andlabs/libui) @ https://github.com/microsoft/vcpkg/issues/17054
  - [nuklear](https://github.com/Immediate-Mode-UI/Nuklear) @ https://github.com/microsoft/vcpkg/issues/17055
  - [tgui](https://github.com/texus/TGUI) @ https://github.com/microsoft/vcpkg/issues/17056
  - [imgui](https://github.com/ocornut/imgui) @ https://github.com/microsoft/vcpkg/issues/17058
  - [glui](https://github.com/libglui/glui) @ https://github.com/microsoft/vcpkg/issues/17059
  - [wxwidgets](https://github.com/wxWidgets/wxWidgets) @ https://github.com/microsoft/vcpkg/issues/17072
  - [allegro5](https://github.com/liballeg/allegro5) @ https://github.com/microsoft/vcpkg/issues/17108
  - [gtk](https://www.gtk.org), [gtkmm](https://www.gtkmm.org) @ https://github.com/microsoft/vcpkg/issues/17216
  - [nana](https://github.com/cnjinhao/nana) @ https://github.com/microsoft/vcpkg/issues/17291
  - [dlib](https://github.com/davisking/dlib) @ ([LAPACK](http://www.netlib.org/lapack/): https://github.com/microsoft/vcpkg/issues/17293, GUI not launching: https://github.com/microsoft/vcpkg/issues/17295)

Experience with [`hunter`](https://github.com/cpp-pm/hunter):

  - [imgui](https://github.com/ocornut/imgui) @ https://github.com/cpp-pm/hunter/issues/376

Experience with [`sw`](https://github.com/SoftwareNetwork/sw):

  - [imgui](https://github.com/ocornut/imgui) @ https://github.com/SoftwareNetwork/sw/issues/64

Experience here with [`conan`](https://github.com/conan-io/conan):

  - [imgui](https://github.com/ocornut/imgui) and [nuklear](https://github.com/Immediate-Mode-UI/Nuklear) (really [allegro5](https://github.com/liballeg/allegro5)) @ https://github.com/conan-io/conan/issues/8763
  - [wxwidgets](https://github.com/wxWidgets/wxWidgets) @ https://github.com/conan-io/conan/issues/8782
  - [libui](https://github.com/andlabs/libui) @ https://github.com/conan-io/conan/issues/8783
  - [tgui](https://github.com/texus/TGUI) @ https://github.com/conan-io/conan/issues/8784
  - [gtk](https://www.gtk.org) @ https://github.com/conan-io/conan/issues/8785

Experience with [`conda`](https://github.com/conda/conda):

  - [fltk](https://github.com/fltk/fltk) @ https://github.com/conda/conda/issues/10601
  - [wxwidgets](https://github.com/wxWidgets/wxWidgets) @ https://github.com/conda/conda/issues/10602

---

EDIT: Created issues for all the GUI frameworks that I tried in `vcpkg` that are available somewhere in `conan`. Still haven't found a single GUI library which works (out-of-the-box).

**Comment by ericLemanissier** [comment]
you may want to add qt to the list

**Comment by SamuelMarks** [comment]
@ericLemanissier I've been avoiding Qt due to licensing issues. I want something usable for open-source, commercial, and noncommercial purposes. Actually on that note I think some others I've been testing are also GPL licensed…

**Comment by jgsogo** [comment]
I'll close this issue... we try to keep track of requested libraries using specific issues (https://github.com/conan-io/conan-center-index/issues/621). On the other hand, this is good feedback for the UI search (https://conan.io/center/) 👍
