### ISSUE TITLE
[question] Why is the compiler setting relevant for "tools" packages like CMake, Ninja under Windows

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan-center-index#5228]
Recently (at least for CMake) the `compiler` setting has been added to the recipe and it is also used in the Ninja recipe. At least under Windows the executables could be statically linked to the runtime libs to reduce the number of required binary packages and make it much more likely that users of Conan-Center can use a binary package right-away.
Even if the runtime would be required, why would it be required to use the same compiler for building CMake as for building the actual project? Is the (still experimental) "Build/Host contexts" feature expected to be used?

**Comment by ericLemanissier** [comment]
I think we more or less agreed to make tools independant on the compiler used : https://github.com/conan-io/conan-center-index/issues/3157#issuecomment-714565227
So it is worth doing pull request to add this to tools recipes:
```
def package_id(self):
    del self.info.settings.compiler
```
cmake and ninja already have this snippet: https://github.com/conan-io/conan-center-index/blob/master/recipes/cmake/3.x.x/conanfile.py#L101-L102 https://github.com/conan-io/conan-center-index/blob/master/recipes/ninja/1.10.x/conanfile.py#L19-L20, so your project should be able to use any cmake/ninja prebuilt binary, even if it comes from a different compiler

**Comment by petermbauer** [comment]
Thanks a lot for the quick clarification, i overlooked that the compiler setting is removed from the packageID.
