### ISSUE TITLE
[question] Create recipe for gist

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan-center-index#5236]
1. Whether it is ok to create recipe for a gist？
2. If it is ok, is there any example?

**Comment by danimtb** [comment]
I believe we have not packaged a gist previously so I am not sure if it could be done. However, it might be of interest. Could you give more details about it?

**Comment by xyz1001** [comment]
My project need [this](https://gist.github.com/panzi/6856583) simple header for endian conversion. It is all right to copy it to my project, but I think it is a better idea to treat it as a header only library. When I try to create recipe for it, I found it is hard to control version. There is no commit id or tag.

**Comment by danimtb** [comment]
I think it could be a useful hedear only package. For versioning, we could stick to this convention here https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases. Then we would have to give it a proper name

**Comment by xyz1001** [comment]
Ok，I will create a pull request for this gist. Thank you for your reply.

**Comment by xyz1001** [comment]
Here is the pull request and there has some discussion.
https://github.com/conan-io/conan-center-index/pull/5240
Could you give some suggestions? @danimtb

**Comment by Croydon** [comment]
Did you ask the author if you would be willing to put it into a repository? Sometimes a simple questions helps 🙂
