### ISSUE TITLE
[package] backward-cpp/1.5: some options are not visible, while installing

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#5241]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **backward-cpp/1.5**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 19**
  * Conan version: ** 1.35.1**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
 conan inspect backward-cpp/1.5@
conan install backward-cpp/1.5@ -o backward-cpp:stack_details="backtrace_symbol"

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
> conan inspect backward-cpp/1.5@
name: backward-cpp
version: 1.5
url: https://github.com/conan-io/conan-center-index
homepage: https://github.com/bombela/backward-cpp
license: MIT
author: None
description: A beautiful stack trace pretty printer for C++
topics: ('conan', 'backward-cpp', 'stack-trace')
generators: cmake
exports: None
exports_sources: ['CMakeLists.txt', 'patches/backward-cpp-*.patch']
short_paths: False
apply_env: True
build_policy: None
revision_mode: hash
settings: ('os', 'arch', 'compiler', 'build_type')
options:
    fPIC: [True, False]
    shared: [True, False]
    stack_details: ['dw', 'bfd', 'dwarf', 'backtrace_symbol']
    stack_walking: ['unwind', 'backtrace']
default_options:
    fPIC: True
    shared: False
    stack_details: dwarf
    stack_walking: unwind

>  conan install backward-cpp/1.5@ -o backward-cpp:stack_details="backtrace_symbol"
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
backward-cpp:stack_details=backtrace_symbol
[build_requires]
[env]

ERROR: backward-cpp/1.5: option 'stack_details' doesn't exist
Possible options are ['stack_walking', 'shared']
```

</details>

Why I can't override stack_details option?

**Comment by SpaceIm** [comment]
Because this option is deleted if Windows (not relevant option I guess): https://github.com/conan-io/conan-center-index/blob/7f42e81bd07f4cc1cc2b3558cecd7c97ffb2b33a/recipes/backward-cpp/all/conanfile.py#L43-L46
I would say it's a limitation of conan about how we can design options of a recipe, and how available options are displayed with conan inspect for a given settings.
