### ISSUE TITLE
[boost] boost/1.71.0: Binaries for GCC 9 are not available

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-center-index#525]
Binaries for GCC 9 are not available.

Found this issue building this recipe: https://github.com/conan-io/conan-center-index/pull/453#issuecomment-567996328

**Comment by danimtb** [comment]
Launching a manual task to generate those packages

**Comment by danimtb** [comment]
Seems boost 1.70.0 is also affected

**Comment by danimtb** [comment]
Missing packages were generated for both versions!

**Comment by helmesjo** [comment]
Hmm I'm not seeing them for GCC-9 (Linux x86_64): `boost/1.71.0@conan/stable`

**Comment by danimtb** [comment]
yes, you should use `boost/1.71.0`. Packages in this index are uploaded without user and channel now

**Comment by helmesjo** [comment]
Alright! I've experienced some issues using that though (different dependencies using different syntax = unsatisfied dependencies etc.), but I'll give it a try. Thanks!

**Comment by jgsogo** [comment]
Wow! @helmesjo , can you open an issue in the Conan repo with this issue about incompatible requirements? Here it is something we should be able to manage (maybe trickier than expected, but we need to have a look at it).

Thanks!

**Comment by helmesjo** [comment]
Did some changes to conan-thrift so the exact case is not present atm, but if I get stuck again I sure will! :)
Thanks!

**Comment by jgsogo** [comment]
I'm trying to reproduce your error with the current version of Conan, but I cannot reach the "Incompatible requirements" condition. If you come across it again, please share/draw the graph of dependencies with us. Thanks!

**Comment by helmesjo** [comment]
Absolutely!

**Comment by helmesjo** [comment]
> Did some changes to conan-thrift so the exact case is not present atm, but if I get stuck again I sure will! :)
> 
> But looking at above it seemed to be:
> 
> 1. `A` dependes on `boost/1.71.0` & `B`
> 2. `B` depends on `boost/1.71.0@conan/stable`
> 3. :(
> 
> Thanks!

@jgsogo Actually, it was the other way around:
1. `A` dependes on `boost/1.71.0@conan/stable` & `B`
2. `B` depends on `boost/1.71.0`
3. :(

Had another project that depends on `boost/1.71.0@conan/stable` and  `thrift/0.13.0@helmesjo/stable`, and it just failed like above.

**Comment by Croydon** [comment]
@helmesjo I recommend you to update all recipes to CCI variants if possible. In this case you should be able to migrate boost and zlib to CCI variants

Beyond that, is there any specific reason why you continue to use your own thrift recipe instead of the Bincrafters one (which is based on your recipe)? 🤔
https://github.com/bincrafters/conan-thrift

**Comment by helmesjo** [comment]
@Croydon
It's lagging behind one version.. 😇 But nah, just hadn't crossed my mind to change! Could you up it to 0.13? 🙂

**Comment by Croydon** [comment]
I have added a 0.13.0 release, CI might take a few more minutes

If you need a newer version of a Bincrafters package you can request it here: https://github.com/bincrafters/community/issues/new/choose
