### ISSUE TITLE
[request] paho-mqtt-c/all to support PAHO_HIGH_PERFORMANCE

### ISSUE THREAD

**Issue by voidbar** [conan-io/conan-center-index#5268]
### Package Details
  * Package Name/Version: **paho-mqtt-c**
  * https://github.com/eclipse/paho.mqtt.c

According to the the library's github documentation [here](https://github.com/eclipse/paho.mqtt.c#build-instructions-for-gnu-make), there is a compilation flag which when turned on enhances the library's performance. 
`-DPAHO_HIGH_PERFORMANCE=ON` should be supported as a recipe option and disabled by default to conform to the existing behavior.

**Comment by prince-chrismc** [comment]
closed with https://github.com/conan-io/conan-center-index/pull/5354
