### ISSUE TITLE
[package] openssl/1.1.1k: Cannot apply install_name_tool on libssl.dylib

### ISSUE THREAD

**Issue by rockdreamer** [conan-io/conan-center-index#5308]
### Why this is an issue
At $WORK, we apply a sequence of install_name_tool commands on all libraries to ensure that our packages load libraries consistently. This is hampered by openssl being built without a link option.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openssl/1.1.1k**
  * Operating System+version: **Macos 10.15**
  * Compiler+version: **apple-clang 11**
  * Conan version: **conan 1.35.1**
  * Python version: **Python 3.9.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
openssl:shared=True
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)

- Build openssl with openssl:shared=True on macos
- copy libssl1.1.dylib 
- run `install_name_tool -add_rpath fjweiopfgjqwefwefiojefreogirpgoqijrepgjioqrepjiogqrepjiogreqpjiogqrepjioqgrejpioqgrepjiogrqepjiogrqepijoqgrepjiogrqeijpogrqejiopgreqjgqojigoreqjiopgqrejipogqrejipogrepgorijeqpgjqiorepijogrqepjiogqrepjiogqrepjiogreqpjiogreqpjiogreqpjiogreqijpogreqijpogreqijopgreqpjioeqgrjierpo libssl.1.1.dylib`

The result contains the solution to the issue at hand:

```
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /Users/cbantaloukas/Downloads/lib_libssl.1.1.dylib (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```

**Comment by SpaceIm** [comment]
Is it really a conan-center issue?

It works fine on my mac with latest openssl revision. Do you confirm?

**Comment by SSE4** [comment]
> Is it really a conan-center issue?
> 
> It works fine on my mac with latest openssl recipe revision. Do you confirm?

I've just checked on my machine, the same command (`install_name_tool ...`) runs successfully against ` libssl1.1.dylib` built from `openssl/1.1.1k` (`openssl:shared=True`)

**Comment by rockdreamer** [comment]
> Is it really a conan-center issue?
> 
> It works fine on my mac with latest openssl recipe revision. Do you confirm?

I pushed a PR with a failing test on purpose to check this. The check failed on at least one (older) version of the recipe. Pushing a slight change to the ldflags

**Comment by rockdreamer** [comment]
I'm solving this with a locally modified copy of the recipe.
