### ISSUE TITLE
[request] <pkgconf>/<1.7.4>

### ISSUE THREAD

**Issue by agn0stico** [conan-io/conan-center-index#5311]
The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

The pkgconf recipe retrieves the sources from [https://distfiles.dereferenced.org/pkgconf](https://distfiles.dereferenced.org/pkgconf) but a git repo is available: https://github.com/pkgconf/pkgconf/tree/pkgconf-1.7.4 

The distfiles website is reporting an expired SSL cerrtificate if I try to install pkgconf/1.7.3

**Comment by Croydon** [comment]
https://github.com/pkgconf/pkgconf/issues/221
