### ISSUE TITLE
[package] pybind11/2.6.2: Unintended CMake target dependencies

### ISSUE THREAD

**Issue by y4n9squared** [conan-io/conan-center-index#5334]
When using the `cmake_find_package` generator, the auto-generated `Findpybind11.cmake` simultaneously makes the component targets depend on the global target and the global target depend on all component targets:

```
# For each component target:
set(pybind11_headers DEPENDENCIES pybind11::pybind11)

# Later in the file:
set_property(TARGET pybind11::pybind11 APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${pybind11_COMPONENTS})
```

This makes the component targets moot as using any one of them in `target_link_libraries` causes all components to be used.

As a result, all non-Debug builds append extraneous compiler and link flags from `pybind11::lto` and `pybind11::opt-size`. For example, on Linux GCC, the flags `-Os` is appended *regardless of what (non-Debug) build type is selected*. This is quite concerning as compiles will succeed but with the wrong optimization level. `-flto` is also appended regardless of CMake's IPO settings.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **pybind11/2.6.2**
  * Operating System+version: **Linux CentOS 7**
  * Compiler+version: **GCC 9.2**
  * Conan version: **conan 1.35.2**
  * Python version: **Python 3.8.6**

### Steps to reproduce (Include if Applicable)

Can be reproduced with a minimal project setup:

**conanfile.txt**

```
[requires]
pybind11/2.6.2

[generators]
cmake_find_package
```

**CMakeLists.txt**

```
find_package(pybind11 REQUIRED)
add_library(foo SHARED foo.cpp)
target_link_libraries(foo PUBLIC pybind11::headers)
```

when built in a Release configuration, will emit the following compiler/link flags:

```
-O2 -DNDEBUG -flto -fno-fat-lto-objects -Os
```

**Comment by vectorsli** [comment]
@y4n9squared Is that the same issue as #6605?

If that's the case, I'd suggest closing this issue in favor of #6605 since the other issue has more discussion.
