### ISSUE TITLE
[center.conan.io] Update conan-center-index wiki

### ISSUE THREAD

**Issue by Dattax** [conan-io/conan-center-index#534]
Hi, we received feedback that the process to add packages may need some clarity. I've proposed updates to the wiki page explaining how to add packages. Here is the original page: https://github.com/conan-io/conan-center-index/wiki

Here is my proposed content: https://github.com/Dattax/conan-center-index/blob/master/Home.md

I've also included the page as an attachment here (Home.txt - just change it to Home.md).

**Comment by uilianries** [comment]
Hi @Dattax! Thank you very much for your content!

**Comment by uilianries** [comment]
Hi again! Your changes have been committed in the Wiki: https://github.com/conan-io/conan-center-index/wiki/Home/3dd17972924ac99aa2ba7664f95360b77bc00681

Regards!
