### ISSUE TITLE
Unable to find binaries for sqlite3 Linux Debug configuration

### ISSUE THREAD

**Issue by ceng1996** [conan-io/conan-center-index#5351]
My team is pulling Conan packages from conan center, and we noticed a recent problem when pulling a particular sqlite3 package configuration.  It seems that a recent [pull request](https://github.com/conan-io/conan-center-index/commit/ef9b1198c90a40a6caec1b53652f1271b1a3afd9) for the sqlite3 package was made, which generated a rebuild of the package.  However the following package configuration is missing its binaries for the latest revision.  Would it be possible to resolve this issue and generate the binaries for this package configuration?

[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug/Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=4.9
os=Linux
os_build=Linux

_/sqlite3/3.34.1/_/2363affcc06f5f9c2904b32855994dee/66199b2d5692340efb56acd74f4ce33b9359da0d/a686860dce827221bd88eec017c92293

**Comment by uilianries** [comment]
Hello @ceng1996 

We updated sqlite3 options, which affected its package ID. But you still can obtain a specific package by its revision.

Please read https://docs.conan.io/en/latest/versioning/revisions.html#package-revisions.

Anyway, I don't recommend you keeping old revisions, new package revisions and versions are better, more secure and stable.

Regards.

**Comment by ceng1996** [comment]
We would like to use the latest revision, but when attempting to pull the latest revision of binaries for the configuration listed above we get an error stating that the binaries couldn't be found.  We can find the binaries for the Linux/Release configuration.  We cannot find the binaries for the Linux/Debug configuration.  I was thinking that something happened in the build pipeline perhaps?

**Comment by uilianries** [comment]
You have a old recipe revision cached and are trying to download the correspondent binaries. Let's remove your cache and download a fresh copy:

    conan remove -f sqlite3/3.34.1@
    conan install sqlige3/3.34.1@ -r conan-center

BTW The latest SQLite3 version available is 3.35.3: https://conan.io/center/sqlite3

I can sure there are package for GCC9, I tested locally.

**Comment by ceng1996** [comment]
We are actually using gcc4.9.2.  I know....it is an old compiler.  :)  We are in the process of upgrading to gcc8. 
 However, it appears the binaries are there now for gcc4.9.2, so something must have happened recently.  Thank you so much for your help!  I really appreciate your feedback!
