### ISSUE TITLE
[package] boost/1.73: Shared Library Builds broken if you build without fiber

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan-center-index#5352]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: boost/1.73
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version: conan 1.35.1
  * Python version: via chocolatey

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
install boost/1.73 with shared=true and boost:without_fiber true
numa is disabled in visual studio, but numa is deleted when without_fiber is true, so you get:

ERROR: boost/1.73.0: Error in validate() method, line 337
if self.options.numa:
ConanException: option 'numa' doesn't exist

**Comment by madebr** [comment]
Indeed, it should be `self.options.get_safe("numa")`.

**Comment by frkami123** [comment]
i got the same problem with boost/1.76.

**Comment by madebr** [comment]
I've just opened #5420.
Please test whether this fixed your problem.
