### ISSUE TITLE
[question] how to build boost on Ubuntu20 for Ubuntu18 

### ISSUE THREAD

**Issue by JochenWilhelmyTomTom** [conan-io/conan-center-index#5370]
Hi!

I'd like to build boost for Ubuntu18 on Ubuntu20. For this I have installed gcc-7 next to the default gcc-9 on Ubuntu20. The idea is that when I compile with gcc-7 on Ubuntu20 it woll work on Ubuntu18 where gcc-7 is the default compiler.

I use the recipe from conan-center-index and build it with conan-package-tools where I add a configuration with env_vars pointing to gcc-7:

            builder.add(
                settings = {
                    "compiler": "gcc",
                    "compiler.version": "7",
                    "build_type": "Debug"},
                env_vars = {
                    "CC": "gcc-7",
                    "CXX": "g++-7",
                    "AR": "gcc-ar-7",
                    "RANLIB": "gcc-ranlib-7",
                    "NM": "gcc-nm-7"},
                options = {})

When using the built boost package on Ubuntu18, I get undefined references to 'statx':
.conan/data/boost/1.76.0/_/_/package/5e22717405c7b0f5a4ba92362e00008e48bafeb8/lib/libboost_filesystem.a(operations.o): In function `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)':
/__w/1/conan-cache/.conan/data/boost/1.76.0/_/_/source/source_subfolder/libs/filesystem/src/operations.cpp:1211: undefined reference to `statx'

Does anybody have an idea how this is done?
Thanks

**Comment by madebr** [comment]
The `statx` call is added to glibc in 2.28.
Ubuntu 18.04 shipped with glibc 2.27: https://launchpad.net/ubuntu/bionic/+source/glibc
Ubuntu 20.04 shipped with glibc 2.30: https://launchpad.net/ubuntu/focal/+source/glibc

The easiest way to build 18.04 compatible libraries, is to use docker images.
See https://github.com/conan-io/conan-package-tools#using-docker

Alternatively, you can setup your own toolchain (by compiling glibc2.27 + gcc-7 yourself)

**Comment by jgsogo** [comment]
I would recommend the docker approach... or just use precompiled binaries from ConanCenter 😄 . Here we try to use the lowest version of Ubuntu for each compiler in order to link with the lowest glibc and maximize compatibility... and hopefully soon we will start to use the same base image for all the compilers.

I'm closing this issue, it's been answered, and there is nothing we can do on our side.

Thanks!
