### ISSUE TITLE
[package] qt/6.0.3: Failed requirement 'vulkan-loader/1.2.172.0'

### ISSUE THREAD

**Issue by TheClonerx** [conan-io/conan-center-index#5371]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.0.3**
  * Operating System+version: **Arch Linux 2021/04/30**
  * Compiler+version: **GCC 10**
  * Conan version: **conan 1.35.2**
  * Python version: **Python 3.9.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```bash
cat << EOF > conanfile.txt
[requires]
qt/6.0.3
[options]
qt:with_vulkan=True
EOF
mkdir build
cd build
conan install ..
```
### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
vulkan-loader/1.2.172.0: Not found in local cache, looking in remotes...
vulkan-loader/1.2.172.0: Trying with 'conan-center'...
ERROR: Failed requirement 'vulkan-loader/1.2.172.0' from 'qt/6.0.3'
ERROR: Unable to find 'vulkan-loader/1.2.172.0' in remotes
```

</details>

**Comment by ericLemanissier** [comment]
@SpaceIm @intelligide do you think it's best to require `vulkan-loader/1.2.172` (the most recent) or `vulkan-loader/v1.2.170.0' (official realease) ?

**Comment by SpaceIm** [comment]
It's best to not require vulkan-loader at all, it's not required ;)

**Comment by ericLemanissier** [comment]
I just tried:

- without vulkan-loader and vulkan-headers, it fails with `-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)`
- with vulkan-headers it fails with `-- Could NOT find Vulkan (missing: Vulkan_LIBRARY)`
- with vulkan-loader it passes

I did not find how qt actually detects vulkan, so there may be a way to make it work with vulkan-headers

**Comment by SpaceIm** [comment]
Qt uses FindVulkan, and as I said, we mimic this file in vulkan-loader only due to conan limitations. So you need to slightly changes upstream CMake files where find_package(Vulkan) is called.
