### ISSUE TITLE
[package] Boost/1.69: Can't build from source, URL pointing to old/removed boost.org server

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan-center-index#5397]
After Bintray sunset, the Boost recipe is pointing to an old, non-existing place.
Recipe should be updated to point to boost.org new download site (boostorg.jfrog.io)

**Comment by DavidAntliff** [comment]
https://github.com/conan-io/conan/issues/8908

**Comment by Croydon** [comment]
The boost recipe uses three mirrors, one of them being Bintray. Bintray should get removed now, but the source download should not fail even with it

https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conandata.yml#L4

**Comment by DavidAntliff** [comment]
>  the source download should not fail even with it

Right - but it does fail. Perhaps 403 is treated differently than a 404?

**Comment by Croydon** [comment]
We are talking about this now in two different issues, so please see the answers here: https://github.com/conan-io/conan/issues/8908

https://github.com/conan-io/conan-center-index/pull/5401 will remove the Bintray mirror from the still maintained recipe (`boost/1.69.0` without `@conan/stable`)
