### ISSUE TITLE
[request] thrift/0.12.0

### ISSUE THREAD

**Issue by emac700** [conan-io/conan-center-index#5406]
### Package Details
  * Package Name/Version: **thrift/0.12.0**
  * Changelog: **https://github.com/apache/thrift/blob/master/CHANGES.md#0120**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by czoido** [comment]
Thanks for reporting, closing as thrift/0.13.0 o 0.18.1 are available in Conan Center
