### ISSUE TITLE
[package] zeromq/4.3.4: Visual Studio compiler.runtime not respected

### ISSUE THREAD

**Issue by jakecobb** [conan-io/conan-center-index#5443]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zeromq/4.3.4**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019**
  * Conan version: **conan 1.36.0**
  * Python version: **Python 3.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)

ZeroMQ on Windows seems to be built against the static C runtime when the setting is for dynamic C runtime.  For 4.3.4, package `4a68df1aecde0f930b6e787577e197482049634b`, in `conaninfo.txt`:

```
[settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=16
    os=Windows
```

So it should be using the `MD` (multi-threaded DLL) runtime.  However, the only lib it has is `lib/libzmq-v142-mt-4_3_4.lib`, which by the naming convention you can see is the `MT` (multi-threaded static) runtime.

Same issue in `c1caed9fb930b0b2a5c0bdf32a7d962a1ad2c838` which has the `compiler.runtime=MDd` (multi-threaded DLL debug), but the `mt-gd` lib file.  So it has switched to debug (`gd`) but still the static runtime.

**Comment by SpaceIm** [comment]
If you look at upstream build files, those lib names are hardcoded. Besides of the name, do you see that it really builds against static runtime or not?

**Comment by jakecobb** [comment]
Good point, checking the DLL with Dependency Walker it does link the dynamic runtime.  So the upstream is just misleadingly named.  It also links the v140 runtime not v142.  Sorry for the false positive.
