### ISSUE TITLE
[request] autoconf/2.71

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#5451]
### Package Details
  * Package Name/Version: **autoconf/2.71**
  * Changelog: **https://lists.gnu.org/archive/html/autoconf/2021-01/msg00126.html**

contains an essential fix for e2k (Elbrus): https://lists.gnu.org/archive/html/config-patches/2015-03/msg00000.html

/cc @madebr @r-a-sattarov

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by madebr** [comment]
Thanks for the heads-up.
Somehow we missed 2.70 last december

**Comment by madebr** [comment]
Is Elbrus becoming common in Russia?
First time I read about this architecture.

**Comment by SSE4** [comment]
> Is Elbrus becoming common in Russia?
> First time I read about this architecture.

not very common, mostly used by government facilities (military, tax, customs, police, etc.)
