### ISSUE TITLE
[service] Missing package: ZeroMQ/4.3.4

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#5470]
Trying to build Behavior.Tree here: https://github.com/conan-io/conan-center-index/pull/5378

However, it fails because [zeromq](https://conan.io/center/zeromq) is not available under specific profiles.

Missing profiles:
- arch=x86_64; build_type=Release; compiler=gcc; compiler.libcxx=libstdc++; compiler.version=10; os=Linux
- arch=x86_64; build_type=Release; compiler=apple-clang; compiler.libcxx=libc++; compiler.version=12.0; os=Macos
- arch=x86_64; build_type=Debug; compiler=apple-clang; compiler.libcxx=libc++; compiler.version=12.0; os=Macos

All them are default, I mean, static library, no extra options.

**Comment by jgsogo** [comment]
Some configurations were missing. I've just generated them: https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/TapaholesList/85/zeromq/4.3.4//summary.json

Ping me next time, please.
