### ISSUE TITLE
[package] libtool/2.4.6: Missing prebuilt package for msvc

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#5476]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libtool/2.4.6**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019**
  * Conan version: **conan 1.36.0**
  * Python version: **Python 3.9.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
CC=cl.exe
CXX=cl.exe
```

### Steps to reproduce (Include if Applicable)

`conan install libtool/2.4.6@`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CC=cl.exe
CXX=cl.exe
Installing package: libtool/2.4.6
Requirements
    autoconf/2.69 from 'conan-center' - Cache
    automake/1.16.3 from 'conan-center' - Cache
    libtool/2.4.6 from local cache - Cache
    m4/1.4.18 from 'conan-center' - Cache
Packages
    autoconf/2.69:3475bd55b91ae904ac96fde0f106a136ab951a5e - Download
    automake/1.16.3:3e48e69237f7f2196164383ef9dedf0f93cbf249 - Download
    libtool/2.4.6:82ad5af1557e85f11dfc0f68ec2820c275dfe6d4 - Missing
    m4/1.4.18:0a420ff5c47119e668867cdb51baff0eca1fdb68 - Download

Installing (downloading, building) binaries...
ERROR: Missing binary: libtool/2.4.6:82ad5af1557e85f11dfc0f68ec2820c275dfe6d4

libtool/2.4.6: WARN: Can't find a 'libtool/2.4.6' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=16, os=Windows
- Options: shared=False
- Dependencies: automake/1.16.3
- Requirements: automake/1.Y.Z
- Package ID: 82ad5af1557e85f11dfc0f68ec2820c275dfe6d4

ERROR: Missing prebuilt package for 'libtool/2.4.6'
Try to build from sources with '--build=libtool'
Use 'conan search <reference> --table table.html'
Or read 'http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

</details>

Surprisingly this package id (82ad5af1557e85f11dfc0f68ec2820c275dfe6d4) is listed on Web UI: https://conan.io/center/libtool?version=2.4.6&revision=9d5d6ca362073ac1ecb3d7d02f181ae8&tab=configuration&os=Windows

**Comment by perseoGI** [comment]
Hi there,
Of course you know that as you have been one of the most active contributors, but if for some reason there is no prebuilt binary, passing `--build=missing` option will compile locally.

I'm closing this issue as we are no longer compiling on Visual Studio v16.
Happy coding 🐸
