### ISSUE TITLE
[request] entt/3.2.2

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan-center-index#550]
### Package Details
  * Package Name/Version: **entt/3.2.2**
  * Website: **https://github.com/skypjack/entt**
  * Source code: **https://github.com/skypjack/entt**

### Description Of The Library / Tool
Gaming meets modern C++ - a fast and reliable entity-component system (ECS) and much more

CC @skypjack

**Comment by Minimonium** [comment]
@skypjack
Just a heads up that the Conan Center Index supersedes the previous contribution model to the default Conan registry. 
In the CCI we create separated from the main repository recipes. There are also more rules, like the ban on default build system files, like CMake config files. The idea is to fully generate them from Conan. So if you or your users have any problems with this new recipe please reach out. 🙂

**Comment by skypjack** [comment]
@Minimonium 

Thank you very much for the heads up, really appreciated!
Is there any documentation for this new model? I missed it to be honest, my fault.
I understand correctly and can I remove support for Conan from the `EnTT` repository or is that still necessary?

**Comment by Minimonium** [comment]
If you don't need Conan as a vehicle to pull your dependencies then no you don't.

If you make a new release it's enough to make an issue here picking the `Package: New Version` issue template and we'll pick it up (or you or your users may make a PR request since we want to trivialize the process as much as possible into adding a pair of a version and a source archive hash 🙂 ). 

There is some information in the wiki: https://github.com/conan-io/conan-center-index/wiki

**Comment by skypjack** [comment]
May I give you a feedback to improve the process?
Until now, when I pushed a tag, the CI was in charge to create a new package on my conan account.
It would be great if you provided an _official_ GH action or something similar to automate the process, since _just open a PR_ sounds a bit error-prone (I mean, I'm pretty sure I'll forget it sooner or later).

**Comment by Minimonium** [comment]
You're absolutely right! We're looking into what can be done with that. I just outlined the current status.
Feedback is much appreciated. 🙂

**Comment by skypjack** [comment]
I'd be glad to test it if you'll ever provide users with an official GH action too. Count me in. :wink:

**Comment by skypjack** [comment]
@Minimonium 

[Here](https://github.com/skypjack/entt/issues/380#issuecomment-569468194) is another feedback that can help you to improve the whole thing.
Is there an _easy way_ to do what he mentions with the new model?

**Comment by danimtb** [comment]
I think using the recipe directly and a `conan source` command before creating the workspace could work (haven't tried it). There are still things to consider and solve as discussed in #22 but if you are afraid of removing the recipe from the library repo, you can keep it and just stop generating the packages in the CI. That will allow people to maintain the local workflow but use the new packages generated by the CI in this repo.
