### ISSUE TITLE
[request] PcapPlusPlus/18.08

### ISSUE THREAD

**Issue by sdmg15** [conan-io/conan-center-index#5501]
### Package Details
  * Package Name/Version: **PcapPlusPlus/18.08**
  * Website: ** https://pcapplusplus.github.io/ **
  * Source code: **https://github.com/seladb/PcapPlusPlus**

### Description Of The Library / Tool
PcapPlusPlus is a multiplatform C++ library for capturing, parsing and crafting of network packets. It is designed to be efficient, powerful and easy to use.

**Comment by Renari** [comment]
It looks line bincrafters has version 20.08
https://bincrafters.jfrog.io/ui/repos/tree/General/conan/bincrafters/pcapplusplus

**Comment by seladb** [comment]
PcapPlusPlus v21.05 was recently added to ConanCenter: https://conan.io/center/pcapplusplus

**Comment by sdmg15** [comment]
Yes nice, but there seems to be no configuration for Windows there. I wonder if even like that we can close this issue ?

**Comment by seladb** [comment]
Yes, in order to add Windows we need WinPcap to be added first to ConanCenter. There is an PR #6348 for that. Once it is merged we can add Windows to PcapPlusPlus
