### ISSUE TITLE
[package] qt/6.0.4: openssl version conflict

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/conan-center-index#5523]
I'm unable to install this packages, because it seems to include a version conflict:

```
'cmake/3.20.0' requires 'openssl/1.1.1j' while 'qt/6.0.4' requires 'openssl/1.1.1k'.
```

I don't know where the `cmake/3.20.0` requirement comes from.  It may be a nested requirement of `qt/6.0.4` itself?

Adding `openssl/1.1.1j` or `openssl/1.1.1k` to a `conanfile/txt` together with `qt/6.0.4` results in the same errors.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.0.4**
  * Operating System+version: **Linux Ubuntu 21.04**
  * Compiler+version: **GCC 11.1**
  * Conan version: **conan 1.34.0**
  * Python version: **Python 3.9.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

1. Run `conan install -b missing qt/6.0.4`

**Comment by SpaceIm** [comment]
2 solutions:

- update to latest cmake recipe revision (openssl/1.1.1k in this one).
- call conan install with 2 profiles, even if it's the same profile for both. Indeed, "1 profile" is fragile when a recipe is both in requirements and build requirements.

**Comment by ericLemanissier** [comment]
This conflict should already be solved.  Please retry with `-u` argument to update recipes to the last revision

**Comment by wouterbeek** [comment]
Thanks for fixing this!
