### ISSUE TITLE
[question] Boost: default i18n_backend on Windows

### ISSUE THREAD

**Issue by lieser** [conan-io/conan-center-index#5528]
I noticed that the current boost recipe needs `libiconv` by default.

From my understanding of https://www.boost.org/doc/libs/1_76_0/libs/locale/doc/html/building_boost_locale.html#bb_build_opts, Boost.Locale by default does not use `libiconv` under Windows and Solaris.
Under Windows, it seems to instead use `winapi` as a backend.

I'm wondering if it would not be better to disable the `libiconv` backend under Windows by default (i.e. set the `i18n_backend` option in the Conan recipe to `None`), to reduce the number ob needed dependencies.
Or was the decision for the `i18n_backend` under Windows intentionally, to e.g. not have different default Conan options under different operating systems?

**Comment by SSE4** [comment]
yes, this could be a useful addition to support winapi backend in our recipe to avoid redundant dependency on libiconv for Windows users. feel free to open PR adding new backend.
