### ISSUE TITLE
[package] eastl/3.15.00: compiler.version check fails on msvc

### ISSUE THREAD

**Issue by klaslinde** [conan-io/conan-center-index#553]
https://github.com/conan-io/conan-center-index/blob/a050ade5a1c8f50dbb08a65327dd3be20ad9a98d/recipes/eastl/all/conanfile.py#L39
conanfile.py:39,64's looking suspicious, shouldn't it be checking against 14? 
Better yet, isn't there a standardized way of performing this check?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **eastl/3.15.00**
  * Operating System+version: **Microsoft Windows 10**
  * Compiler+version: **MSVC 16.4.2**

### Steps to reproduce (Include if Applicable)
Issue should manifest on any visual studio, force a build of eastl from sources:
1. create conanfile refering to eastl,
2. conan install . --build eastl

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
$ conan install conan/ --build eastl
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MT
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

eastl/3.15.00: Settings c++ standard to 14
ERROR: eastl/3.15.00: Invalid configuration: Compiler is too old for c++ 14

```
</details>

**Comment by Minimonium** [comment]
We're looking into a standardized tool: https://github.com/conan-io/conan/issues/6282

**Comment by Minimonium** [comment]
And the version seems incorrect to me, you're right.
