### ISSUE TITLE
[question] usage of qt package with CMake

### ISSUE THREAD

**Issue by yuriy-mochurad** [conan-io/conan-center-index#5548]
I can not make qt/6.0.4 working in CMake project. In my cmake I configure conan with:
```
conan_cmake_run(CONANFILE conanfile.py
               BASIC_SETUP
               NO_OUTPUT_DIRS
               CMAKE_TARGETS
               KEEP_RPATHS
               BUILD missing
               BUILD_TYPE ${CMAKE_BUILD_TYPE}
               PROFILE ${PROFILE}
               PROFILE_AUTO build_type compiler.version)
```

My conan profile is:

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os.version=10.15
os_build=Macos
[options]
[build_requires]
[env]
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

I also enabled `"cmake_find_package", "cmake_find_package_multi"` generators in my conanfile.

When I try to build project with cmake I get:
```
CMake Error at CMakeLists.txt:84 (find_package):
  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
```

In Cmake I am using `find_package`:
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
find_package(Qt6 CONFIG REQUIRED)
```

Note: I was using `qt/5.14.1@bincrafters/stable` in the same project setup and `find_project` was able to find qt without issues. I have read through all similar posts, but did not find solution to the issue I am facing. I would appreciate any ideas how to fix it

**Comment by ericLemanissier** [comment]
What happens if you add `GENERATORS cmake_find_package_multi` to your `conan_cmake_run` invocation ?

**Comment by yuriy-mochurad** [comment]
@ericLemanissier I get same result

**Comment by ericLemanissier** [comment]
is the `Qt6Config.cmake` generated somewhere ? (along with all *Config.cmake files)
Can you please send a full minimal reproducible example ?

**Comment by yuriy-mochurad** [comment]
@ericLemanissier Yes, `Qt6Config.cmake` gets created.
The minimal repro repo can be found here: https://github.com/slash777/conan_qt6
Let me know if that helps.
Thank you

**Comment by ericLemanissier** [comment]
can you try to add `cmake_paths` to the generators, and add `include(${CMAKE_BINARY_DIR}/conan_paths.cmake)` just before `find_package(Qt6 REQUIRED CONFIG)` ? Alternatively you can add the `build` folder (where cmake module files are generated) to `CMAKE_PREFIX_PATH` env var before invoking cmake.

**Comment by yuriy-mochurad** [comment]
@ericLemanissier adding `cmake_paths` and `include(${CMAKE_BINARY_DIR}/conan_paths.cmake)` indeed helped to find qt6 package. Thank you for your support.
But I haven't seen this approach in test_package. Is there any fix required on qt6 conan package side?

**Comment by ericLemanissier** [comment]
I'm sorry, nothing can be done in the qt recipe to simplify this, this has to be done no matter which package you require. 
This is documented in https://docs.conan.io/en/latest/reference/generators/cmake_find_package_multi.html : `You also need to adjust CMAKE_PREFIX_PATH and CMAKE_MODULE_PATH so CMake can locate all the <PKG-NAME>Config.cmake/<PKG-NAME>-config.cmake files: The CMAKE_PREFIX_PATH is used by the find_package and the CMAKE_MODULE_PATH is used by the find_dependency calls that locates the transitive dependencies.`)

**Comment by jgsogo** [comment]
Thanks for taking and answering this question.

@yuriy-mochurad , the test_package functionality is using the CMake build-helper, which is adding some variables to the command line when running CMake.
