### ISSUE TITLE
[package] pdal/2.2.0: Include pdal/private/MathUtils.h in the build

### ISSUE THREAD

**Issue by lakinwecker** [conan-io/conan-center-index#5560]
### Package and Environment Details 
  * Package Name/Version: **pdal/2.2.0**
  * Operating System+version: **Arch Linux** / **Windows 10**
  * Compiler+version: **GCC 11.1.0**
  * Docker image: **conanio/gcc8**
  * Conan version: **1.36.0**
  * Python version: **Python 3.9.2**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
If I compile my application (which depends on pdal at this version) in Arch linux, with Eigen installed via the system packages, the build seems to pick up and let me use the eigen related facilities from `pdal/private/MathUtils.hpp` and `pdal/private/MathUtils.cpp`.  In windows 10 (where I don't have the global eigen installed, it doesn't pick it up. My code compiles fine, but fails to link with an undefined symbol related to the specific function I'm using from that file.

### My CMakeLists.txt
I'm using CMakeLists.txt in both operating systems. And the file includes:
```
include_directories(SYSTEM ${CONAN_INCLUDE_DIRS_PDAL})
link_directories(${CONAN_LIB_DIRS_PDAL})
set(LIBRARIES ${LIBRARIES} CONAN_PKG::pdal)
target_link_libraries(app ${LIBRARIES})
```

### Proposed solution 
I've been recently accepted into the early access program, and I intend to submit a patch which lets PDAL depend on eigen (maybe optionally?) and when it does, it will ensure that it compiles against the conan provided eigen and that these facilities are available.  Thoughts?

**Comment by SpaceIm** [comment]
PDAL always depends on Eigen. Don't you try to use private symbols, which are not properly hidden on Unix platforms, but obviously fail with Visual Studio?

**Comment by lakinwecker** [comment]
While I noticed that the file was marked as "private", the documentation on that method seems to indicate that it's intended for API use, https://github.com/PDAL/PDAL/blob/master/pdal/private/MathUtils.hpp#L222-L229

I guess I'll file a ticket against PDAL to find out if this method is intended to be used as part of the API or not. 

Shall I close this one then?

**Comment by SpaceIm** [comment]
This symbol is not exported by PDAL (no `PDAL_DLL`), you can open a PR upstream.

**Comment by SpaceIm** [comment]
Those symbols were exported in previous versions, but this PR broke it: https://github.com/PDAL/PDAL/pull/3161

**Comment by lakinwecker** [comment]
It's fine. I used it because it was exactly what I needed, but I don't think that it's that critical of a thing. I can reproduce the code locally.  Now that you've pointed out that the private files are not intended for use, I won't depend on them.

Thanks for the prompt and thorough response.  I'm closing this now.
