### ISSUE TITLE
[package] qt/6.0.4: unknown option '-fPIC' on windows

### ISSUE THREAD

**Issue by yuriy-mochurad** [conan-io/conan-center-index#5566]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: qt/6.0.4
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.36.0
  * Python version: 3.7.3

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
cl : command line warning D9002: ignoring unknown option '-fPIC'
```

</details>

**Comment by SpaceIm** [comment]
Not sure to understand the issue, is their something wrong induced by this warning?

**Comment by yuriy-mochurad** [comment]
The build succeeds, but `-fPIC` flag does not do anything on Windows and produces warning noise.
