### ISSUE TITLE
[question] conanbuildinfor.cmake conan_include_build_modules error when include flatbuffer/1.12.0  with short paths

### ISSUE THREAD

**Issue by nowgain-nowpain** [conan-io/conan-center-index#5616]
```
CMake Error at build_r/conanbuildinfo.cmake:7307 (include):
  include could not find load file:
C:/Apps/Conan_data/flatbuffers/1.12.0/_/_/package/49da2fe92eee527087f281dc4348828e4995edaa/bin/cmake/BuildFlatBuffers.cmake
Call Stack (most recent call first):
  build_r/conanbuildinfo.cmake:6783 (conan_include_build_modules)
  CMakeLists.txt:168 (conan_basic_setup)
```
Checked my local conan cache (coanan_data). It has flatbuffers/1.12.0 installed under the required dir: (flatbuffers/1.12.0/_/_/package/49da2fe92eee527087f281dc4348828e4995edaa), since I'm using short paths, it  is redirected to: C:\.conan\17ce4f2\1. I guess this is why the above Error happens. It this a bug or is there a work around if I have to use short paths.  Thanks.

**Comment by SpaceIm** [comment]
Does it work if you replace in flatbuffers conanfile.py:
- `"bin/cmake"` by `os.path.join("bin", "cmake")`
- `"bin/cmake/BuildFlatBuffers.cmake"` by `os.path.join("bin", "cmake", "BuildFlatBuffers.cmake")`
