### ISSUE TITLE
[package] multiple packages build-requirement update

### ISSUE THREAD

**Issue by leyewen** [conan-io/conan-center-index#564]
### Package Details
`libiconv-1.15` upgrade `msys2/20161025` -> `msys2/20190524`.
`libx264-20190605` upgrade `nasm/2.13.02` -> `nasm/2.14`.
`libx265-3.0` upgrade `nasm/2.13.02` -> `nasm/2.14`.
`openh264-1.7.0` upgrade `nasm/2.13.02` -> `nasm/2.14`.
`openh264-1.7.0` upgrade `msys2/20161025` -> `msys2/20190524`.
`xz_utils-5.2.4` upgrade `msys2/20161025` -> `msys2/20190524`.
`OpenCV 4.2.0` and `3.4.9` have been released, 2019-12-23.
......
And others unlisted packages.

Please upgrade `build_requirements` to new version.

**Comment by danimtb** [comment]
@leyewen thanks for the request. Currently we have many PRs open adding new recipes and updating some of them for a lot of libraries. Build requires in recipes are just a helper for the user (in this case to compile with MinGW), but you can always override that using the build require in your profile

**Comment by Croydon** [comment]
I think this issue can be closed.

We don't use `msys2/20161025` in any recipe anymore, and keeping build requirements up to date is an ever ongoing task, having a generic open issue is not helping with that 😃

**Comment by leyewen** [comment]
issue close.
