### ISSUE TITLE
[conan.io/center] version sorting of a package (semver ignored ?)

### ISSUE THREAD

**Issue by dkgs** [conan-io/conan-center-index#5651]
When on a package page, for example: https://conan.io/center/restinio?version=0.6.13 for the package restinio in version 0.6.13 .

The button "Go To Latest" redirect to the version 0.6.9 of the package. I would expected the version 0.6.13 to be the latest instead.

Seems ordering is based on string comparison instead of properly comparing semver versions.

**Comment by prince-chrismc** [comment]
100% I complained in #3618 🤞 this gets fixed

**Comment by jgsogo** [comment]
😞  Yes, we know the bug. Now it is us the ones who should fix it, but we are focusing first on learning the services running behind the scenes and then we will look into the webapp.

The problem, and maybe some of you can suggest a solution, is that not all the packages follow semver and it is hard to figure out a generic implementation that would work for all the references. Probably it is just about trying different _algorithms_ in order and use the first one to match. If none of them, just don't show the button.

**Comment by jgsogo** [comment]
Closing in favor of #9418, it is more concrete about the problem and alternate solutions... and better to centralize it all in the same issue.

Thanks!
