### ISSUE TITLE
[package] autoconf/2.7.1: GDAL fails to build due to autoconf ChannelDefs.pm missing

### ISSUE THREAD

**Issue by Renari** [conan-io/conan-center-index#5715]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **autoconf/2.7.1**
  * Operating System+version: **CentOS 7 docker container**
  * Compiler+version: **gcc 4.8.5**
  * Docker image: **centos/7**
  * Conan version: **conan 1.33.1**
  * Python version: **Python 3.6.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Attempt to install GDAL, I'm using cmake-conan so build_type is being overwritten in the profile above to be `Debug`.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Can't locate Autom4te/ChannelDefs.pm in @INC (@INC contains: /home/conan/w/BuildSingleReference/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/bin/share/autoconf /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/centos/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/bin/autoreconf line 52.
BEGIN failed--compilation aborted at /home/centos/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/bin/autoreconf line 52.
```

</details>

**Comment by Renari** [comment]
I have `ChannelDefs.pm` in these locations:

>/home/centos/.conan/data/autoconf/2.71/\_/\_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/bin/share/autoconf/Autom4te/ChannelDefs.pm
/home/centos/.conan/data/automake/1.16.3/\_/\_/package/258f6f05ca54813b3d7180161753df7f9ccf7e1d/bin/share/automake-1.16/Automake/ChannelDefs.pm

I'm assuming that this entry is supposed to match the autoconf entry above:
> /home/conan/w/BuildSingleReference/.conan/data/autoconf/2.71/\_/\_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/bin/share/autoconf

It would still be missing the include directory of `Autom4te` though.

**Comment by Renari** [comment]
It looks like this can be fixed by adding the correct directories to the `PERL5LIB` environment variable.

**Comment by Renari** [comment]
Further investigation into this leads me to believe the above error is unrelated:
```
autom4te_perllibdir = self._autoconf_datarootdir
self.output.info("Setting AUTOM4TE_PERLLIBDIR to {}".format(autom4te_perllibdir))
self.env_info.AUTOM4TE_PERLLIBDIR = autom4te_perllibdir
```
I believe this is fixing the above issue, currently trying to find out what else could be the cause.

**Comment by Renari** [comment]
This is reproducible simply by running `conan install gdal/3.2.1@ --build=missing`, I still believe this to be a autoconf issue and not a gdal issue.

The above command reports:
```
configure.ac: error: required file 'config.rpath' not found
```
before failing.

**Comment by SpaceIm** [comment]
yes, already reported in https://github.com/conan-io/conan-center-index/issues/5707. Since https://github.com/conan-io/conan-center-index/pull/5539, there might be lot of issues in recipes where underlying build sytem is autotools and autoreconf is called.

**Comment by SpaceIm** [comment]
Please try https://github.com/conan-io/conan-center-index/pull/5718
