### ISSUE TITLE
[request] Running CCI for GCC11

### ISSUE THREAD

**Issue by fpelliccioni** [conan-io/conan-center-index#5725]
It would be very useful if you could generate the binaries for all recipes for GCC11.

Thanks

**Comment by madebr** [comment]
That would be fabulous.
The conan gcc 11 docker image was added in https://github.com/conan-io/conan-docker-tools/pull/260 and fixed in https://github.com/conan-io/conan-docker-tools/pull/265: https://hub.docker.com/r/conanio/gcc11

**Comment by joxoby** [comment]
Are there any updates on this?

**Comment by SSE4** [comment]
it's already there

**Comment by n00b42** [comment]
Is it? I just had a look at some popular packages (e.g. [openssl](https://conan.io/center/openssl)) and there seem to be no gcc11 binarys on [conan-center](https://conan.io/center).

**Comment by SSE4** [comment]
> Is it? I just had a look at some popular packages (e.g. [openssl](https://conan.io/center/openssl)) and there seem to be no gcc11 binarys on [conan-center](https://conan.io/center).

it runs for new PRs only, and only if all the dependencies are already built with GCC 11 (entered new epoch).
to add GCC 11 for the existing packages, we may need to run tapaholes which will take significant time (hours, maybe even days, for all the libraries).

**Comment by Croydon** [comment]
@SSE4 Seems like this was never mentioned in the changelog, maybe it could be added retrospectively?

**Comment by n00b42** [comment]
@SSE4 Ok, thank you for your explanation.

**Comment by SSE4** [comment]
> @SSE4 Seems like this was never mentioned in the changelog, maybe it could be added retrospectively?

see #8587. it will be added to changelog as soon as docs PR is approved.
