### ISSUE TITLE
[conan.io/center] Document how to consume each package

### ISSUE THREAD

**Issue by alejandro-colomar** [conan-io/conan-center-index#5728]
You provide files for cmake's `find_package()` but you don't specify the name of that file, which isn't always consistent with the package name.  For example prometheus-cpp is found with `find_package(prometheus-cpp)`, but librdkafka is found with `find_package(RdKafka)`.

Also, one has to dig into those files (Findxxx.cmake) to see what has to be used in `target_link_library()`  (i.e., `prometheus-cpp::core`).  Could you please provide a list of available features for each package?

**Comment by ericLemanissier** [comment]
Can you take a look at https://docs.conan.io/en/latest/reference/generators/markdown.html ? Does it answer your questions ?

most of conan packages actually use the same cmake package name and targets as the upstream project does, this is why it is not always consistent with the conan package name

**Comment by alejandro-colomar** [comment]
> Can you take a look at https://docs.conan.io/en/latest/reference/generators/markdown.html ? Does it answer your questions ?

Yup, it does.

Would it be a good idea to embed that information in the conan-center website?

Because at the time that I already built the markdown file, I already have the Findxxx.cmake files (or pkg-config, ...) and can read them as esily as the md, and I'll trust more the source code...

I think it helps more in the begining, when I'm planing to consume a package, when I could have a look at the website in conan-center and say "hey, I have to add these 2 lines to my cmake or make files".  Then I add them and it works.  No need to look at generated files.

What do you think?

> most of conan packages actually use the same cmake package name and targets as the upstream project does, this is why it is not always consistent with the conan package name

I guessed so; meh.

**Comment by ericLemanissier** [comment]
> Would it be a good idea to embed that information in the conan-center website?

I think I asked for that when conan.io/center was created, It'd be a great addition !

**Comment by jgsogo** [comment]
It is in the roadmap 😉 . Not enough hands to make it happen really soon, but it will be delivered.

**Comment by alejandro-colomar** [comment]
Is there anything I may help?

**Comment by jgsogo** [comment]
I'm very sorry, but the source code of the frontend and microservices running behind the scenes is not publicly available (it might change in the future).

Our plan is to use the output from the `markdown` generator (using the first configuration that works). This is not ideal but it can be a good starting point. Nevertheless, I feel like the output from the `markdown` generator can be improved in Conan client... maybe in a second iteration we decide that it is better to run some Conan commands, get the JSON output and run some substitution on some template.

**Comment by jgsogo** [comment]
Now you can check the "Use it" tab with the content of the markdown generator.
