### ISSUE TITLE
[request] nats.c/v2.4.1

### ISSUE THREAD

**Issue by jgallucci32** [conan-io/conan-center-index#5732]
### Package Details
  * Package Name/Version: **nats.c/v2.4.1**
  * Website: **https://nats.io/**
  * Source code: **https://github.com/nats-io/nats.c**

### Description Of The Library / Tool
A C client for the NATS messaging system.

NATS is a connective technology built for the ever increasingly hyper-connected world. It is a single technology that enables applications to securely communicate across any combination of cloud vendors, on-premise, edge, web and mobile, and devices. NATS consists of a family of open source products that are tightly integrated but can be deployed easily and independently. NATS is being used globally by thousands of companies, spanning use-cases including microservices, edge computing, mobile, IoT and can be used to augment or replace traditional messaging.

**Comment by OriKerer** [comment]
Looks like @AndreyAndreevich implemented a recipe for bintray that works.
It may be a good base: https://github.com/AndreyAndreevich/conan-nats.c
