### ISSUE TITLE
[package] cmake/*: Over strict `settings` for a tool package

### ISSUE THREAD

**Issue by dribeas** [conan-io/conan-center-index#5749]
The [settings](https://github.com/conan-io/conan-center-index/blob/7a187641767c21e7b9b9bf61479a063641408f93/recipes/cmake/3.x.x/conanfile.py#L14) in the package include `arch`-itecture, `compiler` and `build_type`, which means that when we change any of those parameters it requires a different binary.

Given that this is a tool that can be used with any `compiler` or `build_type` those should not be part of the `settings`.  There's a question about `arch`, personally I would be inclined not to include that either, but this assumes that we can use the same binary everywhere and there maybe 32 systems that are not able to run 64 bit binaries, and vice versa.

But at least the `compiler` and `build_type` should be removed from `settings`.

**Comment by ericLemanissier** [comment]
see https://github.com/conan-io/conan-center-index/issues/3157

**Comment by jgsogo** [comment]
Please, @dribeas , follow the conversation in the linked issue. There you could also find the motivations.
