### ISSUE TITLE
package abseil/20210324.1: Linker error while using  absl::SimpleAtob(absl::string_view, bool *)

### ISSUE THREAD

**Issue by abhijith96** [conan-io/conan-center-index#5766]
Linker Error while using abseil from conan repository. I have build a simple project using abseil as dependency.

Conan install went smoothly. while building my sample project i got a linker error while using
absl::SimpleAtob function. Rest of the functions in abseil were working correctly.

[project link](https://github.com/abhijith96/abseilconsumer). Here i have made two executable. one of them using absl::SImpleAtob and another using absl::flat_hash_set. The executable using flat hash set builds and runs fine. The problem is only with absl::SimpleAtob function.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **abseil/20210324.1**
  * Operating System+version: **Macos Catalina 10.15.6**
  * Compiler+version: apple-clang 11.0
  * Conan version: **conan  1.36.0**
  * Python version: **Python 3.9.5**
  * cpp standard cpp17
  * generator used: cmake

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Debug
[options]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)

clone the project. do conan install. run cmake. then build the project using make.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Undefined symbols for architecture x86_64:
  "absl::lts_20210324::SimpleAtob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, bool*)", referenced from:
      _main in sample_program_giving_linker_error.cpp.o
ld: symbol(s) not found for architecture x86_64`

```

</details>

**Comment by SpaceIm** [comment]
Yes, I can reproduce this issue when C++ standard of consumer project is C++17. Try to set compiler.cppstd to 17 in your profile and build abseil from source.

**Comment by abhijith96** [comment]
thank you, it worked.
