### ISSUE TITLE
[question] How to deal with distributed sources for a package 

### ISSUE THREAD

**Issue by dotChris90** [conan-io/conan-center-index#5767]
Hello Conan team, 

my overall goal is to bring "Fast-DDS" into CCI. 
For that reason i have to add https://github.com/eProsima/foonathan_memory_vendor to CCI and then reference it as dependency from Fast-DDS. 

Now we have the tricky part : 
- the foonathan memory vendor does not contain any C/C++ Code but just CMake files and references to https://github.com/foonathan/memory via git
- the reference is to a specific commit id and not to a tag

My question is now : how to deal with this? 
- shall the vendor just become a   CCI package or also the origin 
- does CCI allow packages with a commit as version? 
- is it allowed that during the jenkins build of conan package git command is executed?

**Comment by jgsogo** [comment]
Hi, @dotChris90 

First of all, you should package the original https://github.com/foonathan/memory (name probably should be `foonathan_memory` given the generated CMake targets). It is ok to package libraries that doesn't publish releases, just [use `cci.<date>` and use the latest commit on that date](https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-version-should-packages-use-for-libraries-without-official-releases). Nevertheless, this library offers tags, so better to follow them. If `fast-dds` requires a specific commit that is not tagged, better to investigate a bit and explain it when submitting the `cci.<date>` release.

 Then, if https://github.com/eProsima/foonathan_memory_vendor is required (probably not?), you could package it as `eprosima-foonathan_memory`, but, please, think about this twice. At first sight, the Conan package for `foonathan_memory` should offer everything needed by `fast-dds`: CMake targets and so on, maybe the patch must be done to `fast-dds` instead to consume _official_ targets.

Then package `fast-dds` using `foonathan_memory` as a requirement.

Maybe my answer is a bit abstract, so probably it is much better to start creating the pull-requests and reason about something more concrete.

**Comment by dotChris90** [comment]
ok - got your points! :D will considering them when start implementation.

**Comment by dotChris90** [comment]
i keep the issue open while implementing if more questions to you guys - but it's not a urgent issue that must be anwsered.

**Comment by dotChris90** [comment]
closed because : PR already present on https://github.com/conan-io/conan-center-index/pull/5891 and Fast-DDS implementation (which i locally have) accept the v0.7 version. so no reason to keep open.
