### ISSUE TITLE
[package] <fmt>/<7.1.3>: Add Conan option to toggle OS support to enable use in bare metal applications

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan-center-index#5771]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **fmt/7.1.3**
  * Operating System+version: **Embedded bare metal (No OS)**
  * Compiler+version: **GCC 11**
  * Conan version: **conan 1.36.0**
  * Python version: **Python 3.9.5**

Currently, fmt is always built with OS support so that it is only suitable for use on platforms with a full-fledged operating system.
fmt has a CMake option, `FMT_OS`, which can be used to disable this requirement.
This allows building for embedded platforms which do not have an operating system or only a real-time operating system.
Would it be possible to add an option in Conan such as `with_os` to toggle the value of the CMake variable?

**Comment by SpaceIm** [comment]
you can try https://github.com/conan-io/conan-center-index/pull/5773

**Comment by jwillikers** [comment]
@SpaceIm Thanks for the quick PR!
