### ISSUE TITLE
[package] fftw/3.3.9: NotFoundException: Not found: http://www.fftw.org/fftw-3.3.9.tar.gz

### ISSUE THREAD

**Issue by CJCombrink** [conan-io/conan-center-index#5817]
conan fails to download the sources for fftw from http://www.fftw.org/fftw-3.3.9.tar.gz.
Updating to use http://fftw.org/fftw-3.3.9.tar.gz works (removed www from the address)

The address http://www.fftw.org/ responds with: 404 Not found
Perhaps the www URL was removed/retired.
The github page also points to the address without the www: https://github.com/FFTW/fftw3
> should instead download official tarballs from http://fftw.org/,

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **fftw/3.3.9**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 16**
  * Conan version: **conan 1.37.0**
  * Python version: **Python3.9.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```
conan install fftw/3.3.9@_/_ --build=fftw
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

fftw/3.3.9: Forced build from source
Installing package: fftw/3.3.9
Requirements
    fftw/3.3.9 from 'conan-center' - Cache
Packages
    fftw/3.3.9:f318cb8b4819a24d69b2d6e6ed8f40f24c919717 - Build

Installing (downloading, building) binaries...
fftw/3.3.9: WARN: Build folder is dirty, removing it: C:\Users\XXX\.conan\data\fftw\3.3.9\_\_\build\f318cb8b4819a24d69b2d6e6ed8f40f24c919717
fftw/3.3.9: WARN: Trying to remove corrupted source folder
fftw/3.3.9: WARN: This can take a while for big packages
fftw/3.3.9: Configuring sources in C:\Users\XXX\.conan\data\fftw\3.3.9\_\_\source
ERROR: fftw/3.3.9: Error in source() method, line 60
        tools.get(**self.conan_data["sources"][self.version])
        NotFoundException: Not found: http://www.fftw.org/fftw-3.3.9.tar.gz
```

</details>

**Comment by Nekto89** [comment]
both links (with and without "www.") work on my side

**Comment by CJCombrink** [comment]
@Nekto89 
Yes I saw today, the problem might have been related to the [8/06/2021 Internet Outage](https://fortune.com/2021/06/09/fastly-internet-outage-reason-tuesday-june-8-websites-down/).

The issue can probably be closed unless there is a reason to move to the https://fftw.org site. 
It seems like the www site does not have security while the https one does.

Please advise.
