### ISSUE TITLE
[package] <coin-utils>/<2.11.4>: installation fails on macos

### ISSUE THREAD

**Issue by abhijith96** [conan-io/conan-center-index#5820]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **coin-utils/2.11.4**
  * Operating System+version: **Macos 10.15.6**
  * Compiler+version: **apple_clang**
  * Docker image: 
  * Conan version: **conan 1.37.0**
  * Python version: **Python 3.9.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)

just do conan create . channel@name -build=coin-utils

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `DYLD_LIBRARY_PATH' environment variable
     during execution

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
ERROR: coin-utils/2.11.4: Error in package() method, line 112
        autotools.install()
        ConanException: Error 2 while executing make install -j12

</details>

**Comment by SpaceIm** [comment]
Can't reproduce this issue on Macos 10.15 & apple-clang 12.

Could you provide the full log? As well as your conanfile because you don't seem to install coin-utils directly.

**Comment by abhijith96** [comment]
from conans import AutoToolsBuildEnvironment, ConanFile, tools
from conans.errors import ConanInvalidConfiguration
from contextlib import contextmanager
import os


class CoinUtilsConan(ConanFile):
    name = "coin-utils"
    version = "2.11.4"
    description = "CoinUtils is an open-source collection of classes and helper functions that are generally useful to multiple COIN-OR projects."
    topics = ("conan", "coin-utils", "sparse", "matrix", "helper", "parsing", "representation")
    url = "https://github.com/conan-io/conan-center-index"
    homepage = "https://github.com/coin-or/CoinUtils"
    license = ("EPL-2.0",)
    settings = "os", "arch", "build_type", "compiler"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
    }
    default_options = {
        "shared": False,
        "fPIC": True,
    }
    exports_sources = "patches/**"

    _autotools = None

    @property
    def _source_subfolder(self):
        return "source_subfolder"

    @property
    def _build_subfolder(self):
        return "build_subfolder"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            del self.options.fPIC
            if self.settings.os == "Windows":
                raise ConanInvalidConfiguration("coin-utils does not provide a shared library on Windows")

    def requirements(self):
        self.requires("zlib/1.2.11@user/testing")
        self.requires("bzip2/1.0.8@user/testing")

    def build_requirements(self):
        if tools.os_info.is_windows and not tools.get_env("CONAN_BASH_PATH"):
            self.build_requires("msys2/20200517")
        if self.settings.compiler == "Visual Studio":
            self.build_requires("automake/1.16.2")

    def source(self):
        if not self.settings.compiler.cppstd:
            self.settings.compiler.cppstd = 14
            print("compiler standard not given cpp 14 is choosen\n")
        else:
            print("compiler cpp standard: ",  self.settings.compiler.cppstd, "\n")
        tools.get(**self.conan_data["sources"][self.version])
        os.rename("CoinUtils-releases-{}".format(self.version), self._source_subfolder)

    @contextmanager
    def _build_context(self):
        if self.settings.compiler == "Visual Studio":
            with tools.vcvars(self.settings):
                env = {
                    "CC": "{} cl -nologo".format(tools.unix_path(self.deps_user_info["automake"].compile)),
                    "CXX": "{} cl -nologo".format(tools.unix_path(self.deps_user_info["automake"].compile)),
                    "LD": "link -nologo",
                    "AR": "{} lib".format(tools.unix_path(self.deps_user_info["automake"].ar_lib)),
                }
                with tools.environment_append(env):
                    yield
        else:
            yield

    def _configure_autotools(self):
        if self._autotools:
            return self._autotools
        self._autotools = AutoToolsBuildEnvironment(self, win_bash=tools.os_info.is_windows)
        self._autotools.libs = []
        if self.settings.compiler == "Visual Studio":
            self._autotools.cxx_flags.append("-EHsc")
            self._autotools.flags.append("-FS")
        yes_no = lambda v: "yes" if v else "no"
        configure_args = [
            "--enable-shared={}".format(yes_no(self.options.shared)),
            "--enable-static={}".format(yes_no(not self.options.shared)),
        ]
        if self.settings.compiler == "Visual Studio":
            configure_args.append("--enable-msvc={}".format(self.settings.compiler.runtime))
        self._autotools.configure(configure_dir=os.path.join(self.source_folder, self._source_subfolder), args=configure_args)
        return self._autotools

    def build(self):
        for patch in self.conan_data.get("patches", {}).get(self.version, []):
            tools.patch(**patch)

        with self._build_context():
            autotools = self._configure_autotools()
            autotools.make()

    def package(self):
        self.copy("LICENSE", src=self._source_subfolder, dst="licenses")
        with self._build_context():
            autotools = self._configure_autotools()
            autotools.install()

        os.unlink(os.path.join(self.package_folder, "lib", "libCoinUtils.la"))

        if self.settings.compiler == "Visual Studio":
            os.rename(os.path.join(self.package_folder, "lib", "libCoinUtils.a"),
                      os.path.join(self.package_folder, "lib", "CoinUtils.lib"))

        tools.rmdir(os.path.join(self.package_folder, "lib", "pkgconfig"))
        tools.rmdir(os.path.join(self.package_folder, "share"))

    def package_info(self):
        self.cpp_info.libs = ["CoinUtils"]
        if self.settings.os == "Linux":
            self.cpp_info.system_libs = ["m"]
        self.cpp_info.includedirs.append(os.path.join("include", "coin"))
        self.cpp_info.names["pkg_config"] = "coinutils"

**Comment by abhijith96** [comment]
everything is same as recipe provided in conan center. i am setting the compiler cpp std manually to cpp 14. In my profile settings.compiler.cppstd is not specified. So zlib and bizp2 were compiled with default compiler.cppstd.
which is c++98 in my version of apple clang. Is the error due to that.

**Comment by abhijith96** [comment]
When delete coin-utils folder from the cache and do build it works fine. When i try to build from source again with the package already present in local cache only it gives this error. When i create packages in downstream of coin-utils with build all option also this error happens.

My rough guess is that we are not doing make clean from the previous build.

**Comment by SpaceIm** [comment]
Yes, I've seen this issue when cross-building to iOS. Don't know what's wrong, because conan remove previous build folder when you build again, and source code is copied in this folder.

**Comment by SpaceIm** [comment]
`autotools.install(args=["-j1"])` seems to help.

**Comment by tkralphs** [comment]
FYI, see https://github.com/coin-or/CoinUtils/issues/181#issuecomment-907719978. 

I know this is off-topic, but I noticed you have a patch to disable pkg-config. There is a n option to configure for that (`--disable-pkg-config`), so no need to patch. But I'm curious why you need to do that in any case. I'm not sure you'll be able to build as easily without pkg-config support in future versions as you can now.

**Comment by tkralphs** [comment]
For historical purposes, I found the issue about parallel builds failing in Clp and I thought I would like it here: https://github.com/coin-or/Clp/issues/109. There is also this [comment](https://github.com/Homebrew/homebrew-core/pull/57830#issuecomment-907857545) discussing an alternative workaround used in the homebrew recipes.

**Comment by SpaceIm** [comment]
Thanks for sharing @tkralphs. Quick question: do you know if calling autoreconf with recent autotools versions would work (assuming we have coin-or m4 files)?

We have two issues currently in all coin-or libraries:
- installation (but easy to fix)
- cross-build to Macos M1:
  - for static, updating config.guess and config.sub is sufficient
  - for shared, it doesn't work, maybe due to old libtool version?

**Comment by tkralphs** [comment]
Sorry, I seem to have missed answering this. For the current release of CoinUtils, autoreconf with recent autotools will not work, as the build system in stable/2.11 is based on a very old version of the autotools. In the meantime, we have fixed all of this and updated the build system to recent autotools. Once I can finally get out a new stable version of CoinUtils, it will be possible to do this. But I see you have already implemented some kind of fix which seems to work.
