### ISSUE TITLE
[package] cppcheck/2.4.1: Running cppcheck missing cfg files

### ISSUE THREAD

**Issue by thesummer** [conan-io/conan-center-index#5831]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cppcheck/2.4.1**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 7.5**
  * Conan version: **conan 1.37.1**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

* Install cppcheck with a runenv:
```
$ conan install "cppcheck/2.4.1@" -r conan-center  -g virtualrunenv
$ source activate_run.sh
```
* Run cppcheck on directory containing C++ files
```
cppcheck --xml --enable=warning,style,performance --std=c++11 . 2> test.xml
cppcheck: Failed to load library configuration file 'std.cfg'. File not found
```

It seems that cppcheck needs to be build locally because it uses some hardcoded paths, so `build_policy = "always"` should be set.
Also [conanfile.py#L66](https://github.com/conan-io/conan-center-index/blob/master/recipes/cppcheck/all/conanfile.py#L66) deletes the `share` directory that's where the *cfg* files are installed by default and where the hardcoded path points to.
With this line deleted (and build locally) I can run the cppcheck installed via conan properly.

If you want, I can prepare a PR for these 2 changes.

**Comment by madebr** [comment]
It would be nice if the `cppcheck` binary could be made relocatable.
Perhaps the files can be loaded from a relative location to the binary location?

Anyway, please open a pr + a test in the test package.
