### ISSUE TITLE
[question] providing applications to cci?

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan-center-index#5839]
I would like to see recipes for tools like:
mono, plantuml, java, etc... 
i.e. Applications

1. Is CCI open to accept PR for these tools?
2. What is when they cannot be build from source and only binaries (for the major three platforms) can be provided?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
> I would like to see recipes for tools like:
> mono, plantuml, java, etc...
> i.e. Applications
> 
> 1. Is CCI open to accept PR for these tools?

Are those tools open-source? Are they develop using C++?

> 2. What is when they cannot be build from source and only binaries (for the major three platforms) can be provided?
> 

You can read the packaging policy here (https://github.com/conan-io/conan-center-index/blob/master/docs/packaging_policy.md). The general rule is that all packages have to be built from sources.

**Comment by derived-coder** [comment]
I am not sure they are developed with C++, but these are tool that I saw are needed by other C++ libraries for code generation or documentation. So when they are buildable via source, I could add recipes for it?

**Comment by jgsogo** [comment]
This is a place for C/C++ packages, not a binary distribution service. If those tools are written in C/C++ they are more than welcome, if they are needed to build other packages we will think about how we can provide them (we can install them in the CI machines and create an `xxx/system` recipe to manage them).

**Comment by derived-coder** [comment]
Mono and Java are written in C/C++ as foundation, but the big parte is in written in C#/Java then
PlantUML is using java

As definition, this would mean I can only add mono/java recipes?

**Comment by jgsogo** [comment]
IMHO, those packages are not meant for ConanCenter, they are not C/C++ or tools required by the C/C++ ecosystem.

What is the use-case you are trying to cover? Why do you think ConanCenter could be a good place to add those recipes? I think it would be helpful if we are able to know about the full picture.

Thanks!

**Comment by derived-coder** [comment]
> these are tools that I saw needed by other C++ libraries for code generation or documentation.

**Comment by jgsogo** [comment]
> > these are tools that I saw needed by other C++ libraries for code generation or documentation.

Which libraries are requiring these tools? Is there any pull-request blocked because of this?

**Comment by jgsogo** [comment]
As said [here](https://github.com/conan-io/conan-center-index/pull/5792#pullrequestreview-763924436), same about final applications: if they are useful for other libraries or to the C++ ecosystem, let's go with them.
