### ISSUE TITLE
[question] How to fix TheiaSfm dependencies

### ISSUE THREAD

**Issue by vcampmany** [conan-io/conan-center-index#5840]
I'm trying to write a recipe for the [TheiaSfm](https://github.com/sweeneychris/TheiaSfM) library. I have written a basic recipe following the example of other recipes in this repository. However, I reached I point were I don't know how to proceed. You can see the recipe in my fork: https://github.com/vcampmany/conan-center-index/tree/master/recipes/theiasfm

I'm hitting two problems with the recipe I wrote.
1. `glog` is a dependency of the library, and I need it with the option `nothreads = False`. Here is how I specify it: [link to recipe](https://github.com/vcampmany/conan-center-index/blob/master/recipes/theiasfm/all/conanfile.py#L45). However, the binary for `glog` with this option is not available. To avoid the issue I tried to create the package with the `--build` flag as follows: `conan create . theiasfm/v0.8 --build=gflags`. This command builds gflags successfully. However, I'm unsure if that is the right way to go. Is there a way to force the build of a package from the recipe itself ,so that the user doesn't have to care about it? And, what is the prefered solution for this type of issues? 

2. TheiaSfm uses `find_package` to get its dependencies and there are `FindX.cmake` files for all the dependencies in the [cmake](https://github.com/sweeneychris/TheiaSfM/tree/master/cmake) folder except for ceres-solver.  When I run `conan create`, of course, cmake doesn't find the ceres dependency. What would be the best way to fix this problem?

Thanks for the help!

**Comment by intelligide** [comment]
For the point 2, use the [`cmake_find_package` generator](https://docs.conan.io/en/latest/reference/generators/cmake_find_package.html) and patch the sources.

**Comment by vcampmany** [comment]
Thanks @intelligide, that worked.
