### ISSUE TITLE
[question] qt/6.1.0 linking issue on windows

### ISSUE THREAD

**Issue by yuriy-mochurad** [conan-io/conan-center-index#5844]
While building project on windows with qt/6.1.0 conan pakage I get weird linking error:

```
MSVCRT.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl __s
crt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) 

fatal error LNK1120: 1 unresolved externals
```

It might looks like it is not related to qt at all, but at the same time building same codebase against Qt installed with installer manually succeeds. 

Any. help would be greatly appreciated. 

`qt` options set in my conanfile are:
```
"qt:qtdeclarative": True,
"qt:shared": True,
"qt:qtquickcontrols2": True,
"qt:qtimageformats": True,
"qt:qtsvg": True,
"qt:qttools": True,
"qt:qtactiveqt": True,
"qt:qttranslations": True,
"qt:opengl": "dynamic"
```

**Comment by yuriy-mochurad** [comment]
@ericLemanissier maybe you would have any ideas what might be an issues here?

**Comment by yuriy-mochurad** [comment]
It looks like conan package might not be linking with qt entrypoint. From doc:

```
On certain platforms, Qt applications link against Qt's entrypoint lib by default.That library provides implementations of main (or WinMain).
```

**Comment by yuriy-mochurad** [comment]
@ericLemanissier it looks like I have found a possible fix for this issue. Adding a line 
```
self.cpp_info.components["qtCore"].libs.append("Qt6EntryPoint%s" % libsuffix)
```
in `package_info` method actually allows me to compile app properly. Can we have this fix in possibly?

**Comment by ericLemanissier** [comment]
Thanks for the investigation. We may need to create a dedicated component, and require it conditionally from qtcore. Do you know for which settings and options.shared values it is needed?

**Comment by OpenLarry** [comment]
Is this issue actually fixed for Qt6? Seems like the mentioned PR only fixes the problem for Qt5.

Currently, I'm having the same issue with Qt 6.1.2 and manual linking to Qt6EntryPoint or adding `-ENTRY:mainCRTStartup` to the linker flags seems to help.

**Comment by ericLemanissier** [comment]
It's probably not solved for qt6. don't hesitate to make a PR
