### ISSUE TITLE
[question] What's the point of having "conan" in topics

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan-center-index#5858]
Probably every recipe has "conan" in list of topics in CCI. Where is it used to be useful?

**Comment by madebr** [comment]
Conan is our religion. We are spreading *The Word*.
Please do your part, and tell your close ones about the one and only truth: Conan.

But seriously, you're probably right.
It has become a habit. And you know what they say about old habits.. :smile:

**Comment by Croydon** [comment]
This is a historical relic from times before CCI and as every recipe had its own git repository. The idea was to use the tags also for meta tags on GitHub/Bintray and similar. 

Now, where we have CCI and Bincrafters tooling also allows to manage unlimited recipes in a single git repository, adding a `conan` tag to every repository is unneccesary. 

In retrospective, it probably always was unnecessary, as those scripts populating the meta data could have added a `conan` tag on the fly.

**Comment by SSE4** [comment]
yes, the point is to add tag to github or similar hosting, so people could search by this topic and find all valid recipes.
while we maintain single git repository now, still, someone may fork an individual recipe to its own repository, so he will get this `conan` topic for free.
