### ISSUE TITLE
[question] Miniz package - difference between amalgonated API

### ISSUE THREAD

**Issue by hnOsmium0001** [conan-io/conan-center-index#5872]
The package miniz/2.1.0 provides multiple header files instead an amalgamated single file. However, the `miniz.h` header doesn't include `miniz_zip.h`, different from the official/amalgamated single `miniz.h` which includes everything.

I found this when trying to package https://github.com/troldal/Zippy, which depends on `mz_zip_archive_file_stat` to be defined after including `miniz.h`.
(Zippy is a dependency of https://github.com/troldal/OpenXLSX which I'm working on also)

1. Generate the amalgamation
2. Patch `miniz.h` to include `miniz_zip.h` also
3. Just let it be and tell downstream users/recipes to modify their code (I don't like this one)

**Comment by SpaceIm** [comment]
Is it better with miniz/2.2.0? https://github.com/conan-io/conan-center-index/pull/6091
