### ISSUE TITLE
[package] qt/5.15.2: Can't build on Windows

### ISSUE THREAD

**Issue by ngc7293** [conan-io/conan-center-index#5894]
I'm trying to build Qt 5.15.2 on my computer because the binaries don't include submodules I use, but it's failing with errors pertaining to other libraries it requires. Those libraries are reported as installed correctly by conan.

I'm working in Visual Studio Entreprise 2019's developer console (both developer command prompt and developer powershell give the same result).

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 16**
  * Conan version: **conan 1.37.2**
  * Python version: **Python 3.8.10**

### Active configuration
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
cppstd=20
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
1. Create conanfile with the following settings:
```
[requires]
qt/5.15.2
protobuf/3.17.1
nlohmann_json/3.9.1
gtest/1.10.0

[options]
qt:shared=True
qt:qtserialport=True
qt:with_mysql=False
qt:with_pq=False
qt:with_sqlite3=False
qt:with_odbc=False

[generators]
cmake
cmake_paths
```
2. `conan install .. -s build_type=Debug -s cppstd=20 --build=missing`
3. get error output shown below when trying to build Qt
```
ERROR: Feature 'system-zlib' was enabled, but the pre-condition 'libs.zlib' failed.

ERROR: Feature 'zstd' was enabled, but the pre-condition 'libs.zstd' failed.

ERROR: Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && !features.schannel && libs.openssl' failed.

ERROR: Feature 'system-png' was enabled, but the pre-condition 'features.png && libs.libpng' failed.
qt/5.15.2:
qt/5.15.2: ERROR: Package '3b9049e39502ba67bc917537989140f28dbbeab3' build failed
```

Is it a bug or am I missing prerequisites?

**Comment by ericLemanissier** [comment]
Can you please send the full log?

**Comment by ngc7293** [comment]
I can't!
I rebooted my computer, removed the `%USERPROFILE%/.conan` folder and tried again and it worked fine on first try. Not sure what happened...
