### ISSUE TITLE
https://conan.io/center search problem

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan-center-index#5896]
Reproduce:
1. Open https://conan.io/center
2. Search "qt"
3. In the result apge, type "wx" in the search box and type enter
4. In fact "wx" matches nothing, the result page doesn't change, i.e.
    * search box shows "qt"
    * search box auto complete list shows results or "qt"
    * search result is also for "qt"
---
Another related problem, reproduce:
1. Open https://conan.io/center
3. type "wx" in the search box and type enter
4. Nothing changes for the page, I think it should show a search result even without any matched result

**Comment by AbrilRBS** [comment]
Fixed with the release of Conan 2 a while back and the new CCI website, thanks for reporting it in the first time, sorry that we didn't circle back to the issue in time :)
