### ISSUE TITLE
[request] liquid-dsp/latest (help needed)

### ISSUE THREAD

**Issue by ruilvo** [conan-io/conan-center-index#5908]
### Package Details
  * Package Name/Version: **liquid-dsp/latest**
  * Website: **https://github.com/jgaeddert/liquid-dsp**
  * Source code: **https://github.com/jgaeddert/liquid-dsp**

### Description Of The Library / Tool

So, this is an amazing DSP library, with a generous library.

I could do the recipe but I need some help: 
- It uses autotools;
- It uses C99 `<complex.h>` so it doesn't build with MSVC. 

However, since, this a C library, it can easily be linked with MSVC.  It's possible to build it with msys2/mingw-64 and then generate a "link library" for MSVC... 
Can this workflow be made with Conan? I mean, if the compiler is MSVC, have msys2/mingw-64 as a dependency and build it with it, and then generate a link library with MSVC, and etc?

**Comment by uilianries** [comment]
@ruilvo I think you are looking for something like https://github.com/conan-io/conan-center-index/blob/c916710e54d587ba27f694a4678e7655a307ab76/recipes/re2c/all/conanfile.py#L43
