### ISSUE TITLE
[question] Packages built from latest git

### ISSUE THREAD

**Issue by espositofulvio** [conan-io/conan-center-index#5928]
Hi all,
I was trying to update all Vulkan related packages but hit a snag because spirv-tools/v2021.1 depends on spirv-headers master and doesn't work with spirv-headers/1.5.4.raytracing.fixed which is the latest release available (not on conan-center but on github). I was wondering if there's a precedent to have packages built from latest git instead of a specific release. I know that that might break packages but in some cases such as the Vulkan ecosystem should be safe as the repos are updated when a new specification is released.

**Comment by SpaceIm** [comment]
Some branches of Vulkan ecosystem are a nightmare to package for conan:
- `spriv-headers` is usually not backward compatible
- each `spirv-tools` version depends on specific commits (non-tagged) of spirv-headers, and there was no release of spirv-headers since last October (no answer here: https://github.com/KhronosGroup/SPIRV-Headers/issues/199)
- each `glslang` version depends on specific commits of `spirv-tools`
- each `shaderc` version depends on specific commits of `glslang` and `spirv-tools`
- each `vulkan-validationlayers` version depends on specific commits of `spirv-tools` and `spirv-headers`

You can package a commit of `spirv-headers` if it allows to unlock the situation. We follow this semantic: `cci.YYYYMMDD` where YYYYMMDD is the commit date.

**Comment by espositofulvio** [comment]
HI @SpaceIm,
thanks for your pointers. I was trying to do what I could with the latest spirv-headers release (1.5.4.raytracing.fixed, which should be enough to enable spirv-tools 2020.6, glslang 11.0.0 and shaderc 2020.5). But as you said it looks like the various release might depend on specific commits instead of other releases.

So my plan is, I'll first see how the LunarG SDK does things as I don't think anyone is really interested in intermediate release between SDKs (at the moment they are on vulkan-headers 1.2.176.1 and I guess whatever depends on that). If I can get a sense of the dependency graph from there, I'll try and package the specific commits from the various components belonging to the latest sdk and send a pull request for all the packages at once if that sounds ok.

It looks like I've found something to do with my weekend as I'm not planning to go to the beach :D

**Comment by espositofulvio** [comment]
OK it looks like the release notes of the Vulkan SDK explicitly states the commit of every component:

[Vulkan SDK Windows release notes](https://vulkan.lunarg.com/doc/view/latest/windows/release_notes.html)

So I guess the best thing will be creating packages from the same commits. 

As following SDK releases might be easier, it may also have sense to name conan packages versions after the SDK, something along the line of "sdk1.2.176".

It might be more informative than cci.YYYYMMDD. What do you think?

**Comment by espositofulvio** [comment]
@SpaceIm 
good news, I've managed to build the following packages on windows with msvc:

- Vulkan-Headers
- Vulkan-Loader
- Spirv-Headers
- Spirv-Tools
- Spirv-Cross
- glslang
- Vulkan-ValidationLayers
- shaderc

All of them at the same version included in the latest LunarG SDK, 1.2.176.1.

I used sdk-1.2.176.1 as the version number for all of them.

If maybe you could get a quick look here: https://github.com/espositofulvio/conan-center-index

It would be useful to see if something else is needed for other compilers/oses

**Comment by AndreyMlashkin** [comment]
I think, creating a conan recipe with git hash should be allowed.
We could just have
spriv-headers/f95c3b3@

**Comment by espositofulvio** [comment]
> I think, creating a conan recipe with git hash should be allowed.
> We could just have
> spriv-headers/f95c3b3@

Hi @AndreyMlashkin,
I've already discussed this with @SpaceIm, the convention for Conan is to have tagged release in the CCI, in case that's not possible then they use the format `cci.YYYYMMDD`. I don't know the story, but I guess they have their reasons, and there's little point trying to change now.
Anyway, I'll close this as spirv-headers is being reviewed.
