### ISSUE TITLE
[package] qt/5.15.2: test fails trying to link to .so while built statically

### ISSUE THREAD

**Issue by Renari** [conan-io/conan-center-index#5931]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Linuxmint 20.1 ulyssa**
  * Compiler+version: **GCC 9.3**
  * Conan version: **conan 1.37.0**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```
conan install qt/5.15.2@ -o qt:qtmultimedia=True -o qt:qtsvg=True --build=qt --build=missing
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: 
        ConanException: qt/5.15.2 package_info(): Package require 'openal' not used in components requires


```

</details>

**Comment by Renari** [comment]
This is odd, since this seems like it should be a simple fix, simply adding `openal::openal` on the following line.

https://github.com/conan-io/conan-center-index/blob/9f32bf3f48411fd91680ca0190317b3a7126f8b1/recipes/qt/5.x.x/conanfile.py#L971

However the issue persists even after specifying openal as a component requires for qtmultimedia.

**Comment by ericLemanissier** [comment]
the actual fix should be to add `openal::openal` on this line, the recipe names are all lower case on CCI.

**Comment by Renari** [comment]
> the actual fix should be to add `openal::openal` on this line, the recipe names are all lower case on CCI.

I had tried this and it didn't seem to work, after wiping my cache though it did work.

**Comment by Renari** [comment]
#5949

**Comment by ericLemanissier** [comment]
can this be closed now that #5949 is merged?

**Comment by Renari** [comment]
The g++ issues mentioned in that PR still occur.

**Comment by ericLemanissier** [comment]
Ok, it's a different issue then. Can you please try this suggestion https://github.com/conan-io/conan-center-index/pull/5691#issuecomment-864899507 ?

**Comment by Renari** [comment]
That appears to work.
