### ISSUE TITLE
[question] tbb: shouldn't tbb_proxy be also removed from package_id?

### ISSUE THREAD

**Issue by forthib** [conan-io/conan-center-index#5939]
Hello,

In tbb recipe, there are two options 'tbbmalloc' and 'tbbproxy' that provide additional libraries from tbb in package_info.
Since 'tbbmalloc' is not used during build time, it is also not used in package_id (del self.info.options.tbbmalloc).
Shouldn't '**tbb_proxy**' be also removed from package_id? There is a line "del self.info.options.**tbbmalloc_proxy**", is it a typo?

Thanks!

**Comment by SpaceIm** [comment]
Yes it's a typo, it should be `del self.info.options.tbbproxy`
