### ISSUE TITLE
[package] ninja/1.9.0: Missing windows binaries

### ISSUE THREAD

**Issue by bfairservice-gt** [conan-io/conan-center-index#5948]
ninja/1.9.0 has no prebuilt windows binaries.  

I notice the recipe was changed recently: https://github.com/conan-io/conan-center-index/pull/5897

In that MR, conan-center-bot said that all the builds passed successfully but in the logs the windows builds indicated `INVALID_CONFIGURATION`.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ninja/1.9.0**
  * Operating System+version: **Microsoft Windows 10 Enterprise 10.0.18363 N/A Build 18363**
  * Compiler+version: **Visual Studio 16**
  * Conan version: **conan 1.37.0**
  * Python version: **Python 3.9.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
`conan install ninja/1.9.0@`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
WARN: Remotes registry file missing, creating default one in C:\Users\vagrant\.conan\remotes.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ninja/1.9.0: Not found in local cache, looking in remotes...
ninja/1.9.0: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.10k]
Downloading conanfile.py completed [2.55k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
ninja/1.9.0: Downloaded recipe revision 0
Installing package: ninja/1.9.0
Requirements
    ninja/1.9.0 from 'conancenter' - Downloaded
Packages
    ninja/1.9.0:0a420ff5c47119e668867cdb51baff0eca1fdb68 - Missing

Installing (downloading, building) binaries...
ERROR: Missing binary: ninja/1.9.0:0a420ff5c47119e668867cdb51baff0eca1fdb68

ninja/1.9.0: WARN: Can't find a 'ninja/1.9.0' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=16, os=Windows
- Options:
- Dependencies:
- Requirements:
- Package ID: 0a420ff5c47119e668867cdb51baff0eca1fdb68

ERROR: Missing prebuilt package for 'ninja/1.9.0'
Try to build from sources with '--build=ninja'
Use 'conan search <reference> --table table.html'
Or read 'http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

</details>

**Comment by SpaceIm** [comment]
@jgsogo Could it come from these lines https://github.com/conan-io/conan-center-index/blob/1e261e6f7f088cb036cacbe370a177f9cb09fee5/recipes/ninja/1.9.x/conanfile.py#L21-L23N, due to the fact that it is run first on a Linux machine?

**Comment by jgsogo** [comment]
Yes. IMHO it is a bug on the implementation of the `cross_building` function, it cannot assume settings from the running machine. I have stumbled over this stone, and it will not be the last time. 😓 

I'll create PR and review some of the latest merges.

Thanks!

**Comment by jgsogo** [comment]
Let's wait for the CI, but I think this is the proper fix: https://github.com/conan-io/conan-center-index/pull/5951/files
