### ISSUE TITLE
[request] arrow/4.0.1

### ISSUE THREAD

**Issue by xanderdunn** [conan-io/conan-center-index#5970]
### Package Details
  * Package Name/Version: **arrow/4.0.1**
  * Changelog: **https://github.com/apache/arrow/blob/master/CHANGELOG.md**

The current arrow version in conan is several versions old at 2.0.0.

**Comment by theirix** [comment]
More than that, 5.0.0 was released a few days ago

**Comment by anders-wind** [comment]
And now 6.0.0 and 6.0.1

**Comment by theirix** [comment]
Very swift arrow! 😄
