### ISSUE TITLE
[service] forcing c++20 with "tools.check_min_cppstd(self, "20")" leads to "Zero packages generated"

### ISSUE THREAD

**Issue by werto87** [conan-io/conan-center-index#5981]
Hi, I am trying to add a package which uses c++20 features. "https://github.com/conan-io/conan-center-index/pull/5979"
When I set "tools.check_min_cppstd(self, "20")".
I get an error:
"Zero packages generated. Looks like all configurations have been discarded by ConanInvalidConfiguration exceptions."
How to add a c++20 only package to conan center?

**Comment by SpaceIm** [comment]
`tools.check_min_cppstd(self, "20")` checks compiler.cppstd in profile, or if not set, default cppstd of compiler.

Profiles in CCI don't set compiler.cppstd, and default C++ standard of current compiler is not C++20.

Therefore, you muste use `tools.check_min_cppstd(self, "20")` only if `compiler.cppstd` is set:

```python
def validate(self):
    if self.settings.compiler.get_safe("cppstd):
        tools.check_min_cppstd(self, "20")
```

 and inject at least C++20 standard (usually underlying build files of the libraries take care of that).

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-is-a-toolscheck_min_cppstd-call-not-enough

**Comment by werto87** [comment]
Thank you! Now I understand the problem.
