### ISSUE TITLE
[service] Add status badge for CI status

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#60]
To help us debug your issue please explain:

Other CI services, like Travis, have a hotsite for status and also a badge using semaphore lights.

We could add a badge on README file with current CI status, not about if all builds are okay, but about Jenkins health, like:

GREEN: "all good, go ahead!"
YELLOW: "we are operating with less capacity"
RED: "we are under maintenance right now"

**Comment by danimtb** [comment]
I thinks this definitely something to add in the future. Something similar to a status page. I think the badge thing is a good idea

**Comment by uilianries** [comment]
Closing this one, because we can not generate an embedded badge from the status page, it only provides an embedded java script. 

https://aui.atlassian.com/aui/7.8/docs/badges.html
