### ISSUE TITLE
[request] xorstr/0.0.1

### ISSUE THREAD

**Issue by saracen24** [conan-io/conan-center-index#6022]
### Package Details
  * Package Name/Version: **xorstr/0.0.1**
  * Website: **https://github.com/JustasMasiulis/xorstr/blob/master/README.md**
  * Source code: **https://github.com/JustasMasiulis/xorstr**

### Description Of The Library / Tool
A heavily vectorized c++17 compile time string encryption.

**Comment by SpaceIm** [comment]
This lib is in CCI: https://github.com/conan-io/conan-center-index/tree/master/recipes/xorstr

**Comment by saracen24** [comment]
> This lib is in CCI:
> https://github.com/conan-io/conan-center-index/tree/master/recipes/xorstr
> https://conan.io/center/xorstr

I have been waiting for a package for a long time, it turns out you have already added it recently. Thanks!
