### ISSUE TITLE
[question] how to use qt/5.15.2@ recipe?

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#6024]
I am trying to switch from the obsolete bincrafters recipe to qt/5.15.2@
As starting point, I take a test_package/conanfile.py

There is a "qt" generator used
> generators = "qt", "cmake", "cmake_find_package_multi", "qmake"

If I try to use this generator in my recipe, I get the following error:

```ERROR: Invalid generator 'qt'. Available types: txt, gcc, compiler_args, cmake, cmake_multi, cmake_paths, cmake_find_package, cmake_find_package_multi, qmake, qbs, scons, visual_studio, visual_studio_multi, visual_studio_legacy, xcode, ycm, virtualenv, virtualenv_python, virtualbuildenv, virtualrunenv, boost-build, pkg_config, json, b2, premake, make, deploy, markdown, CMakeToolchain, CMakeDeps, MSBuildToolchain, MesonToolchain, MSBuildDeps, QbsToolchain, msbuild, VirtualEnv, AutotoolsDeps, AutotoolsToolchain, AutotoolsGen, BazelDeps, BazelToolchain```

I use
> Conan version 1.37.2

Without this generator, I get the following error in both test_package and in my recipe:

``` CMake Error at CMakeLists.txt:95 (find_package):
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.```

**Comment by ericLemanissier** [comment]
These errors are unexpected: [`"qt" generator should be available`](https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/5.x.x/test_package/conanfile.py#L10) and [`Qt5::foo` targets should be available](https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/5.x.x/test_package/CMakeLists.txt#L23)
Can you please send your conanfile, profile, the command you are executing, and the full output ?

**Comment by AndreyMlashkin** [comment]
I have cleaned the local cache and it seems, the problem is gone, thank you!

**Comment by AndreyMlashkin** [comment]
I have another issue, not really related:
is there already support for Qt5:X11Extras module?

**Comment by ericLemanissier** [comment]
the module can be built with option `-o qt:qtx11extras=True`, but it currently be consumed only from qmake projects because the recipe does not yet create the cmake targets for this module

**Comment by AndreyMlashkin** [comment]
Thanks a lot!

**Comment by AndreyMlashkin** [comment]
I have opened a PR about adding x11 extras
https://github.com/conan-io/conan-center-index/pull/6030
