### ISSUE TITLE
[package] itk/all: ITK_USE_FILE isn't present

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan-center-index#6037]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **itk/all**

itk package doesn't provide ITK_USE_FILE that is common for ITK users. Example of such usage with components:
https://github.com/SuperElastix/elastix/blob/2f51507f03fc7527c4471a8e044d6be2f195dd4f/CMakeLists.txt#L32-L65

**Comment by SpaceIm** [comment]
I've added components to itk recipe in https://github.com/conan-io/conan-center-index/pull/9237.
But I've not added `ITK_USE_FILE` variable. It could be defined in a custom module file.
