### ISSUE TITLE
[platform.interfaces] CRLF / LF problems using git

### ISSUE THREAD

**Issue by alejandro-colomar** [conan-io/conan-center-index#6057]
Hi,

Today I checked out your master branch since a few weeks ago.  In the checkout, git gave some warnings about CRLF (probably code edited in Windows).  I'll show you, just that you know and decide what to do:

```
warning: CRLF will be replaced by LF in recipes/platform.interfaces/all/conandata.yml.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in recipes/platform.interfaces/all/conanfile.py.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in recipes/platform.interfaces/config.yml.
The file will have its original line endings in your working directory
```

And then I have these files changed:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   recipes/platform.interfaces/all/conandata.yml
	modified:   recipes/platform.interfaces/all/conanfile.py
	modified:   recipes/platform.interfaces/config.yml
```

Seeing the diff, I can also see some trailing spaces, something that I had already seen previously, BTW.

You may want to do `find * -type f | xargs dos2unix`,
and then maybe `find * -type f | xargs sed -i 's/\s*$//'`.

**Comment by uilianries** [comment]
@alejandro-colomar Thank you for reporting. Indeed it caused a little bit of trouble, but should be fixed now by #6055
