### ISSUE TITLE
[question] What are the requirements for package platform support?

### ISSUE THREAD

**Issue by helmesjo** [conan-io/conan-center-index#6088]
**Just out of curiosity:** 
If I make a package for `libA` which supports Windows, Linux, Macos, but my conan package/recipe only supports say Linux, what are the guidelines regarding this? Is it fine and just expected to be followed up "on demand", or is it a "requirement" that all platforms are resolved before it gets merged? Obviously this is biased towards the ones that are part of the build matrix.

I'm asking because I've seen this a couple of times where a package exist for some cross-platform lib, but when using it one realizes it's only available for a subset of the platforms. 
**I guess the main question is**, should I open an issue whenever I stumble upon this situation (granted I don't just try to solve it myself)?

This time it's specifically `libtins`, which requires `winpcap` on windows _which coincidentally_ has no conan package yet (only one on bincrafters).

**Comment by SpaceIm** [comment]
I guess you can open an issue for `libtins`.
Basically, it should require `libpcap` on non-Windows platform, and raise on Windows for the moment until availability of`winpcap` in CCI.

**Comment by helmesjo** [comment]
Ok, thanks!
