### ISSUE TITLE
[package] libnghttp2/1.43.0: /usr/lib/cmake/boost* related files override the Conan provided BOOST_ROOT

### ISSUE THREAD

**Issue by ghost** [conan-io/conan-center-index#6120]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libnghttp2/1.43.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 7/11**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)

conan install .

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
[  3%] Built target url-parser
[  3%] Built target llhttp
[ 21%] Built target nghttp2
[ 23%] Built target deflatehd
[ 25%] Built target inflatehd
[ 32%] Built target nghttp
[ 39%] Built target nghttpd
[ 44%] Built target h2load
[ 76%] Built target nghttpx_static
[ 77%] Built target nghttpx
make[2]: *** No rule to make target '/usr/local/lib/libboost_system.so.1.76.0', needed by 'lib/libnghttp2_asio.so.1.0.0'.  Stop.
CMakeFiles/Makefile2:672: recipe for target 'source_subfolder/src/CMakeFiles/nghttp2_asio.dir/all' failed
make[1]: *** [source_subfolder/src/CMakeFiles/nghttp2_asio.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

```

</details>

Instead of linking with the Boost libraries defined as a dependency, it attempts to link with the user local installation; the reason is that the Boost CMake related modules under /usr/local/lib/cmake/* override the BOOST_ROOT provided by the Conan package. Removing them remedied my issue but it is not the solution.

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `libnghttp2/1.43.0` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported. 
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
