### ISSUE TITLE
[question] Why are some packages only provided with system requirements

### ISSUE THREAD

**Issue by QShen3** [conan-io/conan-center-index#6179]
For example, the OpenGL and X.Org
https://conan.io/center/opengl
https://conan.io/center/xorg

Are there some licence issues or just technique issues?

**Comment by ericLemanissier** [comment]
please refer to https://github.com/conan-io/conan-center-index/issues/641

**Comment by QShen3** [comment]
@ericLemanissier Thanks for your info. Now I know they are ''proxy recipes''.
