### ISSUE TITLE
[package] <CPR>/<1.6.2>: with_ssl=winssl does not work

### ISSUE THREAD

**Issue by ejb1123** [conan-io/conan-center-index#6185]
### Package and Environment Details
  * Package Name/Version: **cpr/1.6.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 16 (2019)**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.9.5**

### Conan profile
```
Configuration for profile windows-x86-static-release:

[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86
compiler=Visual Studio
compiler.version=16
build_type=Release
compiler.runtime=MT
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce

Create a conanfile.txt as follows  
```INI
[requires]
wxwidgets/3.1.4@bincrafters/stable
cpr/1.6.2
[options]
wxwidgets:shared=False
cpr:shared=False
cpr:with_ssl=winssl
libcurl:with_ssl=schannel
[generators]
cmake
```
Then run `conan install .  --build=missing --profile windows-x86-static-release`

This ends up returning 

```
RROR: There are invalid packages (packages that cannot exist for this configuration):
cpr/1.6.2: Invalid ID: cpr requires libcurl to be built with the option with_ssl='None'.
```
This looks to have been caused by 9447db01c33789221c82a977726f697114e0b05c
</details>

**Comment by SSE4** [comment]
try changing `libcurl:with_ssl=schannel` into `libcurl:with_ssl=winssl` (in your profile)
