### ISSUE TITLE
[package] msys/cci.latest as build dependency for Windows x86

### ISSUE THREAD

**Issue by stefan-floeren** [conan-io/conan-center-index#6190]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **msys/cci.latest**, **icu/69.1**
  * Operating System+version: **Windows 10 Pro 21H1 64-bit**
  * Compiler+version: **Visual Studio 2019 16.10.3**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.9**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
[options]
[build_requires]
[env]
```

### Problem description

With #5953, _icu_ got updated to use the new package version for _msys_. In general, this is a good change, as the old package was failing more often than not.

Unfortunately, this version has one drawback:

> 32-bit MSYS2 no longer supported

This now prevents ICU from building for 32-bit versions of Windows completely:

```
msys2/cci.latest: Invalid ID: Only Windows x64 supported
```

### Expected behavior

MSYS is only used as a build dependency and is not affecting the final results for ICU. After some testing, this combination works fine for x86 builds, as long as the build platform (`arch_build`) is x64.

In my opinion, the test in the [conanfile.py](https://github.com/conan-io/conan-center-index/blob/01de79a37d5906cf935fbebb0c73853cc7d55187/recipes/msys2/all/conanfile.py#L63) should be changed from `arch` to `arch_build`, although this only works if MSYS is a build dependency and not a direct one.

So, before opening a merge request, some questions:
* Is it possible to detect if a package is used as a build or direct dependency?
* Is there a way to answer the same question for CCI?
* Is this the way to go or is there a different solution?

**Comment by ericLemanissier** [comment]
does it fix the problem if you use 2 profiles instead of foo_build settings, as described in https://docs.conan.io/en/latest/reference/profiles.html#build-profiles-and-host-profiles ?

**Comment by stefan-floeren** [comment]
Using 2 profiles seems to work after a quick test. As this is an experimental feature, is there some information if there any major changes to be expected or when it will be stabilized?

**Comment by prince-chrismc** [comment]
IMHO the "experimental" status stays for a very long time... the two profile approach is being deployed at scale in CCCI for the M1 effort but the Conan team. I think it reasonable to say that only minor changes would be considered

**Comment by stefan-floeren** [comment]
Then lets hope you're right.

**Comment by cgri** [comment]
@stefan-floeren Did you consider to open a pull request anyway? Wouldn't your suggested change fix actually the issue? Sorry for pushing this old issue, but I just stumbled about it.

**Comment by shijunz** [comment]
> Using 2 profiles seems to work after a quick test. As this is an experimental feature, is there some information if there any major changes to be expected or when it will be stabilized?

could you share me how to use 2 profiles, i am trying to build it windows on arm.

**Comment by stefan-floeren** [comment]
You need 2 profiles: a build profile (the machine you run the build on) and a host profile (the machine you want to run the result on).

In the first build profile, set arch to x86_64, and in the host you set arch to arm*. Then select both during install:

`conan install --profile:build <BUILD_PROFILE> --profile:host <HOST_PROFILE> ...`
