### ISSUE TITLE
[package] glad/0.1.34: Builds require CMake, but it is missing from `build_requires`

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan-center-index#6195]
The title mainly covers it: if CMake is not available on the building system (easily the case in CI), any attempt to build  glad/0.1.34 fails with 

    glad/0.1.34: Calling build() 'cmake' is not recognized as an internal or external command, operable program or batch file.

Which makes sense, as CMake is not listed in `build_requires`.

**Comment by SpaceIm** [comment]
All CCI recipes assume that CMake is installed on the build machine. You can add cmake recipe to build requirements of your CI profile.

**Comment by Adnn** [comment]
Okay, thank you for this information. (It is somewhat surprising, because at the same time `cmake` is a recipe in CCI).

**Comment by SpaceIm** [comment]
Here is the rational: https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-recipes-that-use-build-tools-like-cmake-that-have-packages-in-conan-center-do-not-use-it-as-a-build-require-by-default
