### ISSUE TITLE
[request] libraries needed to update conan/examples: emsdk, imgui, glfw, glew, folly

### ISSUE THREAD

**Issue by czoido** [conan-io/conan-center-index#620]
We are in the process of updating the [conan examples repo](https://github.com/conan-io/examples) to use recipes from conan center index and updating Windows configurations to vs 2019 but there are some libraries missing: **emsdk**, **imgui**, **glfw**, **glew**, **folly**
Without them, the update to c3i is not possible and [the ci fails](https://github.com/conan-io/examples/pull/39).

**Comment by czoido** [comment]
@uilianries, @SSE4, could you please have a look at these recipes, to see if they can be included in c3i so we can update the examples repository and Conan documentation soon?

**Comment by ericLemanissier** [comment]
glfw and glew require https://github.com/bincrafters/conan-mesa and https://github.com/bincrafters/conan-x11/, the main problem with conan-x11 is that it's a "meta-recipe" which generates a lot of packages (49), so it does not fit the CCI structure. Also, it does not have proper tests currently.
imgui seems easily transferable. folly can be transferred once we transfer libiberty

**Comment by SSE4** [comment]
I think we have most of the things mentioned, probably except emsdk

**Comment by solvingj** [comment]
@SSE4 do you see any issue with submitting emscripten_installer to CCI?  

It's also needed here:

https://github.com/conan-io/conan/issues/7816

**Comment by SSE4** [comment]
sorry, completely missed the question :)
late is better than never, so answering
I personally don't see any problem with emsdk
in fact, we already have PR submitted: https://github.com/conan-io/conan-center-index/pull/6163
the only blocking/tentative thing is that emsdk downloads its own installations of `nodejs`, `python`, etc.
this might be tricky to bypass, or we may just agree to live with it for now

**Comment by SSE4** [comment]
already in CCI:
```
glew/2.1.0
glew/2.2.0
imgui/1.74
imgui/1.75
imgui/1.76
imgui/1.77
imgui/1.78
imgui/1.79
imgui/1.80
imgui/1.81
imgui/1.82
imgui/1.83
imgui/1.84.1
imgui/1.84.2
glfw/3.3.2
glfw/3.3.3
glfw/3.3.4 
folly/2019.10.21.00
folly/2020.08.10.00
```
so `emsdk` is the last nail

**Comment by jgsogo** [comment]
I'm adding the _closes_ keyword from PR #6163 😃
