### ISSUE TITLE
[package] qt/6.1.2: static build missing windows platform plugin

### ISSUE THREAD

**Issue by srnwk** [conan-io/conan-center-index#6227]
### Package and Environment Details
  * Package Name/Version: **qt/6.1.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 19.29**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.9.5**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.runtime=MDd
build_type=Debug
[options]
[conf]
[build_requires]
[env]
```

### Description

Building a simple "hello world" program using Qt6::Widgets fails to run when linking the static qt/6.1.2 libraries:

```
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
Using Qt6's own generated cmake targets, these plugins are linked automatically when consuming e.g. Qt6::Widgets.

I've tried a few things to try to resolve this manually,
* linking the Qt6::qtQWindowsIntegrationPlugin target explicitly -- no change
* using `qt6_import_plugins(example INCLUDE qwindows)` -- results in 
  ```
  Warning: plug-in qwindows is not known to the current Qt installation
  ```
* importing the plugin from a source file:
  ```cpp
  #include <QtPlugin>

  Q_IMPORT_PLUGIN(qwindows);
  ```
  result:
  ```
  LNK2019: unresolved external symbol "struct QStaticPlugin const __cdecl qt_static_plugin_qwindows(void)
  ```
  (though I'm not sure I have the plugin name right).

### Steps to reproduce 
I've created a small repro here: <https://github.com/srnwk/conan-qt-static-repro>

Assuming the above profile is called msvc-debug, and running in a suitable vcvarsall.bat environment:
```
git clone https://github.com/srnwk/conan-qt-static-repro
cd conan-qt-static-repro
conan install . -if build/conan -pr msvc-debug
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug
ninja -C build
build/example.exe
```

**Comment by SpaceIm** [comment]
I'm working on this, many plugins are missing in `package_info()` of qt 6.x.x recipe.
