### ISSUE TITLE
[package] assimp/5.0.0: build fail when all exporters are disabled

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#623]
### Package and Environment Details
  * Package Name/Version: **assimp/5.0.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.7.1**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce

Turn off all exporters like options

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
C:\Users\username\.conan\data\assimp\5.0.0\_\_\build\59f577e4e0c49ac4eef100882845fae49c364584\source_subfolder\code\Common\Exporter.cpp(109,29): error C2466: cannot allocate an array of constant size 0 [C:\Users\username\.conan\data\assimp\5.0.0\_\_\build\59f577e4e0c49ac4eef100882845fae49c364584\build_subfolder\source_subfolder\code\assimp.vcxproj]
```

</details>

### Fix:

Apply a patch to fix `code/Common/Exporter.cpp`

See https://github.com/assimp/assimp/pull/2759

**Comment by uilianries** [comment]
Well, we can drop it by raising a ConanInvalidConfiguration and wait for the next release, or apply that patch. Usually we use the first option.

**Comment by Brouilles** [comment]
Same problem here.
