### ISSUE TITLE
[package] qt/5.15.2: Building with qtwinextras doesn't create target Qt5::WinExtras

### ISSUE THREAD

**Issue by obsgolem** [conan-io/conan-center-index#6238]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 16.0**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.8.5**

  ### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Build qt using the following conanfile:
```
[requires]
qt/5.15.2

[generators]
cmake_find_package_multi

[options]
qt:qtwinextras=True

[imports]
bin, *.dll -> ./bin
```
Examine `Qt5Config.cmake`. Note that there is no target/component Qt5::WinExtras. I believe this is caused by a missing call to `_create_module`.

**Comment by ericLemanissier** [comment]
Could you please try with https://github.com/conan-io/conan-center-index/pull/6235 ?

**Comment by obsgolem** [comment]
I would like to, but I am new to conan and am not entirely sure how to. Could you walk me through it or point me to a guide?

**Comment by obsgolem** [comment]
Appears to work on my machine
