### ISSUE TITLE
[package] qt/5.15.2: Could not find a package configuration file provided by "Qt5" with any of   the following names

### ISSUE THREAD

**Issue by xahon** [conan-io/conan-center-index#6251]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 16**
  * Conan version: **conan 1.36.0**
  * Python version: **Python 3.9.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
1. Copy folder with contents  
https://github.com/conan-io/conan-center-index/tree/82a909e608c8baf8a5d626488db74cc602e300e1/recipes/qt/5.x.x/test_package
2. Run conan install
3. Configure cmake
4. Error

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```
line 12 is `https://github.com/conan-io/conan-center-index/blob/82a909e608c8baf8a5d626488db74cc602e300e1/recipes/qt/5.x.x/test_package/CMakeLists.txt#L12`

</details>

**Comment by xahon** [comment]
Might be related https://github.com/conan-io/conan-center-index/issues/4529

**Comment by ericLemanissier** [comment]
Can you please give us more details on how you invoke conan (which command line arguments), and from which folder you invoke cmake. you are probably missing the "cmake_find_package_multi" generator

**Comment by xahon** [comment]
@ericLemanissier yes, i use `cmake` generator instead of `cmake_find_package_multi`. I'm going to try it

**Comment by xahon** [comment]
thanks, changing `generators` from `generators = "cmake"` to `generator = "cmake_find_package_multi"` in my root `conanfile.py` resolved the issue
