### ISSUE TITLE
[center.conan.io] Need to update link

### ISSUE THREAD

**Issue by Dattax** [conan-io/conan-center-index#626]
On Monday Jan. 13th, we would like to update all links to the new ConanCenter. Can you change the description on this conan-center-index on Monday?. 

Current: Recipes for the conan-center repository https://bintray.com/conan/conan-center

New: Visit ConanCenter at https://conan.io/center

**Comment by Dattax** [comment]
Let's update this today :)

**Comment by memsharded** [comment]
Already changed.

**Comment by Dattax** [comment]
It's still pointing to bintray...it still says "Recipes for the conan-center repository https://bintray.com/conan/conan-center"

This is on github conan-center-index page
