### ISSUE TITLE
[openssl] openssl/1.1.1d: TypeError in dep zlib/1.2.11

### ISSUE THREAD

**Issue by fredrikslattman** [conan-io/conan-center-index#628]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.11**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **clang 9.0.0**
  * Docker image: **ubuntu:18.4**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.6.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=9
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```python
# conanfile.py
    def requirements(self):
        self.requires("asio/1.13.0")
        self.requires("openssl/1.1.1d")
        self.requires("http-parser/2.8.1@bincrafters/stable")
        self.requires("protobuf/3.9.1@bincrafters/stable")
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>
```
zlib/1.2.11: Retrieving package 7c292f54b7e6c224f121c640404bf7fbbeb41a8f from remote 'conan-center' 
Downloading conanmanifest.txt


Downloading conaninfo.txt


Downloading conan_package.tgz




zlib/1.2.11: Package installed 7c292f54b7e6c224f121c640404bf7fbbeb41a8f
zlib/1.2.11: Downloaded package revision a8ecd478273469e4149f67e3c79f4879
ERROR: zlib/1.2.11: Error in package_info() method, line 166
	self.cpp_info.names["cmake_find_package"] = "ZLIB"
	TypeError: '_CppInfo' object does not support item assignment
```
</details>

---------------------------
This started happening with a lot of packages since the `1.21.0` update. It's happening only during the `conan create` command. I'm only experiencing these issues on the "public" packages, doesn't happen with the bincrafters packages.

**Comment by Croydon** [comment]
This should only happen with older Conan versions. Are you absolutely sure that you run Conan 1.21.0?

**Comment by fredrikslattman** [comment]
My mistake, one of the build bots was not on the latest version it seems. I'll close the ticket.
