### ISSUE TITLE
[request] Add appache arrow library

### ISSUE THREAD

**Issue by mrboojum** [conan-io/conan-center-index#63]
I'm requesting the apache arrow library version 0.14.1 to be added:

Link to the website: https://arrow.apache.org/docs/index.html
There is a slightly outdated recipe here: https://github.com/FiligreeTech/conan-arrow

**Comment by danimtb** [comment]
Thanks for the request! Maybe the original author of the recipe @FiligreeTech wants to contribute it to this repo or give us permission to contribute the recipe ourselves 😄

**Comment by Croydon** [comment]
I'm thinking that recipe requests should probably be continued on the wishlist and not here 🤔 

https://github.com/conan-io/wishlist/issues

**Comment by danimtb** [comment]
Not really. We will gradually redirect the whislist issues to this one.

Check the readme:

> Request a new library to be added:
> - Use the [request] tag in the title of the issue to help identifying them.
> - Indicate the name and the version of the library you would like to have in the repository.

**Comment by Croydon** [comment]
Hm, okay. This issue tracker might become quickly crowded and hard to overview if we add everything here.

It will be like Bincrafters + conan-community + wishlist + service questions, problems and requests combined, and will likely get more attention than all these former issue trackers. 🤔

**Comment by uilianries** [comment]
@danimtb what about moving withlist to here?

**Comment by danimtb** [comment]
> @danimtb what about moving withlist to conan-center-index issues?
@uilianries We will gradually redirect the wishlist issues to this repository, but we are not going to move them all at once. Probably we will block new issues but keep the conversations of existing issues open. In the future, we will evaluate what to do: close wishlist repo, move the issues....

**Comment by BrunoFiligree** [comment]
Hi, late to this party. We are happy to contribute our recipe, which we have updated recently.
