### ISSUE TITLE
[question] qt/5.15.2: How can I use/call the qmake binary from the qt package inside another recipe?

### ISSUE THREAD

**Issue by bfederau** [conan-io/conan-center-index#6308]
I would like to use qmake inside another recipe with e.g. self.run('qmake') but the qt bin/ folder isn't appended to the PATH variable like in other recipes

```
bin_path = os.path.join(self.package_folder, "bin")
self.output.info("Appending PATH env var with : {}".format(bin_path))
self.env_info.PATH.append(bin_path)
```

Is there any other way to run the qmake from the qt package inside another recipe?

**Comment by ericLemanissier** [comment]
it should work with `run_environment=True` argument https://docs.conan.io/en/latest/reference/conanfile/other.html#running-commands

**Comment by bfederau** [comment]
Yes, with `run_environment=True` it is working. Thanks.
