### ISSUE TITLE
[package] qt/5.15.2: Could not find the Qt platform plugin "xcb" in ""

### ISSUE THREAD

**Issue by Renari** [conan-io/conan-center-index#6318]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Linux Mint 20.2**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.8.10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)
1. Build an application that depends on qt
2. Attempt to run the application, you'll receive the error:
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by Jihadist** [comment]
Same problem as reported here https://github.com/conan-io/conan-center-index/pull/6029

**Comment by obsgolem** [comment]
This occurs on windows when statically linking as well. I belive this is due to missing a call to `_create_plugin` for the various platform plugins.

**Comment by Jihadist** [comment]
I tried to build https://github.com/conan-io/conan-center-index/pull/6029 with https://github.com/conan-io/conan-center-index/pull/7194 and 
```
#include <QtPlugin>
Q_IMPORT_PLUGIN (QWindowsIntegrationPlugin)
```
because without I had "could not find the Qt..." error. But I had error again 
```
test_package.obj : error LNK2019: unresolved external symbol "struct QStaticPlugin const __cdecl qt_static_plugin_QWindowsIntegrationPlugin(void)" (?qt_static_plugin_QWindowsIntegrationPlugin@@YA?BUQStaticPlugin@@XZ) referenced in function "void __cdecl `dynamic initializer for 'staticQWindowsIntegrationPluginInstance''(void)" (??__EstaticQWindowsIntegrationPluginInstance@@YAXXZ) [C:\Users\user\source\repos\conan-center-index\recipes\qcustomplot\all\test_package\build\ecbfb49a4e2ea8618319be5f9e02c8e0621391fb\test_package.vcxproj]
C:\Users\user\source\repos\conan-center-index\recipes\qcustomplot\all\test_package\build\ecbfb49a4e2ea8618319be5f9e02c8e0621391fb\Release\test_package.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\user\source\repos\conan-center-index\recipes\qcustomplot\all\test_package\build\ecbfb49a4e2ea8618319be5f9e02c8e0621391fb\test_package.vcxproj]
```
Should I add something more to CMakeLists for test package?

**Comment by ericLemanissier** [comment]
> Should I add something more to CMakeLists for test package?

yes, you also have to link to ` Qt6::QWindowsIntegrationPlugin` target

**Comment by Jihadist** [comment]
> 
> 
> > Should I add something more to CMakeLists for test package?
> 
> yes, you also have to link to ` Qt6::QWindowsIntegrationPlugin` target

Maybe recipe should import platform independent integration plugin? For example `Qt6 :: QIntegrationPlugin`
Because if not, all test packages linked against qt will contain a lot of platform dependent if else if.

**Comment by ericLemanissier** [comment]
I'm trying to come up with a solution on https://github.com/conan-io/conan-center-index/pull/7378, I'll reopen the PR when I have something which compiles on my machine
