### ISSUE TITLE
[bug] installing autoconf/2.71 fails when using -pr:b flag

### ISSUE THREAD

**Issue by serghov** [conan-io/conan-center-index#6341]
### Environment Details (include every applicable attribute)
  * Operating System+version: docker ubuntu:18.04
  * Compiler+version: gcc version 7.5.0
  * Conan version: version 1.38.0
  * Python version: Python 3.6.9

Building autoconf/2.71 with the following command fails;
```conan install autoconf/2.71@ --build  -pr default -pr:b default```

The default profile is generated by conan and is
```[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

Build error is;
```
checking for GNU M4 that supports accurate traces... configure: error: no acceptable m4 could be found in $PATH.
GNU M4 1.4.6 or later is required; 1.4.16 or newer is recommended.
GNU M4 1.4.15 uses a buggy replacement strstr on some systems.
Glibc 2.9 - 2.12 and GNU M4 1.4.11 - 1.4.15 have another strstr bug.
```
When building without the ```-pr:b default``` flag, the build succeeds;
```conan install autoconf/2.71@ --build  -pr default```

After inspecting conan source code the issue seems to be [here](https://github.com/conan-io/conan/blob/b61f761e8d8cc092976a7c672037efefe1fa6549/conans/client/installer.py#L617), because ```env_info``` of ```m4``` package is not being propagated to ```autoconf```. Adding ```conan_file.deps_env_info.update(n.conanfile.env_info, n.ref.name)``` in the linked code fixes the issue.

**Comment by madebr** [comment]
I've opened #6357 but it does not fix the problem.

I've created a little reproducer at the bottom of this comment.
The `SOME_EXE` environment variable should be available in both test packages, but it is not.
Adding `some_exe` as a build requirement to the test package of `some_project` is not a satisfactory solution.

```sh
#!/bin/sh
set -e

mkdir -p some_exe/test_package
mkdir -p some_project/test_package

cat >some_exe/conanfile.py <<EOF
from conans import ConanFile


class SomeExeConanFile(ConanFile):
    name = "some_exe"
    version = "0.1"
    def source(self): pass
    def build(self): pass
    def package(self): pass
    def package_info(self):
        self.env_info.SOME_EXE = "/path/to/some_exe"
EOF

cat >some_exe/test_package/conanfile.py <<EOF
from conans import ConanFile
import os


class TestSomeExeConanFile(ConanFile):
    test_type = "build_requires"
    def build(self): pass
    def test(self):
        self.output.info("SOME_EXE={}".format(os.environ["SOME_EXE"]))
EOF

cat >some_project/conanfile.py <<EOF
from conans import ConanFile
import os


class SomeProjectConanFile(ConanFile):
    name = "some_project"
    version = "0.1"
    def source(self): pass
    def build(self): pass
    def package(self): pass
    def build_requirements(self):
        self.build_requires("some_exe/0.1")
    def requirements(self):
        self.requires("some_exe/0.1")
    def build(self):
        self.output.info("Test availability of SOME_EXE environment variable")
        self.output.info("SOME_EXE -> {}".format(os.environ["SOME_EXE"]))
EOF

cat >some_project/test_package/conanfile.py <<EOF
from conans import ConanFile
import os


class TestSomeExeConanFile(ConanFile):
    test_type = "build_requires"  # Change to "requires" or "build_requires" to see both error modes.
    def build(self): pass
    def test(self):
        # SOME_EXE environment should still be available when using some_project
        self.output.info("Test availability of SOME_EXE environment variable")
        self.output.info("SOME_EXE -> {}".format(os.environ["SOME_EXE"]))
EOF

conan remove -f some_exe
conan remove -f some_project
conan create some_exe some_exe/0.1@ -pr:b default64 -pr:h default64
conan create some_project some_project/0.1@ -pr:b default64 -pr:h default64
```

Replace `default64` with a profile for your system.
Mine is:
```
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=gcc
CXX=g++
AS=gcc
ASM=gcc
CFLAGS=-m64
CXXFLAGS=-m64
ASFLAGS=-m64
ASMFLAGS=-m64
LDFLAGS=-m64
```

**Comment by serghov** [comment]
Actually after thinking about this a bit more, I think the path should not be set and this is a correct behavior.
Instead the package should have m4 as both a requirement and build_requrement.
The idea is that you can not be sure that a binary built for host context can be executed in the build context. For instance if we are cross compiling, then the binary built for host context will have a completely different architecture from the build context. 
That is why you would need two versions of m4 in this case, one meant for the build context, and one meant for the host context to be used after the build is finished. And to achieve that, you would need to have m4 both as a requirement and a build_requrement.

**Comment by serghov** [comment]
@madebr I think the issue with adding env variables is mostly in the case of cross compilation. If we add anything executable to the $PATH or any other env variable in the host context that will lead to it being executed in the build context conan might end up trying to execute a file with the wrong architecture and failing.

**Comment by madebr** [comment]
@SpaceIm @prince-chrismc 
Can you take a look at https://github.com/conan-io/conan-center-index/issues/6341#issuecomment-880862257?
In the last weeks, you both did a lot of work about increasing cross compilation support.

The example is a reproducer of the problem with `autoconf`. `some_exe` is `m4` and `some_project` is `autoconf`.

**Comment by prince-chrismc** [comment]
I have no experience cross compiling :)

**Comment by nioncode** [comment]
I just built with `conan install . autoconf/2.71@ --build -pr default -pr:b default` and it worked fine. So I guess this issue can be closed or do you still have the same issue @serghov ?
