### ISSUE TITLE
[request] grpc: Add `shared` option to recipe

### ISSUE THREAD

**Issue by FMeinicke** [conan-io/conan-center-index#6382]
Hi,
I would like to use conan to manage all dependencies of my project. Since it's customary at my work to use shared libraries rather than linking everything statically I'd like to have all dependencies as well as the library that my project generates as shared libraries. The problem is that the grpc recipe does not provide the `shared` option to do so.

I managed to build grpc and all of its dependencies from source as shared libraries and I've been using these without any problems for over a year now.  
I also played around with the CCI recipe for grpc and simply added the `shared` option and tried to build a conan package from that recipe. Except for abseil every other dependency of grpc supports building with the `shared` option out of the box. Hence, to allow building grpc with the `shared` option the abseil recipe has to be changed as well (it also needs the `shared` option).

I would be happy to provide a PR to add this behaviour to grpc (and abseil for that matter). My question is if this should be one PR that modifies both recipes or would you rather have two PRs, one for each recipe (where the PR for abseil would have to be merged first since grpc depends on that change)?

**Comment by SpaceIm** [comment]
Why abseil would need to be shared if you want grpc shared?
Abseil build system doesn't support shared.

**Comment by FMeinicke** [comment]
> Why abseil would need to be shared if you want grpc shared?

Because I've had bad experiences with mixing static and shared libraries.

> Abseil build system files don't support shared.

As I said I managed to build grpc (and all of its third-party dependencies) from source as shared libraries. I.e. abseil *can* be built as shared libraries (and briefly looking at their CMake files confirms that they actually do support building shared):

https://github.com/abseil/abseil-cpp/blob/33541e751039a8c4bd3a395dd1a3a0928885814a/CMake/AbseilHelpers.cmake#L137-L141

**Comment by SpaceIm** [comment]
Indeed, you're right for abseil shared, I missed that. I don't know why it was not added in initial PR adding abseil in CCI.

**Comment by SpaceIm** [comment]
I've opened https://github.com/conan-io/conan-center-index/pull/6383 for abseil.

**Comment by FMeinicke** [comment]
Cool, thanks!

**Comment by SpaceIm** [comment]
Actually, shared was not supported in the "first version" (unofficial) added in conan-center-index. shared on Windows is slightly more complex. It produces only one dll, without a dedicated import library.

**Comment by FMeinicke** [comment]
@SpaceIm, did you have any luck with the abseil recipe? I noticed that the builds in #6383 failed.

**Comment by SpaceIm** [comment]
It fails for some versions yes, and didn't have the time to fix it.

for shared grpc, you can try https://github.com/conan-io/conan-center-index/pull/9044

**Comment by FMeinicke** [comment]
Awesome, I'll give #9044 a try. Thanks for all your work!
