### ISSUE TITLE
[package] zlib/1.2.11: can't compile with clang (not MSVC-clang)

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#6414]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.11**
  * Operating System+version: **Windows 10 docker**
  * Compiler+version: **clang 12**
  * Docker image: https://github.com/AndreyMlashkin/windows-clang-conan/blob/main/Dockerfile
  * Conan version: **conan 1.38.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.version=12.0
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CC=clang-cl
CONAN_CMAKE_GENERATOR=Ninja
CXX=clang-cl
```

### Steps to reproduce (Include if Applicable)
docker build .

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
conan install zlib/1.2.11@ --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.version=12.0
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CC=clang-cl
CONAN_CMAKE_GENERATOR=Ninja
CXX=clang-cl
zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.35k]
Downloading conanfile.py completed [5.94k]
Downloading conan_export.tgz completed [0.34k]
Decompressing conan_export.tgz completed [0.00k]
zlib/1.2.11: Downloaded recipe revision 0
Installing package: zlib/1.2.11
Requirements
    zlib/1.2.11 from 'conancenter' - Downloaded
Packages
    zlib/1.2.11:5448130be8147b3657e4a9b67d4df5c9629137b7 - Build

Installing (downloading, building) binaries...
Downloading conan_sources.tgz completed [1.14k]
Decompressing conan_sources.tgz completed [0.00k]
zlib/1.2.11: Configuring sources in C:\Users\ContainerAdministrator\.conan\data\zlib\1.2.11\_\_\source
Downloading zlib-1.2.11.tar.gz completed [593.46k]

zlib/1.2.11: Copying sources to build folder
zlib/1.2.11: Building your package in C:\Users\ContainerAdministrator\.conan\data\zlib\1.2.11\_\_\build\5448130be8147b3657e4a9b67d4df5c9629137b7
zlib/1.2.11: Generator cmake created conanbuildinfo.cmake
zlib/1.2.11: Calling build()
zlib/1.2.11:
zlib/1.2.11: ERROR: Package '5448130be8147b3657e4a9b67d4df5c9629137b7' build failed
zlib/1.2.11: WARN: Build folder C:\Users\ContainerAdministrator\.conan\data\zlib\1.2.11\_\_\build\5448130be8147b3657e4a9b67d4df5c9629137b7
ERROR: zlib/1.2.11: Error in build() method, line 75
        cmake.configure(build_folder=self._build_subfolder)
        ConanException: compiler.version setting required for vcvars not defined
```

</details>

**Comment by madebr** [comment]
I think you will have to bring this issue to the conan developers.

https://github.com/conan-io/conan-center-index/issues/6416 is releated.

It seems conan has 2 problems:
- clang-cl is not modeled by conan.
  * There is no `settings.compiler == "clang-cl"`
  * `self.settings.compiler=="clang"` has no option with e.g. `self.settings.compiler.frontend=="msvc"`.
  * There exists `self.settings.comipler.toolset -> "v141_clang_c2", "ClangCL"`.
     But is this about toolset?
- clang-cl detection on Windows is wrong for cmake:
    https://github.com/conan-io/conan/blob/6b4728b25625a0e350cb010bd78dc761fc747000/conans/client/build/cmake.py#L223

**Comment by ruilvo** [comment]
Raise this issue in the actual conan "program" repo.

**Comment by AndreyMlashkin** [comment]
Fixed
