### ISSUE TITLE
[package] qt/5.15.2: Building with qttools doesn't create target Qt5::windeployqt

### ISSUE THREAD

**Issue by obsgolem** [conan-io/conan-center-index#6421]
### Package and Environment Details (include every applicable attribute)
* Package Name/Version: qt/5.15.2
* Operating System+version: Windows 10
* Compiler+version: Visual Studio 16.0
* Conan version: conan 1.38.0
* Python version: Python 3.8.5

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Build qt using the following conanfile:
```
[requires]
qt/5.15.2

[generators]
cmake_find_package_multi

[options]
qt:qttools=True

[imports]
bin, *.dll -> ./bin
```
Examine conan_qt_executables_variables.cmake. Note that there is no target/component Qt5::windeployqt. I believe this is caused by windeployqt not being listed in `targets["Core"] = ["moc", "rcc", "qmake"]`.

**Comment by ericLemanissier** [comment]
Does this target exist in vanilla qt builds ?

**Comment by ruilvo** [comment]
If it exists, I'm not sure why I go trough this trouble:
```cmake
get_target_property(MOC_EXE Qt${QT_VERSION_MAJOR}::moc IMPORTED_LOCATION)
get_filename_component(QT_BIN_DIR "${MOC_EXE}" DIRECTORY)
set(QT_DEPLOY_TOOL "windeployqt")
find_program(DEPLOYQT_EXECUTABLE ${QT_DEPLOY_TOOL} HINTS "${QT_BIN_DIR}")
```

And in here: https://stackoverflow.com/a/41199492/5168563
They clearly suggest `to first declare an imported target` and that target is on:
```cmake
add_executable(Qt5::windeployqt IMPORTED)
```
I suggest closing.

**Comment by tcanabrava** [comment]
Please don't close the issue, as I also have it. The issue with the current Qt build for Windows is that it does not *generates* the windeployqt executable. so even if we declare the imported target, there's no binary to call.

**Comment by ericLemanissier** [comment]
this is not the same issue. please report it with full information (at least profile and steps to reproduce)

**Comment by ruilvo** [comment]
Yeah, that issue would be "windeployqt missing from Qt 5.15". Feel free to open an issue with that information. Other than that, if the targets are not canonical, they probably won't get it.

**Comment by obsgolem** [comment]
@tcanabrava You need to enable qttools to get windeployqt to build. The problem here is that I want a target for it. It doesn't look like a vanilla Qt 5 deploy has it, but Qt 6 has it, which makes me think it was simply an oversite during the Qt 5 lifetime.

**Comment by ruilvo** [comment]
If Qt6 has it, I think CCI should have it on qt6. But if Qt5 doesn't have it canonically, I don't think CCI should have it either.
It's not an oversight, it's hindsight. And remember that now Qt6 uses CMake as its build system, to some things are simplified and/or more CMake friendly.

**Comment by ericLemanissier** [comment]
CCI's qt6 has it: https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L601

**Comment by ruilvo** [comment]
@ericLemanissier and macdeployqt? hahah

**Comment by ericLemanissier** [comment]
same question: does vanilla qt provides a target for macdeployqt ?

**Comment by ruilvo** [comment]
I don't mean that. I just haven't found any mention of it in the build, and iirc, it does ship with Qt?

**Comment by ericLemanissier** [comment]
it should, if qt:qttools option is enabled

**Comment by Jihadist** [comment]
Qt has windeployqt. Issue can be closed
