### ISSUE TITLE
[service] conan-center API (conan.bintray.com) doesn't respond with the latest revision of package

### ISSUE THREAD

**Issue by maksim-0** [conan-io/conan-center-index#6425]
I would like to use Qt 5.15.2 with qtwinextras option (it was fixed in #6235 six days ago). If I go to https://conan.io/center/qt?version=5.15.2&tab=recipe I see revision ``21d95c2d7fece05125100584e12ef8d2`` in dropdown selected. I don't know is it latest or not but I confirm that it's pretty fresh by looking at recipe (it has changes to make qtwinextras option work). Great. I edit my conanfile.txt to include Qt with qtwinextras option enabled (I use cmake-conan actually but it doesn't matter):
```
[requires]
qt/5.15.2
[generators]
cmake_find_package
markdown
[options]
qt:shared=True
qt:qtwinextras=True
```
and execute ``conan install ...``. When it's ready I don't have Qt5::WinExtras target. Then I enable ``debug`` logging mode in ``conan.conf`` and see this:
```
1> [CMake] qt/5.15.2: Not found in local cache, looking in remotes...
1> [CMake] qt/5.15.2: Trying with 'conan-center'...
1> [CMake] DEBUG :rest_client_common.py[160]: REST: ping: https://conan.bintray.com/v1/ping [2021-07-19 20:59:12,844]
1> [CMake] DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions', 'matrix_params'] [2021-07-19 20:59:13,678]
1> [CMake] DEBUG :rest_client_common.py[188]: REST: get: https://conan.bintray.com/v1/conans/qt/5.15.2/_/_/download_urls [2021-07-19 20:59:13,680]
1> [CMake] Downloading conanmanifest.txt
1> [CMake] DEBUG :file_downloader.py[129]: DOWNLOAD: https://conan.bintray.com/artifactory/api/conan/conan-center-legacy/v1/files/_/qt/5.15.2/_/5cb549d499b5fb49646034045908706f/export/conanmanifest.txt [2021-07-19 20:59:13,748]
1> [CMake] Downloading conanfile.py
1> [CMake] DEBUG :file_downloader.py[129]: DOWNLOAD: https://conan.bintray.com/artifactory/api/conan/conan-center-legacy/v1/files/_/qt/5.15.2/_/5cb549d499b5fb49646034045908706f/export/conanfile.py [2021-07-19 20:59:13,782]
1> [CMake] Downloading conan_export.tgz
1> [CMake] DEBUG :file_downloader.py[129]: DOWNLOAD: https://conan.bintray.com/artifactory/api/conan/conan-center-legacy/v1/files/_/qt/5.15.2/_/5cb549d499b5fb49646034045908706f/export/conan_export.tgz [2021-07-19 20:59:13,965]
1> [CMake] qt/5.15.2: Downloaded recipe revision 0
```
Conan downloads ``5cb549d499b5fb49646034045908706f`` revision of package. And if we look into conanfile.py it downloads we see that it's doesn't have latest changes. This is not what I expected. I assume it should respond with the latest revision of package.

**Comment by ericLemanissier** [comment]
you should use https://center.conan.io as a remote for conan center. bintray is now completely down

**Comment by maksim-0** [comment]
Wow. That was fast. I've updated ``conan-center`` remote in Conan and it works! My bad. Thank you @ericLemanissier.
