### ISSUE TITLE
[service] Update Visual Studio compiler versions on Windows machines

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#645]
Update to the latest version of visual studio 17 in order to support libraries that only compile with most recent versions.

Related to #567

**Comment by danimtb** [comment]
We need also to update Visual Studio 2019 and 2015 as reported in other PRs

**Comment by ericriff** [comment]
Do we have an ETA for this update?

**Comment by danimtb** [comment]
@ericriff the update of the Visual Studio versions for 2017 and 2019 has been done. I will relaunch the PRs affected and close this issue afterward. Thanks!

**Comment by danimtb** [comment]
It seems affected PRs are working as expected now.
