### ISSUE TITLE
[package] qt/5.15.2: can't use with conan_basic_setup without TARGETS

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#6467]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **ALL**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.8.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
vulkan-loader:shared=True
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

put this into test package of qt:

cmake_minimum_required(VERSION 3.1.0)

set(CMAKE_CXX_STANDARD 11)

project(test_package)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

qt5_wrap_ui(UI_HEADERS
  temp.ui
)

set(SOURCES test_package.cpp greeter.h example.qrc)

add_executable(${PROJECT_NAME} WIN32 ${SOURCES})

target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
...
CMake Error at CMakeLists.txt:12 (qt5_wrap_ui):
  Unknown CMake command "qt5_wrap_ui".
```

</details>

**Comment by ericLemanissier** [comment]
you have to use one of cmake_find_package or cmake_find_package_multi generator to have access to these functions

**Comment by AndreyMlashkin** [comment]
Yes, ok, it works, but only for conan install/create.

If I have a CMake project, which includes conan, a wired thing happens:

Call Stack (most recent call first):
  CMakeLists.txt:159 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:251 (find_package):
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/andrei/sources/build_debug_studio/CMakeFiles/CMakeOutput.log".


There is Qt5Config.cmake in the build folder, but it still can't be found.

Do you need an example, demonstrating the issue?

**Comment by ericLemanissier** [comment]
yes, please provide a reproducible example

**Comment by AndreyMlashkin** [comment]
[example.zip](https://github.com/conan-io/conan-center-index/files/6869343/example.zip)

Call rebuild script there

**Comment by ericLemanissier** [comment]
it works if you add `CMAKE_MODULE_PATH=. ` at the beginning of the line  `cmake -DCMAKE_BUILD_TYPE=Debug .`, there is nothing wrong with the recipe or conan here.

**Comment by AndreyMlashkin** [comment]
@ericLemanissier, it didn't help in my case...
I have also tried to write
set(Qt5_DIR .)
find_package(Qt5 REQUIRED CONFIG HINTS . PATHS .)

Which cmake version do you use?
I am using 3.16.3

**Comment by ericLemanissier** [comment]
It should work with any cmake version. More information on https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure

**Comment by AndreyMlashkin** [comment]
The example I've sent, works for you, right? 

with the script, that looks like this:

conan install . --build missing --build cascade -u && \
cmake CMAKE_MODULE_PATH=. -DCMAKE_BUILD_TYPE=Debug . && \
cmake --build . -j6 --target test_package --config Debug

**Comment by ericLemanissier** [comment]
No, CMAKE_MODULE_PATH must be before the cmake call, on the same line. It's an environment variable

**Comment by AndreyMlashkin** [comment]
This one still does not work for me:

CMAKE_MODULE_PATH=$(pwd)
conan install . --build missing --build cascade -u && \
cmake CMAKE_MODULE_PATH=. -DCMAKE_BUILD_TYPE=Debug . && \
cmake --build . -j6 --target test_package --config Debug

**Comment by ericLemanissier** [comment]
It has to be on the same line: `CMAKE_MODULE_PATH=. cmake ...`

**Comment by AndreyMlashkin** [comment]
I haven't tried it on Linux yet, but this does not work on windows:

conan install . --build missing --build cascade -u
set CMAKE_MODULE_PATH=. cmake -DCMAKE_BUILD_TYPE=Debug .
cmake --build . -j6 --target test_package --config Debug

**Comment by ericLemanissier** [comment]
It should work on Linux. On windows you'll have to use whatever mechanism windows has to define environment variables

**Comment by AndreyMlashkin** [comment]
Still does not work

conan install . --build missing --build cascade -u && \
CMAKE_MODULE_PATH=. cmake -DCMAKE_BUILD_TYPE=Debug . && \
cmake --build . -j6 --target test_package --config Debug 


This also does not work:

conan install . --build missing --build cascade -u && \
CMAKE_MODULE_PATH=. && cmake -DCMAKE_BUILD_TYPE=Debug . && \
cmake --build . -j6 --target test_package --config Debug

Have you tried to build my example from archive, I've posted above?

**Comment by ericLemanissier** [comment]
Yes, I tried your archive and fixed the error by adding the env var as I told you. If the config file is properly generated, but not found by cmake, then the solution is on https://cmake.org/cmake/help/latest/command/find_package.html

**Comment by AndreyMlashkin** [comment]
I have prepared a docker, that shows a problem:
https://github.com/AndreyMlashkin/conan-qt-dependecy-example

I honestly, don't understand how can it work on your end, @ericLemanissier. Maybe some other qt version in path?

Could you please correct the rebuild script or CMakeLists there, so it works in Docker?

**Comment by ericLemanissier** [comment]
OK that's the best way to make some progress. Unfortunately I don't have access to a computer for few weeks, so I won't be able to help you if this repo does not have CI

**Comment by AndreyMlashkin** [comment]
Here we go:
https://github.com/AndreyMlashkin/conan-qt-dependecy-example/runs/3169311273?check_suite_focus=true

**Comment by ericLemanissier** [comment]
@AndreyMlashkin is this now working on your end?

**Comment by AndreyMlashkin** [comment]
Yes, thanks a lot!
