### ISSUE TITLE
[packege] <Protobuf>/<3.17.1>: Profile build_type=None or no build_type fails to build

### ISSUE THREAD

**Issue by rthomaskelly** [conan-io/conan-center-index#6471]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.8**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Put your profile output here
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10.1
compiler.libcxx=libstdc++11
[options]
[build_requires]
[env]
CXX=/usr/local/bin/g++

### Recreate
First included Protobuf and ran conan create. There was no build_type in the profile as shown above. The following error occurred. It is looking for protobuf-targets-none.cmake when it is actually called protobuf-target-noconfig.cmake.
(( no build_type ))

ERROR: protobuf/3.17.1: Error in package() method, line 187
        os.unlink(os.path.join(self.package_folder, self._cmake_install_base_path, "protobuf-targets-{}.cmake".format(str(self.settings.build_type).lower())))
        FileNotFoundError: [Errno 2] No such file or directory: '/root/.conan/data/protobuf/3.17.1/_/_/package/161aeefd41f4dcc8cc1fa9c30b59096a5d33ff4f/lib/cmake/protobuf/protobuf-targets-none.cmake'

root@ch12ldvdi312:/app/build# ls /root/.conan/data/protobuf/3.17.1/_/_/package/161aeefd41f4dcc8cc1fa9c30b59096a5d33ff4f/lib/cmake/protobuf/
protobuf-config.cmake  protobuf-options.cmake
protobuf-module.cmake  protobuf-targets-noconfig.cmake

Now set in profile:
build_type=None

The same error occurs when build_type=None. Conan still generates protobuf-targets-noconfig.cmake, not protobuf-targets-none.cmake

ERROR: protobuf/3.17.1: Error in package() method, line 187
        os.unlink(os.path.join(self.package_folder, self._cmake_install_base_path, "protobuf-targets-{}.cmake".format(str(self.settings.build_type).lower())))
        FileNotFoundError: [Errno 2] No such file or directory: '/root/.conan/data/protobuf/3.17.1/_/_/package/161aeefd41f4dcc8cc1fa9c30b59096a5d33ff4f/lib/cmake/protobuf/protobuf-targets-none.cmake'

root@ch12ldvdi312:/app/build# ls /root/.conan/data/protobuf/3.17.1/_/_/package/161aeefd41f4dcc8cc1fa9c30b59096a5d33ff4f/lib/cmake/protobuf/
protobuf-config.cmake  protobuf-options.cmake
protobuf-module.cmake  protobuf-targets-noconfig.cmake
root@ch12ldvdi312:/app/build#

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

When using conan, not defining `build_type` may result in an undefined behavior or at least, a non controlled environment.
Thus, setting the `build_type`, in your profile or via CLI is mandatory to avoid this kind of problems.
I'm closing this issue as the `protobuf/3.17.1` version is no longer supported by Conan Center Index.

If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
