### ISSUE TITLE
[question] "NO IMPORTS" policy on test packages

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan-center-index#6511]
Currently running the CCI build hooks on a package I'm trying to submit, and getting the following error message:

> ERROR: [TEST PACKAGE - NO IMPORTS() (KB-H034)] The method `imports` is not allowed in test_package/conanfile.py (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H034)

The entry for the knowledge base states:

> #KB-H034: "TEST PACKAGE - NO IMPORTS()"
>
> The method imports helps the test package stage copying all dynamic libraries and special resources. However, the run_environment parameter, used when running commands, is able to solve all paths to the dynamic libraries installed in your cache.

The library I'm submitting a package for (#6512) ships with data files, which are essential to its operation (it doesn't run without these data files). Using the `imports` method solves this issue, as the data files can be packaged in to the `res` folder, and imported to whichever local directory is appropriate. This also serves as a good exemplar for usage of the library, which is especially important given that there doesn't seem to be a way of documenting conan package usage. The sample code, also provided by the library, is being used in the example program. This seems to be a substantial departure from the assumptions underlying the rationale for this rule, so I guess I'm looking for guidance on how to approach this:

* Can exceptions be made for failing hook tests like this which don't cover all use cases for the `imports` method?
* Can anybody offer any alternate ways of approaching the problem I'm facing?

**Comment by SSE4** [comment]
> Can exceptions be made for failing hook tests like this which don't cover all use cases for the imports method?

yes, sometimes exceptions are really necessary, and we white-list certain packages for hooks, if needed

**Comment by Croydon** [comment]
Maybe I misunderstand, but if those data files, which are generally required, are part of the package already, you can get the path to these files in the test_package and run the lib with them?

Is there really a need to import them into the test_package folder?

**Comment by madebr** [comment]
I've implemented @Croydon 's suggestion at https://github.com/conan-io/conan-center-index/pull/6512#discussion_r676933033 and https://github.com/conan-io/conan-center-index/pull/6512#discussion_r676934420

**Comment by samuel-emrys** [comment]
> Maybe I misunderstand, but if those data files, which are generally required, are part of the package already, you can get the path to these files in the test_package and run the lib with them?
> 
> Is there really a need to import them into the test_package folder?

No misunderstanding - you're right. I was thinking about this too hard from the user perspective and not enough from the test case perspective. My only concern with this approach is the documentation of intended usage of the package. Outside of the test package environment, which is able to determine the data file locations at runtime, a user isn't going to be able to easily determine where the data files are being held (the package hash will change frequently). Without that, I'm not sure how the user is going to be able to set their environment variables to point at the appropriate location in a convenient way when running their application outside of using conan.

What I liked about the current example is that it says "you need this data to run, and you need to set it as an environment variable. This is how you can control the location of those data files". Which I guess raises the following questions:

* Is there a better way to consume these as a user?
* Is there a better way to document this usage?

Part of a reason this is a concern is that my experience thus far has been that failure to provide these data files results in an opaque error message. The upstream documentation _does_ make mention that they're required, but it requires a careful reading and is certainly not immediately obvious.

**Comment by madebr** [comment]
It's possible to set environment variables in `package_info`:
```python
def package_info(self):
    self.env_info.MPCCS_DATA = os.path.join(self.package_folder, "res")
```
Then, when running geotrans executables inside a conan environment, you don't need to set it explicitly anymore.
It's always okay to put a comment/`self.ouput.info` somewhere to inform users of this library quirk.

**Comment by samuel-emrys** [comment]
> It's possible to set environment variables in `package_info`:
> 
> ```python
> def package_info(self):
>     self.env_info.MPCCS_DATA = os.path.join(self.package_folder, "res")
> ```
> 
> Then, when running geotrans executables inside a conan environment, you don't need to set it explicitly anymore.
> It's always okay to put a comment/`self.ouput.info` somewhere to inform users of this library quirk.

Yep, I think that this resolves my concerns. The output message is more informative than the exemplar, the trick will be putting it in the right spot. My guess is that for a consumer, having it at the end of the `build()` command would be best? I guess this is going to depend on the order in which dependent libraries are built. This will be something to experiment with.

Anyway, since my issues are resolved, I'm going to close this issue for now. Thanks all.
