### ISSUE TITLE
[package] qt/5.15.2: XmlPatterns is not supported in conan recipe.

### ISSUE THREAD

**Issue by mherok** [conan-io/conan-center-index#6541]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **msvsc 15**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.8.8**
  * Cmake version: **3.17.0-rc3**

### Conan profile
```
os=Windows
os_build=Windows
arch=x86
arch_build=x86
compiler=Visual Studio
compiler.version=15
build_type=Debug
```

### Steps to reproduce
Just intall qt with `qtxmlpatterns=True` option and run Cmake with `find_package(Qt5 REQUIRED COMPONENTS XmlPatterns)`

### Logs
```
CMake Error at build/FindQt5.cmake:6 (message):
Conan: Component 'XmlPatterns' NOT found in package 'Qt5'
```

### Possible solution
It looks like the xmlpatterns option is not supported. After add  in _conanfile.py_
```
if self.options.qtxmlpatterns:
         _create_module("XmlPatterns", [])
```
every things works fine.

**Comment by ericLemanissier** [comment]
@mherok could you please try with #6644 ?

**Comment by wdobbe** [comment]
FYI: I didn't include the xmlpattern module initially in the qt5 component support because it is deprecated.

**Comment by mherok** [comment]
@ericLemanissier It works fine.
@wdobbe Well yes.  However as far as I know, it is marked as deprecated for removal in a future version (possible in Qt6) not in Qt5.
