### ISSUE TITLE
[package] qt/5.15.2: Static build results in `test_package` linker error

### ISSUE THREAD

**Issue by daravi** [conan-io/conan-center-index#6556]
I am getting linker errors when building qt/5.15.2 as a static library while `test_package` is being linked. (see logs)

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Linux AlmaLinux 8.4**
  * Compiler+version: **LLVM 10.0.1**
  * Docker image: **N/A**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.9.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
os.kernel=4.18
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=10
compiler.libcxx=libc++
compiler.cppstd=17
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```
conan create -o qt:qtdeclarative=True -o qt:qtquickcontrols2=True -o qt:qttools=True -o qt:qttranslations=True -o qt:qtvirtualkeyboard=True -o qt:qtx11extras=True -o qt:qtsvg=True . qt/5.15.2@
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
see attachments
```

</details>

[static_build.log](https://github.com/conan-io/conan-center-index/files/6888601/static_build.log)
[config.log](https://github.com/conan-io/conan-center-index/files/6888625/config.log)

**Comment by ericLemanissier** [comment]
This happens because qt links to your system dbus. The fix for this is to add a dbus option to the recipe, which enables the requirement of cci's dbus package, transmit the option value to cmake, and put dbus::foo in the requirements of the proper component. Unfortunately I won't be able to do this for several weeks
