### ISSUE TITLE
[package] mongo-cxx-driver/3.6.1: Compilation with mongo-cxx-driver ad a dependency fails after switching conan 1.36.0 to 1.37.0

### ISSUE THREAD

**Issue by kpk-pl** [conan-io/conan-center-index#6579]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **mongo-cxx-driver/3.6.1**
  * Operating System+version: **Centos7**
  * Compiler+version: **GCC 10**
  * Docker image: **centos7**
  * Conan version: **conan 1.37.0**
  * Python version: **Python 3.6.10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=RelWithDebInfo
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=10
ig=ig
os=Linux
os.version=rh7
os_build=Linux
os_build.release=rh7
icu:compiler.cppstd=17
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
Created a new test project with ' conan new mongo-test/1.0.0 -s'. Added mongo-cxx-driver as a dependency and added an include to whatever header file from mongo-cxx-driver:
conanfile diff:
+ requires = ['mongo-cxx-driver/3.6.1']

CMakeLists.txt:
cmake_minimum_required(VERSION 3.1)
project(mongo-test CXX)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_library(mongo-test mongo-test.cpp)

target_link_libraries(${PROJECT_NAME} PUBLIC CONAN_PKG::mongo-cxx-driver)
install(TARGETS ${PROJECT_NAME})

Source code:
#include "mongo-test.h"
#include <mongocxx/client.hpp>

void mongotest(){
}

When compiled with conan 1.36.0 everything works fine. Switching to conan 1.37.0, check below logs.
This the command I use: 'conan create . -s compiler.cppstd=20 -s compiler.version=10 --build=missing -s icu:compiler.cppstd=17'

If you do conan install -g ycm on that, you will see that mongo-cxx-driver includes are missing from the flags.json.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>
[root@a22cbaa9ae78 test]# conan create . -s compiler.cppstd=20 -s compiler.version=10 --build=missing -s icu:compiler.cppstd=17
Exporting package recipe
mongo-test/1.0.0 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
mongo-test/1.0.0 exports_sources: Copied 1 '.h' file: mongo-test.h
mongo-test/1.0.0 exports_sources: Copied 1 '.cpp' file: mongo-test.cpp
mongo-test/1.0.0: A new conanfile.py version was exported
mongo-test/1.0.0: Folder: /conan-standalone/bamboo/.conan/data/mongo-test/1.0.0/_/_/export
mongo-test/1.0.0: Using the exported files summary hash as the recipe revision: 428c01c64867ed7555fb03fcccd03a41
mongo-test/1.0.0: Exported revision: 428c01c64867ed7555fb03fcccd03a41
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=RelWithDebInfo
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=10
ig=ig
os=Linux
os.version=rh7
os_build=Linux
os_build.release=rh7
icu:compiler.cppstd=17
[options]
[build_requires]
[env]

Installing package: mongo-test/1.0.0
Requirements
    boost/1.74.0 from local cache - Cache
    bzip2/1.0.8 from 'ig' - Cache
    icu/68.1 from 'ig' - Cache
    libbacktrace/cci.20210118 from local cache - Cache
    mongo-c-driver/1.17.2 from 'ig' - Cache
    mongo-cxx-driver/3.6.1 from 'ig' - Cache
    mongo-test/1.0.0 from local cache - Cache
    openssl/1.1.1h from 'ig' - Cache
    snappy/1.1.8 from 'ig' - Cache
    zlib/1.2.11 from 'ig' - Cache
    zstd/1.4.5 from 'ig' - Cache
Packages
    boost/1.74.0:cad5d6b712d7ea837342b055e4a49cdc35f12f0a - Cache
    bzip2/1.0.8:5aad1af20cae69b38fd579b7b1ec6424e25b4eeb - Cache
    icu/68.1:c8c5e9596b6328c7f71615993938fb464d055475 - Cache
    libbacktrace/cci.20210118:f8a5b995af19c2be7af7955957aa73c01e14381e - Cache
    mongo-c-driver/1.17.2:c65c8d287e4555492c80b7708150cf78930467d1 - Cache
    mongo-cxx-driver/3.6.1:9cdc0e35a60772ae5d7eec7c4242b68a08d72697 - Cache
    mongo-test/1.0.0:0d28bc2699891d18ff292ef59e959281b1f27c36 - Build
    openssl/1.1.1h:f8a5b995af19c2be7af7955957aa73c01e14381e - Cache
    snappy/1.1.8:e9b6eb8ff4c5d5cab747eb0b20b78cb8d991a7ac - Cache
    zlib/1.2.11:f8a5b995af19c2be7af7955957aa73c01e14381e - Cache
    zstd/1.4.5:f8a5b995af19c2be7af7955957aa73c01e14381e - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
icu/68.1: Already installed!
icu/68.1: Appending ICU_DATA environment variable: /conan-standalone/bamboo/.conan/data/icu/68.1/_/_/package/c8c5e9596b6328c7f71615993938fb464d055475/res/icudt68l.dat
icu/68.1: Appending PATH environment variable: /conan-standalone/bamboo/.conan/data/icu/68.1/_/_/package/c8c5e9596b6328c7f71615993938fb464d055475/bin
libbacktrace/cci.20210118: Already installed!
openssl/1.1.1h: Already installed!
snappy/1.1.8: Already installed!
zlib/1.2.11: Already installed!
zstd/1.4.5: Already installed!
boost/1.74.0: Already installed!
mongo-c-driver/1.17.2: Already installed!
mongo-cxx-driver/3.6.1: Already installed!
mongo-test/1.0.0: Configuring sources in /conan-standalone/bamboo/.conan/data/mongo-test/1.0.0/_/_/source
mongo-test/1.0.0: Copying sources to build folder
mongo-test/1.0.0: Building your package in /conan-standalone/bamboo/.conan/data/mongo-test/1.0.0/_/_/build/0d28bc2699891d18ff292ef59e959281b1f27c36
[

</details>

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

Conan v1 is almost deprecated and `v1.37.0` is a really old one. 
I'm closing this issue because this recipe has been modified a lot since this issue was open.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
