### ISSUE TITLE
[service] config.yml not found

### ISSUE THREAD

**Issue by n-bes** [conan-io/conan-center-index#6587]
I rebuilt conan-center-index recipes. This is my first results: several package don't follow files-tree structure described on [wiki](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#more-information-about-recipes).

```conan-center-index/recipes/<package>/config.yml``` doesn't exist for these packages:

- 7zip 
- cfgfile
- lzma_sdk
- minizip
- read-excel
- systemc-cci
- tcl

**Comment by ericriff** [comment]
Tried to fix this for `zlib` a very long time ago and I was told those files are not required.y
I also need those files to be there.
https://github.com/conan-io/conan-center-index/pull/1632

**Comment by SpaceIm** [comment]
I agree that all recipes should follow the same files-tree-structure and therefore always have `config.yml` at the top level for consistency.

**Comment by SSE4** [comment]
we may add explicit `config.yml`, it should be harmless, and if it makes workflows for forked repositories easier, I personally don't see a reason to reject it.
our CI is "smart" to work for simple pre-defined structure without `config.yml`, but I'd prefer explicit.
given the fact CI library is not an open-source yet, users have to re-create the logic from scratch, and they need to re-implement this "magic" to deduce structure when `config.yml` is missing as well.

**Comment by n-bes** [comment]
Close. All packages contains explicit ```config.yml```.
