### ISSUE TITLE
[center.conan.io] Packages missing to display or with missing information

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#661]
When searching for `dwarf` you get 2 results with `libdwarf`.

First issue:
- The first the entry without user/channel that works well and the second one with user/channel. Clicking the second entry directs you to a 404 page. --> In this case, we can follow 2 approaches: Avoid listing the old package (the one with user/channel) in the search results, or direct to the correct page, in this case it should be https://conan.io/center/libdwarf/20191104/?user=conan&channel=stable

Second issue:
- Although the second result of the search leads you to a 404 page, the page for that package actually exists: https://conan.io/center/libdwarf/20191104/?user=conan&channel=stable however, the information is empty. This also happens with ZLIB package https://conan.io/center/zlib/1.2.11/?user=conan&channel=stable (although this one does not appear in the search results)

**Comment by aarvyved** [comment]
Thanks for reporting this, you should be able to view the legacy package for `libdwarf` (

> https://conan.io/center/libdwarf/20190505/?user=bincrafters&channel=stable

 ) now. We have added a differentiation between the latest packages and legacy packages in the search bar.
The package `zlib` shown in the search is the latest one.

**Comment by danimtb** [comment]
Verified as fixed! Thanks a lot @aarvyved 😄
