### ISSUE TITLE
[request] glob/0.0.1

### ISSUE THREAD

**Issue by saracen24** [conan-io/conan-center-index#6619]
### Package Details
  * Package Name/Version: **glob/0.0.1**
  * Website: **https://github.com/p-ranav/glob/blob/master/README.md**
  * Source code: **https://github.com/p-ranav/glob**

### Description Of The Library / Tool
Glob for C++17. Unix-style pathname pattern expansion.

**Comment by theirix** [comment]
Waiting for the release https://github.com/p-ranav/glob/issues/7
