### ISSUE TITLE
[package] apr/1.7.0: Does not build with apple clang 12. Issue for PR submission to make it build

### ISSUE THREAD

**Issue by Nicky-D** [conan-io/conan-center-index#6621]
apr/1.7.0 has been disabled and just errors with:
apr does not (yet) support apple-clang 12
This has been a deliberate change because apr fails to build

  * Package Name/Version: **apr/1.7.0**
  * Operating System+version: **OSX 11.5.1**
  * Compiler+version: **clan 12.0.5**
  * Conan version: **conan 1.39.0**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=appl-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by SpaceIm** [comment]
There is a solution to fix it: https://bz.apache.org/bugzilla/show_bug.cgi?id=64753

**Comment by Nicky-D** [comment]
> There is a solution to fix it: https://bz.apache.org/bugzilla/show_bug.cgi?id=64753

Thank you spacelm. Yes this is what I'm going to apply, the suggestion from  JM Marcastel. Patching apr_common.m4 as per his suggestion makes apr compile fine with clang 12
