### ISSUE TITLE
[center.conan.io] Bad UX when header-only is present

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#664]
When a package offers a header-only configuration, the Available Configurations only shows the available number. It could be represented by "Others", or "Header-Only".

https://conan.io/center/boost/1.71.0/?user=_&channel=_&revision=&os=&tab=overview

![Screenshot_2020-01-13 Boost Package version 1 71 0 ConanCenter - Jfrog](https://user-images.githubusercontent.com/4870173/72261792-4a1e1800-35f4-11ea-862e-f628e29a707c.png)

**Comment by Dattax** [comment]
We just put in a fix - you should see a difference by tomorrow afternoon. Thanks for bringing this to our attention.

**Comment by Dattax** [comment]
Please verify (https://conan.io/center/boost/1.72.0/?user=_&channel=_) and close this issue. Thank you!

**Comment by uilianries** [comment]
Hi @Dattax ! That URL is returning 404:

![Screenshot_2020-01-16 JFrog ConanCenter - The Central Repository for C C++ packages](https://user-images.githubusercontent.com/4870173/72565632-0b58be00-3891-11ea-8a44-4b0ac085f880.png)

**Comment by Dattax** [comment]
Ah yes, sorry we just notice that yesterday - that push is coming (it's separate issue from the header-only issue. Check this instead: https://conan.io/center/boost/1.72.0/

**Comment by uilianries** [comment]
The URL https://conan.io/center/boost/1.72.0/?user=_&channel=_ is working:

![Screenshot_2020-01-16 Boost Package version - 1 72 0 - ConanCenter - JFrog](https://user-images.githubusercontent.com/4870173/72565726-3fcc7a00-3891-11ea-9445-b4f063f553a3.png)

We are good now, Thanks a lot!
