### ISSUE TITLE
[request] protobuf/3.6.1

### ISSUE THREAD

**Issue by claudius-kienle** [conan-io/conan-center-index#6657]
### Package Details
  * Package Name/Version: **protobuf/3.6.1**
  * Changelog: **https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by Jihadist** [comment]
protobuf/3.17.1 is now available. Why we need 3.6.1?

**Comment by claudius-kienle** [comment]
I do have a project where I need a specific protobuf version. I created the language specific protoc files with v3.6.1. To use them I also need v3.6.1 as dependency in the application.
Otherwise the error occurs that I use an incompatible protobuf version with the compiled protoc files.

**Comment by Jihadist** [comment]
@claudius-kienle old protobuf recipes need a lot of patches so I think it's not so easy to add ancient protobuf version
