### ISSUE TITLE
[package] protobuf/3.17.1: can't cross-compile windows->android

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#6664]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **protobuf/3.17.1**
  * Operating System+version: **windows 10**
  * Conan version: **conan 1.39.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=armv7
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=11
os=Android
os.api_level=21
[options]
*:with_glib=False
*:with_glew=False
*:BUILD_WITH_RENDERING_SYSTEM=OpenGL
[build_requires]
*:android-ndk/r22b, cmake/3.19.2, ninja/1.10.1, opengl/system
[env]
```

```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
compiler.runtime=MD
[options]
qt:shared=True
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
 conan install protobuf/3.17.1@ --build missing -pr:h profile_host_android -pr:b default -u

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
...
ERROR: protobuf/3.17.1: option 'fPIC' doesn't exist
Possible options are ['shared', 'with_zlib', 'with_rtti', 'lite']
...
```

</details>

**Comment by AndreyMlashkin** [comment]
Problem is gone, seems to be a cache corruption

**Comment by SuTanTank** [comment]
Hi @AndreyMlashkin 

How did you solve this problem? I found that ```configure``` is executed twice, which caused ```del self.options.fPIC``` executed twice.
