### ISSUE TITLE
[center.conan.io] Package search shows mixed versions

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#667]
Hi!

As CCI is providing new Conan package based on name/version@ only and other packages from Conan Center are "incompatible" but present in conan.io/center results, it would be nice having a label to distinguish between CCI packages and old packages from Bintray.

For instance, when searching for Catch2, we have 2 results:

![screenshot](https://user-images.githubusercontent.com/4870173/72280350-e5c08000-3616-11ea-98eb-669b2a657b40.png)
 
As a regular user, I need to click on each one to understand what I want. However, with a simple label it can be solved easily:

![screenshot](https://user-images.githubusercontent.com/4870173/72280710-b65e4300-3617-11ea-9b80-21489681a74d.png)

/cc @ericLemanissier @Croydon

**Comment by Dattax** [comment]
We just fixed this - and you should see a difference by tomorrow. Thanks for catching that.

**Comment by uilianries** [comment]
Thanks @Dattax !

**Comment by philsquared** [comment]
I still see the same behaviour. Is the fix in?

**Comment by memsharded** [comment]
Yes, the output is:

![image](https://user-images.githubusercontent.com/15367152/72429094-6bffd200-378f-11ea-8bd3-25cbc082e641.png)


The way it can be differentiated: use the first package, the one that has a number of downloads attached. But yes, @Dattax I'd prefer to have a more evident separation of cci and legacy packages.

**Comment by danimtb** [comment]
The number of downloads is also something that has been requested #158

**Comment by philsquared** [comment]
Thanks @memsharded, but is that not what it was before?

**Comment by uilianries** [comment]
@philsquared Yes, exactly as before.

**Comment by philsquared** [comment]
Ah, sorry @memsharded - were you saying "yes [the fix is in]" or "yes [the output is the same]"?

**Comment by memsharded** [comment]
Yes, the output is the same, I agree this is still an issue, it hasn't been properly fixed, such output is confusing.

**Comment by aarvyved** [comment]
@memsharded The fix went in this morning and you should see the old/legacy packages with lighter text and and info icon which tells you the packages are from an older version
![Screen Shot 2020-01-16 at 12 59 05 PM](https://user-images.githubusercontent.com/17733601/72562336-03345a80-3860-11ea-94bf-a2a193166045.png)

**Comment by Dattax** [comment]
We will not be able to add the number of downloads for the non-C3I packages. We have implemented the requested change showing the difference between C3I and other packages. I think we can close this issue. :)

**Comment by memsharded** [comment]
Ok, this is cool, many thanks, this issue can be closed!
