### ISSUE TITLE
[conan.io/center] Revisions are non informative ==> they can provide more info

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#6670]
For a certain project, provided by caonan center, the revision drop down box is non descriptive.
It's just a list of hashes.

It's not clear to me what is ordering of these hashes? Is it most recent first or last?
It would also be useful to show their age/date of inclusion. That way people have an idea how old a revision is.

**Comment by jgsogo** [comment]
We are thinking about removing everything related to recipe revisions from the frontend (or at least hide it behind some _advance/drill into details_ link. We think is more confusing than useful for people browsing the webpage. 

Feedback about what information to show in the webpage (and to remove) would be useful now. Thanks!

**Comment by AbrilRBS** [comment]
Closing as not planned with the new UI that has been live for a long time now, where recipe revisions now also show the timestamp of each one
