### ISSUE TITLE
[package request] paho-c recipe, including necessary libraries without options 

### ISSUE THREAD

**Issue by ken00535** [conan-io/conan-center-index#670]
I am beginner of conan, and I want to use paho-c

here is my conanfile.txt

```
[requires]
paho-c/1.3.0@conan/stable
OpenSSL/1.0.2s@conan/stable

[generators]
cmake

[options]
paho-c:shared=True
paho-c:asynchronous=False
paho-c:SSL=True
```

paho-c has three options and conan will generate paho-mqtt3cs.lib or paho-mqtt3as.lib according 
 these options.

But it generate one of these libs once build, and I need to use both of two.

How can I modify my conanfile.txt to use two types of libs?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I think @uilianries was involved in this paho-c recipe, could you please have a look when possible?

**Comment by TrevorMuraro** [comment]
The four libraries do four different things - `paho-mqtt3c` for semi-synchronous client with no SSL, `paho-mqtt3cs` for semi-synchronous client with SSL available, `paho-mqtt3a` for fully asynchronous client with no SSL, `paho-mqtt3as` for fully asynchronous client with SSL available.  You only need one of them.

To use the semi-synchronous clients, `#include "MQTTClient.h"` and use [this API](https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/index.html).  To use the fully asynchronous clients, `#include "MQTTAsync.h"` and use [this API](https://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/publish.html).  Note that both headers will be installed regardless of which library is installed.

**Comment by ken00535** [comment]
@TrevorMuraro thanks.

I use MQTTAsync.h now. This is work for me.
