### ISSUE TITLE
[question] conan-center vs. conancenter remote

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan-center-index#6711]
I have now tried to build libxml2/2.9.12. Just before that I had to add the conancenter remote manually. #6706
I have also removed the deprecated conan-center remote. Now I get the error message:
libxml2/2.9.12: Downloaded recipe revision 0
ERROR: Failed requirement 'zlib/1.2.11' from 'libxml2/2.9.12'
ERROR: No remote 'conan-center' defined in remotes

Do I really need both remotes, since zlib is also in conancenter?

___

 conan search zlib  --remote conancenter
Existing package recipes:

zlib/1.2.8
zlib/1.2.11

**Comment by Croydon** [comment]
No, you only need the new URL `https://center.conan.io`

How you name the remotes is arbitrary. You could add `https://center.conan.io` as `wormhole`

Looks like you have added it as `conancenter` but then made a typo and tried to install from `conan-center`

> ERROR: No remote 'conan-center' defined in remotes

**Comment by dmn-star** [comment]
I did not explicitly pass an option for remotes in the conan install command.
>conan install libxml2/2.9.12@ --build --profile:host ./conan/profiles/mac_catalyst --profile:build ./conan/profiles/mac

libxml2 is also correctly pulled from conancenter, but the conan client seems to want to pull the dependencies for libxml2 from conan-center for whatever reason.

____
The output conan remote list
conancenter: https://center.conan.io [Verify SSL: True]

**Comment by SpaceIm** [comment]
I guess your cache is corrupted now, with previous installed recipes still refering to conan-center while this name doesn't exist anymore in your `remotes.json`

**Comment by Croydon** [comment]
> I guess your cache is corrupted now, with previous installed recipes still refering to a `conan-center` remote while this name doesn't exist anymore in your `remotes.json`

Maybe renaming the remote back to `conan-center` would work around that

**Comment by dmn-star** [comment]
@SpaceIm Yes, that is it. Works now after cache clear.
