### ISSUE TITLE
[question] importing packages from bincrafters?

### ISSUE THREAD

**Issue by drozel** [conan-io/conan-center-index#674]
I tied to use conan-center as i was asked [here](https://github.com/conan-io/conan/issues/6279) and i realized conan-center is quite empty now.
All packages i already found in the bincrafters repo are inaccessible if i change to conan-center.

What is the idea behind conan-center? Don't we want to copy all existing recipes (and it's already pretty big base now) from conan and bincrafters? 
It's even more important for the older versions of the libs.

**Comment by danimtb** [comment]
The migration process of recipes to this repo is not automatic and recipes require at least minor changes to adapt to the repo structure. However, anyone can contribute with recipes and it is not a requirement to have them working for all configurations.

If you want to contribute a recipe from bincrafters, you can always get in touch or collaborate with them through their github fork or reaching them out in slack.

**Comment by Croydon** [comment]
We do migrate every recipe from Bincrafters which is ready for CCI step-by-step

We do have quite a lot of recipes so this takes time. Also not all do yet fulfil the quality standards of CCI so some recipes will take still a long time until we will see them in CCI

You can use the Conan Center and Bincrafters remote at the same time to access recipes from both worlds

**Comment by dmn-star** [comment]
> We do have quite a lot of recipes so this takes time. 

Can you migrate libxslt recipe first, please. :-) Is my last dependency from Bincrafters and we can close #https://github.com/conan-io/wishlist/issues/232

**Comment by Croydon** [comment]
I think this issue can be closed as the question is answered. Transferring recipes is a long-lasting ongoing task and every help is appreciated 😄

**Comment by ericLemanissier** [comment]
@dmn-star see https://github.com/conan-io/conan-center-index/pull/1558
