### ISSUE TITLE
[package] openal/1.21.1: Warning: "Unknown compiler. Assuming your compiler supports c++14"

### ISSUE THREAD

**Issue by daravi** [conan-io/conan-center-index#6762]
Small issue, but this is printed during consumer's conan install:
```
openal/1.21.1: WARN: Unknown compiler. Assuming your compiler supports c++14
```

**Comment by SpaceIm** [comment]
Yes, it comes from an extra indentation.

Honestly, I would remove all these warnings, even when the compiler is "unknown".

**Comment by daravi** [comment]
@SpaceIm Thanks
