### ISSUE TITLE
[package] qt/6.0.4: can't build with tools=True

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#6774]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.0.4**
  * Operating System+version: **MacOs**
  * Conan version: **conan 1.39.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
any
```

### Steps to reproduce (Include if Applicable)
conan create . qt/6.0.4@test/test --build outdated -o qt:qttools=True -u

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
...
Check dependencies of 'qtbase'
Check dependencies of 'qttools'
CMake Error at CMakeLists.txt:69 (message):
  Module 'qttools' depends on 'qtdeclarative', but 'qtdeclarative' will not
  be built.

  Note: Use '-skip qttools' to exclude it from build.



-- Configuring incomplete, errors occurred!

...
```

</details>

**Comment by ericLemanissier** [comment]
IIRC this is an upstream bug which is solved in qt 6.1.2.
