### ISSUE TITLE
msdfgen: provided include hierarchy is not correct

### ISSUE THREAD

**Issue by Jairard** [conan-io/conan-center-index#6779]
Hi,

In the current recipe of `msdfgen`, the resulting includes are stored in a `msdfgen` folder, as you can see in the [test](https://github.com/conan-io/conan-center-index/blob/e0a26a981b43222eb6181f884630822cc96855f6/recipes/msdfgen/all/test_package/test_package.cpp#L1). However, the author stated that the correct way to include this file is `#include <msdfgen.h>` in [this issue](https://github.com/Chlumsky/msdf-atlas-gen/issues/25#issuecomment-894796634).

I think I could push modifications to the `CMakeLists.txt` in the repo, or change the destination paths of includes in the recipe, but I don't know to handle this version-wise, because it would break existing dependencies. Does it have to be a whole new version (`1.9.2` if integrated in the repo, or something like `cci.20210809` else) ?

**Comment by SpaceIm** [comment]
Therefore author should fix its own CMakeLists, because its CMake config file is not compliant: https://github.com/Chlumsky/msdfgen/blob/24a3a3021f9288cc2e2c3da512fc5f0352f3c03c/CMakeLists.txt#L61

**Comment by Jairard** [comment]
I agree about the CMakeLists, I will make PRs in this way (I already made one but I'm not really familiar with CMake and missed the point you noted).

If I understand correctly, the PR you made will allow both `#include <msdfgen/msdfgen.h>` and `#include <msdfgen.h>`, thus not breaking anything. I think it's a nice way to handle it without causing breaks, so thanks for your time :)
