### ISSUE TITLE
[request] MKL/2021.3

### ISSUE THREAD

**Issue by kylemacfarlan** [conan-io/conan-center-index#6801]
### Package Details
  * Package Name/Version: **MKL/2021.3**
  * Website: **https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl.html**

### Description Of The Library / Tool
* Enhanced math routines enable developers and data scientists to create performant science, engineering, or financial applications
* Core functions include BLAS, LAPACK, sparse solvers, fast Fourier transforms (FFT), random number generator functions (RNG), summary statistics, data fitting, and vector math
* Optimizes applications for current and future generations of Intel® CPUs, GPUs, and other accelerators

### Previous Work
There was a request and discussion on the old Conan wishlist here: https://github.com/conan-io/wishlist/issues/203/

Some work has been done on packaging here (and other places):
https://github.com/shellshocked2003/mkl-include
https://github.com/shellshocked2003/mkl-static
https://github.com/shellshocked2003/mkl-shared
https://github.com/bredej/mkl-shared

### Other Information
There is an official Conan recipe for their glue code/wrapper layer oneMKL: https://github.com/oneapi-src/oneMKL, which shows that at least someone in Intel is aware of Conan and can write recipes for it. 

I emailed scripting@intel.com (the email address associated with the MKL pip packages) to ask about the possibility of a Conan package, but never received a response. Perhaps someone officially associated with the Conan team would have better luck

**Comment by aminya** [comment]
Is there an update on this?

**Comment by samuel-emrys** [comment]
I could be wrong, but isn't MKL closed source and proprietary? As per https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#the-conandatayml:

> warning Please be aware that conan-center-index only builds from sources and pre-compiled binaries are not acceptable. For more information see our [packaging policy](https://github.com/conan-io/conan-center-index/blob/master/docs/packaging_policy.md).

**Comment by aminya** [comment]
If it is not possible to upload them to conan.io there should be an other way. For example, how can I use third party recipes that are on GitHub? 


https://github.com/shellshocked2003/mkl-include/issues/2

**Comment by samuel-emrys** [comment]
> If it is not possible to upload them to conan.io there should be an other way. For example, how can I use third party recipes that are on GitHub?
> 
> [shellshocked2003/mkl-include#2](https://github.com/shellshocked2003/mkl-include/issues/2)

@aminya this isn't the place to discuss this, but the short answer is you can clone that repository and [create the package manually](https://docs.conan.io/en/latest/reference/commands/creator/create.html). This can then be self-hosted on [your own private artifactory for C++](https://jfrog.com/blog/announcing-jfrog-artifactory-community-edition-c-c/), or alternatively you can set up a [free cloud instance](https://jfrog.com/artifactory/) - This is what replaces bintray, and it doesn't look like shellshocked have set it up to host their artifacts. Join the [slack channel](https://cppalliance.org/slack/) for further guidance if you require it.
