### ISSUE TITLE
[package] icu: python error when cross-compiling on Windows for linux/unix-targets

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan-center-index#6811]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **icu**
  * Operating System+version: **Windows**
  * Compiler+version: **QCC**
  * Conan version: **conan 1.37.0**
  * Python version: **Python 3.8.6**

### Steps to reproduce (Include if Applicable)
Cross build an icu package on Windows with an GCC-like compiler.

When cross building from Windows one will get an "unpack" error at line [194](https://github.com/conan-io/conan-center-index/blob/e37ade77b464dabff4975b7361fec638d31a49ed/recipes/icu/all/conanfile.py#L194). This is due to the issue that on Windows the path component separator is ```\``` and a ```rsplit('/', 1)``` will not result in a correct outcome.

### Solution
The following change has been tested successfully:

original [line 193](https://github.com/conan-io/conan-center-index/blob/e37ade77b464dabff4975b7361fec638d31a49ed/recipes/icu/all/conanfile.py#L193):
```python
            bin_path = self.deps_env_info["icu"].PATH[0]
```
changed to:
```python
            bin_path = self.deps_env_info["icu"].PATH[0].replace("\\", "/")
```

Best regards

**Comment by SSE4** [comment]
sounds like a reasonable, and safe change
@madebr WDYT?

**Comment by madebr** [comment]
Correct analysis.
A pr would be very much appreciated!

**Comment by Johnnyxy** [comment]
As I cannot provide a PR (caused by CLA problems) I reported the proposed changes directly in the issue.
