### ISSUE TITLE
[package] OPENMPI/4.1.0: a system-required executable could not be found

### ISSUE THREAD

**Issue by AnnonymousProgrammer** [conan-io/conan-center-index#6814]
I tried out the conan hello world application:

https://docs.conan.io/en/latest/getting_started.html

with the only difference that i try to use the openmpi library instead of pocco (openmpi/4.1.0) and I use a simple open mpi hello world application as a main.cpp:

'''
#include <mpi.h>
#include <stdio.h>

int main(int argc, char** argv) {
    // Initialize the MPI environment
    MPI_Init(NULL, NULL);

    // Get the number of processes
    int world_size;
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    // Get the rank of the process
    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

    // Get the name of the processor
    char processor_name[MPI_MAX_PROCESSOR_NAME];
    int name_len;
    MPI_Get_processor_name(processor_name, &name_len);

    // Print off a hello world message
    printf("Hello world from processor %s, rank %d out of %d processors\n",
           processor_name, world_rank, world_size);

    // Finalize the MPI environment.
    MPI_Finalize();
}
'''

I am able to compile the application, however it has issues during runtime (see log file provided below).

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openmpi/4.1.0**
  * Operating System+version: **Linux Ubuntu 18.04.5 LTS**
  * Compiler+version: **gcc 7.5.0**
  * Docker image: **i run it native**
  * Conan version: **conan 1.39.0**
  * Python version: **Python 2.7.17**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

I use the default profile

[settings] 
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)

1. use the conan hello world example (https://docs.conan.io/en/latest/getting_started.html)
2. add to conanfile.txt openmpi instead of poco
3. exchange the main files (the one given above)
4. compile it as described in the conan docs
5. run it

### Logs (Include/Attach if Applicable)
Output if i try to execute the main

[lukas-VirtualBox:27488] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 572 
[lukas-VirtualBox:27488] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 172
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /home/conan/w/BuildSingleReference/.conan/data/openmpi/4.1.0/_/_/package/6a9cec423c448e65a409b5b2194ac20f57e6de85/res/openmpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /home/conan/w/BuildSingleReference/.conan/data/openmpi/4.1.0/_/_/package/6a9cec423c448e65a409b5b2194ac20f57e6de85/res/openmpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[lukas-VirtualBox:27488] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

</details>

**Comment by samuel-emrys** [comment]
A quick look at the `openmpi` recipe shows:

```python
    def package_info(self):
        self.cpp_info.libs = ['mpi', 'open-rte', 'open-pal']
        if self.settings.os == "Linux":
            self.cpp_info.system_libs = ["dl", "pthread", "rt", "util"]
```

do you have the required `system_libs` on your system?

**Comment by planetmarshall** [comment]
The OpenMPI recipe sets up some environment variables which you may need to have available.

Try, in your `conanfile.txt` or `conanfile.py` folder
```
$ conan install . --generator virutalenv
$ source activate.sh
$ <run your program>
```

See [Virtual Environments](https://docs.conan.io/en/latest/mastering/virtualenv.html) for details.

**Comment by AnnonymousProgrammer** [comment]
@planetmarshall thanks for the hint but this does not work either. I get another error:

"
[lukas-VirtualBox:06692] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 458
[lukas-VirtualBox:06692] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 166
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value A system-required executable either could not be found or was not executable by this user (-126) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "A system-required executable either could not be found or was not executable by this user" (-126) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[lukas-VirtualBox:6692] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
"

Does my example code work on your machine?

**Comment by planetmarshall** [comment]
> Does my example code work on your machine?

Yes. Can you share your `CMakeLists.txt`?

**Comment by AnnonymousProgrammer** [comment]
@planetmarshall 
for sure:
"
 project(MyDumbProject)
 cmake_minimum_required(VERSION 2.8.12)
 add_definitions("-std=c++11")


 include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
 conan_basic_setup()


add_executable(main main.cpp foo.cpp)
target_link_libraries(main ${CONAN_LIBS})

enable_testing()

add_executable(
  hello_test
  my_google_test.cc
)
target_link_libraries(hello_test ${CONAN_LIBS})

include(GoogleTest)
gtest_discover_tests(hello_test)
"

**Comment by AnnonymousProgrammer** [comment]
I cleared out the old files and with virtual environment it works. Thanks a lot @planetmarshall :)
