### ISSUE TITLE
[question] Android NDK r23 and macOS

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan-center-index#6873]
> Only a DMG is provided for direct download for macOS because it is required for Catalina and newer.
https://developer.android.com/ndk/downloads

Now what is the easiest way to handle this in Conan?
@a4z

**Comment by SSE4** [comment]
.dmg is a disk image, and can be mounted via command line, then contents can be copied.
yes, it complicates workflow a bit, but still possible.

**Comment by dmn-star** [comment]
So I should then call "hdiutil attach ... -mountroot path" from the Conan recipe ?

**Comment by a4z** [comment]
This is a very ~~stupid and hostile~~ unpleasant change google did here, making work for all existing automated CI systems in the world. Unbelievable. I know they started to provide dmgs some (one or two) versions ago, but still, ... bad.

`hdiutil attach` is one option, but to make that clean, unmounting would also be needed, and that means the save way would be using python `with hdiutil_attach` , where `hdiutil_attach` would need to be a helper we do not have at the moment

**Comment by dmn-star** [comment]
I found a python wrapper for hdiutil dmglib https://github.com/0xbf00/dmglib, https://pypi.org/project/dmglib/
Could we eventually use the lib?

**Comment by a4z** [comment]
I reported that as a bug to the NDK
https://github.com/android/ndk/issues/1563

maybe it helps to get saneness back

**Comment by a4z** [comment]
> I found a python wrapper for hdiutil dmglib https://github.com/0xbf00/dmglib, https://pypi.org/project/dmglib/
> Could we eventually use the lib?

looks good on first glance, but is an external dependency, and I am more than unsure that we want that in a recipe on the cci 
so this is maybe just good for personal / local solutions

**Comment by dmn-star** [comment]
Ok. I have created a feature request.

**Comment by a4z** [comment]
News from Google, the zip still exists
https://dl.google.com/android/repository/android-ndk-r23-darwin.zip

It's just not documented anymore because some people used it wrong and reported bug that they would not have with the dmg package. 
So everything for the conan recipe continues to work as it did.

**Comment by dmn-star** [comment]
Luck again. :-)  I just updated android-ndk to r23.
