### ISSUE TITLE
[center.conan.io] Add a small set me up snippet, like in artifactory

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan-center-index#689]
Please add for every package a small how to setup code snippet, like it is done in artifactory.
e.g. 
```
conan remote add conan-center .. // maybe don't know whether this is necessary
conan install boost/1.72.2
```
Newbies wants to know how to get this binaries in no way.

**Comment by gocarlos** [comment]
also show the options available for the recipe e.g. `Poco:enable_crypto=True`

**Comment by SSE4** [comment]
this line is unnecessary for sure:
```
conan remote add conan-center .. // maybe don't know whether this is necessary
```
**conan-center** remote is automatically added by the conan client since the beginning

**Comment by Dattax** [comment]
What content would go into the set me up? We removed it because we found it unnecessary.

"conan-center remote is automatically added by the conan client since the beginning"

**Comment by uilianries** [comment]
I think `conan install boost/1.72.2 -r conan-center` only.

As @SSE4 commented before, `conan-center` is configured by default, so is unnecessary and can make confusing to newbies.

Any comment @derived-coder ?

**Comment by derived-coder** [comment]
yeah, this snippet looks good.
The thing with the options, I don't know.
One quesiton, for what configuration will this download the libraries? I guess the default config?
Maybe, a snippet for downloading only for some specific config is needed?

**Comment by derived-coder** [comment]
@Dattax 
So what is the current state here? 
Even artifactory has a  `set me up` button. The average user will not know how to install a package for this needed profile....

**Comment by ericLemanissier** [comment]
maybe we could show the md file generated with markdown generator ? The problem is that it depends on the settings and the options

**Comment by derived-coder** [comment]
Didn't knew about this generator. Nice.
However, without showing example code how to install and how to consume a package I see 
a usage problem for the whole site.

**Comment by Croydon** [comment]
This seems to be done, see e.g. https://conan.io/center/recipes/openssl

Issue can be closed
