### ISSUE TITLE
[request] qwt/6.2.0

### ISSUE THREAD

**Issue by maspri** [conan-io/conan-center-index#6895]
### Package Details
  * Package Name/Version: **qwt/6.2.0**
  * Changelog: **https://sourceforge.net/p/qwt/git/ci/develop/tree/CHANGES-6.2**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by kenfred** [comment]
This is done with the merge of https://github.com/conan-io/conan-center-index/pull/7224.
