### ISSUE TITLE
[conan.io/center] Latest package version of some packages from the Web UI not avalible from the command line

### ISSUE THREAD

**Issue by Kasurus** [conan-io/conan-center-index#6900]
I would like to install the newest version of a library that is shown in the [web UI](https://conan.io/center).

From the web UI i can see that [libcurl](https://conan.io/center/libcurl) should be available in version 7.78.0. 
![grafik](https://user-images.githubusercontent.com/38571075/129784783-f396ba9d-83e1-4ecb-aa43-77f675855b21.png)

But the install fails:

``` bash
$ conan install libcurl/7.78.0@
...
libcurl/7.78.0: Not found in local cache, looking in remotes...
libcurl/7.78.0: Trying with 'conan-center'...
ERROR: Unable to find 'libcurl/7.78.0' in remotes
```

I can also see that there seems to no version 7.78.0 from the command line:
``` bash
$ conan search libcurl/* -r=all

Existing package recipes:

Remote 'conan-center':
libcurl/7.50.3@bincrafters/stable
libcurl/7.52.1@bincrafters/stable
libcurl/7.56.1@bincrafters/stable
libcurl/7.60.0@bincrafters/stable
libcurl/7.61.1@bincrafters/stable
libcurl/7.64.1
libcurl/7.64.1@bincrafters/stable
libcurl/7.66.0
libcurl/7.66.0@bincrafters/stable
libcurl/7.67.0
libcurl/7.68.0
libcurl/7.69.1
libcurl/7.70.0
libcurl/7.71.0
libcurl/7.71.1
libcurl/7.72.0
libcurl/7.73.0
libcurl/7.74.0
libcurl/7.75.0
libcurl/7.76.0
libcurl/7.77.0
```
The conan remote setting have not been changed:
``` bash
$ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
```

The same is true for `meson/0.59.0` which is shown in the web UI but on the command line only version `meson/0.58.1` is available.

Normally i could wait for the newest version to arrive but at the moment i can not build libcurl for mingw on windows due to an issue with the version of meson or pkgconf available from the command line possibly related to #6767. This seems to be fixed in master but i can not easily get the version of the recipe that is in the master branch of this repo.

Also the commit #6452 that made the version of libcurl change is 25 days old. When are changes in this repo on master or in the web UI available from the command line with the `conan install` command?

**Comment by dmn-star** [comment]
You should use the new conancenter remote.

> conan search libcurl -r=all
Existing package recipes:

Remote 'conancenter':
libcurl/7.64.1
libcurl/7.66.0
libcurl/7.67.0
libcurl/7.68.0
libcurl/7.69.1
libcurl/7.70.0
libcurl/7.71.0
libcurl/7.71.1
libcurl/7.72.0
libcurl/7.73.0
libcurl/7.74.0
libcurl/7.75.0
libcurl/7.76.0
libcurl/7.77.0
libcurl/7.78.0

**Comment by Kasurus** [comment]
Thanks! That seems to work.

**Comment by Kasurus** [comment]
It would have been easier for me to figure out if the information would have been more prominent e.g. in the readme of this repo:
```
$ conan remote add conancenter https://center.conan.io
```
I would guess there are still some clients out there where this has to be done manually. Since the remote is not added when upgrading and Qt for example ships with version 1.33.1 of conan at the moment. The new remote had been changed in the 1.37 i would guess from the docs.

A other suggestion: I would have had a better chance to find the information to change the remote link if it had been in the docs not only under the topic `Uploading Packages`, because i was trying to use a package. So i might have seen it in the sections `Install`, `Getting Started` or `Using packages` in the docs.

Thanks again for the quick help!
