### ISSUE TITLE
[package] pcre2/10.37: Build fails on Linux when with_bipz2=True (Link error with BZip2)

### ISSUE THREAD

**Issue by daravi** [conan-io/conan-center-index#6914]
Issue in the root CMakeLists.txt of pcre2/10.37
Upstream bug report: https://bugs.exim.org/show_bug.cgi?id=2800

Let me know if you would like a patch PR. (or feel free to do it)

**Comment by SpaceIm** [comment]
It was fixed few months ago in bzip2 recipe, please update bzip2 recipe revision, so that it can generate proper CMake variables in FindBzip2.cmake

**Comment by daravi** [comment]
@SpaceIm Awesome. Thank you for pointing this out.
