### ISSUE TITLE
[question] is there a reason to hardcore macos version for qt6?

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#6915]
I see the following line in qt6 test package:
            if self.settings.os == "Macos":
                cmake.definitions['CMAKE_OSX_DEPLOYMENT_TARGET'] = '10.14'
Is there any reason having it there?

I am not sure, if it is related, as I haven't found hardcoded version in recipe itself, but I am always getting a linker error:

ld: warning: object file (/Users/andreimalashkin/.conan/data/libiconv/1.16/_/_/package/d98fae1010d1fb9e7f79a1e8a72bbf129d8660a2/lib/libiconv.a(relocatable.o)) was built for newer macOS version (11.0) than being linked (10.14)

**Comment by ericLemanissier** [comment]
I only remember I had to this to fix the test, but I'm not sure I found the root cause

**Comment by AndreyMlashkin** [comment]
I would just raise an error in conanfile.py in case it is lower.

**Comment by AndreyMlashkin** [comment]
So, maybe this warning comes from qt build scripts itself, then we could just report it upstream

**Comment by ericLemanissier** [comment]
Please post a full log of the failure you have without CMAKE_OSX_DEPLOYMENT_TARGET, so that we can try to understand and do some research

**Comment by AndreyMlashkin** [comment]
It's not a failure, it's only a warning, while compiling qt6 on macos. I will prepare a log

**Comment by ericLemanissier** [comment]
is this still an issue ?

**Comment by AndreyMlashkin** [comment]
It was only a warning, so it was never an issue
