### ISSUE TITLE
[package] Qt/5.15.2 Fails  to configure with MSVC 2019

### ISSUE THREAD

**Issue by tcanabrava** [conan-io/conan-center-index#6917]
I got a new machine, and just installed everything that I needed to start developing:
msvc and conan.

while trying to trigger a build for Qt 5.15.2, there's a configuration error because it complains about missing libraries.
(those where libraries that I assumed would be installed via conan)

* Conan Profile 
```
C:\Projects\build\diagram-server>conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

Small Excerpt of the Configure failure:
```

ERROR: Feature 'system-zlib' was enabled, but the pre-condition 'libs.zlib' failed.

ERROR: Feature 'zstd' was enabled, but the pre-condition 'libs.zstd' failed.

ERROR: Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && !features.schannel && libs.openssl' failed.

ERROR: Feature 'system-jpeg' was enabled, but the pre-condition 'features.jpeg && libs.libjpeg' failed.

ERROR: Feature 'system-png' was enabled, but the pre-condition 'features.png && libs.libpng' failed.

ERROR: Feature 'sql-psql' was enabled, but the pre-condition 'libs.psql' failed.

ERROR: Feature 'system-sqlite' was enabled, but the pre-condition 'features.sql-sqlite && libs.sqlite3' failed.
```

Full log was too large to paste here.

**Comment by ericLemanissier** [comment]
unfortunately we need the full log. you can use https://gist.github.com/ for example

**Comment by tcanabrava** [comment]
https://gist.github.com/tcanabrava/f16ade507b2e202b60b913e944d34c3f

**Comment by ericLemanissier** [comment]
the log has a lot of `warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'`, which is surprising, could you please clear ~/.conan/data, retry, and send the log ?

**Comment by tcanabrava** [comment]
Yes, sure. Just give me a few hours as I’m away from the computer now.

**Comment by tcanabrava** [comment]
a completely different windows and processor, the same error:
I just wanted to try to replicate, and I didn't had to do much:

https://gist.github.com/tcanabrava/43eabeaf3f2caefc7fd0060830f0e593

**Comment by tcanabrava** [comment]
I'm running conan from inside `Developer command prompt for VS 2019` 
(I'm not sure if this is the cause of the problems, honestly I'm a linux dev stuck on a windows box for the time being and trying to learn the differences.)

**Comment by tcanabrava** [comment]
as you told me that this could be a profile issue, I nuked the default profile and the data folder on ~/.conan/ and I'm trying a clean install with --build=qt
the --build=qt is important as there's no prebuild package for msvc 19 on the repos.

**Comment by tcanabrava** [comment]
No luck, same error: Be aware that this is with a completely new default profile without any cached data.
I think this is a high priority bug as Qt is quite widely used, and the inability to compile on msvc 19 makes hard to deal with.

Please instruct me on how to help - I have no knowledge of windows, but I'm already starting to contribute to conan with some pull requests.

https://gist.github.com/tcanabrava/228cf5d2131088ac0004421635a4110f

**Comment by ericLemanissier** [comment]
Could you please try to use  à 64 bits version of the Visual Studio command prompt? What version of Windows are you using? Please send your conanfile.

**Comment by tcanabrava** [comment]
(and I just found out that visual studio installs many different profiles for the cli, just triggered a x64 bit build - updating as soon as it finishes or fails)

**Comment by tcanabrava** [comment]
Closing, the build failure was my inability to develop in windows. using the x64 command line tools worked correctly.
