### ISSUE TITLE
[package] libjpeg-turbo/2.1.1: When cross compiling for arm the neon asm is not linked

### ISSUE THREAD

**Issue by KristianJerpetjon** [conan-io/conan-center-index#6936]
cross compile the libjpeg-turbo for arm and you get the slow c version not the optimized neon one.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.8**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
N/A

### Steps to reproduce (Include if Applicable)
cross compile the pacakge and look at the cmake output dropping SIMD optimalisations

### Logs (Include/Attach if Applicable)
libjpeg-turbo/2.1.1: Calling build()
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Check for working C compiler: /home/kristian/.conan/data/falcon-sdk/2021.05.1/huddly/latest/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/aarch64-linux-gcc
-- Check for working C compiler: /home/kristian/.conan/data/falcon-sdk/2021.05.1/huddly/latest/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/aarch64-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/kristian/.conan/data/falcon-sdk/2021.05.1/huddly/latest/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/aarch64-linux-g++
-- Check for working CXX compiler: /home/kristian/.conan/data/falcon-sdk/2021.05.1/huddly/latest/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/aarch64-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Adjusting fPIC flag (ON)
-- Conan: Compiler GCC>=5, checking major version 10
-- Conan: Checking correct version: 10
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 2.1.1, BUILD = 20210820
-- 64-bit build (x86_64)
-- CMAKE_INSTALL_PREFIX = /home/kristian/.conan/data/libjpeg-turbo/2.1.1/_/_/package/c8d8346d41953b97e238b71a6b7d5f99729b154f
-- CMAKE_INSTALL_BINDIR = bin (/home/kristian/.conan/data/libjpeg-turbo/2.1.1/_/_/package/c8d8346d41953b97e238b71a6b7d5f99729b154f/bin)
-- CMAKE_INSTALL_DATAROOTDIR = share (/home/kristian/.conan/data/libjpeg-turbo/2.1.1/_/_/package/c8d8346d41953b97e238b71a6b7d5f99729b154f/share)
-- CMAKE_INSTALL_DOCDIR = share/doc/libjpeg-turbo (/home/kristian/.conan/data/libjpeg-turbo/2.1.1/_/_/package/c8d8346d41953b97e238b71a6b7d5f99729b154f/share/doc/libjpeg-turbo)
-- CMAKE_INSTALL_INCLUDEDIR = include (/home/kristian/.conan/data/libjpeg-turbo/2.1.1/_/_/package/c8d8346d41953b97e238b71a6b7d5f99729b154f/include)
-- CMAKE_INSTALL_LIBDIR = lib (/home/kristian/.conan/data/libjpeg-turbo/2.1.1/_/_/package/c8d8346d41953b97e238b71a6b7d5f99729b154f/lib)
-- CMAKE_INSTALL_MANDIR = share/man (/home/kristian/.conan/data/libjpeg-turbo/2.1.1/_/_/package/c8d8346d41953b97e238b71a6b7d5f99729b154f/share/man)
-- Shared libraries disabled (ENABLE_SHARED = 0)
-- Static libraries enabled (ENABLE_STATIC = 1)
-- 12-bit JPEG support disabled (WITH_12BIT = 0)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper disabled (WITH_JAVA = 0)
-- Emulating libjpeg API/ABI v8.0 (WITH_JPEG7 = 1, WITH_JPEG8 = 1)
-- libjpeg API shared library version = 8.2.2
-- Compiler flags = -march=armv8-a+crc -mtune=cortex-a53 -O3 -pipe -mcpu=cortex-a53   -O3 -DNDEBUG
-- Linker flags =
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for memset
-- Looking for memset - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Check size of unsigned char
-- Check size of unsigned char - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Performing Test INCOMPLETE_TYPES
-- Performing Test INCOMPLETE_TYPES - Success
-- Compiler supports pointers to undefined structures.
-- Performing Test RIGHT_SHIFT_IS_UNSIGNED
-- Performing Test RIGHT_SHIFT_IS_UNSIGNED - Failed
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- THREAD_LOCAL = __thread
-- Performing Test HAVE_VERSION_SCRIPT
-- Performing Test HAVE_VERSION_SCRIPT - Success
-- Linker supports GNU-style version scripts
-- CMAKE_EXECUTABLE_SUFFIX =
-- Looking for a ASM_NASM compiler
-- Looking for a ASM_NASM compiler - NOTFOUND
CMake Warning at source_subfolder/simd/CMakeLists.txt:5 (message):
  SIMD extensions disabled: could not find NASM compiler.  Performance will
  suffer.
Call Stack (most recent call first):
  source_subfolder/simd/CMakeLists.txt:48 (simd_fail)

-- FLOATTEST = no-fp-contract
-- RPM architecture = x86_64, DEB architecture = amd64
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY

</details>

**Comment by SpaceIm** [comment]
AFAIR, it's a false warning, Neon is enabled. nasm doesn't make sense for arm architecture.

**Comment by SpaceIm** [comment]
Example:

profile build `macos-x86_64-clang12.0`

```
[settings]
os=Macos
arch=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

profile host `macos-armv8-clang12.0`

```
[settings]
os=Macos
arch=armv8
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

conan install

```
conan install libjpeg-turbo/2.1.1@ -pr:b macos-x86_64-clang12.0 -pr:h macos-armv8-clang12.0 -b libjpeg-turbo
```

log

```
libjpeg-turbo/2.1.1: Calling build()
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Adjusting fPIC flag (ON)
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 2.1.1, BUILD = 20210820
-- 64-bit build (arm64)
-- CMAKE_INSTALL_PREFIX = /Users/spaceim/.conan/data/libjpeg-turbo/2.1.1/_/_/package/cd1a2564713e9dd8c20b3ba739d889957c37e9d7
-- CMAKE_INSTALL_BINDIR = bin (/Users/spaceim/.conan/data/libjpeg-turbo/2.1.1/_/_/package/cd1a2564713e9dd8c20b3ba739d889957c37e9d7/bin)
-- CMAKE_INSTALL_DATAROOTDIR = share (/Users/spaceim/.conan/data/libjpeg-turbo/2.1.1/_/_/package/cd1a2564713e9dd8c20b3ba739d889957c37e9d7/share)
-- CMAKE_INSTALL_DOCDIR = share/doc/libjpeg-turbo (/Users/spaceim/.conan/data/libjpeg-turbo/2.1.1/_/_/package/cd1a2564713e9dd8c20b3ba739d889957c37e9d7/share/doc/libjpeg-turbo)
-- CMAKE_INSTALL_INCLUDEDIR = include (/Users/spaceim/.conan/data/libjpeg-turbo/2.1.1/_/_/package/cd1a2564713e9dd8c20b3ba739d889957c37e9d7/include)
-- CMAKE_INSTALL_LIBDIR = lib (/Users/spaceim/.conan/data/libjpeg-turbo/2.1.1/_/_/package/cd1a2564713e9dd8c20b3ba739d889957c37e9d7/lib)
-- CMAKE_INSTALL_MANDIR = share/man (/Users/spaceim/.conan/data/libjpeg-turbo/2.1.1/_/_/package/cd1a2564713e9dd8c20b3ba739d889957c37e9d7/share/man)
-- Shared libraries disabled (ENABLE_SHARED = 0)
-- Static libraries enabled (ENABLE_STATIC = 1)
-- 12-bit JPEG support disabled (WITH_12BIT = 0)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper disabled (WITH_JAVA = 0)
-- Emulating libjpeg API/ABI v8.0 (WITH_JPEG7 = 1, WITH_JPEG8 = 1)
-- libjpeg API shared library version = 8.2.2
-- Compiler flags =    -O3 -DNDEBUG
-- Linker flags =
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for memset
-- Looking for memset - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Check size of unsigned char
-- Check size of unsigned char - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Performing Test INCOMPLETE_TYPES
-- Performing Test INCOMPLETE_TYPES - Success
-- Compiler supports pointers to undefined structures.
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- THREAD_LOCAL = __thread
-- CMAKE_EXECUTABLE_SUFFIX =
-- Looking for vld1_s16_x3
-- Looking for vld1_s16_x3 - found
-- Looking for vld1_u16_x2
-- Looking for vld1_u16_x2 - found
-- Looking for vld1q_u8_x4
-- Looking for vld1q_u8_x4 - found
-- Use full Neon SIMD intrinsics implementation (NEON_INTRINSICS = ON)
-- SIMD extensions: arm64 (WITH_SIMD = 1)
-- FLOATTEST = no-fp-contract
-- Configuring done
-- Generating done
```

**Comment by KristianJerpetjon** [comment]
Must have been me
