### ISSUE TITLE
[request] certify/0.1

### ISSUE THREAD

**Issue by jhabermas** [conan-io/conan-center-index#6940]
### Package Details
  * Package Name/Version: **certify/0.1**
  * Website: **https://djarek.github.io/certify/**
  * Source code: **https://github.com/djarek/certify**

### Description Of The Library / Tool
Certify is a header-only library which abstracts away the details of accessing a platform's TLS keystore and performing verification of a TLS peer's certificate, according to [RFC2818](https://tools.ietf.org/html/rfc2818). The library depends on OpenSSL and is designed to be easy to integrate with `boost::asio::ssl`.

It greatly simplifies certificate handling when doing network programming with boost and is [recommended ](https://www.boost.org/doc/libs/develop/libs/beast/example/common/root_certificates.hpp) by `boost::beast` author.

**Comment by SpaceIm** [comment]
@uilianries @SSE4 @prince-chrismc certify has been added by https://github.com/conan-io/conan-center-index/pull/7533, so this issue can be closed.
