### ISSUE TITLE
Can't build BOOST 1.72.0 using Intel (ICC) 19.1.0.166

### ISSUE THREAD

**Issue by kwilliamszaf** [conan-io/conan-center-index#698]
Hi,

BOOST's "bootstrap.sh" requires a toolset called "intel-linux" or "intel-darwin", and fails for the toolset "intel".

OS: Debian 9
Compiler: icc 19.1.0.166
BOOST version: 1.72.0

Regards, Kevin

**Comment by SSE4** [comment]
valid bootstrap toolsets:

- [intel-win32](https://github.com/boostorg/build/blob/develop/src/engine/build.bat#L31)
- [intel-darwin](https://github.com/boostorg/build/blob/develop/src/engine/build.sh#L34)
- [intel-linux](https://github.com/boostorg/build/blob/develop/src/engine/build.sh#L34)

valid b2 toolsets (a bit different naming):

- [intel-win](https://github.com/boostorg/build/blob/develop/src/tools/intel-win.jam)
- [intel-darwin](https://github.com/boostorg/build/blob/develop/src/tools/intel-darwin.jam)
- [intel-linux](https://github.com/boostorg/build/blob/develop/src/tools/intel-linux.jam)

need some testing, but changes should be pretty straightforward

**Comment by SSE4** [comment]
@kwilliamszaf it also would be helpful if you could provide your full conan profile (e.g. `conan profile show default` or `conan profile show intel` output)

**Comment by kwilliamszaf** [comment]
Hi @SSE4, yes sure.

Something seems to have changed, in that the BOOST recipe in conan-center-index now **does** actually call bootstrap.sh correctly, but there are linkage errors. (It appears that the Intel libraries are not found.)

So:

1. If I call `./bootstrap.sh --with-toolset=intel-linux` directly in the BOOST source folder in my Conan cache, it compiles correctly.
2. If not (i.e. call `conan create . boost/1.72.0@conan/stable --pr intel --build missing`) it can't resolve Intel library functions like "_intel_fast_memcpy()". (I have sourced compilervars.sh, and I can see several Intel environment variables correctly set.)

My Intel profile is:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=intel
compiler.version=19
build_type=Release
compiler.base=gcc
compiler.base.libcxx=libstdc++11
compiler.base.version=6.3
[options]
[build_requires]
[env]

**Comment by SSE4** [comment]
@kwilliamszaf does the `_intel_fast_memcpy` error come from boost build? do you have a complete log?
as I understand, it's compiler runtime, and it's needed to link with `-lintlc`

**Comment by SSE4** [comment]
@kwilliamszaf by the way, I've created PR with proposed fix: https://github.com/conan-io/conan-center-index/pull/752
it would be nice if you can test it locally and lemme know how does it work for you

**Comment by kwilliamszaf** [comment]
Hi @SSE4, @danimtb 

I pulled the latest changes, and it seems to get further but breaks trying to link the test packages.

The log is very long, but here is an extract where the first failure occurs:

-- Build files have been written to: /home/kwilliams/git_work/conan-center-index/recipes/boost/all/test_package/build/1e557cdf055bcb45ebc7decbeea15b7de523ae91
Scanning dependencies of target random_exe
Scanning dependencies of target lambda
[ 10%] Building CXX object CMakeFiles/random_exe.dir/random.cpp.o
[ 20%] Building CXX object CMakeFiles/lambda.dir/lambda.cpp.o
Scanning dependencies of target regex_exe
Scanning dependencies of target newregex
Scanning dependencies of target test
[ 30%] Building CXX object CMakeFiles/regex_exe.dir/regex.cpp.o
[ 40%] Building CXX object CMakeFiles/newregex.dir/regex.cpp.o
[ 50%] Building CXX object CMakeFiles/test.dir/test.cpp.o
[ 60%] Linking CXX executable bin/random_exe
/home/kwilliams/.conan/data/boost/1.72.0/conan/stable/package/57158c3593481ebf7b6001923ce884d88018adaa/lib/libboost_random.a(random_device.o): In function `boost::random::random_device::random_device()':
random_device.cpp:(.text+0x6b): undefined reference to `__intel_sse2_strlen'
random_device.cpp:(.text+0xd8): undefined reference to `_intel_fast_memcpy'
random_device.cpp:(.text+0x171): undefined reference to `_intel_fast_memcpy'
random_device.cpp:(.text+0x4d5): undefined reference to `_intel_fast_memcpy'
random_device.cpp:(.text+0x664): undefined reference to `_intel_fast_memcpy'
/home/kwilliams/.conan/data/boost/1.72.0/conan/stable/package/57158c3593481ebf7b6001923ce884d88018adaa/lib/libboost_random.a(random_device.o): In function `boost::random::random_device::random_device()':

**Comment by SSE4** [comment]
@kwilliamszaf could you enable verbose logging?
(e.g. by adding `cmake.verbose = True` after the following line: https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/test_package/conanfile.py#L12)
it would be helpful to know all the compiler/linker flags applied. 
from the log, it seems like Intel runtime libraries aren't linked, but AFAIK it should be automatic.

**Comment by kwilliamszaf** [comment]
I don't see too much more info. (Can I email you the full log?)

It's curious that the Intel libraries are not mentioned in the link command.

[ 60%] Linking CXX executable bin/random_exe
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/random_exe.dir/link.txt --verbose=1
/usr/bin/c++     -O3 -DNDEBUG        -rdynamic CMakeFiles/random_exe.dir/random.cpp.o  -o bin/random_exe   -L/home/kwilliams/.conan/data/boost/1.72.0/conan/stable/package/57158c3593481ebf7b6001923ce884d88018adaa/lib  -L/home/kwilliams/.conan/data/zlib/1.2.11/_/_/package/bab457b63b2fcbf923fc7c2ed3697455732774a0/lib  -L/home/kwilliams/.conan/data/bzip2/1.0.8/_/_/package/486e0f191feb7972653c557844fcc39be195866a/lib  -Wl,-rpath,/home/kwilliams/.conan/data/boost/1.72.0/conan/stable/package/57158c3593481ebf7b6001923ce884d88018adaa/lib:/home/kwilliams/.conan/data/zlib/1.2.11/_/_/package/bab457b63b2fcbf923fc7c2ed3697455732774a0/lib:/home/kwilliams/.conan/data/bzip2/1.0.8/_/_/package/486e0f191feb7972653c557844fcc39be195866a/lib /home/kwilliams/.conan/data/boost/1.72.0/conan/stable/package/57158c3593481ebf7b6001923ce884d88018adaa/lib/libboost_random.a /home/kwilliams/.conan/data/boost/1.72.0/conan/stable/package/57158c3593481ebf7b6001923ce884d88018adaa/lib/libboost_regex.a
/home/kwilliams/.conan/data/boost/1.72.0/conan/stable/package/57158c3593481ebf7b6001923ce884d88018adaa/lib/libboost_random.a(random_device.o): In function `boost::random::random_device::random_device()':
random_device.cpp:(.text+0x6b): undefined reference to `__intel_sse2_strlen'
random_device.cpp:(.text+0xd8): undefined reference to `_intel_fast_memcpy'
random_device.cpp:(.text+0x171): undefined reference to `_intel_fast_memcpy'
random_device.cpp:(.text+0x4d5): undefined reference to `_intel_fast_memcpy'
random_device.cpp:(.text+0x664): undefined reference to `_intel_fast_memcpy'

**Comment by kwilliamszaf** [comment]
I see I can upload files here...

[log.zip](https://github.com/conan-io/conan-center-index/files/4143576/log.zip)

**Comment by SSE4** [comment]
I see it uses `/usr/bin/c++`, is it symlink to intel compiler in your case?
could you check `/usr/bin/c++ --version` and `ls -lah /usr/bin/c++`?

**Comment by kwilliamszaf** [comment]
It eventually leads to x86_64-linux-gnu-g++-6 via a couple of symlinks.

/usr/bin/c++ --version
c++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ls -lah /usr/bin/c++
lrwxrwxrwx 1 root root 21 Dec  2 12:23 /usr/bin/c++ -> /etc/alternatives/c++

**Comment by SSE4** [comment]
probably, you haven't configured compiler correctly for CMake, from your log:
```
boost/1.72.0@conan/stable (test package): Running build()
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
```
try to set **CC** and **CXX** environment variables to the **icpc** within your conan profile.

**Comment by SSE4** [comment]
you have said you're using `compilervars.sh`, I am not sure if it sets **CC** and *CXX**, but it appears like CMake uses default compiler (GCC) instead of Intel

**Comment by kwilliamszaf** [comment]
Apologies, I forgot to run `compilervars.sh` this time.

It doesn't set CC/CXX, but setting these manually works 100%.

Thanks for your help!
