### ISSUE TITLE
[question] support Visual Studio build for libftdi

### ISSUE THREAD

**Issue by SamsonBox** [conan-io/conan-center-index#6983]
Hello,
I'm new here and maybe it's a stupid question or answered already a lot of times. So, I need the Visual Studio build for the libftdi package. I modified the existing package already here: `https://github.com/SamsonBox/conan-center-index/tree/libftdi_1.5_vs`. What is the common procedure to update an existing package? Is a pull request the right way?

**Comment by dmn-star** [comment]
> Is a pull request the right way?

Yes. You should still register for early  access program . Please leave a comment here https://github.com/conan-io/conan-center-index/issues/4

**Comment by SamsonBox** [comment]
@dmn-star Thank you. I'm already registered.
