### ISSUE TITLE
[service] Check folder lowercase at the beginning

### ISSUE THREAD

**Issue by lasote** [conan-io/conan-center-index#70]
If the folder containing the recipe is not lowercase the error is on the export and it is very confusing. Check the folder lowercase first.

**Comment by danimtb** [comment]
We have a hook in place checking that the reference is lowercase https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#kb-h002-reference-lowercase

I believe it does not check the folder casing but I am fine with this as it is not causing trouble
