### ISSUE TITLE
[package] icu/1.68: Android cross-build issue

### ISSUE THREAD

**Issue by granger35** [conan-io/conan-center-index#7046]
### Package and Environment Details
  * Package Name/Version: icu/1.68.0
  * Operating System+version: **Linux Ubuntu 18.04**
  * Docker image: **conanio/android-clang_8-armv8**
  * Conan version: **1.39.0**
  
### Conan profile
```
[settings]
os=Android
os_build=Linux
arch=armv8
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
os.api_level=21
compiler.cppstd=17
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conan install icu/68.2@ --build=missing

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=armv8
arch_build=x86_64
build_type=Release
compiler=clang
compiler.cppstd=17
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=21
os_build=Linux
[options]
[build_requires]
[env]

icu/68.2: Not found in local cache, looking in remotes...
icu/68.2: Trying with 'conan-solar'...
icu/68.2: Trying with 'conan-bcom'...
icu/68.2: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.36k]                                          
Downloading conanfile.py completed [16.95k]                                              
Downloading conan_export.tgz completed [0.32k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
icu/68.2: Downloaded recipe revision 0
Installing package: icu/68.2
Requirements
    icu/68.2 from 'conancenter' - Downloaded
Packages
    icu/68.2:3a7ffa4ba95e7de32121bbb457fc97cc2f616d74 - Build

Cross-build from 'Linux:x86_64' to 'Android:armv8'
Installing (downloading, building) binaries...
Downloading conan_sources.tgz completed [1.28k]                                          
Decompressing conan_sources.tgz completed [0.00k]                                        
icu/68.2: Configuring sources in /home/conan/.conan/data/icu/68.2/_/_/source
Downloading icu4c-68_2-src.tgz:  17%|#7        | 4.10M/23.6M [00:00<00:00, 42.8MDownloading icu4c-68_2-src.tgz:  56%|#####6    | 13.3M/23.6M [00:00<00:00, 70.6M                                                                                Downloading icu4c-68_2-src.tgz completed [24157.69k]                                     

icu/68.2: Copying sources to build folder
icu/68.2: Building your package in /home/conan/.conan/data/icu/68.2/_/_/build/3a7ffa4ba95e7de32121bbb457fc97cc2f616d74
icu/68.2: Generator txt created conanbuildinfo.txt
icu/68.2: Aggregating env generators
icu/68.2: Calling build()
icu/68.2: 
icu/68.2: ERROR: Package '3a7ffa4ba95e7de32121bbb457fc97cc2f616d74' build failed
icu/68.2: WARN: Build folder /home/conan/.conan/data/icu/68.2/_/_/build/3a7ffa4ba95e7de32121bbb457fc97cc2f616d74
ERROR: icu/68.2: Error in build() method, line 139
	self.run(self._build_config_cmd, win_bash=tools.os_info.is_windows)
while calling '_build_config_cmd', line 194
	bin_path = self.deps_env_info["icu"].PATH[0]
```

</details>

**Comment by dmn-star** [comment]
Try my profiles

> conan install icu/68.2@ --build=missing --profile:host ./profiles/android  --profile:build ./profiles/mac --update 

Configuration (profile_host):
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=12
os=Android
os.api_level=21
[options]
[build_requires]
*: android-ndk/r22b, cmake/3.21.1, ninja/1.10.2
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=14
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
[options]
[build_requires]
[env]

<img width="644" alt="icu68" src="https://user-images.githubusercontent.com/52277783/130789468-23e1a8ff-2ed5-41a2-81c1-388dd8ee31b7.png">

**Comment by SpaceIm** [comment]
Yes, CCI recipes are designed for 2 profiles approach when cross-building. Some recipes might work with 1 profile, but it's not recommended anymore.
For sure icu recipe can't work with 1 profile when you cross-build.

**Comment by granger35** [comment]
Thank you,

Works well for the following profiles:

Configuration (host)
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=12
os=Android
os.api_level=21
compiler.cppstd=17
[options]
[conf]
[build_requires]
[env]

Configuration (build)
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7
os=Linux
compiler.cppstd=17
[options]
[conf]
[build_requires]
[env]
