### ISSUE TITLE
[package] spdlog/1.9.x: Not available for VS 2019

### ISSUE THREAD

**Issue by TheStormN** [conan-io/conan-center-index#7047]
### Package and Environment Details
  * Package Name/Version: **spdlog/1.9.x**
  * Operating System+version: **Windows 10 21H1**
  * Compiler+version: **MSVC 16.11.1**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.7.8**(Coming from VS installer)

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Debug
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce
Just try to install any version of spdlog from the 1.9.x train and it will fail.

### Logs
<details><summary>Click to expand log</summary>

```
1> [CMake] spdlog/1.9.1: Not found in local cache, looking in remotes...
1> [CMake] spdlog/1.9.1: Trying with 'conan-center'...
1> [CMake] ERROR: Failed requirement 'spdlog/1.9.1' from 'conanfile.py'
1> [CMake] ERROR: Unable to find 'spdlog/1.9.1' in remotes
1> [CMake] CMake Error at cmake/conan.cmake:522 (message):
1> [CMake]   Conan install failed='1'
1> [CMake] Call Stack (most recent call first):
1> [CMake]   cmake/conan.cmake:759 (old_conan_cmake_install)
1> [CMake]   CMakeLists.txt:54 (conan_cmake_run)
1> [CMake] -- Configuring incomplete, errors occurred!
```

</details>

**Comment by SpaceIm** [comment]
Have you updated your remote?
https://blog.conan.io/2021/06/10/New-conan-release-1-37.html

**Comment by dmn-star** [comment]
https://github.com/conan-io/conan-center-index/issues/6900#issuecomment-900558989

Wonder why this doesn't happen automatically with conan client update.

**Comment by TheStormN** [comment]
@SpaceIm Yep, seems to work, but still there is an issue with JFrog artifactory which we use. From my understandings the artifactory should be a mirror to Conan Center if the requested package is not uploaded there, but if I leave it as the only remote, it still fails to find the package. Should some kind of migration be done there too?

**Comment by dmn-star** [comment]
Please check if https://center.conan.io/ is configured as remote repo in Artifactoty.

**Comment by TheStormN** [comment]
I will double check with the admin, still wondering why all these migration things are not automated...

Closing this for now. Will raise an issue with JFrog staff if needed.
