### ISSUE TITLE
[package] mongo-cxx-driver/3.6.1: "could not start SASLPrep for password" when connecting with user name/password

### ISSUE THREAD

**Issue by fabienfondacci** [conan-io/conan-center-index#7068]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **mongo-cxx-driver/3.6.1**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 7**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

This issue was already reported to mongoDB in this ticket: https://jira.mongodb.org/browse/CXX-2201
Unfortunately, they were not able to reproduce this behavior outside of a Conan environment. 
Can you please check if something went wrong with the conan packaging of mongo-cxx-driver/mongo-c-driver?

To reproduce you can download this file: https://jira.mongodb.org/secure/attachment/320965/minimalMongoSetup.zip
After unzipping and working inside the extracted directory, steps are as follows:

1. cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=11 -G "CodeBlocks - Unix Makefiles" 
2. make
3. ./bin/minimalMongoSetup "mongodb://uri-path"
with uri-path the path to your running mongoDB instance (for example: "mongodb://userName:password@localhost:27017/?authSource=admin")

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Exception: could not start SASLPrep for password: generic server error
```

</details>

**Comment by perseoGI** [comment]
Hi @fabienfondacci, 
I was reviewing old issues and I have come across this one.
This version of `mongo-cxx-driver` is pretty old.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays with newer versions, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
