### ISSUE TITLE
[package] qt: 5.15.2 - wayland / libffi issue (using old build repository bincrafters/conan-qt)

### ISSUE THREAD

**Issue by EugenMayer** [conan-io/conan-center-index#7072]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Conan version 1.39.0
conan profile information
default
goedit_general
Configuration for profile default:

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
os=Linux
os_build=Linux
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
[options]
glib:shared=False
libx11:shared=True
libxcb:share=True
qca:shared=True
qt:opengl=no
qt:qttools=True
qt:shared=True
qt:with_fontconfig=True
qt:with_harfbuzz=False
qt:with_libalsa=False
qt:with_libjpeg=False
qt:with_libpng=True
qt:with_mysql=False
qt:with_odbc=False
qt:with_openal=False
qt:with_pcre2=True
qt:with_pq=False
qt:with_sdl2=False
qt:with_sqlite3=False
qt:with_zstd=False
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Compile Qt 5.15.2

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: Conflict in wayland/1.19.0:
    'wayland/1.19.0' requires 'libffi/3.4.2' while 'glib/2.67.0' requires 'libffi/3.3'.
    To fix this conflict you need to override the package 'libffi' in your root package.

```

</details>

**Comment by EugenMayer** [comment]
sorry @ericLemanissier - either i'am stuck somehow or whatever. This is the raw-log copy pasted, entirely https://gist.github.com/EugenMayer/dd6fd8cd71cef297e1c5c2bb76573148

I could not have any more logs for this, this is all I have on the CI - what is missing in particular?

Please be aware, QT is not build in this, but build in a separate CI tasks, pushed to jfrog conan center (our own) and then consumed here. 

Thank you for all the effort

**Comment by ericLemanissier** [comment]
this has all the information needed: `error: Qt requires a C++11 compiler and yours does not seem to be that.`. Maybe it would be fixed by defining compiler.cppstd to the proper value in your profile.
Anyway, I encourage you to continue discussion [on slack](https://cpplang.slack.com/?id=conan), because this problem is not related at all with conan-center.

**Comment by ericLemanissier** [comment]
I think this issue can be closed, because the original problem is on a bincrafters recipe, and subsequent issues have been addressed on slack

**Comment by EugenMayer** [comment]
> I think this issue can be closed, because the original problem is on a bincrafters recipe, and subsequent issues have been addressed on slack

Thank you so much for helping. Should anybody stumble across this, in quick recap

conan-center QT has

- new / other / reduced flags, so you have to adjust flags or adjust flags for specific OS types (like e.g. fontaconfig, alsa)
- the new recipe for QT uses conan to generate the cmake configuration, that is why when you build something depending on QT you will require to run `conan_basic_setup`, have a look at https://github.com/KontextWork/conan-qca/blob/stable/2.3.2/conanfile.py#L45

I hope I did not not miss anything else, eric was helping me left and right like a tsunami!
