### ISSUE TITLE
[request] basis_universal/1.15

### ISSUE THREAD

**Issue by onehundredfeet** [conan-io/conan-center-index#7087]
### Package Details
  * Package Name/Version: **basis_universal/1.15**
  * Website: **https://github.com/BinomialLLC/basis_universal**
  * Source code: **https://github.com/BinomialLLC/basis_universal**

### Description Of The Library / Tool

Basis Universal Supercompressed GPU Texture Codec

Basis Universal is a "supercompressed" GPU texture data interchange system that supports two highly compressed intermediate file formats (.basis or the .KTX2 open standard from the Khronos Group) that can be quickly transcoded to a very wide variety of GPU compressed and uncompressed pixel formats

**Comment by SpaceIm** [comment]
@uilianries @SSE4 @prince-chrismc basis_universal (libbasisu) has been added by https://github.com/conan-io/conan-center-index/pull/6468, so this issue can be closed.
