### ISSUE TITLE
[service] Add Apple Clang 11 support

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#71]
The service should generate packages for Apple Clang 11 / XCode 11.

If added the wiki should be updated as well: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Please don't forget to update the wiki, it doesn't list Clang 8 and GCC 9 yet for instance**

**Comment by Croydon** [comment]
Judging by the wiki edit and some comments in some PR.. is this already done? 🤔

**Comment by danimtb** [comment]
Yes, this should be already in place. Thanks!
