### ISSUE TITLE
[request] abseil/latest

### ISSUE THREAD

**Issue by Samuel-Tyler** [conan-io/conan-center-index#710]
### Package Details
  * Package Name/Version: **abseil/latest**
  * Website: **https://abseil.io/docs/cpp/quickstart**
  * Source code: **https://github.com/abseil/abseil-cpp?files=1**

### Description Of The Library / Tool
Abseil is an open source collection of C++ libraries drawn from the most fundamental pieces of Google’s internal codebase. These libraries are the nuts-and-bolts that underpin almost everything Google runs. Bits and pieces of these APIs are embedded in most of our open source projects, and Abseil aims to bring them together into one comprehensive project. Abseil encompasses the most basic building blocks of Google’s codebase: code that is production-tested and will be fully maintained for years to come.

### Note
Abseil makes updates frequently and supports a "live at head" mantra. Ideally the version would be frequently updated.

**Comment by uilianries** [comment]
You can use https://github.com/bincrafters/conan-abseil as reference.

NOTE: `tools.collect_libs` is not a good, as the libraries order matters for static link.

**Comment by Minimonium** [comment]
@uilianries There is a problem with Abseil removing releases on the GitHub page from time to time. Some releases pointed from the Bincrafters repo do not exist anymore. How should it be solved in the context of the CCI?

**Comment by uilianries** [comment]
> Abseil removing releases on the GitHub page from time to time. 

I didn't know about! We can mirror the source package to JFrog Bintray :)

**Comment by Croydon** [comment]
> There is a problem with Abseil removing releases on the GitHub page from time to time.

I feel like this is a huge anti-pattern. Do they explain somewhere why they are doing this?

**Comment by Croydon** [comment]
In this specific case I wouldn't go for mirroring. When it is hosted on GitHub we can download the zip file of a specific git commit instead of a release zip

**Comment by Minimonium** [comment]
@Croydon No, I just realized that they have much fewer releases now than used by the Bincrafters' recipe. 
Nice idea about the specific git commit link! Didn't about it, thanks!

**Comment by uilianries** [comment]
Yeah, I totally forgot about github commit
