### ISSUE TITLE
[service] Selectively trigger builds

### ISSUE THREAD

**Issue by bmanga** [conan-io/conan-center-index#713]
It would be useful to be able to selectively choose which build(s) the CI should run.
This would be helpful to fix and test configurations on platforms you don't have access to, avoiding the waste to rebuild ones unrelated with a particular change.
For example, it would have been easier for me to only test the latest change in #705 on the failing configuration (win msvc v15 static), and would have saved compute time on the CI end.

**Comment by ericriff** [comment]
I would also like to have access to a feature like this. In order to debug a build that takes about 10 minutes per config I ended up using ConanInvalidConfiguration. This is far from ideal because it will stay on the git history.

**Comment by danimtb** [comment]
Closing this issue as there are no plans to develop this feature so far.

We strongly recommend users to try this by themselves as the conan-center-index CI is not prepared to be used as CI, but as a way to actually build packages.

Thank you!
