### ISSUE TITLE
[service] Cannot view c3i build logs

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#7130]
When wanting to view the c3i build logs, we are 302 re-directed to https://c3i.jfrog.io/ui/native/misc/summary.html .
That makes it currently impossible to view the logs.

e.g.
- https://github.com/conan-io/conan-center-index/pull/7108#issuecomment-907969146
- Click on [All logs](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/7108/3-production/libxml2/2.9.12//summary.json)
- We get a 302 redirection:
    ```
    HTTP/1.1 302 Found
    Date: Tue, 31 Aug 2021 19:48:21 GMT
    Content-Length: 0
    Connection: keep-alive
    Location: https://c3i.jfrog.io/ui/native/misc/summary.html
    Strict-Transport-Security: max-age=15724800; includeSubDomains
    X-Request-ID: df1e10d49003b9910e65568f99893ed0
    ```
- My browser wants to download [summary.html](https://c3i.jfrog.io/ui/native/misc/summary.html) to disk, instead of opening it in the browser and displaying the results.

@jgsogo @uilianries

**Comment by uilianries** [comment]
@madebr Thank you for reporting! In fact it should not happen!

**Comment by SSE4** [comment]
I think it's fixed now
