### ISSUE TITLE
[conan.io/center] allpackages view silently truncates at 1000 packages

### ISSUE THREAD

**Issue by claremacrae** [conan-io/conan-center-index#7134]
After reading #339, I had a look at https://conan.io/center/allpackages

It says there are a nice round 1000 packages:

![image](https://user-images.githubusercontent.com/4840096/131640485-8dd26342-c526-4b2c-a534-3827ead1f16b.png)

Looking at the latest code - 2e7a6337804325616f8d97e3a5b6f66cc72699cb as I write - I get:

```bash
pwd
/Users/clare/Documents/develop/Conan/conan-center-index/recipes
ls -l | wc -l
    1038
```

Is it a coincidence that 38 recipes have been added since https://conan.io/center/allpackages was last updated - or is there perhaps some hard-coded limit of 1000 hidden somewhere in the code that generates that page?

**Comment by dmn-star** [comment]
GitHub? 
<img width="915" alt="1000_truncated" src="https://user-images.githubusercontent.com/52277783/132026703-d62ee07a-8099-41ff-8a3d-ef0f99a69572.png">

**Comment by claremacrae** [comment]
> GitHub?

Ooh - that screenshot is really interesting!

**Comment by eigenwhat** [comment]
Incidentally, as of now, both `/allpackages` and the GitHub directory listing for `recipes/` end at `vulkan-memory-allocator`, so I reckon it's being truncated in a similar fashion.

**Comment by claremacrae** [comment]
> Incidentally, as of now, both `/allpackages` and the GitHub directory listing for `recipes/` end at `vulkan-memory-allocator`, so I reckon it's being truncated in a similar fashion.

Thank you.

From a Conan user perspective, I can understand that GitHub truncating the view in https://github.com/conan-io/conan-center-index/tree/master/recipes is out of Conan's control. It's GitHub code....

But it feels to me like https://conan.io/center/allpackages (which is the subject of this ticket) is in Conan's control and so should not truncate the list...

And if it is truncated because it's using the same mechanism to get the list of repos that 
https://github.com/conan-io/conan-center-index/tree/master/recipes is using, ideally a different implement should be found...

**Comment by claremacrae** [comment]
Also the [GitHub view](https://github.com/conan-io/conan-center-index/tree/master/recipes) warns that this list is truncated...

![image](https://user-images.githubusercontent.com/4840096/133429192-7b1984bf-e0f0-49f8-83dd-a7902c5d1b28.png)

Whereas the Conan view just silently truncates the list...

Perhaps a temporary workaround would be to add a banner to the [Conan view](https://conan.io/center/allpackages) letting people know the list is truncated?
