### ISSUE TITLE
[question] mingw import libraries

### ISSUE THREAD

**Issue by dvirtz** [conan-io/conan-center-index#7150]
mingw-w64 on Linux, when building shared libraries, generates `.dll.a` import libraries. `tools.collect_libs` only recognize `.a` suffixes so it will return the library with the `.dll` part. On the other hand, most recipes, when setting `cpp_info.libs` directly don't append `.dll` in this case but I couldn't find issues which have been opened because of that and recent changes even removed such code as in https://github.com/conan-io/conan-center-index/commit/731a7bfa7b1dfd26004c0f30d43fadc875f56f89. 

Also, the [KB-H054](https://github.com/conan-io/hooks/blob/5a4810657b358591c5805469f0dd2b78715efc4e/hooks/conan-center.py#L970) hook will fail if the `.dll` part is omitted.

What is the correct behavior? 
Will using a recipe work with and without the `.dll` part?
Should the library name contain `.dll` or should `tool.collect_lib` remove it?

**Comment by SpaceIm** [comment]
It doesn't matter in term of link, MinGW is smart enough to link to .dll.a lib even if .dll was omitted.

KB-H054 should be fixed.

**Comment by dvirtz** [comment]
opened an issue in hooks
