### ISSUE TITLE
[request] tensorflow-lite

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#7165]
It's odd that one of the most popular C++ libraries is not available in the index

**Sources**: https://github.com/tensorflow/tensorflow
**Build instructions** (Newer versions support CMake yay): https://www.tensorflow.org/lite/guide/build_cmake **PLEASE READ MY COMMENT BELOW**.

Mandatory dependencies | Available in index?
```
find_package(absl REQUIRED) 		✔  (Same as abseil? The find module name matches)
find_package(eigen REQUIRED)		✔ 
find_package(farmhash REQUIRED) 	✔ (Partial implementation: Windows not supported)
find_package(fft2d REQUIRED)		✔ (Same as fft? fft2d is in the topics of the recipe)
find_package(flatbuffers REQUIRED)	✔ 
find_package(gemmlowp REQUIRED)		x (https://github.com/google/gemmlowp | Also missing on tiny-dnn)
find_package(neon2sse REQUIRED)		✔ (Conan name: intel-neon2sse)
find_package(ruy REQUIRED)			✔
```

Optional dependencies:
```
find_package(opencl_headers REQUIRED)
find_package(vulkan_headers REQUIRED)
find_package(fp16_headers REQUIRED)
find_package(opengl_headers REQUIRED)
find_package(egl_headers REQUIRED)
find_package(fp16_headers REQUIRED)
find_package(xnnpack REQUIRED)
```

I started working on it but I had to stop since I don't have the time. I may pick it back up eventually.

Free tip that made me scratch my head for a while:
The `find` modules this library provides are non regular find modules, they pull sources and build the dependencies at cmake configure time.

**Comment by ericriff** [comment]
I won't be driving this effort anymore since my team no longer needs it.
For the dev that decides to carry this:
My team strongly suggested using the bazel build instead of the CMake version. This is because google treats the CMake build system as a second class citizen, usually gets outdated, library names do not match the ones on bazel (which are the official names), only tensorflow-lite is supported but not the whole tensorflow suite.

**Comment by SSE4** [comment]
#7855 has been merged
