### ISSUE TITLE
[question] There is any way to async this repo to my private repo?

### ISSUE THREAD

**Issue by zh1an** [conan-io/conan-center-index#7191]
I've set up private repo service, but some receipes in the conan-center-index repo, what can I do without add one by one manaually, or there is any way to async this two repo?

**Comment by uilianries** [comment]
Yes. You can fork this repository and it as upstream:

- Clink fork button on https://github.com/conan-io/conan-center-index
- Clone your copy: git clone https://github.com/zh1an/conan-center-index
- Set CCI as upstream: git remote add upstream https://github.com/conan-io/conan-center-index

Now you just need to run `git pull upstream master` to synchronize
