### ISSUE TITLE
[service] Build `header_only=False` when `True` by default

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#7267]
Splitting of from https://github.com/conan-io/conan-center-index/pull/7238#issuecomment-916845706

//cc @jgsogo

**Comment by jgsogo** [comment]
Added to the backlog. We need to revisit the logic we use to generate the profiles.

**Comment by Croydon** [comment]
Was this ever discussed?

**Comment by RubenRBS** [comment]
Have you noticed any issues with it? As far as I can tell, the header_onlyhandling is properly implemented now (and in the new soon-to-come pipeline!)

**Comment by Croydon** [comment]
Indeed, seems to be fixed

True by default, builds False:
https://github.com/conan-io/conan-center-index/blob/7893fb193c478e92b1d14ed90bceb16d7f86e88e/recipes/chaiscript/all/conanfile.py#L29C1-L29C44
https://conan.io/center/recipes/chaiscript?version=6.1.0 (package with no os/options etc displayed is `header_only=True`)

False by default, builds True:
https://github.com/conan-io/conan-center-index/blame/7893fb193c478e92b1d14ed90bceb16d7f86e88e/recipes/libigl/all/conanfile.py#L33
https://conan.io/center/recipes/libigl?version=2.5.0
