### ISSUE TITLE
[question] How should imgui docking branch be supported?

### ISSUE THREAD

**Issue by timothyqiu** [conan-io/conan-center-index#7273]
[imgui](https://github.com/ocornut/imgui) maintains two branches: `master` and `docking`.

* `master` is released with proper versioning.
* `docking` is where docking & multi-viewport support are currently maintained. It's not released by version, but syncs regularly with `master`.

Conan center currently includes the `master` branch releases. I'm wondering how this `docking` branch situtation could be supported.

**Comment by Croydon** [comment]
Creating releases for dev git branches, would be rather random and given that branches get deleted, rebased etc. the Conan packages could just stop working at any given point.

Even if projects do official pre-releases we do not normally add them, only stable releases, unless there is a very good reason. Mostly, when the projects are dead or don't do any stable release in years. Given that imgui is actively maintained, I'm not really seeing the point.

**Comment by timothyqiu** [comment]
Thanks for the answer. I understand that supporting dev branches is not a good idea. However, imgui's `docking` branch is kind of special. It's a well maintained branch and is recommended to use according to the [wiki](https://github.com/ocornut/imgui/wiki/docking#preamble):

> Docking is currently available in the docking branch. This is a well maintained branch and most large teams have been using this branch for a while. It is safe and recommended to use that branch.

If this is not desired, is there a way to customize conan to use a different branch? Or one have to create a private package?

**Comment by Croydon** [comment]
You would need to create a private package
