### ISSUE TITLE
[request] Add issue templates similar to the ones in bincrafters repository

### ISSUE THREAD

**Issue by darcamo** [conan-io/conan-center-index#73]
The [bincrafters](https://github.com/bincrafters/community/issues) repository has some nice issue templates that really help. They make creating new issues easier and more consistent. 

For instance, when creating a new issue a user can select the **Upstream Update** template and the only thing he/she needs to do is filling the library name and version. This improves consistence and maybe the CI could parse these kinds of issues and try to just change the library version in the conan recipe and build it again.

**Comment by Croydon** [comment]
Absolutely agree. I was planning to create a pull request for this soon 👍

**Comment by uilianries** [comment]
Related PR: https://github.com/conan-io/conan-center-index/pull/20
