### ISSUE TITLE
[Service] Duplicate package id is being generated in CI for `libstdc++11` and `libstd++`.

### ISSUE THREAD

**Issue by dheater** [conan-io/conan-center-index#7313]
When the attached PR was submitted for `libcurl`, on Linux, the same package id is being generated in CI when compiled with `libstdc++11` and `libstd++`.

This is causing CI to fail with status `DUPLICATED`

_Originally posted by @dheater in https://github.com/conan-io/conan-center-index/issues/7311#issuecomment-921026926_

**Comment by ericLemanissier** [comment]
This is a false alarm: It's fine to get DUPLICATED status. I think this issue can be closed
