### ISSUE TITLE
License for Recipe files

### ISSUE THREAD

**Issue by Gagu2** [conan-io/conan-center-index#7324]
Hi All,

The conan-center-index package is licensed under MIT license. Hence, I believe that all the files under the recipe folder are also under MIT license. The recipe files may use to pull/include packages which have different licenses, but the the files themselves are under MIT license. 

Please confirm that my understanding is correct regarding this. Also, request the concerned person to update the readme documentation to clarify the same for the future users.

**Comment by Croydon** [comment]
In some cases, files are copied from upstream projects. Mostly, for test_packages. In that case, those specific files have other licenses.

Generally speaking, your understanding is correct.
