### ISSUE TITLE
[arrow] arrow/2.0.0: Support Gandiva in Arrow 2.0.0

### ISSUE THREAD

**Issue by kexianda** [conan-io/conan-center-index#7329]
### Package and Environment Details
  * Package Name/Version: **arrow/2.0.0**
  * Compiler+version: **GCC 9.3 / Clang 11**

I am working on it. I will create a PR for it.

### Logs

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `arrow/2.0.0` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe already has support for `gandiva` option, see https://github.com/conan-io/conan-center-index/blob/master/recipes/arrow/all/conanfile.py?plain=1#L27.

Happy coding 🐸
