### ISSUE TITLE
[package] assimp/5.0.1/5.0.0 : Cannot open assimp-vc142-mt.lib with CMake

### ISSUE THREAD

**Issue by ada-rose-dev** [conan-io/conan-center-index#7342]
I'm having troubles linking when including assimp with Conan + CMake.
Build fails with the following error:
`LINK : fatal error LNK1104: cannot open file 'assimp-vc142-mt.lib' [C:\dev\test0\build\test.vcxproj]`
I've checked `CONAN_LIB_DIRS_ASSIMP` and ensured that the library is at the specified location.
This only occurs with assimp, which leads me to believe it is a problem with the package.
The error occurs when including either version, assimp/5.0.1/5.0.0
I am new to Conan, so please excuse me if I am missing something obvious ^^

### Package and Environment Details
  * Package Name/Version: **assimp/5.0.1/5.0.0**
  * Operating System+version: **Windows 10.0.19043**
  * Compiler+version: **MSVC Build Tools 16**
  * Conan version: **conan 1.40.1**
  * Python version: **Python 3.9.7**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conanfile.txt
```
[requires]
assimp/5.0.1

[generators]
cmake
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.21)
project(test LANGUAGES C CXX)
add_executable(test main.cpp)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
target_link_libraries(test ${CONAN_LIBS})
```

main.cpp
```
int main () {
    return 0;
}
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
[main] Building folder: test0 
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/dev/test0/build --config Debug --target ALL_BUILD -j 10 --
[build] Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
[build] Copyright (C) Microsoft Corporation. All rights reserved.
[build] 
[build]   Checking Build System
[build]   Building Custom Rule C:/dev/test0/CMakeLists.txt
[build]   main.cpp
[build] LINK : fatal error LNK1104: cannot open file 'assimp-vc142-mt.lib' [C:\dev\test0\build\test.vcxproj]
[build] Build finished with exit code 1
```

</details>

**Comment by SpaceIm** [comment]
And if you move `conan_basic_setup()` before `add_executable()`?

**Comment by ada-rose-dev** [comment]
Thank you for the fix! I'll look into the other generators as well.
