### ISSUE TITLE
[question] [package] boost - error linking with shared libbaktrace

### ISSUE THREAD

**Issue by danielgavrila** [conan-io/conan-center-index#7346]
Hello ,

The conan profile is:

[settings]
os=Linux
os_build=Linux
arch=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release

The command 
**conan install boost/1.76.0@  -o boost:shared=True --build=boost -o zlib:shared=True -o bzip2:shared=True**
is working fine

Instead the command bellow
  **conan install boost/1.76.0@  -o boost:shared=True --build=boost -o zlib:shared=True -o bzip2:shared=True -o libbacktrace:shared=True**
fails with the error :

boost/1.76.0: WARN: Boost component 'stacktrace_backtrace' is missing libraries. Try building boost with '-o boost:without_stacktrace_backtrace'. (Option is not guaranteed to exist)
ERROR: boost/1.76.0: Error in package_info() method, line 1545
	raise ConanException("These libraries were expected to be built, but were not built: {}".format(non_built))
	ConanException: These libraries were expected to be built, but were not built: {'boost_stacktrace_backtrace'}

It seems that if Boost component stacktrace is able to link statically the libbacktrace , but fails to link it dynamically. Is it possible to link also dynamically libbacktrace ?

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SSE4** [comment]
unfortunately, I cannot reproduce an error locally, running in `conanio/gcc10` container the same commands

**Comment by daravi** [comment]
@SSE4 I can reproduce this when building `boost/1.77.0` with `-o *:shared=True`:
```
\\ profile/default
[settings]
os=Linux
os_build=Linux
os.kernel=4.18
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=10
compiler.libcxx=libc++
compiler.cppstd=17
build_type=Release
[options]
[build_requires]
[env]
m4:LDFLAGS=[-rtlib=compiler-rt]
```
OS: AlmaLinux (CentOS)
Conan: 1.40.3
Python: 3.9.2

Could this be related to this comment?
https://github.com/ianlancetaylor/libbacktrace/issues/25#issuecomment-477808254

[config.log](https://github.com/conan-io/conan-center-index/files/7282026/config.log)
[output.log](https://github.com/conan-io/conan-center-index/files/7282033/output.log)

**Comment by SSE4** [comment]
@daravi  I've tried to reproduce with `conanio/gcc10` and `conanio/clang10` images with `-o *:shared=True` as you have suggested, but in both cases it builds successfully for me.
seems to be something specific to AlmaLinux (CentOS)?
do you have a docker image to reproduce the problem?

**Comment by danielgavrila** [comment]
Hello,

i did not mention in my first email , but my Linux is also a Centos 7.Seems indeed that is a Centos/Almalinux issue

Best regards,
Daniel

**Comment by klimkin** [comment]
Solved the issue for me.

**Comment by SpaceIm** [comment]
@SSE4 Would it be possible to add this fix to boost recipe? I also see this issue on macOS.

**Comment by SSE4** [comment]
> @SSE4 Would it be possible to add this fix to boost recipe? I also see this issue on macOS.

sorry, no idea. I am not confident to judje. I know boost stacktrace developer (Anton Polukhin), maybe it makes sense to contact him personally or on boost mail-list, or at very least, starting by opening an issue at https://github.com/boostorg/stacktrace/issues. as I remember, he is also not a big fan of b2/bjam, so maybe @grafikrobot may comment on what should be an actual fix.

**Comment by klimkin** [comment]
Fixed the patch to work with disabled stacktrace backtrace:
```
diff --git a/recipes/boost/all/conanfile.py b/recipes/boost/all/conanfile.py
index 85c334ad9..753a32b92 100644
--- a/recipes/boost/all/conanfile.py
+++ b/recipes/boost/all/conanfile.py
@@ -786,6 +786,10 @@ class BoostConan(ConanFile):
             tools.replace_in_file(os.path.join(self.source_folder, self._source_subfolder, "libs", "stacktrace", "build", "Jamfile.v2"),
                                   "$(>) > $(<)",
                                   "echo \"\" > $(<)", strict=False)
+        if self._with_stacktrace_backtrace and self.options["libbacktrace"].shared:
+            tools.replace_in_file(os.path.join(self.source_folder, self._source_subfolder, "libs", "stacktrace", "build", "Jamfile.v2"),
+                                  ": <search>$(LIBBACKTRACE_PATH)/lib <link>static",
+                                  ": <search>$(LIBBACKTRACE_PATH)/lib <link>shared", strict=False)
         # Older clang releases require a thread_local variable to be initialized by a constant value
         tools.replace_in_file(os.path.join(self.source_folder, self._source_subfolder, "boost", "stacktrace", "detail", "libbacktrace_impls.hpp"),
                               "/* thread_local */", "thread_local", strict=False)
@@ -1065,6 +1069,8 @@ class BoostConan(ConanFile):

             cxx_flags.append("-fembed-bitcode")

+        if self._with_stacktrace_backtrace:
+            flags.append("-sLIBBACKTRACE_PATH={}".format(self.deps_cpp_info["libbacktrace"].rootpath))
         if self._with_iconv:
             flags.append("-sICONV_PATH={}".format(self.deps_cpp_info["libiconv"].rootpath))
         if self._with_icu:
```
