### ISSUE TITLE
[service] Some jobs might be stalled or be endless

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#737]
We faced this issue with a mistake in a recipe that was replacing paths in a file with `tools.replace_path_in_file()` that was taking too much time: https://github.com/conan-io/conan-center-index/pull/489#discussion_r369330487

At first sight, I was not able to tell where was the issue. So it will be helpful to implement some sort of timeout or memory watcher in order to fail jobs that behave this way

**Comment by SSE4** [comment]
yes, I believe timeout is needed anyway. I've seen in practice `make` hangs, and various tools crash from time to time, or display modal dialog boxes and error messages (assertions, access violation errors, etc).

**Comment by danimtb** [comment]
Timeouts are now in place, so this shouldn't be an issue when Jenkins is behaving properly 😄
