### ISSUE TITLE
[service] Missing description for hook warning KB-H057 

### ISSUE THREAD

**Issue by bernedom** [conan-io/conan-center-index#7377]
Hi,

I'm trying to update the 'si' package to the latest version. I'm currently getting the hook warning KB-H057, but it lacks a description and a hint on how to solve it in the knowledge base: https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md 

The warning states that `tools.rename(src, dst)` is outdated, and that `tools.rename(self, src, dst)` should be used. However as of conan 1.40 the version of rename() with three parameters seems not to exist. 

```[HOOK - conan-center.py] pre_export(): WARN: [TOOLS RENAME (KB-H057)] The 'tools.rename' in conanfile.py is outdated and may cause permission error on Windows. Use 'conan.tools.rename(self, src, dst)' instead.```

What am I missing here?

**Comment by madebr** [comment]
You're right.
Current [conan.tools](https://github.com/conan-io/conan/blob/3ff360a3478fca74c9694139eed0a9166a86988a/conan/tools/__init__.py) exports nothing.
I think that check was added too soon.
Imho, it's okay to keep using `tools.rename(src, dst)`.

Cc'ing @uilianries for a double check.

**Comment by ericLemanissier** [comment]
I guess it meant `conan.tools.files.rename` https://github.com/conan-io/conan/blob/develop/conan/tools/files/__init__.py#L1?
even conan docs seems wrong: https://docs.conan.io/en/latest/reference/conanfile/tools/files.html#conan-tools-rename

**Comment by madebr** [comment]
Indeed @ericLemanissier that seems to be the case.

**Comment by uilianries** [comment]
New update for Docs: https://github.com/conan-io/docs/pull/2232

**Comment by bernedom** [comment]
Thanks for the quick help! You are awesome.
