### ISSUE TITLE
[question] Why is PreferredToolArchitecture env var can be set only in -pr:h?

### ISSUE THREAD

**Issue by gmikhaile** [conan-io/conan-center-index#7395]
We are cross-building `x64` to `x86` `QtWebengine` that reqiures `64-bit` cross-building toolchain.
To use `amd64_x86` environmet to be able to cross-build  `QtWebengine`  we have to explicitly set `PreferredToolArchitecture=x64` env var in `-pr:h`.

From logical point of view  `PreferredToolArchitecture=x64` has to be set in `-pr:b`. Hasn't it?
Is this intentional decision or maybe some legacy?

**Comment by madebr** [comment]
Conan assumes that nothing in the host requirements can execute.
If nothing of the host requirements can execute, then applying the host environment variables should not influence anything.
These host environment variables should only have meaning for the resulting artifact.

**Comment by jgsogo** [comment]
The `[env]` section in a `profile` are the set of environment variables that will be available while **_building_** packages in that context, like build-requires listed in `profile` are available while building.

If you want to define some environment variables that should be available while **running** some package, they should go in `cpp_info.env_info` of that recipe (in your toolchain, if it is packaged, you can check some recipes for compilers like `android_ndk`).

**Comment by jgsogo** [comment]
Anyway, if you want to propose a different approach it is better if you open the issue in the Conan client repository (https://github.com/conan-io/conan). There you can also find more information about the new build-helpers and environment management for Conan v2.
