### ISSUE TITLE
[boost] boost with zlib

### ISSUE THREAD

**Issue by DenisYarullin** [conan-io/conan-center-index#743]
What options should I set to get boost with zlib inside lib directory?

**Comment by danimtb** [comment]
What do you mean? AFAIK boost always depends on zlib. Could you give more info?

**Comment by DenisYarullin** [comment]
@danimtb 

I want to use zlib as:
```
find_package(Boost 1.71 COMPONENTS zlib REQUIRED)
...
target_link_libraries(myTarget PRIVATE Boost::zlib)
```

but zlib isn't in the lib directory, when I built boost.

**Comment by danimtb** [comment]
zlib is not build inside boost, it is included as separated dependency. You don't have to link with zlib's target but with the boost's one

**Comment by DenisYarullin** [comment]
I downloaded binaries from [https://sourceforge.net/projects/boost/files/boost-binaries/](url) and saw it there: 
![boost_zlib](https://user-images.githubusercontent.com/10007693/73375666-2aae0d00-42cd-11ea-9543-467d1a154d0a.png)
How did they do it?

**Comment by uilianries** [comment]
@DenisYarullin I think it's embedded, which is not Conan case. all dependencies are built separately, so we can reuse them for any other package. 

Also where did you find that `zlib` is an Boost module? Do you have document link?
I didn't find it when looking at CMake 3.16.3

**Comment by DenisYarullin** [comment]
@uilianries These binaries had misled me. I agree with you. Thanks.

**Comment by uilianries** [comment]
@DenisYarullin Thanks for answering, I closing this issue. Feel free to reopen if you need to complement your question. Regards!
