### ISSUE TITLE
[boost] Boost.System is linked but does not appear as package dependency

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-center-index#7431]
This appears to have been introduced by #7290 

If you link to the Boost System library then a link is created by the executable but it does not appear as a dependency in the json manifest which can lead to runtime failures for downstream tools using the manifest to build a deployable package.

## Steps to Reproduce

Build the [attached example](https://github.com/conan-io/conan-center-index/files/7235836/conan_test.tar.gz):
```
$ tar -xf conan-test.tar.gz
$ mkdir conan-test/build
$ cd conan-test/build
$ conan install ..
$ cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
$ cmake --build .
```
Observe that `libboost_system.so` appears in the list of linked libraries, it can also be checked in the output of `ldd`

However, it does not appear in the dependency list in the json manifest

```
$ grep -c boost_system conanbuildinfo.json
0
```

## Expected Behaviour:

Libraries linked by the executable should appear in the dependencies of the json manifest so that downstream tools can use the manifest to create a package (eg https://docs.conan.io/en/latest/integrations/custom.html)

## Actual Behaviour

`boost_system` is linked by the executable but does not appear in the json manifest. If the manifest is used to create a deployable package, the executable will fail with a linking error at runtime.

**Comment by madebr** [comment]
When you run `cmake ..` in your terminal, you are not adding the cmake module path and prefix path.
You need to add the arguments which conan's CMake build helper automatically adds for you:
```sh
cmake .. -DCMAKE_MODULE_PATH=$PWD -DCMAKE_PREFIX_PATH=$PWD
```

You were running cmake's `FindBoost.cmake`, not the one generated by conan.
