### ISSUE TITLE
[service] Something wrong with the Java setup on the M1 Macs

### ISSUE THREAD

**Issue by a4z** [conan-io/conan-center-index#7432]
I can't understand why this PR is failing
https://github.com/conan-io/conan-center-index/pull/7422

except when some java executable is injected into path _before_ that one from the recipe.

Please see explanation in the PR for details

**Comment by SSE4** [comment]
we don't have M1 slaves. we are cross-building for M1 from x86_64 machines.
perhaps, you're trying to launch and M1 `java` executable on the x86_64 and it fails.
I'd suggest to add guard to the test package like:
```
if tools.cross_building(self):
    self.run("java --version", run_environment=True)
```

**Comment by a4z** [comment]
Ah ... that explains it  ! Thanks a lot for the help !! 

(Actually, it should be opposite, you should just have M1 , then you could also execute the x86_64 bins, but I understand that this is an investment _

**Comment by a4z** [comment]
That does not work ... :-(

**Comment by a4z** [comment]
what I actually had to do is 
```
        if self.settings.os == "Macos" and self.settings.arch == "armv8":
            return
```

I will leave that PR open until  #7422 went through the review

**Comment by a4z** [comment]
does work now, test recipe needs `os` and `arch` in `settings`
