### ISSUE TITLE
[boost] libraries built with dependency on boost::system, which is not included in the manifest

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-center-index#7435]
#7290 removed `boost_system` from the dependency manifest, however some boost libraries are still linked to it. Notably:

* `boost_contract`
* `boost_locale`
* `boost_random`
* `boost_type_erasure`

## Steps to reproduce

Build the Boost package with shared libraries

```
conan create . boost/1.70.0@ -o boost:shared=True
```

Run 
```
$ ldd test_package/build/<id>/bin/random_exe
```

An unresolved runtime dependency on `libboost_system` is visible in the output:

```
libboost_random.so.1.70.0 => ${CONAN_USER_HOME}/data/boost/1.70.0/_/_/package/<id>/lib/libboost_random.so.1.70.0 (0x00007f8071ec9000)
libboost_atomic.so.1.70.0 => ${CONAN_USER_HOME}/data/boost/1.70.0/_/_/package/<id>/lib/libboost_atomic.so.1.70.0 (0x00007f8071ec4000)
libboost_system.so.1.70.0 => not found
```

## Expected Results

No runtime dependencies should be added by conan that cannot subsequently be resolved. In addition, the JSON manifest (generated with `--generator json`) should contain all the dependencies necessary to run the package.

## Actual Results

Linking to one of the above libraries generates an additional dependency on `boost_system`, which is not included in the JSON manifest.

## Notes

We use a tool to generate deployable packages (eg deb or zip packages) using the JSON manifest to resolve dependencies. As `boost_system` does not appear in the manifest, we get runtime linking errors at deployment time.

## Workaround

Add an explicit link using CMake

```
target_link_directories(<target> PRIVATE ${Boost_system_LIB_DIRS})
target_link_libraries(<target> PRIVATE boost_system)
```

This resolves the runtime linking issue, but not the absence in the manifest.

**Comment by madebr** [comment]
Is this problem also present with boost/1.77?
If not, perhaps a fix can be backported.

**Comment by planetmarshall** [comment]
It looks to have been resolved as of boost/1.75:

```
$ ldd boost/1.74.0/_/_/package/<id>/lib/libboost_random.so | grep -c boost_system
1
$ ldd boost/1.74.0/_/_/package/<id>/lib/libboost_random.so
...
libboost_system.so.1.74.0 => not found
...
```

```
$ ldd boost/1.75.0/_/_/package/<id>/lib/libboost_random.so | grep -c boost_system
0
```

**Comment by planetmarshall** [comment]
In boost 1.77 `boost_system` in `boost_type_erasure` still contain references to `boost_system`.

The only reason this package builds currently is because the test package is run under the virtual environment, which adds `boost_system` to the `LD_LIBRARY_PATH`.

If the package is built with shared libraries, and the test package is run on Linux using only rpaths to find shared libraries, the test package will fail.

**Comment by madebr** [comment]
I ran the following command in the lib folder of a shared boost/1.77.0 package:
```
for i in *.so; do
  echo "boost dependencies of $i";
  objdump -p "$i" | grep NEEDED | awk '{print $2}' | grep boost;
done
```
<details>
<summary>Output</summary>

```
boost dependencies of libboost_atomic.so
boost dependencies of libboost_chrono.so
boost dependencies of libboost_container.so
boost dependencies of libboost_context.so
boost dependencies of libboost_contract.so
boost dependencies of libboost_coroutine.so
libboost_chrono.so.1.77.0
libboost_context.so.1.77.0
libboost_thread.so.1.77.0
boost dependencies of libboost_date_time.so
boost dependencies of libboost_fiber_numa.so
libboost_fiber.so.1.77.0
libboost_filesystem.so.1.77.0
libboost_context.so.1.77.0
boost dependencies of libboost_fiber.so
libboost_filesystem.so.1.77.0
libboost_context.so.1.77.0
boost dependencies of libboost_filesystem.so
libboost_atomic.so.1.77.0
boost dependencies of libboost_graph.so
libboost_regex.so.1.77.0
boost dependencies of libboost_iostreams.so
boost dependencies of libboost_json.so
libboost_container.so.1.77.0
boost dependencies of libboost_locale.so
libboost_system.so.1.77.0
boost dependencies of libboost_log_setup.so
libboost_log.so.1.77.0
libboost_regex.so.1.77.0
libboost_filesystem.so.1.77.0
libboost_chrono.so.1.77.0
libboost_atomic.so.1.77.0
libboost_thread.so.1.77.0
boost dependencies of libboost_log.so
libboost_filesystem.so.1.77.0
libboost_regex.so.1.77.0
libboost_chrono.so.1.77.0
libboost_atomic.so.1.77.0
libboost_thread.so.1.77.0
boost dependencies of libboost_math_c99f.so
boost dependencies of libboost_math_c99l.so
boost dependencies of libboost_math_c99.so
boost dependencies of libboost_math_tr1f.so
boost dependencies of libboost_math_tr1l.so
boost dependencies of libboost_math_tr1.so
boost dependencies of libboost_nowide.so
boost dependencies of libboost_prg_exec_monitor.so
boost dependencies of libboost_program_options.so
boost dependencies of libboost_random.so
boost dependencies of libboost_regex.so
boost dependencies of libboost_serialization.so
boost dependencies of libboost_stacktrace_addr2line.so
boost dependencies of libboost_stacktrace_backtrace.so
boost dependencies of libboost_stacktrace_basic.so
boost dependencies of libboost_stacktrace_noop.so
boost dependencies of libboost_system.so
boost dependencies of libboost_thread.so
boost dependencies of libboost_timer.so
libboost_chrono.so.1.77.0
boost dependencies of libboost_type_erasure.so
libboost_thread.so.1.77.0
libboost_system.so.1.77.0
libboost_chrono.so.1.77.0
boost dependencies of libboost_unit_test_framework.so
boost dependencies of libboost_wave.so
libboost_filesystem.so.1.77.0
libboost_thread.so.1.77.0
libboost_chrono.so.1.77.0
boost dependencies of libboost_wserialization.so
libboost_serialization.so.1.77.0
```
</details>

So it looks like `libboost_type_erasure` and `libboost_locale` still link to `boost_system`.

And sure enough, 
`libs/locale/build/Jamfile.v2` contains: `result += <library>../../system/build//boost_system ;
`
`libs/type_erasue/Jamfile.v2` contains: `lib boost_type_erasure : dynamic_binding.cpp /boost//thread /boost//system ;`

I think the boost sources need to be patched to remove boost_system  of the link libraries.
This should probably be back ported..
