### ISSUE TITLE
[package] qt/5.15.2: Missing ActiveQt components

### ISSUE THREAD

**Issue by ohanar** [conan-io/conan-center-index#7441]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 16**
  * Conan version: **conan 1.39.0**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
qt:qtactiveqt=True
qt:qtdatavis3d=True
qt:qtsvg=True
qt:qtwinextras=True
qt:shared=True
qt:with_mysql=False
qt:with_odbc=False
qt:with_pq=False
qt:with_sqlite3=False
...
```

### Steps to reproduce (Include if Applicable)
The following CMake will fail using conan's generators:
```
find_package ( Qt5 REQUIRED COMPONENTS AxContainer ) # alternatively AxServer
```

**Comment by ericLemanissier** [comment]
@ohanar could you try https://github.com/conan-io/conan-center-index/pull/7447 and see if activeqt works for you ?
