### ISSUE TITLE
[package] libuv/1.41.1: Cross build to macos armv8 on macos x86_64 not working.

### ISSUE THREAD

**Issue by Zvicii** [conan-io/conan-center-index#7459]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libuv/1.41.1**
  * Operating System+version: **macos x86_64  big sur 11.4**
  * Compiler+version: **apple clang 13.0**

I tried build for macos armv8 from a macos x86_64, it build successfully but generate x86_64 product.
Maybe should add CMAKE_OSX_ARCHITECTURES definition according to profile:host settings to its recipe.

**Comment by SpaceIm** [comment]
No issue for me with apple-clang 12 and by using 2 profiles.

Could you share your profile(s) and conan command as requested in the template please?

**Comment by Zvicii** [comment]
by setting CMAKE_OSX_ARCHITECTURES to cache works for me, closing issue now.
