### ISSUE TITLE
[package] mingw_installer/1.0: Request for MinGW i686-posix-dwarf

### ISSUE THREAD

**Issue by githubuser0xFFFF** [conan-io/conan-center-index#746]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **mingw_installer/1.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **GCC 7.3**
  * Conan version: **conan 1.21.1**
  * Python version: **Python 3.6.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
compiler.exception=dwarf2
compiler.threads=posix
[options]

[build_requires]
mingw_installer/1.0@conan/stable

[env]
```

### Steps to reproduce (Include if Applicable)
conan install mingw_installer/1.0@conan/stable

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
mingw_installer/1.0@conan/stable:
mingw_installer/1.0@conan/stable: ERROR: Package 'c4cd18d72bb5e5cd25f30f3dcbf60f4d4de72b27' build failed
mingw_installer/1.0@conan/stable: WARN: Build folder C:\CodingXP\.conan\data\mingw_installer\1.0\conan\stable\build\c4cd18d72bb5e5cd25f30f3dcbf60f4d4de72b27
ERROR: mingw_installer/1.0@conan/stable: Error in build() method, line 35
        str(self.settings.compiler.version))
while calling 'get_best_installer', line 107
        raise Exception("There is no suitable MinGW release for the requested features %s %s %s %s" % (arch, threads, exception, version))
        Exception: There is no suitable MinGW release for the requested features x86_64 posix dwarf 7
```

</details>

### Additional Information
Would be great to have a MinGW package for for posix  + dwarf. This is the MinGW configuration that ships with the Qt installation when using the Qt online installer from the Qt homepage. This is the verison information from the Qt MinGW:

```
Thread model: posix
gcc version 7.3.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)
```

**Comment by ericLemanissier** [comment]
The binary is available with `compiler.libcxx=libstdc++`. is libstdc++11 a thing on mingw ?

**Comment by githubuser0xFFFF** [comment]
Thank you for this hint. Using `compiler.libcxx=libstdc++` does not change anything. There is no package for the combination dwarf and posix available.

**Comment by ericLemanissier** [comment]
what is the output of `conan search -r all -q 'compiler.exception=dwarf2 AND compiler.threads=posix' mingw_installer/1.0@conan/stable` on your computer ? I get all expected binaries.
Once again, you this is not the place to discuss this issue. you should report on https://github.com/conan-community/community/issues

**Comment by githubuser0xFFFF** [comment]
I posted the answer also here https://github.com/conan-community/community/issues/311 so please answer there.

The output from `conan search -r all -q "compiler.exception=dwarf2 AND compiler.threads=posix" mingw_installer/1.0@conan/stable` shows me a number of packages but if I execute the following line `conan install mingw_installer/1.0@conan/stable` i get the following error:

```
ERROR: mingw_installer/1.0@conan/stable: Error in build() method, line 35
        str(self.settings.compiler.version))
while calling 'get_best_installer', line 107
        raise Exception("There is no suitable MinGW release for the requested features %s %s %s %s" % (arch, threads, exception, version))
        Exception: There is no suitable MinGW release for the requested features x86_64 posix dwarf 7
```
 This is my profile. I'm on Windows 10 64-bit (arch_build=x86_64) and I would like to build for Windows 32-bit (arch=x86)

```
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
compiler.exception=dwarf2
compiler.threads=posix
[options]

[build_requires]
mingw_installer/1.0@conan/stable

[env]
```

So there is no 32-bit MinGW with dwarf and posix.

**Comment by Croydon** [comment]
According to https://github.com/conan-community/community/issues/311 this issue is fixed

And if not, it should be re-opened in conan-community

Please close this one 😄
