### ISSUE TITLE
Recipes validation workflow: consider having a develop branch for integration purpose

### ISSUE THREAD

**Issue by Firefly35** [conan-io/conan-center-index#7461]
In several projects, we rely on conan recipes such as boost (among others) to build our projects.

It is really irritating that the master recipe branch regularly causes build failures for a stable recipe product and version, as the recipes are modified straight into the master branch.

For instance, boost had the numa option added for windows, without considering linux or macOS behavior, breaking those platforms builds (without adding a "numa=false" option to the boost dependency as a workaround).

Such modifications should occur on a develop branch, to allow the build through CI of the recipes on the main supported platforms (windows, linux, macOS...). 

Upon successfull build, then it would be easy to merge the recipe in the master branch, ensuring software quality.

In the past 2 years, we regularly met those kind of breaks (without mentioning the remotes modifications and migrations), and relying on conan at the moment put the question of the maintainbility and reproducibility of our builds.

Please be kind enough to seriously consider to setup a recipe validation workflow in accordance with software quality best practices.

**Comment by Croydon** [comment]
CI is running on pull requests, which could be considered "dev branches".

To avoid breakages, you have to pin the recipe revisions

https://docs.conan.io/en/latest/versioning/revisions.html

**Comment by jgsogo** [comment]
As said above, the way to go when using recipes from ConanCenter is to pin them using explicit revisions. Conan also provides [_lockfiles_ feature](https://docs.conan.io/en/latest/versioning/lockfiles.html) in case you want to pin the full graph of dependencies. With these two features you can achieve the reproducibility you need.

I really hope this answers your concerns. Feel free to open the issue again if you need help with any of these features.

Thanks!
