### ISSUE TITLE
[request] PDBs for <boost>/1.77

### ISSUE THREAD

**Issue by shreyasr89** [conan-io/conan-center-index#7467]
As of now I see that the latest boost version is boost/1.77.
We want to have also the symbols (pdbs) of this package asap with the next version.

**Comment by madebr** [comment]
Missing pdb's has always been a problem with this repo.
See https://github.com/conan-io/conan-center-index/issues/1982 for the earliest issue.

This need conan support to let users opt in into pdb creation.

**Comment by shreyasr89** [comment]
Why not just add another 'pdb' option to atleast support this?? or in the same way as other supported options, without_pdb can be defaulted to False.

**Comment by madebr** [comment]
Adding pdb options to all recipes does not scale.
After all, providing and handling pdb's is something that the package manager should support on a global scale.
It is not something that should be handled in a recipe per recipe base.

In other words, needing a a `pdb` releated option is a xy problem.

**Comment by madebr** [comment]
When/if pdb support drops in conan, we will have to modify a lot of recipes.
But the behavior/implementation will be uniform across all.

**Comment by prince-chrismc** [comment]
FAQs has some more info too https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-pdb-files-are-not-allowed

**Comment by uilianries** [comment]
Closing as PDB files are not distributed by CCI.

You can try locally copying to the metadata folder or even bin folder.

https://blog.conan.io/2023/10/24/Conan-launches-metadata-files.html
