### ISSUE TITLE
[package] fmt/6.1.2: cmake config file missing from package

### ISSUE THREAD

**Issue by matthew-d-jones** [conan-io/conan-center-index#747]
I'm trying to move from using the last bincrafters package (`fmt/5.3.0@bincrafters...`) to `fmt/6.1.2`
and now `find_package(fmt REQUIRED)` in my CMake fails, which seems to be because `fmt-config.cmake` is no longer included in the package.

In case it is relevant, I am using `conan_cmake_run()`:
```
set(CONAN_PROFILE "default" CACHE STRING "Name of conan profile to use, uses default by default")
conan_cmake_run(CONANFILE conan/conanfile.txt
          PROFILE ${CONAN_PROFILE}
          BASIC_SETUP ${OUTPUT_DIRS}
          BUILD outdated
          KEEP_RPATHS)
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **fmt/6.1.2**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8**
  * Conan version: **conan 1.20.5**

**Comment by matthew-d-jones** [comment]
Nevermind, seems to be intentional as the `cmake_find_package` generator exists now.

**Comment by danimtb** [comment]
Yes, this is something intentional explained in the wiki https://github.com/conan-io/conan-center-index/wiki/FAQ#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged Thanks!
