### ISSUE TITLE
[package] qt/5.15.2: Failed to deploy QWebEngine application with MacDeployQt

### ISSUE THREAD

**Issue by narcdev** [conan-io/conan-center-index#7475]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **MacOS Big Sur 11.5.2**
  * Compiler+version: **Apple clang version 12.0.5 (clang-1205.0.22.11)**
  * Conan version: **conan 1.39.0**
  * Python version: **Python 2.7.16 & Python 3.8.11**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
- Build the following example project with Qt Conan : `Qt/Examples/Qt-5.15.2/webenginewidgets/simplebrowser`
- Deploy it with MacDeployQt from Qt Conan : `/Users/builder/.conan/data/qt/5.15.2/bincrafters/stable/package/4819fba7b538b01321fbef38c12a6d76206f8ef1/bin/macdeployqt simplebrowser.app -verbose=3`
- Try to launch it, it failed with : `Could not find QtWebEngineProcess`

I've done the same steps with the "official" version of Qt 5.15.2 (download and install with Maintenance tool) and it works.

### Logs attached (Attach if Applicable)
- Conan QT Macdeployqt log : [conan_macdeploy_out.log](https://github.com/conan-io/conan-center-index/files/7265380/conan_macdeploy_out.log)
- Maintenance Tool QT Macdeployqt log : [maintenance_tool_macdeploy_out.log](https://github.com/conan-io/conan-center-index/files/7265381/maintenance_tool_macdeploy_out.log)

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `qt/5.15.2` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
