### ISSUE TITLE
[package] imgui/1.72 unable to include/build with implementations

### ISSUE THREAD

**Issue by hnOsmium0001** [conan-io/conan-center-index#749]
### Package and Environment Details
  * Package Name/Version: **imgui/1.72**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 2017**
  * Conan version: **conan 1.21.1**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]

```

### Description
In ImGui package, only the core headers are include path, but the implementation headers are in `res/bindings/`. There is no smooth way to include or build them aside from using relative path which is ugly.

**Comment by uilianries** [comment]
@danimtb I think this is what you mentioned earlier today.

**Comment by danimtb** [comment]
This is something we should discuss in order to provide a nice way for consumers to use the needed headers for each implementation

**Comment by perseoGI** [comment]
Hi there! I'm closing this very old issue as it was resolved. 
See https://github.com/conan-io/conan-center-index/blob/master/recipes/imgui/all/conanfile.py?plain=1#L78
