### ISSUE TITLE
[request] imgui/any. "Docking" feature

### ISSUE THREAD

**Issue by xahon** [conan-io/conan-center-index#7557]
### Package Details
  * Package Name/Version: **imgui/any**
  * Homepage: **https://github.com/ocornut/imgui**

There is a feature "Docking" in this library that lives in a separate branch a long time (from 2018) and is still regularly updated over time (last merge from master about 14 days ago). I'd wanted to have a package with this feature, maybe something like `imgui/1.84.2-docking`

**Comment by Sahnvour** [comment]
This will likely answer your questions : https://github.com/ocornut/imgui/wiki/Docking#preamble
In particular,
> It is safe and recommended to use that branch.

**Comment by xahon** [comment]
@jgsogo i can't just come into some other's people repo and merge everything I want. @Sahnvour mentioned a useful link (thank you). I'm sure this can be done in a some way that won't affect main package. Like adding a suffix in version or a brand new package

**Comment by Sahnvour** [comment]
Hi @jgsogo, did you have any time to think about it ? What would be needed to get the docking branch packaged ?

**Comment by AdhTri001** [comment]
Hey nothing done yet? @Sahnvour and @xahon did you managed to get it? Please help I also want to use docking branch with conan.

**Comment by Sahnvour** [comment]
Not that I know of. It should be really easy to do, the issue is more to know wether the conan folks will accept it.
