### ISSUE TITLE
[package] flatbuffers/1.11.0 / flatc/1.11.0

### ISSUE THREAD

**Issue by mjvk** [conan-io/conan-center-index#76]
When using flatbuffers with the cmake_paths generator (which is nice as it does not require any conan references in your cmake file) find_package will not work as the flatbuffers/flatc do not include the relevant cmake files (which also includes build_flatbuffers). Would it be possible to add these to the package?

[settings]
arch=x86_64
arch_build=x86_64
os=Neutrino
os_build=Windows
compiler=qcc
compiler.libcxx=cxx
compiler.version=5.4
os.version=7.0

flatbuffers*:compiler=qcc
flatbuffers*:compiler.libcxx=cxx
flatbuffers*:compiler.version=5.4
flatbuffers*:compiler.cppstd=gnu11

**Comment by mjvk** [comment]
That issue is the same as I am having indeed. My workflow is to:
- do conan install using the cmake_paths generator
- include conan_paths.cmake using CMAKE_PROJECT_XXX_INCLUDE
- Use find_package(FlatBuffers REQUIRED) to get flatbuffers (same as without conan)
- Use build_flatbuffers() to build using flatc (same as without conan)

For me the advantage of using it in this way is that my project is not dependent on Conan. I can build everything myself, set the correct module path and such and my cmake file will work. 

As the software I am building is aimed to run for 20-30 years I rather limit my dependencies on external tools. But I do like to use them because they make my life much easier!

**Comment by uilianries** [comment]
Unfortunately is not possible using the current stage of flatbuffers in Conan Center Index, but you can try the version maintained by the author, which contains all CMake files, including these macros that you mentioned.

https://bintray.com/aardappel/flatbuffers/flatbuffers%3Agoogle

    conan install -r conan-center flatbuffers/1.11.0@google/stable

We are working in solution to export CMake macros, but as it requires a new feature in Conan, it can take much time than you can wait for now.

**Comment by mjvk** [comment]
Hmmm so this means that it becomes infeasible to manually manage your packages or use conan without changing your cmakefile if you are using packages from Conan Center Index? Because you have to do a different call to find_package if you use conan generated vs directly from the authors repo? For me that seems like a loss to be honest. 

Anyway that is not for this issue, thank you for help (and your lots of work, conan rocks!)!
