### ISSUE TITLE
[package] cpr/1.5.0-1.6.2 (at least): Basic usage of CPR with libstdc++ crashes

### ISSUE THREAD

**Issue by ollien** [conan-io/conan-center-index#7615]
https://github.com/libcpr/cpr/issues/634#issue-993853629 documents that CPR from Conan seems to choke pretty badly when used for even simple usages. I've done some digging and tracked this down to it due to ABI breakage with `libstdc++`, but I haven't been able to pin it down further, given that the [test cases have passed just fine with both ABIs](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/7367/1/summary.json).

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: cpr/1.5.0-1.6.2 (at least)
  * Operating System+version: My host is Fedora 34, but I ran this under the Conan docker image  which is running Ubuntu 20.04
  * Compiler+version: GCC 10
  * Docker image: conanio/gcc10
  * Conan version: conan 1.40.3
  * Python version: Python 3.7.4

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
See issue: https://github.com/libcpr/cpr/issues/634#issue-993853629. There are full reproduction steps there.

### Logs (Include/Attach if Applicable)
See aforementioned issue.

**Comment by SpaceIm** [comment]
Please explain how you consume dependencies. Are you sure to properly inject libcxx of your profile in your project?

**Comment by ollien** [comment]
Gotcha. I knew I was missing something. Thanks
