### ISSUE TITLE
[question] How to customise icu data?

### ISSUE THREAD

**Issue by ivanvurbanov** [conan-io/conan-center-index#7673]
Hello, 
I'am building icu for **iOS**, arch=**armv8**, data_packaging=**static** and it builds fine but the _libicudata.a_ file is huge.   In the recipe I don't see any support for [ICU_DATA_FILTER_FILE](https://unicode-org.github.io/icu/userguide/icu_data/buildtool.html#icu-data-configuration-file). How can I customise the icu data so I can lower the size of _libicudata.a_ binary?

**Comment by jgsogo** [comment]
Hi! Currently the recipes doesn't support anything associated to that, but you can do different things:

 * One option is to populate that environment variable with your desired value and build from sources again
 * Another alternative is to add one option to the recipe (something like `data_filter_file: "ANY"`) and set the value you want for that option.
 
The advantage of the second approach is that the value of the option will also be encoded in the packageID and different paths will result in different packageIDs (and this is good as they are different Conan packages with different content). 

I encourage you to open a PR to improve the recipe in that direction.
