### ISSUE TITLE
[request]  cyclonedds/0.8.1

### ISSUE THREAD

**Issue by trittsv** [conan-io/conan-center-index#7710]
### Package Details
  * Package Name/Version: **cyclonedds/0.8.1**
  * Website: **https://projects.eclipse.org/projects/iot.cyclonedds**
  * Source code: **https://github.com/eclipse-cyclonedds/cyclonedds**

### Description Of The Library / Tool
Eclipse Cyclone DDS is a very performant and robust open-source DDS implementation.

**Comment by perseoGI** [comment]
Hi there, I'm closing this issue because `cyclonedds` is already in CCI.
See https://conan.io/center/recipes/cyclonedds?version=0.10.4

`v0.8.1` is an old one so it is not supported.
