### ISSUE TITLE
Would you like to join the UI Research team to help make ConanCenter UI better?

### ISSUE THREAD

**Issue by Dattax** [conan-io/conan-center-index#773]
Hi all, we’re recruiting a team to do a usability study for the next round of UI updates and features for ConanCenter from Feb. 9th - March 30th. We want to work directly with all of you by email and zoom on making the center experience better for the community. If interested in joining the usability team, please fill out this 5-minute form: https://forms.gle/LqTKRertRuRd7QCSA. Ping me or email me directly if you have questions (deepd@jfrog.com). Please have the form done by Feb. 8th!

**Comment by uilianries** [comment]
@danimtb I think we can pin this issue to help it get more popular.

**Comment by Dattax** [comment]
We can unpin and close this :) - I'll be sending an email to participants by the end of the week. Thank you!
