### ISSUE TITLE
What is the correct workflow when you need to rebuild a package locally and reuse it later?

### ISSUE THREAD

**Issue by kobi-ca** [conan-io/conan-center-index#7782]
I have the following scenario.
libfuse was compiled and linked against libc with ABI 2.28. This is what conan.io is providing. This is what the package in libfuse github compiled and linked with.
My Ubuntu machine is 18.04. I cannot upgrade it or the glibc. It has max of ABI 2.27.
The way to solve it is to run `conan install` with `--build=libfuse` and it will build and link it for my platform. This solve my immediate issue.
Now, let's say I'd like to share it with the rest of the team. What is the correct workflow and how does Conan know which package to download for the end users? the one with the 2.27 that I compiled locally? or the prebuilt one from conan center with ABI 2.28?

thanks.

**Comment by madebr** [comment]
No problem, I've been bitten by this problem as well.
