### ISSUE TITLE
[question] Finer grained export_sources() for patches?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#7790]
Currently, all CCI recipes export all patches of all versions in the cache of each version.

Why not using `export_sources()` to export required patches only?

```python
    def export_sources(self):
        for patch in self.conan_data.get("patches", {}).get(self.version, []):
            self.copy(patch["patch_file"])
```

**Comment by ericriff** [comment]
This goes against our desired workflow -- we use the recipe revision as a lock on the requirements list. 
E.g. 
```
self.requires(myLib/myVersion@user/channel#recipeRevisionHash)
```
This way we lock the dependency to a given revision of the recipe and we know that if someone changes the sources or something from the recipe, we will continue to use a package comming from an approved state of the recipe.
With this approach you can slip in source patches without changing the recipe revision. 
I don't know how common my use case is though, but I think that patches being an important part of the recipe should be considered part of the recipe revision.

**Comment by SpaceIm** [comment]
> Edit: I think I got this wrong -- The non-exported patches are not considered to compute the rrev, right?

That's it. What I propose has no effect on your workflow. Relevant patches of a lib version still contribute to rrev.

**Comment by theirix** [comment]
I understand how patches affect the recipe revision but replacing a simple declarative `export_sources` attribute with a multi-line imperative method with `copy` calls (often with `CMakeLists.txt` looks cumbersome and error-prone. It's better to have a common logic in Conan client that intelligently handles versions and metadata from `conandata.yml`.

**Comment by SpaceIm** [comment]
Can be closed now that usage of `export_conandata_patches` (https://github.com/conan-io/conan/pull/11911) is widely adopted.
