### ISSUE TITLE
[conan.io/center] Downloads counter not incremented for months

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#7802]
I hardly doubt that nobody has downloaded ffmpeg, but its counter is still 0. I also see many popular recipes without any progress on this number for months.

**Comment by samuel-emrys** [comment]
It would be good to see this fixed - would help evaluate how much demand there is for a library and how much effort should be put in to submitting version updates.

**Comment by SpaceIm** [comment]
Seems to work now since ffmpeg counter is not 0 anymore.

@jgsogo @uilianries @danimtb do you confirm it has been fixed?

**Comment by danimtb** [comment]
@SpaceIm yes, we forgot to update the issue. The download count for references is working again! Thank you for the follow-up
