### ISSUE TITLE
[package] arrow/2.0.0: Fails to build on Apple silicon (M1, ARM)

### ISSUE THREAD

**Issue by rprechelt** [conan-io/conan-center-index#7863]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **arrow 2.0.0**
  * Operating System+version: **MacOS 12.0**
  * Compiler+version: **Apple Clang 13.0.0**
  * Conan version: **conan 1.41.0**
  * Python version: **Python 3.9.47**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
``` 
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=13.0
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Arrow currently fails to build on Apple silicon under Conan. You get the following error:

``` shell
[  5%] Building CXX object source_subfolder/cpp/src/arrow/CMakeFiles/arrow_objlib.dir/array/builder_base.cc.o
In file included from /Users/rprechelt/.conan/data/arrow/2.0.0/_/_/build/38015df8b07e56c4ab1666b8e3d2bd8633ecc26a/source_subfolder/cpp/src/arrow/array/array_binary.cc:27:
In file included from /Users/rprechelt/.conan/data/arrow/2.0.0/_/_/build/38015df8b07e56c4ab1666b8e3d2bd8633ecc26a/source_subfolder/cpp/src/arrow/util/utf8.h:28:
In file included from /Users/rprechelt/.conan/data/arrow/2.0.0/_/_/build/38015df8b07e56c4ab1666b8e3d2bd8633ecc26a/source_subfolder/cpp/src/arrow/util/simd.h:39:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/nmmintrin.h:15:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/smmintrin.h:13:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/tmmintrin.h:13:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/pmmintrin.h:13:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/emmintrin.h:13:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/xmmintrin.h:13:
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
```

Conan is trying to load x86_64 SIMD instructions that are (obviously) not present on ARM architectures.

If you manually runtime disable _both_ runtime and compile-time SIMD, then you can successfully build on ARM. Runtime-SIMD can be disabled in the settings with `arrow:runtime_simd_level=None`. However, the compile-time SIMD setting is not exposed at the Conanfile (as far as I'm aware) - I had to manually set it in Arrow's Conan file on L325.

``` shell
self._cmake.definitions["ARROW_SIMD_LEVEL"] = "NONE"
```

I think the best solution is to expose `ARROW_SIMD_LEVEL` as a Conanfile option and also disable them automatically when building on ARM (until Arrow supports ARM vector extensions).

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `arrow/2.0.0.` version is no longer supported by Conan Center Index (by far)

I suggest using a newer version of this recipe.
I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
