### ISSUE TITLE
[package] automake/1.16.4: build_type isn't declared in the recipe 

### ISSUE THREAD

**Issue by shtanko-sv** [conan-io/conan-center-index#7871]
automake recipe doesn't contain `build_type` settings, what makes it incompatible with V2 mode:
```
settings = "os", "arch", "compiler"
```

### Package and Environment Details
  * Package Name/Version: **automake/1.16.64**
  * Operating System+version: **CentOS 7.4.1708**
  * Compiler+version: **GCC 11.2**
  * Conan version: **conan 1.41.0**
  * Python version: **Python 3.8.3**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
```

### Steps to reproduce
```shell
conan install automake/1.16.4@ -- build automake
```

### Logs
<details><summary>Click to expand log</summary>

```
ERROR: automake/1.16.4: Error in build() method, line 86
        autotools.make()
        ConanV2Exception: Conan v2 incompatible: build_type setting should be defined.
```

</details>

**Comment by madebr** [comment]
The error is probably thrown because automake's build runs configure + make.
The solution is to add `build_type` and remove it in `package_id`.

**Comment by perseoGI** [comment]
Hi there,
I'm closing this old issue as this was resolved in https://github.com/conan-io/conan-center-index/pull/8239
Thank you for your report!
Happy coding 🐸
