### ISSUE TITLE
[package] libcurl: test package fails when crossbuilding from x86_64 to x86 on Windows

### ISSUE THREAD

**Issue by maksim-petukhov** [conan-io/conan-center-index#7903]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl**
  * Operating System+version: **Windows 21H1**
  * Compiler+version: **VS 16.11**
  * Conan version: **conan 1.40.3**
  * Python version: **Python 3.9.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration (profile_host):
[settings]
arch=x86
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

``conan install libcurl/7.77.0@ --profile:host=windows-msvc-debug-x86 --profile:build=windows-msvc-release-x86_64 --build=libcurl``

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
build	24-Oct-2021 22:11:33	  test_package.vcxproj -> C:\bamboo-agent-home\xml-data\build-dir\THIRDPARTY-LIBCURL-JOB4\recipes\libcurl\all\test_package\build\9383702b7fc20bd2f2bd49777f62475c1274bd29\bin\test_package.exe
build	24-Oct-2021 22:11:33	  Building Custom Rule C:/bamboo-agent-home/xml-data/build-dir/THIRDPARTY-LIBCURL-JOB4/recipes/libcurl/all/test_package/CMakeLists.txt
build	24-Oct-2021 22:11:33	libcurl/7.77.0 (test package): Running test()
error	24-Oct-2021 22:11:33	ERROR: libcurl/7.77.0 (test package): Error in test() method, line 32
error	24-Oct-2021 22:11:33		output = subprocess.check_output(["file", self._test_executable]).decode()
error	24-Oct-2021 22:11:33		FileNotFoundError: [WinError 2] The system cannot find the file specified```

</details>

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `libcurl/7.77.0` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
