### ISSUE TITLE
[package] qt/5.15.2: build fails when some requirements built with shared=True

### ISSUE THREAD

**Issue by maksim-petukhov** [conan-io/conan-center-index#7905]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **GCC 10**
  * Docker image: **custom**
  * Conan version: **conan 1.40.3**
  * Python version: **Python 3.9.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
[options]
libpng:shared=True
qt:opengl=desktop
qt:qtcharts=True
qt:qtdatavis3d=True
qt:qtdeclarative=True
qt:qtimageformats=True
qt:qtmultimedia=True
qt:qtserialbus=True
qt:qtserialport=True
qt:qtsvg=True
qt:qtwayland=True
qt:shared=True
qt:with_libjpeg=libjpeg-turbo
qt:with_odbc=False
zlib:shared=True
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
``conan install qt/5.15.2@ -b=qt -o qt:shared=True -o qt:with_odbc=False -o qt:qtsvg=True -o qt:qtwayland=True -o qt:qtserialport=True -o qt:qtserialbus=True -o qt:qtdeclarative=True -o qt:qtimageformats=True -o qt:qtmultimedia=True -o qt:qtdatavis3d=True -o qt:qtcharts=True -o qt:opengl=desktop -o qt:with_libjpeg=libjpeg-turbo -o libpng:shared=True -o zlib:shared=True``

### Logs (Include/Attach if Applicable

[qt_build_log.txt](https://github.com/conan-io/conan-center-index/files/7447064/qt_build_log.txt)

I was able to fix this locally by changing this https://github.com/conan-io/conan-center-index/blob/c2c4c0c0949b0153b46a05a2597a1eb2900c515d/recipes/qt/5.x.x/conanfile.py#L689 to 
```python
with tools.environment_append(build_env): 
    with tools.environment_append(RunEnvironment(self).vars):
```
But I'm not sure if this is the right fix

**Comment by ericLemanissier** [comment]
It's surprising, because your failure happens on the line `self.run(self._make_program(), run_environment=True)`, which already has the `RunEnvironment` set via the `run_environment=True` argument.
