### ISSUE TITLE
[package] Qt/6.2.1: qt_add_qml_module cannot be used

### ISSUE THREAD

**Issue by mjvankampen** [conan-io/conan-center-index#7913]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.2.1**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC2019**
  * Conan version: **conan 1.42.0**
  * Python version: **Python 3.9.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.runtime=MD
build_type=Release
[options]
[conf]
[build_requires]
*: cmake/3.21.3, ninja/1.10.2
[env]
```

### Steps to reproduce (Include if Applicable)

Build Qt with declarative and try to use [qt6-add-qml-module](https://doc.qt.io/qt-6/qt-add-qml-module.html#qt6-add-qml-module). It fails as it cannot find ```_qt_internal_set_up_static_runtime_library``` which is defined in ```lib/cmake/Qt6/QtPublicTargetHelpers.cmake``` which is not in the conan recipe ([original](https://github.com/qt/qtbase/blob/6faa6cb1d79aa600100398de27ee58481e85e85e/cmake/QtPublicTargetHelpers.cmake))

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
[cmake] CMake Error at C:/.conan/75c80c/1/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:1660 (_qt_internal_set_up_static_runtime_library):
[cmake]   Unknown CMake command "_qt_internal_set_up_static_runtime_library".
[cmake] Call Stack (most recent call first):
[cmake]   C:/.conan/75c80c/1/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:1890 (__qt_propagate_generated_resource)
[cmake]   C:/.conan/75c80c/1/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:340 (_qt_internal_process_resource)
[cmake]   C:/.conan/75c80c/1/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:538 (qt6_add_resources)
[cmake]   C:/.conan/75c80c/1/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:629 (qt6_add_qml_module)
[cmake]   src/CMakeLists.txt:30 (qt_add_qml_module)
```

</details>

**Comment by srnwk** [comment]
Something similar happens also with qt6_add_executable, qt6_finalize_target, etc.

**Comment by ericLemanissier** [comment]
Do you think one of you can make a PR to keep the file QtPublicTargetHelpers.cmake in the package folder and add it to cmake modules? And maybe change the cmakelists.txt of the test recipe folder to make sure it works?

**Comment by mjvankampen** [comment]
Sure, do we think this is the only one? What about the other QtPublicXXXHelpers?

**Comment by srnwk** [comment]
> Sure, do we think this is the only one? What about the other QtPublicXXXHelpers?

You're right, it isn't the only file needed.

> As for the test, Qt does not build with declarative enabled by default, so not sure how we can test this except by calling the Qt internal functions such as `_qt_internal_set_up_static_runtime_library` which seems fragile.

I created a quick & dirty test here: https://github.com/srnwk/conan-center-index/commit/53f308247782ca53fc7411b6d00a9b6f4732bc59 where I just copy those QtPublic*.cmake modules to the lib/cmake/Qt6Core package folder, and attach them to the qtCore component's `build_modules`.

In the test_package I used `qt_add_executable`, which calls some of the same helper functions/macros as `qt_add_qml_module`, and at least that seems to work.

**Comment by ericLemanissier** [comment]
Thanks. I included your commit in my current PR https://github.com/conan-io/conan-center-index/pull/7998

**Comment by mjvankampen** [comment]
Hehe too late :P https://github.com/mjvankampen/conan-center-index/commit/f01bde5a802ba8318252a7c2ac47684a75de9042

**Comment by ericLemanissier** [comment]
Well, we probably want to make a single effort, and avoid multiplicating pull requests for qt, because the CI time is very important. are you ok if I merge in my PR @mjvankampen's commits instead of @srnwk's ?
