### ISSUE TITLE
[question] cross compiling libraries that require glib?

### ISSUE THREAD

**Issue by WilliamBehrens** [conan-io/conan-center-index#7934]
I have a very large sdk that I'm trying to use conan to manage the dependencies of. It gets compiled for windows, linux, and android and cross compiled for arm and x86, as well as some other platforms. in trying to set up the dependencies for it I attempted to cross compile it for android arm from windows 10 (visual studio 2019) using the following command:
`conan install . -if output_android_arm --profile:host=profiles\Android_Arm--profile:build=default --build missing`
and the Android_Arm profile appears as follows:
```
include(default)
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=9
os=Android
os.api_level=21
[build_requires]
*: android-ndk/r21e, cmake/3.19.8, ninja/1.10.2
[options]
[env]
```
The issue I run into is that when cross compiling I get an error when it gets to glib 
```
ERROR: There are invalid packages (packages that cannot exist for this configuration):
glib/2.70.0: Invalid ID: Cross-building not implemented
```
Android is one of the main platforms for the sdk and thus it needs to be able to build for it. why exactly can't glib be cross compiled for it? can I force it? I've gotten all the dependencies to cross compile on their own before without conan so why does this package enforce this rule?

**Comment by SpaceIm** [comment]
Meson based recipes don't support cross-build right now. glib is one of them. AFAIR, there is some WIP in Meson helper to improve this situation. /cc @SSE4

**Comment by SSE4** [comment]
@WilliamBehrens there are some open issues for the conan client:
https://github.com/conan-io/conan/issues/9710
https://github.com/conan-io/conan/issues/9713

I am trying to push them to conan developers, but that doesn't seem to be enough.
right now, meson is not the highest priority for the development, as cmake is getting more attention (and that's fine, it's used more frequently, and there are still plenty of things to improve).
what can you (and others) do to improve the situation?

- like these issues (use 👍 emoji at the first comment)
- write a comment on the issues, explaining your interest, importance, use-case, etc.
- test proposed changes (https://github.com/conan-io/conan/pull/9711)
- reach to the developers via other channels (email, slack, twitter, etc.)

**Comment by SSE4** [comment]
also consider checking:
conan-io/conan-center-index#7360
conan-io/conan-center-index#6678

**Comment by WilliamBehrens** [comment]
ok, I'll be sure to check those issues, I'll see if there's anything I'm able to contribute to the situation
