### ISSUE TITLE
[package] android-ndk/r22: Bug after update android recipe

### ISSUE THREAD

**Issue by paulo-coutinho** [conan-io/conan-center-index#7953]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **android-ndk/r22**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan latest**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
include(default)

[settings]
os=Android
os.api_level=21
compiler=clang
compiler.version=11
compiler.libcxx=c++_static
arch=armv7

[build_requires]
*: android-ndk/r22

```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

There is a problem on Android NDK R22 recipe after update to latest commit:

```
ERROR: android-ndk/r22: Error in package_info() method, line 266
	self.env_info.LD = self._define_tool_var("LD", "ld")
while calling '_define_tool_var', line 168
	raise ConanException(f"'Environment variable {name} could not be created: '{path}'")
	ConanException: 'Environment variable LD could not be created: '/home/runner/.conan/data/android-ndk/r22/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ld'
COMMAND: conan install /home/runner/work/ezored/ezored/files/targets/android/conan/recipe/conanfile.py -pr:b default -pr:h ezored_android_profile -s:h arch=armv7 -s:h os.api_level=16 -s:h build_type=Debug -o ezored_arch=armv7 -o ezored_name=ezored -o ezored_version=1.0.0 --build=missing --update
WORKING DIR: /home/runner/work/ezored/ezored/build/android/Debug/armv7/conan
```

</details>

FULL LOG:
https://github.com/ezored/ezored/runs/4108829881?check_suite_focus=true#step:12:182

**Comment by andioz** [comment]
I'm currently at the same point, same error. As far as I can see, there is a new check in the recipe: if the file the environment variable point to doesn't exist, raise this exception. Don't know if this file was missing before undetected or if it's missing now.

**Comment by paulo-coutinho** [comment]
Can anyone help us :)

**Comment by andioz** [comment]
@justinmcbride I add you here because you made the last update, maybe you have better insights…

**Comment by andioz** [comment]
I tried the previous recipe, adding the checks:

```python
        if not os.path.isfile(path):
            raise ConanException(f"'Environment variable {name} could not be created: '{path}'")
```

I'm not surprised, th old recipe fails here too. `LD` is the only variable which has no executable. I'm not sure if this is a bug for a long time now, but I think things would not work without `LD`, right? 

In my case (armv8), there exists 2 executables with extra suffices:

```
.conan/data/android-ndk/r22/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld.bfd
.conan/data/android-ndk/r22/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld.gold
```
And I've seen there exists options like `-fuse-ld=gold`.
https://github.com/android/ndk/issues/556

I guess in case of `LD` only the prefix is meant, not the real executable, and the additional suffix is added at runtime? Does anyone know more about this NDK details?

**Comment by justinmcbride** [comment]
> @justinmcbride I add you here because you made the last update, maybe you have better insights…

Thanks for the add. I added the raising of the exception at the request of another contributor on review of my PR. Unfortunately, I'm not familiar with the fine details of the NDK, and the inclusion/exclusion of the various tools. I am also surprised though that the NDK would be working (pre-my-PR) without `ld` in the environment properly set.

I'll follow this comment up with another (in a couple of days) about my findings on the insanity that is the naming convention of these tools across different NDK versions.

But in all, it seems that the correct fix isn't as you proposed in your PR. I would suggest simply removing the conan exception from being raised, and leave it at a warning message. Still continue to try and use the LD variable, but revert to allowing usage of the package without it.

To your point in your PR #7976, 

> Are there chances to add tests for **using** the build dependency in the CI runner pipeline?

I was wondering the same in my PR. I would also like to know if there's a way to properly test this kind of package. I would love to have additional input on this from others. This package needs some serious work and time spent investigating all of the potential combinations. Problem for me is that it's quickly eating up my disk space to look at the potential combinations!

```
jmcbride@DESKTOP-OMANIG2 /a/ndk  $ du . -hs
29G     .

jmcbride@DESKTOP-OMANIG2 /a/ndk  $ ls -1
android-ndk-r21e-darwin-x86_64/
android-ndk-r21e-linux-x86_64/
android-ndk-r21e-windows-x86_64/
android-ndk-r22b-darwin-x86_64/
android-ndk-r22b-linux-x86_64/
android-ndk-r22b-windows-x86_64/
android-ndk-r23b-darwin/
android-ndk-r23b-linux/
android-ndk-r23b-windows/
```

**Comment by paulo-coutinho** [comment]
Maybe fixed by:
https://github.com/conan-io/conan-center-index/pull/7976

**Comment by SeanSnyders** [comment]
I am also hitting this issue, cross-compiling on Linux to Android:
![image](https://user-images.githubusercontent.com/1384135/141373754-487e7f4f-cd6b-4534-9614-404acf797934.png)

**Comment by SeanSnyders** [comment]
Hi, this has been closed via a PR to fix the LD variable, but as per my comment above we are hitting this issue for the CC variable in our cross compilation situation.
Seems like similar issue introduced across the board and should be looked at in a broader sense for a fix.

Which leads me to think that this issue should not be closed.

**Comment by andioz** [comment]
> Hi, this has been closed via a PR to fix the LD variable, but as per my comment above we are hitting this issue for the CC variable in our cross compilation situation. Seems like similar issue introduced across the board and should be looked at in a broader sense for a fix.
> 
> Which leads me to think that this issue should not be closed.

I would suggest to create a new issue, maybe with a little bit more details for the build setup.
