### ISSUE TITLE
pcre2/10.37: fails to build due to source files download connection timeout

### ISSUE THREAD

**Issue by yuriy-mochurad** [conan-io/conan-center-index#7963]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: pcre2/10.37
  * Operating System+version: macOS 12.0.1
  * Compiler+version: clang 13.0
  * Conan version: 1.42.0
  * Python version: 3.9.7

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
pcre2/10.37: Configuring sources in ~/.conan/data/pcre2/10.37/_/_/source
ERROR: Error downloading file https://ftp.pcre.org/pub/pcre/pcre2-10.37.tar.gz: 'HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre2-10.37.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x102eadf40>, 'Connection to ftp.pcre.org timed out. (connect timeout=60.0)'))'
Waiting 5 seconds to retry...
ERROR: pcre2/10.37: Error in source() method, line 76
	tools.get(**self.conan_data["sources"][self.version],
	ConanException: Error downloading file https://ftp.pcre.org/pub/pcre/pcre2-10.37.tar.gz: 'HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre2-10.37.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x102ead310>, 'Connection to ftp.pcre.org timed out. (connect timeout=60.0)'))'
```

</details>

**Comment by m-hilgendorf** [comment]
This affects PCRE as well. From [pcre.org](http://pcre.org/) : 

> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

**Comment by yuriy-mochurad** [comment]
> This affects PCRE as well. From [pcre.org](http://pcre.org/) :
> 
> > Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

True, `pcre` seems to be adressed in this PR #7956
