### ISSUE TITLE
[center.conan.io] Can't copy from a package's recipe content

### ISSUE THREAD

**Issue by aucampia-emrsn** [conan-io/conan-center-index#797]
I can't copy from the content of a recipe. For example if I go here: https://conan.io/center/fmt/6.1.2/?user=_&channel=_&revision=&os=&tab=recipe and click recipe tab, and select then right clicking does not give copy and ctrl+c also does not copy.

**Comment by uilianries** [comment]
Hi @iwan-aucamp-emerson ! 

You can also run Conan client to get its content:

    conan get fmt/6.1.2@ -r conan-center > conanfile.py

**Comment by uilianries** [comment]
Furthermore, you can download the recipe by clicking on "Download" button

![Screenshot_2020-02-06 Fmt Package version - 6 1 2 - ConanCenter - JFrog](https://user-images.githubusercontent.com/4870173/73933259-d30a3580-48ba-11ea-9b63-acfb2701d6b5.png)

Regards!

**Comment by uilianries** [comment]
Anyway, I can confirm that ctrl+c is not able to copy the recipe content on that page.

**Comment by SSE4** [comment]
yeah, it's possible, but still requires more actions (clicks) to get the effect needed. e.g. if I only need to copy a few lines. I have to download file somewhere, open it, copy lines, then delete... sounds annoying.

**Comment by Croydon** [comment]
Interesting. With Firefox I can mark lines of code, I get the regular context menu with a copy function, but it does not copy anything

**Comment by uilianries** [comment]
BTW I'm running Mozilla Firefox 72.0.2 on Linux

**Comment by Dattax** [comment]
Thanks for bringing this up - we'll address this.

**Comment by ankushchadha** [comment]
@Dattax is the plan to add a copy to the clipboard icon? Can you share a recent mockup here?

**Comment by ankushchadha** [comment]
hi @aucampia-emrsn, this issue has been addressed. A new copy icon was added to the recipe tab that allows recipe content to be copied over. Here's an example - https://conan.io/center/fmt?tab=recipe

**Comment by prince-chrismc** [comment]
![image](https://user-images.githubusercontent.com/16867443/236888105-4fbc4c0b-6ee5-44ee-8f9f-3e662abb522e.png)
