### ISSUE TITLE
Boost/1.77.0: Missing options

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan-center-index#7981]
How can we get additional boost options that are set via defines into the recipe?
Such as BOOST_ASIO_STANDALONE, BOOST_DLL_USE_STD_FS, BOOST_BEAST_USE_STD_STRING_VIEW, BOOST_LOG_USE_STD_REGEX for example

**Comment by SSE4** [comment]
the easiest way right now is via `extra_b2_flags` option, e.g.:
```
-o boost:extra_b2_flags="define=BOOST_ASIO_STANDALONE define=BOOST_DLL_USE_STD_FS define=BOOST_BEAST_USE_STD_STRING_VIEW define=BOOST_LOG_USE_STD_REGEX 
```
should do the trick
also, consider opening a PR adding dedicated recipe options for each boost option you find useful.

**Comment by SSE4** [comment]
for @madebr 
do you know if there is an automated way to get a list of supported boost options, maybe with `boostdep` or other tool?

**Comment by madebr** [comment]
[`boostdep` is an utility to create boost module dependencies](https://github.com/boostorg/boostdep).
I don't know of a tool to automatically enumerate the available preprocessor options.

I don't think Boost provides a central list with these values, as does none of its subprojects.
Currently this would require parsing all sources which is, I think, a C++-hard problem.

**Comment by SSE4** [comment]
> [`boostdep` is an utility to create boost module dependencies](https://github.com/boostorg/boostdep). I don't know of a tool to automatically enumerate the available preprocessor options.
> 
> I don't think Boost provides a central list with these values, as does none of its subprojects. Currently this would require parsing all sources which is, I think, a C++-hard problem.

I was told on #boost channel in slack: `You'll have to read the docs for every library`
this is unfortunate, but nothing we could do at this moment, except adding options one by one on demand.

**Comment by uilianries** [comment]
In Conan 2.x, extra defines can be applied directly via configuration:

https://docs.conan.io/2/reference/config_files/global_conf.html

In this case, you could do:

    conan create recipes/boost/all/conanfile.py --version=1.78.0 -c tools.build:defines='["BOOST_ASIO_STANDALONE", "BOOST_DLL_USE_STD_FS", "BOOST_BEAST_USE_STD_STRING_VIEW", "BOOST_LOG_USE_STD_REGEX"]'
    
This will be equivalent to use B2 define feature: https://www.boost.org/doc/libs/1_86_0/tools/build/doc/html/index.html#bbv2.overview.invocation.properties

Closing this issue as it's oriented to no longer Boost version and is focused on Conan 1.x.
