### ISSUE TITLE
qt/6.2.1: Could not find the Qt platform plugin "windows" in ""

### ISSUE THREAD

**Issue by amrkamal2025** [conan-io/conan-center-index#7988]
Hi,
I use Conan the simplest way, I have this file and I use conan install command to install it
```
[requires]
qt/6.2.1
[generators]
cmake
```
and link it using CMake using this way

```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(ConanQt main.cpp)

target_link_libraries(ConanQt ${CONAN_LIBS})
```
the library itself works good without GUI, all other core library like QString, QFile, all this stuff working more than perfect, but when I use Qt GUI I got this issue

```
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fi
x this problem.
```

so what I am missing? is there anything I need to copy to my directory or the project directory to use this static build?

full setting
```

    arch=x86_64
    arch_build=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=16
    os=Windows
    os_build=Windows
```

Thanks in advance.

**Comment by ericLemanissier** [comment]
The easiest workaround is to use option qt:shared=True.
Otherwise please check the solution mentioned in https://github.com/conan-io/conan-center-index/issues/6318#issuecomment-920832506

**Comment by amrkamal2025** [comment]
Thank you very much it worked i used 
```
#include <QtPlugin>
Q_IMPORT_PLUGIN (QWindowsIntegrationPlugin)
```
in my main.cpp
