### ISSUE TITLE
[question] How do you install packages from the new conan center remote?

### ISSUE THREAD

**Issue by egendron93** [conan-io/conan-center-index#799]
I am trying to install the boost/1.72.0 package from the new conan center remote (https://conan.io/center/).

My current remotes are:
```
conan-center: https://conan.bintray.com [Verify SSL: True]
conan-community: https://api.bintray.com/conan/conan-community/conan [Verify SSL: True]
bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]
```

The conan install command I am using is:
```
conan install boost/1.72.0@conan/stable
```

The current output is:
```
conan install boost/1.72.0@conan/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

boost/1.72.0@conan/stable: Not found in local cache, looking in remotes...
boost/1.72.0@conan/stable: Trying with 'conan-center'...
boost/1.72.0@conan/stable: Trying with 'conan-community'...
boost/1.72.0@conan/stable: Trying with 'bincrafters'...
ERROR: Unable to find 'boost/1.72.0@conan/stable' in remotes
```

I did not see anything in the documentation about the new conan center changing it's remote URL. Is there a new URL or is the new conan center not yet available to the public?

**Comment by egendron93** [comment]
```
conan --version
Conan version 1.22.0
```

**Comment by ericLemanissier** [comment]
as indicated on https://conan.io/center/boost/1.72.0/?user=_&channel=_ you need to use `boost/1.72.0` without @conan/stable

**Comment by Croydon** [comment]
Now, the remote is the same for conan-center

You need to remove the `@user/channel`

Instead of `boost/1.72.0@conan/stable` it is `boost/1.72.0` for conanfiles

Or in the command it is `conan install boost/1.72.0@`

**Comment by egendron93** [comment]
The @ without the rest of the reference is what i was missing, thank you. Is there some documentation for this? I looked around but didn't seem to find anything mentioning adding the @ without the rest of the reference.

Without the @ it acts as if I'm installing with just the path argument.
```
conan install boost/1.72.0 
ERROR: Conanfile not found at /workspaces/project/boost/1.72.0
```

**Comment by Croydon** [comment]
Adding just the `@` is just for CLI commands.
If you have a `conanfile.py` or `conanfile.txt` you don't need the `@` for recipe references

The reason is backwards compatibility for existing CLI calls. A command like `conan create . bincrafters/stable` interprets the last argument as `user/branch`, while calls with `@` like `conan create . boost/1.72.0` are interpreted as `recipe/version`

**Comment by danimtb** [comment]
Thanks for reporting. I was recently thinking about this and stating clearly in the readme of this repo how to consume the packages generated by this service. I will create an issue to improve that
