### ISSUE TITLE
[libpng] libpng/1.6.37: Fails to build with Unknown processor CMAKE_SYSTEM_PROCESSOR='armv8'

### ISSUE THREAD

**Issue by Talkless** [conan-io/conan-center-index#8003]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libpng/1.6.37**
  * Operating System+version: **Debian 10 Buster amd64**
  * Compiler+version: **clang 9**
  * Conan version: **conan 1.41.0**
  * Python version: **Python 3.7.3**

### Conan profile
`[env]` values where stolen from some CMake project managed by QtCreator
```
[settings]
arch=armv8
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=9
os=Android
os.api_level=21
os_build=Linux
[options]
libpng:shared=True
[build_requires]
[env]
ANDROID_ABI=arm64-v8a
CMAKE_SYSTEM_PROCESSOR=aarch64
CMAKE_C_COMPILER=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
CMAKE_CXX_COMPILER=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
CMAKE_MAKE_PROGRAM=/usr/bin/make
ANDROID_NATIVE_API_LEVEL=21
ANDROID_NDK=/opt/android-sdk-linux/ndk/21.3.6528147
CMAKE_TOOLCHAIN_FILE=/opt/android-sdk-linux/ndk/21.3.6528147/build/cmake/android.toolchain.cmake
AR=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar
CC=aarch64-linux-android21-clang
CHOST=arm64-v8a-linux-android
CXX=aarch64-linux-android21-clang++
LD=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld
PATH=[/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin,/home/vincas/opt/jdk8u265-b01/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games]
RANLIB=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ranlib
STRIP=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip
```

### Steps to reproduce (Include if Applicable)

```
conan install libpng/1.6.37@ -pr profile_provided.txt -b missing
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=armv8
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=9
os=Android
os.api_level=21
os_build=Linux
[options]
libpng:shared=True
[build_requires]
[env]
ANDROID_ABI=arm64-v8a
ANDROID_NATIVE_API_LEVEL=21
ANDROID_NDK=/opt/android-sdk-linux/ndk/21.3.6528147
AR=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar
CC=aarch64-linux-android21-clang
CHOST=arm64-v8a-linux-android
CMAKE_CXX_COMPILER=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
CMAKE_C_COMPILER=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
CMAKE_MAKE_PROGRAM=/usr/bin/make
CMAKE_SYSTEM_PROCESSOR=aarch64
CMAKE_TOOLCHAIN_FILE=/opt/android-sdk-linux/ndk/21.3.6528147/build/cmake/android.toolchain.cmake
CXX=aarch64-linux-android21-clang++
LD=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld
PATH=[/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin,/home/vincas/opt/jdk8u265-b01/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games]
RANLIB=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ranlib
STRIP=/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip
Installing package: libpng/1.6.37
Requirements
    libpng/1.6.37 from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    libpng/1.6.37:ab3137e9088f4e42cd2e661737f5d334514be82c - Build
    zlib/1.2.11:d90c6937a846904107bf4cebd7a8705bc34c61ab - Cache

Cross-build from 'Linux:x86_64' to 'Android:armv8'
Installing (downloading, building) binaries...
zlib/1.2.11: Already installed!
libpng/1.6.37: Copying sources to build folder
libpng/1.6.37: Building your package in /home/vincas/.conan/data/libpng/1.6.37/_/_/build/ab3137e9088f4e42cd2e661737f5d334514be82c
libpng/1.6.37: Generator cmake_find_package created FindZLIB.cmake
libpng/1.6.37: Generator cmake created conanbuildinfo.cmake
libpng/1.6.37: Aggregating env generators
libpng/1.6.37: Calling build()
CMake Error at /usr/share/cmake-3.18/Modules/Platform/Android-Determine.cmake:289 (message):
  Android: Unknown processor CMAKE_SYSTEM_PROCESSOR='armv8'.
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:129 (include)
  CMakeLists.txt:2 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
libpng/1.6.37: 
libpng/1.6.37: WARN: Package binary is corrupted, removing: ab3137e9088f4e42cd2e661737f5d334514be82c
libpng/1.6.37: WARN: Build folder is dirty, removing it: /home/vincas/.conan/data/libpng/1.6.37/_/_/build/ab3137e9088f4e42cd2e661737f5d334514be82c
libpng/1.6.37: ERROR: Package 'ab3137e9088f4e42cd2e661737f5d334514be82c' build failed
libpng/1.6.37: WARN: Build folder /home/vincas/.conan/data/libpng/1.6.37/_/_/build/ab3137e9088f4e42cd2e661737f5d334514be82c
ERROR: libpng/1.6.37: Error in build() method, line 144
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 139
	self._cmake.configure()
	ConanException: Error 1 while executing cd '/home/vincas/.conan/data/libpng/1.6.37/_/_/build/ab3137e9088f4e42cd2e661737f5d334514be82c' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_SYSTEM_NAME="Android" -DCMAKE_SYSTEM_VERSION="21" -DCMAKE_ANDROID_ARCH_ABI="arm64-v8a" -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM="android-21" -DANDROID_TOOLCHAIN="clang" -DANDROID_STL="none" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="clang" -DCONAN_COMPILER_VERSION="9" -DBUILD_SHARED_LIBS="ON" -DCMAKE_INSTALL_PREFIX="/home/vincas/.conan/data/libpng/1.6.37/_/_/package/ab3137e9088f4e42cd2e661737f5d334514be82c" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_MODULE_PATH="/home/vincas/.conan/data/libpng/1.6.37/_/_/build/ab3137e9088f4e42cd2e661737f5d334514be82c" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DPNG_TESTS="False" -DPNG_SHARED="True" -DPNG_STATIC="False" -DPNG_DEBUG="False" -DPNG_PREFIX="" -DCMAKE_SYSTEM_PROCESSOR="armv8" -DPNG_ARM_NEON="on" -Wno-dev '/home/vincas/.conan/data/libpng/1.6.37/_/_/build/ab3137e9088f4e42cd2e661737f5d334514be82c'

```

</details>

**Comment by SpaceIm** [comment]
Can you try this fix:

```patch
--- a/recipes/libpng/all/conanfile.py
+++ b/recipes/libpng/all/conanfile.py
@@ -126,7 +126,7 @@ class LibpngConan(ConanFile):
         self._cmake.definitions["PNG_STATIC"] = not self.options.shared
         self._cmake.definitions["PNG_DEBUG"] = self.settings.build_type == "Debug"
         self._cmake.definitions["PNG_PREFIX"] = self.options.api_prefix
-        if tools.cross_building(self.settings):
+        if tools.cross_building(self.settings) and not tools.get_env("CMAKE_SYSTEM_PROCESSOR"):
             self._cmake.definitions["CMAKE_SYSTEM_PROCESSOR"] = self._libpng_cmake_system_processor
         if self._has_neon_support:
             self._cmake.definitions["PNG_ARM_NEON"] = self._neon_msa_sse_vsx_mapping[str(self.options.neon)]
```

**Comment by Talkless** [comment]
@SpaceIm With this change build have started, but failed in a different way:

```
[ 91%] Linking C shared library ../lib/libpng16.so
/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot open linker script file /home/vincas/.conan/data/libpng/1.6.37/styritrade/stable/build/ab3137e9088f4e42cd2e661737f5d334514be82c/source_subfolder/libpng.vers: No such file or directory
```

**Comment by Talkless** [comment]
This is verbose output:
```
[ 12%] Linking C shared library ../lib/libpng16.so
cd /home/vincas/.conan/data/libpng/1.6.37/styritrade/stable/build/ab3137e9088f4e42cd2e661737f5d334514be82c/source_subfolder && /usr/bin/cmake -E cmake_link_script CMakeFiles/png.dir/link.txt --verbose=1                                                                               
/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 -fPIC -DCPU_SETSIZE=1024    -funwind-tables -no-canonical-prefixes -fexceptions   -O3 -DNDEBUG  -Wl,--version-script='/home/vincas/.conan/data/libpng/1.6.37/styritrade/stable/build/ab3137e9088f4e42cd2e661737f5d334514be82c/source_subfolder/libpng.vers' -shared -Wl,-soname,libpng16.so -o ../lib/libpng16.so CMakeFiles/png.dir/png.c.o CMakeFiles/png.dir/pngerror.c.o CMakeFiles/png.dir/pngget.c.o CMakeFiles/png.dir/pngmem.c.o CMakeFiles/png.dir/pngpread.c.o CMakeFiles/png.dir/pngread.c.o CMakeFiles/png.dir/pngrio.c.o CMakeFiles/png.dir/pngrtran.c.o CMakeFiles/png.dir/pngrutil.c.o CMakeFiles/png.dir/pngset.c.o CMakeFiles/png.dir/pngtrans.c.o CMakeFiles/png.dir/pngwio.c.o CMakeFiles/png.dir/pngwrite.c.o CMakeFiles/png.dir/pngwtran.c.o CMakeFiles/png.dir/pngwutil.c.o CMakeFiles/png.dir/arm/arm_init.c.o CMakeFiles/png.dir/arm/filter_neon.S.o CMakeFiles/png.dir/arm/filter_neon_intrinsics.c.o CMakeFiles/png.dir/arm/palette_neon_intrinsics.c.o   -L/home/vincas/.conan/data/zlib/1.2.11/_/_/package/d90c6937a846904107bf4cebd7a8705bc34c61ab/lib  /home/vincas/.conan/data/zlib/1.2.11/_/_/package/d90c6937a846904107bf4cebd7a8705bc34c61ab/lib/libz.a -lm  -latomic -lm                                                                                                                        
/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot open linker script file /home/vincas/.conan/data/libpng/1.6.37/styritrade/stable/build/ab3137e9088f4e42cd2e661737f5d334514be82c/source_subfolder/libpng.vers: No such file or directory
```
.vers mentioned here:
```
-Wl,--version-script='/home/vincas/.conan/data/libpng/1.6.37/styritrade/stable/build/ab3137e9088f4e42cd2e661737f5d334514be82c/source_subfolder/libpng.vers'
```

**Comment by Talkless** [comment]
Running `strace` does not show that it was ever generated(writter), just tries to read:
```
[pid  5458] openat(AT_FDCWD, "/home/vincas/.conan/data/libpng/1.6.37/styritrade/stable/build/ab3137e9088f4e42cd2e661737f5d334514be82c/source_subfolder/libpng.vers", O_RDONLY) = -1 ENOENT (No such file or directory) 
```

**Comment by madebr** [comment]
Is this https://github.com/conan-io/conan/issues/9736?
I think this is a conan issue.
`CONAN_CMAKE_SYSTEM_PROCESSOR` ==> `CMAKE_SYSTEM_PROCESSOR` is not applied to dependencies of the `android-ndk` recipe.

If you agree with me, please post a message with your findings at the issue mentioned before. Thanks.

**Comment by tuanhle94** [comment]
I'm getting the same issue on Ubuntu 18.04


`Configuration (profile_host):
[settings]
arch=armv7
build_type=Debug
compiler=clang
compiler.libcxx=libc++
compiler.version=11
os=Android
os.api_level=16
[options]
[build_requires]
[env]
AR=/opt/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
AS=/opt/android-ndk-r22//toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as
CC=/opt/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi16
CONAN_CMAKE_ANDROID_NDK=/opt/android-ndk-r22/
CXX=/opt/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7a-linux-androideabi16
LD=/opt/android-ndk-r22//toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld
PATH=[/usr/local/bin]
RANLIB=/opt/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
STRIP=/opt/android-ndk-r22//toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

swig/4.0.2: Forced build from source
bison/3.7.6: Forced build from source
conanfile.py: Installing package
Requirements
    boost/1.75.0 from 'conan-center' - Cache
    jbig/20160605 from 'conancenter' - Cache
    libdeflate/1.8 from 'conancenter' - Cache
    libiconv/1.16 from 'conan-center' - Cache
    libjpeg/9d from 'conancenter' - Cache
    libpng/1.6.37 from 'conancenter' - Cache
    libtiff/4.3.0 from 'conancenter' - Cache
    libwebp/1.2.0 from 'conancenter' - Cache
    libxml2/2.9.10 from 'conan-center' - Cache
    openjpeg/2.4.0 from 'conan-center' - Cache
    openssl/3.0.0 from 'conancenter' - Cache
    xz_utils/5.2.5 from 'conancenter' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
    zstd/1.5.0 from 'conancenter' - Cache
Packages
    boost/1.75.0:c567cf874f5b7a579c421ba3a04d9dca285b33c4 - Cache
    jbig/20160605:27b2762521da1330e55d7fa2bc1a9fc531833025 - Cache
    libdeflate/1.8:04876d24ce05edaa21774562a6332b04a130ece5 - Cache
    libiconv/1.16:04876d24ce05edaa21774562a6332b04a130ece5 - Cache
    libjpeg/9d:04876d24ce05edaa21774562a6332b04a130ece5 - Cache
    libpng/1.6.37:5807403f85fb45dd183b6af8b89d03681ae290f0 - Build
    libtiff/4.3.0:06d288b28e8b67697b4cf8240276b0ad23d05119 - Cache
    libwebp/1.2.0:a37748624a2ba4c3d831ddd21975f98cf659aa86 - Cache
    libxml2/2.9.10:14ebfbc7b3f7bd964ae399bd0067da1f7c5e0ba9 - Cache
    openjpeg/2.4.0:04876d24ce05edaa21774562a6332b04a130ece5 - Cache
    openssl/3.0.0:6afb67e050d0e2db2ba0ae0ff6191c83d541ff3b - Build
    xz_utils/5.2.5:04876d24ce05edaa21774562a6332b04a130ece5 - Cache
    zlib/1.2.11:04876d24ce05edaa21774562a6332b04a130ece5 - Cache
    zstd/1.5.0:04876d24ce05edaa21774562a6332b04a130ece5 - Cache
Build requirements
    autoconf/2.71 from 'conancenter' - Cache
    automake/1.16.4 from 'conancenter' - Cache
    bison/3.7.6 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conan-center' - Cache
    flex/2.6.4 from 'conancenter' - Cache
    m4/1.4.19 from 'conancenter' - Cache
    pcre/8.45 from 'conancenter' - Cache
    swig/4.0.2 from 'conancenter' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Build requirements packages
    autoconf/2.71:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    automake/1.16.4:258f6f05ca54813b3d7180161753df7f9ccf7e1d - Cache
    bison/3.7.6:f034150aa8c4acc1a81326b5b78cef4846a95f87 - Build
    bzip2/1.0.8:d91c5078b0c5af8e17bc80e2389019770a579bcc - Cache
    flex/2.6.4:f034150aa8c4acc1a81326b5b78cef4846a95f87 - Cache
    m4/1.4.19:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache
    pcre/8.45:98d5b1b3218d8339ab86e358c746f41ac0172f5a - Cache
    swig/4.0.2:ecb2d71ae4bad3b51dade00ec89140273402b5d7 - Build
    zlib/1.2.11:961755854760682044d37dabfc2d998658edf961 - Cache

Cross-build from 'Linux:x86_64' to 'Android:armv7'
Installing (downloading, building) binaries...
boost/1.75.0: Already installed!
bzip2/1.0.8: Already installed!
bzip2/1.0.8: Appending PATH environment variable: /root/.conan/data/bzip2/1.0.8/_/_/package/d91c5078b0c5af8e17bc80e2389019770a579bcc/bin
jbig/20160605: Already installed!
jbig/20160605: Appending PATH environment variable: /root/.conan/data/jbig/20160605/_/_/package/27b2762521da1330e55d7fa2bc1a9fc531833025/bin
libdeflate/1.8: Already installed!
libiconv/1.16: Already installed!
libiconv/1.16: Appending PATH environment var: /root/.conan/data/libiconv/1.16/_/_/package/04876d24ce05edaa21774562a6332b04a130ece5/bin
libjpeg/9d: Already installed!
libwebp/1.2.0: Already installed!
m4/1.4.19: Already installed!
m4/1.4.19: Appending PATH environment variable: /root/.conan/data/m4/1.4.19/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin
m4/1.4.19: Setting M4 environment variable: /root/.conan/data/m4/1.4.19/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin/m4
openjpeg/2.4.0: Already installed!
xz_utils/5.2.5: Already installed!
zlib/1.2.11: Already installed!
zlib/1.2.11: Already installed!
zstd/1.5.0: Already installed!
autoconf/2.71: Already installed!
autoconf/2.71: Appending PATH env var with : /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin
autoconf/2.71: Setting AC_MACRODIR to /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/share/autoconf
autoconf/2.71: Setting AUTOCONF to /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoconf
autoconf/2.71: Setting AUTORECONF to /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoreconf
autoconf/2.71: Setting AUTOHEADER to /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoheader
autoconf/2.71: Setting AUTOM4TE to /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autom4te
autoconf/2.71: Setting AUTOM4TE_PERLLIBDIR to /root/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/share/autoconf
flex/2.6.4: Already installed!
flex/2.6.4: Appending PATH environment variable: /root/.conan/data/flex/2.6.4/_/_/package/f034150aa8c4acc1a81326b5b78cef4846a95f87/bin
flex/2.6.4: Setting LEX environment variable: /root/.conan/data/flex/2.6.4/_/_/package/f034150aa8c4acc1a81326b5b78cef4846a95f87/bin/flex
libpng/1.6.37: Copying sources to build folder
libpng/1.6.37: Building your package in /root/.conan/data/libpng/1.6.37/_/_/build/5807403f85fb45dd183b6af8b89d03681ae290f0
libpng/1.6.37: Generator cmake created conanbuildinfo.cmake
libpng/1.6.37: Generator cmake_find_package created FindZLIB.cmake
libpng/1.6.37: Aggregating env generators
libpng/1.6.37: Calling build()
CMake Error at /usr/local/share/cmake-3.19/Modules/Platform/Android-Determine.cmake:301 (message):
  Android: Unknown processor CMAKE_SYSTEM_PROCESSOR='armv7'.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/CMakeDetermineSystem.cmake:159 (include)
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
libpng/1.6.37:
libpng/1.6.37: WARN: Package binary is corrupted, removing: 5807403f85fb45dd183b6af8b89d03681ae290f0
libpng/1.6.37: WARN: Build folder is dirty, removing it: /root/.conan/data/libpng/1.6.37/_/_/build/5807403f85fb45dd183b6af8b89d03681ae290f0
libpng/1.6.37: ERROR: Package '5807403f85fb45dd183b6af8b89d03681ae290f0' build failed
libpng/1.6.37: WARN: Build folder /root/.conan/data/libpng/1.6.37/_/_/build/5807403f85fb45dd183b6af8b89d03681ae290f0
ERROR: libpng/1.6.37: Error in build() method, line 144
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 139
        self._cmake.configure()
        ConanException: Error 1 while executing cd '/root/.conan/data/libpng/1.6.37/_/_/build/5807403f85fb45dd183b6af8b89d03681ae290f0' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_SYSTEM_NAME="Android" -DCMAKE_SYSTEM_VERSION="16" -DCMAKE_ANDROID_ARCH_ABI="armeabi-v7a" -DANDROID_ABI="armeabi-v7a" -DANDROID_NDK="/opt/android-ndk-r22/" -DANDROID_PLATFORM="android-16" -DANDROID_TOOLCHAIN="clang" -DANDROID_STL="none" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="clang" -DCONAN_COMPILER_VERSION="11" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/libpng/1.6.37/_/_/package/5807403f85fb45dd183b6af8b89d03681ae290f0" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_MODULE_PATH="/root/.conan/data/libpng/1.6.37/_/_/build/5807403f85fb45dd183b6af8b89d03681ae290f0" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DPNG_TESTS="False" -DPNG_SHARED="False" -DPNG_STATIC="True" -DPNG_DEBUG="True" -DPNG_PREFIX="" -DCMAKE_SYSTEM_PROCESSOR="armv7" -DPNG_ARM_NEON="on" -Wno-dev '/root/.conan/data/libpng/1.6.37/_/_/build/5807403f85fb45dd183b6af8b89d03681ae290f0'
CMake Error at cmake/conan_dependencies.cmake:182 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan_dependencies.cmake:94 (invoke_conan_install)
  CMakeLists.txt:63 (add_conan_dependencies)


-- Configuring incomplete, errors occurred!`

**Comment by SpaceIm** [comment]
Does it still fail with last revision of libpng recipe? https://github.com/conan-io/conan-center-index/pull/8672 should have fixed this issue.

**Comment by Talkless** [comment]
I still get error `...source_subfolder/libpng.vers: No such file or directory`:
```
[ 91%] Linking C shared library ../lib/libpng16.so
/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot open linker script file /home/vincas/.conan/data/libpng/1.6.37/_/_/build/ab3137e9088f4e42cd2e661737f5d334514be82c/source_subfolder/libpng.vers: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [source_subfolder/CMakeFiles/png.dir/build.make:366: lib/libpng16.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:172: source_subfolder/CMakeFiles/png.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2
libpng/1.6.37: 
libpng/1.6.37: ERROR: Package 'ab3137e9088f4e42cd2e661737f5d334514be82c' build failed
libpng/1.6.37: WARN: Build folder /home/vincas/.conan/data/libpng/1.6.37/_/_/build/ab3137e9088f4e42cd2e661737f5d334514be82c
ERROR: libpng/1.6.37: Error in build() method, line 152
        cmake.build()
        ConanException: Error 2 while executing cmake --build '/home/vincas/.conan/data/libpng/1.6.37/_/_/build/ab3137e9088f4e42cd2e661737f5d334514be82c' '--' '-j16'
```

**Comment by Talkless** [comment]
This is interesting find: https://stackoverflow.com/a/62541328
Suggests to set `-DHAVE_LD_VERSION_SCRIPT=OFF` on Android.

**Comment by Talkless** [comment]
This worked!
```
$ git diff
diff --git a/recipes/libpng/all/conanfile.py b/recipes/libpng/all/conanfile.py
index e7becda8d..8f7cc5a5e 100644
--- a/recipes/libpng/all/conanfile.py
+++ b/recipes/libpng/all/conanfile.py
@@ -133,6 +133,8 @@ class LibpngConan(ConanFile):
         self._cmake.definitions["PNG_STATIC"] = not self.options.shared
         self._cmake.definitions["PNG_DEBUG"] = self.settings.build_type == "Debug"
         self._cmake.definitions["PNG_PREFIX"] = self.options.api_prefix
+        if self.settings.os == "Android":
+            self._cmake.definitions["HAVE_LD_VERSION_SCRIPT"] = False
         if tools.cross_building(self):
             self._cmake.definitions["CONAN_LIBPNG_SYSTEM_PROCESSOR"] = self._libpng_cmake_system_processor
         if self._has_neon_support:
```

**Comment by paulocoutinhox** [comment]
Hi. This is solved? I have the same problem :(

**Comment by Talkless** [comment]
Looks like my Debian Sid upgraded to openjdk-17. I simply switched to 11 using:
```
sudo update-alternatives --config java
```
And selected openjdk-11. Works fine again.

**Comment by kambala-decapitator** [comment]
seeing the same with v1.57:

```
libpng/1.6.39: CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/Users/kambala/dev/vcmi/conan-deps-android-64/.conan/data/libpng/1.6.39/_/_/build/3bcd3ef0f6d66512f3b3820040087300d6f64ec8/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/kambala/dev/vcmi/conan-deps-android-64/.conan/data/libpng/1.6.39/_/_/package/3bcd3ef0f6d66512f3b3820040087300d6f64ec8" -DCMAKE_SYSTEM_PROCESSOR="armv8" -DCMAKE_MACOSX_BUNDLE="OFF" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/kambala/dev/vcmi/conan-deps-android-64/.conan/data/libpng/1.6.39/_/_/build/3bcd3ef0f6d66512f3b3820040087300d6f64ec8/src"
-- Using Conan toolchain: /Users/kambala/dev/vcmi/conan-deps-android-64/.conan/data/libpng/1.6.39/_/_/build/3bcd3ef0f6d66512f3b3820040087300d6f64ec8/build/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.25/Modules/Platform/Android-Determine.cmake:370 (message):
  Android: Unknown processor CMAKE_SYSTEM_PROCESSOR='armv8'.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:159 (include)
  CMakeLists.txt:31 (project)


CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
libpng/1.6.39: 
libpng/1.6.39: ERROR: Package '3bcd3ef0f6d66512f3b3820040087300d6f64ec8' build failed
libpng/1.6.39: WARN: Build folder /Users/kambala/dev/vcmi/conan-deps-android-64/.conan/data/libpng/1.6.39/_/_/build/3bcd3ef0f6d66512f3b3820040087300d6f64ec8/build/Release
ERROR: libpng/1.6.39: Error in build() method, line 163
	cmake.configure()
	ConanException: Error 1 while executing cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/Users/kambala/dev/vcmi/conan-deps-android-64/.conan/data/libpng/1.6.39/_/_/build/3bcd3ef0f6d66512f3b3820040087300d6f64ec8/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/kambala/dev/vcmi/conan-deps-android-64/.conan/data/libpng/1.6.39/_/_/package/3bcd3ef0f6d66512f3b3820040087300d6f64ec8" -DCMAKE_SYSTEM_PROCESSOR="armv8" -DCMAKE_MACOSX_BUNDLE="OFF" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/kambala/dev/vcmi/conan-deps-android-64/.conan/data/libpng/1.6.39/_/_/build/3bcd3ef0f6d66512f3b3820040087300d6f64ec8/src"
```

used `-c tools.cmake.cmaketoolchain:system_processor=aarch64` for a workaround

**Comment by SpaceIm** [comment]
It's a regression coming from https://github.com/conan-io/conan-center-index/pull/12386. See https://github.com/conan-io/conan-center-index/pull/12386#discussion_r950438726

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/15538 should fix this issue.
