### ISSUE TITLE
[question/bug] Pixman recipe fails to find cpu-features when cross compiling to android from windows

### ISSUE THREAD

**Issue by WilliamBehrens** [conan-io/conan-center-index#8011]
This is my `android.jinja`:
```
include(default)
[settings]
arch=armv7
compiler=clang
compiler.libcxx=c++_shared
compiler.version=9
os=Android
os.api_level=21
[build_requires]
android-ndk/r21e
cmake/3.19.8
ninja/1.10.2
[conf]
tools.android:ndk_path={{os.getenv("ANDROID_NDK")}}
tools.microsoft.msbuild:max_cpu_count={{os.cpu_count()}}
tools.build:processes={{os.cpu_count()}}
tools.gnu.make:jobs={{os.cpu_count()}}
tools.ninja:jobs={{os.cpu_count()}}
```
and I'm running `conan install . -if conan -pr:b=default -pr:h=android.jinja --build missing` as my install command, for what ever reason though I'm getting an error saying that pixman cannot find `#include <cpu-features.h>` I checked the recipe and it appears that it doesn't have a requirement of cpu-features so I'm not sure if thats an error in the recipe or if I'm doing something wrong.

**Comment by SSE4** [comment]
yes, it seems to be a requirement for Android:
https://github.com/freedesktop/pixman/blob/eadb82866b0f6a326a61c36f60e5c2be8f7479af/pixman/meson.build#L108
https://github.com/freedesktop/pixman/blob/eadb82866b0f6a326a61c36f60e5c2be8f7479af/meson_options.txt#L82

as I can see, google cpu_features library can be used:
https://developer.android.com/ndk/guides/cpu-features
https://github.com/google/cpu_features/blob/3e8243b7d9951c078259c3186c039a6e8f036055/ndk_compat/cpu-features.h

so, it's probably just a matter of adding the following code:
```
def requirements(self):
    if self.settings.os == "Android":
        self.requires("cpu_features/0.6.0")
```

**Comment by WilliamBehrens** [comment]
nice, I'll set up the pr when I can
