### ISSUE TITLE
[request] libdrm/2.4.100 (rescue from bincrafters-legacy?)

### ISSUE THREAD

**Issue by egnor** [conan-io/conan-center-index#8024]
### Package Details
  * Package Name/Version: **libdrm/2.4.100**
  * Website: **https://gitlab.freedesktop.org/mesa/drm**
  * Source code: **https://gitlab.freedesktop.org/mesa/drm**

### Description Of The Library / Tool
This is a quite specialized library to access a specific Linux kernel interface (the Direct Rendering Manager, DRM -- not to be confused with digital rights management!) used for high performance display I/O. Other than low level nerds like me, it is mostly useful because other packages depend on it. For example, ffmpeg is likely to (optionally) depend on it in the future.

There is currently a bincrafters package at https://github.com/bincrafters/conan-libdrm which is in the "conan-legacy-bincrafters" package drop (https://bincrafters.jfrog.io/ui/packages/conan:%2F%2Flibdrm?name=libdrm&type=packages). It would be nice to have it "properly" in conan-center, that way other conancenter packages can depend directly on it without pulling things from elsewhere.

I could set up a PR to make it so, but I'm not sure about the relationship (if any) between bincrafters and conan-center (competitors? friends? descendants?) or how we think about importing packages between them to see if this is even a good idea.

**Comment by Croydon** [comment]
For the time being, you should be able to consume this package from our Bincrafters remote like any other package (remote: https://bincrafters.jfrog.io/artifactory/api/conan/public-conan ;  recent changes: https://bincrafters.github.io/2020/04/19/infrastructure-changes-and-required-actions/)

Bincrafters is older than Conan Center Index and we share mostly the same goals, so no, we are not competitors 🙂

Feel free to either help migrating the recipe to CCI or improving it further in Bincrafters. If you migrate it to CCI, please just provide clear credits in your pull request  and / or commit.
