### ISSUE TITLE
[request] rapidjson/cci.20211112

### ISSUE THREAD

**Issue by pdavydov108** [conan-io/conan-center-index#8030]
### Package Details
  * Package Name/Version: **rapidjson/cci.20211112**
  * Source code: **https://github.com/Tencent/rapidjson**
  * Homepage: **https://rapidjson.org/**

Can you please update rapidjson to the latest version? The current latest release available in conan center now is almost one year old. The reason why I'm asking it is that I tried to build my project in c++20 mode and hit [this nasty bug](https://github.com/Tencent/rapidjson/issues/1846). It can cause an infinite recursion and segfault in c++20 mode. This bug can only be detected at runtime (for some reason gcc emitted no waringing for me). It's easy to trigger it in code. I'm afraid it can stop some people (including me) to adopt c++20.

**Comment by prince-chrismc** [comment]
Please feel free to open a PR! Bumping a version tends to be very easy in Conan (see https://github.com/conan-io/conan-center-index/pull/8032 for example)

Just comment on #4 and ope na PR. It does not take long at all!

**Comment by pdavydov108** [comment]
hey @prince-chrismc, thanks for you reply. I have created a PR for this.
