### ISSUE TITLE
[package] poco/all: components missing

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#8037]
`poco` recipe provides only one "unofficial" `Poco::Poco` target in `package_info()`.

Actually upstream config files have many targets:
`Poco::ActiveRecord`
`Poco::Crypto`
`Poco::Data`
`Poco::DataPostgreSQL`
`Poco::DataSQLite`
`Poco::Encodings`
`Poco::Foundation`
`Poco::JSON`
`Poco::JWT`
`Poco::MongoDB`
`Poco::Net`
`Poco::NetSSL`
`Poco::Redis`
`Poco::Util`
`Poco::XML`
`Poco::Zip`

(probably more or less depending on options)

**Comment by SSE4** [comment]
are these components actually needed, or just for completeness/perfection?

**Comment by SpaceIm** [comment]
It's required to properly model CMake config file of upstream. Currently, this recipe just provides one target with all the libraries, and this imported target name doesn't even exist upstream.
