### ISSUE TITLE
[service] Improve readme with example of consuming packages generated by this service

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#804]
Coming from https://github.com/conan-io/conan-center-index/issues/799

We should update the readme with examples for consumers and indicate how to deal with references that don't have user and channel

**Comment by Croydon** [comment]
While at it, we can remove the entire section `Reporting Issues` since we have now issue templates

**Comment by Croydon** [comment]
Except of `If your issue is not appropriate for a public discussion, please contact us via e-mail at info@conan.io.`

**Comment by danimtb** [comment]
this was completed long time ago
