### ISSUE TITLE
[request] <iir1>/<1.9.0>

### ISSUE THREAD

**Issue by wouterz** [conan-io/conan-center-index#8115]
### Package Details
  * Package Name/Version: **iir1/1.9.0**
  * Source code: **https://github.com/berndporr/iir1**

### Description Of The Library / Tool
An infinite impulse response (IIR) filter library for Linux, Mac OSX and Windows which implements Butterworth, RBJ, Chebychev filters and can easily import coefficients generated by Python (scipy).

**Comment by SpaceIm** [comment]
@uilianries @SSE4 @prince-chrismc iir1 has been added by https://github.com/conan-io/conan-center-index/pull/8171, so this issue can be closed.
