### ISSUE TITLE
[question] status.conan.io remote is out-of-date (bintray should be deprecated, center.conan.io should be out of beta)

### ISSUE THREAD

**Issue by JenTzori** [conan-io/conan-center-index#8125]
Hi! 

My team had some confusion over the new remote link. To my understanding, conan.bintray.com is deprecated and center.conan.io is the new remote. This is correctly detailed in the [docs](https://docs.conan.io/en/latest/uploading_packages/remotes.html#conan-center-deprecated), but the [status page](https://status.conan.io/) still lists bintray as the remote, and lists center.conan.io as being in beta stages.

Would you be able to update the status page to reflect the old remote being deprecated and remove the "beta" label on https://status.conan.io? Thanks in advance!

- [X]  I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by tapia** [comment]
The person that can do this change is on sick leave. I'll try again next week.

**Comment by tapia** [comment]
Fixed
