### ISSUE TITLE
qt/6.2.1: qmlimportscanner not found

### ISSUE THREAD

**Issue by yuriy-mochurad** [conan-io/conan-center-index#8188]
When using `macdeployqt` that is being built by the package - it can not find `qmlimportscanner`. I can see `qmlimportscanner` is being built under `lib` folder, but simple copying to `bin` also does not help a lot, because then `qmlimportscanner` starts complaining about libraries not found

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.2.1**
  * Operating System+version: MacOS 12.0.1
  * Compiler+version: **clang 13**
  * Conan version: **conan 1.42.0**
  * Python version: **Python 3.9.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os.version=10.14
os_build=Macos
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: qmlimportscanner not found at "/.conan/data/qt/6.2.1/_/_/package/664ff38ff1fdbe812ce50815b42f83214a3da0f0/bin/qmlimportscanner"
ERROR: Rebuild qtdeclarative/tools/qmlimportscanner
```

</details>

**Comment by ericLemanissier** [comment]
Could you please retry to rebuild qt with conan's argument `-u` to update your qt recipe, because https://github.com/conan-io/conan-center-index/pull/7998 may have fixed the problem

**Comment by yuriy-mochurad** [comment]
@ericLemanissier I freshly built is yesterday. I also just double checked and patch included in #7998 is already part of my package locally. I also forgot to mention qt configuration the issue reproduced is:

```
"qt:shared": True,
"qt:qtdeclarative": True,
"qt:qtshadertools": True,
"qt:qtsvg": True,
"qt:qtcharts": True,
"qt:qttools": True,
"qt:qttranslations": True,
"qt:with_harfbuzz": False,
"qt:opengl": "dynamic"
```

**Comment by ericLemanissier** [comment]
Ok, so my findings on this topic are that qmlimportscanner is installed to `${INSTALL_LIBEXECDIR}` https://github.com/qt/qtdeclarative/blob/v6.2.1/tools/qmlimportscanner/CMakeLists.txt#L11
qt recipes sets `INSTALL_LIBEXECDIR` to `lib` on macos https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L521
macdeployqt tries to load it from `QLibraryInfo::path(QLibraryInfo::LibraryExecutablesPath)` https://github.com/qt/qttools/blob/v6.2.1/src/macdeployqt/shared/shared.cpp#L1266. I'm not entirely sure what is the relation between this path and cmake's `${INSTALL_LIBEXECDIR}`

Anyway, can you please give more information on the environment in which you are running `macdeployqt` ? Is it from conan's `self.run(...)` ? from bash ? Do you use conan's `Virtualrunenv` generator ? Could you please paste the full error message you get after putting `qmlimportscanner` in `bin` ?

**Comment by yuriy-mochurad** [comment]
I do not use conan's `Virtualrunenv`. In general deployment is executed from my cmake script, but to cut the complexity it can also be reproduced from bash command line. So command looks like this:
```
> $ ~/.conan/data/qt/6.2.1/_/_/package/664ff38ff1fdbe812ce50815b42f83214a3da0f0/bin/macdeployqt <path_to_compiled_app> -qmldir=<path_to_qml>
ERROR: qmlimportscanner not found at "~/.conan/data/qt/6.2.1/_/_/package/664ff38ff1fdbe812ce50815b42f83214a3da0f0/bin/qmlimportscanner"
ERROR: Rebuild qtdeclarative/tools/qmlimportscanner
```

If I copy `qmlimportscanner` to `bin` folder I get this:
```
WARNING: QML file parse error (deployment will continue):
WARNING: "dyld[1378]: Library not loaded: @rpath/libQt6Core.6.dylib\n  Referenced from: ~/.conan/data/qt/6.2.1/_/_/package/664ff38ff1fdbe812ce50815b42f83214a3da0f0/bin/qmlimportscanner\n Reason: tried: '~/.conan/data/qt/6.2.1/_/_/package/664ff38ff1fdbe812ce50815b42f83214a3da0f0/bin/libQt6Core.6.dylib' (no such file),...<many_more_search_paths_here>"
ERROR: qmlimportscanner output error. Expected json array, got:
ERROR: ""
```

**Comment by ericLemanissier** [comment]
Could it be that macOS's `System Integrity Protection` is preventing the loading of these libraries ? can you try to forward directly LD_LIBRARY_PATH and DYLD_LIBRARY_PATH to macdeployqt ?

**Comment by yuriy-mochurad** [comment]
@ericLemanissier it is not exist, because this library is created under `lib` folder, exactly as `qmlimportscanner `.
So it looks like `qmlimportscanner ` expects this library to be in the same folder as it is

**Comment by yuriy-mochurad** [comment]
@ericLemanissier but it also tries to search in paths like:
```
'~/.conan/data/pcre2/10.37/_/_/package/ababfd301154fd2c0c0456a4e244de72c25ab7c8/lib/libQt6Core.6.dylib' (no such file),
```
Not sure why, maybe we need to add qt library path as part of the qt conan configuration?

**Comment by yuriy-mochurad** [comment]
After copying `qmlimportscanner ` to `bin` folder and adding `lib` folder to `DYLD_LIBRARY_PATH ` deployment seems to be working as expecting

**Comment by yuriy-mochurad** [comment]
@ericLemanissier any specific reason why we set `${INSTALL_LIBEXECDIR}` to `lib` on macos and linux here: https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L521

I double checked locally on macos - if it is set to `bin` I do nor have any issues deploying the app, but I do not know what consequences it has.

**Comment by ericLemanissier** [comment]
originally it was mimicking this
https://github.com/qt/qtbase/blob/v6.2.1/cmake/QtBuild.cmake#L112-L116
But we had to change libexec to lib in this commit https://github.com/conan-io/conan-center-index/pull/5635/commits/5836158daf3d2ae5ca95e2a5bee291731dd27894 in order to fix this failure: https://github.com/conan-io/conan-center-index/pull/5635#issuecomment-849172970
If we change INSTALL_LIBEXECDIR, we probably have to change this line too https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L22, wdyt ?

**Comment by yuriy-mochurad** [comment]
@ericLemanissier thank you for hints. I will test it locally and if all good open a PR. Lets see if that will pass the build stage successfully :)
