### ISSUE TITLE
[request] opentelemetry-cpp/1.1.0

### ISSUE THREAD

**Issue by MathiasDanzeisen** [conan-io/conan-center-index#8189]
### Package Details
  * Package Name/Version: **opentelemetry-cpp/1.1.0**
  * Changelog: **https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.1.0**

Hi together,
it would be nice if we could make new version of opentelemetry available. 
I'm especially interested in the grpc/logging feature, could this be added as an option?

I guess at least the following [dependencies ](https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.1.0/third_party_release) need to be updated as well:
***gRPC=v1.39.1***
thrift=0.14.1
***abseil=20210324.0***
...
nlohmann-json=v3.9.1
opentelemetry-proto=v0.11.0
***prometheus-cpp=v0.11.0*** (might be added newly)

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

FYI: @seemk @uilianries

**Comment by seemk** [comment]
Is Prometheus exporter a requirement for you, or could this be left out?

**Comment by MathiasDanzeisen** [comment]
@seemk Thanks, for the reply! In our use case it it not needed.
