### ISSUE TITLE
[package] vulkan-validationlayers/1.2.182: Wrong VK_LAYER_PATH environment variable on windows

### ISSUE THREAD

**Issue by iKoznov** [conan-io/conan-center-index#8201]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **vulkan-validationlayers/1.2.182**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019**
  * Conan version: **conan  1.42.1**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Here is my CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.5)
project(Example CXX)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})
list(APPEND CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR})

if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
  message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
  file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/v0.16.1/conan.cmake"
                "${CMAKE_BINARY_DIR}/conan.cmake"
                EXPECTED_HASH SHA256=396e16d0f5eabdc6a14afddbcfff62a54a7ee75c6da23f32f7a31bc85db23484
                TLS_VERIFY ON)
endif()

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_run(
        REQUIRES vulkan-validationlayers/1.2.182
        GENERATORS virtualenv )
```

It generates environment.bat.env file, containing this path:
```
VK_LAYER_PATH=C:\.conan\aabbaa\1\bin;%VK_LAYER_PATH%
```

But it does not point to where files **VkLayer_khronos_validation.dll** and **VkLayer_khronos_validation.json** are located, actualy they are in `C:\.conan\aabbaa\1\lib`

</details>

**Comment by SpaceIm** [comment]
Yes correct.

Actually, the first version packaged for vulkan-validationlayers has a patch to install `VkLayer_khronos_validation.dll` and `VkLayer_khronos_validation.json`. While creating this recipe, I've also submitted a PR to upstream, to improve installation, it was merged but they without modification of install location of dll and json: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2551#discussion_r581430471
In the meantime, we have packaged new versions, and forgotten to take into account that the location of these files was not the one of the first version packaged in CCI.
I'll fix that.

**Comment by SpaceIm** [comment]
Could you try https://github.com/conan-io/conan-center-index/pull/8225 please?

**Comment by iKoznov** [comment]
Now it fails:
```
ERROR: vulkan-validationlayers/1.2.182: Error in package() method, line 146
	shutil.move(bin_file, os.path.join(self.package_folder, "bin", os.path.basename(bin_file)))
	FileNotFoundError: [Errno 2] No such file or directory: 'C:\\.conan\\22c7b1\\1\\bin\\VkLayer_khronos_validation.dll'
```

Creating bin directory helps:
```
# move dll and json manifest files in bin folder
for ext in ("*.dll", "*.json"):
    for bin_file in glob.glob(os.path.join(self.package_folder, "lib", ext)):
        bin_dir = os.path.join(self.package_folder, "bin")
        os.makedirs(bin_dir, exist_ok=True)
        shutil.move(bin_file, os.path.join(bin_dir, os.path.basename(bin_file)))
```

**Comment by SpaceIm** [comment]
Indeed. It's fixed now (but not yet merged).

**Comment by iKoznov** [comment]
Now it works. Thanks!
