### ISSUE TITLE
[package] autoconf/2.71: Conan v2 incompatible: build_type setting should be defined

### ISSUE THREAD

**Issue by drmacdon** [conan-io/conan-center-index#8237]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **autoconf/2.71**
  * Operating System+version: **OSX 12.01**
  * Compiler+version: **apple-clang 13.0**
  * Conan version: **conan 1.42.2**
  * Python version: **Python 3.9.9**

### Conan profile
```
[settings]
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
build_type=Release
[options]
[conf]
[build_requires]
[env]
CONAN_V2_MODE=1
```

### Steps to reproduce
```bash
conan install autoconf/2.71@ --build
```

### Logs
```bash
ERROR: autoconf/2.71: Error in build() method, line 82
	autotools.make()
	ConanV2Exception: Conan v2 incompatible: build_type setting should be defined.
```

**Comment by SSE4** [comment]
fix has been merged
