### ISSUE TITLE
Question: How to skip running tests while cross-building?

### ISSUE THREAD

**Issue by mbodmer** [conan-io/conan-center-index#824]
There are many test_package conanfiles trying to run produced binaries.

e.g: zlib/1.2.11 on line 23/24:

```python
if "x86" in self.settings.arch:
            self.run(os.path.join("bin", "test"), run_environment=True)
```

Now I am trying to cross-compile this package with mingw from Linux to Windows.

Does this really have to be handled in each package (more or less sophisticated), or should this not be handeld in e.g. self.run(). Or should this already be the case, but I am doing something wrong?

Hope can I suppress running these cross binaries? I am also using conan-package-tools, but this shouldn't be of concern here.

**Comment by SSE4** [comment]
hi @mbodmer 
the idiomatic way is to use **tools.cross_building**, for example:
https://github.com/conan-io/conan-center-index/blob/dc2819f0dcd7fe2b9ffc0fdee1b4a2c7fb6e764e/recipes/sqlite3/all/test_package/conanfile.py#L18

**Comment by mbodmer** [comment]
OK, thanks.
