### ISSUE TITLE
[package] poco/1.11.1: Incorrect option for Active Record and missing option for Active Record Compiler

### ISSUE THREAD

**Issue by lbakman** [conan-io/conan-center-index#8266]
**Incorrect option name: enable_active_record**

"enable_active_record" should be renamed to "enable_activerecord" to match the option name in the CMakeLists.txt.

The CMakeLists.txt contains the following option:
option(ENABLE_ACTIVERECORD "Enable ActiveRecord" ON)

**Missing option name: enable_activerecord_compiler**

Add the option "enable_activerecord_compiler" to allow the Active Record Compiler feature to be enabled/disabled.

The CMakeLists.txt contains the following option:
option(ENABLE_ACTIVERECORD_COMPILER "Enable ActiveRecord Compiler" ON)

It is not possible to enable or disable the Active Record Compiler from conan.

I believe the correct option should be:
"ActiveRecordCompiler": _PocoComponent("enable_activerecord_compiler", True, ["Util", "XML"], [], False),

The config_options() method should be updated to include:
```
        if tools.Version(self.version) < "1.11":
            del self.options.enable_activerecord
            del self.options.enable_activerecord_compiler
```
in stead of
```
        if tools.Version(self.version) < "1.11":
            del self.options.enable_active_record
```

**Comment by SpaceIm** [comment]
> "enable_active_record" should be renamed to "enable_activerecord" to match the option name in the CMakeLists.txt.

Is it worth changing the name (breaking change in interface of the recipe) for an extra space?

> I believe the correct option should be:
> "ActiveRecordCompiler": _PocoComponent("enable_activerecord_compiler", True, ["Util", "XML"], [], False),

Well actually it should not be added like this in the recipe because it's a tool, not a library. Moreover, it depends on Foundation, not XML: https://github.com/pocoproject/poco/blob/de61f0049175a941cc83c2615c3bdc5e947b89f9/ActiveRecord/Compiler/CMakeLists.txt#L17

**Comment by lbakman** [comment]
Concerning enable_active_record: The way it is today, it simply does not work.

Setting poco:enable_active_record=False does nothing. The conan option is mapped directly to the CMake option thorugh "copm.option.upper()". 

I have no preference as to where the change should be made (conan or poco CMakeLists.txt), but it currently does not work.

Concerning enable_activerecord_compiler: 

I thought that the last flag of the _PocoComponent tuple indicated whether the component was a library or not ("is_lib"). If that is not the case, then I guess that my line is incorrect.

As for the dependencies. Those are set by trial and error. Foundation is not an optional component - it is always built. Util depends on Foundation, so I figured that by specifying Util, I would get Foundation indirectly. Also, it does depend on XML. It may not be evident from the CMakeLists.txt file, but you cannot compile the Active Record Compiler tool unless you also enable XML.

This file references the XML component: https://github.com/pocoproject/poco/blob/poco-1.11.1/ActiveRecord/Compiler/src/Parser.cpp

The Active Record Compiler currently gets its dependency on XML from the Util component. But where the Util component can handle a disabled XML component, Active Record Compiler cannot.

If the last flag is indeed indicating whether the output is a library or not, I would argue that the component could be changed to this:
"ActiveRecordCompiler": _PocoComponent("enable_activerecord_compiler", True, ["Foundation", "Util", "XML"], [], False),

My goal is to be able to disable the Active Record component and the Active Record Compiler using the official recipe, and currently I cannot.

Regards

Lau

**Comment by SpaceIm** [comment]
I see, so yes the typo in option name has side effect for this specific recipe due to how conan options and CMake options are mapped here.
My understanding of is_lib property in this dictionnary is to tell wheither it's header only or not (mainly for `package_info()`). Maybe there should be an enumerate: lib, header_only, executable.

**Comment by SpaceIm** [comment]
Yes but it shouldn't be too hard to add it.

**Comment by lbakman** [comment]
I will create a pull request to fix this problem. I have used an alternative recipe since I originally posted this issue.
I would prefer using the original recipe, but I have postponed creating a pull request due to our dicussion about is_lib.

**Comment by lbakman** [comment]
@tuduongquyet I guess you beat me to it.

**Comment by lbakman** [comment]
@tuduongquyet Sorry. Not to disregard your pull request, but I believe that the changes in my pull-request has seen more use as I have been using them in a local recipe since December 2021.

**Comment by tuduongquyet** [comment]
> @tuduongquyet Sorry. Not to disregard your pull request, but I believe that the changes in my pull-request has seen more use as I have been using them in a local recipe since December 2021.

Please use your PR and fix this issue.
