### ISSUE TITLE
[onetbb/2021.3.0] oneTBB and TBB are different versions of the same package

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-center-index#8308]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **onetbb/2021.3.0**

### Steps to reproduce (Include if Applicable)

Create the following conanfile:

```
[requires]
opencv/4.5.3
onetbb/2021.3.0

[options]
opencv:parallel=tbb
```
Then
```
conan install .
```

### Logs (Include/Attach if Applicable)
```
ERROR: At least two recipes provides the same functionality:
 - 'tbb' provided by 'onetbb/2021.3.0', 'tbb/2020.3'
```

Since both recipes are essentially different versions of the same package, Can I suggest moving both recipes into the same folder? (Maybe under `tbb` as this is more widely used, although `onetbb` is the new name - using the latter would necessitate changing any recipes currently using tbb)

**Comment by SpaceIm** [comment]
Since `onetbb` is the new name, I'm in favor to move old versions to `onetbb` recipe and deprecate `tbb` recipe.
Therefore all recipes depending on tbb should change to depend on onetbb.

**Comment by SpaceIm** [comment]
deprecate tbb recipe: https://github.com/conan-io/conan-center-index/pull/9162
support all versions in onetbb recipe: https://github.com/conan-io/conan-center-index/pull/9164
