### ISSUE TITLE
[request] llvm-core/13.0.0

### ISSUE THREAD

**Issue by kexianda** [conan-io/conan-center-index#8328]
### Package Details
  * Package Name/Version: **llvm-core/13.0.0**
  * Changelog: **https://releases.llvm.org/13.0.0/docs/ReleaseNotes.html**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by kexianda** [comment]
PR: https://github.com/conan-io/conan-center-index/pull/8329

**Comment by czoido** [comment]
Thanks for reporting, closing as it's already in Conan Center.
