### ISSUE TITLE
[question] flatbuffers/2.0.0: flatc application not present, flatc/2.0.0 does not exist, where do we get flatc?

### ISSUE THREAD

**Issue by kk49** [conan-io/conan-center-index#8374]
Related to #4039.

With the latest flatbuffers release 2.0.0, there is now no way to get a matching flatc executable. Is there a fix in the works for this? #4039 claims there is an open PR for it, but I can't find it either. Did this issue fall through the cracks?

**Comment by toge** [comment]
How about `options_from_context=False` like following:
```
conan install -o flatbuffers:options_from_context=False flatbuffers/2.0.0@ --build=missing
```

**Comment by kk49** [comment]
> How about `options_from_context=False` like following:
> 
> ```
> conan install -o flatbuffers:options_from_context=False flatbuffers/2.0.0@ --build=missing
> ```

Do you know if that the recommend long term solution or is the flatc executable supposed to go back into the default package?

**Comment by toge** [comment]
I don't know the right way.
But I used to set `options_from_context=False` by reading  https://github.com/conan-io/conan-center-index/pull/3345#issuecomment-718679145

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/9292 should be a long term solution.
