### ISSUE TITLE
[question] ZeroMQ draft build

### ISSUE THREAD

**Issue by garndesh** [conan-io/conan-center-index#8377]
ZeroMQ has some of it's features marked as DRAFT that I would like to use. This is enabled by adding the ENABLE_DRAFTS definition to cmake but the current recipe does not support this option.

I think all that is needed is to add an option to the recipe like `"draft": [True, False]` that defaults to False and to add the cmake definition.

```
if self.options.draft:
    self._cmake.definitions["ENABLE_DRAFTS"] = True
```

Wat can I do to add this option to the recipe?

**Comment by toge** [comment]
Hello @garndesh .
I make PR for this issue.
I added three options(with_draft_api, with_websocket, with_radix_tree).
Please wait for merged.

I'm glad you will write some comments if you have some requests.
