### ISSUE TITLE
[package] qt/6.2.0+: Missing targets from qtdeclarative module

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan-center-index#8422]
From 6.2.0 forwards Qt moved targets for a lot of modules into the QtDeclarative module, but the targets still exist:
https://github.com/qt/qtdeclarative

Specifically, the recipe doesn't create the target for QtQuickControls2, because the module is no longer available. But the issue is that the target still must exist, because otherwise it's a breaking change for consuming recipes and it does exist in the upstream: https://github.com/qt/qtdeclarative/blob/dev/src/quickcontrols2/CMakeLists.txt

/cc @ericLemanissier

**Comment by ericLemanissier** [comment]
indeed, sorry about that. For my defense, this was not easy/possible to spot on https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.0/release-note.md and https://www.qt.io/blog/qt-6.2-lts-released

**Comment by ericLemanissier** [comment]
Well, the qtmodules.conf directly comes from upstream repo qt5 (.gitmodules). I don't think qt provides a description of targets per module. Do you think of a file written by hand?

**Comment by Minimonium** [comment]
Aha, I missed that it's an upstream one. Yeah, not sure. They're pretty cooperative these days, maybe they could agree to encode some target information in there too.

**Comment by ericLemanissier** [comment]
Maybe we could create python file for each qt version, which would populate self.cpp_info. This file would be imported (as pyhon import) from the main recipe and exported with the recipe (as conan export). The function would then be called from package_info(self)
That would have the advantage of avoiding the rebuild of all qt versions each time there is a change in the components.
