### ISSUE TITLE
[question] Why Qt plugins are not in LD path?

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#8444]
I have expanded qt test_package to include qtwidgets, you can take a look at my branch
https://github.com/conan-io/conan-center-index/compare/master...AndreyMlashkin:add_qt_gui_example?expand=1

It fails here:
qt/6.2.2 (test package): Running test()
qt/6.2.2 (test package): Testing qmake
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Resource content: "Hello World From Resource\n"
"Hello World!"
qt/6.2.2 (test package): Testing CMake_find_package_multi
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
ERROR: qt/6.2.2 (test package): Error in test() method, line 131
	self._test_with_cmake_find_package_multi()
while calling '_test_with_cmake_find_package_multi', line 125
	self.run(os.path.join("bin", "test_package"), run_environment=True)
	ConanException: Error 134 while executing bin/test_package

As I see, in conanfile of the test, it is run with run_environment=True. My question is then, why plugins folder is not included to bin paths?

**Comment by SpaceIm** [comment]
I guess some run_env vars are not properly set in qt recipe like `QT_QPA_PLATFORM` or `QT_PLUGIN_PATH`.

**Comment by ericLemanissier** [comment]
The easiest workaround is to use option qt:shared=True.
Otherwise please check the solution mentioned in https://github.com/conan-io/conan-center-index/issues/6318#issuecomment-920832506

**Comment by AndreyMlashkin** [comment]
qt:shared=True fixes the issue, thank you!
