### ISSUE TITLE
[request] zlib/1.2.11 needs macos compiler.version=13.0 variant

### ISSUE THREAD

**Issue by igagis** [conan-io/conan-center-index#8456]
Currently, when building under `macos 11.6` the following error occurs:

```console
ERROR: Missing binary: zlib/1.2.11:e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc
zlib/1.2.11: WARN: Can't find a 'zlib/1.2.11' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.version=13.0, os=Macos
- Options: fPIC=True, minizip=deprecated, shared=False
- Dependencies: 
- Requirements: 
- Package ID: e4fbacdee83eb1a2e68227ffe19f6e9a61b36cbc
```

the zlib package doesn't provide variant with compiler version `13`

**Comment by ericLemanissier** [comment]
this compiler is not supported by Conan-Center-Index yet, (this is not specific to zlib). cf https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md#macos

**Comment by igagis** [comment]
@ericLemanissier any estimates of when it will be supported?

**Comment by igagis** [comment]
now `compiler.version=14` is needed...
