### ISSUE TITLE
[package] zstd/1.4.4: Missing in config.yml

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#846]
Package Name/Version: **zstd/1.4.4**

https://github.com/conan-io/conan-center-index/pull/694 added 1.4.4 in conandata.yml, but 1.4.4 was not added in config.yml

**Comment by uilianries** [comment]
Thanks for reporting @SpaceIm !

**Comment by danimtb** [comment]
You are totally right! Thanks for the report. Will fix it ASAP
