### ISSUE TITLE
[question] How to set all dependent Conan package CXXFLAGS parameters

### ISSUE THREAD

**Issue by nmgwddj** [conan-io/conan-center-index#8460]
I have found a way to set [env] in default profile, like this:

```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=13.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
CFLAGS="-fvisibility=hidden -fvisibility-inlines-hidden"
CXXFLAGS="-fvisibility=hidden -fvisibility-inlines-hidden"
```

But this depends on the default configuration of each CI machine, and I don't want to maintain a separate profile configuration file, because it is very cumbersome to specify this configuration every time CMake configure.
Is there any other more elegant way to set this configuration?

**Comment by SpaceIm** [comment]
It's not related to conan-center but conan client.

You probably don't want to propagate symbol visibility to all dependencies. It's either managed internally or not handled by each dependency.

**Comment by nmgwddj** [comment]
> It's not related to conan-center but conan client: https://github.com/conan-io/conan/issues
> 
> You probably don't want to propagate symbol visibility to all dependencies. It's either managed internally or not handled by each dependency.

Thanks, move to conan client.
