### ISSUE TITLE
[question] ms-gsl/2.0.0 recipe changed and forced Conan update

### ISSUE THREAD

**Issue by Novakov** [conan-io/conan-center-index#8463]
Pull request https://github.com/conan-io/conan-center-index/pull/8281 changed minimum required Conan version for `ms-gsl` recipe, this resulted in requirement of newer Conan version even for **old** version 2.0.0. While this change itself is not terrible on it's own Conan 1.43.0 removed `cmake_target_namespace` property (https://github.com/conan-io/conan/pull/10099) which we use in ~30 recipes for our internal packages. 

With Conan 1.43 CMake files generated by `CMakeDeps` generator uses different target names than files generated by previous version which results in CMake (correctly) complaining about missing targets and none of our packages is able to build. 

With Conan 1.40 we cannot use `ms-gsl/2.0.0` package as it requires Conan 1.43.0+

I know that `CMakeDeps` generator is marked as experimental and understand the need to go forward and brake things from time to time and will work out some way to clean up our internal packages (suggestions welcome!). I'm creating issue here because I think that it might be interesting case of butterfly effect to consider with future changes in Conan or recipes on ConanCenter.

**Comment by SSE4** [comment]
even if a recipe has changed, old revisions are still available, we never remove them. we don't force you to always use the latest revision of the package. if breakage is a serious concern, usage of lock files and revisions is recommended.

**Comment by Novakov** [comment]
For consumer project we are using lockfiles but only base lockfile which stores only version (full lockfile is generated during build and depends on few options selected by user). For packages we do not use lockfiles to allow them to be built with newest versions of dependencies. 

Using full lockfiles would save us from the issue but that's a bit different approach and has it's own set of pros & cons.

**Comment by danimtb** [comment]
@Novakov for direct dependencies is easy to depend on older recipe revisions:

```
$ conan search ms-gsl/2.0.0@ --revisions -r conancenter
Revisions for 'ms-gsl/2.0.0' at remote 'conancenter':
c5e1606d1254064ddf1068644f93f6bf (2021-12-14 11:35:15 UTC)
a8aed8e8b6c7485d007560c3fc60412e (2021-11-29 12:31:41 UTC)
0422329ed82acd68d276c07ae14d9a35 (2021-10-29 23:40:48 UTC)
abb835f05e9749a8e3fb501aa630135a (2020-09-02 19:17:26 UTC)
b57ed14543fb6eb3abd2a82fdc3ea84b (2020-04-30 13:22:05 UTC)
3d48a6c36e2d91412349184786bdaa4d (2020-04-23 10:10:43 UTC)
80da3e83294a567dc8fd8349dbf78aff (2019-12-19 08:50:27 UTC)
1ba60117aa280fa405c9462a7f80a254 (2019-10-13 07:37:15 UTC)
```

In my case, running with Conan 1.41.0, I had to use revision `a8aed8e8b6c7485d007560c3fc60412e` in my conanfile.txt:

```
(py37-conan) λ conan install . --update
...
ms-gsl/2.0.0: Retrieving from server 'conancenter'
ms-gsl/2.0.0: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.10k]
Downloading conanfile.py completed [3.20k]
Downloading conan_export.tgz completed [0.25k]
Decompressing conan_export.tgz completed [0.00k]
ms-gsl/2.0.0: Downloaded recipe revision a8aed8e8b6c7485d007560c3fc60412e
conanfile.txt: Installing package
Requirements
    ms-gsl/2.0.0 from 'conancenter' - Downloaded
Packages
    ms-gsl/2.0.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download

Installing (downloading, building) binaries...
ms-gsl/2.0.0: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'conancenter'
Downloading conanmanifest.txt completed [0.59k]
Downloading conaninfo.txt completed [0.25k]
Downloading conan_package.tgz completed [26.43k]
Decompressing conan_package.tgz completed [0.00k]
ms-gsl/2.0.0: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
ms-gsl/2.0.0: Downloaded package revision a2b78228f75651aeabfdcaf58d065f90
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
```

**Comment by jgsogo** [comment]
Hi, @Novakov , I'm submitting this to the docs in this project (https://github.com/conan-io/conan-center-index/pull/8488), hope it adds some context to this issue. We have also asked for some whitepaper about best-practices when consuming Conan recipes.

You need to understand that ConanCenter needs to work also in the interest of Conan, and now we are struggling to define a compatible subset of features that will make recipes compatible with v2, so eventually all the recipes will be moving to new Conan versions (once they start to use new generators). This is something that sooner or later will happen.

Conan also needs feedback from these new features (some are experimental) and needs to be sure that the behavior that (alpha/beta-)users are executing is the _current_ one (for example, `set_property` in `cpp_info` has modified its internal logic in the latest releases) so their feedback value is maximized.

I hope my additions to this repository on the docs side are visible enough and help to highlight this problem and features that can serve as a workaround (revisions, lockfiles, local Artifactory). It should also be the recommended way to consume recipes from ConanCenter (I also use them, even in [my toy projects](https://github.com/jgsogo/blog-emsdk-magnum-viewer)). Please, feel free to comment in the PR and ask for more clarification or anything that you think could serve to other people facing the same issue.

Thanks!

**Comment by Novakov** [comment]
I understand that both Conan and ConanCenter need to evolve and that sometimes things can be broken and/or updated. I opened issue here to let you know that logical chain of decisions and actions resulted in a bit unfortunate situation for us, so maybe there is something that can be improved. 
Best practices for consuming recipes is very much appreciated and I'm looking forward to read it. I read the changes to docs you did and they clarify a lot of things - we were using our own repository (conan-server actually), so re-uploading working version of `ms-gsl` and removing conancenter solved the issue for us (we still need to update our packages to new Conan version but that's for a bit later). 
Unfortunately solutions you mentioned need to be applied before encoutering problems, so users have to be aware of them from the beginning which can be hard because there are a lot of concepts in Conan ecosystem and getting good view of what is going on is not a trivial task (I hope that white paper and constantly improving docs could solve that problem). 
Regarding revisions and lockfiles - that approaches are a bit troubling for me. My understanding is that for building packages it is good to use newest possible version of dependencies so you will get all possible bug fixes and package is not limiting it's consumers when it comes to version ranges. Of course there is problem of ABI-compatibility but that can be solved by following semver versioning. By using package revisions and/or lockfiles we are effectively pinning specific versions of dependencies and manually update them to newer versions. While doable that put significant workload on package creators. On the other hand we using revision/lockfiles can prevent problems with breaking changes inside Conan/ConanCenter recipes, so there are two conflicting factors and to be honest I don't know how to balance them. 

I love that Conan and ConanCenter is evolving and fixing things from time to time is something that I'm willing to do. I hope that you will find this discussion useful (It is useful for me!) and maybe someone in future will dig up this issue to weight different approaches in their own situation.
