### ISSUE TITLE
[package] spdlog/1.9.2: Crashes Apple clang 13 on macos-11 (Github Actions) in C++20.

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan-center-index#8480]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spdlog/1.9.2**
  * Operating System+version: **macOS 11.6.2 (from github actions)**
  * Compiler+version: **apple clang 13.0.0**
  * Conan version: **conan 1.43.1**
  * Cpp standard: **20**

### Minimal example

I made a repository triggering the issue: https://github.com/Adnn/spdlog192_appleclang_crash/actions/runs/1606462938

### Steps to reproduce

Running this command:

    conan install --build=missing -s compiler.cppstd=20 spdlog/1.9.2@

On the environment results in a compiler crash:

> [ 71%] Building CXX object source_subfolder/CMakeFiles/spdlog.dir/src/async.cpp.o
> clang: error: unable to execute command: Segmentation fault: 11
> clang: error: clang frontend command failed due to signal (use -v to see invocation)
> Apple clang version 13.0.0 (clang-1300.0.29.3)
> Target: x86_64-apple-darwin20.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode_13.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> clang: note: diagnostic msg: 
> 
> PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
> Preprocessed source(s) and associated run script(s) are located at:
> clang: note: diagnostic msg: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/file_sinks-937046.cpp
> clang: note: diagnostic msg: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/file_sinks-937046.sh
> clang: note: diagnostic msg: Crash backtrace is located in
> clang: note: diagnostic msg: /Users/runner/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
> clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
> clang: note: diagnostic msg: 
> 

---

I will also post on spdlog issue tracker.

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported, most importantly, dependency versions have changed.

I've successufly compiled `spdolg` locally locally with `apple-clang v15`:
```sh
$ conan create recipes/spdlog/all --version 1.9.2 --build=missing -s compiler.cppstd=20

Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=15
os=Macos
...
spdlog/1.9.2 (test package): Running CMake.build()
spdlog/1.9.2 (test package): RUN: cmake --build "/Users/perseo/sources/conan-center-index/recipes/spdlog/all/test_package/build/apple-clang-15-armv8-20-release" -- -j14
[ 50%] Building CXX object CMakeFiles/test_package.dir/test_package.cpp.o
[100%] Linking CXX executable test_package
[100%] Built target test_package

======== Testing the package: Executing test ========
spdlog/1.9.2 (test package): Running test()
spdlog/1.9.2 (test package): RUN: ./test_package
[2024-09-10 15:56:52.333] [info] Welcome to spdlog version 1.9.2  !
```
