### ISSUE TITLE
[package] openssl/1.0.2u: linking against libcrypto.a causes linker to set the EXEC_STACK bit in the executable

### ISSUE THREAD

**Issue by cleeland** [conan-io/conan-center-index#851]
When building and linking 64 bit ELF binaries, the linker follows rather arcane rules for determining whether the resulting executable needs an executable stack (good summary of rules is at http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka14320.html).  As it turns out, libcrypto.a as built by this recipe contains several `.o` files which include `.note.GNU-stack` as well as a handful of `.o` files that do not have that section, and the linker marks the resulting executable as needing an executable stack.

This is a direct consequence of the recipe using `./Configure` rather than `./config`.  The `./config` script contains specific checks that ensure that the assembler gets invoked with `--noexecstack` if the assembler supports that option, whereas `Configure` contains no such logic, and from what I can tell offers no option to enable such a thing.

It's not clear why the recipe chose "Configure" rather than "config" for unix targets.  I also haven't been able to test against a packaged 1.1.1.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openssl/1.0.2u**
  * Operating System+version: **Linux Centos 7.6**
  * Compiler+version: **devtoolset-7 (gcc-7)**
  * Conan version: **conan 1.21.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Put your profile output here
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by SSE4** [comment]
interesting thing that `./config` and `./Configure` have so different effects. I'll take a look.

**Comment by cleeland** [comment]
It looks like the probe (and subsequent use) of `--noexecstack` has been moved from `config` to `Configure` in 1.1.1, and a quick inspection of the 1.1.1d static library produced by the current recipe suggests confirmation of this.

It looks like https://github.com/openssl/openssl/pull/6174 fixed this in 1.1.1 in the upstream, but never got backported to 1.0.2.

**Comment by cleeland** [comment]
An easy way to check whether a static library has all .o files with .note.GNU-stack section:

1. Count the number of .o files in the library: ```$ ar t /path/to/libcrypto.a | wc -l```
2. Count the number of `.note.GNU-stack` sections in the library: ```$ readelf -St /path/to/libcrypto.a | grep -c .note.GNU-stack```

Those numbers should be equal.  If they aren't (the result from step 2 would return a lower value) then the lib contains "mixed" object files.

NOTE: I've considered integrating this step into `test_package` as a validation step, although I haven't studied yet on how to only perform certain packaging steps when the library under test is on an ELF system.

**Comment by SSE4** [comment]
I think it wasn't backported because 1.0.2 is EOL already. since 1.1.1 works as expected, do you still want this to be fixed?

**Comment by cleeland** [comment]
They are still releasing lettered 1.0.2 (most recent was 1.0.2u in late december 2019), and moving from 1.0.x to 1.1.x is a breaking change.

Basically, we moved from a system-distributed openssl to the conan-based variant of the same release line, and things broke in very subtle but significant ways that cost probably 100+ engineering hours to hunt down.  Plus it's a viral security risk.

**Comment by Croydon** [comment]
> They are still releasing lettered 1.0.2 (most recent was 1.0.2u in late december 2019)

1.0.2u is the last patch in the 1.0.2 series. As @SSE4 said, it is EOL

**Comment by perseoGI** [comment]
Hi there! 
I'm closing this very old issue as `openssl/1.0.2u` was deprecated a long time ago.

If this issue remains, do not hesitate to reopen it! 😄
