### ISSUE TITLE
[request] liboping/1.10.0

### ISSUE THREAD

**Issue by MauriceS-WTI** [conan-io/conan-center-index#8581]
### Package Details
  * Package Name/Version: **liboping/1.10.0**
  * Website: **https://noping.cc/**
  * Source code: **https://github.com/octo/liboping/**

### Description Of The Library / Tool
liboping is a C library to generate ICMP echo requests, better known as “ping packets”. It is intended for use in network monitoring applications or applications that would otherwise need to fork ping(1) frequently.

**Comment by perseoGI** [comment]
Hi there! 
Thank you for your request. 
It's been a while since this issue was open and as you can see here https://conan.io/center/recipes/liboping?version=1.10.0, recipe is already supported in CCI.

Happy coding 🐸
