### ISSUE TITLE
[question] (keychain) Component not found for transitive pkg_config dependency

### ISSUE THREAD

**Issue by hrantzsch** [conan-io/conan-center-index#8601]
I'm stuck trying to fix the [keychain recipe](https://github.com/conan-io/conan-center-index/blob/e560a620c69dfa7fd0f7e53fb1c39222d22da7b3/recipes/keychain/all/conanfile.py), which is broken on Linux.

On Linux, keychain depends on [libsecret](https://github.com/conan-io/conan-center-index/blob/e560a620c69dfa7fd0f7e53fb1c39222d22da7b3/recipes/libsecret/all/conanfile.py) which in turn depends on [libgcrypt](https://github.com/conan-io/conan-center-index/blob/e560a620c69dfa7fd0f7e53fb1c39222d22da7b3/recipes/libgcrypt/all/conanfile.py). Trying to build the keychain package I get
```
keychain/1.2.0: Building your package in /home/hannes/.conan/data/keychain/1.2.0/_/_/build/20ab154eea08dcc30d1a21570a4979ff53ff917e
keychain/1.2.0: Generator cmake created conanbuildinfo.cmake
keychain/1.2.0: ERROR: Generator pkg_config(file:None) failed
Component 'libgcrypt::gcrypt' not found in 'libgcrypt' package requirement
ERROR: Component 'libgcrypt::gcrypt' not found in 'libgcrypt' package requirement
```

Building libsecret works fine. When setting `with_libgcrypt=False` for libsecret, keychain is also built successfully. Only if the transitive dependency is required I get the error above.

Any idea where the issue is? It feels like it would be a problem with the libsecret recipe, but is there anything else I need to do in addition to
```
    self.cpp_info.requires.append("libgcrypt::gcrypt")
```

**Comment by SpaceIm** [comment]
Yes, I don't even understand how https://github.com/conan-io/conan-center-index/pull/7368 could have passed CI.

**Comment by hrantzsch** [comment]
Thanks for the quick investigation and fix!

**Comment by ericLemanissier** [comment]
I guess it passed CI ([and it still does](https://github.com/eirikb/proof-of-conan/runs/4690983909?check_suite_focus=true)) because the test recipe [only uses the `cmake` generator](https://github.com/conan-io/conan-center-index/blob/4ddb4fef04eee681b17506e5bac1a879a1dad321/recipes/libsecret/all/test_package/conanfile.py#L7)
It looks like this generator ignores non existing components. or maybe it just ignores `self.cpp_info.requires`
