### ISSUE TITLE
[request] protobuf/3.5.2

### ISSUE THREAD

**Issue by Morwenn** [conan-io/conan-center-index#864]
### Package Details
  * Package Name/Version: **protobuf/3.5.2**
  * Changelog: *empty*

Not an upstream request but a downstream request: protobuf seems to have a fairly strong version lock-in, and the Conan Community package `opencv/4.1.1@conan/stable` requires `protobuf/3.5.2`. So far so good since there is a Bincrafters recipe in the old Conan Center packages. However it doesn't follow the current rules of CCI and provides its own CMake config files, which causes some problems here and there. Would it be possible to add `protobuf/3.5.2` to CCI?

**Comment by Croydon** [comment]
Personally, I don't feel comfortable adding even more protobuf version to CCI until we have figured protobuf+protoc out 

https://github.com/conan-io/conan-center-index/pull/65

**Comment by Morwenn** [comment]
Oh, I wasn't aware that there was such a problem, my bad.

**Comment by leyewen** [comment]
Unfortunately, `opencv/4.1.1@conan/stable` strongly dependency `protobuf-3.5.2` version. Since `protobuf-3.8.0` removed vestigial `wire_format_lite_inl.h`, you only can use `protobuf` < `3.8.0` for `opencv/4.1.1` building. Add `protobuf/3.5.2@bincrafters/stable` dependency instead.
