### ISSUE TITLE
[request] bullet3/3.21

### ISSUE THREAD

**Issue by MattClemson** [conan-io/conan-center-index#8649]
### Package Details
  * Package Name/Version: bullet3/3.21
  * Changelog: https://github.com/bulletphysics/bullet3/releases/tag/3.21

The above mentioned version was released in December by the upstream project and is not yet available as a recipe. Would it be possible to add this version, please?

**Comment by SpaceIm** [comment]
@uilianries @SSE4 can be closed (https://github.com/conan-io/conan-center-index/pull/9676)
