### ISSUE TITLE
[package] <xorg>/<system>: Missing dependencies

### ISSUE THREAD

**Issue by daravi** [conan-io/conan-center-index#8711]
I think the following are missing from the list in yum/dnf section: "libICE-devel", "libSM-devel"

**Comment by ericLemanissier** [comment]
Just so that I understand why https://github.com/bincrafters/system-packages-checks did not show failure: are these packages implicitly installed ? Does this link to some failures?

**Comment by daravi** [comment]
To be honest I don't remember how I ended up finding this issue. I am going through my local recipes and trying to find PRs for the diffs I find since I am moving away from my Conan project in case. I think this was needed when I migrated from CentOS to AlmaLinux so maybe these are packages that are installed by default on CentOS but not on AlmaLinux. (CentOS successor) Now that I think about it maybe this ticket should be closed as incomplete as I don't have time to investigate this further.

**Comment by ericLemanissier** [comment]
I tried to replicate the problem, but the package already installs libICE-devel and libSM-devel on [almalinux](https://github.com/bincrafters/system-packages-checks/runs/4757877488?check_suite_focus=true) and [centos](https://github.com/bincrafters/system-packages-checks/runs/4757877590?check_suite_focus=true)

**Comment by daravi** [comment]
Thank you @ericLemanissier.
