### ISSUE TITLE
libusb: Build fails with Visual Studio and RelWithDebInfo

### ISSUE THREAD

**Issue by Trilion99** [conan-io/conan-center-index#8774]
Library name and version: libusb/1.0.24 (dependency from libftdi/1.5) 

Conan version: 1.42.1
Operating System: Win 10
Compiler: Visual Studio 2019

Build of libusb fails when compiler build type is set to RelWithDebInfo. Fixed by defaulting to Release if RelWithDebInfo is detected.

Fix: 

`        if self.settings.compiler == "Visual Studio" and self.settings.build_type == "RelWithDebInfo":
            self.output.info(f"libusb:build_type={self.settings.build_type} adjusted to Release")
            self.settings.build_type = "Release"`

added to the `    def configure(self):` block in the conanfile.

Similar to issue https://github.com/conan-io/conan-center-index/issues/8041

Will make a pull request if no further comments with a better way to solve this.

**Comment by SSE4** [comment]
yes, you're right, the fix is needed, feel free to create a new PR with a fix.
