### ISSUE TITLE
[request] cereal/1.3.0

### ISSUE THREAD

**Issue by tonyelewis** [conan-io/conan-center-index#879]
### Package Details
  * Package Name/Version: **cereal/1.3.0**
  * Changelog: **https://github.com/USCiLab/cereal/releases/tag/v1.3.0**

The above mentioned version is newly released (25 Oct 2019) by the upstream project and not yet available as a recipe. Please add this version.

Thanks very much.

**Comment by danimtb** [comment]
@tonyelewis we have a nice recipe in the conan-community repo that should be working https://github.com/conan-community/conan-cereal

Please feel free to take that recipe and contribute it to this repo via PR 😄

**Comment by tonyelewis** [comment]
@danimtb I can't see any mention of 1.3.0 in that repo. Am I being foolish?

**Comment by danimtb** [comment]
@tonyelewis no, that version is not there. But don't worry, PR #881 should fit your needs 😄

**Comment by tonyelewis** [comment]
Indeed. Thanks very much to everyone who's contributing to this issue / that PR.

**Comment by tonyelewis** [comment]
Thanks very much everyone.
