### ISSUE TITLE
[package] spdlog/1.8.2: why introduce breaking changes?

### ISSUE THREAD

**Issue by EnilPajic** [conan-io/conan-center-index#8791]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spdlog/1.8.2**
  * Operating System+version: **Windows 10, 11; macOS 11, 11.6**
  * Compiler+version: **MSVC; clang 11, 12, 13**
  * Conan version: **1.44.0**
  * Python version: **Python 3.9.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=13.0
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Maybe I misunderstood something, but our CI/CD pipeline, that worked for a long time, started to fail on 22nd December 2021. Nothing regarding the pipeline setup was changed. Re-run of old pipelines (that were successful) failed. 

I investigated and found [this](https://github.com/conan-io/conan-center-index/commit/b158c5e1538a8eb14f8beca342703b6f742a7db3#diff-01c43ca6e9b97cfb75be1640171375906433f05b6f426fe27581328967b669b8R130) diff, which changed spdlog recipe a lot. It changed the way cmake finds spdlog:

```python

         target = "spdlog_header_only" if self.options.header_only else "spdlog"
         self.cpp_info.set_property("cmake_file_name", "spdlog")
         self.cpp_info.set_property("cmake_target_name", "spdlog::{}".format(target)
         self.cpp_info.set_property("pkg_config_name", "spdlog")

         self.cpp_info.names["cmake_find_package"] = "spdlog"
         self.cpp_info.names["cmake_find_package_multi"] = "spdlog"
         self.cpp_info.components["libspdlog"].names["cmake_find_package"] = target
         self.cpp_info.components["libspdlog"].names["cmake_find_package_multi"] = target
```

So, we used spdlog as `spdlog::libspdlog`, as in `add_library(spdlog::libspdlog ALIAS spdlog)` and it worked... until 22nd Dec. 
The fix was easy, just use `spdlog::spdlog` but I'm wondering why spdlog's new recipe introduced breaking changes for older versions? Or I'm using spdlog wrong?

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
...
CMake Error at cmake/OurLib.cmake:113 (add_library):
  Target "our_target" links to target "spdlog::libspdlog" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  libOurLib/CMakeLists.txt:20 (add_libOurLib)


CMake Error at cmake/OutLib.cmake:260 (add_executable):
  Target "out_target2" links to target "spdlog::libspdlog" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  our_target2/cli/CMakeLists.txt:3 (add_ourLib_executable)
...
```

</details>

**Comment by SpaceIm** [comment]
The idea is to rely on recipe revision to avoid breaking CI.

This "component" will disapear anyway in conan v2 because it's a side effect of `.names` implementation when we have to model a CMake target like `namespace::name` where `namespace != name`.

**Comment by EnilPajic** [comment]
Thank you for quick answer! Yes, the idea of exact revision is what we're planning to do.
