### ISSUE TITLE
[package] scdoc: wrong version

### ISSUE THREAD

**Issue by cemkeylan** [conan-io/conan-center-index#8880]
Hello,

It seems you have packaged scdoc with the wrong version in <https://github.com/conan-io/conan-center-index/commit/d362fde3311fb2c21cb05cc53ff0b44b09076d12>. The correct version is `1.11.2`.

**Comment by SpaceIm** [comment]
Indeed

/ping @uilianries @SSE4 @jgsogo 

Is it possible to fix the recipe and remove 1.11.12 in conan-center despite the policy to not remove existing revisions?

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
I'm closing this issue as this issue is already solved
Happy coding 🐸

**Comment by SpaceIm** [comment]
solved by https://github.com/conan-io/conan-center-index/pull/22000
