### ISSUE TITLE
[package] libjpeg/9d: wrong SHA256 checksum

### ISSUE THREAD

**Issue by RalfKubis** [conan-io/conan-center-index#8921]
Same as in #4151

They have re-packed the tar-ball on 4. January 2022, again.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libjpeg/9d**
  * Operating System+version: **Windows-10.0.22000**
  * Compiler+version: **MSVC 1929**
  * Docker image: **n/a**
  * Conan version: **conan 1.44.1**
  * Python version: **Python 3.10.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
build libjpeg/9d

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Downloading conan_sources.tgz
libjpeg/9d: Configuring sources in x:\.conan\data\libjpeg\9d\_\_\source
ERROR: libjpeg/9d: Error in source() method, line 41
        tools.get(**self.conan_data["sources"][self.version])
        ConanException: sha256 signature failed for 'jpegsrc.v9d.tar.gz' file.
 Provided signature: 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee
 Computed signature: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a
```

</details>

**Comment by SpaceIm** [comment]
fixed in https://github.com/conan-io/conan-center-index/pull/7681, use the latest revision
