### ISSUE TITLE
[question] qt5.15.2 recipe. QtWebEngine missing.

### ISSUE THREAD

**Issue by bartiszosti** [conan-io/conan-center-index#8942]
Hello!
I need the QtWebEngine module but despite I've enabled it in options I don't have it.
I have license.

> conan create . qt/5.15.2@
-o qt:opengl=dynamic
-o qt:openssl=True
-o qt:commercial=True
-o openssl:shared=True
-o qt:qtmultimedia=True
-o qt:qtwebengine=True
-o qt:shared=True
-o qt:qtsvg=True
-o qt:qtlocation=True
-o qt:qtwebchannel=True
-o qt:qtquickcontrols2=True

> [settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
compiler.toolset=v143
build_type=Debug
[options]
[build_requires]
[env]

**Comment by ericLemanissier** [comment]
Can you please send the full build log ?

I just managed to start the build with -o qt:qtwebengine=True -o qt:shared=True -o qt:gui=True -o qt:qtdeclarative=True -o qt:qtlocation=True -o qt:qtwebchannel=True

**Comment by bartiszosti** [comment]
At this moment I can only send the error which occurs when I building my application.
![image](https://user-images.githubusercontent.com/64412654/149757465-0bf3966e-8f1b-4797-9116-6a526f590801.png)
I'll start the build and afterwards I'll share the log.

**Comment by bartiszosti** [comment]
[config.log](https://github.com/conan-io/conan-center-index/files/7920691/config.log)
Is it what you wanted?

**Comment by ericLemanissier** [comment]
no, what I need is the full console log, produced when building qt itself

**Comment by bartiszosti** [comment]
How to get it?

**Comment by ericLemanissier** [comment]
you can rebuilt qt by using the `-b qt` argument, and then simply cut and paste what is printed in the console.

did you follow the documentation https://doc.qt.io/qt-5/qtwebengine-platform-notes.html#windows
```
On Windows, the following additional tools are required:

Visual Studio 2017 version 15.8 or later, or clang-cl version 8 or later
Active Template Library (ATL), usually included in the Visual Studio installation
Windows 10 SDK version 10.0.19041 or later
Qt WebEngine can only be built on 64-bit Windows, with a x64-bit toolchain. For building Qt WebEngine for x86 applications, you need to configure and compile Qt with the Visual Studio 2017 x64 to x86 cross-compile toolchain. This toolchain can be set up on the command line by running vcvarsall.bat amd64_x86.
```

**Comment by bartiszosti** [comment]
![image](https://user-images.githubusercontent.com/64412654/151171790-920c7df5-67b5-4e74-84b4-2fd6b6ca46ca.png)
This is answer.

**Comment by shijunz** [comment]
I plan to enable build on the windows on arm64, it is possible?
