### ISSUE TITLE
[question] how to remove hooks

### ISSUE THREAD

**Issue by maidamai0** [conan-io/conan-center-index#8969]
I installed the hooks following the [Test the recipe locally](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#test-the-recipe-locally). Now I want to remove this because it prints many messages and takes longer time than a barely `conan create`.

the `conan config list` doesn't show anything like `hooks` so I don't know which one to remove with `conan config rm`

How can I do this?

**Comment by SpaceIm** [comment]
```
conan config rm hooks.conan-center
```
