### ISSUE TITLE
[meson] meson/0.59.1: meson 0.59.1 commented out; however, it's required to build glib.

### ISSUE THREAD

**Issue by lexknuther** [conan-io/conan-center-index#8982]
meson 0.59.1 is commented out; however, it's required to build glib.

**Comment by SpaceIm** [comment]
It doesn't mean that the recipe of 0.59.1 & packages are not in conan-center, just that this specific version is not maintained anymore in conan-center-index.

**Comment by lexknuther** [comment]
Is there some corresponding documentation for this?  Basically, we are trying to replicate a small subset of the conan-center-index packages on a private network and want to know what to look out for.

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

Of course, this problem does not exist anymore in `glib` recipe as meson is one of the lucky packages which are ABI backwards compatible and therefore, they can be used safely with version ranges, see https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges

Also se version range usage in `glib` recipe:
https://github.com/conan-io/conan-center-index/blob/12660248e804af3822fea18318285bb7f78a41a0/recipes/glib/all/conanfile.py?plain=1#L87

> Is there some corresponding documentation for this?

Not really... as @SpaceIm years ago, this behavior still remains. When a version is removed from CCI it does not mean that the recipe is deleted, nor their pre compiled binaries. It means that it will no longer receive future revisions of the recipe so if a bug is detected or a dependency changed or whatever possible change a recipe could suffer, it will no longer be reflected in that deprecated version. 
All in all, it is not recommended to use non supported versions of CCI but their recipes will remain.
