### ISSUE TITLE
[question] aws-sdk-cpp: should text-to-speech=True by default?

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan-center-index#8983]
On Linux if `aws-sdk-cpp:text-to-speech=True` it brings in an iceberg of dependencies for audio processing and even `x/system`.  On WIndows all of the dependencies are already there so it's no big deal, but building on a headless Linux box requires system packages to be added, not to mention a mountain of Conan packages that need to be built.

I don't think it's worth it based on how many people will use the feature.

WDYT?

**Comment by SpaceIm** [comment]
`text-to-speech` is a high level component, part of the default build of `aws-sdk-cpp`:
https://github.com/aws/aws-sdk-cpp/blob/30a3d7bad7b738a49402766963930e4ca62ac250/cmake/sdksCommon.cmake#L133-L139
https://github.com/aws/aws-sdk-cpp/blob/30a3d7bad7b738a49402766963930e4ca62ac250/cmake/sdks.cmake#L45-L70

So it's not a good idea to disable this one by default.

**Comment by sourcedelica** [comment]
That's reasonable.  Thanks.
