### ISSUE TITLE
[zulu-openjdk] Wrong package downloaded when cross compiling

### ISSUE THREAD

**Issue by edupazpix4d** [conan-io/conan-center-index#8999]
In the method `build`, the sources being downloaded rely on `self.settings.arch` whereas in cross_compiling this brings issues.

In our specific case, we are building Android ARM8 in a Macos X86_64 machine, so the package being downloaded is [["11.0.12"]["macos]["armv8"]](https://github.com/conan-io/conan-center-index/blob/master/recipes/zulu-openjdk/all/conandata.yml#L32) making the compilation fail. 

### Package and Environment Details
  * Package Name/Version: **zulu-openjdk/11.0.12**
  * Operating System+version: **Macos Monterrey 12.1 (21C52)**
  * Compiler+version: **Apple clang version 13.0.0 (clang-1300.0.29.30)**
  * Conan version: **conan 1.44.0**
  * Python version: **Python 3.9.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Android
os_build=Macos
os.api_level=24
arch=armv8
arch_build=x86_64
compiler=clang
compiler.version=9
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
Output of the Android build when using the zulu-openjdk package:
```
/Users/myuser/repos/build-ANDROID/applications/myapp/myapp-arm64-v8a/gradlew: line 172: /Users/myuser/.conan/data/zulu-openjdk/11.0.12/scan/stable/package/a5ad5696abf650a25eea8f377806b3d5fe234e6e/bin/java: Bad CPU type in executable
/Users/myuser/repos/build-ANDROID/applications/myapp/myapp-arm64-v8a/gradlew: line 172: /Users/myuser/.conan/data/zulu-openjdk/11.0.12/scan/stable/package/a5ad5696abf650a25eea8f377806b3d5fe234e6e/bin/java: Undefined error: 0
```

**Comment by SpaceIm** [comment]
It's not how cross-compilation should be done in conan now. Please use 2 profiles. CCI recipes don't handle the old 1 profile way to coss-compile.

**Comment by edupazpix4d** [comment]
Thanks for the feedback @SpaceIm .
