### ISSUE TITLE
[package] libmodbus: use github sources since the official site has expired certs

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#9012]
For `libmodbus` we use the sources from the official site:
https://github.com/conan-io/conan-center-index/blob/master/recipes/libmodbus/all/conandata.yml#L3

Currently that site is note reachable by Conan because of some expired certs, so the package can't be built.
```
ERROR: Error downloading file https://libmodbus.org/releases/libmodbus-3.1.6.tar.gz: 'HTTPSConnectionPool(host='libmodbus.org', port=443): Max retries exceeded with url: /releases/libmodbus-3.1.6.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))'
```

But if we go to the official site, there is a link to this github repo. So it looks like the code actually lives there. The site only stores tarballs.
https://libmodbus.org/ -> https://github.com/stephane/libmodbus/

I think we should update the recipe so we consume github's tarballs since it is a more reliable site. 
But there is a catch, for some reason the github version of the tarball does not package the `configure` script, only `configure.ac`. So tweaking of the recipe would be needed.
There is also a new version available.

Thanks,

Eric.

**Comment by Croydon** [comment]
We prefer to use official source downloads over the auto-generated tarballs from GitHub.

The website works again, so the downloads should too https://github.com/stephane/libmodbus/issues/626

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

I'm closing this issue as newer versions of this recipe do now point to GitHub tarballs. 
See https://github.com/conan-io/conan-center-index/pull/13236/files

Happy coding 🐸
