### ISSUE TITLE
[package] sdl/2.0.18: Debug library for Android don't have "d" in library name

### ISSUE THREAD

**Issue by paulo-coutinho** [conan-io/conan-center-index#9024]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl/2.0.18**
  * Operating System+version: **macos catalina**
  * Compiler+version: **clang 13**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.44.1**
  * Python version: **Python 3.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration (profile_host):
[settings]
arch=armv7
build_type=Debug
compiler=clang
compiler.libcxx=c++_static
compiler.version=11
os=Android
os.api_level=16
[options]
nativium_arch=armv7
nativium_product_name=Nativium
nativium_project_name=nativium
nativium_target=android
nativium_version=1.0.0
nativium_version_code=1
[build_requires]
*: android-ndk/r22
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Build `sdl/2.0.18` for `Android` in `Debug`

### Logs
<details><summary>Click to expand log</summary>

```
ld: error: unable to find library -lSDL2maind
ld: error: unable to find library -lSDL2d
```

</details>

**Comment by SpaceIm** [comment]
Indeed: https://github.com/libsdl-org/SDL/blob/release-2.0.18/CMakeLists.txt#L2681-L2683
