### ISSUE TITLE
[package] <fmt>/<8.1.1>: Invalid setting 'baremetal' is not a valid 'settings.os' value.

### ISSUE THREAD

**Issue by Ambrase** [conan-io/conan-center-index#9058]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **fmt/8.1.1**
  * Operating System+version: **Linux Centos 8.4.2105**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.44.1**
  * Python version: **Python 3.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)

Try to install fmt/8.1.1

</details>

Fmt can't be installed for me anymore. It seems this recipe is incorrect to the current Conan version
https://conan.io/center/fmt?tab=recipe
```
        elif self.settings.os == "baremetal":
```

Conan raises the following error:
ERROR: fmt/8.1.1: Error in config_options() method, line 52
        elif self.settings.os == "baremetal":
        ConanException: Invalid setting 'baremetal' is not a valid 'settings.os' value.
Possible values are ['AIX', 'Android', 'Arduino', 'Emscripten', 'FreeBSD', 'Linux', 'Macos', 'Neutrino', 'SunOS', 'Windows', 'WindowsCE', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

**Comment by SpaceIm** [comment]
Your `settings.yml` is outdated.

**Comment by ivabrajer** [comment]
I don't think that's it. I've cleaned entire local Conan cache just in case and the issue is still happening. But I'll check it out once more tomorrow.

**Comment by SpaceIm** [comment]
At least it's in the release note of conan 1.43.0: https://github.com/conan-io/conan/releases/tag/1.43.0

**Comment by JorgenPo** [comment]
I had the similar issue and the solution that worked for me was:
In conan directory you should have `settings.yml.new` file with the new conan configuration, you need to merge or replace the `settings.yml` with `settings.yml.new` to solve the issue

**Comment by ivabrajer** [comment]
@JorgenPo Thanks, I confirm that updating `settings.yml` file helped and resolved the issue for me.
