### ISSUE TITLE
[conan.io/center] Handling of versions string not just with 3 numbers

### ISSUE THREAD

**Issue by igormironchik** [conan-io/conan-center-index#9114]
I'm the author of `cfgfile` library. I used versioning with more than 3 numbers, like `0.2.8.2.1`, `0.2.9.1`. I refused from it and switched to 3-numbered versions since `0.2.10`. The problem is that in `conan.io/center` by default `cfgfile` library shows with `0.2.9.1` version as more fresh, whereas `0.2.10` is already at conan. Consider, please, handling of versions with format that differs from 3-numbered. I want to say that `0.2.10` is more fresh than `0.2.9.1`. Thanks.

**Comment by db4** [comment]
It has nothing to do with CCI and it cannot be changed (at least for Conan 1.x). Conan follows [Semantic Versioning](https://semver.org/) scheme to compare versions, which assumes 3 numbers.

**Comment by igormironchik** [comment]
Nothing means nothing. Ok.

**Comment by db4** [comment]
Maybe I misread your question and you meant something like this? https://github.com/conan-io/conan-center-index/issues/9418

**Comment by igormironchik** [comment]
Yes, that issue is very similar to my. I commented there, let this issue be closed. Thanks.
