### ISSUE TITLE
[package] libxml2 : fix MinGW + cleanup

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#919]
I've been trying to build custom libxml2 build (MinGW, shared, with ICU, no iconv).
there are several things to be addressed:

- MinGW build doesn't handle ICU libraries at all, makefile has to be patched
- MinGW build uses hard-coded library names for zlib, libconv, etc. (same situation as for MSVC), makefile has to be patched

other minor things (to cleanup):

- currently recipe builds redundand things and deletes them as post-processing step (test executables, shared/static libs). it would be nice to use **make libxml2** (**make libxml2a** for static) instead of just **make**, and **make install-libs** instead of just **make install** to reduce build times and simplify the recipe.
- MinGW and MSVC share almost the same code (copy-paste), it needs to be unified
- AutoToolsBuildEnvironment wasn't used for MSVC and MinGW builds, thus build flags aren't always respected
- MinGW makefile hard-codes **gcc.exe** (might not pick up the right compiler from the profile)

I'll try to address mentioned problems in next days.

/cc @madebr

**Comment by SSE4** [comment]
plus, we're missing some options (some users needed to customize the build):
```
                    "python=no",
                    "valid=no",
                    "xinclude=no",
                    "xptr=no",
                    "c14n=no",
                    "catalog=no",
                    "regexps=no",
                    "schemas=no",
                    "schematron=no",
                    "legacy=no",
                    "ftp=no",
                    "http=no",
```
```
            '--without-valid',
            '--without-xinclude',
            '--without-xptr',
            '--without-c14n',
            '--without-catalog',
            '--without-regexps',
            '--without-schemas',
            '--without-schematron',
            '--without-legacy',
            '--without-ftp',
            '--without-http'
```

**Comment by Croydon** [comment]
//cc @annulen https://github.com/bincrafters/conan-icu/pull/31

**Comment by annulen** [comment]
I think it makes sense to use autotools for MinGW build, it should reduce complexity and I don't see any possible downside except maybe slightly longer configure step. I'm also using libxslt package, and it needs modification to support MinGW/configure.js build, however with autotools things work out of the box.

As for MSVC, IIRC there are wrappers allowing MS compilers to be used with autotools, though I'm not sure it's worth to replace Makefile
