### ISSUE TITLE
[zlib] Package does not build with custom source folder

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#92]
moved from https://github.com/conan-community/community/issues/208, by @planetmarshall 

### Package Details (Include if Applicable)
* Package Name/Version: **zlib/1.2.11**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Conan version: **conan 1.15.0**
* Python version: **python 3.5.2**

### Steps to reproduce (Include if Applicable)

```
conan source . -sf tmp/source
conan install . -if tmp/build
conan build . -bf tmp/build -sf tmp/source
```

### Build logs (Include if Available)

```
conanfile.py (zlib/1.2.11@None/None): Running build()
ERROR: conanfile.py (zlib/1.2.11@None/None): Error in build() method, line 49
        self._build_zlib()
while calling '_build_zlib', line 81
        with tools.chdir(self._source_subfolder):
        FileNotFoundError: [Errno 2] No such file or directory: 'source_subfolder'
```

**Comment by uilianries** [comment]
I'm not sure if it's a bug. As discussed [here](https://github.com/conan-io/conan/issues/5165), `create` and development flow are different things and they can result in different behaviors.

**Comment by franramirez688** [comment]
See the Conan layout: https://docs.conan.io/2/reference/conanfile/attributes.html#layout
