### ISSUE TITLE
[package] libffi/3.4.3: msvc isn't a valid target

### ISSUE THREAD

**Issue by WilliamBehrens** [conan-io/conan-center-index#9205]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libffi/3.4.3**
  * Operating System+version: **Windows 10 Visual Studio 2019**
  * Compiler+version: **MSVC 16**
  * Conan version: **conan 1.44.1**
  * Python version: **Python 3.9.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
include(default)

[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=16
compiler.runtime=MD

[options]

[conf]

[build_requires]

[env]
```

### Steps to reproduce (Include if Applicable)
conan create path/to/libffi libffi/3.4.3@ -pr:b=path/to/profile --build missing -s build_type=Release

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
checking host system type... x86_64-w64-cygwin
checking target system type... Invalid configuration `x86_64-windows-msvc': OS `msvc' not recognized
configure: error: /bin/sh /c/users/wbehrens/.conan/data/libffi/3.4.2/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/source_subfolder/config.sub x86_64-windows-msvc failed
libffi/3.4.2: 
libffi/3.4.2: ERROR: Package '3fb49604f9c2f729b85ba3115852006824e72cab' build failed
libffi/3.4.2: WARN: Build folder C:\Users\wbehrens\.conan\data\libffi\3.4.2\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab
ERROR: libffi/3.4.2: Error in build() method, line 147
        autotools = self._configure_autotools()
while calling '_configure_autotools', line 132
        self._autotools.configure(args=config_args, configure_dir=self._source_subfolder, build=build, host=host)
        ConanException: Error 1 while executing /c/users/wbehrens/.conan/data/libffi/3.4.2/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/source_subfolder/configure --enable-debug=no --enable-shared=no --enable-static=yes --prefix=C:/Users/wbehrens/.conan/data/libffi/3.4.2/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab --build=x86_64-w64-cygwin --host=x86_64-w64-cygwin --target=x86_64-windows-msvc
```

</details>

**Comment by WilliamBehrens** [comment]
I just wanted to note that adding `target=""` to the autotools config line did fix the error but I'm not sure if it created the right binary, I'll have to test it

**Comment by SpaceIm** [comment]
Are you that you are using this profile and not another one with `compiler=msvc`?

**Comment by SpaceIm** [comment]
Does https://github.com/conan-io/conan-center-index/pull/9206 help?

**Comment by WilliamBehrens** [comment]
It seems just telling it to target cygwin worked and created the .lib file, I'm not sure if the libffi modernize will fix it though
