### ISSUE TITLE
[package] yasm/1.3.0 : conan create is faulty

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#9209]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **yasm/1.3.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 2019**
  * Conan version: **conan 1.44.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
build_type=RelWithDebInfo
cppstd=17
[options]
[conf]
[build_requires]
[env]
CONAN_USE_ALWAYS_SHORT_PATHS=True
```

### Steps to reproduce (Include if Applicable)
cd ... conan-center-index\recipes\yasm\all
conan create . yasm/1.3.0@ --build missing

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
> conan create . yasm/1.3.0@ --build missing
ERROR: Package 00dfe7 has an invalid version number: '1'. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
```

</details>

**Comment by AndreyMlashkin** [comment]
I have tried to delete that folder from local cache and then it points to another folder...

PS C:\Users\Administrator\sources\conan-center-index\recipes\yasm\all> conan create . yasm/1.3.0@ --build missing
ERROR: Package 01aa6e has an invalid version number: '1'. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
PS C:\Users\Administrator\sources\conan-center-index\recipes\yasm\all> conan remove yasm -f
ERROR: Package 01aa6e has an invalid version number: '1'. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
PS C:\Users\Administrator\sources\conan-center-index\recipes\yasm\all> conan remove yasm -f
ERROR: Package 07302e has an invalid version number: '1'. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
PS C:\Users\Administrator\sources\conan-center-index\recipes\yasm\all> conan create . yasm/1.3.0@ --build missing
ERROR: Package 07302e has an invalid version number: '1'. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
PS C:\Users\Administrator\sources\conan-center-index\recipes\yasm\all> conan create . yasm/1.3.0@ --build missing
ERROR: Package 0a02b3 has an invalid version number: '1'. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash

**Comment by AndreyMlashkin** [comment]
And it points to some old folder, creation date is few days before.
Based on content, it points to a different lib

**Comment by AndreyMlashkin** [comment]
Now I see, that any conan recipe has the same problem... Seems to be a conan client issue...

**Comment by SSE4** [comment]
maybe it needs quotes in powsershell, Iike `conan create . "yasm/1.3.0@" --build missing`? IDK, maybe address character is special.

**Comment by AndreyMlashkin** [comment]
I had conan packages and short paths (I have USE_SHORT_PATHS=True on windows) in the same folder
