### ISSUE TITLE
[package] boost/1.78.0: Cannot disable statx API from package options

### ISSUE THREAD

**Issue by steromano87** [conan-io/conan-center-index#9220]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.78.0**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **GCC 9**
  * Docker image: **conanio/gcc9-ubuntu16.04**
  * Conan version: **conan 1.44.1**
  * Python version: **Python 3.6.15**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)
Build any application using as dependency **boost/1.78.0** leaving the default options (i.e. do not force-build the package, but download it from Conan Center).

Since older Ubuntu versions do not have the `statx` system call, it should be useful to add an option to the package to programmatically disable it during dependency compilation.
If package build is not forced, the downloaded package will have the statx calls enabled, hence resulting in errors during linking (see logs below).
The same errors are not found if the package is force-built (because `statx` is not detected and automatically disabled):
```
conan install . --build boost
```
The option should map the `BOOST_FILESYSTEM_DISABLE_STATX` compile definition (see [Boost source code](https://github.com/boostorg/filesystem/blob/f8024b245c97e65beae5b6b73e7a0f0a9558f23e/CMakeLists.txt#L18)).

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
/home/conan/.conan/data/boost/1.78.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/lib/libboost_filesystem.a(operations.o): In function `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)':
operations.cpp:(.text+0x6dc): undefined reference to `statx'
operations.cpp:(.text+0x89f): undefined reference to `statx'
/home/conan/.conan/data/boost/1.78.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/lib/libboost_filesystem.a(operations.o): In function `boost::filesystem::detail::copy_directory(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)':
operations.cpp:(.text+0xade): undefined reference to `statx'
/home/conan/.conan/data/boost/1.78.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/lib/libboost_filesystem.a(operations.o): In function `boost::filesystem::detail::equivalent(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)':
operations.cpp:(.text+0x1f92): undefined reference to `statx'
operations.cpp:(.text+0x1fc5): undefined reference to `statx'
/home/conan/.conan/data/boost/1.78.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/lib/libboost_filesystem.a(operations.o):operations.cpp:(.text+0x204c): more undefined references to `statx' follow
/home/conan/.conan/data/boost/1.78.0/_/_/package/ca891ed5c8e67ebb3e46639c100abdbca6d8b11e/lib/libboost_filesystem.a(unique_path.o): In function `boost::filesystem::detail::(anonymous namespace)::fill_random_getrandom(void*, unsigned long)':
unique_path.cpp:(.text+0x107): undefined reference to `getrandom'
collect2: error: ld returned 1 exit status
```

</details>

**Comment by SSE4** [comment]
@steromano87 can you try with `-o boost:extra_b2_flags=define= BOOST_FILESYSTEM_DISABLE_STATX`?

**Comment by steromano87** [comment]
Hi @SSE4 I just added the workaround you suggested and it worked like a charm, now `statx` is disabled regardless of the kernel capabilities.

You can close the issue.
