### ISSUE TITLE
[package] zlib/1.2.11: Bug - Patch not found

### ISSUE THREAD

**Issue by paulo-coutinho** [conan-io/conan-center-index#9236]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.11**
  * Operating System+version: **macos latest**
  * Compiler+version: **clang**
  * Docker image: n/a
  * Conan version: **conan 1.45**
  * Python version: **Python 3.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
onfiguration (profile_host):
[settings]
arch=armv7
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=iOS
os.version=9.0
os_build=Macos
[options]
nativium_arch=armv7
nativium_group=ios
nativium_product_name=Nativium
nativium_project_name=nativium
nativium_target=ios
nativium_version=1.0.0
nativium_version_code=1
darwin-toolchain:enable_arc=None
darwin-toolchain:enable_bitcode=True
darwin-toolchain:enable_visibility=None
[build_requires]
*: darwin-toolchain/1.0.0@nativium/stable
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
zlib/1.2.11: ERROR: Package '21d83103204988510118994b964ba1a76172a076' build failed
zlib/1.2.11: WARN: Build folder /Users/runner/.conan/data/zlib/1.2.11/_/_/build/21d83103204988510118994b964ba1a76172a076
ERROR: zlib/1.2.11: Error in build() method, line 77
	self._patch_sources()
while calling '_patch_sources', line 56
	tools.patch(**patch)
	FileNotFoundError: [Errno 2] No such file or directory: 'patches/0003-cmake-fix-msys2-subsystem.patch'
```

</details>

**Comment by paulo-coutinho** [comment]
Full build error:
https://github.com/nativium/nativium-game/runs/5041433324?check_suite_focus=true#step:14:2938

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/9056#issuecomment-1028216050

**Comment by vjpr** [comment]
Seems like its reading old patches...

https://github.com/conan-io/conan-center-index/blob/c318e234b1cb25b5ec15409c4cfd1b9309ac753c/recipes/zlib/all/conanfile.py#L60

https://github.com/conan-io/conan-center-index/blob/master/recipes/zlib/all/conandata.yml#L8

**Comment by SpaceIm** [comment]
What are your exact commands? It would be worth opening an issue on conan client side.

I can't reproduce this issue with:

```sh
# list all recipe revisions
conan search zlib/1.2.11@ -r conancenter -rev
# install second last revision: 683857dbd5377d65f26795d4023858f9 (2021-12-14 16:35:09 UTC)
conan install zlib/1.2.11@#683857dbd5377d65f26795d4023858f9 -b missing
# update to latest revision
conan install -u zlib/1.2.11@ -b missing
```

**Comment by paulo-coutinho** [comment]
Hi,

After re-run, it works on CI. I don't know what happen.

Github was offline yesterday, so it can be an uncommon problem.
