### ISSUE TITLE
[package] Botan/2.18.2: baremetal target not supported

### ISSUE THREAD

**Issue by Siviuze** [conan-io/conan-center-index#9268]
Hello,

Botan recipe doesn't support baremetal target (but Botan support a no os target).

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **Botan/2.18.2**
  * Operating System+version: **Baremetal**
  * Conan version: **conan 1.43.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=baremetal
arch=armv8
compiler=gcc
compiler.version=7.5
compiler.libcxx=libstdc++11
compiler.cppstd=17
build_type=Release
[options]
[conf]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Ninja
CONAN_CMAKE_TOOLCHAIN_FILE=/src/build/baremetal.cmake
CC=/opt/arm/v8hf/bin/arm_v8hf-gcc
CXX=/opt/arm/v8hf/bin/arm_v8hf-g++

### Steps to reproduce (Include if Applicable)
Try to build with baremetal os

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>
Cross-build from 'Linux:x86_64' to 'baremetal:armv8'
Installing (downloading, building) binaries...
botan/2.18.2: WARN: Build folder is dirty, removing it: /home/builder/wdc_workspace/.conan/data/botan/2.18.2/_/_/build/4b391300556dc1ca95deb4e89566fa2dbeff2dfb
botan/2.18.2: Copying sources to build folder
botan/2.18.2: Building your package in /home/builder/wdc_workspace/.conan/data/botan/2.18.2/_/_/build/4b391300556dc1ca95deb4e89566fa2dbeff2dfb
botan/2.18.2: Generator txt created conanbuildinfo.txt
botan/2.18.2: Aggregating env generators
botan/2.18.2: Calling build()
   INFO: ./configure.py invoked with options "--build-targets=static --distribution-info=Conan --without-documentation --cc-abi-flags=  --extra-cxxflags=-fPIC -std=c++17  --cc=gcc --cpu=armv8 --prefix=/home/builder/wdc_workspace/.conan/data/botan/2.18.2/_/_/package/4b391300556dc1ca95deb4e89566fa2dbeff2dfb --os=None --without-pkg-config"
   INFO: Configuring to build Botan 2.18.2 (revision unknown)
   INFO: Running under 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
   INFO: CXX environment variable is set which will override compiler path
   INFO: Implicit --cc-bin=/opt/arm/v8hf/bin/arm_v8hf-g++ due to environment variable CXX
   INFO: Autodetected platform information: OS="Linux" machine="x86_64" proc="x86_64"
   INFO: Using /etc/ssl/certs/ca-certificates.crt as system certificate store
   INFO: Canonicalized CPU target armv8 to arm64
  ERROR: Unknown OS "None"; available options: aix android cygwin dragonfly emscripten freebsd haiku hpux hurd includeos ios linux llvm macos mingw nacl netbsd none openbsd qnx solaris uwp windows
botan/2.18.2: 
botan/2.18.2: ERROR: Package '4b391300556dc1ca95deb4e89566fa2dbeff2dfb' build failed
botan/2.18.2: WARN: Build folder /home/builder/wdc_workspace/.conan/data/botan/2.18.2/_/_/build/4b391300556dc1ca95deb4e89566fa2dbeff2dfb
ERROR: botan/2.18.2: Error in build() method, line 171
        self.run(self._configure_cmd)
        ConanException: Error 1 while executing  ./configure.py --build-targets=static --distribution-info="Conan" --without-documentation --cc-abi-flags=" " --extra-cxxflags="-fPIC -std=c++17 --cc=gcc --cpu=armv8 --prefix=/home/builder/.conan/data/botan/2.18.2/_/_/package/4b391300556dc1ca95deb4e89566fa2dbeff2dfb --os=None --without-pkg-config

</details>

### Proposed fix:
Adding 'baremetal': 'none' in the os dictionnary of the recipe solve this issue.

**Comment by lieser** [comment]
Is this resolved with your PR, or is there still something open?

**Comment by Siviuze** [comment]
Resolved. I though the issue had closed automatically...
