### ISSUE TITLE
[feature] Update conan.io repository to use latest vulkan-headers branch

### ISSUE THREAD

**Issue by Makogan** [conan-io/conan-center-index#9286]
Currently the conan center allows vulkan headers up to 1.2.198 but vulkan 1.3 came out some time ago, the latest github branch is on 1.3.204: https://github.com/KhronosGroup/Vulkan-Headers/tree/sdk-1.3.204

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by SpaceIm** [comment]
There are new versions of vulkan-headers each week. In `conan-center` the tradeoff is to package sdk versions (more or less every 2 months). So the last SDK version is 1.3.204 released 2 days ago, it will be packaged soon or later.

**Comment by Makogan** [comment]
Is there a timeline of when the sooner or alter will be? I am a little blocked by not having access to the latest validation layers, some of the stuff I am doing is supported by my driver but the outdated layers think I am breaking vulkan.

**Comment by SpaceIm** [comment]
It depends on Khronos Group, when a SDK version is released. Even latest version of Vulkan SDK on LunarG website is 1.2.198.

**Comment by SpaceIm** [comment]
For vulkan-validationlayers, see https://github.com/conan-io/conan-center-index/pull/9618
