### ISSUE TITLE
[question] old version support

### ISSUE THREAD

**Issue by miliYoung** [conan-io/conan-center-index#9351]
Hello, I have some question of conan center.  if I want to use an older version of the open source library , what can I do for it?  For example, I 'am using the version of 3.7.10 on sqlite3 in my own project, and to some reason I don't want to change the current version, but the recipes only support the version above  3.29.0. if I use conan center to manager my project, Could I add the version that I want to use to the sqlite3's recipes and submit about the modification? How does the  conan center choose the useful version of the open library? Is there some standards of choosing the version of open source library?

**Comment by db4** [comment]
I think it's the reason to setup your own Conan repo and upload the necessary recipe there. For the majority of people, a recent version of sqlite3 is quite enough. Then why waste limited CCI resources packaging the old one?

**Comment by miliYoung** [comment]
> I think it's the reason to setup your own Conan repo and upload the necessary recipe there. For the majority of people, a recent version of sqlite3 is quite enough. Then why waste limited CCI resources packaging the old one?

Thanks for your answer, I think it is a good idea to setup my own Conan repo too, but I still want to know the principle of conan center on how to choose the version of open source. For example, conan center has the version of curl on 7.64.1 and 7. 66.0, why not have the version of 7.65.0?

**Comment by jgsogo** [comment]
Hi, @miliYoung . It is ok to add older versions if it is for a good reason, but in the long term (talking in semver terms) only the latest minor for each major version will be available in this repository and will be built by the CI. And in the future, depending on the number of versions, we might decide to remove old ones.

What happens with older versions? They will always be available in ConanCenter, even if we remove the entries in this reposittory, **those references and packages stay available in the remote** (of course they won't get new recipe revisions, but they are usable as they were at the time they were created).

I hope this answers your question. Thanks

**Comment by jgsogo** [comment]
Closing. If anything to add, please open it again. Thanks!
