### ISSUE TITLE
[package] OpenSSL/1.0.2o: fail to install with option "build missing"

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan-center-index#940]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **OpenSSL/1.0.2o**
  * Operating System+version: **Linux Manajaro 19.0.0**
  * Compiler+version: **ndk r16b arm-linux-androideabi-clang 5.0**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.8.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
standalone_toolchain=Android/android-19-armeabi-v7a
target_host=arm-linux-androideabi
cc_compiler=clang
cxx_compiler=clang++

[settings]
compiler=clang
compiler.version=5.0
compiler.libcxx=libc++
os=Android
os.api_level=19
arch=armv7
build_type=Release

[env]
CONAN_CMAKE_FIND_ROOT_PATH=${HOME}/$standalone_toolchain/sysroot
PATH=[/home/xyz1001/$standalone_toolchain/bin]
SYSROOT=/home/xyz1001/$standalone_toolchain/bin/sysroot
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
NM=$target_host-nm
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
STRIP=$target_host-strip
CFLAGS= -fPIE -fPIC -I${HOME}/$standalone_toolchain/include/c++/4.9.x
CXXFLAGS= -fPIE -fPIC -I${HOME}/$standalone_toolchain/include/c++/4.9.x
LDFLAGS= -pie
CPPFLAGS=-DANDROID -fPIC

[options]
```

### Steps to reproduce (Include if Applicable)

conan install OpenSSL/1.0.2o@conan/stable -p android-19-armeabi-v7a -r conan-center --build missing

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
arm-linux-androideabi-clang -O3 -I. -I.. -I../include -I/home/xyz1001/.conan/data/zlib/1.2.11/conan/stable/package/eb51f1b1ac216b9d083a3fbbc5271795c7b5dd77/include -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -D__ANDROID_API__=19 -fPIC -O3 -fomit-frame-pointer -Wall -DANDROID -fPIC  -c -o mem_clr.o mem_clr.c
arm-linux-androideabi-arm-linux-androideabi-ar  r ../libcrypto.a cryptlib.o mem.o mem_dbg.o cversion.o ex_data.o cpt_err.o ebcdic.o uid.o o_time.o o_str.o o_dir.o o_fips.o o_init.o fips_ers.o mem_clr.o
make[1]: arm-linux-androideabi-arm-linux-androideabi-ar: Command not found
make[1]: *** [../libcrypto.a] Error 127
make[1]: Leaving directory `/home/xyz1001/.conan/data/OpenSSL/1.0.2o/conan/stable/build/e4ef8046d6a5827b4f9274ceaf8b3cccb755cfdb/sources/crypto'
make: *** [build_crypto] Error 1
OpenSSL/1.0.2o@conan/stable:
OpenSSL/1.0.2o@conan/stable: ERROR: Package 'e4ef8046d6a5827b4f9274ceaf8b3cccb755cfdb' build failed
OpenSSL/1.0.2o@conan/stable: WARN: Build folder /home/xyz1001/.conan/data/OpenSSL/1.0.2o/conan/stable/build/e4ef8046d6a5827b4f9274ceaf8b3cccb755cfdb
ERROR: OpenSSL/1.0.2o@conan/stable: Error in build() method, line 552
        self._make()
while calling '_make', line 522
        self._run_make()
while calling '_run_make', line 482
        self.run(" ".join(command), win_bash=self._win_bash)
        ConanException: Error 2 while executing /home/xyz1001/Android/android-19-armeabi-v7a/bin/make -j8
```

</details>

Issue #28 is same as this, I tried the [fix](https://github.com/conan-io/conan-center-index/pull/129/files) , but it is not work.

**Comment by SSE4** [comment]
@xyz1001 seems like this commit accidentally reverted things: https://github.com/conan-io/conan-center-index/commit/99320f9cfb9fcd9723f7a8357fe2f85e6547deb2
I'll create PR to put the fix back

**Comment by SSE4** [comment]
@xyz1001 please test #957 and let us know

**Comment by xyz1001** [comment]
I tried #957 , but it is not work

**Comment by SSE4** [comment]
@xyz1001 the same error? or different one?

**Comment by xyz1001** [comment]
@SSE4 same error

**Comment by SSE4** [comment]
re-opened to continue the investigation, there must be one more bug

**Comment by SSE4** [comment]
I have reproduced the error on Manjaro docker image. **Makefile.org** contains correct AR, while the final **Makefile** has incorrect AR. so, the incorrect replace happens somewhere here:
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2o/Configure#L1726

**Comment by xyz1001** [comment]
Has there been any progress? @SSE4

**Comment by SSE4** [comment]
@xyz1001 right now I don't know how to fix it correctly without breaking other use-cases. suggestions and PRs are welcomed.

**Comment by SSE4** [comment]
@xyz1001 I am going to try adding one more replace for the actual makefile, that's the only safe solution I can imagine right now. in general, this makefile replacement system is very fragile, hopefully it's only 1.0.2x which is EOL.

**Comment by ah7675** [comment]
> @xyz1001 I am going to try adding one more replace for the actual makefile, that's the only safe solution I can imagine right now. in general, this makefile replacement system is very fragile, hopefully it's only 1.0.2x which is EOL.

I have submitted a simple solution, it should work as expected.

**Comment by xyz1001** [comment]
@ah7675 I tried your solution and it works. Thanks
