### ISSUE TITLE
[question] libuuid version

### ISSUE THREAD

**Issue by db4** [conan-io/conan-center-index#9410]
libuuid is now a part of [util-linux](https://github.com/util-linux/util-linux), can be built with meson (so Windows is supported), and hopefully has other improvements. I would like to update the CCI recipe to take it from there. But what version should it have? The current CCI version is 1.0.3, but util-linux does not declare a separate libuuid version, just a version of the whole package (the most recent one is util-linux 2.38). So the CCI recipe should be libuuid/2.38? Or what?

**Comment by Croydon** [comment]
If it is now part of util-linux then it probably shouldn't be packaged separately in CCI anymore as well

**Comment by db4** [comment]
> it probably shouldn't be packaged separately

Debian packagers don't think so: [libuuid1 (2.37.3-1 and others)](https://packages.debian.org/sid/libuuid1).
OK, despite existing Meson files libuuid still cannot be built for Windows. So using util-linux sources doesn't make much sense yet.
