### ISSUE TITLE
[question] Eigen package always has the same packageID regardless of the MPL2_only option value

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#9428]
This might be a question for the Conan repo instead of the index. Sorry if that's the case.

So I just started paying attention to the packages IDs and I noticed that regardless of the value of the `MPL2_only` option the generated package ID for the `eigen` package is always the same.

```
$  conan export recipes/eigen/all eigen/3.3.7@eric/testing 
Exporting package recipe
eigen/3.3.7@eric/testing exports: File 'conandata.yml' found. Exporting it...
eigen/3.3.7@eric/testing exports: Copied 1 '.yml' file: conandata.yml
eigen/3.3.7@eric/testing: Calling export_sources()
eigen/3.3.7@eric/testing: A new conanfile.py version was exported
eigen/3.3.7@eric/testing: Folder: /home/eric/.conan/data/eigen/3.3.7/eric/testing/export
eigen/3.3.7@eric/testing: Using the exported files summary hash as the recipe revision: c66dbf0dface54209d2d31cc7e386eeb 
eigen/3.3.7@eric/testing: Exported revision: c66dbf0dface54209d2d31cc7e386eeb

$ conan info eigen/3.3.7@eric/testing -o eigen:MPL2_only=True
eigen/3.3.7@eric/testing
    ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    BuildID: None
    Context: host
    Remote: None
    URL: https://github.com/conan-io/conan-center-index
    Homepage: http://eigen.tuxfamily.org
    Licenses: MPL-2.0, LGPL-3.0-or-later
    Description: Eigen is a C++ template library for linear algebra: matrices, vectors,                    numerical solvers, and related algorithms.
    Topics: eigen, algebra, linear-algebra, vector, numerical
    Provides: eigen
    Recipe: Cache
    Revision: c66dbf0dface54209d2d31cc7e386eeb
    Package revision: None
    Binary: Missing
    Binary remote: None
    Creation date: 2022-02-19 02:32:14 UTC

$ conan info eigen/3.3.7@eric/testing -o eigen:MPL2_only=False
eigen/3.3.7@eric/testing
    ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    BuildID: None
    Context: host
    Remote: None
    URL: https://github.com/conan-io/conan-center-index
    Homepage: http://eigen.tuxfamily.org
    Licenses: MPL-2.0, LGPL-3.0-or-later
    Description: Eigen is a C++ template library for linear algebra: matrices, vectors,                    numerical solvers, and related algorithms.
    Topics: eigen, algebra, linear-algebra, vector, numerical
    Provides: eigen
    Recipe: Cache
    Revision: c66dbf0dface54209d2d31cc7e386eeb
    Package revision: None
    Binary: Missing
    Binary remote: None
    Creation date: 2022-02-19 02:32:14 UTC
```

In both cases the ID is `5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9`. Reading the docs a bit this seems to be a consequence of 
```
    def package_id(self):
        self.info.header_only()
```
I'm wondering if we should remove this line for eigen. If the package ID is the same, is conan able to differentiate both packages?
Pulling the wrong package would be a big deal since basically you're including code under a different license.

**Comment by SpaceIm** [comment]
What should it change package id? This recipe option doesn't make sense anyway, if I could I would remove it.

**Comment by ericriff** [comment]
Why do you think it doesn't make sense? It uses the built in option to disable the non MPL2 parts of the library. If it is not through an option, how should this be done?

About the package id, maybe for this particular case it is OK to have the same package id. But if eigen's build system were to decide not to install the headers disabled by MPL2_only, would it be OK to have the same package id?

What's does the package ID supposed to encode?

**Comment by SpaceIm** [comment]
> Why do you think it doesn't make sense? It uses the built in option to disable the non MPL2 parts of the library. If it is not through an option, how should this be done?

Which built-in option? Do you see something in https://gitlab.com/libeigen/eigen/-/blob/master/CMakeLists.txt? It's a pure interface definition, users are expected to handle this definition themself, not through conan.

> About the package id, maybe for this particular case it is OK to have the same package id. But if eigen's build system were to decide not to install the headers disabled by MPL2_only, would it be OK to have the same package id?
> 
> What's does the package ID supposed to encode?

package id encodes package content. Since this definition doesn't change at all package content, there is no point to generate a different package id.

**Comment by ericriff** [comment]
> Which built-in option? Do you see something in [gitlab.com/libeigen/eigen/-/blob/master/CMakeLists.txt](https://gitlab.com/libeigen/eigen/-/blob/master/CMakeLists.txt)? Is it defined somewhere in upstream CMake config file? Outside of conan, how users would handle this definition? It's a pure interface definition, users are expected to handle this definition themself, not through conan.
I see what you mean now. It is not a CMake option, it is a documented feature. Maybe that's better wording. I'm not sure how the Eigen devs expect devs to use this. But if we were to remove this option from conan, how do we expect developers that can't use the non MPL2 parts of eigen to easily control this?

> package id encodes package content. Since this option doesn't change package content at all, there is no point to generate a different package id.

This is the piece of information that I had missing. In the hypothetical case of Eigen deciding to make this a proper option and then do not install some headers based on its value (the headers that have a different license), there we would need different package ids?

**Comment by ericriff** [comment]
> it should be possible, `self.info.header_only` just clears the lists of `settings`, `options` and `requires`, but values could be added after that call

Would that trigger a different package ID even though the actual content of the package is the same? That works for me.
But I don't know if that breaks the fundamental rationale behind the package id.

**Comment by SSE4** [comment]
> Would that trigger a different package ID even though the actual content of the package is the same? That works for me. But I don't know if that breaks the fundamental rationale behind the package id.

yes, but as it installs different headers depending on that option, it should result in a different package ID

**Comment by SpaceIm** [comment]
> yes, but as it installs different headers depending on that option, it should result in a different package ID

No, headers are the same.

**Comment by SSE4** [comment]
> > yes, but as it installs different headers depending on that option, it should result in a different package ID
> 
> No, headers are the same.

above some hypothetical case is discussed on how to handle package ID if `MPL2` options result in different headers installed (but both cases are header-only).

for the real/actual use-case of Eigen, it should just plain `self.info.header_only()`, that's it.

**Comment by jgsogo** [comment]
I think we can close this one. All different topics are clear, and given the option in the recipe, now the information from `conan info` is accurate (see https://github.com/conan-io/conan-center-index/pull/9571)
