### ISSUE TITLE
[question] How to add binaries to an existing package

### ISSUE THREAD

**Issue by HerrNamenlos123** [conan-io/conan-center-index#9438]
I am new to Conan, just discovered it today and it seems perfect for me!

I need some packages like for example libpng or zlib, and they are available for my compiler in MD, MDd and MTd configuration, but I need them in MT configuration.

Is there a way I can request that this configuration is compiled and added to the existing package version? Or can I compile it myself and upload it somewhere? It's not 100% clear to me yet how to publish packages. Just asking if this is even possible for an existing official package or will I always have to compile it myself every time I need it?

**Comment by SpaceIm** [comment]
conancenter remote (https://center.conan.io) provides pre-built packages for these configurations: https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md

MT should be available.

**Comment by HerrNamenlos123** [comment]
Hmmm, i am 100% sure i looked into a package i needed and it did not have 16 configurations for windows, it had less and MT was not there, but i checked and all packages i do need actually all have 16 configurations. I just can't remember which one it was, but all of those that i need actually have 16 configurations, so nevermind.

I still have to build all of them tho, because i'm using Visual Studio 2022 (that's version 17) and only version 15 and 16 are available, I guess requesting Visual Studio 2022 packages is not that easy...

**Comment by SpaceIm** [comment]
Yes, conan-center doesn't build binaries for Visual Studio 2022 yet. But I'm pretty sure they will be available in the near future.

**Comment by HerrNamenlos123** [comment]
Alright, I would like to see VS2022 binaries as soon as possible!
Closing this issue for now
