### ISSUE TITLE
[package] qt/5.15.2: Missing QtScript subModule

### ISSUE THREAD

**Issue by nFlachet** [conan-io/conan-center-index#9453]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSV 16**
  * Conan version: **conan 1.45.0**
  * Python version: **Python 3.10.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=15
os=Windows
arch_build=x86_64
os_build=Windows
[options]
[conf]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)
Try to create the package with this options:

conan install qt/5.15.2@ -s compiler="Visual Studio" -s build_type="Debug" -s compiler.version="16" -s compiler.runtime="MD" -o *:shared=True -o qtscript=True -b missing

The compilation works and the package is created.

But when I tried to consomme the package, with the conan generators ""cmake_find_package_multi" or "cmake_find_package", I have an error on the cmake file:

find_package(Qt5 REQUIRED NO_MODULE COMPONENTS Core Gui Widgets QtScript)

I think it's missing a 

`        if self.options.qtscript:
            _create_module("Script")`

In the package_info of the conanfile.py

**Comment by ericLemanissier** [comment]
Indeed, thanks for the report. Don't hesitate to make a pull request

**Comment by nFlachet** [comment]
I tried to add the _createModule in the recipe, but it didn't solved the problem, but I have no clue why it failed.

For now, I created a customize findQt5Script.cmake and it works.

**Comment by ericLemanissier** [comment]
Is it really `find_package(Qt5 REQUIRED NO_MODULE COMPONENTS Core Gui Widgets QtScript)` or did you mean `find_package(Qt5 REQUIRED NO_MODULE COMPONENTS Core Gui Widgets Script)` ?

**Comment by ericLemanissier** [comment]
Any change you try with https://github.com/conan-io/conan-center-index/pull/9543 and send us a fully detailed log if it still fails ?
