### ISSUE TITLE
[service] Why CI is so slow?

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#9474]
Why CI is so slow now? It takes long hours to finish a simple build...
Is it possible to add my machine to the runners pool? I have some spare ones.

**Comment by jgsogo** [comment]
Hi @AndreyMlashkin,

I agree with you that sometimes it takes too long to build a PR, but the number of servers we have available is limited and there are many PRs every day building many configurations, so sometimes one header-only needs to wait for some big boy (Qt/grpc/boost/ffmpeg...) until it finishes and releases some worker.

This snapshot is taken right now, time-window is 24 hours, the _red line_ is the number of busy executors:

![image](https://user-images.githubusercontent.com/1406456/155511135-b38a421d-6e16-41df-af67-02c5c2f619e3.png)

As you can see, there is always something ongoing. Besides that, there are some constraints in the CI process that should be satisfied, and force us to run some configurations in a queue: header-only libraries are built using Linux, but tested on all the other platforms, lower compiler version is always preferred (to maximize compatibility),... so sometimes we cannot start building another configuration until something has finished before.

We have some ideas to improve the pipeline and increase some parallelization, we have also started to configure the servers in a different way so we can use all of them in all the different environments we have (production and staging), which will increase the number of workers available. We have some other ideas in the backlog to _throw more items to the waiting queue_ so they start as soon as there is an idle worker... 

Of course, even if we manage to deliver all the ideas we have in mind, the CI will still be _very slow_ for anyone that is waiting. I need to say that this is a free service sponsored by JFrog, so far we are happy with the metrics and the traction, but if we want to ask for more resources, we need to show them that they are needed and used (basic metric is the increase on the number of recipes).

---

> Is it possible to add my machine to the runners pool? I have some spare ones.

Well, probably they won't let us connect a server that is not under our full control, but I will share your message just in case someone thinks that we can accept some kind of contribution in that direction.
