### ISSUE TITLE
[bug] Conan search returns timeout

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#950]
To help us debug your issue please explain:

Hi!

As Conan Center is growing, the time requested to list all recipes is no longer enough:

```
conan search -r conan-center
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0). [Remote: conan-center]
```

As you can see, 60 seconds is not enough to retrieve all information.

However, if I update the timeout request by `CONAN_TIMEOUT_REQUEST`, I can receive the answer:

```
CONAN_REQUEST_TIMEOUT=360 conan search -r conan-center
Existing package recipes:

7z_installer/1.0@conan/stable
Args/5.0.1.4@igormironchik/stable
...
```

Using`time` it took 1m39.

As Conan Center is the official repository, I think `search` should work without timeouts. So Or Bintray is slow, Or Conan needs to update its timeout limit.

Conan Version: 1.16.1

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Moved to conan-center-index, as this is mostly about the ConanCenter, not the client side.

**Comment by kaihowl** [comment]
Probably observing the problem again right now. Details: https://twitter.com/kaihowl/status/1267750305443262465

**Comment by hewigovens** [comment]
I just installed and tried searching boost, it takes 2min50s to get the results, is someone working on this?
```shell
$ time sudo conan search "boost" --remote=conan-center
Existing package recipes:

boost/1.64.0@conan/stable
boost/1.65.1@conan/stable
boost/1.66.0@conan/stable
boost/1.67.0@conan/stable
boost/1.68.0@conan/stable
boost/1.69.0
boost/1.69.0@conan/stable
boost/1.70.0
boost/1.70.0@conan/stable
boost/1.71.0
boost/1.71.0@conan/stable
boost/1.72.0
boost/1.73.0

real	2m50.146s
user	0m0.530s
sys	0m0.066s
```
BTW: we manage our c++ project internal dependencies (boost/json/gtest/protobuf) in a script, trying to find a usable package manager

**Comment by uilianries** [comment]
I can say https://conan.io/center is much much faster than the command line when looking for patterns.

**Comment by kaihowl** [comment]
@uilianries I observe this timeout during the resolution of version ranges as part of `conan create`. See https://gitlab.com/ptr-project/catch2_extended/-/jobs/589079001 for example.

```
 raise ConanConnectionError(("%s\n\nUnable to connect to %s=%s\n" +
 conans.errors.ConanConnectionError: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search?q=boost&ignorecase=False (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))
```

The only way to remedy this seems increasing the timeout, pinning the version, or using lockfiles. I don't have any good logical reason for pinning or lockfiles as far as I can see. Increasing the timeout seems ok. Yet, the performance is surprisingly slow for a simple query. Is this something that should be reported here or is there a better place (or even an existing ticket) for this?

**Comment by kuklinistvan** [comment]
I'm experiencing this too :(

**Comment by thejohnfreeman** [comment]
4 minutes seems like too long.

```
$ time conan search "boost/*" -r=conan-center
Existing package recipes:

boost/1.64.0@conan/stable
boost/1.65.1@conan/stable
boost/1.66.0@conan/stable
boost/1.67.0@conan/stable
boost/1.68.0@conan/stable
boost/1.69.0
boost/1.69.0@conan/stable
boost/1.70.0
boost/1.70.0@conan/stable
boost/1.71.0
boost/1.71.0@conan/stable
boost/1.72.0
boost/1.73.0

real    3m53.877s
user    0m0.483s
sys     0m0.060s
```

**Comment by DominikDeak** [comment]
Unfortunately, search performance is becoming a significant bottleneck and often fails in my case. Sample error message:

```
conan search "boost/*" --remote=all --raw

ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search?q=boost%2F%2A (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

**Comment by sonman** [comment]
I am using a conan center on premise. Search takes sometimes minutes because local ConanCenter waits for bintray to answer. The conan search has therefore a not so good user experience.

**Comment by AndWass** [comment]
Also hit this issue.

It also happens if I have a range in `conanfile.txt`:
```
[requires]
boost/[>=1.73]
```

```
$> conan install -if build .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search?q=boost%2F%2A&ignorecase=False (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

Output of `time conan search boost/* -r all`:
```
ERROR: HTTPSConnectionPool(host='api.bintray.com', port=443): Max retries exceeded with url: /conan/conan/conan-center/v1/conans/search?q=boost%2F%2A (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.bintray.com', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conan-center=https://api.bintray.com/conan/conan/conan-center
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

real    4m2.708s
user    0m0.015s
sys     0m0.000s
```

**Comment by tjwrona1992** [comment]
@AndWass this is also happening for me too. I noticed it when I tried to add a range in a conanfile "requires" statement.

I then tried doing a manual search and it failed. I stumbled upon this ticket and it looks like I am experiencing the same problem as others.

Searching for boost fails:
```
>conan search -r all boost
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search?q=boost (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

Searching in general fails:
```
>conan search -r conan-center
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

Searching for a specific package version does work (although it is quite slow... took about 10 seconds):
```
>conan search -r conan-center boost/1.75.0
Existing package recipes:

boost/1.75.0
```

I am using Conan version 1.29.2.

@memsharded, do you have any updates on the status of this issue? This is causing a big bottleneck in my development workflow.

**Comment by uilianries** [comment]
@tjwrona1992 Indeed the timeout persists. As alternative, you can use https://conan.io/center. The web search is pretty faster.

For the current timeout problem, we don't have a date for a fix, not soon at least. It requires maintenance on server side, not on Conan client.

**Comment by tjwrona1992** [comment]
@uilianries I appreciate the feedback. Unfortunately the problem I am having is that I want to be able to specify version ranges within my conanfiles for different packages I am consuming. Since these dependencies are downloaded during my CMake run with cmake-conan (https://github.com/conan-io/cmake-conan) i don't think there is any way to avoid this problem beacuse CMake will always be using the command line to fetch the dependencies.

For now I will have to just hard-code all of the version numbers to not be ranges, but I would prefer to be able to make my dependencies more flexible than that.

**Comment by nminkov** [comment]
The problem persists. Any solution insight?

**Comment by blockspacer** [comment]
Looks like `conan search` not using bloom filter for popular packages, see https://stackoverflow.com/questions/18447874/google-chrome-usage-of-bloom-filter

**Comment by aleksa2808** [comment]
+1

I was planning to experiment with a VS Code extension for finding/installing packages, but after observing conan-center queries being this slow (timing out on most popular packages for me) I had to hang up my hat for now. ☹️

**Comment by AJIOB** [comment]
I cannot mirror a specific boost version:

```
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
Downloading conan_sources.tgz
boost/1.72.0: Getting the complete package list from 'boost/1.72.0#0'...
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/boost/1.72.0/_/_/search (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))
Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

Do we have any solution?

**Comment by jgsogo** [comment]
This is not an issue anymore with latest changes to Artifactory
