### ISSUE TITLE
[question] method-ordering with new methods (validate, generate,..)

### ISSUE THREAD

**Issue by Hopobcn** [conan-io/conan-center-index#9518]
Hi, CCI docs (https://github.com/conan-io/conan-center-index/blob/master/docs/reviewing.md#order-of-methods-and-attributes) doesn't specify which is the recommended order with `validate()` method.

My guess is that the order is 

.. configure > requirements > package_id > build_id > build_requirements > system_requirements > **validate** > source > imports > **generate** > build ...

am I correct? Could this be added to the docs?

**Comment by SpaceIm** [comment]
From conan source code, I think `validate()` of a conanfile is called just after `package_id()` of the same conanfile.

**Comment by SSE4** [comment]
feel free to create PR for docs adding validate method to the list

**Comment by SSE4** [comment]
one more method missing in the list is `layout`. maybe there are others.
