### ISSUE TITLE
[service] error "Object of type range is not JSON serializable" for ranges in options

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#954]
from #906

using ranges in options like:
```
"debug_level": range(1, 14),
```
CCI throws:
```
ERROR: Object of type range is not JSON serializable
```
it works locally. right now I use a workaround:
```
"debug_level": [i for i in range(1, 14)],
```

**Comment by jgsogo** [comment]
This error was originated by the `conan inspect` command, like this one (https://github.com/conan-io/conan/pull/7151). If it is happening, it has to be discussed in the Conan repository, it is about allowing generators in this kind of expression or a list/tuple is required (it is what it is documented).
