### ISSUE TITLE
[package] dbus/1.12.20: with_x11=False should not build X11 

### ISSUE THREAD

**Issue by rnapier** [conan-io/conan-center-index#9563]
In the dbus recipe, when the `with_x11` option is False, the behavior is different on autoconf (unix-like) systems, and cmake (Windows) systems.

Under cmake, it sets DBUS_BUILD_X11 to false. This completely disables X11.

Under autoconf, it passes `--disable-x11-autolaunch`. This does not set DBUS_BUILD_X11 to false. It just disables autolaunch.

The `with_x11` option should disable X11 on all platforms. The correct autoconf parameter is `--without-x`.

Beyond compiling X11 when not needed, this breaks the dbus build on systems that have X11 installed only in /usr/local (this happens on Macs with homebrew). Autoconf discovers X11 in /usr/local, and enables it (setting DBUS_BUILD_X11 to 1), but the compiler is not passed an `-I` to search /usr/local. This is probably an upstream bug, but I expect does not impact very many people.

(PR shortly)

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **dbus/1.12.20**
  * Operating System+version: **macOS 12.2.1 **
  * Compiler+version: **Apple Clang 13.0.0**
  * Docker image: **None**
  * Conan version: **conan 1.45.0**
  * Python version: **Python 3.10.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=13.0
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]```


### Steps to reproduce (Include if Applicable)

* Install `libx11` homebrew package on Mac.
* `conan install --build=missing` with dbus/1.12.20

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
...
        Building X11 code:        yes
...
Making all in tools
  CC       dbus_launch-dbus-launch.o
  CC       dbus_launch-dbus-launch-x11.o
  CC       dbus_launch-tool-common.o
  CC       dbus-monitor.o
  CC       dbus-print-message.o
  CC       tool-common.o
  CC       dbus-send.o
  CC       dbus-echo.o
  CC       dbus-spam.o
  CC       test-tool.o
  CC       dbus-update-activation-environment.o
  CC       dbus-cleanup-sockets.o
../source_subfolder/tools/dbus-cleanup-sockets.c:377:1: warning: function 'usage' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
{
^
../source_subfolder/tools/dbus-launch-x11.c:37:10: fatal error: 'X11/Xlib.h' file not found
../source_subfolder/tools/dbus-cleanup-sockets.c:#include <X11/Xlib.h>384
:         ^~~~~~~~~~~~1
: warning: function 'version' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
{
^
../source_subfolder/tools/dbus-update-activation-environment.c:67:10: warning: 'environ' macro redefined [-Wmacro-redefined]
# define environ (*_NSGetEnviron ())
         ^
../config.h:501:10: note: previous definition is here
# define environ (*_NSGetEnviron())
         ^
1 error generated.
../source_subfolder/tools/dbus-launch.c:45:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
make[2]: *** [dbus_launch-dbus-launch-x11.o] Error 1
```

</details>

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

This problem does not exist nowadays  because autotools build system support was removed from this recipe in this PR https://github.com/conan-io/conan-center-index/pull/11616

Happy coding 🐸
