### ISSUE TITLE
[package] qt/5.12.7: build failure related to harfbuzz in Debug with VS 2017

### ISSUE THREAD

**Issue by sebhmg** [conan-io/conan-center-index#958]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.7**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 15**
  * Conan version: **conan 1.22.2**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
compiler.toolset=v141
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
The following command fails when using `conanfile.txt` with the configuration below:
`conan install -s build_type=Debug --build qt`

Content of `conanfile.txt`:
```
[requires]
boost/1.72.0
eigen/3.3.7
glew/2.1.0@bincrafters/stable
glib/2.58.3@bincrafters/stable # also a qt dependency
glm/0.9.9.7
gtest/1.10.0
hdf5/1.8.21 # or /1.10.6 # TODO! use patched source for non-ASCII filenames
nanoflann/1.3.0@simcenter/stable
nlohmann_json/3.7.3
openssl/1.1.1d # also a qt dependency
qt/5.12.7@bincrafters/stable
zlib/1.2.11 # also a qt dependency
# gdal
# teigha / ODA
# geosoft
# GeometricTools / WildMagic

[options]
qt:qtimageformats=True
qt:qtsvg=True
qt:qttranslations=True
qt:qtwinextras=True
qt:with_fontconfig=True
#qt:with_harfbuzz=False
qt:with_glib=True
qt:with_icu=False
qt:with_mysql=False
qt:with_openal=False
qt:with_pq=False
qt:with_sdl2=False
qt:with_sqlite3=False

hdf5:shared=True
openssl:shared=True
zlib:shared=True
glib:shared=True
glew:shared=True
```

It passes with `qt:with_harfbuzz=False`.

### Logs (Include/Attach if Applicable)
See attached [build_qt_debug.log](https://github.com/conan-io/conan-center-index/files/4246889/build_qt_debug.log)

**Comment by ericLemanissier** [comment]
I triggered a rebuild of harfbuzz earlier today, which should have solved this error. Could you retry with `--update` argument ?

**Comment by sebhmg** [comment]
@ericLemanissier, thank you!
My debug build is passing know. Awesome!

**Comment by Croydon** [comment]
@sebhmg Also since Qt is a Bincrafters package, please report problems of Bincrafters packages here: https://github.com/bincrafters/community/issues

Thanks 😄

**Comment by sebhmg** [comment]
@Croydon, sorry for my mistake. [README on bincrafters/community](https://github.com/bincrafters/community) is pointing to [conan-center-index](https://github.com/conan-io/conan-center-index/issues/new/choose), but only for requesting new packages. Noted!
