### ISSUE TITLE
[package] xorg/system: SM component doesn't advertise dependency on system uuid

### ISSUE THREAD

**Issue by rockdreamer** [conan-io/conan-center-index#9580]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **xorg/system**
  * Operating System+version: **Linux Centos 7**
  * Compiler+version: **GCC 10**
  * Docker image: **rockdreamer/centos7-gcc10**
  * Conan version: **conan 1.43.1**
  * Python version: **Python 3.8.11**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
os.distro=CentOS
compiler.cppstd=17
[options]
brotli:shared=True
bzip2:shared=True
expat:shared=True
fontconfig:shared=True
freetype:shared=True
glib:shared=True
glib:with_mount=False
glib:with_selinux=False
gtest:shared=True
harfbuzz:shared=True
icu:shared=True
jasper:shared=True
jbig:shared=True
libcurl:shared=True
libelf:shared=True
libffi:shared=True
libgettext:shared=True
libiconv:shared=False
libjpeg:shared=True
libmount:shared=True
libpng:shared=False
libselinux:shared=True
libtiff:shared=True
libuuid:shared=True
libwebp:shared=True
libxl:shared=True
libxml2:shared=True
nspr:shared=True
nss:shared=True
pcre:shared=True
pcre2:shared=True
vulkan-loader:shared=True
wayland:shared=True
xkbcommon:shared=True
xz_utils:shared=True
zlib:shared=True
zstd:shared=True
[conf]
[build_requires]
[env]
CC=/opt/rh/devtoolset-10/root/usr/bin/gcc
CXX=/opt/rh/devtoolset-10/root/usr/bin/g++
LD=/opt/rh/devtoolset-10/root/usr/bin/ld
MAKE=/opt/rh/devtoolset-10/root/usr/bin/make
```

### Steps to reproduce (Include if Applicable)

Run conan install . on this conanfile.txt
```
[requires]
xorg/system
```

`[exelinkflags]` doesn't include `-luuid`

</details>

**Comment by ericLemanissier** [comment]
what makes you think SM needs uuid ?
```
$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/sm.pc
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include

Name: SM
Description: X Session Management Library
Version: 1.2.3
Requires:
Requires.private: ice xproto
Cflags: -I${includedir}
Libs: -L${libdir} -lSM
```
Either sm needs uuid, and there's a bug in sm.pc to be reported at the distro's level, or sm does not need uuid, and the recipe is fine as-is.

**Comment by ericLemanissier** [comment]
> I tried looking for the libSM bug report page linked from the [configure.ac](https://gitlab.freedesktop.org/xorg/lib/libsm/-/commit/e6ccf19f8d1f71ef79f192b4ca9debf7280232a3#87db583be5c13c1f7b3c958b10e03d67b6a2ca06) file but I get a [not found](https://gitlab.freedesktop.org/xorg/lib/libsm/-/issues) error.

I think the issues are reported in https://gitlab.freedesktop.org/groups/xorg/-/issues

**Comment by rockdreamer** [comment]
Thank you for that and for submitting further improvements!

libSM doesn't have Issues enabled so I've [submitted one in libX11](https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/154), asking for a better place to do so if there is one
