### ISSUE TITLE
[question] how to request and share a package build for a specific set of options

### ISSUE THREAD

**Issue by sebhmg** [conan-io/conan-center-index#959]
I would like to build and publish a package for an existing recipe with specific options.
I can build it locally, but is there a better way, using a bot and have it published automatically for the community?

- how do I request such a build
- is there a way to trigger and publish a build through a Pull Request
- if I build it locally, how do I upload the build to the original repo of the recipe in order to make this build available to the community?

More specifically, I would like to build **qt/5.12.7@bincrafters/stable** with the set of options below:
<details><summary>click to view options</summary>

```
[options]
qt:qtimageformats=True
qt:qtsvg=True
qt:qttranslations=True
qt:qtwinextras=True
qt:with_fontconfig=True
qt:with_glib=True
qt:with_icu=False
qt:with_mysql=False
qt:with_openal=False
qt:with_pq=False
qt:with_sdl2=False
qt:with_sqlite3=False

hdf5:shared=True
openssl:shared=True
zlib:shared=True
glib:shared=True
glew:shared=True
```

</details>

**Comment by memsharded** [comment]
Hi @sebhmg 

It is not possible to create custom binaries in ConanCenter or to contribute them. The binaries that are created are some defaults good for a big fraction of users, and around 130 different binaries are already being created for most libraries. We decide which configurations are built and we code that in our pipelines to do so. We also add new compiler versions for the mainstream compilers when they are released. But the cost and complexity of maintaining more configurations that can be customly requested, is too high.

Quick note, that package is not being created by us (the ConanCenter automatic build service), but by the bincrafters community. Packages in ConanCenter doesn't have a user/channel like bincrafters/stable. They were contributed with a previous method, not working anymore.

What I would totally recommend is to host your own server for your own binaries. Artifactory CE is completely free, you can put it in your server and put there all your binaries, for both ConanCenter packages but also for your own private packages. This has several advantages:
- Private packages, share only with the people you want. For free.
- Robust pipelines, no matter what happens to ConanCenter, or the network, or internet, as long as you have access to your Artifactory, your builds will not break.
- Faster downloads if it is close to your CI servers, important if doing intensive CI.

**Comment by sebhmg** [comment]
Hi @memsharded ,
thank you for the detailed answer and the recommendation!
I will look into running Artifactory CE.
