### ISSUE TITLE
[OpenSSL] Broken on Windows with Clang and MinGW

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#96]
moved from https://github.com/conan-community/community/issues/236, by @LunarWatcher 

### Description of Problem, Request, or Question

Very related to #188, with the main difference that I'm using Clang (**not** clang-cl) with MinGW. The stacktrace is actually identical:

```
ERROR: OpenSSL/1.0.2o@conan/stable: Error in build() method, line 124
        raise Exception("Unsupported operating system: %s" % self.settings.os)
        Exception: Unsupported operating system: Windows
```

Same issue with 1.1.1c and 1.1.1b. 

```
ERROR: OpenSSL/1.1.1c@conan/stable: Error in build() method, line 101
        raise Exception("Unsupported operating system: %s" % self.settings.os)
        Exception: Unsupported operating system: Windows
```

Other packages compile fine (off the top of my head, fmt and I think zlib) with my setup as well, including packages from conan/stable (so this seems to be specific to this package, and maybe others I haven't tried). 

### Package Details (Include if Applicable)
* Package Name/Version: OpenSSL, at least 1.0.2o and 1.1.1c, though presumably all versions
* Operating System: **Windows**
* Operation System Version: **Windows 10, 1803**
* Compiler+version: **Clang 8.0.0**
* Conan version: **conan 1.16.1**
* Python version: **Python 3.7.3**

### Steps to reproduce (Include if Applicable)

1. Install MinGW, grab the packages necessary to build (MinGW packages (some are listed [here](https://stackoverflow.com/a/38434410/6296561), as well as `pacman -Sy base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-glew mingw-w64-x86_64-SDL2`. Not sure if I've left out any - I've installed a lot to get the environment working), Python 3, pip, and Conan)
2. Install Clang from the website, targeting Windows, add the install directory to MinGW's path
3. ```
   export CXX=clang++ -target x86_64-pc-windows-gnu
   export CC=clang -target x86_64-pc-windows-gnu
   ```
4. From the MinGW terminal: `conan install OpenSSL/1.1.1c@conan/stable --build missing`

**Comment by uilianries** [comment]
It's working using Ninja. Do we need mingw?

https://gist.github.com/uilianries/b114b80aff1c7f8eb5b2e2ae0bd7fd9e

**Comment by LunarWatcher** [comment]
@uilianries MinGW isn't just a CMake generator. It's a toolchain,  and can normally be used alongside ninja. I prefer ninja in general, but it's not comparable to MinGW. They're two different systems.

**Comment by uilianries** [comment]
I see, I thought you are using clang + make.exe (that's why mingw was required)

**Comment by madebr** [comment]
This fails on Windows 10,  gcc 8, mingw_installer/1.0@conan/stable
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++
compiler.threads=posix
compiler.version=8
os=Windows
os_build=Windows
[options]
[build_requires]
*: mingw_installer/1.0@conan/stable
[env]
```
The following error is shown:
```
openssl/1.1.1d: Configuring OpenSSL version 1.1.1d (0x1010104fL) for mingw-conan-Release-Windows-x86_64-gcc-8
openssl/1.1.1d: Using os-specific seed configuration
openssl/1.1.1d: Creating configdata.pm
openssl/1.1.1d: Creating Makefile
openssl/1.1.1d: Can't locate Pod/Usage.pm in @INC (you may need to install the Pod::Usage module) (@INC contains: . /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at configdata.pm line 13648.
openssl/1.1.1d: BEGIN failed--compilation aborted at configdata.pm line 13648.
openssl/1.1.1d: Compilation failed in require.
openssl/1.1.1d: BEGIN failed--compilation aborted.
openssl/1.1.1d:
openssl/1.1.1d: ERROR: Package '7c5dc145f1d2a7a4dae0800ece9117131c661244' build failed
```

**Comment by perseoGI** [comment]
I'm closing this issue as `openssl/1.1.1` recipe has suffer tons of modifications since this issue was opened.

If this issue remains, do not hesitate to reopen it! 😄
