### ISSUE TITLE
[service] Enable pylint hook

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-center-index#960]
Some warning and even prone errors can be detected by pylint

During the last weeks we found some problems which could be avoided if pylint was enabled.

For instance, duplicated method: https://github.com/conan-io/conan-center-index/pull/936#pullrequestreview-363706858

/cc @SSE4

**Comment by SSE4** [comment]
it might need some tuning. have you tried running it locally against existing repository? does it throw many annoying (irrelevant) warnings, false positives and so on?

**Comment by ericLemanissier** [comment]
this has been fixed with https://github.com/conan-io/conan-center-index/pull/7749
