### ISSUE TITLE
[service] builds may run/report in incorrect order, resulting in wrong PR status

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#963]
have seen several times:
https://github.com/conan-io/conan-center-index/pull/957
https://github.com/conan-io/conan-center-index/pull/906
https://github.com/conan-io/conan-center-index/pull/791
sometimes earlier build finishes after the newer one overriding PR status (label).

**Comment by danimtb** [comment]
This could be just me relaunching some jobs in the background. I think it was the case for #906

**Comment by danimtb** [comment]
Could be related to the auto-canceling feature. When there is a new commit, the new jobs try to cancel any other previous job that might be still running. Stopping a job is not immediate as it has to stop any other task that is run in the slaves, so that might cause misleading bot reports.

**Comment by SSE4** [comment]
yeah, but you didn't touch #957 I believe, right?

**Comment by danimtb** [comment]
This section has been heavily refactored and is now reporting the build of packages in a different format. I don't think it is an issue anymore, at least in its original form. Thank you!
