### ISSUE TITLE
[question] How to set link flag for openssl when cross building?

### ISSUE THREAD

**Issue by werto87** [conan-io/conan-center-index#9651]
I am using conan to cross build from x86_64 linux to arm linux. I like to set the linker flag "-fuse-ld=lld". The [openssl recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/openssl/3.x.x/conanfile.py) is using
```py
lflags=" ".join(env_build.link_flags)
```
to pass the link flags.

I am using this command to get the dependencies:
```
conan install .. --profile:build=clang --profile:host=armv7 --build missing
```
I whould like to set link_flags in armv7 profile. How to do this?

The profiles:
```
Configuration (profile_host):
[settings]
arch=armv7
compiler=clang
compiler.libcxx=libc++
compiler.version=13
os=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/clang
CFLAGS=--sysroot=/home/walde/armv7 --target=armv7l-unknown-linux-gnueabihf
CONAN_CMAKE_TOOLCHAIN_FILE=/home/walde/armv7/Toolchain_arm.cmake
CXX=/usr/bin/clang++
CXXFLAGS=--sysroot=/home/walde/armv7 --target=armv7l-unknown-linux-gnueabihf

Configuration (profile_build):
[settings]
arch=x86_64
compiler=clang
compiler.libcxx=libc++
compiler.version=13
os=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
```

**Comment by SpaceIm** [comment]
`LDFLAGS="-fuse-ld=lld"` in env section of host profile?

**Comment by werto87** [comment]
> `LDFLAGS="-fuse-ld=lld"` in env section of host profile?

Works. Thank you!
