### ISSUE TITLE
[package] <boost>/<1.69.0>: conflict at zlib

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan-center-index#966]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.69.0@conan/stable**
  * Operating System+version: **Linux Manjaro 19.0**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.22.0**
  * Python version: **Python 3.8.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

1. create a conanfile.txt which require `OpenSSL/1.0.2o@conan/stable` and `boost/1.69.0@conan/stable`
2. exec `conan install .`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: Conflict in boost/1.69.0@conan/stable
    Requirement zlib/1.2.11 conflicts with already defined zlib/1.2.11@conan/stable
    To change it, override it in your base requirements
```

</details>

I don't know why there are no user/channel in [boost conanfile.py line 123-130](https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py) , It should be like
```
            if self.options.zlib:
                self.requires("zlib/1.2.11@conan/stable")
            if self.options.bzip2:
                self.requires("bzip2/1.0.8@conan/stable")
            if self.options.lzma:
                self.requires("lzma/5.2.4@bincrafters/stable")
            if self.options.zstd:
                self.requires("zstd/1.3.5@bincrafters/stable")
```

**Comment by Croydon** [comment]
`@username/channel` is optional for a while now.

All packages in the Conan Center Index don't have a `@username/channel` anymore. Packages with a `@username/channel` do come from places like [conan-community](https://github.com/conan-community) and [Bincrafters](https://github.com/bincrafters).

Please update your `conanfile.txt` references to `openssl/1.0.2u` and `boost/1.69.0`

**Comment by xyz1001** [comment]
I think it makes sense， but may cause some Incompatibilities
