### ISSUE TITLE
[FIXED ✅ ] Wrong commit pushed to `master` on 2022/03/09 ~8:44h CET 

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-center-index#9668]
We pushed some commits to `master` branch on 2022/03/09 around ~8:44h CET. These commits have already been reverted and removed from `master`. 

If someone, or some CI, cloned/forked the repository during this time and tries to update/push/sync again after these commits were removed, it might get some errors related to git-history incongruence. For those affected, **we really recommend cloning/forking the branch again**.

Sorry for the inconvenience.

**Comment by ericLemanissier** [comment]
I guess they are these ones ?
![image](https://user-images.githubusercontent.com/1926390/157403044-3db59adb-8069-426a-9a8b-1fe9a0153fd1.png)

**Comment by jgsogo** [comment]
> I guess they are these ones?

Yes. Only the last one is the actual merge commit in `master`. The others belong to a branch/es (and there are more from the past days).

A fix would be `git reset --hard c84eda21ed69a12fa578de459b4a18e33088da91` if there are no more commits after those ones.

**Comment by ericLemanissier** [comment]
ok, thanks, for the notice. https://github.com/bincrafters/conan-center-index/tree/master is sane again

**Comment by derived-coder** [comment]
@jgsogo 
Can you not protect master branch from this happening again? Only MR can push changes to master.

Additionally, no custom branches in upstream, only MR via forks.

**Comment by jgsogo** [comment]
Hi, @derived-coder 

In general, all PRs required CLA + CI green + 3 positive reviews, but still the bot (@conan-center-bot ) needs to be able to merge PRs that don't satisfy those requirements: it counts reviews from users without write permissions (they are not taken into account), it is able to merge some PRs only with CLA + CI green (`Bump version` and `Bump dependencies`). For this reason, @conan-center-bot is Admin (only for this repo) and we cannot block admins from it.

Some users inherit the admin role from `conan-io` organization, so they will be able to merge/write in the repo without PRs. 

In terms of Github configuration, we can 
<img width="447" alt="image" src="https://user-images.githubusercontent.com/1406456/158643897-e4d91096-7241-4664-9f9f-9064776840cd.png">

but we cannot 

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1406456/158643938-a57244b2-1629-44e2-94b8-b9b05e64acc1.png">

----

About other branches in upstream. The bot uses them to create PRs related to documentation and, in the future, it might start to create other PRs bumping dependencies. Those branches are not meant to be used and should never be created by humans.

**Comment by derived-coder** [comment]
1.
I do not get it. Is your `master` branch now protected or not? Nobody, also bots should not be able to directly push to master. I do not see any reason. Only MR should be allowed.

2.
The other branches like: `bot/infra-2022-02-26 ` are mirrored too. I see that you are creating almost every day such a branch. For an auto mirror of a fork, this creates quite some noise. Is it possible to exclude such stuff in a mirror? We are using gitlab. The best would be of course to not create it in upstream, but you might have your reasons.

**Comment by jgsogo** [comment]
`master` branch is protected, but the protection doesn't include administrators. AFAIK, there isn't a configuration in GitHub to block pushing to master for everyone,  all you can do is _"Require a pull-request before merging"_, but if that restriction doesn't _"Include administrators"_, they will be able to push to `master`.

We cannot "include administrators" for the reason I told you about before, and some users have the [Admin role from the `conan-io` organization](https://github.com/conan-io) and within a repository, you cannot revoke that admin role.

---

About forks, you probably shouldn't configure it as a mirror, instead use something like sync and fetch only the branches you are interested in (`master`). GitHub has it as a built-in capability for forks, not sure about GitLab.
