### ISSUE TITLE
[package] c-ares/1.17.1: fails to build on mingw

### ISSUE THREAD

**Issue by dvirtz** [conan-io/conan-center-index#9674]
Error is

```
In file included from /root/.conan/data/c-ares/1.17.1/_/_/build/3027a2bf0a64b8cf013441df42862a577f509d52/source_subfolder/src/lib/ares_setup.h:214,
                 from /root/.conan/data/c-ares/1.17.1/_/_/build/3027a2bf0a64b8cf013441df42862a577f509d52/source_subfolder/src/lib/ares_cancel.c:15:
/root/.conan/data/c-ares/1.17.1/_/_/build/3027a2bf0a64b8cf013441df42862a577f509d52/source_subfolder/src/lib/setup_once.h:113:8: error: redefinition of 'struct timeval'
  113 | struct timeval {
      |        ^~~~~~~
In file included from /opt/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/winsock2.h:52,
                 from /root/.conan/data/c-ares/1.17.1/_/_/build/3027a2bf0a64b8cf013441df42862a577f509d52/build_subfolder/source_subfolder/ares_build.h:26,
                 from /root/.conan/data/c-ares/1.17.1/_/_/build/3027a2bf0a64b8cf013441df42862a577f509d52/source_subfolder/src/lib/ares_setup.h:83,
                 from /root/.conan/data/c-ares/1.17.1/_/_/build/3027a2bf0a64b8cf013441df42862a577f509d52/source_subfolder/src/lib/ares_cancel.c:15:
/opt/mingw-w64-build/x86_64-w64-mingw32/x86_64-w64-mingw32/include/_timeval.h:10:8: note: originally defined here
   10 | struct timeval
      |        ^~~~~~~
```

The cause is that detection of `HAVE_STRUCT_TIMEVAL` fails due to

```
/root/.conan/data/mingw-w64/8.0.2/_/_/package/6c0af486d761293b534496741c71f331201fadf0/lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lAdvapi32
```

This was fixed upstream in https://github.com/c-ares/c-ares/commit/28b2fa40bd6c4d54bcb182f6caa0af0e5759a138

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **c-ares/1.17.1**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **MinGW 10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
arch=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
compiler.threads=win32
compiler.exception=seh
build_type=RelWithDebInfo
[options]
mingw-w64:threads=win32
[conf]
[build_requires]
*: mingw-w64/8.0.2
[env]
```

### Steps to reproduce (Include if Applicable)
build c-ares/1.17.1 with the above profile

**Comment by ericLemanissier** [comment]
this is an upstream bug which is solved in `c-ares/1.18.1` already available on conan-center.

**Comment by uilianries** [comment]
Thank you for the solution @ericLemanissier !

**Comment by uilianries** [comment]
@dvirtz please, check if updating your package version solves your problem, then we can close this issue.

**Comment by SpaceIm** [comment]
We may backport this fix to previous versions, since it's a build issue.

**Comment by dvirtz** [comment]
> @dvirtz please, check if updating your package version solves your problem, then we can close this issue.

yes, upgrading to `c-ares/1.18.1` solves my problem

**Comment by ericLemanissier** [comment]
This issue can probably be closed then, right ?
