### ISSUE TITLE
[package] Tesseract/5.0.0: GCC Requirement too restrictive

### ISSUE THREAD

**Issue by brandonmkunkel** [conan-io/conan-center-index#9678]
I am working to compile the tesseract library into binaries for deployment on various Linux distros (with Ubuntu 18.04+ as my primary target right now).

The tesseract package (versions >=5.0.0) uses too restrictive of a GCC version (9+) to support C++17, when GCC 7 supports the C++17 standard (see references below). I have tried many different combinations of docker images/compilers and cannot produce a binary that "just works" on Ubuntu 18.04 due to GLIBC/CXX issues.

For reference: 
 * [GCC C++17 standard support](https://gcc.gnu.org/projects/cxx-status.html)
 * [Clang C++ Standard support](https://clang.llvm.org/cxx_status.html) - seems full support is around clang ~7
 * [Visual Studio C++ Standard Support](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170)

I've tried a combination of different solutions to target Ubuntu 18.04 (with glibc 2.27):
* Conanio/gcc9 - glibc (2.30)
* Conanio/gcc8 - glibc (2.27) - fails to meet tesseract conanfile min gcc >=9 criteria, likely would work to meet needs
* Conanio/gcc7 - glibc (2.26) - fails to meet tesseract conanfile  min gcc >= 9 criteria, likely would work to meed needs
* Conanio/clang7 - glibc (2.28), glibc too new and won't be compatible with target glibc
* Using various centos images with upgrading the gcc to version 9.0 (GLIBC compatibility issues gone, but GLIBCXX compatibility issues)

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **tesseract/5.0.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 9**
  * Docker image: **conanio/gcc9**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

Not using a custom profile

### Steps to reproduce (Include if Applicable)

1. Use docker to build lightweight project that uses tesseract in `conanio/gcc9`, builds against GLIBC 2.30
2. `docker cp` the binaries to an `ubuntu:18.04` image, uses GLIBC 
3. Run `ldd /path/to/binary` to confirm GLIBC/GLIBCXX compatiblity issues

### Logs (Include/Attach if Applicable)
<details><summary>ldd result on Ubuntu 18.04 for binary built with conanio/gcc9</summary>

```
# ldd libocr.so
./libocr.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./libocr.so)
./libocr.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./libocr.so)
	linux-vdso.so.1 (0x00007fffb9d83000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8c536f6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8c5336d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8c5314e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8c52db0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8c529bf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8c54de5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8c527a7000)
```

</details>

**Comment by brandonmkunkel** [comment]
Thanks for the quick response @uilianries . So the Conan Center binaries are actually built in CI on Ubuntu 16.04 images? I'm going to try building my application from an Ubuntu 16.04 image. 

The rest of my response below pertains to the issues I've run into building from scratch: 

It is hard to compile a package from scratch using the tesseract package and be compatible with older glibc runtimes because the recipe explicitly states gcc 9 as the compiler, which eliminates a whole suite of `conanio` docker images or requires some hacky behaviors with configuring new docker images on older runtimes with newer compilers. 

At first glance it should be easy to convert the recipe to downgrade gcc9 -> gcc7. Are there any difficulties with modifying the Tesseract recipe?
https://github.com/conan-io/conan-center-index/blob/fe837d4775b00e8c1bf4372d0508db941aa0ba5b/recipes/tesseract/all/conanfile.py#L85

**Comment by uilianries** [comment]
> Thanks for the quick response @uilianries . So the Conan Center binaries are actually built in CI on Ubuntu 16.04 images? I'm going to try building my application from an Ubuntu 16.04 image.

Yes. All docker images consumed by Conan Center Index are available on Hub Docker: https://hub.docker.com/u/conanio
Also, you can obtain their recipes on https://github.com/conan-io/conan-docker-tools

The images with the suffix `-ubuntu16.04` are the newer. We still use old glibc due compatibility, but we build compilers from sources.

> At first glance it should be easy to convert the recipe to downgrade gcc9 -> gcc7. Are there any difficulties with modifying the Tesseract recipe?

Usually we block compiler versions due c++ standard support. If Tesseract works with gcc7, it can be downgraded yes, but it need to use `conanio/gcc7` docker image due compatibility with other packages, we can't the repository due a single package. You can open a PR or check locally if it works with that docker image and updating the recipe to gcc7.

**Comment by brandonmkunkel** [comment]
Checking in with my progress. I was able to compile with the `conanio/gcc9-ubuntu16.04` docker image, the "glibc" compatibility issue is gone, leaving now a "glibcxx" compatibility which is likely linked to the compiler version. 

<details><summary>ldd command from target docker container (image: ubuntu:18.04)</summary>
# ldd --verbose libocr.so

./libocr.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./libocr.so)
        linux-vdso.so.1 (0x00007fffae5fc000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa7f5896000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa7f568e000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa7f5305000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa7f50e6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa7f4d48000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa7f4957000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa7f6a04000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa7f473f000)

        Version information:
        ./libocr.so:
                librt.so.1 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/librt.so.1
                libdl.so.2 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libdl.so.2
                libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
                libm.so.6 (GLIBC_2.15) => /lib/x86_64-linux-gnu/libm.so.6
                libstdc++.so.6 (GLIBCXX_3.4.20) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (CXXABI_1.3.8) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.17) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.19) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.18) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.26) => not found
                libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.9) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (CXXABI_1.3) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.14) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (CXXABI_1.3.3) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (CXXABI_1.3.5) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.15) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.22) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libpthread.so.0 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libpthread.so.0
                libpthread.so.0 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libpthread.so.0
                libc.so.6 (GLIBC_2.22) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.7) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.11) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.6) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libdl.so.2:
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/librt.so.1:
                libpthread.so.0 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libpthread.so.0
                libpthread.so.0 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libpthread.so.0
                libpthread.so.0 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libpthread.so.0
                libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
        /usr/lib/x86_64-linux-gnu/libstdc++.so.6:
                libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                libgcc_s.so.1 (GCC_4.2.0) => /lib/x86_64-linux-gnu/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.3) => /lib/x86_64-linux-gnu/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.0) => /lib/x86_64-linux-gnu/libgcc_s.so.1
                libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.18) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.16) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.17) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libpthread.so.0:
                ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libm.so.6:
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
        /lib/x86_64-linux-gnu/libgcc_s.so.1:
                libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6

</details>

**Comment by brandonmkunkel** [comment]
Found Github Issue from the tesseract source repository talking about compiler constraints. Seems the maintainers accept gcc 7 as the minimal version for their build processes.  Now I just need to confirm on my PR (work in progress) that this gcc version is compatible with the conan package's dependencies with local testing. 

https://github.com/tesseract-ocr/tesseract/issues/3210#issuecomment-774599019

**Comment by brandonmkunkel** [comment]
Submitted PR for the downgrade https://github.com/conan-io/conan-center-index/pull/9682
