### ISSUE TITLE
[question] Why is after two days `continuous-integration/jenkins/pr-merge` errored?

### ISSUE THREAD

**Issue by igormironchik** [conan-io/conan-center-index#9697]
PR #9661 has been built successfully on PR creation stage, all checks were green. But after two days I see that `continuous-integration/jenkins/pr-merge`is  errored and highlighted with red. What's wrong? Thanks.

**Comment by jgsogo** [comment]
That could have been a missing notification. Now the failure is related to https://github.com/conan-io/conan-center-index/issues/9698. We will be visiting all the PRs in the following hours (today and tomorrow).

If that happens again, it is preferable that you mention us in the PR, that way we get the notification.

**Comment by igormironchik** [comment]
My PR is merged. Thanks. So I close this issue.
