### ISSUE TITLE
[🤖  INFRA] CI relaunched, many jobs expected to fail (everything is working)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-center-index#9698]
Hi,

Today we have redeployed the jobs in Jenkins and, as a consequence, all of them have been triggered again. Our servers are not prepared for such a volume of jobs (all PRs at once!) and many of them will fail unexpectedly, some others will be canceled by us trying to keep the load under some threshold that will guarantee that running jobs can succeed.

In the following hours (today, tomorrow) we will be retrying all these PRs and trying to leave them in the expected status: green, failed, or pending on some infrastructure changes, but no one should be _running forever_ or with UnexpectedError label after those retriggers.

You can **keep using the repository as always**, but there is no need for you to trigger again past PRs, we will take care of them. I would ask you to have some patience.

Thanks

PS.- Should we start a bulletin? 🗞️

**Comment by uilianries** [comment]
Please, pin this issue, so anyone will see on issues page.

**Comment by danimtb** [comment]
Reopening this issue as it happened again after the new deployment (https://github.com/conan-io/conan-center-index/pull/10417)

**Comment by uilianries** [comment]
Closing this issue due the new redesigned ConanCenterIndex CI service.

Please, read https://github.com/conan-io/conan-center-index/discussions/25772 for further information.
