### ISSUE TITLE
[package] onetbb/2021.3.0: recipe broken in Conan 1.46.0

### ISSUE THREAD

**Issue by soerenkoenig** [conan-io/conan-center-index#9701]
since Conan version 1.46.0 onetbb/2021.3.0 does not build anymore

 line 90 in conanfile.py is producing an error:

ERROR: onetbb/2021.3.0: Error in build() method, line 90
[cmake] 	cmake.configure("src")
[cmake] 	AttributeError: 'str' object has no attribute 'items'

Changing line 90 from:

cmake.configure("src") 

to

 cmake.configure(build_script_folder="src")

seems to fix the bug

### Steps to reproduce (Include if Applicable)

build onetbb/2021.3.0 with Conan version 1.46.0

**Comment by uilianries** [comment]
Hi @soerenkoenig  Which OS and Version?

**Comment by soerenkoenig** [comment]
The problem is not OS specific but related to the conan version. In conan Version 1.43 it is possible to build the package onetbb/2021.3.0 but in conan version 1.46 it fails. Seems to be related to a change in the behavior  of cmake.configure method used in the recipe at line 90.
I ran into the problem by running 
conan install  —build  on a conanfile.txt containing the package:

onetbb/2021.3.0

after updating to conan version 1.46.

Same error on macOS and Ubuntu.

**Comment by SpaceIm** [comment]
```
conan install onetbb/2021.3.0@ -o "*":shared=True -b onetbb
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
[options]
*:shared=True
[build_requires]
[env]
[conf]
tools.cmake.cmaketoolchain:generator=Ninja

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
[options]
[build_requires]
[env]
[conf]
tools.cmake.cmaketoolchain:generator=Ninja

onetbb/2021.3.0: Forced build from source
Installing package: onetbb/2021.3.0
Requirements
    onetbb/2021.3.0 from 'conancenter' - Cache
Packages
    onetbb/2021.3.0:0b44072b9b70a752a87262baad24399cbdb238c3 - Build

Installing (downloading, building) binaries...
[HOOK - conan-center.py] pre_source(): [IMMUTABLE SOURCES (KB-H010)] OK
onetbb/2021.3.0: Configuring sources in /Users/spaceim/.conan/data/onetbb/2021.3.0/_/_/source
Downloading v2021.3.0.tar.gz completed [1612.63k]

[HOOK - conan-center.py] post_source(): [LIBCXX MANAGEMENT (KB-H011)] OK
[HOOK - conan-center.py] post_source(): [CPPSTD MANAGEMENT (KB-H022)] OK
onetbb/2021.3.0: Copying sources to build folder
onetbb/2021.3.0: Building your package in /Users/spaceim/.conan/data/onetbb/2021.3.0/_/_/build/0b44072b9b70a752a87262baad24399cbdb238c3
onetbb/2021.3.0: Generator txt created conanbuildinfo.txt
onetbb/2021.3.0: Calling generate()
onetbb/2021.3.0: Aggregating env generators
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
onetbb/2021.3.0: Calling build()
onetbb/2021.3.0:
onetbb/2021.3.0: ERROR: Package '0b44072b9b70a752a87262baad24399cbdb238c3' build failed
onetbb/2021.3.0: WARN: Build folder /Users/spaceim/.conan/data/onetbb/2021.3.0/_/_/build/0b44072b9b70a752a87262baad24399cbdb238c3
ERROR: onetbb/2021.3.0: Error in build() method, line 90
	cmake.configure("src")
	AttributeError: 'str' object has no attribute 'items'
```

This is why I'm a little bit reluctant with PR using new helpers, it's still not very stable.

**Comment by uilianries** [comment]
@SpaceIm Thank you for posting the output!

**Comment by p-groarke** [comment]
Same here :
https://github.com/p-groarke/fea_libs/runs/5523797163?check_suite_focus=true
https://github.com/p-groarke/fea_libs/runs/5523906195?check_suite_focus=true

Commenting to get notified of updates.
