### ISSUE TITLE
[request] <shaderc>/<v2022.1>

### ISSUE THREAD

**Issue by AlessandroScrem** [conan-io/conan-center-index#9704]
### Package Details
  * Package Name/Version: **shaderc/2022.1**
  * Website: **https://github.com/google/shaderc.git**
  * Source code: **https://github.com/Kitware/CMake**

### A collection of tools, libraries and tests for shader compilation

request compilation for Windows

build instructions:
git clone https://github.com/google/shaderc.git
cd shaderc
python3 utils/git-sync-deps

mkdir build
cd build
cmake ..
cmake --build . --config RelWithDebInfo

**Comment by SpaceIm** [comment]
shaderc is already in conan-center. You're asking for the latest version I guess, not a new recipe.

**Comment by AlessandroScrem** [comment]
Thank you for the support.
I got it.
Sincerely Alessandro
I

Il ven 11 mar 2022, 00:26 SpaceIm ***@***.***> ha scritto:

**Comment by AbrilRBS** [comment]
Closing as newer versions have been added thru the years, sorry that we didn't circle back to this PR sooner!
