### ISSUE TITLE
[request] glad/0.1.36

### ISSUE THREAD

**Issue by asoluter** [conan-io/conan-center-index#9706]
### Package Details
  * Package Name/Version: **glad/0.1.36**
  * Changelog: https://github.com/Dav1dde/glad/compare/v0.1.35...v0.1.36

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by czoido** [comment]
Thanks for reporting, closing as it's already in Conan Center.
