### ISSUE TITLE
[package] ffmpeg/4.4, opencv/4.5.3: incompatible dependencies

### ISSUE THREAD

**Issue by MiSo1289** [conan-io/conan-center-index#9810]
### Package and Environment Details:
- Package: opencv/4.5.3
- Conan version: 1.46.0
- OS: Ubuntu 20.04
- Python version: 3.8.5
- Compiler: GCC 9

### Conan profile:
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
*:fPIC=True
*:shared=False
boost:header_only=True
date:use_system_tz_db=True
opencv:contrib=True
opencv:nonfree=True
opencv:parallel=openmp
[build_requires]
[env]
```

### Steps to reproduce:
```sh
conan install opencv/4.5.3@ -u -b missing
```

### Logs:
```
ERROR: Conflict in libsndfile/1.0.31:
    'libsndfile/1.0.31' requires 'ogg/1.3.4' while 'vorbis/1.3.7' requires 'ogg/1.3.5'.
    To fix this conflict you need to override the package 'ogg' in your root package.
```

### Other info:
Adding `--require-override ogg/1.3.4` fixes the issue; however we have a number of projects that depend on opencv and adding `ogg/1.3.4` to requirements of each one doesn't seem like a good solution.

**Comment by MiSo1289** [comment]
More specifically, this seems to be an issue with the `ffmpeg/4.4` package that is required by opencv if `with_ffmpeg` is set to `True`; trying to install just ffmpeg yields the same error.

**Comment by SSE4** [comment]
#9484 should fix that
