### ISSUE TITLE
[question] Transitive private dependency fails to link with static linking, what am I doing wrong?

### ISSUE THREAD

**Issue by accwebs** [conan-io/conan-center-index#9814]
I *have* to think the answer is already documented somewhere, but I'm trying to round out work on a new package recipe for nomination (via PR) to conan-center-index and I'm really confusing myself.

---

Situation:
* `funchook` - library I'm building the recipe for
* `capstone` - optional dependency of funchook - conditional based on funchook recipe options - but consider it to be required for this discussion

Right now I have set capstone to be a *private* dependency of funchook (since capstone is not at all deliberately exposed by funchook or part of funchook's API).

I have built a simple test_package in my draft recipe and am trying to build/test it using `conan create`, etc.

---

The problem:  

When I build funchook with shared=True, things work fine.  But shared=False fails.

Case 1:  shared=True
```
# test_package binary build works
conan create -o funchook:disassembler=capstone -o funchook:shared=True . funchook/1.1.0@
```

Case 2:  shared=False
```
# test_package binary fails to link due to missing capstone symbols
conan create -o funchook:disassembler=capstone -o funchook:shared=False . funchook/1.1.0@
```

Debugging:  Through various debugging flags, determined that test_package's output binary is being linked with `-lfunchook` and NOT `-lcapstone`.

---

Analysis:

Of course when funchook is a shared lib (.so file on linux) it DOES include the capstone code directly embedded in it (since Capstone is statically linked into the funchook.so).  So then linking test_package with:
`-lfunchook` 
is sufficient.  Thus the "case 1" build works.

On the other hand, from what I read online, output static library files (.a files on linux) don't include transitive dependencies in them.  So the "leaf" module test_package would need to be linked with:
`-lfunchook -lcapstone` 
for "case 2".  Because -lcapstone is omitted, the link fails.

---

**Overall, this seems like a fairly "basic" issue that - if truly is a Conan limitation - would affect every Conan recipe with private transitive dependencies.  As a result (and because I'm having trouble finding anyone with this exact problem), I have to think it's a conceptual error on my part instead.**  But I can't seem to get my mind around how to change the recipe to work for both shared=True and shared=False.

I feel like there must be something wrong with my recipe such that Conan isn't able to compute the right value for `${CONAN_TARGETS}` depending on the type of dependency (static vs shared) but I'm not entirely sure where the problem might lie.

It's late here but I can get my 'draft' recipe committed on my fork tomorrow and link to it here, if that helps.  For now, I'm mainly trying to sanity check that this issue isn't "expected" given Conan's current design (i.e. it MUST be a bug on my end in the package recipe, right?).

Edits:  to clarify the question/issue

**Comment by jgsogo** [comment]
Hi, @accwebs 

If you have a look at the Conan repository, there are many [issues about private requirements](https://github.com/conan-io/conan/issues?q=is%3Aissue+is%3Aopen+private+requirements). TL;DR; they are not recommended. 

Private requirements are not propagated, so they don't reach your test_package as you have experienced yourself. In Conan v1.x they are not recommended, and **you won't find any in this repository**. Conan v2 will have a new graph model with improved capabilities and private-like-requirements should work more as expected.

If you want to dig into details, I recommend you to read and write in the conan-io/conan repository, there you will get more details about the issue and about the upcoming changes. That repo is a good place to talk about Conan internals, here we try to focus more on recipes themselves... which is more than enough for the time we have 😄 .

**Comment by accwebs** [comment]
Hi @jgsogo !

> Private requirements are not propagated, so they don't reach your test_package as you have experienced yourself.  In Conan v1.x they are not recommended, and you won't find any in this repository

Aha!  So this *is* indeed a design limitation of private repositories.  I started to suspect this yesterday, hence my general question (rather than focusing on the recipe code).  No wonder I was having trouble finding examples of how to use private dependencies :-D 

Thanks for the confirmation.  I'll redesign my package to no longer use private=True for capstone and hopefully this will result in the world making some sense once more. :-)
