### ISSUE TITLE
[android_ndk_installer] android_ndk_installer: Invalid configuration: only libc++ standard library is supported

### ISSUE THREAD

**Issue by prsolucoes** [conan-io/conan-center-index#983]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **android_ndk_installer**
  * Operating System+version: **ubuntu 18**
  * Compiler+version: **gcc**
  * Conan version: **conan 1.22.2**
  * Python version: **Python 3.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
include(default)

[settings]
os=Android
os.api_level=21
compiler=clang
compiler.version=8
arch=armv7

[build_requires]
android_ndk_installer/r20@bincrafters/stable
```

### Steps to reproduce (Include if Applicable)

```
git clone https://github.com/ezored/ezored.git
cd ezored
python make.py target android_aar conan
python make.py target android_aar build
python make.py target android_aar package
```

### Logs (Include/Attach if Applicable)

Full log is here:
https://github.com/ezored/ezored/runs/471493458?check_suite_focus=true

<details><summary>Click to expand log</summary>

```
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
android_ndk_installer/r20@bincrafters/stable: Downloaded recipe revision 0
ERROR: android_ndk_installer/r20@bincrafters/stable: Invalid configuration: only libc++ standard library is supported
COMMAND: conan install /home/runner/work/ezored/ezored/files/targets/android_aar/conan/recipe/conanfile.py --profile ezored_android_aar_profile -s arch=armv7 -s os.api_level=16 -s build_type=Debug --build=missing --update
WORKING DIR: /home/runner/work/ezored/ezored/build/android_aar/Debug/armv7/conan
[ERROR] Command execution has failed
##[error]Process completed with exit code 10.
```

</details>

**Comment by ericLemanissier** [comment]
Please close this issue, and report this on https://github.com/bincrafters/community/issues/new/choose, and explain why this is a bug/why you cannot use libc++

**Comment by prsolucoes** [comment]
Hi,

I don't have problems with libc++. This problem start recently. I have libc++ into my cmakelists:

```
set(PROJECT_CMAKE_CXX_FLAGS "${PROJECT_CMAKE_CXX_FLAGS} -stdlib=libc++" CACHE INTERNAL "")
```

I never had problems with this, until now.

Thanks.

**Comment by ericLemanissier** [comment]
Once again, this is not the good repo for issues on bincrafters recipes.Please close this issue, and report this on https://github.com/bincrafters/community/issues/
 Regarding your problem, you need to set conan setting compiler.libcxx to libc++

**Comment by prsolucoes** [comment]
Ah ok. I think that all problems need be send here. Sorry, i will post there.

**Comment by prsolucoes** [comment]
But you solution works. Only to know. Thanks.
