### ISSUE TITLE
[package] cpython/3.10.0: build fails if SQLite3 is disabled

### ISSUE THREAD

**Issue by erikogenvik** [conan-io/conan-center-index#9890]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cpython/3.10.0**
 
### Steps to reproduce (Include if Applicable)
If you try to build "cpython" with SQLite3 disabled you'll get a build error from Conan, as it tries to access the "self.options['sqlite3']" structure which only exists if SQLite3 is enabled.

It's a simple fix, PR incoming.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: cpython/3.10.0: Error in build() method, line 427
	autotools = self._configure_autotools()
while calling '_configure_autotools', line 234
	"--enable-loadable-sqlite-extensions={}".format(yes_no(not self.options["sqlite3"].omit_load_extension)),
	ConanException: option 'omit_load_extension' doesn't exist
```

</details>

**Comment by uilianries** [comment]
Thank you for reporting and providing a quick fix!
