### ISSUE TITLE
[docs] Update older versions removal policy

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#9900]
From the discussion at https://github.com/conan-io/conan-center-index/pull/9784#discussion_r829101784

The topic has been discussed internally evaluating the pros and cons of keeping older versions in `conandata.yml` and `config.yml` commented out.

Pros:

> - Keeping old versions commented makes it clearer to understand how the Conan Center remote got populated. Having versions in the remote but not in git can lead to confusion (e.g. https://github.com/conan-io/conan-center-index/issues/9452) and I think that will increase with Conan Center growing and the number of versions we remove growing as well. Confusion aside, even if people are aware of that it's still quicker to understand the history of the Conan Center remote if it is commented. (We had a similar discussion about obsolete packages and I think the consensus there was to keep it in git as well to prevent things like accidentally re-use of package names and for transparency)

> - Sometimes there is the need to build older versions for whatever reason. Once we comment them, we don't test them anymore and they might start to fail at some points - that's true. However, since Conan can't build them without manual changes in the conandata.yml file or without using some tool for that, it should be clear enough that there isn't official community support for it.

Cons:

> - Versions which are commented are not tested anymore and could not work with the current conanfile.py

Although having versions commented out could be helpful for anyone wanting those versions for create their own pacakges, having them untested with the new changes arriving to the *conanfile.py* is something that would make that experience even more frustrating to the user.
Also, we always tend to promote users to use the latest version possible (that's why we also bump dependencies versions in the recipes).
Similar to the deprecation policy (I think we don't have it documented yet), the case here is different, as older versions won't be allowed (unless strictly required https://github.com/conan-io/conan-center-index/blob/master/docs/reviewing.md#supported-versions) and not having old versions commented out will discourage the opening of new PRs adding again the version.

So, from our side, the policy should be removing those vesions from `conandata.yml` and `config.yml` making sure that no current recipe in master branch (latest recipe revision) has that version as requirement.

The following sections in the documentation should be updated:
- https://github.com/conan-io/conan-center-index/blob/master/docs/reviewing.md#supported-versions
- https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-is-the-policy-for-adding-older-versions-of-a-package
- https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-is-the-policy-for-removing-older-versions-of-a-package

cc/ @Croydon @SpaceIm @SSE4 @jgsogo @uilianries

**Comment by jgsogo** [comment]
I agree that Git is our friend. You can always recover sources URLs getting the files (`conandata.yml`) from that reference in ConanCenter.

**Comment by SpaceIm** [comment]
I agree.
