### ISSUE TITLE
[package] ffmpeg/4.3.2: Linking error when linking static lib to shared lib

### ISSUE THREAD

**Issue by dssimonspoerri** [conan-io/conan-center-index#9903]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ffmpeg/4.3.2**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **clang 12.0.1**
  * Conan version: **conan 1.45.0**
  * Python version: **Python 3.9.11**

### Steps to reproduce (Include if Applicable)
Statically compile FFmpeg into a shared lib with fPIC activated using clang. This results in the attached linking errors. The linker flags described in https://ffmpeg.org/platform.html#Advanced-linking-configuration apparently are not only required for GCC, but for clang too to link successfully.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
/usr/bin/ld.lld: error: can't create dynamic relocation R_X86_64_PC32 against symbol: ff_h264_cabac_tables in readonly segment; recompile object files with -fPIC
```

</details>

**Comment by uilianries** [comment]
Could you share you entire output when installing the package, including the command? We would need to check the exactly package ID which has no fPIC. By default, all packages have fPIC, probably it uses an non-standard option to enable/disable fPIC.
