### ISSUE TITLE
[conan.io/center] Markdown failed `cppzmq/4.8.1@#010df8fa1c5ebbc615704e8c16693bac`

### ISSUE THREAD

**Issue by mschilling9** [conan-io/conan-center-index#9944]
When attempting to figure out how I _should_ be linking cppzmq into my C++ CMake project, I came across this UI bug on conan.io/center. 

It directed me to write this issue. 

Specs: 
Model: Macbook M1 Pro 14 in. 16 gig memory, 8 core 
Browser: Firefox 98.0.2 

This isn't a blocking issue; however, I guess I figured for posterity I would oblige to the directions after clicking the link.

**Comment by SSE4** [comment]
locally I get:
```
ERROR: cppzmq/4.8.1: 'settings.arch' value not defined
```

**Comment by jgsogo** [comment]
After some fixes, now the tab is available. Thanks for reporting
