### ISSUE TITLE
[conan.io/center] The "Use It" tab spends about 1 minute contemplating world peace before actually doing anything

### ISSUE THREAD

**Issue by Brynyard** [conan-io/conan-center-index#9951]
Make it contemplate less and work more please.

**Comment by jgsogo** [comment]
Hi, @Brynyard .

The tab shows the output of the markdown generator (`conan install <reference> -g markdown`). We started to generate these files for the packages that are being merged in the past days (at the time they are merged and uploaded to the center), but there are still many packages that don't have that file generated and the process is triggered when the tab is visited.

**The command `conan install -g markdown` does not simply generate a markdown file, it is a full Conan install**: it requires building the graph of dependencies and downloading and uncompressing all the binaries. It would be great to have something that doesn´t require so many operations, but that´s a request for the Conan client.

OTH, there are some packages that fail to generate this mardown. We run the process in a Linux container using one of the profiles and sometimes the configuration is not suitable for the underlying container. Probably this is what happens for the issues reported like https://github.com/conan-io/conan-center-index/issues/9942. In this case, we preferred to write some error than to try to generate it again and again (for every visitor).

At least, only the first person visiting the tab should suffer the _contemplation_, while next visitors should just get the content.

**Comment by jgsogo** [comment]
We have been fixing some issues that have been reported in the last few days about missing markdown files. At the moment the process has already run for ~650 reference names (of course some of them could be failures) and it is running for every PR that is merged. We will trigger the generation again for failing ones, although we probably won't look for them proactively, so better if they are reported.

So far, there is only one error we probably won't fix, it affects `llvm-core`. The process runs out of memory (it uses a virtual filesystem) while downloading all the packages. To target this issue, we think it is a better approach to improve how the markdown files are generated (https://github.com/conan-io/conan/issues/10965 and https://github.com/conan-io/conan/issues/10967)

In the following hours (this week) most of the reported errors should be fixed.

I'm closing this issue, everything should be more or less clear about this process... and hopefully no more (so long) contemplation 😄 

Thanks!
