### ISSUE TITLE
[package] gmp/6.1.2: Link order

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#997]
gmp recipe should explicitly enumerates gmp and gmpxx libs in cpp_info.libs since libgmpxx depends on libgmp (and maybe add a C++ test_package).

**Comment by uilianries** [comment]
Hi @SpaceIm could you give more details? The template for bug report was not filled. Please, give the profile at least.

**Comment by SpaceIm** [comment]
Because I'm not a user of GMP, but I've seen several issues related to undefined reference (not with conan), therefore I've checked dependencies between libgmpxx and libgmp, and libgmpxx depends on libgmp. Since this recipe doesn't specify linking order, a program relying on C++ API might fail to link gmp.
