### ISSUE TITLE
[question] meson/glib cross compilation

### ISSUE THREAD

**Issue by WilliamBehrens** [conan-io/conan-center-index#9984]
I'm working on a project that requires that glib be cross compiled to a 32bit arm platform, as far as I can tell though glib within conan doesn't support cross compiling because the meson generator doesn't support it yet. Is there and recommended temporary fixes until this gets added?

**Comment by SSE4** [comment]
it needs to migrate to new toolchain.
last time I've tried I ran into some conan client issues (e.g. https://github.com/conan-io/conan/issues/10683).

**Comment by WilliamBehrens** [comment]
What do you mean it needs to migrate to a new toolchain?

**Comment by SSE4** [comment]
> What do you mean it needs to migrate to a new toolchain?

in short, migrate from [old integration](https://docs.conan.io/en/latest/reference/build_helpers/meson.html) to [new integration](https://docs.conan.io/en/latest/reference/conanfile/tools/meson/mesontoolchain.html). the old one is very limited, and didn't support cross-building at all. but the new one is not mature and stable enough, and there are still some obstacles.
