### ISSUE TITLE
[clipper] clipper/4.8.8: source download url returns 404 not found

### ISSUE THREAD

**Issue by SergeyKrivohatskiy** [conan-io/conan-center-index#9991]
Please update download url in `recipes/clipper/all/conandata.yml` for version `4.8.8`

### Steps to reproduce
`conan install -b=clipper clipper/4.8.8@`

### Logs
```
ERROR: clipper/4.8.8: Error in source() method, line 50
        tools.get(**self.conan_data["sources"][self.version],
        NotFoundException: Not found: https://sourceforge.net/code-snapshots/svn/p/po/polyclipping/code/polyclipping-code-r585-tags-4.8.8.zip
```

**Comment by SergeyKrivohatskiy** [comment]
This also affects assimp package now from this commit added 1 hour ago https://github.com/conan-io/conan-center-index/commit/e4643f2c116c3d92951ec2adddde899e060bb189

**Comment by SpaceIm** [comment]
@intelligide I see that 4.8.8 is a snapshot from sourceforce. These links are not persistent, they must be generated on the fly. You can find a robust approach in `libnova` recipe:
https://github.com/conan-io/conan-center-index/blob/3a925a0dda5345b5a1d884d5df13535d9e524096/recipes/libnova/all/conandata.yml#L3-L6
https://github.com/conan-io/conan-center-index/blob/3a925a0dda5345b5a1d884d5df13535d9e524096/recipes/libnova/all/conanfile.py#L47-L66

**Comment by SpaceIm** [comment]
post url is wrong in https://github.com/conan-io/conan-center-index/pull/9992, I'll submit another PR.
